### ISSUE TITLE
关于IKEv2最近遇到的一些奇怪问题，几天的尝试总结

### ISSUE THREAD

**Issue by mappinglan** [hwdsl2/setup-ipsec-vpn#1000]
利用教程提供的脚本在GCP上搭建IKEv2服务器，客户端(包括Windows ,Android,Linux)均可以正常连接，但是大部分网页访问异常。期间也尝试了aliyun,azure，镜像选择ubuntu,debian，无一例外均存在这个问题。目前可以通过修改服务器的MTU值解决部分客户端的问题。服务器运行ifconfig ens4 mtu 1500后，Android，Windows11(实体机非虚拟机)问题解决，访问网页正常。但是这个方案对于windows(虚拟机)，Linux(无论实体机还是虚拟机）无济于事。对于在GCP上搭建的其它类型的VPN，比如Wireguard,OpenVPN,L2tp/ipsec，不存在问题，网络均可以正常访问。
//这是虚拟机Windows11客户端的连接创建过程
![5](https://user-images.githubusercontent.com/38003050/129850608-7fffd8e3-88cb-4702-94cd-91197828a0be.png)
//IKEv2连接后，一下网页比如"Bing"是可以正常访问的，myip显示的也是IKEv2服务器IP。但是Google访问异常，并且奇怪的是明明地址栏是google.com但证书却显示的是facebook.com
![4](https://user-images.githubusercontent.com/38003050/129851041-12433091-18db-4f30-934f-5a157d2063cc.png)
![3](https://user-images.githubusercontent.com/38003050/129851077-63912dc0-e84e-44cc-a7d3-95831e6912b6.png)
![1](https://user-images.githubusercontent.com/38003050/129851084-8b483c2f-b329-4743-93b9-7affa96c1f4a.png)
//这是Windows11实体机，在服务器修改MTU值后（多次实验，改为1480或者1500都可以，但不改，无论如何也无法访问google)，访问网络正常。
![2021-08-18](https://user-images.githubusercontent.com/38003050/129852158-2539acc7-a493-40fa-b39e-a0b930647ce0.png)
![2021-08-18 (1)](https://user-images.githubusercontent.com/38003050/129852181-67dec4fe-6f5d-4501-90ae-974d0e609a70.png)
还有客户端Debian11,Ubuntu21.04和虚拟机上的Windows11表现一模一样，这里没有截图。
对于这个问题，我感觉非常的奇怪，明明都是一样Windows11,一个宿主机一个客户机，一个正常一个异常，但对于Wireguard,OpenVPN,L2tp/ipsec就无此问题。根据目前的现象可以判断应该是一些配置有问题，但我实在是找不到解决方案。

**Comment by keliew** [comment]
DNS?

**Comment by mappinglan** [comment]
> DNS?

Win11宿主机和客户机完全一样的配置，只是证书不一样，应该不是DNS的问题吧。

**Comment by keliew** [comment]
> > DNS?
> 
> Win11宿主机和客户机完全一样的配置，只是证书不一样，应该不是DNS的问题吧。

你是指什么证书？
VPN的DNS也改一下试试

**Comment by jamesguo71** [comment]
确实非常奇怪！我之前也在GCP上折腾过，当时用的应该是香港服务器，但是很多网页就是打不开（或者只是偶尔能打开）。当时正在上网络的课，还尝试了不同的方法，但是就是定位不到问题。期待你的update。

**Comment by mappinglan** [comment]
> 确实非常奇怪！我之前也在GCP上折腾过，当时用的应该是香港服务器，但是很多网页就是打不开（或者只是偶尔能打开）。当时正在上网络的课，还尝试了不同的方法，但是就是定位不到问题。期待你的update。

@keliew 修改Windows网卡DNS之后确实可以正常访问Google了，这确实是一个DNS问题。感谢帮助！

**Comment by mappinglan** [comment]
在Linux用NetworkManager GUI修改DNS之后，还是没法正常访问网页。你知道Linux系统下如何解决这个问题吗？ @keliew

**Comment by keliew** [comment]
> 在Linux用NetworkManager GUI修改DNS之后，还是没法正常访问网页。你知道Linux系统下如何解决这个问题吗？ @keliew

我的意思是 https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#use-alternative-dns-servers
改别的DNS试试

**Comment by mappinglan** [comment]
> > 在Linux用NetworkManager GUI修改DNS之后，还是没法正常访问网页。你知道Linux系统下如何解决这个问题吗？ @keliew
> 
> 我的意思是 https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#use-alternative-dns-servers
> 改别的DNS试试

改这个没用，试过了。windows虚拟机必须修改以太网卡DNS才可以，改IKEv2的DNS无效。现在Android,Windows的所有问题都已解决。只有Linux客户端还是无法正常访问网页，apt update,apt install可以正常安装程序，很明确这个问题与DNS有关。

**Comment by keliew** [comment]
其他网站都能正常访问？并且确定是通过VPN访问的？

**Comment by mappinglan** [comment]
> 其他网站都能正常访问？并且确定是通过VPN访问的？

确定所有网站都是经过VPN。环境，Linux宿主机Windows客户机。只是Linux作为客户端现在还不能正常访问网页。
![Screenshot from 2021-08-18 19-28-08](https://user-images.githubusercontent.com/38003050/129890363-853c9a56-10a1-4f82-99ab-17a462dc84bc.png)

**Comment by mappinglan** [comment]
linux下经过wireshark抓包分析，修改DNS为8.8.8.8后，DNS请求确实是到了8.8.8.8。但是同样的配方，在Windows下可以解决问题，Linux还是无济于事。看来还有其它未知的问题。

**Comment by mappinglan** [comment]
现在我不使用Strongswan而是使用libreswan作为客户端连接服务器，访问网页还是异常。
![Screenshot from 2021-08-19 12-36-05](https://user-images.githubusercontent.com/38003050/130008577-7851337e-312a-468f-91f1-4d4393c60c8b.png)

**Comment by mappinglan** [comment]
知识贫乏导致问题解决笨手笨脚，在尝试了各种可能之后终于找到解决方案。就算博主提到的Android MTU/MSS 问题，
服务器运行
iptables -t mangle -A FORWARD -m policy --pol ipsec --dir in \
  -p tcp -m tcp --tcp-flags SYN,RST SYN -m tcpmss --mss 1361:1536 \
  -j TCPMSS --set-mss 1360
iptables -t mangle -A FORWARD -m policy --pol ipsec --dir out \
  -p tcp -m tcp --tcp-flags SYN,RST SYN -m tcpmss --mss 1361:1536 \
  -j TCPMSS --set-mss 1360

之前也尝试过运行这两条命令，可能其它地方设置有问题，没有成功。今天认真把所有步骤走了一遍，在服务器手动安装apt install libreswan,不是脚本安装，但配置是博主的配置，又尝试了这个Android MTU/MSS 问题，顺利解决问题。被这个看似是Android的问题迷惑了太久。
@hwdsl2
![Screenshot from 2021-08-22 12-37-26](https://user-images.githubusercontent.com/38003050/130342503-df854038-842f-4927-afbb-54f2ddbe11bd.png)

**Comment by hwdsl2** [comment]
@mappinglan 好的。谢谢你提供的详细信息。

**Comment by mappinglan** [comment]
当libreswan服务端使用域名时，linux系统下libreswan客户端连接是会提示
# ipsec auto --add mytunnel
addconn: ERROR: hostname.example.com failed DNSSEC validation!
这是一个DNSSEC问题，需要修改本地主机的DNS地址，比如8.8.8.8。
windows虚拟机也会遇到此问题，前面提到过。
这是ipsec client的配置
conn vpnclient
  left=%defaultroute
  leftcert=vpnclient
  leftid=%fromcert
  leftrsasigkey=%cert
  leftsubnet=0.0.0.0/0 
  leftmodecfgclient=yes
  right=wower.cool
  rightsubnet=0.0.0.0/0 
  rightid=@wower.cool
  rightrsasigkey=%cert
  narrowing=yes
  ikev2=insist
  rekey=yes
  fragmentation=yes
  mobike=yes
  auto=add

**Comment by Minephliss** [comment]
成功解决问题啦，感谢大佬

**Comment by itbj** [comment]
> 知识贫乏导致问题解决笨手笨脚
很多配置都是猜的。有時候也是開發人員的問題，相同的配置，不同的OS就有問題。VPN互通是需要相互協商很多參數，大家標準不統一。
