### ISSUE TITLE
Assign specific IP address for ikev2 clients

### ISSUE THREAD

**Issue by gspannu** [hwdsl2/setup-ipsec-vpn#1003]
**Checklist**

- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [x] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
Feature request to enable specific IP address assigned to specific clients (rather than automatic assignment from the pool). This feature exists for PPP/L2P clients but not for ikev2.

**Is your enhancement request related to a problem? Please describe.**
Although your documentation states that ikev2 clients cannot get assigned IP addresses, **I think it is possible**.

_Please see this [thread](https://github.com/libreswan/libreswan/issues/487) at Libreswan GitHub._

**2 methods are suggested in the above thread**
- using the certificate identification via CN or SAN
- and the other is base code change to accept a filename with ids vs IP address range. 
I have been unable to get those to work -  but I am no expert in this area..._hence looking for your help._

_It would be a great addition to the already brilliant ikev2 implementation that you have provided._

My essential use case is that I am running a VPN server along (with an ad-blocker and Unbound recursive DNS server) and wish to control these clients individually based on their assigned IP address.
Currently, the clients get a dynamically assigned IP; so there is no way to fine tune the Ad-Blocking and Unbound DNS capability according to the connected client.

**Additional context**
https://github.com/libreswan/libreswan/issues/487

**Comment by gspannu** [comment]
### I have managed to find a solution !!!

The client name itself can be used to distinguish between the various clients and assigned specific IP addresses.

The ikev2.conf file needs to look like this...
example:

```
conn c1
  also=ikev2-shared
  rightid=@clientname1
  rightaddresspool=10.10.10.101-10.10.10.101

conn c2
  also=ikev2-shared
  rightid=@clientname2
  rightaddresspool=10.10.10.102-10.10.10.102

conn c3
  also=ikev2-shared
  rightid=@clientname3
  rightaddresspool=10.10.10.103-10.10.10.103

conn ikev2-shared
 ... all usual entries here
 ....
 ....
 ....
```

Notice the line
rightid=@clientname1

The **@** before the **client name** is very important - that is what correctly identifies the connection.
So specify your clientnames with whatever names; and make sure that the rightid= starts with @ and then the client name.

Hopefully, this helps others....

@hwdsl2 
_May I request you to put this advise in the main Readme.md so anyone else trying to get specific IP addresses per client on ikev2 can use this method._ Thanks.

**Comment by gspannu** [comment]
@hwdsl2 
Closing the issue as found [resolution](https://github.com/hwdsl2/setup-ipsec-vpn/issues/1003#issuecomment-902611614) for assigning specific IP addresses for ikev2 connections.

**Comment by yygyqkhh** [comment]
> @hwdsl2[根据找到的解决方案](https://github.com/hwdsl2/setup-ipsec-vpn/issues/1003#issuecomment-902611614)解决问题，以便为 ikev2 连接分配特定 IP 地址。

Hello, can you post the certificate generation process?

**Comment by letoams** [comment]
We have a test script that creates a bunch of them, https://github.com/libreswan/libreswan/blob/main/testing/x509/dist_certs.py

Sent using a virtual keyboard on a phone
