### ISSUE TITLE
IKEv2 VPN Only

### ISSUE THREAD

**Issue by usmcfiredog** [hwdsl2/setup-ipsec-vpn#1004]
**Checklist**

- [x ] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [x ] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [x ] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x ] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x ] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x ] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
To setup and configure an IKEv2 VPN only. Do not want an IPSEC or the others just the IKEv2.

Also have you thought about switching to strongswan in order to allow MOBIKE on raspberry pi's?

**Is your enhancement request related to a problem? Please describe.**
no
**Additional context**
n/a

**Comment by taftatata** [comment]
<a href="https://www.google.com/url?q=https://bit.ly/36c2ELF">eps adalah</a>
<a href="https://plus.google.com/url?q=https://bit.ly/36c2ELF">cara menghitung eps</a>
<a href="https://maps.google.com/url?q=https://bit.ly/36c2ELF">eps saham</a>
<a href="https://images.google.co.jp/url?q=https://bit.ly/36c2ELF">eps saham adalah</a>
<a href="https://maps.google.co.jp/url?q=https://bit.ly/36c2ELF">pengertian eps</a>
<a href="https://www.google.co.jp/url?q=https://bit.ly/36c2ELF">eps dalam saham</a>
<a href="http://www.google.co.uk/url?q=https://bit.ly/36c2ELF">cara mencari eps di laporan keuangan</a>
<a href="https://images.google.co.uk/url?q=https://bit.ly/36c2ELF">cara menghitung eps saham</a>
<a href="https://maps.google.co.uk/url?q=https://bit.ly/36c2ELF">pengertian eps dalam saham</a>
<a href="https://images.google.fr/url?q=https://bit.ly/36c2ELF">cara menghitung eps pada laporan keuangan</a>
<a href="https://maps.google.fr/url?q=https://bit.ly/36c2ELF">rumus eps setelah merger</a>
<a href="https://www.google.fr/url?q=https://bit.ly/36c2ELF">rumus eps growth</a>
<a href="https://images.google.it/url?q=https://bit.ly/36c2ELF">rumus eps menurut para ahli</a>
<a href="https://maps.google.it/url?q=https://bit.ly/36c2ELF">rumus eps dan dps</a>
<a href="https://images.google.de/url?q=https://bit.ly/36c2ELF">rumus price earning ratio</a>
<a href="https://maps.google.de/url?q=https://bit.ly/36c2ELF">earning per share artinya</a>
<a href="https://www.google.de/url?q=https://bit.ly/36c2ELF">rumus eps setelah merger</a>
<a href="https://images.google.es/url?q=https://bit.ly/36c2ELF">rumus eps dan dps</a>
<a href="https://maps.google.es/url?q=https://bit.ly/36c2ELF">rumus eps growth</a>
<a href="https://www.google.es/url?q=https://bit.ly/36c2ELF">rumus eps menurut para ahli</a>
<a href="https://www.google.ca/url?q=https://bit.ly/36c2ELF">rumus price earning ratio</a>
<a href="https://images.google.nl/url?q=https://bit.ly/36c2ELF">earning per share artinya</a>
<a href="https://maps.google.nl/url?q=https://bit.ly/36c2ELF">cara menghitung laba per saham dasar dan dilusian</a>
<a href="https://www.google.nl/url?q=https://bit.ly/36c2ELF">cara menghitung rata rata tertimbang saham beredar</a>
<a href="https://images.google.pl/url?q=https://bit.ly/36c2ELF">rumus eps dalam laporan keuangan</a>
<a href="https://maps.google.pl/url?q=https://bit.ly/36c2ELF">rumus eps growth</a>
<a href="https://www.google.pl/url?q=https://bit.ly/36c2ELF">rumus eps menurut para ahli</a>
<a href="https://images.google.com.au/url?q=https://bit.ly/36c2ELF">rumus eps menurut kasmir</a>
<a href="https://maps.google.com.au/url?q=https://bit.ly/36c2ELF">rumus eps dan dps</a>
<a href="https://www.google.com.au/url?q=https://bit.ly/36c2ELF">rumus eps setelah merger</a>
<a href="https://images.google.com.br/url?q=https://bit.ly/36c2ELF">rumus eps per pbv</a>
<a href="https://maps.google.com.br/url?q=https://bit.ly/36c2ELF">rumus eps ttm</a>
<a href="https://www.google.com.br/url?q=https://bit.ly/36c2ELF">rumus eps manajemen keuangan</a>
<a href="https://images.google.co.in/url?q=https://bit.ly/36c2ELF">rumus epsilon di excel</a>
<a href="https://maps.google.co.in/url?q=https://bit.ly/36c2ELF">rumus epsilon</a>
<a href="https://www.google.co.in/url?q=https://bit.ly/36c2ELF">rumus diluted eps</a>
<a href="https://www.google.it/url?q=https://bit.ly/36c2ELF">rumus mencari eps</a>
<a href="https://images.google.ch/url?q=https://bit.ly/36c2ELF">rumus ebit dan eps</a>
<a href="https://maps.google.ch/url?q=https://bit.ly/36c2ELF">rumus perhitungan eps</a>
<a href="https://www.google.ch/url?q=https://bit.ly/36c2ELF">rumus estimasi eps</a>
<a href="https://images.google.cz/url?q=https://bit.ly/36c2ELF">rumus ebit eps</a>
<a href="https://maps.google.cz/url?q=https://bit.ly/36c2ELF">rumus roa dan eps</a>
<a href="https://www.google.cz/url?q=https://bit.ly/36c2ELF">rumus proyeksi eps</a>
<a href="https://images.google.be/url?q=https://bit.ly/36c2ELF">rumus rasio pertumbuhan eps</a>
<a href="https://maps.google.be/url?q=https://bit.ly/36c2ELF">rumus rasio eps</a>
<a href="https://www.google.be/url?q=https://bit.ly/36c2ELF">cara mencari jumlah saham beredar</a>
<a href="https://plusone.google.com/url?q=https://bit.ly/36c2ELF">cara menghitung saham biasa</a>
<a href="https://images.google.at/url?q=https://bit.ly/36c2ELF">cara menghitung jumlah saham beredar</a>
<a href="https://maps.google.at/url?q=https://bit.ly/36c2ELF">laba per lembar saham</a>
<a href="https://www.google.at/url?q=https://bit.ly/36c2ELF">laba perlembar saham</a>
<a href="https://ditu.google.cn/url?q=https://bit.ly/36c2ELF">contoh soal eps</a>
<a href="https://images.google.se/url?q=https://bit.ly/36c2ELF">contoh soal earning per share</a>
<a href="https://maps.google.se/url?q=https://bit.ly/36c2ELF">earning per share rumus</a>
<a href="https://www.google.se/url?q=https://bit.ly/36c2ELF">earning per share</a>
<a href="https://images.google.ru/url?q=https://bit.ly/36c2ELF">eps adalah</a>
<a href="https://maps.google.ru/url?q=https://bit.ly/36c2ELF">rumus laba per saham</a>
<a href="https://www.google.ru/url?q=https://bit.ly/36c2ELF">market price per share adalah</a>
<a href="https://images.google.ca/url?q=https://bit.ly/36c2ELF">cara mencari dividen</a>
<a href="https://maps.google.ca/url?q=https://bit.ly/36c2ELF">roa roe roi</a>
<a href="https://images.google.dk/url?q=https://bit.ly/36c2ELF">analisis roe</a>
<a href="https://maps.google.dk/url?q=https://bit.ly/36c2ELF">cara mencari eps di laporan keuangan</a>
<a href="https://www.google.dk/url?q=https://bit.ly/36c2ELF">kepanjangan eps</a>
<a href="https://images.google.com.tr/url?q=https://bit.ly/36c2ELF">price earnings ratio per</a>
<a href="https://maps.google.com.tr/url?q=https://bit.ly/36c2ELF">pengaruh eps terhadap harga saham</a>
<a href="https://www.google.com.tr/url?q=https://bit.ly/36c2ELF">cara mencari dividen di laporan keuangan</a>
<a href="https://images.google.hu/url?q=https://bit.ly/36c2ELF">cara menghitung price earning ratio</a>
<a href="https://maps.google.hu/url?q=https://bit.ly/36c2ELF">price earning ratio formula</a>
<a href="https://www.google.hu/url?q=https://bit.ly/36c2ELF">price earnings ratio formula</a>
<a href="https://images.google.com.mx/url?q=https://bit.ly/36c2ELF">roe saham</a>
<a href="https://maps.google.com.mx/url?q=https://bit.ly/36c2ELF">dividend payout ratio formula</a>
<a href="https://www.google.com.mx/url?q=https://bit.ly/36c2ELF">cara menghitung dividen saham</a>
<a href="https://images.google.com.hk/url?q=https://bit.ly/36c2ELF">dividen per share</a>
<a href="https://maps.google.com.hk/url?q=https://bit.ly/36c2ELF">rumus dps</a>
<a href="https://www.google.com.hk/url?q=https://bit.ly/36c2ELF">cara menghitung dividend payout ratio</a>
<a href="https://images.google.com.sg/url?q=https://bit.ly/36c2ELF">cara menghitung dividend yield</a>
<a href="https://maps.google.com.sg/url?q=https://bit.ly/36c2ELF">pengertian per</a>
<a href="https://www.google.com.sg/url?q=https://bit.ly/36c2ELF">rumus dividend per share</a>
<a href="https://images.google.pt/url?q=https://bit.ly/36c2ELF">laba per lembar saham</a>
<a href="https://maps.google.pt/url?q=https://bit.ly/36c2ELF">laba perlembar saham</a>
<a href="https://www.google.pt/url?q=https://bit.ly/36c2ELF">earning per share rumus</a>
<a href="https://images.google.co.nz/url?q=https://bit.ly/36c2ELF">per ratio</a>
<a href="https://maps.google.co.nz/url?q=https://bit.ly/36c2ELF">rumus kebijakan dividen</a>
<a href="https://www.google.co.nz/url?q=https://bit.ly/36c2ELF">price to earning ratio adalah</a>
<a href="https://images.google.com.ar/url?q=https://bit.ly/36c2ELF">roe formula</a>
<a href="https://maps.google.com.ar/url?q=https://bit.ly/36c2ELF">dividend payout ratio</a>
<a href="https://images.google.co.id/url?q=https://bit.ly/36c2ELF">price earnings ratio</a>
<a href="https://maps.google.co.id/url?q=https://bit.ly/36c2ELF">rumus eps</a>
<a href="https://www.google.co.id/url?q=https://bit.ly/36c2ELF">price to earning ratio</a>
<a href="https://images.google.no/url?q=https://bit.ly/36c2ELF">price earning ratio</a>
<a href="https://maps.google.no/url?q=https://bit.ly/36c2ELF">return on equity</a>
<a href="https://www.google.no/url?q=https://bit.ly/36c2ELF">earnings per share</a>
<a href="https://images.google.co.th/url?q=https://bit.ly/36c2ELF">eps adalah</a>
<a href="https://maps.google.co.th/url?q=https://bit.ly/36c2ELF">roe</a>
<a href="https://www.google.co.th/url?q=https://bit.ly/36c2ELF">rumus return on equity</a>
<a href="https://images.google.com.ua/url?q=https://bit.ly/36c2ELF">rumus roe</a>
<a href="https://maps.google.com.ua/url?q=https://bit.ly/36c2ELF">roe adalah</a>
<a href="https://www.google.com.ua/url?q=https://bit.ly/36c2ELF">return on equity adalah</a>
<a href="https://images.google.co.za/url?q=https://bit.ly/36c2ELF">equity adalah</a>
<a href="https://maps.google.co.za/url?q=https://bit.ly/36c2ELF">earning per share dalam laporan keuangan</a>
<a href="https://www.google.co.za/url?q=https://bit.ly/36c2ELF">teori earning per share
</a>

**Comment by letoams** [comment]
On Aug 19, 2021, at 20:00, usmcfiredog ***@***.***> wrote:
> 
> ﻿
> Describe the enhancement request
> 
> To setup and configure an IKEv2 VPN only. Do not want an IPSEC or the others just the IKEv2.
> 
You misunderstand. The IKEv2 protocol configures IPsec. You cannot use IKEv2 without IPsec. Unfortunately, some vendor GUI’s used bad names for this. But “IKEv2” and “IKEv2 IPsec” is the exact same thing.

> Also have you thought about switching to strongswan in order to allow MOBIKE on raspberry pi's?
> 
Libreswan supports mobike without problems with mobike=yes
If that does not work on raspberry Pi, the kernel is likely based on old Debian kernels without XFRM_MIGRATE enabled. Please ask the raspberry Pi community to fix their kernel.

**Comment by hwdsl2** [comment]
Thanks @letoams for clarifying!

@usmcfiredog Please refer to IKEv2 only VPN [1]. Regarding MOBIKE, the IKEv2 setup script tries to automatically detect whether MOBIKE is supported. In the case of Raspberry Pis (with Raspbian), you can run the following commands to check:
```
modprobe -q configs
zcat /proc/config.gz | grep "CONFIG_XFRM_MIGRATE=y"
```
If the output is empty, then your Raspberry Pi's OS kernel does not support MOBIKE. Otherwise, if the output is not empty, you may edit /etc/ipsec.d/ikev2.conf and replace `mobike=no` with `mobike=yes`, then restart the IPsec service.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#ikev2-only-vpn
