### ISSUE TITLE
Have connection to the server but it is no internet connect from that

### ISSUE THREAD

**Issue by st-small** [hwdsl2/setup-ipsec-vpn#1005]
Hello! Thank you very much for you script it is amazing and frees so much of the time for me. But I have very big trouble with internet traffic missing. It happens a few times per hour and I should to reconnect my VPN connection. It happens on my iOS and macOS devices. And I don't understand how I can check the bug.

I connected to my server and checked logs using `grep pluto /var/log/auth.log` command and found some interesting lines:

`pluto[12462]: "ikev2-cp"[1028] <my office IP address> #1516: ERROR: asynchronous network error report on ens3 (<my server IP address>:4500), complainant <my office IP address>: No route to host [errno 113, origin ICMP type 3 code 1 (not authenticated)]`

how I can improve my VPN server settings to be more happy?!

Thank you very much for any advices.

**Comment by hwdsl2** [comment]
@st-small Hello! Your logs indicate that there could be network issues between your VPN client and VPN server. You may want to try a different server or another server provider. You can also try connecting using IPsec/L2TP [1] and/or IPsec/XAuth ("Cisco IPsec") [2] mode.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md
