### ISSUE TITLE
Access local domain names machines (local IP address) while connected to ikev2 VPN

### ISSUE THREAD

**Issue by gspannu** [hwdsl2/setup-ipsec-vpn#1006]
**A question about usage, and not a bug actually**
How do I go about avoiding some traffic over the VPN?
Where do I set these parameters per client?

**Description**
I have setup a ikev2 only connection to my VPN server. All my traffic is reputed through the server. My DNS server is also running on the same server machine.  
Server is running with:
Debian 10, Unbound DNS server, IKEv2 VPN server : all clients connect to this server via VPN and get their DNS queries resolved.

---
### Requirement:
- I have a few local (inaccessible from the internet) machines that I need to access from my clients (while also connected to the VPN).
- Examples are some local machines like router.home, nest.home, machinename.local (these machines have 192.168.30.x and 10.21.x.x addresses)

### Questions
1. Where do I define these settings?
2. Can I define these per client?
---

**Server (please complete the following information)**
- OS: [Debian 10]
- Hosting provider: [Digital Ocean]

**Client(s) (please complete the following information)**
- Device: [iPhones, iPAD, MACs]
- OS: [iOS 14, iOS 15 beta, macOS Big Sur, macOS Monterey beta]
- VPN mode: [IKEv2 only]

**My sample ikev2.conf file**
Looks like this (_some addresses redacted_)

```
conn ikev2-shared
  left=%defaultroute
  leftcert=<server IP address>
  leftsendcert=always
  leftsubnet=0.0.0.0/0
  leftrsasigkey=%cert
  right=%any
  rightca=%same
  rightrsasigkey=%cert
  narrowing=yes
  dpddelay=30
  dpdtimeout=120
  dpdaction=clear
  auto=add
  ikev2=insist
  rekey=no
  pfs=no
  ike=aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1
  phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes128-sha2,aes256-sha2
  ikelifetime=24h
  salifetime=24h
  encapsulation=yes
  leftid=<server IP address>
  modecfgdns=<Another server IP address>
  mobike=yes

conn gspMBP
  rightid=@deblon3-gspMBP
  rightaddresspool=10.10.10.21-10.10.10.21
  also=ikev2-shared

conn gspiPhone
  rightid=@deblon3-gspiPhone
  rightaddresspool=10.10.10.22-10.10.10.22
  also=ikev2-shared
 
conn dgiPhone
 rightid=@deblon3-dgiPhone
 rightaddresspool=10.10.10.25-10.10.10.25
 also=ikev2-shared 

```

### Any help would be much appreciated

**Comment by hwdsl2** [comment]
@gspannu Hello! For your use case, the `ipsec.conf` option you need is `modecfgdomains`. Please refer to [1] for more details. This setting applies to all VPN clients of a specific `ipsec.conf` connection on the server, so it cannot be "defined per client".  However, in your configuration file above, you may be able to set a different `modecfgdomains` for each connection, for example,`gspMBP` and `gspiPhone`. You'll need to restart the IPsec service for the changes to take effect.

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server/issues/233
