### ISSUE TITLE
After update clients mikrotitk not connection

### ISSUE THREAD

**Issue by jchelp** [hwdsl2/setup-ipsec-vpn#1008]
I was using the previous version with the ubuntu 20.4 server and mikrotik clients authenticating only with ipsec key, but I was having constant drops, after I ran the vpnup.sh not even the vpn interface went up anymore, I saw that it has some certificates, can I give a help, how to solve this problem?

**Checklist**

- [ ] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [ ] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [ ] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [ ] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [ ] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ ] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**

**To Reproduce**

1. ...
2. ...

**Expected behavior**

**Logs**
[Check logs and VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status), and add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- OS: [e.g. Debian 10]
- Hosting provider (if applicable): [e.g. GCP, AWS]

**Client (please complete the following information)**
- Device: [e.g. iPhone 8]
- OS: [e.g. iOS 13.6]
- VPN mode: [IPsec/L2TP, IPsec/XAuth ("Cisco IPsec") or IKEv2]

**Additional context**

**Comment by hwdsl2** [comment]
@jchelp Hello! If 4.5 doesn't work for your use case, you may re-install the older 4.4 version on your VPN server:
```
wget https://git.io/vpnupgrade -O vpnup.sh
nano vpnup.sh
# Replace SWAN_VER=4.5 with SWAN_VER=4.4
# Then save the file and run:
sudo sh vpnup.sh
```
I am not familiar with Mikrotik as a VPN client, but #914 suggests IKEv2 [1] may work better (compared to IPsec/L2TP), which you can give a try. In addition, you can check VPN logs for errors [2].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status

**Comment by jchelp** [comment]
Thanks for the answer I managed to make it work again with L2PT in this new version but I would like to use IKEv2 to close the connection on the client side got ip but on the server did not go up any interface or routes on the clients if you have any tips I would appreciate it and congratulations for the project.
