### ISSUE TITLE
LibreSWAN 3.19 refuses Android's OAKLEY proposals. Commit ba0fbb3860 works fine

### ISSUE THREAD

**Issue by keijodputt** [hwdsl2/setup-ipsec-vpn#101]
Nerfs with latest commit (tree 85ac19fc70), on vanilla Ubuntu 14.04.5 LTS and 16.04.1 LTS when trying to negotiate L2TP/IPSec, IPSEC/xauth-psk from Android 5. 
Pasting auth.log output for IPSec/xauth-psk excerpt:

Jan 18 15:37:45 awi pluto[18237]: "xauth-psk"[8] xxx.xxx.xxx.xxx #8: responding to Main Mode from unknown peer xxx.xxx.xxx.xxx
Jan 18 15:37:45 awi pluto[18237]: "xauth-psk"[8] xxx.xxx.xxx.xxx #8: Oakley Transform [OAKLEY_AES_CBC (256), OAKLEY_SHA1, OAKLEY_GROUP_MODP1024] refused
Jan 18 15:37:45 awi pluto[18237]: "xauth-psk"[8] xxx.xxx.xxx.xxx #8: Oakley Transform [OAKLEY_AES_CBC (256), OAKLEY_MD5, OAKLEY_GROUP_MODP1024] refused
Jan 18 15:37:45 awi pluto[18237]: "xauth-psk"[8] xxx.xxx.xxx.xxx #8: Oakley Transform [OAKLEY_AES_CBC (128), OAKLEY_SHA1, OAKLEY_GROUP_MODP1024] refused
Jan 18 15:37:45 awi pluto[18237]: "xauth-psk"[8] xxx.xxx.xxx.xxx #8: Oakley Transform [OAKLEY_AES_CBC (128), OAKLEY_MD5, OAKLEY_GROUP_MODP1024] refused
Jan 18 15:37:45 awi pluto[18237]: "xauth-psk"[8] xxx.xxx.xxx.xxx #8: Oakley Transform [OAKLEY_3DES_CBC (192), OAKLEY_SHA1, OAKLEY_GROUP_MODP1024] refused
Jan 18 15:37:45 awi pluto[18237]: "xauth-psk"[8] xxx.xxx.xxx.xxx #8: Oakley Transform [OAKLEY_3DES_CBC (192), OAKLEY_MD5, OAKLEY_GROUP_MODP1024] refused
Jan 18 15:37:45 awi pluto[18237]: "xauth-psk"[8] xxx.xxx.xxx.xxx #8: 1DES is not encryption
Jan 18 15:37:45 awi pluto[18237]: "xauth-psk"[8] xxx.xxx.xxx.xxx #8: OAKLEY_DES_CBC is not supported.  Attribute OAKLEY_ENCRYPTION_ALGORITHM
Jan 18 15:37:45 awi pluto[18237]: "xauth-psk"[8] xxx.xxx.xxx.xxx #8: 1DES is not encryption
Jan 18 15:37:45 awi pluto[18237]: "xauth-psk"[8] xxx.xxx.xxx.xxx #8: OAKLEY_DES_CBC is not supported.  Attribute OAKLEY_ENCRYPTION_ALGORITHM
Jan 18 15:37:45 awi pluto[18237]: "xauth-psk"[8] xxx.xxx.xxx.xxx #8: no acceptable Oakley Transform
Jan 18 15:37:45 awi pluto[18237]: "xauth-psk"[8] xxx.xxx.xxx.xxx #8: sending notification NO_PROPOSAL_CHOSEN to xxx.xxx.xxx.xxx:500
Jan 18 15:37:45 awi pluto[18237]: "xauth-psk"[8] xxx.xxx.xxx.xxx #8: deleting state (STATE_MAIN_R0)
Jan 18 15:37:45 awi pluto[18237]: "xauth-psk"[8] xxx.xxx.xxx.xxx: deleting connection "xauth-psk"[8] xxx.xxx.xxx.xxx instance with peer xxx.xxx.xxx.xxx {isakmp=#0/ipsec=#0}

Starting from scratch with tree ba0fbb3860 does the job decently on both vanilla Ubuntu 14.04.5 and 16.04.1 for L2TPD/IPSec and IPSec/xauth-psk in Android5 AND Windows7.

I'm going to stick to this branch in production but will test a little more and come back with any other findings.

Regards,
Keijo!

**Comment by hwdsl2** [comment]
@keijodputt Thanks for the report. The reason is that Libreswan 3.19 dropped MODP1024 from IKEv1 "ike=" default list [1], which caused this behavior. I will add a commit to update `ipsec.conf` configuration, so that MODP1024 is explicitly added back to the "ike=" list, in order to fix this compatibility issue. To simplify things, I will also remove `aes256-sha2_512` as it appears not needed.

[1] https://github.com/libreswan/libreswan/commit/42a8628fdff17914d29ee554ad5f545567ce9a1d

**Comment by keijodputt** [comment]
Tried your new commit on vanilla Ubuntu 16 LTS, here are the results:
L2TP/IPSec both work on Windows/Android
IPSec/xauth-psk on Android threw this:

Jan 18 22:56:34 awi pluto[20049]: "l2tp-psk"[2] xxx.xxx.xxx.xxx #21: responding to Main Mode from unknown peer xxx.xxx.xxx.xxx
Jan 18 22:56:34 awi pluto[20049]: "l2tp-psk"[2] xxx.xxx.xxx.xxx #21: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Jan 18 22:56:34 awi pluto[20049]: message repeated 5 times: [ "l2tp-psk"[2] xxx.xxx.xxx.xxx #21: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD]
Jan 18 22:56:34 awi pluto[20049]: "l2tp-psk"[2] xxx.xxx.xxx.xxx #21: 1DES is not encryption
Jan 18 22:56:34 awi pluto[20049]: "l2tp-psk"[2] xxx.xxx.xxx.xxx #21: OAKLEY_DES_CBC is not supported.  Attribute OAKLEY_ENCRYPTION_ALGORITHM
Jan 18 22:56:34 awi pluto[20049]: "l2tp-psk"[2] xxx.xxx.xxx.xxx #21: 1DES is not encryption
Jan 18 22:56:34 awi pluto[20049]: "l2tp-psk"[2] xxx.xxx.xxx.xxx #21: OAKLEY_DES_CBC is not supported.  Attribute OAKLEY_ENCRYPTION_ALGORITHM
Jan 18 22:56:34 awi pluto[20049]: "l2tp-psk"[2] xxx.xxx.xxx.xxx #21: no acceptable Oakley Transform
Jan 18 22:56:34 awi pluto[20049]: "l2tp-psk"[2] xxx.xxx.xxx.xxx #21: sending notification NO_PROPOSAL_CHOSEN to xxx.xxx.xxx.xxx:1
Jan 18 22:56:34 awi pluto[20049]: "l2tp-psk"[2] xxx.xxx.xxx.xxx #21: deleting state (STATE_MAIN_R0)

Bests.

**Comment by hwdsl2** [comment]
@keijodputt Thanks for the update. Your new issue is normal, it is most likely caused by (rapidly) switching from IPsec/L2TP to IPsec/XAuth. If you connected using IPsec/L2TP, after disconnecting you must do one of the following before connecting the same peer again using IPsec/XAuth, and vice versa. This is because Libreswan may "remember" which connection you used and refuse to switch.

1. Restart the IPsec service: `service ipsec restart`, or
2. Wait a few minutes
