### ISSUE TITLE
How To kick Active Connection

### ISSUE THREAD

**Issue by bakhtiyarsierad** [hwdsl2/setup-ipsec-vpn#1011]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**
Hi, how to kick a active connection? after i delete vpn user?

**Server (please complete the following information)**
- OS: Ubuntu 18.04
- Hosting provider : Hosterbyte.com

**Client (please complete the following information)**
- Device: Mikrotik
- OS: -
- VPN mode: [IPsec/L2TP]

Please advices 
Thank s

**Comment by hwdsl2** [comment]
@bakhtiyarsierad Hello! To "kick" an active connection, you may try:
```
ipsec whack --deletestate <state_id>
```
The `<state_id>` can be found by running `ipsec status`, then look at the number near the start of each line, after the `#` symbol. For example, `000 #4: "l2tp-psk"[1]...` has state ID 4. There may be multiple state IDs corresponding to each connection.

Note that the `--deletestate` is a developer command only and not intended for end users. Use at your own risk.

References:
https://bugzilla.redhat.com/show_bug.cgi?id=1631044
https://github.com/libreswan/libreswan/issues/111

**Comment by ptorrent** [comment]
Hello @hwdsl2  

I just tried 

```
ipsec whack --deletestate <state_id>
```

It's freezing ipsec, after that I'm not able to do "ipsec status", looks like ipsec is frozen in a nightmare...

**Comment by letoams** [comment]
On Thu, 4 Jan 2024, ptorrent wrote:

> I just tried
> 
> ipsec whack --deletestate <state_id>
> 
> It's freezing ipsec, after that I'm not able to do "ipsec status", looks like ipsec is frozen in a nightmare...

sounds like you were ssh'ed into the machine using that ipsec tunnel you just deleted?
