### ISSUE TITLE
Add OpenVZ support

### ISSUE THREAD

**Issue by rctphone** [hwdsl2/setup-ipsec-vpn#1012]
As far as I understand libreswan now supports OpenVZ, can you add to your scripts please?

https://libreswan.org/wiki/FAQ#Does_libreswan_work_with_OpenVZ_virtualization.3F

**Comment by hwdsl2** [comment]
@rctphone Hello! OpenVZ support is outside the scope of this project. Please use a non-OpenVZ VPS (e.g. KVM or Xen-based) or dedicated server for the IPsec VPN. Alternatively, you may try OpenVPN [1], which can run on an OpenVZ VPS.

[1] https://github.com/Nyr/openvpn-install
