### ISSUE TITLE
希望了解在ike2下，可否通过配置Ike2.conf或配置描述文件的方式，实现按url分流

### ISSUE THREAD

**Issue by ixuonion** [hwdsl2/setup-ipsec-vpn#1013]
您好！
目前看到文档中关于配置ipsec.conf/Ike2.conf实现VPN分流的办法，想咨询下，ipsec.conf是否支持按照配置多个URL的方式来进行分流？目前看到关于ipsec.conf是支持配置left=fqdn 的，想咨询下这种用例是否支持多个地址的配置，感谢。

**Comment by hwdsl2** [comment]
@ixuonion 你好！你说的用例我没有尝试过，建议你使用多个服务器实现。虽然可能可以在 `ikev2.conf` 添加多个具有不同 `left=...` 的小节，但是当客户端连接后，VPN 服务器的出站方向的公有 IP 地址将为同一个 IP，即使服务器有多个 IP。所以仍然不能实现分流。
