### ISSUE TITLE
Doesn't work on ubuntu

### ISSUE THREAD

**Issue by Itay1787** [hwdsl2/setup-ipsec-vpn#1014]
**Describe the issue**
The service does not start. After installation and let the script do its thing. The ipsec.service is not running, and failed to start.

```
ipsec.service - Internet Key Exchange (IKE) Protocol Daemon for IPsec
     Loaded: loaded (/lib/systemd/system/ipsec.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2021-09-10 13:12:43 UTC; 2s ago
       Docs: man:ipsec(8)
             man:pluto(8)
             man:ipsec.conf(5)
    Process: 19695 ExecStartPre=/usr/local/libexec/ipsec/addconn --config /etc/ipsec.conf --checkconfig (code=exited, status=0/SUCCESS)
    Process: 19696 ExecStartPre=/usr/local/libexec/ipsec/_stackmanager start (code=exited, status=0/SUCCESS)
    Process: 19845 ExecStartPre=/usr/local/sbin/ipsec --checknss (code=exited, status=0/SUCCESS)
    Process: 19846 ExecStartPre=/usr/local/sbin/ipsec --checknflog (code=exited, status=0/SUCCESS)
    Process: 19857 ExecStart=/usr/local/libexec/ipsec/pluto --leak-detective --config /etc/ipsec.conf --nofork (code=exited, status=5)
    Process: 19862 ExecStopPost=/sbin/ip xfrm policy flush (code=exited, status=0/SUCCESS)
    Process: 19863 ExecStopPost=/sbin/ip xfrm state flush (code=exited, status=0/SUCCESS)
    Process: 19864 ExecStopPost=/usr/local/sbin/ipsec --stopnflog (code=exited, status=0/SUCCESS)
   Main PID: 19857 (code=exited, status=5)
     Status: "Exited."
      Error: 5 (Input/output error)
        CPU: 213ms

Sep 10 13:12:43 systemd[1]: ipsec.service: Failed with result 'exit-code'.
Sep 10 13:12:43 systemd[1]: Failed to start Internet Key Exchange (IKE) Protocol Daemon for IPsec.
Sep 10 13:12:43 systemd[1]: ipsec.service: Scheduled restart job, restart counter is at 5.
Sep 10 13:12:43 systemd[1]: Stopped Internet Key Exchange (IKE) Protocol Daemon for IPsec.
Sep 10 13:12:43 systemd[1]: ipsec.service: Start request repeated too quickly.
Sep 10 13:12:43 systemd[1]: ipsec.service: Failed with result 'exit-code'.
Sep 10 13:12:43 systemd[1]: Failed to start Internet Key Exchange (IKE) Protocol Daemon for IPsec.
```
**To Reproduce**
Follow the instructions, wait for the installation to complete and see that the ipsec.service is inactive and fails to start

**Expected behavior**
That it will work

**Server (please complete the following information)**
- OS: Ubuntu 18.04 LTS And I tried in Ubuntu 20.04 LTS
- Hosting provider (if applicable): LXC Proxmox

**Comment by hwdsl2** [comment]
@Itay1787 Hello! LXC containers [1] are not supported by the VPN setup scripts. For Proxmox, please instead create a KVM-based virtual machine [2] and run the VPN setup scripts inside the VM.

[1] https://pve.proxmox.com/wiki/Linux_Container
[2] https://pve.proxmox.com/wiki/Qemu/KVM_Virtual_Machines

**Comment by hwdsl2** [comment]
@Itay1787 Looking into this further, it is actually possible to use the VPN setup scripts under LXC in Proxmox. However, you'll need to configure the LXC container according to these requirements:
1. The LXC container must NOT be an "unprivileged" container. Un-check that option when creating the container.
2. Append the following lines [1] to your LXC container's configuration. e.g. `/etc/pve/lxc/100.conf`, then restart the container:
   ```
   lxc.cgroup.devices.allow: c 108:0 rwm
   lxc.mount.entry: /dev/ppp dev/ppp none bind,create=file
   ```

[1] https://forum.proxmox.com/threads/this-system-lacks-ppp-kernel-support.59240/
