### ISSUE TITLE
aws 香港和东京连接不上，不确定是操作问题，还是什么问题

### ISSUE THREAD

**Issue by dyustc** [hwdsl2/setup-ipsec-vpn#1016]
**任务列表**<img width="1440" alt="截屏2021-09-17 01 36 36" src="https://user-images.githubusercontent.com/14801111/133659203-6b3238d0-7472-4044-a7fb-91d6251da217.png">
- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [x] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ ] 这个 bug 是关于 VPN 安装脚本，而不是 IPsec VPN 本身

**问题描述**
在aws 东京和香港 ubuntu 20. 04上配置了IKEv2, 按照步骤来了，用的默认步骤，但是客户端macOS连接不上 , 东京的l2tp/Ipsec方式也连接不上。。

**重现步骤**
重现该 bug 的步骤：

按照教程来的，先配置server，再配置client

**期待的正确结果**

**日志**
[检查日志及 VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)，并添加错误日志以帮助解释该问题（如果适用）。
<img width="1433" alt="截屏2021-09-17 01 37 03" src="https://user-images.githubusercontent.com/14801111/133659410-06e7ec6c-9829-4a8c-831b-49fefc65d894.png">
<img width="1440" alt="截屏2021-09-17 01 36 36" src="https://user-images.githubusercontent.com/14801111/133659426-1306a599-ab5a-4daf-b3ee-1b12a218c2ef.png">

**服务器信息（请填写以下信息）**
- 操作系统: Ubuntu 20.04.2 LTS
- 服务提供商（如果适用）: AWS

**客户端信息（请填写以下信息）**
- 设备: mbp 2020
- 操作系统: macOS 11.5.2
- VPN 模式: IPsec/L2TP,  IKEv2

**其它信息**
添加关于该 bug 的其它信息。

**Comment by hwdsl2** [comment]
@dyustc 你好！你提供的日志显示 VPN 连接请求没有到达服务器。对于 AWS (EC2)，你必须在服务器（EC2 instance）的 security group 中打开入站端口 UDP 500 和 UDP 4500。请参见：
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-security-groups.html

**Comment by dyustc** [comment]
@hwdsl2 谢谢大佬。可以请问aws 的 Windows server， 需要放开什么端口吗， 我现在的实例是windows server， 在创建的时候安全组里打开了UDP 500和4500, 好像还不奏效

**Comment by hwdsl2** [comment]
@dyustc 是用的 Windows 上的 Windows Subsystem for Linux (WSL) 吗？该用法没有测试过，目前不支持。你可能需要配置 Windows 防火墙打开相应的端口。

**Comment by dyustc** [comment]
@hwdsl2 我用的是windows server自带的routing and remote access, 防火墙里加了一个应该是routing and remote access自带的udp port, 1701,  不知道你之前联通过没？ 另外两个是手动添加的udp port 500 和 4500，不过目前好像l2tp不通。

<img width="1555" alt="截屏2021-09-19 01 14 19" src="https://user-images.githubusercontent.com/14801111/133897019-0cd17422-8ed4-4438-8670-cec5faad8e75.png">
<img width="1733" alt="截屏2021-09-19 01 13 39" src="https://user-images.githubusercontent.com/14801111/133897023-8599b758-10a3-4d7c-8c0c-a63be46e03f4.png">

或者，请问你有什么可以在windows server上配置vpn成功的方法吗

**Comment by hwdsl2** [comment]
@dyustc 这个配置我不太熟悉，你再自己尝试一下？UDP 端口 1701 不需要打开。打开 UDP 500 和 4500 即可。
