### ISSUE TITLE
OpenWrt connection help

### ISSUE THREAD

**Issue by st-small** [hwdsl2/setup-ipsec-vpn#1019]
That you very much for your project. I'm successfully use it for my own vpn server and happy. But I stuck when tried to connect my router to the server. I have Xiaomi 4A router with OpenWrt 19.07.8. I didn't find any truth and helpful guide to make connection. Can anybody help me?

**Comment by hwdsl2** [comment]
@st-small Hello! AFAIK, as a VPN client OpenWrt only supports L2TP without IPsec. This mode does not have any encryption, and is not supported by the VPN setup scripts. So unfortunately, you cannot use OpenWrt to connect as an IPsec/L2TP VPN client.

**Comment by st-small** [comment]
@hwdsl2 thank you for quick reply. But I found this article https://openwrt.org/docs/guide-user/services/vpn/strongswan/basics is it wrong?

**Comment by hwdsl2** [comment]
@st-small The article you linked above is not wrong - it does provide an example for configuring OpenWrt with IPsec. However, this requires significant configuration, and currently there is no example for how to modify it to use with this project.

**Comment by letoams** [comment]
Openwrt does support libreswan so perhaps you can do it manually by installing it but the scripting of this software likely wouldn’t work on it 

Sent using a virtual keyboard on a phone

**Comment by MichaelUray** [comment]
There is an example how to setup IPsec/L2TP VPN Clients with LibreSWAN, that should (did not test it) work with OpenWRT as well.
https://github.com/Ralph-Lee/VPN-IKEv2-LibreSWAN/blob/master/docs/clients.md#linux
