### ISSUE TITLE
IPSEC without certificate

### ISSUE THREAD

**Issue by nu07** [hwdsl2/setup-ipsec-vpn#1021]
can me use ipsec without PSK or ceritiface?

*only hostname,username,password

thank's :)

**Comment by hwdsl2** [comment]
@nu07 Hello! Using IPsec without PSK or certificate is not supported in this project.

**Comment by letoams** [comment]
On Sep 28, 2021, at 09:55, Wisnu Kristanto ***@***.***> wrote:
> 
> ﻿
> can me use ipsec without PSK or ceritiface?
> 
> *only hostname,username,password
> 
No. In IKEv1, user/passwd only works in addition to PSK/cert auth.
In IKEv2, it can be done with EAP but libreswan does not support EAP yet. The next version will have EAPTLS but they still uses certificates. What you are asking for is not a common deployment method.
 
Paul

**Comment by nu07** [comment]
ok, big thank's for information :)

**Comment by nu07** [comment]
what is the solution for ipsec which only uses username and password?

**Comment by letoams** [comment]
EAP mschapv2 

Sent using a virtual keyboard on a phone
