### ISSUE TITLE
Unable setup docker container on Raspberry PI 3 Model B

### ISSUE THREAD

**Issue by Pokemon5252525252** [hwdsl2/setup-ipsec-vpn#1024]
Unable to setup the docker container.

1. run the command "docker run --name birblosvpn --restart=always -v ikev2-vpn-data:/etc/ipsec.d -p 500:500/udp -p 4500:4500/udp -d --privileged hwdsl2/ipsec-vpn-server"

Expected to setup the container and provide me with the VPN details.

docker: Error response from daemon: driver failed programming external connectivity on endpoint birblosvpn (022022a5175168908ca1004038a3be59690dc8587bd39cea389cc433084c8b4e): Error starting userland proxy: listen udp4 0.0.0.0:4500: bind: address already in use.

OS: Raspbian GNU/Linux 10 (buster)

**Comment by hwdsl2** [comment]
@Pokemon5252525252 Hello! This is not a bug in the pre-built Docker image. The error means your Docker host probably already have another Docker container running, that listens on UDP port 4500.  You'll need to find which container is listening on this port (run `docker ps -a` to list containers), and stop the container.

Another possibility is that you already set up the VPN on the Docker host directly. In that case, you'll need to stop the IPsec and xl2tpd services on the Docker host, before creating the Docker container for the VPN.
