### ISSUE TITLE
AWS无法链接，确认测试500 4500 UDP端口已通

### ISSUE THREAD

**Issue by shore-liyang** [hwdsl2/setup-ipsec-vpn#1025]
**任务列表**

- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [x] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ ] 这个 bug 是关于 VPN 安装脚本，而不是 IPsec VPN 本身

**问题描述**
AWS EC2完成了部署后，通过IKEv2或者L2TP都无法链接，均为未响应。
测试UPD均通的
![image](https://user-images.githubusercontent.com/91306289/135427565-07b305f5-2fdb-40ad-8442-f355d83c5f6b.png)

**重现步骤**
重现该 bug 的步骤：
![image](https://user-images.githubusercontent.com/91306289/135427631-aede91ec-1a75-4dcb-ab94-0226a76811f7.png)

1. 正常链接L2TP或IKEv2

**期待的正确结果**
期望正确链接

**日志**
[检查日志及 VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)，并添加错误日志以帮助解释该问题（如果适用）。

**服务器信息（请填写以下信息）**
- 操作系统: AWS Linux
- 服务提供商（如果适用）: AWS

**客户端信息（请填写以下信息）**
- 设备: MBP
- 操作系统: OS X
- VPN 模式: [IPsec/L2TP, IPsec/XAuth ("Cisco IPsec") 或 IKEv2]

**其它信息**
添加关于该 bug 的其它信息。

**Comment by xyyxhcj** [comment]
same for me 
it works in last year

**Comment by hwdsl2** [comment]
@shore-liyang 你好！AWS已测试过。请再次尝试连接客户端，然后检查服务器上的日志是否有错误 [1]。如果没有新的日志出现，则说明客户端的连接请求没有到达服务器。可能是客户端和服务器之间的网络问题，或者在配置客户端时输入了错误的服务器地址。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E6%A3%80%E6%9F%A5%E6%97%A5%E5%BF%97%E5%8F%8A-vpn-%E7%8A%B6%E6%80%81

**Comment by shore-liyang** [comment]
d

> @shore-liyang 你好！AWS已测试过。请再次尝试连接客户端，然后检查服务器上的日志是否有错误 [1]。如果没有新的日志出现，则说明客户端的连接请求没有到达服务器。可能是客户端和服务器之间的网络问题，或者在配置客户端时输入了错误的服务器地址。
> 
> [1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E6%A3%80%E6%9F%A5%E6%97%A5%E5%BF%97%E5%8F%8A-vpn-%E7%8A%B6%E6%80%81

你可以看到上面我nmap所测试出来的联通性是正常的，500和4500的udp

**Comment by shore-liyang** [comment]
试了一下，最终可以了，原因是还需要开放1701的UDP端口，但是文档里没有写，也辛苦确认下是否有遗漏

> @shore-liyang 你好！AWS已测试过。请再次尝试连接客户端，然后检查服务器上的日志是否有错误 [1]。如果没有新的日志出现，则说明客户端的连接请求没有到达服务器。可能是客户端和服务器之间的网络问题，或者在配置客户端时输入了错误的服务器地址。
> 
> [1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E6%A3%80%E6%9F%A5%E6%97%A5%E5%BF%97%E5%8F%8A-vpn-%E7%8A%B6%E6%80%81

**Comment by hwdsl2** [comment]
@shore-liyang UDP 1701 端口是不需要打开的。应该不是这个原因。要 VPN 正常工作，只需打开 UDP 500 和 UDP 4500。

**Comment by xyyxhcj** [comment]
![image](https://user-images.githubusercontent.com/27875017/135565492-578f0205-1cb9-4e8a-b47e-a232008c2dbc.png)

**Comment by BISON7777** [comment]
跟你同样的问题

**Comment by KingingWang** [comment]
> 
我打开了UDP 500 和 UDP 4500，但是vpn可以连接但是无法上网，我关闭防火墙之后，可以正常上网

**Comment by kngharv** [comment]
> 

请问: 如何在EC2上面关防火墙?

**Comment by hwdsl2** [comment]
@kngharv 你好！关于 EC2 security group 请参见[这里](https://docs.aws.amazon.com/zh_cn/AWSEC2/latest/UserGuide/ec2-security-groups.html)。防火墙可以通过 security group 规则进行配置。

**Comment by kngharv** [comment]
> @kngharv 你好！关于 EC2 security group 请参见[这里](https://docs.aws.amazon.com/zh_cn/AWSEC2/latest/UserGuide/ec2-security-groups.html)。防火墙可以通过 security group 规则进行配置。

谢谢.  

弄了半天, 问题不在我这边.  (我起了一个最简单的web server来试探防火墙和我自己的security group).  我回头睡了一觉,第二天一切都正常运行了.

我在同一个环境用了您的脚本多年, 这几天遇到问题是因为我换成您的docker image.

很显然, 有时候security group作改变, 或者是改变了太频繁, AWS会等一阵才会真正的执行.
