### ISSUE TITLE
L2TP Works fine when connecting from  ios iphone, but not working when connected from a huawei router!

### ISSUE THREAD

**Issue by hgareeballa** [hwdsl2/setup-ipsec-vpn#1028]
**Checklist**

- [ ] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [ ] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [ ] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [ ] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [ ] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ ] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**

**To Reproduce**

1. ...
2. ...

**Expected behavior**

**Logs**
[Check logs and VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status), and add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- OS: [e.g. Debian 10]
- Hosting provider (if applicable): [e.g. GCP, AWS]

**Client (please complete the following information)**
- Device: [e.g. iPhone 8]
- OS: [e.g. iOS 13.6]
- VPN mode: [IPsec/L2TP, IPsec/XAuth ("Cisco IPsec") or IKEv2]

**Additional context**

**Comment by setdjod** [comment]
Same problem here

**Comment by hwdsl2** [comment]
@hgareeballa Hello! This VPN client is not currently supported. Try these settings [1] and see if it works for you. To troubleshoot further, retry the connection, then check the Libreswan and xl2tpd logs for errors [2].

[1] https://stackoverflow.com/q/56249580
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status

**Comment by ardel** [comment]
Worked for me using the instructions from here https://www.ispreview.co.uk/talk/threads/huawei-b535-232-4g-lte-router-issue.36112/page-23#post-247784

**Comment by aminmazi** [comment]
worked for me based on the above comment instructions:
after installing the vpn, Slightly modify the iptables rules in /etc/iptables.rules. Replace all the INPUT lines with these three:

```
-A INPUT -m conntrack --ctstate INVALID -j DROP
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p udp -m multiport --dports 500,1701,4500 -j ACCEPT
```
