### ISSUE TITLE
安全层在初始化与远程计算机的协商时遇到一个处理错误

### ISSUE THREAD

**Issue by dbaflight** [hwdsl2/setup-ipsec-vpn#103]
你好，

连接时 windows 报错 ：安全层在初始化与远程计算机的协商时遇到一个处理错误
ios： vpn 服务器并未响应
我之前已在多台相同环境 vps 上成功安装，唯独这台不行。
环境是 centos6 64
客户端配置也没有更改过。

谢谢

**Comment by hwdsl2** [comment]
@dbaflight 你好！请再次尝试连接 VPN，然后检查日志并提供输出，可隐去 IP：
···
grep pluto /var/log/secure
···

**Comment by dbaflight** [comment]
Jan 24 10:13:05 iZj6c682eje02ucc54goalZ pluto[8692]: "xauth-psk"[5] 182.150.165.116 #54: responding to Main Mode from unknown peer 182.150.165.116
Jan 24 10:13:05 iZj6c682eje02ucc54goalZ pluto[8692]: "xauth-psk"[5] 182.150.165.116 #54: transition from state STATE_MAIN_R0 to state STATE_MAIN_R1
Jan 24 10:13:05 iZj6c682eje02ucc54goalZ pluto[8692]: "xauth-psk"[5] 182.150.165.116 #54: STATE_MAIN_R1: sent MR1, expecting MI2
Jan 24 10:13:05 iZj6c682eje02ucc54goalZ pluto[8692]: "xauth-psk"[5] 182.150.165.116 #54: transition from state STATE_MAIN_R1 to state STATE_MAIN_R2
Jan 24 10:13:05 iZj6c682eje02ucc54goalZ pluto[8692]: "xauth-psk"[5] 182.150.165.116 #54: STATE_MAIN_R2: sent MR2, expecting MI3
Jan 24 10:13:06 iZj6c682eje02ucc54goalZ pluto[8692]: "xauth-psk"[5] 182.150.165.116 #54: ignoring informational payload IPSEC_INITIAL_CONTACT, msgid=00000000, length=28
Jan 24 10:13:06 iZj6c682eje02ucc54goalZ pluto[8692]: | ISAKMP Notification Payload
Jan 24 10:13:06 iZj6c682eje02ucc54goalZ pluto[8692]: |   00 00 00 1c  00 00 00 01  01 10 60 02
Jan 24 10:13:06 iZj6c682eje02ucc54goalZ pluto[8692]: "xauth-psk"[5] 182.150.165.116 #54: Main mode peer ID is ID_IPV4_ADDR: '100.0.0.107'
Jan 24 10:13:06 iZj6c682eje02ucc54goalZ pluto[8692]: "xauth-psk"[5] 182.150.165.116 #54: switched from "xauth-psk"[5] 182.150.165.116 to "xauth-psk"
Jan 24 10:13:06 iZj6c682eje02ucc54goalZ pluto[8692]: "xauth-psk"[6] 182.150.165.116 #54: transition from state STATE_MAIN_R2 to state STATE_MAIN_R3
Jan 24 10:13:06 iZj6c682eje02ucc54goalZ pluto[8692]: "xauth-psk"[6] 182.150.165.116 #54: new NAT mapping for #54, was 182.150.165.116:59738, now 182.150.165.116:59717
Jan 24 10:13:06 iZj6c682eje02ucc54goalZ pluto[8692]: "xauth-psk"[6] 182.150.165.116 #54: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=aes_256 integ=sha2_256 group=MODP2048}
Jan 24 10:13:06 iZj6c682eje02ucc54goalZ pluto[8692]: | event EVENT_v1_SEND_XAUTH #54 STATE_MAIN_R3
Jan 24 10:13:06 iZj6c682eje02ucc54goalZ pluto[8692]: "xauth-psk"[6] 182.150.165.116 #54: XAUTH: Sending Username/Password request (XAUTH_R0)
Jan 24 10:13:09 iZj6c682eje02ucc54goalZ pluto[8692]: "xauth-psk"[6] 182.150.165.116 #54: discarding duplicate packet; already STATE_XAUTH_R0
Jan 24 10:13:12 iZj6c682eje02ucc54goalZ pluto[8692]: "xauth-psk"[6] 182.150.165.116 #54: discarding duplicate packet; already STATE_XAUTH_R0
Jan 24 10:13:16 iZj6c682eje02ucc54goalZ pluto[8692]: "xauth-psk"[6] 182.150.165.116 #54: discarding duplicate packet; already STATE_XAUTH_R0
Jan 24 10:13:29 iZj6c682eje02ucc54goalZ pluto[8692]: "xauth-psk"[6] 182.150.165.116 #54: discarding duplicate packet; already STATE_XAUTH_R0
Jan 24 10:14:10 iZj6c682eje02ucc54goalZ pluto[8692]: "xauth-psk"[6] 182.150.165.116 #54: max number of retransmissions (8) reached STATE_XAUTH_R0
Jan 24 10:14:10 iZj6c682eje02ucc54goalZ pluto[8692]: "xauth-psk"[6] 182.150.165.116 #54: deleting state (STATE_XAUTH_R0)
Jan 24 10:14:10 iZj6c682eje02ucc54goalZ pluto[8692]: "xauth-psk"[6] 182.150.165.116: deleting connection "xauth-psk"[6] 182.150.165.116 instance with peer 182.150.165.116 {isakmp=#0/ipsec=#0}

**Comment by dbaflight** [comment]
另发现关闭 iptables 后可连接，但无法上网.

**Comment by hwdsl2** [comment]
@dbaflight 你的 VPN 客户端没有响应服务器发来的 用户名/密码请求。不清楚是什么问题。你试一下重启 IPsec 服务：
```
service ipsec restart
service xl2tpd restart
```

然后尝试一下使用另外这个 IPsec/L2TP 模式连接。另外请检查并确认你的 Windows 系统中 没有 添加 ProhibitIpSec 注册表键 [1]。

如果你关闭 IPTables，客户端可能会使用不加密的 L2TP 方式连接（无 IPsec），你的数据得不到保护。而且客户端连接后上网必须要 IPTables 转发规则才能工作。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/issues/46#issuecomment-238094752

**Comment by dbaflight** [comment]
已解决。
感谢

**Comment by iceking112** [comment]
@dbaflight 请问你这边是如何解决的？

**Comment by wxmdsh** [comment]
我现在也遇到一样的问题，上面的方法试过了。现在是
length of ISAKMP Identification Payload is larger than can fit
probable authentication failure (mismatch of preshared secrets?): malformed payload in packet
byte at offset 1 (29) of 'ISAKMP Identification Payload'.'?reserved?' is 0xad but should have been zero (ignored)

**Comment by hwdsl2** [comment]
@wxmdsh 你好！这个错误一般是因为你的 VPN 客户端配置中输入的 IPsec PSK 和服务器上的不一致。请检查并按照文档重新创建 VPN 配置。

**Comment by lengfengbyit** [comment]
@composercc 我也遇到了同样的问题， 你的这个问题解决了吗？我现在的可以连接一个window，但使用第二个windows连接时就会报这个错误。

**Comment by dbaflight** [comment]
你好，后来我再遇到这种情况，重启电脑或者网络重置就能解决。你可以试一下。



Ziyi Yang
The First Clinical College of Chongqing Medical University
2017220512@stu.cqmu.edu.cn


------------------ 原始邮件 ------------------
发件人: lengfengbyit <notifications@github.com>
发送时间: 2019年9月5日 13:47
收件人: hwdsl2/setup-ipsec-vpn <setup-ipsec-vpn@noreply.github.com>
抄送: Yang <2017220512@stu.cqmu.edu.cn>, Mention <mention@noreply.github.com>
主题: 回复：[hwdsl2/setup-ipsec-vpn] 安全层在初始化与远程计算机的协商时遇到一个处理错误 (#103)




@composercc 我也遇到了同样的问题， 你的这个问题解决了吗？我现在的可以连接一个window，但使用第二个windows连接时就会报这个错误。

**Comment by lengfengbyit** [comment]
谢谢， 我已经解决了，在ipsec.conf配置中增加overlapip=yes参数即可




------------------ 原始邮件 ------------------
发件人: "Yang"<notifications@github.com>;
发送时间: 2019年9月5日(星期四) 晚上8:46
收件人: "hwdsl2/setup-ipsec-vpn"<setup-ipsec-vpn@noreply.github.com>;
抄送: "冷锋"<1348207308@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [hwdsl2/setup-ipsec-vpn] 安全层在初始化与远程计算机的协商时遇到一个处理错误 (#103)



你好，后来我再遇到这种情况，重启电脑或者网络重置就能解决。你可以试一下。 
 
 
 
 Ziyi Yang 
 The First Clinical College of Chongqing Medical University 
 2017220512@stu.cqmu.edu.cn 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: lengfengbyit <notifications@github.com> 
 发送时间: 2019年9月5日 13:47 
 收件人: hwdsl2/setup-ipsec-vpn <setup-ipsec-vpn@noreply.github.com> 
 抄送: Yang <2017220512@stu.cqmu.edu.cn>, Mention <mention@noreply.github.com> 
 主题: 回复：[hwdsl2/setup-ipsec-vpn] 安全层在初始化与远程计算机的协商时遇到一个处理错误 (#103) 
 
 
 
 
 @composercc 我也遇到了同样的问题， 你的这个问题解决了吗？我现在的可以连接一个window，但使用第二个windows连接时就会报这个错误。

**Comment by tictak** [comment]
> 谢谢， 我已经解决了，在ipsec.conf配置中增加overlapip=yes参数即可
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Yang"<notifications@github.com>; 发送时间: 2019年9月5日(星期四) 晚上8:46 收件人: "hwdsl2/setup-ipsec-vpn"<setup-ipsec-vpn@noreply.github.com>; 抄送: "冷锋"<1348207308@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [hwdsl2/setup-ipsec-vpn] 安全层在初始化与远程计算机的协商时遇到一个处理错误 (#103) 你好，后来我再遇到这种情况，重启电脑或者网络重置就能解决。你可以试一下。 Ziyi Yang The First Clinical College of Chongqing Medical University 2017220512@stu.cqmu.edu.cn
> ------------------ 原始邮件 ------------------ 发件人: lengfengbyit <notifications@github.com> 发送时间: 2019年9月5日 13:47 收件人: hwdsl2/setup-ipsec-vpn <setup-ipsec-vpn@noreply.github.com> 抄送: Yang <2017220512@stu.cqmu.edu.cn>, Mention <mention@noreply.github.com> 主题: 回复：[hwdsl2/setup-ipsec-vpn] 安全层在初始化与远程计算机的协商时遇到一个处理错误 (#103) @composercc 我也遇到了同样的问题， 你的这个问题解决了吗？我现在的可以连接一个window，但使用第二个windows连接时就会报这个错误。 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

解决了我的问题，谢谢！
