### ISSUE TITLE
L2tp连接失败-win10

### ISSUE THREAD

**Issue by xyyxhcj** [hwdsl2/setup-ipsec-vpn#1030]
@xyyxhcj 你好！你提供的日志显示 Windows 10 客户端在连接后马上自动断开。这说明你在该客户端上没有应用必要的注册表更改 [1]，或者在应用注册表更改后没有重启计算机以生效。你再试一下。另外，你也可以使用 IKEv2 模式 [2]（推荐）。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#windows-%E9%94%99%E8%AF%AF-809
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md

_Originally posted by @hwdsl2 in https://github.com/hwdsl2/setup-ipsec-vpn/issues/1026#issuecomment-933121684_

**Comment by xyyxhcj** [comment]
之前是修改了注册表 但是没有重启 ,刚又操作了一遍 也重启了,但是还是同样连接不上
我用iphone也连接不上

**Comment by Scottpedia** [comment]
@xyyxhcj 

你好！我刚才试了一下你在 #1026 上提供的连接信息，结果是能连上。我的操作系统是 macOS 。

**Comment by xyyxhcj** [comment]
> @xyyxhcj
> 
> 你好！我刚才试了一下你在 #1026 上提供的连接信息，结果是能连上。我的操作系统是 macOS 。说明问题应该是出在了你的 Windows 客户端上。

我iphone也连不上啊

**Comment by hwdsl2** [comment]
@xyyxhcj 不要在这里粘贴你的服务器信息，请尽快重新安装该服务器或者重新运行脚本以生成新的VPN登录信息。

如果iPhone也连不上，问题应该在你的VPN服务器。建议你换一个服务器提供商试试看？也可能是连接被防火墙干扰了。
