### ISSUE TITLE
ikev2 mikrotik configuration

### ISSUE THREAD

**Issue by amirabasalinaghi** [hwdsl2/setup-ipsec-vpn#1034]
can you please add client setup (ikev2) for mikrotik routeros ?
i dont know how to setup ikev2 methode on mikrotik
i tried many configurations but failed
thanks

**Comment by kadkin-a** [comment]
RouterOS 7.9  model RB750Gr3
I m trying to setup IKEV2 on mikrotik.
But, I couldn't add .p12 certificate 
I add a file .p12 and nothing certificate appears in the list.

**Comment by hwdsl2** [comment]
@kadkin-a Please see:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#routeros
