### ISSUE TITLE
IKEv2: add each cert's revokation status to list of existing clients

### ISSUE THREAD

**Issue by mgmeier** [hwdsl2/setup-ipsec-vpn#1038]
**Checklist**

- [X] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [X] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [X] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [X] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [ ] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [ ] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
Currently, the `ikev2.sh` script command `--listclients` flat out lists all known clients, regardless of their certificate's revocation status. Would it be possible to make the call to `certutil` in function `list_existing_clients()` display the revocation status, or might it be feasible to use two calls to `certutil`, outputting clients with valid vs. revoked certificates?

**Is your enhancement request related to a problem? Please describe.**
There is no technical problem adressed. It is a mere improvement to administration needs and making `ikev2.sh` the single point of contact for those needs.

**Additional context**
does not apply

**Comment by letoams** [comment]
I am not sure that makes sense?

We always use our own certificate even if it has been revoked - we have no other option until admin reconfigures things.

We reject incoming certificates if at the time these were revoked. When using CRLs we will use these until we get a new CRL even if these are revoked. When using OCSP, we don’t really know anything until time of use when we issue the OCSP request which we don’t want to do just for listing our currently remembered certificates.

Paul

Sent using a virtual keyboard on a phone

**Comment by mgmeier** [comment]
Thank you for your quick answer. Tell me, with a specific question, where my issue might be unclear? To emphasize: this enhancement is not about VPN connectivity and behavior (which is working fine as expected), only about the `ikev2.sh` script output verbosity.

**Comment by hwdsl2** [comment]
@mgmeier Hello! Thanks for the enhancement request. Yes, this is a nice to have improvement to show certificate statuses when listing IKEv2 clients. I'll take a look when I have time. Pull requests are welcome!
