### ISSUE TITLE
web / desktop manager

### ISSUE THREAD

**Issue by AnonymousWebHacker** [hwdsl2/setup-ipsec-vpn#1039]
I see this repo very complete, and it works wonderfully. You just need to have a web or desktop administrator to manage the basic things like, users, speed limit, traffic quota, etc.

**Comment by hwdsl2** [comment]
@AnonymousWebHacker Thank you for your suggestions. The features you mentioned are outside the scope of this project.

**Comment by AnonymousWebHacker** [comment]
@hwdsl2  any way to limit the traffic of created users?
I want to create my user but not exceed the traffic of my vps, that is, limit it to consume only 100 GB for example

**Comment by hwdsl2** [comment]
@AnonymousWebHacker No, limiting traffic of VPN users is not supported.

**Comment by AnonymousWebHacker** [comment]
@hwdsl2 I am working on that, I think possible if it can be done with raw tables in iptables, then I share if it works :)
