### ISSUE TITLE
Can't connect to VPN server via IKEv2

### ISSUE THREAD

**Issue by Pokemon5252525252** [hwdsl2/setup-ipsec-vpn#1044]
**Describe the issue**
![image](https://user-images.githubusercontent.com/68750348/141308436-f5ed2bf0-4e4c-4ca9-ad1e-d894d3df4fb5.png)

**To Reproduce**

1. create a new IKEv2 client
2. export p12 cert to desktop
3. import cert via cmd using certutil
4. create vpn profile via PowerShell
5. connect

**Expected behavior**
Expected to connect to the VPN server

**Logs**
![image](https://user-images.githubusercontent.com/68750348/141308157-a3184bcb-9085-4cd8-aa86-3b56fe5de749.png)

**Server (please complete the following information)**
OS: Raspbian GNU/Linux 10 (buster)

**Client (please complete the following information)**
- Device: Windows Surface
- OS: Windows 10 v21H1  OS Build:19043.1320
- VPN mode: IKEv2

**Additional context**
![image](https://user-images.githubusercontent.com/68750348/141307497-2575a7b8-0844-45c4-ae7c-0aebe620e045.png)

**Comment by hwdsl2** [comment]
@Pokemon5252525252 Hello! Please check that you entered the correct VPN server address in the VPN client's configuration.

In the PowerShell commands [1], be sure to replace `'Your VPN Server IP (or DNS name)'` with the actual VPN server address. In addition, if you specified a DNS name (e.g. vpn.example.com) when setting up IKEv2, you must use the DNS name (not the IP address) for `'Your VPN Server IP (or DNS name)'` in the PowerShell commands. On the other hand, if you didn't specify a DNS name when setting up IKEv2, use the server's IP address.

Please read the above, then remove and re-create the VPN connection. Let us know if this works for you.

By the way, your logs only show xl2tpd but not Libreswan (IPsec). You may check logs using these instructions [2].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#configure-ikev2-vpn-clients
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status

**Comment by Pokemon5252525252** [comment]
I already replaced the IP when using PowerShell

![image](https://user-images.githubusercontent.com/68750348/141366946-95bab30a-6bcd-431a-8db3-bdb63f71e7a8.png)

Here is the logs:

![image](https://user-images.githubusercontent.com/68750348/141367413-bdbd1e31-8259-4c3a-bf3f-af394d04de6d.png)
![image](https://user-images.githubusercontent.com/68750348/141367435-ee3c556f-d096-4353-88de-f33c501ae3a1.png)
![image](https://user-images.githubusercontent.com/68750348/141367563-63a82496-47a8-4fe2-93fc-5e15ecff3691.png)
![image](https://user-images.githubusercontent.com/68750348/141367686-74766df2-19ef-4daa-9e4b-a1efd73bed2e.png)
![image](https://user-images.githubusercontent.com/68750348/141367772-577c74e3-4292-4cc9-90b2-c5f7d5bb5435.png)
![image](https://user-images.githubusercontent.com/68750348/141367825-a5de7086-5d02-4773-bd6a-15795dc1934e.png)

I have created a new certificate and imported it, but it still doesn't work:

![image](https://user-images.githubusercontent.com/68750348/141368599-d8ddd75d-c07e-43ff-9553-99338cf36159.png)

Error Revoking Client:

![image](https://user-images.githubusercontent.com/68750348/141368026-eb44d8fe-294c-479e-a2b0-ec9878bf3b51.png)

**Comment by hwdsl2** [comment]
@Pokemon5252525252 Can you post the output of: `grep -a pluto /var/log/auth.log`?

**Comment by hwdsl2** [comment]
@Pokemon5252525252 From your screenshot, it looks like you are using the VPN server's local IP `192.168.0.133` to connect. When setting up IKEv2, by default, the server's public IP (not local IP) is written to the server's IKEv2 certificate. It won't work if you specify the VPN server's local IP as "Server name or address".

Please instead enter your VPN server's public IP in the "Server name or address" field. If your computer shares the same public IP as your VPN server, you can find the public IP from [here](https://ipchicken.com).

In addition, you'll need to forward UDP ports 500 and 4500 on your router to your VPN server (Raspberry Pi) for the connection to the public IP to work.

Let us know if this works for you. As an alternative, if you must specify the VPN server's local IP when connecting, you can remove IKEv2 and set it up again using custom options, and enter the local IP `192.168.0.133` during setup.

The error you saw when revoking a client certificate is likely a different issue.

**Comment by Pokemon5252525252** [comment]
At the time I am writing this, I've reinstalled the vpn under the local ip and it now works. Thanks :D
