### ISSUE TITLE
Restore import password

### ISSUE THREAD

**Issue by Kitanit** [hwdsl2/setup-ipsec-vpn#1046]
I installed a VPN server a couple of days ago and did not copy the import password, is it possible to see it again?
*I need it to create the certificate from the screenshot below

![image](https://user-images.githubusercontent.com/65107731/141520474-7a292b95-6ddd-46d7-a1f6-5ce8dfe06543.png)

**Comment by Pokemon5252525252** [comment]
Yes you can, you will need the helper script in order for this to work.

If the helper scrip is in the directory, run ```sudo bash ikev2.sh```
Then select option 2 and type the client name you are trying to get the certificate and the private key to import the certificate.

**Comment by hwdsl2** [comment]
@Kitanit Hello! As @Pokemon5252525252 mentioned, you may run the IKEv2 helper script again (run `sudo ikev2.sh`) and select the option to export configuration for an existing client. The password for client config files will be displayed in the output after exporting.

**Comment by DangHuengZing** [comment]
I have ruan "sudo ikev2.sh" and select the export configuratgion, but no password displayed. As below:
## Creating client configuration...

================================================

IKEv2 VPN client "XXX" exported!

VPN server address: XXX
VPN client name: XXX

Client configuration is available at:
/root/XXX.p12 (for Windows & Linux)
/root/XXX.sswan (for Android)
/root/XXX.mobileconfig (for iOS & macOS)

Next steps: Configure IKEv2 VPN clients. See:
https://git.io/ikev2clients

================================================

can't find the "import password", any solutions?plz

**Comment by hwdsl2** [comment]
@DangHuengZing Hello! An import password is no longer required if it is not displayed in the output of `ikev2.sh`. Just press Enter when prompted for the password.
