### ISSUE TITLE
Digital Ocean not working?

### ISSUE THREAD

**Issue by dhnokia** [hwdsl2/setup-ipsec-vpn#1049]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**
I created a droplet on Digital Ocean (1 ram 1 cpu). I executed script. Seems everything fine and everything working, but it is not.

**Expected behavior**
i opened every port on digital ocean ui. Turned off ufw and fail2ban in case that matters, but
I can't even telnet that ports from localhost

root@ubuntu-s-1vcpu-1gb-ams3-01:/var/log# telnet 127.0.0.1 4500
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
root@ubuntu-s-1vcpu-1gb-ams3-01:/var/log# telnet 127.0.0.1 500
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused

i tried docker container it too doesnt work.

**Logs**
grep xl2tpd /var/log/syslog
Nov 15 16:11:01 ubuntu-s-1vcpu-1gb-ams3-01 xl2tpd[3161]: xl2tpd version xl2tpd-1.3.10 started on ubuntu-s-1vcpu-1gb-ams3-01 PID:3161
Nov 15 16:11:01 ubuntu-s-1vcpu-1gb-ams3-01 xl2tpd[3161]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
Nov 15 16:11:01 ubuntu-s-1vcpu-1gb-ams3-01 xl2tpd[3161]: Forked by Scott Balmos and David Stipp, (C) 2001
Nov 15 16:11:01 ubuntu-s-1vcpu-1gb-ams3-01 xl2tpd[3161]: Inherited by Jeff McAdams, (C) 2002
Nov 15 16:11:01 ubuntu-s-1vcpu-1gb-ams3-01 xl2tpd[3161]: Forked again by Xelerance (www.xelerance.com) (C) 2006-2016
Nov 15 16:11:01 ubuntu-s-1vcpu-1gb-ams3-01 xl2tpd[3161]: Listening on IP address 0.0.0.0, port 1701

 netstat -tulnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      675/systemd-resolve
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1021/sshd
tcp6       0      0 :::22                   :::*                    LISTEN      1021/sshd
udp        0      0 127.0.0.1:4500          0.0.0.0:*                           3021/pluto
udp        0      0 167.172.38.32:4500      0.0.0.0:*                           3021/pluto
udp        0      0 10.18.0.5:4500          0.0.0.0:*                           3021/pluto
udp        0      0 10.110.0.2:4500         0.0.0.0:*                           3021/pluto
udp        0      0 127.0.0.1:500           0.0.0.0:*                           3021/pluto
udp        0      0 167.172.38.32:500       0.0.0.0:*                           3021/pluto
udp        0      0 10.18.0.5:500           0.0.0.0:*                           3021/pluto
udp        0      0 10.110.0.2:500          0.0.0.0:*                           3021/pluto
udp        0      0 127.0.0.53:53           0.0.0.0:*                           675/systemd-resolve
udp        0      0 0.0.0.0:1701            0.0.0.0:*                           3161/xl2tpd
udp6       0      0 ::1:500                 :::*                                3021/pluto

Nov 15 16:06:24 ubuntu-s-1vcpu-1gb-ams3-01 pluto[3021]: "l2tp-psk": added IKEv1 connection
Nov 15 16:06:24 ubuntu-s-1vcpu-1gb-ams3-01 pluto[3021]: "xauth-psk": added IKEv1 connection
Nov 15 16:06:24 ubuntu-s-1vcpu-1gb-ams3-01 pluto[3021]: "ikev2-cp": loaded private key matching left certificate '167.172.38.32'
Nov 15 16:06:25 ubuntu-s-1vcpu-1gb-ams3-01 pluto[3021]: "ikev2-cp": added IKEv2 connection
Nov 15 16:06:25 ubuntu-s-1vcpu-1gb-ams3-01 pluto[3021]: listening for IKE messages
Nov 15 16:06:25 ubuntu-s-1vcpu-1gb-ams3-01 pluto[3021]: Kernel supports NIC esp-hw-offload
Nov 15 16:06:25 ubuntu-s-1vcpu-1gb-ams3-01 pluto[3021]: adding UDP interface eth1 10.110.0.2:500
Nov 15 16:06:25 ubuntu-s-1vcpu-1gb-ams3-01 pluto[3021]: adding UDP interface eth1 10.110.0.2:4500
Nov 15 16:06:25 ubuntu-s-1vcpu-1gb-ams3-01 pluto[3021]: adding UDP interface eth0 10.18.0.5:500
Nov 15 16:06:25 ubuntu-s-1vcpu-1gb-ams3-01 pluto[3021]: adding UDP interface eth0 10.18.0.5:4500
Nov 15 16:06:25 ubuntu-s-1vcpu-1gb-ams3-01 pluto[3021]: adding UDP interface eth0 167.172.38.32:500
Nov 15 16:06:25 ubuntu-s-1vcpu-1gb-ams3-01 pluto[3021]: adding UDP interface eth0 167.172.38.32:4500
Nov 15 16:06:25 ubuntu-s-1vcpu-1gb-ams3-01 pluto[3021]: adding UDP interface lo 127.0.0.1:500
Nov 15 16:06:25 ubuntu-s-1vcpu-1gb-ams3-01 pluto[3021]: adding UDP interface lo 127.0.0.1:4500
Nov 15 16:06:25 ubuntu-s-1vcpu-1gb-ams3-01 pluto[3021]: adding UDP interface lo [::1]:500
Nov 15 16:06:25 ubuntu-s-1vcpu-1gb-ams3-01 pluto[3021]: forgetting secrets
Nov 15 16:06:25 ubuntu-s-1vcpu-1gb-ams3-01 pluto[3021]: loading secrets from "/etc/ipsec.secrets"
Nov 15 16:16:19 ubuntu-s-1vcpu-1gb-ams3-01 pluto[3021]: forgetting secrets
Nov 15 16:16:19 ubuntu-s-1vcpu-1gb-ams3-01 pluto[3021]: loading secrets from "/etc/ipsec.secrets"

**Server (please complete the following information)**
- OS: Ubuntu 20.04, 18.04, Centos 8
- Hosting provider: digital ocean

**Client (please complete the following information)**
- OS: android 11 and windows 10
- VPN mode:  IPsec/L2TP

**Comment by hwdsl2** [comment]
@dhnokia Hello! Using the VPN setup scripts on Digital Ocean was tested and should work fine. Your logs indicate that the VPN server started successfully and is listening for connections. There is no need to turn off ufw or fail2ban, and you cannot use `telnet 127.0.0.1 500` to test connections.

Please configure VPN clients using these instructions [1]. IKEv2 mode is recommended over IPsec/L2TP mode.

[1] https://github.com/hwdsl2/setup-ipsec-vpn#next-steps
