### ISSUE TITLE
L2TP without PSK

### ISSUE THREAD

**Issue by casaoui86** [hwdsl2/setup-ipsec-vpn#1051]
Hello all, 

I setup the VPN on my RPI (outside my network) and worked well from my phone. 

But i need to connect my router (inside my network), and the router do not use PSK. only username and password

So how can i by pass PSK option please ? 

Thank you

**Comment by hwdsl2** [comment]
@casaoui86 Hello! L2TP without PSK (IPsec) is not supported. Traffic is not encrypted at all in this mode, which defeats the purpose of using a VPN.
