### ISSUE TITLE
Fail to connect on server (RPi) reboot

### ISSUE THREAD

**Issue by LoryB** [hwdsl2/setup-ipsec-vpn#1052]
**Describe the issue**
After first install everything works very well but after restart my iPhone can't connect to the IKEv2 VPN.
So I checked the log and got this (the rest is in the issue logs section):

Nov 16 20:54:06 LBE-Home pluto[1067]: netlink_acquire got message with length 116 < 232 bytes; ignore message

I've read on a [Libreswan discussion](https://www.mail-archive.com/swan@lists.libreswan.org/msg03236.html) that IPSec is trying to setup but RPi is still configuring the network card (due to all the other daemons installed) and it fails.
After=network-online.target is waiting but not enough so a guy suggested to add a ping loop like this: 
ExecStartPre=/bin/sh -c 'until ping -c1 1.1.1.1; do sleep 1; done;'
With this line on ipsec.service the problem is solved but is there a better way to solve the issue?

**To Reproduce**
1. Restart RPi
2. Try to connect (it doesn't connect)

**Expected behavior**
1. Restart RPi
2. Connected

**Logs**
Nov 16 20:54:06 LBE-Home pluto[1067]: loading secrets from "/etc/ipsec.secrets"
Nov 16 20:54:06 LBE-Home pluto[1067]: netlink_acquire got message with length 116 < 232 bytes; ignore message
Nov 16 20:54:06 LBE-Home pluto[1067]: netlink_acquire got message with length 116 < 232 bytes; ignore message
Nov 16 20:54:08 LBE-Home pluto[1067]: netlink_acquire got message with length 116 < 232 bytes; ignore message
Nov 16 20:54:12 LBE-Home pluto[1067]: netlink_acquire got message with length 60 < 232 bytes; ignore message
Nov 16 20:54:12 LBE-Home pluto[1067]: netlink_acquire got message with length 60 < 232 bytes; ignore message
Nov 16 20:54:12 LBE-Home pluto[1067]: netlink_acquire got message with length 60 < 232 bytes; ignore message
Nov 16 20:54:12 LBE-Home pluto[1067]: netlink_acquire got message with length 68 < 232 bytes; ignore message
Nov 16 20:54:12 LBE-Home pluto[1067]: netlink_acquire got message with length 68 < 232 bytes; ignore message
Nov 16 20:54:13 LBE-Home pluto[1067]: netlink_acquire got message with length 116 < 232 bytes; ignore message
Nov 16 20:54:15 LBE-Home pluto[1067]: netlink_acquire got message with length 116 < 232 bytes; ignore message

**Server**
- Device: Raspberry Pi 4 Model B+ 4GB RAM
- OS: "Raspbian GNU/Linux 10 (buster)"

**Client 1**
- Device: iPhone XR
- OS: iOS 15.0.2
- VPN mode: IKEv2

**Client 2**
- Device: Dell Precision 7730
- OS: Windows 10 Pro x64 21H1
- VPN mode: IKEv2

**Comment by hwdsl2** [comment]
@LoryB Hello! Can you try editing `/etc/rc.local` and replace `sleep 15` with e.g. `sleep 30`? This increases the delay at system boot before the IPsec service is restarted. Reboot your server after that, and check the logs again. Does this fix the issue?

**Comment by LoryB** [comment]
@hwdsl2 I've tried to change from 15 to 30 seconds on rc.local but I still have the same trouble on restart. At the moment the only solution that works is that line on the IPSec.service: ExecStartPre=/bin/sh -c 'until ping -c1 1.1.1.1; do sleep 1; done;'

**Comment by hwdsl2** [comment]
@LoryB I'm closing this since the current 15-second delay in `rc.local` should work for most cases to wait for the Raspberry Pi's network to be up. For your use case, please continue to use the `ExecStartPre` workaround you identified.
