### ISSUE TITLE
同一个局域网下的机器，只能连接一台

### ISSUE THREAD

**Issue by zkbutt** [hwdsl2/setup-ipsec-vpn#1055]
同一个局域网下的机器，只能连接一台，如何连接多台呢

**Comment by ericshunhawk** [comment]
https://github.com/hwdsl2/setup-ipsec-vpn/issues/937#issuecomment-782517518

**Comment by ericshunhawk** [comment]
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#%E6%97%A0%E6%B3%95%E5%90%8C%E6%97%B6%E8%BF%9E%E6%8E%A5%E5%A4%9A%E4%B8%AA-ikev2-%E5%AE%A2%E6%88%B7%E7%AB%AF

**Comment by zkbutt** [comment]
![图片](https://user-images.githubusercontent.com/18031838/143603267-c92220f6-24ef-4c2c-ad64-cfcbbf0547a7.png)
不行呀 查看了这个  cat /etc/ipsec.d/ikev2.conf  这个里  leftid=165.   中已经没有@了

**Comment by zkbutt** [comment]
> https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#%E6%97%A0%E6%B3%95%E5%90%8C%E6%97%B6%E8%BF%9E%E6%8E%A5%E5%A4%9A%E4%B8%AA-ikev2-%E5%AE%A2%E6%88%B7%E7%AB%AF

不行

**Comment by zkbutt** [comment]
> [#937 (comment)](https://github.com/hwdsl2/setup-ipsec-vpn/issues/937#issuecomment-782517518)

![图片](https://user-images.githubusercontent.com/18031838/143609153-0a601dc2-d047-405b-981c-f1b173eedd25.png)
用 IKEv2 在一个NAT 可以多台连接了 但是很多网页无法打开

**Comment by hwdsl2** [comment]
@zkbutt 你好！关于网页无法打开的问题，你可以尝试：清除客户端DNS缓存，重启客户端，以及在服务器上修复MTU/MSS问题 [1]。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#android-mtumss-issues
