### ISSUE TITLE
Cant connect

### ISSUE THREAD

**Issue by rama0dev** [hwdsl2/setup-ipsec-vpn#1056]
Help, i install in server, after close connection, now i can connect to server (i use ssh)

**Comment by hwdsl2** [comment]
@rama0dev Hello! The VPN setup scripts does NOT block SSH connections after running. Therefore, the issue you described is probably not related to the VPN setup scripts. You'll need to troubleshoot further yourself.

**Comment by rama0dev** [comment]
But after install vpn on server, i cant connect by ssh, sftp,ftp,and in web cant open website
