### ISSUE TITLE
更改 IPsec PSK 後無法使用

### ISSUE THREAD

**Issue by cj-neo** [hwdsl2/setup-ipsec-vpn#1057]
**问题描述**
安裝完後測試 OK 一切正常，但是修改 IPsec PSK 之後，使用 

sudo service ipsec restart
sudo service xl2tpd restart

重置服務之後就無法使用（client 端連不上了）

1.嘗試把 IPsec PSK 改回來也不行
2.嘗試重新安裝（用原本隨機的 KEY 帳號 密碼） 也不行
3.重新開機也不行

順便問一下，要如何才能完整移除整個服務，謝謝！！！！

**重现步骤**
重现该 bug 的步骤：

1. 更改 IPsec PSK 
2. 重置服務

**期待的正确结果**
要能正常 @@"

**日志**
我看日誌都沒顯示錯誤，有需要再給

**服务器信息（请填写以下信息）**
- 操作系统: UBUNTU 20.4 LST
- 服务提供商（如果适用）: ORACLE CLOUD  ARM CPU (AARCH64)

**客户端信息（请填写以下信息）**
- 设备: NOKIA 7 PLUS
- 操作系统: ANDROID 10
- VPN 模式: IPsec/L2TP

**其它信息**
是不是和 ARM 的 CPU 有關，我看下面還有一個說樹莓派開機之後不能用，樹莓派也是 ARM CPU 不知道是不是一個問題

**Comment by hwdsl2** [comment]
@cj-neo 你好！要移除 VPN，可以使用辅助脚本，请参见 [1]。你可以尝试移除 VPN 后重新安装。你所说的这个问题有些奇怪，在我的测试中没有遇到过。我觉得有可能是 IPsec 服务未能正常重启导致的。你可以检查一下 IPsec 服务状态 `sudo service ipsec status` 以及该服务的日志 `journalctl -u ipsec`。

关于 #1052 树莓派开机之后无法使用，应该和这个 Issue 无关。它主要是关于在树莓派开机时 IPsec 服务等待网络可用。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/uninstall-zh.md

**Comment by cj-neo** [comment]
實在很抱歉，我發現是我手機的問題，換一台手機就一切正常了 @@" 

感謝您的耐心回覆！！

**Comment by cj-neo** [comment]
也不是手機的問題，是因為兩台手機用同一個 PPPOE 撥接（硬撥接上網）造成衝突
