### ISSUE TITLE
请问下在服务器上如何查询有哪些IP 进行了VPN连接

### ISSUE THREAD

**Issue by zkbutt** [hwdsl2/setup-ipsec-vpn#1058]
请问下在服务器上如何查询有哪些IP 进行了VPN连接 ?
如果可以的话能不能查到每一个IP的流量 ?

**Comment by hwdsl2** [comment]
@zkbutt 你好！不支持该功能。但是你可以使用命令 `ipsec trafficstatus` 查看已连接的客户端的信息。

**Comment by keliew** [comment]
可以通过pppd获取信息
https://linux.die.net/man/8/pppd
