### ISSUE TITLE
Ipsec Server + wireguard client same server

### ISSUE THREAD

**Issue by AnonymousWebHacker** [hwdsl2/setup-ipsec-vpn#1059]
1 - Install the L2PT server using the script, and it installed perfect. I can connect to him

2 - I install wireguard, and use it as a client, to connect to another server. 

My idea is to forward the traffic from the L2PT to the wireguard. I found that https://github.com/hwdsl2/setup-ipsec-vpn/issues/990#issuecomment-883872931 , but i have a problem first

What's the matter?

If I start the wireguard client, I cannot connect to L2PT. I have to turn off the wireguard, to be able to connect. This is my wireguard configuration.
```
[Interface]
PrivateKey = <redacted>
Address = 10.66.66.6/32,fd42:42:42::6/128
DNS = 1.1.1.1,1.0.0.1

# Configuration allow ssh ip vps
PostUp = ip rule add table 200 from <ip-vps>
PostUp = ip route add table 200 default via <gw-vps>
PreDown = ip rule delete table 200 from <ip-vps>
PreDown = ip route delete table 200 default via  <gw-vps>

[Peer]
PublicKey = <redacted>
PresharedKey = <redacted>
Endpoint = ipserver-external:443
AllowedIPs = 0.0.0.0/0
```
eth0 = 144.100.1.1/21 gw 144.100.1.254
wg0 = 10.66.66.6/24 wg 10.66.66.6

**Comment by hwdsl2** [comment]
@AnonymousWebHacker Hello! This use case is not currently supported. If you start WireGuard on the server, it may no longer be able to accept incoming IPsec connections on UDP ports 500/4500. This is probably because all traffic on the VPN server would go through the WireGuard connection.

**Comment by AnonymousWebHacker** [comment]
Thanks for your answer.

Is this something that happens to me in my vps provider? something new in wireguard or what? Because, there are some articles on the internet of this use L2PT + Wireguard Client, example 
https://github.com/hwdsl2/setup-ipsec-vpn/issues/990

Anyway, I'm going to find out, if there are any rules that I can add in the wireguard configuration, that allow connections on 500/4500.

**Comment by AnonymousWebHacker** [comment]
@hwdsl2 In fact, I tried to install outline server through docker 
```
docker0 inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
etho      inet 10.0.0.1  netmask 255.255.255.0  broadcast 10.0.0.255
```
Outline, use an API-port to connect the Manager and a user-port to connect the client.

And I start wireguard with that configuration above, and I can connect perfectly to the outline server, using the IP of eth0
