### ISSUE TITLE
Port forward not working IKEV2

### ISSUE THREAD

**Issue by KarimMn** [hwdsl2/setup-ipsec-vpn#1061]
**Checklist**

- [ x ] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [ x ] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [ x ] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [ x ] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [ x ] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ x ] This bug is about the VPN setup scripts, and not IPsec VPN itself
 

**Describe the issue**
First many thanks to the author for creating a very simple tool for VPN setup.

I installed and run the script on my VPS, clients can connect to either L2TP/IPsec or IKEv2; port forwarding is only working on L2TP however it's impossible to access the client VPN with the Iptables rules in the documentation. 

As far as I understand, the IKEV2 isn't creating a new route or interface so how is it possible to to forward the port from server to client?

IKEv2 Script   Copyright (c) 2020-2021 Lin Song   7 Nov 2021

Checking for existing IKEv2 client(s)...

Client Name       Certificate Status
------------      -------------------
vpnclient         valid

------------------------------------------

Windows client IP is 192.168.43.10 / Server IP  0.0.0.0

**Comment by hwdsl2** [comment]
@KarimMn Hello! For port forwarding to VPN clients in IKEv2 mode, please see "Example 2" in the docs [1]. Does that resolve your issue?

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#port-forwarding-to-vpn-clients

**Comment by KarimMn** [comment]
> @KarimMn Hello! For port forwarding to VPN clients in IKEv2 mode, please see "Example 2" in the docs [1]. Does that resolve your issue?
> 
> [1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#port-forwarding-to-vpn-clients

I may have rushed but that tutorial didn't work initially, now that I tried this : 

`iptables -D FORWARD -j DROP
netif=$(route 2>/dev/null | grep -m 1 '^default' | grep -o '[^ ]*$')
iptables -I FORWARD 2 -i "$netif" -d 192.168.43.0/24 -p tcp  --dport 3389 -j ACCEPT
iptables -t nat -A PREROUTING -p tcp --dport 3389 -j DNAT --to 192.168.43.10
iptables -A FORWARD -j DROP`

It works. 

What I'm trying to accomplish is a bit different. I'm trying to forward every tcp/udp port to my router. I tried --dport 81:32400 but this didn't work and internet stopped working. 

What I'm trying to accomplish? I'm behind a CGNAT and most VPN providers won't allow port forwarding or dedicated IP all together. I need remote access to many devices in my location behind the routers so port forwarding on the router is done, I was trying to forward every incoming request to the router instead as fast solution to this issue. Not sure if it's doable.

Thank you.

**Comment by hwdsl2** [comment]
@KarimMn Glad to know that the TCP 3389 forwarding works. For your specific use case, which is to forward every tcp/udp port, unfortunately this method won't work, and is not recommended due to the security risk of exposing port(s) to the Internet. Perhaps you can look into alternative solutions for your use case.
