### ISSUE TITLE
android can access L2TP vpn seccuess,and can access internal ,but it can not access internet

### ISSUE THREAD

**Issue by olivinelee** [hwdsl2/setup-ipsec-vpn#1062]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**
mac ,IOS，Windows is well, but android can access L2TP vpn seccuess,and can access internal ,but it can not access internet

**To Reproduce**

1. Android access l2tp vpn scuess
2. test access the internal services,eg:print server,scuess
3. test access the internet,eg:www.baidu.com,and others, failed

**Expected behavior**

**Logs**
[Check logs and VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status), and add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- OS: [Centos 7.6]
- Hosting provider (if applicable): [local server]

**Client (please complete the following information)**
- Device: [xiaomi]
- OS: [android 11]
- VPN mode: [IPsec/L2TP]

**Comment by hwdsl2** [comment]
@olivinelee Hello! Android clients worked fine in my tests. This could be a DNS or MTU/MSS issue. Please try this fix [1]. Or you may switch to use different DNS server(s) [2]. You may also try IKEv2 mode [3] (recommended) or IPsec/XAuth mode [4].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#android-mtumss-issues
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#use-alternative-dns-servers
[3] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md
[4] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md

**Comment by olivinelee** [comment]
@hwdsl2 i have already fixed the mtumss accroading to the [1] ,and change dns ,it do not work。
after testing,dns can reslov the website, i think the android doesn't have correct route.   but  ios ,mac ,windows is ok..

**Comment by hwdsl2** [comment]
@olivinelee In that case please instead try IKEv2 mode (recommended) or IPsec/XAuth mode, as mentioned above.
