### ISSUE TITLE
IKEv2模式连接后，无法打开youtube（chrome匿名模式）

### ISSUE THREAD

**Issue by ossacomu** [hwdsl2/setup-ipsec-vpn#1065]
**任务列表**

- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [x] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] 这个 bug 是关于 VPN 安装脚本，而不是 IPsec VPN 本身

**问题描述**
使用Ikev2 模式客户端可以建立VPN连接，但是无法访问youtube。使用Ipsec psk+username/passwd 方式没问题

**重现步骤**
重现该 bug 的步骤：

1. ...wget https://git.io/vpnquickstart -O vpn.sh && sudo sh vpn.sh
2. ...根据“IKEv2 VPN 配置和使用指南” 配置windows10 Ikev2客户端。
3. connect VPN.
4. 在chrome匿名模式中，打开youtube. 无法打开。
5. 如果浏览器已经有youtube缓存，无论是否匿名模式，都可以打开。
6. 改用IPsec/L2TP模式可以打开。

**期待的正确结果**
VPN连接后，可以访问youtube。

**日志**
[检查日志及 VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)，并添加错误日志以帮助解释该问题（如果适用）。

**服务器信息（请填写以下信息）**
- 操作系统: Ubuntu 20.04.1 LTS
- 服务提供商（如果适用）: GCP, US-west-1

**客户端信息（请填写以下信息）**
- 设备: Laptop PC
- 操作系统: Windows10
- VPN 模式:  IKEv2

**其它信息**
添加关于该 bug 的其它信息。

**Comment by hwdsl2** [comment]
@ossacomu 你好！请尝试修改 Windows 网络连接的属性，并指定 DNS 服务器 `8.8.8.8` 和 `8.8.4.4`，然后重新连接 VPN，应该可以解决。根据这个较早的 Issue [1] 中的反馈，在某些情况下，在 Windows 下使用 IKEv2 模式时系统可能不能使用 VPN 服务器所指定的 DNS 服务器，需要手动在客户端的网络连接属性中配置。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/issues/1000#issuecomment-900988644

**Comment by yuanjie1853** [comment]
这个BUG我也遇到了。。 但这样设置，是否会影响断开VPN后的正常连接解析速度？
