### ISSUE TITLE
 sh ikev2setup.sh  --auto ikev2setup.sh: 678: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by xiaoxiyouran** [hwdsl2/setup-ipsec-vpn#1066]
here is error, when execute ike2 by readme.

`/home/ubuntu/setup-ipsec-vpn/extras >>> sh ikev2setup.sh  --auto
ikev2setup.sh: 678: Syntax error: "(" unexpected`

**Comment by hwdsl2** [comment]
@xiaoxiyouran Hello! Please use `bash` instead of `sh` to run the script.
