### ISSUE TITLE
Windows 10 Clients DNS leaks issue over IKEv2 connection

### ISSUE THREAD

**Issue by LightMoon** [hwdsl2/setup-ipsec-vpn#1067]
Hi,

Windows 10 clients are experiencing, DNS leaks over the IKEv2 connection.
Wondering if this is a known bug or a misconfiguration on my server-side?

https://pastebin.com/KFSSZEbN

**Comment by hwdsl2** [comment]
@LightMoon Hello! This is a known issue. Please see [1] for additional information and workarounds.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#windows-dns-leaks-and-ipv6
