### ISSUE TITLE
How to add access control?

### ISSUE THREAD

**Issue by bino7** [hwdsl2/setup-ipsec-vpn#107]

**Comment by hwdsl2** [comment]
@bino7 I don't understand your question. Please provide more details.

**Comment by bino7** [comment]
An account can only have a limited number of connections. and Multiple accounts setup.

**Comment by hwdsl2** [comment]
@bino7 Sorry, not planned. Actually I am not aware of any method to achieve this with Libreswan. Maybe you can try alternatives such as OpenVPN [1]? See [2] for some hints.

[1] https://github.com/Nyr/openvpn-install
[2] https://forums.openvpn.net/viewtopic.php?t=18164
