### ISSUE TITLE
Unable to Import .mobileconfig or .p12 on iOS/iPadOS

### ISSUE THREAD

**Issue by gforal** [hwdsl2/setup-ipsec-vpn#1073]
Greetings,

I have the VPN setup and working on Windows clients, however, when trying to import the .mobileconfig on my iPhone and iPad, I get an error saying "THE PASSWORD FOR THE CERTIFICATE [vpnuser] IS INCORRECT." Tried all combinations of the client config files password, PSK and YOUR_PASSWORD.

**Troubleshooting:**
- Uninstalled, reinstalled IPSEC and IKEv2, Created new VPN config files
- Successful import into certlm.msc using the password for .p12 files
- Successfully connected to the VPN on Windows clients
- Created new user

**Client Details:**
- iPhone 13 Pro Max with iOS 15.2
- iPad Pro 11 2nd Gen with iOS 15.2

**Server Details**
- Ubuntu 21.10 (5.13.0-22-generic)
- Date of IPSEC script install (1/2/2022)

**Comment by hwdsl2** [comment]
@gforal Hello! Thanks for reporting. I was able to reproduce this issue on a Ubuntu 21.10 system. A fix has been submitted, and you may download and run the latest version of the IKEv2 helper script like this:

```
wget https://git.io/ikev2setup -O /opt/src/ikev2.sh
sudo ikev2.sh
```

Re-export the IKEv2 client's configuration by selecting the appropriate option from the script's menu. Then import the generated new config file(s) to your VPN client(s).

Please note, Ubuntu 21.10 is NOT a supported OS [1] for the VPN setup scripts. Use e.g. Ubuntu 20.04 instead.

[1] https://github.com/hwdsl2/setup-ipsec-vpn#requirements

**Comment by gforal** [comment]
Works perfectly now. Thanks for the quick response!
