### ISSUE TITLE
Ubuntu client cannot use IKEv2 VPN DNS

### ISSUE THREAD

**Issue by ritmas** [hwdsl2/setup-ipsec-vpn#1077]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**
IKEv2 VPN server is up & running. It uses [Hashicorp Consul DNS](https://www.consul.io/docs/discovery/dns) servers defined as `modecfgdns`. Both OS X and Ubuntu clients can connect to VPN, access other servers by IP over private/local network, but only Ubuntu cannot pickup VPN DNS servers, it cannot resolve [Hashicorp Consul FQDN](https://www.consul.io/docs/discovery/dns#standard-lookup), e.g. `lan.my-service.service.gcp.consul`

**To Reproduce**

1. [Configure IKEv2 VPN client for Ubuntu](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#linux)
2. Connect to VPN
3. Run ping on Ubuntu client terminal
```bash
$ ping -c 1 lan.my-service.service.gcp.consul
ping: lan.my-service.service.gcp.consul: Name or service not known

$ ping -c 1 10.0.0.10
PING 10.0.0.10 (10.0.0.10) 56(84) bytes of data.
64 bytes from 10.0.0.10: icmp_seq=1 ttl=63 time=34.1 ms

--- 10.0.0.10 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 34.116/34.116/34.116/0.000 ms
```

**Expected behavior**
```bash
$ ping -c 1 lan.my-service.service.gcp.consul
PING lan.my-service.service.gcp.consul (10.0.0.10): 56 data bytes
64 bytes from 10.0.0.10: icmp_seq=0 ttl=63 time=33.854 ms

--- lan.my-service.service.gcp.consul ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 33.854/33.854/33.854/0.000 ms
```

**Server (please complete the following information)**
- OS: CentOS Linux release 7.9.2009 (Core)
- Hosting provider: GCP

**Client (please complete the following information)**
- Device: Asus ZenBook 13 UX325JA
- OS: Ubuntu 20.04.3 LTS (Focal Fossa)
- VPN mode: IKEv2

**Additional context**
> /etc/ipsec.d/ikev2.conf on server
```bash
conn ikev2-cp
  ...
  leftsubnet=10.0.0.0/8
  ...
  modecfgdns="10.0.0.1 10.0.0.2 10.0.0.3"
  modecfgdomains="consul"
  ...
  authby=rsa-sha1
```
> /etc/resolv.conf on Ubuntu client
```bash
nameserver 127.0.0.53
options edns0 trust-ad
search lan
```

**Comment by letoams** [comment]
Likely the Ubuntu uses a different dns reconfiguration tool than centos/fedora

There is a todo to add support for “resolvconf” library. What is your system using ?

Sent using a virtual keyboard on a phone

**Comment by letoams** [comment]
On Thu, 13 Jan 2022, Rimantas Ragainis wrote:

> I think it's default one - systemd-resolved

It's scheduled, hopefully for the next release:

https://github.com/libreswan/libreswan/issues/172

**Comment by hwdsl2** [comment]
Thanks @letoams for the responses. @ritmas Since this is a planned feature in Libreswan, let's track it in https://github.com/libreswan/libreswan/issues/172. I'll close this one.
