### ISSUE TITLE
选项2的方式安装，Mac连接提示：您已被通信设备断开连接。请尝试重新连接。如果仍然有问题，请验证您的设置。

### ISSUE THREAD

**Issue by xuanyuan219** [hwdsl2/setup-ipsec-vpn#1078]
以下为连接错误后的检查日志
Jan 14 01:32:57 yisu-** xl2tpd[612524]: xl2tpd[612524]: Connection established to 114.2*2.11*.242, 58164.  Local: 723, Remote: 7 (ref=0/0).  LNS session is 'default'
Jan 14 01:32:57 yisu-** xl2tpd[612524]: xl2tpd[612524]: Call established with 114.2*2.11*.242, PID: 738459, Local: 49666, Remote: 1738, Serial: 1
Jan 14 01:32:57 yisu-** xl2tpd[612524]: /usr/sbin/pppd: You need to create the /dev/ppp device node by
Jan 14 01:32:57 yisu-** xl2tpd[612524]: executing the following command as root:
Jan 14 01:32:57 yisu-** xl2tpd[612524]: #011mknod /dev/ppp c 108 0
Jan 14 01:32:57 yisu-** xl2tpd[612524]: xl2tpd[612524]: child_handler : pppd exited for call 1738 with code 4
Jan 14 01:32:57 yisu-** xl2tpd[612524]: xl2tpd[612524]: call_close: Call 49666 to 114.2*2.11*.242 disconnected
Jan 14 01:32:57 yisu-** xl2tpd[612524]: xl2tpd[612524]: result_code_avp: result code endianness fix for buggy Apple client. network=768, le=3
Jan 14 01:32:57 yisu-** xl2tpd[612524]: xl2tpd[612524]: control_finish: Connection closed to 114.2*2.11*.242, serial 1 ()
Jan 14 01:32:57 yisu-** xl2tpd[612524]: xl2tpd[612524]: result_code_avp: result code endianness fix for buggy Apple client. network=256, le=1
Jan 14 01:32:57 yisu-** xl2tpd[612524]: xl2tpd[612524]: control_finish: Connection closed to 114.2*2.11*.242, port 58164 (), Local: 723, Remote: 7

![image](https://user-images.githubusercontent.com/9054488/149381127-272a1a57-a25d-4326-a869-f68b86088874.png)

**Comment by xuanyuan219** [comment]
谁能告诉我一下如何调整解决？

**Comment by hwdsl2** [comment]
@xuanyuan219 你好！如果你的服务器运行 Debian 11 或 10，并使用 "cloud" 版本的 Linux 内核，可能会出现你的日志中显示的问题。原因是 `/dev/ppp` 相关的内核模块不可用，所以不能使用 IPsec/L2TP 模式。在该情况下，你可以使用 IKEv2 或者 IPsec/XAuth ("Cisco IPsec") 模式连接。详情参见 [1]。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#debian-1110-%E5%86%85%E6%A0%B8
