### ISSUE TITLE
RFC 3706 error

### ISSUE THREAD

**Issue by ighostx** [hwdsl2/setup-ipsec-vpn#108]
Hello. I am installed l2tp/ipsec through vpnsetup.sh (27 Jan git.) And it did not work.
Newly installed server, debian 8.2 at scaleway.com
Client win 10 x64 and android MM.

logs error:
Configured DPD (RFC 3706) support not enabled because remote peer did not advertise DPD support

Full log -> [pastebin](http://pastebin.com/U2JLcUUd)

I do not put configs, because I have not edited this. All automatically edited script in auto mode. thanks.

**Comment by hwdsl2** [comment]
@ighostx Hello! The RFC3706 message you mentioned is normal. For Scaleway servers please first change to the latest kernel, reboot your server and try again. The default kernel has broken IPsec support. See: https://github.com/hwdsl2/setup-ipsec-vpn/issues/102#issuecomment-274634889 

Please also apply the NAT registry fix for Windows 10, as mentioned in [1]. Reboot your Windows PC before retrying.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#windows-error-809

**Comment by ighostx** [comment]
kernel changed, applied nat fix for windows 10 and worked. only win 10, on android MM not work )
there are solutions for android? Thanks.

android connection log > [pastebin](http://pastebin.com/aULdaAku)

**Comment by hwdsl2** [comment]
@ighostx Please try the first fix in [1]. If still not working or cannot find that option, edit `/etc/ipsec.conf` and append ",3des-sha2" to the end of both "ike=" and "phase2alg=" lines. Restart IPsec with "service ipsec restart", then try connecting again.

Please let us know which solution worked for you.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#android-6-and-7

**Comment by ighostx** [comment]
`  ike=3des-sha1,3des-sha1;modp1024,aes-sha1,aes-sha1;modp1024,aes-sha2,aes-sha2;modp1024,3des-sha2;modp1024
 
 phase2alg=3des-sha1,aes-sha1,aes-sha2,3des-sha2`

work =)
