### ISSUE TITLE
ipad ios8 无法安装ivke2.

### ISSUE THREAD

**Issue by huixindebaicai** [hwdsl2/setup-ipsec-vpn#1080]
iphone手机ios14 按照步骤安装客户端没问题。能正常访问。换成ipad ios8一样的步骤。配置成功后。点击vpn 连不上服务器。是不是因为pad系统太老的原因导致无法连接呀？

**Comment by hwdsl2** [comment]
@huixindebaicai 你好！这个有可能是你的 iPad 的系统版本较低的原因。iOS 8 已不受支持。如果你想要进一步检查 VPN 日志中的错误，可以参见这里 [1]。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E6%A3%80%E6%9F%A5%E6%97%A5%E5%BF%97%E5%8F%8A-vpn-%E7%8A%B6%E6%80%81

**Comment by huixindebaicai** [comment]
> @huixindebaicai 你好！这个有可能是你的 iPad 的系统版本较低的原因。iOS 8 已不受支持。如果你想要进一步检查 VPN 日志中的错误，可以参见这里 [1]。
谢啦。我看看
