### ISSUE TITLE
How to implement Split-Tunneling by using domain?

### ISSUE THREAD

**Issue by CloudSung** [hwdsl2/setup-ipsec-vpn#1084]
Hi there, 
I can implement the split-tunneling after read that section in docs.
but what if we need to use the split-tunneling by domain, b'coz the destination website cannot provide the IP list and submask after CDN.
Is there any possible the use the function to implement in this case?

**Comment by hwdsl2** [comment]
@CloudSung Hello! Split tunneling using domain names is not supported. For your use case, you may want to look into alternative solutions.
