### ISSUE TITLE
need to be confirmed

### ISSUE THREAD

**Issue by wxq126597** [hwdsl2/setup-ipsec-vpn#1085]
**任务列表**

- [ ✔] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [ ✔] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [ ✔] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [ ✔] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [ ✔] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ ×] 这个 bug 是关于 VPN 安装脚本，而不是 IPsec VPN 本身

**问题描述**
手机ios15.2：The L2TP-VPN 服务器未响应
电脑win10：错误 789

19号前还用的好好的 重启服务试过，重装两次系统都不行 日志信息找不出问题在哪 翻过之前的issue  有个香港同学的贴里说是GFW干扰的关系 能不能帮忙确认下 谢谢 如果这种情况ikev2还能用么？

**日志**
手机链接时:
Jan 24 13:35:58 ONEVPS190605083555 pluto[8518]: "l2tp-psk"[1] 117.xxx.xxx.xxx #1: responding to Main Mode from unknown peer 117.xxx.xxx.xxx:41187
Jan 24 13:35:58 ONEVPS190605083555 pluto[8518]: "l2tp-psk"[1] 117.xxx.xxx.xxx #1: sent Main Mode R1
Jan 24 13:35:58 ONEVPS190605083555 pluto[8518]: "l2tp-psk"[1] 117.xxx.xxx.xxx #1: sent Main Mode R2
Jan 24 13:35:59 ONEVPS190605083555 pluto[8518]: "l2tp-psk"[1] 117.xxx.xxx.xxx #1: STATE_MAIN_R2: retransmission; will wait 0.5 seconds for response
Jan 24 13:35:59 ONEVPS190605083555 pluto[8518]: "l2tp-psk"[1] 117.xxx.xxx.xxx #1: ignoring informational payload IPSEC_INITIAL_CONTACT, msgid=00000000, length=28
Jan 24 13:35:59 ONEVPS190605083555 pluto[8518]: "l2tp-psk"[1] 117.xxx.xxx.xxx #1: Peer ID is ID_IPV4_ADDR: '10.0.0.200'
Jan 24 13:35:59 ONEVPS190605083555 pluto[8518]: "l2tp-psk"[1] 117.xxx.xxx.xxx #1: switched to "l2tp-psk"[2] 117.xxx.xxx.xxx
Jan 24 13:35:59 ONEVPS190605083555 pluto[8518]: "l2tp-psk"[1] 117.xxx.xxx.xxx: deleting connection instance with peer 117.xxx.xxx.xxx {isakmp=#0/ipsec=#0}
Jan 24 13:35:59 ONEVPS190605083555 pluto[8518]: "l2tp-psk"[2] 117.xxx.xxx.xxx #1: IKE SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA2_256 group=MODP2048}
Jan 24 13:36:02 ONEVPS190605083555 pluto[8518]: "l2tp-psk"[2] 117.xxx.xxx.xxx #1: retransmitting in response to duplicate packet; already STATE_MAIN_R3
Jan 24 13:36:06 ONEVPS190605083555 pluto[8518]: "l2tp-psk"[2] 117.xxx.xxx.xxx #1: retransmitting in response to duplicate packet; already STATE_MAIN_R3
Jan 24 13:36:09 ONEVPS190605083555 pluto[8518]: "l2tp-psk"[2] 117.xxx.xxx.xxx #1: discarding duplicate packet -- exhausted retransmission; already STATE_MAIN_R3
电脑链接时:
Jan 24 13:38:53 ONEVPS190605083555 pluto[8518]: "l2tp-psk"[3] 117.xxx.xxx.xxx #3: responding to Main Mode from unknown peer 117.xxx.xxx.xxx:41259
Jan 24 13:38:53 ONEVPS190605083555 pluto[8518]: "l2tp-psk"[3] 117.xxx.xxx.xxx #3: Oakley Transform [AES_CBC (256), HMAC_SHA1, DH20] refused
Jan 24 13:38:53 ONEVPS190605083555 pluto[8518]: "l2tp-psk"[3] 117.xxx.xxx.xxx #3: Oakley Transform [AES_CBC (128), HMAC_SHA1, DH19] refused
Jan 24 13:38:53 ONEVPS190605083555 pluto[8518]: "l2tp-psk"[3] 117.xxx.xxx.xxx #3: sent Main Mode R1
Jan 24 13:38:54 ONEVPS190605083555 pluto[8518]: "l2tp-psk"[3] 117.xxx.xxx.xxx #3: sent Main Mode R2
Jan 24 13:38:54 ONEVPS190605083555 pluto[8518]: "l2tp-psk"[3] 117.xxx.xxx.xxx #3: Peer ID is ID_IPV4_ADDR: '10.0.0.4'
Jan 24 13:38:54 ONEVPS190605083555 pluto[8518]: "l2tp-psk"[3] 117.xxx.xxx.xxx #3: IKE SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA1 group=MODP2048}
Jan 24 13:38:54 ONEVPS190605083555 pluto[8518]: "l2tp-psk"[3] 117.xxx.xxx.xxx #3: Configured DPD (RFC 3706) support not enabled because remote peer did not advertise DPD support
Jan 24 13:38:55 ONEVPS190605083555 pluto[8518]: "l2tp-psk"[3] 117.xxx.xxx.xxx #3: retransmitting in response to duplicate packet; already STATE_MAIN_R3
Jan 24 13:38:56 ONEVPS190605083555 pluto[8518]: "l2tp-psk"[3] 117.xxx.xxx.xxx #3: retransmitting in response to duplicate packet; already STATE_MAIN_R3
Jan 24 13:38:59 ONEVPS190605083555 pluto[8518]: "l2tp-psk"[3] 117.xxx.xxx.xxx #3: discarding duplicate packet -- exhausted retransmission; already STATE_MAIN_R3

**Comment by hwdsl2** [comment]
@wxq126597 你好！从你的日志来看，有可能是GFW干扰的问题。你可以尝试IKEv2，但有可能也会被干扰。你可以另外尝试其它的解决方案。
