### ISSUE TITLE
Problem iptable 

### ISSUE THREAD

**Issue by TheReiner** [hwdsl2/setup-ipsec-vpn#1088]
Hi,

I used the script for the installation, and the VPN works fine, I have internet over the tunnel

however, I cannot ping my server with its local ip or even access Samaba or SSH server. It's like, the IP 192.168.43.1 didn't exist. 

`ssh debian@192.168.43.1
ssh: connect to host 192.168.43.1 port 22: Operation timed out`

This is my iptable.rule

> *filter
> :INPUT ACCEPT [119:6158]
> :FORWARD ACCEPT [0:0]
> :OUTPUT ACCEPT [35389:44240517]
> :f2b-sshd - [0:0]
> [547:42345] -A INPUT -p tcp -m multiport --dports 22 -j f2b-sshd
> [0:0] -A INPUT -s 192.168.43.0/24 -d 192.168.43.1/32 -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
> [0:0] -A INPUT -s 192.168.43.0/24 -d 192.168.43.1/32 -p tcp -m state --state NEW -m tcp --dport 445 -j ACCEPT
> [0:0] -A INPUT -s 192.168.43.0/24 -d 192.168.43.1/32 -p tcp -m state --state NEW -m tcp --dport 139 -j ACCEPT
> [0:0] -A INPUT -s 192.168.43.0/24 -d 192.168.43.1/32 -p udp -m state --state NEW -m udp --dport 138 -j ACCEPT
> [0:0] -A INPUT -s 192.168.43.0/24 -d 192.168.43.1/32 -p udp -m state --state NEW -m udp --dport 137 -j ACCEPT
> [548:44563] -A INPUT -p tcp -m multiport --dports 22 -j f2b-sshd
> [0:0] -A INPUT -p udp -m udp --dport 1701 -m policy --dir in --pol none -j DROP
> [29:2047] -A INPUT -m conntrack --ctstate INVALID -j DROP
> [27248:4474305] -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
> [6:3032] -A INPUT -p udp -m multiport --dports 500,4500 -j ACCEPT
> [0:0] -A INPUT -p udp -m udp --dport 1701 -m policy --dir in --pol ipsec -j ACCEPT
> [0:0] -A INPUT -p udp -m udp --dport 1701 -j DROP
> [12:480] -A FORWARD -m conntrack --ctstate INVALID -j DROP
> [0:0] -A FORWARD -i ens3 -o ppp+ -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
> [0:0] -A FORWARD -i ppp+ -o ens3 -j ACCEPT
> [0:0] -A FORWARD -i ppp+ -o ppp+ -j ACCEPT
> [17916:41072352] -A FORWARD -d 192.168.43.0/24 -i ens3 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
> [26224:2694665] -A FORWARD -s 192.168.43.0/24 -o ens3 -j ACCEPT
> [0:0] -A FORWARD -s 192.168.43.0/24 -o ppp+ -j ACCEPT
> [0:0] -A FORWARD -j DROP
> [27:2032] -A f2b-sshd -s 112.85.42.2/32 -j REJECT --reject-with icmp-port-unreachable
> [1068:84876] -A f2b-sshd -j RETURN
> [0:0] -A f2b-sshd -j RETURN
> COMMIT
> *nat
> :PREROUTING ACCEPT [566:61172]
> :INPUT ACCEPT [122:8634]
> :OUTPUT ACCEPT [29:2248]
> :POSTROUTING ACCEPT [29:2248]
> [0:0] -A POSTROUTING -s 192.168.42.0/24 -o ens3 -j MASQUERADE
> [422:49798] -A POSTROUTING -s 192.168.43.0/24 -o ens3 -m policy --dir out --pol none -j MASQUERADE
> COMMIT

Thanks for Help me.

**Comment by hwdsl2** [comment]
@TheReiner Hello! For IKEv2 and IPsec/XAuth ("Cisco IPsec") modes, the VPN server does \*not\* have an internal IP within the `192.168.43.0/24` network. Therefore `192.168.43.1` cannot be used to reach the VPN server. For your use case, you may need to use IPsec/L2TP mode instead. Then you can reach the VPN server using its internal IP `192.168.42.1`. See [1] for more information.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#internal-vpn-ips-and-traffic

**Comment by letoams** [comment]
On Jan 27, 2022, at 19:33, Lin Song ***@***.***> wrote:
> 
> ﻿
> @TheReiner Hello! For IKEv2 and IPsec/XAuth ("Cisco IPsec") modes, the VPN server does *not* have an internal IP within the 192.168.43.0/24 network. Therefore 192.168.43.1 cannot be used to reach the VPN server.
> 

You can simply configure the .1 address on the loopback interface to accomplish this. Be sure to exclude NAT from 192.168.43.0/24 to 192.168.43.0/24

Paul

**Comment by TheReiner** [comment]
Very thanks for your fast answer :)

@hwdsl2  i can't use IPsec/L2TP mode  because i have cloud kernel and i have not /dev/ppp

@letoams i'm not sure what i'm doing...

/etc/network/interfaces 

```
auto lo
iface lo inet loopback
    address 192.168.43.1
    dns-nameservers 213.186.33.99

auto ens3
iface ens3 inet dhcp
    accept_ra 0
    mtu 1500
```

and iptable.rules, but it's already exclude ? not ?

```
*nat
:PREROUTING ACCEPT [566:61172]
:INPUT ACCEPT [122:8634]
:OUTPUT ACCEPT [29:2248]
:POSTROUTING ACCEPT [29:2248]
[0:0] -A POSTROUTING -s 192.168.42.0/24 -o ens3 -j MASQUERADE
[422:49798] -A POSTROUTING -s 192.168.43.0/24 -o ens3 -m policy --dir out --pol none -j MASQUERADE
COMMIT
```
