### ISSUE TITLE
Digital ocean An error occurred! Please refresh the page!

### ISSUE THREAD

**Issue by yadude87** [hwdsl2/setup-ipsec-vpn#1092]
Digital ocean deploy button give me a error 
![C1DAD799-E74E-4280-8A9A-40C5A92612D0](https://user-images.githubusercontent.com/95441223/151807685-901a2526-ae67-4b14-a875-58be429098d5.png)

**Comment by hwdsl2** [comment]
@yadude87 Thanks for reporting! Please open an issue in the relevant repository [1].

[1] https://github.com/carlfriess/DigitalOceanVPNSetup/issues
