### ISSUE TITLE
ASK: Specify users and interfaces ppp+

### ISSUE THREAD

**Issue by AnonymousWebHacker** [hwdsl2/setup-ipsec-vpn#1093]
Is there a way to specify that user1 is always ppp0 and user2 is always ppp1?
Or does this already do it automatically?

the idea of ​​that is that it would be possible to measure the traffic of each user, example with 
```
vnstat -i ppp0
vnstat -i ppp1
```
my VPS provider issues high rates of bills, due to traffic overloads, (it is the only one available in my country).
For this reason, I would need my user user1 to consume 100 GB and my familiar user2 100 GB

**Comment by hwdsl2** [comment]
@AnonymousWebHacker Hello! As far as I know, it is not possible to use a specific `ppp` interface for each user. However, there is a "l2tp monitor" script that may be helpful for your use case. See [1] for more information. The "l2tp monitor" script may or may not work - use it at your own risk.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/issues/166#issuecomment-313117920

**Comment by AnonymousWebHacker** [comment]
@hwdsl2 I was using your script for a few days, but right now it doesn't give me output
```
root@srv172139-206152:/opt/l2pt# python2.7 l2pt-monitor.py 
PPTPD Client Statistics 

Username              #      TX      RX         Remote IP          Local IP  Int     CTX     CRX  Duration/Last seen
```

**Comment by hwdsl2** [comment]
@AnonymousWebHacker Did you add the line "debug" and restart the xl2tpd service? Quote from [1]:

"Before using, you must add a line "debug" to your "/etc/ppp/options.xl2tpd", and run "service xl2tpd restart". Also, a known issue is that the "Remote IP" column does not work."

[1] https://github.com/hwdsl2/setup-ipsec-vpn/issues/166

**Comment by AnonymousWebHacker** [comment]
I had activated it, only that no data comes out because the script collects the data from ./var/log/syslog, giving a delayed reading of the consumed traffic, and not in real time

**Comment by AnonymousWebHacker** [comment]
We are trying to improve the script you have given us, but it collects system log data, the data is out of date.

Would there be any way in the ipsec-server to deliver this data in real time?

**Comment by hwdsl2** [comment]
@AnonymousWebHacker IPsec/L2TP mode uses xl2tpd and ppp, which logs the total TX and RX bytes if you have debug enabled. As far as I know, the IPsec server (Libreswan) cannot provide this data in real time with L2TP username.

For IKEv2 and IPsec/XAuth ("Cisco IPsec") modes, try the command "ipsec trafficstatus", which gives you a near real time stats. This command will not show L2TP username for IPsec/L2TP mode.

**Comment by AnonymousWebHacker** [comment]
Give me some idea.

My main idea was with your script, to be able to see the traffic of each user, (which is somewhat cumbersome, because it is backlogged traffic, and not quite right). I was thinking that if at least a relationship between `user` and interface `pppx` could be established, it could be read with `vnstat` in real time.

Whether it's L2PT, Cisco or IKEv2 there has to be another way that works for them
Any other idea?

**Comment by hwdsl2** [comment]
@AnonymousWebHacker To answer your questions:
1. It will \*not\* always be the ppp6. The ppp interface name assigned depends on the order of connection by VPN users, and could be different each time.
2. I am not sure about this. As I said earlier, the script may or may not work, and unfortunately I can't help you debug it.

**Comment by letoams** [comment]
ipsec trafficstatus is live data

So is ipsec whack —globalstatus 

You can get live interface statistics on the ppp interface with ifconfig or the ip command

Sent using a virtual keyboard on a phone

**Comment by AnonymousWebHacker** [comment]
so, both commands release statistics in real time?

Those statistics are reset to 0 every time there is a reconnect?

So you can make a script that stores the traffic that exists in real time, add it up and establish a relationship with the interface or user
