### ISSUE TITLE
在Windows上删除IKEv2连接并恢复

### ISSUE THREAD

**Issue by optimusleobear** [hwdsl2/setup-ipsec-vpn#1098]
你好！新年快乐🎉！

我在参考了Windows的IKEv2部署说明，和[IKEv2配置脚本](https://github.com/hwdsl2/vpn-extras/blob/main/scripts/ikev2_config_import.cmd)后，我判断在Windows设置中删除VPN连接之后，如需要恢复安装前的状态，还应该在mmc中删除Personal和根证书中的两个证书（部署VPN前都不存在），并在注册表中删除新加的键。请问这样的步骤正确吗？

**Comment by hwdsl2** [comment]
@optimusleobear 你好！新年快乐。你上面说的这些步骤是正确的。
