### ISSUE TITLE
Can´t access different Subnet 

### ISSUE THREAD

**Issue by Rixxter** [hwdsl2/setup-ipsec-vpn#1099]
Hi,
I have the VPN Server running on an VPS and 2 cleients:

client 1: laptop, win11 connecting via IKEv2 IP 192.168.43.10
client 2: Synology NAS connecting via L2TP/IPSEC ( IKEv2 not supported) IP 192.168.42.10

The synology is my backup Server, so my laptop needs access to it.
Ping from 192.168.43.10 to 192.168.42.1 is fine, bute ping to 192.168.42.10 is timed out.

How can I get access to my Synology?

**Comment by hwdsl2** [comment]
@Rixxter Hello! Traffic from the 192.168.43.0/24 internal VPN network to the 192.168.42.0/24 network is allowed by default [1]. Please check that:
1. Your Synology NAS firewall allows incoming "ping" packets from 192.168.43.0/24
2. Your Windows 11 firewall allows incoming "ping response" packets from 192.168.42.0/24.

You can confirm that the VPN server allows such traffic by running `iptables -I FORWARD 8 -j LOG`, then look at the output of `dmesg` after trying the "ping" you mentioned. There should be no related "dropped" packets in the output.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/2bb938416c2801c406828d021db178cf6becc462/vpnsetup_ubuntu.sh#L478
