### ISSUE TITLE
Can't connect VPN after server stop/reboot

### ISSUE THREAD

**Issue by mikhailbalin** [hwdsl2/setup-ipsec-vpn#11]
Hi,
I use EC2 as a VPN server and have configured it with this script smoothly, but I've noticed that after instance has been stopped I can no longer connect VPN. Are there any special commands that could make the settings permanent?

**Comment by hwdsl2** [comment]
Hello, the VPN scripts are designed to work across server reboots. To help troubleshoot the issue, can you run the following commands on the server and post the outputs?

```
ipsec verify
ps aux | grep l2tp
iptables -nvL INPUT
cat /etc/rc.local
```

**Comment by mikhailbalin** [comment]
Yes, I'm sorry. I think I've tried to connect to fast. I've made several tests and can not connect only once after reboot. This is the output right after the installation:

ubuntu@ip-172-31-54-154:~$ sudo ipsec verify
Verifying installed system and configuration files

Version check and ipsec on-path                   	[OK]
Libreswan 3.16 (netkey) on 3.13.0-74-generic
Checking for IPsec support in kernel              	[OK]
 NETKEY: Testing XFRM related proc values
         ICMP default/send_redirects              	[OK]
         ICMP default/accept_redirects            	[OK]
         XFRM larval drop                         	[OK]
Pluto ipsec.conf syntax                           	[OK]
Hardware random device                            	[N/A]
Two or more interfaces found, checking IP forwarding	[OK]
Checking rp_filter                                	[OK]
Checking that pluto is running                    	[OK]
 Pluto listening for IKE on udp 500               	[OK]
 Pluto listening for IKE/NAT-T on udp 4500        	[OK]
 Pluto ipsec.secret syntax                        	[OK]
Checking 'ip' command                             	[OK]
Checking 'iptables' command                       	[OK]
Checking 'prelink' command does not interfere with FIPSChecking for obsolete ipsec.conf options          	[OK]
Opportunistic Encryption                          	[DISABLED]

ubuntu@ip-172-31-54-154:~$ sudo ps aux | grep l2tp
root     15973  0.0  0.0   4436   592 pts/2    Ss+  01:46   0:00 /usr/sbin/xl2tpd
root     16480  0.0  0.1  32776  2008 ?        Ss   01:47   0:00 /usr/sbin/pppd passive nodetach 192.168.42.1:192.168.42.10 refuse-pap auth require-chap name l2tpd file /etc/ppp/options.xl2tpd /dev/pts/2
ubuntu   16515  0.0  0.0  10436   932 pts/0    S+   01:49   0:00 grep --color=auto l2tp

ubuntu@ip-172-31-54-154:~$ sudo iptables -nL INPUT
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
fail2ban-ssh  tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 22
DROP       all  --  0.0.0.0/0            0.0.0.0/0            ctstate INVALID
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
REJECT     all  --  0.0.0.0/0            127.0.0.0/8          reject-with icmp-port-unreachable
ICMPALL    icmp --  0.0.0.0/0            0.0.0.0/0            icmptype 255
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp spts:67:68 dpts:67:68
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:22
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 500,4500
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:1701 policy match dir in pol ipsec
DROP       udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:1701
DROP       all  --  0.0.0.0/0            0.0.0.0/0        

ubuntu@ip-172-31-54-154:~$ sudo cat /etc/rc.local
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.


# Added by hwdsl2 VPN script
/usr/sbin/service fail2ban restart || /bin/true
/usr/sbin/service ipsec start
/usr/sbin/service xl2tpd start
echo 1 > /proc/sys/net/ipv4/ip_forward
exit 0


But I think it should be all fine with it. Thank you for your work and help!
Regards,
Michael

**Comment by hwdsl2** [comment]
Glad to hear it is working! Yes it is a good idea to wait a few minutes after reboot. The command outputs you posted all look fine. And I've removed them from your comment for privacy.
