### ISSUE TITLE
你好，我按照#166操作了，使用的你的monitor脚本，配置了debug后重启，但是重连之后记录数据是空的，是与脚本目录放的位置有关系吗？

### ISSUE THREAD

**Issue by mooneee** [hwdsl2/setup-ipsec-vpn#1101]

**Comment by hwdsl2** [comment]
@mooneee 你好！对于 `l2tp-monitor.py` 脚本，你需要配置 debug 之后重启 xl2tpd 服务：`sudo service xl2tpd restart`。和脚本存放的位置应该无关。另外，该脚本仅适用于 IPsec/L2TP 模式，对 IPsec/XAuth ("Cisco IPsec") 和 IKEv2 模式无效。你可以另外使用 `ipsec trafficstatus` 获取当前的 VPN 流量信息。
