### ISSUE TITLE
ikev2 mobileconfig file

### ISSUE THREAD

**Issue by yadude87** [hwdsl2/setup-ipsec-vpn#1102]
can the same mobileconfig file be used on more then one device or each device need its own mobileconfig file

**Comment by letoams** [comment]
On Thu, 10 Feb 2022, yadude87 wrote:

> can the same mobileconfig file be used on more then one device or each device need its own mobileconfig file

You can use the same one, but I would recommend changing the
certificates embedded to be different to avoid conflicts.

Also, if you are using two different VPN profiles on the same
device, you obviously need to change all the GUIDs to another
random value.

**Comment by hwdsl2** [comment]
Thanks @letoams! @yadude87 You may use the same .mobileconfig file on multiple macOS/iOS devices, as long as they don't connect at the same time. On the other hand, if you need to connect multiple devices at a time to the VPN server, each device must use a unique .mobileconfig file. You may add more IKEv2 clients using the IKEv2 helper script.

**Comment by yadude87** [comment]
okay thank you
