### ISSUE TITLE
ERROR:  authorized with policy PSK+XAUTH

### ISSUE THREAD

**Issue by feelingfrance** [hwdsl2/setup-ipsec-vpn#1103]
一切安装顺利，aws ubuntu 18的系统。IOS 手机用ipsec, l2TP, 或者生成的mobileconfig 导入到手机后，连接都是提示无法成功VPN
用grep pluto /var/log/auth.log 查看日志，出现一条如下错误（只要点击启动VPN按钮就会出现）：
（不同的VPN模式登陆出现下面两种日志）
packet from *.*.*.*:43347: initial Main Mode message received but no connection has been authorized with policy PSK+XAUTH
或者
packet from *.*.*.*:43347: initial Main Mode message received but no connection has been authorized with policy PSK
两个UDP端口都打开了，测试应该没有被封

**Comment by hwdsl2** [comment]
@feelingfrance 你好！我使用 AWS Ubuntu 18.04 系统测试过了，无法重现此问题，可以正常连接。你的日志中的错误 `initial Main Mode message received but no connection has been authorized with policy` 一般是因为使用不同模式 (IPsec/L2TP, IPsec/XAuth ("Cisco IPsec", IKEv2) 连接在同一个 NAT（比如家用路由器）后面的多个 VPN 客户端导致的。对于在同一个 NAT 后面的多个 VPN 客户端，如果第一个客户端不正确断开连接，VPN 服务器可能会暂时记住连接模式，从而无法使用不同模式连接。要解决此问题，你可以尝试重启服务器上的 IPsec 服务：`sudo service ipsec restart`。

**Comment by feelingfrance** [comment]
不存在NAT情况，因为是用ios 手机用的5G信号也出现这个
ERROR: authorized with policy PSK+XAUTH。
而且我清空iptables也不行，出现同样的错误

**Comment by hwdsl2** [comment]
@feelingfrance 试一下重启 IPsec 服务：`sudo service ipsec restart`，或者换一个 instance 重装 VPN。
