### ISSUE TITLE
Multiple code errors in `ikev2.sh` script.

### ISSUE THREAD

**Issue by EpicBirb** [hwdsl2/setup-ipsec-vpn#1104]
**Checklist**

- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**
Multiple errors in ikev2.sh script

**To Reproduce**

get the latest script and run it

**Expected behavior**
Expected to run the script ¯\_(ツ)_/¯

**Server (please complete the following information)**
- OS: Raspbian GNU/Linux 10 (buster)

**Additional context**
Script from: ![https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/extras/ikev2setup.sh](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/extras/ikev2setup.sh)

I already fixed some of the errors my self but there is one that I don't know, I am not sure if there are any more errors but I will list the changes that needs to be changed:

LINE 704: ikev2.sh: 704: ikev2.sh: Syntax error: "(" unexpected
Before: `certutil -z <(head -c 1024 /dev/urandom) \`
After: `certutil -z head -c 1024 /dev/urandom \`

LINE 1007: ikev2.sh: 704: ikev2.sh: Syntax error: "(" unexpected
Before: `certutil -z <(head -c 1024 /dev/urandom) \`
After: `certutil -z head -c 1024 /dev/urandom \`

LINE 1018: ikev2.sh: 704: ikev2.sh: Syntax error: "(" unexpected
Before: `certutil -z <(head -c 1024 /dev/urandom) \`
After: `certutil -z head -c 1024 /dev/urandom \`

LINE 1027: ikev2.sh: 704: ikev2.sh: Syntax error: "(" unexpected
Before: `certutil -z <(head -c 1024 /dev/urandom) \`
After: `certutil -z head -c 1024 /dev/urandom \`

--[END OF CHANGES]--

After all of these changes, I finally end up with this error:
```
IKEv2 Script   Copyright (c) 2020-2022 Lin Song   16 Feb 2022

IKEv2 is already set up on this server.

Select an option:
  1) Add a new client
  2) Export configuration for an existing client
  3) List existing clients
  4) Revoke a client certificate
  5) Remove IKEv2
  6) Exit
Option: 1
ikev2.sh: 646: ikev2.sh: [[: not found
1: invalid selection.
Option:
```

I don't really know how to fix this error since I don't script in shell that much

**Comment by hwdsl2** [comment]
@EpicBirb Hello! Thanks for your suggestions. However, the fixes you mentioned are not correct. No change is needed, simply run the original version of the script with `bash` instead of `sh`. It cannot be run with `sh`.
