### ISSUE TITLE
How to kick off an active connection?

### ISSUE THREAD

**Issue by lfpak** [hwdsl2/setup-ipsec-vpn#1106]
I referenced #1011
`ipsec whack --deletestate <state_id>`
It doesn't achieve the effect I want.

If I use.
`service ipsec restart`
This works, but kicks out all clients

How do I kick out individual clients?

**Comment by letoams** [comment]
On Fri, 25 Feb 2022, lfpak wrote:

> I referenced #1011
> ipsec whack --deletestate <state_id>
> It doesn't achieve the effect I want.

Make sure the state to delete is the IKE SA and not the IPsec SA. When
you kill the IKE SA, the IPsec SA is also torn down. If you kill the
IPsec SA, then the IKE SA lingers around and shows as "connected".

> If I use.
> This works, but kicks out all clients
> 
> How do I kick out individual clients?

Another way is to use delete: ipsec whack --deleteid --name <id> but I'm
not entirely sure if that works for all kinds of IDs like certificate.

Paul

**Comment by lfpak** [comment]
> 

Paul，Thank you for your answer.

`ipsec whack --deleteid --name <id>`

I tried the command you provided and the result is that the client is still online and the single id changes.

However, I found the answer I was looking for on google with this command of yours. It applies to ipsec, the command is as follows.
`ipsec whack --deleteuser --name <username>`

I will close the issue

**Comment by ptorrent** [comment]
Hello !

I tried  ipsec whack --deleteuser --name <username>

But nothing happend.

This is the ouptut of 

ipsec whack --trafficstatus

```
006 #2: "ikev2-cp"[1] xx.xx.164.197, type=ESP, add_time=1704384802, inBytes=1979035, outBytes=49964714, maxBytes=2^63B, id='CN=my_super_user, O=IKEv2 VPN', lease=25.0.0.2/32
```

And what I did for disconnec the client:

```
ipsec whack --deleteuser --name my_super_user
```

No error, nothing happend. What do you put as username ?

Thanks for your help !

**Comment by ptorrent** [comment]
```
ipsec whack --deleteuser --name my_super_user--debug base
```
restult as 021 no connection named "my_super_user". Looks like it's not the username but the connection name ? how to get it ?

**Comment by ptorrent** [comment]
By reading ipsec command I found how to get the connection name... seems that's " ikev2-cps" ? ^^

So I tried this:

```
ipsec whack --deleteuser --name ikev2-cps --debug base
```

No more error but the client is still connected

What a nightmare x), ipsec ikev2 seems very complex to understand...
