### ISSUE TITLE
macos ikev2 与L2TP连接超时失败

### ISSUE THREAD

**Issue by fengxiaohu** [hwdsl2/setup-ipsec-vpn#1109]
**任务列表**

- [x] =我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [x] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)

**问题描述**

**重现步骤**
macos Bigsur 11.3.1 链接vpn超时，连接失败

1. ...
2. ...

**期待的正确结果**
正常连接

**日志**
[检查日志及 VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)，并添加错误日志以帮助解释该问题（如果适用）。
`ipsec status`
![image](https://user-images.githubusercontent.com/23492381/156333259-978c6a89-fcb0-4d02-87e5-096e5255a328.png)

` grep pluto /var/log/secure`
![image](https://user-images.githubusercontent.com/23492381/156333532-e3233f01-d189-4346-acc2-6e79ca760ec5.png)
![image](https://user-images.githubusercontent.com/23492381/156334447-c4beba79-75ae-4749-979b-b82b7758fe3f.png)

**服务器信息（请填写以下信息）**
- 操作系统: [Centos7]
- 服务提供商（如果适用）: [VPS]
![image](https://user-images.githubusercontent.com/23492381/156334932-8e3d8a0a-498f-45df-9717-55fe466f26a0.png)

**客户端信息（请填写以下信息）**
- 设备: [macbook M1]
- 操作系统: [Bigsur 11.3.1]
- VPN 模式: [IPsec/L2TP IKEv2均尝试过]

**其它信息**
udp 4500 500 两个端口已通
VPS 未被封禁ip

**Comment by hwdsl2** [comment]
@fengxiaohu 你好！你提供的日志不完整，没有包含全部的错误信息。请运行：
```
grep pluto /var/log/secure
grep xl2tpd /var/log/messages
```
然后将完整的日志（去掉比如 IP 地址后）在这里回复一下。

**Comment by fengxiaohu** [comment]
好的，谢谢您。
我今天重新将VPS reset，重新安装后发现还是不行。

我把输出重定向到了三个txt文件中，替换了ip。
[ipsec.txt](https://github.com/hwdsl2/setup-ipsec-vpn/files/8175688/ipsec.txt)
[pluto.txt](https://github.com/hwdsl2/setup-ipsec-vpn/files/8175690/pluto.txt)
[xl2ptd.txt](https://github.com/hwdsl2/setup-ipsec-vpn/files/8175691/xl2ptd.txt)
麻烦您帮我看看

**Comment by BlakeJian** [comment]
vpn我用的ant  挺好用
下载连接
安卓,苹果,Windows 好用的加速器 刷INS、访推特，完美支持高清1080P视频，无任何流量限制,真正免费的加速器 https://ant.aff003.net/aff/aSfvv

**Comment by fengxiaohu** [comment]
> vpn我用的ant 挺好用 下载连接 安卓,苹果,Windows 好用的加速器 刷INS、访推特，完美支持高清1080P视频，无任何流量限制,真正免费的加速器 https://ant.aff003.net/aff/aSfvv

打广告不太好吧同学

**Comment by hwdsl2** [comment]
@fengxiaohu 看了你提供的日志。IPsec/L2TP模式的问题可能是因为你的 VPN 客户端配置里的 IPsec PSK 不正确（和服务器的不一致）。也可能是网络的问题。具体表现为日志中的 `probable authentication failure (mismatch of preshared secrets?): malformed payload in packet`。正确的 PSK 可以在服务器的 `/etc/ipsec.secrets` 文件找到。

IKEv2模式的问题应该是 VPN 客户端和服务器之间的网络问题，有可能是 GFW 干扰或屏蔽了你的连接。具体表现为日志中的 retransmission。IPsec VPN 较容易被干扰，建议你换用其它解决方案比如 Shadowsocks。

**Comment by fengxiaohu** [comment]
> @fengxiaohu 看了你提供的日志。IPsec/L2TP模式的问题可能是因为你的 VPN 客户端配置里的 IPsec PSK 不正确（和服务器的不一致）。也可能是网络的问题。具体表现为日志中的 `probable authentication failure (mismatch of preshared secrets?): malformed payload in packet`。正确的 PSK 可以在服务器的 `/etc/ipsec.secrets` 文件找到。
> 
> IKEv2模式的问题应该是 VPN 客户端和服务器之间的网络问题，有可能是 GFW 干扰或屏蔽了你的连接。具体表现为日志中的 retransmission。IPsec VPN 较容易被干扰，建议你换用其它解决方案比如 Shadowsocks。

好的，谢谢您。我之前是成功搭建的，但是突然就用不了了。看来大概率是GFW的问题。等最近这段时间过去吧

**Comment by changhefirst** [comment]
天津，联通宽带+4g，移动4g。10月2日下午，手机正常翻墙过程中，IKEv2的VPN掉线。直到今天，重新安装，换vps重新安装，都无法正常连接。之前出现过2次掉线，重启vps后恢复正常。使用docker版代码安装，ip可以ping通，500/4500udp通，但是，无论手机还是mac都无法正常连接。偶尔有2次能够连接，但仍然无法上网。最夸张的是有一次连通后，实验访问facebook，然后chrome报告说facebook不支持https，不建议继续访问。被成功中间人？

症状和楼上基本一致。也是retransmitting response这步，client和server两边都在发，但互相似乎收不到。
