### ISSUE TITLE
azure setup error

### ISSUE THREAD

**Issue by yadude87** [hwdsl2/setup-ipsec-vpn#1111]
"code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "VMExtensionProvisioningError",
      "message": "VM has reported a failure when processing extension 'installcustomscript'. Error message: \"Enable failed: failed to execute command: command terminated with exit status=1\n[stdout]\n## VPN setup in progress... Please be patient.\n## Installing packages required for setup...\n\n[stderr]\n2022-03-04 16:48:36 URL:https://raw.githubusercontent.com/hwdsl2/setup-ipsec-vpn/master/vpnsetup.sh [9423/9423] -> \"vpn.sh\" [1]\n+ wget -t 3 -T 30 -q -O /tmp/vpn.01FD6/vpn.sh https://github.com/hwdsl2/setup-ipsec-vpn/raw/master/vpnsetup_ubuntu.sh\n+ apt-get -yqq update\n+ apt-get -yqq install wget dnsutils openssl iptables iproute2 gawk grep sed net-tools\nE: Package 'net-tools' has no installation candidate\n+ apt-get -yqq install wget dnsutils openssl iptables iproute2 gawk grep sed net-tools\nE: Package 'net-tools' has no installation candidate\nError: 'apt-get install' failed.\n\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "
    }
  ]
}

**Comment by hwdsl2** [comment]
@yadude87 Hello! Your logs indicate that this may be a transient error with the Debian repositories that your server used. Try deploying the template again on a new server.
