### ISSUE TITLE
Trouble connecting with Draytek router

### ISSUE THREAD

**Issue by ChrisKayAyling** [hwdsl2/setup-ipsec-vpn#1117]
Good Afternoon,

I've managed to connect perfectly using a windows machine however when trying to connect from a Draytek router in Lan to Lan mode it fails to connect.

Tried a number of different configurations still with no luck?

Regards
Chris

**Comment by hwdsl2** [comment]
@ChrisKayAyling Hello! Draytek routers are not supported as an IPsec VPN client for this project.
