### ISSUE TITLE
About turning on L2TP debug, no logs appear

### ISSUE THREAD

**Issue by lfpak** [hwdsl2/setup-ipsec-vpn#1118]
I added the line `debug` to `/etc/ppp/options.xl2tpd` and after restarting `service xl2tpd restart`, I didn't find the file `var/log/syslog`, what am I missing?
`/etc/ppp/options.xl2tpd` reads as follows.
```
+mschap-v2
ipcp-accept-local
ipcp-accept-remote
noccp
auth
mtu 1280
mru 1280
proxyarp
lcp-echo-failure 4
lcp-echo-interval 30
connect-delay 5000
ms-dns 8.8.8.8
ms-dns 8.8.4.4
debug
```

**Comment by hwdsl2** [comment]
@lfpak Hello! Some Linux systems (e.g. CentOS) may store xl2tpd logs in `/var/log/messages`. See [1] for more information.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status
