### ISSUE TITLE
Blog post on using setup-ipsec-vpn on a Raspberry Pi 3

### ISSUE THREAD

**Issue by nodesocket** [hwdsl2/setup-ipsec-vpn#112]
@hwdsl2 I wrote a blog post on using your awesome project to setup a VPN server on a Raspberry Pi 3. Maybe you can link to it from the README here?

https://blog.elasticbyte.net/setting-up-a-native-cisco-ipsec-vpn-server-using-a-raspberry-pi/

Thanks again, `setup-ipsec-vpn` is fantastic and has been a lifesaver. Also, I see your interested in potential DevOps/Engineer gigs and positions. Send me an e-mail `justin [at] elasticbyte #dot# net` if you are interested. I may have some projects and tasks. Background see [Elastic Byte](https://elasticbyte.net).

**Comment by hwdsl2** [comment]
@nodesocket Great article Justin! Thank you for sharing with us. I'm glad the project was helpful for you.

**Comment by hwdsl2** [comment]
@nodesocket I found a minor issue in your blog post: In the `wget` command, there should be no space after the `\` at end of each line. Otherwise if a reader copy and paste from your blog post, that multi-line command won't work. Please check.

**Comment by nodesocket** [comment]
@hwdsl2 the trailing spaces were due to the syntax highlighting plugin [prism.js](http://prismjs.com/). I opted to just use a GitHub gist instead. Post updated.

Thanks for pointing this out.
