### ISSUE TITLE
Access VPN client's subnet from other devices in VPN server's subnet

### ISSUE THREAD

**Issue by martin8877** [hwdsl2/setup-ipsec-vpn#1121]
Hi, 
I have two devices (EC2 instances) in the same subnet (172.31.0.0/24). An instance A (eth0 - 172.31.0.200) is a LT2P VPN Server. An instance B (eth0 - 172.31.0.100) needs access to a VPN client which is connected to instance A. The VPN client is connected to instance A and I am able to ping client's local IP (192.168.55.55) from instance A but not from instance B. 
I tried to add route ` route add -net 192.168.55.0 netmask 255.255.255.0 gw 172.31.0.200 dev eth0` on instance B but it's still not working.

**Comment by hwdsl2** [comment]
@martin8877 Hello! For your use case, I don't think it will work (to let instance B access a VPN client connected to instance A). You may need to let the client connect to instance B directly.

**Comment by martin8877** [comment]
I found out that it can be done with iptables on instance A:
`iptables -I FORWARD 8 -i eth0 -o ppp+ -j ACCEPT`

And then just add static route on instance B or set subnet's route table in AWS VPC console (VPC / Subnets / Route table).

I'm iptables newbie, so I'm not sure if this rule should be put on position eight (before DROP in FORWARD chain) or if there are any security risks.

**Comment by hwdsl2** [comment]
@martin8877 The IPTables rule you mentioned could work as you mentioned. It is not ideal, however, because this rule opens your IPsec/L2TP VPN clients to the Internet - hosts on the Internet may be able to reach these clients.
