### ISSUE TITLE
Need ipsec pluto to start ipsec normally

### ISSUE THREAD

**Issue by carmineyiu** [hwdsl2/setup-ipsec-vpn#1123]
After install vpn.sh in alpine (sys) mode, ipsec is not running. 

-> ipsec status
whack: Pluto is not running (no "/run/pluto/pluto.ctl")

-> service ipsec restart
 * service: No such file or directory
 
-> ipsec pluto
pluto: warning: chdir("/run/pluto") to dumpdir failed (2: No such file or directory)

-> ipsec status
back to normal. 

Any parameter to avoid command "ipsec pluto"?

**Comment by letoams** [comment]
Is this on a systemd OS? Then try systemctl start ipsec

Or use “ipsec start” which will use the detected init system 

Sent using a virtual keyboard on a phone

**Comment by hwdsl2** [comment]
@carmineyiu Hello! Thanks for reporting this issue. I was able to reproduce it and a fix is coming. Alpine Linux uses OpenRC and it is necessary to modify `/etc/init.d/ipsec` to use `/sbin/openrc-run` instead of `/sbin/runscript`. On your Alpine Linux system, run:
```
sed -i '1c\#!/sbin/openrc-run' /etc/init.d/ipsec
service ipsec restart
```

**Comment by carmineyiu** [comment]
Thank. problem resolved.
after running the sed commend and restart ipsec
rc-status
ipsec [started]
