### ISSUE TITLE
ios cant use vpn

### ISSUE THREAD

**Issue by Hsgay** [hwdsl2/setup-ipsec-vpn#1126]
I use this sh to make a vpn 
 but some iphone cant ues this l2TP AND   some can use it 
can i  get some answer?   thanks

**Comment by hwdsl2** [comment]
@Hsgay Hello! The issue is most likely on the VPN client side if some clients can connect but some cannot as you mentioned. Try recreating the VPN connection with the correct credentials.

Instead of IPsec/L2TP mode, it is recommended to use IKEv2: https://git.io/ikev2
