### ISSUE TITLE
端口问题

### ISSUE THREAD

**Issue by KingingWang** [hwdsl2/setup-ipsec-vpn#1127]
我想问一下，这个项目用到了哪些端口号，我需要在ufw中放行

**Comment by KingingWang** [comment]
开放了400和4500 udp和tcp ，但是连上不能上网，关闭防火墙后可以上网，就很奇怪，请问要怎么解决

**Comment by KingingWang** [comment]
> @KingingWang 你好！要使 VPN 正常工作，需要在服务器打开端口 UDP 500 和 UDP 4500。

我开了，但是不能用

**Comment by hwdsl2** [comment]
@KingingWang 有可能是你的ufw影响了VPN脚本添加的IPTables的FORWARD或NAT规则。建议你换一台服务器重装VPN试试看。
