### ISSUE TITLE
I can't activate VPN, I think my account password and public password are correct, but I can't connect it. Could you please help me check it? The following is my log, Ubuntu always tells me that the network connection fails to activate! Thank you very much.

### ISSUE THREAD

**Issue by qq1103491718** [hwdsl2/setup-ipsec-vpn#1130]
Mar 15 20:19:38 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[3] 14.153.79.64 #3: responding to Main Mode from unknown peer 14.153.79.64:21692
Mar 15 20:19:38 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[3] 14.153.79.64 #3: sent Main Mode R1
Mar 15 20:19:38 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[3] 14.153.79.64 #3: sent Main Mode R2
Mar 15 20:19:38 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[3] 14.153.79.64 #3: Peer ID is ID_IPV4_ADDR: '192.168.0.100'
Mar 15 20:19:38 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[3] 14.153.79.64 #3: switched to "l2tp-psk"[4] 14.153.79.64
Mar 15 20:19:38 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[3] 14.153.79.64: deleting connection instance with peer 14.153.79.64 {isakmp=#0/ipsec=#0}
Mar 15 20:19:38 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #3: IKE SA established {auth=PRESHARED_KEY cipher=AES_CBC_128 integ=HMAC_SHA1 group=MODP2048}
Mar 15 20:19:42 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #3: retransmitting in response to duplicate packet; already STATE_MAIN_R3
Mar 15 20:20:12 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: packet from 101.4.62.36:47221: 1-byte length of ISAKMP Vendor ID Payload is smaller than minimum
Mar 15 20:20:12 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: packet from 101.4.62.36:47221: malformed payload in packet
Mar 15 20:22:23 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #4: responding to Main Mode from unknown peer 14.153.79.64:21692
Mar 15 20:22:23 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #4: sent Main Mode R1
Mar 15 20:22:23 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #4: sent Main Mode R2
Mar 15 20:22:23 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #4: Peer ID is ID_IPV4_ADDR: '192.168.0.100'
Mar 15 20:22:23 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #4: IKE SA established {auth=PRESHARED_KEY cipher=AES_CBC_128 integ=HMAC_SHA1 group=MODP2048}
Mar 15 20:22:27 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #4: retransmitting in response to duplicate packet; already STATE_MAIN_R3
^[[AMar 15 20:24:28 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #5: responding to Main Mode from unknown peer 14.153.79.64:21692
Mar 15 20:24:28 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #5: sent Main Mode R1
Mar 15 20:24:28 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #5: sent Main Mode R2
Mar 15 20:24:28 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #5: Peer ID is ID_IPV4_ADDR: '192.168.0.100'
Mar 15 20:24:28 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #5: IKE SA established {auth=PRESHARED_KEY cipher=AES_CBC_128 integ=HMAC_SHA1 group=MODP2048}
Mar 15 20:24:32 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #5: retransmitting in response to duplicate packet; already STATE_MAIN_R3
Mar 15 20:25:08 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #6: responding to Main Mode from unknown peer 14.153.79.64:21692
Mar 15 20:25:08 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #6: sent Main Mode R1
Mar 15 20:25:08 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #6: sent Main Mode R2
Mar 15 20:25:08 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #6: Peer ID is ID_IPV4_ADDR: '192.168.0.100'
Mar 15 20:25:08 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #6: IKE SA established {auth=PRESHARED_KEY cipher=AES_CBC_128 integ=HMAC_SHA1 group=MODP2048}
Mar 15 20:25:12 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #6: retransmitting in response to duplicate packet; already STATE_MAIN_R3
Mar 15 20:25:47 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #7: responding to Main Mode from unknown peer 14.153.79.64:21692
Mar 15 20:25:47 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #7: sent Main Mode R1
Mar 15 20:25:47 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #7: sent Main Mode R2
Mar 15 20:25:47 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #7: Peer ID is ID_IPV4_ADDR: '192.168.0.100'
Mar 15 20:25:47 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #7: IKE SA established {auth=PRESHARED_KEY cipher=AES_CBC_128 integ=HMAC_SHA1 group=MODP2048}
Mar 15 20:25:51 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #7: retransmitting in response to duplicate packet; already STATE_MAIN_R3
Mar 15 20:26:20 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #8: responding to Main Mode from unknown peer 14.153.79.64:21692
Mar 15 20:26:20 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #8: sent Main Mode R1
Mar 15 20:26:20 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #8: sent Main Mode R2
Mar 15 20:26:20 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #8: Peer ID is ID_IPV4_ADDR: '192.168.0.100'
Mar 15 20:26:20 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #8: IKE SA established {auth=PRESHARED_KEY cipher=AES_CBC_128 integ=HMAC_SHA1 group=MODP2048}
Mar 15 20:26:24 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #8: retransmitting in response to duplicate packet; already STATE_MAIN_R3
Mar 15 20:26:49 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #9: responding to Main Mode from unknown peer 14.153.79.64:21692
Mar 15 20:26:49 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #9: sent Main Mode R1
Mar 15 20:26:49 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #9: sent Main Mode R2
Mar 15 20:26:49 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #9: Peer ID is ID_IPV4_ADDR: '192.168.0.100'
Mar 15 20:26:49 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #9: IKE SA established {auth=PRESHARED_KEY cipher=AES_CBC_128 integ=HMAC_SHA1 group=MODP2048}
Mar 15 20:26:53 iZj6ciuzx7lule3j0ygurlZ pluto[5072]: "l2tp-psk"[4] 14.153.79.64 #9: retransmitting in response to duplicate packet; already STATE_MAIN_R3

**Comment by qq1103491718** [comment]
> 2022 年 3 月 15 日星期二，base niuguri 写道：“未启用已配置的 DPD (RFC 3706) 支持，因为远程对等方未宣传 DPD 支持”
> 这是一个可以忽略的无害错误。保罗



> On Tue, 15 Mar 2022, base niuguri wrote: "Configured DPD (RFC 3706) support not enabled because remote peer did not advertise DPD support"
> This is a harmless error that can be ignored. Paul

I guess I know that my national firewall has blocked my VPN connection, so I can't connect to it no matter how hard I try even if I switch servers

**Comment by hwdsl2** [comment]
@qq1103491718 Hello! Yes, I think this is caused by network issues between the VPN client and server, as you mentioned. You may want to try a different solution.
