### ISSUE TITLE
pfsense 连接不成功

### ISSUE THREAD

**Issue by anhilo** [hwdsl2/setup-ipsec-vpn#1131]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**

**To Reproduce**

1. ...
2. ...

**Expected behavior**

**Logs**
[Check logs and VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status), and add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- OS: [e.g. Debian 10]
- Hosting provider (if applicable): [e.g. GCP, AWS]

**Client (please complete the following information)**
- Device: [e.g. iPhone 8]
- OS: [e.g. iOS 13.6]
- VPN mode: [IPsec/L2TP, IPsec/XAuth ("Cisco IPsec") or IKEv2]

**Additional context**
经过各种尝试，仍然连接不上docker环境下的ipsec ikev2 服务端，查看日志

<html>
<body>

Mar 15 20:39:05 | charon | 66922 | 06[ENC] <con100000\|74> parsed content of encrypted payload
-- | -- | -- | --
Mar 15 20:39:05 | charon | 66922 | 06[ENC] <con100000\|74> insert decrypted payload of type NOTIFY at end of list
Mar 15 20:39:05 | charon | 66922 | 06[ENC] <con100000\|74> verifying message structure
Mar 15 20:39:05 | charon | 66922 | 06[ENC] <con100000\|74> found payload of type NOTIFY
Mar 15 20:39:05 | charon | 66922 | 06[ENC] <con100000\|74> parsed IKE_AUTH response 1 [ N(AUTH_FAILED) ]
Mar 15 20:39:05 | charon | 66922 | 06[IKE] <con100000\|74> received AUTHENTICATION_FAILED notify error
Mar 15 20:39:05 | charon | 66922 | 06[CHD] <con100000\|74> CHILD_SA con100000{75} state change: CREATED => DESTROYING

</body>
</html>

**Comment by qq1103491718** [comment]
你是今天连接不上的嘛？用的哪里的服务器 阿里云的？

**Comment by anhilo** [comment]
不是今天，是今天测试使用。windows 机器使用p12的key能连。但是pfsense连接不上。不知道该如何配置。看了有routeros的配置方式，有点不一样，pfsense 导入一次证书，可以看到有ca和client的证书都包含。

**Comment by qq1103491718** [comment]
> 不是今天，是今天测试使用。windows 机器使用p12的key能连。但是pfsense连接不上。不知道该如何配置。看了有routeros的配置方式，有点不一样，pfsense 导入一次证书，可以看到有ca和client的证书都包含。

你可以看一下日志，它总是尝试链接。你可以换一台服务器试一下，我换一台就好了 不是设置的问题 ，估计看youtube流量太大被郭嘉墙检查到了

**Comment by anhilo** [comment]
我用的是国内的机器。国内的网络连，应该不至于有墙的问题。pfsense你测试OK了么。能贴一下设置界面嘛。

**Comment by anhilo** [comment]
我又测试了一边，说下我的流程。
```docker run \
    --name ipsec-vpn-server \
    --restart=always \
    -v ikev2-vpn-data:/etc/ipsec.d \
    -v /lib/modules:/lib/modules:ro \
    -p 500:500/udp \
    -p 4500:4500/udp \
    -d --privileged \
    hwdsl2/ipsec-vpn-server``` 在腾讯云机器上创建ipsec 服务，拿到vpnclient.p12 文件。
上传到pfsense 证书管理界面
![image](https://user-images.githubusercontent.com/1735477/158529321-1f62f713-719a-4375-9f2e-b6cc752a57c0.png)
![image](https://user-images.githubusercontent.com/1735477/158529420-7f9fce08-ab73-4a42-9724-832c77c40e76.png)
![image](https://user-images.githubusercontent.com/1735477/158529504-6f181952-c6ce-443c-83b9-4552d1643bb4.png)
ipsec配置界面都是默认。
![image](https://user-images.githubusercontent.com/1735477/158529603-d5958bfe-e217-4d82-950b-bcc42f0e9972.png)
在ipsec状态界面，还是无法连接
@qq1103491718

**Comment by anhilo** [comment]
https://github.com/hwdsl2/setup-ipsec-vpn/issues/930 根据这个解决了。
