### ISSUE TITLE
problem IKEv2 connection (Android 11, strongswan)

### ISSUE THREAD

**Issue by Shayan-Goudarzi** [hwdsl2/setup-ipsec-vpn#1132]
Hi.
on other versions is ok, but on android 11 devices it just stuck on 
> establishing IKE_SA failed, peer not responding

and then start reconnecting loop again...
any idea?

**Comment by hwdsl2** [comment]
@Shayan-Goudarzi Hello! You may check VPN status and logs for errors using these instructions [1].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status

**Comment by Shayan-Goudarzi** [comment]
@hwdsl2 tnx. but no need of that.
thats happen because of a wrong routing in my network.
the problem got solved

**Comment by amirdana** [comment]
hey @Shayan-Goudarzi, im facing the same problem, how did you fix it?
