### ISSUE TITLE
Ejecutar desde Router

### ISSUE THREAD

**Issue by DrakoAI** [hwdsl2/setup-ipsec-vpn#1135]
Hola, me gustaria sugerir que se pudiera ejecutar el codigo desde los router, en especifico el HUAWIE WiFi AX3 que es el que tengo. 😅

Y tambien que se pueda ver contenido bloqueado en otros paises.

Gracias. ✌

**Comment by hwdsl2** [comment]
@DrakoAI Hello! Thank you for your suggestion. Currently, the Huawei WiFi AX3 router is not supported as an IPsec VPN client for this project.
