### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by linux0x5c** [hwdsl2/setup-ipsec-vpn#1138]
```
## Compiling and installing Libreswan, please wait...
+ make -j25 -s base
/opt/src/libreswan-4.6/lib/libswan/addr_lookup.c: In function ‘resolve_defaultroute_one’:
/opt/src/libreswan-4.6/lib/libswan/addr_lookup.c:468:9: error: ‘RTA_PREF’ undeclared (first use in this function)
    case RTA_PREF:
         ^
/opt/src/libreswan-4.6/lib/libswan/addr_lookup.c:468:9: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [addr_lookup.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /usr/include/linux/xfrm.h:4:0,
                 from ../../include/netlink_attrib.h:6,
                 from /opt/src/libreswan-4.6/lib/libswan/netlink_attrib.c:24:
/usr/include/linux/in6.h:30:8: error: redefinition of ‘struct in6_addr’
 struct in6_addr {
        ^
In file included from ../../include/libreswan.h:26:0,
                 from ../../include/names_constant.h:5,
                 from ../../include/constants.h:354,
                 from ../../include/lswlog.h:31,
                 from /opt/src/libreswan-4.6/lib/libswan/netlink_attrib.c:23:
/usr/include/netinet/in.h:197:8: note: originally defined here
 struct in6_addr
        ^
In file included from /usr/include/linux/xfrm.h:4:0,
                 from ../../include/netlink_attrib.h:6,
                 from /opt/src/libreswan-4.6/lib/libswan/netlink_attrib.c:24:
/usr/include/linux/in6.h:41:8: error: redefinition of ‘struct sockaddr_in6’
 struct sockaddr_in6 {
        ^
In file included from ../../include/libreswan.h:26:0,
                 from ../../include/names_constant.h:5,
                 from ../../include/constants.h:354,
                 from ../../include/lswlog.h:31,
                 from /opt/src/libreswan-4.6/lib/libswan/netlink_attrib.c:23:
/usr/include/netinet/in.h:238:8: note: originally defined here
 struct sockaddr_in6
        ^
In file included from /usr/include/linux/xfrm.h:4:0,
                 from ../../include/netlink_attrib.h:6,
                 from /opt/src/libreswan-4.6/lib/libswan/netlink_attrib.c:24:
/usr/include/linux/in6.h:49:8: error: redefinition of ‘struct ipv6_mreq’
 struct ipv6_mreq {
        ^
In file included from ../../include/libreswan.h:26:0,
                 from ../../include/names_constant.h:5,
                 from ../../include/constants.h:354,
                 from ../../include/lswlog.h:31,
                 from /opt/src/libreswan-4.6/lib/libswan/netlink_attrib.c:23:
/usr/include/netinet/in.h:274:8: note: originally defined here
 struct ipv6_mreq
        ^
make[3]: *** [netlink_attrib.o] Error 1
make[2]: *** [base] Error 2
make[1]: *** [recursive-base] Error 2
make: *** [recursive-base] Error 2
Error: Libreswan 4.6 failed to build.
+ status=1
+ /bin/rm -f /tmp/vpn.w8d63/vpn.sh
+ /bin/rmdir /tmp/vpn.w8d63
+ exit 1
```

系统Centos 7.2

**Comment by gpsim** [comment]
我也遇到同样的问题 + wget -t 3 -T 30 -q -O /tmp/vpn.IZO9Y/vpn.sh https://github.com/hwdsl2/setup-ipsec-vpn/raw/master/vpnsetup_centos.sh
## VPN credentials not set by user. Generating random PSK and password...
## VPN setup in progress... Please be patient.
## Installing packages required for setup...
+ yum -y -q install wget bind-utils openssl tar iptables iproute gawk grep sed net-tools
## Trying to auto discover IP of this server...
## Adding the EPEL repository...
+ yum -y -q install epel-release
## Installing packages required for the VPN...
+ yum -y -q install nss-devel nspr-devel pkgconfig pam-devel libcap-ng-devel libselinux-devel curl-devel nss-tools flex bison gcc make util-linux ppp
+ yum --enablerepo=epel -y -q install xl2tpd
+ yum '--enablerepo=*server-*optional*' '--enablerepo=*releases-optional*' -y -q install systemd-devel libevent-devel fipscheck-devel iptables-services
## Installing Fail2Ban to protect SSH...
+ yum --enablerepo=epel -y -q install fail2ban
## Downloading helper scripts...
+ ikev2.sh addvpnuser.sh delvpnuser.sh 
## Downloading Libreswan...
+ wget -t 3 -T 30 -q -O libreswan-4.7.tar.gz https://github.com/libreswan/libreswan/archive/v4.7.tar.gz
## Compiling and installing Libreswan, please wait...
+ make -j2 -s base
/opt/src/libreswan-4.7/lib/libswan/addr_lookup.c: In function ‘resolve_defaultroute_one’:
/opt/src/libreswan-4.7/lib/libswan/addr_lookup.c:471:9: error: ‘RTA_PREF’ undeclared (first use in this function)
    case RTA_PREF:
         ^
/opt/src/libreswan-4.7/lib/libswan/addr_lookup.c:471:9: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [addr_lookup.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [base] Error 2
make[1]: *** [recursive-base] Error 2
make: *** [recursive-base] Error 2
Error: Libreswan 4.7 failed to build.
