### ISSUE TITLE
这是被gfw干扰了吗

### ISSUE THREAD

**Issue by Tiantian201807** [hwdsl2/setup-ipsec-vpn#1141]
Mar 27 21:30:54 c2021062500846 pluto[21601]: "l2tp-psk"[3] XXX #3: Peer ID is ID_IPV4_ADDR: '192.168.1.6'
Mar 27 21:30:54 c2021062500846 pluto[21601]: "l2tp-psk"[3] XXX  #3: IKE SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA1 group=MODP2048}
Mar 27 21:30:54 c2021062500846 pluto[21601]: "l2tp-psk"[3] XXX  #3: Configured DPD (RFC 3706) support not enabled because remote peer did not advertise DPD support
Mar 27 21:30:55 c2021062500846 pluto[21601]: "l2tp-psk"[3] XXX  #3: retransmitting in response to duplicate packet; already STATE_MAIN_R3
Mar 27 21:30:56 c2021062500846 pluto[21601]: "l2tp-psk"[3] XXX  #3: retransmitting in response to duplicate packet; already STATE_MAIN_R3
Mar 27 21:30:59 c2021062500846 pluto[21601]: "l2tp-psk"[3] XXX  #3: discarding duplicate packet -- exhausted retransmission; already STATE_MAIN_R3
Mar 27 21:31:02 c2021062500846 pluto[21601]: "l2tp-psk"[3] XXX  #3: discarding duplicate packet -- exhausted retransmission; already STATE_MAIN_R3
Mar 27 21:31:05 c2021062500846 pluto[21601]: "l2tp-psk"[3] XXX  #3: discarding duplicate packet -- exhausted retransmission; already STATE_MAIN_R3
Mar 27 21:31:08 c2021062500846 pluto[21601]: "l2tp-psk"[3] XXX  #3: discarding duplicate packet -- exhausted retransmission; already STATE_MAIN_R3
Mar 27 21:31:11 c2021062500846 pluto[21601]: "l2tp-psk"[3] XXX  #3: discarding duplicate packet -- exhausted retransmission; already STATE_MAIN_R3

在win11上我先用一个vpn软件连接以后，再连这台VPN服务器可以连接上，也能正常使用。
但是如果直接连这台服务器，就会出现上面的错误，并且连接不了，这是被gfw干扰了吗，还是其他什么原因。
有解决方案吗？

**Comment by hwdsl2** [comment]
@Tiantian201807 你好！从你的日志来看，是可能被GFW干扰了。建议你换用其他的解决方案。

**Comment by landall** [comment]
> @Tiantian201807 你好！从你的日志来看，是可能被GFW干扰了。建议你换用其他的解决方案。

我基本上每台机器过几个月就会这样一次 = =|||
