### ISSUE TITLE
ikev2下只能两个设备同时接入

### ISSUE THREAD

**Issue by chokyzhou** [hwdsl2/setup-ipsec-vpn#1146]
哈喽，我情况是当第三个设备连入后，第一个连入的设备还会显示已连接vpn但收不到包。想问下ikev2下能同时连入几个设备？

**Comment by hwdsl2** [comment]
@chokyzhou 你好！IKEv2 下同时连接的客户端没有限制。但是，如果要连接多个客户端，则必须为每个客户端生成唯一的证书。请参见：
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#无法同时连接多个-ikev2-客户端
