### ISSUE TITLE
Close connection after connected for duration

### ISSUE THREAD

**Issue by nodesocket** [hwdsl2/setup-ipsec-vpn#1147]
**Describe the enhancement request**

Is it possible to set a maximum connection time limit? I.E. after 6 hours, I'd like to forcefully close VPN connections. Using IPsec/XAuth ("Cisco IPsec") only. Is this built into Libreswan at all?

**Is your enhancement request related to a problem? Please describe.**

Limit connections when forgetting to disconnect VPN when finished with it.

**Comment by hwdsl2** [comment]
@nodesocket Hello! Libreswan does not support this feature AFAIK.

@letoams Is setting a maximum connection time limit supported in Libreswan?

**Comment by letoams** [comment]
> On Apr 5, 2022, at 21:09, Lin Song ***@***.***> wrote:
> 
> ﻿
> @nodesocket Hello! Libreswan does not support this feature AFAIK.
> 
> @letoams Is setting a maximum connection time limit supported in Libreswan?
> 

salifetime=6h

With 

rekey=no

Will terminate the connection and wait for the peer to connect again.

Paul

**Comment by hwdsl2** [comment]
Thanks @letoams! @nodesocket Please try these settings, `salifetime=6h` and `rekey=no`, in your `/etc/ipsec.conf` and/or `/etc/ipsec.d/ikev2.conf`, then restart the IPsec service. Note that with these settings, the client can still rekey or reconnect after the connection terminates.

**Comment by nodesocket** [comment]
@hwdsl2 @letoams which of the categories do these settings go under?

- config setup
- conn shared
- conn l2tp-psk
- conn xauth-psk

**Comment by hwdsl2** [comment]
@nodesocket For IPsec/L2TP mode, put those settings in `conn l2tp-psk`. For IPsec/XAuth ("Cisco IPsec") mode, put them in `conn xauth-psk`. For IKEv2 mode, put them in `/etc/ipsec.d/ikev2.conf`. Then restart the IPsec service.

**Comment by letoams** [comment]
Yes, set salifetime=6h and rekey=no

Sent using a virtual keyboard on a phone
