### ISSUE TITLE
在nat8下能够使用ipsec访问外网吗

### ISSUE THREAD

**Issue by iwrwr** [hwdsl2/setup-ipsec-vpn#1148]
ipsec架设在win系统下的VMware虚拟的linux里，然后通过nat8共享网络
并且进行相应的linux vpn端口到win端口的转发
在外网下连接win转发出的vpn能够连接上，但无法访问外网和linux的nat内网ip
这是由于nat下ipsec的缘故吗

**Comment by hwdsl2** [comment]
@iwrwr 你好！你所说的配置我不熟悉。有可能是VMnet8的原因，也可能是Windows防火墙禁止了VPN的流量。
