### ISSUE TITLE
Android 12 native client

### ISSUE THREAD

**Issue by P0zitiff4ik** [hwdsl2/setup-ipsec-vpn#1149]
Samsung Galaxy S20FE Android 12 (OneUI 4.0)
Native client doesn't connecting through ikev2-rsa. Strongswan works fine

**Comment by hwdsl2** [comment]
@P0zitiff4ik Hello! Thank you for reporting this issue. Currently, the Android 12 native IKEv2 client is not supported. Please instead use the strongSwan Android VPN client.

**Comment by letoams** [comment]
This will work with the next version of libreswan (fix is in git already)

Sent using a virtual keyboard on a phone

**Comment by xianren78** [comment]
solved with libreswan 4.7, and you can update your server with latest script
