### ISSUE TITLE
Clients are isolated or not?

### ISSUE THREAD

**Issue by tunayuyar** [hwdsl2/setup-ipsec-vpn#115]
Hi,

As in subject each client connecting vpn server is isolated or not? 

Reason Im asking is can i play games(over lan option) with my friends when we all connect to same vpn server? As you know some of the old games do not have internet option for multiplayer and sometimes even if they do have, you cannot forward ports or even reach router to forward ports?

If clients are isolated how  I can make it so that every client can see each other?

Thanks.

**Comment by hwdsl2** [comment]
@tunayuyar Hello! In the default configuration VPN clients are allowed to
connect to each other, using their assigned virtual VPN subnet address.

If you connect using IPsec/L2TP, the VPN clients have virtual IP of
192.68.42.10 (first client), up to 192.68.42.250. The VPN server has
virtual IP 192.168.42.1.

If you connect using Cisco IPsec, the VPN clients have virtual IP of
192.68.43.10 (first client), up to 192.68.43.250.

**Comment by hwdsl2** [comment]
@tunayuyar Hello! In the default configuration VPN clients are allowed to
connect to each other, using their assigned virtual VPN subnet address.

If you connect using IPsec/L2TP, the VPN clients have virtual IP of
192.168.42.10 (first client), up to 192.168.42.250. The VPN server has
virtual IP 192.168.42.1.

If you connect using Cisco IPsec, the VPN clients have virtual IP of
192.168.43.10 (first client), up to 192.168.43.250.
