### ISSUE TITLE
求解

### ISSUE THREAD

**Issue by oceans-wu** [hwdsl2/setup-ipsec-vpn#1150]
我是两台服务器，一台服务器做服务端一台做端口转发，这两台内网互通，当转发成公网可以正常连接，当转发内网的时候报错用户名密码验证失败，但是账号密码都是没有改变
Apr 07 11:38:31 HK_IPSEC pluto[13083]: "xauth-psk"[4] 192.168.2.221 #4: XAUTH: password file (/etc/ipsec.d/passwd) open.
Apr 07 11:38:31 HK_IPSEC pluto[13083]: "xauth-psk"[4] 192.168.2.221 #4: XAUTH: failure user(yisu:xauth-psk)
Apr 07 11:38:31 HK_IPSEC pluto[13083]: "xauth-psk"[4] 192.168.2.221 #4: XAUTH: User yisu: Authentication Failed: Incorrect Username
or Password
Apr 07 11:38:31 HK_IPSEC pluto[13083]: "xauth-psk"[4] 192.168.2.221 #4: Expected MODE_CFG_REPLY is missing username and password att
ribute
Apr 07 11:38:31 HK_IPSEC pluto[13083]: "xauth-psk"[4] 192.168.2.221 #4: XAUTH: Sending Username/Password request (XAUTH_R0->XAUTH_R0
)
Apr 07 11:38:31 HK_IPSEC pluto[13083]: "xauth-psk"[4] 192.168.2.221 #4: XAUTH: User <unknown>: Authentication Failed (retry 1)
Apr 07 11:38:31 HK_IPSEC pluto[13083]: "xauth-psk"[4] 192.168.2.221 #4: received Delete SA payload: self-deleting ISAKMP State #4
Apr 07 11:38:31 HK_IPSEC pluto[13083]: "xauth-psk"[4] 192.168.2.221 #4: deleting state (STATE_XAUTH_R0) aged 0.206531s and sending n
otification
Apr 07 11:38:31 HK_IPSEC pluto[13083]: "xauth-psk"[4] 192.168.2.221: deleting connection instance with peer 192.168.2.221 {isakmp=#0
/ipsec=#0}

**Comment by hwdsl2** [comment]
@oceans-wu 你好！你所说的情况一般不应该发生。请检查你的用户名和密码是否输入正确？另外你可以尝试将 `/etc/ipsec.conf` 中的 `leftid=...` 换成你的服务器的内网 IP，然后重启 IPsec 服务试试看。如果无效，可以改回原来的值。

如果你确定 VPN 凭据输入正确，有可能是 Libreswan 的问题。你可以到这里问一下 [1][2]。

[1] https://github.com/libreswan/libreswan
[2] https://lists.libreswan.org/mailman/listinfo/swan

**Comment by oceans-wu** [comment]
用户名密码没做任何修改，公网是可以的连上的，left=内网    leftid=内网，此情况在在转发服务器装了客户端，相同的账号密码是可以 successfully 的。

**Comment by hwdsl2** [comment]
@oceans-wu 我觉得有可能是 Libreswan 的 bug，建议你到以上两个链接问一下。

**Comment by oceans-wu** [comment]
好的非常感谢
