### ISSUE TITLE
ike2配置leftsubnets后能连接

### ISSUE THREAD

**Issue by monday2k** [hwdsl2/setup-ipsec-vpn#1153]
ike2配置leftsubnets后能连接，提示策略不匹配

**Comment by hwdsl2** [comment]
@monday2k 你好！请参见这些相关的 Issue：
https://github.com/hwdsl2/setup-ipsec-vpn/issues/1053
https://github.com/hwdsl2/setup-ipsec-vpn/issues/530
https://github.com/libreswan/libreswan/issues/243

根据以上 Issue 的讨论，Libreswan 4.4及以上版本应该可以使用leftsubnets（服务器端）。有可能是一个bug，建议你在 https://github.com/libreswan/libreswan 开一个 Issue 详细说明一下。
