### ISSUE TITLE
"Wireless interface wls32 detected. DO NOT run this script on your PC or Mac!"

### ISSUE THREAD

**Issue by yyaaa1** [hwdsl2/setup-ipsec-vpn#1155]
我的server default的网卡确实是无线网卡，系统是ubuntu参考 https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/vpnsetup.sh#L78-L84 注释掉对应行也还是会报相同的错误。想请教下该如何跳过这个检查？以及为什么不建议在无线网卡上搭建vpn？谢谢

**Comment by hwdsl2** [comment]
@yyaaa1 你好！对于你的用例，请使用：
https://raw.githubusercontent.com/hwdsl2/setup-ipsec-vpn/master/vpnsetup_ubuntu.sh
下载该脚本并注释掉相应行，然后运行。该检查主要是为了帮助避免用户在比如Linux笔记本电脑等上运行VPN脚本。

**Comment by yyaaa1** [comment]
好的谢谢
