### ISSUE TITLE
Powershell issue breaking autoconfiguration script

### ISSUE THREAD

**Issue by CaptainFrosty** [hwdsl2/setup-ipsec-vpn#1156]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**
Hello, I am attempting to configure Windows 11 as a client for an IKEv2 only tunnel. Everything went smoothly on my server. The problem is the script for automatic configuration is failing because there is something wrong with the commands for the VpnClient module on PowerShell:

```
PS C:\Users\Jesse> Get-VpnConnection
Get-VpnConnection : Invalid class
At line:1 char:1
+ Get-VpnConnection
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (PS_VpnConnection:root/Microsoft/...S_VpnConnection) [Get-VpnConnection],
    CimException
    + FullyQualifiedErrorId : HRESULT 0x80041010,Get-VpnConnection
```
So the script fails at those commands. I ran a diagnostic on WMI and got some errors, so I ran a repair on that, but the issue persists. I'm not sure how to get that module back if I were to try to deleting and reimporting it. 

**To Reproduce**

1. Copy IKEv2 script and config file from server
2. Fix encryption to resolve policy match errors
3. Run script in elevated cmd

**Expected behavior**

**Server (please complete the following information)**
- OS: Rocky 8.5
- Hosting provider (if applicable): BuyVM KVM

**Client (please complete the following information)**
- Device: amd64 desktop
- OS: Windows 11 Pro 21H2 build 22000.613
- VPN mode: IKEv2-only

**Comment by hwdsl2** [comment]
@CaptainFrosty Hello! This looks like an issue with PowerShell on your PC. Here are some results from the web based on the "invalid class" PowerShell error, although they are for Windows 10. Let us know if this fixes the issue.

https://superuser.com/questions/1152280/get-net-powershell-cmdlets-failing-with-invalid-class
https://docs.microsoft.com/en-us/answers/questions/665424/add-vpnconnection-script-works-on-co-worker39s-pc.html

**Comment by CaptainFrosty** [comment]
Everything else is fine on PowerShell, since it says CimException I assume it is WMI. So I believe I fixed the problem by deleting the WMI repository and rebooting. The error messages no longer show. It is strange to me that the actual utilities to fix WMI don't work, but deleting the folder does. Tomorrow I will try the script again.

**Comment by CaptainFrosty** [comment]
@hwdsl2 The connection is working now. My only issue is that I'd rather use the DNS of my server, if that is not possible I'd prefer Quad9. It's currently set to Google DNS.

**Comment by hwdsl2** [comment]
@CaptainFrosty Glad to hear it's working. For DNS please refer to:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#use-alternative-dns-servers

I'm closing this, if you encounter issues with the DNS you can continue to comment here.

**Comment by CaptainFrosty** [comment]
@hwdsl2 I guess I was confused because I did specify the server variables in the server installation, but I don't think I did in the IKEv2 script.

**Comment by hwdsl2** [comment]
@CaptainFrosty In that case, you can edit `/etc/ipsec.d/ikev2.conf` and replace `8.8.8.8` and `8.8.4.4` with your desired DNS servers, then restart the IPsec service. More details can be found in the link in my previous comment.
