### ISSUE TITLE
共享密钥的组名

### ISSUE THREAD

**Issue by brucemi** [hwdsl2/setup-ipsec-vpn#1157]
我尝试用一个Cisco Teleworker VPN Client 来连接到VPN服务器，但是这个客户端的共享密钥有一个 组的名称（group name） 一定要输入。我想请教下，您的这个vpn服务器上是否有默认的 组的名称（group name），还是不支持这样的连接方式？
多谢盼付！
关于这个客户端和组名的 详细说明请见下面的链接。
https://www.cisco.com/assets/sol/sb/isa500_emulator/help/guide/ah1560717.html

**Comment by hwdsl2** [comment]
@brucemi 你好！需要组名 (group name) 的连接方式是 IPsec aggressive mode，该模式下 IPsec 共享密钥更容易受攻击，所以目前不支持该连接方式。
