### ISSUE TITLE
Pull users from Active Directory

### ISSUE THREAD

**Issue by KurtStineAI2** [hwdsl2/setup-ipsec-vpn#1158]
**Checklist**

- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [x] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
Is it possible to pull and update L2TP users from an Active Directory instance? This way, when a user's password updates, their VPN password would also update

**Comment by hwdsl2** [comment]
@KurtStineAI2 Hello! This feature is not currently supported.

**Comment by letoams** [comment]
You need to look for pppd options for active directory which might require putting radius in between. A quick google shows https://mivilisnet.wordpress.com/2018/10/01/how-to-integrate-your-mikrotik-router-with-windows-ad/

Sent using a virtual keyboard on a phone
