### ISSUE TITLE
How to enable disable client isolation?

### ISSUE THREAD

**Issue by rexsllemel** [hwdsl2/setup-ipsec-vpn#1159]
As I see there is no documentation on how to enable disable client isolation. I only know average linux/firewall stuff. There were also no specific article online so I guess asking here will be the best shot.

I hope you will add documentation for this.

Thank you!

**Comment by hwdsl2** [comment]
@rexsllemel Hello! There is documentation for this. Please refer to:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#internal-vpn-ips-and-traffic

More specifically, from the link above:
```
Client-to-client traffic is allowed by default. If you want to disallow client-to-client traffic, run the following commands on the VPN server.
... ...
```
