### ISSUE TITLE
Manage/limit active connections per client

### ISSUE THREAD

**Issue by AuthorShin** [hwdsl2/setup-ipsec-vpn#1161]
**Checklist**

- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [x] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
A clear and concise description of your enhancement request.

Hello
I there a way to manage/limit active connections per client?
For example user Joe can have 2 active connection but not more so for him in order to connect his new laptop need to disconnect his phone and also we have Rebecca that only can have 1 active connection so can only use her phone and to connect her new PC she have to disconnect the phone.

**Additional context**
Add any other context about the enhancement request here.

Bandwidth limit and time period limit also can be very nice as well, so they can only use 1TB every week and if they use more the speed slows down (limit to like 1mbps) or they no longer can connect till the start of the next week. and also if account (user client) was created on 01/02/2022 it will expire after 02/02/2022 so the user can no longer connect and use the VPN.

**Comment by hwdsl2** [comment]
@AuthorShin Hello! Thanks for your request. Unfortunately, IPsec does not support managing or limiting active connections per client, or other advanced features you mentioned out of the box. So the features you listed are not supported in this project.

There are a few things you can try, however, if you use IKEv2 mode:

1. You can set the client certificate validity period (in months) when adding a new IKEv2 client. This option will be available when you run `sudo ikev2.sh`, then select the option to add a new client. After expiration, the client certificate can no longer be used by IKEv2 clients to connect.
2. For IKEv2, by default, the same client certificate cannot be used by more than one device to connect to the VPN server at the same time. A new connection will replace the previous one in that case.

**Comment by AuthorShin** [comment]
Thank you very much for the answer, I was hoping that there might be a service out there to sit on top of IPsec to manage L2TP clients.
I saw people done the same (provide VPN accounts with these type of limits) but they don't tell how they have done it and I'm pretty sure it's with Linux not Mikrotik or Windows.
But again thank you for very good solution about IKEv2 but I was looking for a way to set it on L2TP.

**Comment by letoams** [comment]
You can configure pam-authorize=yes then using something like pam_url to connect to your own REST API where you can allow/dent the client. This also allows centralization, so one client connect per group of vpn servers.

Just remember, a client might be reconnecting and you don’t want to lock them out because you still have the old instance connected.

Paul

Sent using a virtual keyboard on a phone

**Comment by Mathiaszero** [comment]
>     1. You can set the client certificate validity period (in months) when adding a new IKEv2 client. This option will be available when you run `sudo ikev2.sh`, then select the option to add a new client. After expiration, the client certificate can no longer be used by IKEv2 clients to connect.

I came across this and was wondering if it was possible to set more specific times, not just in period of months? For example, is there a way so I can set it in fractions, like 0.12 months or 7 days for example?

**Comment by hwdsl2** [comment]
@Mathiaszero Hello! Because certutil only supports specifying validity periods in months ([reference](https://manpages.ubuntu.com/manpages/jammy/en/man1/certutil.1.html)), I think your use case is not currently supported.
