### ISSUE TITLE
ikev2 client connectivity issue

### ISSUE THREAD

**Issue by kalkir** [hwdsl2/setup-ipsec-vpn#1162]
Hi, 

I have recently set up ipsec ikev2 mode connection, generated the client .p12 file and extracted ca certificate and key. I have installed the client 'network-manager-strongswan' and setup the client, it is connecting fine. But I can only connect to google, seems like there is a TLS handshake issue. Somebody help on this.

**Comment by kalkir** [comment]
@hwdsl2  Thanks, I have tried the solutions mentioned in the troubleshooting guide, but none of them helps. I can actually connect to the ports when I troubleshoot with 443, but the TLS handshake is happening, so the https website are not loading other than google.com.

**Comment by letoams** [comment]
Check the MTU workarounds with tcp clamping from the documentation 

Sent using a virtual keyboard on a phone

**Comment by hwdsl2** [comment]
@kalkir Please give this a try, which I believe is what @letoams referred to:
https://libreswan.org/wiki/FAQ#My_ssh_sessions_hang_or_connectivity_is_very_slow

**Comment by kalkir** [comment]
@hwdsl2 @letoams I have tried the mentioned solutions but it didn't work for me.
