### ISSUE TITLE
ignoring IKEv1 packet as policy

### ISSUE THREAD

**Issue by foxfire881** [hwdsl2/setup-ipsec-vpn#1165]
**问题描述**
Kali系统修改/etc/os-release为Debian，之前的setup_ipsec_vpn.sh脚本使用一切正常，一键安装之后使用帐号密码就可以登录，非常方便。

前几天更新了系统，然后vpn就断掉无法连接了，于是下载了最新的setup_ipsec_vpn.sh，发现新版脚本默认启用了ikev2，引入一堆证书啥的，安全性虽然高了但是配置也变得复杂多了，而且默认生成的苹果客户端证书配置文件在iOS15上无法导入，在最后一步“安装”时老是报错说密码不对（哪来的密码？）

于是按照文档使用sudo ikev2.sh --removeikev2移除了ikev2，但是运行完发现ipsec无法启动了，报错:
whack:Pluto is not running(no "/var/run/pluto/pluto.ctl") [FAILED]

看了下脚本，新版脚本似乎改用strongswan了（我记得以前旧版好像是openswan+libreswan），于是apt install openswan，安装之后ipsec可以启动了，ipsec verify校验也全部通过，但是仍然无法连接，报错：

May  6 00:10:15 kali-rpi pluto[11690]: 4 CPU cores online
May  6 00:10:15 kali-rpi pluto[11690]: starting up 3 helper threads
May  6 00:10:15 kali-rpi pluto[11690]: started thread for helper 0
May  6 00:10:15 kali-rpi pluto[11690]: helper(1) seccomp security for helper not supported
May  6 00:10:15 kali-rpi pluto[11690]: started thread for helper 1
May  6 00:10:15 kali-rpi pluto[11690]: started thread for helper 2
May  6 00:10:15 kali-rpi pluto[11690]: using Linux xfrm kernel support code on #4 SMP PREEMPT Debian kali-pi (2021-11-05)
May  6 00:10:15 kali-rpi pluto[11690]: helper(3) seccomp security for helper not supported
May  6 00:10:15 kali-rpi pluto[11690]: kernel: xfrm XFRM_MSG_UPDPOLICY for flow add port bypass(in) encountered unexpected policy
May  6 00:10:15 kali-rpi pluto[11690]: kernel: xfrm XFRM_MSG_UPDPOLICY for flow add port bypass(fwd) encountered unexpected policy
May  6 00:10:15 kali-rpi pluto[11690]: kernel: xfrm XFRM_MSG_UPDPOLICY for flow add port bypass(out) encountered unexpected policy
May  6 00:10:15 kali-rpi pluto[11690]: kernel: xfrm XFRM_MSG_UPDPOLICY for flow add port bypass(in) encountered unexpected policy
May  6 00:10:15 kali-rpi pluto[11690]: kernel: xfrm XFRM_MSG_UPDPOLICY for flow add port bypass(fwd) encountered unexpected policy
May  6 00:10:15 kali-rpi pluto[11690]: kernel: xfrm XFRM_MSG_UPDPOLICY for flow add port bypass(out) encountered unexpected policy
May  6 00:10:15 kali-rpi pluto[11690]: helper(2) seccomp security for helper not supported
May  6 00:10:15 kali-rpi pluto[11690]: selinux support is NOT enabled.
May  6 00:10:15 kali-rpi pluto[11690]: systemd watchdog for ipsec service configured with timeout of 200000000 usecs
May  6 00:10:15 kali-rpi pluto[11690]: watchdog: sending probes every 100 secs
May  6 00:10:15 kali-rpi pluto[11690]: seccomp security not supported
May  6 00:10:15 kali-rpi pluto[11690]: "l2tp-psk": failed to add connection: IKE DH algorithm 'modp1024' is not supported
May  6 00:10:15 kali-rpi pluto[11690]: "xauth-psk": failed to add connection: IKE DH algorithm 'modp1024' is not supported
May  6 00:10:15 kali-rpi pluto[11690]: listening for IKE messages
May  6 00:10:15 kali-rpi pluto[11690]: Kernel supports NIC esp-hw-offload
May  6 00:10:15 kali-rpi pluto[11690]: adding UDP interface eth0 10.0.0.3:500
May  6 00:10:15 kali-rpi pluto[11690]: adding UDP interface eth0 10.0.0.3:4500
May  6 00:10:15 kali-rpi pluto[11690]: adding UDP interface lo 127.0.0.1:500
May  6 00:10:15 kali-rpi pluto[11690]: adding UDP interface lo 127.0.0.1:4500
May  6 00:10:15 kali-rpi pluto[11690]: adding UDP interface lo [::1]:500
May  6 00:10:15 kali-rpi pluto[11690]: loading secrets from "/etc/ipsec.secrets"
May  6 00:10:15 kali-rpi pluto[11690]: WARNING: using a weak secret (PSK)
May  6 00:10:33 kali-rpi pluto[11690]: packet from 101.22.10.100:500: ignoring IKEv1 packet as policy is set to silently drop all IKEv1 packets
May  6 00:10:36 kali-rpi pluto[11690]: packet from 101.22.10.100:500: ignoring IKEv1 packet as policy is set to silently drop all IKEv1 packets
May  6 00:10:39 kali-rpi pluto[11690]: packet from 101.22.10.100:500: ignoring IKEv1 packet as policy is set to silently drop all IKEv1 packets
May  6 00:10:43 kali-rpi pluto[11690]: packet from 101.22.10.100:500: ignoring IKEv1 packet as policy is set to silently drop all IKEv1 packets

**重现步骤**
重现该 bug 的步骤：

以上已有步骤描述。

**期待的正确结果**
希望安装前给个配置选项，让用户自己选择“帐号+密码”还是"ikev2的证书"认证，选择好了再开始安装，而不是安装之后再用脚本去移除，这样不知道会影响什么关联配置，排错很麻烦。有很多用户是家庭使用，对安全性要求并不高，方便才是更重要的，搞太麻烦了反而舍本逐末了。

**日志**
[检查日志及 VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)，并添加错误日志以帮助解释该问题（如果适用）。

**服务器信息（请填写以下信息）**
- 操作系统: 树莓派Kali，Kali本身是基于Debian的，所以把OS信息改回Debian安装。
- 服务提供商（如果适用）: Kali

**客户端信息（请填写以下信息）**
- 设备: iPhone Xs Max
- 操作系统: iOS 15
- VPN 模式: IPsec/L2TP

**其它信息**
添加关于该 bug 的其它信息。

**Comment by hwdsl2** [comment]
@foxfire881 你好！首先感谢你的建议。VPN 脚本一直是使用 Libreswan。Kali Linux 目前并不支持。你所说的 IKEv2 证书导入密码错误的问题可能是因为 Kali Linux 使用较新版本的 nss-tools 和/或 OpenSSL 导致的。对于此问题，脚本针对比如 Ubuntu 22.04 和 Alpine 3.15 等系统加入了一些 workaround [1]，但因为不支持 Kali Linux，所以该 workaround 在你的系统上没有被应用。

你日志中显示有错误，比如 `"l2tp-psk": failed to add connection: IKE DH algorithm 'modp1024' is not supported`。这是因为当你安装 Openswan 之后，它默认可能已经不支持 modp1024 算法。

要解决你的 VPN 服务器的问题，我觉得主要有两个方案可选：

1. 编辑你的服务器上的 /etc/ipsec.conf 并将 `ike=aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1,aes256-sha2;modp1024,aes128-sha1;modp1024` 替换为 `ike=aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1`，然后重启 Openswan 服务。请注意，去掉 modp1024 算法之后，Android设备可能无法连接。

或者

2. 移除 Openswan。然后重新运行这个 VPN 脚本 [2] 安装 VPN。在运行前，你可以注释掉脚本最后的 set_up_ikev2，这样就不会配置 IKEv2。

如果你有其他问题，可以继续在这里回复。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/160fbe70a81e0b7c90034fd216ac3f3239c0519a/extras/ikev2setup.sh#L757
[2] https://raw.githubusercontent.com/hwdsl2/setup-ipsec-vpn/master/vpnsetup_ubuntu.sh

**Comment by foxfire881** [comment]
> @foxfire881 你好！首先感谢你的建议。VPN 脚本一直是使用 Libreswan。Kali Linux 目前并不支持。你所说的 IKEv2 证书导入密码错误的问题可能是因为 Kali Linux 使用较新版本的 nss-tools 和/或 OpenSSL 导致的。对于此问题，脚本针对比如 Ubuntu 22.04 和 Alpine 3.15 等系统加入了一些 workaround [1]，但因为不支持 Kali Linux，所以该 workaround 在你的系统上没有被应用。
> 
> 你日志中显示有错误，比如 `"l2tp-psk": failed to add connection: IKE DH algorithm 'modp1024' is not supported`。这是因为当你安装 Openswan 之后，它默认可能已经不支持 modp1024 算法。

谢谢大佬的回复和解决方案，晚上回去就试试。因为Kali是基于Debian修改的所以才使用了大佬的脚本安装，之前使用一直非常方便一键安装成功。

modp1024算法是其中一个报错信息，SSL建立连接时会自动协商客户端和服务端都支持的算法，如果遇到不支持的算法会自动忽略不使用。

除此之外下面还有多条这样的报错信息：
May 6 00:10:43 kali-rpi pluto[11690]: packet from 101.22.10.100:500: ignoring IKEv1 packet as policy is set to silently drop all IKEv1 packets

感觉这个才是导致VPN无法工作的原因，网络包都被丢弃了，符合客户端连接VPN时的报错特征（报错：”服务端没有响应“，而不是其他信息提示），大佬知道这个错误要怎么处理吗？搜遍了网上资料也没有找到处理方案，只搜索到pluto的源码中有这个报错信息，问题是怎么查看、设置pluto的policy呢？

**Comment by foxfire881** [comment]
> @foxfire881 你好！首先感谢你的建议。VPN 脚本一直是使用 Libreswan。Kali Linux 目前并不支持。你所说的 IKEv2 证书导入密码错误的问题可能是因为 Kali Linux 使用较新版本的 nss-tools 和/或 OpenSSL 导致的。对于此问题，脚本针对比如 Ubuntu 22.04 和 Alpine 3.15 等系统加入了一些 workaround [1]，但因为不支持 Kali Linux，所以该 workaround 在你的系统上没有被应用。
> 
> 你日志中显示有错误，比如 `"l2tp-psk": failed to add connection: IKE DH algorithm 'modp1024' is not supported`。这是因为当你安装 Openswan 之后，它默认可能已经不支持 modp1024 算法。

谢谢大佬的回复和解决方案，晚上回去就试试。因为Kali是基于Debian修改的所以才使用了大佬的脚本安装，之前使用一直非常方便一键安装成功。

modp1024算法是其中一个报错信息，SSL建立连接时会自动协商客户端和服务端都支持的算法，如果遇到不支持的算法会自动忽略不使用。

除此之外下面还有多条这样的报错信息：
May 6 00:10:43 kali-rpi pluto[11690]: packet from 101.22.10.100:500: ignoring IKEv1 packet as policy is set to silently drop all IKEv1 packets

感觉这个才是导致VPN无法工作的原因，网络包都被丢弃了，符合客户端连接VPN时的报错特征（报错：”服务端没有响应“，而不是其他信息提示），大佬知道这个错误要怎么处理吗？搜遍了网上资料也没有找到处理方案，只搜索到pluto的源码中有这个报错信息，问题是怎么查看、设置pluto的policy呢？

**Comment by hwdsl2** [comment]
@foxfire881 对于你所说的错误信息，你可以尝试在 /etc/ipsec.conf 的 "config setup" 小节加入 "ikev1-policy=accept"，开头空两格。参见 [1]。然后重启 IPsec 服务。该选项适用于 Libreswan，accept 为默认值。

[1] https://libreswan.org/man/ipsec.conf.5.html

**Comment by foxfire881** [comment]
> ikev1-policy=accept

666，加上这行之后立马啥都没改立马就通了！！大佬就是大佬~ 敬仰！再次感谢！！
