### ISSUE TITLE
Establishing IKE_SA failed, peer not responding

### ISSUE THREAD

**Issue by amirdana** [hwdsl2/setup-ipsec-vpn#1166]
on ubuntu 18.04 fresh install
i'm getting this error on android client: establishing IKE_SA failed, peer not responding

any help would be appreciated

log:
May  6 10:01:53 00[DMN] Starting IKE service (strongSwan 5.9.3rc1, Android 9 - PPR1.180610.011/2020-04-01, Redmi Note 8 Pro - Redmi/begonia/Xiaomi, Linux 4.14.94+, aarch64)
May  6 10:01:53 00[LIB] loaded plugins: androidbridge charon android-log openssl fips-prf random nonce pubkey chapoly curve25519 pkcs1 pkcs8 pem xcbc hmac socket-default revocation eap-identity eap-mschapv2 eap-md5 eap-gtc eap-tls x509
May  6 10:01:53 00[JOB] spawning 16 worker threads
May  6 10:01:53 06[CFG] loaded user certificate 'CN=225784463, O=IKEv2 VPN' and private key
May  6 10:01:53 06[CFG] loaded CA certificate 'CN=IKEv2 VPN CA, O=IKEv2 VPN'
May  6 10:01:53 06[IKE] initiating IKE_SA android[1] to 5.188.190.31
May  6 10:01:53 06[ENC] generating IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(REDIR_SUP) ]
May  6 10:01:53 06[NET] sending packet: from 192.168.1.50[51442] to 5.188.190.31[500] (464 bytes)
May  6 10:01:55 12[IKE] retransmit 1 of request with message ID 0
May  6 10:01:55 12[NET] sending packet: from 192.168.1.50[51442] to 5.188.190.31[500] (464 bytes)
May  6 10:01:58 13[IKE] retransmit 2 of request with message ID 0
May  6 10:01:58 13[NET] sending packet: from 192.168.1.50[51442] to 5.188.190.31[500] (464 bytes)
May  6 10:02:02 10[IKE] retransmit 3 of request with message ID 0
May  6 10:02:02 10[NET] sending packet: from 192.168.1.50[51442] to 5.188.190.31[500] (464 bytes)
May  6 10:02:08 14[IKE] giving up after 3 retransmits
May  6 10:02:08 14[IKE] establishing IKE_SA failed, peer not responding
May  6 10:02:08 15[IKE] unable to terminate IKE_SA: ID 1 not found

**Comment by hwdsl2** [comment]
@amirdana Hello! Your logs indicate that the Android client could not reach the VPN server on UDP port 500. This may be a firewall or network issue. For servers with an external firewall (e.g. EC2/GCE), open UDP ports 500 and 4500 for the VPN. See important notes [1].

[1] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes

**Comment by amirdana** [comment]
by external firewall you mean the vps provider is restricting the ports?

here is my open ports:
sudo netstat -tunlp

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      285/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      592/sshd            
tcp6       0      0 :::22                   :::*                    LISTEN      592/sshd            
udp        0      0 127.0.0.1:500           0.0.0.0:*                           1400/pluto          
udp        0      0 5.188.190.31:500        0.0.0.0:*                           1400/pluto          
udp        0      0 127.0.0.53:53           0.0.0.0:*                           285/systemd-resolve 
udp        0      0 127.0.0.1:4500          0.0.0.0:*                           1400/pluto          
udp        0      0 5.188.190.31:4500       0.0.0.0:*                           1400/pluto          
udp        0      0 0.0.0.0:1701            0.0.0.0:*                           1418/xl2tpd         
udp6       0      0 2a03:90c0:164::2c3:500  :::*                                1400/pluto          
udp6       0      0 ::1:500                 :::*                                1400/pluto
