### ISSUE TITLE
Allow clients to connect without IPSec?

### ISSUE THREAD

**Issue by LoneRager117** [hwdsl2/setup-ipsec-vpn#1167]
I have used this script to setup a L2TP/IPSec VPN, but I have some clients that I want to allow to connect without using IPSec. I have tried deleting these rules:

```
iptables -A INPUT -p udp --dport 1701 -m policy --dir in --pol ipsec -j ACCEPT
iptables -A INPUT -p udp --dport 1701 -j DROP
```

But they just come right back. What am I missing here? Thank you!

**Comment by hwdsl2** [comment]
@LoneRager117 Hello! Connecting without IPsec is NOT recommended because the traffic is not encrypted, which defeats the purpose of a VPN. It is not supported in the default configuration.

If you want to do that anyway, however, you can try removing this IPTables rule, instead of the two you mentioned (those should not be removed):
```
    iptables -A INPUT -p udp --dport 1701 -m policy --dir in --pol none -j DROP
```

**Comment by LoneRager117** [comment]
I set this up on one VPS, and it worked, however I just set this up on a AWS Ubuntu VPS, and I can connect with IPSec enabled, but not with it disabled.  I have deleted these firewall rules.  Anything else I should check on?

**Comment by hwdsl2** [comment]
@LoneRager117 For your use case, you'll need to open UDP port 1701 in your AWS server's security group. Again, this is NOT recommended because the traffic is not encrypted without IPsec.

**Comment by laz980415** [comment]
你好 我执行了 
`iptables -A INPUT -p udp --dport 1701 -m policy --dir in --pol none -j DROP`
但是依然同一个局域网只能有一台设备进行连接

**Comment by laz980415** [comment]
@hwdsl2 你好 我执行了 
`# iptables -A INPUT -p udp --dport 1701 -m policy --dir in --pol none -j DROP
# systemctl restart iptables 
`
但是同一个局域网还是只能有一台设备可以连接

**Comment by hwdsl2** [comment]
@laz980415 你好！由于 IPsec/L2TP 的局限性，如果需要连接在同一个 NAT（比如家用路由器）后面的多个设备，你必须使用 [IKEv2](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md) 或者 [IPsec/XAuth](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth-zh.md) 模式。参见[重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#%E9%87%8D%E8%A6%81%E6%8F%90%E7%A4%BA)。
