### ISSUE TITLE
killing ike2 SA before new ike2 SA resulting in loss connection

### ISSUE THREAD

**Issue by AuthorShin** [hwdsl2/setup-ipsec-vpn#1168]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**

The problem is when it's rekeying every 24h it's "killing ike2 SA" before making "new ike2 SA" resulting in loss connection and therefore if you are in a video call or online video game you will get disconnected from their servers.
*I don't know if it's a libreswan problem or my configurations on server/client so I open this issue.

**To Reproduce**

Wait for the rekey and see for yourself :D

**Expected behavior**

Making "new ike2 SA" before "killing ike2 SA".

**Server (please complete the following information)**
- OS: Debian 11

**Client (please complete the following information)**
- Device: RB4011
- OS: RouterOS v6.49
- VPN mode: IKEv2

**Comment by hwdsl2** [comment]
@AuthorShin Hello! Thanks for reporting this issue. Generally speaking, commonly used VPN clients (such as Windows, macOS, iOS, Android, etc.) would initiate the rekey well in advance before the 24-hour IKE SA expiration. So this normally would not be an issue. Try setting the rekey interval on your VPN client to a value smaller than 24 hours, and enable rekey in case it's disabled. I see that you are using RouterOS (which I'm not familiar with), please refer to the RouterOS documentation.
