### ISSUE TITLE
Ubiquiti EdgeOS Authentication - no acceptable ecdsa/rsa-pss (almost there)

### ISSUE THREAD

**Issue by y3sh** [hwdsl2/setup-ipsec-vpn#1169]
I'm nearly able to authenticate IKEv2 using StrongSwan client (`Linux strongSwan U5.6.3/K4.9.79-UBNT`) from EdgeOS on Ubiquiti edgerouters, which I believe is a Debian variant by way of a fork from Vyatta/VyOS. Having read much of the docs and many issues here, I have nearly achieved connectivity but am stumped by issues similar to prior ones (see end). Though the solution there doesn't work here (`authby=sha1`).

My goal is of course to authenticate, but also to make a wiki doc with how to achieve an all-traffic vpn from these routers. Given the growing popularity of Ubiquiti routers along with many unresolved forum discussions on community.ui.com, reddit.com, serverfault.com, and others trying to figure out similar vpn client configs with little success. Hopefully this post can also be a reference point for others too.

Below is my work in progress enumerating all the steps I've taken (with the error at the end). For clarity, I am using an EdgeOS v2.0.9 router (Ubiquiti ER-4) and an AWS instance running Amazon Linux 2 AMI.  

### EdgeOS -> VPN Server Tunnel (IKEv2) Setup Steps

On AWS instance (let's say it has a static ip of `3.13.14.15`)

```shell
# Pull latest build as of May 20, 2022
wget https://get.vpnsetup.net -nv -O vpn.sh 

sudo \
VPN_IPSEC_PSK='foo-bar-key-here' \
VPN_USER='foo-user' \
VPN_PASSWORD='foo-bar-password-here' \
sh vpn.sh

# Extract the RSA X509 certs for the ipsec service, no password added
openssl pkcs12 -in vpnclient.p12 -cacerts -nokeys -out ikev2vpnca.cer
openssl pkcs12 -in vpnclient.p12 -clcerts -nokeys -out vpnclient.cer
openssl pkcs12 -in vpnclient.p12 -nocerts -nodes  -out vpnclient.key
```

Now copy the keys to local machine
```shell
scp ec2-user@3.13.14.15:vpnclient.cer ~/Desktop/.
scp ec2-user@3.13.14.15:ikev2vpnca.cer ~/Desktop/.
scp ec2-user@3.13.14.15:vpnclient.key ~/Desktop/.

# Test mobileconfig on mac/iphone first, works OK!
```

And copy the certs to the router
```shell
scp ~/Desktop/vpnclient.cer admin@10.0.0.1:/config/.
scp ~/Desktop/ikev2vpnca.cer admin@10.0.0.1:/config/.
scp ~/Desktop/vpnclient.key admin@10.0.0.1:/config/.
```

Now ssh into the router via `ssh admin@10.0.0.1`
```shell
cd /config

# restrict perms
sudo chown root.root ikev2vpnca.cer vpnclient.cer vpnclient.key
sudo chmod 600 ikev2vpnca.cer vpnclient.cer vpnclient.key

# Install certs
sudo mv ikev2vpnca.cer /etc/ipsec.d/cacerts/.
sudo mv vpnclient.cer /etc/ipsec.d/certs/.
sudo mv vpnclient.key /etc/ipsec.d/private/.
```

Make a new file `/config/ipsec.conf` and add the following. I'll make an attempt at trying to explain what I think these options mean.
```shell
# https://wiki.strongswan.org/projects/strongswan/wiki/ConnSection
# Left is local, right is remote
# 
# Always `sudo ipsec restart` after edits. 
conn vpnclient
 keyexchange=ikev2
 left=%any              # requests IP from remote
 leftid=vpnclient       # matches id in ipsec.secrets below
 leftsourceip=%config4  # requests tunnel IP
 leftsubnet=10.0.0.0/24 # restrict participant mask
 leftauth=pubkey        # uses certs
 leftcert=vpnclient.cer # the public key
 leftsendcert=always    # don't wait to be asked for it
 right=3.13.14.15       # remote pub net interface  
 rightid=3.13.14.15     # hardcoded for static ip
 rightsubnet=0.0.0.0/0  # wide open
 rightauth=pubkey       # uses certs
 rightdns=8.8.8.8,8.8.4.4 # google dns
 esp=aes128gcm16        # from https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md
 auto=start             # bring up immediately, otherwise you need to run `sudo ipsec up vpnclient`
 dpdaction=clear        # remove conns when they break
 dpddelay=10s           # how frequently to send keepalives
```

In the router's `/config/ipsec.secrets` put the following. `vpnclient` references the `leftid` above.
```shell
# https://wiki.strongswan.org/projects/strongswan/wiki/Ipsecsecrets
vpnclient : RSA vpnclient.key
```

Alter the EdgeOS's `/config/config.boot`
```shell
configure
set vpn ipsec allow-access-to-local-interface disable
set vpn ipsec auto-firewall-nat-exclude enable
set vpn ipsec include-ipsec-conf /config/ipsec.conf
set vpn ipsec include-ipsec-secrets /config/ipsec.secrets
commit ; save ; exit

# A reboot may be necessary if save didn't apply immediately, you'll know below if listcerts doesn't show your cert.
sudo reboot
```

Get ready to connect. Out on the AWS server, start watching logs in a different ssh session to debug.
```shell
ssh ec2-user@3.13.14.15

sudo tail /var/log/secure | grep --line-buffered pluto
```

Update ipsec, run, and test the connection
```shell
# Make sure ipsec pulls in new certs
sudo ipsec rereadall

# Check that the certs were loaded
sudo ipsec listcerts
sudo ipsec listcacerts

# Restart ipsec to pick up changes in ipsec.conf
sudo ipsec restart
sudo ipsec up vpnclient # not necessary if you have auto=start above
sudo ipsec statusall
```

---

### Where I am Currently Stuck

With all the above, the resulting error is no acceptable signature hash.

```diff
  proposal 1:IKE=AES_CBC_256-HMAC_SHA2_256-HMAC_SHA2_256_128-MODP2048 chosen from remote proposals
  sent IKE_SA_INIT reply {cipher=AES_CBC_256 integ=HMAC_SHA2_256_128 prf=HMAC_SHA2_256 group=MODP2048}
  processing decrypted IKE_AUTH request: SK{IDi,CERT,N,CERTREQ,AUTH,CP,SA,TSi,TSr,N,N,N,N}
  ignoring CERTREQ payload that is not ASN1
  switched to "ikev2-cp"[65] <my pub ip>

- authentication failed: no acceptable ECDSA/RSA-PSS ASN.1 signature hash proposal included for rsasig
- responding to IKE_AUTH message (ID 1) from <my pub ip>:1024 with encrypted notification AUTHENTICATION_FAILED
```

I have tried setting `authby=sha1`, however that flag seems invalid (from https://github.com/hwdsl2/setup-ipsec-vpn/issues/930)
```shell
Starting strongSwan 5.6.3 IPsec [starter]...
# bad value: authby=sha1
  bad argument value in conn 'vpnclient'
# ignored conn 'vpnclient' due to 1 parsing error
### 1 parsing error (0 fatal) ###
```

I have tried opening up `ike` and `esp` to more ciphers, however no change (from https://github.com/hwdsl2/setup-ipsec-vpn/issues/1122).
```shell
# Couldn't find docs on allowed values, maybe https://docs.strongswan.org/docs/5.9/config/IKEv2CipherSuites.html
# or https://github.com/nm-l2tp/NetworkManager-l2tp/blob/main/README.md
vi /config/ipsec.conf
  ...
  esp=aes128gcm16 # it seems the VPN server likes this value, otherwise I'll see `INVALID_KE_PAYLOAD requesting MODP2048`
  ike=aes256-sha2_256-modp2048,aes256-sha2_256-modp1536,aes256-sha2_256-modp1024,aes256-sha1-modp2048,aes256-sha1-modp1536,aes256-sha1-modp1024,aes256-sha1-ecp384,aes128-sha1-modp1024,aes128-sha1-ecp256,3des-sha1-modp2048,3des-sha1-modp1024
  ...
  :wq
sudo ipsec restart
sudo ipsec up vpnclient
...
```

### Where to from here?

Are there other auth strategies I could try to resolve the rsa pss issue? This actually is good, because Ubiquiti edgerouters don't have hardware support for `aes128gcm16` -- e.g. https://help.ui.com/hc/en-us/articles/115006567467-EdgeRouter-Hardware-Offloading.

For now I'm fine setting up the vpn on each computer as on-demand for these connections, which is fine because they are fast enough to still do over 500mbps throughput. 

---

### Resources

Docs

- https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#debian-1110-kernel

- https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#android

- https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#routeros

Related Issues

- https://github.com/hwdsl2/setup-ipsec-vpn/issues/1060

- https://github.com/hwdsl2/setup-ipsec-vpn/issues/1122

- https://github.com/hwdsl2/setup-ipsec-vpn/issues/1077

- https://github.com/hwdsl2/setup-ipsec-vpn/issues/930

External

- EdgeOS with AlgoVPN (doesn't work anymore) https://github.com/kiratp/algo/blob/master/docs/client-edgemax.md

  -  ipsec.conf with some ansible variables https://github.com/kiratp/algo/blob/master/roles/vpn/templates/ipsec.conf.j2

- Ubiquiti forums ikev2 for nordvpn (with 11k views) https://community.ui.com/questions/IPSec-to-NordVPN-IKEv2-EAP-MSCHAPv2/9b2615c4-960b-4563-afa2-aeeefee3fd48#answer/900f60de-fcad-45d5-a9e4-ccac764332a9

- Ubiquiti site-to-site VTI over IKEv2 https://help.ui.com/hc/en-us/articles/115012305347-EdgeRouter-Route-Based-Site-to-Site-VPN-to-Azure-VTI-over-IKEv2-IPsec-

- MARC Strong Swang boards https://marc.info/?l=strongswan-users&m=147066200415239&w=2

- Reddit ramblings, unhelpful mixed bag

  - https://www.reddit.com/r/Ubiquiti/comments/acsex2/ikev2ipsec_vpn_on_edgerouter/

  - https://www.reddit.com/r/Ubiquiti/comments/somr5s/edgerouter_ike2ipsec_nordvpn_client/

  - https://www.reddit.com/r/Ubiquiti/comments/93pgj1/edgerouter_x_setting_up_vpn/

  - https://www.reddit.com/r/meraki/comments/9kzyqu/use_ubiquiti_edgerouter_x_to_get_ikev2/

  - https://www.reddit.com/r/Ubiquiti/comments/cui1wj/edgerouter_4_mdnsrepeater_ipsec_sitetosite_vpn/

**Comment by hwdsl2** [comment]
@y3sh Hello! Thank you for the detailed issue description. The error you mentioned, `authentication failed: no acceptable ECDSA/RSA-PSS ASN.1 signature hash proposal included for rsasig`, can be fixed using `authby=rsa-sha1`. This option should be added on your VPN server, not on the client.

Edit `/etc/ipsec.d/ikev2.conf` on your VPN server. Append `authby=rsa-sha1` to the end of `conn ikev2-cp` section, indented by two spaces. Save the file and run `sudo service ipsec restart`.

Let us know if this fixes the issue.

**Comment by y3sh** [comment]
@COI-03 I just use the `diff` keyword after three back-ticks 
````text
```diff
    - minus is red
    + is green
```
````

**Comment by y3sh** [comment]
Thanks @hwdsl2 

It seems to be connected now, with `ipsec status` showing ` vpnclient[1]: ESTABLISHED 20 minutes ago ...`. On the server it throws the error:
```diff
"ikev2-cp"[18] x.x.x.x #30: established IKE SA; authenticated using RSA with SHA1 and peer certificate 'CN=vpnclient, O=IKEv2 VPN' issued by CA 'CN=IKEv2 VPN CA, O=IKEv2 VPN'
"ikev2-cp"[18] x.x.x.x #31: proposal 1:ESP=AES_GCM_C_128-DISABLED SPI=c4360aab chosen from remote proposals 1:ESP:ENCR=AES_GCM_C_128;ESN=DISABLED[first-match] 2:ESP:ENCR=AES_CBC_128;ENCR=AES_CBC_192;ENCR=AES_CBC_256;INTEG=HMAC_SHA2_256_128;INTEG=HMAC_SHA2_384_192;INTEG=HMAC_SHA2_512_256;INTEG=HMAC_SHA1_96;INTEG=AES_XCBC_96;ESN=DISABLED
"ikev2-cp"[18] x.x.x.x #31: established Child SA using #30; IPsec tunnel [0.0.0.0-255.255.255.255:0-65535 0] -> [192.168.43.10-192.168.43.10:0-65535 0] {ESPinUDP=>0xc4360aab <0x210769d5 xfrm=AES_GCM_16_128-NONE NATD=x.x.x.x:4500 DPD=active}
"ikev2-cp"[18] x.x.x.x #31: ESP traffic information: in=0B out=0B
"ikev2-cp"[18] x.x.x.x: kernel: xfrm XFRM_MSG_DELPOLICY for flow %discard(discard)(in) encountered unexpected policy
--ERROR: "ikev2-cp"[18] x.x.x.x #31: kernel: xfrm XFRM_MSG_DELPOLICYdelete(UNUSED) response for flow (in): No such file or directory (errno 2)
```

While this appears to be connected, I'm unable to route traffic through the tunnel. I'm not sure what the cause is yet -- likely I misconfigured a NAT or firewall policy. If there's something else obvious here I could try it, otherwise we can probably close the ticket as there is more investigation to do on my end.

**Comment by hwdsl2** [comment]
@y3sh Thanks for the update. The error you highlighted, `kernel: xfrm XFRM_MSG_DELPOLICYdelete(UNUSED) response for flow (in): No such file or directory (errno 2)`, is a known issue with Libreswan 4.6. It generally should not affect the functionality of the VPN, and is to be fixed in the upcoming Libreswan version. For the other issue you mentioned, "unable to route traffic through the tunnel", it could be your firewall policy or IPTables issues on the VPN server (less likely). Please investigate further yourself.

**Comment by y3sh** [comment]
@hwdsl2 I was able to get the error resolved by changing `left=%any` to have my WAN IP instead of `%any`.

A couple new issues remain though, am only able to receive and rather slowly. Both I feel are still probably out of scope of this repo though.
