### ISSUE TITLE
Failure when deploy VM in Azure

### ISSUE THREAD

**Issue by ruijie-shi** [hwdsl2/setup-ipsec-vpn#1170]
**Describe the issue**
Failure when deploy VM in Azure

**To Reproduce**

1. Click deploy to azure
2. Choose West US 2 or any region, then deploy. 
3. Validation error as above.

**Expected behavior**
It should deploy resources successfully.

**Logs**
The template deployment failed with error: 'The resource with id: '/subscriptions/4a1bd0ed-03d2-4365-8736-8a64a9825e49/resourceGroups/USAVPN/providers/Microsoft.Compute/virtualMachines/vpnserver' failed validation with message: 'The requested size for resource '/subscriptions/4a1bd0ed-03d2-4365-8736-8a64a9825e49/resourceGroups/USAVPN/providers/Microsoft.Compute/virtualMachines/vpnserver' is currently not available in location 'westus2' zones '' for subscription '4a1bd0ed-03d2-4365-8736-8a64a9825e49'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details.'.'. (Code: InvalidTemplateDeployment)
Troubleshooting Options

**Server (please complete the following information)**
- OS: ubuntu22.04, 
- VM size: Standard_B1s
- Hosting provider (if applicable): Azure

**Comment by ruijie-shi** [comment]
Try other region like JapanEast also fail, which I just set up successfully a week ago.

**Comment by hwdsl2** [comment]
@ruijie-shi Hello! Thank you for reporting this issue. I tried but was not able to reproduce the issue you mentioned. I tested by deploying a new VM using the template in this project, in the West US 2 region with VM size Standard_B1s and Ubuntu 22.04. The deployment was successful.

This is most likely an issue with your Azure subscription, which prevents creation of certain VMs. To troubleshoot further, please refer to:
https://docs.microsoft.com/en-us/azure/azure-resource-manager/troubleshooting/error-sku-not-available?tabs=azure-portal
