### ISSUE TITLE
This script failed to install on OpenVZ Server, please add support for OpenVZ

### ISSUE THREAD

**Issue by VPN-V2Ray** [hwdsl2/setup-ipsec-vpn#1173]
This script failed to install on OpenVZ server, please add support for OpenVZ

**Comment by hwdsl2** [comment]
@VPN-V2Ray Hello! This project does not support OpenVZ VPS, because IPsec kernel support may not be available inside OpenVZ containers. You may instead try OpenVPN:

https://github.com/hwdsl2/openvpn-install
