### ISSUE TITLE
 Failed to fetch http://ftp.estpak.ee/ubuntu/pool/main/s/systemd/libsystemd-dev_245.4-4ubuntu3.16_amd64.deb  404  Not Found

### ISSUE THREAD

**Issue by Armanitos94** [hwdsl2/setup-ipsec-vpn#1174]
Failed to fetch http://ftp.estpak.ee/ubuntu/pool/main/s/systemd/libsystemd-dev_245.4-4ubuntu3.16_amd64.deb  404  Not Found

**Comment by hwdsl2** [comment]
@Armanitos94 Hello! This seems to be a transient error with your `apt` repositories. Try: `apt-get clean`, then re-run the VPN setup script.

**Comment by Armanitos94** [comment]
Hello @hwdsl2 ! Thanks for the answer! I ran this command but the error is still happening.
Even if you follow this link (http://ftp.estpak.ee/ubuntu/pool/main/s/systemd/libsystemd-dev_245.4-4ubuntu3.16_amd64.deb), the query returns not found

**Comment by Armanitos94** [comment]
Updated Ubuntu from 20.04 --> 22.04 and it worked. Thank u
