### ISSUE TITLE
用脚本装好VPN后，为什么会把系统的防火墙给关了？

### ISSUE THREAD

**Issue by wlc743859910** [hwdsl2/setup-ipsec-vpn#1176]
服务器是腾讯云的香港服务器，服务器控制台安全组里面打开了ALL全部端口，用脚本安装完VPN后，服务器的系统防火墙被关闭了。用命令打开防火墙后 VPN却又死活都连接不上。。。系统防火墙的500跟4500端口也是打开的，还是连不上。不知道什么原因

**Comment by hwdsl2** [comment]
@wlc743859910 你好！VPN 脚本不会关闭你的服务器的系统防火墙。应该是别的原因。请检查 VPN 日志是否有错误：
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E6%A3%80%E6%9F%A5%E6%97%A5%E5%BF%97%E5%8F%8A-vpn-%E7%8A%B6%E6%80%81

如果尝试连接之后没有新的日志，说明 VPN 服务器未收到连接请求。如果你的服务器有外部防火墙，需要打开 UDP 500 和 4500 端口。如果你有更多信息，可以继续在这里回复。
