### ISSUE TITLE
IPv6 feature

### ISSUE THREAD

**Issue by renlips** [hwdsl2/setup-ipsec-vpn#1177]
**Checklist**

- [V] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [V] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [V] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [V] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [V] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [V] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
IPv6 feature (6to4):
I have VPS(server) with IPv6 and IPv4. My cellphone (VPN client) has only IPv4. Could you provide a possibility to acquire IPv6 address from the VPN server to use it within the internet.
Or, if your VPN client has both addressed (IPv4 and IPv6).

**Is your enhancement request related to a problem? Please describe.**
None

**Additional context**
None

**Comment by hwdsl2** [comment]
Thank you @letoams for the response. @renlips This feature is not yet available in the current Librewan version. For your second use case, you may try [OpenVPN](https://github.com/hwdsl2/openvpn-install) instead.
