### ISSUE TITLE
IPsec not working

### ISSUE THREAD

**Issue by eddyc05** [hwdsl2/setup-ipsec-vpn#118]
wondering if someone can help me out with ipsec connection issue. i've recently moved to a new building next door, i'm using the same ISP provider (China Telecom) however ipsec has failed to work after moving to my new apartment (router is the same). The VPN tunnel is successfully connected however there's no internet. I know the issue isn't on the server end since IPSEC works fine when i connect to the server through 4G on my iphone. Where should i start in terms of ironing out the issue?

**Comment by eddyc05** [comment]
VPN Log (4G connection):
![4g](https://cloud.githubusercontent.com/assets/5252279/23701903/d718d4b6-0433-11e7-924c-e983bc91b5ac.png)

VPN Log (WIFI connection):
![wifi](https://cloud.githubusercontent.com/assets/5252279/23701917/e71d1d18-0433-11e7-88f8-04ada0fcdfd5.png)

**Comment by hwdsl2** [comment]
@eddyc05 Your logs all look fine. Try the following steps:

1. Reboot both the VPN server and your VPN client, then try connecting again.
1. Rebuild your server using the latest version of VPN setup scripts, after backing up any important files.
1. Try an alternative solution. See [1] for a list.

Good luck!

[1] https://github.com/hwdsl2/setup-ipsec-vpn#see-also
