### ISSUE TITLE
关于IKEv2 模式：为 VPN 客户端分配静态 IP问题

### ISSUE THREAD

**Issue by 15956802724** [hwdsl2/setup-ipsec-vpn#1183]
![image](https://user-images.githubusercontent.com/31676113/174216008-33a5dcb8-c2c3-4152-8ed3-d532784868b0.png)

ip池设置为100-250时,静态设置无效
测试设置99-250,静态才可以生效

如果必须设置100-250的话,静态必须这样设置

静态要设置为192.168.43.10的话
192.168.43.10-192.168.43.11

非专业测试

**Comment by hwdsl2** [comment]
@15956802724 你好！感谢你的反馈。我测试过了，无法重现此问题。IP 池设置为 `192.168.43.100-192.168.43.250` 时，是可以将静态设置为 `192.168.43.10-192.168.43.10` 的。可能是你的测试中某个环节出现了问题。
