### ISSUE TITLE
Android & iOS Certificate Password

### ISSUE THREAD

**Issue by ddubnyk** [hwdsl2/setup-ipsec-vpn#1184]
**Server
- OS: [Debian 11]
- Hosting provider (if applicable): [Self Hosted]

**Client
- Device: [e.g. iPhone 13 Pro, OnePlus 6T, OnePlus 8 Pro]
- OS: [e.g. iOS 15, Android 12]
- VPN mode: [IPsec IKEv2]

**Additional context**
When importing the certificate into iOS and Android, it is requesting a password. I have not specified a password for the certificate anywhere and it is saying incorrect password, and will not import the certificate.

When i do the same thing on my Linux machine, when it requests for the password when i convert the certificate, i don't provide a password and it works so i know for a fact i never provided a password and don't need one. I have uninstalled and reinstalled the vpn and the same thing happens. Am i simply missing something? 

I have read over the documentation and read me multiple times and have found nothing about a certificate password or even how to set one so I'm quite sure there shouldn't be one after running the script. I apologize if it does say.

**Comment by hwdsl2** [comment]
@ddubnyk Hello! There is an option (when running the VPN setup script) to protect IKEv2 client config files with a password. See Installation section in the README, expand "Advanced users can optionally customize IKEv2 options". Quote:
> By default, no password is required when importing IKEv2 client configuration. You can choose to protect client config files using a random password.
> sudo VPN_PROTECT_CONFIG=yes sh vpn.sh

Perhaps you enabled that option when setting up the VPN? If you did not, and the IKEv2 script's output does not contain an import password, then your device should not request a password when importing. Please follow the instructions step-by-step for Android here:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#android

And for iOS here:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ios

**Comment by ddubnyk** [comment]
PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

You know i completely forgot i am running testing version of Debian. So maybe there is a bug in testing version.

I did look after running the script at the output, and there was nothing about a certificate password. The IPSEC PSK, VPN username, and VPN password show. But no certificate password.

However when i follow the import instructions to import to my Linux machine i do not require a password to convert the certificate so it's weird as to why Android and iOS think there is one. Mind you, those technically are different output certs. But let me know if maybe you can reproduce or if you have any other ideas.

**Comment by hwdsl2** [comment]
@ddubnyk Thanks for the update. This is an issue with newer NSS versions on certain Linux distributions. The .p12 files exported by `pk12util` in these OS cannot be imported into Windows, iOS and Android devices, with the incorrect password error. Additional processing using e.g. `openssl` is required as a workaround.

For your use case, the fix is simple. Edit /opt/src/ikev2.sh and find the highlighted line from here:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/d36c435c95ed12df474d823960de840cfd452d4c/extras/ikev2setup.sh#L767

Replace `"$os_type" = "ubuntu"` with `"$os_type" = "debian"`. Save the file and exit the editor. Then run `sudo ikev2.sh` to re-export the client configuration.

Let us know if this works for you.

**Comment by ddubnyk** [comment]
Thank you very much! Yes that worked for me. Much appreciated.
