### ISSUE TITLE
UFW rules

### ISSUE THREAD

**Issue by Joy096** [hwdsl2/setup-ipsec-vpn#1186]
I use ipsec vpn on Ubuntu 20.04 of Oracle Cloud. I prefer UFW instead of IPTABLES. When I use IPTABLES the VPN connection works normally, but when I use UFW I cannot connect to the VPN. Which ports should I open in UFW and which rules should I add to /etc/ufw/before.rules for correct working? Thx.

Input
> ip route show default

Output
> default via 10.0.0.1 dev ens3

**Comment by hwdsl2** [comment]
@Joy096 Hello! UFW is not currently supported in this project. You'll need to open UDP port 500 and UDP port 4500, and allow UDP port 1701 traffic with IPsec policy only. In addition, you'll need to add IPTables FORWARD and NAT rules. Unfortunately, I'm not sure about the exact rules you'll add to the UFW configuration, but you can give it a try yourself.

https://github.com/hwdsl2/setup-ipsec-vpn/blob/e5c630ce4e16cee59856badf4f682f7287a32fad/vpnsetup_ubuntu.sh#L505-L543

**Comment by Joy096** [comment]
Thx, I found a solution. I put the next lines to /etc/ufw/before.rules:

before *filter
```
*nat
-A POSTROUTING -s 192.168.42.0/24 -o ens3 -j MASQUERADE
-A POSTROUTING -s 192.168.43.0/24 -o ens3 -m policy --dir out --pol none -j MASQUERADE
COMMIT
```

**Comment by hwdsl2** [comment]
@Joy096 Thanks for sharing!
