### ISSUE TITLE
android手机用L2TP/IPSec PSK模式连接vpn成功，但是手机无法打开网页！

### ISSUE THREAD

**Issue by cegod** [hwdsl2/setup-ipsec-vpn#1187]
@hwdsl2 首先，非常感谢您的贡献，一键安装vpn非常好用。
我使用您的脚本搭建了vpn服务器，win7、win10、macos环境都能够正常使用，但是Android手机连接成功后，不能打开网页，以为是dns问题，调整dns后问题依旧，查看故障排查，使用([https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#android-mtumss-%E9%97%AE%E9%A2%98]) 的方法依旧不行，后来将/etc/ppp/option.xl2tpd文件中mtu值由1280改为1500，问题得以解决。
请教您，这样解决是否合理，期待您的回复！

**Comment by hwdsl2** [comment]
@cegod 你好！感谢你的反馈。你所说的更改 /etc/ppp/options.xl2tpd 中的 MTU 值是一个可行的解决方案，对于特定的用例可能有效。一般来说，较小的 MTU 值可以提高对网络的兼容性，但某些用例可能需要调整该值。另外你提供的链接中的解决方案主要是针对 IPsec/XAuth ("Cisco IPsec") 和 IKEv2 模式。

**Comment by cegod** [comment]
@hwdsl2 您好，感谢您的回复！针对我的问题，您有没有更加适合的解决办法？！

**Comment by hwdsl2** [comment]
@cegod 你好！对于你的用例，我这里没有更佳的解决办法。如上所说，修改 MTU 值是一个可行的方案。

**Comment by cegod** [comment]
@hwdsl2 您好，我再请教一个问题，您的脚本部署环境是CentOS 7+，为什么没有采用firewall防火墙，而是使用了iptables？
我之前配置了l2tp/ipsec就是用的firewall防火墙，但是没有成功。

**Comment by cegod** [comment]
@hwdsl2 您好，我再请教一个问题，您的脚本部署环境是CentOS 7+，为什么没有采用firewall防火墙，而是使用了iptables？
我之前配置了l2tp/ipsec就是用的firewall防火墙，但是没有成功。

**Comment by hwdsl2** [comment]
@cegod 目前本项目在 CentOS 等系统下不支持 firewalld 防火墙，因为某些 VPN 需要的防火墙规则在 firewalld 下比较难配置。

**Comment by cegod** [comment]
@hwdsl2 感谢您的回复，我受益匪浅，祝好！
