### ISSUE TITLE
Running this script on top of new Algo server

### ISSUE THREAD

**Issue by git-sgmoore** [hwdsl2/setup-ipsec-vpn#119]
I have a chromebook and Algo does not work for me because I must use L2TP. So, I setup a new server using the following repo "https://github.com/trailofbits/algo". I logged into that new server and ran the script from your repo. This gave me the information to use L2TP with my chromebook. I chose this option because of Algo's additonal OS hardening and etc.. However, I am unsure of any vulnerabilities I have created, besides using L2TP in general, by doing this.

Could anyone let me know running this script on top of algo is a bad idea?

**Comment by hwdsl2** [comment]
@git-sgmoore Hello! As far as I know, the VPN setup scripts in this repo does not open any unnecessary port in IPTables, besides those required for the VPN. Therefore IMHO it should not affect your server's security in a negative way. But make sure that you use very strong VPN credentials (such as the IPsec PSK and password).

**Comment by SquirrelCoder** [comment]
@git-sgmoore hey man,

how did you get "ipsec" VPN with algo deployed on the same server?

**Comment by git-sgmoore** [comment]
SquirrelCoder,

That's a good question. I'm sure there is a way, but I haven't figured it out yet. I have two $5/month servers. One server is just Algo and can be used with iOS for example. The other is Algo along with the IPSec script and I only use IPSec through it.

If you figure out how to do both on the same server, please let me know!
