### ISSUE TITLE
Cert Password

### ISSUE THREAD

**Issue by wekalati** [hwdsl2/setup-ipsec-vpn#1192]
**Checklist**

- [ ] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [ ] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [ ] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [ ] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [ ] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ ] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**

**To Reproduce**

1. ...
2. ...

**Expected behavior**

**Logs**
[Check logs and VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status), and add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- OS: [e.g. Debian 11]
- Hosting provider (if applicable): [e.g. GCP, AWS]

**Client (please complete the following information)**
- Device: [e.g. iPhone 12]
- OS: [e.g. iOS 15]
- VPN mode: [IPsec/L2TP, IPsec/XAuth ("Cisco IPsec") or IKEv2]

**Additional context**

Hello, hope you are doing well...
I noticed that scripts leaves the cert password empty.
No I use blackberry, on blackberry it will ask me for a password when I try to import the cert. and I can't leave the password field blank! otherwise the "OK" button will be greyed out and I won't be able to import the cert!
How can I set a password for cert?

**Comment by hwdsl2** [comment]
@wekalati Hello! BlackBerry is not a supported VPN client for this project. With that said, you can choose to protect client config files using a random password like this:

```
sudo VPN_PROTECT_CONFIG=yes ikev2.sh --addclient [client name]
```

Replace `[client name]` in the command above with the name of your new IKEv2 client. A random password will be generated to protect the config files of the new IKEv2 client, and will be displayed.
