### ISSUE TITLE
Are there plans to support IPv6, it doesn't seem to work with IPv6 now

### ISSUE THREAD

**Issue by roninmsn** [hwdsl2/setup-ipsec-vpn#1193]
Thanks for the script!

Android 12+ only supports IKEV2.

My public IP only supports IPv6, is there a way now?

**Comment by hwdsl2** [comment]
@roninmsn Hello! Currently there is no plan to support IPv6 in this project. However, you can instead try [OpenVPN](https://github.com/hwdsl2/openvpn-install) and/or [WireGuard](https://github.com/hwdsl2/wireguard-install) which support IPv6.

**Comment by roninmsn** [comment]
Thanks!
Tried, all systems can not be used. "OpenVPN Connect" also messed up the OS(Win11) network. i reinstalled the system.

**Comment by letoams** [comment]
On Tue, 5 Jul 2022, Lin Song wrote:

> @roninmsn Hello! Currently there is no plan to support IPv6 in this project. However, you can instead try OpenVPN and/or
> WireGuard which support IPv6.

libreswan should be adding IPv6 addresspool support in the next version
(4.8)

Paul
