### ISSUE TITLE
Why is my connection timing out？😭

### ISSUE THREAD

**Issue by monk-h** [hwdsl2/setup-ipsec-vpn#1195]
**I used aws ec2 ubuntu 18.04.But when I used the vpnclient.mobileconfig,it doesn't work on my iOS and macOS**

```
================================================

IPsec VPN server is now ready for use!

Connect to your new VPN with these details:

Server IP: *******
IPsec PSK: *******
Username: ******
Password: ******

Write these down. You'll need them to connect!

VPN client setup: https://vpnsetup.net/clients

================================================

================================================

IKEv2 setup successful. Details for IKEv2 mode:

VPN server address: *******
VPN client name: vpnclient

Client configuration is available at:
/home/ubuntu/vpnclient.p12 (for Windows & Linux)
/home/ubuntu/vpnclient.sswan (for Android)
/home/ubuntu/vpnclient.mobileconfig (for iOS & macOS)

Next steps: Configure IKEv2 clients. See:
https://vpnsetup.net/clients

================================================
```

**Comment by hwdsl2** [comment]
@monk-h Hello! For servers with an external firewall (e.g. AWS), you will need to open UDP ports 500 and 4500 for the VPN. Please refer to the documentation:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-security-groups.html

**Comment by monk-h** [comment]
wow it's worked.👍👍👍 

> @monk-h Hello! For servers with an external firewall (e.g. AWS), you will need to open UDP ports 500 and 4500 for the VPN. Please refer to the documentation:
> https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-security-groups.html

wow it's worked.👍👍👍
