### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Richard-Wolffer** [hwdsl2/setup-ipsec-vpn#1196]
I want to know how to set split tunneling with the l2tp-ipsec VPN on Android. Thanks.

**Comment by hwdsl2** [comment]
@Richard-Wolffer Hello! Please refer to:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#split-tunneling

Note that split tunneling has some limitations and is not supported by all VPN clients. For this project, you cannot use split tunneling with IPsec/L2TP mode, only with IPsec/XAuth ("Cisco IPsec") and IKEv2 modes.
