### ISSUE TITLE
请问客户端能访问服务端默认网卡的ip和端口，但vpn的内网不行

### ISSUE THREAD

**Issue by jeasonlyo** [hwdsl2/setup-ipsec-vpn#1197]
服务器：阿里云 centos，
客户端：win11，
问题：使用[IPsec/L2TP]  和 [IKEv2] 两种模式都是一样，vpn 内网无法ping 通也不能访问端口
![image](https://user-images.githubusercontent.com/37092708/180823099-14b93ea3-731d-49dc-88ce-164fcd2846d8.png)
![image](https://user-images.githubusercontent.com/37092708/180823161-8a2b0b61-cef1-474f-ad3c-c211e8e9bc61.png)
请问这正常吗

**Comment by hwdsl2** [comment]
@jeasonlyo 你好！这个是正常的，VPN 的内网默认不允许 Internet 上的主机访问，以提高安全性。更多信息请参见 [VPN 内网 IP 和流量](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#vpn-%E5%86%85%E7%BD%91-ip-%E5%92%8C%E6%B5%81%E9%87%8F) 以及 [访问 VPN 服务器的网段](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#%E8%AE%BF%E9%97%AE-vpn-%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9A%84%E7%BD%91%E6%AE%B5)。
