### ISSUE TITLE
[Question] Creating Windows Connection

### ISSUE THREAD

**Issue by aw1875** [hwdsl2/setup-ipsec-vpn#1198]
I've been attempting to create a Windows connection manually with C++ and I've been having some issues/have some questions. From my understanding based on the documentation and the automatic install batch file, the Ras Entry we are creating should be using Machine Certificates as the Auth type. I've been having issues doing this in C++ so first I wanted to ask if anyone can see any issues with my code:

```c++
RASENTRY rasEntry;
RASDEVINFO devInfo;
memset(&rasEntry, 0, sizeof(rasEntry));
rasEntry.dwSize = offsetof(RASENTRY, ipv6addr);

wcscpy_s(rasEntry.szLocalPhoneNumber, localConnection);
wcscpy_s(rasEntry.szDeviceName, CONNECTION_NAME);
wcscpy_s(rasEntry.szDeviceType, 4, RASDT_Vpn);

// My understanding is this is what should change that setting
rasEntry.dwfOptions2 |= RASEO2_RequireMachineCertificates; 

// Rest of setup
rasEntry.dwFramingProtocol = RASFP_Ppp;
rasEntry.dwEncryptionType = ET_Require;
rasEntry.dwType = RASET_Vpn;
rasEntry.dwVpnStrategy = VS_Ikev2Only;
rasEntry.dwfNetProtocols = RASNP_Ip | RASNP_Ipv6;
rasEntry.dwRedialCount = 3;
rasEntry.dwRedialPause = 60;
rasEntry.dwIPv4InterfaceMetric = 1;
rasEntry.dwIPv6InterfaceMetric = 1;
```

Second, if I'm not doing anything wrong here is there another form of authentication that would be possible to use (i.e., MSCAP)?

Thanks in advance!

Edit: I guess I'm just tired and realized my mistake with the code. The question part still stands though.

**Comment by hwdsl2** [comment]
@aw1875 Hello! Unfortunately I am not sure about creating a Windows connection manually with C++, so I can't help you with this. You may want to instead ask on e.g. the [Libreswan mailing list](https://lists.libreswan.org/mailman/listinfo/swan).

**Comment by aw1875** [comment]
@hwdsl2 I actually found my mistake shortly after posting that, I forgot to make my dwfOptions2 |= instead of =. However, my second question about connecting without using p12 certificate is more of the question I wanted to know an answer for. I currently have setup connections on 2 separate servers and want my client to be able to connect to either. However, the only solution for that is installing the certificate for each server individually which will be a little big of a pain if I add more connections.
