### ISSUE TITLE
IPsec/L2TP Windows 11 client behind masquerade do not connect

### ISSUE THREAD

**Issue by muhlpachr** [hwdsl2/setup-ipsec-vpn#1199]
I have MSW11 IPsec/L2TP client behind masquerade.

I am able to connect W11 client only sometimes after sucessfull connect of RouterOS client from same LAN.

Attached are Pluto logs for ok and failed connection of W11 client.

How can I modify Pluto config to stabilize connection please ?
It seams from log there are more attempts - why is that ?

For failed attempt RasClient in MSW11 emit event:
The user MICHAL-NUC\michal dialed a connection named vpn which has failed. The error code returned on failure is 809.

[pluto_ok.log](https://github.com/hwdsl2/setup-ipsec-vpn/files/9185258/pluto_ok.log)
[pluto_failed.log](https://github.com/hwdsl2/setup-ipsec-vpn/files/9185263/pluto_failed.log)

Thank you.

Regards,
Michal

**Comment by hwdsl2** [comment]
@muhlpachr Hello! If the VPN client is behind restrictive NAT (e.g. the "masquerade" you mentioned), it can interfere with the VPN connection process between the VPN client and VPN server (the server normally use UDP ports 500 and 4500 for IPsec, but the client could use random ports on its side), for example, the client can't receive the server's response, or vice versa. Error 809 could be a symptom of such issues. I've seen these errors in Windows virtual machines behind restrictive NAT networks on certain virtualization platforms. Solutions may require proper configuration of the NAT network to allow VPN connections to establish.

For your particular use case, which involves RouterOS and Windows 11 clients from the same LAN: On RouterOS you can specify the IP subnet that should go through the VPN, which could mean that your Windows 11 client on the same LAN can have its traffic go through the VPN automatically without connecting by itself. See:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#routeros

**Comment by muhlpachr** [comment]
Hi @hwdsl2
As you can see from logs, NAT is detected and handled by NAT-Traversal: Result using RFC 3947 (NAT-Traversal) in Pluto.
As you can see from logs, traffic from W11 client reach Pluto without interfere.
But Pluto is able to establish IPsec IKEv1 phase 2 only after some internal cleanup - it seams like timing rare condition.

Random src UDP ports ISAKMP and ESP are not trouble, RouterOS IPsec/L2TP client connects everytime with various src ports.

In my case masquerading is done by LTE operator network, so it is not under my control and I can not get subnet without masquerade.

My intention is not to use IKEv2 as you recomend, but IPsec/L2TP (IKEv1 is ivolved) because I need way for MSW11 VPN setup without Admin rights on MSW11.

Thank you.

**Comment by muhlpachr** [comment]
BTW there are 5x instancies of IKEv1 phase 1 established in OK log with W11 client before IKEv1 phase 2 gets through.
That is not healthy and stable ...

**Comment by hwdsl2** [comment]
@muhlpachr Thank you for the update. Unfortunately, I am not sure how to make it work for your particular use case. I would suggest that you ask on the [Libreswan users mailing list](https://github.com/libreswan/libreswan) or open an issue in the [GitHub repository](https://github.com/libreswan/libreswan).
