### ISSUE TITLE
This script does NOT support OpenVZ VPS.

### ISSUE THREAD

**Issue by peiweichen** [hwdsl2/setup-ipsec-vpn#12]
So what kind of server should I choose , plz give a hint

**Comment by hwdsl2** [comment]
@Peiwei You can use the VPN scripts on any VPS (or dedicated sever) except for OpenVZ VPS. For example, a VPS server based on KVM or Xen virtualization would be fine for this purpose.

If you are unsure about which virtualization type your VPS provider uses, please contact them directly and ask.
