### ISSUE TITLE
I hope you can add IPv6 support

### ISSUE THREAD

**Issue by MorganHXu** [hwdsl2/setup-ipsec-vpn#120]
I like your one-key deployment experience of your script.
Most VPS vendor support both IPv4 and IPv6, so can you update the script to make it support IPv6 traffic forwarding? most ISP in China and US can only support IPv4, so VPS is a good way for us to access IPv6.
I know SoftEther can do that by default.
Thanks.

**Comment by luca-exe** [comment]
Well that would be great.

Am 14.03.2017 07:10 schrieb "MorganHXu" <notifications@github.com>:

**Comment by luca-exe** [comment]
Well that would be great!

**Comment by hwdsl2** [comment]
Sorry, not planned. See #74 for an alternative.
