### ISSUE TITLE
[Question] Domain Restrictions

### ISSUE THREAD

**Issue by yejune** [hwdsl2/setup-ipsec-vpn#1201]
How can I send traffic with VPN only for specific domains?

**Comment by hwdsl2** [comment]
@yejune Hello! This is not supported in this project. However, you can send traffic for specific destination subnet(s) through the VPN tunnel. See [split tunneling](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#split-tunneling).
