### ISSUE TITLE
执行ikev2.sh有问题

### ISSUE THREAD

**Issue by warrenhoo** [hwdsl2/setup-ipsec-vpn#1203]
已经执行vpn.sh安装完毕，并且在家目录下生成了三个配置文件，但是Ip地址是公网Ip想换成域名，执行VPN_DNS_NAME='xxxx.xyz' ikev2.sh --auto，提示：
Error: Invalid parameter '--auto'. IKEv2 is already set up on this server.
       To manage VPN clients, re-run this script without '--auto'.

执行： ikev2.sh ，没有更换域名的选项

**Comment by hwdsl2** [comment]
@warrenhoo 你好！请参见 [更改 IKEv2 服务器地址](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#%E6%9B%B4%E6%94%B9-ikev2-%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%9C%B0%E5%9D%80)。
