### ISSUE TITLE
修改/etc/ipsec.d/ikev2.conf ，导致链接策略错误问题

### ISSUE THREAD

**Issue by dd-ping** [hwdsl2/setup-ipsec-vpn#1207]
你好，我使用自动脚本 全程自动部署之后 ， 我再该文件下修改了网段之后win10 再次链接 vpn 显示链接策略错误，仅仅是修改 192.168.44.xxx - 192.168.44.250  , xxx 部分，并重启了ipsec

**Comment by hwdsl2** [comment]
@dd-ping 你好！你需要编辑 VPN 服务器上的 `/etc/ipsec.conf`，将 `rightaddresspool=192.168.43.10-192.168.43.250` 替换为与 `/etc/ipsec.d/ikev2.conf` 中相同的值。然后重启 IPsec 服务。这两个文件中的 `rightaddresspool` 必须一致。请参见：
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#vpn-%E5%86%85%E7%BD%91-ip-%E5%92%8C%E6%B5%81%E9%87%8F

另外你的 IPTables 规则可能需要修改，因为指定了自定义子网。或者，你可以 [卸载 VPN](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/uninstall-zh.md)，然后指定自定义子网并重新安装。请参见：
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#%E8%87%AA%E5%AE%9A%E4%B9%89-vpn-%E5%AD%90%E7%BD%91

**Comment by dd-ping** [comment]
你好 ， 服务器使用的是centos7，(win10)两边的客户端链接了上vpn 并且分配到了地址，也能够相互 ping通 ，但是客户端之间的软件无法通信？

**Comment by hwdsl2** [comment]
@dd-ping 这个可能是你的客户端防火墙阻止了相关流量。
