### ISSUE TITLE
what does the IPSec ID mean

### ISSUE THREAD

**Issue by 95uxin** [hwdsl2/setup-ipsec-vpn#121]
I try to connect cisco ipsec on my linux.
[The Cisco VPNC client is available in the vpnc package (SPM).](https://help.ubuntu.com/community/VPNClient#VPNC)
here is the configure file.
```
IPSec gateway <host>
IPSec ID <group username>
IPSec secret <group password>
Xauth username <username>
Xauth password <password>
```
so , what does the` ipsec id(group username)` mean?
I try to use the name as same as `Xauth username <username>` but failed.

**Comment by hwdsl2** [comment]
@95uxin It is the group name in aggressive mode. See #70. Please read all comments in that issue.

Alternatively you can follow the Linux instructions at https://git.io/vpnclients for IPsec/L2TP.

**Comment by 95uxin** [comment]
Thanks for quick reply.
Seems Same problem with that gay in #70 . 
after adding  these lines after`cisco-unity=yes` and restart the vps
```
rightid=@[mygroup1]
 aggrmode=yes
```

shows
```
 packet from 223.104.109.28:57595: IKEv1 Aggressive Mode with PSK is vulnerable to dictionary attacks and is cracked on large scale by TLA's
pluto[1088]: "xauth-psk"[1] 223.104.109.28 #11: Aggressive mode peer ID is ID_KEY_ID: '@#0x77757573696e2e636f6d'
pluto[1088]: "xauth-psk"[1] 223.104.109.28 #11: responding to Aggressive Mode, state #11, connection "xauth-psk"[1] 223.104.109.28 from 223.104.109.28
pluto[1088]: "xauth-psk"[1] 223.104.109.28 #11: transition from state STATE_AGGR_R0 to state STATE_AGGR_R1
 pluto[1088]: "xauth-psk"[1] 223.104.109.28 #11: STATE_AGGR_R1: sent AR1, expecting AI2
 pluto[1088]: "xauth-psk"[1] 223.104.109.28 #11: byte 2 of ISAKMP Hash Payload should have been zero, but was not (ignored)
 pluto[1088]: "xauth-psk"[1] 223.104.109.28 #11: length of ISAKMP Hash Payload is larger than can fit
 pluto[1088]: "xauth-psk"[1] 223.104.109.28 #11: malformed payload in packet

```

Should I add password for the  group i added  in `ipsec.secrets` ?
Could you give me an example group pwd adding?
thx!

**Comment by hwdsl2** [comment]
@95uxin You should use your IPsec PSK as the "IPSec secret <group password>":

```
IPSec gateway: YOUR_VPN_SERVER_IP
IPSec ID: mygroup1
IPSec secret: YOUR_VPN_IPSEC_PSK
Xauth username: YOUR_VPN_USERNAME
Xauth password: YOUR_VPN_PASSWORD
```

**Comment by lance-wr** [comment]
1
