### ISSUE TITLE
ikev2.sh script on Debian 11

### ISSUE THREAD

**Issue by SebastianGogoasa** [hwdsl2/setup-ipsec-vpn#1211]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**
`ikev2.sh --[options] [client]` command generates an error while executed on Debian 11.

**To Reproduce**

1. `ikev2.sh --[options] [client]`

**Expected behavior**
To not show an error about not finding `/etc/redhat-release` file, the script has been executed on Debian 11 and it's expected that `/etc/redhat-release` to not be present there.

**Logs**
- Not required

**Server (please complete the following information)**
- OS: Debian 11
- Hosting provider (if applicable): Not applicable

**Client (please complete the following information)**
- Device: -
- OS: -
- VPN mode: -

**Additional context**
-

**Comment by hwdsl2** [comment]
@SebastianGogoasa Thanks for reporting! I'll push a fix for this now.

**Comment by hwdsl2** [comment]
@SebastianGogoasa To update the IKEv2 script on your VPN server, see:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#update-ikev2-helper-script
