### ISSUE TITLE
ikev2.sh Script

### ISSUE THREAD

**Issue by SebastianGogoasa** [hwdsl2/setup-ipsec-vpn#1212]
**Checklist**

- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [x] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [X] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
Hello Lin,

Yesterday I've passed you that Bug in regards to Debian 11 where the `ikev2.sh` was looking for `release` file.
The script was working perfectly fine on Debian 11 - which is my main OS for many reasons - if a dummy file would be placed to trick the script to go over that error - that's what I did.

Please revert back that change and include Debian 11 as well, all that's needed it's a check  for that file, a boolean in regards to the file presence.

**Is your enhancement request related to a problem? Please describe.**
-

**Additional context**
-

**Comment by hwdsl2** [comment]
@SebastianGogoasa Hello! Thanks for reporting. I have already pushed a fix for this in #1211, to improve the OS detection. To update the IKEv2 script on your VPN server to the fixed version, please follow instructions at:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#update-ikev2-helper-script
