### ISSUE TITLE
请问如何查看当前连接用户和用户登录日志？

### ISSUE THREAD

**Issue by cegod** [hwdsl2/setup-ipsec-vpn#1214]
@hwdsl2 您好，我使用您的脚本搭建了Ipsec/L2TP VPN，请问如何查看当前连接用户和用户历史登录日志？感谢！

**Comment by hwdsl2** [comment]
@cegod 你好！你可以使用命令 ipsec trafficstatus 查看已连接的客户端的信息。不支持查看用户历史登录日志，IPsec/L2TP 登录用户名需要启用 debug 才能在日志中显示，更多信息请参见 #166。
