### ISSUE TITLE
Windows 10 Home 配置 IPsec/L2TP VPN 客户端后连接成功，但IP检测未变。

### ISSUE THREAD

**Issue by ossacomu** [hwdsl2/setup-ipsec-vpn#1215]
**问题描述**
根据 “配置 IPsec/L2TP VPN 客户端” 在windows10 Home上配置VPN后，可以成功连接VPN。但访问youtube等外网均失败。

检测ip地址后，发现IP地址未改变。

查看windows 10 route table后发现，vpn default route 缺失。

**重现步骤**
重现该 bug 的步骤：

1. 连接VPN
2. https://www.ipchicken.com/

**期待的正确结果**
IP地址改为VPN地址

**日志**
对比另一台VPN连接后，能正常改变IP的windows10 Pro. 发现有问题的机器（windows 10 Home）缺少一条vpn default route.

以下是windows 10 Pro 连接VPN后，部分route table（192.168.42.12为VPN分配的内网地址）：
IPv4 Route Table
===========================================================================
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0     192.168.29.1     192.168.1.50   4506
          0.0.0.0          0.0.0.0      192.168.1.1     192.168.1.50   4250
          0.0.0.0          0.0.0.0         On-link     192.168.42.12     26

其中：           0.0.0.0          0.0.0.0         On-link     192.168.42.12     26 在VPN连接后出现. 
有问题的windows 10 Home连接VPN后获得IP 192.168.42.11，但未能添加默认路由，导致所有包仍然走的原路由。

**服务器信息（请填写以下信息）**
- 操作系统: Rocky Linux 9
- 服务提供商（如果适用）: GCP

**客户端信息（请填写以下信息）**
- 设备: Laptop
- 操作系统: Windows 10 Home
- VPN 模式: IPsec/L2TP

**其它信息**
添加关于该 bug 的其它信息。

**Comment by hwdsl2** [comment]
@ossacomu 你好！这是本项目第一次收到关于 Windows 10 Home 的此类问题的报告，我觉得有可能是你的特定系统的问题，而不是所有 Windows 10 Home。请首先尝试这个链接 [1] 中的几个解决方案。

该问题应该向 Microsoft 报告，而不是这里，因为它是 Windows 系统自带的客户端的问题，不是服务器端的问题。

推荐使用 IKEv2 模式连接 VPN。该模式比 IPsec/L2TP 更佳。请参见 [2]。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#%E8%BF%9E%E6%8E%A5-ikev2-%E5%90%8E%E4%B8%8D%E8%83%BD%E6%89%93%E5%BC%80%E7%BD%91%E7%AB%99
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md

**Comment by ossacomu** [comment]
是我傻逼了。我重新创建了一遍，就没问题了。谢谢。
