### ISSUE TITLE
l2tp vpn on Huawei B525 

### ISSUE THREAD

**Issue by coccobellof5** [hwdsl2/setup-ipsec-vpn#1219]
![image](https://user-images.githubusercontent.com/83649516/187081816-21075f73-09f2-486e-8452-6fd99d923862.png)

Hello everybody.
I'm having a problem.
I would like to configure the l2tp vpn on a huawei b525 modem, but it does not connect.
It asks me for the hostname, I entered the one of the vpn server, but still it does not connect.
You can help me?
I tried it on android smartphone and it works.
I don't understand

**Comment by hwdsl2** [comment]
@coccobellof5 Hello! The Huawei B525 is not supported as a VPN client for this project. See earlier issue #525.
