### ISSUE TITLE
如果同时安装pptp ，那iptables应该怎么改？

### ISSUE THREAD

**Issue by wpzzz** [hwdsl2/setup-ipsec-vpn#122]
假设pptp 内网ip是192.168.41.0/24
直接修改/etc/iptables.rules吗?  
谢谢

**Comment by hwdsl2** [comment]
@wpzzz Yes. Please try the following:

```
iptables -t nat -I POSTROUTING -s 192.168.41.0/24 -o eth+ -j MASQUERADE
iptables-save > /etc/iptables.rules
```

**Comment by wpzzz** [comment]
不行啊， 客户端连接失败 错误代码628
服务器日志
 GRE: read(fd=6,buffer=55fa1813e4a0,len=8196) from PTY failed: status = -1 error = Input/output error, usually caused by unexpected termination of pppd, check option syntax and pppd logs
CTRL: PTY read or GRE write failed (pty,gre)=(6,7)

/etc/iptables.rules

`*filter
:INPUT ACCEPT [47:3662]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [651:526668]
:fail2ban-ssh - [0:0]
-A INPUT -p tcp -m multiport --dports 22 -j fail2ban-ssh
-A INPUT -p udp -m udp --dport 1701 -m policy --dir in --pol none -j DROP
-A INPUT -m conntrack --ctstate INVALID -j DROP
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p udp -m multiport --dports 500,4500 -j ACCEPT
-A INPUT -p udp -m udp --dport 1701 -m policy --dir in --pol ipsec -j ACCEPT
-A INPUT -p udp -m udp --dport 1701 -j DROP
-A FORWARD -m conntrack --ctstate INVALID -j DROP
-A FORWARD -i eth+ -o ppp+ -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i ppp+ -o eth+ -j ACCEPT
-A FORWARD -s 192.168.42.0/24 -d 192.168.42.0/24 -i ppp+ -o ppp+ -j ACCEPT
-A FORWARD -d 192.168.43.0/24 -i eth+ -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 192.168.43.0/24 -o eth+ -j ACCEPT
-A FORWARD -j DROP
-A fail2ban-ssh -s 119.249.54.71/32 -j REJECT --reject-with icmp-port-unreachable
-A fail2ban-ssh -j RETURN
COMMIT
# Completed on Thu Mar 16 14:46:32 2017
# Generated by iptables-save v1.4.21 on Thu Mar 16 14:46:32 2017
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -s 192.168.41.0/24 -o eth+ -j MASQUERADE
-A POSTROUTING -s 192.168.42.0/24 -o eth+ -j MASQUERADE
-A POSTROUTING -s 192.168.43.0/24 -o eth+ -m policy --dir out --pol none -j MASQUERADE
COMMIT
# Completed on Thu Mar 16 14:46:32 201`


但是iptables -L -n   没有关于92.168.41.0/24的规则


pptp服务端和客户端本身是没有没问题， vps只安装了pptp的话，客户端可以正常连接，即使不设置iptables也能连上，当然这样的话无法联网

**Comment by hwdsl2** [comment]
@wpzzz You can see the added `192.168.41.0/24` rule by running `iptables -L -n -t nat`.

The problem is not with IPTables. When you run the IPsec VPN setup scripts, it overwrites `/etc/ppp/chap-secrets`, which originally contained your PPTP username and password. You can re-add your credentials to that file as a new line in the following format [1]:

```
YOUR_PPTP_USERNAME    pptpd    YOUR_PPTP_PASSWORD    *
```

Then restart the pptpd service, and retry the connection.

[1] https://wiki.archlinux.org/index.php/PPTP_server

**Comment by wpzzz** [comment]
那里我一直用 username *  passwd *  所以没问题
我刚才发现iptables -F之后就可以连上了，然后我逐条删除测试，问题出在这个规则， 只要删除这条就能连上，如果日常使用时 ，这样直接删除合适吗？

-A INPUT -m conntrack --ctstate INVALID -j DROP

**Comment by hwdsl2** [comment]
@wpzzz 可以删除。虽然我觉得那条规则一般不会影响连接。你再检查一下其它 IPTables 规则是否都还在：

```
iptables -nvL
iptables -nvL -t nat
```

**Comment by wpzzz** [comment]
都在的，我之前测试清空nat表 依旧连不上，清空filter就可以，然后一条条排除。 重启vps后iptables重新加载，pptp连不上，然后只删除那一条，就能连上
