### ISSUE TITLE
How to configure so i can use L2TP without a "preshared key" - so just with username & password authentication

### ISSUE THREAD

**Issue by kosuodhmwa** [hwdsl2/setup-ipsec-vpn#1220]
Hello

**Question:** How to configure so i can use L2TP without a "preshared key" - so just with username & password authentication

Thank you very much for your feedback.

Best regards from Switzerland, Jan

**Comment by kosuodhmwa** [comment]
One question more: How can i set up IKEv2 also without additional thinks like key-files -> so also only username & password.

I know that this is theoretically possible from my VPN provider... 

Does your tool support that 2 cases (this one and the other one i wrote above)

**Comment by letoams** [comment]
On Sun, 28 Aug 2022, Patrick Meier wrote:

> Question: How to configure so i can use L2TP without a "preshared key" - so just with username & password authentication

You cannot use only "username and password" with L2TP because IKEv1 is
used by L2TP and it requires either a PSK or an X.509 certificate.

With IKEv2, it is possible to have an EAP method that only has user and
password, but libreswan currently only supports EAPTLS, which does not
use a user/password but uses an X.509 certificate.

Paul

**Comment by kosuodhmwa** [comment]
I was thinking L2TP is associated with "IPSec" and not with "IKEv1".... so not correctly?

Then, there are 3 thing involved (L2TP, IPSec, and IKE)

Any why i can connect with windows client when i select this option - NOT IKE (!!):
![image](https://user-images.githubusercontent.com/24782840/187381864-48ba2796-eb23-45e4-afa1-d6f972ac9ecd.png)

**Comment by kosuodhmwa** [comment]
Another question here, about "How to use IKEv option on Win10 VPN connection setting without keyfile/certificate but with USERNAME & PASSWORD": https://github.com/hwdsl2/setup-ipsec-vpn/issues/1221

**Comment by letoams** [comment]
On Aug 30, 2022, at 03:55, Patrick Meier ***@***.***> wrote:
> 
> ﻿I was thinking L2TP is associated with "IPSec" and not with "IKEv1".... so not correctly?

All IPsec is negotiated using IKE (v1 or v2)

> Then, there are 3 thing involved (L2TP, IPSec, and IKE)
> 

Yes.

> Any why i can connect with windows client when i select this option - NOT IKE (!!):
> 
> 
(image doesn’t show up in my email here)

**Comment by kosuodhmwa** [comment]
Thank you very much for your feedback.

"Any why" -> "AND why"

Question #2 was solved with your answer on Question #1 - so all is clearly now :-)
