### ISSUE TITLE
How can i configure it so i can select "IKEv2" on Windows 10 VPN connection setting WITHOUT some keyfiles - just username and password

### ISSUE THREAD

**Issue by kosuodhmwa** [hwdsl2/setup-ipsec-vpn#1221]
Hello

I known that it is (theoretically, if we look only at IKEv2) possible (my own VPN provider is able to do that), but on https://debianforum.de/forum/viewtopic.php?t=184836 i asked about that thing... then i've got an answer about the /etc/ipsec.conf file; but, when i look into it after a fresh setup-ipsec-vpn installation, there is no name-value-pair "block" with section-"title" called "conn IKEv2"... do i need to configure it first, as setup-ipsec-vpn prints out after installation. ("To create a IKEv2 config, do that steps ... ")

Thank you very very much for your feedback.

Best regards from Switzerland,
Jan

**Comment by hwdsl2** [comment]
@kosuodhmwa Hello! IKEv2 with username and password authentication (EAP) is not currently supported in this project. This feature is not yet available in Libreswan 4.7, which added EAPTLS support for IKEv2 but not with username/password authentication.

**Comment by kosuodhmwa** [comment]
Thank you very much for your feedback!

**Comment by kosuodhmwa** [comment]
-> It seems to be possible with packages "strongswan" and "libcharon-extra-plugins" if i read that: https://debianforum.de/forum/viewtopic.php?t=184836

(you can use an online translator if you want to read it)

Maybe that would be a nice feature for your project...? :-)

**Comment by letoams** [comment]
They use EAPmschapv2, which is not supported by libreswan (but is supported by strongswan)

Sent using a virtual keyboard on a phone

**Comment by kosuodhmwa** [comment]
Thank you very much for your feedback... :-)
