### ISSUE TITLE
有不需要 IPsec预共享密钥 的脚本吗？我需要登录在路由器上面，路由器不支持需要 IPsec预共享密钥 的服务

### ISSUE THREAD

**Issue by wlc743859910** [hwdsl2/setup-ipsec-vpn#1222]
有不需要 IPsec预共享密钥 的脚本吗？我需要登录在路由器上面，路由器不支持需要 IPsec预共享密钥 的服务

![image](https://user-images.githubusercontent.com/84552324/187583398-aa71d248-57d9-48b5-9c30-58797f01b78f.png)

![image](https://user-images.githubusercontent.com/84552324/187583425-7ac01f2c-c2f8-46ba-9c21-5822c15dd4c6.png)

**Comment by hwdsl2** [comment]
@wlc743859910 你好！本项目不支持不带 IPsec 预共享密钥的 L2TP 模式。你可以另外尝试比如 [SoftEther VPN](https://github.com/SoftEtherVPN/SoftEtherVPN)。请注意，不带 IPsec 的 L2TP 模式下数据没有任何加密。
