### ISSUE TITLE
Is your VPN solution also installable in Raspbian 11 "Bullseys" instead of Debian 11 "Bullseye" ?

### ISSUE THREAD

**Issue by kosuodhmwa** [hwdsl2/setup-ipsec-vpn#1223]
As the title says - thank you very much for your feedback :-)

**Comment by hwdsl2** [comment]
@kosuodhmwa Hello! Yes, you can use this project with Raspbian 11. You may need to forward UDP ports 500 and 4500 from your home router to the Raspberry Pi. Refer to linked articles at the end of [this section](https://github.com/hwdsl2/setup-ipsec-vpn#requirements).

**Comment by kosuodhmwa** [comment]
Thank you very much, i was able to install it on Debian - if it is the same process on Raspbian: Very nice, thank you very much!! :-)
