### ISSUE TITLE
安卓11无法使用youtube软件，但是网页版可以正常使用，

### ISSUE THREAD

**Issue by CherryPeel** [hwdsl2/setup-ipsec-vpn#1224]
**任务列表**

- [√  ] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [ √ ] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [√  ] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [√  ] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [√ ] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)

安卓11无法使用youtube软件，但是网页版可以正常使用，

**Comment by hwdsl2** [comment]
@CherryPeel 你好！这个很可能是 MTU/MSS 问题。请参见这些链接中的解决方案：
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#android-mtumss-%E9%97%AE%E9%A2%98
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#%E8%BF%9E%E6%8E%A5-ikev2-%E5%90%8E%E4%B8%8D%E8%83%BD%E6%89%93%E5%BC%80%E7%BD%91%E7%AB%99

另外你可以尝试换用不同的模式连接，比如 [IKEv2](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md)。
