### ISSUE TITLE
get.vpnsetup.net ssl has expired

### ISSUE THREAD

**Issue by iyuhang** [hwdsl2/setup-ipsec-vpn#1225]
root@iZ2ze2xvhv7hsozjhqplraZ:~# wget https://get.vpnsetup.net -O vpn.sh && sudo sh vpn.sh
--2022-09-04 15:43:38--  https://get.vpnsetup.net/
Resolving get.vpnsetup.net (get.vpnsetup.net)... 172.67.163.121, 104.21.66.191, 2606:4700:3030::ac43:a379, ...
Connecting to get.vpnsetup.net (get.vpnsetup.net)|172.67.163.121|:443... connected.
ERROR: The certificate of ‘get.vpnsetup.net’ is not trusted.
ERROR: The certificate of ‘get.vpnsetup.net’ has expired.

**Comment by hwdsl2** [comment]
@iyuhang Hello! The certificate is valid. Testing using `curl`:
```
* Connected to get.vpnsetup.net port 443 (#0)
... ...
* Server certificate:
*  subject: CN=*.vpnsetup.net
*  start date: Aug 24 02:21:44 2022 GMT
*  expire date: Nov 22 02:21:43 2022 GMT
*  subjectAltName: host "get.vpnsetup.net" matched cert's "*.vpnsetup.net"
*  issuer: C=US; O=Let's Encrypt; CN=E1
*  SSL certificate verify ok.
```
If you get a "not trusted" or "expired" response, do not connect because it is not secure (possible MitM attack, etc.) Use this URL instead:
```
https://github.com/hwdsl2/setup-ipsec-vpn/raw/master/vpnsetup.sh
```
