### ISSUE TITLE
Why i don't need to open UPD port when i use L2TP with IPSec and preshared Key [PSK]...?

### ISSUE THREAD

**Issue by jayjupdhig** [hwdsl2/setup-ipsec-vpn#1226]
Hello

Question: As the title says: Why i don't need to open UPD port when i use L2TP with IPSec and preshared Key [PSK]...?
(So the default config after installing with: PSK: xxx, Username: yyy, Password: zzz)

-> https://wiki.securepoint.de/UTM/VPN/%C3%9Cbersicht
-> Translated to english: https://wiki-securepoint-de.translate.goog/UTM/VPN/%C3%9Cbersicht?_x_tr_sl=de&_x_tr_tl=en&_x_tr_hl=en

**CITE:** **_'L2TP VPN [...] Ports: 1701/UDP'_**

**-> When i read there, the wrote avout an open UDP port 1701 which is necessary... but with the (default) L2TP/IPSec with PSK config, the UDP ports 5000 and 450 are enough to establish a connection from the Windows 10 VPN client (Encryption: "Required", "Strong" does not seem to be supported yet).**

Thank you very very much for your feedback(s). :-) 

With best regards from Switzerland,
Jan

**Comment by letoams** [comment]
You need to have UDP port 500 and 4500 open. L2TP packets on port 1701 are encrypted using IPsec (ESP) and encapsulated in UDP 4500. So you do not need port 1701 open.

Sent using a virtual keyboard on a phone

**Comment by kosuodhmwa** [comment]
OK thx :-)

**Comment by hwdsl2** [comment]
Thanks @letoams for the response.
