### ISSUE TITLE
Local and Peer Subnet

### ISSUE THREAD

**Issue by bailaowai** [hwdsl2/setup-ipsec-vpn#1230]
Hello, may I know how to find out the peer and the local subnet do that I can setup my router?

Also, what is the local and peer ID?
![image](https://user-images.githubusercontent.com/69111040/190306460-b8a3eb4f-2b0b-4ed9-8d05-8a192fab3e68.jpeg)
![image](https://user-images.githubusercontent.com/69111040/190306487-bc0e59b1-f33c-48a4-b158-7d7e1772187d.jpeg)

**Comment by hwdsl2** [comment]
@bailaowai Hello! The iKuai router is not supported as a VPN client for this project. More information and links can be found at: https://github.com/hwdsl2/docker-ipsec-vpn-server/issues/190
