### ISSUE TITLE
Fails to connect after doing all steps on Raspberry Pi

### ISSUE THREAD

**Issue by CrazyMan1234** [hwdsl2/setup-ipsec-vpn#1231]
Hello, I did this on the latest version of Ubuntu, and I got my IP, psk, username, and password. Still every time I try connecting, it gives me an error. This is on a raspberry pi and not a vps since this is a private VPN only for me. I port forwarded 500 and 4500 on the correct IP. I've also tried uninstalling then reinstalling, but nothing works?

**Comment by hwdsl2** [comment]
@CrazyMan1234 Hello! What error did you encounter? Please check IPsec and L2TP logs on your VPN server:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status

If no new logs appear after trying to connect again, then traffic did not reach your VPN server (Raspberry Pi). This means either your port forwarding (UDP ports 500 and 4500) didn't work, or your IP could not accept incoming connections (for example, is behind carrier-grade NAT).

**Comment by CrazyMan1234** [comment]
avi@RaspSystem:~$ sudo service ipsec restart
Job for ipsec.service failed because a fatal signal was delivered causing the control process to dump core.
See "systemctl status ipsec.service" and "journalctl -xeu ipsec.service" for details.
avi@RaspSystem:~$ sudo service xl2tpd restart
avi@RaspSystem:~$ ipsec status
whack: Pluto is not running (no "/run/pluto/pluto.ctl")
avi@RaspSystem:~$ ipsec trafficstatus
whack: Pluto is not running (no "/run/pluto/pluto.ctl")
avi@RaspSystem:~$ systemctl status ipsec.service
● ipsec.service - Internet Key Exchange (IKE) Protocol Daemon for IPsec
     Loaded: loaded (/lib/systemd/system/ipsec.service; enabled; vendor preset: enabled)
     Active: activating (start-pre) since Sun 2022-09-18 11:05:59 CDT; 1s ago
       Docs: man:ipsec(8)
             man:pluto(8)
             man:ipsec.conf(5)
    Process: 67885 ExecStartPre=/usr/local/libexec/ipsec/addconn --config /etc/ipsec.conf --checkconfig (code=exited, status=0/SUCCESS)
Cntrl PID: 67886 (_stackmanager)
      Tasks: 3 (limit: 4122)
     Memory: 808.0K
        CPU: 984ms
     CGroup: /system.slice/ipsec.service
             ├─67886 /bin/sh /usr/local/libexec/ipsec/_stackmanager start
             └─68062 modprobe --quiet --use-blacklist sha512-arm64

Sep 18 11:05:59 RaspSystem systemd[1]: Starting Internet Key Exchange (IKE) Protocol Daemon for IPsec...
Sep 18 11:05:59 RaspSystem _stackmanager[67896]: Cannot open netlink socket: Protocol not supported
Sep 18 11:05:59 RaspSystem _stackmanager[67898]: Cannot open netlink socket: Protocol not supported
avi@RaspSystem:~$ journalctl -xeu ipsec.service
Sep 18 11:06:11 RaspSystem pluto[69035]: helper(3) seccomp security for helper not supported
Sep 18 11:06:11 RaspSystem pluto[69035]: using Linux xfrm kernel support code on #14-Ubuntu SMP PREEMPT Fri Jun 24 13:10:28 UTC 2022
Sep 18 11:06:11 RaspSystem pluto[69035]: FATAL ERROR: socket() in init_netlink()Protocol not supported (errno 93)
Sep 18 11:06:11 RaspSystem pluto[69035]: WARNING: helper threads still running
Sep 18 11:06:11 RaspSystem pluto[69035]: ABORT: ASSERTION FAILED: event_initialized(ev) (free_signal_handlers() +461 programs/pluto/server.c)
Sep 18 11:06:11 RaspSystem systemd[1]: ipsec.service: Main process exited, code=dumped, status=6/ABRT
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ An ExecStart= process belonging to unit ipsec.service has exited.
░░ 
░░ The process' exit code is 'dumped' and its exit status is 6.
Sep 18 11:06:11 RaspSystem bash[69044]: Cannot open netlink socket: Protocol not supported
Sep 18 11:06:11 RaspSystem bash[69046]: Cannot open netlink socket: Protocol not supported
Sep 18 11:06:11 RaspSystem systemd[1]: ipsec.service: Control process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ An ExecStopPost= process belonging to unit ipsec.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Sep 18 11:06:11 RaspSystem systemd[1]: ipsec.service: Failed with result 'core-dump'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The unit ipsec.service has entered the 'failed' state with result 'core-dump'.
Sep 18 11:06:11 RaspSystem systemd[1]: Failed to start Internet Key Exchange (IKE) Protocol Daemon for IPsec.
░░ Subject: A start job for unit ipsec.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit ipsec.service has finished with a failure.
░░ 
░░ The job identifier is 27031 and the job result is failed.
Sep 18 11:06:11 RaspSystem systemd[1]: ipsec.service: Consumed 1.500s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The unit ipsec.service completed and consumed the indicated resources.
Sep 18 11:06:11 RaspSystem systemd[1]: ipsec.service: Scheduled restart job, restart counter is at 16.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ Automatic restarting of the unit ipsec.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
Sep 18 11:06:11 RaspSystem systemd[1]: Stopped Internet Key Exchange (IKE) Protocol Daemon for IPsec.
░░ Subject: A stop job for unit ipsec.service has finished
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A stop job for unit ipsec.service has finished.
░░ 
░░ The job identifier is 27118 and the job result is done.
Sep 18 11:06:11 RaspSystem systemd[1]: ipsec.service: Consumed 1.500s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The unit ipsec.service completed and consumed the indicated resources.
Sep 18 11:06:11 RaspSystem systemd[1]: Starting Internet Key Exchange (IKE) Protocol Daemon for IPsec...
░░ Subject: A start job for unit ipsec.service has begun execution
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit ipsec.service has begun execution.
░░ 
░░ The job identifier is 27118.
Sep 18 11:06:11 RaspSystem _stackmanager[69060]: Cannot open netlink socket: Protocol not supported
Sep 18 11:06:11 RaspSystem _stackmanager[69062]: Cannot open netlink socket: Protocol not supported


I ran all of those commands + some more and here was my output. I tried restarting ipsec.service and it just gave me an error.

**Comment by letoams** [comment]
Seems that kernel is missing basic functionality ? Is it a custom compile ?

Sent using a virtual keyboard on a phone

**Comment by CrazyMan1234** [comment]
no its not?

**Comment by letoams** [comment]
On Sun, 18 Sep 2022, CrazyMan1234 wrote:

> CGroup: /system.slice/ipsec.service
> ├─67886 /bin/sh /usr/local/libexec/ipsec/_stackmanager start
> └─68062 modprobe --quiet --use-blacklist sha512-arm64

stackmanager is a shell script that runs just before starting the
libreswan pluto IKE daemon. If it shows, it might be hanging on
something.

> Sep 18 11:05:59 RaspSystem _stackmanager[67896]: Cannot open netlink socket: Protocol not supported

That's weird because stackmanager doesn't do netlink itself, it just
calls ip xfrm and modprobe and echo's into /proc files.

You can try editing /usr/local/libexec/ipsec/_stackmanager and make it
do nothing and see if that works around your issue.

Paul

**Comment by CrazyMan1234** [comment]
You mean remove everything in it? I tried that it just gave me more errors.

**Comment by hwdsl2** [comment]
@CrazyMan1234 It looks like the Linux kernel on your Raspberry Pi's Ubuntu system lacks support for IPsec. I did a web search and found some similar issues: [1] [2].

Possible solutions:
1. Change your Raspberry Pi's OS to e.g. Raspbian (Raspberry Pi OS), and install IPsec again.
2. Use [OpenVPN](https://github.com/hwdsl2/openvpn-install) and/or [WireGuard](https://github.com/hwdsl2/wireguard-install) instead. For OpenVPN, forward UDP/1194. For WireGuard, forward UDP/51820. These are the default ports unless you change them during setup.

I'm closing this but you can continue the discussion here if needed.

[1] https://serverfault.com/questions/996843/strongswan-no-start-embedder-linux
[2] https://lists.openswan.org/pipermail/users/2011-September/021047.html

**Comment by CrazyMan1234** [comment]
Alr it worked tysm man! :D
I switched to Raspbian and just did the one-liner and boom it worked. 
I'm probably gonna host on a vps soon since I got it working on a actual pi
Thanks again!
