### ISSUE TITLE
Passing through Bonjour/mDNS services

### ISSUE THREAD

**Issue by mav2287** [hwdsl2/setup-ipsec-vpn#1232]
I have Bonjour/mDNS services I would like to pass through to VPN clients. From what I understand the forecast Plugin can handle this, but it is disabled by default. I went through all the readme docs and couldn't find anything on this. Is setting this up an option through one of the scripts? Is this something you would want to look at adding? If not any advice on how to get it turned on manually?

In case you haven't look at the forecast plugin the docs are here: https://docs.strongswan.org/docs/5.9/plugins/forecast.html

Thanks for taking a look and thanks for all your work on these scripts! They are great!

**Comment by hwdsl2** [comment]
@mav2287 Hello! This project uses [Libreswan](https://libreswan.org), not strongSwan, so the "forecast" plugin does not apply here. This feature is not currently supported and unfortunately I am not sure how this (Bonjour/mDNS passthrough) would work using Libreswan. For your reference, there was an earlier discussion on AirPrint [here](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues/287).

**Comment by mav2287** [comment]
Good catch on that, it's late so I must have spaced on the project name. After digging further (on the right project) looks like EoIP shared ethernet LAN using IPsec may be the direction to head. It also looks like this may solve the mentioned AirPrint issue. Has anyone done anything along this lines with these scripts/setup?

https://libreswan.org/wiki/EoIP_shared_ethernet_LAN_using_IPsec
