### ISSUE TITLE
安装时报错

### ISSUE THREAD

**Issue by wj36149** [hwdsl2/setup-ipsec-vpn#1234]
[](url)**任务列表**

- [ ] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [ ] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [ ] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [x] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [ ] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] 这个 bug 是关于 VPN 安装脚本，而不是 IPsec VPN 本身

**问题描述**
使用清楚简明的语言描述这个 bug。

**重现步骤**
重现该 bug 的步骤：

1. ...
2. ...

**期待的正确结果**
简要地描述你期望的正确结果。

**日志**
[检查日志及 VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)，并添加错误日志以帮助解释该问题（如果适用）。

**服务器信息（请填写以下信息）**
- 操作系统: [Proxmox VE上的 Debian 11]
- 服务提供商（如果适用）: [比如 GCP, AWS]

**客户端信息（请填写以下信息）**
- 设备: [比如 iPhone 12]
- 操作系统: [比如 iOS 15]
- VPN 模式: [IPsec/L2TP, IPsec/XAuth ("Cisco IPsec") 或 IKEv2]

**其它信息**
使用脚本安装时报错
![屏幕截图 2022-09-20 135426](https://user-images.githubusercontent.com/48109441/191179102-d6d35eb9-b0c5-464d-a7f3-b2e46d70b962.png

**Comment by zouchengli** [comment]
你这是啥系统啊，看样子是debian，建议使用最新ubuntu 22.04 TLS

**Comment by hwdsl2** [comment]
@wj36149 你好！根据你服务器的日志来看，Libreswan没有成功编译，应该是你的服务器的系统的问题。建议你更换一个Linux发行版比如Ububtu试试看。在Proxmox上推荐使用VM而不是container安装VPN。
