### ISSUE TITLE
ikev2l可以正常连接，但是无法访问国外网站，请问有什么方法可以

### ISSUE THREAD

**Issue by Arutosann** [hwdsl2/setup-ipsec-vpn#1240]
ikev2l可以正常连接，但是无法访问国外网站，请问有什么方法可以

**Comment by hwdsl2** [comment]
@Arutosann 你好！在某些情况下，Windows 在连接后不使用 IKEv2 指定的 DNS 服务器，可能导致无法访问某些网站。要解决此问题，可以在你的 Windows 系统的网络连接属性 -> TCP/IPv4 中手动输入 DNS 服务器，例如 Google Public DNS (8.8.8.8, 8.8.4.4)。另外，可以参见这里的解决方案：
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#%E8%BF%9E%E6%8E%A5-ikev2-%E5%90%8E%E4%B8%8D%E8%83%BD%E6%89%93%E5%BC%80%E7%BD%91%E7%AB%99
