### ISSUE TITLE
您好 我这个链接时候也出现了问题。win10客户端报错无法建立与服务器之间链接。事件查看器里的报错是：的拨号连接，该连接已失败。失败后返回的错误代码为 809。

### ISSUE THREAD

**Issue by BigLongBoy** [hwdsl2/setup-ipsec-vpn#1241]
本来之前有一个L2tp/ipsec 的vpn 一夜之间突然就不好用了，现在想换成lk的试试。服务是阿里云
在
grep pluto /var/log/secure命令输出结果如下：

Oct  2 16:30:31 iZj6c9ybkgud17sjalfxzpZ pluto[3953]: "ikev2-cp"[1]  #1: proposal 2:IKE=AES_CBC_256-HMAC_SHA2_256-HMAC_SHA2_256_128-MODP2048 chosen from remote proposals 1:IKE:ENCR=AES_CBC_256;INTEG=HMAC_SHA1_96;PRF=HMAC_SHA1;DH=MODP2048[first-match] 2:IKE:ENCR=AES_CBC_256;INTEG=HMAC_SHA2_256_128;PRF=HMAC_SHA2_256;DH=MODP2048[better-match] 3:IKE:ENCR=AES_CBC_256;INTEG=HMAC_SHA2_384_192;PRF=HMAC_SHA2_384;DH=MODP2048
Oct  2 16:30:31 iZj6c9ybkgud17sjalfxzpZ pluto[3953]: "ikev2-cp"[1] ip地址 #1: sent IKE_SA_INIT reply {cipher=AES_CBC_256 integ=HMAC_SHA2_256_128 prf=HMAC_SHA2_256 group=MODP2048}
Oct  2 16:30:31 iZj6c9ybkgud17sjalfxzpZ pluto[3953]: "ikev2-cp"[1] ip地址 #1: processing decrypted IKE_AUTH request: SK{IDi,CERT,CERTREQ,AUTH,N(MOBIKE_SUPPORTED),CP,SA,TSi,TSr}
Oct  2 16:30:31 iZj6c9ybkgud17sjalfxzpZ pluto[3953]: "ikev2-cp"[1] ip地址 #1: ignoring CERTREQ payload that is not ASN1: content is not binary ASN.1
Oct  2 16:30:31 iZj6c9ybkgud17sjalfxzpZ pluto[3953]: "ikev2-cp"[1] ip地址 #1: reloaded private key matching left certificate 'vpn.example.com'
Oct  2 16:30:31 iZj6c9ybkgud17sjalfxzpZ pluto[3953]: "ikev2-cp"[1] ip地址 #1: responder established IKE SA; authenticated using PKCS#1 1.5 RSA with SHA1 and peer certificate 'CN=vpnclient, O=IKEv2 VPN' issued by CA 'CN=IKEv2 VPN CA, O=IKEv2 VPN'
Oct  2 16:30:31 iZj6c9ybkgud17sjalfxzpZ pluto[3953]: | pool 192.168.43.10-192.168.43.250: growing address pool from 0 to 1
Oct  2 16:30:31 iZj6c9ybkgud17sjalfxzpZ pluto[3953]: "ikev2-cp"[1] ip地址3 #2: proposal 1:ESP=AES_GCM_C_128-DISABLED SPI=549b21d0 chosen from remote proposals 1:ESP:ENCR=AES_GCM_C_128;ESN=DISABLED[first-match]
Oct  2 16:30:31 iZj6c9ybkgud17sjalfxzpZ pluto[3953]: "ikev2-cp"[1] ip地址3 #2: responder established Child SA using #1; IPsec tunnel [0.0.0.0-255.255.255.255:0-65535 0] -> [192.168.43.10-192.168.43.10:0-65535 0] {ESPinUDP=>0x549b21d0 <0xd21fdeb7 xfrm=AES_GCM_16_128-NONE NATD=221.218.140.63:13933 DPD=active}
Oct  2 16:30:32 iZj6c9ybkgud17sjalfxzpZ pluto[3953]: "ikev2-cp"[1] ip地址3 #1: IKE_AUTH request fragment 1 of 16 has duplicate Message ID 1; retransmitting response
Oct  2 16:30:33 iZj6c9ybkgud17sjalfxzpZ pluto[3953]: "ikev2-cp"[1] ip地址3 #1: IKE_AUTH request fragment 1 of 16 has duplicate Message ID 1; retransmitting response
防火墙也是打开了，我有点想不通
![截图08](https://user-images.githubusercontent.com/47029688/193445410-e65632b3-f564-4f31-87a8-d24df86cdc4d.png)

**Comment by hwdsl2** [comment]
@BigLongBoy 你好！从你的日志来看，可能是连接被 GFW 干扰或屏蔽了。建议你另外尝试其他的解决方案比如 Shadowsocks。

**Comment by BigLongBoy** [comment]
> @BigLongBoy 你好！从你的日志来看，可能是连接被 GFW 干扰或屏蔽了。建议你另外尝试其他的解决方案比如 Shadowsocks。
非常感谢回复 那我换一个云服务提供商尝试一下吧
