### ISSUE TITLE
IKEV2 上午还能连接，下午提示无法连接

### ISSUE THREAD

**Issue by SourceKim** [hwdsl2/setup-ipsec-vpn#1242]
**问题描述**
- 上午还能连接，下午就无法连接了
- 尝试重新安装脚本 - 失败
- 尝试重装服务器系统 - 失败

**重现步骤**
重现该 bug 的步骤：

1. 按照教程提交脚本
2. 导出证书
3. 回传证书到设备中
4. 开启连接

**期待的正确结果**
能连接

**日志**
Oct  2 09:07:00 hwsrv-1003501 pluto[29419]: message repeated 2 times: [ "ikev2-cp"[1] 157.61.159.55 #1: IKE_AUTH request fragment 1 of 4 has duplicate Message ID 1; retransmitting response]
Oct  2 09:07:16 hwsrv-1003501 pluto[29419]: "ikev2-cp"[1] 157.61.159.55 #3: proposal 1:IKE=AES_CBC_256-HMAC_SHA2_256-HMAC_SHA2_256_128-MODP2048 chosen from remote proposals 1:IKE:ENCR=AES_CBC_256;PRF=HMAC_SHA2_256;INTEG=HMAC_SHA2_256_128;DH=MODP2048[first-match]
Oct  2 09:07:16 hwsrv-1003501 pluto[29419]: "ikev2-cp"[1] 157.61.159.55 #3: sent IKE_SA_INIT reply {cipher=AES_CBC_256 integ=HMAC_SHA2_256_128 prf=HMAC_SHA2_256 group=MODP2048}
Oct  2 09:07:16 hwsrv-1003501 pluto[29419]: "ikev2-cp"[1] 157.61.159.55 #1: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 0.5 seconds for response
Oct  2 09:07:16 hwsrv-1003501 pluto[29419]: "ikev2-cp"[1] 157.61.159.55 #3: processing decrypted IKE_AUTH request: SK{IDi,CERT,N(INITIAL_CONTACT),IDr,AUTH,CP,N(ESP_TFC_PADDING_NOT_SUPPORTED),N(NON_FIRST_FRAGMENTS_ALSO),SA,TSi,TSr,N(MOBIKE_SUPPORTED)}
Oct  2 09:07:16 hwsrv-1003501 pluto[29419]: "ikev2-cp"[1] 157.61.159.55 #3: switched to "ikev2-cp"[2] 157.61.159.55
Oct  2 09:07:16 hwsrv-1003501 pluto[29419]: "ikev2-cp"[2] 157.61.159.55 #3: responder established IKE SA; authenticated using PKCS#1 1.5 RSA with SHA1 and peer certificate '@kim' issued by CA 'CN=IKEv2 VPN CA, O=IKEv2 VPN'
Oct  2 09:07:16 hwsrv-1003501 pluto[29419]: | pool 192.168.43.10-192.168.43.250: growing address pool from 1 to 2
Oct  2 09:07:16 hwsrv-1003501 pluto[29419]: "ikev2-cp"[2] 157.61.159.55 #4: proposal 1:ESP=AES_GCM_C_128-DISABLED SPI=07ca0134 chosen from remote proposals 1:ESP:ENCR=AES_GCM_C_128;ESN=DISABLED[first-match]
Oct  2 09:07:16 hwsrv-1003501 pluto[29419]: "ikev2-cp"[2] 157.61.159.55 #4: responder established Child SA using #3; IPsec tunnel [0.0.0.0-255.255.255.255:0-65535 0] -> [192.168.43.11-192.168.43.11:0-65535 0] {ESPinUDP=>0x07ca0134 <0xa444a122 xfrm=AES_GCM_16_128-NONE NATD=157.61.159.55:31469 DPD=active}
Oct  2 09:07:17 hwsrv-1003501 pluto[29419]: "ikev2-cp"[1] 157.61.159.55 #1: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 1 seconds for response
Oct  2 09:07:17 hwsrv-1003501 pluto[29419]: "ikev2-cp"[2] 157.61.159.55 #3: IKE_AUTH request fragment 1 of 4 has duplicate Message ID 1; retransmitting response
Oct  2 09:07:18 hwsrv-1003501 pluto[29419]: "ikev2-cp"[1] 157.61.159.55 #1: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 2 seconds for response
Oct  2 09:07:19 hwsrv-1003501 pluto[29419]: "ikev2-cp"[2] 157.61.159.55 #3: IKE_AUTH request fragment 1 of 4 has duplicate Message ID 1; retransmitting response
Oct  2 09:07:20 hwsrv-1003501 pluto[29419]: "ikev2-cp"[1] 157.61.159.55 #1: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 4 seconds for response
Oct  2 09:07:23 hwsrv-1003501 pluto[29419]: "ikev2-cp"[2] 157.61.159.55 #3: IKE_AUTH request fragment 1 of 4 has duplicate Message ID 1; retransmitting response
Oct  2 09:07:24 hwsrv-1003501 pluto[29419]: "ikev2-cp"[1] 157.61.159.55 #1: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 8 seconds for response
Oct  2 09:07:31 hwsrv-1003501 pluto[29419]: "ikev2-cp"[2] 157.61.159.55 #3: IKE_AUTH request fragment 1 of 4 has duplicate Message ID 1; retransmitting response
Oct  2 09:07:32 hwsrv-1003501 pluto[29419]: "ikev2-cp"[1] 157.61.159.55 #1: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 16 seconds for response
Oct  2 09:07:47 hwsrv-1003501 pluto[29419]: "ikev2-cp"[2] 157.61.159.55 #3: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 0.5 seconds for response
Oct  2 09:07:47 hwsrv-1003501 pluto[29419]: "ikev2-cp"[2] 157.61.159.55 #3: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 1 seconds for response
Oct  2 09:07:48 hwsrv-1003501 pluto[29419]: "ikev2-cp"[1] 157.61.159.55 #1: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 32 seconds for response
Oct  2 09:07:48 hwsrv-1003501 pluto[29419]: "ikev2-cp"[2] 157.61.159.55 #3: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 2 seconds for response
Oct  2 09:07:50 hwsrv-1003501 pluto[29419]: "ikev2-cp"[2] 157.61.159.55 #3: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 4 seconds for response
Oct  2 09:07:54 hwsrv-1003501 pluto[29419]: "ikev2-cp"[2] 157.61.159.55 #3: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 8 seconds for response
Oct  2 09:08:02 hwsrv-1003501 pluto[29419]: "ikev2-cp"[2] 157.61.159.55 #3: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 16 seconds for response
Oct  2 09:08:18 hwsrv-1003501 pluto[29419]: "ikev2-cp"[2] 157.61.159.55 #3: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 32 seconds for response
Oct  2 09:08:20 hwsrv-1003501 pluto[29419]: "ikev2-cp"[1] 157.61.159.55 #1: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 64 seconds for response
Oct  2 09:08:50 hwsrv-1003501 pluto[29419]: "ikev2-cp"[2] 157.61.159.55 #3: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 64 seconds for response
Oct  2 09:09:24 hwsrv-1003501 pluto[29419]: "ikev2-cp"[1] 157.61.159.55 #1: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 128 seconds for response
Oct  2 09:09:54 hwsrv-1003501 pluto[29419]: "ikev2-cp"[2] 157.61.159.55 #3: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 128 seconds for response

**服务器信息（请填写以下信息）**
- 操作系统: Ubuntu20
- 服务提供商（如果适用）: hostwind

**客户端信息（请填写以下信息）**
- 设备: macos & iOS
- 操作系统: iOS14
- VPN 模式: IKEv2
- 
**其它信息**
添加关于该 bug 的其它信息。

**Comment by hwdsl2** [comment]
@SourceKim 你好！从你的日志来看，可能是连接被 GFW 干扰或屏蔽了。建议你另外尝试其他的解决方案比如 Shadowsocks。

**Comment by SourceKim** [comment]
> VPS 换 IP 立即可以工作，但过不了半天就会被阻断。

请教一下有什么解决方案吗？
