### ISSUE TITLE
安卓连接 no acceptable Oakley Transform，苹果可成功

### ISSUE THREAD

**Issue by Lunkeqing** [hwdsl2/setup-ipsec-vpn#1244]
背景：
苹果可以连接成功 L2TP or IPSec
安卓不可以，且排除了同一局域网的场景（使用手机5G流量）
client端配置没有变化，以前使用的IPSec Xauth PSK 可以连接成功。今天遇到点问题，重装系统，重新下载执行过脚本。之前可能用的是2020年版本的脚本了。

以下有两种模式的日志，包括IPSec Xauth PSK 以及 L2TP/IPSec PSK.

IPSec Xauth PSK 如下：

Oct  4 02:42:13 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: message repeated 6 times: [ "xauth-psk"[1] 116.162.94.109 #1: discarding initial packet; already STATE_MAIN_R0]
Oct  4 02:46:04 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #2: responding to Main Mode from unknown peer 116.162.94.109:808
Oct  4 02:46:04 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #2: Oakley Transform [AES_CBC (256), HMAC_SHA2_384, MODP1024] refused
Oct  4 02:46:04 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #2: Oakley Transform [AES_CBC (256), HMAC_SHA2_256, MODP1024] refused
Oct  4 02:46:04 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #2: WARNING: connection xauth-psk PSK length of 26 bytes is too short for HMAC_SHA2_512 PRF in FIPS mode (32 bytes required)
Oct  4 02:46:04 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #2: Oakley Transform [AES_CBC (256), HMAC_SHA2_512, MODP1024] refused
Oct  4 02:46:04 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #2: Oakley Transform [AES_CBC (256), HMAC_SHA1, MODP1024] refused
Oct  4 02:46:04 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #2: Oakley Transform [AES_CBC (256), HMAC_MD5, MODP1024] refused
Oct  4 02:46:04 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #2: WARNING: connection xauth-psk PSK length of 26 bytes is too short for HMAC_SHA2_512 PRF in FIPS mode (32 bytes required)
Oct  4 02:46:04 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #2: Oakley Transform [AES_CBC (128), HMAC_SHA2_512, MODP1024] refused
Oct  4 02:46:04 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #2: Oakley Transform [AES_CBC (128), HMAC_SHA2_384, MODP1024] refused
Oct  4 02:46:04 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #2: Oakley Transform [AES_CBC (128), HMAC_SHA2_256, MODP1024] refused
Oct  4 02:46:04 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #2: Oakley Transform [AES_CBC (128), HMAC_SHA1, MODP1024] refused
Oct  4 02:46:04 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #2: Oakley Transform [AES_CBC (128), HMAC_MD5, MODP1024] refused
Oct  4 02:46:04 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #2: Oakley Transform [3DES_CBC (192), HMAC_SHA2_256, MODP1024] refused
Oct  4 02:46:04 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #2: Oakley Transform [3DES_CBC (192), HMAC_SHA1, MODP1024] refused
Oct  4 02:46:04 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #2: Oakley Transform [3DES_CBC (192), HMAC_MD5, MODP1024] refused
Oct  4 02:46:04 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #2: OAKLEY_DES_CBC(UNUSED) is not supported.  Attribute OAKLEY_ENCRYPTION_ALGORITHM
Oct  4 02:46:04 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: message repeated 2 times: [ "xauth-psk"[1] 116.162.94.109 #2: OAKLEY_DES_CBC(UNUSED) is not supported.  Attribute OAKLEY_ENCRYPTION_ALGORITHM]
Oct  4 02:46:04 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #2: no acceptable Oakley Transform
Oct  4 02:46:04 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #2: sending notification NO_PROPOSAL_CHOSEN to 116.162.94.109:808
Oct  4 02:46:07 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #2: discarding initial packet; already STATE_MAIN_R0

=====

L2TP/IPSec PSK日志如下：

Oct  4 02:53:45 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #3: responding to Main Mode from unknown peer 116.162.94.109:814
Oct  4 02:53:45 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #3: Oakley Transform [AES_CBC (256), HMAC_SHA2_384, MODP1024] refused
Oct  4 02:53:45 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #3: Oakley Transform [AES_CBC (256), HMAC_SHA2_256, MODP1024] refused
Oct  4 02:53:45 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #3: WARNING: connection xauth-psk PSK length of 26 bytes is too short for HMAC_SHA2_512 PRF in FIPS mode (32 bytes required)
Oct  4 02:53:45 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #3: Oakley Transform [AES_CBC (256), HMAC_SHA2_512, MODP1024] refused
Oct  4 02:53:45 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #3: Oakley Transform [AES_CBC (256), HMAC_SHA1, MODP1024] refused
Oct  4 02:53:45 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #3: Oakley Transform [AES_CBC (256), HMAC_MD5, MODP1024] refused
Oct  4 02:53:45 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #3: WARNING: connection xauth-psk PSK length of 26 bytes is too short for HMAC_SHA2_512 PRF in FIPS mode (32 bytes required)
Oct  4 02:53:45 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #3: Oakley Transform [AES_CBC (128), HMAC_SHA2_512, MODP1024] refused
Oct  4 02:53:45 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #3: Oakley Transform [AES_CBC (128), HMAC_SHA2_384, MODP1024] refused
Oct  4 02:53:45 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #3: Oakley Transform [AES_CBC (128), HMAC_SHA2_256, MODP1024] refused
Oct  4 02:53:45 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #3: Oakley Transform [AES_CBC (128), HMAC_SHA1, MODP1024] refused
Oct  4 02:53:45 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #3: Oakley Transform [AES_CBC (128), HMAC_MD5, MODP1024] refused
Oct  4 02:53:45 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #3: Oakley Transform [3DES_CBC (192), HMAC_SHA2_256, MODP1024] refused
Oct  4 02:53:45 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #3: Oakley Transform [3DES_CBC (192), HMAC_SHA1, MODP1024] refused
Oct  4 02:53:45 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #3: Oakley Transform [3DES_CBC (192), HMAC_MD5, MODP1024] refused
Oct  4 02:53:45 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #3: OAKLEY_DES_CBC(UNUSED) is not supported.  Attribute OAKLEY_ENCRYPTION_ALGORITHM
Oct  4 02:53:45 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: message repeated 2 times: [ "xauth-psk"[1] 116.162.94.109 #3: OAKLEY_DES_CBC(UNUSED) is not supported.  Attribute OAKLEY_ENCRYPTION_ALGORITHM]
Oct  4 02:53:45 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #3: no acceptable Oakley Transform
Oct  4 02:53:45 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #3: sending notification NO_PROPOSAL_CHOSEN to 116.162.94.109:814
Oct  4 02:53:48 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #3: discarding initial packet; already STATE_MAIN_R0

**Comment by Lunkeqing** [comment]
> On Mon, 3 Oct 2022, Lunkeqing wrote: Oct 4 02:42:13 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: message repeated 6 times: [ "xauth-psk"[1] 116.162.94.109 #1: discarding initial packet; already STATE_MAIN_R0] Oct 4 02:46:04 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #2: responding to Main Mode from unknown peer 116.162.94.109:808 Oct 4 02:46:04 iZj6c2svm6ds06un4uzhdkZ pluto[16953]: "xauth-psk"[1] 116.162.94.109 #2: Oakley Transform [AES_CBC (256), HMAC_SHA2_384, MODP1024] refused
> All of your proposals use DiffieHellman group 1, which is no longer supported as it is _way_ to weak. Please at the least make the client use DH5. Paul

Really thanks for the reply. The client is my phone of android(Huawei Harmony actually), which i have no access to modify any protocol settings. i will considering upgrade the OS version and try it out

**Comment by hwdsl2** [comment]
@Lunkeqing Hello! To improve security, DH group 1 (modp1024) has recently been disabled in the default configuration of the VPN setup scripts. Android users can instead connect using IKEv2 mode (recommended) [1].

If you still want to connect from an Android device using IPsec/L2TP or IPsec/XAuth ("Cisco IPsec") mode, see [2] [3] for instructions (not recommended).

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md
[3] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md
