### ISSUE TITLE
Route L2TP clients traffic through SSH tunnel

### ISSUE THREAD

**Issue by AuthorShin** [hwdsl2/setup-ipsec-vpn#1246]
Hi
Is there a way to SSH tunnel the traffic of the L2TP server to another server? like when we use sshuttle to tunnel to another server via SSH but this time in a way that the traffic of L2TP clients are also route through that. 
Thanks in advance

**Comment by hwdsl2** [comment]
@AuthorShin Hello! Unfortunately, I am not aware of a method to SSH tunnel the traffic of the L2TP server to another server.
