### ISSUE TITLE
Pluto is not running (no "/run/pluto/pluto.ctl")

### ISSUE THREAD

**Issue by beliaev-maksim** [hwdsl2/setup-ipsec-vpn#1248]
I am running an ubuntu server 20.04 LTS

it looks like there was a scheduled ubuntu update which caused VPN not to start any more. (before that I had a stable work of VPN for more than a year.
```
$ sudo ipsec verify
Verifying installed system and configuration files

Version check and ipsec on-path                         [OK]
Libreswan 4.6 (XFRM) on 5.4.0-126-generic
Checking for IPsec support in kernel                    [OK]
 NETKEY: Testing XFRM related proc values
         ICMP default/send_redirects                    [OK]
         ICMP default/accept_redirects                  [OK]
         XFRM larval drop                               [OK]
Pluto ipsec.conf syntax                                 [OK]
Checking rp_filter                                      [OK]
Checking that pluto is running                          [FAILED]
Checking 'ip' command                                   [OK]
Checking 'iptables' command                             [OK]
Checking 'prelink' command does not interfere with FIPS [OK]
Checking for obsolete ipsec.conf options                [OK]

ipsec verify: encountered 2 errors - see 'man ipsec_verify' for help
```

```
$ sudo ipsec status
whack: Pluto is not running (no "/run/pluto/pluto.ctl")
```

as per #1123 I did `sudo ipsec pluto` which recovered the VPN.

Just wanted to inform you that the ipsec script might require an update for the latest updates.

**Comment by hwdsl2** [comment]
@beliaev-maksim Hello! Thank you for letting us know. Do you see any errors in the IPsec logs? Check using `grep pluto /var/log/auth.log`.

**Comment by beliaev-maksim** [comment]
nothing really unusal, I see:
`"ikev2-cp"[338]  #688: kernel: xfrm XFRM_MSG_DELPOLICYdelete(UNUSED) response for flow (in): No such file or directory (errno 2)`

`ERROR: asynchronous network error report on eno1 (<ip>:4500), complainant <IP>: No route to host [errno 113, origin ICMP type 3 code 1 (not authenticated)]`

but I see this errors also for the older dates, so, do not think it caused this issue

**Comment by hwdsl2** [comment]
@beliaev-maksim I tested on a new Ubuntu 20.04 system and the IPsec VPN (Libreswan) runs fine both before and after `apt-get update && apt-get dist-upgrade` and a reboot. So I couldn't reproduce this issue.

Since your logs don't show anything unusual, I suspect that this may be an issue with your specific system, due to things like out of memory during the system update, or other reasons.

**Comment by beliaev-maksim** [comment]
Interesting that after reboot it still does not work until I manually  run pluto. So, I have to do it every boot
