### ISSUE TITLE
Deploy fail when deploying vpnserver/installcustomscript

### ISSUE THREAD

**Issue by ruijieshi** [hwdsl2/setup-ipsec-vpn#1251]
A failure message shows up for step vpnserver/installcustomscript:

{
    "status": "Failed",
    "error": {
        "code": "VMExtensionProvisioningError",
        "message": "VM 在处理扩展“installcustomscript”时报告了故障。错误消息:“Enable failed: failed to execute command: command terminated with exit status=1\n[stdout]\n## VPN setup in progress... Please be patient.\n## Installing packages required for setup...\n\n[stderr]\n2022-10-10 04:57:16 URL:https://raw.githubusercontent.com/hwdsl2/setup-ipsec-vpn/master/vpnsetup.sh [9648/9648] -> \"vpn.sh\" [1]\n+ wget -t 3 -T 30 -q -O /tmp/vpn.U3rD6/vpn.sh https://github.com/hwdsl2/setup-ipsec-vpn/raw/master/vpnsetup_ubuntu.sh\n+ apt-get -yqq update\n+ apt-get -yqq install wget dnsutils openssl iptables iproute2 gawk grep sed net-tools\nE: Unable to locate package net-tools\n+ apt-get -yqq install wget dnsutils openssl iptables iproute2 gawk grep sed net-tools\nE: Unable to locate package net-tools\nError: 'apt-get install' failed.\n”\r\n\r\n有关故障排除的详细信息，请访问 https://aka.ms/VMExtensionCSELinuxTroubleshoot"
    }
}

**Comment by hwdsl2** [comment]
@ruijieshi Hello! The package `net-tools` is available in both Ubuntu and Debian:
https://packages.ubuntu.com/search?keywords=net-tools&searchon=names
https://packages.debian.org/search?keywords=net-tools

Please retry the deployment. This error is most likely caused by temporary apt-get mirror or cache issues on your server.

**Comment by TingtingAn** [comment]
@ruijieshi   你好，请问怎么处理的？ 我也遇到这个问题了。

**Comment by ruijieshi** [comment]
@LuoyeAn 我换了westus区域成功了。
