### ISSUE TITLE
关于项目，有三个问题，希望项目大大能帮助解答。 I have 3 questions for this project, Can you help me ?

### ISSUE THREAD

**Issue by Johintim** [hwdsl2/setup-ipsec-vpn#1252]
1.默认使用下面命令配置的VPN，最大支持几个设备同时连接？
wget https://get.vpnsetup.net -O vpn.sh && sudo sh vpn.sh

2. 如何查看，VPN服务启动成功了？
是通过netstat -anp， 查看4500端口吗？

3. 是否可以通过什么脚本重启VPN服务？

English
1. When I use the default commad to config the VPN, How many devices are supported at the same user?
The default commad is below
wget https://get.vpnsetup.net -O vpn.sh && sudo sh vpn.sh

2. How do I check whether the VPN server is started successfully?
use netstat -anp , if the  4500 port is open?

3.Can I use some script to restart the VPN service in my machine?

**Comment by Johintim** [comment]
由于我也遇到了，无法连接的问题。发生了两次，这次是第二次。
第一次(2022/10/9)：
我的排查思路是，首先测试了我的机器ip，是否已经被ban。发现，确实使用xshell，无法连接。
所以我选择了，跟换ip，和重装系统，再重配VPN。
问题解决。
第二次(2022/10/10):
我还是按照了上述的排查思路，发现IP没有被ban，一些端口也能访问
so the issue is block now.
所以有了上面的3个问题。

**Comment by Johintim** [comment]
我是使用StrongSwan去连接。
报错信息是。无法建立VPN：服务器地址无法连接
some error log
`[IKE] giving up after 3 retransmits
[IKE] establishing IKE_SA failed, peer not responding
[IKE] unable to terminate IKE_SA: ID 4 not found
`

**Comment by hwdsl2** [comment]
@Johintim 你好！关于你的问题：
1. 同时连接的项目数 Libreswan 没有限制，但受限于你的服务器的 CPU，内存和网络带宽等。默认的 VPN 子网支持 241 个设备。
2. 你可以使用这些命令比如 `sudo service ipsec status`, `sudo ipsec status`, `sudo ipsec verify`, `grep pluto /var/log/auth.log /var/log/secure` 也可以使用 `netstat` 检查 UDP 端口 500 和 4500。
3. `sudo service ipsec restart; sudo service xl2tpd restart`

另外 IPsec 较容易被 GFW 干扰，建议你另外尝试比如 Shadowsocks。

**Comment by gdjisworking** [comment]
> @Johintim 你好！关于你的问题：
> 
> 1. 同时连接的设备数量 Libreswan 没有限制，但受限于你的服务器的 CPU，内存和网络带宽等。默认的 VPN 子网支持 241 个设备。
> 2. 你可以使用这些命令比如 `sudo service ipsec status`, `sudo ipsec status`, `sudo ipsec verify`, `grep pluto /var/log/auth.log /var/log/secure` 也可以使用 `netstat` 检查 UDP 端口 500 和 4500。
> 3. `sudo service ipsec restart; sudo service xl2tpd restart`
> 
> 另外 IPsec 较容易被 GFW 干扰，建议你另外尝试比如 Shadowsocks。

你好我们配置里面可以修改默认的4500和500端口吗？

**Comment by gdjisworking** [comment]
因为默认端口4500和500经常会被防火墙封禁，能否自定义呢？

**Comment by hwdsl2** [comment]
@gdjisworking 目前 IPsec VPN 不支持修改默认的500和4500端口。
