### ISSUE TITLE
开机自启

### ISSUE THREAD

**Issue by accp309** [hwdsl2/setup-ipsec-vpn#1253]
如何设置 开机自启

**Comment by hwdsl2** [comment]
@accp309 你好！VPN 安装脚本默认会配置开机启动 Libreswan 和 xl2tpd，无需另外的步骤。

**Comment by accp309** [comment]
好的，最近不知是不是20大，连不上了……服务器倒是可以连上

**Comment by accp309** [comment]
请问哪里可以看日志？

**Comment by hwdsl2** [comment]
@accp309 https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status

**Comment by accp309** [comment]
> 

![image](https://user-images.githubusercontent.com/10875681/196364837-3ba1f254-bf24-414f-b5f0-f58dd8fdc7f5.png)
这个是什么意思==？

**Comment by Johintim** [comment]
如果IP可以连上，但是VPN用不了，那么可能就是端口被封了。推荐换IP
