### ISSUE TITLE
How to configure L2TP login authentication to use certificate + pre-shared key instead of account password + pre-shared key

### ISSUE THREAD

**Issue by putianhui** [hwdsl2/setup-ipsec-vpn#1258]
After the successful installation of the service, I get the following L2TP connection information
This is the authentication method of pre shared key+account password
```bash
================================================
IPsec VPN server is now ready for use!
Connect to your new VPN with these details:

Server IP: 1.1.1.1
IPsec PSK: xxxxxxxxxxxxxxxxxxxxxx
Username: vpnuser
Password: xxxxxxxxxxxxxxxxxxxx

Write these down. You'll need them to connect!
VPN client setup: https://vpnsetup.net/clients
================================================
```

How do I configure to log in using the authentication method of pre shared key+certificate?
<img width="531" alt="image" src="https://user-images.githubusercontent.com/68322685/197438049-b0ade80d-e27e-48fb-85db-51a8d54625a5.png">

**Comment by hwdsl2** [comment]
@putianhui Hello! Using certificate + pre-shared key is not supported in this project. It is recommended to connect using [IKEv2 mode](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md) which uses certificate-based authentication.
