### ISSUE TITLE
Can't connect to VPN server in Oracle Cloud after successfully setup

### ISSUE THREAD

**Issue by fanlessfan** [hwdsl2/setup-ipsec-vpn#1259]
This is fantastic script.

I successfully install the VPN server on the Oracle Cloud VM [Oracle-Linux-8.5-aarch64-2022.03.17-1] and successfully import the vpnclient.mobileconfig to my iPhone (IOS 16.1). But the iPhone can't connect to the VPN server. I use another tool to verify that there is only port 22 (ssh) open on the VPN server by default. Oracle close everything else. I have to open the ICMP ping for me to check if the VM is running or not. Do you know which port need to open on the Oracle Cloud firewall for IKEv2 VPN?

Thanks.

**Comment by hwdsl2** [comment]
@fanlessfan Hello! For servers with an external firewall, please open UDP ports 500 and 4500 for the IPsec VPN. After which you should be able to connect.
