### ISSUE TITLE
Script doesn't handle interfaces named in "ens??" format

### ISSUE THREAD

**Issue by swy** [hwdsl2/setup-ipsec-vpn#126]
On first run of this script on an Ubuntu 16.04.2 LTS VPS I just provisioned, it errored due to eth0 not being available.  An audit of line 70 explains why- it's written to expect the "ethX" format, but the VPS provided network interface in the "ensXX" format.  To address this, I edited line 70 to match my VPS ens18, and ran the script.
This ran successfully, yielded an endpoint I could authenticate to, but ended up in iptables rules that had no exit route for traffic, seeking nonexistent "eth+" as an exit route.
Auditing line 71 to match the declared interface name yielded iptables rules that could route traffic properly.

**Comment by hwdsl2** [comment]
@swy Thanks for the report. However, the script already provides a workaround for this use case. You just need to run the two commands in the output at the time when you first run the script:

```
Error: Network interface 'eth0' is not available.

DO NOT RUN THIS SCRIPT ON YOUR PC OR MAC!

If running on a server, try this workaround:

VPN_IFACE="$(route | grep '^default' | grep -o '[^ ]*$')"
sudo VPN_IFACE="$VPN_IFACE" sh vpnsetup.sh
```

And if you want to modify the script manually, you must replace both the `eth0` on line 70, and the `eth+` on line 71. But the above workaround provided by the script is easier.

**Comment by swy** [comment]
Got it, thanks.  Any reason why the interface isn't grepped out of route and assigned to VPN_IFACE by default, vs being steps for the user to take in an error condition?

**Comment by hwdsl2** [comment]
@swy This was intended to further prevent users from accidentally running the VPN setup script on their PC or laptop (with Wi-Fi).
