### ISSUE TITLE
希望增加"VPN服务器网段内其它机器访问VPN客户端"的指导

### ISSUE THREAD

**Issue by Sebavid** [hwdsl2/setup-ipsec-vpn#1262]
你好，我使用脚本部署完成之后可以通过客户端访问服务端及服务端网段内其它机器。
但是我有个需求是需要服务器网段内其它机器访问客户端，我看到#420提过类似问题，我按照执行iptables -I FORWARD 2 -i ens192 -o ppp+ -s 10.1.0.0/16 -j ACCEPT 之后不起效果。

场景：
vpn服务器：10.1.5.253
启动服务端：VPN_XAUTH_NET=10.1.0.0/16 VPN_XAUTH_POOL=10.1.5.10-10.1.5.99 sh vpn.sh
vpn客户端：10.1.5.10
vpn服务器网段其它机器：10.1.5.117
现状：10.1.5.10能够访问10.1.5.117，但是10.1.5.117不能访问10.1.5.10

请问vpn服务器网段内的10.1.5.117如何才能访问vpn客户端10.1.5.10，谢谢

**Comment by hwdsl2** [comment]
@Sebavid 你好！VPN 服务器网段内其它机器并不知道到 VPN 客户端的路由，即使它们在同一个网段。你可以尝试在 VPN 服务器网段内其它机器上添加路由，同时也添加你所说的 IPTables 规则。示例请参见 #1121。如果你有新的信息可以继续在这里回复。

**Comment by Sebavid** [comment]
谢谢，已解决。
vpn服务器：10.1.5.253
1、安装：VPN_XAUTH_NET=10.1.6.0/16 VPN_XAUTH_POOL=10.1.6.10-10.1.6.99 sh vpn.sh
2、添加规则：iptables -I FORWARD 2 -i ens192 -o ppp+ -s 10.1.0.0/16 -j ACCEPT
3、公司局域网内其它机器添加路由：route add -net 10.1.6.0 netmask 255.255.255.0 gw 10.1.5.253 dev ens192
第三步测试通过之后，公司工程师在交换机上加了条规则，就不用每台机器添加路由了。
完成：VPN服务器网段内其它机器可以访问VPN客户端

**Comment by Yuwenchengdu** [comment]
> 谢谢，已解决。 vpn服务器：10.1.5.253 1、安装：VPN_XAUTH_NET=10.1.6.0/16 VPN_XAUTH_POOL=10.1.6.10-10.1.6.99 sh vpn.sh 2、添加规则：iptables -I FORWARD 2 -i ens192 -o ppp+ -s 10.1.0.0/16 -j ACCEPT 3、公司局域网内其它机器添加路由：route add -net 10.1.6.0 netmask 255.255.255.0 gw 10.1.5.253 dev ens192 第三步测试通过之后，公司工程师在交换机上加了条规则，就不用每台机器添加路由了。 完成：VPN服务器网段内其它机器可以访问VPN客户端

第3条，目标网段是10.1.6.0/24吧？
