### ISSUE TITLE
Cannot connect to vpn after successful setup

### ISSUE THREAD

**Issue by mamdos** [hwdsl2/setup-ipsec-vpn#1263]
hi 
I setup the vpn successfully but i can't connect to it an any of my devices and encounter to this error on windows.
how can I fix that ?
![Screenshot 2022-11-01 190210](https://user-images.githubusercontent.com/53936241/199300875-1786d1dd-6033-41f9-97fd-3ccb186c8d30.png)

**Comment by hwdsl2** [comment]
@mamdos Hello! If your server has an external firewall, open UDP ports 500 and 4500 for the VPN. This error could indicate network issues between the VPN client and server. For example, the VPN connection may be blocked in certain countries. In that case, you may want to try alternative solutions such as Shadowsocks.
