### ISSUE TITLE
how to check which user is logon vpn

### ISSUE THREAD

**Issue by fanlessfan** [hwdsl2/setup-ipsec-vpn#1264]
Thank you for make this script to make setting up vpn server so easy. I read the whole document and didn't find how to find out which user is currently logon to the vpn server. Could you let me know? THX

**Comment by hwdsl2** [comment]
@fanlessfan Hello! You may try: `sudo ipsec trafficstatus`.  This works for both IKEv2 and IPsec/XAuth ("Cisco IPsec") modes. For IPsec/L2TP mode, usernames won't be displayed, refer to [#317.](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues/317).
