### ISSUE TITLE
cannot connect to vpn

### ISSUE THREAD

**Issue by kevinliukaiwen** [hwdsl2/setup-ipsec-vpn#1265]
after set ikev2 on my iphone ,i cant connect to vpn,
i've read the help log but find nothing,

Nov  4 05:59:25 vultr pluto[1676]: "ikev2-cp"[1] 114.87.242.114 #1: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 4 seconds for response
Nov  4 05:59:25 vultr pluto[1676]: "ikev2-cp"[2] 114.87.242.114 #3: IKE_AUTH request fragment 1 of 4 has duplicate Message ID 1; retransmitting response
Nov  4 05:59:29 vultr pluto[1676]: "ikev2-cp"[1] 114.87.242.114 #1: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 8 seconds for response
Nov  4 05:59:29 vultr pluto[1676]: "ikev2-cp"[2] 114.87.242.114 #3: IKE_AUTH request fragment 1 of 4 has duplicate Message ID 1; retransmitting response
Nov  4 05:59:37 vultr pluto[1676]: "ikev2-cp"[1] 114.87.242.114 #1: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 16 seconds for response
Nov  4 05:59:37 vultr pluto[1676]: "ikev2-cp"[2] 114.87.242.114 #3: IKE_AUTH request fragment 1 of 4 has duplicate Message ID 1; retransmitting response
Nov  4 05:59:53 vultr pluto[1676]: "ikev2-cp"[1] 114.87.242.114 #1: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 32 seconds for response
Nov  4 05:59:54 vultr pluto[1676]: "ikev2-cp"[2] 114.87.242.114 #3: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 0.5 seconds for response
Nov  4 05:59:54 vultr pluto[1676]: "ikev2-cp"[2] 114.87.242.114 #3: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 1 seconds for response
Nov  4 05:59:55 vultr pluto[1676]: "ikev2-cp"[2] 114.87.242.114 #3: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 2 seconds for response
Nov  4 05:59:57 vultr pluto[1676]: "ikev2-cp"[2] 114.87.242.114 #3: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 4 seconds for response
Nov  4 06:00:01 vultr pluto[1676]: "ikev2-cp"[2] 114.87.242.114 #3: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 8 seconds for response
Nov  4 06:00:09 vultr pluto[1676]: "ikev2-cp"[2] 114.87.242.114 #3: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 16 seconds for response
Nov  4 06:00:25 vultr pluto[1676]: "ikev2-cp"[1] 114.87.242.114 #1: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 64 seconds for response
Nov  4 06:00:25 vultr pluto[1676]: "ikev2-cp"[2] 114.87.242.114 #3: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 32 seconds for response
Nov  4 06:00:57 vultr pluto[1676]: "ikev2-cp"[2] 114.87.242.114 #3: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 64 seconds for response
Nov  4 06:01:29 vultr pluto[1676]: "ikev2-cp"[1] 114.87.242.114 #1: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 128 seconds for response
Nov  4 06:02:01 vultr pluto[1676]: "ikev2-cp"[2] 114.87.242.114 #3: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 128 seconds for response

**Comment by hwdsl2** [comment]
@kevinliukaiwen Hello! Your logs show that there may be network issues between the VPN client and server, for example, the connection is blocked by the GFW. You may want to try alternative solutions such as Shadowsocks.

**Comment by dum3ng** [comment]
I have encountered the same issue, but with a litte difference.
At first everything is Ok, but some days later I can not connect anymore, the log info is just the same.
The network has no problem, I can still ssh into the server.

**Comment by hwdsl2** [comment]
@dum3ng It could be due to similar reasons. You may want to instead try e.g. Shadowsocks.
