### ISSUE TITLE
隐私设置错误，您的连接不是私密连接

### ISSUE THREAD

**Issue by wannianxianyu** [hwdsl2/setup-ipsec-vpn#1266]
l2tp、IKEv2 等能连接成功，也能访问百度github等网站，但是却无法访问google youtube等。
重新换了ip也不行，是否是我的服务器配置有什么问题？
![image](https://user-images.githubusercontent.com/24456816/199944128-557336cd-d5f2-40d0-a39e-06c5f0b82bf1.png)

**Comment by hwdsl2** [comment]
@wannianxianyu 你好！这个可能是 DNS 的问题，你的客户端 DNS 缓存可能之前保存了错误的 google youtube 等 IP 地址。你可以尝试重启客户端或清除 DNS 缓存。另外，可以尝试在网络连接属性 -> TCP/IPv4 中手动输入 DNS 服务器，参见这个链接中的第3项：
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#%E8%BF%9E%E6%8E%A5-ikev2-%E5%90%8E%E4%B8%8D%E8%83%BD%E6%89%93%E5%BC%80%E7%BD%91%E7%AB%99
