### ISSUE TITLE
Fix IKEv2 issue on windows

### ISSUE THREAD

**Issue by darwincr** [hwdsl2/setup-ipsec-vpn#1268]
Thank you very much for your scripts they worked very well for me

In the windows VPN Client i had an issue, the fix to the vpn client was not covered in your documentation

The error message on eventviewer was

"CoId={6895FC76-F2F6-0000-C953-9668F6F2D801}: The user xxxxx\yyyyyy dialed a connection named Home-IKEv2 which has failed. The error code returned on failure is 87."

the steps below fixed the issue with IKEv2 VPN Client on Windows 10 for me
https://github.com/trailofbits/algo/issues/1051

- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [x] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
A clear and concise description of your enhancement request.

**Is your enhancement request related to a problem? Please describe.**
(If applicable) A clear and concise description of what the problem is.

**Additional context**
Add any other context about the enhancement request here.

**Comment by hwdsl2** [comment]
@darwincr Hello! Thanks for sharing! I can add this to the troubleshooting section.
