### ISSUE TITLE
push routes to clients

### ISSUE THREAD

**Issue by mw-cyrano** [hwdsl2/setup-ipsec-vpn#1269]
As documented [here](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#access-vpn-servers-subnet), one can configure a NAT to the server's private network.

Works fine. But by default, the vpn clients aren't given a static route to this network via DHCP. So they don't know about it and try to reach the private network via their default gateway, not to the vpn server.

The builtin xl2tpd dhcp would need a SendOption for that or it needs to be disabled and you'd need a separate DHCP server.

What's the best practice for this? I checked the man pages and didn't find an option for either way.

**Comment by hwdsl2** [comment]
@mw-cyrano Hello! Unfortunately I am not sure about this. Please ask in the relevant community or the Libreswan/strongSwan users mailing list. As you mentioned, the currently working solution is to configure a NAT for this use case.

**Comment by mw-cyrano** [comment]
No, there is no working solution, as you'd have to configure the route to the network on each client, which isn't even possible on Mac via the graphical interface. How do others in the project work around this?

**Comment by hwdsl2** [comment]
Others are welcome to comment on this issue if you have thoughts. @mw-cyrano When I tested this using these instructions I added [1], I did not need to add static routes on the VPN clients for it to work. By default, when connected to the VPN, clients send all traffic through the VPN server, so the NAT rules added should take care of this.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#access-vpn-servers-subnet

**Comment by mw-cyrano** [comment]
> By default, when connected to the VPN, clients send all traffic through the VPN server, so the NAT rules added should take care of this.

That is one way to configure it, but you'll route all traffic including the video conferences through your company network, which is unnecessary and a bottle neck.

We usually configure a VPN only for our internal services. So the default route doesn't point into the VPN.

**Comment by hwdsl2** [comment]
@mw-cyrano That makes sense. Yes I can leave this open for a period of time, so others have a chance to comment if they have thoughts on your use case.

**Comment by letoams** [comment]
On Sun, 13 Nov 2022, Lin Song wrote:

> Others are welcome to comment on this issue if you have thoughts. @mw-cyrano When I tested this using these instructions I added [1], I did not need to
> add static routes on the VPN clients for it to work. By default, when connected to the VPN, clients send all traffic through the VPN server, so the NAT
> rules added should take care of this.

Instead of 0.0.0.0/0 you can set a smaller network to split the tunnel
for only corporate resources. Specifying more than one subnet currently
is tricky and might not work for all cases.

**Comment by mw-cyrano** [comment]
The NAT is not the problem. You can NAT an arbitrary amount of networks on the server. The problem are the routes on the clients. They do not know anything about the company's private IP space.

Example:
transport network in the vpn: 192.168.42.0/24
company network: 10.99.0.0/16

A vpn client will have a routing table like this:
default via <your home router's ip>
192.168.42.1 dev ppp0 #device route vpn adapter
<vpn-server-ip> via <home router's ip>

And that's about it. Everything destined to 10.99.0.0/16 will go along the default route. Not your vpn server, as the client's do not know the route. Yes can set them manually, but proprietary solutions like Sophos do not need that. They push the routes via DHCP-options. And I fail to do that as xl2tpd brings a crippled DHCP server, that doesn't seem to be able to do that.

Cross reference: https://github.com/xelerance/xl2tpd/issues/251

**Comment by wilkolazki** [comment]
[This superuser answer](https://superuser.com/questions/12022/how-can-i-make-the-windows-vpn-route-selective-traffic-by-destination-network#1289149) suggest using `Add-VpnConnectionRoute` to achieve this goal.

I have incorporated this in the client setup script by adding:
```

echo Setting routes...
powershell -command "Add-VpnConnectionRoute -ConnectionName '%conn_name%' -DestinationPrefix 172.26.0.0/16"
if !errorlevel! neq 0 (
  echo ERROR: Could not set routing configuration for the IKEv2 VPN connection.
  goto :Done
)
```
... after `Set-VpnConnectionIPsecConfiguration` call. 

Sadly, while I was able to add a route to my nework, I cannot stop system from stealing default route.

**Comment by mw-cyrano** [comment]
This again seems to be a client based workaround. We have that working, we are not looking for a workaround. We are trying to resolve the issue properly. And the proper solution is to push the routes from the dhcp-server. And therefore we need to setup a proper DHCP-server.

**Comment by hwdsl2** [comment]
Thanks all for contributing ideas. @mw-cyrano For your use case (split tunneling and push routes to clients), it looks like the VPN setup scripts couldn't support it, as the issue may be on the xl2tpd side. I see that you've opened https://github.com/xelerance/xl2tpd/issues/251. I'll go ahead and close this issue, you can follow up on the linked xl2tpd issue.
