### ISSUE TITLE
Route local traffic through VPN server

### ISSUE THREAD

**Issue by nodesocket** [hwdsl2/setup-ipsec-vpn#127]
Is it possible to route traffic locally through the VPN server? E.G. running the VPN server at home and route all devices at home through it.

![screen shot 2017-04-01 at 9 07 27 pm](https://cloud.githubusercontent.com/assets/523312/24584334/4a7ddaca-171f-11e7-80f9-8c0d63743fb9.png)

**Comment by hwdsl2** [comment]
@nodesocket Hello! Not sure if this is what you want, but you should be able to connect to the VPN server's private (local) IP using your VPN clients. If you do this for all devices in your home, then their traffic would be all routed through the VPN server. Although I don't see the benefits of this, as the devices would have the same public IP as without the VPN.

If you are unable to connect using the server's private IP, note that this functionality was recently added in commit 0300707. Check your /etc/ipsec.secrets file, and if you see the server's public IP as the first field, then were are using a version of the setup script prior to that commit. You may try downloading and re-run the latest version of the script.

**Comment by nodesocket** [comment]
The idea is to encrypt traffic before heading out to my ISP. Would that work using the local addr of the VPN server?

**Comment by hwdsl2** [comment]
@nodesocket No, that would not achieve what you want. Your connections would look like this, and all traffic going out from the VPN server to the Internet are not encrypted.

```
             encrypted               Not encrypted               Not encrypted
VPN client -------------- VPN server -------------- home router -------------- Internet
(10.0.0.210)                    (10.0.0.220)                       (10.0.0.1)

```

**Comment by nodesocket** [comment]
Gotcha. So that setup only encrypts between the client and VPN server, which in this case is not very useful.

**Comment by hwdsl2** [comment]
@nodesocket Yes, that is correct.

**Comment by nodesocket** [comment]
Let me ask this. If my home router supports site-to-site VPN, and I configure the route to VPN back to `10.0.0.210` would that make any difference? No right?

**Comment by hwdsl2** [comment]
@nodesocket No, that would not make any difference. In addition, I think such a setup may create routing loops. I would suggest that you instead set up a server outside your home network for this purpose.
