### ISSUE TITLE
VPN映射端口问题，请赐教。

### ISSUE THREAD

**Issue by sixnqs** [hwdsl2/setup-ipsec-vpn#1271]
感谢您的文档让我成功搭建VPN、咨询下

想要将 VPN 服务器上的端口转发到一个已连接的 VPN 客户端。通过在 VPN 服务器上添加 IPTables 规则如何实现呢？

我需要把VPN服务器全部端口映射到VPN客户端上如何实现呢？

我所使用的是 L2TP、IKEV2，能否代码举例说明下、感谢。

**Comment by hwdsl2** [comment]
@sixnqs 你好！在连接到 VPN 时，客户端可以访问 VPN 服务器上的端口，无需另外的配置。

如果你的用例是映射端口到 VPN 客户端本身，例如让客户端可以使用比如 127.0.0.1:80 访问 VPN 服务器上的 Web 服务，该功能无法通过 IPsec VPN 实现，但你可以另外尝试比如 SSH 端口转发。

请参见：
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#vpn-%E5%86%85%E7%BD%91-ip-%E5%92%8C%E6%B5%81%E9%87%8F
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#%E8%AE%BF%E9%97%AE-vpn-%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9A%84%E7%BD%91%E6%AE%B5

**Comment by helloweizhang** [comment]
我也想实现这样的功能.类似nps或者frp的内网穿透.
就是在VPS搭建一个L2TP的服务器端. 然后客户端用a1用户名连上后自动分配192.168.42.20的IP给它
服务器上做iptalbles转发. 将5000的端口转发到192.168.42.20这个L2tp的IP
然后我群晖nas登录这个a1账号 .就可以实现无公网情况下通过VPS的5000端口访问群晖NAS

但是我按照教程来做.却一直都不成功. 不知道问题在哪里
