### ISSUE TITLE
IKEV2链接无法访问互联网

### ISSUE THREAD

**Issue by sixnqs** [hwdsl2/setup-ipsec-vpn#1272]
请问我按照脚本假设的VPN用安卓12版本运行IKEV2可以链接成功但是不能访问互联网，有时可以有时不行。
用其他手机的L2TP网络就没有问题、请赐教

另外想咨询下脚本是否支持  IKEV2/IPSec PSK链接、如果可以有没有可以参考的设置文档
服务器的带宽完全够用。

感谢！！！

**Comment by hwdsl2** [comment]
@sixnqs 你好！这个可能是网络不稳定或者 MTU/MSS 问题。请尝试这个链接中的解决方案 2：
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#%E8%BF%9E%E6%8E%A5-ikev2-%E5%90%8E%E4%B8%8D%E8%83%BD%E6%89%93%E5%BC%80%E7%BD%91%E7%AB%99

本项目不支持 IKEv2 PSK。你可以在这里找到 Libreswan 的一些配置示例和文档：
https://libreswan.org/wiki/Configuration_examples
https://libreswan.org/man/ipsec.conf.5.html

**Comment by sixnqs** [comment]
> @sixnqs你好！这个可能是网络不稳定或者MTU/MSS问题。请尝试这个链接中的解决方案 2: [https://github . com/hwd sl 2/setup-IPSec-VPN/blob/master/docs/ike v2-how to-zh . MD # % E8 % BF % 9E % E6 % 8E % A5-ike v2-% E5 % 90% 8E % E4 % B8 % 8D % E8 % 83% BD % E6 % 89% 93% E5 % BC % 80% E7 % BD % 91% E7 % AB % 99](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#%E8%BF%9E%E6%8E%A5-ikev2-%E5%90%8E%E4%B8%8D%E8%83%BD%E6%89%93%E5%BC%80%E7%BD%91%E7%AB%99)
> 
> 本项目不支持IKEv2·PSK .你可以在这里找到利布雷斯万的一些配置示例和文档： https://libreswan.org/wiki/Configuration_examples https://libreswan.org/man/ipsec.conf.5.html

已经收到您的回复、我尝试下、谢谢

**Comment by sixnqs** [comment]
根据您之前提供的解决方式修改了部分参数、我找到了问题出现的规律、只有晚上才会出现这样的情况、白天通过IKEv2协议链接网络没问题、一到晚上就会出现可以链接但是没有网络的问题，我同时用两部手机测试过的出的结论。请问您这边有收到这样的反馈吗？我是用的默认的设置包括DNS。如果您知道的还望赐教。感谢

**Comment by sixnqs** [comment]
收到您的回复、感谢、我再研究下。
