### ISSUE TITLE
import config for an existing client from another vpn server

### ISSUE THREAD

**Issue by fanlessfan** [hwdsl2/setup-ipsec-vpn#1273]
Thank you @hwdsl2 for this easy to use script. I can use ikev2.sh to add new client and delete existing client successfully. I wonder if we can import an existing client from another vpn server so that a single user can log in to two different servers. Yes, the two vpn servers have the same DNS name.

Thank you again for the fantastic script.

**Comment by hwdsl2** [comment]
@fanlessfan Hello! For your use case: By default, during VPN setup, each VPN server will generate its own IKEv2 VPN CA. This means clients created on different servers are not issued by the same CA, so they are not "interchangeable".

One way to achieve this might be to copy the first server's entire `/etc/ipsec.d` directory to the second server (remove the existing `/etc/ipsec.d` first, be sure to make a backup). Then restart the IPsec service. This way, both servers will have the same IKEv2 VPN CA and same client database. Note that the existing client database will be lost in this process.
