### ISSUE TITLE
脚本执行成功后，通过账号密码登录提示协议不对，换成L2tp或者IPsec也不行 搬瓦工vps  Centos 7 x86_64  

### ISSUE THREAD

**Issue by GODOFZHZ** [hwdsl2/setup-ipsec-vpn#1275]
![image](https://user-images.githubusercontent.com/28758664/202885029-aa7a5d1e-cd56-4e59-b232-00cb79203ce2.png)
![ebc742c36d1c6eefdce333c499b3989](https://user-images.githubusercontent.com/28758664/202885068-5f6f8e89-add3-4abb-a831-d31af7bdf669.jpg)

**Comment by GODOFZHZ** [comment]
[root@admin ~]# ls
virt-sysprep-firstboot.log  vpnclient.mobileconfig  vpnclient.p12  vpnclient.sswan  vpnsetup.sh
[root@admin ~]# ./vpnsetup.sh
-bash: ./vpnsetup.sh: Permission denied
[root@admin ~]# sudo sh vpnsetup.sh
+ wget -t 3 -T 30 -q -O /tmp/vpn.GtKu2/vpn.sh https://raw.githubusercontent.com/hwdsl2/setup-ipsec-vpn/master/vpnsetup_centos.sh
## VPN credentials not set by user. Generating random PSK and password...
## VPN setup in progress... Please be patient.
## Installing packages required for setup...
+ yum -y -q install wget bind-utils openssl tar iptables iproute gawk grep sed net-tools
## Adding the EPEL repository...
+ yum -y -q install epel-release
## Installing packages required for the VPN...
+ yum -y -q install nss-devel nspr-devel pkgconfig pam-devel libcap-ng-devel libselinux-devel curl-devel nss-tools flex bison gcc make util-linux ppp
+ yum --enablerepo=epel -y -q install xl2tpd
+ yum '--enablerepo=*server-*optional*' '--enablerepo=*releases-optional*' -y -q install systemd-devel libevent-devel fipscheck-devel iptables-services
## Installing Fail2Ban to protect SSH...
+ yum --enablerepo=epel -y -q install fail2ban
## Downloading helper scripts...
+ ikev2.sh addvpnuser.sh delvpnuser.sh
## Libreswan 4.9 is already installed, skipping...
## Creating VPN configuration...
## Updating sysctl settings...
## Updating IPTables rules...
## Enabling services on boot...
## Starting services...
sysctl: setting key "net.ipv4.tcp_congestion_control": No such file or directory

================================================

IPsec VPN server is now ready for use!

Connect to your new VPN with these details:

Server IP: 172.xx.xxx.xx
IPsec PSK: SbLsbTznJ2tG9ukGYiiz
Username: vpnuser
Password: poNAR3LHC2jgzEpU

Write these down. You'll need them to connect!

VPN client setup: https://vpnsetup.net/clients

================================================

================================================

IKEv2 is already set up on this server.

Next steps: Configure IKEv2 clients. See:
https://vpnsetup.net/clients

To manage IKEv2 clients, run: sudo ikev2.sh

================================================

**Comment by hwdsl2** [comment]
@你好！这个错误可能是 GFW 屏蔽或干扰导致的。你可以检查 VPN 日志：
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E6%A3%80%E6%9F%A5%E6%97%A5%E5%BF%97%E5%8F%8A-vpn-%E7%8A%B6%E6%80%81

在此情况下，日志中可能有 retransmission 字样。建议你换用其他解决方案比如 Shadowsocks。
