### ISSUE TITLE
ikev2.sh创建出的用户用mobileconfig链接服务器如何设置只允许单点登录

### ISSUE THREAD

**Issue by wangzhenjjcn** [hwdsl2/setup-ipsec-vpn#1279]
**任务列表**

- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)，没有找到类似的改进建议
- [x] 这个改进建议是关于 VPN 安装脚本，而不是 IPsec VPN 本身
- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [x] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)

**描述改进建议**
希望在sh里面增加个便捷设置的选项，比如允许/禁止多点登录，类似这样的

**你的改进建议与遇到的问题有关吗？请描述。**
ikev2.sh创建出的用户配置文件mobileconfig链接服务器目前没有明确的数量限制，可能只有服务器端口或者硬件容量的限制
不知道是否有方法可以设置只允许单IP登录。如果没有这样的设置的话，是否是需要服务器端监测链接来实现
也就是说，设置无法实现需要软件编程实现这个功能，想咨询下，谢谢回复

**其它信息**
添加关于该改进建议的其它信息。

**Comment by hwdsl2** [comment]
@wangzhenjjcn 你好！关于允许/禁止多点登录，据我所知，Libreswan 目前不支持此功能。

另外，有一个选项叫做 uniqueids，可以在 /etc/ipsec.conf 中配置。脚本默认 `uniqueids=no`，你可以改成 `uniqueids=yes` 然后重启 IPsec 服务 `sudo service ipsec restart`。启用该选项后，remote ID 相同（比如使用相同证书登录）的第二个连接将会替换已有的连接，也就是说已有连接会断开。你可以测试一下看看是否对你的用例有帮助。
