### ISSUE TITLE
Phase 1/2 alghoritms might not work, but alternative ones may

### ISSUE THREAD

**Issue by gnysek** [hwdsl2/setup-ipsec-vpn#1281]
https://github.com/hwdsl2/setup-ipsec-vpn/blob/651c404bf6f30f5ba3bd866450a7e0e83b2ca2ad/docs/clients.md?plain=1#L230-L231

For me, on 18.04, I wasn't able to connect using above settings, but when I entered `3des-sha1-modp1024` and `3des-sha1` I've connected (probably depends on router configuration, but maybe it would be good to include alternative configuration?).

**Comment by hwdsl2** [comment]
@gnysek Thank you for your suggestion. The default configuration in the VPN scripts does not support 3DES or MODP1024, so "aes128-sha1" is used in the documentation as you mentioned. Perhaps you've customized /etc/ipsec.conf to add those algorithms? Those are not included by default.

**Comment by gnysek** [comment]
No, I've done was only `apt install network-manager-l2tp-gnome` and then I've connected to VPN for which I've only got IP/login/pass/preshared_key (so I can't check what settings are there).
I've just googled (finding this page and few others), and while finally setting from other one worked for me, I wanted to leave some trace for others that will also search and default aes128 won't work for them.

**Comment by Argo160** [comment]
> No, I've done was only `apt install network-manager-l2tp-gnome` and then I've connected to VPN for which I've only got IP/login/pass/preshared_key (so I can't check what settings are there). I've just googled (finding this page and few others), and while finally setting from other one worked for me, I wanted to leave some trace for others that will also search and default aes128 won't work for them.

Hello,
Could you please kindly let me know how you have done that?
Mine can not connect via l2tp :/
