### ISSUE TITLE
ubuntn使用ikev2配置vpn过程中openssl报错

### ISSUE THREAD

**Issue by sakeri1** [hwdsl2/setup-ipsec-vpn#1282]
**任务列表**

- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [x] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] 这个 bug 是关于 VPN 安装脚本，而不是 IPsec VPN 本身

**问题描述**
openssl报错
oot@tenda-desktop:~# openssl pkcs12 -in sakuras.p12 -cacerts -nokeys -out ca.cer
Enter Import Password:
Error outputting keys and certificates
40B76D7D9A7F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:349:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()

**重现步骤**
重现该 bug 的步骤：

1. 导出p12密钥后按照指进行添加，报错routines:inner_evp_generic_fetch:unsupported

**期待的正确结果**
1、希望可以正确配置

**日志**
[检查日志及 VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)，并添加错误日志以帮助解释该问题（如果适用）。

**服务器信息（请填写以下信息）**
- 操作系统: [centos7]
- 服务提供商（如果适用）: [比如 oracle]

**客户端信息（请填写以下信息）**
- 设备: [比如 台式机]
- 操作系统: [比如 ubuntu22.04]
- VPN 模式: [IKEv2]

**其它信息**
添加关于该 bug 的其它信息。

**Comment by ZARD20** [comment]
试过很多这个确实来噻，注册送永久的流量的，兄弟们可以试试https://915merry.top/auth/register?code=aFk138

**Comment by hwdsl2** [comment]
@sakeri1 你好！你的 Linux 系统版本是什么？该问题可能是因为你的系统运行 OpenSSL 版本 3。请尝试在 openssl 命令中添加 `-legacy`，例如：
```
openssl pkcs12 -legacy -in sakuras.p12 -cacerts -nokeys -out ca.cer
```

**Comment by sakeri1** [comment]
感谢您的帮助，现在可以了，非常感谢
