### ISSUE TITLE
FATAL ERROR: find IPv4 interfaces failed calling bind(0.0.0.0:500): Address already in use (errno 98)

### ISSUE THREAD

**Issue by uugear** [hwdsl2/setup-ipsec-vpn#1286]
First of all I want to thank you for the work on this wonderful project!

I followed the instruction and setup the VPN server, and I configured the IKEv2 client in Windows 11 accordingly (I run the reg update as well). The connection was failed and I checked the log on server with "grep pluto /var/log/auth.log" command, and I found this in the log:
```
Nov 27 11:52:53 adr124 pluto[15453]: listening for IKE messages
Nov 27 11:52:53 adr124 pluto[15453]: FATAL ERROR: find IPv4 interfaces failed calling bind(0.0.0.0:500): Address already in use (errno 98)
```
I then run "cat /etc/services" and found 500 port is occupied by IPsec:
```
isakmp          500/tcp                 # IPsec - Internet Security Association
isakmp          500/udp                 #  and Key Management Protocol
```
I also tried running the ikev2onlymode.sh script, but it doesn't change anything, and VPN connection still fail.

Maybe I did something wrong, but I have no clue at all. Could you please give me some hits? Thank you in advance.

**Comment by hwdsl2** [comment]
@uugear Hello! This is most likely caused by another existing IPsec service on your server that uses UDP port 500. For example, the `strongswan-starter` or `libreswan` packages on Ubuntu/Debian. You can check using `sudo lsof -i :500`.

You can stop and disable the existing IPsec service (if any), then re-install the VPN using instructions in the README.

**Comment by uugear** [comment]
@hwdsl2 Thank you for the fast answer, and you are right. It was due to the fact that I also tried installing it using docker, and the running container occupied the port. Now it is all fixed, thank you!
