### ISSUE TITLE
Error installing in centos

### ISSUE THREAD

**Issue by 7054company** [hwdsl2/setup-ipsec-vpn#1287]
Getting error runing instation script

## Compiling and installing Libreswan, please wait...                + make -j2 -s base                                                   /opt/src/libreswan-4.9/lib/libswan/unbound.c:33:65: fatal error: unbound.h: No such fil

**Comment by 7054company** [comment]
## Compiling and installing Libreswan, please wait...                + make -j2 -s base                                                   /opt/src/libreswan-4.9/lib/libswan/unbound.c:33:65: fatal error: unbound.h: No such file or directory                                      #include <unbound.h>  /* rpm:unbound-devel deb:libunbound-dev */                                                                     ^   compilation terminated.                                              make[3]: *** [unbound.o] Error 1                                     make[3]: *** Waiting for unfinished jobs....                         make[2]: *** [base] Error 2                                          make[1]: *** [recursive-base] Error 2                                make: *** [recursive-base] Error 2                                   Error: Libreswan 4.9 failed to build.                                [root@43-205-70-36 ~]#

**Comment by hwdsl2** [comment]
@7054company Hello! Please run: `sudo yum install unbound-devel`, then re-run the VPN setup script. This package is normally not required for Libreswan compilation, unless you customized compile options in `Makefile.inc.local`.

**Comment by 7054company** [comment]
New issued arrived previous is fixed 



+ make -j2 -s base                                                   In file included from /opt/src/libreswan-4.9/programs/pluto/send.c:36:0:                                                                  /opt/src/libreswan-4.9/programs/pluto/log.h:171:51: fatal error: libaudit.h: No such file or directory                                     # include <libaudit.h> /* from audit-libs devel */                                                                     ^                 compilation terminated.                                              In file included from /opt/src/libreswan-4.9/programs/pluto/ikev1_cert.c:34:0:                                                            /opt/src/libreswan-4.9/programs/pluto/log.h:171:51: fatal error: libaudit.h: No such file or directory                                     # include <libaudit.h> /* from audit-libs devel */                                                                     ^                 compilation terminated.                                              make[3]: *** [send.o] Error 1                                        make[3]: *** Waiting for unfinished jobs....                         make[3]: *** [ikev1_cert.o] Error 1                                  make[2]: *** [base] Error 2                                          make[1]: *** [recursive-base] Error 2                                make: *** [recursive-base] Error 2                                   Error: Libreswan 4.9 failed to build.                                [root@43-205-70-36 ~]# cd /opt                                       [root@43-205-70-36 opt]# ls

**Comment by 7054company** [comment]
Ok it is fixed

**Comment by 7054company** [comment]
New issue arrived



## Downloading Libreswan...                                          + wget -t 3 -T 30 -q -O libreswan-4.9.tar.gz https://github.com/libreswan/libreswan/archive/v4.9.tar.gz                                   ## Compiling and installing Libreswan, please wait...                + make -j2 -s base                                                   /opt/src/libreswan-4.9/programs/pluto/kernel_xfrm.c: In function ‘xfrm_raw_policy’:                                                       /opt/src/libreswan-4.9/programs/pluto/kernel_xfrm.c:706:10: error: missing braces around initializer [-Werror=missing-braces]                struct xfrm_user_tmpl tmpls[4] = {0};                                       ^                                                          /opt/src/libreswan-4.9/programs/pluto/kernel_xfrm.c:706:10: error: (near initialization for ‘tmpls[0]’) [-Werror=missing-braces]          /opt/src/libreswan-4.9/programs/pluto/kernel_xfrm.c:706:10: error: missing initializer for field ‘spi’ of ‘struct xfrm_id’ [-Werror=missing-field-initializers]                                                In file included from /opt/src/libreswan-4.9/programs/pluto/kernel_xfrm.c:70:0:                                                           /opt/src/libreswan-4.9/programs/pluto/linux-copy/linux/xfrm.h:27:10: note: ‘spi’ declared here                                              __be32  spi;                                                                 ^                                                          /opt/src/libreswan-4.9/programs/pluto/kernel_xfrm.c:706:10: error: missing initializer for field ‘family’ of ‘struct xfrm_user_tmpl’ [-Werror=missing-field-initializers]                                         struct xfrm_user_tmpl tmpls[4] = {0};                                       ^                                                          In file included from /opt/src/libreswan-4.9/programs/pluto/kernel_xfrm.c:70:0:                                                           /opt/src/libreswan-4.9/programs/pluto/linux-copy/linux/xfrm.h:243:10: note: ‘family’ declared here                                          __u16   family;                                                              ^                                                          /opt/src/libreswan-4.9/programs/pluto/kernel_xfrm.c: In function ‘add_icmpv6_bypass_policy’:                                              /opt/src/libreswan-4.9/programs/pluto/kernel_xfrm.c:2299:4: error: missing initializer for field ‘ifindex’ of ‘struct xfrm_selector’ [-Werror=missing-field-initializers]                                          .sel.dport = htons(icmp_code),                                       ^                                                                In file included from /opt/src/libreswan-4.9/programs/pluto/kernel_xfrm.c:70:0:                                                           /opt/src/libreswan-4.9/programs/pluto/linux-copy/linux/xfrm.h:60:6: note: ‘ifindex’ declared here                                           int ifindex;                                                             ^                                                              /opt/src/libreswan-4.9/programs/pluto/kernel_xfrm.c:2300:4: error: missing initializer for field ‘ifindex’ of ‘struct xfrm_selector’ [-Werror=missing-field-initializers]                                          .sel.sport_mask = 0xffff,                                            ^                                                                In file included from /opt/src/libreswan-4.9/programs/pluto/kernel_xfrm.c:70:0:                                                           /opt/src/libreswan-4.9/programs/pluto/linux-copy/linux/xfrm.h:60:6: note: ‘ifindex’ declared here                                           int ifindex;                                                             ^                                                              cc1: all warnings being treated as errors                            make[3]: *** [kernel_xfrm.o] Error 1                                 make[3]: *** Waiting for unfinished jobs....                         make[2]: *** [base] Error 2                                          make[1]: *** [recursive-base] Error 2                                make: *** [recursive-base] Error 2                                   Error: Libreswan 4.9 failed to build.                                [root@43-205-70-36 ~]#

**Comment by hwdsl2** [comment]
@7054company It looks like you customized the [install script](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/vpnsetup_centos.sh) for your use case, because I never saw these errors before in my tests. If you are sure you've found a bug, consider filing an issue at https://github.com/libreswan/libreswan.
