### ISSUE TITLE
卸载后无法重新安装

### ISSUE THREAD

**Issue by yangislet** [hwdsl2/setup-ipsec-vpn#1288]
1. 使用脚本官方脚本卸载
2. 重新安装后报Error: This script requires Libreswan already installed.
       See: https://github.com/hwdsl2/setup-ipsec-vpn  [https://ibb.co/vPFZ8Zp](url)

**Comment by yangislet** [comment]
the cmd of “hwdsl2”  is not found,i have remove the "hwdsl2"

**Comment by hwdsl2** [comment]
@yangislet 你好！从你的截图来看，你在重新安装 VPN 时使用了升级脚本 vpnup.sh。这是不正确的。应该使用 vpn.sh 安装。具体参见项目文档。
