### ISSUE TITLE
multiple or accounting

### ISSUE THREAD

**Issue by moandes** [hwdsl2/setup-ipsec-vpn#1289]
Dear hwdsl2

I'm beginner user 😔 
1. how can i create multiple user? Please write the code 🙏🏼
2. can i connect this script to any accounting scripts like ibsng? (if yes how?🥺)

Thanks for ur help and support 🥰

**Comment by hwdsl2** [comment]
@moandes Hello! For managing VPN users, please see:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users.md

https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#configure-ikev2-vpn-clients

For your other question, unfortunately I am not familiar with accounting scripts. This use case is not supported in this project.

**Comment by moandes** [comment]
> For your other question, unfortunately I am not familiar with accounting scripts. This use case is not supported in this project.


Thanks for ur reply,

i mean, is it possible to install any scripts to have a web panel? ( for create and manage users)

**Comment by hwdsl2** [comment]
@moandes This is outside the scope of this project.
