### ISSUE TITLE
VPN is blocking other ports besides Web and Email

### ISSUE THREAD

**Issue by chikorita157** [hwdsl2/setup-ipsec-vpn#129]
I can't seem to get some programs like Open Broadcaster Software (TCP 1935) since it seems that the rules that are created by the script is blocking this traffic. Is there a way to unblock certain ports so they can go through the VPN?

**Comment by hwdsl2** [comment]
@chikorita157 Hello! The VPN setup script does not block any port on the VPN server [1], except for unencrypted L2TP traffic on UDP 1701. It is possible that your VPS or dedicated server provider is blocking this port. You can view the current IPTables rules on the server by running:

```
sudo iptables -nvL; sudo iptables -nvL -t nat
```

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/vpnsetup.sh#L362-L367

**Comment by chikorita157** [comment]
I had to had this line to the iptables rules:

-A POSTROUTING -j SNAT --to-source <server ip address> -o eth+

With that, I got OBS streaming working again.

**Comment by hwdsl2** [comment]
@chikorita157 Glad to hear it is working. But the syntax of your IPTables rule seems incorrect. Besides, the VPN script already adds these two rules [1], which enables access to the Internet via the VPN server.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/vpnsetup.sh#L378-L379
