### ISSUE TITLE
win10可以正常链接访问，但是Android10 链接VPN失败

### ISSUE THREAD

**Issue by yangislet** [hwdsl2/setup-ipsec-vpn#1290]
1.   strongSwan.apk 导入VPN的 “.sswan”无法链接VPN，但是win10可以连接VPN并且正常访问网站

2. vim /etc/ppp/options.xl2tpd 修改MTU为280后，重启VPN服务，APP还是无法链接VPN

3. strongSwan.apk的日志报错信息为： [https://postimg.cc/8JynFPvk](url)

**Comment by yangislet** [comment]
what!  are you serious？ if i don't give money for them, i can't use the strongSwan.apk?

**Comment by hwdsl2** [comment]
@yangislet 你好！strongSwan VPN client 是免费的。请确保使用官方的 strongSwan VPN client。从 [Google Play](https://play.google.com/store/apps/details?id=org.strongswan.android)，[F-Droid](https://f-droid.org/en/packages/org.strongswan.android/) 或 [strongSwan 下载网站](https://download.strongswan.org/Android/)下载。

从你的日志来看，连接请求无法到达服务器。这通常是因为客户端和服务器之间的网络问题。请换一个网络（比如 4G 而不是 WiFi）试一下。另外，IPsec VPN 较容易被 GFW 干扰，可能导致连接问题。对于该用例，请使用其他解决方案比如 Shadowsocks。
