### ISSUE TITLE
请问服务端或者客户端能否增加路由表功能，让流量只走国外

### ISSUE THREAD

**Issue by cloudslsw** [hwdsl2/setup-ipsec-vpn#1293]
主要是windows连上后，看直播和玩游戏同时进行，能不能增加一个路由表让看直播比如B站走直连，然后玩游戏走服务器

**Comment by hwdsl2** [comment]
@cloudslsw 你好！该功能本项目目前不支持。但是如果你希望仅通过 VPN 隧道发送特定目标子网的流量，可以尝试 [VPN 分流](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#vpn-%E5%88%86%E6%B5%81)。
