### ISSUE TITLE
Linux client not loading only certain websites

### ISSUE THREAD

**Issue by dobbsrx** [hwdsl2/setup-ipsec-vpn#1294]
So, I am running the server off an rpi 4 that also runs pihole... I have 3 clients (2 Apple devices and 1 linux device)

The Apple devices have no issues, but my Linux device for some reason has issues opening certain websites.

For example, all google websites, Netflix, Crunchyroll work perfectly fine... however, GitHub and Reddit either time out or they only partially load.

I have reinstalled twice on my Linux client with 2 different created profiles using the instructions in the wiki... I'm curious if anyone has had issues with Linux clients specifically? Maybe iptables need to be adjusted or something? But like I said my Apple devices have no issues and all websites work perfectly fine. 

The distro used is KDE Arch

**Comment by hwdsl2** [comment]
@dobbsrx Hello! This could be a DNS or MTU/MSS issue. The following links may help:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#cannot-open-websites-after-connecting-to-ikev2
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#android-mtumss-issues
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#use-alternative-dns-servers

**Comment by hwdsl2** [comment]
@dobbsrx Please try the solutions in the links above, especially the ones related to MTU/MSS. This is more likely an issue specific to this Linux client. I'm closing this but if you have additional information feel free to reply here.
