### ISSUE TITLE
Custom domaine

### ISSUE THREAD

**Issue by astromandev** [hwdsl2/setup-ipsec-vpn#1296]
it wont use' custom domaine on strongswans conf file and wont work if domain is set munaly on app

**Comment by hwdsl2** [comment]
@astromandev Hello! For IKEv2 mode, the server's IP address is used by default. For your use case, you'll need to change the IKEv2 server address to use a DNS name (custom domain). Please refer to:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#change-ikev2-server-address

Alternatively, you can remove IKEv2 and set it up again using custom options. See:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#remove-ikev2
