### ISSUE TITLE
使用IKEV2模式连接vpn成功，但是无法上网

### ISSUE THREAD

**Issue by Penguin-Trading** [hwdsl2/setup-ipsec-vpn#1297]
**问题描述**
笔记本连接wifi，使用IKEV2模式连接vpn成功，无法上网。
手机连接wifi，使用IKEV2模式连接vpn成功，无法上网。
手机使用流量，使用IKEV2模式连接vpn成功，可以上网。

宽带是新装的联通，我怀疑是宽带的问题，尝试修改电脑网络里的dns没有效果，联通自带的猫上面没有dns相关设置。有什么建议吗？

![image](https://user-images.githubusercontent.com/108123259/208060854-0cd98243-a596-4c9e-a3d5-591c04f09bbc.png)

**服务器信息（请填写以下信息）**
- 操作系统: Ubuntu 22
- 服务提供商（如果适用）: [AWS]

**客户端信息（请填写以下信息）**
- 设备: 华为matebook
- 操作系统: win11
- VPN 模式: [IKEv2]

**Comment by hwdsl2** [comment]
@Penguin-Trading 你好！根据你的描述，如果手机使用流量用 IKEv2 模式连接成功并可以上网，应该是你的宽带网络的问题。检查并打开你的路由器上的 VPN passthrough 设置（如果有）。另外尝试一下这里的第 2 个解决方案 (MTU/MSS)：
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#%E8%BF%9E%E6%8E%A5-ikev2-%E5%90%8E%E4%B8%8D%E8%83%BD%E6%89%93%E5%BC%80%E7%BD%91%E7%AB%99

如果无法解决，你可以尝试一下其他的解决方案。

**Comment by Penguin-Trading** [comment]
外接一个路由器可以了，自带的猫不行
