### ISSUE TITLE
部署安装短时间后无法使用

### ISSUE THREAD

**Issue by 416738994** [hwdsl2/setup-ipsec-vpn#1299]
**任务列表**

- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)，没有找到类似的改进建议
- [x] 这个改进建议是关于 VPN 安装脚本，而不是 IPsec VPN 本身
- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [x] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)

**描述改进建议**
目前一键安装可能存在一定的隐性bug，在使用1～2天后服务器就无法再连接。IP未被GFW拦截。

**你的改进建议与遇到的问题有关吗？请描述。**
目前不清楚该问题与什么相关

**Comment by hwdsl2** [comment]
@416738994 你好！GFW 可能不拦截你的 IP 而仅屏蔽其特定的端口（比如 VPN）。如果几天后无法连接，有可能是这个原因。检查日志的话，可能看到 retransmission 字样。
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E6%A3%80%E6%9F%A5%E6%97%A5%E5%BF%97%E5%8F%8A-vpn-%E7%8A%B6%E6%80%81

建议你尝试一下其他解决方案，比如 Shadowsocks。

**Comment by 416738994** [comment]
非常感谢您
