### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by jlhg** [hwdsl2/setup-ipsec-vpn#13]
It might be great if docker is supported.
Will you consider to port it? Thanks.

**Comment by hwdsl2** [comment]
@jlhg Thanks for the suggestion! However I am currently very busy and don't have time for it. Sorry! You are welcome to fork the repo and make improvements though.

**Comment by uname-yang** [comment]
Thanks for your help #14  @hwdsl2 .i will do the docker enhancement.
