### ISSUE TITLE
send all traffic to another tunnel

### ISSUE THREAD

**Issue by zavataafnan** [hwdsl2/setup-ipsec-vpn#1301]
Hi all, 

I set up IPSEC and IKEv2 VPN simply and quickly and thanks. 
I have another tun0 and I want that IPSEC and IKEv2 use tun0 instead of eth0. is that possible to change table rules, so we achieve this?

Best Regards,
Mostafa

**Comment by hwdsl2** [comment]
@zavataafnan Hello! This feature is outside the scope of this project, and is not supported. You may want to instead ask on e.g. the Libreswan users mailing list or strongSwan discussions:
https://lists.libreswan.org/mailman/listinfo/swan
https://github.com/strongswan/strongswan/discussions
