### ISSUE TITLE
Setup VPN for custom ports instead of default

### ISSUE THREAD

**Issue by hassaan-dev** [hwdsl2/setup-ipsec-vpn#1302]
Hi,

I am using this great `repo` to setup vpn from long time. I am opening question not issue.

I know the default ports are following

```
TCP: 500,450,5743,1701
UDP: 500,4500,5743,1194,1701,8080
```

But can customize these ports? I mean can I use 80 or 443 port while setting up?

**Comment by letoams** [comment]
Yes it is possible but you need to be able to set the port on the client too, as it would not be able to negotiate the port.

This tends to be only supported for TCP on clients. But in our (libreswan upstream) experience, switching to tcp on the standard port 4500 almost always works as most networks block all UDP, and not ipsec specifically.

You can set the listen-udp and listen-tcp parameters to the port of your choosing and match this with remote-port in the client config.

Paul

Sent using a virtual keyboard on a phone

**Comment by hwdsl2** [comment]
Thanks @letoams!
@hassaan-dev Please find the ipsec.conf documentation here:
https://libreswan.org/man/ipsec.conf.5.html

For example, you can set "listen-tcp=yes" in /etc/ipsec.conf, under "config setup" to enable listening on TCP port 4500. To specify a custom UDP port, set the "leftikeport" parameter under each connection section (for IKEv2, edit /etc/ipsec.d/ikev2.conf). Restart the IPsec service when finished: `sudo service ipsec restart`.
