### ISSUE TITLE
no suitable connection found with IKEv2 policy

### ISSUE THREAD

**Issue by dom6770** [hwdsl2/setup-ipsec-vpn#1305]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ ] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**
Trying to connect to the VPN with Android & Windows 11, both time unsuccessful. Windows 11 reports "Policy match error", Android "Unsuccessful"

**To Reproduce**

1. Install VPN Server
2. Use ike2v_config_import.cmd to import cert and create vpn connection. (Android: Import and create cert manually)
3. (Windows) Enable stronger cipher as stated in the troubleshooting post about "Policy match error". 
4. (Windows) Reboot
5. Trying to connect
6. Error

**Expected behavior**
VPN connection should be successful, but isn't. It was successful in the past, but now it isn't.

**Logs**
[Check logs and VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status), and add error logs to help explain the problem, if applicable.

service ipsec status:
```
Dec 25 13:03:52 NetworkServer pluto[337389]: packet from [$IP_REMOTE]:500: ISAKMP_v2_IKE_SA_INIT message received on [$IP_VPN]:500 but no suitable connection found with IKEv2 policy
Dec 25 13:03:52 NetworkServer pluto[337389]: packet from [$IP_REMOTE]:500: responding to IKE_SA_INIT (34) message (Message ID 0) with unencrypted notification NO_PROPOSAL_CHOSEN
```

pluto: https://wastebin.neus.xyz/7l0QCc.txt
xl2tpd: https://wastebin.neus.xyz/F30nDd

**Server (please complete the following information)**
- OS: Debian GNU/Linux 11 (bullseye) (Kernel: Linux 5.10.0-19-amd64)
- Hosting provider (if applicable): [e.g. GCP, AWS]

**Client (please complete the following information)**
- Android: Pixel 7 Pro w/ Android 13
- Windows: Windows 11 22H2 22621.819
- VPN mode: IPsec/IKEv2

**Comment by hwdsl2** [comment]
@dom6770 Hello! From the logs you posted, it looks like you are trying to connect to the VPN server using IPv6. IPv6 is not currently supported in this project, and that's probably the reason for the errors you encountered.

Please instead connect to the VPN server using IPv4. If you are using a DNS (domain) name to connect, try removing the AAAA DNS record so clients can connect using IPv4.
