### ISSUE TITLE
Ограничение по количеству подключений IKEv2

### ISSUE THREAD

**Issue by Radmin24** [hwdsl2/setup-ipsec-vpn#1306]
Доброго времени суток. Настроил VPN для нашей компании и раздал comunitu менеджерам. Знаю что они могут передавать mibileconfig на другоие свои устройства и подключать множество устройств по одному сертификату. Как устранить данный недочет. Хочу использовать именно IKEv2 только для одного подключения. В документации не нашел ничего похожего.

**Comment by hwdsl2** [comment]
@Radmin24 Hello! This feature (limit to one IKEv2 connection per user certificate) is not currently supported in this project.

There is an option called `uniqueids` that can be configured in `/etc/ipsec.conf`. The VPN setup scripts default to `uniqueids=no`, you can change it to `uniqueids=yes` and restart the IPsec service with `sudo service ipsec restart`. When this option is enabled, the second connection from VPN clients using the same remote ID (for example, with the same IKEv2 certificate) will replace the existing connection, which means that the existing connection will be disconnected. You can test it to see if it helps your use case.

Refer to Libreswan documentation: https://libreswan.org/man/ipsec.conf.5.html

**Comment by Radmin24** [comment]
Ты мне помог сильно. Спасибо.
