### ISSUE TITLE
how to remote spesific port in local?

### ISSUE THREAD

**Issue by CanD62** [hwdsl2/setup-ipsec-vpn#1307]
hello, i use your project vpn l2tp
i have problem to remote mikrotik local
my mikrotik done connected l2tp with ip 192.168.42.10 form vpn
and now i will remote with ip vpn with spesific port local: 8291

my iptables setup in rc.local
netif=eth0
iptables -t nat -I POSTROUTING -s 192.168.42.0/24 -o "$netif" -j MASQUERADE
iptables -I FORWARD 2 -i "$netif" -o ppp+ -p tcp --dport 2025 -j ACCEPT
iptables -t nat -A PREROUTING -p tcp --dport 2025 -j DNAT --to 192.168.42.10:8291

so, i connect to remote ipserver:2025

this not working. what wrong? please help me
thanks.

![Untitled](https://user-images.githubusercontent.com/7421087/209888845-763e92d1-2f5e-48ff-a8f0-fd70c0caba46.png)

**Comment by hwdsl2** [comment]
@CanD62 Hello! It looks like you are trying to forward TCP port 2025 on the VPN server to TCP port 8291 on the VPN client at 192.168.42.10.

For your use case, try these rules instead (note that the FORWARD rule should have `--dport 8291`):
```
netif=eth0
iptables -I FORWARD 2 -i "$netif" -o ppp+ -p tcp --dport 8291 -j ACCEPT
iptables -t nat -A PREROUTING -p tcp --dport 2025 -j DNAT --to 192.168.42.10:8291
```

**Comment by CanD62** [comment]
I'm try it still not working sir.

![2](https://user-images.githubusercontent.com/7421087/209911347-40b39891-bc17-497a-8c27-b4d54d8991e1.jpg)

![1](https://user-images.githubusercontent.com/7421087/209911318-c99aa09f-e216-4557-ba17-309dd258922d.png)

**Comment by hwdsl2** [comment]
@CanD62 You'll need to either restart the VPN server or manually run these commands, in order to apply the changes to IPTables rules:
```
netif=eth0
iptables -I FORWARD 2 -i "$netif" -o ppp+ -p tcp --dport 8291 -j ACCEPT
iptables -t nat -A PREROUTING -p tcp --dport 2025 -j DNAT --to 192.168.42.10:8291
```
As I am not familiar with your use case, you'll need to troubleshoot further yourself. One thing to try is to temporarily remove the DROP rule from the IPTables FORWARD chain, and add it back after troubleshooting. Also make sure that the network interface name `netif` is correct. Check default interface name:
```
route 2>/dev/null | grep -m 1 '^default' | grep -o '[^ ]*$'
```
