### ISSUE TITLE
Remote to client vpn not working

### ISSUE THREAD

**Issue by CanD62** [hwdsl2/setup-ipsec-vpn#1308]
I'm follow this intruction but still not working
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#port-forwarding-to-vpn-clients

# Get default network interface name
netif=$(route 2>/dev/null | grep -m 1 '^default' | grep -o '[^ ]*$')
iptables -I FORWARD 2 -i "$netif" -o ppp+ -p tcp --dport 443 -j ACCEPT
iptables -t nat -A PREROUTING -p tcp --dport 443 -j DNAT --to 192.168.42.10

i check open port still closed
https://www.yougetsignal.com/tools/open-ports/

**Comment by hwdsl2** [comment]
@CanD62 Hello! As mentioned in #1307, unfortunate I'm not familiar with your use case and cannot debug on your device, you'll need to troubleshoot further yourself.

The port forwarding instructions in the advanced usage section had been tested earlier and work fine for the described use case in the documentation.
