### ISSUE TITLE
IPSec/L2TP connection established, traffic missing

### ISSUE THREAD

**Issue by dParikesit** [hwdsl2/setup-ipsec-vpn#1309]
**Checklist**

- [v] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [v] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [v] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [v] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [v] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [?] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**
I ran the one-liner script in an AWS EC2 instance, and got the IPSec credential.
I've successfully connected to the VPN, but then the traffic is lost. In the windows settings vpn, the "bytes sent" were increasing, but "bytes received" didn't change as seen in the pictures. For some reason, the ssh connection wasn't destroyed.
![vpn1](https://user-images.githubusercontent.com/64581930/210141256-647c8490-aed4-4cab-a5c1-1fef5d408eb3.png)
![vpn2](https://user-images.githubusercontent.com/64581930/210141258-c842eb1c-6ca4-47e1-91d9-908351acd005.png)

Here is the xl2tpd logs
```
15:00:32 xl2tpd[6712]: Connection established to [redacted], 1701.  Local: 30033, Remote: 7 (ref=0/0).  LNS session is 'default'
15:00:32 xl2tpd[6712]: check_control: Received out of order control packet on tunnel 7 (got 3, expected 2)
15:00:32 xl2tpd[6712]: handle_control: bad control packet!
15:00:32 xl2tpd[6712]: start_pppd: I'm running:
15:00:32 xl2tpd[6712]: "/usr/sbin/pppd"
15:00:32 xl2tpd[6712]: "/dev/pts/3"
15:00:32 xl2tpd[6712]: "passive"
15:00:32 xl2tpd[6712]: "nodetach"
15:00:32 xl2tpd[6712]: "192.168.42.1:192.168.42.10"
15:00:32 xl2tpd[6712]: "refuse-pap"
15:00:32 xl2tpd[6712]: "auth"
15:00:32 xl2tpd[6712]: "require-chap"
15:00:32 xl2tpd[6712]: "name"
15:00:32 xl2tpd[6712]: "l2tpd"
15:00:32 xl2tpd[6712]: "file"
15:00:32 xl2tpd[6712]: "/etc/ppp/options.xl2tpd"
15:00:32 xl2tpd[6712]: Call established with [redacted], PID: 7273, Local: 27697, Remote: 1, Serial: 0
15:02:03 xl2tpd[6712]: Maximum retries exceeded for tunnel 30033.  Closing.
15:02:03 xl2tpd[6712]: Terminating pppd: sending TERM signal to pid 7273
15:02:03 xl2tpd[6712]: Connection 7 closed to [redacted], port 1701 (Timeout)
15:02:34 xl2tpd[6712]: Unable to deliver closing message for tunnel 30033. Destroying anyway.
```

Here is the pluto logs
```
15:00:32 pluto[6693]: "l2tp-psk"[2] [redacted] #13: responding to Main Mode from unknown peer [redacted]:7668
15:00:32 pluto[6693]: "l2tp-psk"[2] [redacted] #13: Oakley Transform [AES_CBC (256), HMAC_SHA1, DH20] refused
15:00:32 pluto[6693]: "l2tp-psk"[2] [redacted] #13: Oakley Transform [AES_CBC (128), HMAC_SHA1, DH19] refused
15:00:32 pluto[6693]: "l2tp-psk"[2] [redacted] #13: sent Main Mode R1
15:00:32 pluto[6693]: "l2tp-psk"[2] [redacted] #13: sent Main Mode R2
15:00:32 pluto[6693]: "l2tp-psk"[2] [redacted] #13: Peer ID is ID_IPV4_ADDR: '[redacted]'
15:00:32 pluto[6693]: "l2tp-psk"[2] [redacted] #13: IKE SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA1 group=MODP2048}
15:00:32 pluto[6693]: "l2tp-psk"[2] [redacted] #13: Configured DPD (RFC 3706) support not enabled because remote peer did not advertise DPD support
15:00:32 pluto[6693]: "l2tp-psk"[2] [redacted] #13: the peer proposed: [redacted]/32:1701 -UDP-> [redacted]/32:1701
15:00:32 pluto[6693]: |   checking hostpair [redacted]/32:1701 -> [redacted]/32:1701
15:00:32 pluto[6693]: "l2tp-psk"[2] [redacted] #13: NAT-Traversal: received 2 NAT-OA. Using first; ignoring others
15:00:32 pluto[6693]: "l2tp-psk"[2] [redacted] #14: responding to Quick Mode proposal {msgid:00000001}
15:00:32 pluto[6693]: "l2tp-psk"[2] [redacted] #14:     us: [redacted]/32:UDP/1701===[redacted][[redacted]]  them: [redacted][[redacted]]===[redacted]/32:UDP/1701
15:00:32 pluto[6693]: "l2tp-psk"[2] [redacted] #14: sent Quick Mode reply, inbound IPsec SA installed, expecting confirmation transport mode {ESPinUDP=>0x5ff9f63a <0xa77c912f xfrm=AES_CBC_256-HMAC_SHA1_96 NATOA=192.168.1.5 NATD=[redacted]:27885 DPD=unsupported}
15:00:32 pluto[6693]: "l2tp-psk"[2] [redacted] #14: IPsec SA established transport mode {ESPinUDP=>0x5ff9f63a <0xa77c912f xfrm=AES_CBC_256-HMAC_SHA1_96 NATOA=[redacted] NATD=[redacted]:27885 DPD=unsupported}Dec 31 15:00:34 ip-[redacted] pluto[6693]: netlink_expire got message with length 116 < 232 bytes; ignore message
15:00:34 pluto[6693]: netlink_expire got message with length 116 < 232 bytes; ignore message
15:00:34 pluto[6693]: netlink_expire got message with length 116 < 232 bytes; ignore message
15:00:34 pluto[6693]: netlink_expire got message with length 116 < 232 bytes; ignore message
15:00:34 pluto[6693]: netlink_expire got message with length 60 < 232 bytes; ignore message
15:00:34 pluto[6693]: message repeated 2 times: [ netlink_expire got message with length 60 < 232 bytes; ignore message]
```

**Server (please complete the following information)**
- OS: Ubuntu 22.04
- Hosting provider: AWS

**Client (please complete the following information)**
- Device: Windows 11 22621.963
- VPN mode: IPsec/L2TP,

Any idea what's happening?

**Comment by hwdsl2** [comment]
@dParikesit Hello! First, please make sure that you opened both UDP ports 500 and 4500 in your EC2 instance's security group.

Your Libreswan (pluto) logs look normal, the xl2tpd logs show that maximum retires exceeded for the VPN tunnel. This could indicate network issues between the VPN client and server, although the exact cause is unknown.

You may want to instead try the recommend IKEv2 mode, refer to the project documentation for more details.
