### ISSUE TITLE
Shrew Soft VPN Client and Windows ARM

### ISSUE THREAD

**Issue by zell180** [hwdsl2/setup-ipsec-vpn#1310]
Hi,
in the guide you ask to install VPN Shrew Soft Client but on ARM64 driver are not compatible and the client not work. I'll try alternative method with IPSEC VPN Windows client but i got security error and none of the pourposed fix works.

Can you help me?

**Comment by hwdsl2** [comment]
@zell180 Hello! The Shrew Soft VPN client is no longer actively developed. As you said, it is not working on ARM systems.

Please try IKEv2 mode instead, for which Windows has a native client. Refer to the documentation for more details and troubleshooting information.
