### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Ahantya** [hwdsl2/setup-ipsec-vpn#1311]
How could I block a specific website and all traffic to it? I know this is technically not a bug but it's the best category.

**Comment by scottpedia** [comment]
@Ahantya u can either use the DNS method or the `iptable` method to block traffic to and from a specific website.

**Comment by hwdsl2** [comment]
Thanks @scottpedia!
@Ahantya This feature is outside the scope of this project. For your use case, you can try blocking the website using IPTables (by inserting rules to the IPTables FORWARD chain, only works if the website's IP is static), or alternatively, specify a [custom DNS server](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#use-alternative-dns-servers) which you can configure to block certain DNS queries. Note that these methods may or may not work for your use case.
