### ISSUE TITLE
DNS can't be changed in customized subnet option 

### ISSUE THREAD

**Issue by KBapna** [hwdsl2/setup-ipsec-vpn#1313]
**Checklist**

- [x ] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x ] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x ] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x ] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x ] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [unknown ] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**
I have set up VPN on custom subnet 172.25.2.2 and have vpn clients on it. 
I have adguard home set up on same server and want to use it for all dns queries. It gives response to all DNS queries perfectly even internal queries are being answer perfectly but...
I am unable to browse internet sometimes or ping domains even though ip is being found and delivered by dns query.
Most of the sites work flawlessly even after flushdns but some sites mostly google related stops working.

**To Reproduce**

1. Install ikev2 on custom subnet
2. Manually change DNS to adguard home in 3 config files and connect to vpn (ikev2)
3. Browse internet after ipconfig /flushdns and some sites will show connection reset error but most of them will work fine.

**Expected behavior**
Able to connect and ping all sites

**Troubleshooting**
Have done nslookup and it shows google dns even though adguard home is set to use cloudflare dns but custom dns names work which are set up on adguard home eg 172.25.0.4 adguard.gg

On other devices directly connected to server shows 172.25.0.4 on nslookup and can browse internet with no problems.

**Server**
- OS: Ubuntu 20
- Hosting provider (if applicable): Homelab

**Client**
- Device: Windows 11 and Android 12
- VPN mode: IKEv2

**Additional context**
N/A

**Comment by hwdsl2** [comment]
@KBapna Hello! For your use case, it looks like you want VPN clients to use the adguard home DNS server, but they are using Google Public DNS (the default). Using a custom VPN subnet should not affect the custom DNS server(s) you specified.

First, make sure that you specified the custom DNS server(s) in `/etc/ipsec.d/ikev2.conf` (replace 8.8.8.8 and 8.8.4.4), then you must restart the IPsec service for the changes to take effect. Refer to [Use alternative DNS servers](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#use-alternative-dns-servers). If it is the same server, try putting either the server's IP address or `127.0.0.1`, or refer to your `/etc/resolv.conf` for the correct IP to use. There were some related discussions in earlier issues in this repo (such as #661, #141), I don't remember the conclusion, but you can try searching for it.

Although unlikely, this could also be a MTU/MSS issue which you can read more [here](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#android-mtumss-issues).

**Comment by KBapna** [comment]
hey! thanks that did solve it.
