### ISSUE TITLE
Android. stongswan client writes in log - NO_PROPOSAL_CHOSEN. 

### ISSUE THREAD

**Issue by ALEXSANPEDRO** [hwdsl2/setup-ipsec-vpn#1314]
stongswan client writes in log - NO_PROPOSAL_CHOSEN

1. install via script
2. change ip address of server(cause i have 2 ips)
3. create ikev client for new server ip address

When i try to connect throught android strongswan it says NO_PROPOSAL_CHOSEN in app logs

**Last LOGS on server**

Jan 13 08:32:15 localhost pluto[17177]: "ikev2-cp": IKE SA proposals (connection add):
Jan 13 08:32:15 localhost pluto[17177]: "ikev2-cp":   1:IKE=AES_CBC_256-HMAC_SHA2_256-HMAC_SHA2_256_128-MODP2048+MODP3072+MODP4096+MODP8192+ECP_256                                                                                    +ECP_384+ECP_521+CURVE25519
Jan 13 08:32:15 localhost pluto[17177]: "ikev2-cp":   2:IKE=AES_CBC_128-HMAC_SHA2_256-HMAC_SHA2_256_128-MODP2048+MODP3072+MODP4096+MODP8192+ECP_256                                                                                    +ECP_384+ECP_521+CURVE25519
Jan 13 08:32:15 localhost pluto[17177]: "ikev2-cp":   3:IKE=AES_CBC_256-HMAC_SHA1-HMAC_SHA1_96-MODP2048+MODP3072+MODP4096+MODP8192+ECP_256+ECP_384+                                                                                    ECP_521+CURVE25519
Jan 13 08:32:15 localhost pluto[17177]: "ikev2-cp":   4:IKE=AES_CBC_128-HMAC_SHA1-HMAC_SHA1_96-MODP2048+MODP3072+MODP4096+MODP8192+ECP_256+ECP_384+                                                                                    ECP_521+CURVE25519
Jan 13 08:32:15 localhost pluto[17177]: "ikev2-cp": Child SA proposals (connection add):
Jan 13 08:32:15 localhost pluto[17177]: "ikev2-cp":   1:ESP=AES_GCM_C_128+AES_GCM_C_256-NONE-NONE-ENABLED+DISABLED
Jan 13 08:32:15 localhost pluto[17177]: "ikev2-cp":   2:ESP=AES_CBC_128-HMAC_SHA1_96-NONE-ENABLED+DISABLED
Jan 13 08:32:15 localhost pluto[17177]: "ikev2-cp":   3:ESP=AES_CBC_256-HMAC_SHA1_96-NONE-ENABLED+DISABLED
Jan 13 08:32:15 localhost pluto[17177]: "ikev2-cp":   4:ESP=AES_CBC_128-HMAC_SHA2_256_128-NONE-ENABLED+DISABLED
Jan 13 08:32:15 localhost pluto[17177]: "ikev2-cp":   5:ESP=AES_CBC_256-HMAC_SHA2_256_128-NONE-ENABLED+DISABLED
Jan 13 08:32:15 localhost pluto[17177]: "ikev2-cp": loaded private key matching left certificate '*.*.*.*'
Jan 13 08:32:15 localhost pluto[17177]: "ikev2-cp": added IKEv2 connection
Jan 13 08:32:15 localhost pluto[17177]: listening for IKE messages
Jan 13 08:32:15 localhost pluto[17177]: Kernel supports NIC esp-hw-offload
Jan 13 08:32:15 localhost pluto[17177]: adding UDP interface wg0 10.66.66.1:500
Jan 13 08:32:15 localhost pluto[17177]: adding UDP interface wg0 10.66.66.1:4500
Jan 13 08:32:15 localhost pluto[17177]: adding UDP interface eth0 *.*.*.*:500
Jan 13 08:32:15 localhost pluto[17177]: adding UDP interface eth0 *.*.*.*:4500
Jan 13 08:32:15 localhost pluto[17177]: adding UDP interface eth0 *.*.*.*:500
Jan 13 08:32:15 localhost pluto[17177]: adding UDP interface eth0 *.*.*.*:4500
Jan 13 08:32:15 localhost pluto[17177]: adding UDP interface lo 127.0.0.1:500
Jan 13 08:32:15 localhost pluto[17177]: adding UDP interface lo 127.0.0.1:4500
Jan 13 08:32:15 localhost pluto[17177]: adding UDP interface lo [::1]:500
Jan 13 08:32:15 localhost pluto[17177]: adding UDP interface lo [::1]:4500
Jan 13 08:32:15 localhost pluto[17177]: adding UDP interface wg0 *.*.*.*:500
Jan 13 08:32:15 localhost pluto[17177]: adding UDP interface wg0 *.*.*.*:4500
Jan 13 08:32:15 localhost pluto[17177]: forgetting secrets
Jan 13 08:32:15 localhost pluto[17177]: loading secrets from "/etc/ipsec.secrets"
Jan 13 08:35:35 localhost pluto[17177]: packet from *.*.*.*:52990: ISAKMP_v2_IKE_SA_INIT message received on *.*.*.*:500 but no suitable connection found with IKEv2 policy

**Server (please complete the following information)**
- OS: Ubuntu 20.04
- Hosting provider (if applicable): BuyVM

**Client (please complete the following information)**
- Device: Huawei p20
- OS: android
- VPN mode: IKEv2

**Additional context**

Just installed standart throught script, then start script to change ip address, and then create new ikev2 user. Thats all.
Besides this i use same config in another vps - all god, but now, cant connect.

**Comment by ALEXSANPEDRO** [comment]
> Looks like pluto crashed and then restarts but doesn’t yet have connections loaded and thus responds with no proposal chosen.Can you ensure the latest libreswan is installed ? Or debug further why it crashed ?


I returned the snapshot taken before the installation via the script. Now I will try to install and recheck the script again.
I will immediately unsubscribe according to the result, in about an hour and a half.

**Comment by hwdsl2** [comment]
@ALEXSANPEDRO Hello! For your use case, first install the VPN and change the IKEv2 address, then edit `/etc/ipsec.d/ikev2.conf`, find the line `left=%defaultroute` and replace it with `left=YOUR_SERVER_IP`, indented by two spaces. `YOUR_SERVER_IP` is the IP address on the server that you want to use for the VPN. Run `sudo service ipsec restart` after that.

Let us know if this resolves the issue.

**Comment by ALEXSANPEDRO** [comment]
@hwdsl2 Thanks a lot!! It resolves the issue!
