### ISSUE TITLE
How listen port 500 and 4500 bind to 0.0.0.0 ?

### ISSUE THREAD

**Issue by zouchengli** [hwdsl2/setup-ipsec-vpn#1316]

**Comment by hwdsl2** [comment]
@zouchengli Hello! By default, Libreswan listens on all network interfaces of the server, so there is no need to specify 0.0.0.0. To listen on a specific interface, you may specify the "listen" parameter in the "config setup" section of /etc/ipsec.conf, then restart the IPsec service. Refer to the manual:
https://libreswan.org/man/ipsec.conf.5.html

**Comment by zouchengli** [comment]
> @zouchengli Hello! By default, Libreswan listens on all network interfaces of the server, so there is no need to specify 0.0.0.0. To listen on a specific interface, you may specify the "listen" parameter in the "config setup" section of /etc/ipsec.conf, then restart the IPsec service. Refer to the manual: https://libreswan.org/man/ipsec.conf.5.html

I want 

> @zouchengli Hello! By default, Libreswan listens on all network interfaces of the server, so there is no need to specify 0.0.0.0. To listen on a specific interface, you may specify the "listen" parameter in the "config setup" section of /etc/ipsec.conf, then restart the IPsec service. Refer to the manual: https://libreswan.org/man/ipsec.conf.5.html

I want to forward these udp ports to the virtual machine vpn service through the router. I guess these two ports are not open to the outside world, and the internal network equipment and ip are bound.

**Comment by zouchengli** [comment]
大佬，是这样的，我这边是用一个虚拟服务器搭建的vpn服务，但是这些vpn服务我要通过外部的网关ip地址去访问，这就涉及到端口转发，但是我转发500 4500这两个端口貌似不起作用

**Comment by zouchengli** [comment]
> @zouchengli Hello! By default, Libreswan listens on all network interfaces of the server, so there is no need to specify 0.0.0.0. To listen on a specific interface, you may specify the "listen" parameter in the "config setup" section of /etc/ipsec.conf, then restart the IPsec service. Refer to the manual: https://libreswan.org/man/ipsec.conf.5.html

我刚才指定端口监听至0.0.0.0 然而 这 500 4500这两个端口不见了。

**Comment by zouchengli** [comment]
> @zouchengli Hello! By default, Libreswan listens on all network interfaces of the server, so there is no need to specify 0.0.0.0. To listen on a specific interface, you may specify the "listen" parameter in the "config setup" section of /etc/ipsec.conf, then restart the IPsec service. Refer to the manual: https://libreswan.org/man/ipsec.conf.5.html

貌似只能配置有网卡的ip，0.0.0.0绑定不了。
报警告：no public interfaces found

**Comment by hwdsl2** [comment]
@zouchengli 你好！根据你的描述，listen 参数可能不支持 0.0.0.0，而是需要特定的 IP 地址。你可以去掉该参数并重启 IPsec 服务。

端口转发的话，UDP 500 和 UDP 4500 端口是正确的。可能是你的端口转发配置有问题，比如检查目标 IP 地址是否是 VPN 服务器的地址。

使用客户端连接后你可以检查 Libreswan 日志：
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E6%A3%80%E6%9F%A5%E6%97%A5%E5%BF%97%E5%8F%8A-vpn-%E7%8A%B6%E6%80%81

**Comment by zouchengli** [comment]
> 


> @zouchengli 你好！根据你的描述，listen 参数可能不支持 0.0.0.0，而是需要特定的 IP 地址。你可以去掉该参数并重启 IPsec 服务。
> 
> 端口转发的话，UDP 500 和 UDP 4500 端口是正确的。可能是你的端口转发配置有问题，比如检查目标 IP 地址是否是 VPN 服务器的地址。
> 
> 使用客户端连接后你可以检查 Libreswan 日志： https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E6%A3%80%E6%9F%A5%E6%97%A5%E5%BF%97%E5%8F%8A-vpn-%E7%8A%B6%E6%80%81
> 
> 如果没有新的日志，连接请求可能没有到达服务器。

我可不可以这样，目标ip设置成内部虚拟机ip，域名指向的是路由器上网ip，路由器把udp 500 4500 端口转发到虚拟机可以吗？

**Comment by hwdsl2** [comment]
@zouchengli 你所说的应该是正确的端口转发方式，可以尝试一下。

**Comment by zouchengli** [comment]
> 

貌似不行，请求不进来。
<img width="700" alt="image" src="https://user-images.githubusercontent.com/27568522/212604087-c727a438-14a4-4f13-96bd-1b7616da5a2d.png">
<img width="590" alt="image" src="https://user-images.githubusercontent.com/27568522/212604170-d38ad15d-cef5-42ce-b734-10201a53131b.png">
