### ISSUE TITLE
Unable to use smart card for authentication Windows built-in IKEv2 client

### ISSUE THREAD

**Issue by trochdewei** [hwdsl2/setup-ipsec-vpn#1318]
Is it possible to use smart-card as auth method? writing certificate to card results in error 13801. After editing certificate selection parameters I get error 798
![1](https://user-images.githubusercontent.com/37622670/214873095-6537b2d9-21ff-4a51-b952-0b774c19d58f.PNG)
![2](https://user-images.githubusercontent.com/37622670/214873110-3de2dea3-dfc9-4389-b07c-3904a3fa03b9.PNG)
![3](https://user-images.githubusercontent.com/37622670/214873113-66436ca3-23f8-4d72-836e-493c85da61dd.PNG)

**Comment by hwdsl2** [comment]
@trochdewei Hello! This feature is not currently supported. The error 798 you encountered is related to IKEv2 EAP authentication, which is not yet supported in Libreswan and therefore not available in this project.

**Comment by letoams** [comment]
On Thu, 26 Jan 2023, Lin Song wrote:

> @trochdewei Hello! This feature is not currently supported. The error 798 you encountered is related to IKEv2 EAP authentication,
> which is not yet supported in Libreswan and therefore not available in this project.

Note that EAPTLS is supported in libreswan 4.7 and newer. This allows
for Windows VPN without Administrator access for the certificate
import in the system store. The certificate can now be a simple
user store configuration.

libreswan server example config: https://github.com/libreswan/libreswan/blob/main/testing/pluto/interop-ikev2-eaptls-strongswan-client/east.conf

How windows gets access to the cert, smartcard or software, does not
matter for libreswan.
