### ISSUE TITLE
result_code_avp: avp is incorrect size.  8 < 10

### ISSUE THREAD

**Issue by orf** [hwdsl2/setup-ipsec-vpn#132]
Hey,
Thank you so very much for this awesome image. I've been running a vpn server with it for the last half a year, but I recently tried to connect my Android phone to it.

The connection fails with this message:

```xl2tpd[1]: Connection established to x, 39948.  Local: 14628, Remote: 28503 (ref=0/0).  LNS session is 'default'
xl2tpd[1]: start_pppd: I'm running:
xl2tpd[1]: "/usr/sbin/pppd"
xl2tpd[1]: "passive"
xl2tpd[1]: "nodetach"
xl2tpd[1]: "192.168.42.1:192.168.42.10"
xl2tpd[1]: "refuse-pap"
xl2tpd[1]: "auth"
xl2tpd[1]: "require-chap"
xl2tpd[1]: "name"
xl2tpd[1]: "l2tpd"
xl2tpd[1]: "file"
xl2tpd[1]: "/etc/ppp/options.xl2tpd"
xl2tpd[1]: "/dev/pts/0"
xl2tpd[1]: Call established with x, Local: 24701, Remote: 32604, Serial: x
xl2tpd[1]: child_handler : pppd exited for call 32604 with code 11
xl2tpd[1]: call_close: Call 24701 to xdisconnected
xl2tpd[1]: result_code_avp: avp is incorrect size.  8 < 10
xl2tpd[1]: handle_avps: Bad exit status handling attribute 1 (Result Code) on mandatory packet.
xl2tpd[1]: Terminating pppd: sending TERM signal to pid 1075
xl2tpd[1]: Connection 28503 closed to x, port 39948 (Result Code: expected at least 10, got 8)
xl2tpd[1]: Unable to deliver closing message for tunnel 14628. Destroying anyway.```

I've checked out the troubleshooting guide and there is no option for backwards compatibility, and `sha2-truncbug=yes` is in the config.

Any ideas with the next steps I can take? I'm running Android 7.0

**Comment by hwdsl2** [comment]
@orf Hello! It looks like this is a bug in Android or xl2tpd. See [1][2][3]. I would suggest that you instead use IPsec/XAuth mode [4] to connect (which does not use xl2tpd/pppd), OR set up IKEv2 [5] and use the strongSwan VPN client.

[1] https://issuetracker.google.com/issues/36997388
[2] https://github.com/xelerance/xl2tpd/issues/44
[3] https://github.com/xelerance/xl2tpd/issues/90
[4] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md
[5] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md
