### ISSUE TITLE
cant't capture ipsec package.

### ISSUE THREAD

**Issue by LPL-hacker** [hwdsl2/setup-ipsec-vpn#1320]
I set up an ipsec vpn server on my ubuntu VM and configure IPsec/L2TP VPN Clients. I used wireshark to capture any network adapter. And visit https://www.ipchicken.com/, but didn't see any esp or ah protocol message，

**Comment by hwdsl2** [comment]
@LPL-hacker Hello! This is outside the scope of this project. Please read Wireshark documentation and investigate further yourself.
