### ISSUE TITLE
ikev2-only -> Mikrotik 6.48.6 HapAC2 "can't verify peer's certificate from store"

### ISSUE THREAD

**Issue by ALEXSANPEDRO** [hwdsl2/setup-ipsec-vpn#1326]
**Describe the issue**
I decided to deploy IKEV2 on a new VPS as a backup. On the first one, I did it according to the instructions, set it up on Mikrotik - everything is OK.

But I also installed a VPN server on the second server, ran the IKEV2 only script, and added a user. Copied *.p12 - upload it on mikrotik 2 times, before the appearance of "KT". Then follow the standard instructions. However, the connection is terminated at the first step, and the logs on the microtic are showered with such an error - " certificate signature failure(7) at depth:0 cert:CN=*.*.*.*,C=,ST=,L=,O=IKEv2 VPN,OU=,SN=
can't verify peer's certificate from store"

**To Reproduce**

1. use steps from manual
2. add certificate to mikrot, setup, check logs. 

**Expected behavior**
I expect to connect to my second ikev2 server throught mikrotik

**Logs**
Mikrotik logs: certificate signature failure(7) at depth:0 cert:CN=*.*.*.*,C=,ST=,L=,O=IKEv2 VPN,OU=,SN=
can't verify peer's certificate from store"

Last Server Logs: Feb 15 12:14:57 rootsecure pluto[832382]: "ikev2-cp"[3] *.*.*.* #1760: proposal 1:ESP=AES_CBC_128-HMAC_SHA1_96-DISABLED SPI=0f343ea1 chosen from remote proposals 1:ESP:ENCR=AES_CBC_256;ENCR=AES_CBC_192;ENCR=AES_CBC_128;INTEG=HMAC_SHA1_96;ESN=DISABLED[first-match]
Feb 15 12:14:57 rootsecure pluto[832382]: "ikev2-cp"[3] *.*.*.* #1760: responder established Child SA using #1759; IPsec tunnel [0.0.0.0-255.255.255.255:0-65535 0] -> [192.168.43.10-192.168.43.10:0-65535 0] {ESPinUDP=>0x0f343ea1 <0x9f6e9308 xfrm=AES_CBC_128-HMAC_SHA1_96 NATD=*.*.*.*:4500 DPD=active}
Feb 15 12:14:58 rootsecure pluto[832382]: "ikev2-cp"[3] *.*.*.* #1761: proposal 1:IKE=AES_CBC_128-HMAC_SHA1-HMAC_SHA1_96-MODP2048 chosen from remote proposals 1:IKE:ENCR=AES_CBC_128;ENCR=3DES;PRF=HMAC_SHA1;INTEG=HMAC_SHA1_96;DH=MODP2048;DH=MODP1024[first-match]
Feb 15 12:14:58 rootsecure pluto[832382]: "ikev2-cp"[3] *.*.*.* #1761: sent IKE_SA_INIT reply {cipher=AES_CBC_128 integ=HMAC_SHA1_96 prf=HMAC_SHA1 group=MODP2048}
Feb 15 12:14:58 rootsecure pluto[832382]: "ikev2-cp"[3] *.*.*.* #1761: processing decrypted IKE_AUTH request: SK{IDi,AUTH,CERT,CERTREQ,N(INITIAL_CONTACT),SA,TSi,TSr,CP}
Feb 15 12:14:58 rootsecure pluto[832382]: "ikev2-cp"[3] *.*.*.* #1761: responder established IKE SA; authenticated peer '3072-bit PKCS#1 1.5 RSA with SHA1' signature using peer certificate '@aeza' issued by CA 'CN=IKEv2 VPN CA, O=IKEv2 VPN'
Feb 15 12:14:58 rootsecure pluto[832382]: "ikev2-cp"[3] *.*.*.* #1762: proposal 1:ESP=AES_CBC_128-HMAC_SHA1_96-DISABLED SPI=0bc09135 chosen from remote proposals 1:ESP:ENCR=AES_CBC_256;ENCR=AES_CBC_192;ENCR=AES_CBC_128;INTEG=HMAC_SHA1_96;ESN=DISABLED[first-match]

(ive deleted ip's from logs)

I se this and it strange: Feb 15 12:14:58 rootsecure pluto[832382]: "ikev2-cp"[3] *.*.*.* #1761: responder established IKE SA; authenticated peer '3072-bit PKCS#1 1.5 RSA with SHA1' signature using peer certificate '@aeza' issued by CA 'CN=IKEv2 VPN CA, O=IKEv2 VPN'

**Server (please complete the following information)**
- OS: Ubuntu 20.04
- Hosting provider (if applicable): AEZA

**Client (please complete the following information)**
- Device: Mikrotik HAP AC2
- OS: ROS 6.48.6
- VPN mode:  IKEv2

**Additional context**

This in my second server setup. I've done all like in first time(wher all works fine), but this issua cant let me connect to new server. 

P.S.: hwdsl2. please help=)

**Comment by ALEXSANPEDRO** [comment]
trying fully reinstall ikev2 server, create new cert for user, but same situation. Cant understand - why. Cause other server with same setting/steps works well

**Comment by ALEXSANPEDRO** [comment]
certificate signature failure(7) at depth:0 cert:CN=79.*.*.*,C=,ST=,L=,O=IKEv2 VPN,OU=,SN=

but in cert issuer is "CN=IKEv2 VPN CA,O=IKEv2 VPN

**Comment by ALEXSANPEDRO** [comment]
last message from "grep pluto /var/log/auth.log" - packet from 217.*.*.*:4500: IKE_AUTH request has no corresponding IKE SA; message dropped

**Comment by ALEXSANPEDRO** [comment]
Feb 15 16:02:20 rootsecure pluto[19135]: "ikev2-cp"[2]  #135: sent IKE_SA_INIT reply {cipher=AES_CBC_128 integ=HMAC_SHA1_96 prf=HMAC_SHA1 group=MODP2048}
Feb 15 16:02:21 rootsecure pluto[19135]: "ikev2-cp"[2]  #135: failed to match authenticator
Feb 15 16:02:21 rootsecure pluto[19135]: "ikev2-cp"[2]  #135: saved fragment 1 of 2 invalid; dropped
Feb 15 16:02:21 rootsecure pluto[19135]: "ikev2-cp"[2]  #135: failed to match authenticator
Feb 15 16:02:21 rootsecure pluto[19135]: "ikev2-cp"[2]  #135: saved fragment 2 of 2 invalid; dropped
Feb 15 16:02:26 rootsecure pluto[19135]: "ikev2-cp"[2]  #135: failed to match authenticator
Feb 15 16:02:26 rootsecure pluto[19135]: "ikev2-cp"[2]  #135: fragment 1 of 2 invalid
Feb 15 16:02:26 rootsecure pluto[19135]: "ikev2-cp"[2]  #135: failed to match authenticator
Feb 15 16:02:26 rootsecure pluto[19135]: "ikev2-cp"[2]  #135: fragment 2 of 2 invalid
Feb 15 16:02:31 rootsecure pluto[19135]: "ikev2-cp"[2]  #135: failed to match authenticator
Feb 15 16:02:31 rootsecure pluto[19135]: "ikev2-cp"[2]  #135: fragment 1 of 2 invalid
Feb 15 16:02:31 rootsecure pluto[19135]: "ikev2-cp"[2] #135: failed to match authenticator
Feb 15 16:02:31 rootsecure pluto[19135]: "ikev2-cp"[2]  #135: fragment 2 of 2 invalid
Feb 15 16:02:33 rootsecure pluto[19135]: "ikev2-cp"[1]  #1: STATE_V2_ESTABLISHED_IKE_SA: retransmission; will wait 128 seconds for response
Feb 15 16:02:36 rootsecure pluto[19135]: "ikev2-cp"[2]  #135: failed to match authenticator
Feb 15 16:02:36 rootsecure pluto[19135]: "ikev2-cp"[2]  #135: fragment 1 of 2 invalid
Feb 15 16:02:36 rootsecure pluto[19135]: "ikev2-cp"[2]  #135: failed to match authenticator
Feb 15 16:02:36 rootsecure pluto[19135]: "ikev2-cp"[2]  #135: fragment 2 of 2 invalid
Feb 15 16:02:41 rootsecure pluto[19135]: "ikev2-cp"[2]  #135: failed to match authenticator
Feb 15 16:02:41 rootsecure pluto[19135]: "ikev2-cp"[2]  #135: fragment 1 of 2 invalid
Feb 15 16:02:41 rootsecure pluto[19135]: "ikev2-cp"[2]  #135: failed to match authentica




More logs if it helps.....

**Comment by letoams** [comment]
On Wed, 15 Feb 2023, Alec wrote:

> Subject: Re: [hwdsl2/setup-ipsec-vpn] ikev2-only -> Mikrotik 6.48.6 HapAC2
>     "can't verify peer's certificate from store" (Issue #1326)
> Feb 15 16:02:20 rootsecure pluto[19135]: "ikev2-cp"[2] #135: sent IKE_SA_INIT reply {cipher=AES_CBC_128
> integ=HMAC_SHA1_96 prf=HMAC_SHA1 group=MODP2048}
> Feb 15 16:02:21 rootsecure pluto[19135]: "ikev2-cp"[2] #135: failed to match authenticator
> Feb 15 16:02:21 rootsecure pluto[19135]: "ikev2-cp"[2] #135: saved fragment 1 of 2 invalid; dropped
> Feb 15 16:02:21 rootsecure pluto[19135]: "ikev2-cp"[2] #135: failed to match authenticator
> Feb 15 16:02:21 rootsecure pluto[19135]: "ikev2-cp"[2] #135: saved fragment 2 of 2 invalid; dropped

This appears to be a low level crypto error. Possibly related to
fragmentation? Try disabling fragmentation (fragmentation=no) or
switch to a different crypto algorithm (eg AES_GCM. Avoid using
SHA1 as it is not in our default set anymore and you should be
using sha2 there, so try ike=aes_gcm-sha2-modp2048 and esp=aes_gcm)

**Comment by ALEXSANPEDRO** [comment]
i USE STEP BY STEP INSTRUCTION HERE. i DONE THIS A COUPLE OF MONTH AGO WITH SUCH SETTINGS ON MY ROUTER, BUT NOW SAME CONFIG ON PTHER VPS - AND NO RESULT.

Ma hapac2 works well with other ikev2only installed script. 

> On Wed, 15 Feb 2023, Alec wrote: Subject: Re: [hwdsl2/setup-ipsec-vpn] ikev2-only -> Mikrotik 6.48.6 HapAC2 "can't verify peer's certificate from store" (Issue #1326) Feb 15 16:02:20 rootsecure pluto[19135]: "ikev2-cp"[2] #135: sent IKE_SA_INIT reply {cipher=AES_CBC_128 integ=HMAC_SHA1_96 prf=HMAC_SHA1 group=MODP2048} Feb 15 16:02:21 rootsecure pluto[19135]: "ikev2-cp"[2] #135: failed to match authenticator Feb 15 16:02:21 rootsecure pluto[19135]: "ikev2-cp"[2] #135: saved fragment 1 of 2 invalid; dropped Feb 15 16:02:21 rootsecure pluto[19135]: "ikev2-cp"[2] #135: failed to match authenticator Feb 15 16:02:21 rootsecure pluto[19135]: "ikev2-cp"[2] #135: saved fragment 2 of 2 invalid; dropped
> This appears to be a low level crypto error. Possibly related to fragmentation? Try disabling fragmentation (fragmentation=no) or switch to a different crypto algorithm (eg AES_GCM. Avoid using SHA1 as it is not in our default set anymore and you should be using sha2 there, so try ike=aes_gcm-sha2-modp2048 and esp=aes_gcm)

where i can turn off fragmentation or change cryptoalgoritm to  ike=aes_gcm-sha2-modp2048 and esp=aes_gcm

**Comment by ALEXSANPEDRO** [comment]
if i chaged these settings, the manual for mikrotik will be unusefull? cause if i change crypto algoritms i need to change settings on Mikrotik to same algoritms

**Comment by letoams** [comment]
On Thu, 16 Feb 2023, Alec wrote:

> if i chaged these settings, the manual for mikrotik will be unusefull? cause if i change crypto algoritms i need to change settings on Mikrotik to same
> algoritms

Yes, you should change them on both ends.

**Comment by ALEXSANPEDRO** [comment]
but cant understand why on other vps all works great with standart settings. it must work with standart settings in my opinion..

**Comment by hwdsl2** [comment]
Thanks @letoams for your insights.

@ALEXSANPEDRO To disable IKEv2 fragmentation, edit `/etc/ipsec.d/ikev2.conf` on your VPN server. Find the line `fragmentation=yes` and change it to `fragmentation=no`, then run `sudo service ipsec restart`.

To change the algorithms as @letoams mentioned, edit the same file and replace
```
ike=aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1
```
with
```
ike=aes_gcm-sha2-modp2048,aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1
```

Then restart the IPsec service: `sudo service ipsec restart`.

Let us know if this resolves the issue.

**Comment by hwdsl2** [comment]
@ALEXSANPEDRO Please try the steps in my previous comment regarding disabling IKEv2 fragmentation and/or change the IKE algorithms.

Another possibility is that because your Mikrotik device previously had an IKEv2 client certificate imported (from your older VPS) and trusted, the "IKEv2 VPN CA" that issued that client certificate could conflict with the "IKEv2 VPN CA" from the newer VPS. Note that those CAs will be different since they were generated on different servers. Perhaps you can try removing all existing IKEv2 related certificates from the Mikrotik device, then re-import the one(s) from the new VPS.

I'm closing this but if you have additional information, feel free to reply here.

**Comment by ALEXSANPEDRO** [comment]
> Another possibility is that because your Mikrotik device previously had an IKEv2 client certificate imported (from your older VPS) and trusted, the "IKEv2 VPN CA" that issued that client certificate could conflict with the "IKEv2 VPN CA" from the newer VPS. Note that those CAs will be different since they were generated on different servers. Perhaps you can try removing all existing IKEv2 related certificates from the Mikrotik device, then re-import the one(s) from the new VPS.
> 


Yeap, this helped me! When i remove cert from old vps and use only new - all works good! Thanks!
