### ISSUE TITLE
无法连接到 IKEv2 VPN

### ISSUE THREAD

**Issue by yinchonging** [hwdsl2/setup-ipsec-vpn#1327]
**任务列表**

- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [x] 我检查了 [IKEv1 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#ikev1-故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#ikev2-故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] 这个 bug 是关于 VPN 安装脚本，而不是 IPsec VPN 本身

**问题描述**
首先感谢作者，脚本用了很多年了。最近频繁出现问题，连续三天三次，每天重部署一次，每次都出问题，也没有任何错误提示，就是连不上，也按照文档检查了，不好使，只能用新系统重新部署，然后用几次后又不能连接。

特来求助！

**重现步骤**
重现该 bug 的步骤：

1.新ubuntu系统，执行update
2.安装vpn
3.配置客户端
4.某次中途会断掉，然你后就再也连不上

按故障排查过，udp端口也开着，服务器客户端都分别重启过，客户端重新重启重新配置过

**日志** 

[auth.log](https://github.com/hwdsl2/setup-ipsec-vpn/files/10752032/auth.log)

> root@localhost:~# grep xl2tpd /var/log/syslog
Feb 15 07:23:46 localhost xl2tpd[2056]: Not looking for kernel SAref support.
Feb 15 07:23:46 localhost xl2tpd[2056]: Using l2tp kernel support.
Feb 15 07:23:46 localhost xl2tpd[2051]: Starting xl2tpd: xl2tpd.
Feb 15 07:23:46 localhost xl2tpd[2062]: xl2tpd version xl2tpd-1.3.16 started on localhost PID:2062
Feb 15 07:23:46 localhost xl2tpd[2062]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
Feb 15 07:23:46 localhost xl2tpd[2062]: Forked by Scott Balmos and David Stipp, (C) 2001
Feb 15 07:23:46 localhost xl2tpd[2062]: Inherited by Jeff McAdams, (C) 2002
Feb 15 07:23:46 localhost xl2tpd[2062]: Forked again by Xelerance (www.xelerance.com) (C) 2006-2016
Feb 15 07:23:46 localhost xl2tpd[2062]: Listening on IP address 0.0.0.0, port 1701
Feb 15 07:24:49 localhost xl2tpd[2062]: death_handler: Fatal signal 15 received
Feb 15 07:24:49 localhost xl2tpd[5713]: Stopping xl2tpd: xl2tpd.
Feb 15 07:24:49 localhost systemd[1]: xl2tpd.service: Deactivated successfully.
Feb 15 07:24:49 localhost xl2tpd[5723]: Not looking for kernel SAref support.
Feb 15 07:24:49 localhost xl2tpd[5723]: Using l2tp kernel support.
Feb 15 07:24:49 localhost xl2tpd[5719]: Starting xl2tpd: xl2tpd.
Feb 15 07:24:49 localhost xl2tpd[5724]: xl2tpd version xl2tpd-1.3.16 started on localhost PID:5724
Feb 15 07:24:49 localhost xl2tpd[5724]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
Feb 15 07:24:49 localhost xl2tpd[5724]: Forked by Scott Balmos and David Stipp, (C) 2001
Feb 15 07:24:49 localhost xl2tpd[5724]: Inherited by Jeff McAdams, (C) 2002
Feb 15 07:24:49 localhost xl2tpd[5724]: Forked again by Xelerance (www.xelerance.com) (C) 2006-2016
Feb 15 07:24:49 localhost xl2tpd[5724]: Listening on IP address 0.0.0.0, port 1701
Feb 16 03:32:29 localhost xl2tpd[5724]: death_handler: Fatal signal 15 received
Feb 16 03:32:29 localhost xl2tpd[10391]: Stopping xl2tpd: xl2tpd.
Feb 16 03:32:29 localhost systemd[1]: xl2tpd.service: Deactivated successfully.
Feb 16 03:32:29 localhost xl2tpd[10400]: Not looking for kernel SAref support.
Feb 16 03:32:29 localhost xl2tpd[10400]: Using l2tp kernel support.
Feb 16 03:32:29 localhost xl2tpd[10396]: Starting xl2tpd: xl2tpd.
Feb 16 03:32:29 localhost xl2tpd[10401]: xl2tpd version xl2tpd-1.3.16 started on localhost PID:10401
Feb 16 03:32:29 localhost xl2tpd[10401]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
Feb 16 03:32:29 localhost xl2tpd[10401]: Forked by Scott Balmos and David Stipp, (C) 2001
Feb 16 03:32:29 localhost xl2tpd[10401]: Inherited by Jeff McAdams, (C) 2002
Feb 16 03:32:29 localhost xl2tpd[10401]: Forked again by Xelerance (www.xelerance.com) (C) 2006-2016
Feb 16 03:32:29 localhost xl2tpd[10401]: Listening on IP address 0.0.0.0, port 1701

**服务器信息**
- 操作系统: [ubuntu 22]
- 服务提供商: [linode]

**客户端信息（请填写以下信息）**
- 设备: [Surface Pro 、iPhone 12]
- 操作系统: [iOS 16/Windows 11]
- VPN 模式: [IKEv2]

**其它信息**

![屏幕截图_20230216_113503](https://user-images.githubusercontent.com/2151476/219264351-1dbf64d0-a8cd-4f73-a336-25c020fba925.png)

**Comment by hwdsl2** [comment]
@yinchonging 你好！根据你的描述，很可能是因为 VPN 连接被 GFW 屏蔽或干扰了。IPsec VPN 较容易被干扰，建议换用其他解决方案比如 Shadowsocks。

**Comment by chenj-freedom** [comment]
@hwdsl2 Shadowsoocks可以自己有比较好的提供商吗？
