### ISSUE TITLE
VPN server 支持通过动态IPV6地址连接

### ISSUE THREAD

**Issue by skyrockgz** [hwdsl2/setup-ipsec-vpn#1328]
**任务列表**

- [ ] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)，没有找到类似的改进建议
- [ ] 这个改进建议是关于 VPN 安装脚本，而不是 IPsec VPN 本身
- [ ] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [ ] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [ ] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [ ] 我检查了 [IKEv1 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#ikev1-故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#ikev2-故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)

**描述改进建议**
家里的移动宽带下的debian具备动态ipv6公网ip和光猫下的192.168.1.x内网ipv4。
手机iphone在网移动网络下获得ipv6和内网的ipv4
希望能够通过iOS内置的VPN客户端 的IKEv2协议通过ipv6地址连接到家庭内的Debian搭建的VPN server后，VPN获得家庭局域网内的ipv4 内网地址192.168.1.y
这样手机就可以像局域网访问家庭局域网内的服务，并使用家庭局域网内的旁路由192.168.1.w 访问公网

**你的改进建议与遇到的问题有关吗？请描述。**
目前的脚本生成的vpn server默认都是使用ipv4地址连接的，是否可以增加默认使用ipv6地址连接的选项？

**其它信息**
添加关于该改进建议的其它信息。
移动家宽没有ipv4公网ip地址，ipv6的公网ip地址也是动态的，几天换一次

**Comment by hwdsl2** [comment]
@skyrockgz 你好！感谢你的建议。本项目目前不支持使用 IPv6 连接，你可以另外尝试比如 [OpenVPN](https://github.com/hwdsl2/openvpn-install) 或 [WireGuard](https://github.com/hwdsl2/wireguard-install)。
