### ISSUE TITLE
Couldn't connect to L2tp/IPSec or IPSec XAuth

### ISSUE THREAD

**Issue by StevenSmitt** [hwdsl2/setup-ipsec-vpn#1329]
Android phones could not connect to my VPS using XAuth or L2tp/IPsec, but Mikrotik router or Windows PC connects succesfully, I'm trying to connect from different subnets, but nothing

log from server when I tried to connect using xauth: https://pastebin.com/ytzZTEJZ
log from server when I tried to connect using l2tp: https://pastebin.com/mVAvCTzS
log from server when Mikrotik connected: https://pastebin.com/1ft7RTWs

**Comment by hwdsl2** [comment]
@StevenSmitt Hello! Please refer to [this section](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#android). Android users should connect using [IKEv2 mode](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md) (recommended), which is more secure.

The native VPN client in Android uses the less secure modp1024 (DH group 2) for the IPsec/L2TP and IPsec/XAuth ("Cisco IPsec") modes. To improve security, modp1024 (DH group 2) is no longer enabled by default in this project.

If you still want to connect from Android using IPsec/L2TP or IPsec/XAuth ("Cisco IPsec") mode, you must first edit `/etc/ipsec.conf` on the VPN server. Find the line `ike=...` and append `,aes256-sha2;modp1024,aes128-sha1;modp1024` at the end. Save the file and run `sudo service ipsec restart`.

**Comment by StevenSmitt** [comment]
> ...Find the line `ike=...` and append `,aes256-sha2;modp1024,aes128-sha1;modp1024` at the end. Save the file and run `sudo service ipsec restart`.

Thanks it works!

**Comment by letoams** [comment]
On Wed, 22 Feb 2023, StevenSmitt wrote:

>       ...Find the line ike=... and append ,aes256-sha2;modp1024,aes128-sha1;modp1024 at the end.
>       Save the file and run sudo service ipsec restart.
> 
> Thanks it works!

Note that a university budget can break modp1024 these days. Your VPN
will not be strong at all, and not compliant with any kind of
certifications (FIPS, PCI-DSS, medical ones, etc)
