### ISSUE TITLE
请问怎么修改 IP？

### ISSUE THREAD

**Issue by pengweichu** [hwdsl2/setup-ipsec-vpn#1331]
**描述改进建议**

IP 经常被封，每次更改 IP 都要重新安装，很麻烦，请问有什么方便的方法在不重新安装的情况下更改IP吗？

**Comment by hwdsl2** [comment]
@pengweichu 你好！请参见：[域名和更改服务器 IP](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#%E5%9F%9F%E5%90%8D%E5%92%8C%E6%9B%B4%E6%94%B9%E6%9C%8D%E5%8A%A1%E5%99%A8-ip) 以及 [更改 IKEv2 服务器地址](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#%E6%9B%B4%E6%94%B9-ikev2-%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%9C%B0%E5%9D%80)。
