### ISSUE TITLE
使用Macbook M1 Cisco IPSec链接vpn

### ISSUE THREAD

**Issue by injecTerminal** [hwdsl2/setup-ipsec-vpn#1332]
Macbook PRO M1 A2338
使用Cisco IPSec 链接vpn认证失败
一开始流畅正常运行，后面不知道是服务器问题还是自己操作失误导致的。
具体详见ipsec日志
现在andriod 用l2tp可以正常连接访问![mmexport1677644912414.png](https://user-images.githubusercontent.com/42806424/222044907-28582730-86bb-4649-ab54-3bf347f596b1.png)

**Comment by hwdsl2** [comment]
@injecTerminal 你好！从你的日志来看，你在客户端上输入的 IPsec PSK 和服务器上的不一致。它可以在服务器上的 `/etc/ipsec.secrets` 文件中找到。也有可能是客户端和服务器之间的网络问题。
