### ISSUE TITLE
windows有线无法打开谷歌 wifi就可以

### ISSUE THREAD

**Issue by Insofan** [hwdsl2/setup-ipsec-vpn#1334]
google youtube 在台式用有线的时候打不开 换成wifi就能打开 iphone ipad mac都用的wifi能正常打开 google

**Comment by hwdsl2** [comment]
@Insofan 你好！这个可能是 DNS 的问题，请参见 [这个链接](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#%E8%BF%9E%E6%8E%A5-ikev2-%E5%90%8E%E4%B8%8D%E8%83%BD%E6%89%93%E5%BC%80%E7%BD%91%E7%AB%99) 中的第 3 个解决方案。具体来说：

在某些情况下，Windows 在连接后不使用 IKEv2 指定的 DNS 服务器。要解决此问题，可以在网络连接属性 -> TCP/IPv4 中手动输入 DNS 服务器，例如 Google Public DNS (8.8.8.8, 8.8.4.4)。
