### ISSUE TITLE
部分设备只能访问国外网站，无法访问国内网站（其中包括github）

### ISSUE THREAD

**Issue by ASh-en** [hwdsl2/setup-ipsec-vpn#1336]
**任务列表**

- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [x] 我检查了 [IKEv1 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#ikev1-故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#ikev2-故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)

**问题描述**
ubuntu22.04原网络为校园网，需要登录，登录后正常访问各类国内网站，通过IKEv2正常连接vpn后，只能访问国外网站，无法访问国内网站（百度，微信，qq等都无法使用）。考虑到是否为校园网问题，使用苹果手机对ubuntu开启热点后，再连接vpn存在相同情况。
同时采用苹果手机分别使用校园网和流量登录后，再通过IKEv2连接vpn均能正常访问国内外网站。

服务器端网卡信息：
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1452 qdisc fq state UP group default qlen 1000
    link/ether 52:54:00:96:64:32 brd ff:ff:ff:ff:ff:ff
    altname enp0s4
    altname ens4
    inet 10.7.185.16/16 brd 10.7.255.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe96:6432/64 scope link 
       valid_lft forever preferred_lft forever
3: ip_vti0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0

ubuntu客户端信息：
2: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 2c:f0:5d:e2:34:61 brd ff:ff:ff:ff:ff:ff
    inet 172.25.5.20/24 brd 172.25.5.255 scope global dynamic noprefixroute enp2s0
       valid_lft 79682sec preferred_lft 79682sec
    inet 192.168.43.10/32 scope global enp2s0
       valid_lft forever preferred_lft forever
    inet6 2001:da8:216:2505:8cde:4619:8ea7:eae8/64 scope global temporary dynamic 
       valid_lft 598086sec preferred_lft 79404sec
    inet6 2001:da8:216:2505:ef61:1961:65b4:5622/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 2591891sec preferred_lft 604691sec
    inet6 fe80::9d3:c3e8:4f89:4a6f/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
3: wlp3s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 70:cf:49:ba:ee:fb brd ff:ff:ff:ff:ff:ff
6: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none 
    inet 192.168.43.10/32 scope global noprefixroute tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::ae7d:f69e:b250:7ea4/64 scope link stable-privacy 
       valid_lft forever preferred_lft forever

同时ubuntu22.04存在无法建立l2tp/ipsec的连接问题（所以采用IKEv2替代）

**期待的正确结果**
是否需要对ubuntu22.04进行特别的路由设置，希望能给一个解决方案，保证再ubuntu端通过IKEv2对国内外网站正常访问。

**服务器信息（请填写以下信息）**
- 操作系统: Centos stream 8

**客户端信息（请填写以下信息）**
- 设备:台式机
- 操作系统: ubuntu22.04lts
- VPN 模式:  IKEv2

**Comment by ASh-en** [comment]
连接外网也存在部分问题，如YouTube无法播放视频，外网响应慢等问题。

**Comment by hwdsl2** [comment]
@ASh-en 你好！根据你的描述，有可能是 DNS 的问题。Ubuntu 系统在连接 VPN 后可能不使用 VPN 服务器指定的 DNS 服务器。关于此问题的相关讨论请参见 #1077。你可以尝试在你的 Ubuntu 系统上手动指定 DNS 服务器比如 Google Public DNS 等。

对于连接外网的问题，除了上面的 DNS 问题之外，请尝试 [连接 IKEv2 后不能打开网站](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#%E8%BF%9E%E6%8E%A5-ikev2-%E5%90%8E%E4%B8%8D%E8%83%BD%E6%89%93%E5%BC%80%E7%BD%91%E7%AB%99) 中的几个解决方案。 

另外，IPsec/L2TP 模式的相关说明请参见[这里](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#linux)。你也可以[检查 VPN 日志](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E6%A3%80%E6%9F%A5%E6%97%A5%E5%BF%97%E5%8F%8A-vpn-%E7%8A%B6%E6%80%81)。

如果你有更多信息可以继续在这里回复。

**Comment by whatever8080** [comment]
我也遇到类似情况，但用这个解决了[Android MTU/MSS问题](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#android-mtumss-%E9%97%AE%E9%A2%98)

虽然作者说的是对于ipsec XAuth类型的连接，但确实也适用于IKEv2的情况
