### ISSUE TITLE
INFORMATIONAL request has no corresponding IKE SA; message dropped

### ISSUE THREAD

**Issue by chenj-freedom** [hwdsl2/setup-ipsec-vpn#1337]
On Win10, still have this problem. My VPN server is centOS7, and I can't find '/etc/crypto-policies/back-ends/nss.config' this file. Could you give me some advice?

_Originally posted by @chenj-freedom in https://github.com/hwdsl2/setup-ipsec-vpn/issues/1206#issuecomment-1460429625_

**Comment by hwdsl2** [comment]
@chenj-freedom Hello! CentOS 7 does not have the issue described in #1206. CentOS 7 comes with an NSS version that allows `SHA1` by default, so there is no need to change the NSS configuration. I have tested and confirmed this.

The file `/etc/crypto-policies/back-ends/nss.config` does not exist in CentOS 7. Instead, there is `/etc/pki/nss-legacy/nss-rhel7.config` which is possibly related. The log message you mentioned: `INFORMATIONAL request has no corresponding IKE SA; message dropped`, does not indicate a problem by itself.
