### ISSUE TITLE
我不知道我的防火墙该如何设置。

### ISSUE THREAD

**Issue by shuang-wu-leng** [hwdsl2/setup-ipsec-vpn#1338]
-----------------------------------------------------------------------------------------------------------------------------------------
[root@racknerd-8010dc ~]# systemctl status iptables
● iptables.service - IPv4 firewall with iptables
   Loaded: loaded (/usr/lib/systemd/system/iptables.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
[root@racknerd-8010dc ~]# 
[root@racknerd-8010dc ~]# 
[root@racknerd-8010dc ~]# 
[root@racknerd-8010dc ~]# systemctl status firewalld
● firewalld.service
   Loaded: masked (/dev/null; bad)
   Active: inactive (dead) since Sat 2023-03-11 04:49:40 EST; 7min ago
 Main PID: 2398 (code=exited, status=0/SUCCESS)

Mar 11 04:46:24 racknerd-8010dc systemd[1]: Starting firewalld - dynamic firewall daemon...
Mar 11 04:46:24 racknerd-8010dc systemd[1]: Started firewalld - dynamic firewall daemon.
Mar 11 04:46:24 racknerd-8010dc firewalld[2398]: WARNING: AllowZoneDrifting is enabled. This is considered an insecu... now.
Mar 11 04:49:39 racknerd-8010dc systemd[1]: Stopping firewalld - dynamic firewall daemon...
Mar 11 04:49:40 racknerd-8010dc systemd[1]: Stopped firewalld - dynamic firewall daemon.
Hint: Some lines were ellipsized, use -l to show in full.

-----------------------------------------------------------------------------------------------------------------------------------------
您好，我使用vps中的centos7系统搭建您的此项目，但是当我搭建好了之后我发现我的iptables和firewalld都是关闭状态，我在想这样会不会非常的危险。我试着手动打开iptables或者firewalld但是无论开启哪一个都会导致vpn无法使用（具体的症状是可以连接但无法访问任何网页）。我看了你写的文档并且在firewalld中添加了4500udp、500udp和1701tcp端口但是还是不行，只要一开防火墙vpn立马失效。本人是个菜鸟，如果您能帮我解决此问题我将感激不尽！

**Comment by hwdsl2** [comment]
@shuang-wu-leng 你好！对于 CentOS 7 系统，使用本项目的脚本安装 VPN 之后，IPTables 服务应该是打开（启用）的状态。你的系统显示 IPTables 没有运行，建议你在备份你的数据之后重装 VPS 的系统，然后重新安装 VPN，看看是否有帮助。或者另外在一个新的 VPS 上安装。

另外，对于 CentOS 8 和 9 系统则默认启用 nftables 而不是 IPTables 服务。
