### ISSUE TITLE
配置完成后，连接不上

### ISSUE THREAD

**Issue by LinightKira** [hwdsl2/setup-ipsec-vpn#1342]
问题：
Mar 13 22:55:07 VM-8-3-centos pluto[28405]: "l2tp-psk"[2] [223.72.xx.xxx](http://223.72.xx.xxx/) #7: WARNING: connection l2tp                                                                                                               -psk PSK length of 20 bytes is too short for HMAC_SHA2_384 PRF in FIPS mode (24 bytes required)
Mar 13 22:55:07 VM-8-3-centos pluto[28405]: "l2tp-psk"[2] [223.72.xx.xxx](http://223.72.xx.xxx/) #7: Oakley Transform [AES_CB                                                                                                               C (256), HMAC_SHA2_384, MODP1024] refused

解决方式：
The native VPN client in Android uses the less secure modp1024 (DH group 2) for the IPsec/L2TP and IPsec/XAuth ("Cisco IPsec") modes. To improve security, modp1024 (DH group 2) is no longer enabled by default in this project.

If you still want to connect from Android using IPsec/L2TP or IPsec/XAuth ("Cisco IPsec") mode, you must first edit `/etc/ipsec.conf` on the VPN server. Find the line` ike=...` and append` ,aes256-sha2;modp1024,aes128-sha1;modp1024` at the end. Save the file and run `sudo service ipsec restart`.

**Comment by smutao** [comment]
use an old version, e.g. from 2021

**Comment by hwdsl2** [comment]
@LinightKira 你好！Android 系统自带的 VPN 客户端对 IPsec/L2TP 和 IPsec/XAuth ("Cisco IPsec") 模式使用安全性较低的 modp1024 (DH group 2)。为增强 VPN 安全性，本项目禁用了该模式。推荐使用 [IKEv2 模式](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md)连接。如你所说，如果你仍然想启用安全性较低的 modp1024，可以参见[这里](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#android)（不推荐）。
