### ISSUE TITLE
在ikev2模式下，支持不同客户端配置不同的子网路由策略

### ISSUE THREAD

**Issue by snomile** [hwdsl2/setup-ipsec-vpn#1343]
**任务列表**

- [✅] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)，没有找到类似的改进建议
- [✅ ] 这个改进建议是关于 VPN 安装脚本，而不是 IPsec VPN 本身
- [ ✅] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [ ✅] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [ ✅] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [ ✅] 我检查了 [IKEv1 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#ikev1-故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#ikev2-故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)

**描述改进建议**
在ikev2模式下，支持不同客户端配置不同的子网路由策略

**你的改进建议与遇到的问题有关吗？请描述。**
**需求**：假设有2个客户端client1、client2均连接到vpn server，对于client1，希望仅路由其192.168.0.1/24网段的请求；对于client2，希望路由其0.0.0.0/0的请求（相当于全局vpn，将客户的所有流量都路由到vpn网关）。

**问题**：目前无法通过安装脚本配置不同客户端的不同子网路由策略。

**解决思路**：如果暂时无法通过脚本在增加客户端时设置子网路由策略，能否手工添加多个conn配置块，并在每个配置块中设置不同的leftsubnet实现？但这种情况下，如何让不同客户端可以命中不同的conn配置块呢，请指导。

**Comment by hwdsl2** [comment]
@snomile 你好！感谢你的建议。该功能是可以通过手工添加多个conn配置块，并在每个配置块中设置不同的leftsubnet实现的。请参见 [VPN 内网 IP 和流量](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#vpn-%E5%86%85%E7%BD%91-ip-%E5%92%8C%E6%B5%81%E9%87%8F)，展开 "IKEv2 模式：为 VPN 客户端分配静态 IP" 部分。对于此用例，可以在该部分中的示例的基础上在每个配置块中设置不同的leftsubnet实现。保存文件后重启 IPsec 服务。

**Comment by snomile** [comment]
> @snomile 你好！感谢你的建议。该功能是可以通过手工添加多个conn配置块，并在每个配置块中设置不同的leftsubnet实现的。请参见 [VPN 内网 IP 和流量](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#vpn-%E5%86%85%E7%BD%91-ip-%E5%92%8C%E6%B5%81%E9%87%8F)，展开 "IKEv2 模式：为 VPN 客户端分配静态 IP" 部分。对于此用例，可以在该部分中的示例的基础上在每个配置块中设置不同的leftsubnet实现。保存文件后重启 IPsec 服务。

非常感谢，按照您提供的方法配置成功。
