### ISSUE TITLE
Wrong static ip assigned for Windows clients

### ISSUE THREAD

**Issue by carlos-gomez-espinosa** [hwdsl2/setup-ipsec-vpn#1344]
Hi, I think there is a mistake regarding the fixed ip's issue when you connect from windows.

I have several fixed ip's assigned with the IKEV2 method, and if I use iOS, it works perfectly, it assigns me the ips correctly.

However, if I connect using windows, it doesn't assign those ips. It assigns me from 192.168.43.100, which is the range that I have as in your example for the autoassigned ip's.

Is there any way to solve it and that windows gives me the ip that I have assigned?

**Comment by hwdsl2** [comment]
@carlos-gomez-espinosa Hello! As mentioned in the [Internal VPN IPs and traffic](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#internal-vpn-ips-and-traffic) section (expand "IKEv2 mode: Assign static IPs to VPN clients"), when assigning static IPs to IKEv2 clients, the "rightid=" value must exactly match the client name with the `@` prefix added.

Does your Windows client's IKEv2 certificate name match the "rightid" value you specified in `ikev2.conf` for the IP you want to assign?

**Comment by carlos-gomez-espinosa** [comment]
Yes, The certificate match with the @client name that I have filled in the config.
That's because I think it's strange, because with the mobileconfig for iOS works perfect. And those files are generated in the same step

**Comment by bagus-repository** [comment]
> Yes, The certificate match with the @client name that I have filled in the config. That's because I think it's strange, because with the mobileconfig for iOS works perfect. And those files are generated in the same step

Have I have same issue when connecting from windows client, have set conn rightid="CN=client, O=IKEv2 VPN" still give client from auto IP pool 192.168.43.100, When connecting through mobile get correct static IP

**Comment by hwdsl2** [comment]
@bagus-repository Try `rightid="CN=vpnclient, O=IKEv2 VPN"` (`vpnclient` is the default client name). Restart the IPsec service after making changes. For more information see [Internal VPN IPs and traffic](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#internal-vpn-ips-and-traffic).

**Comment by bagus-repository** [comment]
@hwdsl2 I solve this issue by reading this https://github.com/hwdsl2/setup-ipsec-vpn/issues/1119#issuecomment-1064179108 from `sudo ipsec trafficstatus`

I get information that connected vpn using wrong certificate that I used earlier (other than default "vpnclient"), check to my Windows personal certificate remove the wrong certificate and reinstall vpn using IKEv2 script, it works I get static configured IP!
