### ISSUE TITLE
如何配置ipsec客户端使只有指定的ip段的请求才走vpn？

### ISSUE THREAD

**Issue by RainYuan110** [hwdsl2/setup-ipsec-vpn#1347]
你好，
       我按照客户端的配置说明配置了win11的vpn配置。走的是ikev2.但是一但开启，客户端的所有访问都是走的vpn。我希望只有指定的ip段才走vpn，其他的走本地网络。请问该如何配置？
       万分感谢！

**Comment by hwdsl2** [comment]
@RainYuan110 你好！请参见 [VPN 分流](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#vpn-%E5%88%86%E6%B5%81)。
