### ISSUE TITLE
can i set up a vpn with ipv6 address?

### ISSUE THREAD

**Issue by Robert-Lin** [hwdsl2/setup-ipsec-vpn#1348]

**Comment by Sky-hacke** [comment]
同问，想同时使用ipv6

**Comment by hwdsl2** [comment]
@Robert-Lin @Sky-hacke Hello! IPv6 is not currently supported in this project. You can instead try [OpenVPN](https://github.com/hwdsl2/openvpn-install) or [WireGuard](https://github.com/hwdsl2/wireguard-install).
