### ISSUE TITLE
可以用 strongswan 替代libreswan 部署等价的服务器吗？

### ISSUE THREAD

**Issue by ptpt52** [hwdsl2/setup-ipsec-vpn#1349]
@hwdsl2 
可以用 strongswan 替代libreswan 部署等价的服务器吗？
或者，可以用strongswan + l2tp 做客户端吗?

**Comment by ptpt52** [comment]
常见的VPN类型有这些
```
L2TP/IPSec PSK
L2TP/IPSec RSA
IPSec Xauth PSK
IPSec Xauth RSA
IPSec Hybrid RSA
IKEv2/IPSec MSCHAPv2
IKEv2/IPSec PSK
IKEv2/IPSec RSA
```
我有计划每一个都搞清楚如何部署，然后希望可以用strongswan部署支持这些。

**Comment by daa20** [comment]
IPsec最新的协议是IKEv2，v2特别是对v1的补充和完善。
感觉把IKEv2的了解和部署下，应该就可以了。
IKEv2/IPSec MSCHAPv2 IKEv2/IPSec PSK IKEv2/IPSec RSA



··^-·-·^·-^-·
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hwdsl2/setup-ipsec-vpn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月22日(星期三) 中午11:33
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [hwdsl2/setup-ipsec-vpn] 可以用 strongswan 替代libreswan 部署等价的服务器吗？ (Issue #1349)





 
常见的VPN类型有这些
 L2TP/IPSec PSK L2TP/IPSec RSA IPSec Xauth PSK IPSec Xauth RSA IPSec Hybrid RSA IKEv2/IPSec MSCHAPv2 IKEv2/IPSec PSK IKEv2/IPSec RSA  
我有计划每一个都搞清楚如何部署，然后希望可以用strongswan部署支持这些。

**Comment by hwdsl2** [comment]
@ptpt52 你好！用 strongSwan 替代 Libreswan 部署一般是可行的。本项目目前不支持，但是你可以自己搜索相关示例，比如 trailofbits/algo 使用 strongSwan。

关于不同的 VPN 类型，你可以参见 Libreswan 的一些示例：
https://libreswan.org/wiki/Configuration_examples

关于使用 strongSwan 作为客户端，[这里](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E4%BD%BF%E7%94%A8%E5%91%BD%E4%BB%A4%E8%A1%8C%E9%85%8D%E7%BD%AE-linux-vpn-%E5%AE%A2%E6%88%B7%E7%AB%AF)有一些示例步骤。
