### ISSUE TITLE
I can use is with raspberry pi but not pine64 

### ISSUE THREAD

**Issue by tinysun** [hwdsl2/setup-ipsec-vpn#135]
I can use is with raspberry pi on raspbian.
but it is not work on pine64 (debian  longsleep Kernel (3.10.102)or(3.10.105) ).
pluto was not run? I am not sure.Maybe same error of that kernel.
Can you fix it on next version?
Thank you very much.
If you need test server, I can open my pine64 on ssh for you.

you can mail me anytime.

**Comment by tinysun** [comment]
我可以在我的树莓派(raspbian系统)上运行。
但是我没法再pine64上用。（debian longsleep Kernel (3.10.102)or(3.10.105) ）
好像是pluto没运行起来？我也不确定，也许是内核问题。
不知道您能否在下一个版本提供一下对pine64的支持。
非常感谢。
如果您需要调试环境，我可以把我的pine64的ssh打开为您开放。

您可以随时给我发信或者加我微信也行。

**Comment by hwdsl2** [comment]
@tinysun Hello! Please first try these commands:
```
sudo service ipsec restart
sudo service xl2tpd restart
```

Then connect your VPN client(s) again. If it still does not work, run this command to check the VPN logs for errors:
```
sudo grep pluto /var/log/auth.log
```
