### ISSUE TITLE
Problems with access local resources

### ISSUE THREAD

**Issue by ShibalovRoman** [hwdsl2/setup-ipsec-vpn#1350]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ ] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**
I use digital ocean 2 droplets. Both of them are in one local network and I can ping 1->2 and 2->1. I setup by default settings VPN server, enable only IKEv2, open all ports. I added new cert and add him to local PC. I connected to VPN and I see that I can't connect to any service relates on server1 (which is without VPN). Also I can't even ping him. But from server2 from SSH I can. It means firewall aren't blocking me. What is the problem can be here? I successfully use internet from VPN but can't use local resources on other servers in local network. I read many closed issues and didn't any normal solution for this. Thanks

**Expected behavior**

**Server (please complete the following information)**
- OS: [e.g. Debian 11] Ubuntu 22
- Hosting provider (if applicable): [e.g. GCP, AWS] DO

**Client (please complete the following information)**
- Device: [e.g. iPhone 12] PC
- OS: [e.g. iOS 15] Windows 11
- VPN mode: [IPsec/L2TP, IPsec/XAuth ("Cisco IPsec") or IKEv2] IKEv2 only

**Comment by hwdsl2** [comment]
@ShibalovRoman Hello! For this use case, you may need to modify IPTables rules. Please refer to [Access VPN server's subnet](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#access-vpn-servers-subnet), more specifically, the part after "Please note, additional configuration is required if the VPN server has multiple network interfaces...". Let us know if this works for you.

**Comment by ShibalovRoman** [comment]
Great, I missed something after hours of research...
Could you please help with adding commands to /etc/rc.local - in which format should I do this? Just copy-paste?

**Comment by ShibalovRoman** [comment]
Thanks. I missed this part after hours of investigation. I just need to open ports on local system
