### ISSUE TITLE
连接经常超时问题

### ISSUE THREAD

**Issue by hxj524** [hwdsl2/setup-ipsec-vpn#1351]
搭建了VPN后，开始能够正常运行，但是过了一段时间后，就出现无法连接，即使重启服务器也不行，但是更换了IP后又正常时我们是为什么

**Comment by hwdsl2** [comment]
@hxj524 你好！IPsec VPN 较容易被屏蔽或干扰。建议另外尝试其他解决方案比如 Shadowsocks。
