### ISSUE TITLE
mac ikev2连接失败

### ISSUE THREAD

**Issue by injecTerminal** [hwdsl2/setup-ipsec-vpn#1352]
![mmexport1679818009077.png](https://user-images.githubusercontent.com/42806424/227763358-6b3ff27a-a1e3-4e0b-a321-824dbc6b41aa.png)

xauth 连接失败
![mmexport1679818517797.png](https://user-images.githubusercontent.com/42806424/227763680-919ecbb7-b8ec-49fc-bdf4-ff6e058e1dd4.png)

**Comment by hwdsl2** [comment]
@injecTerminal 你好！从你的日志来看，可能是连接被屏蔽或干扰了。建议另外尝试其他解决方案比如 Shadowsocks。
