### ISSUE TITLE
编译libreswan-4.10出错

### ISSUE THREAD

**Issue by peekpi** [hwdsl2/setup-ipsec-vpn#1353]
错误信息：
```shell
## Downloading Libreswan...
+ wget -t 3 -T 30 -q -O libreswan-4.10.tar.gz https://github.com/libreswan/libreswan/archive/v4.10.tar.gz
## Compiling and installing Libreswan, please wait...
+ make -j2 -s base
/opt/src/libreswan-4.10/programs/pluto/nss_cert_verify.c: In function ‘verify_end_cert’:
/opt/src/libreswan-4.10/programs/pluto/nss_cert_verify.c:211:5: error: ‘certificateUsageIPsec’ undeclared (first use in this function)
   { certificateUsageIPsec, "IPsec" },
     ^
/opt/src/libreswan-4.10/programs/pluto/nss_cert_verify.c:211:5: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [nss_cert_verify.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [base] Error 2
make[1]: *** [recursive-base] Error 2
make: *** [recursive-base] Error 2
Error: Libreswan 4.10 failed to build.
```
在libreswan的issue里找到一个回复，说是需要libnss>3.44，或者设置USE_NSS_IPSEC_PROFILE=false，不过设置后编译还会遇到其他的问题。
https://github.com/libreswan/libreswan/issues/273#issuecomment-530476542

**Comment by letoams** [comment]
On Mon, 27 Mar 2023, PeekPI wrote:

> ## Downloading Libreswan...
> + wget -t 3 -T 30 -q -O libreswan-4.10.tar.gz https://github.com/libreswan/libreswan/archive/v4.10.tar.gz
> ## Compiling and installing Libreswan, please wait...
> + make -j2 -s base
> /opt/src/libreswan-4.10/programs/pluto/nss_cert_verify.c: In function ‘verify_end_cert’:
> /opt/src/libreswan-4.10/programs/pluto/nss_cert_verify.c:211:5: error: ‘certificateUsageIPsec’ undeclared (first use in this functio
> n)
>    { certificateUsageIPsec, "IPsec" },
>      ^
> /opt/src/libreswan-4.10/programs/pluto/nss_cert_verify.c:211:5: note: each undeclared identifier is reported only once for each func
> tion it appears in

Upgrade your NSS library version or compile with USE_NSS_IPSEC_PROFILE=false

**Comment by peekpi** [comment]
> On Mon, 27 Mar 2023, PeekPI wrote: ## Downloading Libreswan... + wget -t 3 -T 30 -q -O libreswan-4.10.tar.gz https://github.com/libreswan/libreswan/archive/v4.10.tar.gz ## Compiling and installing Libreswan, please wait... + make -j2 -s base /opt/src/libreswan-4.10/programs/pluto/nss_cert_verify.c: In function ‘verify_end_cert’: /opt/src/libreswan-4.10/programs/pluto/nss_cert_verify.c:211:5: error: ‘certificateUsageIPsec’ undeclared (first use in this functio n) { certificateUsageIPsec, "IPsec" }, ^ /opt/src/libreswan-4.10/programs/pluto/nss_cert_verify.c:211:5: note: each undeclared identifier is reported only once for each func tion it appears in
> Upgrade your NSS library version or compile with USE_NSS_IPSEC_PROFILE=false

thanks, I upgraded libnss to 3.44 and the issue is fixed.

**Comment by peekpi** [comment]
I use bandwagonhost and install ubuntu os. seem like the check in `vpnsetup_ubuntu.sh` not work properly:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/9184ec7bf275b36c0dcb32e50a863dfd9e8e72a7/vpnsetup_ubuntu.sh#L270-L273
The `$os_ver` in my vps is `stretchsid`, so I just removed this check, and it works.
context of `/etc/debian_version`: `stretch/sid`

**Comment by hwdsl2** [comment]
@peekpi 你好！感谢你的错误报告。`stretchsid` 对应比如 Ubuntu 16.04 系统，该系统在 2021 年 4 月已不受支持。推荐换用新的受支持的 Ubuntu 版本。
