### ISSUE TITLE
clash premium透明网关和ikev2 wirguard等VPN共存问题

### ISSUE THREAD

**Issue by warrenhoo** [hwdsl2/setup-ipsec-vpn#1354]
**任务列表**

- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)，没有找到类似的改进建议
- [x] 这个改进建议是关于 VPN 安装脚本，而不是 IPsec VPN 本身
- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [x] 我检查了 [IKEv1 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#ikev1-故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#ikev2-故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)

**描述改进建议**
使用debian11 全新安装clash premium代理软件，配置软件使用tun模式，不用再iptables即克将本机作为透明代理网关，用本脚本在本机运行，安装完成后，客户端能连上，只可访问局域网网址，不能访问广域网网址。再安装了作者自己的wirguard脚本，能访问局域网网址和广域网网址，但CPU飙升死机。openvpn脚本安装的openvpn客户端不能连上。

**你的改进建议与遇到的问题有关吗？请描述。**
linux小白，不是很清楚tun和iptables的兼容性或相关性，不知道githuber能否调试一下，虚拟一个debian安装clash premuim做透明网关，再用您的vpn脚本试试兼容性。

**其它信息**
添加关于该改进建议的其它信息。

**Comment by hwdsl2** [comment]
@warrenhoo 你好！我对该代理软件不熟悉，它可能与 IPsec VPN 等不兼容。建议你到网上相关的社区问一下，或者自己做进一步的测试。

**Comment by k186** [comment]
确保你子网能访问 透明代理，然后在配置文件中增加http代理配置，同时 根证书要增加一个透明代理的
