### ISSUE TITLE
如何区分设备？我希望得到一些建议

### ISSUE THREAD

**Issue by dd-ping** [hwdsl2/setup-ipsec-vpn#1355]
非常感谢！ 我现在有3个client ， 我想让client1 、 client2 之间链接，不想让client3 跟 1 / 2  进行通信

**Comment by hwdsl2** [comment]
@dd-ping 你好！本项目默认不支持此功能，但你可能可以通过为客户端分配静态 IP，然后添加 IPTables FORWARD 规则实现。更多信息请参见[这里](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#vpn-%E5%86%85%E7%BD%91-ip-%E5%92%8C%E6%B5%81%E9%87%8F)。
