### ISSUE TITLE
windows链接不稳定的情况

### ISSUE THREAD

**Issue by sick88** [hwdsl2/setup-ipsec-vpn#1356]
windows连接vpn之后google youtube之类网站提示ERR_CONNECTION_TIMED_OUT.有时又可以正常访问,切换过DNS.没能解决这个现象,请问有什么好的建议吗

**Comment by hwdsl2** [comment]
@sick88 你好！根据你的描述，可能是 MTU/MSS 问题。请尝试[这里](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#%E8%BF%9E%E6%8E%A5-ikev2-%E5%90%8E%E4%B8%8D%E8%83%BD%E6%89%93%E5%BC%80%E7%BD%91%E7%AB%99)的几个解决方案。
