### ISSUE TITLE
ipsec status - Pluto is not running

### ISSUE THREAD

**Issue by DenimMerzhan** [hwdsl2/setup-ipsec-vpn#1359]
Hello, I tried to find the answer on the Internet but without success.

I am using ubuniti 20.04 as OS, after all the steps I ran the script installation and everything went well
I got my login details but my iPhone can't connect

I read the possible errors and tried to run the ipsec status command however it gave the error Pluto is not running (no "/run/pluto/pluto.ctl")

Tell me what should I do?

Before that, I set up the server and received the configuration file on my phone and it worked, but I need to connect using the IP data and password

**Comment by hwdsl2** [comment]
@DenimMerzhan Hello! Please try restarting the IPsec service on your VPN server:

sudo service ipsec restart

To check the IPsec logs for errors, try:

grep pluto /var/log/auth.log

You can also set up the VPN again on a new server.
