### ISSUE TITLE
有点问题

### ISSUE THREAD

**Issue by rockts** [hwdsl2/setup-ipsec-vpn#136]
不知道为什么
1、路由器可以连接上
2、Mac可以连接上
3、win10一直连接不上。
我的VPN 用的国外的VPS ，但不知道为什么连接上了。也不能访问国外网站
4、还有怎么可以把本地Ip变成VPN公网IP来使用？
连接上VPN 完全不知道能干吗

**Comment by klzsysy** [comment]
你的是什么路由？cisco吗 能否分享一下配置

**Comment by hwdsl2** [comment]
@rockts 请尝试故障排除步骤：
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除
