### ISSUE TITLE
I don't become anonymous

### ISSUE THREAD

**Issue by ecalcutin** [hwdsl2/setup-ipsec-vpn#1360]
I am located in Romania. Google detects like I am from Romania.

I bought VPS based in **Republic of Moldova** and made this VPS act as VPN.
Once connected as IKEv2 client, I got that's VPS IP, I am able to open resources what I was not able to open without VPN, but I don't become anonymous.
For instance Google knows what I am still using its services from **Romania**, and my new IP (from Moldova) doesn't matter.

I'd like to expect that Google will treat me as user from Moldova, other VPN apps or Chrome extensions make it possible (e.g. VeeVPN chrome extension).

Let me know, what I am doing wrong? Why some services treat me as Romania user, while I am using VPN(VPS from Moldova) ???

P.S. Using Windows 11
<img width="281" alt="image" src="https://user-images.githubusercontent.com/42963334/229508539-540fcfe4-34d6-444a-af91-0a5cb191d3f6.png">

Maybe I should use another protocol, lets say WireGuard?

**Comment by hwdsl2** [comment]
@ecalcutin Hello! Please check if your computer network has IPv6 enabled. IPv6 traffic can bypass the IKEv2 VPN. Search for "my ip" on Google and see if it shows an IPv6 address.

Other than that, you may try using a private browser window or clear the browser cookies. You can also try WireGuard instead.
