### ISSUE TITLE
whack: Pluto is not running

### ISSUE THREAD

**Issue by eggboy** [hwdsl2/setup-ipsec-vpn#1363]
**Describe the issue**
I upgraded my raspberry pi last week, and VPN stopped working.

**Logs**

$ grep pluto /var/log/auth.log
Apr  9 11:12:31 raspberrypi pluto[16867]: using Linux xfrm kernel support code on #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023
Apr  9 11:12:31 raspberrypi pluto[16867]: ERROR: kernel: xfrm XFRM_MSG_UPDPOLICY add port bypass response for flow (in): Operation not supported (errno 95)
Apr  9 11:12:31 raspberrypi pluto[16867]: FATAL ERROR: kernel: could not insert ICMP_NEIGHBOUR_DISCOVERY bypass policy
Apr  9 11:12:31 raspberrypi pluto[16867]: WARNING: helper threads still running
Apr  9 11:12:31 raspberrypi pluto[16867]: helper(3) seccomp security for helper not supported
Apr  9 11:12:31 raspberrypi pluto[16867]: ABORT: ASSERTION FAILED: event_initialized(ev) (free_signal_handlers() +457 /programs/pluto/server.c)

**Server (please complete the following information)**
$ uname -a
Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

**Comment by letoams** [comment]
Looks like your kernel has no IPsec support Sent using a virtual keyboard on a phoneOn Apr 8, 2023, at 22:32, Jay Lee ***@***.***> wrote:﻿
Describe the issue
I upgraded my raspberry pi last week, and VPN stopped working.
Logs
$ grep pluto /var/log/auth.log
Apr  9 11:12:31 raspberrypi pluto[16867]: using Linux xfrm kernel support code on #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023
Apr  9 11:12:31 raspberrypi pluto[16867]: ERROR: kernel: xfrm XFRM_MSG_UPDPOLICY add port bypass response for flow (in): Operation not supported (errno 95)
Apr  9 11:12:31 raspberrypi pluto[16867]: FATAL ERROR: kernel: could not insert ICMP_NEIGHBOUR_DISCOVERY bypass policy
Apr  9 11:12:31 raspberrypi pluto[16867]: WARNING: helper threads still running
Apr  9 11:12:31 raspberrypi pluto[16867]: helper(3) seccomp security for helper not supported
Apr  9 11:12:31 raspberrypi pluto[16867]: ABORT: ASSERTION FAILED: event_initialized(ev) (free_signal_handlers() +457 /programs/pluto/server.c)
Server (please complete the following information)
$ uname -a
Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux

**Comment by hwdsl2** [comment]
@eggboy Hello! As @letoams said, this may be because your Rapsberry Pi's Linux kernel lacks IPsec support. Please try a different kernel version on your Raspberry Pi to see if it works for the IPsec VPN. You can also try [OpenVPN](https://github.com/hwdsl2/openvpn-install) or [WireGuard](https://github.com/hwdsl2/wireguard-install) instead.
