### ISSUE TITLE
使用ikev2连接chat.openai.com会显示access denied，请问有没有解决的方式？

### ISSUE THREAD

**Issue by DangHuengZing** [hwdsl2/setup-ipsec-vpn#1365]
我试过使用openVPN，也是无法连接。是VPN的种类问题么？
先感激解惑。

**Comment by hwdsl2** [comment]
@DangHuengZing 你好！该错误说明这个网站可能屏蔽了你的服务器提供商的 IP 地址范围，所以更换 VPN 类型并不能解决问题。

**Comment by 234867617** [comment]
你解决了吗

**Comment by HenryCooper86** [comment]
ChatGPT access denied or Error 1020 is related to your VPC IP address, OpenAI uses Cloudflare to block majority VPC services such as AWS Light Sail, Linode, Digital Ocean and so on. You can use a proxy services to change your VPC public address to something that is not blacklisted by OpenAi.
