### ISSUE TITLE
是否有方式能设置前置代理，让出口流量通过前置代理访问互联网

### ISSUE THREAD

**Issue by lxxself** [hwdsl2/setup-ipsec-vpn#1366]
当前使用了docker方式部署，请问下是否有方式能够让它的流量出口是走指定的前置代理（http或socks5代理）。如果是脚本部署，又是如何设置。
另外想问下，当client连接后能禁止clinet访问某个局域网网段么

**Comment by hwdsl2** [comment]
@lxxself 你好！对于你所说的功能，“让出口流量通过前置代理访问互联网”，据我所知并没有好的解决方案。要禁止 client 访问某个网段，你可以尝试添加 IPTables FORWARD 规则。参见脚本的[默认规则](https://github.com/hwdsl2/setup-ipsec-vpn/blob/7ad76833888aae46803cfb3d12baed91ae46c944/vpnsetup_ubuntu.sh#L591-L598)。该方法不一定完全有效。
