### ISSUE TITLE
Error processing signature payload

### ISSUE THREAD

**Issue by CaptainFrosty** [hwdsl2/setup-ipsec-vpn#1368]
Hello, for some reason my IKEv2 VPN stopped working on Windows, and my server is saying it's due to the client choosing disabled protocols I believe:

`
NSS: SGN_Digest(SHA-1) function failed: SEC_ERROR_SIGNATURE_ALGORITHM_DISABLED: Could not create or verify a signature using a signature algorithm that is disabled because it is not secure.
1:ESP=AES_GCM_C_128-DISABLED SPI=d27d5d32 chosen from remote proposals
`

is what my ipsec daemon says. I have no idea why it would start doing that or how to stop it. The configuration on the VPN is correct according to PowerShell.

**Comment by hwdsl2** [comment]
@CaptainFrosty Hello! What is your server's Linux distribution and version? (e.g. CentOS 8 Stream) By default, the SHA-1 algorithm is disabled in CentOS Stream 8 and 9 for certificate signature validation. The VPN scripts [contain a fix](https://github.com/hwdsl2/setup-ipsec-vpn/blob/9f7530fc9bfbd1890ae7952d421c8d11ec424031/vpnsetup_centos.sh#L649-L657) to re-enable the SHA-1 algorithm. 

Edit the file `/etc/crypto-policies/back-ends/nss.config` on your VPN server. Check if it contains `SHA1` on the `allow=` line. If not, replace `allow=` with `allow=SHA1:`. Let us know if this fixes the issue.

**Comment by CaptainFrosty** [comment]
Thanks for your assistance. I am using Rocky Linux 9. That is strange, I don't know why it would randomly downgrade its ciphers; it is actually a recent clean installation of Win 11 22H2 with some group policy applied, but nothing that ought to affect IPsec. 

Yes, my server was missing SHA1 from the config file. It works with SHA1 added. It was my understanding that SHA1 is now vulnerable to collision attacks. It's concerning because it think it involves Schannel and the machine certificate store. It is odd to me that Windows doesn't seem to provide any configuration for the ESP portion of the negotiation. I hope I will able to identify the issue without having to reset this nearly brand new OS. Resetting the network settings doesn't help anything. Most of the errors are coming from the Schannel and LSA event logs.

**Comment by hwdsl2** [comment]
@CaptainFrosty For this use case SHA-1 is likely fine, you can add it to your server configuration as I mentioned above. The generated IKEv2 certificates themselves use the SHA-1 signature algorithm, which may be the reason for this error. This means it might not be a Windows configuration issue in your use case.

**Comment by CaptainFrosty** [comment]
@hwdsl2 The details for the certificate in my store say it uses sha256 for the signature algorithm, but it is still using SHA1 in the connection, which is what I find strange.

**Comment by CaptainFrosty** [comment]
I resolved the issue with

`Set-VpnConnectionIPsecConfiguration -ConnectionName 'IKEv2 VPN 198.98.50.117' -AuthenticationTransformConstants GCMAES128 -CipherTransformConstants GCMAES128 -EncryptionMethod AES256 -IntegrityCheckMethod SHA256 -PfsGroup PFS2048 -DHGroup Group14 -PassThru -Force`

I removed SHA1 from my server crypto policies and after adding PFS2048 to the configuration it is using SHA2 again.
