### ISSUE TITLE
在阿里云使用弹性公网IP 映射在 N个ECS其中之一的时候，导致iptables有问题其他ECS无法访问外网

### ISSUE THREAD

**Issue by maikebing** [hwdsl2/setup-ipsec-vpn#137]
情况是这样的，我在 阿里云有 4台服务器， 负责不同业务， 也有不同的操作系统。 
然后 在 阿里云的VPC 虚拟私人云中建立了映射了一个弹性公网IP， 所谓的EIP . 
通过阿里云的VPC我可以联网，其他三台机子可以通过 这一台对外的机子可以访问外网。 
但当 这台对外的机子安装了 咱的vpn服务后， 就不能上外网了。 

下面的命令是指定10.1.1.0 这个网段的 机子通过 10.1.1.204这个 机子上外网。 这个需要 vpc路由配合

https://help.aliyun.com/knowledge_detail/38776.html?spm=5176.7838743.2.20.9dkp4s
 
iptables -t nat -I POSTROUTING -s 10.1.1.0/24 -j SNAT --to-source 10.1.1.204

**Comment by hwdsl2** [comment]
@maikebing 你好！你这个问题可能是因为 VPN 脚本在 IPTables FORWARD 部分添加了 DROP 导致的。你可以尝试删除该规则：
```
iptables -D FORWARD -j DROP
```

然后保存新的 IPTables 规则：
```
# Ubuntu/Debian
iptables-save > /etc/iptables.rules

# CentOS
iptables-save > /etc/sysconfig/iptables
```

**Comment by maikebing** [comment]
感谢。
