### ISSUE TITLE
IPT_FILE2 is not defined in function enable_on_boot in vpnsetup_ubuntu.sh

### ISSUE THREAD

**Issue by peterjpxie** [hwdsl2/setup-ipsec-vpn#1372]
**Checklist**

- [ x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [ x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [ x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [ x] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [ x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ x] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**
variable IPT_FILE2 is not defined in the function enable_on_boot
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/vpnsetup_ubuntu.sh#L630
```
enable_on_boot() {
  bigecho "Enabling services on boot..."
  IPT_PST=/etc/init.d/iptables-persistent
  IPT_PST2=/usr/share/netfilter-persistent/plugins.d/15-ip4tables
  ipt_load=1
  if [ -f "$IPT_FILE2" ] && { [ -f "$IPT_PST" ] || [ -f "$IPT_PST2" ]; }; then
...
```

I think this line is missing:
```
IPT_FILE2=/etc/iptables/rules.v4
```

**To Reproduce**

1. check the code as mentioned above

**Expected behavior**
variable IPT_FILE2 is defined before use.

**Logs**

**Server (please complete the following information)**
- OS: Ubuntu
- Hosting provider (if applicable): [e.g. GCP, AWS]

**Client (please complete the following information)**
N.A.

**Additional context**
None

**Comment by hwdsl2** [comment]
@peterjpxie Hello! Thank you for reporting this issue. The IPT_FILE2 variable is defined earlier in function "update_iptables" on line 573. This variable continues to be available to the "enable_on_boot" function since the latter is called after "update_iptables", and in shell scripts variables defined in a function are not limited in scope to the function unless the "local" keyword is used. So this should not be an issue in this case.

**Comment by peterjpxie** [comment]
@hwdsl2 thanks for educating!
