### ISSUE TITLE
netmask is always 255.255.255.255 instead of 255.255.255.0

### ISSUE THREAD

**Issue by jariesdev** [hwdsl2/setup-ipsec-vpn#1373]
**Checklist**

- [ x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [ x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [ x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [ ] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x ] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ ] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**
I successfully setup the VPN using the script. My problem was, I need to access services from one client to another. the problem is client1 cant connect to client2 and viseversa but can from C1 -> vpnserver -> C2. I also tries custom subnet but netmask always set to 255.255.255.0.

I tries this with normal installation without any secret and net env variables.

vpn server ifconfig
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet x.x.x.x  netmask 255.255.255.0  broadcast x.x.x.x
        inet6 fe80::f03c:93ff:fe20:8826  prefixlen 64  scopeid 0x20<link>
        inet6 2400:8901::f03c:93ff:fe20:8826  prefixlen 64  scopeid 0x0<global>
        ether f2:3c:93:20:88:26  txqueuelen 1000  (Ethernet)
        RX packets 41468  bytes 109681597 (109.6 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 36508  bytes 6179976 (6.1 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 354  bytes 35585 (35.5 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 354  bytes 35585 (35.5 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ppp0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1280
        inet 10.1.0.1  netmask 255.255.255.255  destination 10.1.0.10
        inet6 fe80::9070:3df5:7ace:9b4d  prefixlen 128  scopeid 0x20<link>
        ppp  txqueuelen 3  (Point-to-Point Protocol)
        RX packets 775  bytes 106862 (106.8 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 19  bytes 1536 (1.5 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ppp1: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1280
        inet 10.1.0.1  netmask 255.255.255.255  destination 10.1.0.11
        inet6 fe80::49fc:5c51:9351:31b7  prefixlen 128  scopeid 0x20<link>
        ppp  txqueuelen 3  (Point-to-Point Protocol)
        RX packets 633  bytes 70823 (70.8 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 373  bytes 109314 (109.3 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

here I have client1 10.1.0.10 and client 2 10.1.0.11

**Comment by hwdsl2** [comment]
@jariesdev Hello! Client-to-client traffic is allowed by default. See [Internal VPN IPs and traffic](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#internal-vpn-ips-and-traffic). The net mask 255.255.255.255 is normal because you are using IPsec/L2TP mode and the `ppp` interfaces are point-to-point.

For your use case, the connection from client C1 to client C2 would normally go through the VPN server, while both are connected to the VPN. Check that the firewalls on the VPN clients allow such traffic, as firewalls may block this traffic by default. You may also try the [IKEv2](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md) or [IPsec/XAuth](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md) modes.
