### ISSUE TITLE
CentOS8无法安装？Error: CentOS Linux 8 is EOL and not supported.

### ISSUE THREAD

**Issue by Wendell-zwt** [hwdsl2/setup-ipsec-vpn#1374]
sh vpn.sh
Error: CentOS Linux 8 is EOL and not supported.

**Comment by hwdsl2** [comment]
@Wendell-zwt Hello! CentOS Linux 8 [reached End Of Life (EOL)](https://www.centos.org/centos-linux-eol/) on December 31st, 2021. Please instead use a [supported Linux version](https://github.com/hwdsl2/setup-ipsec-vpn#requirements).
