### ISSUE TITLE
connect failed

### ISSUE THREAD

**Issue by LesenHuang** [hwdsl2/setup-ipsec-vpn#1375]
<img width="1665" alt="截屏2023-05-06 下午8 40 17" src="https://user-images.githubusercontent.com/119478008/236624721-2efa7985-4fd0-4cf0-b8fa-c24d07a3a32d.png">

**Comment by hwdsl2** [comment]
@LesenHuang Hello! According to your logs, your connection may be blocked by the GFW. You may want to try alternative solutions such as Shadowsocks.
