### ISSUE TITLE
How to connect to ikev2 with mikrotik routerOS

### ISSUE THREAD

**Issue by MAhmo0D9** [hwdsl2/setup-ipsec-vpn#1376]
hey there, i have configured this server on my ubuntu VPS and it connect very well. now i have a hap lite mikrotik with routerOS and i need to config my mikrotik as ikev2 client. how to add ikev2 on my mikrotik? i`ve done every tutorials on internet for this, but won`t connect:(
help me >_<

**Comment by hwdsl2** [comment]
@MAhmo0D9 Hello! Please refer to these instructions for RouterOS:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#routeros
