### ISSUE TITLE
Two clients connected, just one ppp0 interface and one rouet ?

### ISSUE THREAD

**Issue by xmaxmex** [hwdsl2/setup-ipsec-vpn#1378]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [ ] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [ ] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ ] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**

**To Reproduce**

1. ...
2. ...

**Expected behavior**

**Logs**
[Check logs and VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status), and add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- OS: [e.g. Debian 11]
- Hosting provider (if applicable): [e.g. GCP, AWS]

**Client (please complete the following information)**
- Device: [e.g. iPhone 12]
- OS: [e.g. iOS 15]
- VPN mode: [IPsec/L2TP, IPsec/XAuth ("Cisco IPsec") or IKEv2]

**Additional context**

Hi,

A have two vpn clients, one mikrotik side, its ok ppp0 and ip 192.168.42.10.

And android strongswan, with sswan file, just say connected!

But on Linux server, a ihave only one ppp0 ?

And only route to the ip 192.168.42.10

On Andorid exist a tun1 with ip 192.168.43.10

But on android i cant ping 192.168.43.1?

I can ping 192.168.43.10, tun1 inteface

And on Linux Server doesnt exist routes and a new ppp1 inteface ?

Any help?

**Comment by hwdsl2** [comment]
@xmaxmex Hello! Please see [Internal VPN IPs and traffic](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#internal-vpn-ips-and-traffic). When connecting using IPsec/XAuth ("Cisco IPsec") or IKEv2 mode, the VPN server does NOT have an internal IP within the VPN subnet `192.168.43.0/24`, so it is normal that you cannot ping `192.168.43.1`.

A `ppp` interface is only created if using IPsec/L2TP mode to connect, but not for IPsec/XAuth ("Cisco IPsec") or IKEv2 mode. The Android strongSwan VPN client uses IKEv2 mode, so you won't see a `ppp` interface in this case.
