### ISSUE TITLE
Traffic client-to-client doesnt work!

### ISSUE THREAD

**Issue by xmaxmex** [hwdsl2/setup-ipsec-vpn#1379]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ ] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**

**To Reproduce**

1. Mikrotik as IPsec/L2tp client - ip 192.168.42.10
2. Windows 11 IPsec Pres ahred key client - ip 192.168.42.11

**Expected behavior**

Ping both clients

**Logs**
[Check logs and VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status), and add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- OS: Ubuuntu 20.04
- Hosting provider (if applicable): VMS

**Client (please complete the following information)**
- Device: Mikrotik 6.x
- OS: RouterOS
- VPN mode: IPsec/L2TP

**Additional context**

On windows 11, using the reg tip, i can connect on IPsec/L2tp, and get ip address 192.168.42.11, ping server 192.168.42.1 ok.

Both client-to-client traffic doesnt work!?

My Mikrotik with firewall disabled with ip 192.168.42.10, cant ping windows with firewall disabled with ip 192.168.42.11

My goal is on windows client side acces a subnet on back mikrotik client (100.64.0.0/24)

Add a route rule on Linux vpn server, on server i can ping this subnet add 192.168.42.10 as gateway

route add -net 100.64.0.0 netmask 255.255.255.0 gw 192.168.42.10 

Any tip?

**Comment by hwdsl2** [comment]
@xmaxmex Hello! Client-to-client traffic is enabled by default [1]. For your use case, if you cannot ping from client `192.168.42.10` to the Windows client at `192.168.42.11`, it is most likely blocked by the firewall on Windows. To confirm that this is the case, you can try pinging `192.168.42.11` from `192.168.42.10`. For troubleshooting purposes, you can temporarily remove the DROP rule [2] from the IPTables FORWARD chain, see if that helps, then add it back.

From a connected VPN client, unfortunately it is generally difficult to access the subnet behind another connected VPN client. This use case is not currently supported in this project. You can instead give [WireGuard](https://github.com/hwdsl2/wireguard-install) or [OpenVPN](https://github.com/hwdsl2/openvpn-install) a try, to see if they work for this use case.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/d343401ccacadc5bf919b8191911b24fb7f154de/vpnsetup_ubuntu.sh#L591-L598
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/d343401ccacadc5bf919b8191911b24fb7f154de/vpnsetup_ubuntu.sh#L598
