### ISSUE TITLE
无法找到 PFX 密码

### ISSUE THREAD

**Issue by pengweichu** [hwdsl2/setup-ipsec-vpn#1381]
**任务列表**

- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [x] 我检查了 [IKEv1 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#ikev1-故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#ikev2-故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] 这个 bug 是关于 VPN 安装脚本，而不是 IPsec VPN 本身

**问题描述**
按照手册使用脚本自动安装 VPN 之后，运行 ikev2_config_import.cmd ，输入连接名和IP 地址后，要求我输入 PFX 密码，但是我在安装成功后的屏幕输出信息里并没有看到 P12 的密码。（我之前按照这个步骤安装过很多次都没有问题）

**重现步骤**
重现该 bug 的步骤：

1. 卸载当前已经安装的 VPN: 
`wget https://get.vpnsetup.net/unst -O unst.sh &&sudo bash unst.sh`

2.  rm -rf * 删除当前 root 目录下所有的文件
3. 运行脚本安装 VPN： `wget https://get.vpnsetup.net/ -O vpn.sh && sudo sh vpn.sh`
得到的输出如下，并没有看到 P12 证书的密码：

```
+ wget -t 3 -T 30 -q -O /tmp/vpn.zlBFm/vpn.sh https://raw.githubusercontent.com/hwdsl2/setup-ipsec-vpn/master/vpnsetup_ubuntu.sh
## VPN credentials not set by user. Generating random PSK and password...
## VPN setup in progress... Please be patient.
## Installing packages required for setup...
+ apt-get -yqq update
+ apt-get -yqq install wget dnsutils openssl iptables iproute2 gawk grep sed net-tools
## Trying to auto discover IP of this server...
## Installing packages required for the VPN...
+ apt-get -yqq install libnss3-dev libnspr4-dev pkg-config libpam0g-dev libcap-ng-dev libcap-ng-utils libselinux1-dev libcurl4-nss-dev flex bison gcc make libnss3-tools libevent-dev libsystemd-dev uuid-runtime ppp xl2tpd
## Installing Fail2Ban to protect SSH...
+ apt-get -yqq install fail2ban
## Downloading helper scripts...
+ ikev2.sh addvpnuser.sh delvpnuser.sh
## Downloading Libreswan...
+ wget -t 3 -T 30 -q -O libreswan-4.11.tar.gz https://github.com/libreswan/libreswan/archive/v4.11.tar.gz
## Compiling and installing Libreswan, please wait...
+ make -j3 -s base
+ make -s install-base
## Creating VPN configuration...
## Updating sysctl settings...
## Updating IPTables rules...
## Enabling services on boot...
## Starting services...

================================================

IPsec VPN server is now ready for use!

Connect to your new VPN with these details:

Server IP: 184.72.xx.xxx
IPsec PSK: xxxxx
Username: vpnuser
Password: xxxxx

Write these down. You'll need them to connect!

VPN client setup: https://vpnsetup.net/clients

================================================

================================================

IKEv2 setup successful. Details for IKEv2 mode:

VPN server address: 184.72.xx.xxx
VPN client name: vpnclient

Client configuration is available at:
/root/vpnclient.p12 (for Windows & Linux)
/root/vpnclient.sswan (for Android)
/root/vpnclient.mobileconfig (for iOS & macOS)

Next steps: Configure IKEv2 clients. See:
https://vpnsetup.net/clients

================================================

```
4. 下载 /root 下所有文件，然后在 Windows 10 中以管理员权限运行 ` ikev2_config_import.cmd`
提示我输入PFX 密码，直接按回车失败。

```
Importing .p12 file...
When prompted, enter the password for client config files, which can be found
in the output of the IKEv2 helper script on your server.
Enter PFX password:
CertUtil: -importPFX command FAILED: 0x80090006 (-2146893818 NTE_BAD_SIGNATURE)
CertUtil: Invalid Signature.
Enter PFX password:

```

**期待的正确结果**
希望在安装后正确输出密码，或者不设置密码。

**日志**

**服务器信息（请填写以下信息）**
- 操作系统: [比如 Debian 11]: Ubuntu 22.04.2 LTS (GNU/Linux 5.19.0-1024-aws x86_64)

- 服务提供商（如果适用）: [比如 GCP, AWS]: AWS

**客户端信息（请填写以下信息）**
- 设备: PC
- 操作系统:  Windows 10, 22H2, OS build 19045.2965
- VPN 模式: IKEv2

**其它信息**
添加关于该 bug 的其它信息。

**Comment by hwdsl2** [comment]
@pengweichu 你好！我使用 Ubuntu 22.04 和 Windows 10 22H2 客户端测试，无法重现此问题，卸载后重新安装 VPN 后，新的 p12 文件可以成功导入。你确定你的系统是 Ubuntu 22.04？请使用 `cat /etc/os-release` 查看。

**Comment by Ruinique** [comment]
> 我重新尝试安装，加上了 VPN_PROTECT_CONFIG=yes 参数，安装后看到了 P12 证书的密码。 然后在客户端用脚本配置的时候，输入 P12 证书密码，还是一样的错误。
> 
> 我的 WINDOWS 版本： windows 10, 22H2, OS build 19045.2965

请问你现在解决这个问题了吗，我遇到了一样的问题，windows 11,
