### ISSUE TITLE
Consider setting VPN_IFACE before setting NET_IF0

### ISSUE THREAD

**Issue by jonalmeida** [hwdsl2/setup-ipsec-vpn#139]
I may be wrong about the basis of my suggestion, but it would seem better to set `VPN_IFACE` first ([#L78](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/vpnsetup.sh#L78)) and then try to call `NET_IF0` and `NET_IFS` after that.

This would check if the correct NIC exists, and then uses that, else, it uses the `eth0` default.

**Comment by hwdsl2** [comment]
@jonalmeida Hello! Thanks for the suggestion. However, the error message when 'eth0' is unavailable was added intentionally, in order to protect users from accidentally running the VPN setup script on their PC or Mac (with Wi-Fi). See #126.
