### ISSUE TITLE
ike 身份验证凭证不可接受

### ISSUE THREAD

**Issue by q10283245** [hwdsl2/setup-ipsec-vpn#1391]
在安装过程中已经分配了同一个域名 但是在windows中导入证书后连接的时候提示 身份验证凭证不可接受
在安卓中 导入sswan文件 也提示鉴权失败
 我确定已经保证了域名是一致的 并且使用更改域名脚本进行了确认 更该域名脚本执行结果如下
 root@Ipsec:~# bash ikev2addr.sh 
Welcome! Use this script to change this IKEv2 VPN server's address.

Current server address: open.wfsever.cn

Do you want IKEv2 VPN clients to connect to this server using a DNS name,
e.g. vpn.example.com, instead of its IP address? [y/N] y

Enter the DNS name of this VPN server: open.wfsever.cn

Error: IKEv2 server address is already 'open.wfsever.cn'. Nothing to do.
Abort. No changes were made.

**Comment by hwdsl2** [comment]
@q10283245 你好！请检查 Windows 客户端的 VPN 连接属性 -> 服务器地址，是否输入了服务器的域名而不是 IP 地址。另外检查 sswan 文件中是否是正确的域名。你也可以尝试卸载并重新安装 VPN。

**Comment by q10283245** [comment]
我在安装的时候使用的是域名 而不是IP地址 所以sswan文件和VPN连接属性->服务器地址中都是使用的域名并且确保vpn中的地址就是域名

**Comment by q10283245** [comment]
我在安装的时候使用的是域名而不是IP地址所以sswan文件和VPN连接属性-&gt;服务器地址中都是使用的域名并确保vpn中的域名就是域名
至于重新安装我已经多次尝试了使用pve单独架设一个debian和使用群晖的docker进行安装 但是结果都是一样的问题 IKV用户凭证不被接受 或者安卓的用户鉴权失败




晚风
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hwdsl2/setup-ipsec-vpn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月23日(星期二) 晚上11:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hwdsl2/setup-ipsec-vpn] ike 身份验证凭证不可接受 (Issue #1391)





 
@q10283245 你好！请检查 Windows 客户端的 VPN 连接属性 -&gt; 服务器地址，是否输入了服务器的域名而不是 IP 地址。另外检查 sswan 文件中是否是正确的域名。你也可以尝试卸载并重新安装 VPN。

**Comment by hwdsl2** [comment]
@q10283245 如果你的域名启用了 IPv6，可以移除 AAAA 记录试试看。根据你的描述，很可能是因为别的错误导致的。你可以[检查 VPN 日志](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E6%A3%80%E6%9F%A5%E6%97%A5%E5%BF%97%E5%8F%8A-vpn-%E7%8A%B6%E6%80%81)是否有详细的错误信息。另外可以查看一下安卓 strongSwan 客户端的连接日志。

**Comment by q10283245** [comment]
我使用的是二级域名  open.xxxx.cn

**Comment by hwdsl2** [comment]
@q10283245 是的，如上所述，请检查一下VPN服务器上的日志以及客户端连接的strongSwan客户端日志，有没有相关的错误信息。可以把IP等信息去掉。
