### ISSUE TITLE
配置成功后可以用一段时间，之后不管用，然后过一段时间又能用。

### ISSUE THREAD

**Issue by YKai87** [hwdsl2/setup-ipsec-vpn#1394]
自己一个人用，用一段时间（时间长短不定），就链接不上去。在此过程中，有时候修改密码和秘钥又可以用，然后不能用后，再次修改密码和密码又不能用。
然后过一段时间（时间长短不定），又能用了，不知道咋回事。

**Comment by hwdsl2** [comment]
@YKai87 你好！IPsec VPN 较容易被干扰或屏蔽。对于此用例，建议换用其他解决方案比如 Shadowsocks。
