### ISSUE TITLE
ikev2配置完成后，过了一天就用不了了

### ISSUE THREAD

**Issue by 01shu** [hwdsl2/setup-ipsec-vpn#1395]
**任务列表**

- [ √] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [  √] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [ √ ] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [ √ ] 我检查了 [IKEv1 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#ikev1-故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#ikev2-故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [  √] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ ] 这个 bug 是关于 VPN 安装脚本，而不是 IPsec VPN 本身

**问题描述**
ikev2配置完成后，过了一天就用不了了。在windows连接的时候，报错信息如下：
无法建立计算机与 vpn 服务器之间的网络连接 因为远程服务器未响应。这可能是因为未将计算机与远程服务器之间的某种网络设备(如防火墙、nat、路由器等)配置为允许 vpn 连接。

**服务器信息（请填写以下信息）**
- 操作系统: [centos8]
- 服务提供商（如果适用）: [vultr]

**客户端信息（请填写以下信息）**
- 设备: [iPhone 14]
- 操作系统: [Windows 10]
- VPN 模式: [IKEv2]

**其它信息**
添加关于该 bug 的其它信息。

**Comment by hwdsl2** [comment]
@01shu 你好！IPsec VPN 较容易被干扰或屏蔽。对于此用例，建议换用其他解决方案比如 Shadowsocks。

**Comment by 01shu** [comment]
> 



> @01shu你好！IPsec VPN更容易被干扰乱或屏幕亮。对于这个例子，建议换用其他解决方案比如Shadowsocks。

为什么会出现这种情况呢？解决方法就只能使用shadowsocks吗？
