### ISSUE TITLE
multi-user vpn management

### ISSUE THREAD

**Issue by LesenHuang** [hwdsl2/setup-ipsec-vpn#1397]
There are user names and passwords in the vpn service connection configuration, whether it is possible to create multiple users and set the number of connections and traffic control. like multi-user vpn management.
----  This article uses Google Translate

**Comment by hwdsl2** [comment]
@LesenHuang Hello! Please refer to [Manage VPN users](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users.md). Setting the number of connections and traffic control are not supported in this project.
