### ISSUE TITLE
How to connect VPN server using IPsec credential, not configuration file.

### ISSUE THREAD

**Issue by YouthDream0925** [hwdsl2/setup-ipsec-vpn#1398]
Hi, Lin Song. How are you?

I want to connect VPN server using IPsec credential, not configuration file. Is it possible?
![Screenshot_2](https://github.com/hwdsl2/setup-ipsec-vpn/assets/122069772/67bc3567-b716-4df7-9031-3629b1b80045)

After VPN setting in my linux server, I got IPsec credentials like this picture. I want to connect VPN server using this credential. Can you help me?

**Comment by hwdsl2** [comment]
@YouthDream0925 Hello! Please see these instructions:

https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md

https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md
