### ISSUE TITLE
能否配置为使用不带 IPsec 的裸 L2TP 方式？

### ISSUE THREAD

**Issue by Jianru-Lin** [hwdsl2/setup-ipsec-vpn#140]
脚本非常好用，实在是极有帮助的工具！

但是有些地方不太明白，冒昧请教，能否配置为使用不带 IPsec 的裸 L2TP 方式？

具体来说，我通过 iOS 使用 IPSec 方式连接无问题，可以代理流量访问站点。不过我注意到在 iOS 创建 VPN 配置时，如果选择 L2TP 模式，则有一个额外的开关“发送所有流量”，而 IPSec 和 IKEv2 方式都没有这个开关。

我尝试了更改为 L2TP 方式连接。但是并未成功。请问是否支持这一方式？如果支持，我猜我的使用方法不对，还请提示一二。

谢谢！

**Comment by hwdsl2** [comment]
@Jianru-Lin 你好！iOS VPN 的 L2TP 模式其实就是 IPsec/L2TP （脚本支持这个模式）, 不是你所说的 “不带 IPsec 的裸 L2TP 方式”。不带 IPsec 的 L2TP 是不加密的，所以很少使用。另外，在使用 Cisco IPsec 模式连接时，默认也是发送所有流量，那个没有问题。

如果 L2TP 方式连接不成功，有可能是被“防火墙”屏蔽了。你也可以尝试重启服务器上的服务并重试连接：
```
sudo service ipsec restart
sudo service xl2tpd restart
```

**Comment by Jianru-Lin** [comment]
@hwdsl2 感谢指导！

**Comment by HaiBinXiaoCheng** [comment]
您好，想问个问题，iOS-Cisco IPsec能不能不发送所有流量，只发送自己指定目的IP的流量

**Comment by hwdsl2** [comment]
@HaiBinXiaoCheng 你好！不支持只发送指定目的IP的流量。
