### ISSUE TITLE
登陆立刻被封

### ISSUE THREAD

**Issue by dtiansong** [hwdsl2/setup-ipsec-vpn#1400]
**任务列表**

- [Y ] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [ Y] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [Y] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [ Y] 我检查了 [IKEv1 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#ikev1-故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#ikev2-故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [ Y] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ N] 这个 bug 是关于 VPN 安装脚本，而不是 IPsec VPN 本身

**问题描述**
The VPN is getting blocked as soon as I log in, and it's using the IPSec protocol. I'm using the VPN terminal that comes with IOS. 

**重现步骤**
重现该 bug 的步骤：

**期待的正确结果**
简要地描述你期望的正确结果。

**日志**
[检查日志及 VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)，并添加错误日志以帮助解释该问题（如果适用）。

**服务器信息（请填写以下信息）**
- 操作系统: [比如 Debian 11]
- 服务提供商（如果适用）: AWS
- 

**客户端信息（请填写以下信息）**
chip：Apple M1 ProMemory16 GB
OS：macos 13.4(22F66)
- VPN 模式: [IPsec/L2TP,

**其它信息**
添加关于该 bug 的其它信息。

**Comment by hwdsl2** [comment]
@dtiansong 你好！IPsec VPN 较容易被干扰或屏蔽。对于此用例，建议换用其他解决方案比如 Shadowsocks。
