### ISSUE TITLE
Problem to connect with Android Devices and Windows.

### ISSUE THREAD

**Issue by mazyaar** [hwdsl2/setup-ipsec-vpn#1401]
I hav problem to connect to server with Android Device and window 11 but on iPhone and Routerboard works with no problem.

**Comment by hwdsl2** [comment]
@mazyaar Hello! For Android devices, please follow instructions for: [IKEv2](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#android) (recommended), [IPsec/L2TP](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#android) or [IPsec/XAuth](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md#android) mode.
For Windows 11, see instructions for [IKEv2 mode](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#windows-7-8-10-and-11). Alternatively, you can connect using [IPsec/L2TP mode](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#windows), but a one-time registry change will be required. See the linked documentation for more details.
