### ISSUE TITLE
支持IPV6

### ISSUE THREAD

**Issue by seekwindow** [hwdsl2/setup-ipsec-vpn#1408]
IPV4很快会失效，需要经常更改IP。能否添加IPV6支持。

**Comment by hwdsl2** [comment]
@seekwindow 你好！感谢你的建议。IPv4应该不会失效。本项目使用 Libreswan 作为 IPsec 服务器软件，当前的 Libreswan 版本不支持为客户端同时分配 IPv4 和 IPv6 地址。因为该局限性，本项目短期内没有支持 IPv6 的计划。

**Comment by seekwindow** [comment]
我的意思，IPV4很容易被GFW识别并屏蔽，所以需要经常更换。
如果不能同时支持，能否考虑单独支持IPV6。我的SS代理使用IPV6非常稳定，希望VPN也支持IPV6，这样iPhone使用比较方便。
