### ISSUE TITLE
Can't get local DNS to work through this.

### ISSUE THREAD

**Issue by thomas-frantz** [hwdsl2/setup-ipsec-vpn#141]
Now, first off, this isn't necessarily an issue with the script, but I figure this would be the best place to look for help since you all would be most familiar with the script. So, thanks in advance, even though this may not be your problem, and may not even be an issue with the script, but I appreciate the help nevertheless.

Basically, I'm setting up an IPSec +XAuth VPN, as well as pihole ( https://github.com/pi-hole/pi-hole/ ) on a digital ocean VPN so that I can get adblocking on my phone (also has the added benefit that all my phone traffic is going through to the internet using a route I know about.)

Network setup:
Digital Ocean droplet:
 - eth0 is the public/internet static IP
 - eth1 <Local/Private IP> 10.128.50.30

I got my android able to connect to the VPN via public (of course) and it can look at the pihole web admin interface just fine on 10.128.50.30, though I did have to add `-A INPUT -s 192.168.0.43/24 -j ACCEPT` in order for it to get to that point, but yeah.

Now, on my android in the IPSec VPN config, I set 10.128.50.30 as the DNS address. Locally on the server, I can do an nslookup, set DNS to 10.128.50.30 and look up domains just fine - I can even see in the pihole web admin where the local box is looking things up. But my phone? Nope.

At this point, I'm not sure what it could be, and I don't know hardly anything about ipsec (I know a lot about openvpn, but don't want to root my phone.) I've considered

 - Maybe it's not routing 10.128.50.30 through the VPN, but then the admin page wouldn't work at all
 - Maybe it's not routing DNS through the VPN, but I'm not sure how I can confirm this from my phone (as in, maybe it's trying to do DNS lookups outside of the VPN then route just the connection to the resolved server through the VPN?) But that seems kind of odd, I don't know why it would do that. I would assume android and ipsec would route **all** traffic through, once connected.
 - Maybe the firewall is blocking it or not setup to route like I'm trying to do? I tried disabling all the DROPs temporarily, but still no go. I've got next to no experience setting up NATs and all that, so I'm not sure there.

As I said above, my goal is basically to have a digital ocean box I can VPN my phone into, which has pihole setup on it, but only accessible from the VPN itself (I don't really want to run a public DNS or easily viewable web admin :)

**Comment by thomas-frantz** [comment]
Alright, so I ended up getting this to work finally, I had to add in a few iptables prerouting rules for it, as well as a few input/output.

**Comment by amgadfahmi** [comment]
hi @thomas-frantz am trying to do the same using local dns server (unbound) i tried to do the same but with no luck so far, would you please share more details like iptable sample + whats the ip configured as local dns for vpn server  in the /etc/ppp/options.xl2tpd and /etc/ipsec.conf 
was there any other changes !

**Comment by joelfischerr** [comment]
@amgadfahmi Have you found a solution to this?
