### ISSUE TITLE
能增加一个linux/ubuntu的IKEv2的无界面配置吗

### ISSUE THREAD

**Issue by onebyoneby** [hwdsl2/setup-ipsec-vpn#1412]
需要做点对点加密协议，但是始终无法解决无桌面吧linux系统的IKEv2的配置

**Comment by hwdsl2** [comment]
@onebyoneby 你好！关于 Linux 命令行连接 IKEv2 请参见：#1007, #1060, #1213, #1399。我打算有空整理和测试一下并加到文档里。
