### ISSUE TITLE
我使用L2TP，但是无法访问任何网络

### ISSUE THREAD

**Issue by onebyoneby** [hwdsl2/setup-ipsec-vpn#1413]
![image](https://github.com/hwdsl2/setup-ipsec-vpn/assets/50565415/4e492e33-8759-4cf2-8007-8c0ca682465b)

所有设置包括ipsec 链接都成功的

**Comment by onebyoneby** [comment]
无法访问任务网络

**Comment by onebyoneby** [comment]
![image](https://github.com/hwdsl2/setup-ipsec-vpn/assets/50565415/81e86857-7cd9-4bb9-a4f9-d92c93f5fe04)

**Comment by hwdsl2** [comment]
@onebyoneby 你好！你所说的问题有可能是连接被 GFW 干扰或屏蔽，也可能是 IPTables 规则的问题。对于前者，你可以另外尝试比如 Shadowsocks。对于后者，你可以 [卸载](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/uninstall-zh.md)然后[重新安装 VPN](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#%E5%AE%89%E8%A3%85%E8%AF%B4%E6%98%8E) 试试看，或者换一个新的服务器安装。
