### ISSUE TITLE
aliyun部署被墙

### ISSUE THREAD

**Issue by wujw1992** [hwdsl2/setup-ipsec-vpn#1414]
阿里云部署后，使用不一会儿就被墙了，通过更改弹性IP，又可用了，但是不久还是会被墙，请问是否有更好的办法？

**Comment by hwdsl2** [comment]
@wujw1992 你好！IPsec VPN 较容易被干扰或屏蔽。对于该用例，请另外使用其他解决方案，比如 Shadowsocks。
