### ISSUE TITLE
Connecting to IPSec IKEv2 VPN from CLI

### ISSUE THREAD

**Issue by rohittp0** [hwdsl2/setup-ipsec-vpn#1415]
**Checklist**

- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [x] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
This is not really an enhancement request but since there is no template for question or discussion :)
There is no documentation currently available on connecting to the VPN server from CLI. I am trying to connect an EC2 instance to my VPN, but don't know how to do it.

**Is your enhancement request related to a problem? Please describe.**
No

**Additional context**
I have asked the question on ask Ubuntu as well : https://askubuntu.com/questions/1474340/connecting-to-ipsec-ikev2-vpn-from-cli

**Comment by hwdsl2** [comment]
@rohittp0 Hello! Thank you for your suggestion. For IPsec/L2TP mode please refer to [Configure Linux VPN clients using the command line](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#configure-linux-vpn-clients-using-the-command-line). For IKEv2, please refer to these issues: #1399, #1007, #1060, #1213. The detailed instructions have not yet been added to the documentation in this project, but I plan to do that when I have time.
