### ISSUE TITLE
Setup problem

### ISSUE THREAD

**Issue by mrPuh66** [hwdsl2/setup-ipsec-vpn#1418]
There's a problem when run
> sh ikev2.sh

/usr/bin/ikev2.sh: ikev2.sh: line 768: syntax error
 near unexpected token `('
/usr/bin/ikev2.sh: ikev2.sh: line 768: `  certutil
-z <(head -c 1024 /dev/urandom) \'

**Comment by hwdsl2** [comment]
@mrPuh66 Hello! The IKEv2 helper script should be run using "bash", not "sh".
