### ISSUE TITLE
安卓手机连上vpn但是不能上网，iPhone,Mac,Windows都没有问题

### ISSUE THREAD

**Issue by elsonwx** [hwdsl2/setup-ipsec-vpn#142]
samsung s7 edge能连上vpn但是不能上网，iPhone,Mac,Windows都没有问题，大家有遇到过吗？

**Comment by hwdsl2** [comment]
@elsonwx 你好！请尝试以下步骤：
1. https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#android-6-and-7
2. https://gist.github.com/hwdsl2/9030462#gistcomment-2081914

**Comment by elsonwx** [comment]
回去试试，谢谢啦

**Comment by elsonwx** [comment]
按照第2步设置sha2-truncbug=no解决了，这提醒我们小白遇到问题要先查下文档，翻下issue。

**Comment by Whale-fall** [comment]
> @elsonwx 你好！请尝试以下步骤：
> 
> 1. https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#android-6-and-7
> 2. https://gist.github.com/hwdsl2/9030462#gistcomment-2081914

大佬您好，我按以上步骤尝试了，，但是我的手机还是不能上网，还有其他排查手段么

**Comment by Whale-fall** [comment]
就很奇怪，之前还能使用，但是今天开始qq显示异地登陆被封锁以后，，连上vpn就使得整个手机都无法访问网络，但是这种状态下win10电脑连接手机开的热点能正常访问网站

**Comment by Whale-fall** [comment]
> @Whale-fall 换个vps（换ip）试下呗

我是没有办法才搭了vpn，，ss在手机上不知道什么原因能连接上但是没有数据包发送，， 电脑上用ss挺好的，，这说明ip没有问题吧

**Comment by Whale-fall** [comment]
难道是需要设置dns转发么

**Comment by bulidoge** [comment]
看这个.....我解决了 如果是华为的话很可能是这样 被后台自动清理了https://blog.csdn.net/sxf1061700625/article/details/127476100
