### ISSUE TITLE
配置完成后使用了几个月，但已经有两个星期无法连上了

### ISSUE THREAD

**Issue by hanzi7000** [hwdsl2/setup-ipsec-vpn#1422]
![image](https://github.com/hwdsl2/setup-ipsec-vpn/assets/77834896/a8d0607d-5929-4dc0-a98d-acac16a461e4)
连接失败报错为：L2TP连接尝试失败，因为安全层在初始化与远程计算机的协商时遇到了一个处理错误
请问是什么问题呢？可以麻烦您解答一下吗？
谢谢了。

**Comment by hwdsl2** [comment]
@hanzi7000 你好！IPsec VPN 较容易被 GFW 干扰或屏蔽。对于此用例，建议换用其他解决方案比如 Shadowsocks。
