### ISSUE TITLE
同一个配置信息连接局域网限制

### ISSUE THREAD

**Issue by onebyoneby** [hwdsl2/setup-ipsec-vpn#1423]
我使用了ipsec/L2TP客户端，当我的相同配置，出现在同一局域网内，如192.168.1.10和192.168.1.20同一局域网不同电脑上进行VPN拨号时，首先拨号的那台电脑能成功，第2台电脑拨号不成功。经过测试相同配置在不同路由器上能拨号成功，请问如何在同一局域网内进行相同IPSEC信息进行拨号呢，（跟账号密码无关，已经过测试进行排除）

**Comment by hwdsl2** [comment]
@onebyoneby 你好！由于 IPsec/L2TP 的局限性，如果需要连接在同一个 NAT（比如家用路由器）后面的多个设备，你必须使用 [IKEv2](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md) 或者 [IPsec/XAuth](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth-zh.md) 模式。
