### ISSUE TITLE
VPN 连接失败，Warning: /dev/ppp is missing, and IPsec/L2TP mode may not work

### ISSUE THREAD

**Issue by BaiLuoYan** [hwdsl2/setup-ipsec-vpn#1425]
服务器部署在亚马逊云上，系统是 ubuntu，运行一直都很稳定，但是从上周二开始就连接不上，于是重新部署了一下，部署完成后出现如下警告
<img width="417" alt="image" src="https://github.com/hwdsl2/setup-ipsec-vpn/assets/8652307/6debafff-9bb3-4647-9c87-902e9540ff12">

同样连接不上，以下是连接失败时的 ipsec 日志
<img width="750" alt="image" src="https://github.com/hwdsl2/setup-ipsec-vpn/assets/8652307/6779c7ef-7a81-4316-bcc3-ce36ff3c1e82">

**Comment by hwdsl2** [comment]
@BaiLuoYan 你好！请参见：
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#debian-%E5%86%85%E6%A0%B8

从你的日志来看，可能是连接被GFW屏蔽了。IPsec VPN较容易被屏蔽，对于此用例，你可以换用其他解决方案比如Shadowsocks。
