### ISSUE TITLE
端口转发未作用

### ISSUE THREAD

**Issue by arthur-yyr** [hwdsl2/setup-ipsec-vpn#1426]
**Checklist**

- [x ] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [ x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [ x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [ x] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [ x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ ] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**
我试着让tcp 25565端口转发到其中一个IKEv2客户端，这客户端是一个游戏伺服器
然而我透过此网站检查发现25565窗口并未被打开
https://www.canyouseeme.org
我使用的方式是编辑/etc/rc.local
该档案内容如下：
`#port forward for Game Server
netif=$(route 2>/dev/null | grep -m 1 '^default' | grep -o '[^ ]*$')
iptables -I FORWARD 2 -i "$netif" -d 192.168.43.0/24 -p tcp --dport 25565 -j ACCEPT
iptables -t nat -A PREROUTING -p tcp --dport 25565 -j DNAT --to 192.168.43.98

#Added by hwdsl2 VPN script
(sleep 15
service ipsec restart
service xl2tpd restart
echo 1 > /proc/sys/net/ipv4/ip_forward)&
exit 0`

**To Reproduce**

1. ...
2. ...

**Expected behavior**

**Logs**
[Check logs and VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status), and add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- OS: Debian 11
- Hosting provider : ablenet

**Client (please complete the following information)**
- Device: WindowsPC
- OS: Windows 11
- VPN mode: IKEv2

**Additional context**

**Comment by hwdsl2** [comment]
@arthur-yyr 你好！对于你的用例，请首先确保你的游戏伺服器上的该端口已打开并接受来自外部的连接。除了将你所说的命令添加到 rc.local 之外，你还需要手动在 VPN 伺服器上运行它们以生效。

另外你可以为客户端分配静态 IP，这是可选的。请参见：
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#vpn-%E5%86%85%E7%BD%91-ip-%E5%92%8C%E6%B5%81%E9%87%8F

**Comment by arthur-yyr** [comment]
您好，我之后调查网卡名称，将
netif=$(route 2>/dev/null | grep -m 1 '^default' | grep -o '[^ ]*$')
去掉，并将
"$netif"改为网卡名称后就成功了
之后发现(route 2>/dev/null | grep -m 1 '^default' | grep -o '[^ ]*$')回传的是空字串，导致原本的用法不成功
![Screenshot 2023-07-21 060054](https://github.com/hwdsl2/setup-ipsec-vpn/assets/55269513/0a9407e7-2457-4f76-b9d4-bab8720c0514)
