### ISSUE TITLE
我开放了安全组 链接上后无网络绑定了多个弹性IP

### ISSUE THREAD

**Issue by esoman888** [hwdsl2/setup-ipsec-vpn#1428]
![image](https://github.com/hwdsl2/setup-ipsec-vpn/assets/45381544/0c6432a9-fece-4d2f-9ffb-cf8c4e5187d9)
![image](https://github.com/hwdsl2/setup-ipsec-vpn/assets/45381544/af6f7156-bd58-4958-b01e-6b8468cd71a2)
![image](https://github.com/hwdsl2/setup-ipsec-vpn/assets/45381544/68fd2041-5dea-48ad-9d0e-2b87e93dd980)
![image](https://github.com/hwdsl2/setup-ipsec-vpn/assets/45381544/c92ecd39-7efb-4145-a84d-5cc2e77b584f)
![image](https://github.com/hwdsl2/setup-ipsec-vpn/assets/45381544/aac116b4-c710-4f8e-81e1-2783cb6a8ef1)

**Comment by esoman888** [comment]
写晕了抱歉 
需要重启
service xl2tpd restart

**Comment by hwdsl2** [comment]
@esoman888 你好！你所说的用例目前本项目不支持。对于开放端口，请为 IPsec VPN 打开UDP端口500和4500。
