### ISSUE TITLE
我确认我的IP没有被GW，但是就无法进行VPN链接

### ISSUE THREAD

**Issue by onebyoneby** [hwdsl2/setup-ipsec-vpn#1429]
![image](https://github.com/hwdsl2/setup-ipsec-vpn/assets/50565415/c035d456-c6db-44ba-9a66-c29a0090dc4f)
![image](https://github.com/hwdsl2/setup-ipsec-vpn/assets/50565415/fe450d0a-5413-4296-a82f-8cb9592eb798)
我使用IPSEC/L2TP模式，这是我电脑主机日志，服务器日志，就是无法创建VPN拨号，我也测试过用IKEv2模式，但是这个模式会造成频繁掉线。
我确认我的500、4500、IP都没有被墙

**Comment by onebyoneby** [comment]
![image](https://github.com/hwdsl2/setup-ipsec-vpn/assets/50565415/610e19bb-14c3-45f6-9572-7d385d904a8c)

**Comment by hwdsl2** [comment]
@onebyoneby 你好！IPsec VPN 较容易被屏蔽或干扰。对于此用例，请另外尝试比如 Shadowsocks。使用 nc 测试端口并不能准确反映被GFW屏蔽的情况。

**Comment by onebyoneby** [comment]
我换了IKEv2模式很容易掉线，比IPsec  用的更不好
