### ISSUE TITLE
Multiple Users

### ISSUE THREAD

**Issue by dochemlock** [hwdsl2/setup-ipsec-vpn#143]
When adding new users restarting the services causes the chap-secrets & passed file to revert to the original.

**Comment by hwdsl2** [comment]
@dochemlock Hello! Are you using the Docker image hwdsl2/ipsec-vpn-server? For the Docker container, as mentioned in the important notes [1], after editing the VPN config files, you must also comment out the relevant sections in `/opt/src/run.sh`, to avoid losing your changes on container restart. In your case, you need to comment out lines 202 to 212 [2] of `/opt/src/run.sh`.

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server#important-notes
[2] https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/run.sh#L202-L212
