### ISSUE TITLE
No internet access after connection

### ISSUE THREAD

**Issue by leemurphy1977** [hwdsl2/setup-ipsec-vpn#1430]
Firstly, your script is awesome and has save me so much time and effort.  Appreciate all your work and support on it.

The only issue I have is after I connect successfully, I don't have internet access.  I can connect to any device on the network, but no internet.   The only change I've made is to the DNS server, as we have an internal DNS server.  I can ping an external address and the correct IP is returned (so DNS is working), but the ping fails, and I can't connect to that site. 

I'm not sure if this is due to the gateway of the connection is showing as 0.0.0.0, can I set that to the internal gateway, or is this something to do with IP tables?  I'm using a Raspberry Pi if that matters, and I find IP tables confusing.

**Comment by hwdsl2** [comment]
@leemurphy1977 Hello! This may be an IPTables issue. Check your current IPTables rules using:

sudo iptables -nvL; sudo iptables -nvL -t nat 

Your other option is to uninstall the VPN and reinstall. See project README for more info.
