### ISSUE TITLE
setup with no PSK key

### ISSUE THREAD

**Issue by ilankas** [hwdsl2/setup-ipsec-vpn#1432]
**Checklist**

- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [x] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
I want to be able to run scripts and set up vpn with ability not to use PSK (only username and password)

**Is your enhancement request related to a problem? Please describe.**
I'm not able to connect to vpn wiht my router GUI, as it allows to enter only username and password (no psk)

**Additional context**
<img width="293" alt="Screenshot_1" src="https://github.com/hwdsl2/setup-ipsec-vpn/assets/6858616/ec72a9a1-61e2-4aba-8eb2-c54fa9cb32d8">

**Comment by hwdsl2** [comment]
@ilankas Hello! This feature is not supported. Without an IPsec PSK, VPN traffic will not be encrypted, which defeats the purpose of using a VPN.
