### ISSUE TITLE
IPsec 比 IKev2更加稳定

### ISSUE THREAD

**Issue by onebyoneby** [hwdsl2/setup-ipsec-vpn#1434]
我在自己使用过程中IKev2经常掉线，反而是IPsec更加稳定呢，但是推荐使用IKev2模式。
还有IPsec和IKev2能否绑定IP域名进行VPN链接呢，我尝试把子域名指向IP地址，但是无法建立VPN连接 还是要域名+端口号呢，或者用代理服务器转发到服务器内部的500 、4500端口

**Comment by hwdsl2** [comment]
@onebyoneby 你好！一般来说 IKEv2 比较稳定，有可能与你的网络状况或 GFW 干扰等有关。安装 VPN 时 IKEv2 默认使用 IP 地址，如果要改为域名，你需要更改 IKEv2 服务器地址到该域名。请参见：

https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#%E6%9B%B4%E6%94%B9-ikev2-%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%9C%B0%E5%9D%80

对于 IPsec/XAuth 模式，应该可以直接使用域名连接，无需更改服务器地址。
