### ISSUE TITLE
Non-routable network server

### ISSUE THREAD

**Issue by mrbluecoat** [hwdsl2/setup-ipsec-vpn#1436]
Sorry if this has been asked before, but is it possible to run the IKEv2 on a non-routable network (e.g. 192.168.x or 10.x)? I know it's unusual to have a VPN server behind a NAT with a non-public IP address but I'm interested if this is possible for clients that are also on that same local network.

**Comment by hwdsl2** [comment]
@mrbluecoat Hello! It is possible to run IKEv2 on a local network as you mentioned. Please refer to the "change IKEv2 address" section in the IKEv2 documentation in this project on how to change the server address to your server's local IP. Alternatively, you can specify the VPN_PUBLIC_IP variable (set to your server's local IP) during initial VPN setup.
