### ISSUE TITLE
Have error on connecting to VPN from mobile iOS

### ISSUE THREAD

**Issue by IaManJah** [hwdsl2/setup-ipsec-vpn#1438]
Hello,
I am have problems to connect to VPN (IPsec). I am setup it an year ago. And today I can not connect to VPN from my **mobile operator's** internet. From **cable provider** all connected wells without any problems.
I am try to solved a problem but without a results.

**So, I have logs from **auth.logs** (it is failed connection from mobile provider. Where xx.xxx.4.53 is my IP)**

Aug  7 08:20:22 94997 pluto[1137]: "xauth-psk"[3] xx.xxx.4.53 #2: responding to Main Mode from unknown peer xx.xxx.4.53:48789
Aug  7 08:20:22 94997 pluto[1137]: "xauth-psk"[3] xx.xxx.4.53 #2: sent Main Mode R1
Aug  7 08:20:23 94997 pluto[1137]: "xauth-psk"[3] xx.xxx.4.53 #2: sent Main Mode R2
Aug  7 08:20:23 94997 pluto[1137]: "xauth-psk"[3] xx.xxx.4.53 #2: ignoring informational payload IPSEC_INITIAL_CONTACT, msgid=00000000, length=28
Aug  7 08:20:23 94997 pluto[1137]: "xauth-psk"[3] xx.xxx.4.53 #2: Peer ID is ID_IPV4_ADDR: '10.131.165.110'
Aug  7 08:20:23 94997 pluto[1137]: "xauth-psk"[3] xx.xxx.4.53 #2: switched to "xauth-psk"[4] xx.xxx.4.53
Aug  7 08:20:23 94997 pluto[1137]: "xauth-psk"[3] xx.xxx.4.53: deleting connection instance with peer xx.xxx.4.53 {isakmp=#0/ipsec=#0}
Aug  7 08:20:23 94997 pluto[1137]: "xauth-psk"[4] xx.xxx.4.53 #2: IKE SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA2_256 group=MODP2048}
Aug  7 08:20:23 94997 pluto[1137]: "xauth-psk"[4] xx.xxx.4.53 #2: XAUTH: Sending Username/Password request (MAIN_R3->XAUTH_R0)
Aug  7 08:20:23 94997 pluto[1137]: "xauth-psk"[4] xx.xxx.4.53 #2: XAUTH: password file authentication method requested to authenticate user 'MY_USER_NAME'
Aug  7 08:20:23 94997 pluto[1137]: "xauth-psk"[4] xx.xxx.4.53 #2: XAUTH: password file (/etc/ipsec.d/passwd) open.
Aug  7 08:20:23 94997 pluto[1137]: "xauth-psk"[4] xx.xxx.4.53 #2: XAUTH: success user(MY_USER_NAME:xauth-psk)
Aug  7 08:20:23 94997 pluto[1137]: "xauth-psk"[4] xx.xxx.4.53 #2: XAUTH: User MY_USER_NAME: Authentication Successful
Aug  7 08:20:23 94997 pluto[1137]: "xauth-psk"[4] xx.xxx.4.53 #2: STATE_XAUTH_R1: retransmission; will wait 0.5 seconds for response
Aug  7 08:20:24 94997 pluto[1137]: "xauth-psk"[4] xx.xxx.4.53 #2: STATE_XAUTH_R1: retransmission; will wait 1 seconds for response
Aug  7 08:20:25 94997 pluto[1137]: "xauth-psk"[4] xx.xxx.4.53 #2: STATE_XAUTH_R1: retransmission; will wait 2 seconds for response
Aug  7 08:20:27 94997 pluto[1137]: "xauth-psk"[4] xx.xxx.4.53 #2: STATE_XAUTH_R1: retransmission; will wait 4 seconds for response
Aug  7 08:20:31 94997 pluto[1137]: "xauth-psk"[4] xx.xxx.4.53 #2: STATE_XAUTH_R1: retransmission; will wait 8 seconds for response
Aug  7 08:20:39 94997 pluto[1137]: "xauth-psk"[4] xx.xxx.4.53 #2: STATE_XAUTH_R1: retransmission; will wait 16 seconds for response
Aug  7 08:20:55 94997 pluto[1137]: "xauth-psk"[4] xx.xxx.4.53 #2: STATE_XAUTH_R1: retransmission; will wait 32 seconds for response

**And here is my **success connection** from cable provider (where yyy.yyy.210.145 is my cable provider IP)**

Aug  7 08:21:14 94997 pluto[1137]: "xauth-psk"[5] yyy.yyy.210.145 #3: responding to Main Mode from unknown peer yyy.yyy.210.145:24123
Aug  7 08:21:14 94997 pluto[1137]: "xauth-psk"[5] yyy.yyy.210.145 #3: sent Main Mode R1
Aug  7 08:21:14 94997 pluto[1137]: "xauth-psk"[5] yyy.yyy.210.145 #3: sent Main Mode R2
Aug  7 08:21:14 94997 pluto[1137]: "xauth-psk"[5] yyy.yyy.210.145 #3: ignoring informational payload IPSEC_INITIAL_CONTACT, msgid=00000000, length=28
Aug  7 08:21:14 94997 pluto[1137]: "xauth-psk"[5] yyy.yyy.210.145 #3: Peer ID is ID_IPV4_ADDR: '10.1.30.40'
Aug  7 08:21:14 94997 pluto[1137]: "xauth-psk"[5] yyy.yyy.210.145 #3: switched to "xauth-psk"[6] yyy.yyy.210.145
Aug  7 08:21:14 94997 pluto[1137]: "xauth-psk"[5] yyy.yyy.210.145: deleting connection instance with peer yyy.yyy.210.145 {isakmp=#0/ipsec=#0}
Aug  7 08:21:14 94997 pluto[1137]: "xauth-psk"[6] yyy.yyy.210.145 #3: IKE SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA2_256 group=MODP2048}
Aug  7 08:21:14 94997 pluto[1137]: "xauth-psk"[6] yyy.yyy.210.145 #3: XAUTH: Sending Username/Password request (MAIN_R3->XAUTH_R0)
Aug  7 08:21:14 94997 pluto[1137]: "xauth-psk"[6] yyy.yyy.210.145 #3: XAUTH: password file authentication method requested to authenticate user 'MY_USER_NAME'
Aug  7 08:21:14 94997 pluto[1137]: "xauth-psk"[6] yyy.yyy.210.145 #3: XAUTH: password file (/etc/ipsec.d/passwd) open.
Aug  7 08:21:14 94997 pluto[1137]: "xauth-psk"[6] yyy.yyy.210.145 #3: XAUTH: success user(MY_USER_NAME:xauth-psk)
Aug  7 08:21:14 94997 pluto[1137]: "xauth-psk"[6] yyy.yyy.210.145 #3: XAUTH: User MY_USER_NAME: Authentication Successful
Aug  7 08:21:14 94997 pluto[1137]: "xauth-psk"[6] yyy.yyy.210.145 #3: XAUTH: xauth_inR1(STF_OK)
Aug  7 08:21:14 94997 pluto[1137]: "xauth-psk"[6] yyy.yyy.210.145 #3: IKE SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA2_256 group=MODP2048}
Aug  7 08:21:14 94997 pluto[1137]: | pool 192.168.43.10-192.168.43.250: growing address pool from 0 to 1
Aug  7 08:21:14 94997 pluto[1137]: "xauth-psk"[6] yyy.yyy.210.145 #3: modecfg_inR0(STF_OK)
Aug  7 08:21:14 94997 pluto[1137]: "xauth-psk"[6] yyy.yyy.210.145 #3: sent ModeCfg reply, expecting Ack {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA2_256 group=MODP2048}
Aug  7 08:21:14 94997 pluto[1137]: "xauth-psk"[6] yyy.yyy.210.145 #3: the peer proposed: 0.0.0.0/0 -<all>-> 192.168.43.10/32

Any Ideas why I can not connect to VPN from my mobile operator?

**Comment by hwdsl2** [comment]
@IaManJah Hello! From your logs, it looks like your mobile operator could be blocking your VPN connection. See the lines with "retransmission" in the logs. If connecting from China, it could be due to the GFW. For this use case, you may want to instead try e.g. Shadowsocks.
