### ISSUE TITLE
UDP Ports

### ISSUE THREAD

**Issue by MAGFRG** [hwdsl2/setup-ipsec-vpn#1439]
Hi! Is it possible change default UDP 500/4500 ports?

**Comment by MAGFRG** [comment]
Or what can i do, if 500/4500 blocked by provider?

**Comment by letoams** [comment]
You can set the ike nat port to something else than 4500. Don’t touch the 500 port as it doesn’t support NAT.If both ends are Linux, you can also try enabling TCP (currently not yet supported by apple / android).See man ipsec.conf for syntax on ike ports and tcp.PaulSent using a virtual keyboard on a phoneOn Aug 8, 2023, at 06:57, Mohammed Baskhanov ***@***.***> wrote:﻿
Or what can i do, if 500/4500 blocked by provider?

**Comment by hwdsl2** [comment]
Thanks @letoams!

@MAGFRG Please refer to "leftikeport" in:

https://libreswan.org/man/ipsec.conf.5.html

The file to modify is /etc/ipsec.conf, you'll need to restart the IPsec service (sudo service ipsec restart) when finished.

Note that not all IPsec VPN clients support custom ports.
