### ISSUE TITLE
Can't connect to VPN after install

### ISSUE THREAD

**Issue by goneyukon** [hwdsl2/setup-ipsec-vpn#144]
After installing this on my Pi running the latest version of Ubuntu, everything went well but I can't actually connect to the VPN.  This is what I'm getting when I try to connect on my Mac:

"The VPN server did not respond. Verify the server address and try reconnecting."

Using netcat, I can see the ports are responding over UDP (both locally and using external IP).  I do see this error in the logs which I think may be the culprit:

`/var/log/auth.log:May  8 17:46:26 abpi pluto[12962]: packet from 172.58.XX.XX:43188: initial Main Mode message received on 10.0.1.XXX:500 but no connection has been authorized with policy PSK+XAUTH+IKEV1_ALLOW`

...but I'm not really sure what to do about it.

10.0.1.XXX is my internal IP for my Pi.

Any assistance would be greatly appreciated.

**Comment by hwdsl2** [comment]
Hello! This error usually appears when trying to connect multiple clients
using both Cisco IPsec (IPsec/XAuth) and IPsec/L2TP modes. Only one of
these modes can be used when connecting multiple VPN clients from behind
the same NAT.

To fix, try "sudo service ipsec restart; sudo service xl2tpd restart", OR
reboot your Raspberry Pi. If it works, feel free to close this issue.

**Comment by goneyukon** [comment]
Thank you.  I've tried numerous times to restart the services and reboot the Pi and nothing works.  And I haven't attempted to connect multiple devices at the same time--I can't even connect one.

**Comment by hwdsl2** [comment]
Thanks for the update. Can you please try running the latest version of VPN
setup script again with your previous VPN credentials? It could be that
your Raspberry Pi's local IP changed after you initially run the script.

**Comment by goneyukon** [comment]
It worked miraculously this morning... not sure what changed.  Will go ahead and close.  Thanks all.

**Comment by slasc** [comment]
I was having issues getting getting this working on my Raspberry Pi running Stretch Raspbian. I downgraded my kernel to 4.9.80, and it still didn't work. What finally made it work was changing the left=%defaultroute to left=YOUR_IP which @hwdsl2 suggested above. Thank you, @hwdsl2 !!
