### ISSUE TITLE
你好，我在安装脚本时出现无法链接！

### ISSUE THREAD

**Issue by a834003831** [hwdsl2/setup-ipsec-vpn#1441]
Last login: Sun Aug 13 13:22:35 2023 from 100.104.30.254
root@iZm5eaock376etnkoh3m18Z:~# wget https://get.vpnsetup.net -O vpn.sh && sudo sh vpn.sh
--2023-08-13 13:22:42--  https://get.vpnsetup.net/
Resolving get.vpnsetup.net (get.vpnsetup.net)... 172.67.163.121, 104.21.66.191, 2606:4700:3030::ac43:a379, ...
Connecting to get.vpnsetup.net (get.vpnsetup.net)|172.67.163.121|:443... failed: Connection timed out.
Connecting to get.vpnsetup.net (get.vpnsetup.net)|104.21.66.191|:443... failed: Connection timed out.
Connecting to get.vpnsetup.net (get.vpnsetup.net)|2606:4700:3030::ac43:a379|:443... failed: Network is unreachable.
Connecting to get.vpnsetup.net (get.vpnsetup.net)|2606:4700:3037::6815:42bf|:443... failed: Network is unreachable.

**Comment by hwdsl2** [comment]
@a834003831 你好！请尝试换用以下链接之一：
```
https://github.com/hwdsl2/setup-ipsec-vpn/raw/master/vpnsetup.sh
https://gitlab.com/hwdsl2/setup-ipsec-vpn/-/raw/master/vpnsetup.sh
```
