### ISSUE TITLE
"Always On VPN" .mobileconfig files

### ISSUE THREAD

**Issue by cpujoe** [hwdsl2/setup-ipsec-vpn#1443]
**Checklist**

- [X] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [X] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [X] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [X] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [X] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [X] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
Your ikev2.sh script correctly builds Mac .mobileconfig files. This works well.

Could you add support for (or document the settings needed) to produce the "Always On VPN" .mobileconfig file used by iOS? (Specifically Supervised Devices).

I have tried to put this together using the iMazing Profile Editor tool and Apple Configurator, but I cannot easily get it to work.

**Is your enhancement request related to a problem? Please describe.**
No.

**Additional context**
N/A.

**Comment by hwdsl2** [comment]
@cpujoe Hello! Thank you for your suggestion. However, "always on VPN" is an uncommon use case and the feature is not currently planned for this project. You are welcome to customize the VPN scripts to give it a try yourself.

Currently, as an alternative, the "VPN on demand" feature is supported. For more details please refer to:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#configure-ikev2-vpn-clients
https://support.apple.com/guide/deployment/vpn-overview-depae3d361d0/web
