### ISSUE TITLE
Troubleshooting error during "vpnclient.mobileconfig" creation and import on iOS devices.

### ISSUE THREAD

**Issue by DeVLaB4U** [hwdsl2/setup-ipsec-vpn#1445]
Upon a fresh installation using the "Quick start" method, the "vpnclient.mobileconfig" file is produced. However, this file doesn't successfully import into iOS devices. It appears that there might be a missing or incorrect configuration within the generated "vpnclient.mobileconfig" file.

Reproduction Steps:
To reproduce this issue, please follow these steps:
1. Perform a fresh installation using the "Quick start" method.
2. Obtain the automatically generated "vpnclient.mobileconfig" file.
3. Attempt to import the "vpnclient.mobileconfig" file into an iOS device.

Current Behavior:
However, as described, the "vpnclient.mobileconfig" file fails to import and does not pass XML validation. It seems that there might be missing XML tags after the line:

```
<string>Adds a PKCS#12-formatted certificate</string>
<key>PayloadDisplayName</key>
<string>ikev2_test</string>
```

Specifically, adding the following missing tags appears to resolve the issue:

```
<key>PayloadContent</key>
<data>

```

Please consider investigating this issue.
Thanks!

**Comment by hwdsl2** [comment]
@DeVLaB4U Hello! What is your server's Linux distribution and version (e.g. Ubuntu 22.04)? Please check to make sure the .mobileconfig file is not corrupted when transferring from the VPN server to the VPN client.

The VPN scripts have been tested, and the .mobileconfig file import worked fine in my tests. The lines you mentioned seem to be fine in the script:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/f084bcb0462658a247ca509eaa1817371aac4fd4/extras/ikev2setup.sh#L1004C12-L1004C12

If you have additional information feel free to reply here.

**Comment by DeVLaB4U** [comment]
Yes, needed lines in the scripts, but somehow generated profile does't work nor import.

I try to merge this:
`https://github.com/hwdsl2/setup-ipsec-vpn/pull/1298/commits/a61b7493d97153edc3bc8f6c11125742f32dc9e3 `
and after that i get "vpnclient.`signed`.mobileconfig".

And now this profile import on ios devices and work!

**Comment by hwdsl2** [comment]
@DeVLaB4U What is your server's Linux distribution and version?

**Comment by DeVLaB4U** [comment]
> @DeVLaB4U What is your server's Linux distribution / version?
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"

It is ok ?
