### ISSUE TITLE
经常使用一段时间就不能用了

### ISSUE THREAD

**Issue by lbiaoapp** [hwdsl2/setup-ipsec-vpn#1453]
一台服务器用一两天就不能用了，以为是服务器把UDP端口封了，但是提交工单后，技术人员说商品正常的，然后就有了下边的对话
问：是不是把UDP端口500和4500封了？
答：您好这边看到您的这两个端口处于过滤状态您的防火墙已经放通，辛苦您提供一下您启动服务的截图，以及您运行一下netstat -ano | grep 4500，netstat -ano | grep 500，提供一下截图

<img width="923" alt="image" src="https://github.com/hwdsl2/setup-ipsec-vpn/assets/14230615/8151c5c6-80a8-4733-b33a-3fdcdb9b7100">

**Comment by hwdsl2** [comment]
@lbiaoapp 你好！你的截图显示 VPN 服务器正常监听 10.0.x.x 地址，它可能是服务器的私有 IP，所以这里没有问题，无需修改配置。但是，IPsec VPN 较容易被 GFW 干扰或屏蔽，所以会出现你所说的无法连接的情况。对于此用例，建议换用 IPsec VPN 之外的其他解决方案，比如 Shadowsocks。
