### ISSUE TITLE
смена адреса

### ISSUE THREAD

**Issue by aleksan149** [hwdsl2/setup-ipsec-vpn#1457]
Дорогой друг, скажи, если к моему ikev2 серверу привязано DNS имя, а у сервера сменился ip, смогу ли я подключаться как и раньше без изменения настроек на клиенте? на хостинге DNS я уже сделал новую A запись о смене ip адреса.

**Comment by hwdsl2** [comment]
@aleksan149 Hello! That is correct. If you specified a DNS name when setting up IKEv2, the VPN should continue to work after server IP changes, after you update the DNS record with the new IP.
