### ISSUE TITLE
Как отключить пользователя

### ISSUE THREAD

**Issue by lakafakabich** [hwdsl2/setup-ipsec-vpn#1458]
Как временно отключить пользователя ikev2? Ну или приостановить его работу.

**Comment by hwdsl2** [comment]
@lakafakabich Hello! Please see [Revoke a client certificate](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#revoke-a-client-certificate).

**Comment by lakafakabich** [comment]
@hwdsl2 А можно ли его потом вернуть обратно пользователю?
