### ISSUE TITLE
Setup pihole with ikev2/IPsec

### ISSUE THREAD

**Issue by LouisBeke2** [hwdsl2/setup-ipsec-vpn#1460]
Hi, i want to ask how i can add my pihole to ikev2/IPsec i know that its already was asked but i seems to be not working with me. if it's possible can it be answered in the simplest way?

thank you

**Comment by hwdsl2** [comment]
@LouisBeke2 Hello! Unfortunately this project has not been tested for working with Pi Hole and I am not able to give specific instructions. Please refer to earlier issues regarding setting local DNS server(s) for IKEv2 mode.

**Comment by LouisBeke2** [comment]
hi, how do i edit the local dns to the same machine because pihole and IKEv2 is on the same pc 

and in what files

**Comment by hwdsl2** [comment]
@LouisBeke2 Try using the IP address of that machine. File to edit is /etc/ipsec.d/ikev2.conf, modecfgdns option.

**Comment by LouisBeke** [comment]
now i got this 
![image](https://github.com/hwdsl2/setup-ipsec-vpn/assets/142576734/ab0ec440-1a5c-474c-bb2c-54017d6209eb)
How can i fix it

**Comment by hwdsl2** [comment]
@LouisBeke It could be an issue with your DNS server, although I am not sure.

**Comment by LouisBeke** [comment]
whats this 
![image](https://github.com/hwdsl2/setup-ipsec-vpn/assets/142576734/c76bfbd4-33c9-4a80-b3f8-69c2cba00b3b)
