### ISSUE TITLE
How to move ikev2 clients to another vds server?

### ISSUE THREAD

**Issue by ivangurin** [hwdsl2/setup-ipsec-vpn#1462]
Hello,

is it possible to export all clients from existence vpn server and import to another vpn server? Couse, I don't want to setup each device again.

**Comment by letoams** [comment]
If you take the server config abd server p12 file to the new server and update DNS to point to the new server, yes?Sent using a virtual keyboard on a phoneOn Sep 22, 2023, at 08:33, Ivan Gurin ***@***.***> wrote:﻿
Hello,
is it possible to export all clients from existence vpn server and import to another vpn server? Couse, I don't want to setup each device again.

**Comment by hwdsl2** [comment]
Thanks @letoams!

@ivangurin Please see #1273. In addition, copy `/etc/ipsec.conf` to the new server if you want to migrate configuration for IKEv1. Restart the IPsec service when finished.
