### ISSUE TITLE
IKEv2很快无法连接，同一个VPS的Open VPN还是正常使用

### ISSUE THREAD

**Issue by HuijieLin** [hwdsl2/setup-ipsec-vpn#1465]
设备情况：
iPhone 12 Pro/ 16.6

使用下面脚本搭建的IKEv2，刚搭建完在手机上安装了证书之后，是可以正常连接以及联网，第二天后，就没办法了连接上了，手机一直显示正在连接，我卸载重新安装后，依然还是没办法连接，请问需要如何调试或者排查问题呢
搭建脚本：`wget https://get.vpnsetup.net -O vpn.sh && sudo sh vpn.sh`

但是相同的VPS，使用`wget -O openvpn.sh https://get.vpnsetup.net/ovpn` 搭建的open VPN还是能正常连接的

**Comment by hwdsl2** [comment]
@HuijieLin 你好！IPsec VPN 较容易被 GFW 干扰或屏蔽。对于该用例，请另外使用其他解决方案，比如 Shadowsocks。
