### ISSUE TITLE
请问如何控制流量的分发？

### ISSUE THREAD

**Issue by jazzii36** [hwdsl2/setup-ipsec-vpn#1466]
使用vpn连接后都是全局流量代理远程服务器了么，能否控制部分流量不走服务器？

**Comment by hwdsl2** [comment]
@jazzii36 请参见上面的链接或中文说明：[VPN 分流](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#vpn-%E5%88%86%E6%B5%81)。

**Comment by jazzii36** [comment]
您好，抱歉解释下，我想问的是流量全局代理和部分代理的概念，国内用户对于被墙网站可能希望走代理，而对于国内正常网站如果走代理反而会变慢，请问如何实现这一目标？

**Comment by jazzii36** [comment]
@scottpedia

**Comment by hwdsl2** [comment]
@jazzii36 你好！目前本项目不支持你所说的功能，你可以另外尝试其他解决方案。
