### ISSUE TITLE
Get Active Connections by client name on IKEV2

### ISSUE THREAD

**Issue by IIRobotNinjaII** [hwdsl2/setup-ipsec-vpn#1468]
I was wondering if it would be possible to see active connections on IKEV2 and how much bandwidth they are using.

**Comment by letoams** [comment]
On Tue, 3 Oct 2023, IIRobotNinjaII wrote:

> I was wondering if it would be possible to see active connections on IKEV2 and how much bandwidth they are using.

"ipsec trafficstatus"

**Comment by IIRobotNinjaII** [comment]
Yes this does give me the number of active connections but the client id's associated with them seem to be wrong, how do one identify each connection is made by whom?

**Comment by hwdsl2** [comment]
@IIRobotNinjaII The client IDs should be correct in the output. Make sure that you generate a unique certificate for each client using `sudo ikev2.sh`.

**Comment by letoams** [comment]
On Thu, 5 Oct 2023, IIRobotNinjaII wrote:

> Yes this does give me the number of active connections but the client id's associated with them seem to be wrong, how do one identify each connection is
> made by whom?

It tells you the remote ID? Why is that wrong? I know people who use
this to map it back to endpoint certificates and their traffic usage.

**Comment by kkamenij** [comment]
I agree with the author of the question.
I created a user using ikev2.sh --addclient username
I launched the VPN according to the instructions on Windows using the generated username.p12 file and the VPN on iOS using username.mobileconfig.
And here is my output of the ipsec --trafficstatus command:
`006 #10692: "ikev2-cp"[4338] 95.37.233.3, type=ESP, add_time=1697111970, inBytes=5866918, outBytes=68687854, maxBytes=2^63B, id='CN=vpnclient, O=IKEv2 VPN', lease=192.168.43.15/32
006 #10694: "ikev2-cp"[4348] 95.37.233.3, type=ESP, add_time=1697113520, inBytes=7633, outBytes=29251, maxBytes=2^63B, id='@username', lease=192.168.43.13/32`
as you can see, I'm on the same network (wi-fi) but my "id=" are different.
what could be the problem? how to bring it to one view - the second, which shows the real username that was specified when creating the account?

**Comment by hwdsl2** [comment]
@kkamenij For Windows, the remote ID is displayed like "CN=vpnclient, O=IKEv2 VPN" in the ”ipsec trafficstatus" output. This is normal because Windows sends the remote ID in this way. The string after "CN=" is the VPN client name. In this case, it is "vpnclient". You may have imported vpnclient.p12 to this Windows client.

**Comment by kkamenij** [comment]
I’m telling you exactly that I imported exactly the certificate that was generated for the new user

**Comment by hwdsl2** [comment]
@kkamenij You may have imported the vpnclient certificate earlier on that Windows system before you imported the new certificate. Check your certificate store (run box -> certlm.msc) and remove that one.

It is not possible for Windows to send a remote ID without the corresponding cert.

**Comment by hwdsl2** [comment]
@kkamenij The "trusted root certificate authorities" store should contain the certificate named "IKEv2 VPN CA", issued by "IKEv2 VPN CA". This is the CA certificate. On the other hand, in your "personal" certificate store there should be a certificate named "vpnclient" (or your client name), issued by "IKEv2 VPN CA".

When importing the p12 file using the helper script, these two certificates should be automatically placed into the above mentioned locations, respectively. 

If you manually imported the p12 file and selected to put everything inside "personal", you can move the CA cert to the "trusted root certificate authorities", or if it is already there, just delete "IKEv2 VPN CA" from "personal".

**Comment by kkamenij** [comment]
Damn, I figured out what the problem was.
I installed everything (double click on the certificate) in the root center and there were two certificates there.
As soon as I replaced the first step and installed via certutil, everything worked as it should.
Thank you very much for your prompt support and this tool in general!
