### ISSUE TITLE
Forcing a specific DNS to be used

### ISSUE THREAD

**Issue by r2nuts** [hwdsl2/setup-ipsec-vpn#1469]
Hi there! First of all thank you for the step-by-step guide on vpn setup. 
one thing I would like to change - is a use of specific dns (us based), cannot figure out how can I edit or implement this into the vpn config, can you please suggest
Thank you

**Comment by hwdsl2** [comment]
@r2nuts Hello! Please see Advanced usage:

https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md
