### ISSUE TITLE
notif Client connected or disconected

### ISSUE THREAD

**Issue by horasjey** [hwdsl2/setup-ipsec-vpn#1470]
Hallo,
how to run script bash if user connected or disconected ..?

thak's

**Comment by letoams** [comment]
Add a leftupdown=/your/scriptThis will replace the default updown script so perhaps verify it doesn’t do anything you need.On Oct 6, 2023, at 07:56, Horas Hajovan Siregar ***@***.***> wrote:﻿
Hallo,
how to run script bash if user connected or disconected ..?
thak's

**Comment by hwdsl2** [comment]
@horasjey Add the leftupdown= line with the path to your custom script to file /etc/ipsec.conf and /etc/ipsec.d/ikev2.conf, then run "service ipsec restart".

**Comment by horasjey** [comment]
hallo @hwdsl2 ,
Can we do it to find out what users are connecting to the server and limit only 1 session for 1 user,
I have created a static user, but when I log in on 2 VPN devices, they both get that IP
`"horas" l2tpd "horas" 192.168.42.11` ,
and how to limit bandwidth in/out for users...?


thak's

**Comment by hwdsl2** [comment]
@horasjey Hello! These features are not currently supported in this project.
