### ISSUE TITLE
How to disable ipsec and xl2tpd

### ISSUE THREAD

**Issue by visitoid** [hwdsl2/setup-ipsec-vpn#1471]
Hello! How can I disable services ipsec and xl2tpd on Ubuntu 22 so that they don't load automatically after the server restarts?

**Comment by hwdsl2** [comment]
@visitoid Hello! For your use case, try:

systemctl disable ipsec
systemctl disable xl2tpd

Also edit /etc/rc.local and remove the restart commands for these services.
