### ISSUE TITLE
after a connection to the ikev2 vpn server, how to access internet through a http or socks proxy

### ISSUE THREAD

**Issue by zhou1978a** [hwdsl2/setup-ipsec-vpn#1472]
I have made an IKEv2 vpn server in my company.  The server's local network ip is :192.168.11.172. And there is an another computer with ip 192.168.11.223 which running the clash service.  Opening port is 7890 and 7891 (socks 5). 

my need is this:  after connection to the vpn server, I can access the internet, and data goes through the 192.168.11.223 proxy, so I can access google and youtube service 

any idea?

**Comment by hwdsl2** [comment]
@zhou1978a Hello! This use case is not supported in this project. Unfortunately, I am not aware of a method to send VPN traffic through a proxy as you mentioned.

**Comment by zhou1978a** [comment]
thanks a lot, never mind. It is possible to add an local listener something like gost or redsocks which handle the proxy thing. Then add iptables rules to control data to the local port. But I never make it.
