### ISSUE TITLE
backup

### ISSUE THREAD

**Issue by aleksan149** [hwdsl2/setup-ipsec-vpn#1473]
Привет дорогой друг!
1. Я хочу перенести свой vpn ikev2 на новую машину. Как я могу сделать это, сохранив всех своих пользователей, чтобы не пришлось выпускать новые сертификаты для пользователей? Какие папки нужно скопировать?
С адресом проблем нет, использую доменное имя.
2. Как приостановить сертификат для пользователя, чтобы его потом можно было возобновить, при этом не импортировать новый сертификат на стороне клиента?
Заранее благодарю тебя!

**Comment by hwdsl2** [comment]
@aleksan149 Hello! For transferring IKEv2 configuration to a new server, see issue #1462.

It is not supported to suspend a user certificate.
