### ISSUE TITLE
View data

### ISSUE THREAD

**Issue by skop1986** [hwdsl2/setup-ipsec-vpn#1474]
Hi, how do I view the connection credentials? VPN_IPSEC_PSK VPN_USER VPN_PASSWORD

**Comment by hwdsl2** [comment]
@skop1986 Hello! The connection credentials are displayed in the output of the VPN setup script. If you need to view them after install, see:

https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users.md#view-vpn-users
