### ISSUE TITLE
安装几天就连不上了

### ISSUE THREAD

**Issue by wekyun** [hwdsl2/setup-ipsec-vpn#1475]
刚安装可以用，用了几天就连不上了

[root@xjp ~]# service ipsec start
Redirecting to /bin/systemctl start ipsec.service

**Comment by hwdsl2** [comment]
@wekyun 你好！IPsec VPN 较容易被 GFW 干扰或屏蔽。对于此用例，你可以换用其他解决方案。

**Comment by chgaowei** [comment]
@hwdsl2  有其他的方案推荐吗

**Comment by wekyun** [comment]
只能暂时不用了，前几个月用的一直没问题，更新后才不行了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月23日(周一) 下午2:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hwdsl2/setup-ipsec-vpn] 安装几天就连不上了 (Issue #1475)




 
@hwdsl2  有其他的方案推荐吗
