### ISSUE TITLE
ip

### ISSUE THREAD

**Issue by aleksan149** [hwdsl2/setup-ipsec-vpn#1477]
Друг, такая проблема. Я использую статические адреса для своих клиентов в файле /etc/ipsec.d/ikev2.conf
У меня все хорошо работало, но вдруг мой iphone перестал подключаться к серверу. я удалил запись с присвоенным ip клиента из файла /etc/ipsec.d/ikev2.conf и мой iphone вновь стал подключаться. В чем может быть дело?

**Comment by hwdsl2** [comment]
@aleksan149 Hello! For your use case, I'm not sure why the static IPs stopped working. You can refer to the documentation here:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#internal-vpn-ips-and-traffic
