### ISSUE TITLE
Add support for IPv6 only servers

### ISSUE THREAD

**Issue by Epaphroditus** [hwdsl2/setup-ipsec-vpn#1482]
**Checklist**

- [] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [ ] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [ ] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [ ] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [ ] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [ ] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
Is it possible to modify the script to run using a server that only has an IPv6 address such as Vultr's?

**Is your enhancement request related to a problem? Please describe.**
(If applicable) A clear and concise description of what the problem is.

**Additional context**
Add any other context about the enhancement request here.

I

**Comment by hwdsl2** [comment]
@Epaphroditus Hello! Thank you for your suggestion. Currently, there is no plan to support IPv6 only servers in this project. This would likely require a lot of changes to the current scripts.
