### ISSUE TITLE
How to set up a server with multiple IPs?

### ISSUE THREAD

**Issue by tik216** [hwdsl2/setup-ipsec-vpn#1485]
这个一键脚本非常好用，如果能在多个IP的服务器上使用那就更完美了
This one-click script is very easy to use. It would be even more perfect if it could be used on multiple IP servers.

**Comment by hwdsl2** [comment]
@tik216 你好！请参见 [指定 VPN 服务器的公有 IP](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E6%8C%87%E5%AE%9A-vpn-%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9A%84%E5%85%AC%E6%9C%89-ip)。该说明适用于 Docker 容器的用例。对于不使用 Docker 直接安装，你可以像这样指定 `VPN_PUBLIC_IP`:
```
sudo VPN_PUBLIC_IP=192.0.2.2 sh vpn.sh
```
如果已安装 VPN，需要按照项目文档说明先卸载后重新安装。

**Comment by tik216** [comment]
那多个IP如何建多个L2TP呢

**Comment by hwdsl2** [comment]
@tik216 这个用例目前本项目不支持。同一个服务器不能有多个 IPsec VPN 配置。

**Comment by hwdsl2** [comment]
@tik216 I added a new section to advanced usage in 5dbb6e2, which you can find [here](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#specify-vpn-servers-public-ip).

**Comment by tik216** [comment]
请问在docker里建立多个容器，可以实现多IP，多条L2TP吗？

**Comment by hwdsl2** [comment]
@tik216 你说的用例应该是可以实现的。请参见 [指定 VPN 服务器的公有 IP](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage-zh.md#%E6%8C%87%E5%AE%9A-vpn-%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9A%84%E5%85%AC%E6%9C%89-ip)。

**Comment by tik216** [comment]
好的，非常感谢。实现了给你加鸡腿

**Comment by hwdsl2** [comment]
@tik216 另外对于该用例，在创建 Docker 容器时，`docker run` 命令中的端口转发参数，你可能需要指定一个公有 IP。参见：
https://docs.docker.com/engine/reference/commandline/run/#publish

**Comment by tik216** [comment]
大佬，你干脆出个教程吧
