### ISSUE TITLE
win11连接失败

### ISSUE THREAD

**Issue by 1ryxc3** [hwdsl2/setup-ipsec-vpn#1488]
vpn部署成功IPsec可以在iphone使用，但是win11 l2tp/ipsec模式下显示不能建立到远程计算机的链接，因此用于连接的段口已关闭

**Comment by hwdsl2** [comment]
@1ryxc3 你好！请参见：
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#ikev1-%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4
另外你可以在网上搜索关键字`用于此连接的端口已关闭` ，可以找到其他解决方案。
