### ISSUE TITLE
Passing into the newly issued mobileconfig a new IKEv2 user login and password pair.

### ISSUE THREAD

**Issue by IvanV-001** [hwdsl2/setup-ipsec-vpn#1489]
Hi Mr. Lin,
Thank you a lot for this brilliant script!

A question about new IKEv2 users creation.
Your guidance separately describes a [certificate issuing ](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#add-a-client-certificate) and [an IPSEC new login-password pairs creating with the chap-secrets file](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users.md#manually-manage-vpn-users).

As I understand, the generated certificates and client config files (e.g. .mobileconfig for iOS) has embedded pair login-password as a payload.
Say, I need to create a new IPSEC/IKEv2 user.
Do I understand properly that first - we need to add a user into the **chap-secrets** file, next - to issue the certificates for existing in the file user using [the script.](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#add-a-client-certificate)

So it's not clear for me how to pass into the newly issued .mobileconfig a new IKEv2 user login and password pair.

Thank you,
Ivan

**Comment by hwdsl2** [comment]
@IvanV-001 Hello! To answer your question: This project supports 3 different VPN modes: IPsec/L2TP, IPsec/XAuth ("Cisco IPsec") and IKEv2. You can find more details in the project documentation.

The first two modes use pre-shared key (PSK) plus username/password to authenticate. The IKEv2 mode, however, only uses certificates to authenticate, there is no PSK or password required. The generated `.mobileconfig` file does not contain a username/password pair for authentication.

The [Manage VPN Users](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users.md) instructions are for the IPsec/L2TP and IPsec/XAuth modes, not IKEv2 mode. For IKEv2, you only need to follow the instructions to [add a client certificate](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#add-a-client-certificate).
