### ISSUE TITLE
How can I specifiy a NIC to connect the VPN server 

### ISSUE THREAD

**Issue by encore-zhou** [hwdsl2/setup-ipsec-vpn#149]
For example , I have two network interface in my VPS(eth0 and eth1), both of them  can connect to the network. When I start the ipsec connection with command `sudo ipsect up myvpn`, ipsect will automatically connect the server with eth0. How can I config the ipsec to force it to use  eth1.
Thanks!

**Comment by hwdsl2** [comment]
Hello! I think you are referring to the VPN client side setup on Linux. The
strongSwan VPN client uses your default outgoing network interface for
connections. Not sure about your use case, you may want to get help through
the strongSwan users mailing list.
