### ISSUE TITLE
IKEV2 VPN, listing connected client

### ISSUE THREAD

**Issue by ptorrent** [hwdsl2/setup-ipsec-vpn#1491]
Hello there,

Not sure it's a bug or a missunderstanding..

I'm trying to use  IKEV2 VPN. Was able to export key and send them to my android phone. I was able to create the VPN connection and connect the client. But I've no ppp interface on the serveur, not log output on systemlog and messages.

Did I miss something ?

**To Reproduce**

1. Connect the Android client
2. Wait unit Android client say it's connected
3. Nothing on server side
4.
**Logs**
no logs

**Server **
- Debian 11
- server 5.10.0-20-amd64

**Client**
- Android 13
- IKEv2

Is there a way to list connected client on IKEV2 ?

Thanks for your help !

**Comment by hwdsl2** [comment]
@ptorrent Hello! IKEv2 mode does not create a ppp interface on the server, only the IPsec/L2TP mode does that. So this is normal. To check VPN logs and status, see:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status

For example, to check the status of the IPsec VPN server:
```
ipsec status
```

And to show currently established VPN connections:
```
ipsec trafficstatus
```

**Comment by letoams** [comment]
IKEv2 dos t require or use a ppp interface. That was only there when using IKEv1 with L2TP

**Comment by ptorrent** [comment]
Awesome ! thanks for your support and your job

**Comment by ptorrent** [comment]
Oh other question, is there a way to execute a script when a subnet up ?

same as /etc/ppp/ip-up /etc/ppp/ip-down ?

**Comment by letoams** [comment]
You have to modify the _updown script.PaulSent using a virtual keyboard on a phoneOn Nov 22, 2023, at 11:20, ptorrent ***@***.***> wrote:﻿
Oh other question, is there a way to execute a script when a subnet up ?
same as /etc/ppp/ip-up /etc/ppp/ip-down ?

**Comment by ptorrent** [comment]
Got it thanks !

**Comment by syndicaterus** [comment]
Hi! I want to run a script to send a message to a telegram bot when someone connects to a vpn. How can I implement this? maybe such a question has already arisen?

**Comment by letoams** [comment]
On Tue, 7 May 2024, syndicaterus wrote:

> Hi! I want to run a script to send a message to a telegram bot when someone connects to a vpn. How
> can I implement this? maybe such a question has already arisen?

You copy _updown.xfrm and add your code there. Remember to do
a double fork to not block pluto. Example code see:

https://github.com/libreswan/libreswan/blob/main/contrib/updown-example/example-terminate.py

**Comment by syndicaterus** [comment]
> On Tue, 7 May 2024, syndicaterus wrote: Hi! I want to run a script to send a message to a telegram bot when someone connects to a vpn. How can I implement this? maybe such a question has already arisen?
> You copy _updown.xfrm and add your code there. Remember to do a double fork to not block pluto. Example code see: https://github.com/libreswan/libreswan/blob/main/contrib/updown-example/example-terminate.py

I tried running a random script for sending a telegram message if I connected to a VPN after making changes to the _updown.xfrm file. The bot sends a message with the specified text. For example `python3 /usr/local/bin/example-terminate.py TEST` And I receive a message in telegram.
But now I try to run this script and pass the `python3 /usr/local/bin/example-terminate.py $PLUTO_XAUTH_USERNAME` variable to it, but nothing happens. I have an error:
up-client output: Username:
up-client output: No username provided

Where is my mistake?

**Comment by letoams** [comment]
XAUTH values are only set for IKEv1.
You want the peer id.

**Comment by syndicaterus** [comment]
> XAUTH values are only set for IKEv1. You want the peer id.

Got it, thanks for the answer.

I made a script that executes the` ipsec trafficstatus` command and then sends its data to telegram. This script works, but it does not run if I add it to _updown.xfrm For example: 
```
up-client)
         # connection to my client subnet coming up
         addvtiiface
         updateresolveconf
         addcat
         addsource
         notifyNM connect
         addvti
        /usr/local/sbin/example-terminate.py
```

Are there any ideas so that I can send the peer id in messages in telegram?

**Comment by letoams** [comment]
On Wed, 8 May 2024, syndicaterus wrote:

>       XAUTH values are only set for IKEv1. You want the peer id.
> 
> Got it, thanks for the answer.
> 
> I made a script that executes the ipsec trafficstatus command and then sends its data to telegram.
> This script works, but it does not run if I add it to _updown.xfrm For example:
> 
> up-client)

up-client might not always be called. add it to up-host as well?

Also you want the environment variable PLUTO_PEER_ID to get the peer ID.

**Comment by syndicaterus** [comment]
> On Wed, 8 May 2024, syndicaterus wrote: XAUTH values are only set for IKEv1. You want the peer id. Got it, thanks for the answer. I made a script that executes the ipsec trafficstatus command and then sends its data to telegram. This script works, but it does not run if I add it to _updown.xfrm For example: up-client)
> up-client might not always be called. add it to up-host as well? Also you want the environment variable PLUTO_PEER_ID to get the peer ID.

Thank you very much! It works!
 ```
up-client)
        # connection to my client subnet coming up
        addvtiiface
        updateresolvconf
        addcat
        addsource
        notifyNM connect
        addvti
       /usr/local/sbin/UserConnected.py $PLUTO_PEER_ID
        # If you are doing a custom version, firewall commands go here.
        ;;
    down-client)
        # connection to my client subnet going down
        downrule
        delnflog
        delcat
        delvti
        restoreresolvconf
        notifyNM disconnect
        /usr/local/sbin/UserDisconnected.py $PLUTO_PEER_ID
        # If you are doing a custom version, firewall commands go here.
```
