### ISSUE TITLE
Server Password Exposed

### ISSUE THREAD

**Issue by Arch881010** [hwdsl2/setup-ipsec-vpn#1492]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ ] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**
If your server has a password, it is stored inside of the .mobileconfig file that can be easily extracted.

**To Reproduce**

1. Create a password only protected Ubuntu server.
2. Run the script. (wget)
3. Create a new client under IKEv2.
4. Download the mobile config as created by the new client.
5. Open in any text rendering platform.
6. Ctrl + F: "password"
7. The password is found to ssh into the server as stored in plain text.
8. ssh root@ip
9. password
10. Should either work or reject if "public key" isn't required or not.

**Expected behavior**
The expected behaviour should keep the password to the server a secret or encrypted. Meaning this is probably a huge risk to any .mobileconfig files that severs' have password protection enabled.

**Logs**
[Check logs and VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status), and add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- OS: Ubuntu 23.10 x64
- Hosting provider (if applicable): DigitalOcean (New York)

**Client (please complete the following information)**
- Device: Laptop (but config is for mobile)
- OS: Any
- VPN mode: IKev2

**Additional context**
A friend and I were messing with a remote server of mine, which is currently a working vpn, and discovered the password in plain text that actually was *correct* and was able to log into the server via ssh.

**Comment by Arch881010** [comment]
It can be, but the password in this case was directly the same. Even after changing the user, psk, etc.

**Comment by Arch881010** [comment]
I'll retest but thats definetely odd.

**Comment by Arch881010** [comment]
1st Test with config does not show same password nor has the same password as marked. But I could be confusing this with IPSEC instead of IKev2.

**Comment by Arch881010** [comment]
After a quick check, I think it was very randomly (like goodness knows the chance) the perfect generation to my server. 
Test 2 (Autoconfig): Didn't expose password.
I guess this could of, as prior, a perfectly randomly generated password that matched my server's. Have a good day all.

**Comment by hwdsl2** [comment]
@Arch881010 As you've confirmed in your tests, there is nothing to worry about in this issue. The password to protect the `.mobileconfig` file is randomly generated and unrelated to your server login password.

This password is only added if you used the `VPN_PROTECT_CONFIG=yes` option (or if you enabled the option during interactive IKEv2 setup). See [Customize IKEv2 options](https://github.com/hwdsl2/setup-ipsec-vpn#customize-ikev2-options) for more information.
