### ISSUE TITLE
chatgpt 苹果手机端无法登录

### ISSUE THREAD

**Issue by hubleilei** [hwdsl2/setup-ipsec-vpn#1496]
![999](https://github.com/hwdsl2/setup-ipsec-vpn/assets/152010776/9acebdbb-9ef0-421a-b93d-3dc63eb2b4a8)
你好，我遇到一个问题。电脑端网址是可以正常登录的。苹果手机端能连上，连接网址也没问题，但chatgpt app无法登录，我在该服务器使用nginx配置正向代理连接chatgpt app是可以登录的，所以ip地址我想应该是没问题的，我不清楚问题出在哪里，是哪里配置需要更改吗？该如何解决？

**Comment by hwdsl2** [comment]
@hubleilei 你好！根据你提供的错误信息，ChatGPT APP可能因为检测到正在使用 VPN 从而拒绝登录。这个是该 APP 本身添加的限制，不是 VPN 服务器上的问题。你可以考虑换用比如你所说的其他解决方案。
