### ISSUE TITLE
如何使用SSL证书，仅用账号+密码连接？

### ISSUE THREAD

**Issue by JunwayGuo** [hwdsl2/setup-ipsec-vpn#1498]
你好，请问如何实现类似此脚本的配置：
[https://github.com/quericy/one-key-ikev2-vpn#客户端配置说明](https://github.com/quericy/one-key-ikev2-vpn#客户端配置说明)
使用SSL证书，客户端不需要导入任何配置或证书，仅用账号+密码，即可连接。

**Comment by hwdsl2** [comment]
@JunwayGuo 你好！你所说的用例是 IKEv2 模式下通过 EAP（用户名+密码）进行身份认证。目前本项目不支持该连接方式。
