### ISSUE TITLE
ikev2.sh removing prompt 

### ISSUE THREAD

**Issue by ptorrent** [hwdsl2/setup-ipsec-vpn#1499]
Hello !

That would be nice to be able to call:

./ikev2.sh --revokeclient test -y
./ikev2.sh --removeclient test -y

To remove the alert

**Comment by hwdsl2** [comment]
@ptorrent Hello! Thank you for your suggestion, I'll consider it for future improvements of the VPN scripts. In the meantime, feel free to customize your copy of `/opt/src/ikev2.sh` on the VPN server.

**Comment by ptorrent** [comment]
Yes I did it :)

Thanks for your rapidity
