### ISSUE TITLE
Disconnect IKEV2 client manually

### ISSUE THREAD

**Issue by ptorrent** [hwdsl2/setup-ipsec-vpn#1500]
Hello again !

Is there a way to disconnect a client from the ikev2 server ?

**Comment by letoams** [comment]
See “man ipsec whack”It is something like: ipsec whack —deletestate —id <id of client>PaulSent using a virtual keyboard on a phoneOn Dec 2, 2023, at 03:27, ptorrent ***@***.***> wrote:﻿
Hello again !
Is there a way to disconnect a client from the ikev2 server ?

**Comment by hwdsl2** [comment]
@ptorrent Please refer to: #1011, #1106.
