### ISSUE TITLE
关于VPN 服务器网段访问 VPN 客户端网段其他电脑资源

### ISSUE THREAD

**Issue by Yuwenchengdu** [hwdsl2/setup-ipsec-vpn#1501]
对于“**VPN 服务器网段访问 VPN 客户端**”您给的示例的疑惑，
1、“VPN 服务器 IP 是 10.1.0.2，你想要访问 VPN 客户端的设备的 IP 是 10.1.0.3”
为何假定服务器和客户端在一个网段里，这在实际中应该不会成立，或者这是vpn创建时分配的虚拟IP?
2、示例中多次出现的192.168.43.0/24网段代表什么含义？我在本地IPtables列表中有发现
3、iptables -I FORWARD 2 -i "$netif" -o ppp+ -s 10.1.0.3 -j ACCEPT
这条语句，意思是，接受源地址10.1.0.3的数据包，从本地默认网卡进入，从虚拟ppp网卡出
既然来源是客户端，是否要从ppp网卡进入？毕竟本地网卡不能直连客户端
4、iptables -I FORWARD 2 -i "$netif" -d 192.168.43.0/24 -s 10.1.0.3 -j ACCEPT
这条也是，接受客户端到43网段的数据，为什么入口是本地网卡，还是默认所有数据只能从本地网卡接收？

另外想请你扩展下“vpn服务端（网段）访问客户端网段”的配置说明
目前我可以通过服务器ping通客户端本地网卡，但与客户端网段其他IP无法通信，尝试在客户端设置IP转发以及iptables规则都没有成功。麻烦给出您的思考，或者操作方向，谢谢！

**Comment by hwdsl2** [comment]
@Yuwenchengdu 你好！关于你的问题：

1. 文中的 “你想要访问 VPN 客户端的设备” 是指与服务器在同一子网的设备。比如说你有多个专用服务器或 VPS 在同一子网，其中之一是 IPsec VPN 服务器，而你想要从与服务器在同一子网的其他设备访问连接到该服务器的 VPN 客户端。
2. 192.168.43.0/24 是客户端默认子网之一，具体参见高级用法中的 VPN 内网 IP 和流量。
3. 4. 你对规则的理解是对的，但来源是服务器同一子网的其他设备，不是客户端。

对于访问客户端网段中的其他设备（而不是客户端本身），这是一个不同的用例，目前没有说明。你可能需要修改服务器上的路由表（"route add ... via ...")并在 IPTables FORWARD chain 添加允许规则。具体你可以参考之前的Issue自己尝试一下。

**Comment by Yuwenchengdu** [comment]
> @Yuwenchengdu 你好！关于你的问题：
> 
> 1. 文中的 “你想要访问 VPN 客户端的设备” 是指与服务器在同一子网的设备。比如说你有多个专用服务器或 VPS 在同一子网，其中之一是 IPsec VPN 服务器，而你想要从与服务器在同一子网的其他设备访问连接到该服务器的 VPN 客户端。
> 2. 192.168.43.0/24 是客户端默认子网之一，具体参见高级用法中的 VPN 内网 IP 和流量。
> 3. 和4 你对规则的理解是对的，但来源是服务器同一子网的其他设备，不是客户端。
> 
> 对于访问客户端网段中的其他设备（而不是客户端本身），这是一个不同的用例，目前没有说明。你可能需要修改服务器上的路由表（"route add ... via ...")并在 IPTables FORWARD chain 添加允许规则。具体你可以参考之前的Issue自己尝试一下。

感谢回复~
上面确实是我理解错了。

至于访问客户端网段中的其他设备，我参考“访问 VPN 服务器的网段”的提示在客户端上做了以下配置，现在可以从服务器端ping通客户端50网段的IP。但反向ping不通，可能需要在服务器端也配置吧？感觉IPtables的水很深
netif=enp3s0
iptables -I FORWARD 2 -i "$netif" -o ppp+ -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -I FORWARD 2 -i ppp+ -o "$netif" -j ACCEPT
iptables -I FORWARD 2 -i "$netif" -d 192.168.42.0/24 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -I FORWARD 2 -s 192.168.42.0/24 -o "$netif" -j ACCEPT
iptables -t nat -I POSTROUTING -s 192.168.42.0/24 -o "$netif" -m policy --dir out --pol none -j MASQUERADE
iptables -t nat -I POSTROUTING -s 192.168.42.0/24 -o "$netif" -j MASQUERADE

**Comment by hwdsl2** [comment]
@Yuwenchengdu 你的 IPTables 规则中第 3, 4, 5 行应使用 192.168.43.0/24 而不是 192.168.42.0/24。具体参见[访问 VPN 服务器的网段](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#%E8%AE%BF%E9%97%AE-vpn-%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9A%84%E7%BD%91%E6%AE%B5)。此方法我不确定是否可行，对于此用例，你再自己尝试一下。
