### ISSUE TITLE
How can i make ipv4 AND ipv6 working?

### ISSUE THREAD

**Issue by DerKartdomi** [hwdsl2/setup-ipsec-vpn#1502]
**Checklist**

- [x ] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [ ] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [ x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [ x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x ] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x ] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
A clear and concise description of your enhancement request.

I want to configure my VPN with ipv4 and ipv6 so that it supports both of them but i fail with the configuration. Can someone help me?

**Comment by letoams** [comment]
On Thu, 7 Dec 2023, DerKartdomi wrote:

You will need to wait for libreswan 5.0 to combine v4 and v6 into one
IPsec SA. Until then, you would need to define two separate conns, but
that might not be compatible with common clients (eg apple, microsoft)

Paul

**Comment by hwdsl2** [comment]
@DerKartdomi Correct, this is not currently supported in this project. 

It is possible to connect to SSH to the same server while the VPN is active, using the VPN server's public IP. The VPN scripts do not block such connections by default.

You can optionally set up [OpenVPN](https://github.com/hwdsl2/openvpn-install) and/or [WireGuard](https://github.com/hwdsl2/wireguard-install) in addition to the IPsec VPN on the same server.

**Comment by DerKartdomi** [comment]
@hwdsl2 Ports are blocked on a public WiFi. When I have connected to the VPN server I can access all ports except those of the server itself. If I want to establish an SSH connection I get a time out and nothing happens with openvpn. what can I do then?

**Comment by patrickmdx** [comment]
> On Thu, 7 Dec 2023, DerKartdomi wrote: You will need to wait for libreswan 5.0 to combine v4 and v6 into one IPsec SA. Until then, you would need to define two separate conns, but that might not be compatible with common clients (eg apple, microsoft) Paul
> […](#)
> Date: Thu, 7 Dec 2023 11:13:01 From: DerKartdomi ***@***.***> Cc: Subscribed ***@***.***> To: hwdsl2/setup-ipsec-vpn ***@***.***> Subject: [hwdsl2/setup-ipsec-vpn] How can i make ipv4 AND ipv6 working? (Issue #1502) Checklist * [x ] I searched existing Issues, and did not find a similar enhancement request * This enhancement request is about the VPN setup scripts, and not IPsec VPN itself * [ x] I read the README * [ x] I read the Important notes * [x ] I followed instructions to configure VPN clients * [x ] I checked IKEv1 troubleshooting, IKEv2 troubleshooting and VPN status Describe the enhancement request A clear and concise description of your enhancement request. I want to configure my VPN with ipv4 and ipv6 so that it supports both of them but i fail with the configuration. Can someone help me? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.[AAW5L6P36X3HB7QFY7KHGILYIHTI3A5CNFSM6AAAAABALKBFWGWGG33NNVSW45C7OR4XAZNFJFZXG5LFVJRW63LNMVXHIX3JMTHHSD7CIM.gif] Message ID: ***@***.***>

So can I configure my IkEv2 server to only work with IPV6? If so, could you tell me the way?

**Comment by hwdsl2** [comment]
@patrickmdx This use case is not currently supported in this project.
