### ISSUE TITLE
使用安卓系统自带vpn客户端连接下载速度最高只有3MB/S左右，而用strongswan连接则没有这种问题

### ISSUE THREAD

**Issue by yufeiyang2008** [hwdsl2/setup-ipsec-vpn#1504]
使用安卓系统自带vpn客户端连接下载速度最高只有3MB/S左右，而用strongswan连接则没有这种问题，可以达到速度上限。
不知道是不是安卓系统的bug，还是需要优化

**Comment by hwdsl2** [comment]
@yufeiyang2008 你好！使用安卓 strongSwan 客户端连接时，.sswan 配置文件中指定了较优化的 AES-GCM 加密算法。而用安卓系统自带的客户端连接时则不能选择算法。这是可能的原因之一。参见 [Benchmark](https://libreswan.org/wiki/Benchmarking_and_Performance_testing)。
