### ISSUE TITLE
请问IP检测方法

### ISSUE THREAD

**Issue by Sky-hacke** [hwdsl2/setup-ipsec-vpn#1505]
目前正在使用openwrt固件，当网关指向旁路由后vpn server监测到的地址一直都是节点地址并非pppoe拨号的公网地址。
希望询问下ip检测方法和对应域名，我在旁路由上对对应域名进行放行。

**Comment by hwdsl2** [comment]
@Sky-hacke 你好！在安装 VPN 时，你可以使用 VPN_PUBLIC_IP 变量指定 VPN 服务器的公网地址，参见[指定 VPN 服务器的公有 IP](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#%E6%8C%87%E5%AE%9A-vpn-%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9A%84%E5%85%AC%E6%9C%89-ip)。如果已安装 VPN，需要[卸载](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/uninstall-zh.md)后重新安装。IP 检测方法请参见[这些行](https://github.com/hwdsl2/setup-ipsec-vpn/blob/18d51449edf8267944a0ca490d09add71d21085a/vpnsetup_ubuntu.sh#L248-L257)。
