### ISSUE TITLE
Automatic reconnecting not working in mobile networks (working in Wifi networks)

### ISSUE THREAD

**Issue by BenLender** [hwdsl2/setup-ipsec-vpn#1507]
**Checklist**

- [X] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [X] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [X] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [X] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [X] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**
VPN on demand does not work on mobile networks anymore.

**To Reproduce**

1. Setup ikev2 vpn on raspberry pi according to guide: https://github.com/hwdsl2/setup-ipsec-vpn/
2. Setup mobile clients using .mobileconfig files
3. Activate VPN on demand option in iOS GUI

**Expected behavior**
When the VPN connection is lost, the mobile device reconnects no matter the network it is in.
Actual behavior: the mobile device reconntects flawlessly in wifi networks. The mobile device does not connect when not in a wifi network. While in a mobile network, as soon as "vpn on demand" is deactivated manually activing the vpn connecting becomes possible.

**Logs**
[Check logs and VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status), and add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- OS: Debian 10
- Hosting provider: not applicable

**Client (please complete the following information)**
- Device: iPhone SE 2nd gen
- OS: iOS 17.1.2
- VPN mode: IKEv2

**Additional context**
not applicable

**Comment by hwdsl2** [comment]
@BenLender Hello! The default VPN On Demand configuration in this project disconnects the VPN while on mobile networks, so this is normal. In the most common use case, people expect the VPN to connect on Wi-Fi networks but not mobile networks.

To change this behavior for your use case:

1. Edit `/opt/src/ikev2.sh` on your VPN server. Find [this section](https://github.com/hwdsl2/setup-ipsec-vpn/blob/18d51449edf8267944a0ca490d09add71d21085a/extras/ikev2setup.sh#L957-L962):
   ```
          <dict>
            <key>InterfaceTypeMatch</key>
            <string>Cellular</string>
            <key>Action</key>
            <string>Disconnect</string>
          </dict>
   ```
   and replace "Disconnect" with "Connect", i.e.
   ```
          <dict>
            <key>InterfaceTypeMatch</key>
            <string>Cellular</string>
            <key>Action</key>
            <string>Connect</string>
          </dict>
   ```
2. Save the file, then run `sudo ikev2.sh` to export updated client configuration files for your iPhone.
3. Remove the previously imported `.mobileconfig` file from your iPhone, then import the new `.mobileconfig` file from step 2.

**Comment by BenLender** [comment]
@hwdsl2 Thank you very much!
