### ISSUE TITLE
linux部署了IKEv2客户端，开启VPN需要密码，VPN服务器是用一键部署安装的。

### ISSUE THREAD

**Issue by hourui5188** [hwdsl2/setup-ipsec-vpn#1508]
**任务列表**

![download](https://github.com/hwdsl2/setup-ipsec-vpn/assets/154574201/59ea91ff-dbf3-454b-855e-344acf6d5ffd)

- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [x] 我检查了 [IKEv1 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#ikev1-故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#ikev2-故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ ] 这个 bug 是关于 VPN 安装脚本，而不是 IPsec VPN 本身

**问题描述**
使用清楚简明的语言描述这个 bug。

**重现步骤**
重现该 bug 的步骤：

1. ...
2. ...

**期待的正确结果**
简要地描述你期望的正确结果。

**日志**
[检查日志及 VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)，并添加错误日志以帮助解释该问题（如果适用）。

**服务器信息（请填写以下信息）**
- 操作系统: [比如 Debian 11]
- 服务提供商（如果适用）: [比如 GCP, AWS]

**客户端信息（请填写以下信息）**
- 设备: [比如 iPhone 12]
- 操作系统: [比如 iOS 15]
- VPN 模式: [IPsec/L2TP, IPsec/XAuth ("Cisco IPsec") 或 IKEv2]

**其它信息**
添加关于该 bug 的其它信息。

**Comment by hwdsl2** [comment]
@hourui5188 你好！请参见 [Linux IKEv2 客户端配置步骤](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#linux)。在按照链接中的步骤配置客户端后，私钥文件没有密码。如果连接时出现你所说的密码提示，可能是私钥文件已损坏，可以重新按照步骤尝试一下。
