### ISSUE TITLE
HowTo for Opnsense (Client)

### ISSUE THREAD

**Issue by spike1986** [hwdsl2/setup-ipsec-vpn#1509]
Hello, i search a HowTo for connected opnsense Client to Ipsec Server. Server is install with your script.

**Comment by hwdsl2** [comment]
@spike1986 Hello! This VPN client is not currently supported in this project. You may want to look into alternative solutions.

**Comment by spike1986** [comment]
Hello @hwdsl2,
Many thanks for your quick response. I tried your wireguard script. Connection works unfortunately the download is at max. 5 Mbit/s and the upload at 238 Mbit/s.
I spent several weeks researching on the Internet and couldn't find a solution. I am currently trying OpenVPN.

**Comment by hwdsl2** [comment]
@spike1986 The bandwidth is limited by the lower of your server's up and down link bandwidth, there is also encryption overhead. Not sure about your particular case but one thing to try is using a different server location or different provider.

**Comment by spike1986** [comment]
@hwdsl2 I have rented a VPS with 1 Gig Down/UP. This is also measurable. But as soon as the VPN is on. I have the low values.
