### ISSUE TITLE
多个server的ikev2证书冲突

### ISSUE THREAD

**Issue by landall** [hwdsl2/setup-ipsec-vpn#1510]
**任务列表**

- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [x] 我检查了 [IKEv1 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#ikev1-故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#ikev2-故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] 这个 bug 是关于 VPN 安装脚本，而不是 IPsec VPN 本身

**问题描述**
多个不同server导出的ikev2证书，导入同一个Win10后，会出现只有一个生效的问题。
我目前观察到的是，导入本机的证书，会优先于导入本用户的证书，然后导入本机的证书，最后一个生效。
不知道是否跟他们的证书名字都一样有关系。

另外为什么在证书里查看不到跟Server Name和Client Name有关的域？

**日志**
[检查日志及 VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)，并添加错误日志以帮助解释该问题（如果适用）。

**服务器信息（请填写以下信息）**
- 操作系统: [比如 Debian 11]   AlmaLinux 8
- 服务提供商（如果适用）: [比如 GCP, AWS]   Racknerd、Vmiss、Desivps、AWS

**客户端信息（请填写以下信息）**
- 设备: [比如 iPhone 12]
- 操作系统: [比如 iOS 15]    Win10
- VPN 模式: [IPsec/L2TP, IPsec/XAuth ("Cisco IPsec") 或 IKEv2]     IKEv2

**其它信息**
添加关于该 bug 的其它信息。

**Comment by hwdsl2** [comment]
@landall 你好！关于你的问题：
1. 在导入证书时，必须选择计算机帐户（或本地计算机），不要选择我的用户帐户（或当前用户）。后者会导致 VPN 证书不工作。在开始菜单搜索 certlm.msc 可直接打开计算机帐户的证书管理。
2. 对于客户端名称的问题，你可以运行 `sudo ikev2.sh` 添加新的客户端并指定一个不同的名称。然后移除已有的证书并导入新证书。请参阅[管理 IKEv2 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#%E7%AE%A1%E7%90%86-ikev2-%E5%AE%A2%E6%88%B7%E7%AB%AF)。
3. 上述证书管理界面中的”颁发给“ 栏即显示客户端的名称（比如默认的 vpnclient）。 客户端证书一般不包含服务器地址。

**Comment by landall** [comment]
我这里看不到 颁发给 那一栏。

我确认一下，在证书管理器里看到的证书的位置是：\本地计算机\受信任的根证书颁发机构\证书
这个没问题吧？
我用不同的客户端名字，并不能起到区别证书的作用。依然是错误的在生效。

**Comment by hwdsl2** [comment]
@landall 客户端证书应放在“个人\证书“中。IKEv2 VPN CA 证书应放在 “受信任的根证书颁发机构\证书” 中。

**Comment by landall** [comment]
搞定。可以关闭issue了。
