### ISSUE TITLE
ikev2.sh could not find certificate named "IKEv2 VPN CA"

### ISSUE THREAD

**Issue by ptorrent** [hwdsl2/setup-ipsec-vpn#1513]
Hello there !

I'm usine ikev2 script for creating certificates for clients. It was working fine, but since 2 days I got this error without any reason :

```
Use one word only, no special characters except '-' and '_'.
Client name: test

Specify the validity period (in months) for this client certificate.
Enter an integer between 1 and 120: [120] 120

## Generating client certificates...

Generating key.  This may take a few moments...

certutil: could not find certificate named "IKEv2 VPN CA": error 0: Success
certutil: unable to create cert (Success)
## Creating client configuration...pk12util: find user certs from nickname failed: SEC_ERROR_UNKNOWN_CERT: The requested certificate could not be found
```

Am I doing something wrong ?

**Comment by ptorrent** [comment]
PS: I already tried to execute vpn.sh at last version. Still same issue

**Comment by hwdsl2** [comment]
@ptorrent Hello! The "IKEv2 VPN CA" certificate may be corrupted or missing on your VPN server, which triggers this issue. I am not sure about the exact reason this happened. [Recent tests](https://github.com/hwdsl2/setup-ipsec-vpn/actions/runs/7367891670) have passed so it may be an issue specific to your server.

To check the "IKEv2 VPN CA" certificate, run:
```
sudo certutil -L -d sql:/etc/ipsec.d -n "IKEv2 VPN CA"
```

To fix this issue, you may need to [uninstall the VPN](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/uninstall.md) (which permanently deletes all VPN configuration), then [install it again](https://github.com/hwdsl2/setup-ipsec-vpn#installation).

**Comment by ptorrent** [comment]
Hello, thanks for your support. It's working after ikev reinstallation.

What I've to backup for prevent this behavior ?

**Comment by hwdsl2** [comment]
@ptorrent Please refer to #1462.
