### ISSUE TITLE
OpenVZ VPS is not supported.

### ISSUE THREAD

**Issue by alimajnoon1377** [hwdsl2/setup-ipsec-vpn#1514]
Hi 
When I want to install it I saw this:
Error: OpenVZ VPS is not supported.

**Comment by hwdsl2** [comment]
@alimajnoon1377 Hello! OpenVZ VPS is not supported in this project, as kernel support for IPsec may be unavailable. Please instead use e.g. a KVM-based VPS. Example providers include DigitalOcean, Vultr, Linode and OVH.

**Comment by alimajnoon1377** [comment]
Hi Lin
thanks for response
I am Iranian. In our country, all people should use VPN to achieve free
internet. can you help us to do it?
 We need a protocol to be able to connect to VPN at high speed. But the
government quickly filters our servers. The basic solution is to use
the Cloudflare cloud, but it is not efficient. Can you guide us to use
ipsec and similar methods behind cloudflare cloud?

**Comment by hwdsl2** [comment]
@alimajnoon1377 For this use case I would suggest that you look into alternative solutions other than IPsec VPN, for example, Shadowsocks or similar, or other solutions suitable for your use case. Unfortunately, I am not familiar with those so you'll need to explore yourself.
