### ISSUE TITLE
Не подключается при переносе на новый сервер

### ISSUE THREAD

**Issue by aleksan149** [hwdsl2/setup-ipsec-vpn#1516]
Я переехал на новый сервер. Перенес полностью всю папку ipsec.d  для своего ikev2 на новый сервер, вместо ip используется dns. Не подключается. Записи A DNS в полном порядке

**Comment by hwdsl2** [comment]
@aleksan149 Hello! For your use case, please make sure that you first [install the IPsec VPN](https://github.com/hwdsl2/setup-ipsec-vpn#installation) on the new server with same configuration (IKEv2 DNS name, etc.) as the old server, and after that, transfer the entire `/etc/ipsec.d` folder from the old server to the new server. For more information, refer to #1273 and #1462.
