### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by ibrahem2345** [hwdsl2/setup-ipsec-vpn#1519]
i have opened the ports and still nothing is working .
and i have upgraded Liberswan and all the packages before the installation 😞 .
do you think that the problem is caused from the Provider ?
if it's so can you recommend some providers for me ?
and thanks a lot ❤️
and i have tried on another VPS provider but still not working and i get the IPsec / IKEv2 information from the terminal after the installation .
And I am sure that everything on the installation process is correct, so can you tell me where is the problem from?

**Comment by hwdsl2** [comment]
@ibrahem2345 Hello! If you are connecting from e.g. Russia or mainland China, IPsec VPNs are relatively easy to block compared to alternative solutions such as Shadowsocks.

If your connection is not working with multiple providers, and your use case fits the above, it is likely that the connection was blocked. In this case, as discussed in #1518, I would suggest looking into alternative solutions other than IPsec VPN.
