### ISSUE TITLE
Doesn't work with .mobileconfig macos ios

### ISSUE THREAD

**Issue by kkamenij** [hwdsl2/setup-ipsec-vpn#1520]
Greetings! 
I met the following problem. The VPN has stopped working on the iPhone if the connection attempt is based on a mobile network. If you use wifi, everything works as it should. It doesn't work at all on macos. I tried different devices, different operators, the problem is the same

**Comment by hwdsl2** [comment]
@kkamenij Hello! If you are using VPN On Demand, refer to [this section](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ios) and expand the "Customize VPN On Demand rules: Connect on Wi-Fi and cellular networks" sub-section to learn how to enable mobile networks for VPN On Demand.

On the other hand, if you are not using VPN On Demand, it is likely that your Internet Service Provider is blocking IPsec VPN connections. In this case, you may want to look into alternative solutions other than IPsec VPN, such as Shadowsocks. The VPN was tested with both macOS and iOS clients and the connections worked fine in the tests.

You may troubleshoot further by retrying the connection, then [check logs and VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status) for errors. "Retransmission" related errors usually indicate that the connection was blocked or the network is unstable.
