### ISSUE TITLE
多用户使用的问题。

### ISSUE THREAD

**Issue by a52948** [hwdsl2/setup-ipsec-vpn#1521]
**描述改进建议**
IKEv2在使用时，好像只能连一个终端，通过IKEv2证书多个终端好像没办法共同使用。

**Comment by hwdsl2** [comment]
@a52948 你好！对于此用例，你需要为每个 IKEv2 终端生成唯一的证书。请参见[管理 IKEv2 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#%E7%AE%A1%E7%90%86-ikev2-%E5%AE%A2%E6%88%B7%E7%AB%AF)。
