### ISSUE TITLE
I want to get the remote subnet

### ISSUE THREAD

**Issue by ibrahem2345** [hwdsl2/setup-ipsec-vpn#1522]
### Hello There
i have installed everything correctly but when i want to put the information on my router it asks me for the remote subnet , 
any idea how to get it ? 
i want to connect through L2TP 
❤️

**Comment by hwdsl2** [comment]
@ibrahem2345 Hello! You can try `0.0.0.0/0` for the remote subnet. If that doesn't work, your router may not support connecting to an IPsec/L2TP VPN server.
