### ISSUE TITLE
 [Question] Is it possible to assign static IPs to clients?

### ISSUE THREAD

**Issue by chiragrajk** [hwdsl2/setup-ipsec-vpn#1525]
When adding new client with IKEv2 only mode, how can I assign static IP to each client?

**Comment by letoams** [comment]
On Tue, 6 Feb 2024, Chirag Rajkarnikar wrote:

> When adding new client with IKEv2 only mode, how can I assign static IP to each client?

Not yet possible. See https://github.com/libreswan/libreswan/issues/473

**Comment by chiragrajk** [comment]
@letoams Thanks
Also there's already a related issue https://github.com/hwdsl2/setup-ipsec-vpn/issues/1003
