### ISSUE TITLE
tunnel between

### ISSUE THREAD

**Issue by kalilovers** [hwdsl2/setup-ipsec-vpn#1528]
greetings . Can we use this script to establish a tunnel between two Linux servers in IPsec?
Suppose we have an x-ui panel located on the second server. And users' requests are sent to the first server and transferred to the second server through this secure tunnel.
we need it for vpn limition in iran for a secure tunnel

**Comment by hwdsl2** [comment]
@kalilovers Hello! This use case is not supported in this project, please look into alternative solutions. GRE tunnels may be close to your use case, however it can be blocked by your ISP.

**Comment by kalilovers** [comment]
> @kalilovers Hello! This use case is not supported in this project, please look into alternative solutions. GRE tunnels may be close to your use case, however it can be blocked by your ISP.

Thanks a lot . But gre and the likes are in trouble now
