### ISSUE TITLE
我只想通过VPN访问服务器的内网,不想通过VPN访问服务器的外网,应该怎么弄呢?

### ISSUE THREAD

**Issue by acracker** [hwdsl2/setup-ipsec-vpn#1531]
我只想通过VPN访问服务器的内网,不想通过VPN访问服务器的外网,应该怎么弄呢?
有自动设置的脚本吗? 
我大概知道手工怎么操作, 但是发布出去给同事使用,就很麻烦.  没有搜到怎么使用powershell来配置
大概步骤为
1. 禁用IPV4上的 路由添加
2. 添加一个内网的默认路由

**Comment by hwdsl2** [comment]
@acracker 你好！请参见 [VPN 分流](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#vpn-%E5%88%86%E6%B5%81)。目前这些步骤需要手动操作。
