### ISSUE TITLE
希望能在wiki中加入IPsec-VPN迁移的相关内容

### ISSUE THREAD

**Issue by lisiimage** [hwdsl2/setup-ipsec-vpn#1533]
**任务列表**

- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)，没有找到类似的改进建议
- [x] 这个改进建议是关于 VPN 安装脚本，而不是 IPsec VPN 本身
- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [x] 我检查了 [IKEv1 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#ikev1-故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#ikev2-故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)

**描述改进建议**
希望能在wiki中加入IPsec-VPN迁移的相关内容。比如说更换了硬件和OS，如何沿用之旧系统的配置信息，把IPsec-VPN迁移到新的服务器，使客户端无感「避免重复在客户端重复安装和配置IPsec-VPN」。

**你的改进建议与遇到的问题有关吗？请描述。**
（如果适用）清楚，简洁地说明问题所在。

**其它信息**
添加关于该改进建议的其它信息。

**Comment by hwdsl2** [comment]
@lisiimage 你好！感谢你的建议。目前在[域名和更改服务器 IP](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#%E5%9F%9F%E5%90%8D%E5%92%8C%E6%9B%B4%E6%94%B9%E6%9C%8D%E5%8A%A1%E5%99%A8-ip)小节中有一些相关信息，例如在恢复一个映像到具有不同 IP 的新服务器后如何更改 IKEv2 地址。另外请参见 #1529 和 #1462。我有空再将相关文档完善一下。
