### ISSUE TITLE
Question - how to config client for not "tunnel-all" with ikev2?

### ISSUE THREAD

**Issue by 0x-2a** [hwdsl2/setup-ipsec-vpn#1534]
What's a good strategy to achieve the following config for an `ikev2 vpn`?

Let's say we have a Server Network that looks like this:
- VPN Server: LAN IP 10.0.0.11
- Server A: LAN IP 10.0.0.22

From the client, I only want traffic to the 10.0.0.xxx subnet routed through the VPN (no external internet traffic).
- Client: LAN IP 192.168.1.123 from client router's DHCP
- Client traffic to 10.0.0.22 -> routes to Server A above
- Traffic for 10.0.0.xxx -> routes through VPN to the subnet where the VPN server is running
- All other client traffic -> normal routing through client's router

Is this controlled entirely by the client config? I've gotten it to work with L2TP but not `IKEV2`.

**Comment by hwdsl2** [comment]
@0x-2a Hello! For your use case, please refer to [split tunneling](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#split-tunneling) in the advanced usage section of project documentation.
