### ISSUE TITLE
关于buildroot 下 4g 链接问题

### ISSUE THREAD

**Issue by dd-ping** [hwdsl2/setup-ipsec-vpn#1535]
**任务列表**

- [ *] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [ *] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [ *] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [ *] 我检查了 [IKEv1 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#ikev1-故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#ikev2-故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [ *] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ ] 这个 bug 是关于 VPN 安装脚本，而不是 IPsec VPN 本身

**问题描述**
使用清楚简明的语言描述这个 bug。

我使用的是  使用命令行配置 Linux VPN 客户端 的拨号方式  https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E4%BD%BF%E7%94%A8%E5%91%BD%E4%BB%A4%E8%A1%8C%E9%85%8D%E7%BD%AE-linux-vpn-%E5%AE%A2%E6%88%B7%E7%AB%AF

destroying IKE SA in state CONNECTING wi thout notif ication
IKE_ SA [1] closed successfully
interface ppp0
Stopping strongSwan IPsec.
Starting strongSwan 5. 6.3 IPsec Lstarterj...
modprobe: can t open modules. dep' : No such file or directory
modprobe: can t open' modules. dep' : No such file or directory
modprobe: can t open' modules. dep' : No such file or directory
modprobe: can t open modules. dep
No such file or directory
modprobe: can’t open’ modules. dep' : No such file or directory
initiating Main Mode IKE_ SA myvpn[1] to x. x. x. x
generating ID_ PROT request 0 [ SA VVV V V
sending packet: from 172. 17. 253. 35[500] to x. x. x. x[500]_ (216 bytes)
received packet: from x. x. x. x[500] to 172. 17. 253. 35[500] (144 bytes)
parsed ID_ _PROT response 0 [ SAVV V ]
received FRAGMENTATION vendor ID
received DPD vendor II
received NAT-T (RFC 3947) vendor ID
generating ID_ PROT request 0 [ KE No NAT-D NAT-D ]
sending packet: from 172. 17. 253. 35[500] to x. x. x. x[500]_ (372 bytes)
received packet: from x. x. x. x[500] to 172. 17. 253.35[500] (372 bytes)
parsed ID_ PROT response 0 [ KE No NAT-D NAT-D ]
local host is behind NAT, sending keep alives
remote host is behind NAT
generating ID_ PROT request 0 [ ID HASH N (INITIAL_ _CONTACT) ]
sending packet: from 172. 17.253. 35[4500] to x. x. x.x[4500] (108 bytes)
sending retransmit 1 of request message_ ID 0，seq 3
sending packet: from 172. 17.253. 35[4500] to x. x.x. x[4500] (108 bytes)

**重现步骤**
重现该 bug 的步骤：

当意外断开链接之后再次进行链接的时候 无法再次链接上，即使是重启服务器 的 ipsec 跟 xl2tpd 也无法连接

**期待的正确结果**
简要地描述你期望的正确结果。

**日志**
[检查日志及 VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)，并添加错误日志以帮助解释该问题（如果适用）。

**服务器信息（请填写以下信息）**
- 操作系统: [比如 Debian 11]
- 服务提供商（如果适用）: [比如 GCP, AWS]

**客户端信息（请填写以下信息）**
- 设备: [比如 iPhone 12]
- 操作系统: [比如 iOS 15]
- VPN 模式: [IPsec/L2TP, IPsec/XAuth ("Cisco IPsec") 或 IKEv2]

**其它信息**
添加关于该 bug 的其它信息。

**Comment by hwdsl2** [comment]
@dd-ping 你好！请尝试重启客户端上的 strongswan 和 xl2tpd 服务，参见[文档](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E4%BD%BF%E7%94%A8%E5%91%BD%E4%BB%A4%E8%A1%8C%E9%85%8D%E7%BD%AE-linux-vpn-%E5%AE%A2%E6%88%B7%E7%AB%AF)中的 " 当你每次尝试连接到 VPN 时，必须重复下面的所有步骤" 部分。

另外，你也可以使用 IKEv2 模式从命令行连接。请参见[这里](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#linux)。

如果无法解决，你可以到 [Libreswan 项目](https://github.com/libreswan/libreswan)提交一个 Issue。
