### ISSUE TITLE
ios17系统版本下 使用ikev2协议进行连接有误

### ISSUE THREAD

**Issue by bl4ckn1ght** [hwdsl2/setup-ipsec-vpn#1536]
**任务列表**

- [ √] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)，没有找到类似的改进建议
- [ √] 这个改进建议是关于 VPN 安装脚本，而不是 IPsec VPN 本身
- [ √] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [ √] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [ √] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [ ] 我检查了 [IKEv1 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#ikev1-故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#ikev2-故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)

**描述改进建议**
客户端系统版本：ios17.3.1
服务端系统版本：Ubuntu22.04
问题描述：能成功使用ikev2协议证书进行vpn连接，通过ip查询还是本机地址，流量并没有通过服务器端

**你的改进建议与遇到的问题有关吗？请描述。**
需要调整ikev2证书相关配置

**Comment by hwdsl2** [comment]
@bl4ckn1ght 你好！本项目使用 iOS 17 客户端测试过，连接 IKEv2 之后流量正常经过服务器端。建议你重启手机或服务器，然后重新连接试一下。或者尝试换一个网站或者浏览器检测 IP。
