### ISSUE TITLE
Unable to Connect to Ikev2 protocol 

### ISSUE THREAD

**Issue by saadabbasi9d** [hwdsl2/setup-ipsec-vpn#1541]
I am Unable to Connect to Ikev2 protocol using username and password mentioned in /etc/ppp/chapsecrets despite restarting the service . IPSEC/L2tp is working fine but IPSEC/ikev2 with username and pasword is not working but with generated file it is working.

**Comment by hwdsl2** [comment]
@saadabbasi9d Hello! For IKEv2 mode, only certificate-based authentication is supported, not username/password. Please refer to the [IKEv2 guide](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md) for how to configure and manage IKEv2 clients.
