### ISSUE TITLE
Can I generate files while adding a new user for ikev2 with encryption algorithm ed448 or ed25519?

### ISSUE THREAD

**Issue by algoritmsystems** [hwdsl2/setup-ipsec-vpn#1544]
Can I generate files while adding a new user for ikev2 with encryption algorithm ed448 or ed25519?
Which algorithm types are supported and how to configure it?

**Comment by hwdsl2** [comment]
@algoritmsystems Hello! This is not currently supported. Currently, the IKEv2 script generates certificates with RSA signatures and 3072-bit keys by default. See [ikev2setup.sh](https://raw.githubusercontent.com/hwdsl2/setup-ipsec-vpn/master/extras/ikev2setup.sh) or `/opt/src/ikev2.sh` on your server. You may be able to customize the [certutil](https://www.linux.org/docs/man1/certutil.html) commands to use `curve25519`, but there may be some [bugs](https://bugzilla.redhat.com/show_bug.cgi?id=1760722) that prevent it from working.
