### ISSUE TITLE
Can I use nftables instead of iptables

### ISSUE THREAD

**Issue by algoritmsystems** [hwdsl2/setup-ipsec-vpn#1545]
When I run: #sh vpn.sh
Getting this error:
wget -t 3 -T 30 -q -O /tmp/vpn.fKYft/vpn.sh https://raw.githubusercontent.com/hwdsl2/setup-ipsec-vpn/master/vpnsetup_ubuntu.sh
VPN credentials not set by user. Generating random PSK and password...
Error: IPTables check failed. Reboot and re-run this script.

How to run script with installed nftables instead of iptables?
Thanks!

**Comment by hwdsl2** [comment]
@algoritmsystems Hello! If you encounter this error, try rebooting your server and re-run the script after that. If that doesn't help, it may not be currently supported, you can instead try e.g. OpenVPN or WireGuard.
