### ISSUE TITLE
目前手机是华为鸿蒙4.0系统，可以使用华为手机自带vpn连接不，不使用第三方vpn

### ISSUE THREAD

**Issue by maojianyou** [hwdsl2/setup-ipsec-vpn#1546]
**任务列表**

- [ ] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)，没有找到类似的改进建议
- [ ] 这个改进建议是关于 VPN 安装脚本，而不是 IPsec VPN 本身
- [ ] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [ ] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [ ] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [ ] 我检查了 [IKEv1 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#ikev1-故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#ikev2-故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)

**描述改进建议**
使用清楚简明的语言描述你的改进建议。
目前我的手机是华为鸿蒙系统4.0.0，目前不想使用第三方客户端app作为vpn连接，我看华为自带vpn支持
ikev2/ipsec MSCHAPv2  
ikev2/ipsec PSK
ikev2/ipsec RSA  

需要填写服务器地址
ipsec标识符
等相关信息
但这3种方式，还要输入用户名称跟密码，但我看这种VPN不支持输入用户名跟密码同时验证，是否能实现华为鸿蒙系统也支持手机自带vpn连接

**你的改进建议与遇到的问题有关吗？请描述。**
希望支持华为鸿蒙系统4.0的版本，不用使用第三方vpn客户端，直接能连接

**其它信息**
添加关于该改进建议的其它信息。

**Comment by hwdsl2** [comment]
@maojianyou 你好！感谢你的建议。目前本项目对于 IKEv2 模式不支持使用用户名和密码连接，仅支持使用证书。因为目前的 Libreswan 版本不支持该功能。IKEv2/IPSec RSA 模式一般不需要输入用户名和密码，请参考[安卓系统 IKEv2 配置步骤](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#android)。

**Comment by jianghuaangte** [comment]
https://github.com/palw3ey/ye3ipsec
可以用这个，支持客户端和服务端的 IKEv2 ，你说的这几个模式都支持
