### ISSUE TITLE
Error: Connection activation failed: The 'strongswan' plugin only supports a single active connection.

### ISSUE THREAD

**Issue by wangyx89007** [hwdsl2/setup-ipsec-vpn#1549]
使用nmcli创建了两个ikev2类型的VPN，开启第二个VPN时，出现"Error: Connection activation failed: The 'strongswan' plugin only supports a single active connection."，请问该如何解决

**Comment by wangyx89007** [comment]
Linux版本为CentOS7.9

**Comment by hwdsl2** [comment]
@wangyx89007 你好！对于你的用例，该错误是因为你的 VPN 客户端上 NetworkManager 的 strongswan 插件的局限性导致的。参见[这个 Issue](https://github.com/strongswan/strongswan/issues/1493)。你可以另外尝试其他的解决方案。
