### ISSUE TITLE
Android (possibly routing) issue

### ISSUE THREAD

**Issue by DL6ER** [hwdsl2/setup-ipsec-vpn#155]
On Android (using the `Fing` app), I can connect fine to my new IPSec VPN server, but I do see 100% package loss to `8.8.8.8` and `192.168.2.1` (my Internet gateway).
Nevertheless, pinging `192.168.2.10` (the Raspberry IPSec VPN server is running on) is working fine.

IPv4 forwarding is enabled on the server
```
cat /proc/sys/net/ipv4/ip_forward
1
```

There is an OpenVPN server installed on the very same machine that is in use for quite some time. Here, it works fine (connected clients can access the internal network as well as the Internet), but my goal is to replace OpenVPN by IPSec.

**Comment by hwdsl2** [comment]
@DL6ER Hello! Please reboot both the Raspberry Pi 3 and your Android phone, then re-connect the VPN and try the Fing app again.

Also check your IPTables rules on the RPi server. Post the output of:

```
sudo iptables -nvL; sudo iptables -nvL -t nat
```

**Comment by DL6ER** [comment]
Rebooted both devices, re-connected the VPN (successful) and still seeing the same issue.

`iptables` is unconfigured (the Raspberry is hidden behind a router with firewall and NAT), so the phone should have unlimited access to the server and the server to the Internet.

```
sudo iptables -nvL;
Chain INPUT (policy ACCEPT 995 packets, 105K bytes)
 pkts bytes target     prot opt in     out     source               destination         
   96  9649 fail2ban-ssh  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 22

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
   13   864 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT 929 packets, 128K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain fail2ban-ssh (1 references)
 pkts bytes target     prot opt in     out     source               destination         
   96  9649 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0
```

```
sudo iptables -nvL -t nat
Chain PREROUTING (policy ACCEPT 59 packets, 4534 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 38 packets, 3150 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 40 packets, 2695 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 40 packets, 2695 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 SNAT       all  --  *      *       10.8.0.0/24          0.0.0.0/0            to:192.168.2.10
    0     0 SNAT       all  --  *      *       10.8.0.0/24          0.0.0.0/0            to:192.168.2.10
```

**Comment by hwdsl2** [comment]
@DL6ER Some IPTables rules are required for the IPsec VPN to have access to the Internet. That should have been taken care of by the VPN setup script. Not sure why your IPTables rules are missing.

Before suggesting which IPTables rules to add, I need to know your RPi's default network interface. Is it `wlan0` (wireless) or `eth0` (wired)?

**Comment by DL6ER** [comment]
Now that you mention it, I remember having seen some IPTables complaints during the installation and thought that they might have been irrelevant as my device is anyhow shielded from the public Internet. Apparently I have been wrong.

I installed the rules as scripted in [vpnsetup.sh#L378](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/vpnsetup.sh#L378) and it is working now. Thanks for your fast help!
