### ISSUE TITLE
in ikev2setup.sh shouldn't this use openssl sha2

### ISSUE THREAD

**Issue by aflashback** [hwdsl2/setup-ipsec-vpn#1552]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**
in ikev2setup.sh file export_p12_file method I see all openssh commands are using sha1 shouldn't this be sha2 , is there a reason ?

example: 
openssl pkcs12 -keypbe PBE-SHA1-3DES -certpbe PBE-SHA1-3DES

Thanks!

**Comment by letoams** [comment]
> Describe the issue
> in ikev2setup.sh file export_p12_file method I see all openssh commands are using sha1 shouldn't this be sha2 , is there a reason ?
> 
> example:
> openssl pkcs12 -keypbe PBE-SHA1-3DES -certpbe PBE-SHA1-3DES
> 

Sadly, Apple doesn’t support all pkcs12 wrappings. It doesn’t do aes, only 3des. Not sure if it supports sha2

Paul

**Comment by hwdsl2** [comment]
@aflashback Hello! Yes, this is mainly for compatibility with VPN client devices, such as iPhones and iPads. For a personal VPN, using 3DES and SHA1 for IKEv2 certificates should be fine from a security perspective.
