### ISSUE TITLE
Renew revoked or expired certificate

### ISSUE THREAD

**Issue by Yuckly** [hwdsl2/setup-ipsec-vpn#1554]
**Describe the enhancement request**
Is there a way to renew the certificate after it expires or is revoked? I was searching for answer but could not find a complete description.

**Is your enhancement request related to a problem? Please describe.**
There is no way to renew revoked or expired certicate with ikev2.sh

**Additional context**
I think adding this function to ikev2.sh will be really helpful.

**Comment by hwdsl2** [comment]
@Yuckly Hello! Thank you for your suggestion. Renewing an expired IKEv2 client certificate is not currently supported. You can instead run "sudo ikev2.sh" to delete the IKEv2 client certificate and add a new client with the same name. After that, import the new client config file into your IKEv2 client device.

For the other use case you mentioned, you can create a new client with a different name without deleting the client certificate you revoked, then import it into your IKEv2 client device.
