### ISSUE TITLE
apt-get Install Failed

### ISSUE THREAD

**Issue by martinmarshall** [hwdsl2/setup-ipsec-vpn#1556]
## Installing packages required for the VPN...
+ apt-get -yqq install libnss3-dev libnspr4-dev pkg-config libpam0g-dev libcap-ng-dev libcap-ng-utils libselinux1-dev libcurl4-nss-dev flex bison gcc make libnss3-tools libevent-dev libsystemd-dev uuid-runtime ppp xl2tpd
**E: Package 'libcurl4-nss-dev' has no installation candidate**
Error: 'apt-get install' failed.

**Comment by hwdsl2** [comment]
@martinmarshall Hello! Please use a [supported LInux distribution](https://github.com/hwdsl2/setup-ipsec-vpn#requirements). Ubuntu 24.04 is not supported yet.

**Comment by hwdsl2** [comment]
Updated for Ubuntu 24.04 in b58e65e.
