### ISSUE TITLE
It doesn't seem to work with GCP

### ISSUE THREAD

**Issue by olegkorol** [hwdsl2/setup-ipsec-vpn#1559]
Hi!

First of all, thanks for putting this together.

I am trying to connect an on-premises server to GCP with a tunnel using IPSec IKEv2.
I've attempted setting up the VPN server on both DigitalOcean and EC2, with the same (unsatisfactory) results.

It is **possible to connect clients like e.g. my laptop**, which means that the VPN is working... but I cannot get it to work with GCP.

For a bit of context, on the GCP side I am using a Cloud VPN Gateway which then has a Cloud VPN Tunnel. The latter's configuration looks like this:

<img width="540" alt="Screenshot 2024-05-17 at 2 09 22 PM" src="https://github.com/hwdsl2/setup-ipsec-vpn/assets/13587499/74dadbc4-1ec1-4f32-b212-6d522a4661f1">

...based on the actual IP Range from the VM's subnet and the output of the `vpn.sh` script:

```text
IPsec VPN server is now ready for use!

Connect to your new VPN with these details:

Server IP: 178.x.x.x # Remote peer IP address above
IPsec PSK: <PSK_FROM_VPN_SERVER> # IKE pre-shared key above
Username: <USERNAME>
Password: <PASSWORD>

Write these down. You'll need them to connect!
```

----

Then **the two servers keep "handshaking" forever but the connection does not succeed**.

These are some the logs I see in the Cloud VPN Gateway:

<img width="946" alt="Screenshot 2024-05-17 at 2 15 52 PM" src="https://github.com/hwdsl2/setup-ipsec-vpn/assets/13587499/a54c2181-6e41-4ee5-9dc3-8b21adc0f9c2">
<img width="946" alt="Screenshot 2024-05-17 at 2 16 19 PM" src="https://github.com/hwdsl2/setup-ipsec-vpn/assets/13587499/8613c460-b747-4799-88c8-a7e2bfdd900b">

Any ideas? Am I missing something?
Many thanks in advance!

_PS: I was able to set up such a connection using two different GCP projects, with their own VPCs and subnets, by running Cloud VPN Tunnels the exact same way I described above. So I imagine that the issue would not be the GCP Cloud VPN Tunnel's configuration, but rather the IPSec's configuration._

**Comment by hwdsl2** [comment]
@olegkorol Hello! Thank you for providing the details of your use case. Unfortunately, this is not currently supported in this project. The Cloud VPN Gateway in GCP uses IKEv2 with pre-shared keys, while this project requires certificate-based authentication for IKEv2, or pre-shared keys with username/password for IKEv1.

If you would like to explore the use case further yourself, you may refer to these [configuration examples](https://libreswan.org/wiki/Configuration_examples) and/or ask on the [Libreswan users mailing list](https://lists.libreswan.org/mailman/listinfo/swan).

**Comment by olegkorol** [comment]
Thanks for the swift reply, @hwdsl2!
I'll check those resources and see if I can get this up and running :)

**Comment by olegkorol** [comment]
Update on this:

Switched from Libreswan to Strongswan (as I did not find any helpful references) and tried these approaches:
- https://github.com/GoogleCloudPlatform/community/blob/master/archived/using-cloud-vpn-with-strongswan/index.md
- https://blog.thecloudside.com/using-strongswan-to-setup-site-to-site-ipsec-vpn-between-gcp-and-digital-ocean-617da7d63b46
- https://github.com/truemetal/ikev2_vpn/tree/master

Result: neither of those approaches seems to work (_at least anymore_).
So I wasn't able to get it up and running after all.
