### ISSUE TITLE
Enable PFS for LT2P IPSEC

### ISSUE THREAD

**Issue by richardtop** [hwdsl2/setup-ipsec-vpn#1561]
**Checklist**

- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [x] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
Why PFS (Perfect Forward Secrecy) is not enabled for the l2tp ipsec vpn configuration by default?

here's the part from the mobileconfig:

> 
>         <key>EnablePFS</key>
>         <integer>0</integer>

**Comment by hwdsl2** [comment]
@richardtop Hello! `.mobileconfig` files are used for IKEv2 mode in this project, not IPsec/L2TP mode. Because PFS requires specific VPN ciphers, it is not enabled by default for compatibility with different versions of iOS and macOS systems. You may enable it for your use case by editing `/opt/src/ikev2.sh`, then re-create the IKEv2 client configuration.

**Comment by richardtop** [comment]
Could you please clarify more in detail how to enable PFS for IKEv2, i.e. when should I edit the file exactly and which command should I run afterwards? Thanks.

**Comment by hwdsl2** [comment]
@richardtop To enable PFS, edit the generated `.mobileconfig` file(s), find the EnablePFS key (as you mentioned above), change its value from 0 to 1. After that, remove the existing VPN profile (if any) from your VPN client (macOS or iOS), then import the edited `.mobileconfig` file.

Reference: https://developer.apple.com/documentation/devicemanagement/vpn/ikev2
