### ISSUE TITLE
Newly generated mobileconfig files don't work with the same pass that works for older configs

### ISSUE THREAD

**Issue by rolandjitsu** [hwdsl2/setup-ipsec-vpn#1564]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**

It looks like any new mobileconfig file the ikev2 script generates, does not work with the password that was used so far. I tried older configs and those work ok.

![Screenshot 2024-06-13 at 12 49 18](https://github.com/hwdsl2/setup-ipsec-vpn/assets/1479737/2b4f06ff-36a6-4063-9976-6b5a3eb43e96)

I have tried to get the certs from the p12 file and that works as well (both on the same machine where I generated it and other machines).

**To Reproduce**

1. Run
```shell
sudo bash ikev2.sh --addclient test-1
```
2. Get the .mobileconfig file to a macOS
3. Try to install the profile

**Expected behavior**

I should be able to install the profile.

**Logs**
[Check logs and VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status), and add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- OS: Ubuntu 20.04.5 LTS (Focal Fossa)
- Hosting provider (if applicable): GCP

**Client (please complete the following information)**
- Device: MacBook Air
- OS: 11.7 (other versions behave the same)
- VPN mode: IKEv2

**Additional context**

I know this is not a lot to go by, but I'd appreciate some help with pointers where this issue could be. Maybe the OS got some patch from GCP and some libs were updated (I haven't updated anything on the VM)?

**Comment by hwdsl2** [comment]
@rolandjitsu Hello! The libnss3 packages on Ubuntu 20.04 were recently updated to newer versions in the Ubuntu repositories, and as a result, the IKEv2 script was updated on April 10, 2024 in 25670f3 to fix the creation of `.mobileconfig` files on this OS.

Please update the IKEv2 script on your server using these instructions [1]. After that, re-run the script (`sudo ikev2.sh`) to re-create the client configuration `.mobileconfig` files, then import to your iOS or macOS device(s).

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#update-ikev2-helper-script

**Comment by rolandjitsu** [comment]
Thanks @hwdsl2 . I've applied the patch and it seems to work.
