### ISSUE TITLE
连接后网速特别慢，使用一键脚本安装的

### ISSUE THREAD

**Issue by 0x7ffffff** [hwdsl2/setup-ipsec-vpn#1566]
利用一键安装脚本后，通过mobileconfig连接上后网络极其的卡，只有5kb的下行速度
服务器的网络是20M（新加坡）的机器，经过测试在服务端，进行访问google等是没问题的，但是搭建成vpn后客户端访问速度机器差
请问这种原因需要怎么调配设置吗？
还是服务器有问题？

**Comment by hwdsl2** [comment]
@0x7ffffff 你好！VPN 的网速受限于客户端和服务器的上行和下行速度。但你所说的情况速率特别低，有可能是 VPN 客户端和服务器之间的网络存在问题，或者 VPN 连接受到了干扰。你可以尝试更换一个服务器提供商，或者尝试其他解决方案比如 Shadowsocks。

**Comment by 0x7ffffff** [comment]
非常感谢！已通过shadowsocks解决
