### ISSUE TITLE
IKEV2 突然 无法连接

### ISSUE THREAD

**Issue by david20220502** [hwdsl2/setup-ipsec-vpn#1567]
使用的 aliyun，debian11，然后使用作者脚本一键安装的
之前使用ikev2 方式连接，一直很正常，前天 突然所有设备手机 电脑都不能连接，win11 上提示的是跟没开服务器防火墙端口一样的提示，但是确认已经开启。服务器后台也是正常连接，ping  ip也正常。重新装服务器系统  重新运行脚本ikev2也连接不了。不知道怎么解决，有没有兄弟和我一样情况的。
**Checklist**

- [ ] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [ ] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [ ] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [ ] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [ ] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ ] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**

**To Reproduce**

1. ...
2. ...

**Expected behavior**

**Logs**
[Check logs and VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status), and add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- OS: [e.g. Debian 11]
- Hosting provider (if applicable): [e.g. GCP, AWS]

**Client (please complete the following information)**
- Device: [e.g. iPhone 12]
- OS: [e.g. iOS 15]
- VPN mode: [IPsec/L2TP, IPsec/XAuth ("Cisco IPsec") or IKEv2]

**Additional context**

**Comment by hwdsl2** [comment]
@david20220502 你好！根据你所描述的情况，可能是 VPN 连接被防火墙（比如 GFW）屏蔽了。建议你尝试其他解决方案，比如 Shadowsocks。

**Comment by david20220502** [comment]
shadowsocks会不会更容易挂？

**Comment by Adddllheids** [comment]
你好，请问你找到原因了吗，我也是aliyun和debian，突然不能用了

**Comment by david20220502** [comment]
可能是这个脚本被识别了，我不用aliyun了

**Comment by fanlilinSaber** [comment]
突然就不能用了  重新安装vpn 还是不行，
