### ISSUE TITLE
libreswan 5.0 的配置需要更新吗？

### ISSUE THREAD

**Issue by dawnbrave** [hwdsl2/setup-ipsec-vpn#1568]
有一些关键词好像不用了，但一键生成的还有。
最重要的功能，静态IP设定无效。
我换成4.15版本，静态IP功能又能用了。
是不是新版的配置文件要做相应适配呀？

**Comment by hwdsl2** [comment]
@dawnbrave 你好！Libreswan 4.15 的已有配置一般可以继续在 5.0 版本使用。有一些关键词在 5.0 版本已被弃用，你可以通过[查看 Libreswan 日志](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E6%A3%80%E6%9F%A5%E6%97%A5%E5%BF%97%E5%8F%8A-vpn-%E7%8A%B6%E6%80%81) 中的提示来查看这些关键词。

你所说的静态 IP 设定无效，是哪个 VPN 模式？IPsec/L2TP, IPsec/XAuth ("Cisco IPsec"), 还是 IKEv2？

**Comment by dawnbrave** [comment]
> @dawnbrave 你好！Libreswan 4.15 的已有配置一般可以继续在 5.0 版本使用。有一些关键词在 5.0 版本已被弃用，你可以通过 [查看 Libreswan 日志](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E6%A3%80%E6%9F%A5%E6%97%A5%E5%BF%97%E5%8F%8A-vpn-%E7%8A%B6%E6%80%81) 中的提示来查看这些关键词。
> 
> 你所说的静态 IP 设定无效，是哪个 VPN 模式？IPsec/L2TP, IPsec/XAuth ("Cisco IPsec"), 还是 IKEv2？

IKEv2模式下不太正常，重新安装4.15版本就没有问题，解析正确。
新版本L2TP模式也能正常分配， IPsec/XAuth没有测试。

**Comment by dawnbrave** [comment]
> @dawnbrave 你好！Libreswan 4.15 的已有配置一般可以继续在 5.0 版本使用。有一些关键词在 5.0 版本已被弃用，你可以通过 [查看 Libreswan 日志](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E6%A3%80%E6%9F%A5%E6%97%A5%E5%BF%97%E5%8F%8A-vpn-%E7%8A%B6%E6%80%81) 中的提示来查看这些关键词。
> 
> 你所说的静态 IP 设定无效，是哪个 VPN 模式？IPsec/L2TP, IPsec/XAuth ("Cisco IPsec"), 还是 IKEv2？

另外报告一下，我的服务器版本是debian 12.5
在Libreswan 4.15版本下，我配置Linux客户端也无需在服务器 配置 authby=rsa-sha1，已经实现了大一统。
不管是android，linux（debian12.5）和 win11，只要在服务器配置rightid="CN=client1, O=IKEv2 VPN"的格式，
都能够正确识别并配置固定IP。

**Comment by hwdsl2** [comment]
@dawnbrave 感谢你提供的信息。我有空再测试一下静态 IP 的问题。

**Comment by dawnbrave** [comment]
> @dawnbrave 感谢你提供的信息。我有空再测试一下静态 IP 的问题。

好的，谢谢。有时间的话，可以对5.0再做一次适配。
我刚才在4.15一切正常的情况下，用升级脚本升级到5.0，然后就不能指定IP了。
