### ISSUE TITLE
Windwos导入vpn证书时要求输入PFX密码

### ISSUE THREAD

**Issue by zhyxxxxxx** [hwdsl2/setup-ipsec-vpn#1569]
Windwos11使用脚本导入vpn证书时要求输入PFX密码，我从未在配置VPN服务端时设置过密码，请问如处理？

**Comment by hwdsl2** [comment]
@zhyxxxxxx 你好！对于你的用例，在PFX密码提示处，直接按回车键继续即可。如果无法导入，并且你的服务器运行 Ubuntu 20.04，请参见[Ubuntu 20.04 无法导入客户端配置](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#ubuntu-2004-%E6%97%A0%E6%B3%95%E5%AF%BC%E5%85%A5%E5%AE%A2%E6%88%B7%E7%AB%AF%E9%85%8D%E7%BD%AE)。

**Comment by zhyxxxxxx** [comment]
@hwdsl2 回车会提示密码错误，服务器是UNRAID的Docker环境。我把脚本复制服务器上与.p12证书同一目录后导入解决。难道是复制过程导致了证书损坏？
