### ISSUE TITLE
突然连接不上

### ISSUE THREAD

**Issue by fanlilinSaber** [hwdsl2/setup-ipsec-vpn#1576]
你好，一直用的阿里云服务器 CentOS 用了好几年了，突然就没法连接了，重新安装vpn配置和已有故障排除方法都不行
windows还是提示：
无法建立计算机与 VPN 服务器之间的网络连接，因为远程服务器未响应。这可能是因为未将计算机与远程服务器之间的某种网络设备(如防火墙、NAT、路由器等)配置为允许 VPN 连接。请与管理员或服务提供商联系以确定哪种设备可能产生此问题。
mac和iphone 都不行了 之前是都可以的

如果真是被防火墙（比如 GFW）屏蔽了，重置服务器可以重置安装可以解决吗

**Comment by DingDangCat2** [comment]
同楼上问，安卓自带vpn选项一直提示正在连接。之前也是同样配置都能正常访问。

**Comment by hwdsl2** [comment]
@fanlilinSaber 你好！根据你的描述，确实可能是防火墙屏蔽了连接。对于该情况，重置服务器不一定有用。请考虑换用 IPsec VPN 以外的其他解决方案，比如 Shadowsocks。

**Comment by fanlilinSaber** [comment]
好吧，谢谢解答
