### ISSUE TITLE
Problem when importing the certificate to the device

### ISSUE THREAD

**Issue by AlexITProf** [hwdsl2/setup-ipsec-vpn#1577]
Hey there!!!
Everything worked fine, but now that I have generated new certificates when importing to iOS devices, the Android OS of the device asks for a password. Is it possible to remove this one, I did not set passwords in the config, everything worked fine earlier, thank you)

**Comment by hwdsl2** [comment]
@AlexITProf Hello! Please see [Ubuntu 20.04 cannot import client config](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ubuntu-2004-cannot-import-client-config). You may encounter this issue on servers running Ubuntu 20.04, this can usually be resolved by following the steps in #1564 to update the IKEv2 helper script to the latest version.
