### ISSUE TITLE
make it have an uninstall option

### ISSUE THREAD

**Issue by skydzhugashvili5** [hwdsl2/setup-ipsec-vpn#1579]
**Checklist**

- [ ] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [ ] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [ ] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [ ] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [ ] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [ ] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
A clear and concise description of your enhancement request.

read title

**Is your enhancement request related to a problem? Please describe.**
(If applicable) A clear and concise description of what the problem is.

no

**Additional context**
Add any other context about the enhancement request here.

n/a

**Comment by hwdsl2** [comment]
@skydzhugashvili5 Hello! Please see [Uninstall the VPN](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/uninstall.md).
