### ISSUE TITLE
我ubuntu服务器装了SoftEthetvpn，在安装这一个，UDP 500和4500会冲突吗？

### ISSUE THREAD

**Issue by 625045508** [hwdsl2/setup-ipsec-vpn#1584]
我已经在内网Ubuntu服务器安装了 SoftEtherVPN, 并且映射到公网后， 外网手电脑可以拿到内网iP地址，互通和出国都OK, 无在部署个这ipsec-vpn， 不知道会不会端口冲突。也想问下这VPN能否和 SoftEtherVPN一样，创建虚拟网卡，绑定到br-lan网桥下，连上以后获取内网iP地址呢？

**Comment by hwdsl2** [comment]
@625045508 你好！对于 SoftEtherVPN，它的 L2TP/IPsec VPN 功能也使用 UDP 端口 500 和 4500，可能会造成端口冲突，不建议在同一台服务器上使用本项目的脚本。关于内网 IP 地址请参见 [VPN 内网 IP 和流量](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#vpn-%E5%86%85%E7%BD%91-ip-%E5%92%8C%E6%B5%81%E9%87%8F)，它和你描述的用例好像不太一样。
