### ISSUE TITLE
如何支持路由器上的l2tp client

### ISSUE THREAD

**Issue by jdkcn** [hwdsl2/setup-ipsec-vpn#159]
很多路由器的vpn都有l2tp。  小米、华硕.. 

不过这些路由器都不支持设置共享密钥。 不知道要如何设置才能支持这些路由器。

感谢提供这么方便的脚本。Google了一圈没找到解决办法。

**Comment by hwdsl2** [comment]
@jdkcn 你好！你所说的不支持设置共享密钥的路由器，其实它们是只支持不带 IPsec （不加密）的 L2TP 连接。这个模式主要是为了方便连接到某些特殊的因特网服务提供商设计的 （比如在俄罗斯），而不能用来连接 VPN。因为在该模式下传输的数据没有任何加密。

如果要连接到 IPsec/L2TP VPN 服务器，则需要明确写明支持 IPsec/L2TP 模式的路由器。这些路由器一般都比较高端。比如某些 Cisco 路由器。

**Comment by jdkcn** [comment]
@hwdsl2 感谢回答。那如果要配置不带IPSec的话。应该如何配置呢？谢谢。
看了一下。好像openwrt 的 l2tp client 也是不支持 IPsec 的。  ：）

其它的路由器大多基于openwrt 的。所以大家也就都不支持 IPsec 了对吧？

**Comment by hwdsl2** [comment]
@jdkcn 你好。如上所述，不带 IPsec 的 L2TP 模式不能用来连接 IPsec/L2TP VPN，因为在该模式下数据传输没有任何加密。支持 IPsec/L2TP 的路由器比较少，一般都比较高端。比如某些 Cisco 路由器。请参考 [1]。

另外，你也可以尝试 OpenVPN [2]。支持 OpenVPN 的路由器要比支持 IPsec/L2TP 的更多一些。

[1] https://community.spiceworks.com/topic/569867-any-router-s-wan-interface-supports-l2tp-over-ipsec-not-l2tp-alone
[2] https://github.com/Nyr/openvpn-install

**Comment by wangkaichimera** [comment]
请加下，我的路由器是WVR302应该怎么设置呢？按理说这个型号的是同时支持作为VPN的Server或者Client的，麻烦您了，谢谢！

**Comment by hwdsl2** [comment]
@wangkaichimera 你好！关于 WVR302 的设置，我也不太清楚。请查阅相关文档或网络教程。
