### ISSUE TITLE
静态IP端口转发 本地局域网跑的debain搭建证书无效

### ISSUE THREAD

**Issue by shangkouyou** [hwdsl2/setup-ipsec-vpn#1590]
**任务列表**

- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [ ] 我检查了 [IKEv1 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#ikev1-故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#ikev2-故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [ ] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ ] 这个 bug 是关于 VPN 安装脚本，而不是 IPsec VPN 本身

**问题描述**
我本地是申请公网IP地址的 用的是端口转发方式  本地运行的debain12系统  用的一件脚本自定义变量搭建成功之后 证书无效 该证书己过期，或者尚未生效。
**重现步骤**
重现该 bug 的步骤：
证书无效 该证书己过期，或者尚未生效。

脚本步骤
```
wget https://get.vpnsetup.net -O 21vpn.sh
VPN_DNS_NAME=10.86.2.3 \
VPN_PUBLIC_IP=10.86.2.105 \
VPN_DNS_SRV1=8.8.8.8 VPN_DNS_SRV2=119.29.29.29 \
VPN_XAUTH_NET=10.21.0.0/24 \
VPN_XAUTH_POOL=10.21.0.50-10.21.0.250 \
VPN_CLIENT_NAME=transnovo \
bash 21vpn.sh
```

**期待的正确结果**
证书的问题怎么弄 或者是 我可自签证书吗

**服务器信息（请填写以下信息）**
- 操作系统: debian12
- 服务提供商（如果适用）: 本地静态公网IP

**客户端信息（请填写以下信息）**
- 设备: windows
- 操作系统: windows10
- VPN 模式: IKEv2证书

**其它信息**
现状问题就是证书这个

**Comment by shangkouyou** [comment]
大佬们 你们本地跑的 证书是咋解决的呀

**Comment by hwdsl2** [comment]
@shangkouyou 你好！对于你所说的错误 `该证书己过期，或者尚未生效`，请首先检查你的 VPN 服务器和客户端上的系统时间是否准确。如果系统时间不对，生成的证书可能出现此问题。在校正服务器上的时间后，你可能需要[卸载](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/uninstall-zh.md)并重新安装 VPN。

对于你所说的在安装 VPN 时指定的变量，`VPN_DNS_NAME` 必须是一个域名（例如 `vpn.example.com`）而不是 IP 地址。如果你需要指定服务器的公有 IP，使用 `VPN_PUBLIC_IP` 变量指定即可。上述两个变量不要同时指定。

**Comment by shangkouyou** [comment]
> @shangkouyou* 你好！对于你所说的错误 `该证书己过期，或者尚未生效`，请首先检查你的 VPN 服务器和客户端上的系统时间是否准确。如果系统时间不对，生成的证书可能出现此问题。在校正服务器上的时间后，你可能需要[卸载](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/uninstall-zh.md)并重新安装 VPN。
> 
> 对于你所说的在安装 VPN 时指定的变量，`VPN_DNS_NAME` 必须是一个域名（例如 `vpn.example.com`）而不是 IP 地址。如果你需要指定服务器的公有 IP，使用 `VPN_PUBLIC_IP` 变量指定即可。上述两个变量不要同时指定。

好的谢谢你

**Comment by shangkouyou** [comment]
> @shangkouyou* 你好！对于你所说的错误 `该证书己过期，或者尚未生效`，请首先检查你的 VPN 服务器和客户端上的系统时间是否准确。如果系统时间不对，生成的证书可能出现此问题。在校正服务器上的时间后，你可能需要[卸载](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/uninstall-zh.md)并重新安装 VPN。
> 
> 对于你所说的在安装 VPN 时指定的变量，`VPN_DNS_NAME` 必须是一个域名（例如 `vpn.example.com`）而不是 IP 地址。如果你需要指定服务器的公有 IP，使用 `VPN_PUBLIC_IP` 变量指定即可。上述两个变量不要同时指定。

真的是时间问题 谢谢大佬 还想问下大佬昂 那个证书 可以多用户同时用的吗 证书密码可以自定义吗

**Comment by hwdsl2** [comment]
@shangkouyou 推荐为每个 IKEv2 客户端生成唯一的证书，请参见[配置 IKEv2 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#%E9%85%8D%E7%BD%AE-ikev2-vpn-%E5%AE%A2%E6%88%B7%E7%AB%AF)。目前不支持自定义证书密码。
