### ISSUE TITLE
ios安装描述文件提示密码不正确

### ISSUE THREAD

**Issue by yancy-hong** [hwdsl2/setup-ipsec-vpn#1591]
直接从服务器中下载`vpnclient.mobileconfig`，导入手机文件夹的，安装描述文件时提示`证书'vpnclient'的密码不正确`

**Comment by hwdsl2** [comment]
@yancy-hong 你好！请参见 [Ubuntu 20.04 无法导入客户端配置](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#ubuntu-2004-%E6%97%A0%E6%B3%95%E5%AF%BC%E5%85%A5%E5%AE%A2%E6%88%B7%E7%AB%AF%E9%85%8D%E7%BD%AE)。

**Comment by yancy-hong** [comment]
谢谢，README我都看半天了，没看到这条
