### ISSUE TITLE
h3c gr3000路由器 支持ipsec，为啥还是无法连接 ，服务器是华为云ecs自建的docker ipsec

### ISSUE THREAD

**Issue by warmsunshiny** [hwdsl2/setup-ipsec-vpn#1592]
![fadsfsafsa](https://github.com/user-attachments/assets/8bee093f-1ac2-430a-abca-f62a493dcea0)

**Comment by hwdsl2** [comment]
@warmsunshiny 你好！目前本项目对于 IPsec/L2TP 和 IPsec/XAuth 连接方式均需要 IPsec PSK 和用户名/密码，它与该路由器不兼容。根据网上的信息来看，该路由器的 IPsec VPN 配置并没有输入用户名和密码的选项，所以无法连接到本项目搭建的 VPN 服务器。

如果你想了解更多相关信息，请参见网上的[这个文档](https://developer.aliyun.com/article/1588499)，有一些相关的示例。对于本项目搭建的服务器，以下参数可能适用。但如上所述，对于 VPN 服务器配置，你将需要去除用户名/密码的要求，可以参见[这些示例](https://libreswan.org/wiki/Configuration_examples)。

IKE验证算法：SHA1
IKE加密算法：AES 或 AES128
IKE DH组：DH14 modp2048

对端地址：VPN 服务器 IP
预共享密钥：安装脚本输出中的 IPsec PSK

安全协议类型：ESP
ESP验证算法：SHA1
ESP加密算法：AES 或 AES128

**Comment by warmsunshiny** [comment]
我看了我的路由器只支持ike2模式，不支持ike1；我再找下其他的
