### ISSUE TITLE
按照流程搭建好正常使用，几天后无缘无故不能使用，VPS重装后再按照流程安装VPN，一直不能使用

### ISSUE THREAD

**Issue by bitbybit-dy** [hwdsl2/setup-ipsec-vpn#1596]
sudo journalctl -u ipsec  查询的日志结果：
Aug 30 10:46:23 bitbybit.com pluto[1000]: addconn: loading secrets from "/etc/ipsec.secrets"
Aug 30 10:46:23 bitbybit.com pluto[1000]: addconn:
Aug 30 10:46:46 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: responding to Main Mode from unknown peer 223.104.215.209:60917
Aug 30 10:46:46 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: sent Main Mode R1
Aug 30 10:46:47 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: sent Main Mode R2
Aug 30 10:46:47 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: STATE_MAIN_R2: retransmission; will wait 0.5 seconds for response
Aug 30 10:46:47 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: 50466-byte length of ISAKMP Identification Payload is larger than can fit
Aug 30 10:46:47 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: probable authentication failure (mismatch of preshared secrets?): malformed payload in packet
Aug 30 10:46:48 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: STATE_MAIN_R2: retransmission; will wait 1 seconds for response
Aug 30 10:46:49 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: STATE_MAIN_R2: retransmission; will wait 2 seconds for response
Aug 30 10:46:50 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: 50466-byte length of ISAKMP Identification Payload is larger than can fit
Aug 30 10:46:50 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: probable authentication failure (mismatch of preshared secrets?): malformed payload in packet
Aug 30 10:46:51 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: STATE_MAIN_R2: retransmission; will wait 4 seconds for response
Aug 30 10:46:51 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: 50466-byte length of ISAKMP Identification Payload is larger than can fit
Aug 30 10:46:51 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: probable authentication failure (mismatch of preshared secrets?): malformed payload in packet
Aug 30 10:46:53 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: 50466-byte length of ISAKMP Identification Payload is larger than can fit
Aug 30 10:46:53 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: probable authentication failure (mismatch of preshared secrets?): malformed payload in packet
Aug 30 10:46:55 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: STATE_MAIN_R2: retransmission; will wait 8 seconds for response
Aug 30 10:46:55 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: 50466-byte length of ISAKMP Identification Payload is larger than can fit
Aug 30 10:46:55 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: probable authentication failure (mismatch of preshared secrets?): malformed payload in packet
Aug 30 10:46:57 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: 50466-byte length of ISAKMP Identification Payload is larger than can fit
Aug 30 10:46:57 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: probable authentication failure (mismatch of preshared secrets?): malformed payload in packet
Aug 30 10:47:03 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: STATE_MAIN_R2: retransmission; will wait 16 seconds for response
Aug 30 10:47:03 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: 50466-byte length of ISAKMP Identification Payload is larger than can fit
Aug 30 10:47:03 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: probable authentication failure (mismatch of preshared secrets?): malformed payload in packet
Aug 30 10:47:09 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: 50466-byte length of ISAKMP Identification Payload is larger than can fit
Aug 30 10:47:09 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: probable authentication failure (mismatch of preshared secrets?): malformed payload in packet
Aug 30 10:47:19 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: STATE_MAIN_R2: retransmission; will wait 32 seconds for response
Aug 30 10:47:51 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: STATE_MAIN_R2: 60 second timeout exceeded after 7 retransmits.  No response (or no acceptable response) to our IKEv1 message
Aug 30 10:47:51 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209 #1: deleting ISAKMP SA (MAIN_R2) aged 64.337573s and NOT sending notification
Aug 30 10:47:51 bitbybit.com pluto[1000]: "l2tp-psk"[1] 223.104.215.209: deleting connection instance with peer 223.104.215.209
Aug 30 10:47:58 bitbybit.com pluto[1000]: "l2tp-psk"[2] 223.104.215.209 #2: responding to Main Mode from unknown peer 223.104.215.209:60917
Aug 30 10:47:58 bitbybit.com pluto[1000]: "l2tp-psk"[2] 223.104.215.209 #2: sent Main Mode R1
Aug 30 10:47:58 bitbybit.com pluto[1000]: "l2tp-psk"[2] 223.104.215.209 #2: sent Main Mode R2
Aug 30 10:47:58 bitbybit.com pluto[1000]: "l2tp-psk"[2] 223.104.215.209 #2: ignoring informational payload IPSEC_INITIAL_CONTACT, msgid=00000000, length=28
Aug 30 10:47:58 bitbybit.com pluto[1000]: "l2tp-psk"[2] 223.104.215.209 #2: Peer ID is ID_IPV4_ADDR: '10.173.120.16'
Aug 30 10:47:58 bitbybit.com pluto[1000]: "l2tp-psk"[2] 223.104.215.209 #2: switched to "l2tp-psk"[3] 223.104.215.209
Aug 30 10:47:58 bitbybit.com pluto[1000]: "l2tp-psk"[2] 223.104.215.209: deleting connection instance with peer 223.104.215.209
Aug 30 10:47:58 bitbybit.com pluto[1000]: "l2tp-psk"[3] 223.104.215.209 #2: ISAKMP SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA2_256 group=MODP2048}
Aug 30 10:48:01 bitbybit.com pluto[1000]: "l2tp-psk"[3] 223.104.215.209 #2: retransmitting in response to duplicate packet; already STATE_MAIN_R3
Aug 30 10:48:04 bitbybit.com pluto[1000]: "l2tp-psk"[3] 223.104.215.209 #2: retransmitting in response to duplicate packet; already STATE_MAIN_R3
Aug 30 10:48:08 bitbybit.com pluto[1000]: "l2tp-psk"[3] 223.104.215.209 #2: discarding duplicate packet -- exhausted retransmission; already STATE_MAIN_R3
Aug 30 10:48:20 bitbybit.com pluto[1000]: "l2tp-psk"[3] 223.104.215.209 #2: discarding duplicate packet -- exhausted retransmission; already STATE_MAIN_R3
(END)

**Comment by bitbybit-dy** [comment]
这里边的IP地址都是什么IP，我手机分别使用wifi和流量，发现日志的IP都是一样的。奇怪的是这些IP也不是服务器IP地址

**Comment by bitbybit-dy** [comment]
ISAKMP 识别有效载荷的 50466 字节长度大于可以容纳的长度。——是什么意思，这个可能致病的问题

**Comment by bitbybit-dy** [comment]
Aug 30 11:15:03 bitbybit.com pluto[5844]: forgetting secrets
Aug 30 11:15:03 bitbybit.com pluto[5844]: loading secrets from "/etc/ipsec.secrets"
Aug 30 11:15:03 bitbybit.com pluto[5844]: addconn: "ikev2-cp": ikev2=yes has been replaced by keyexchange=ikev2
Aug 30 11:15:03 bitbybit.com pluto[5844]: addconn: "ikev2-cp": added IKEv2 connection
Aug 30 11:15:03 bitbybit.com pluto[5844]: addconn: listening for IKE messages
Aug 30 11:15:03 bitbybit.com pluto[5844]: addconn: Kernel supports NIC esp-hw-offload
Aug 30 11:15:03 bitbybit.com pluto[5844]: addconn: adding UDP interface eth0 74.48.151.25:500
Aug 30 11:15:03 bitbybit.com pluto[5844]: addconn: adding UDP interface eth0 74.48.151.25:4500
Aug 30 11:15:03 bitbybit.com pluto[5844]: addconn: adding UDP interface lo 127.0.0.1:500
Aug 30 11:15:03 bitbybit.com pluto[5844]: addconn: adding UDP interface lo 127.0.0.1:4500
Aug 30 11:15:03 bitbybit.com pluto[5844]: addconn: adding UDP interface lo [::1]:500
Aug 30 11:15:03 bitbybit.com pluto[5844]: addconn: adding UDP interface lo [::1]:4500
Aug 30 11:15:03 bitbybit.com pluto[5844]: addconn: adding UDP interface eth0 [2607:f130:0:196:216:3eff:feea:5dcc]:500
Aug 30 11:15:03 bitbybit.com pluto[5844]: addconn: adding UDP interface eth0 [2607:f130:0:196:216:3eff:fe
Aug 30 11:15:03 bitbybit.com pluto[5844]: addconn: ea:5dcc]:4500
Aug 30 11:15:03 bitbybit.com pluto[5844]: addconn: "ikev2-cp": oriented IKEv2 connection (local: left=74.48.151.25  remote: right=0.0.0.0)
Aug 30 11:15:03 bitbybit.com pluto[5844]: addconn: "xauth-psk": oriented IKEv1 connection (local: left=74.48.151.25  remote: right=0.0.0.0)
Aug 30 11:15:03 bitbybit.com pluto[5844]: addconn: "l2tp-psk": oriented IKEv1 connection (local: left=74.48.151.25  remote: right=0.0.0.0)
Aug 30 11:15:03 bitbybit.com pluto[5844]: addconn: forgetting secrets
Aug 30 11:15:03 bitbybit.com pluto[5844]: addconn: loading secrets from "/etc/ipsec.secrets"
Aug 30 11:15:03 bitbybit.com pluto[5844]: addconn:
Aug 30 11:17:34 bitbybit.com pluto[5844]: "l2tp-psk"[1] 171.223.167.161 #1: responding to Main Mode from unknown peer 171.223.167.161:3320
Aug 30 11:17:34 bitbybit.com pluto[5844]: "l2tp-psk"[1] 171.223.167.161 #1: sent Main Mode R1
Aug 30 11:17:34 bitbybit.com pluto[5844]: "l2tp-psk"[1] 171.223.167.161 #1: sent Main Mode R2
Aug 30 11:17:34 bitbybit.com pluto[5844]: "l2tp-psk"[1] 171.223.167.161 #1: ignoring informational payload IPSEC_INITIAL_CONTACT, msgid=00000000, length=28
Aug 30 11:17:34 bitbybit.com pluto[5844]: "l2tp-psk"[1] 171.223.167.161 #1: Peer ID is ID_IPV4_ADDR: '192.168.1.2'
Aug 30 11:17:34 bitbybit.com pluto[5844]: "l2tp-psk"[1] 171.223.167.161 #1: switched to "l2tp-psk"[2] 171.223.167.161
Aug 30 11:17:34 bitbybit.com pluto[5844]: "l2tp-psk"[1] 171.223.167.161: deleting connection instance with peer 171.223.167.161
Aug 30 11:17:34 bitbybit.com pluto[5844]: "l2tp-psk"[2] 171.223.167.161 #1: ISAKMP SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA2_256 group=MODP2048}
Aug 30 11:17:38 bitbybit.com pluto[5844]: "l2tp-psk"[2] 171.223.167.161 #1: retransmitting in response to duplicate packet; already STATE_MAIN_R3
Aug 30 11:17:41 bitbybit.com pluto[5844]: "l2tp-psk"[2] 171.223.167.161 #1: retransmitting in response to duplicate packet; already STATE_MAIN_R3
Aug 30 11:17:44 bitbybit.com pluto[5844]: "l2tp-psk"[2] 171.223.167.161 #1: discarding duplicate packet -- exhausted retransmission; already STATE_MAIN_R3
Aug 30 11:17:56 bitbybit.com pluto[5844]: "l2tp-psk"[2] 171.223.167.161 #1: discarding duplicate packet -- exhausted retransmission; already STATE_MAIN_R3
(END)

y使用默认的PSK和账户密码又重装了一遍，还是报错

**Comment by bitbybit-dy** [comment]
这是我总结的教程：（哪里有问题？？？？？？？）

############################################################################### 安装 VPN
# 下载
# wget https://git.io/vpnsetup -O vpnsetup.sh
wget https://get.vpnsetup.net -O vpn.sh

# 安装
sudo bash vpn.sh

# 清理 apt 缓存
sudo rm -rf /var/lib/apt/lists/*
sudo apt-get clean # /var/cache/apt/archives/


############################################################################### 卸载 VPN
wget https://get.vpnsetup.net/unst -O unst.sh
sudo bash unst.sh


############################################################################### 配置与管理
# PSK 配置文件
sudo cat /etc/ipsec.secrets

# IPsec/L2TP 用户配置文件
sudo cat /etc/ppp/chap-secrets

# IPsec/XAuth ("Cisco IPsec") 用户配置文件
sudo cat /etc/ipsec.d/passwd

# ipsec 配置文件
sudo cat /etc/ipsec.conf

# xl2tpd 配置文件
sudo cat /etc/xl2tpd/xl2tpd.conf

# ipsec 服务
sudo systemctl status ipsec
sudo systemctl restart ipsec
sudo journalctl -u ipsec | less # log

# xl2tpd 服务
sudo systemctl status xl2tpd
sudo systemctl restart xl2tpd
sudo journalctl -u xl2tpd | less # log

# 检查 Libreswan (IPsec) 和 xl2tpd 日志是否
sudo grep pluto /var/log/auth.log | less
sudo grep xl2tpd /var/log/syslog | less

# 查看 IPsec VPN 服务器状态
sudo ipsec status | less

# 显示当前已建立的 VPN 连接
sudo ipsec whack --trafficstatus
sudo ipsec trafficstatus

**Comment by bitbybit-dy** [comment]
完结！估计500、4500被GFW封禁了。

**Comment by ArcCal** [comment]
这个协议就不是用来翻墙的。不加前置，被封几乎是立即的。

**Comment by bitbybit-dy** [comment]
请教一二，加什么前置，如果想正常使用VPN，该使用什么工具？

**Comment by ArcCal** [comment]
就v2ray、clash之类的

**Comment by bitbybit-dy** [comment]
话说，可以直接部署http带密码认证的代理在服务器上吗？

**Comment by hwdsl2** [comment]
@bitbybit-dy 你好！根据你提供的日志来看，可能是连接被 GFW 屏蔽或干扰了。建议你另外尝试除 IPsec VPN 之外的其他解决方案。
