### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by cinderhk** [hwdsl2/setup-ipsec-vpn#1599]
Hello, can this run in centos7 environment? if cant't, Can you develop and run in centos 7 environment? I want to use it

**Comment by letoams** [comment]
Centos 7 has been end of life for years. No one is working on it and you shouldn’t deploy it anymoreSent using a virtual keyboard on a phoneOn Sep 13, 2024, at 02:35, cinderhk ***@***.***> wrote:﻿
Hello, can this run in centos7 environment? if cant't, Can you develop and run in centos 7 environment? I want to use it

**Comment by hwdsl2** [comment]
@cinderhk Hello! As @letoams mentioned, CentOS 7 has reached [EOL](https://www.redhat.com/en/topics/linux/centos-linux-eol) and is no longer supported. If you want to install the IPsec VPN, please instead use one of the [supported Linux versions](https://github.com/hwdsl2/setup-ipsec-vpn?tab=readme-ov-file#requirements).
