### ISSUE TITLE
Windows users cannot use it

### ISSUE THREAD

**Issue by dbaflight** [hwdsl2/setup-ipsec-vpn#16]
Hello,
I have successfully installed on my server, and iOS users can use this VPN. However, when I am using it on windows, it can not burn through the Chinese Great Firewall. For example, the browser can open 'baidu.com' but 'google.com' cannot be opened.

**Comment by hwdsl2** [comment]
Hello @dbaflight, the issue you encountered is possibly due to DNS caching of incorrect IP addresses. To flush DNS cache, open an elevated command prompt and run ipconfig /flushdns , then reboot your Windows computer. You may also try opening the websites in a different browser.

**Comment by dbaflight** [comment]
Thanks for your reply. Problem has been solved.
