### ISSUE TITLE
Credentials error on Win 11 with IKEv2 only

### ISSUE THREAD

**Issue by CaptainFrosty** [hwdsl2/setup-ipsec-vpn#1602]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**
Hello, I could use some help with an error I'm getting despite not changing anything with my server or client setup. I am getting _"IKE credentials are unacceptable"_ with the native Win 11 VPN client. I have made a new user and reran the VPN setup script.

**To Reproduce**

1. Try to connect with Windows 11
2. Fails negotiation

**Expected behavior**
It has worked perfectly until recently.

**Logs**
![image](https://github.com/user-attachments/assets/7604bed1-0da7-4872-817c-1ff778047249)

**Server (please complete the following information)**
- OS: Rocky Linux 9

**Client (please complete the following information)**
- Device: PC
- OS: Win 11 Pro 23H2
- VPN mode: IKEv2

**Additional context**

Thanks for all that you do.

**Comment by CaptainFrosty** [comment]
I think I had a problem like this before. May be on the client side with Windows trying to use SHA1 instead of SHA256 with the cert signature. I don't think I ever figured out how to fix it.

**Comment by CaptainFrosty** [comment]
I can fix this by adding SHA1 as an accepted cipher server side, correct? I would just prefer not to as it isn't the greatest.

**Comment by hwdsl2** [comment]
@CaptainFrosty Hello! Thanks for providing the details on this error. To fix this on Rocky Linux, edit `/etc/crypto-policies/back-ends/nss.config` on your VPN server, and add `SHA1:` after `allow=`. For example, assume that the relevant line looks like this:
```
config="disallow=ALL allow=HMAC-SHA256...
```
Change it to:
```
config="disallow=ALL allow=SHA1:HMAC-SHA256...
```
Save the file and run `sudo service ipsec restart`.

When `SHA1` is disallowed in this configuration, IKEv2 certificates with `SHA1` signatures (which refers to the signatures inside the certificates themselves) would be rejected with the error you mentioned. Changing the configuration as described above would fix the issue. Currently, `SHA1` signatures are needed for IKEv2 for compatibility with e.g. Apple devices.

Note that this file `/etc/crypto-policies/back-ends/nss.config` is provided by the `crypto-policies` package. As of today 2024-09-23, the latest version on Rocky Linux 9 is `crypto-policies-20240202-1.git283706d.el9.noarch`, and `SHA1` is allowed by default in this version:
```
config="disallow=ALL allow=HMAC-SHA256:...:SHA512:SHA224:SHA1:ECDHE-RSA:..."
```

**Comment by hwdsl2** [comment]
@CaptainFrosty I looked into this further and found that the generated IKEv2 certificates already contain SHA-256 signatures by default (tested on Rocky Linux 9), so this is NOT an issue with signatures inside the certificates.

Instead, VPN clients such as Apple devices and Windows could be using SHA1 signatures when initiating a VPN connection. This is client side behavior which can't be changed on the VPN server side. However, you should be able to fix the issue by adding SHA1 to `/etc/crypto-policies/back-ends/nss.config` as mentioned in my comment above.

**Comment by CaptainFrosty** [comment]
I think this is an issue with the Windows IKE service. It works properly again after a reset/OS reinstall, then randomly errors again. My VPN certs correctly report as SHA256 signatures yet Windows IKE still offers SHA1. Have tried to fix with PowerShell to no avail. 

Isn't SHA1 considered a compromised algorithm? I will add it back for now until I can reset Windows or something, but I prefer to not have it on my crypto policies.

**Comment by CaptainFrosty** [comment]
@hwdsl2 my untouched file
![image](https://github.com/user-attachments/assets/5ef0c073-643f-4d8d-87e2-b2000f9d6e47)

adding SHA1 to the beginning does not seem to change the error

**Comment by CaptainFrosty** [comment]
I actually just tried from strongswan on Android and I get the same sort of authentication error.

**Comment by CaptainFrosty** [comment]
Well, I recreated a new user on the VPN, and I forcibly disabled SHA1 in Windows using 

`
"$data = '0'; reg add 'HKLM\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Hashes\SHA' /v 'Enabled' /t 'REG_DWORD' /d "^""$data"^"" /f"`

and now my error message has changed at least. Making some progress:

![image](https://github.com/user-attachments/assets/a0558e60-080d-4709-b33c-ecf75508879a)

**Comment by CaptainFrosty** [comment]
And then I have this one also:

![image](https://github.com/user-attachments/assets/82015dec-42de-4c9a-8d2f-1b628a3996a0)

**Comment by hwdsl2** [comment]
@CaptainFrosty Please refer to [ipsec.conf documentation](https://libreswan.org/man/ipsec.conf.5.html) and search for "authby" on that page. To allow RSA authentication with SHA-1 (the default), you'll need to include `rsasig` in the `authby` line in your image above, in file `/etc/crypto-policies/back-ends/libreswan.config`. I don't think this file is installed by default, maybe it's part of your custom configuration.

For adding SHA1 to `/etc/crypto-policies/back-ends/nss.config`, see [my comment above](https://github.com/hwdsl2/setup-ipsec-vpn/issues/1602#issuecomment-2369930025). You can add it after `allow=` on the relevant line.

**Comment by CaptainFrosty** [comment]
@hwdsl2 I figured out the problem. There was something wrong with the NSS database on my server. It was the server certificate that was the problem. After rebuilding the database and reinstalling libreswan everything is working fine.

**Comment by ultrafunkamsterdam** [comment]
Ran into the same issue. 
L2TP works fine in windows using PSK.

what fixed it for me was this:
Import the p12 store in local machine, under user, then rightclick, copy, and paste it also in the trusted root.
Assuming you already created the VPN profile, click "more vpn properties"
![image](https://github.com/user-attachments/assets/d11eadd0-03a2-4b39-abc5-3bb249e9d9d9)

on the "security" tab, check "marchine certificate"

![image](https://github.com/user-attachments/assets/b8a1f466-f98d-47ab-862f-a2bb16ea699a)
