### ISSUE TITLE
Cannot connect to a server through IKEv2 after updating to iOS 18.

### ISSUE THREAD

**Issue by danirbadmaev** [hwdsl2/setup-ipsec-vpn#1605]
I have no idea what happened.

Seems like the issue is not quite popular, yet there are some (not working) workarounds on forums, for example:
https://techsearch.watchguard.com/KB?type=Known%20Issues&SFDCID=kA1Vr00000060IHKAY&lang=en_US 

I've tried to change "LocalIdentifier" and "PayloadCertificateFileName" fields in .mobileconfig  in accordance to FQDN format by adding '.com' to the vpnclient name. That didn't work.

There is also a possible hint for the problem in the Apple patch notes, see the key 'allowVPNcreation':
https://support.apple.com/en-us/121158 
https://developer.apple.com/forums/thread/757362?answerId=799025022#799025022

**Comment by hwdsl2** [comment]
@danirbadmaev Hello! I am unable to reproduce this issue on an iOS 18 device, the IKEv2 VPN connects fine. This may be an issue with your specific VPN server or iOS client. Try creating a new IKEv2 client and importing to your iOS device.

**Comment by bobrutskovav** [comment]
This problem is actual on many clients on iOS 18 device(((
