### ISSUE TITLE
这个脚本配套的防火墙是禁用firewalld启用nftables么？

### ISSUE THREAD

**Issue by landall** [hwdsl2/setup-ipsec-vpn#1606]
好多年前用这个脚本建过一轮vpn，昨天vps突然数据全丢失，被迫重建。

我的操作系统是AlmaLinux 8

想问一下，目前的这个脚本应该如何开启防火墙？

我的理解是，继续按照默认去禁用Firewalld，然后手动启用nftables？

----

另外，我如果防火墙被其他程序把规则覆盖了，修复步骤是怎样的？我现在只能覆盖式安装一次。

**Comment by hwdsl2** [comment]
@landall 你好！对于你的用例，在 AlmaLinux 8 上如果安装 VPN 时 firewalld 已启用，脚本将禁用 firewalld 并将已有的规则加入 IPTables 中。该过程是自动完成的。你可以通过编辑 `/etc/sysconfig/iptables` 以修复或自定义 IPTables 规则。 完成后使用 iptables-restore 重新载入该文件或重启。

如果是 AlmaLinux 版本 9，则在安装 VPN 时会禁用 firewalld 并将已有的规则加入 nftables 中。你可以通过编辑 `/etc/sysconfig/nftables.conf` 以修复或自定义 IPTables 规则。完成后使用 nft 重新载入该文件或重启。

请参见：
https://github.com/hwdsl2/setup-ipsec-vpn/blob/b895650cafb1910fe1d9d5bf43213bb9a673e5ef/vpnsetup_centos.sh#L268-L296
https://github.com/hwdsl2/setup-ipsec-vpn/blob/b895650cafb1910fe1d9d5bf43213bb9a673e5ef/vpnsetup_centos.sh#L604-L666
