### ISSUE TITLE
有证书但是找不到RSA key

### ISSUE THREAD

**Issue by yuboliu** [hwdsl2/setup-ipsec-vpn#161]
查看ipsec日志
[root@localhost ipsec.d]# journalctl -xu ipsec

Jun 26 18:04:18 localhost.localdomain pluto[92764]: | Sending [CERT] of certificate: O=Example,CN=10.10.216.177
Jun 26 18:04:18 localhost.localdomain pluto[92764]: "ikev2-remote-access"[1] 10.11.207.66 #3: Failed to find our RSA key
Jun 26 18:04:18 localhost.localdomain pluto[92764]: | ikev2_parent_inI2outR2_tail returned STF_FATAL
Jun 26 18:04:18 localhost.localdomain pluto[92764]: "ikev2-remote-access"[1] 10.11.207.66 #3: deleting state #3 (STATE_PARENT_R2)

从日志可以看出找不到我们证书的RSA key
[root@localhost ipsec.d]# certutil -L -d sql:/etc/ipsec.d -n 10.10.216.177

 Issuer: "O=Example,CN=Example CA"
        Validity:
            Not Before: Mon Jun 26 10:03:00 2017
            Not After : Fri Jun 26 10:03:00 2020
        Subject: "O=Example,CN=10.10.216.177"

可以看到存在一个O=Example,CN=10.10.216.177的证书

配置文件：
conn ikev2-remote-access
        left=10.10.216.177
        leftcert=10.10.216.177
        leftid=10.10.216.177
        leftsendcert=always
        leftsubnet=0.0.0.0/0
        leftrsasigkey=%cert
        right=%any
        rightaddresspool=192.168.43.10-192.168.43.250
        rightca=%same
        rightrsasigkey=%cert
        modecfgdns1=8.8.8.8
        modecfgdns2=8.8.4.4
        narrowing=yes
        dpddelay=30
        dpdtimeout=120
        dpdaction=clear
        auto=add
        ikev2=insist
        rekey=no
        fragmentation=yes
        ike=3des-sha1,3des-sha2,aes-sha1,aes-sha1;modp1024,aes-sha2,aes-sha2;modp1024,aes256-sha2_512
        phase2alg=3des-sha1,3des-sha2,aes-sha1,aes-sha2,aes256-sha2_512

**Comment by hwdsl2** [comment]
@yuboliu 你好！你这个问题很可能是因为运行的生成服务器证书的命令不完整导致的。请重新按照 IKEv2 文档 [1] 中的步骤操作，注意有些命令有两行。如需删除已有的证书，可以尝试使用 certutil -D -d sql:/etc/ipsec.d -n "Nickname"。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md
