### ISSUE TITLE
你好。怎么才能让Vpn切换IP。

### ISSUE THREAD

**Issue by zhucan3n** [hwdsl2/setup-ipsec-vpn#1610]
你好。我的服务器是动态拨号服务器。
怎么才能让Vpn切换IP。或者有接口吗？

**Comment by hwdsl2** [comment]
@zhucan3n 你好！对于你的用例，你可以在安装 VPN 时指定一个域名作为服务器地址。请参见[域名和更改服务器 IP](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#%E5%9F%9F%E5%90%8D%E5%92%8C%E6%9B%B4%E6%94%B9%E6%9C%8D%E5%8A%A1%E5%99%A8-ip)。
