### ISSUE TITLE
ikev2 分流后客户端之间无法互通

### ISSUE THREAD

**Issue by huangqingchao** [hwdsl2/setup-ipsec-vpn#1614]
**任务列表**

- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [x] 我检查了 [IKEv1 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#ikev1-故障排除)，[IKEv2 故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#ikev2-故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] 这个 bug 是关于 VPN 安装脚本，而不是 IPsec VPN 本身

**问题描述**
使用 `ikev2` 方式，两个客户端连接后，两台客户端可以互相ping通
设置 分流 后，两个客户端互相无法ping通

**重现步骤**
重现该 bug 的步骤：
1、按照步骤搭建了仅`ikev2`，并且两个客户端连接成功，两个客户端都固定ipsec ip
用户1：u1 - RouterOS - ipsec ip 10.0.0.2 - 内网IP 192.168.0.1
用户2:  u2 - Macbook 15.0.1 - ipsec ip 10.0.0.3 - 内网IP 192.168.31.2
u2 可以 ping 通 10.0.0.2，但无法ping 通192.168.0.1

2、u2 按照 [IKEv2 模式：启用 VPN 分流 (split tunneling)](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#vpn-%E5%88%86%E6%B5%81)方式，设置了
```
conn ikev2-shared
  ...
  # leftsubnet=0.0.0.0/0

conn u1
  leftsubnet=0.0.0.0/0
  ...

conn u2
  leftsubnet=192.168.0.0/24
  ...
```

3、两端连接后，u1没变，u2 MacBook的路由表
```
netstat -nr | grep 10.0
10.0.0.3           10.0.0.3           UH                 ipsec0
192.168.0          10.0.0.3           UGSc               ipsec0
```

4、这时候 u2 无法ping通 10.0.0.2，ping 192.168.0.1时，看到u1的ipsec peer没有收到任何数据包，也无法ping通

**期待的正确结果**
1、u2能ping通10.0.0.2
2、u2能ping通192.168.0.1

我的想法也应该有点问题，但是我是想要实现
1、ipsec 所有客户端网段10.0.0.0/24能够互通
2、所有客户端可以访问192.168.0.0/24网段
不知道能不能实现这个功能

**日志**
[检查日志及 VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)，并添加错误日志以帮助解释该问题（如果适用）。

**服务器信息（请填写以下信息）**
- 操作系统: [比如 Debian 12]
- 服务提供商（如果适用）: [阿里ECS]

**客户端信息（请填写以下信息）**
- 设备1（u1）: [软路由]
- 操作系统: [Router OS]
- 设备2（u2）: [Macbook]
- 操作系统: [MacOS 15.0.1]
- VPN 模式: [IKEv2]

**其它信息**
添加关于该 bug 的其它信息。

**Comment by hwdsl2** [comment]
@huangqingchao 你好！关于你的用例：目前本项目对访问 VPN 服务器后面的子网有文档说明，请参见高级用法中的相关节。但是，对于访问 VPN 客户端后面的子网（比如你的用例是用户 2 访问用户 1 后面的子网）目前并不支持，没有文档说明。建议你可以另外尝试比如在用户 1 的子网 192.168.0.0/24 内搭建 VPN 服务器，或者尝试其他解决方案比如 [WireGuard](https://github.com/hwdsl2/wireguard-install) 等。
