### ISSUE TITLE
同一个路由器下 只能连接一个账号

### ISSUE THREAD

**Issue by wanbogithub** [hwdsl2/setup-ipsec-vpn#1616]
我公司和家里几台电脑 同时只能连接2个账号，我绑定了9个虚拟ip和1个主ip 添加了9个账号对应9个ip地址 家里的4台电脑只能连接上一个账号，公司2台电脑也只能连接一个，就是同时连接 只有家里和公司2个账号 我想9个账号同时连接，可有办法

**Comment by hwdsl2** [comment]
@wanbogithub 你好！对于你的用例，由于 IPsec/L2TP 模式的局限性，如果需要连接在同一个 NAT（比如家用路由器）后面的多个设备，请使用 [IKEv2](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md) 或者 [IPsec/XAuth](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth-zh.md) 模式，并为每个客户端生成唯一的证书或用户名/密码。参见 [管理 VPN 用户](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users-zh.md)。另外，你也可以尝试 [OpenVPN](https://github.com/hwdsl2/openvpn-install/blob/master/README-zh.md) 或 [WireGuard](https://github.com/hwdsl2/wireguard-install/blob/master/README-zh.md)。
