### ISSUE TITLE
Hello, do you support multiple IPs?

### ISSUE THREAD

**Issue by a834003831** [hwdsl2/setup-ipsec-vpn#1617]
Hello, does this script automatically detect multiple IPs on the server and generate one key for each IP?

**Comment by hwdsl2** [comment]
@a834003831 你好！目前脚本不支持该用例。你可以指定 VPN 服务器的公有 IP，请参见[这里](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#%E6%8C%87%E5%AE%9A-vpn-%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9A%84%E5%85%AC%E6%9C%89-ip)。但是在指定 IP 后，对于 IKEv2 模式，只会为该 IP 生成证书。对于 IPsec/L2TP 和 IPsec/XAuth 模式，你可以使用任何服务器上的公网 IP 连接，它们将共享相同的 IPsec PSK 和用户名/密码。参见[管理 VPN 用户](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users-zh.md)。对于你的用例，你可以另外尝试其他解决方案。

**Comment by a834003831** [comment]
> @a834003831 你好！目前脚本不支持该用例。你可以指定 VPN 服务器的公有 IP，请参见[这里](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#%E6%8C%87%E5%AE%9A-vpn-%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9A%84%E5%85%AC%E6%9C%89-ip)。但是在指定 IP 后，对于 IKEv2 模式，只会为该 IP 生成证书。对于 IPsec/L2TP 和 IPsec/XAuth 模式，你可以使用任何服务器上的公网 IP 连接，它们将共享相同的 IPsec PSK 和用户名/密码。参见[管理 VPN 用户](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users-zh.md)。对于你的用例，你可以另外尝试其他解决方案。

你好，你是中国的大佬嘛？如果我需要搭建多个账户对应不同的IP，有什么好的方案嘛？
