### ISSUE TITLE
IPv6 support?

### ISSUE THREAD

**Issue by fanlessfan** [hwdsl2/setup-ipsec-vpn#1619]
Hello,

I can successfully running in ipv4 environment. but failed on ipv6. does it support ipv6?

thx

**Comment by letoams** [comment]
On Wed, 4 Dec 2024, VA3EMQ wrote:

> I can successfully running in ipv4 environment. but failed on ipv6. does it support ipv6?

If you want to run where it accepts v6 and v4 (and gives you a v4 and v6 IP when you connect)
you need something along the lines of:

conn vpn4
 	left=193.110.157.148
 	leftsubnet=0.0.0.0/0,::/0
 	also=vpn-base
conn vpn6
 	left=2a03:6000:1004:1::148
 	leftsubnet=0.0.0.0/0,::/0
 	also=vpn-base

conn vpn-base
 	leftsubnet=0.0.0.0/0,2000::/3
 	rightaddresspool=100.64.13.0/24,2a03:6000:1005::/97
         [...regular options...]

Paul

**Comment by fanlessfan** [comment]
Thank you Paul @letoams. here is my modified ikev2.conf I use ikev2 only setup. but still not successful.

here is log

Dec 04 13:37:57 NASVM3 pluto[10559]: packet from [2605:b100:163:553b:c76:b44f:397e:6b7c]:500: ISAKMP_v2_IKE_SA_INIT mes>
Dec 04 13:37:57 NASVM3 pluto[10559]: packet from [2605:b100:163:553b:c76:b44f:397e:6b7c]:500: responding to IKE_SA_INIT>
Dec 04 13:38:20 NASVM3 pluto[10559]: packet from [2605:b100:163:553b:c76:b44f:397e:6b7c]:500: ISAKMP_v2_IKE_SA_INIT mes>
Dec 04 13:38:20 NASVM3 pluto[10559]: packet from [2605:b100:163:553b:c76:b44f:397e:6b7c]:500: responding to IKE_SA_INIT>

here is the ikev2.conf

conn ikev2-cp
  left=%defaultroute
  leftcert=vpn.zhous.net
  leftsendcert=always
  leftsubnet=0.0.0.0/0,2000::/3
  leftrsasigkey=%cert
  right=%any
  rightid=%fromcert
  rightaddresspool=192.168.43.0/24,2607:fea8:3c5f:ff66:0:ffff/96
  rightca=%same
  rightrsasigkey=%cert
  narrowing=yes
  dpddelay=30
  retransmit-timeout=300s
  dpdaction=clear
  auto=add
  ikev2=insist
  rekey=no
  pfs=no
  ike=aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1
  phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes128-sha2,aes256-sha2
  ikelifetime=24h
  salifetime=24h
  encapsulation=yes
  leftid=@vpn.zhous.net
  modecfgdns="192.168.99.9 8.8.4.4"
  mobike=yes

**Comment by letoams** [comment]
On Wed, 4 Dec 2024, VA3EMQ wrote:

> Thank you Paul @letoams. here is my modified ikev2.conf I use ikev2 only setup. but still not successful.
> 
> here is log
> 
> Dec 04 13:37:57 NASVM3 pluto[10559]: packet from [2605:b100:163:553b:c76:b44f:397e:6b7c]:500: ISAKMP_v2_IKE_SA_INIT mes>
> Dec 04 13:37:57 NASVM3 pluto[10559]: packet from [2605:b100:163:553b:c76:b44f:397e:6b7c]:500: responding to IKE_SA_INIT>
> Dec 04 13:38:20 NASVM3 pluto[10559]: packet from [2605:b100:163:553b:c76:b44f:397e:6b7c]:500: ISAKMP_v2_IKE_SA_INIT mes>
> Dec 04 13:38:20 NASVM3 pluto[10559]: packet from [2605:b100:163:553b:c76:b44f:397e:6b7c]:500: responding to IKE_SA_INIT>
> 
> here is the ikev2.conf
> 
> conn ikev2-cp
> left=%defaultroute

This only listens on IPv4. This is why in my example you see two conns.
One with a left= using ipv4 and one using a left= with ipv6.

Paul

**Comment by fanlessfan** [comment]
Thank you Paul. Could you let me know what should I put in the left= base on my ikev2 conf file? is the server IP?

**Comment by fanlessfan** [comment]
here are the full error messages

`Dec  4 14:21:46 NASVM3 pluto[30042]: packet from [2605:b100:163:553b:c76:b44f:397e:6b7c]:500: ISAKMP_v2_IKE_SA_INIT message received on [2607:fea8:3c5f:ff66:4c41:53ff:fe56:4d03]:500 but no suitable connection found with IKEv2 policy
Dec  4 14:21:46 NASVM3 pluto[30042]: packet from [2605:b100:163:553b:c76:b44f:397e:6b7c]:500: responding to IKE_SA_INIT (34) message (Message ID 0) with unencrypted notification NO_PROPOSAL_CHOSEN
`

Here are the conf.

`cat /etc/ipsec.d/ikev2.conf 
conn vpn4
 	left=127.0.0.1
 	leftsubnet=0.0.0.0/0,::/0
 	also=ikev2-cp
conn vpn6
 	left=2607:fea8:3c5f:ff66:4c41:53ff:fe56:4d03
 	leftsubnet=0.0.0.0/0,::/0
 	also=ikev2-cp

conn ikev2-cp
  left=%defaultroute
  leftcert=vpn.zhous.net
  leftsendcert=always
  leftsubnet=0.0.0.0/0,2000::/3
  leftrsasigkey=%cert
  right=%any
  rightid=%fromcert
  rightaddresspool=192.168.43.0/24,2607:fea8:3c5f:ff66:0:ffff/96
  rightca=%same
  rightrsasigkey=%cert
  narrowing=yes
`

I have error from the above config though.

`Dec 04 14:28:28 NASVM3 pluto[30103]: addconn: Failed to load connection left= is not set`
`Dec 04 14:28:28 NASVM3 pluto[30103]: addconn: Failed to load connection left= is not set`

**Comment by letoams** [comment]
On Wed, 4 Dec 2024, VA3EMQ wrote:

> here are the full error messages
> 
> Dec 4 14:21:46 NASVM3 pluto[30042]: packet from [2605:b100:163:553b:c76:b44f:397e:6b7c]:500: ISAKMP_v2_IKE_SA_INIT message received on
> [2607:fea8:3c5f:ff66:4c41:53ff:fe56:4d03]:500 but no suitable connection found with IKEv2 policy Dec 4 14:21:46 NASVM3 pluto[30042]: packet from
> [2605:b100:163:553b:c76:b44f:397e:6b7c]:500: responding to IKE_SA_INIT (34) message (Message ID 0) with unencrypted notification NO_PROPOSAL_CHOSEN
> 
> Here are the conf.
> 
> `cat /etc/ipsec.d/ikev2.conf
> conn vpn4
> left=127.0.0.1

This is not a valid left=

> leftsubnet=0.0.0.0/0,::/0
> also=ikev2-cp

Add auto=add

> conn vpn6
> left=2607:fea8:3c5f:ff66:4c41:53ff:fe56:4d03
> leftsubnet=0.0.0.0/0,::/0
> also=ikev2-cp

Instead of ::/0 please use 2000::/3
Add auto=add

> I have error from the above config though.
> 
> Dec 04 14:28:28 NASVM3 pluto[30103]: addconn: Failed to load connection left= is not set
> Dec 04 14:28:28 NASVM3 pluto[30103]: addconn: Failed to load connection left= is not set

The IPs you configure for left= MUST be IPs configured on your host.

Paul

**Comment by letoams** [comment]
On Wed, 4 Dec 2024, VA3EMQ wrote:

> Thank you Paul. Could you let me know what should I put in the left= base on my ikev2 conf file? is the server IP?

You omit left= in the base conn, and only have left= in the specific
v4/v6 conns.

**Comment by fanlessfan** [comment]
I still get error left= is not set after modify to below.

cat /etc/ipsec.d/ikev2.conf 
conn vpn4
  left=192.168.99.8
  leftsubnet=0.0.0.0/0,::/0
  also=ikev2-cp
conn vpn6
  left=2607:fea8:3c5f:ff66:4c41:53ff:fe56:4d03
  leftsubnet=0.0.0.0/0,::/0
  also=ikev2-cp

conn ikev2-cp
#  left=%defaultroute
  left=192.168.99.8,2607:fea8:3c5f:ff66:4c41:53ff:fe56:4d03
  leftsubnet=0.0.0.0/0,2000::/3
  rightaddresspool=192.168.43.0/24,2607:fea8:3c5f:ff66:0:ffff/97
  leftcert=vpn.zhous.net
  leftsendcert=always
  leftrsasigkey=%cert
  right=%any
  rightid=%fromcert
  rightca=%same
  rightrsasigkey=%cert
  narrowing=yes
  dpddelay=30
  retransmit-timeout=300s
  dpdaction=clear
  auto=add
  ikev2=insist
  rekey=no
  pfs=no
  ike=aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1
  phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes128-sha2,aes256-sha2
  ikelifetime=24h
  salifetime=24h
  encapsulation=yes
  leftid=@vpn.zhous.net
  modecfgdns="192.168.99.9 8.8.4.4"
  mobike=yes

ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq state UP group default qlen 1000
    link/ether 4e:41:53:56:4d:03 brd ff:ff:ff:ff:ff:ff
    inet 192.168.99.8/17 brd 192.168.127.255 scope global dynamic noprefixroute ens3
       valid_lft 3801sec preferred_lft 3801sec
    inet6 2607:fea8:3c5f:ff66:4c41:53ff:fe56:4d03/64 scope global dynamic noprefixroute 
       valid_lft 86294sec preferred_lft 14294sec
    inet6 fe80::4c41:53ff:fe56:4d03/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever

**Comment by fanlessfan** [comment]
also `no suitable connection found with IKEv2 policy` when I try to vpn in.

Thanks in advance

**Comment by hwdsl2** [comment]
@fanlessfan Hello! This project does not currently support sending IPv6 traffic through the VPN. In addition to the Libreswan configuration changes @letoams mentioned, you may also need IP6Tables rule(s) to correctly forward IPv6 traffic and possibly other changes, which this project does not currently have in the scripts.

Feel free to continue the discussion here, but for now I would suggest that you try alternative solutions such as [OpenVPN](https://github.com/hwdsl2/openvpn-install) or [WireGuard](https://github.com/hwdsl2/wireguard-install). Those two projects currently support sending IPv6 traffic through the VPN.

**Comment by fanlessfan** [comment]
Thanks @hwdsl2
