### ISSUE TITLE
IPsec Security Association tracking

### ISSUE THREAD

**Issue by Ejz** [hwdsl2/setup-ipsec-vpn#162]
Hi. I need ability of L2TP/IPSec VPN to track multiple clients behind the same NAT router. As [Man page](https://linux.die.net/man/5/xl2tpd.conf) says this can only be done by Openswan KLIPS in "mast" mode. Does Libreswan support this feature?

**Comment by hwdsl2** [comment]
@Ejz Hello! I think Libreswan supports KLIPS, but am not sure about the details. It is outside the scope of this project. You can find some references here [1] [2] [3]. Questions should be directed to the Libreswan mailing list [4]. Thanks!

[1] https://github.com/libreswan/libreswan/blob/master/README.KLIPS
[2] https://libreswan.org/wiki/KLIPS
[3] https://libreswan.org/wiki/SAref_code
[4] https://lists.libreswan.org/mailman/listinfo/swan
