### ISSUE TITLE
Assign static IPs to VPN clients problem

### ISSUE THREAD

**Issue by DaniloL88s** [hwdsl2/setup-ipsec-vpn#1620]
I really have several problems when I try to configure the ikev2 client to assign a static IP to a Windows client.
I put below all the config files and what appears to me from the ipsec trafficstatus.
I can't understand what the problem is also because I have really tried so many times

conn ikev2-cp
  left=%defaultroute
  leftcert=45.xx.xxx.xxx
  leftsendcert=always
  leftsubnet=0.0.0.0/0
  leftrsasigkey=%cert
  right=%any
  rightid=%fromcert
  rightaddresspool=192.168.43.100-192.168.43.250
  rightca=%same
  rightrsasigkey=%cert
  narrowing=yes
  dpddelay=30
  retransmit-timeout=300s
  dpdaction=clear
  auto=add
  ikev2=insist
  rekey=no
  pfs=no
  ike=aes_gcm_c_256-hmac_sha2_256-ecp_256,aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1
  phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes128-sha2,aes256-sha2
  ikelifetime=24h
  salifetime=24h
  encapsulation=yes
  leftid=45.xx.xxx.xxx
  modecfgdns="8.8.8.8 8.8.4.4"
  mobike=no`

conn ikev2-shared
  left=%defaultroute
  leftcert=45.xx.xxx.xxx
  leftsendcert=always
  leftsubnet=0.0.0.0/0
  leftrsasigkey=%cert
  right=%any
  rightca=%same
  rightrsasigkey=%cert
  narrowing=yes
  dpddelay=30
  retransmit-timeout=300s
  dpdaction=clear
  ikev2=insist
  rekey=no
  pfs=no
  ike=aes_gcm_c_256-hmac_sha2_256-ecp_256,aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1
  phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes128-sha2,aes256-sha2
  ikelifetime=24h
  salifetime=24h
  encapsulation=yes
  leftid=45.xx.xxx.xxx
  modecfgdns="8.8.8.8 8.8.4.4"
  mobike=no

conn DaniloPC
  rightid="CN=DaniloPC, O=IKEv2 VPN"
  rightaddresspool=192.168.43.20-192.168.43.20
  also=ikev2-shared

conn username
  rightid="CN=username, O=IKEv2 VPN"
  rightaddresspool=192.168.43.22-192.168.43.22
  also=ikev2-shared

Trafficstatus log:
`#2: "ikev2-cp"[1] MYIP, type=ESP, add_time=1733338737, inBytes=119392, outBytes=354784, maxBytes=2^63B, id='CN=DaniloPC, O=IKEv2 VPN', lease=192.168.43.100/32
`

I don't understand why despite the various ipsec restarts and reboots of the operating system, despite having tried with different certificates and therefore clients, the problem persists. Do I forget to do something? Am I forgetting some step?

**Comment by letoams** [comment]
[ added libreswan list to the CC: ]

On Wed, 4 Dec 2024, DaniloL88s wrote:

> I really have several problems when I try to configure the ikev2 client to assign a static IP to a Windows client.
> I put below all the config files and what appears to me from the ipsec trafficstatus.
> I can't understand what the problem is also because I have really tried so many times

Yes, we need to add a better simpler method to support static IP leases.

> `conn ikev2-cp
> rightaddresspool=192.168.43.100-192.168.43.250
[...]

> 
> conn ikev2-shared
> left=%defaultroute
> leftcert=45.xx.xxx.xxx
> leftsendcert=always
> leftsubnet=0.0.0.0/0
> leftrsasigkey=%cert
> right=%any
> rightca=%same
> rightrsasigkey=%cert
> narrowing=yes
> dpddelay=30
> retransmit-timeout=300s
> dpdaction=clear
> ikev2=insist
> rekey=no
> pfs=no
> ike=aes_gcm_c_256-hmac_sha2_256-ecp_256,aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1
> phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes128-sha2,aes256-sha2
> ikelifetime=24h
> salifetime=24h
> encapsulation=yes
> leftid=45.xx.xxx.xxx
> modecfgdns="8.8.8.8 8.8.4.4"
> mobike=no

> conn DaniloPC
> rightid="CN=DaniloPC, O=IKEv2 VPN"
> rightaddresspool=192.168.43.20-192.168.43.20
> also=ikev2-shared
> 
> conn username
> rightid="CN=username, O=IKEv2 VPN"
> rightaddresspool=192.168.43.22-192.168.43.22
> also=ikev2-shared`
> 
> Trafficstatus log:
> #2: "ikev2-cp"[1] MYIP, type=ESP, add_time=1733338737, inBytes=119392, outBytes=354784, maxBytes=2^63B, id='CN=DaniloPC, O=IKEv2 VPN',
> lease=192.168.43.100/32
> 
> I don't understand why despite the various ipsec restarts and reboots of the operating system, despite having tried with different certificates and
> therefore clients, the problem persists. Do I forget to do something? Am I forgetting some step?

It looks like you got matched with conn ikev2-cp and not conn DaniloPC.

I think instead of hacking this into the template vs instance code
selection, we should have a simple file allowing ID:IP matches to
be used with a generic addresspool.

A workaround could be to use a different leftid= for ikev2-cp vs the
individual conns. But that would then require custom params on the
clients as well.

Paul

**Comment by hwdsl2** [comment]
Thanks @letoams. @DaniloL88s Your IPsec configuration looks fine for assigning static IPs to Windows clients, according to [Internal VPN IPs and traffic](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#internal-vpn-ips-and-traffic) in the project docs. A few things to try:

1. Restart the IPsec service using `sudo service ipsec restart`, then [check the Libreswan logs](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status) and run `ipsec status` to make sure that the `DaniloPC` connection is loaded correctly. After that, try reconnecting the Windows client.
2. If the above doesn't work, run `certlm.msc` in Windows to open the Certificate Manager ([steps](https://learn.microsoft.com/en-us/dotnet/framework/wcf/feature-details/how-to-view-certificates-with-the-mmc-snap-in#view-certificates-with-the-certificate-manager-tool)). Go to Certificates - Personal - Certificates, and check to see if there are multiple certificates issued by `IKEv2 VPN CA`. If so, keep only the `DaniloPC` one and remove other certificates issued by `IKEv2 VPN CA`. After that, re-connect the client. This makes sure the client authenticates with the VPN server using the correct certificate.

If you have additional information feel free to continue to reply here.

**Comment by DaniloL88s** [comment]
@bleve Thanks for the answer, if I put `rightid="CN=*, OU=*"`, VPN has problem to connect (Credential IKE error), if I put only `rightid="CN=*"` it works but same problem.

**Comment by bleve** [comment]
I see one big issue in your config.  you are missing `auto=add` in two per person connections, so likely they were not loaded at all.

I'd also change the config like this, by using also include in all connections. Then you don't have so much duplication in config.

```
conn ikev2-cp
        also=ikev2-shared
        #
        rightid="CN=*, O=IKEv2 VPN"
        rightaddresspool=192.168.43.100-192.168.43.250
        #
        auto=add

conn ikev2-cp-DaniloPC
        also=ikev2-shared
        #
        rightid="CN=DaniloPC, O=IKEv2 VPN"
        rightaddresspool=192.168.43.20-192.168.43.20
        #
        auto=add

conn ikev2-cp-username
        also=ikev2-shared
        #
        rightid="CN=username, O=IKEv2 VPN"
        rightaddresspool=192.168.43.22-192.168.43.22
        #
        auto=add

conn ikev2-shared
        left=%defaultroute
        leftcert=45.xx.xxx.xxx
        leftsendcert=always
        leftsubnet=0.0.0.0/0
        leftrsasigkey=%cert
        #
        right=%any
        rightca=%same
        rightrsasigkey=%cert
        #
        narrowing=yes
        dpddelay=30
        retransmit-timeout=300s
        dpdaction=clear
        ikev2=insist
        rekey=no
        pfs=no
        ike=aes_gcm_c_256-hmac_sha2_256-ecp_256,aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1
        phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes128-sha2,aes256-sha2
        ikelifetime=24h
        salifetime=24h
        encapsulation=yes
        leftid=45.xx.xxx.xxx
        modecfgdns="8.8.8.8 8.8.4.4"
        mobike=no
```

**Comment by DaniloL88s** [comment]
Thank so much, with this config it works properly.
It would be best to add this to the guide that @hwdsl2 made.

**Comment by hwdsl2** [comment]
Thanks @bleve for the insights. @DaniloL88s Yes, the [documentation](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#internal-vpn-ips-and-traffic) does contain `auto=add` for the two per person connections.
