### ISSUE TITLE
你好，求推出多线路得脚本

### ISSUE THREAD

**Issue by a834003831** [hwdsl2/setup-ipsec-vpn#1622]
一直用大佬的脚本很多年了，因为是直播，对网络稳定性有需求，外面的脚本，都不如大佬做出来的，求大佬出个可以多线路的脚本

curl -O http://www.yeexun.net/n1/install.sh&&chmod +x install.sh&&./install.sh

这是别人的脚本，可以参考下，大佬

**Comment by hwdsl2** [comment]
@a834003831 你好！感谢你的建议。不太清楚你所说的多线路的含义，如果是指同一个服务器上有多个公有 IP，并同时支持 VPN 客户端连接的话，目前本项目不支持该功能。但是你可以指定服务器的公有 IP，请参见[高级用法](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md)中的 “指定 VPN 服务器的公有 IP“ 小节。另外，如果你说的是 VPN 客户端连接到多个 VPN 服务器并在它们之间切换的话，IPsec VPN 客户端一般不支持该使用方式，你可以另外尝试一下其他解决方案。
