### ISSUE TITLE
如何让不同用户通过不同网卡访问外网

### ISSUE THREAD

**Issue by charlieqwq** [hwdsl2/setup-ipsec-vpn#1623]
如题，服务器有2个网卡，记为eth0 eth1，现尝试通过指定用户分配ip并指定网络接口的方式进行分流，但是只有将出口指定为eth0才能上网，eth1可以连接访问内网但是无法访问外网
![image](https://github.com/user-attachments/assets/bf53327e-88a7-4e6a-b5e4-f97cb7c24a8e)
![image](https://github.com/user-attachments/assets/363700d3-a38a-418a-9a8a-ed14f52473e1)
可见eth0有流量但eth1没有，应如何处理

**Comment by hwdsl2** [comment]
@charlieqwq 你好！请参见[指定 VPN 服务器的公有 IP](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#%E6%8C%87%E5%AE%9A-vpn-%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9A%84%E5%85%AC%E6%9C%89-ip) 以及它之前的小节。请注意，该方法仅适用于服务器的默认网络接口对应多个公有 IP 的情况。如果服务器有多个网络接口，例如 eth0 和 eth1，并且对应不同的公有 IP，则此方法无效。

对于你的用例，有可能不能使用上述方法。一般来说，可以通过比如修改 Linux 路由表来指定目标是特定子网的流量走某一个网络接口，但通过路由表可能无法区分多个 VPN 用户的流量。另外，你也可以尝试一下 IPsec VPN 以外的其他解决方案。
