### ISSUE TITLE
.mobileconfig can't be used in newer versions of iOS on iPhone

### ISSUE THREAD

**Issue by dimaphuket** [hwdsl2/setup-ipsec-vpn#1626]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [IKEv1 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ikev1-troubleshooting), [IKEv2 troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ikev2-troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] This bug is about the VPN setup scripts, and not IPsec VPN itself

Created .mobileconfig files can not be used on iPhones anymore
**Describe the issue**
When using .mobileconfig files on iPhone profile can not be installed with an error "Incorrect password". It appears that the problem is that .p12 certificates are incompatible with newer version of SSL.
Can you update this script to insure that .p12 certificates are compatible with newer versions of iPhones?
Current workaround was to create .p12 manually than use the following commands (original p12 had name spb1)
cp spb1.p12 temp_certificate.p12
openssl pkcs12 -in temp_certificate.p12 -out temp_certificate.pem -nodes -passin pass:12345
openssl pkcs12 -in temp_certificate.p12 -nocerts -out temp_certificate.key -passin pass:12345 -passout pass:'12345'
openssl pkcs12 -export -out new_certificate.p12 -inkey temp_certificate.key -in temp_certificate.pem -passin pass:12345 -passout pass:12345

**Comment by hwdsl2** [comment]
@dimaphuket Hello! What is your VPN server's Linux distribution and version (e.g. Ubuntu 24.04)? The IKEv2 script already contains code that detects the newer OpenSSL version 3 and apply the appropriate conversion for the mobileconfig file.

**Comment by hwdsl2** [comment]
@dimaphuket Please see section [Ubuntu 20.04 cannot import client config](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#ubuntu-2004-cannot-import-client-config) in IKEv2 troubleshooting, which I think may be the issue you encountered. To resolve the issue, follow the instructions in that section to update the IKEv2 script to the latest version, then run `sudo ikev2.sh` and select "export" to re-create the client configuration file.
