### ISSUE TITLE
 Suggested addition of compatible system: OpenWRT.

### ISSUE THREAD

**Issue by Kings-Github** [hwdsl2/setup-ipsec-vpn#1629]
This is a very perfect project, but I believe it would be even more perfect if support for the OpenWRT system could be added.

Suggested compatible systems:

1.OpenWRT for x86_64 architecture platform, recommended model: Soft Router
2.OpenWRT for aarch64_cortex-a53 architecture platform, recommended model: Beryl AX (GL-MT3000)

Thank you!

**Comment by Kings-Github** [comment]
The Beryl AX (GL-MT3000) is a very cute router that natively supports OpenWRT. I believe it would work really well with this project, and I'm sure you'll like it when you see it.

This router is extremely compact and portable, so you can take it anywhere with you. Additionally, it supports U-BOOT flashing, meaning you can't really damage the router no matter what you do, which makes it even more impressive to me! It also supports Wi-Fi 6, providing excellent wireless signal performance!

This is not an advertisement, haha~

**Comment by hwdsl2** [comment]
@Kings-Github Hello! Thank you for your suggestions. Currently, this project does not support usage with OpenWRT as a VPN client, however you may be able to configure it manually. You can find more information in this earlier issue: #1019.
