### ISSUE TITLE
mac系统能连上VPN 但是不能上外网 查ip也是国内的ip

### ISSUE THREAD

**Issue by WongCM** [hwdsl2/setup-ipsec-vpn#163]
求助下该如何解决，曾经连上过一次上外网完全没问题，但是断开后再连就一直不行，而且连着连着还会自动断开，日志如下

    Jun 28 01:09:37 133-130-101-55 pluto[2832]: "l2tp-psk"[7] 112.115.206.59 #7: responding to Main Mode from unknown peer 112.115.206.59
    Jun 28 01:09:37 133-130-101-55 pluto[2832]: "l2tp-psk"[7] 112.115.206.59 #7: transition from state STATE_MAIN_R0 to state STATE_MAIN_R1
    Jun 28 01:09:37 133-130-101-55 pluto[2832]: "l2tp-psk"[7] 112.115.206.59 #7: STATE_MAIN_R1: sent MR1, expecting MI2
    Jun 28 01:09:40 133-130-101-55 pluto[2832]: "l2tp-psk"[7] 112.115.206.59 #8: responding to Main Mode from unknown peer 112.115.206.59
    Jun 28 01:09:40 133-130-101-55 pluto[2832]: "l2tp-psk"[7] 112.115.206.59 #8: transition from state STATE_MAIN_R0 to state STATE_MAIN_R1
    Jun 28 01:09:40 133-130-101-55 pluto[2832]: "l2tp-psk"[7] 112.115.206.59 #8: STATE_MAIN_R1: sent MR1, expecting MI2
    Jun 28 01:09:40 133-130-101-55 pluto[2832]: "l2tp-psk"[7] 112.115.206.59 #8: transition from state STATE_MAIN_R1 to state STATE_MAIN_R2
    Jun 28 01:09:40 133-130-101-55 pluto[2832]: "l2tp-psk"[7] 112.115.206.59 #8: STATE_MAIN_R2: sent MR2, expecting MI3
    Jun 28 01:09:40 133-130-101-55 pluto[2832]: "l2tp-psk"[7] 112.115.206.59 #8: ignoring informational payload IPSEC_INITIAL_CONTACT, msgid=00000000, length=28
    Jun 28 01:09:40 133-130-101-55 pluto[2832]: | ISAKMP Notification Payload
    Jun 28 01:09:40 133-130-101-55 pluto[2832]: |   00 00 00 1c  00 00 00 01  01 10 60 02
    Jun 28 01:09:40 133-130-101-55 pluto[2832]: "l2tp-psk"[7] 112.115.206.59 #8: Main mode peer ID is ID_IPV4_ADDR: '192.168.1.102'
    Jun 28 01:09:40 133-130-101-55 pluto[2832]: "l2tp-psk"[7] 112.115.206.59 #8: switched from "l2tp-psk"[7] 112.115.206.59 to "l2tp-psk"
    Jun 28 01:09:40 133-130-101-55 pluto[2832]: "l2tp-psk"[8] 112.115.206.59 #8: transition from state STATE_MAIN_R2 to state STATE_MAIN_R3
    Jun 28 01:09:40 133-130-101-55 pluto[2832]: "l2tp-psk"[8] 112.115.206.59 #8: new NAT mapping for #8, was 112.115.206.59:27018, now 112.115.206.59:27019
    Jun 28 01:09:40 133-130-101-55 pluto[2832]: "l2tp-psk"[8] 112.115.206.59 #8: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=aes_256 integ=sha2_256 group=MODP2048}
    Jun 28 01:09:44 133-130-101-55 pluto[2832]: "l2tp-psk"[8] 112.115.206.59 #8: the peer proposed: 133.130.101.55/32:17/1701 -> 192.168.1.102/32:17/0
    Jun 28 01:09:44 133-130-101-55 pluto[2832]: "l2tp-psk"[8] 112.115.206.59 #8: NAT-Traversal: received 2 NAT-OA. Using first, ignoring others
    Jun 28 01:09:44 133-130-101-55 pluto[2832]: "l2tp-psk"[8] 112.115.206.59 #9: responding to Quick Mode proposal {msgid:5e7152cd}
    Jun 28 01:09:44 133-130-101-55 pluto[2832]: "l2tp-psk"[8] 112.115.206.59 #9:     us: 133.130.101.55:17/1701
    Jun 28 01:09:44 133-130-101-55 pluto[2832]: "l2tp-psk"[8] 112.115.206.59 #9:   them: 112.115.206.59[192.168.1.102]:17/50925
    Jun 28 01:09:44 133-130-101-55 pluto[2832]: "l2tp-psk"[8] 112.115.206.59 #9: transition from state STATE_QUICK_R0 to state STATE_QUICK_R1
    Jun 28 01:09:44 133-130-101-55 pluto[2832]: "l2tp-psk"[8] 112.115.206.59 #9: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 transport mode {ESP/NAT=>0x02bb6d39 <0x5518e705 xfrm=AES_256-HMAC_SHA1 NATOA=192.168.1.102 NATD=112.115.206.59:27019 DPD=active}
    Jun 28 01:09:46 133-130-101-55 pluto[2832]: "l2tp-psk"[8] 112.115.206.59 #9: transition from state STATE_QUICK_R1 to state STATE_QUICK_R2
    Jun 28 01:09:46 133-130-101-55 pluto[2832]: "l2tp-psk"[8] 112.115.206.59 #9: STATE_QUICK_R2: IPsec SA established transport mode {ESP/NAT=>0x02bb6d39 <0x5518e705 xfrm=AES_256-HMAC_SHA1 NATOA=192.168.1.102 NATD=112.115.206.59:27019 DPD=active}
    Jun 28 01:12:39 133-130-101-55 pluto[2832]: "l2tp-psk"[8] 112.115.206.59 #8: received Delete SA(0x02bb6d39) payload: deleting IPSEC State #9
    Jun 28 01:12:39 133-130-101-55 pluto[2832]: "l2tp-psk"[8] 112.115.206.59 #8: deleting other state #9 (STATE_QUICK_R2) "l2tp-psk"[8] 112.115.206.59
    Jun 28 01:12:39 133-130-101-55 pluto[2832]: "l2tp-psk"[8] 112.115.206.59 #8: ESP traffic information: in=0B out=0B
    Jun 28 01:12:40 133-130-101-55 pluto[2832]: "l2tp-psk" #8: deleting state (STATE_MAIN_R3)
    Jun 28 01:12:40 133-130-101-55 pluto[2832]: "l2tp-psk"[8] 112.115.206.59: deleting connection "l2tp-psk"[8] 112.115.206.59 instance with peer 112.115.206.59 {isakmp=#0/ipsec=#0}
    Jun 28 01:12:40 133-130-101-55 pluto[2832]: packet from 112.115.206.59:27019: received and ignored empty informational notification payload
    
用下面这个命令查看也是能看到这个连接的，但就是不能上网

    ipsec whack --trafficstatus

**Comment by hwdsl2** [comment]
@WongCM 你好！从日志来看没有什么问题。如果 VPN 连接成功过，但是之后又不行，很可能是因为防火墙干扰导致的。你可以先试一下重启服务：
```
sudo service ipsec restart
sudo service xl2tpd restart
```

然后重启你的客户端电脑，并重新连接。如果还是不行，那很可能不是 VPN 服务器的问题。请尝试其它解决方案，比如 Shadowsocks。

**Comment by WongCM** [comment]
已经解决了 多谢

**Comment by onlyforcloud** [comment]
@WongCM 请问是怎么解决的呢，一样的问题。

**Comment by madalion** [comment]
> @WongCM 请问是怎么解决的呢，一样的问题。

请问解决了么，又碰到一样的问题
