### ISSUE TITLE
Is there any way to create an anonymous (wildcard) login/access?

### ISSUE THREAD

**Issue by ahmednitul** [hwdsl2/setup-ipsec-vpn#164]
Hello,

I'd like to enable access/authenticate with any informations, means either if the user usages vpn or guest or admin as username/password/secrets, it would authenticate/authorize and connect them.

I tried using %any and blank, also "*" in the secrets/user-management files as instructed in (https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users.md) but it does not work.

Could you please advise?

Thanks.

**Comment by hwdsl2** [comment]
@ahmednitul Hello! AFAIK your use case is not possible with Libreswan. Further questions can be asked on the Libreswan mailing list [1].

[1] https://lists.libreswan.org/mailman/listinfo/swan
