### ISSUE TITLE
如何统计用户访问的流量？

### ISSUE THREAD

**Issue by figofuture** [hwdsl2/setup-ipsec-vpn#166]
如题？如何统计通过VPN访问网络的用户流量？

**Comment by hwdsl2** [comment]
@figofuture Hello! The feature you mentioned is outside the scope of this project. You will need to write  scripts to do that. Here is an example [1], which is based on [2]. **Warning:** Use these at your own risk!

The usage and example outputs are very similar to [2]. Refer to the project's README. It works with IPsec/L2TP only. Before using, you must add a line "debug" to your "/etc/ppp/options.xl2tpd", and run "service xl2tpd restart". Also, a known issue is that the "Remote IP" column does not work.

[1] https://gist.github.com/hwdsl2/855904bfdf0aec6a9cf8d16882acccea
[2] https://github.com/boukeversteegh/pptpd-monitor

**Comment by skop1986** [comment]
@hwdsl2 Hello, I added a script, but I get this message
~# python3 /opt/src/l2tp-monitor.py
File "/opt/src/l2tp-monitor.py", line 62
    print fstring,
    ^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

Python 3.10.12

**Comment by hwdsl2** [comment]
@skop1986 The script you mentioned is deprecated, as it only supports Python 2 and is not compatible with Python 3. You can refer to the [original repo](https://github.com/boukeversteegh/pptpd-monitor) for more information.

**Comment by skop1986** [comment]
> @skop1986 The script you mentioned is deprecated, as it only supports Python 2 and is not compatible with Python 3. You can refer to the [original repo](https://github.com/boukeversteegh/pptpd-monitor) for more information.

Thanks for your reply.  Unfortunately, I don't have the experience to fix it(

**Comment by skop1986** [comment]
> @skop1986 The script you mentioned is deprecated, as it only supports Python 2 and is not compatible with Python 3. You can refer to the [original repo](https://github.com/boukeversteegh/pptpd-monitor) for more information.

It seems like it turned out to be updated for python 3, but now it gives out this:

:~# python3 /opt/src/l2tp-monitor.py --rotate
/opt/src/l2tp-monitor.py:64: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if interval is 0:
 Traceback (most recent call last):
  File "/opt/src/l2tp-monitor.py", line 298, in <module>
    monitor.monitor()
  File "/opt/src/l2tp-monitor.py", line 59, in monitor
    sessionlist  = self.get_sessions()
  File "/opt/src/l2tp-monitor.py", line 102, in get_sessions
    self.process_line(line, activesessions, sessionlist)
  File "/opt/src/l2tp-monitor.py", line 113, in process_line
    match =  self.r_pptpd.search(line)
TypeError: cannot use a string pattern on a bytes-like object

**Comment by skop1986** [comment]
> @skop1986 The script you mentioned is deprecated, as it only supports Python 2 and is not compatible with Python 3. You can refer to the [original repo](https://github.com/boukeversteegh/pptpd-monitor) for more information.

Good afternoon! Please tell me, are you planning to update the script?

**Comment by hwdsl2** [comment]
@skop1986 For the script mentioned, there are no plans to update it at this time.

**Comment by skop1986** [comment]
@hwdsl2 Thank you for your work and time! This is a really good product!

**Comment by skop1986** [comment]
It looks like there is no user information in the file (/var/log/syslog/) that I am accessing. What file can contain this information?

**Comment by hwdsl2** [comment]
@skop1986 This applies to IPsec/L2TP mode only. Before using, you must add a line "debug" to your "/etc/ppp/options.xl2tpd", and run "service xl2tpd restart". The log file is most likely /var/log/messages.

**Comment by skop1986** [comment]
The only thing that helped me make it work was to install python 2.7))
