### ISSUE TITLE
生成的key 密码都是随机的吗？

### ISSUE THREAD

**Issue by samz406** [hwdsl2/setup-ipsec-vpn#167]
就是生成的key 密码都是随机的吗？

**Comment by hwdsl2** [comment]
@samz406 Yes, if not specified by the user, the IPsec PSK and VPN password are both randomly generated from a set of characters. For details, see [1].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/vpnsetup.sh#L109-L111
