### ISSUE TITLE
Unable to connect to IPSEC vpn through IPv6 network

### ISSUE THREAD

**Issue by prasanna-patil** [hwdsl2/setup-ipsec-vpn#168]
Hello !!
I am trying to configure a VPN server on an Amazon ec2 instance(ubuntu 14.0.4) which should support IPv4 and IPv6 connections. From IPv4 network I am able to establish a VPN connection, but from IPv6 I dont even see any log in auth.log or syslog.

First I used the Amazon IPv6 ipaddress, but it didnt work. So I changed it to tunnel broker IPv6 but still the result is same.

My IPv6 config is as below:-

conn ipv6
  connaddrfamily="ipv6"
  authby=secret
  pfs=no
  cisco-unity=yes
  auto=add
  left=2001:470:a:x::x
  right="%any"
  rightaddresspool=172.16.5.2-172.16.5.250
  modecfgdns1=172.16.0.2
  modecfgdomain=vpn.mydomain.com
  leftxauthserver=yes
  rightxauthclient=yes
  leftmodecfgserver=yes
  rightmodecfgclient=yes
  modecfgpull=yes
  xauthby=file
  ike-frag=yes
  ikev2=never
  also=shared
  mark=%unique

Following are the logs after restarting ipsec service:-
Jul 10 11:13:06 vpnserver pluto[10175]: | setup callback for interface lo:500 fd 22
Jul 10 11:13:06 vpnserver pluto[10175]: | setup callback for interface eth0:500 fd 21
Jul 10 11:13:06 vpnserver pluto[10175]: | setup callback for interface sit0:500 fd 20
Jul 10 11:13:06 vpnserver pluto[10175]: | setup callback for interface sit1:500 fd 19
Jul 10 11:13:06 vpnserver pluto[10175]: | setup callback for interface sit0:500 fd 18
Jul 10 11:13:06 vpnserver pluto[10175]: | setup callback for interface lo:4500 fd 17
Jul 10 11:13:06 vpnserver pluto[10175]: | setup callback for interface lo:500 fd 16
Jul 10 11:13:06 vpnserver pluto[10175]: | setup callback for interface eth0:4500 fd 15
Jul 10 11:13:06 vpnserver pluto[10175]: | setup callback for interface eth0:500 fd 14
Jul 10 11:13:06 vpnserver pluto[10175]: loading secrets from "/etc/ipsec.secrets"

Where eth0 and sit1 both are having IPv6 ip addresses.

Can you please suggest what changes are required for the server to accept ipv6 connections??

Regards,
Prasanna

**Comment by hwdsl2** [comment]
@prasanna-patil Hello! Unfortunately IPv6 is not supported at this time. An alternative that you can try is Nyr's OpenVPN script [1]. Read his notes [2] on how to enable IPv6 (requires a routable /64 on your server).

[1] https://github.com/Nyr/openvpn-install
[2] https://www.lowendtalk.com/discussion/62645/any-openvpn-auto-installer-script-that-support-ipv6
