### ISSUE TITLE
why enable PPP 

### ISSUE THREAD

**Issue by leslie-wang** [hwdsl2/setup-ipsec-vpn#169]
Thanks for the wonderful work!

Seems like PPP is also installed, and configured in iptable rules. Just wonder why? seems like xl2tpd is the minimum requirement.

**Comment by hwdsl2** [comment]
@leslie-wang Hello! xl2tpd requires PPP to work. PPP is the Point-to-Point Protocol daemon which is used to manage network connections between two nodes on Linux.
