### ISSUE TITLE
Thegreenbow VPN client

### ISSUE THREAD

**Issue by eddyc05** [hwdsl2/setup-ipsec-vpn#171]
Does anyone have any idea how to get thegreenbow vpn client to work with IPsec/XAuth. Keep getting p1 algorithm mismatch

**Comment by eddyc05** [comment]
Jul 16 15:08:19 vultr pluto[13364]: "l2tp-psk"[4] XXX.XXX.XXX.XXX #64: responding to Main Mode from unknown peer XXX.XXX.XXX.XXX
Jul 16 15:08:19 vultr pluto[13364]: "l2tp-psk"[4] XXX.XXX.XXX.XXX #64: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Jul 16 15:08:19 vultr pluto[13364]: "l2tp-psk"[4] XXX.XXX.XXX.XXX #64: no acceptable Oakley Transform
Jul 16 15:08:19 vultr pluto[13364]: "l2tp-psk"[4] XXX.XXX.XXX.XXX #64: sending notification NO_PROPOSAL_CHOSEN to XXX.XXX.XXX.XXX:500
Jul 16 15:08:19 vultr pluto[13364]: "l2tp-psk"[4] XXX.XXX.XXX.XXX #64: deleting state (STATE_MAIN_R0)
Jul 16 15:15:24 vultr pluto[13364]: "l2tp-psk"[4] XXX.XXX.XXX.XXX #65: responding to Main Mode from unknown peer XXX.XXX.XXX.XXX
Jul 16 15:15:24 vultr pluto[13364]: "l2tp-psk"[4] XXX.XXX.XXX.XXX #65: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Jul 16 15:15:24 vultr pluto[13364]: "l2tp-psk"[4] XXX.XXX.XXX.XXX #65: no acceptable Oakley Transform
Jul 16 15:15:24 vultr pluto[13364]: "l2tp-psk"[4] XXX.XXX.XXX.XXX #65: sending notification NO_PROPOSAL_CHOSEN to XXX.XXX.XXX.XXX:500
Jul 16 15:15:24 vultr pluto[13364]: "l2tp-psk"[4] XXX.XXX.XXX.XXX #65: deleting state (STATE_MAIN_R0)

**Comment by hwdsl2** [comment]
@eddyc05 This error may occur when you first connect a VPN client using IPsec/L2TP mode, then connect another one using IPsec/XAuth mode. Try restarting services on the VPN server using commands below. Then re-connect your VPN client.

```
sudo service ipsec restart
sudo service xl2tpd restart
```
