### ISSUE TITLE
提示连接不上

### ISSUE THREAD

**Issue by forgotmymilk** [hwdsl2/setup-ipsec-vpn#172]
![2017-07-19_16-28-49](https://user-images.githubusercontent.com/5485053/28357930-920e0d1c-6c9f-11e7-9bb7-5c49757c26f8.png)

**Comment by hwdsl2** [comment]
@forgotmymilk Please follow the troubleshooting steps at:   
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting
