### ISSUE TITLE
服务器在内网，需要如何配置

### ISSUE THREAD

**Issue by klzsysy** [hwdsl2/setup-ipsec-vpn#173]
除了在前端防火墙开放udp 500， 4500还需要做哪些配置？
我看到程序只监听网卡ip，
并不是
0.0.0.0:500
0.0.0.0:4500

理论上应该是支持的，比如cisco的SAS系防火墙有个叫T-NAT的功能，可以支持内网穿透。

**Comment by hwdsl2** [comment]
@klzsysy 你好！Libreswan 默认监听服务器上的所有 IP 的 UDP 500 和 4500 端口。如果你的前端防火墙开放这两个端口并将它们转发到服务器，则应该可以正常连接。

**Comment by klzsysy** [comment]
@hwdsl2 thanks，已配置成功
