### ISSUE TITLE
Multiple connection error

### ISSUE THREAD

**Issue by adrian09h** [hwdsl2/setup-ipsec-vpn#174]
@hwdsl2  Thanks for your good work.
I've configured IPsec VPN server on Cent OS 7.
I am trying to connection multiple devices under a same wifi router.
I've followed this. https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md and Important notes on https://github.com/hwdsl2/setup-ipsec-vpn.
I've configured Shrew Client on windows 8.1, iOS and Android.
I can connect a Windows device and an iOS device simultaneously.
But when I try to connect on two Windows devices, it's not working.
As soon as I've connected from a new Windows device, other windows device connection still show "Connected" status, but no internet connection.

As well, I cannot connect on an Android device, it shows vpn connected notification icon, but I cannot browse internet. It shows "You are offline. NDS_PROBE_FINISHED_NO_INTERNET", I am using Samsung Galaxy S6 edge +.

**Comment by hwdsl2** [comment]
@adrian09h Hello! The multiple Windows devices behind the same NAT could be a known issue, as Windows devices will try to use the same outgoing ports (UDP 500 and 4500) on the router, which could cause a conflict.

Does your Android device works when it is the only VPN client connected to the server? Please first check that. Also, try restarting services on the VPN server:

```
sudo service ipsec restart
sudo service xl2tpd restart
```

Regarding Android

**Comment by Ejz** [comment]
try `encapsulation=yes` in your config.

**Comment by adrian09h** [comment]
Thanks for your replies @hwdsl2 , @Ejz 
I've installed Libreswan 3.20 and encapsulation = yes is also included in config, but I cannot have a valid Internet access thru xauth in Android running on Android 7.0

**Comment by hwdsl2** [comment]
@adrian09h Can you try the troubleshooting steps mentioned in my previous
reply?
