### ISSUE TITLE
Can password be not salted and hashed for IPsec/XAuth ("Cisco IPsec")?

### ISSUE THREAD

**Issue by leonguyen52** [hwdsl2/setup-ipsec-vpn#175]
I want to ask that can I config to use the raw password as IPsec/L2TP?

Thank you so much for your script.

**Comment by hwdsl2** [comment]
@leonguyen52 No, AFAIK, according to Libreswan docs [1], passwords must be salted and hashed for IPsec/XAuth ("Cisco IPsec").

[1] https://libreswan.org/wiki/Configuration_examples
