### ISSUE TITLE
增加新用户后，无法用新用户登陆

### ISSUE THREAD

**Issue by ideacco** [hwdsl2/setup-ipsec-vpn#176]
使用您的一键安装工具，在 vultr 服务器（ CentOS 7 x64 ）成功架设了。
使用初始密码和账号手机（ ios ）测试没毛病，连接很顺畅。

问题是，我想增加几个新用户的时候，再用新用户连接的时候，手机却提示 ‘与 VPN 的服务协议失败’。
可是我除了修改了用户列表之外没有修改其他地方，难道是我写法不正确么？

**Comment by ideacco** [comment]
我又试了一下，发现一个奇怪的问题，就是iphone 的列表里面不能有两个IPSec VPN 配置，否则哪怕另外一个不连接，第二个IPSec的也无法使用。

**Comment by bh105401** [comment]
新增用户后是不是没有重启服务

**Comment by ideacco** [comment]
重启了，后来发现是iphone设置本身限制了这个列表里面IPSec的设置，比如列表里面有两个不同帐号但是连接同一个服务器的时候，必须删掉一个，另一个才能连接。不知道是不是IOS的BUG。
