### ISSUE TITLE
如何启动重启之类的呢

### ISSUE THREAD

**Issue by tisfeng** [hwdsl2/setup-ipsec-vpn#177]

**Comment by hwdsl2** [comment]
@tisfeng Please try:

```
sudo service ipsec restart
sudo service xl2tpd restart
```

**Comment by tisfeng** [comment]
哦好的，谢谢

**Comment by tisfeng** [comment]
请问一下，有时候网络不稳定，IPSec甚至会自动断开连接是什么原因呢

vps是Ubuntu 16.04，在Mac，iOS都出现过好几次一会自动断开的现象

**Comment by tisfeng** [comment]
![image](https://user-images.githubusercontent.com/25194972/28932618-bfd35694-78ac-11e7-8bc5-f0a042af379c.png)

刚这一会儿出现了两次。。

**Comment by hwdsl2** [comment]
@tisfeng 如果网络不稳定，请尝试其它的 VPS 服务提供商。另外你也可以试一下 Shadowsocks.

**Comment by fhrl94** [comment]
这个可以添加到说明中, 重启后不会重新启动服务
