### ISSUE TITLE
在linux的下IPsec 连接失败

### ISSUE THREAD

**Issue by Rehtt** [hwdsl2/setup-ipsec-vpn#178]
`establishing connection 'myvpn' failed`

**Comment by hwdsl2** [comment]
@Rehtt Please note that the built-in IPsec/L2TP client in some popular Linux distributions has bugs that prevents a successful VPN connection. For IPsec/L2TP mode, you must follow the instructions in [1]. Alternatively, see #152 for how to use "vpnc" to connect via IPsec/XAuth mode. 

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#linux

**Comment by Rehtt** [comment]
我按照教程操作但在`route add YOUR_VPN_SERVER_IP gw `这一部出现了错误：`YOUR_VPN_SERVER_IP: 未知的主机`

**Comment by hwdsl2** [comment]
@Rehtt 你需要将 YOUR_VPN_SERVER_IP 替换成你的 VPN 服务器的 IP 地址。
