### ISSUE TITLE
Can this work on Windows/Android/iPhone at same time

### ISSUE THREAD

**Issue by sudanking** [hwdsl2/setup-ipsec-vpn#18]
Can this work on Windows/Android/iPhone at same time?
it is work for me in Android and iPhone.... but not in windows 10.... any idea?

**Comment by hwdsl2** [comment]
@sudanking What error(s) did you see? If it is `Error 628`, go to the "Security" tab [1] of VPN connection properties, enable `CHAP` and disable `MS-CHAP v2`.

Also, please note that multiple devices behind the same NAT (e.g. home router) cannot connect to the VPN simultaneously due to a limitation [2]. Try connecting only one device at a time.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/issues/7#issuecomment-210084875
[2] https://github.com/hwdsl2/setup-ipsec-vpn/issues/9

**Comment by sudanking** [comment]
this what I get in event viewer:
The user XXXXXXXX dialed a connection named XXXXXXX which has failed. The error code returned on failure is 809.

I use single connection from one place to server.

**Comment by hwdsl2** [comment]
@sudanking As explained in important notes [1], to avoid `Error 809` please add the following registry key and reboot your Windows 10 computer [2]. 

 -  Client behind NAT devices
    Solution: Modern Windows devices do not support L2TP/IPsec connections when the Windows computer or VPN server are located behind a NAT. If the Windows VPN client fails with Error 809 when trying to establish a VPN connection to an MX located behind a NAT, add the "AssumeUDPEncapsulationContextOnSendRule" DWORD value to the Windows registry. This DWORD value allows Windows to establish security associations when both the VPN server and the Windows based VPN client computer are behind NAT devices.
 
    For Windows Vista, 7, 8, 10, and 2008 Server:

    HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PolicyAgent 

    RegValue: AssumeUDPEncapsulationContextOnSendRule

    Type: DWORD

    Data Value: 2

    Note that after creating this key you will need to reboot the machine.

In case that you also see `Error 628`, refer to my previous comment.

[1] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes
[2] https://documentation.meraki.com/MX-Z/Client_VPN/Troubleshooting_Client_VPN#Windows_Error_809

**Comment by hwdsl2** [comment]
@sudanking Closing this issue for now. Please follow instructions in my earlier comment. Feel free to reply if the problem persists.
