### ISSUE TITLE
在执行route add default dev ppp0时总是提示SIOCADDRT: Network is unreachable

### ISSUE THREAD

**Issue by Rehtt** [hwdsl2/setup-ipsec-vpn#180]

**Comment by hwdsl2** [comment]
Did you replace the placeholder IP address with its corresponding actual
values? Please share details of the complete command you ran.

**Comment by Rehtt** [comment]
#!/bin/sh
mkdir -p /var/run/xl2tpd; 
touch /var/run/xl2tpd/l2tp-control;
service strongswan restart;
service xl2tpd restart;
ipsec up myvpn;
echo "c myvpn" > /var/run/xl2tpd/l2tp-control;
echo "完成第一步";
read -p "继续" var
IP=`wget -qO- http://ipv4.icanhazip.com;`;
route add 服务器ip gw 192.168.0.171;
route add $IP gw 192.168.0.171;
read -p "继续" var
route add default dev ppp0;

**Comment by hwdsl2** [comment]
@Rehtt The syntax of your shell script is not correct. Fix it and try again:

1. Remove all `;` at the end of each line.
2. Replace `服务器ip` with the actual IP address of your VPN server.
3. Save the script, then check its syntax before running, with `bash -n scriptname`.

**Comment by Rehtt** [comment]
我执行完ipsec up myvpn后没有看见ppp0接口

**Comment by Rehtt** [comment]
好了，我想应该是家里网络原因。不过还是感谢你的解答。
