### ISSUE TITLE
Error: 'yum install' failed.

### ISSUE THREAD

**Issue by clacki** [hwdsl2/setup-ipsec-vpn#181]
Hello ,
Give me This Error : (centos 6.9 final 64bit)

Transaction Check Error:
  file /usr/lib64/libkadm5clnt_mit.so.8.0 from install of libkadm5-1.10.3-65.el6.x86_64 conflicts with file from package krb5-libs-1.10.3-33.el6.x86_64
  file /usr/lib64/libkadm5srv_mit.so.8.0 from install of libkadm5-1.10.3-65.el6.x86_64 conflicts with file from package krb5-libs-1.10.3-33.el6.x86_64

Error Summary
-------------

Error: 'yum install' failed.

**Comment by hwdsl2** [comment]
@clacki Try: `rpm -e krb5-libs-1.10.3-33.el6.x86_64`

**Comment by clacki** [comment]
@hwdsl2 Thank You , You're The Best .

Problem Fixed

Have you a script that run cisco vpn automatically like this script in centos ?!

**Comment by hwdsl2** [comment]
@clacki You're welcome. This script already sets up both IPsec/L2TP and Cisco IPsec for CentOS.
