### ISSUE TITLE
Radius Problem

### ISSUE THREAD

**Issue by clacki** [hwdsl2/setup-ipsec-vpn#182]
Hello,

When I will connect your xl2tp script to radius server ,give me this Error : 

Aug 10 21:54:38 localhost pppd[3878]: Plugin pppol2tp.so loaded.
Aug 10 21:54:38 localhost pppd[3878]: Plugin radius.so loaded.
Aug 10 21:54:38 localhost pppd[3878]: RADIUS plugin initialized.
Aug 10 21:54:38 localhost pppd[3878]: Plugin radattr.so loaded.
Aug 10 21:54:38 localhost pppd[3878]: RADATTR plugin initialized.
Aug 10 21:54:38 localhost pppd[3878]: pppd 2.4.5 started by root, uid 0
Aug 10 21:54:38 localhost pppd[3878]: Using interface ppp0
Aug 10 21:54:38 localhost pppd[3878]: Connect: ppp0 <--> 
Aug 10 21:54:41 localhost pppd[3878]: rc_avpair_new: unknown attribute 60
Aug 10 21:54:41 localhost pppd[3878]: rc_avpair_gen: received unknown attribute 85 of length 4: 0x0000003C
Aug 10 21:54:41 localhost pppd[3878]: Peer test failed CHAP authentication
Aug 10 21:54:41 localhost pppd[3878]: Connection terminated.
Aug 10 21:54:41 localhost pppd[3878]: Exit.
Aug 10 21:54:41 localhost xl2tpd[3141]: call_close: Call 38482 to 192.168.11.50 disconnected
Aug 10 21:54:41 localhost xl2tpd[3141]: control_finish: Connection closed to 192.168.11.50, serial 0 ()
Aug 10 21:54:41 localhost xl2tpd[3141]: control_finish: Connection closed to 192.168.11.50, port 1701 (), Local: 6755, Remote: 33

**Comment by hwdsl2** [comment]
@clacki Hello! Connecting to a Radius server is outside the scope of this project. Try asking on the Libreswan or Strongswan mailing lists [1] [2].

[1] https://lists.libreswan.org/mailman/listinfo/swan
[2] https://lists.strongswan.org/mailman/listinfo/users
