### ISSUE TITLE
Cisco AnyConnect

### ISSUE THREAD

**Issue by clacki** [hwdsl2/setup-ipsec-vpn#183]
Hello ,
When I install Your script , I can connect to cisco by my device ?(like ios)
by installing this script cisco anyconnect install in my server ?
please say how can config and edit cisco in your script.

**Comment by hwdsl2** [comment]
@clacki No, this script will neither install nor does it have anything to do with Cisco AnyConnect. That software is for SSL VPN, not IPsec.

The VPN script is intended to set up a VPN server with both IPsec/L2TP and IPsec/XAuth. For client configuration details, see [1]. While the latter is also called Cisco IPsec, it is NOT related to the SSL VPN required by AnyConnect.

[1] https://github.com/hwdsl2/setup-ipsec-vpn#next-steps
