### ISSUE TITLE
ubuntu17.04做为客户端无法通过ipsec协议链接vpn

### ISSUE THREAD

**Issue by hellowords** [hwdsl2/setup-ipsec-vpn#185]
你好 @hwdsl2 
下图是我运行之后的报错信息，网络上找了好多资料都没发现解决办法，
![screenshot from 2017-08-11 21-31-25](https://user-images.githubusercontent.com/13344029/29215196-998c438e-7edc-11e7-9338-b3784c8f241e.png)

**Comment by hwdsl2** [comment]
@hellowords Hello! This error means that your IPsec PSK is incorrect. Please make sure that it exactly matches between the VPN server and client.

**Comment by hellowords** [comment]
感谢回复！  @hwdsl2  [我之前是通过另一位作者的脚本创建的vpn服务器](https://github.com/quericy/one-key-ikev2-vpn)
使用这个脚本ios，mac，windows都能成功链接，但是linux下一直没能成功过。
根据你提供的的linux链接方式，我连接[另一位作者](https://github.com/quericy/one-key-ikev2-vpn)提供的脚本创建的vpn服务器，出现了以上错误，检查之后凭证口令都是填写正确的。
刚刚重新创建了一个vps主机，用您提供的脚本创建了一个vpn服务器，linux可以链接成功了，但是访问不了外网，国内网站可以访问.不清楚是不是防火墙的问题，以下是一些信息图：
![new](https://user-images.githubusercontent.com/13344029/29240593-e44ba036-7f9a-11e7-9e02-df58772af7f2.png)

----
![2](https://user-images.githubusercontent.com/13344029/29240688-f31bd5d4-7f9c-11e7-8228-b766ec2fa4d6.png)
期待您的回复。：）

**Comment by hellowords** [comment]
这个是网卡的设置问题吗？还是`/etc/ipsec.conf`里面的参数设置问题？

----
![6](https://user-images.githubusercontent.com/13344029/29240902-dc5f25ae-7fa0-11e7-9dc2-794258528f55.png)

**Comment by hwdsl2** [comment]
@hellowords 你好！如果国内网站可以访问，但访问不了外网，则很可能是被防火墙屏蔽了。

你可以尝试首先重启你的 Linux 客户端，然后重启 VPN 服务器。最后重新按照 [1] 中的步骤操作。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#linux

**Comment by hellowords** [comment]
好的，感谢回复。
