### ISSUE TITLE
How to generate IPsec PSK

### ISSUE THREAD

**Issue by duythien** [hwdsl2/setup-ipsec-vpn#187]
Hello

Default your script will be create a share key like below:

```
L2TP over IPsec VPN Server:
===========================
IP-Address: 188.226.xxx.xxx
Username: vpnuser
Password: hFVSabf2Q48bL35YWHnhnHC0
IPsec PSK: 6wJWxgjeE7YcnmMV3VtaKw73
```

I want to some Psec PSK like this:

```
Server IP: 35.160.225.xx
IPsec PSK: Kwdrfv5we5A
Username: vpnuser
Password: K0Q8DNVNMcNs2mJDUXYlxmhLvY4vqXXX
```
Which a command line to do that. Thanks

**Comment by hwdsl2** [comment]
@duythien Hello! The command to generate an IPsec PSK can be found at line 109 of the script [1]. You may adjust the parameters as necessary.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/vpnsetup.sh#L109
