### ISSUE TITLE
How to add another ip for multiple ips vps?

### ISSUE THREAD

**Issue by taekubz** [hwdsl2/setup-ipsec-vpn#189]
Hi, I was wondering if it's possible to add another ip for multiple ips vps? And add a specific user for that new ip address?

Thank you.

**Comment by hwdsl2** [comment]
@taekubz Hello! I understand your question but it is outside the scope of this project, because that is not a common use case. Please direct your question(s) to the Libreswan users mailing list [1].

[1] https://lists.libreswan.org/mailman/listinfo/swan
