### ISSUE TITLE
 prcpucfg.h: No such file or directory

### ISSUE THREAD

**Issue by rgagnon** [hwdsl2/setup-ipsec-vpn#19]
Hi,

I'm on ubuntu 12.04 and I'm getting this error.  Any idea?

`In file included from /opt/src/libreswan-3.17/lib/libswan/alg_info.c:34:0:
/opt/src/libreswan-3.17/include/constants.h:107:45: fatal error: prcpucfg.h: No such file or directory
compilation terminated.
make[3]: *** [alg_info.o] Error 1
make[3]: Leaving directory `/opt/src/libreswan-3.17/OBJ.linux.x86_64/lib/libswan'
make[2]: *** [local-base] Error 2
make[2]: Leaving directory `/opt/src/libreswan-3.17/lib/libswan'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/opt/src/libreswan-3.17/lib'
make: *** [all] Error 2
`

**Comment by hwdsl2** [comment]
@rgagnon As a workaround, please edit the VPN script and insert the following just above the `make programs && make install` line:

`sed -i "s/prcpucfg\.h/nspr\/prcpucfg.h/" /opt/src/libreswan-3.17/include/constants.h`

Then re-run the script. Let me know if this fixes the problem.

**Comment by rgagnon** [comment]
It goes a little bit further.

I added this line as well : 

`sed -i "s/pk11pub\.h/nss\/pk11pub.h/" /opt/src/libreswan-3.17/include/lswconf.h`

But now it is complaining about this one : 

`/usr/include/nss/pk11pub.h:6:21: fatal error: plarena.h: No such file or directory`

**Comment by hwdsl2** [comment]
@rgagnon Are you sure that your server is running Ubuntu 12.04? Please post the output of:

`lsb_release -sr`
and
`uname -a`

**Comment by rgagnon** [comment]
I'm far from an expert but I would say yes.  Here is : 

```
lsb_release -sr
12.04
bitnami@ip-10-141-255-56:~$ uname -a
Linux ip-10-141-255-56 3.2.0-58-virtual #88-Ubuntu SMP Tue Dec 3 17:58:13 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by hwdsl2** [comment]
I just tested again on a new Ubuntu 12.04 server and all went fine. Can you please run:

`   apt-get -y update`
`   apt-get -y install libnss3-dev libnspr4-dev pkg-config libpam0g-dev \`
`        libcap-ng-dev libcap-ng-utils libselinux1-dev \`
`        libcurl4-nss-dev flex bison gcc make \`

Do you see any error?

Also post the output of `grep ^[^#] /etc/apt/sources.list`.

**Comment by rgagnon** [comment]
No error, everything was already up to date

here is the grep : 
```
grep ^[^#] /etc/apt/sources.list
deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ precise main
deb-src http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ precise main
deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ precise-updates main
deb-src http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ precise-updates main
deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ precise universe
deb-src http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ precise universe
deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ precise-updates universe
deb-src http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ precise-updates universe
deb http://security.ubuntu.com/ubuntu precise-security main
deb-src http://security.ubuntu.com/ubuntu precise-security main
deb http://security.ubuntu.com/ubuntu precise-security universe
deb-src http://security.ubuntu.com/ubuntu precise-security universe
```

**Comment by hwdsl2** [comment]
May I know which Amazon Machine Image (AMI) did you use to launch the Ubuntu EC2 instance? You can find that info in the instance details after selecting it in the control panel. I will try to look further into this myself.

**Comment by rgagnon** [comment]
I'm sorry,

I think the AMI was deprecated : ami-11fdc978

Is was originally take from bitnami but now they are on 14.04

Please check : 
[https://aws.amazon.com/marketplace/search/results/ref=dtl_navgno_search_box?page=1&searchTerms=Ruby+Stack+powered+by+Bitnami]()

Should I upgrade to 14.04?

**Comment by hwdsl2** [comment]
Yes I would suggest that you upgrade to 14.04 and try again from there. Please keep me updated.

**Comment by hwdsl2** [comment]
@rgagnon I have found the reason that Libreswan failed to compile on your system. It seems that the `PATH` variable set by this particular AMI interferes with the compilation process.

Please use the following workaround (works on both Ubuntu 14.04 and 12.04):

`sudo PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" sh vpnsetup.sh`

Let me know if this resolves your issue.

**Comment by rgagnon** [comment]
Yes it worked!  Thank you.  Now I can try to make my vpn connection to work.

Really appreciated.

**Comment by hwdsl2** [comment]
@rgagnon Great! You are welcome. Feel free to close the issue.
