### ISSUE TITLE
Weird issue, unable to connect to the vpn.

### ISSUE THREAD

**Issue by taekubz** [hwdsl2/setup-ipsec-vpn#190]
I just launched 2 vps servers from different providers, but both come with the same OS, different version, one is Ubuntu 14.04.2 LTS and another one from digital ocean is  Ubuntu 14.04.5 LTS

I have installed vpn on both server, and can only connect to the one from digital ocean, which works fine.

I have checked username and password, key and ip address, they were correct.  Is this the problem with the version of ubuntu?

Thank you.

**Comment by hwdsl2** [comment]
@taekubz The version of Ubuntu (14.04.5 or 14.04.2) should not make any difference. Try reinstalling the VPS that has issues. If still not working, then the issue is with your VPS provider.
