### ISSUE TITLE
使用阿里云香港ECS搭建失败，udp500和udp4500以及tcp1701均已打开，IPSec和L2TP均无法连接

### ISSUE THREAD

**Issue by RoseEnd** [hwdsl2/setup-ipsec-vpn#191]

**Comment by hwdsl2** [comment]
@RoseEnd 你好！请参考下列几个和阿里云有关的 Issue 中的解决方案：
#160 
#146 
#137 
hwdsl2/docker-ipsec-vpn-server#24

**Comment by RoseEnd** [comment]
我又重新跑了一遍iphone是可以了，但是windows还是不行，我也修改了注册表，重启了机器还是不行。系统是win10

**Comment by hwdsl2** [comment]
@RoseEnd 好的。请再次检查并确保注册表更改是正确的，详情参见 [1]，然后重启 VPN 客户端并重试。

另外你也可以尝试使用 IPsec/XAuth 模式 [2] 连接。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#windows-%E9%94%99%E8%AF%AF-809
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth-zh.md#windows

**Comment by xuminzhong** [comment]
@hwdsl2 @RoseEnd 是的，我也遇到Android行但 Windows 不行，最后解决了，是注册表和services的原因。
在 [#160](https://github.com/hwdsl2/setup-ipsec-vpn/issues/160) 有回复。
