### ISSUE TITLE
swan_ver need update

### ISSUE THREAD

**Issue by vcarus** [hwdsl2/setup-ipsec-vpn#192]
in the install script,
swan_ver=3.20

refer to https://github.com/libreswan/libreswan/releases
swan_ver should be 3.21

**Comment by hwdsl2** [comment]
@vcarus Libreswan 3.21 was released a few days ago. It may require new dependencies (such as libldns-dev) which I have not yet had time to test. For now, please stay on the Libreswan 3.20 version and do not upgrade to 3.21.

**Comment by vcarus** [comment]
I just upgrade system to Ubuntu 17.10 dev.

Libreswan 3.21 works well. All dependencies can be simply installed by apt.

**Comment by hwdsl2** [comment]
Thanks for letting us know!
