### ISSUE TITLE
[enhancement] replace xl2tpd to ACCEL-PPP for better performance

### ISSUE THREAD

**Issue by vcarus** [hwdsl2/setup-ipsec-vpn#193]
Homepage: http://accel-ppp.org

Some test by zhensheng: https://zhensheng.im/2017/08/15/3029

**Comment by hwdsl2** [comment]
@vcarus Thank you for the suggestion. But ACCEL-PPP is outside the scope of this project. With that said, you are welcome to fork this repo and make enhancements for your needs.
