### ISSUE TITLE
vpn客户端还是上不了网

### ISSUE THREAD

**Issue by Rehtt** [hwdsl2/setup-ipsec-vpn#195]
服务器地址与密码都正确，android与windowns都正常，唯独linux失败。linux的vpn状态：
![2017-08-19 11-51-19](https://user-images.githubusercontent.com/28680927/29483316-1c5b959a-84d6-11e7-8c62-9246deaf522e.png)

**Comment by hwdsl2** [comment]
@Rehtt Run `ifconfig` and see if you have the interface `ppp0`.

Your IPsec connection is successfully established. The problem could be with your L2TP connection and/or IP routes. Try:

1. Restart services on your VPN server:
```
sudo service ipsec restart
sudo service xl2tpd restart
```

2. Browse to the Linux docs [1]. On your VPN client, perform ALL steps after this line:   
`Note: You must repeat all steps below every time you try to connect to the VPN.`   

Please post any error message you received while following these steps.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#linux

**Comment by Rehtt** [comment]
还是不行啊_(:з」∠)_

**Comment by hwdsl2** [comment]
@Rehtt I just re-tested the Linux instructions in [1] and was able to successfully establish a VPN connection using Ubuntu 16.04 as a client.

As this is not an issue with the VPN script itself, let's take the conversation elsewhere (e.g. email). Please refrain from opening more issues, in consideration of the ~200 people watching this repo.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#linux
