### ISSUE TITLE
照着脚本安装成功了 但始终连不上

### ISSUE THREAD

**Issue by shen-xianpeng** [hwdsl2/setup-ipsec-vpn#197]
显示vpn服务器没有响应

哪里可以查看log， 看看我是哪里出错了。  求指导！

系统：
Linux 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

(env) [root@~]# virt-what 
kvm

**Comment by hwdsl2** [comment]
@shen-xianpeng To check the Libreswan (IPsec) log for errors:

# Ubuntu & Debian
grep pluto /var/log/auth.log
# CentOS & RHEL
grep pluto /var/log/secure

**Comment by shen-xianpeng** [comment]
Thanks!
