### ISSUE TITLE
setsockopt recvref[30]: Protocol not available

### ISSUE THREAD

**Issue by NiranjanKumarJakka** [hwdsl2/setup-ipsec-vpn#198]
hello, 
i have installed in google cloud i got this error setsockopt recvref[30]: Protocol not available.
What is the solutions please help me

**Comment by hwdsl2** [comment]
@NiranjanKumarJakka Hello! This message: `xl2tpd[1]: setsockopt recvref[30]: Protocol not available` is normal and expected. The VPN should work fine. Try connecting using your VPN client.
