### ISSUE TITLE
How to renumber?

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [hwdsl2/setup-ipsec-vpn#199]
What is the difference between 192.168.42.0/24 and 192.168.43.0/24? I would like to assign a different IP space to VPN clients.

How can I assign clients an IP space that does not get NAT'ed?

It would be nice to have a easier way to renumber.

**Comment by hwdsl2** [comment]
@kjeojfeofjgeofkjodfioejo Hello! 192.168.42.0/24 is the subnet for
IPsec/L2TP VPN clients, while 192.168.43.0/24 is the subnet for IPsec/XAuth
VPN clients. To change those, just modify the corresponding variables in
the VPN script before running.

It is not supported to assign clients an IP space that is not NAT'ed. You
must use RFC1918 IP space.
