### ISSUE TITLE
Does your script can help to connect to a meraki?

### ISSUE THREAD

**Issue by rgagnon** [hwdsl2/setup-ipsec-vpn#20]
Hi,

I'm far from a expert in networking/vpn. 

I need to connect my EC2 on a meraki router thru a vpn.

Does your script can help me to figure this out?

thank you

**Comment by hwdsl2** [comment]
Sorry I am not familiar with meraki routers. Perhaps these results from Google can help? I am closing this issue for now, but feel free to comment if needed.

https://www.google.com/search?q=meraki+router+ec2+vpn
