### ISSUE TITLE
ubuntu上工作正常，centos7上出现error789？

### ISSUE THREAD

**Issue by deng47** [hwdsl2/setup-ipsec-vpn#200]
在aws ec2的ubuntu上部署后，vpn一切正常，非常方便
然后在google compute engine的centos7上部署时，我直接使用aws ec2上的IPsec PSK、Username和Password，结果连接时出现error789
<img width="327" alt="789" src="https://user-images.githubusercontent.com/17677938/29589143-eb631042-8748-11e7-80f5-798de18ef5eb.png">

用ipsec verify查看似乎一切正常
<img width="505" alt="status" src="https://user-images.githubusercontent.com/17677938/29589049-9e04a004-8748-11e7-8e36-9cff24f91851.png">

我用的是win7，配置好一个客户端后连接aws的服务器正常，然后把同一个vpn客户端的主机名改为google compute engine上的主机名就出现789错误了
<img width="280" alt="vpn" src="https://user-images.githubusercontent.com/17677938/29589196-341fd31a-8749-11e7-9a7a-d061451f8d18.png">

请问是我哪里搞错了？

**Comment by hwdsl2** [comment]
@deng47 你好！关于 789 错误：根据你所说的，原因有可能是:

1. （最有可能）没有在 Google Compute Engine 的防火墙上打开 UDP 500 和 4500 端口。参考链接 [1].
2. 客户端和服务器上的 IPsec PSK 不一致。
3. GCE 的连接被”防火墙“屏蔽了...

更多故障排除信息请看 [2] [3].

另外可以查看一下 GCE 服务器上的 VPN 日志，使用以下命令：

```
# Ubuntu & Debian
grep pluto /var/log/auth.log
grep xl2tpd /var/log/syslog

# CentOS & RHEL
grep pluto /var/log/secure
grep xl2tpd /var/log/messages
```

[1] https://cloud.google.com/compute/docs/vpc/firewalls
[2] https://documentation.meraki.com/MX-Z/Client_VPN/Troubleshooting_Client_VPN#Windows_Error_789
[3] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps

**Comment by deng47** [comment]
的确是防火墙的问题，打开两个端口以后就运作正常了
非常感谢
