### ISSUE TITLE
client connection log

### ISSUE THREAD

**Issue by davisbra** [hwdsl2/setup-ipsec-vpn#201]
How to find client (user) log?
how many concurrent user with same username can connect?
system requirement for 500 concurrent user?
thank you

**Comment by wangkaichimera** [comment]
cat /var/log/auth.log in ubuntu

**Comment by hwdsl2** [comment]
@davisbra Similar to @wangkaichimera mentioned, to check the connection logs, please try:

```
# Ubuntu & Debian
grep pluto /var/log/auth.log
grep xl2tpd /var/log/syslog

# CentOS & RHEL
grep pluto /var/log/secure
grep xl2tpd /var/log/messages
```

Regarding your other questions, there is not any set limit on those, as it depends on your system resources (CPU, RAM size, network, etc.) For more details, try asking on the Libreswan mailing list [1].

[1] https://lists.libreswan.org/mailman/listinfo/swan

**Comment by davisbra** [comment]
thanks for your answer
but i need to see log of visited website
for example i want to know that client1(with ip:x.x.x.x) visite  facebook.com(facebook ip=x.x.x.x)
where cat I found this log?or how can I log in this way?

**Comment by hwdsl2** [comment]
@davisbra Unfortunately what you described is not possible with the Libreswan logs. And I am not aware of any method to achieve that. It is outside the scope of this project.
