### ISSUE TITLE
open ssl password incorrect

### ISSUE THREAD

**Issue by hklkf** [hwdsl2/setup-ipsec-vpn#203]
run openssl passwd -1 'your_vpn_password_1'  , i got the new password but didn't match cisco user password,how to fix it???

**Comment by hwdsl2** [comment]
@hklkf Replace 'your_vpn_password_1' in the command you mentioned with your
actual Cisco user password. The output will give you the salted and hashed
password for use in the /etc/ipsec.d/passwd file.

**Comment by hklkf** [comment]
hi hwdsl2

i tired to gen the password,i input same password but the key not match

ACC1 is running setup.sh key
ACC2 is a new openssl key

ACC1:$1$fhTETZkx$w7T8Nmt0c6deJAv9bwM/X1:xauth-psk
ACC2:$1$Kl.k2oQu$OgFsm8N/XHWjzCqsZicMA0/X1:xauth-psk

**Comment by hwdsl2** [comment]
@hklhf This is normal because a different salt is used to hash the password
each time this command is run, hence a different output. Use the generated
results, it should work fine.

**Comment by hklkf** [comment]
@hwdsl2 still not work too,can you connect my teamviewer ,i show you the problem

**Comment by hwdsl2** [comment]
@hklkf Sorry, I can't help you on teamviewer. Try explaining the problem
further in this issue. I'll look at it later this week.

**Comment by hklkf** [comment]
@hwdsl2 

ok,thank you so much
