### ISSUE TITLE
 Whether you can add user authentication and flow control？

### ISSUE THREAD

**Issue by xyzs996** [hwdsl2/setup-ipsec-vpn#204]
This item is very good，
Whether you can add user authentication and flow control

**Comment by hwdsl2** [comment]
@xyzs996 Not sure what you are asking. If you wish to add, edit or remove VPN user accounts, see Manage VPN Users [1]. Per-user bandwidth quotas are outside the scope of this project.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users.md
