### ISSUE TITLE
I failed，OpenSSL：error，HELP

### ISSUE THREAD

**Issue by qqppwskj** [hwdsl2/setup-ipsec-vpn#205]
login as: root
root@104.148.70.68's password:
Last login: Tue Sep  5 22:32:51 2017 from 61.153.148.193
[root@nnod85ko ~]# wget https://git.io/vpnsetup-centos.sh && sudo sh vpnsetup.sh
--2017-09-05 22:39:53--  https://git.io/vpnsetup-centos.sh
正在解析主机 git.io... 50.19.219.240, 50.19.245.69, 50.16.248.61, ...
正在连接 git.io|50.19.219.240|:443... 已连接。
OpenSSL: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error
无法建立 SSL 连接。

**Comment by hwdsl2** [comment]
@qqppwskj Try using curl instead:

yum -y install curl
curl -LO https://git.io/vpnsetup-centos
mv vpnsetup-centos vpnsetup.sh
sudo sh vpnsetup.sh

**Comment by qqppwskj** [comment]
Thank you very much.
