### ISSUE TITLE
PC can't connect

### ISSUE THREAD

**Issue by kevinwangkk** [hwdsl2/setup-ipsec-vpn#206]
the Phone can connet  , but the win10 and win7 cann't connet

**Comment by kevinwangkk** [comment]
AssumeUDPEn...  = 2     
but  PC can't connect

**Comment by hwdsl2** [comment]
@kevinwangkk Double check that you've added the correct registry key [1].
You must reboot your PC after modifying the key.

[1]
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#windows-error-809
