### ISSUE TITLE
How to add the account?

### ISSUE THREAD

**Issue by TedKuo0212** [hwdsl2/setup-ipsec-vpn#208]
Dear Sir,

Thanks for your sharing, and it work normally in my server, could you tell me how to add other accounts for my friend？

**Comment by dehbini** [comment]
@TedKuo0212 you can read this tutorial for managing users(add, remove or edit account) https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users.md

**Comment by hwdsl2** [comment]
@TedKuo0212 Please refer to the document @dehbini mentioned. Thanks!
