### ISSUE TITLE
PPTP vpn is broken after installing l2tp ipsec.

### ISSUE THREAD

**Issue by taekubz** [hwdsl2/setup-ipsec-vpn#209]
Hello, I have been using l2tp ipsec for a while and it works flawlessly.

Few days ago, I just rent a new vps and install pptp vpn on the server using this script

https://github.com/MdNor/digital-ocean-pptp-vpn

but after installing L2TP/IPSEC. The PPTP vpn is no longer working.

How do I solve this problem?

Thank you.

**Comment by hwdsl2** [comment]
@taekubz To fix this issue, please try these commands:

```
iptables -I FORWARD 2 -i eth0 -d 10.1.0.0/24 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
iptables -I FORWARD 3 -s 10.1.0.0/24 -o eth0 -j ACCEPT
```

To make sure that this change persist across reboots, add the above two lines to your `/etc/rc.local` at the end but before any "exit 0" line.
