### ISSUE TITLE
Win10 连接问题

### ISSUE THREAD

**Issue by HyramTang** [hwdsl2/setup-ipsec-vpn#218]
Win10，修改好注册表、选中了质询握手身份验证协议，添加了高级设置中的key，连接时还是出现：**不能建立到远程计算机的连接。你可能需要更改此连接的网络设置**

iPhone上IOS10.3系统配置VPN后可连接

劳烦帮忙解惑下，谢谢！

**Comment by wshinibaba** [comment]
检查服务是否开启，注册表有个值为要为0，请参考readme中更多错误的第三个tplink的链接

**Comment by HyramTang** [comment]
@wshinibaba 尝试了还是不行噢，确定服务都开启了，注册表也添加了，还是同样错误。

**Comment by hwdsl2** [comment]
@HyramTang 你好！这个是你的 Windows 系统本身的问题，不是服务器的原因。请自行在搜索引擎搜索 "不能建立到远程计算机的连接，你可能需要更改此连接的网络设置"。以下的几个搜索结果可供参考。

[1] http://www.vpnest.cc/1546.html
[2] http://blog.initm.com/netkeeper-720/
[3] http://www.w10zj.com/Win10xy/Win10xf_2927.html

**Comment by ECer23** [comment]
@HyramTang 请问你的问题解决了吗？我也遇到同样的问题

**Comment by HyramTang** [comment]
没有哦，上文的方案都试了，应该是自己网络的问题，后来换其它方案了[shadowsocks-install](https://github.com/iMeiji/shadowsocks_install)，可以参考下，不过还是非常感谢这个项目:smile:！

**Comment by RayLee3306** [comment]
windows 10很奇葩，我也遇到过这问题。我的解决方案是，打开 设备管理器->网络适配器，卸载掉所有以WAN-开头的设备，然后再重新“扫描检测硬件改动”重新安装上去即可正常。
