### ISSUE TITLE
服务器一重启就连不上，好像只能重装ipsec

### ISSUE THREAD

**Issue by jkingben** [hwdsl2/setup-ipsec-vpn#220]
重装ipsec后一直很正常，但只要重启了服务器，就变成如图这样，一直就连不上了，只能删了再次重装，这是为什么？
![image](https://user-images.githubusercontent.com/5220242/30784049-1c4a2cf8-a180-11e7-94a4-826057b078b7.png)

一直在循环这3条错误信息

**Comment by jkingben** [comment]
iptables没动过，用的是路由器连接，下面是auth.log的输出

root@taiwan-a:~# grep pluto /var/log/auth.log
Sep 24 23:47:04 taiwan-a pluto[2559]: NSS DB directory: sql:/etc/ipsec.d
Sep 24 23:47:04 taiwan-a pluto[2559]: Initializing NSS
Sep 24 23:47:04 taiwan-a pluto[2559]: Opening NSS database "sql:/etc/ipsec.d" read-only
Sep 24 23:47:04 taiwan-a pluto[2559]: NSS initialized
Sep 24 23:47:04 taiwan-a pluto[2559]: NSS crypto library initialized
Sep 24 23:47:04 taiwan-a pluto[2559]: FIPS HMAC integrity support [disabled]
Sep 24 23:47:04 taiwan-a pluto[2559]: libcap-ng support [enabled]
Sep 24 23:47:04 taiwan-a pluto[2559]: Linux audit support [disabled]
Sep 24 23:47:04 taiwan-a pluto[2559]: Starting Pluto (Libreswan Version 3.21 XFRM(netkey) KLIPS FORK PTHREAD_SETSCHEDPRIO NSS SYSTEMD_WATCHDOG LIBCAP_NG XAUTH_PAM NETWORKMANAGER CURL(non-NSS)) pid:2559
Sep 24 23:47:04 taiwan-a pluto[2559]: core dump dir: /var/run/pluto
Sep 24 23:47:04 taiwan-a pluto[2559]: secrets file: /etc/ipsec.secrets
Sep 24 23:47:04 taiwan-a pluto[2559]: leak-detective enabled
Sep 24 23:47:04 taiwan-a pluto[2559]: NSS crypto [enabled]
Sep 24 23:47:04 taiwan-a pluto[2559]: XAUTH PAM support [enabled]
Sep 24 23:47:04 taiwan-a pluto[2559]: NAT-Traversal support  [enabled]
Sep 24 23:47:04 taiwan-a pluto[2559]: Initializing libevent in pthreads mode: headers: 2.0.21-stable (2001500); library: 2.0.21-stable (2001500)
Sep 24 23:47:04 taiwan-a pluto[2559]: Encryption algorithms:
Sep 24 23:47:04 taiwan-a pluto[2559]:   AES_CCM_16         IKEv1:     ESP     IKEv2:     ESP     FIPS  {256,192,*128}  (aes_ccm aes_ccm_c)
Sep 24 23:47:04 taiwan-a pluto[2559]:   AES_CCM_12         IKEv1:     ESP     IKEv2:     ESP     FIPS  {256,192,*128}  (aes_ccm_b)
Sep 24 23:47:04 taiwan-a pluto[2559]:   AES_CCM_8          IKEv1:     ESP     IKEv2:     ESP     FIPS  {256,192,*128}  (aes_ccm_a)
Sep 24 23:47:04 taiwan-a pluto[2559]:   3DES_CBC           IKEv1: IKE ESP     IKEv2: IKE ESP     FIPS  [*192]  (3des)
Sep 24 23:47:04 taiwan-a pluto[2559]:   CAMELLIA_CTR       IKEv1:     ESP     IKEv2:     ESP           {256,192,*128}
Sep 24 23:47:04 taiwan-a pluto[2559]:   CAMELLIA_CBC       IKEv1: IKE ESP     IKEv2: IKE ESP           {256,192,*128}  (camellia)
Sep 24 23:47:04 taiwan-a pluto[2559]:   AES_GCM_16         IKEv1: IKE ESP     IKEv2: IKE ESP     FIPS  {256,192,*128}  (aes_gcm aes_gcm_c)
Sep 24 23:47:04 taiwan-a pluto[2559]:   AES_GCM_12         IKEv1: IKE ESP     IKEv2: IKE ESP     FIPS  {256,192,*128}  (aes_gcm_b)
Sep 24 23:47:04 taiwan-a pluto[2559]:   AES_GCM_8          IKEv1: IKE ESP     IKEv2: IKE ESP     FIPS  {256,192,*128}  (aes_gcm_a)
Sep 24 23:47:04 taiwan-a pluto[2559]:   AES_CTR            IKEv1: IKE ESP     IKEv2: IKE ESP     FIPS  {256,192,*128}  (aesctr)
Sep 24 23:47:04 taiwan-a pluto[2559]:   AES_CBC            IKEv1: IKE ESP     IKEv2: IKE ESP     FIPS  {256,192,*128}  (aes)
Sep 24 23:47:04 taiwan-a pluto[2559]:   SERPENT_CBC        IKEv1: IKE ESP     IKEv2: IKE ESP           {256,192,*128}  (serpent)
Sep 24 23:47:04 taiwan-a pluto[2559]:   TWOFISH_CBC        IKEv1: IKE ESP     IKEv2: IKE ESP           {256,192,*128}  (twofish)
Sep 24 23:47:04 taiwan-a pluto[2559]:   TWOFISH_SSH        IKEv1: IKE         IKEv2: IKE ESP           {256,192,*128}  (twofish_cbc_ssh)
Sep 24 23:47:04 taiwan-a pluto[2559]:   CAST_CBC           IKEv1:     ESP     IKEv2:     ESP           {*128}  (cast)
Sep 24 23:47:04 taiwan-a pluto[2559]:   NULL               IKEv1:     ESP     IKEv2:     ESP           []
Sep 24 23:47:04 taiwan-a pluto[2559]: Hash algorithms:
Sep 24 23:47:04 taiwan-a pluto[2559]:   MD5                IKEv1: IKE         IKEv2:
Sep 24 23:47:04 taiwan-a pluto[2559]:   SHA1               IKEv1: IKE         IKEv2:             FIPS  (sha)
Sep 24 23:47:04 taiwan-a pluto[2559]:   SHA2_256           IKEv1: IKE         IKEv2:             FIPS  (sha2 sha256)
Sep 24 23:47:04 taiwan-a pluto[2559]:   SHA2_384           IKEv1: IKE         IKEv2:             FIPS  (sha384)
Sep 24 23:47:04 taiwan-a pluto[2559]:   SHA2_512           IKEv1: IKE         IKEv2:             FIPS  (sha512)
Sep 24 23:47:04 taiwan-a pluto[2559]: PRF algorithms:
Sep 24 23:47:04 taiwan-a pluto[2559]:   HMAC_MD5           IKEv1: IKE         IKEv2: IKE               (md5)
Sep 24 23:47:04 taiwan-a pluto[2559]:   HMAC_SHA1          IKEv1: IKE         IKEv2: IKE         FIPS  (sha sha1)
Sep 24 23:47:04 taiwan-a pluto[2559]:   HMAC_SHA2_256      IKEv1: IKE         IKEv2: IKE         FIPS  (sha2 sha256 sha2_256)
Sep 24 23:47:04 taiwan-a pluto[2559]:   HMAC_SHA2_384      IKEv1: IKE         IKEv2: IKE         FIPS  (sha384 sha2_384)
Sep 24 23:47:04 taiwan-a pluto[2559]:   HMAC_SHA2_512      IKEv1: IKE         IKEv2: IKE         FIPS  (sha512 sha2_512)
Sep 24 23:47:04 taiwan-a pluto[2559]: Integrity algorithms:
Sep 24 23:47:04 taiwan-a pluto[2559]:   HMAC_MD5_96        IKEv1: IKE ESP AH  IKEv2: IKE ESP AH        (md5 hmac_md5)
Sep 24 23:47:04 taiwan-a pluto[2559]:   HMAC_SHA1_96       IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (sha sha1 sha1_96 hmac_sha1)
Sep 24 23:47:04 taiwan-a pluto[2559]:   HMAC_SHA2_512_256  IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (sha512 sha2_512 hmac_sha2_512)
Sep 24 23:47:04 taiwan-a pluto[2559]:   HMAC_SHA2_384_192  IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (sha384 sha2_384 hmac_sha2_384)
Sep 24 23:47:04 taiwan-a pluto[2559]:   HMAC_SHA2_256_128  IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (sha2 sha256 sha2_256 hmac_sha2_256)
Sep 24 23:47:04 taiwan-a pluto[2559]:   AES_XCBC_96        IKEv1:     ESP AH  IKEv2:     ESP AH  FIPS  (aes_xcbc)
Sep 24 23:47:04 taiwan-a pluto[2559]:   AES_CMAC_96        IKEv1:     ESP AH  IKEv2:     ESP AH  FIPS  (aes_cmac)
Sep 24 23:47:04 taiwan-a pluto[2559]: DH algorithms:
Sep 24 23:47:04 taiwan-a pluto[2559]:   MODP1024           IKEv1: IKE ESP AH  IKEv2: IKE ESP AH        (dh2)
Sep 24 23:47:04 taiwan-a pluto[2559]:   MODP1536           IKEv1: IKE ESP AH  IKEv2: IKE ESP AH        (dh5)
Sep 24 23:47:04 taiwan-a pluto[2559]:   MODP2048           IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (dh14)
Sep 24 23:47:04 taiwan-a pluto[2559]:   MODP3072           IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (dh15)
Sep 24 23:47:04 taiwan-a pluto[2559]:   MODP4096           IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (dh16)
Sep 24 23:47:04 taiwan-a pluto[2559]:   MODP6144           IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (dh17)
Sep 24 23:47:04 taiwan-a pluto[2559]:   MODP8192           IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (dh18)
Sep 24 23:47:04 taiwan-a pluto[2559]:   DH19               IKEv1: IKE         IKEv2: IKE ESP AH  FIPS  (ecp_256)
Sep 24 23:47:04 taiwan-a pluto[2559]:   DH20               IKEv1: IKE         IKEv2: IKE ESP AH  FIPS  (ecp_384)
Sep 24 23:47:04 taiwan-a pluto[2559]:   DH21               IKEv1: IKE         IKEv2: IKE ESP AH  FIPS  (ecp_521)
Sep 24 23:47:04 taiwan-a pluto[2559]:   DH23               IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS
Sep 24 23:47:04 taiwan-a pluto[2559]:   DH24               IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS
Sep 24 23:47:04 taiwan-a pluto[2559]: no crypto helpers will be started; all cryptographic operations will be done inline
Sep 24 23:47:04 taiwan-a pluto[2559]: Using Linux XFRM/NETKEY IPsec interface code on 4.11.9-041109-generic
Sep 24 23:47:04 taiwan-a pluto[2559]: systemd watchdog for ipsec service configured with timeout of 200000000 usecs
Sep 24 23:47:04 taiwan-a pluto[2559]: watchdog: sending probes every 100 secs
Sep 24 23:47:04 taiwan-a pluto[2559]: seccomp security not supported
Sep 24 15:47:06 taiwan-a pluto[2559]: added connection description "l2tp-psk"
Sep 24 15:47:06 taiwan-a pluto[2559]: added connection description "xauth-psk"
Sep 24 15:47:06 taiwan-a pluto[2559]: listening for IKE messages
Sep 24 15:47:06 taiwan-a pluto[2559]: adding interface ens4/ens4 10.140.0.3:500
Sep 24 15:47:06 taiwan-a pluto[2559]: adding interface ens4/ens4 10.140.0.3:4500
Sep 24 15:47:06 taiwan-a pluto[2559]: adding interface lo/lo 127.0.0.1:500
Sep 24 15:47:06 taiwan-a pluto[2559]: adding interface lo/lo 127.0.0.1:4500
Sep 24 15:47:06 taiwan-a pluto[2559]: adding interface lo/lo ::1:500
Sep 24 15:47:06 taiwan-a pluto[2559]: | setup callback for interface lo:500 fd 18
Sep 24 15:47:06 taiwan-a pluto[2559]: | setup callback for interface lo:4500 fd 17
Sep 24 15:47:06 taiwan-a pluto[2559]: | setup callback for interface lo:500 fd 16
Sep 24 15:47:06 taiwan-a pluto[2559]: | setup callback for interface ens4:4500 fd 15
Sep 24 15:47:06 taiwan-a pluto[2559]: | setup callback for interface ens4:500 fd 14
Sep 24 15:47:06 taiwan-a pluto[2559]: loading secrets from "/etc/ipsec.secrets"
Sep 24 15:48:06 taiwan-a pluto[2559]: "l2tp-psk"[1] 116.233.xxx #1: responding to Main Mode from unknown peer 116.233.xxx
Sep 24 15:48:06 taiwan-a pluto[2559]: "l2tp-psk"[1] 116.233.xxx #1: transition from state STATE_MAIN_R0 to state STATE_MAIN_R1
Sep 24 15:48:06 taiwan-a pluto[2559]: "l2tp-psk"[1] 116.233.xxx #1: STATE_MAIN_R1: sent MR1, expecting MI2
Sep 24 15:48:16 taiwan-a pluto[2559]: "l2tp-psk"[1] 116.233.xxx #2: responding to Main Mode from unknown peer 116.233.xxx
Sep 24 15:48:16 taiwan-a pluto[2559]: "l2tp-psk"[1] 116.233.xxx #2: transition from state STATE_MAIN_R0 to state STATE_MAIN_R1
Sep 24 15:48:16 taiwan-a pluto[2559]: "l2tp-psk"[1] 116.233.xxx #2: STATE_MAIN_R1: sent MR1, expecting MI2
Sep 24 15:48:26 taiwan-a pluto[2559]: "l2tp-psk"[1] 116.233.xxx #3: responding to Main Mode from unknown peer 116.233.xxx
Sep 24 15:48:26 taiwan-a pluto[2559]: "l2tp-psk"[1] 116.233.xxx #3: transition from state STATE_MAIN_R0 to state STATE_MAIN_R1
Sep 24 15:48:26 taiwan-a pluto[2559]: "l2tp-psk"[1] 116.233.xxx #3: STATE_MAIN_R1: sent MR1, expecting MI2

**Comment by hwdsl2** [comment]
@jkingben 你好！根据你提供的日志，该问题一般是因为网络原因导致的。从日志来看，你的服务器在 NAT 后面 （10.140.0.3）。你是否配置了服务商的防火墙以打开 UDP 500 和 4500 端口并转发到服务器的 IP？另外，服务器重启后它的内网 IP 地址是否有变化？我觉得有可能是 UDP 4500 端口在重启后未打开，因为需要它进行 NAT traversal。

**Comment by jkingben** [comment]
我用的是google的GCP，默认打开的是全端口通过，没有限制端口的访问。

**Comment by jkingben** [comment]
![image](https://user-images.githubusercontent.com/5220242/30784286-118123f8-a185-11e7-8f3b-e13b1486ef9c.png)

**Comment by jkingben** [comment]
IP地址范围那里又加了个内网的地址，现在正常了。。。奇怪，0.0.0.0/0难道还不包括这内网地址

**Comment by hwdsl2** [comment]
@jkingben 嗯，我觉得还是 GCP 防火墙的问题，不是服务器的原因。如果还有问题的话，你可以再检查一下是否有其它的冲突的规则，或者尝试为该服务器单独添加开放 UDP 500 和 4500 端口的规则。
