### ISSUE TITLE
ios经常无故掉线

### ISSUE THREAD

**Issue by glucee** [hwdsl2/setup-ipsec-vpn#222]
我发现ios用L2TP的方式，总是无故掉线。不知道各位有没有相同问题。
服务器运行环境：AWS EC2
服务器版本：Ubuntu 16.04
ios版本：ios11
VPN连接方式：L2TP

**Comment by wshinibaba** [comment]
Ios锁屏了一会儿好像就会自动断开？

**Comment by glucee** [comment]
是的，应该是这种状况！

**Comment by wshinibaba** [comment]
ios就是这样的，好像可以安装什么证书来解决

**Comment by glucee** [comment]
安装什么证书？

**Comment by hwdsl2** [comment]
@glucee 如上所述，ios 锁屏自动断网的确是苹果手机系统本身的局限性。如需自动重连功能，你可以另外尝试 OpenVPN [1].

[1] https://github.com/Nyr/openvpn-install
