### ISSUE TITLE
如何设置端口转发？

### ISSUE THREAD

**Issue by glucee** [hwdsl2/setup-ipsec-vpn#223]
我看脚本已经设置了iptables，也预留了一些参数，里面也有redirect，但方法不详。

我有一台国内的VPS，是想让国外IP的流量转发到某个端口（已经用ssredir listen to1080端口）。

如果可以设置成国外IP转发到这个端口，这样任何设备连接到这台VPN就自动可以翻墙，而且国内IP速度也足够快。

**Comment by hwdsl2** [comment]
@glucee 你好！你所说的端口转发很难通过 VPN 和 IPTables 实现。你可以另外尝试 ss-redir 透明代理，网上有教程。

**Comment by aogg** [comment]
vpn server后使用代理，还是很多这样的需求的 @hwdsl2
