### ISSUE TITLE
同一個路由器問題

### ISSUE THREAD

**Issue by kevinwangkk** [hwdsl2/setup-ipsec-vpn#230]
最近在使用的時候發現一個問題，同一個路由器下的兩臺電腦衹有一臺能夠鏈接成功，鏈接成功的電腦下綫后，另一臺可以正常鏈接，請問如何解決？

**Comment by hwdsl2** [comment]
@kevinwangkk 你好！这个是正常的。同一个 VPN 账户可以在你的多个设备上使用。但是由于 IPsec/L2TP 的局限性，如果需要同时连接在同一个 NAT （比如家用路由器）后面的多个设备到 VPN 服务器，你必须仅使用 IPsec/XAuth 模式[1]。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth-zh.md

**Comment by lamite** [comment]
您好,我也遇到这个问题.请问,必须仅使用 IPsec/XAuth 模式,如何操作?例如,我在2台iphone上,VPN的Type选的都是IPsec,但依然有这个问题.请问是否有更详细的说明,谢谢.

**Comment by hwdsl2** [comment]
@lamite 你好！在2台 iPhone 上都选择 IPsec 的话，应该可以同时连接。如果不行的话，有可能是苹果系统的问题。你可以另外尝试一下 IKEv2 [1]。

[1] https://github.com/gaomd/docker-ikev2-vpn-server
