### ISSUE TITLE
win10 IPsec/XAuth 配置

### ISSUE THREAD

**Issue by kevinwangkk** [hwdsl2/setup-ipsec-vpn#231]
請問win10 IPsec/XAuth 如何配置

**Comment by hwdsl2** [comment]
@kevinwangkk 你好！Windows 10 IPsec/XAuth 你可以尝试使用 Shrew Soft VPN client [1] 。因为该软件一直未更新，可能有bug。如果遇到问题，建议你换用 IPsec/L2TP模式。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth-zh.md

**Comment by wpexia** [comment]
@hwdsl2  Shrew Soft VPN client 不支持win10，且在win10 上，用各种兼容模式也好，都打不开。
