### ISSUE TITLE
Can connect to VPN with local IP but not public IP?

### ISSUE THREAD

**Issue by taekubz** [hwdsl2/setup-ipsec-vpn#232]
Hello, I just installed a vpn server on my vm workstation, it works fine when I test this vpn using host machine by connecting to the vpn server with local IP 192.168.1.X  and it gave me vpn IP(same IP with host), have no problem connecting to internet. But when I tried to connect using my own public IP or NO-IP on vpn client, I got error 789. I have configured everything properly on my host operating system (window 7) and have no problem connecting to a vpn server built from digital ocean using both public ip and hostname. But I couldn't understand why I can't connect to this server installed on my own computer using public IP.

Many thanks to you!!

**Comment by taekubz** [comment]
Hi there, I just found out on youtube that it has to do port forwarding on my router. But apparently my ISP doesn't allow that. Is there alternative way to fix this without messing with my ISP' router?

Thank you.

**Comment by hwdsl2** [comment]
@taekubz Hello! Unfortunately, for your use case, port forwarding on your router (UDP ports 500 & 4500) is required, and there is no workaround for that. I would suggest that you instead set up the VPN server with a cloud provider.
