### ISSUE TITLE
can not visit blocked site?

### ISSUE THREAD

**Issue by ddyllen-z** [hwdsl2/setup-ipsec-vpn#234]
No error, all going well. My ip is us,but can't visit block website.why?

**Comment by hwdsl2** [comment]
@ddyllen-z Hello! Not sure what you mean by blocked website. First, try clearing the DNS cache by rebooting both your VPN client and VPN server, and reconnect the VPN. Note that if you were referring to something like Netflix, they do block most VPN IPs and VPS provider IPs, and there is no simple workaround for that. Anyway, this is not an issue with the VPN setup scripts.

**Comment by ddyllen-z** [comment]
tks.
