### ISSUE TITLE
增加用户问题

### ISSUE THREAD

**Issue by DreamboyA** [hwdsl2/setup-ipsec-vpn#235]
/etc/ppp/chap-secrets 增加用户 
密码不用openssl加盐
<pre><code>
 # Secrets for authentication using CHAP
 # client  server  secret  IP addresses
 "vpnuser" l2tpd "8cT8voiLLq6PfZGS" *
 "fenger" l2tpd "qweasdzxc123" *
</pre></code>
或者加盐
<pre><code>
 # Secrets for authentication using CHAP
 # client  server  secret  IP addresses
 "vpnuser" l2tpd "8cT8voiLLq6PfZGS" *
 "fenger" l2tpd "$1$5pKNgQcS$hRi2u2KQ4eB6kEjZN1" *
</pre></code>

都是密码错误

**Comment by hwdsl2** [comment]
@DreamboyA 你好！/etc/ppp/chap-secrets 文件中增加用户时，密码不使用openssl加盐。

你可以尝试重启服务，sudo service ipsec restart，或者重启你的 VPN
服务器。检查客户端上的密码输入是否有错误。客户端是什么系统和版本？
