### ISSUE TITLE
xl2tpd restart error

### ISSUE THREAD

**Issue by DreamboyA** [hwdsl2/setup-ipsec-vpn#236]
<pre><code>
root@ubuntu:/etc/ppp# xl2tpd restart

xl2tpd version:  xl2tpd-1.3.6
Usage: xl2tpd [-c <config file>] [-s <secret file>] [-p <pid file>]
              [-C <control file>] [-D]
              [-v, --version]
</pre></code>

**Comment by hwdsl2** [comment]
@DreamboyA Your command is incorrect. Try this:

service xl2tpd restart
