### ISSUE TITLE
IOS可以连接但是windows电脑始终连接不上

### ISSUE THREAD

**Issue by LancelotYG** [hwdsl2/setup-ipsec-vpn#238]
用L2TP显示无法建立计算机与VPN服务器之间的网络连接，因为远程服务器未响应。这可能是因为未将计算机与.........
查看了注册表没有问题。REG ADD HKLM\SYSTEM\CurrentControlSet\Services\PolicyAgent /v AssumeUDPEncapsulationContextOnSendRule /t REG_DWORD /d 0x2 /f   也没用。
用 IPsec/XAuth VPN 模式显示negotiation timeout occurred。
实在是没有办法。

**Comment by LancelotYG** [comment]
用的是linode

**Comment by hwdsl2** [comment]
@LancelotYG 你好！当前防火墙对VPN的封锁比较严重。你可以尝试一下 [1] 中的步骤。检查一下日志。或者你可以换用 Shadowsocks。

[1]
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E9%A2%9D%E5%A4%96%E7%9A%84%E6%AD%A5%E9%AA%A4

**Comment by LancelotYG** [comment]
谢谢，已经解决了。将几个服务从手动改成了自动，重启后没问题了。
不过想再问一下，如果想用ipv6连接vpn 应该如何操作？

**Comment by hwdsl2** [comment]
@LancelotYG 好的！关于你的另一个问题：当前不支持使用 IPv6 连接到 VPN 服务器。

**Comment by VSakuya** [comment]
@LancelotYG 请问你开了什么服务？
