### ISSUE TITLE
一个帐号可以供多个人使用吗？

### ISSUE THREAD

**Issue by beepony** [hwdsl2/setup-ipsec-vpn#239]
如图，我新建了一个帐号，是否可以让多个人同时使用改帐号登录。如果不行的话，是否有多账号的文档呢？

**Comment by wshinibaba** [comment]
同一个 VPN 账户可以在你的多个设备上使用。但是由于 IPsec/L2TP 的局限性，如果需要同时连接在同一个 NAT （比如家用路由器）后面的多个设备到 VPN 服务器，你必须仅使用 IPsec/XAuth 模式。

**Comment by hwdsl2** [comment]
@beepony Thanks @wshinibaba!  @beepony please refer to "important notes" section [1] of README.

[1] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes

**Comment by Test-Jim** [comment]
> Thanks @wshinibaba! @beepony please refer to the "important notes" section [1] of README.
> 
> [1] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes

你好，我自己这边使用的类型是L2TP ，我朋友使用的是IPsec类型，我们不在一个局域网内，但是我们好像可以同时使用一个账号？

**Comment by hwdsl2** [comment]
@Test-Jim 你好！据我所知，对用户账户的这个限制不能实现。
