### ISSUE TITLE
多账号多链接数

### ISSUE THREAD

**Issue by hsu-1027** [hwdsl2/setup-ipsec-vpn#241]
你好，我想问下ipsec vpn下 第二个链接无论是同一个账号还是第二个账号都无法链接
log打印如下

Oct 17 03:56:34 li1725-83 pluto[26705]: "xauth-psk"[1] Wan+IP #1: responding to Main Mode from unknown peer Wan+IP
Oct 17 03:56:34 li1725-83 pluto[26705]: "xauth-psk"[1] Wan+IP #1: transition from state STATE_MAIN_R0 to state STATE_MAIN_R1
Oct 17 03:56:34 li1725-83 pluto[26705]: "xauth-psk"[1] Wan+IP #1: STATE_MAIN_R1: sent MR1, expecting MI2
Oct 17 03:56:37 li1725-83 pluto[26705]: "xauth-psk"[1] Wan+IP #2: responding to Main Mode from unknown peer Wan+IP
Oct 17 03:56:37 li1725-83 pluto[26705]: "xauth-psk"[1] Wan+IP #2: transition from state STATE_MAIN_R0 to state STATE_MAIN_R1
Oct 17 03:56:37 li1725-83 pluto[26705]: "xauth-psk"[1] Wan+IP #2: STATE_MAIN_R1: sent MR1, expecting MI2
Oct 17 03:56:40 li1725-83 pluto[26705]: "xauth-psk"[1] Wan+IP #3: responding to Main Mode from unknown peer Wan+IP
Oct 17 03:56:40 li1725-83 pluto[26705]: "xauth-psk"[1] Wan+IP #3: transition from state STATE_MAIN_R0 to state STATE_MAIN_R1
Oct 17 03:56:40 li1725-83 pluto[26705]: "xauth-psk"[1] Wan+IP #3: STATE_MAIN_R1: sent MR1, expecting MI2
Oct 17 03:56:43 li1725-83 pluto[26705]: "xauth-psk"[1] Wan+IP #4: responding to Main Mode from unknown peer Wan+IP
Oct 17 03:56:43 li1725-83 pluto[26705]: "xauth-psk"[1] Wan+IP #4: transition from state STATE_MAIN_R0 to state STATE_MAIN_R1
Oct 17 03:56:43 li1725-83 pluto[26705]: "xauth-psk"[1] Wan+IP #4: STATE_MAIN_R1: sent MR1, expecting MI2

**Comment by hwdsl2** [comment]
@hsu-1027 你好！如果两台客户端设备都是 Windows 的话，由于它们都尝试使用路由器上的 UDP 500 和 4500 端口，所以可能不能同时连接。

另外你可以试一下 [1] 和 [2] 中的故障排除步骤。

[1] http://www.tp-link.com/en/faq-1029.html
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#windows-%E9%94%99%E8%AF%AF-809

**Comment by hsu-1027** [comment]
多个客户端都是ios及mac下是否有方法可以解决？

**Comment by hwdsl2** [comment]
@hsu-1027
你好！从你的日志来看，感觉是第二个客户端的连接被网络设备或者防火墙屏蔽了，而不是两个客户端同时连接的问题。你试试如果不连接第一个客户端的时候，是不是第二个客户端也无法连接？

一般来说，在 IPsec/XAuth 模式下多个客户端是可以同时连接的。

另外，重启一下服务器上的 IPsec 服务可能有帮助：

sudo service ipsec restart

**Comment by hsu-1027** [comment]
@hwdsl2 
您好，我重启过服务仍然没用
主要表现为1个ip已经连上后，同一个ip拨都无法链接，第一个链接断开后，需要过会其他设备才能连上，但同一ip仅有一个链接
