### ISSUE TITLE
Fail to connect from Windows and iOS client

### ISSUE THREAD

**Issue by CyanideCentral** [hwdsl2/setup-ipsec-vpn#242]
My VPN is set up on a DigitalOcean Ubuntu VPS, and connection failure has lasted for several days. I've already tried reinstalling the VPN but it's no use.

Pluto log:
Oct 17 03:11:38 ubuntu-LYR0 pluto[15434]: "l2tp-psk"[1] 117.136.45.158 #1: responding to Main Mode from unknown peer 117.136.45.158
Oct 17 03:11:38 ubuntu-LYR0 pluto[15434]: "l2tp-psk"[1] 117.136.45.158 #1: transition from state STATE_MAIN_R0 to state STATE_MAIN_R1
Oct 17 03:11:38 ubuntu-LYR0 pluto[15434]: "l2tp-psk"[1] 117.136.45.158 #1: STATE_MAIN_R1: sent MR1, expecting MI2
Oct 17 03:11:41 ubuntu-LYR0 pluto[15434]: "l2tp-psk"[1] 117.136.45.158 #2: responding to Main Mode from unknown peer 117.136.45.158
Oct 17 03:11:41 ubuntu-LYR0 pluto[15434]: "l2tp-psk"[1] 117.136.45.158 #2: transition from state STATE_MAIN_R0 to state STATE_MAIN_R1
Oct 17 03:11:41 ubuntu-LYR0 pluto[15434]: "l2tp-psk"[1] 117.136.45.158 #2: STATE_MAIN_R1: sent MR1, expecting MI2
Oct 17 03:11:44 ubuntu-LYR0 pluto[15434]: "l2tp-psk"[1] 117.136.45.158 #3: responding to Main Mode from unknown peer 117.136.45.158
Oct 17 03:11:44 ubuntu-LYR0 pluto[15434]: "l2tp-psk"[1] 117.136.45.158 #3: transition from state STATE_MAIN_R0 to state STATE_MAIN_R1
Oct 17 03:11:44 ubuntu-LYR0 pluto[15434]: "l2tp-psk"[1] 117.136.45.158 #3: STATE_MAIN_R1: sent MR1, expecting MI2
Oct 17 03:11:47 ubuntu-LYR0 pluto[15434]: "l2tp-psk"[1] 117.136.45.158 #4: responding to Main Mode from unknown peer 117.136.45.158
Oct 17 03:11:47 ubuntu-LYR0 pluto[15434]: "l2tp-psk"[1] 117.136.45.158 #4: transition from state STATE_MAIN_R0 to state STATE_MAIN_R1
Oct 17 03:11:47 ubuntu-LYR0 pluto[15434]: "l2tp-psk"[1] 117.136.45.158 #4: STATE_MAIN_R1: sent MR1, expecting MI2
Oct 17 03:14:55 ubuntu-LYR0 pluto[15434]: "l2tp-psk"[1] 117.136.45.158 #5: responding to Main Mode from unknown peer 117.136.45.158
Oct 17 03:14:55 ubuntu-LYR0 pluto[15434]: "l2tp-psk"[1] 117.136.45.158 #5: transition from state STATE_MAIN_R0 to state STATE_MAIN_R1
Oct 17 03:14:55 ubuntu-LYR0 pluto[15434]: "l2tp-psk"[1] 117.136.45.158 #5: STATE_MAIN_R1: sent MR1, expecting MI2
Oct 17 03:14:55 ubuntu-LYR0 pluto[15434]: packet from 117.136.45.158:46297: not enough room in input packet for ISAKMP Message (remain=0, sd->size=28)
Oct 17 03:14:55 ubuntu-LYR0 pluto[15434]: packet from 117.136.45.158:46297: Received packet with mangled IKE header - dropped
Oct 17 03:14:55 ubuntu-LYR0 pluto[15434]: packet from 117.136.45.158:46297: not enough room in input packet for ISAKMP Message (remain=0, sd->size=28)
Oct 17 03:14:55 ubuntu-LYR0 pluto[15434]: packet from 117.136.45.158:46297: Received packet with mangled IKE header - dropped
Oct 17 03:14:55 ubuntu-LYR0 pluto[15434]: packet from 117.136.45.158:46297: not enough room in input packet for ISAKMP Message (remain=0, sd->size=28)
Oct 17 03:14:55 ubuntu-LYR0 pluto[15434]: packet from 117.136.45.158:46297: Received packet with mangled IKE header - dropped
Oct 17 03:14:58 ubuntu-LYR0 pluto[15434]: "l2tp-psk"[1] 117.136.45.158 #6: responding to Main Mode from unknown peer 117.136.45.158
Oct 17 03:14:58 ubuntu-LYR0 pluto[15434]: "l2tp-psk"[1] 117.136.45.158 #6: transition from state STATE_MAIN_R0 to state STATE_MAIN_R1
Oct 17 03:14:58 ubuntu-LYR0 pluto[15434]: "l2tp-psk"[1] 117.136.45.158 #6: STATE_MAIN_R1: sent MR1, expecting MI2
Oct 17 03:15:01 ubuntu-LYR0 pluto[15434]: "l2tp-psk"[1] 117.136.45.158 #7: responding to Main Mode from unknown peer 117.136.45.158
Oct 17 03:15:01 ubuntu-LYR0 pluto[15434]: "l2tp-psk"[1] 117.136.45.158 #7: transition from state STATE_MAIN_R0 to state STATE_MAIN_R1
Oct 17 03:15:01 ubuntu-LYR0 pluto[15434]: "l2tp-psk"[1] 117.136.45.158 #7: STATE_MAIN_R1: sent MR1, expecting MI2
Oct 17 03:15:04 ubuntu-LYR0 pluto[15434]: "l2tp-psk"[1] 117.136.45.158 #8: responding to Main Mode from unknown peer 117.136.45.158
Oct 17 03:15:04 ubuntu-LYR0 pluto[15434]: "l2tp-psk"[1] 117.136.45.158 #8: transition from state STATE_MAIN_R0 to state STATE_MAIN_R1
Oct 17 03:15:04 ubuntu-LYR0 pluto[15434]: "l2tp-psk"[1] 117.136.45.158 #8: STATE_MAIN_R1: sent MR1, expecting MI2

**Comment by hwdsl2** [comment]
@CyanideCentral Hello! Currently there is significant blocking by the firewall for people in China. Try a new Droplet with a different IP, a new DigitalOcean region, or another VPS provider. You may also try Shadowsocks.
