### ISSUE TITLE
现在l2tp会被网络供应商屏蔽么

### ISSUE THREAD

**Issue by 346673164** [hwdsl2/setup-ipsec-vpn#244]
用脚本搭建成功。发现在家一直连不上，一直以为是搭建的有问题。
结果用手机4g网络发现可以链接，公司也可以连接。
难不成是家里的长城宽带进制了？如果是的话，有什么解决方案么？

**Comment by nxtreaming** [comment]
会被屏蔽，但不会彻底屏蔽，只是周期性的干扰。
基本无解，换实现方式。

-----------------------------------------
Productive. Reliable. Fast.

2017-10-21 17:46 GMT+08:00 346673164 <notifications@github.com>:

**Comment by hwdsl2** [comment]
@346673164 你好！上面 @nxtreaming 的回复是对的。如果无法正常连接，你可以尝试换用其它的解决方案，比如 Shadowsocks。

**Comment by aishlai** [comment]
Shadowsocks 最近封的很厉害，换了服务器，2天又被封

**Comment by 346673164** [comment]
你是哪里的服务器呢？我发现我这边vultr官网都上不去，服务器能ping通，但是ssh连不上。

**Comment by aishlai** [comment]
我用的是linode，日本节点的，特殊时期，管控比较严格，出国流量应该会被过滤，就算是开SS也别用8838端口以及附近的端口，如果443没有被占用，或者995都行，你可以试试这两个端口；
另外你现在遇到的ping的通，但是ssh连接不上，应该是你服务器配置，或者本地配置的问题，如果使用密码登录，请确认密码正确，是否有空格什么的；如果是证书，请重新检查证书文件是否一致

**Comment by aishlai** [comment]
@346673164 vultr是否提供了remote access的功能吗？如果有，你可以通过remote access登录，然后tail ssh的登录日志，看下你通过ssh远程连接的时候，报了什么错

**Comment by 346673164** [comment]
@aishlai 我换手机网络 是可以ssh过去的 所以肯定不是ssh的server有问题。看来是封了，不过奇怪的是，不封ip不封端口。telnet还可以通。我在深圳，发现有朋友上海的也有这样情况，不fq发现vultr官网也上不了。好心累

**Comment by Daanlex** [comment]
我家里长城也是连不上分公司的VPN了，去武汉的公司又是可以连接其他分公司的VPN的···十九大没开之前是可以连的，突然某天早上就连不上了，希望会开完了，能够放开吧

**Comment by juicechu** [comment]
是的，我的也是，4G网络和电信网络可以登录 L2TP，就长城宽带登不了

**Comment by brijagstu7** [comment]
我的l2tp VPN生存了半个月左右，开始频繁断线，表现为连不上、一连上几分钟就断。不过最让我奇怪的是我换了静态IP甚至换了主机，问题仍然存在（我使用的是谷歌云），有人能为我解答吗？在我的理解里，GFW只会封IP或者端口，如果它不能认出包的内容的话（与IP无关的关键词屏蔽）。

**Comment by aishlai** [comment]
TCP阻断 or TCP干扰 都会引起掉线




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "brijagstu7"<notifications@github.com&gt;; 
发送时间: 2019年11月23日(星期六) 晚上6:37
收件人: "hwdsl2/setup-ipsec-vpn"<setup-ipsec-vpn@noreply.github.com&gt;; 
抄送: "aishlai"<aishlai@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [hwdsl2/setup-ipsec-vpn] 现在l2tp会被网络供应商屏蔽么 (#244)




我的l2tp VPN生存了半个月左右，开始频繁断线，表现为连不上、一连上几分钟就断。不过最让我奇怪的是我换了静态IP甚至换了主机，问题仍然存在（我使用的是谷歌云），有人能为我解答吗？在我的理解里，GFW只会封IP或者端口，如果它不能认出包的内容的话（与IP无关的关键词屏蔽）。

**Comment by AIvin8** [comment]
知道哪儿能有孟加拉节点的分享啊各位老哥😅？
