### ISSUE TITLE
windows10无法上网

### ISSUE THREAD

**Issue by uncode** [hwdsl2/setup-ipsec-vpn#246]
MAC连接后可以上网，windows 10连接后无法连接到网络

**Comment by hwdsl2** [comment]
@uncode 你好！需要提供更多信息。请问你是用的哪种方式连接 （IPsec/L2TP 还是 Cisco IPsec）？如需同时连接在同一NAT （比如家用路由器）后面的两台设备，则必须使用 Cisco IPsec 模式。参见 [1]。

另外请发一下服务器的日志：

```
# Ubuntu/Debian
grep pluto /var/log/auth.log
grep xl2tpd /var/log/syslog

# CentOS/RHEL
grep pluto /var/log/secure
grep xl2tpd /var/log/messages
```

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#%E9%87%8D%E8%A6%81%E6%8F%90%E7%A4%BA

**Comment by uncode** [comment]
我使用了 Shrew soft软件连接，
会提示 detached from key daemon
不过中间连上过一次，
但是没有网络相应
并提示：getway not responde

**Comment by uncode** [comment]
我的日志文件好像被自己删除了

**Comment by hwdsl2** [comment]
@uncode 你好！这个问题是因为 Shrew Soft 软件比较旧，不支持 Windows 10 （有 bug）。你可以试一下 IPsec/L2TP 模式 [1]。或者另外尝试其它解决方案 (OpenVPN, Shadowsocks, ...)。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md
