### ISSUE TITLE
遇到的各种问题汇总

### ISSUE THREAD

**Issue by zhijun1997** [hwdsl2/setup-ipsec-vpn#247]
目前遇到的问题比较杂而且很奇怪，为了方便分析，我先选择从看起来表面的地方开始。

第一次安装完成之后，苹果产品成功连接了IPSEC，但无法正常上网，而且一段时间过后自动断开了连接。

自第一次断开连接之后，目前MAC、IOS使用IPSec、L2TP均无法正常连接。

**目前日志如下：**
IPSec
![ipsec](https://user-images.githubusercontent.com/18146816/31887731-0821cb42-b82c-11e7-8ba0-4d2d8ae8f02d.png)

L2TP
![l2tp](https://user-images.githubusercontent.com/18146816/31887732-0858a55e-b82c-11e7-8f0f-0492f978dd18.png)

IOS端状态如下：

![img_0014](https://user-images.githubusercontent.com/18146816/31888121-5963f5ba-b82d-11e7-892d-34f5ab3bce38.PNG)

**Comment by zhijun1997** [comment]
状况更新：

很奇怪，过了一段时间之后，IPSEC和L2TP又恢复正常了

**日志如下**

![ipsec](https://user-images.githubusercontent.com/18146816/31887855-7936d28c-b82c-11e7-9168-457f8c2551c1.png)
![l2tp](https://user-images.githubusercontent.com/18146816/31887856-796b6056-b82c-11e7-9c55-851ffebc9e6f.png)

**IOS端连接状态如下：**
![img_0015](https://user-images.githubusercontent.com/18146816/31887897-a4f9b33a-b82c-11e7-8611-287150ea63cd.PNG)

**总结了一下现在的情况：**

1、MacOS和IOS：只要连接过L2TP、IPSEC，只要断开之后，在一段时间内都无法连接（变成上一条的情况），只有过一段时间之后才能重连。

2、MacOS和IOS：无论L2TP还是IPSEC，连接进去之后没有网络，但是能ping通自己，以及VPN的网关IP，而且一段时间过后自动挂断。

**Comment by hwdsl2** [comment]
@zhijun1997 你好！看了你上面的日志。是这样的，（同一个路由器后面的） VPN 客户端不能混合使用 IPsec/L2TP 和
IPsec/XAuth (Cisco IPsec) 模式，只能选择其一。否则 Libreswan
会记住上次使用的模式并出现像你第一个日志中的错误信息。过一会之后，它会自动忘记上次的连接并恢复正常（你也可以手动重启服务器上的 IPsec 服务）。

关于无法上网的问题，是断续出现还是一直出现？前者可能是网络受干扰。后者有可能是你的 IPTables 防火墙有问题。查看一下规则：

sudo iptables -nvL; sudo iptables -nvL -t nat

另外为了安全起见，你可以把上面日志截图里的 IP 去掉。

**Comment by zhijun1997** [comment]
感谢提醒IP相关事项！不过我是学习用的服务器，没有关系的。

根据你说的不能混用之类的，意思就是说如果用L2TP和CISCO IPSec之间短暂时间内只能固定连接一个对吗？理解了。

现在目前的情况是这样：L2TP和IPSEC均不能访问网络（一直出现的情况），CentOS防火墙处于关闭状态，这是IPTABLES的规则信息：

![l2tp](https://user-images.githubusercontent.com/18146816/31893930-773f3fd8-b83f-11e7-8030-7b8bae7d5f9c.png)

看看是不是漏了什么放行规则或者转发规则？

**Comment by zhijun1997** [comment]
# 更新一下状况：

我添加了IKEv2的连接支持，并且使用WINDOWS成功建立了连接，目前IKEv2使用正常，没有断线和网络问题。但L2TP和IPSEC问题依旧。

**现在遇到的问题有2个：**

1. L2TP没网，PING不通路由，但PING得通VPN网关。
2. IPSec没网，未测试PING。

## L2TP连接状态截图：

![l2tp](https://user-images.githubusercontent.com/18146816/31907993-11bb26c6-b868-11e7-8790-6cb59881fdd5.png)
![l2tp1](https://user-images.githubusercontent.com/18146816/31907994-11eb9c48-b868-11e7-9013-e1527d513744.png)



## iptables配置截图：

![1](https://user-images.githubusercontent.com/18146816/31908128-799e9dea-b868-11e7-937c-32b90d88e12d.png)
![2](https://user-images.githubusercontent.com/18146816/31908130-79f0e406-b868-11e7-8556-97f73fe2d423.png)


**另外IKEv2能否改为使用用户名和密码进行验证而不使用证书？如果可以，如何修改？**

**Comment by anydream** [comment]
@hwdsl2 请问如何配置这个"自动忘记上次的连接"的时间呢?
发现在同一个内网的windows连接之后, iOS就无法连接了, 反过来也一样.
所以设置忘记时间为最小值.

**Comment by hwdsl2** [comment]
@anydream 你好！你说的这个时间无法配置。如需立即连接，可以在服务器上重启 IPsec 服务 `service ipsec restart`。

为避免这个问题，对于在同一个路由器后面的 VPN 客户端设备，建议不要混合 IPsec/L2TP 和 Cisco IPsec 模式，而是选择其一使用。

**Comment by hwdsl2** [comment]
@zhijun1997 你好！看了你更新的配置截图。问题在于你的以下几条规则：

```
-A POSTROUTING -j MASQUERADE
-A POSTROUTING -j MASQUERADE
-A POSTROUTING -o eth0 -j MASQUERADE
-A POSTROUTING -o eth0 -j MASQUERADE
```

将你的 IPTables 规则文件中的以上几行删掉，然后重启服务器。之后应该就可以了。如果还是不行，请尝试在一个全新安装的系统上重新运行 VPN 脚本。
