### ISSUE TITLE
Anyway to make it work with: "Use certificate for authentication" option of L2TP on Windows

### ISSUE THREAD

**Issue by ss-17** [hwdsl2/setup-ipsec-vpn#248]
Hi.

Thanks for such a wonderful script. It worked flawlessly. Though I am unable to figure out how to make it with work with the "Use certificate for authentication" option of L2TP of the in-built VPN client on Windows instead of using a pre-shared key.

![image](https://user-images.githubusercontent.com/33026572/31887708-ffd8bbea-b816-11e7-85ae-9ceea9786d79.png)

Will appreciate any help/pointers you can provide.

Thanks & Regards.

**Comment by hwdsl2** [comment]
@ss-17 Hello! Instead of using L2TP certificates, which is not supported, try setting up IKEv2 [1].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md
