### ISSUE TITLE
Is this any way I can easily undo the script?

### ISSUE THREAD

**Issue by FruityFree** [hwdsl2/setup-ipsec-vpn#25]
It looks like it was bad idea try to setup vpn and web app on same vps=/

**Comment by hwdsl2** [comment]
@FruityFree If using Ubuntu/Debian, please try the following steps to remove the VPN:

```
service ipsec stop
service xl2tpd stop
apt-get remove xl2tpd
rm -rf /usr/local/sbin/ipsec /usr/local/libexec/ipsec
rm -f /etc/init.d/ipsec
rm -rf /opt/src/libreswan-*
```

Optionally, remove these config files: `/etc/ipsec.conf`, `/etc/ipsec.secrets`, `/etc/xl2tpd/xl2tpd.conf`, `/etc/ppp/options.xl2tpd`, `/etc/ppp/chap-secrets`, `/etc/ipsec.d/passwd`.

Edit `/etc/sysctl.conf` and remove lines after `# Added by hwdsl2 VPN script`.   
Edit `/etc/iptables.rules` and remove unneeded rules. Your original rules are backed up as `/etc/iptables.rules-old-date-time`. If using IPv6, also edit `/etc/ip6tables.rules`.   
Edit `/etc/rc.local` and remove lines after `# Added by hwdsl2 VPN script`, except "exit 0".   
Reboot your server.

**Comment by FruityFree** [comment]
Thanks a lot! It works

**Comment by hwdsl2** [comment]
Great! Closing this now.
