### ISSUE TITLE
如何单独使用L2TP

### ISSUE THREAD

**Issue by wjszh668** [hwdsl2/setup-ipsec-vpn#251]
就是不使用L2TP+IPSEC这种方式,单独通过L2TP的UDP1701端口进行连接

**Comment by hwdsl2** [comment]
@wjszh668 你好！单独使用 L2TP （无 IPsec） 的话，传输的数据没有任何加密，这样你连接到 VPN 就没有意义了。但是，如果你坚持使用该模式的话，将这个 IPTables 规则 [1] 改为 ACCEPT 即可。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/vpnsetup.sh#L382
