### ISSUE TITLE
采用vultr的vps,不能自运行

### ISSUE THREAD

**Issue by mybrandy** [hwdsl2/setup-ipsec-vpn#252]
采用vultr的vps,   在选择Ubuntu后，自带的一个 Startup Script ( Manage )项，我将添加密码后的脚本复制进去了，但是点击Deploy New Instance后系统并没有开机运行脚本，帮忙看下怎么回事，
![001](https://user-images.githubusercontent.com/33001317/32062447-1903f80e-baa7-11e7-9d84-19b76ebb906c.PNG)

这是script的解释说明
Boot
These scripts are executed by the VPS the very first time it starts up.

The startup script is saved to /tmp/firstboot.exec
Output produced can be found in /tmp/firstboot.log
Scripts are executed using /bin/bash (Linux), /bin/sh (FreeBSD), or cmd.exe (Windows) 

@hwdsl2

**Comment by hwdsl2** [comment]
@mybrandy 你好！Vultr 的 VPS 在启动时运行一些 `apt-get` 任务，它们与 VPN 安装脚本中的命令冲突。你可以参见这个 Issue： [1] 建议在 Vultr 上不要使用 Startup 脚本安装 VPN。你可以在 VPS 部署完毕后手动登录然后下载运行 VPN 脚本。

[1] https://github.com/saltstack/salt/issues/37062
