### ISSUE TITLE
执行报错

### ISSUE THREAD

**Issue by guoweibo** [hwdsl2/setup-ipsec-vpn#253]
service ipsec restart
ipsec_setup: /usr/local/sbin/ipsec: unknown IPsec command "_realsetup

**Comment by hwdsl2** [comment]
@guoweibo Have no idea what you are trying to say in this issue. Need
details and clarification.

**Comment by hwdsl2** [comment]
@guoweibo Possibly related: [1]. But this has nothing to do with the VPN setup scripts in this repo.

[1] https://forums.gentoo.org/viewtopic-t-569685-start-0.html
