### ISSUE TITLE
IPSec won't start on Debian Wheezy

### ISSUE THREAD

**Issue by marcetcheverry** [hwdsl2/setup-ipsec-vpn#255]
` ps ax | grep IPSec` returns empty.

```
● ipsec.service - Internet Key Exchange (IKE) Protocol Daemon for IPsec
   Loaded: loaded (/lib/systemd/system/ipsec.service; enabled)
   Active: failed (Result: start-limit) since Fri 2017-10-27 18:30:39 -03; 8s ago
     Docs: man:ipsec(8)
           man:pluto(8)
           man:ipsec.conf(5)
  Process: 5278 ExecStopPost=/sbin/ip xfrm policy flush (code=exited, status=2)
  Process: 5274 ExecStop=/usr/local/libexec/ipsec/whack --shutdown (code=exited, status=1/FAILURE)
  Process: 5269 ExecStart=/usr/local/libexec/ipsec/pluto --leak-detective --config /etc/ipsec.conf --nofork (code=exited, status=5)
  Process: 5258 ExecStartPre=/usr/local/sbin/ipsec --checknflog (code=exited, status=0/SUCCESS)
  Process: 5253 ExecStartPre=/usr/local/sbin/ipsec --checknss (code=exited, status=0/SUCCESS)
  Process: 5102 ExecStartPre=/usr/local/libexec/ipsec/_stackmanager start (code=exited, status=0/SUCCESS)
  Process: 5101 ExecStartPre=/usr/local/libexec/ipsec/addconn --config /etc/ipsec.conf --checkconfig (code=exited, status=0/SUCCESS)
 Main PID: 5269 (code=exited, status=5)
   Status: "Exited."

Oct 27 18:30:39 myserver systemd[1]: Failed to start Internet Key Exchange (IKE) Protocol Daemon for IPsec.
Oct 27 18:30:39 myserver systemd[1]: Unit ipsec.service entered failed state.
Oct 27 18:30:39 myserver ip[5278]: RTNETLINK answers: Operation not supported
Oct 27 18:30:39 myserver systemd[1]: ipsec.service holdoff time over, scheduling restart.
Oct 27 18:30:39 myserver systemd[1]: Stopping Internet Key Exchange (IKE) Protocol Daemon for IPsec...
Oct 27 18:30:39 myserver systemd[1]: Starting Internet Key Exchange (IKE) Protocol Daemon for IPsec...
Oct 27 18:30:39 myserver systemd[1]: ipsec.service start request repeated too quickly, refusing to start.
Oct 27 18:30:39 myserver systemd[1]: Failed to start Internet Key Exchange (IKE) Protocol Daemon for IPsec.
Oct 27 18:30:39 myserver systemd[1]: Unit ipsec.service entered failed state.
```

I see this in particular

` Oct 27 18:30:39 elaliado ip[5278]: RTNETLINK answers: Operation not supported`

I did manage to get IPSec to start by installing

` apt-get install strongswan-starter ipsec-tools`

But I still can not connect, any ideas?

**Comment by hwdsl2** [comment]
@marcetcheverry Hello! The VPN setup scripts in this repo had dropped support for Debian 7 (Wheezy) in August 2017, as that OS is old and Libreswan no longer compiles on it. Also, the error `Operation not supported` indicate that you could be using the OpenVZ platform, which is not supported as well.

If you wish to use the VPN setup scripts from this repo, start with a fresh install of a supported Linux OS (see README).

**Comment by marcetcheverry** [comment]
Sorry, I meant Debian Jessie (8)

cat /etc/debian_version

I am unsure if I am running OpenVZ or not, but the script works just fine in another Linode instance similar as the one that is having the issue.

**Comment by hwdsl2** [comment]
@marcetcheverry If the server is on Linode then it should not be OpenVZ. This could be a Linux kernel issue because Linode uses their own custom-built kernel by default. You can try switching to a native kernel [1] before running the VPN setup script.

[1] https://www.linode.com/docs/tools-reference/custom-kernels-distros/run-a-distribution-supplied-kernel-with-kvm

**Comment by marcetcheverry** [comment]
The thing is I am running the same kernel on another Linode instance and it is running fine, so it isn't the kernel, but perhaps some hardening done long ago would be my best guess.

**Comment by marcetcheverry** [comment]
I can confirm it isn't the kernel, as I have installed the Debian kernel and it still does not work.

Furthermore, Debian 8 works just fine (I have tried it emulated using VirtualBox).

What could it be about this machine that causes your script to fail?

**Comment by hwdsl2** [comment]
@marcetcheverry Unfortunately I am not sure about that error. Maybe try
asking on the Libreswan users or strongSwan users mailing list?

**Comment by marcetcheverry** [comment]
I have fixed, the issue was running an x86_64 / amd64 kernel with i386 user space.

**I am unsure if we should detect this in your script or in the Libreswan installation by checking for discrepancies of `uname -r` and `file /bin/ls` or `dpkg --print-architecture`, so other people do not face this issue.**

There are some differences between Libreswan 3.21 and 3.22, 3.22 checks earlier if the IPSEC stack fails to initialize. So if you are running 3.21 you will fail at the connection level (see `/var/log/auth.log`), but 3.22 will fail to start up `pluto`.

I will add some of the auth.log log here for people that search for this.

```
ERROR: netlink response for Get SPI esp.0@HOST_IP included errno 95: Operation not supported
ERROR: netlink response for Add SA esp.8988281@CLIENT_IP included errno 95: Operation not supported
ERROR: netlink response for Del SA esp.8988281@CLIENT_IP included errno 95: Operation not supported
ERROR: netlink XFRM_MSG_DELPOLICY response for flow unk255.10000@HOST_IP included errno 95: Operation not supported
ERROR: netlink XFRM_MSG_DELPOLICY response for flow unk255.10000@HOST_IP included errno 95: Operation not supported
```

**Comment by hwdsl2** [comment]
@marcetheverry Thanks for letting us know!
