### ISSUE TITLE
Can we use ddns to setup on Raspberry Pi?

### ISSUE THREAD

**Issue by leosunderland** [hwdsl2/setup-ipsec-vpn#256]
Currently I can setup successfully on my Pi 3 but since my network doesnt have static ip so it will change. Can I use ddns with your script?

**Comment by leosunderland** [comment]
I tried by replacing in /etc/ipsec.conf and reboot. It worked perfectly. Thank you.

**Comment by Br1an6** [comment]
> I tried by replacing in /etc/ipsec.conf and reboot. It worked perfectly. Thank you.

```
  interfaces=%defaultroute
  uniqueids=no

conn shared
  left=%defaultroute
  leftid=xxx.xxx.xxx.xxx
  right=%any
  encapsulation=yes
  authby=secret
  pfs=no
  rekey=no
  keyingtries=5
  dpddelay=30
  dpdtimeout=120
  dpdaction=clear
  ikev2=never
  ike=aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1,aes256-sha2;modp1024,aes128-sha1;modp1024
  phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes128-sha2,aes256-sha2
  sha2-truncbug=yes
```

Quick question @leosunderland , so you  just modified "leftid=your ddns address"
Have you tried it with L2TP?
