### ISSUE TITLE
Error: 'apt-get install' failed.

### ISSUE THREAD

**Issue by c826** [hwdsl2/setup-ipsec-vpn#257]
你好，系统是Ubuntu 12.04.5，安装过程中出现下面错误。
大概看了一下issues没发现解决办法，求助。

`
Unpacking bind9-host (from .../bind9-host_1%3a9.8.1.dfsg.P1-4ubuntu0.22_amd64.deb) ...
dpkg: error processing /var/cache/apt/archives/bind9-host_1%3a9.8.1.dfsg.P1-4ubuntu0.22_amd64.deb (--unpack):
 unable to create `/usr/bin/host.dpkg-new' (while processing `./usr/bin/host'): Permission denied
Unpacking dnsutils (from .../dnsutils_1%3a9.8.1.dfsg.P1-4ubuntu0.22_amd64.deb) ...
dpkg: error processing /var/cache/apt/archives/dnsutils_1%3a9.8.1.dfsg.P1-4ubuntu0.22_amd64.deb (--unpack):
 unable to create `/usr/bin/dig.dpkg-new' (while processing `./usr/bin/dig'): Permission denied
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Processing triggers for man-db ...
Errors were encountered while processing:
 /var/cache/apt/archives/bind9-host_1%3a9.8.1.dfsg.P1-4ubuntu0.22_amd64.deb
 /var/cache/apt/archives/dnsutils_1%3a9.8.1.dfsg.P1-4ubuntu0.22_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
Error: 'apt-get install' failed.
`

**Comment by jglimmers** [comment]
same as your situation.

......
No package fail2ban available.
Error: Nothing to do
Error: 'yum install' failed.

**Comment by hwdsl2** [comment]
@c826 Hello! Ubuntu 12.04 is not supported as Libreswan 3.21 no longer
compiles on it. But your error output suggests that something is wrong with
your OS that is unrelated to the VPN scripts. Try [1], or try starting with
a fresh installed OS.

@jglimmers Your error looks different. The fail2ban package is from EPEL
and sometimes the CentOS EPEL repos are being updated and are unavailable
temporarily, causing the error. Try "yum clean all" then rerun the VPN
script.

[1]
https://askubuntu.com/questions/148383/how-to-resolve-dpkg-error-processing-var-cache-apt-archives-python-apport-2-0

>

**Comment by c826** [comment]
@hwdsl2 Thanks , it seems to be a problem with apt-get, I tried link[1], but not work. Then I tried script with CentOS, then it worked.
