### ISSUE TITLE
Error: 'yum install' failed

### ISSUE THREAD

**Issue by jglimmers** [hwdsl2/setup-ipsec-vpn#258]
## VPN setup in progress... Please be patient.

.......
## Installing packages required for the VPN...

Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: centos.ustc.edu.cn
 * extras: mirrors.163.com
 * updates: centos.ustc.edu.cn
Package nss-devel-3.28.4-4.el6_9.x86_64 already installed and latest version
Package nspr-devel-4.13.1-1.el6.x86_64 already installed and latest version
Package 1:pkgconfig-0.23-9.1.el6.x86_64 already installed and latest version
Package pam-devel-1.1.1-24.el6.x86_64 already installed and latest version
Package libcap-ng-devel-0.6.4-3.el6_0.1.x86_64 already installed and latest version
Package libselinux-devel-2.0.94-7.el6.x86_64 already installed and latest version
Package libcurl-devel-7.19.7-53.el6_9.x86_64 already installed and latest version
Package flex-2.5.35-9.el6.x86_64 already installed and latest version
Package bison-2.4.1-5.el6.x86_64 already installed and latest version
Package gcc-4.4.7-18.el6.x86_64 already installed and latest version
Package 1:make-3.81-23.el6.x86_64 already installed and latest version
Package fipscheck-devel-1.2.0-7.el6.x86_64 already installed and latest version
Nothing to do
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: centos.ustc.edu.cn
 * extras: mirrors.163.com
 * updates: centos.ustc.edu.cn
Package ppp-2.4.5-33.0.rhel6.x86_64 already installed and latest version
_**No package xl2tpd available.**_
Nothing to do
Loaded plugins: fastestmirror
Setting up Remove Process
**_No Match for argument: libevent-devel_**
Loading mirror speeds from cached hostfile
 * base: centos.ustc.edu.cn
 * extras: mirrors.163.com
 * updates: centos.ustc.edu.cn
Package(s) libevent-devel available, but not installed.
No Packages marked for removal
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: centos.ustc.edu.cn
 * extras: mirrors.163.com
 * updates: centos.ustc.edu.cn
Package libevent2-devel-2.0.21-2.el6.x86_64 already installed and latest version
Nothing to do

## Installing Fail2Ban to protect SSH...

Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: centos.ustc.edu.cn
 * extras: mirrors.163.com
 * updates: centos.ustc.edu.cn
No package fail2ban available.
Error: Nothing to do
Error: 'yum install' failed.

**Comment by hwdsl2** [comment]
@jglimmers Your system is missing the "EPEL" repository. Try:

yum clean all
yum install epel-release

Then rerun the VPN scripts.
