### ISSUE TITLE
It used to work but now I got error "The L2TP-VPN server did not respond."

### ISSUE THREAD

**Issue by qiulang** [hwdsl2/setup-ipsec-vpn#262]
It used to work. But now after I had successfully run it on digitalocean droplet and tried to connect to it from my mac I got the following error:

"The L2TP-VPN server did not respond. Try reconnecting. If the problem continues, verify your settings and contact your Administrator."

I can ssh to my machine, so how do I debug the issue?

Thanks

**Comment by hwdsl2** [comment]
@qiulang Hello! You may try these additional troubleshooting steps and
check the Libreswan and xl2tpd logs [1].

[1]
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps

**Comment by qiulang** [comment]
Hi 
`ipsec verify `shows everything is ok but I still restart the service ipsec& xl2tpd
Unfortunately I still can not connect the vpn server.

**Comment by hwdsl2** [comment]
@qiulang Check the Libreswan (IPsec) and xl2tpd logs for errors:

```
# Ubuntu & Debian
grep pluto /var/log/auth.log
grep xl2tpd /var/log/syslog

# CentOS & RHEL
grep pluto /var/log/secure
grep xl2tpd /var/log/messages
```

**Comment by qiulang** [comment]
Hi 

```
grep pluto /var/log/auth.log
Nov  7 06:14:08 ubuntu-512mb-sfo1-01 pluto[11794]: "l2tp-psk"[2] 71.6.146.185 #13: ERROR: asynchronous network error report on eth0 (sport=500) for message to 71.6.146.185 port 500, complainant 71.6.146.185: Connection refused [errno 111, origin ICMP type 3 code 3 (not authenticated)]
```

xl2tpd log didn't error.

So how do I  fix it ?

**Comment by hwdsl2** [comment]
@qiulang This error indicates that the IPsec pre-shared key (PSK) entered on your VPN client does not match the IPsec PSK on the VPN server (in file /etc/ipsec.secrets). Remove and re-create [1] your VPN connection, and double check your VPN credentials.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md

**Comment by qiulang** [comment]
Hi, I am quite sure I used the correct PSK. 
But to eliminate the possibility, I run your script again. 

Still same error!

Now I can only guess our evil Great FireWall has upgraded to the next level :(

**Comment by orkenstein** [comment]
Getting the same error in Mac Os native VPN tool. 
But able to connect with Shimo.
