### ISSUE TITLE
andriod 4/7 can connected, can ping dns,but no name resolved

### ISSUE THREAD

**Issue by joevil** [hwdsl2/setup-ipsec-vpn#264]
I can ping 8.8.8.8 and get response from it under 4G CM**CC with VPN connected , but cannot resolve any hostname eg www.google.com or www.youtube.com. with JuiceSSH.
please look at it.

**Comment by hwdsl2** [comment]
@joevil Hello! Can you try rebooting both your VPN client and VPN server,
to clear the DNS cache?

Also, can other apps (besides JuiceSSH) on your Android phone resolve DNS?

Which method (IPsec/L2TP or Cisco IPsec) did you use to connect to the VPN?

Additional troubleshooting information for Android can be found on the
client setup instructions page in this repo.

**Comment by joevil** [comment]
Reboot the server and the phone for multiple times.
Windows & iPhone are fine with the VPN.
Wechat can have data through it(Tencent might have used ip listed in the apps).
Weibo is not working at all.

I am using with the IPSec Xauth PSK on my andirod phone (v4.4.2).
Huawei P10 do not work either.( not sure about the os version)

**Comment by joevil** [comment]
~$ getprop |grep dns
[dhcp.wlan0.dns1]: [10.38.193.1x2]
[dhcp.wlan0.dns2]: [10.38.193.2y5]
[dhcp.wlan0.dns3]: []
[dhcp.wlan0.dns4]: []
[net.change]: [net.dns2]
[net.dns1]: [8.8.8.8]
[net.dns2]: [8.8.4.4]
[net.rmnet0.dns1]: [221.179.3z.7]
[net.rmnet0.dns2]: [120.196.16j.7]

**Comment by joevil** [comment]
ip route show 
default via 10.109.243.16 dev rmnet0
...
...

**Comment by joevil** [comment]
GCE is used as the server side.

**Comment by joevil** [comment]
the dns lookup works with company's wifi which is able to access google, but not work with Ch*in*a Tele*com*

**Comment by joevil** [comment]
seems to be the same issue with https://issuetracker.google.com/issues/36988006
and https://forums.openvpn.net/viewtopic.php?t=18032
any suggestion?

**Comment by hwdsl2** [comment]
@joevil Thanks for the update. From what you described it does look like an Android 4.4 bug. Unfortunately I am not aware of any fix for this other than upgrading your Android. Perhaps you can take a look at other users' suggestions from the links you posted, or try connecting using a different mode, e.g. IPsec/L2TP [1] or IKEv2 [2]. You may also look into alternatives such as OpenVPN [3].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md
[3] https://github.com/Nyr/openvpn-install
