### ISSUE TITLE
Connection with Fedora 24

### ISSUE THREAD

**Issue by djoey123** [hwdsl2/setup-ipsec-vpn#27]
Is it possible to connect Fedora with the Vpn?
I cant find it anywhere how i can connect with linux..

**Comment by hwdsl2** [comment]
To configure an IPsec/L2TP vpn client on Fedora,  refer to this article [1] and its comments.

[1] https://www.moucha.cc/charon/l2tpipsec-vpn-client-on-fedora/

**Comment by djoey123** [comment]
cant get it working i got this error:
[root@localhost Documenten]# ipsec pluto --stderrlog --config /etc/ipsec.conf --nofork
Pluto initialized
May 31 11:15:24: NSS DB directory: sql:/etc/ipsec.d
May 31 11:15:24: NSS readonly initialization ("sql:/etc/ipsec.d") failed (err -8174) 
May 31 11:15:24: FATAL: NSS initialization failure

**Comment by hwdsl2** [comment]
Please see the comments in the article I linked earlier. Specifically, you need to run `ipsec initnss` once before the auto --add command.

**Comment by djoey123** [comment]
now i only got this problem when i use add:
[root@localhost ipsec.d]# ipsec auto --add djoeyvpn
connect(pluto_ctl) failed: Connection refused

**Comment by hwdsl2** [comment]
Did you forget to run "ipsec pluto --stderrlog --config /etc/ipsec.conf --nofork" ? Does the output of "sudo ipsec status" look normal?
