### ISSUE TITLE
 Installing Fail2Ban to protect SSH failed

### ISSUE THREAD

**Issue by Rehtt** [hwdsl2/setup-ipsec-vpn#270]
centos7 x86_64 bbr
![default](https://user-images.githubusercontent.com/28680927/32759123-c08557b0-c922-11e7-9c2c-f45053720359.PNG)

**Comment by hwdsl2** [comment]
@Rehtt Run "yum install epel-release". Then rerun the VPN script.

**Comment by Rehtt** [comment]
run"yum install epel-release" 后还是一样

**Comment by hwdsl2** [comment]
@Rehtt What error did you see when running "yum install epel-release"? Try:

yum clean all
yum install epel-release

**Comment by Rehtt** [comment]
![default](https://user-images.githubusercontent.com/28680927/32759591-239dc222-c925-11e7-84fe-7e660ffc3ea1.PNG)
![1](https://user-images.githubusercontent.com/28680927/32759597-283a480a-c925-11e7-85bd-2fa61eca139e.PNG)

**Comment by hwdsl2** [comment]
@Rehtt Your `EPEL` repository was removed for some reason. Try:

```
yum remove epel-release
yum clean all
yum install epel-release
```

**Comment by Rehtt** [comment]
谢谢，安装成功了
