### ISSUE TITLE
Successfully implemented but issue of network connectivity

### ISSUE THREAD

**Issue by rajaunleashed** [hwdsl2/setup-ipsec-vpn#271]
I have successfully implemented but the problem is that I want the internet network used by users device network not my server network I just want to replace DNS is it possible using IPSec?

**Comment by hwdsl2** [comment]
@rajaunleashed Please clarify your question.

**Comment by rajaunleashed** [comment]
My question is that the ipsec-vpn changes the user public ip and my server bandwidth is used. I want only override DNS using ipsec VPN.

Is this possible?

**Comment by hwdsl2** [comment]
@rajaunleashed Unfortunately what you described is not possible with an IPsec VPN.

**Comment by rajaunleashed** [comment]
ok thank you

**Comment by rajaunleashed** [comment]
I want this kind of functionality to change DNS settings from iOS app.

https://itunes.apple.com/us/app/dns-override-set-dns-for-wi-fi-and-cellular/id1060830093?mt=8
