### ISSUE TITLE
epel-release can't install by yum at AWS redhat 7.4

### ISSUE THREAD

**Issue by lcgogo** [hwdsl2/setup-ipsec-vpn#273]
Hi hwdsl2,

I tried to run the sh at AWS redhat 7.4, but meet followed error:

Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
No package epel-release available.
Error: Nothing to do
Error: 'yum install' failed.

[root@ip-172-31-9-125 setup-ipsec-vpn]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.4 (Maipo)
[root@ip-172-31-9-125 setup-ipsec-vpn]#

**Comment by hwdsl2** [comment]
@lcgogo Hello! See this page [1] and run the command in the RHEL 7 section.
Once it succeeds, comment out the "yum install epel-release" line in the
VPN script before using.

[1] https://aws.amazon.com/premiumsupport/knowledge-center/ec2-enable-epel/

**Comment by lcgogo** [comment]
Many thanks.

Now I meet another issue like below after fix the epel issue.

a - keywords.o
a - interfaces.o
a - lswlog.o
a - lswid.o
a - lswlog_exit.o
In file included from /opt/src/libreswan-3.22/programs/pluto/demux.h:21:0,
                 from /opt/src/libreswan-3.22/programs/pluto/nat_traversal.h:21,
                 from /opt/src/libreswan-3.22/programs/pluto/kernel_pfkey.c:62:
/opt/src/libreswan-3.22/programs/pluto/server.h:21:52: fatal error: event2/event.h: No such file or directory
 #include <event2/event.h> /* from libevent devel */
                                                    ^
compilation terminated.
In file included from /opt/src/libreswan-3.22/programs/pluto/kernel_netlink.c:65:0:
/opt/src/libreswan-3.22/programs/pluto/server.h:21:52: fatal error: event2/event.h: No such file or directory
 #include <event2/event.h> /* from libevent devel */
                                                    ^
compilation terminated.
make[3]: *** [kernel_pfkey.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [kernel_netlink.o] Error 1
make[2]: *** [base] Error 2
make[1]: *** [recursive-base] Error 2
make: *** [recursive-base] Error 2
Error: Libreswan 3.22 failed to build.

**Comment by hwdsl2** [comment]
@lcgogo Try: "yum clean all; yum install libevent-devel"

**Comment by lcgogo** [comment]
[root@ip-172-31-9-125 ~]# yum clean all
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
Cleaning repos: epel rhui-REGION-client-config-server-7 rhui-REGION-rhel-server-releases
              : rhui-REGION-rhel-server-rh-common
Cleaning up everything
Maybe you want: rm -rf /var/cache/yum, to also free up space taken by orphaned data from disabled or removed repos
[root@ip-172-31-9-125 ~]# yum install libevent-devel
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
epel/x86_64/metalink                                                         |  16 kB  00:00:00
epel                                                                         | 4.7 kB  00:00:00
rhui-REGION-client-config-server-7                                           | 2.9 kB  00:00:00
rhui-REGION-rhel-server-releases                                             | 3.5 kB  00:00:00
rhui-REGION-rhel-server-rh-common                                            | 3.8 kB  00:00:00
(1/10): epel/x86_64/group_gz                                                 | 261 kB  00:00:00
(2/10): epel/x86_64/updateinfo                                               | 849 kB  00:00:00
(3/10): rhui-REGION-client-config-server-7/x86_64/primary_db                 | 6.5 kB  00:00:00
(4/10): rhui-REGION-rhel-server-releases/7Server/x86_64/group                | 709 kB  00:00:00
(5/10): rhui-REGION-rhel-server-rh-common/7Server/x86_64/group               |  104 B  00:00:00
(6/10): rhui-REGION-rhel-server-releases/7Server/x86_64/updateinfo           | 2.4 MB  00:00:00
(7/10): rhui-REGION-rhel-server-rh-common/7Server/x86_64/updateinfo          |  32 kB  00:00:00
(8/10): rhui-REGION-rhel-server-rh-common/7Server/x86_64/primary_db          | 119 kB  00:00:00
(9/10): epel/x86_64/primary_db                                               | 6.1 MB  00:00:01
(10/10): rhui-REGION-rhel-server-releases/7Server/x86_64/primary_db          |  44 MB  00:00:01
**No package libevent-devel available.**
Error: Nothing to do

**Comment by lcgogo** [comment]
I fixed it by using rpm installation.

wget ftp://195.220.108.108/linux/centos/7.4.1708/os/x86_64/Packages/libevent-2.0.21-4.el7.x86_64.rpm
wget ftp://195.220.108.108/linux/centos/7.4.1708/os/x86_64/Packages/libevent-devel-2.0.21-4.el7.x86_64.rpm
rpm -ivh libevent-2.0.21-4.el7.x86_64.rpm
rpm -ivh libevent-devel-2.0.21-4.el7.x86_64.rpm

**Comment by hwdsl2** [comment]
@lcgogo Thanks for letting us know!
