### ISSUE TITLE
Multiple windows clients behind NAT not working

### ISSUE THREAD

**Issue by jamsheer** [hwdsl2/setup-ipsec-vpn#274]
Multiple windows clients behind NAT not working - Only one windows client is working at a time, Is there any plan to implement protostack=klips so that multiple windows clients will work ? rather than using protostack=netkey , 

Please advice

**Comment by hwdsl2** [comment]
@jamsheer Hello! Thanks for your report. Multiple windows clients behind the same NAT is indeed a known limitation because they all try to use source ports UDP 500 and 4500 on your router, which results in a conflict. There is currently no plan to implement protostack=klips.
