### ISSUE TITLE
多个客户端在同一个局域网下

### ISSUE THREAD

**Issue by pkanyue** [hwdsl2/setup-ipsec-vpn#275]
使用 IPsec/L2TP的时候，同一个局域网只能连一个client。 
改用 IPsec/XAuth 的时候，不管是不是同一个局域网，都只能连一个client，后边连接的会把前面的顶下线。
有什么好的办法吗？

**Comment by hwdsl2** [comment]
@pkanyue 你好！使用 IPsec/XAuth 模式连接的时候，不管是不是同一个局域网一般都是可以同时连接多个 VPN 客户端的（同一个局域网后面的多个 Windows 客户端除外）。如果不行，你可以尝试重启 VPN 服务器。另外看一下日志：`grep pluto /var/log/auth.log /var/log/secure`。

**Comment by pkanyue** [comment]
@hwdsl2 你好，谢谢你的回答，同一个局域网后面的多个 Windows 客户端除外，这个是不是意味着，同一个局域网下的多个windows电脑是不可以同时连接的？
有什么其他解决的办法吗 ？

**Comment by hwdsl2** [comment]
@pkanyue 是的，因为 Windows 客户端在连接 IPsec 时都会使用 UDP 500 和 4500 作为源端口，造成冲突。这个没有好的解决办法。或许你可以试一下 IKEv2 （见上面链接），或者 OpenVPN [1]。

[1] https://github.com/Nyr/openvpn-install

**Comment by pkanyue** [comment]
@hwdsl2 好的，谢谢，对这个不太懂，如果我在使用 openvpn-install ，是否得先卸载setup-ipsec-vpn ？还是可以共存直接去安装呢 ？

**Comment by hwdsl2** [comment]
@pkanyue 我觉得应该是可以共存直接安装 openvpn-install，不用先卸载。
