### ISSUE TITLE
关于连接的客户端之间，建立虚拟局域网，实现ftp，局域网游戏功能的问题

### ISSUE THREAD

**Issue by VSakuya** [hwdsl2/setup-ipsec-vpn#276]
问题：请问各个客户端之间是否能走tcp，udp协议呢？我现在可以让客户端之间能ping通。
期望结果：
1，1号客户端可以通过vpn连接2号客户端的分享文件夹；
2，两个客户端之间可以游玩一些局域网游戏，通过192.168.42.*的IP即可连接。
我现在的iptables.rule的设置：

>\# Modified by hwdsl2 VPN script
\# Generated by iptables-save v1.6.0 on Thu Nov 16 03:22:04 2017
 *nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -s 192.168.42.0/24 -o ens3 -j
-A POSTROUTING -s 192.168.42.0/24 -o 192.168.42.0/24 -j ACCEPT
-A POSTROUTING -s 192.168.43.0/24 -o ens3 -m policy --dir out --pol none -j
COMMIT
\# Completed on Thu Nov 16 03:22:04 2017
\# Generated by iptables-save v1.6.0 on Thu Nov 16 03:22:04 2017
*filter
:INPUT ACCEPT [2:80]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -p udp -m udp --dport 1701 -m policy --dir in --pol none -j DROP
-A INPUT -m conntrack --ctstate INVALID -j DROP
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p udp -m multiport --dports 500,4500 -j ACCEPT
-A INPUT -p udp -m udp --dport 1701 -m policy --dir in --pol ipsec -j ACCEPT
-A INPUT -p udp -m udp --dport 1701 -j DROP
-A INPUT -p all -s 192.168.42.0/24 -d 192.168.42.0/24 -j ACCEPT
-A INPUT -s 192.168.42.0/24 -j ACCEPT
-A FORWARD -m conntrack --ctstate INVALID -j DROP
-A FORWARD -i ens3 -o ppp+ -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i ppp+ -o ens3 -j ACCEPT
-A FORWARD -p all -s 192.168.42.0/24 -d 192.168.42.0/24 -i ppp+ -o ppp+ -j ACCEPT
-A FORWARD -d 192.168.43.0/24 -i ens3 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 192.168.43.0/24 -o ens3 -j ACCEPT
COMMIT
\# Completed on Thu Nov 16 03:22:04 2017

备注：我觉得我应该是iptables设置有问题，但是我这几天尝试学习修改无果，希望各位大大能帮忙解决！谢谢！

**Comment by hwdsl2** [comment]
@VSakuya 你好！ VPN 脚本默认创建的 IPTables 规则是允许 VPN 客户端之间互相通信的（使用它们分配的 VPN IP 地址比如 192.168.42.*) ，这包括 ICMP ("ping"), TCP, UDP 等。你上面的 IPTables 规则似乎做了一些不正确的修改。建议你在一个全新安装的系统上重新运行脚本搭建 VPN 服务器，再试一下。

**Comment by VSakuya** [comment]
@hwdsl2 感谢回答！我就是使用默认的不行才进行修改的，我测试的游戏是《东方非想天则》，是一款直接输入IP进行联机的格斗游戏，但是连接一直失败。然后测试Ftp也显示ECONNREFUSED。
重置后的iptables：
<code>
\# Modified by hwdsl2 VPN script
\# Generated by iptables-save v1.6.0 on Thu Nov 23 07:27:50 2017
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -s 192.168.42.0/24 -o ens3 -j MASQUERADE
-A POSTROUTING -s 192.168.43.0/24 -o ens3 -m policy --dir out --pol none -j MASQUERADE
COMMIT
\# Completed on Thu Nov 23 07:27:50 2017
\# Generated by iptables-save v1.6.0 on Thu Nov 23 07:27:50 2017
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:ufw-after-forward - [0:0]
:ufw-after-input - [0:0]
:ufw-after-logging-forward - [0:0]
:ufw-after-logging-input - [0:0]
:ufw-after-logging-output - [0:0]
:ufw-after-output - [0:0]
:ufw-before-forward - [0:0]
:ufw-before-input - [0:0]
:ufw-before-logging-forward - [0:0]
:ufw-before-logging-input - [0:0]
:ufw-before-logging-output - [0:0]
:ufw-before-output - [0:0]
:ufw-reject-forward - [0:0]
:ufw-reject-input - [0:0]
:ufw-reject-output - [0:0]
:ufw-track-forward - [0:0]
:ufw-track-input - [0:0]
:ufw-track-output - [0:0]
-A INPUT -p udp -m udp --dport 1701 -m policy --dir in --pol none -j DROP
-A INPUT -m conntrack --ctstate INVALID -j DROP
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p udp -m multiport --dports 500,4500 -j ACCEPT
-A INPUT -p udp -m udp --dport 1701 -m policy --dir in --pol ipsec -j ACCEPT
-A INPUT -p udp -m udp --dport 1701 -j DROP
-A INPUT -j ufw-before-logging-input
-A INPUT -j ufw-before-input
-A INPUT -j ufw-after-input
-A INPUT -j ufw-after-logging-input
-A INPUT -j ufw-reject-input
-A INPUT -j ufw-track-input
-A FORWARD -m conntrack --ctstate INVALID -j DROP
-A FORWARD -i ens3 -o ppp+ -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i ppp+ -o ens3 -j ACCEPT
-A FORWARD -s 192.168.42.0/24 -d 192.168.42.0/24 -i ppp+ -o ppp+ -j ACCEPT
-A FORWARD -d 192.168.43.0/24 -i ens3 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 192.168.43.0/24 -o ens3 -j ACCEPT
-A FORWARD -j ufw-before-logging-forward
-A FORWARD -j ufw-before-forward
-A FORWARD -j ufw-after-forward
-A FORWARD -j ufw-after-logging-forward
-A FORWARD -j ufw-reject-forward
-A FORWARD -j ufw-track-forward
-A FORWARD -j DROP
-A OUTPUT -j ufw-before-logging-output
-A OUTPUT -j ufw-before-output
-A OUTPUT -j ufw-after-output
-A OUTPUT -j ufw-after-logging-output
-A OUTPUT -j ufw-reject-output
-A OUTPUT -j ufw-track-output
COMMIT
\# Completed on Thu Nov 23 07:27:50 2017
</code>
