### ISSUE TITLE
Block list of domain names

### ISSUE THREAD

**Issue by IvanDelsinne** [hwdsl2/setup-ipsec-vpn#277]
Hello,

I successfully installed a functioning VPN thanks to both your tool and guide but I wondered how to block a given list of domains to every VPN user.

I guess some redirects in a /etc/hosts file would work, but I wonder if that would be enough.

After searching a bit about block lists, I haven't found anything definitive, so I wondered if any had a clean way of doing so.

**Comment by hwdsl2** [comment]
@IvanDelsinne Hello! The feature you mentioned (block a given list of domains to every VPN user) is outside the scope of this project. I am not aware of any reliable way to achieve this, because if you block the domains through DNS, the user can just use the domains' IPs directly.
