### ISSUE TITLE
RV042 Cisco Router Configuration

### ISSUE THREAD

**Issue by p2pow350** [hwdsl2/setup-ipsec-vpn#278]
Hi,
not actually an issue but I'm trying to configure a RV042 Cisco VPN router with a server configured with your setup.
As far as I can see the result is a VPN server with a full access through Username/Password Auth but the router only support Tunnel Mode with IPs local/remote (of course providing a PSK).

Do you have any clue for configuring one of these router?
The server connection is working flawlessly as I can connect with my Mac, my PC and my Android phone also.

Thanks so much for your efforts
Max

**Comment by hwdsl2** [comment]
@p2pow350 Hello! Unfortunately I have no idea how to configure a RV042 Cisco VPN router. I would suggest that you try asking on the Libreswan or strongSwan users mailing lists.
