### ISSUE TITLE
Centos 6.9 issue

### ISSUE THREAD

**Issue by mikecastrodemaria** [hwdsl2/setup-ipsec-vpn#279]
When I use the script on Centos 6.9, I have 2 error message:

## Creating VPN configuration...
vpnsetup.sh: line 268: /etc/xl2tpd/xl2tpd.conf:  No such file
......

## Starting services...
FATAL: Could not load /lib/modules/3.2.13-grsec-xxxx-grs-ipv6-64/modules.dep: No such file or directory
...

**Comment by hwdsl2** [comment]
@mikecastrodemaria Hello! Cannot reproduce the first error from your comment on a CentOS 6.9 system. The second error is probably caused by `modprobe -q pppol2tp` in the script and your server's use of a "grsecurity" kernel. This error can be safely ignored.
