### ISSUE TITLE
Windows10成功链接，但是无法访问google

### ISSUE THREAD

**Issue by jinjianan** [hwdsl2/setup-ipsec-vpn#280]
1. 服务器：Vultr CentOS 7
2. 运行后，通过mac链接可访问www.google.com
3. 使用相同账号登录windows可以链接，但是无法访问google，查看IP，已经变更为“VPN服务器的IP”
4. 考虑到是同一路由器下的问题，断开MAC，重新连接。问题依旧如第三点描述。

望不吝赐教

**Comment by hwdsl2** [comment]
@jinjianan See my comments in #243.

**Comment by gzlboy** [comment]
@hwdsl2 vpn已经连接上，看ip已经也是国外的ip了，但win10依然访问不了google和facebook，手机用的IPsec/XAuth 模式 模式没有问题，那个帖子看了，没有帮助=。=

**Comment by jinjianan** [comment]
@hwdsl2  ,  i read the #243 and try but still not work.

**Comment by wyj365372704** [comment]
如果你电脑的dns用的是国内运营商自动分配的，可以修改为阿里dns 223.5.5.5   ，google就可以正常打开了。
