### ISSUE TITLE
DNS lookup issues

### ISSUE THREAD

**Issue by ForPizzaSake** [hwdsl2/setup-ipsec-vpn#281]
Hey there, 

So I'm currently having issues with the DNS lookup when connected to the VPN.
For instance, I can ping Google and I can connect to their site directly using their IP address 
(216.58.206.110) and the page will load perfectly.

The issue is when I try access Google via the address bar by typing https://google.com. It'll just load forever and eventually just timeout.

I've tried restarting both the VPN services, restarted the server, flushed the DNS cache. None of these methods worked.

Any other solutions I should try?

Thanks!

**Comment by hwdsl2** [comment]
@ForPizzaSake Hello! For the DNS lookup issues, is it only Google, or some
websites, or all websites?

You can try replacing the Google public DNS servers 8.8.8.8 and 8.8.4.4 in
both /etc/ipsec.conf and /etc/ppp/options.xl2tpd with other DNS providers
servers of your choice, and restart the IPsec service.

**Comment by ForPizzaSake** [comment]
All websites, even Github.

Also, I'll try that, but ideally using Google's DNS would be preferred.

**Comment by ForPizzaSake** [comment]
I've tried using OpenDNS (208.67.222.222 and 208.67.220.220) which still fails after restarting the VPN service.

**Comment by ForPizzaSake** [comment]
Resolved the issue: My main wireless card was using a static IP address. This *somehow* conflicted with it.
