### ISSUE TITLE
Can not add more users?

### ISSUE THREAD

**Issue by kambit** [hwdsl2/setup-ipsec-vpn#284]
This script just can add one user, how to add more users?

**Comment by rtemelcea** [comment]
You can't connect to same user two times .
What you need to do :

- [ ] sudo su(make sure your root)
- [ ] cd /etc/ppp
- [ ] use your prefered editor to edit chap-secrets file ex : nano chap-secrets
- [ ] here you create a new user with exactly this template
- [ ] "username" l2tpd "user_password" *

**Comment by hwdsl2** [comment]
@kambit Please see "Manage VPN Users" [1].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users.md
