### ISSUE TITLE
how to chance de username and passwd after installing?

### ISSUE THREAD

**Issue by bvans** [hwdsl2/setup-ipsec-vpn#285]

**Comment by rtemelcea** [comment]
What you need to do :

- [ ] - sudo su(make sure your root)
- [ ] - cd /etc/ppp
- [ ] - use your prefered editor to edit chap-secrets file ex : nano chap-secrets
- [ ] - here you create /edit users with exactly this template
- [ ] - "username" l2tpd "user_password" *

**Comment by hwdsl2** [comment]
@bvans  Please see "Manage VPN Users" [1].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users.md
