### ISSUE TITLE
VPN disconnects after 60 minutes

### ISSUE THREAD

**Issue by tomnielsen** [hwdsl2/setup-ipsec-vpn#286]
Steps:
 1. Open a vpn connection
 2. Continue to use connection for 60+ minutes
Result: At exactly 60 minutes, the server closes the vpn connection.

It would be nice to document how to increase this timeout.

Note: The client is MacOS. Have not tested on other platforms.
Note: It may have something to do with the login credentials expiring for username/password combo?

**Comment by hwdsl2** [comment]
@tomnielsen Hello! I've been unable to reproduce your issue (60 minutes disconnect) on MacOS Sierra as a VPN client. Please note that the VPN needs to re-key periodically (either at the request of the VPN client, or initiated by the VPN server). It could be some network-related issues on your client end that prevents successful rekeying. This has nothing to do with the login credentials expiring.
