### ISSUE TITLE
Cannot connect 2 clients at the same time

### ISSUE THREAD

**Issue by RiteshSingh** [hwdsl2/setup-ipsec-vpn#287]
Dear Lin @hwdsl2 ,

Thanks for the Awesome script!!

I am facing a small problem.

It seems that the VPN doesn't allow me to connect two clients at the same time. So, using it on mobile and laptop at the same time is impossible.

Please do look into it.

Thanks again for all your efforts,
Ritesh

**Comment by rtemelcea** [comment]
You can't connect to same user two times . 
What you need to do : 

- sudo su(make sure your root)
-  cd /etc/ppp
- use your prefered editor to edit chap-secrets file ex : nano chap-secrets
- here you create a new user with exactly this template
- "username" l2tpd "user_password" *

**Comment by RiteshSingh** [comment]
Dear @rtemelcea ,

I feel sincere gratitude for your most kind reply and help. Thank you so much!!

I just had one more small question.

**Is there any upper limit to the number of user accounts that can be created using the method mentioned above by you?**

Thanks again,
Ritesh

**Comment by hwdsl2** [comment]
@RiteshSingh Hello! There is no fixed limit to the user accounts that can be created. Refer to [1] for "Manage VPN Users". Regarding connecting multiple VPN clients at the same time, see limitation in "Important Notes" [2].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users.md
[2] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes

**Comment by RiteshSingh** [comment]
Dear Lin @hwdsl2,

Thank you so much for your most kind and gracious reply.

And sorry for asking you a question that has already been documented. I can imagine how easily this could become frustrating. Yet, you are kind and patient enough to help us out. Thanks a lot for that.

I had just one more question. **How would a VPN server created using this script scale? Would such a server be able to handle hundreds or thousands of users at a time (given sufficient resources of course)?**

Thanks a lot again,
Ritesh

**Comment by hwdsl2** [comment]
@RiteshSingh You're welcome. Regarding your last question, I don't know. I
think maybe you can ask on the Libreswan users mailing list.
