### ISSUE TITLE
RPi 3 connection failure with "auth AUTH_ALGORITHM_HMAC_SHA2_512 not implemented or allowed"

### ISSUE THREAD

**Issue by jonalmeida** [hwdsl2/setup-ipsec-vpn#289]
Hey Lin,

I've been trying to run the setup on my Raspberry Pi as I've done previously before on other machines, but I haven't seen this error message below before. I was wondering if you knew what I could do to fix it.

I thought this might be related to #102 but that person didn't have the kmodule loaded. This seems to have it, but it's still failing with the same unimplemented error for the auth algorithm.

I also had a look at [other guides](https://blog.elasticbyte.net/setting-up-a-native-cisco-ipsec-vpn-server-using-a-raspberry-pi/) that used the same script and I don't see other users facing the same issue, so I figured that it isn't a limitation on the RPi itself.

Any help would be appreciated! Thank you again!

```
Dec  6 23:09:53 euler pluto[19941]: | failed to install outgoing SA: 0
Dec  6 23:09:53 euler pluto[19941]: "l2tp-psk"[3] 195.251.50.56 #10: deleting state (STATE_QUICK_R0)
Dec  6 23:09:56 euler pluto[19941]: "l2tp-psk"[3] 195.251.50.56 #5: the peer proposed: 184.105.50.202/32:17/1701 -> 192.0.0.4/32:17/0
Dec  6 23:09:56 euler pluto[19941]: "l2tp-psk"[3] 195.251.50.56 #11: responding to Quick Mode proposal {msgid:4c2bb0a9}
Dec  6 23:09:56 euler pluto[19941]: "l2tp-psk"[3] 195.251.50.56 #11:     us: 192.168.86.79[184.105.50.202]:17/1701
Dec  6 23:09:56 euler pluto[19941]: "l2tp-psk"[3] 195.251.50.56 #11:   them: 195.251.50.56[192.0.0.4]:17/0
Dec  6 23:09:56 euler pluto[19941]: "l2tp-psk"[3] 195.251.50.56 #11: ESP transform ESP_AES(256) / auth AUTH_ALGORITHM_HMAC_SHA2_512 not implemented or allowed
Dec  6 23:09:56 euler pluto[19941]: "l2tp-psk"[3] 195.251.50.56 #11: setup_half_ipsec_sa() hit fail:
Dec  6 23:09:56 euler pluto[19941]: | failed to install outgoing SA: 0
Dec  6 23:09:56 euler pluto[19941]: "l2tp-psk"[3] 195.251.50.56 #11: deleting state (STATE_QUICK_R0)
Dec  6 23:09:59 euler pluto[19941]: "l2tp-psk"[3] 195.251.50.56 #5: the peer proposed: 184.105.50.202/32:17/1701 -> 192.0.0.4/32:17/0
Dec  6 23:09:59 euler pluto[19941]: "l2tp-psk"[3] 195.251.50.56 #12: responding to Quick Mode proposal {msgid:4c2bb0a9}
Dec  6 23:09:59 euler pluto[19941]: "l2tp-psk"[3] 195.251.50.56 #12:     us: 192.168.86.79[184.105.50.202]:17/1701
Dec  6 23:09:59 euler pluto[19941]: "l2tp-psk"[3] 195.251.50.56 #12:   them: 195.251.50.56[192.0.0.4]:17/0
Dec  6 23:09:59 euler pluto[19941]: "l2tp-psk"[3] 195.251.50.56 #12: ESP transform ESP_AES(256) / auth AUTH_ALGORITHM_HMAC_SHA2_512 not implemented or allowed
Dec  6 23:09:59 euler pluto[19941]: "l2tp-psk"[3] 195.251.50.56 #12: setup_half_ipsec_sa() hit fail:
Dec  6 23:09:59 euler pluto[19941]: | failed to install outgoing SA: 0

```

**Comment by hwdsl2** [comment]
@jonalmeida Hello! Try removing the unsupported SHA2_512 algorithm from ipsec.conf. This change is specific to the Raspberry Pi. If you're running Raspbian, the latest version of VPN setup script should automatically take care of this. Ref: [1].

```
sed -i '/phase2alg/s/,aes256-sha2_512//' /etc/ipsec.conf
service ipsec restart
```

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/vpnsetup.sh#L284

**Comment by jonalmeida** [comment]
Yes, that worked. I realized I was still using an older version of the setup script, but I'm also using Ubuntu Mate on the RPi.

Thanks for responding so quickly! :)
