### ISSUE TITLE
Running "echo c myvpn > /var/run/xl2tpd/l2tp-control" does not create ppp interface.

### ISSUE THREAD

**Issue by munikarmanish** [hwdsl2/setup-ipsec-vpn#290]
#### Versions:
- strongswan == 5.6.1
- xl2tpd == 1.3.10
- os == latest arch linux

#### Description:
All commands upto `ipsec up myvpn` run successfully. But when I run `echo "c myvpn" > /var/run/xl2tpd/l2tp-control`, no new network interface is created (and hence I cannot run subsequent commands).

#### Expected behavior:
When i send command to `l2tp-control`, I expect a network interface (eg: ppp0) to be created.

#### `journalctl` output (last few lines):
```
...
Dec 09 00:28:17 lenovopc ipsec[8887]: 13[IKE] IKE_SA myvpn[1] established between 192.168.10.2[192.168.10.2]...96.88.26.209[96.88.26.209]
Dec 09 00:28:17 lenovopc ipsec[8887]: 13[IKE] scheduling reauthentication in 3294s
Dec 09 00:28:17 lenovopc ipsec[8887]: 13[IKE] maximum IKE_SA lifetime 3474s
Dec 09 00:28:17 lenovopc ipsec[8887]: 13[ENC] generating QUICK_MODE request 663705518 [ HASH SA No KE ID ID NAT-OA NAT-OA ]
Dec 09 00:28:17 lenovopc ipsec[8887]: 13[NET] sending packet: from 192.168.10.2[4500] to 96.88.26.209[4500] (356 bytes)
Dec 09 00:28:17 lenovopc ipsec[8887]: 14[NET] received packet: from 96.88.26.209[4500] to 192.168.10.2[4500] (308 bytes)
Dec 09 00:28:17 lenovopc ipsec[8887]: 14[ENC] parsed QUICK_MODE response 663705518 [ HASH SA No KE ID ID NAT-OA NAT-OA ]
Dec 09 00:28:17 lenovopc ipsec[8887]: 14[IKE] CHILD_SA myvpn{1} established with SPIs c06a9768_i 0796d331_o and TS 192.168.10.2/32[udp/l2f] === 96.88.26.209/32[udp/l2f]
Dec 09 00:28:17 lenovopc ipsec[8887]: 14[ENC] generating QUICK_MODE request 663705518 [ HASH ]
Dec 09 00:28:17 lenovopc ipsec[8887]: 14[NET] sending packet: from 192.168.10.2[4500] to 96.88.26.209[4500] (60 bytes)
Dec 09 00:28:17 lenovopc ipsec[8887]: 06[KNL] creating acquire job for policy 192.168.10.2/32[udp/l2f] === 96.88.26.209/32[udp/l2f] with reqid {1}
Dec 09 00:28:17 lenovopc charon[8906]: 08[IKE] sending keep alive to 96.88.26.209[4500]
Dec 09 00:28:17 lenovopc ipsec[8887]: 06[CFG] trap not found, unable to acquire reqid 1
Dec 09 00:28:37 lenovopc charon[8906]: 15[IKE] sending keep alive to 96.88.26.209[4500]
Dec 09 00:28:46 lenovopc xl2tpd[8928]: xl2tpd[8928]: Maximum retries exceeded for tunnel 21931.  Closing.
Dec 09 00:28:46 lenovopc xl2tpd[8928]: xl2tpd[8928]: Connection 0 closed to 96.88.26.209, port 1701 (Timeout)
Dec 09 00:28:57 lenovopc charon[8906]: 10[IKE] sending keep alive to 96.88.26.209[4500]
Dec 09 00:29:17 lenovopc xl2tpd[8928]: xl2tpd[8928]: Unable to deliver closing message for tunnel 21931. Destroying anyway.
Dec 09 00:29:17 lenovopc charon[8906]: 08[IKE] sending keep alive to 96.88.26.209[4500]
Dec 09 00:29:37 lenovopc charon[8906]: 11[IKE] sending keep alive to 96.88.26.209[4500]

```

Looks like the issue is `[CFG] trap not found, unable to acquire reqid 1`! But I don't understand what it means. Can anyone help me solve it?

**Comment by Croissong** [comment]
I started having the the same issue this week.

**Comment by munikarmanish** [comment]
@Croissong you mean you had the same config files working fine last week?

What's interesting is that these instructions (linux client) are working fine in my office computer (Xubuntu 17.10), but not in my home Arch Linux laptop. The only difference I can guess are version numbers. Ubuntu's strongswan/xl2tpd are *slightly* older than Arch's. I tried downgrading those packages in Arch, but the issue persists.

**Comment by Croissong** [comment]
@munikarmanish yes same config was working last week. I am also on arch. However i cannot spot `trap not found, unable to acquire reqid` in my logs, i am only getting `Maximum retries exceeded for tunnel`.

**Comment by Croissong** [comment]
With linux-lts its working

**Comment by munikarmanish** [comment]
@Croissong so could it be a *linux kernal* issue? or maybe *systemd*? Let me try with **linux-lts** too to verify...

**Comment by munikarmanish** [comment]
I can confirm that this issue is solved in Arch Linux by using Linux LTS kernel. 👍

Thanks @Croissong for the help!

**Comment by Croissong** [comment]
This issue is also discussed here https://github.com/libreswan/libreswan/issues/140
