### ISSUE TITLE
Full path to ipsec command on webmin

### ISSUE THREAD

**Issue by david-xhf** [hwdsl2/setup-ipsec-vpn#292]
Hi, I am using webmin to admin it.
The webmin asks for 'module configuration' below:

FreeSWAN IPsec configuration file           |  /etc/ipsec.conf
IPsec secrets file                                        |  /etc/ipsec.d/passwd
Full path to ipsec command                     |  /etc/ipsec.conf
Policy files directory                                  |  /etc/ipsec.d/policies
Command to start IPsec server                 |  /user/local/sbin/ipsec start
Command to stop IPsec server                 |  /user/local/sbin/ipsec stop
Command to re-start IPsec server            | /user/local/sbin/ipsec restart
File to which IPsec messages are logged  |  /var/log/messages

But it says: **The FreeSWAN command /etc/ipsec.conf was not found on your system or is not the right program. Maybe it is not installed, or your module configuration is incorrect.**

Could you help me fill in those configurations? Thanks so much!

**Comment by hwdsl2** [comment]
@david-xhf Hello! Unfortunately Webmin configuration is outside the scope of this project.
