### ISSUE TITLE
A few questions 

### ISSUE THREAD

**Issue by canusuck** [hwdsl2/setup-ipsec-vpn#301]
1. How to change the preset vpn: preshared key name and other moments.
2. How to get rid of dnsleaks? Use dnsmasq on the host machine, you can tell by the settings then.
3. Can I do it and if I can do it better: Double / Triple / Quad bundle for VPN
4. How to change ports to others? How to change ports if VPN is already installed on the server? Where to look ?

In advance I thank for answers

**Comment by hwdsl2** [comment]
@canusuck Hello! To answer your questions ...

1. Please refer to "Manage VPN Users" [1].
2. DNS leaks are usually an issue with your VPN client and outside the scope of this project.
3. Not sure what you are talking about here.
4. There is no easy way to change ports for IPsec/L2TP VPNs.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users.md
