### ISSUE TITLE
IPsec/XAuth connection established, but no internet connection via Android 7.0 smartphone.

### ISSUE THREAD

**Issue by Wikinaut** [hwdsl2/setup-ipsec-vpn#303]
I installed IPsec using your script and established the client-server connection but cannot use the internet tunnel from my smartphone.

Pls. can you assist, what else can I check?

I already checked https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting but no success.

Client
* IPsec/XAuth
* Android 7.0

Server
* debian 9 fully patched
* using your setup script
* firewall ports open:  udp 500,4500,1701

```
ipsec whack --trafficstatus:

006 #2: "xauth-psk"[2] xxx.xxx.xxx.xxx, username=vpnuser, type=ESP, add_time=1515369985, inBytes=0, outBytes=0, lease=192.168.43.10/32
```

iptables.rules:

```
# Modified by hwdsl2 VPN script
# Generated by iptables-save v1.6.0 on Tue Dec 26 03:46:57 2017
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -s 192.168.42.0/24 -o eth0 -j MASQUERADE
-A POSTROUTING -s 192.168.43.0/24 -o eth0 -m policy --dir out --pol none -j MASQUERADE
COMMIT
# Completed on Tue Dec 26 03:46:57 2017
# Generated by iptables-save v1.6.0 on Tue Dec 26 03:46:57 2017
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -p udp -m udp --dport 1701 -m policy --dir in --pol none -j DROP
-A INPUT -m conntrack --ctstate INVALID -j DROP
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p udp -m multiport --dports 500,4500 -j ACCEPT
-A INPUT -p udp -m udp --dport 1701 -m policy --dir in --pol ipsec -j ACCEPT
-A INPUT -p udp -m udp --dport 1701 -j DROP
-A FORWARD -m conntrack --ctstate INVALID -j DROP
-A FORWARD -i eth0 -o ppp+ -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i ppp+ -o eth0 -j ACCEPT
-A FORWARD -s 192.168.42.0/24 -d 192.168.42.0/24 -i ppp+ -o ppp+ -j ACCEPT
-A FORWARD -d 192.168.43.0/24 -i eth0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 192.168.43.0/24 -o eth0 -j ACCEPT
-A FORWARD -j DROP
COMMIT
# Completed on Tue Dec 26 03:46:57 2017
```

updated 28.02.2018

Not working on
* HUAWEI P8 LITE 2017
* Android 7.0
* Build PRA-LX1C432B194

**Comment by ShadowQuark** [comment]
Hi,

I met exact the same problem. I tested the connection from Android, iOS, Window, and Mac devices. All other 3 platforms work properly. Android is the only problematic selection. Probably the server works well, but there are some problems in the default Android VPN Client, like secure check settings, and so on...

I am also looking forward the solution for such problem.

**Comment by Wikinaut** [comment]
I suppose a server problem (firewall settings or so), but I'm not sure.

**Comment by ShadowQuark** [comment]
Maybe we can try some 3rd party VPN client on Android.

**Comment by RacerBas** [comment]
I am experiencing the same issue, however when I tested it yesterday on 4G it worked and today it doesn't anymore. Restarting the service or the entire server does not seem to solve it

**Comment by joevil** [comment]
Bothered by this same issue as well for a long time(#264),  now I have the Android 8.0 phone but still not work.

**Comment by Wikinaut** [comment]
It *is* working on
* HUAWEI P8 LITE
* Android 6.0
* Build ALE-L21C432B614

**Comment by hwdsl2** [comment]
To everyone commenting on this issue - Does this only occur for IPsec/XAuth
mode (i.e. Can you try using IPsec/L2TP mode [1] and see if it works fine
on Android 7.0?)

Also, please try the troubleshooting steps in [2], especially number 3.

It would be very helpful for further troubleshooting if you all can post
Libreswan or Xl2tpd logs when the issue occurred, see [3].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md
[2]
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#android-6-and-above
[3]
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps

**Comment by Wikinaut** [comment]
@hwdsl2 this
> Edit /etc/ipsec.conf on the VPN server. Find sha2-truncbug=yes and replace it with sha2-truncbug=no, indented with two spaces. Save the file and run service ipsec restart.

***solved*** my issue (Android 7.0 on HUAWEI P8 Lite 2017)

Info to you: the line ```sha2-truncbug=yes``` was not present.
Perhaps you also add the information, that this line should be added in the section ```conn xauth-psk```.

**Comment by Wikinaut** [comment]
@hwdsl2 I have another, question, issue. I will file this separately.

As I reported this issue here, I close it now.

**Comment by Wikinaut** [comment]
sha2-truncbug=yes
* not working on Android 7.0

sha2-truncbug=no
* not working with Android 6.0

**Comment by Wikinaut** [comment]
@hwdsl2 I noticed, that both Android are **working** with other IPSec Xauth with PSK servers - so this issue still looks to be an issue of one of the packages used in /hwdsl2/setup-ipsec-vpn .

**Comment by hwdsl2** [comment]
@Wikinaut The sha2-truncbug line can be found in the “conn shared” section.

What you observed in your previous comment is due to a bug [1] in Android
6.0 which requires sha2-truncbug=yes. Unfortunately there is not much we
can do to be compatible with both Android 6.0 and 7.0.

[1] https://libreswan.org/wiki/FAQ#Configuration_Matters

**Comment by Wikinaut** [comment]
> "conn shared"
uh, yes, sorry. I will correct it above.

**Comment by hwdsl2** [comment]
@Wikinaut Can you give us details of the other IPsec XAuth server where
both Android 6 and 7 are working?

**Comment by Wikinaut** [comment]
@hwdsl2 wrote
> What you observed in your previous comment is due to a bug [1] in Android 6.0 which requires sha2-truncbug=yes. Unfortunately there is not much we can do to be compatible with both Android 6.0 and 7.0.

Fritz.box (router by AVM) with IPSec XAuth with PSK works with my both Androids - so there is a way (somehow. Unfortunately I cannot help to find out, how).

**Comment by Wikinaut** [comment]
Fritz box 7490
https://en.avm.de/products/fritzbox/fritzbox-7490/

**Comment by Wikinaut** [comment]
Perhaps interesting detail to know for you (this is, what I wanted to report separately):

The fritz-box-VPN does require (and this is really needed) the username (e.g. "vpnuser") **also** as string in the IPSec-ID field. if I leave the field empty (your software does not work, if I fill the IPSec-ID field with "vpnuser"). it it not even connecting to my fritz-box-VPN.

Is this a hint?

**Comment by alhinai21** [comment]
I have same issue it connect but no internet connection, i try it on android 7, 8 and p beta

On server side, I try cent, Debian and the docker container, all on vultr

Any logs needed to solve this issue please tell me

**Comment by hwdsl2** [comment]
@alhinai21 Have you tried toggling sha2-truncbug in /etc/ipsec.conf (yes or
no) and restart ipsec service?

For logs “grep pluto /var/log/auth.log /var/log/secure”

**Comment by saikiran91** [comment]
> @alhinai21 Have you tried toggling sha2-truncbug in /etc/ipsec.conf (yes or no) and restart ipsec service? For logs “grep pluto /var/log/auth.log /var/log/secure”

It worked for me after setting sha2-truncbug to no but is there any drawback?

**Comment by hwdsl2** [comment]
@saikiran91 You should be fine with setting `sha2-truncbug=no`.

**Comment by letoams** [comment]
The drawback is that now only android
Phones work, not iPhones, windows, macs, etc

**Comment by tonycai** [comment]
I have encountered the issue on iPhone 8 Plus but resolved by the below manipulates. 

docker exec -it ipsec-vpn-server env TERM=xterm bash -l

apt-get update && apt-get -y install nano

# cat /etc/ipsec.conf
# nano /etc/ipsec.conf
# use sha2-truncbug=yes replace sha2-truncbug=no

then

# service ipsec restart

exit

**Comment by saikiran91** [comment]
> The drawback is that now only android Phones work, not iPhones, windows, macs, etc
> […](#)
> Sent from my iPhone
> On Sep 22, 2019, at 01:15, saikiran91 ***@***.***> wrote: @alhinai21 Have you tried toggling sha2-truncbug in /etc/ipsec.conf (yes or no) and restart ipsec service? For logs “grep pluto /var/log/auth.log /var/log/secure” It worked for me after setting sha2-truncbug to no but is there any drawback? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

@letoams I worked on iOS as well.

**Comment by danishIlyasco** [comment]
@hwdsl2 , @letoams Internet connectivity problem facing(unable to ping android devices) for devices connected via Ipsec XAuth RSA(certificates).
Below is my ipsec.conf with the default Iptables.
config setup
  protostack=netkey
  virtual-private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:!192.168.42.0/24,%v4:!192.168.43.0/24

conn shared
  left=%defaultroute
  leftid=5.57.55.66 #please this is dummy public ip of my azure linux Machine running as server
  right=%any
  encapsulation=yes
  pfs=no
  rekey=no
  keyingtries=5
  dpddelay=30
  dpdtimeout=300
  dpdaction=clear
  ikev2=never
  ike=aes256-sha2;modp2048,aes128-sha2;modp2048,aes256-sha1;modp2048,aes128-sha1;modp2048,aes256-sha2;modp1024,aes128-sha1;modp1024
  phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes256-sha2_512,aes128-sha2,aes256-sha2
  ikelifetime=24h
  salifetime=24h
  sha2-truncbug=no

conn xauth-rsa
  auto=add
  authby=rsasig
  leftcert=BBServerCert
  leftrsasigkey=%cert
  leftsendcert=always
  leftsubnet=0.0.0.0/0
  rightaddresspool=192.168.43.10-192.168.43.250
  rightid=%fromcert
  rightrsasigkey=%cert
  modecfgdns="8.8.8.8 8.8.4.4"
  leftxauthserver=yes
  rightxauthclient=yes
  leftmodecfgserver=yes
  rightmodecfgclient=yes
  modecfgpull=yes
  xauthby=alwaysok
  fragmentation=yes
  also=shared
