### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by canusuck** [hwdsl2/setup-ipsec-vpn#305]
1. How many people can simultaneously connect using the L2TP / IPsec protocol?
2. How to get rid of DNSLeaks? For example, I have a server in Sweden, how can I receive only DNS Sweden?
3. How to connect correctly to Linux?
4. Is ikev2 safer than l2tp? Is it faster? How much can it be used at the same time?

Thank you in advance for your response.

**Comment by hwdsl2** [comment]
@canusuck Hello! To answer your questions ...

1. There is no definite answer to this, it depends on your server's CPU/RAM/Bandwidth, etc.
2. DNS leaks are usually an issue with your VPN client and outside the scope of this project.
3. For configuring Linux clients, please see [1].
4. IKEv2 is a new version of the IKE protocol and has many advantages [2].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#linux
[2] https://en.wikipedia.org/wiki/Internet_Key_Exchange#Improvements_with_IKEv2
