### ISSUE TITLE
Doesn't hide IP address

### ISSUE THREAD

**Issue by kpennell** [hwdsl2/setup-ipsec-vpn#306]
I followed this tutorial to a T and set it up on my mac and what not. It seemed to be running but did not hide my ip address at all. Googled 'my ip address' and it didn't change.

**Comment by hwdsl2** [comment]
Hello! Please check if you’ve enabled the “Send all traffic over VPN
connection”. See [1]. Also, check the box to show VPN status in the menu
bar and make sure it shows connected.

After successful connection google “my ip” and you should see your VPN
server IP.

[1] https://support.apple.com/kb/PH25563?locale=en_US

**Comment by kpennell** [comment]
yep!
