### ISSUE TITLE
DNS污染问题

### ISSUE THREAD

**Issue by lujunda** [hwdsl2/setup-ipsec-vpn#310]
您好，在win10下使用shrew soft vpn client，好像dns解析的流量没有走vpn。
当地的dns污染很严重，google和youtube的解析结果都是错误ip，貌似所有走udp 53的解析请求都会被篡改，不管设置什么dns，google等网站的解析结果都是错误的。
所以现在出现了个很奇怪的现象，iphone、macos都可以正常使用vpn（它们的dns解析流量应该也是走vpn的），win10连接vpn却无法访问google等网站。

现在的解决方案是在win10上搭了个dnscrypt，但这样需要每次都打开两个软件才能科学上网，请问有没有什么其他推荐的解决方法呢。

**Comment by hwdsl2** [comment]
@lujunda 你好！你所说的在Win10下使用Shrew Soft VPN Client，DNS解析的流量没有走VPN的问题，我之前也遇到过。这个Shrew Soft VPN 软件已经几年没有更新了，它并不支持 Win10，存在许多 bug。据我所知，目前并没有好的解决方法。
