### ISSUE TITLE
cisco ipsec can't be established after exec "apt upgrade -y" in Ubuntu 16.04.3

### ISSUE THREAD

**Issue by yadee** [hwdsl2/setup-ipsec-vpn#311]
system:Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-109-generic x86_64)
I'm using Aliyun, All thing is OK before upgrade.

**Comment by yadee** [comment]
ps:
I launch new instance with ubuntu16.04, first exec "apt update && apt upgrade -y", then set up vpn via "wget https://git.io/vpnsetup -O vpnsetup.sh && sudo sh vpnsetup.sh" . It's also failed.

**Comment by hwdsl2** [comment]
@yadee Hello! I've been unable to reproduce your issue on a fully updated Ubuntu 16.04 system. I suggest that you re-install a fresh Ubuntu OS (after backing up your data) and re-run the VPN setup script.
