### ISSUE TITLE
VPN L2TP Server accepts local network connections only 

### ISSUE THREAD

**Issue by DaveJunior** [hwdsl2/setup-ipsec-vpn#312]
Dears,

I’ve successufully instaled this script on two machines. A Ubuntu Server 16.04.3 LTS and on a Raspberry with Jessie.

While I,m on my own network, The VPN Works fine. But when I try to Connect over The internet, I got no connection.

I’ve already open the doors on my router and even let the server Ip as the DMZ by the router.

To test network issues, I have been able to use SSH to this Server over the internet using the DDNS name that I’ve configured. 

So, the router is redirecting the connections tho the server properly.

The alow Ipsec passthrough and PPTP passthrought are also checked too.

I’ve also insert iptables -F and -X with no success.

Before setting the router as DMZ to my Server, I have set the doors forwarding with no success too.

Is there something else that I’m missing?

My router has a VPN feature wich has no tunnel or something else configured. 

Is that possible that routers lime that still watching VPN doors itself despite the DMZ configured?

Thanks

**Comment by hwdsl2** [comment]
@DaveJunior Hello! In this case it would be helpful to check the IPsec and xl2tpd logs using the steps in [1]. Try connecting your VPN client, then check the server logs. If no new log appears, then there could be an issue with port forwarding on your router for the VPN, or some other issues that make the VPN server not accessible from the Internet.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps
