### ISSUE TITLE
比较基础的问题，aws东京，无法连接，不确定是不是端口被墙了

### ISSUE THREAD

**Issue by lzj1989712** [hwdsl2/setup-ipsec-vpn#313]
客户端使用ios 11

采用l2tp连接

![image](https://user-images.githubusercontent.com/5946974/35499191-4fdd90c4-050c-11e8-92ab-c72f3ac5224b.png)

采用xauth模式

![image](https://user-images.githubusercontent.com/5946974/35499204-5ee0afc0-050c-11e8-99a1-0b6af0a7955a.png)

**Comment by hwdsl2** [comment]
@lzj1989712 你好！你的第一部分日志说明你在使用 XAuth 模式连接之后立即尝试切换为 L2TP 模式，这种情况下服务器还没有忘记上次的 XAuth 模式，所以不能连接成功。你需要等几分钟，或者重启服务器后再试。你的第二部分日志看起来好像是端口被屏蔽了。
