### ISSUE TITLE
Shrew VPN Clients kicking each other off

### ISSUE THREAD

**Issue by deneb711** [hwdsl2/setup-ipsec-vpn#314]
First of all, thanks for developing and supporting this script! I've configure VPN and have been able to connect without issue via LT2P/IPSEC. Upon reading through your issues, I realized that if I want to have multiple users connected at the same time, I'll have to move to Cisco IPsec with Xauth. I've done so, however, I still seem to be running into some issues. While a Max OSX client can coexist with Shrew clients, it seems that I can't have more than one Shrew client connected at the same time. The moment a second client connects, the previous client gets kicked off. The logs on my VPN server indicate the following:

route to peer's client conflicts with "xauth-psk"[201] xx.xxx.xx.xxx xx.xxx.xx.xxx; releasing old connection to free the route

Not sure why this is happening since I was under the impression that using Cisco IPSec with Xauth would allow multiple users to connect. These two specific users are logging in remotely from completely different networks.

Your help is much appreciated!

**Comment by nexus38** [comment]
Thank you for developing and supporting this script. I have the exact same issue and the issue is when 2nd user connected to VPN the server kicks 1st user. I also followed the instructions on [manage-users.md](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users.md) but it did not work.

Your help is much appreciated!

**Comment by hwdsl2** [comment]
@deneb711 @nexus38 Hello! For Windows clients (using the native VPN client OR the Shrew Soft VPN client) that are behind the same NAT (e.g. home router), it is generally not possible to connect multiple IPsec/XAuth clients simultaneously, because they try to use the same outgoing ports on the router, resulting in a conflict.

On the other hand, if this issue (Shrew VPN Clients kicking each other off) occurs even for clients behind different networks, then it looks like a bug in the Shrew Soft VPN client. Unfortunately it is very old and haven't been updated for several years.

**Comment by MikeLund** [comment]
@hwdsl2 Can you please clarify what the readme says then?

[README.md](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md) says this:
> The same VPN account can be used by your multiple devices. However, due to an IPsec/L2TP limitation, **if you wish to connect multiple devices simultaneously from behind the same NAT (e.g. home router), you must use only IPsec/XAuth mode**.

This implies that multiple IPsec/XAuth clients _should_ work behind the same NAT. But now you're saying:
> it is generally not possible to connect multiple IPsec/XAuth clients simultaneously

So is it somehow possible to use multiple IPsec/XAuth clients behind the same NAT? And if so, how?
I've created two IPsec/XAuth users. They both work fine (one client on macOS, one on Android), but if connected behind the same NAT, they kick each other off.

So I would appreciate you to clarify this. Thank you for your time!

**Comment by hwdsl2** [comment]
@MikeLund My comment above was referring to Windows clients in particular -

It is generally not possible to connect multiple *Windows* IPsec/XAuth
clients simultaneously from behind the same NAT (because they try to use
the same outgoing (source) ports on your router, resulting in a conflict).

**Comment by MikeLund** [comment]
I've already upgraded. But I may have found the root of the issue though: clients behind same NAT are given the same IP lease (from the default range in your setup, 192.168.43.10).

```
:~# ipsec whack --trafficstatus
006 #228: "xauth-psk"[10] 202.x.x.111, username=mobile, type=ESP, add_time=1518445965, inBytes=32216, outBytes=163708, lease=192.168.43.10/32
006 #232: "xauth-psk"[10] 202.x.x.111, username=macos, type=ESP, add_time=0, inBytes=98529, outBytes=145916, lease=192.168.43.10/32
```

If I connect again from outside the NAT (using 4G or something), I get a unique lease IP:
```
:~# ipsec whack --trafficstatus
006 #232: "xauth-psk"[10] 202.x.x.111, username=macos, type=ESP, add_time=1518446058, inBytes=207312, outBytes=451325, lease=192.168.43.10/32
006 #234: "xauth-psk"[11] 77.x.x.56, username=mobile, type=ESP, add_time=1518446090, inBytes=1316, outBytes=2597, lease=192.168.43.13/32
```

Guess I make issue on it, hopefully it's a real bug and not just config problem :)

**Comment by almerion** [comment]
I have same issue on Linux\Debian. Script is working well for one user but when second user connect, server kicking first user.

**Comment by letoams** [comment]
note libreswan 3.26 was released that addresses the issue related to bad lease ip re-use
