### ISSUE TITLE
请问为什么l2tp无法连接，ipsec则可以(IOS)

### ISSUE THREAD

**Issue by dilllay** [hwdsl2/setup-ipsec-vpn#318]
你好，我无论使用docker安装还是脚本安装之后都无法使用单纯的l2tp连接，IOS中的ipsec则可以。需求是这样的，我的路由只能使用l2tp和pptp，所以一直没办法成功连接vps上搭建的vpn。我曾经读过已经closed的issue中提到不要再同一个路由后面使用不相同的方式来连接vpn，但我手机使用4g，路由上使用的宽带同样不能连接l2tp。我部署的环境是google cloud platform，外部防火墙已经开放了udp1701，500，4500端口。

**Comment by hwdsl2** [comment]
@dilllay 你好！你所说的单纯的 L2TP （无 IPsec）是不受安装脚本支持的，无法连接是正常的。该模式下的数据传输无任何加密，所以用它来连接 VPN 没有意义。这个模式之所以在某些路由器上存在，可能是为了和俄罗斯的某些因特网提供商兼容而添加的。

**Comment by dilllay** [comment]
@hwdsl2 感谢回复，我非常了解ipsec的好处和作用，但在实际生活中硬性环境因素导致无法选择，现在确认知道了原因之后只好另寻其他方法去解决，再次感谢
