### ISSUE TITLE
VPN can't work with Debian 9

### ISSUE THREAD

**Issue by monk0** [hwdsl2/setup-ipsec-vpn#319]
I set up the VPN according to the course, has been the normal work, but recently suddenly even not work, log as follows, please help.

grep pluto /var/log/auth.log
![image](https://user-images.githubusercontent.com/13928223/36153884-b36a350c-110a-11e8-9b9f-5e287a039455.png)

grep xl2tpd /var/log/syslog
![image](https://user-images.githubusercontent.com/13928223/36153924-caa5f788-110a-11e8-9fc9-12ee003ef54f.png)

**Comment by hwdsl2** [comment]
@monk0 Hello! Your logs show that your connection is blocked or interfered with by a firewall. This is not an issue with the VPN scripts. I suggest that you try alternative solutions such as Shadowsocks.
