### ISSUE TITLE
Log user connections

### ISSUE THREAD

**Issue by tedens** [hwdsl2/setup-ipsec-vpn#320]
Im looking to log when a user connects/disconnects mostly for security auditing. I looked through the documentation and did not see anything about allowing a log file. No syslog has be populated and there is no auth.log in /var/log. I see that when a user connects some info does go into messages and secure but not the actual username connecting (l2tpd by the way). Any help is greatly appreciated.

**Comment by hwdsl2** [comment]
@tedens Hello! Libreswan logs to `/var/log/auth.log` on Ubuntu/Debian, and to `/var/log/secure` on CentOS. For xl2tpd, it logs to `/var/log/syslog` on Ubuntu/Debian, and to `/var/log/messages` on CentOS.

If you wish to additionally log IPsec/L2TP usernames, add a line `debug` to your `/etc/ppp/options.xl2tpd` file, and run `service xl2tpd restart`. Then check the respective log files as mentioned above.

**Comment by tedens** [comment]
Thank you for that information. I already had debug enabled but still can not see the actual username that is connecting. Only their IP address.

**Comment by man20820** [comment]
> @tedens Hello! Libreswan logs to `/var/log/auth.log` on Ubuntu/Debian, and to `/var/log/secure` on CentOS. For xl2tpd, it logs to `/var/log/syslog` on Ubuntu/Debian, and to `/var/log/messages` on CentOS. Refer to [1] for more information.
> 
> If you wish to additionally log IPsec/L2TP usernames, add a line `debug` to your `/etc/ppp/options.xl2tpd` file, and run `service xl2tpd restart`. Then check the respective log files as mentioned above.
> 
> [1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps

how about using docker? I can't find any auth.log or syslog files in /var/log/

**Comment by hwdsl2** [comment]
@man20820 See: https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/docs/advanced-usage.md#enable-libreswan-logs

**Comment by UGVkcm8** [comment]
Installed those scripts but it registers always the same user for every connection despite they're using another.
Example:

auth-down 23/01/26 15:13:14 ppp0 **vpn** root 0

The user that logged out was not "vpn".

**Comment by ToF78** [comment]
ethereali: I had a similar problem as the OP, your script helped, thank you! Would it be possible to log more information, such as amount of data transferred during the connection? We use something like that for OpenVPN, not sure if it's possible in this case.

Also, on Almalinux 8, the username is recorded in the log correctly.

**Comment by Bellavene** [comment]
> another way to log user connections
> 
> create two scripts in /etc/ppp/ - auth-down , auth-up
> 
> make executable chmod +x /etc/ppp/auth*

Done, but nothing happened. /var/log/pppstats is empty
