### ISSUE TITLE
I have build  ,status good but can't connect

### ISSUE THREAD

**Issue by jackkite** [hwdsl2/setup-ipsec-vpn#322]
Feb 20 14:44:32 wangfei23 pluto[13499]: "l2tp-psk"[6] 114.242.248.5 #10: deleting incomplete state after 60.000 seconds
Feb 20 14:44:32 wangfei23 pluto[13499]: "l2tp-psk"[6] 114.242.248.5 #10: deleting state (STATE_MAIN_R1)
Feb 20 14:44:32 wangfei23 pluto[13499]: deleting connection "l2tp-psk"[6] 114.242.248.5 instance with peer 114.242.248.5 {isakmp=#0/ipsec=#0}

**Comment by hwdsl2** [comment]
@jackkite Your logs indicate that the connection is interrupted by firewall. Please try alternative solutions such as Shadowsocks.
