### ISSUE TITLE
Multiple clients not works

### ISSUE THREAD

**Issue by LevelOne2k** [hwdsl2/setup-ipsec-vpn#323]
Hello, I have successfully installed IPsec VPN Server Auto Setup Script. I've created 2 additional users for IPsec, it works the connection works. Invalid passwords and usernames.

Both clients get the same IP address: 192.168.43.10

A client can then no longer connect to the Internet. Does not connect multiple clients at the same time?

**Comment by hwdsl2** [comment]
@LevelOne2k Hello! This is currently a known issue, where multiple VPN clients behind the same NAT (e.g. home router) cannot connect simultaneously to the VPN server. For details, refer to [1] [2] [3]. This limitation applies both when using the same VPN user or different VPN users. For IPsec/XAuth a fix has been planned in the next Libreswan version [3].

[1] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes
[2]  #314
[3] libreswan/libreswan#166

**Comment by letoams** [comment]
note libreswan 3.26 was released that addresses the issue related to bad lease ip re-use
