### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SharpColours** [hwdsl2/setup-ipsec-vpn#324]
Hey there!

Nice service you've got here; works perfectly. A couple of questions, is there any way to operate a logging system to log all websites accessed by which IP on this system; and any way to block specific sites from being accessed? E.g. just deny the site connection.

Thanks,

_Joseph_

**Comment by hwdsl2** [comment]
@SharpColours Hello! Unfortunately there is no easy way to log websites as
you mentioned. For denying access to select websites, you may try IPTables
(block all relevant IPs in the FORWARD chain), maybe combined with a custom
DNS server with blocking feature.

Both are outside the scope of this project.

**Comment by SharpColours** [comment]
Ah okay, thanks anyway! :)
