### ISSUE TITLE
Why Open VZ is not supported? 

### ISSUE THREAD

**Issue by tribody** [hwdsl2/setup-ipsec-vpn#325]
RT,I want to setup a Ipsec/L2tp vpn server on my vps. But it's open vz based. Can I modify your code to adapt to mine?

**Comment by setka007** [comment]
I not 100% sure but as i remember when i had my openvz server i had to ask my administrator(seller) to load in some modules to my server if i wanted to use ANY vpn tunel. I recommend You to swap Openvz to KVM or XEN -  those virtualization is much more effective and you don't have to ask your administration for any help.

**Comment by hwdsl2** [comment]
@tribody Hello! IPsec VPN requires Linux kernel support. All OpenVZ VPS on a host node share the same kernel, which generally lacks support for IPsec. Therefore you need to switch to e.g. KVM or XEN, like @setka007 said, in order to set up an IPsec VPN server.
