### ISSUE TITLE
VPN Access Manager 配置连接失败

### ISSUE THREAD

**Issue by monkey-wenjun** [hwdsl2/setup-ipsec-vpn#326]

**Comment by monkey-wenjun** [comment]
MAC 下配置完即可连接而Windows 参考文档配置无法连接并且还报错

![](https://file.awen.me/blog/woouv.png!awen)

我的配置如下

![](https://file.awen.me/blog/hjt2q.png!awen)


![](https://file.awen.me/blog/s9x22.png!awen)

![](https://file.awen.me/blog/yn9t1.png!awen)

![](https://file.awen.me/blog/ppmzw.png!awen)


操作系统版本：Windows 10 专业版

**Comment by monkey-wenjun** [comment]
并且在win7上测试也无效。

**Comment by wangzhenjjcn** [comment]
@monkey-wenjun 
import this file [vpnSampleSettings](https://raw.githubusercontent.com/wangzhenjjcn/Auto_IPsecVPN_InstallBash/master/VPNClientForWindows10/Sample.vpn)
then edit your PSK and Link with your password is OK
导入这个文件然后设置公钥用你的账户登录就OK了

**Comment by wangzhenjjcn** [comment]
@monkey-wenjun 右击另存为即可
