### ISSUE TITLE
l2tp can not connect

### ISSUE THREAD

**Issue by zhengwenk** [hwdsl2/setup-ipsec-vpn#327]
auth log
<pre>
Feb 27 04:30:58 ip-172-31-26-228 pluto[3455]: "l2tp-psk"[2] 61.148.245.103 #21: responding to Main Mode from unknown peer 61.148.245.103 on port 59650
Feb 27 04:30:58 ip-172-31-26-228 pluto[3455]: "l2tp-psk"[2] 61.148.245.103 #21: STATE_MAIN_R1: sent MR1, expecting MI2
Feb 27 04:31:01 ip-172-31-26-228 pluto[3455]: "l2tp-psk"[2] 61.148.245.103 #22: responding to Main Mode from unknown peer 61.148.245.103 on port 59650
Feb 27 04:31:01 ip-172-31-26-228 pluto[3455]: "l2tp-psk"[2] 61.148.245.103 #22: STATE_MAIN_R1: sent MR1, expecting MI2
Feb 27 04:31:04 ip-172-31-26-228 pluto[3455]: "l2tp-psk"[2] 61.148.245.103 #23: responding to Main Mode from unknown peer 61.148.245.103 on port 59650
Feb 27 04:31:04 ip-172-31-26-228 pluto[3455]: "l2tp-psk"[2] 61.148.245.103 #23: STATE_MAIN_R1: sent MR1, expecting MI2
Feb 27 04:31:07 ip-172-31-26-228 pluto[3455]: "l2tp-psk"[2] 61.148.245.103 #24: responding to Main Mode from unknown peer 61.148.245.103 on port 59650
Feb 27 04:31:07 ip-172-31-26-228 pluto[3455]: "l2tp-psk"[2] 61.148.245.103 #24: STATE_MAIN_R1: sent MR1, expecting MI2
</pre>

**Comment by wangzhenjjcn** [comment]
https://www.shrew.net/
Use this client
done
@zhengwenk

**Comment by hwdsl2** [comment]
Thanks @wangzhenjjcn!

@zhengwenk Your logs indicate that your connection is blocked by firewall. Try alternative solutions such as Shadowsocks.
