### ISSUE TITLE
Separate subnetworks for users groups

### ISSUE THREAD

**Issue by urpylka** [hwdsl2/setup-ipsec-vpn#329]
Hello, how can I create user groups connections, where all the connection in group are accepted and  all the connections between groups are declined?

Also I saw a param “group name” in Cisco connection . What is it?

**Comment by hwdsl2** [comment]
@urpylka Hello! Not sure what you meant by "user group connections" but it is not supported.  The "group name" is used in IPsec "aggressive mode". See #304.

**Comment by urpylka** [comment]
Now all users may connect to only one local network. I mean that I want to make **connect several users** (some group of clients) **to local network**. Also I want that **another group connect to another local network**.

**Comment by hwdsl2** [comment]
@EllaMozes Hello! This is not supported. You can assign static IPs to VPN clients, however, which may be helpful in your use case (but it's not what you are asking for).
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage.md#internal-vpn-ips-and-traffic
