### ISSUE TITLE
VPN Host IP Logged When Connecting to Other Resources on LAN

### ISSUE THREAD

**Issue by coughlinj** [hwdsl2/setup-ipsec-vpn#33]
@hwdsl2 
I tried the suggestion you made in the gist comments about changing the conn l2tp-psk's leftsubnet from leftsubnet=.../32 with leftsubnet=10.0.0.0/8, restarting the service, and re-connecting, but no luck. If you have other suggestions, I'd love to try them. If not, just let me know and I'll close out the issue. I'm guessing I'll probably have to handle this through some outbound NAT with firewalld. 

Thanks again for your help!

**Comment by hwdsl2** [comment]
@coughlinj Thank you for the update. I thinked about it a bit more and unfortunately it seems that what you were trying to do is not possible unless the server(s) you've trying to access are all connected to the same VPN. Please change back the `leftsubnet` line in your `ipsec.conf` to its original value. You may have to explore alternative methods.
