### ISSUE TITLE
IPsec/XAuth connection established, but no internet connection via Android 8.0 smartphone.

### ISSUE THREAD

**Issue by joevil** [hwdsl2/setup-ipsec-vpn#330]
when set with sha2-truncbug=yes, the connection established, it seems using **sha2_256** for cipher.
log as:

Mar  5 13:47:06 instance-2 pluto[26494]: "xauth-psk"[1] xxx.xx.xxx.xxx #1: responding to Main Mode from unknown peer xxx.xx.xxx.xxx on port 500
Mar  5 13:47:06 instance-2 pluto[26494]: "xauth-psk"[1] xxx.xx.xxx.xxx #1: Oakley Transform [AES_CBC (256), HMAC_SHA2_384, MODP1024] refused
Mar  5 13:47:06 instance-2 pluto[26494]: "xauth-psk"[1] xxx.xx.xxx.xxx #1: STATE_MAIN_R1: sent MR1, expecting MI2
Mar  5 13:47:06 instance-2 pluto[26494]: "xauth-psk"[1] xxx.xx.xxx.xxx #1: STATE_MAIN_R2: sent MR2, expecting MI3
Mar  5 13:47:06 instance-2 pluto[26494]: "xauth-psk"[1] xxx.xx.xxx.xxx #1: Peer ID is ID_IPV4_ADDR: '192.168.1.141'
Mar  5 13:47:06 instance-2 pluto[26494]: "xauth-psk"[1] xxx.xx.xxx.xxx #1: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=aes_256 integ=sha2_256 group=MODP1024}
Mar  5 13:47:06 instance-2 pluto[26494]: "xauth-psk"[1] xxx.xx.xxx.xxx #1: ignoring informational payload IPSEC_INITIAL_CONTACT, msgid=00000000, length=28
Mar  5 13:47:06 instance-2 pluto[26494]: | ISAKMP Notification Payload
Mar  5 13:47:06 instance-2 pluto[26494]: |   00 00 00 1c  00 00 00 01  01 10 60 02
Mar  5 13:47:06 instance-2 pluto[26494]: "xauth-psk"[1] xxx.xx.xxx.xxx #1: received and ignored informational message
Mar  5 13:47:07 instance-2 pluto[26494]: "xauth-psk"[1] xxx.xx.xxx.xxx #1: XAUTH: Sending Username/Password request (MAIN_R3->XAUTH_R0)
Mar  5 13:47:07 instance-2 pluto[26494]: "xauth-psk"[1] xxx.xx.xxx.xxx #1: XAUTH: password file authentication method requested to authenticate user 'vpnuser'
Mar  5 13:47:07 instance-2 pluto[26494]: "xauth-psk"[1] xxx.xx.xxx.xxx #1: XAUTH: password file (/etc/ipsec.d/passwd) open.
Mar  5 13:47:07 instance-2 pluto[26494]: "xauth-psk"[1] xxx.xx.xxx.xxx #1: XAUTH: success user(vpnuser:xauth-psk)
Mar  5 13:47:07 instance-2 pluto[26494]: "xauth-psk"[1] xxx.xx.xxx.xxx #1: XAUTH: #1: completed for user 'vpnuser' with status SUCCESSS
Mar  5 13:47:07 instance-2 pluto[26494]: "xauth-psk"[1] xxx.xx.xxx.xxx #1: XAUTH: User vpnuser: Authentication Successful
Mar  5 13:47:07 instance-2 pluto[26494]: "xauth-psk"[1] xxx.xx.xxx.xxx #1: XAUTH: xauth_inR1(STF_OK)
Mar  5 13:47:07 instance-2 pluto[26494]: "xauth-psk"[1] xxx.xx.xxx.xxx #1: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=aes_256 integ=sha2_256 group=MODP1024}
Mar  5 13:47:07 instance-2 pluto[26494]: "xauth-psk"[1] xxx.xx.xxx.xxx #1: modecfg_inR0(STF_OK)
Mar  5 13:47:07 instance-2 pluto[26494]: "xauth-psk"[1] xxx.xx.xxx.xxx #1: STATE_MODE_CFG_R1: ModeCfg Set sent, expecting Ack {auth=PRESHARED_KEY cipher=aes_256 integ=sha2_256 group=MODP1024}
Mar  5 13:47:07 instance-2 pluto[26494]: "xauth-psk"[1] xxx.xx.xxx.xxx #1: the peer proposed: 0.0.0.0/0:0/0 -> 192.168.43.10/32:0/0
Mar  5 13:47:07 instance-2 pluto[26494]: "xauth-psk"[1] xxx.xx.xxx.xxx #2: responding to Quick Mode proposal {msgid:f82ea591}
Mar  5 13:47:07 instance-2 pluto[26494]: "xauth-psk"[1] xxx.xx.xxx.xxx #2:     us: 0.0.0.0/0===10.140.0.3[35.229.180.xxx,MS+XS+S=C]
Mar  5 13:47:07 instance-2 pluto[26494]: "xauth-psk"[1] xxx.xx.xxx.xxx #2:   them: xxx.xx.xxx.xxx[+MC+XC+S=C]===192.168.43.10/32
Mar  5 13:47:07 instance-2 pluto[26494]: "xauth-psk"[1] xxx.xx.xxx.xxx #2: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 tunnel mode {ESP/NAT=>0x0bfce49e <0x0359c6a3 xfrm
=AES_CBC_256-HMAC_SHA2_512_256 NATOA=none NATD=xxx.xx.xxx.xxx:4500 DPD=active username=vpnuser}
Mar  5 13:47:07 instance-2 pluto[26494]: "xauth-psk"[1] xxx.xx.xxx.xxx #2: STATE_QUICK_R2: IPsec SA established tunnel mode {ESP/NAT=>0x0bfce49e <0x0359c6a3 xfrm=AES_CBC_256-HMAC_SHA2_512_256 
NATOA=none NATD=xxx.xx.xxx.xxx:4500 DPD=active username=vpnuser}

**Comment by joevil** [comment]
when set with sha2-truncbug= no, get the same log

**Comment by hwdsl2** [comment]
@joevil Hello! Make sure that you don’t put a space between “=“ and “no”.
It should read “sha2-truncbug=no”, indented by two spaces. Then run
“service ipsec restart”.

If it still does not work try changing the phase2alg line to the following
and restart the IPsec service.

phase2alg=3des-sha1,3des-sha2,aes-sha1,aes256-sha2_512

**Comment by joevil** [comment]
@hwdsl2  set as advice, still get no connection;
along with the init log:

Mar  6 02:09:19 instance-2 pluto[8526]: NSS DB directory: sql:/etc/ipsec.d
Mar  6 02:09:19 instance-2 pluto[8526]: Initializing NSS
Mar  6 02:09:19 instance-2 pluto[8526]: Opening NSS database "sql:/etc/ipsec.d" read-only
Mar  6 02:09:19 instance-2 pluto[8526]: NSS initialized
Mar  6 02:09:19 instance-2 pluto[8526]: NSS crypto library initialized
Mar  6 02:09:19 instance-2 pluto[8526]: FIPS HMAC integrity support [disabled]
Mar  6 02:09:19 instance-2 pluto[8526]: libcap-ng support [enabled]
Mar  6 02:09:19 instance-2 pluto[8526]: Linux audit support [disabled]
Mar  6 02:09:19 instance-2 pluto[8526]: Starting Pluto (Libreswan Version 3.23 XFRM(netkey) KLIPS FORK PTHREAD_SETSCHEDPRIO NSS SYSTEMD_WATCHDOG LABELED_IPSEC LIBCAP_NG XAUTH_PAM NETWORKMANAGER CURL(non-NSS)) pid:8526
Mar  6 02:09:19 instance-2 pluto[8526]: core dump dir: /run/pluto
Mar  6 02:09:19 instance-2 pluto[8526]: secrets file: /etc/ipsec.secrets
Mar  6 02:09:19 instance-2 pluto[8526]: leak-detective enabled
Mar  6 02:09:19 instance-2 pluto[8526]: NSS crypto [enabled]
Mar  6 02:09:19 instance-2 pluto[8526]: XAUTH PAM support [enabled]
Mar  6 02:09:19 instance-2 pluto[8526]: NAT-Traversal support  [enabled]
Mar  6 02:09:19 instance-2 pluto[8526]: Initializing libevent in pthreads mode: headers: 2.0.21-stable (2001500); library: 2.0.21-stable (2001500)
Mar  6 02:09:19 instance-2 pluto[8526]: Encryption algorithms:
Mar  6 02:09:19 instance-2 pluto[8526]:  AES_CCM_16          IKEv1:     ESP     IKEv2:     ESP     FIPS  {256,192,*128}  (aes_ccm aes_ccm_c)
Mar  6 02:09:19 instance-2 pluto[8526]:  AES_CCM_12          IKEv1:     ESP     IKEv2:     ESP     FIPS  {256,192,*128}  (aes_ccm_b)
Mar  6 02:09:19 instance-2 pluto[8526]:  AES_CCM_8           IKEv1:     ESP     IKEv2:     ESP     FIPS  {256,192,*128}  (aes_ccm_a)
Mar  6 02:09:19 instance-2 pluto[8526]:  3DES_CBC            IKEv1: IKE ESP     IKEv2: IKE ESP     FIPS  [*192]  (3des)
Mar  6 02:09:19 instance-2 pluto[8526]:  CAMELLIA_CTR        IKEv1:     ESP     IKEv2:     ESP           {256,192,*128}
Mar  6 02:09:19 instance-2 pluto[8526]:  CAMELLIA_CBC        IKEv1: IKE ESP     IKEv2: IKE ESP           {256,192,*128}  (camellia)
Mar  6 02:09:19 instance-2 pluto[8526]:  AES_GCM_16          IKEv1:     ESP     IKEv2: IKE ESP     FIPS  {256,192,*128}  (aes_gcm aes_gcm_c)
Mar  6 02:09:19 instance-2 pluto[8526]:  AES_GCM_12          IKEv1:     ESP     IKEv2: IKE ESP     FIPS  {256,192,*128}  (aes_gcm_b)
Mar  6 02:09:19 instance-2 pluto[8526]:  AES_GCM_8           IKEv1:     ESP     IKEv2: IKE ESP     FIPS  {256,192,*128}  (aes_gcm_a)
Mar  6 02:09:19 instance-2 pluto[8526]:  AES_CTR             IKEv1: IKE ESP     IKEv2: IKE ESP     FIPS  {256,192,*128}  (aesctr)
Mar  6 02:09:19 instance-2 pluto[8526]:  AES_CBC             IKEv1: IKE ESP     IKEv2: IKE ESP     FIPS  {256,192,*128}  (aes)
Mar  6 02:09:19 instance-2 pluto[8526]:  SERPENT_CBC         IKEv1: IKE ESP     IKEv2: IKE ESP           {256,192,*128}  (serpent)
Mar  6 02:09:19 instance-2 pluto[8526]:  TWOFISH_CBC         IKEv1: IKE ESP     IKEv2: IKE ESP           {256,192,*128}  (twofish)
Mar  6 02:09:19 instance-2 pluto[8526]:  TWOFISH_SSH         IKEv1: IKE         IKEv2: IKE ESP           {256,192,*128}  (twofish_cbc_ssh)
Mar  6 02:09:19 instance-2 pluto[8526]:  CAST_CBC            IKEv1:     ESP     IKEv2:     ESP           {*128}  (cast)
Mar  6 02:09:19 instance-2 pluto[8526]:  NULL_AUTH_AES_GMAC  IKEv1:     ESP     IKEv2:     ESP           {256,192,*128}  (aes_gmac)
Mar  6 02:09:19 instance-2 pluto[8526]:  NULL                IKEv1:     ESP     IKEv2:     ESP           []
Mar  6 02:09:19 instance-2 pluto[8526]: Hash algorithms:
Mar  6 02:09:19 instance-2 pluto[8526]:  MD5                 IKEv1: IKE         IKEv2:
Mar  6 02:09:19 instance-2 pluto[8526]:  SHA1                IKEv1: IKE         IKEv2:             FIPS  (sha)
Mar  6 02:09:19 instance-2 pluto[8526]:  SHA2_256            IKEv1: IKE         IKEv2:             FIPS  (sha2 sha256)
Mar  6 02:09:19 instance-2 pluto[8526]:  SHA2_384            IKEv1: IKE         IKEv2:             FIPS  (sha384)
Mar  6 02:09:19 instance-2 pluto[8526]:  SHA2_512            IKEv1: IKE         IKEv2:             FIPS  (sha512)
Mar  6 02:09:19 instance-2 pluto[8526]: PRF algorithms:
Mar  6 02:09:19 instance-2 pluto[8526]:  HMAC_MD5            IKEv1: IKE         IKEv2: IKE               (md5)
Mar  6 02:09:19 instance-2 pluto[8526]:  HMAC_SHA1           IKEv1: IKE         IKEv2: IKE         FIPS  (sha sha1)
Mar  6 02:09:19 instance-2 pluto[8526]:  HMAC_SHA2_256       IKEv1: IKE         IKEv2: IKE         FIPS  (sha2 sha256 sha2_256)
Mar  6 02:09:19 instance-2 pluto[8526]:  HMAC_SHA2_384       IKEv1: IKE         IKEv2: IKE         FIPS  (sha384 sha2_384)
Mar  6 02:09:19 instance-2 pluto[8526]:  HMAC_SHA2_512       IKEv1: IKE         IKEv2: IKE         FIPS  (sha512 sha2_512)
Mar  6 02:09:19 instance-2 pluto[8526]: Integrity algorithms:
Mar  6 02:09:19 instance-2 pluto[8526]:  HMAC_MD5_96         IKEv1: IKE ESP AH  IKEv2: IKE ESP AH        (md5 hmac_md5)
Mar  6 02:09:19 instance-2 pluto[8526]:  HMAC_SHA1_96        IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (sha sha1 sha1_96 hmac_sha1)
Mar  6 02:09:19 instance-2 pluto[8526]:  HMAC_SHA2_512_256   IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (sha512 sha2_512 hmac_sha2_512)
Mar  6 02:09:19 instance-2 pluto[8526]:  HMAC_SHA2_384_192   IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (sha384 sha2_384 hmac_sha2_384)
Mar  6 02:09:19 instance-2 pluto[8526]:  HMAC_SHA2_256_128   IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (sha2 sha256 sha2_256 hmac_sha2_256)
Mar  6 02:09:19 instance-2 pluto[8526]:  AES_XCBC_96         IKEv1:     ESP AH  IKEv2:     ESP AH  FIPS  (aes_xcbc)
Mar  6 02:09:19 instance-2 pluto[8526]:  AES_CMAC_96         IKEv1:     ESP AH  IKEv2:     ESP AH  FIPS  (aes_cmac)
Mar  6 02:09:19 instance-2 pluto[8526]:  NONE                IKEv1:     ESP     IKEv2:     ESP     FIPS  (null)
Mar  6 02:09:19 instance-2 pluto[8526]: DH algorithms:
Mar  6 02:09:19 instance-2 pluto[8526]:  MODP1024            IKEv1: IKE ESP AH  IKEv2: IKE ESP AH        (dh2)
Mar  6 02:09:19 instance-2 pluto[8526]:  MODP1536            IKEv1: IKE ESP AH  IKEv2: IKE ESP AH        (dh5)
Mar  6 02:09:19 instance-2 pluto[8526]:  HMAC_SHA2_512_256   IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (sha512 sha2_512 hmac_sha2_512)
Mar  6 02:09:19 instance-2 pluto[8526]:  MODP2048            IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (dh14)
Mar  6 02:09:19 instance-2 pluto[8526]:  MODP3072            IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (dh15)
Mar  6 02:09:19 instance-2 pluto[8526]:  MODP4096            IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (dh16)
Mar  6 02:09:19 instance-2 pluto[8526]:  MODP6144            IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (dh17)
Mar  6 02:09:19 instance-2 pluto[8526]:  MODP8192            IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  (dh18)
Mar  6 02:09:19 instance-2 pluto[8526]:  DH19                IKEv1: IKE         IKEv2: IKE ESP AH  FIPS  (ecp_256)
Mar  6 02:09:19 instance-2 pluto[8526]:  DH20                IKEv1: IKE         IKEv2: IKE ESP AH  FIPS  (ecp_384)
Mar  6 02:09:19 instance-2 pluto[8526]:  DH21                IKEv1: IKE         IKEv2: IKE ESP AH  FIPS  (ecp_521)
Mar  6 02:09:19 instance-2 pluto[8526]:  DH23                IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS
Mar  6 02:09:19 instance-2 pluto[8526]:  DH24                IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS
Mar  6 02:09:19 instance-2 pluto[8526]: starting up 2 crypto helpers
Mar  6 02:09:19 instance-2 pluto[8526]: started thread for crypto helper 0
Mar  6 02:09:19 instance-2 pluto[8526]: started thread for crypto helper 1
Mar  6 02:09:19 instance-2 pluto[8526]: Using Linux XFRM/NETKEY IPsec interface code on 3.10.0-693.17.1.el7.x86_64
Mar  6 02:09:19 instance-2 pluto[8526]: seccomp security for crypto helper not supported
Mar  6 02:09:19 instance-2 pluto[8526]: seccomp security for crypto helper not supported
Mar  6 02:09:19 instance-2 pluto[8526]: | selinux support is enabled.
Mar  6 02:09:19 instance-2 pluto[8526]: systemd watchdog for ipsec service configured with timeout of 200000000 usecs
Mar  6 02:09:19 instance-2 pluto[8526]: watchdog: sending probes every 100 secs
Mar  6 02:09:19 instance-2 pluto[8526]: seccomp security not supported
Mar  6 02:09:20 instance-2 pluto[8526]: added connection description "l2tp-psk"
Mar  6 02:09:20 instance-2 pluto[8526]: added connection description "xauth-psk"
Mar  6 02:09:20 instance-2 pluto[8526]: listening for IKE messages
Mar  6 02:09:20 instance-2 pluto[8526]: adding interface eth0/eth0 10.140.0.3:500
Mar  6 02:09:20 instance-2 pluto[8526]: adding interface eth0/eth0 10.140.0.3:4500
Mar  6 02:09:20 instance-2 pluto[8526]: adding interface lo/lo 127.0.0.1:500
Mar  6 02:09:20 instance-2 pluto[8526]: adding interface lo/lo 127.0.0.1:4500
Mar  6 02:09:20 instance-2 pluto[8526]: adding interface lo/lo ::1:500
Mar  6 02:09:20 instance-2 pluto[8526]: | setup callback for interface lo:500 fd 21
Mar  6 02:09:20 instance-2 pluto[8526]: | setup callback for interface lo:4500 fd 20
Mar  6 02:09:20 instance-2 pluto[8526]: | setup callback for interface lo:500 fd 19
Mar  6 02:09:20 instance-2 pluto[8526]: | setup callback for interface eth0:4500 fd 18
Mar  6 02:09:20 instance-2 pluto[8526]: | setup callback for interface eth0:500 fd 17
Mar  6 02:09:20 instance-2 pluto[8526]: loading secrets from "/etc/ipsec.secrets"
Mar  6 02:09:42 instance-2 pluto[8526]: "xauth-psk"[1] 117.xxx.39.xx #1: responding to Main Mode from unknown peer 117.xxx.39.xx on port 10927
Mar  6 02:09:42 instance-2 pluto[8526]: "xauth-psk"[1] 117.xxx.39.xx #1: Oakley Transform [AES_CBC (256), HMAC_SHA2_384, MODP1024] refused
Mar  6 02:09:42 instance-2 pluto[8526]: "xauth-psk"[1] 117.xxx.39.xx #1: STATE_MAIN_R1: sent MR1, expecting MI2
Mar  6 02:09:43 instance-2 pluto[8526]: "xauth-psk"[1] 117.xxx.39.xx #1: STATE_MAIN_R2: sent MR2, expecting MI3
Mar  6 02:09:43 instance-2 pluto[8526]: "xauth-psk"[1] 117.xxx.39.xx #1: Peer ID is ID_IPV4_ADDR: '10.217.149.138'
Mar  6 02:09:43 instance-2 pluto[8526]: "xauth-psk"[1] 117.xxx.39.xx #1: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=aes_256 integ=sha2_256 group=MODP1024}
Mar  6 02:09:43 instance-2 pluto[8526]: recvfrom 117.xxx.39.xx:19851 too small packet (0)
Mar  6 02:09:43 instance-2 pluto[8526]: recvfrom 117.xxx.39.xx:19851 too small packet (0)
Mar  6 02:09:43 instance-2 pluto[8526]: recvfrom 117.xxx.39.xx:19851 too small packet (0)
Mar  6 02:09:43 instance-2 pluto[8526]: "xauth-psk"[1] 117.xxx.39.xx #1: XAUTH: Sending Username/Password request (MAIN_R3->XAUTH_R0)
Mar  6 02:09:43 instance-2 pluto[8526]: "xauth-psk"[1] 117.xxx.39.xx #1: ignoring informational payload IPSEC_INITIAL_CONTACT, msgid=00000000, length=28
Mar  6 02:09:43 instance-2 pluto[8526]: | ISAKMP Notification Payload
Mar  6 02:09:43 instance-2 pluto[8526]: |   00 00 00 1c  00 00 00 01  01 10 60 02
Mar  6 02:09:43 instance-2 pluto[8526]: "xauth-psk"[1] 117.xxx.39.xx #1: received and ignored informational message
Mar  6 02:09:43 instance-2 pluto[8526]: "xauth-psk"[1] 117.xxx.39.xx #1: XAUTH: password file authentication method requested to authenticate user 'vpnuser'
Mar  6 02:09:43 instance-2 pluto[8526]: "xauth-psk"[1] 117.xxx.39.xx #1: XAUTH: password file (/etc/ipsec.d/passwd) open.
Mar  6 02:09:43 instance-2 pluto[8526]: "xauth-psk"[1] 117.xxx.39.xx #1: XAUTH: success user(vpnuser:xauth-psk)
Mar  6 02:09:43 instance-2 pluto[8526]: "xauth-psk"[1] 117.xxx.39.xx #1: XAUTH: #1: completed for user 'vpnuser' with status SUCCESSS
Mar  6 02:09:43 instance-2 pluto[8526]: "xauth-psk"[1] 117.xxx.39.xx #1: XAUTH: User vpnuser: Authentication Successful
Mar  6 02:09:44 instance-2 pluto[8526]: "xauth-psk"[1] 117.xxx.39.xx #1: XAUTH: xauth_inR1(STF_OK)
Mar  6 02:09:44 instance-2 pluto[8526]: "xauth-psk"[1] 117.xxx.39.xx #1: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=aes_256 integ=sha2_256 group=MODP1024}
Mar  6 02:09:44 instance-2 pluto[8526]: "xauth-psk"[1] 117.xxx.39.xx #1: modecfg_inR0(STF_OK)
Mar  6 02:09:44 instance-2 pluto[8526]: "xauth-psk"[1] 117.xxx.39.xx #1: STATE_MODE_CFG_R1: ModeCfg Set sent, expecting Ack {auth=PRESHARED_KEY cipher=aes_256 integ=sha2_256 group=MODP1024}
Mar  6 02:09:44 instance-2 pluto[8526]: "xauth-psk"[1] 117.xxx.39.xx #1: the peer proposed: 0.0.0.0/0:0/0 -> 192.168.43.10/32:0/0
Mar  6 02:09:44 instance-2 pluto[8526]: "xauth-psk"[1] 117.xxx.39.xx #2: responding to Quick Mode proposal {msgid:e9bfb3f9}
Mar  6 02:09:44 instance-2 pluto[8526]: "xauth-psk"[1] 117.xxx.39.xx #2:     us: 0.0.0.0/0===10.140.0.3[35.229.18x.2xx,MS+XS+S=C]
Mar  6 02:09:44 instance-2 pluto[8526]: "xauth-psk"[1] 117.xxx.39.xx #2:   them: 117.xxx.39.xx[+MC+XC+S=C]===192.168.43.10/32
Mar  6 02:09:44 instance-2 pluto[8526]: "xauth-psk"[1] 117.xxx.39.xx #2: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 tunnel mode {ESP/NAT=>0x00010bef <0x6a0a91ec xfrm=AES_CBC_256-HMAC_SHA2_512_256 NATOA=none NATD=117.136.3
9.85:19851 DPD=active username=vpnuser}
Mar  6 02:09:45 instance-2 pluto[8526]: "xauth-psk"[1] 117.xxx.39.xx #2: STATE_QUICK_R2: IPsec SA established tunnel mode {ESP/NAT=>0x00010bef <0x6a0a91ec xfrm=AES_CBC_256-HMAC_SHA2_512_256 NATOA=none NATD=117.xxx.39.xx:19851 DPD=active username=
vpnuser}

**Comment by joevil** [comment]
btw, I set the psk with 24 digit.

**Comment by joevil** [comment]
it seems Integrity algorithms using HMAC_SHA2_512_256  which is 
Mar 6 02:09:19 instance-2 pluto[8526]: HMAC_SHA2_512_256 IKEv1: IKE ESP AH IKEv2: IKE ESP AH FIPS (sha512 sha2_512 hmac_sha2_512)

how can I confirm it is supported by Android 8.0?

**Comment by joevil** [comment]
https://issuetracker.google.com/issues/37074640#comment353
if you use huawei, you all add aes256-sha2_512


docker exec vpn sed -i  's/ike=/ike=aes256-sha2_256,aes256-sha2_512,/g'   /etc/ipsec.conf  
docker exec vpn sed -i 's/phase2alg=/phase2alg=aes256-sha2_256,aes256-sha2_512,/'  /etc/ipsec.conf  
docker exec vpn sed -i '26 i\  sha2-truncbug=yes' /etc/ipsec.conf
docker exec vpn service ipsec restart
-----------
this fixed my issue.
