### ISSUE TITLE
IPSec/XAuth连接不上

### ISSUE THREAD

**Issue by scherpe** [hwdsl2/setup-ipsec-vpn#331]
日志如下：

> Mar  6 06:14:56 6a4c93e34bea pluto[608]: loading secrets from "/etc/ipsec.secrets"
Mar  6 06:17:25 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #1: responding to Main Mode from unknown peer 120.85.64.3 on port 7576
Mar  6 06:17:25 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #1: WARNING: connection l2tp-psk PSK length of 8 bytes is too short for sha2_256 PRF in FIPS mode (16 bytes required)
Mar  6 06:17:25 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #1: STATE_MAIN_R1: sent MR1, expecting MI2
Mar  6 06:17:28 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #1: retransmitting in response to duplicate packet; already STATE_MAIN_R1
Mar  6 06:17:31 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #1: retransmitting in response to duplicate packet; already STATE_MAIN_R1
Mar  6 06:17:34 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #1: retransmitting in response to duplicate packet; already STATE_MAIN_R1
Mar  6 06:17:41 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #2: responding to Main Mode from unknown peer 120.85.64.3 on port 7576
Mar  6 06:17:41 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #2: WARNING: connection l2tp-psk PSK length of 8 bytes is too short for sha2_256 PRF in FIPS mode (16 bytes required)
Mar  6 06:17:41 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #2: STATE_MAIN_R1: sent MR1, expecting MI2
Mar  6 06:17:44 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #2: retransmitting in response to duplicate packet; already STATE_MAIN_R1
Mar  6 06:17:48 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #2: retransmitting in response to duplicate packet; already STATE_MAIN_R1
Mar  6 06:17:51 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #2: retransmitting in response to duplicate packet; already STATE_MAIN_R1
Mar  6 06:18:24 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #3: responding to Main Mode from unknown peer 120.85.64.3 on port 7576
Mar  6 06:18:24 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #3: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:18:24 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #3: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:18:24 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #3: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:18:24 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #3: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:18:24 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #3: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:18:24 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #3: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:18:24 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #3: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:18:24 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #3: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:18:24 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #3: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:18:24 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #3: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:18:24 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #3: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:18:24 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #3: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:18:24 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #3: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:18:24 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #3: OAKLEY_DES_CBC(UNUSED) is not supported.  Attribute OAKLEY_ENCRYPTION_ALGORITHM
Mar  6 06:18:24 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #3: OAKLEY_DES_CBC(UNUSED) is not supported.  Attribute OAKLEY_ENCRYPTION_ALGORITHM
Mar  6 06:18:24 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #3: no acceptable Oakley Transform
Mar  6 06:18:24 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #3: sending notification NO_PROPOSAL_CHOSEN to 120.85.64.3:7576
Mar  6 06:18:25 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #1: deleting incomplete state after 60.000 seconds
Mar  6 06:18:25 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #1: deleting state (STATE_MAIN_R1)
Mar  6 06:18:41 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #2: deleting incomplete state after 60.000 seconds
Mar  6 06:18:41 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #2: deleting state (STATE_MAIN_R1)
Mar  6 06:19:26 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #4: responding to Main Mode from unknown peer 120.85.64.3 on port 7576
Mar  6 06:19:26 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #4: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:19:26 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #4: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:19:26 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #4: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:19:26 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #4: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:19:26 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #4: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:19:26 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #4: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:19:26 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #4: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:19:26 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #4: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:19:26 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #4: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:19:26 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #4: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:19:26 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #4: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:19:26 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #4: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:19:26 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #4: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:19:26 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #4: OAKLEY_DES_CBC(UNUSED) is not supported.  Attribute OAKLEY_ENCRYPTION_ALGORITHM
Mar  6 06:19:26 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #4: OAKLEY_DES_CBC(UNUSED) is not supported.  Attribute OAKLEY_ENCRYPTION_ALGORITHM
Mar  6 06:19:26 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #4: no acceptable Oakley Transform
Mar  6 06:19:26 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #4: sending notification NO_PROPOSAL_CHOSEN to 120.85.64.3:7576
Mar  6 06:19:29 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #4: discarding initial packet; already STATE_MAIN_R0
Mar  6 06:19:32 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #4: discarding initial packet; already STATE_MAIN_R0
Mar  6 06:19:36 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #4: discarding initial packet; already STATE_MAIN_R0
Mar  6 06:26:54 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #5: responding to Main Mode from unknown peer 120.85.64.3 on port 7576
Mar  6 06:26:54 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #5: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:26:54 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #5: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:26:54 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #5: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:26:54 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #5: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:26:54 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #5: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:26:54 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #5: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:26:54 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #5: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:26:54 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #5: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:26:54 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #5: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:26:54 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #5: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:26:54 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #5: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:26:54 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #5: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:26:54 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #5: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:26:54 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #5: OAKLEY_DES_CBC(UNUSED) is not supported.  Attribute OAKLEY_ENCRYPTION_ALGORITHM
Mar  6 06:26:54 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #5: OAKLEY_DES_CBC(UNUSED) is not supported.  Attribute OAKLEY_ENCRYPTION_ALGORITHM
Mar  6 06:26:54 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #5: no acceptable Oakley Transform
Mar  6 06:26:54 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #5: sending notification NO_PROPOSAL_CHOSEN to 120.85.64.3:7576
Mar  6 06:26:54 6a4c93e34bea pluto[608]: packet from 120.85.64.3:7576: not enough room in input packet for ISAKMP Message (remain=0, sd->size=28)
Mar  6 06:26:54 6a4c93e34bea pluto[608]: packet from 120.85.64.3:7576: Received packet with mangled IKE header - dropped
Mar  6 06:26:54 6a4c93e34bea pluto[608]: packet from 120.85.64.3:7576: not enough room in input packet for ISAKMP Message (remain=0, sd->size=28)
Mar  6 06:26:54 6a4c93e34bea pluto[608]: packet from 120.85.64.3:7576: Received packet with mangled IKE header - dropped
Mar  6 06:26:54 6a4c93e34bea pluto[608]: packet from 120.85.64.3:7576: not enough room in input packet for ISAKMP Message (remain=0, sd->size=28)
Mar  6 06:26:54 6a4c93e34bea pluto[608]: packet from 120.85.64.3:7576: Received packet with mangled IKE header - dropped
Mar  6 06:26:58 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #5: discarding initial packet; already STATE_MAIN_R0
Mar  6 06:27:01 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #5: discarding initial packet; already STATE_MAIN_R0
Mar  6 06:27:04 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #5: discarding initial packet; already STATE_MAIN_R0
Mar  6 06:35:34 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #6: responding to Main Mode from unknown peer 120.85.64.3 on port 7576
Mar  6 06:35:34 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #6: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:35:34 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #6: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:35:34 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #6: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:35:34 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #6: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:35:34 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #6: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:35:34 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #6: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:35:34 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #6: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:35:34 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #6: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:35:34 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #6: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:35:34 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #6: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:35:34 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #6: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:35:34 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #6: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:35:34 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #6: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:35:34 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #6: OAKLEY_DES_CBC(UNUSED) is not supported.  Attribute OAKLEY_ENCRYPTION_ALGORITHM
Mar  6 06:35:34 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #6: OAKLEY_DES_CBC(UNUSED) is not supported.  Attribute OAKLEY_ENCRYPTION_ALGORITHM
Mar  6 06:35:34 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #6: no acceptable Oakley Transform
Mar  6 06:35:34 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #6: sending notification NO_PROPOSAL_CHOSEN to 120.85.64.3:7576
Mar  6 06:35:38 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #6: discarding initial packet; already STATE_MAIN_R0
Mar  6 06:35:42 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #6: discarding initial packet; already STATE_MAIN_R0
Mar  6 06:35:44 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #6: discarding initial packet; already STATE_MAIN_R0
Mar  6 06:36:01 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #7: responding to Main Mode from unknown peer 120.85.64.3 on port 7576
Mar  6 06:36:01 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #7: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:36:01 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #7: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:36:01 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #7: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:36:01 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #7: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:36:01 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #7: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:36:01 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #7: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:36:01 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #7: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:36:01 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #7: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:36:01 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #7: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:36:01 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #7: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:36:01 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #7: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:36:01 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #7: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:36:01 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #7: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:36:01 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #7: OAKLEY_DES_CBC(UNUSED) is not supported.  Attribute OAKLEY_ENCRYPTION_ALGORITHM
Mar  6 06:36:01 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #7: OAKLEY_DES_CBC(UNUSED) is not supported.  Attribute OAKLEY_ENCRYPTION_ALGORITHM
Mar  6 06:36:01 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #7: no acceptable Oakley Transform
Mar  6 06:36:01 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #7: sending notification NO_PROPOSAL_CHOSEN to 120.85.64.3:7576
Mar  6 06:45:17 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #8: responding to Main Mode from unknown peer 120.85.64.3 on port 7576
Mar  6 06:45:17 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #8: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:45:17 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #8: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:45:17 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #8: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:45:17 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #8: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:45:17 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #8: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:45:17 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #8: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:45:17 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #8: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:45:17 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #8: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:45:17 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #8: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:45:17 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #8: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:45:17 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #8: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:45:17 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #8: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:45:17 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #8: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
Mar  6 06:45:17 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #8: OAKLEY_DES_CBC(UNUSED) is not supported.  Attribute OAKLEY_ENCRYPTION_ALGORITHM
Mar  6 06:45:17 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #8: OAKLEY_DES_CBC(UNUSED) is not supported.  Attribute OAKLEY_ENCRYPTION_ALGORITHM
Mar  6 06:45:17 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #8: no acceptable Oakley Transform
Mar  6 06:45:17 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #8: sending notification NO_PROPOSAL_CHOSEN to 120.85.64.3:7576
Mar  6 06:45:21 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #8: discarding initial packet; already STATE_MAIN_R0
Mar  6 06:45:24 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #8: discarding initial packet; already STATE_MAIN_R0
Mar  6 06:45:27 6a4c93e34bea pluto[608]: "l2tp-psk"[1] 120.85.64.3 #8: discarding initial packet; already STATE_MAIN_R0
Mar  6 06:45:34 6a4c93e34bea pluto[608]: "xauth-psk"[1] 112.96.161.30 #9: responding to Main Mode from unknown peer 112.96.161.30 on port 11830
Mar  6 06:45:34 6a4c93e34bea pluto[608]: "xauth-psk"[1] 112.96.161.30 #9: WARNING: connection xauth-psk PSK length of 8 bytes is too short for sha2_256 PRF in FIPS mode (16 bytes required)
Mar  6 06:45:34 6a4c93e34bea pluto[608]: "xauth-psk"[1] 112.96.161.30 #9: STATE_MAIN_R1: sent MR1, expecting MI2
Mar  6 06:45:37 6a4c93e34bea pluto[608]: "xauth-psk"[1] 112.96.161.30 #9: retransmitting in response to duplicate packet; already STATE_MAIN_R1
Mar  6 06:45:40 6a4c93e34bea pluto[608]: "xauth-psk"[1] 112.96.161.30 #9: retransmitting in response to duplicate packet; already STATE_MAIN_R1
Mar  6 06:45:49 6a4c93e34bea pluto[608]: "xauth-psk"[1] 112.96.161.30 #9: retransmitting in response to duplicate packet; already STATE_MAIN_R1
Mar  6 06:46:34 6a4c93e34bea pluto[608]: "xauth-psk"[1] 112.96.161.30 #9: deleting incomplete state after 60.000 seconds
Mar  6 06:46:34 6a4c93e34bea pluto[608]: "xauth-psk"[1] 112.96.161.30 #9: deleting state (STATE_MAIN_R1)
Mar  6 06:46:34 6a4c93e34bea pluto[608]: deleting connection "xauth-psk"[1] 112.96.161.30 instance with peer 112.96.161.30 {isakmp=#0/ipsec=#0}

**Comment by hwdsl2** [comment]
@scherpe Hello! Your logs indicate that the connection is interrupted by firewall. Please try alternative solutions such as Shadowsocks.

**Comment by sonhill** [comment]
> @scherpe Hello! Your logs indicate that the connection is interrupted by firewall. Please try alternative solutions such as Shadowsocks.

Hello, could you please advise how I can use Shadowsocks?
