### ISSUE TITLE
Plain text passwords

### ISSUE THREAD

**Issue by dheera** [hwdsl2/setup-ipsec-vpn#332]
Is there any better way for authentication than to store passwords in /etc/ppp/chap-secrets in plain text?
Alternatively, is there any way the machine can simply authenticate against /etc/passwd and /etc/shadow?

**Comment by hwdsl2** [comment]
@dheera Hello! The /etc/ppp/chap-secrets and /etc/ipsec.secrets files are readable only by root for security. If you wish to read more about using PAM for authentication, see [1]. This is currently not supported by the VPN scripts.

[1] https://libreswan.org/wiki/VPN_server_for_remote_clients_using_IKEv1_XAUTH_with_PSK
