### ISSUE TITLE
UDP port 

### ISSUE THREAD

**Issue by zhiqiang0626** [hwdsl2/setup-ipsec-vpn#333]
The UDP port is not 1701. What is it?

**Comment by zhiqiang0626** [comment]
Found the answer, UDP port number contains: 1701,4500,500

**Comment by hwdsl2** [comment]
@zhiqiang0626 Hello! If you are referring to the L2TP port, it is indeed
UDP 1701. However, connections directly to that port (L2TP without IPsec)
is blocked because they are not encrypted and insecure. You must connect to
the server using IPsec/L2TP or IPsec/XAuth modes. See README for details.

**Comment by zhiqiang0626** [comment]
Thank you very much for the answer. It has been solved.

**Comment by GabLeRoux** [comment]
@hwdsl2 I think this issue can be closed 👍
