### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by sHAsHiLx** [hwdsl2/setup-ipsec-vpn#334]
I have previous server and script worked fine. Now I installed new server and copy all iptables rules to it from old one (there is corporate server and iptables rules contains not only rules for accept L2TP vpn, so I NEED it really, don't want to construct it from start). Now I want to use script to install L2TP server but confused if script is check for existing iptables rules and not add them once more.

**Comment by hwdsl2** [comment]
@sHAsHiLx Hello! The VPN setup script does make an effort to check for existing IPTables rules before adding them. See [1]. You may modify these conditions according to your specific needs. To be safe, make a backup of the IPTables rules before running the script.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/vpnsetup.sh#L373-L380
