### ISSUE TITLE
How many clients are supported per ipsec vpn server?

### ISSUE THREAD

**Issue by leoliuasia** [hwdsl2/setup-ipsec-vpn#335]
Hello, I have a question about how many clients are supported per ipsec vpn server?
Can anyone point out?
After my tests, it looks like one client are supported to me.
And looks like after 2-3 days, the connection can not be done, even reinstall the ipsec vpn server.
reboot the server also not working...I don't know what's behind in this.

**Comment by setka007** [comment]
Hi
In my opinion you have a problem with your dedicated/vps server. I have a KVM VPS server and everything is working great:) Got mikrotik RouterBoard at home and is connected 24hrs 7day a week to my VPN server and always running well - zero problems. I have connected 3 clients at the same time(routerboard, my personal Iphone and laptop with MacOS - all devices are using same login and pass - also no problem at all. What i recommend to you is:
1. update/upgrade your system
2. read manual and reinstall everything again
3. check firewall settings(disable all rules for installation time and try to connect again)
If you will have same problem i would think about different server from other ISP/location. 
Hope you'll sort your problems out :) Let us know;)
cheers

**Comment by joevil** [comment]
Only 1 client behind the same NAT.

**Comment by leoliuasia** [comment]
@setka007 Thank for sharing! Can you tell me about what kvm vps provider you  are using?

**Comment by leoliuasia** [comment]
@joevil Thanks. That's helpful!

**Comment by leoliuasia** [comment]
I just got a new issue, when I connecting the vpn server, ios keeping require me to supply the password. Is the server needs to reconfigure. It works fine yesterday. The issue just happens today.

**Comment by setka007** [comment]
Hi leoliuasia
My ISP is located in Poland https://sldc.eu/ I'm with them almost 3 years and never had any problems. Ask them for a trial free account and try to do some test with your configuration files.

**Comment by leoliuasia** [comment]
@setka007 Thank you!That's nice!

**Comment by hwdsl2** [comment]
@leoliuasia Currently only one VPN client behind the same NAT (e.g. home router) can connect to the VPN server at a time. However this restriction does not apply for clients behind different NATs.

IPsec connections from China are often interfered with by the firewall - If your server suddenly stops working, you may want to look into alternative solutions such as Shadowsocks.

**Comment by leoliuasia** [comment]
@hwdsl2 Thank you!
