### ISSUE TITLE
xl2tp can not connect

### ISSUE THREAD

**Issue by goodboy0924** [hwdsl2/setup-ipsec-vpn#336]
xl2tpd[10387]: Not looking for kernel SAref support.
xl2tpd[10387]: L2TP kernel support not detected (try modprobing l2tp_ppp and pppol2tp)
xl2tpd[10387]: xl2tpd version xl2tpd-1.3.8 started on li1553-82.members.linode.com PID:10387
xl2tpd[10387]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
xl2tpd[10387]: Forked by Scott Balmos and David Stipp, (C) 2001
xl2tpd[10387]: Inherited by Jeff McAdams, (C) 2002
xl2tpd[10387]: Forked again by Xelerance (www.xelerance.com) (C) 2006-2016
xl2tpd[10387]: Listening on IP address 0.0.0.0, port 1701
xl2tpd[10387]: udp_xmit failed to 175.162.175.181:52485 with err=-1:No such device
xl2tpd[10387]: control_finish: Peer requested tunnel 29 twice, ignoring second one.
xl2tpd[10387]: udp_xmit failed to 175.162.175.181:52485 with err=-1:No such device
xl2tpd[10387]: udp_xmit failed to 175.162.175.181:52485 with err=-1:No such device
xl2tpd[10387]: control_finish: Peer requested tunnel 29 twice, ignoring second one.
xl2tpd[10387]: udp_xmit failed to 175.162.175.181:52485 with err=-1:No such device
xl2tpd[10387]: udp_xmit failed to 175.162.175.181:52485 with err=-1:No such device
xl2tpd[10387]: control_finish: Peer requested tunnel 29 twice, ignoring second one.
xl2tpd[10387]: udp_xmit failed to 175.162.175.181:52485 with err=-1:No such device
xl2tpd[10387]: udp_xmit failed to 175.162.175.181:52485 with err=-1:No such device
^Cxl2tpd[10387]: death_handler: Fatal signal 2 received
xl2tpd[10387]: udp_xmit failed to 175.162.175.181:52485 with err=-1:No such device
xl2tpd[10387]: Connection 29 closed to 175.162.175.181, port 52485 (Server closing)

**Comment by hwdsl2** [comment]
@goodboy0924 Hello! This is due to an xl2tpd bug [1] under Linux kernel 4.15.x. As a workaround please switch to a different kernel version in your Linode control panel (or switch to distribution-supplied Linux kernel [2]).

[1] https://github.com/xelerance/xl2tpd/issues/147
[2] https://linode.com/docs/tools-reference/custom-kernels-distros/run-a-distribution-supplied-kernel-with-kvm/
