### ISSUE TITLE
最近老是链接不上VPN，是否与某会召开有关？

### ISSUE THREAD

**Issue by hellowords** [hwdsl2/setup-ipsec-vpn#337]
使用linode服务器，之前很稳定，但是前段时间开始一直链接不上，新建一个vps主机，大多时候连ssh都连不上，好不容易搭建成功一个，用了没几天又无法链接，期间没做任何更改。这是为什么呢？

**Comment by WangDaoO** [comment]
应该是这样的，我遇到了同样的问题，更换一次ip之后一个星期就不能连接了，今天换了服务器同样连接不上
