### ISSUE TITLE
IPsec Transform refused

### ISSUE THREAD

**Issue by mikey411vm** [hwdsl2/setup-ipsec-vpn#338]
I am trying to connect to this ipsec vpn via a chromebook and receiving the following log error:

Mar 17 02:48:27 instance-1 pluto[2424]: "l2tp-psk"[5] 74.70.80.172 #17: **ESP IPsec Transform refused: AES_GCM_16_128-NONE**
Mar 17 02:48:27 instance-1 pluto[2424]: "l2tp-psk"[5] 74.70.80.172 #17: **no acceptable Proposal in IPsec SA**

My ipsec.conf file is as follows:

version 2.0

config setup
  virtual-private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:!192.168.42.0/24,%v4:!192.168.43.0/24
  protostack=netkey
  interfaces=%defaultroute
  uniqueids=no

conn shared
  left=%defaultroute
  leftid=35.190.159.238
  right=%any
  encapsulation=yes
  authby=secret
  pfs=no
  rekey=no
  keyingtries=5
  dpddelay=30
  dpdtimeout=120
  dpdaction=clear
  **ike=3des-sha1,3des-sha2,aes-sha1,aes-sha1;modp1024,aes-sha2,aes-sha2;modp1024,aes256-sha2_512
  phase2alg=3des-sha1,aes-sha1,aes-sha2,aes256-sha2_512**
  sha2-truncbug=yes

conn l2tp-psk
  auto=add
  leftprotoport=17/1701
  rightprotoport=17/%any
  type=transport
  phase2=esp
  also=shared

conn xauth-psk
  auto=add
  leftsubnet=0.0.0.0/0
  rightaddresspool=192.168.43.10-192.168.43.250
  modecfgdns="8.8.8.8, 8.8.4.4"
  leftxauthserver=yes
  rightxauthclient=yes
  leftmodecfgserver=yes
  rightmodecfgclient=yes
  modecfgpull=yes
  xauthby=file
  ike-frag=yes
  ikev2=never
  cisco-unity=yes
  also=shared

Presumably, aes-gmc-16-128 needs to be in the IKE configuration line? I've tried adding it in there as well as in the phase2 line but haven't had luck. It may be a syntax issue, as I am quite the beginner... Any help would be appreciated! I've been successful in accessing from a Windows 10 and an iOS machine as well as an Android Oreo phone.

**Comment by hwdsl2** [comment]
@mikey411vm Hello! Unfortunately Chromebook requires`phase2alg=aes_gcm-null` or similar [1] but this configuration would not allow other platforms (e.g. Android) to connect, so there is no good solution at this point.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/issues/265
