### ISSUE TITLE
Cannot ping Local IP 

### ISSUE THREAD

**Issue by kunjuvaavas** [hwdsl2/setup-ipsec-vpn#339]
Its connecting but internal ip ping is timing out

**Comment by WangDaoO** [comment]
I  think you should first search how ping works?

**Comment by hwdsl2** [comment]
@kunjuvaavas Hello! When connecting using IPsec/L2TP, the default IPTables configuration does allow pings within the VPN subnet (192.168.42.1 for the VPN server and 192.168.42.10 and up for VPN clients).
