### ISSUE TITLE
Is it available to enable IKEv2?

### ISSUE THREAD

**Issue by littleguga** [hwdsl2/setup-ipsec-vpn#34]
os: ubuntu 14.04

If yes - how i can do this?

I tried:(in `/etc/ipsec.conf`)
```
conn xauth-psk
  #ikev2=never
  keyexchange=ikev2
```
but get; (`/var/log/syslog/`):
```
Jun 24 01:21:33 unix xl2tpd[29837]: death_handler: Fatal signal 15 received
Jun 24 01:21:34 unix xl2tpd[30198]: setsockopt recvref[30]: Protocol not available
Jun 24 01:21:34 unix xl2tpd[30198]: This binary does not support kernel L2TP.
Jun 24 01:21:34 unix xl2tpd[30199]: xl2tpd version xl2tpd-1.3.6 started on unix PID:30199
```

**Comment by hwdsl2** [comment]
Sorry, `IKEv2` is not supported yet. Please search GitHub for other alternatives. Here are some examples (I have not tested these):

https://github.com/gaomd/docker-ikev2-vpn-server  
https://github.com/quericy/one-key-ikev2-vpn

**Comment by littleguga** [comment]
> not supported yet

So it planned to be added?

**Comment by hwdsl2** [comment]
Not planned, sorry. 

From what I understand, IKEv2 is best used with certificates, which would add more complexity to the script and client setup.

**Comment by littleguga** [comment]
@hwdsl2 got it. 

Big thank to you for your work!

**Comment by hwdsl2** [comment]
@lgg @yandy @XPOTiFY   
An IKEv2 How-To for Windows 7 and newer is now available [1]. This is for advanced users only.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md
