### ISSUE TITLE
AliYun Install L2TP Don't Connection

### ISSUE THREAD

**Issue by aarongo** [hwdsl2/setup-ipsec-vpn#340]
在阿里云服务器上进行安装xl2tpd 但是远端客户端无法连接,服务本身启动正常

**Comment by WangDaoO** [comment]
首先，如果是为了翻墙的话，使用国内服务器是没有意义的，因为服务器本身就在墙内…
然后是最近两会期间，和这些协议相关的端口传输都莫名丢失数据…

**Comment by wangzhenjjcn** [comment]
windows要用客户端，手机应该可以的

**Comment by hwdsl2** [comment]
@aarongo 你好！阿里云服务器对 VPN 有限制，参见 #160 。
