### ISSUE TITLE
Can't see ports 500 and 4500 from outside

### ISSUE THREAD

**Issue by GabLeRoux** [hwdsl2/setup-ipsec-vpn#342]
Hi there,
Thanks for this well documented project. I just tried this on a brand new Debian 9 server on AWS, but I can't manage to connect to it using MacOs.

```bash
ssh my-vpn-server
sudo apt-get update && sudo apt-get upgrade -y
wget https://git.io/vpnsetup -O vpnsetup.sh && sudo sh vpnsetup.sh
```

Everything installed correctly, services are running. I've created my Security Groups and correctly attached to instance:

![image](https://user-images.githubusercontent.com/1264761/37801052-6ee43294-2dfb-11e8-9262-520385467d36.png)

But `500` and `4500` aren't attached on `0.0.0.0`. I see a few 500 and 4500, but state

```bash
sudo netstat -peanut
```
```
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          22812      7703/sshd
tcp        0    356 <SNIP>:22        199.91.205.230:49220    ESTABLISHED 0          13576      562/sshd: admin [pr
tcp6       0      0 :::22                   :::*                    LISTEN      0          22821      7703/sshd
udp        0      0 127.0.0.1:323           0.0.0.0:*                           0          12979      507/chronyd
udp        0      0 0.0.0.0:68              0.0.0.0:*                           0          11659      283/dhclient
udp        0      0 127.0.0.1:4500          0.0.0.0:*                           0          41303      24042/pluto
udp        0      0 <SNIP>:4500      0.0.0.0:*                           0          41301      24042/pluto
udp        0      0 0.0.0.0:1701            0.0.0.0:*                           0          40338      23730/xl2tpd
udp        0      0 127.0.0.1:500           0.0.0.0:*                           0          41302      24042/pluto
udp        0      0 <SNIP>:500       0.0.0.0:*                           0          41300      24042/pluto
udp6       0      0 fe80::898:2dff:fed7:546 :::*                                0          11839      365/dhclient
udp6       0      0 ::1:323                 :::*                                0          12980      507/chronyd
udp6       0      0 ::1:500                 :::*                                0          41304      24042/pluto
```

From the server itself:

```bash
nmap -Pn localhost -p 500,4500
```
```
Starting Nmap 7.40 ( https://nmap.org ) at 2018-03-22 22:05 UTC
Nmap scan report for localhost (127.0.0.1)
Host is up (0.000070s latency).
PORT     STATE  SERVICE
500/tcp  closed isakmp
4500/tcp closed sae-urn

Nmap done: 1 IP address (1 host up) scanned in 0.03 seconds
```

I know Security Group and firewall rules are correctly set as I did the following test:

```bash
python -m SimpleHTTPServer 500 &
python -m SimpleHTTPServer 4500 &
```

and I was able to see webservers from the outside and also, the commands didn't fail to attach on ports so they were free for `0.0.0.0`. 

Here's how I attempt to connect to the vpn:

![image](https://user-images.githubusercontent.com/1264761/37801676-dbe8e388-2dfd-11e8-9c09-5d56487baccb.png)

![image](https://user-images.githubusercontent.com/1264761/37801717-02516d60-2dfe-11e8-8251-397fb93b6a8d.png)

I'll update here if I find the solution.

**Comment by hwdsl2** [comment]
@GabLeRoux Hello! You should open UDP ports 500 and 4500 in your security
group, NOT TCP.

**Comment by GabLeRoux** [comment]
Ohh thanks! That sounds totally right. Trying it right now. I'm used to work with tcp ahah 👍

**Comment by GabLeRoux** [comment]
![image](https://user-images.githubusercontent.com/1264761/37802372-8d002ed6-2e00-11e8-8b7d-4db67441388f.png)
Right, that was simple as that. Should have read your security group documentation more carefully. Thanks!
