### ISSUE TITLE
VM在HK ，VPN 搭建成功，但速度非常慢，原因可能是什么

### ISSUE THREAD

**Issue by abigbone** [hwdsl2/setup-ipsec-vpn#344]
`wget https://git.io/vpnsetup-centos -O vpnsetup.sh && sudo sh vpnsetup.sh`

并且根据情况修改了秘钥和账户密码，但连接速度非常慢，远比ssh 慢多了，可能的原因是什么？

cc  https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md

**Comment by wangzhenjjcn** [comment]
带宽低？

**Comment by wangzhenjjcn** [comment]
@abigbone 你说的是带宽慢还是ping慢，指代不清啊

**Comment by abigbone** [comment]
这是服务器ping google 的值
> PING google.com (172.217.27.142) 56(84) bytes of data.
64 bytes from tsa03s02-in-f142.1e100.net (172.217.27.142): icmp_seq=1 ttl=53 time=16.6 ms
64 bytes from tsa03s02-in-f142.1e100.net (172.217.27.142): icmp_seq=2 ttl=53 time=16.6 ms
64 bytes from tsa03s02-in-f142.1e100.net (172.217.27.142): icmp_seq=3 ttl=53 time=16.7 ms
64 bytes from tsa03s02-in-f142.1e100.net (172.217.27.142): icmp_seq=4 ttl=53 time=16.7 ms
64 bytes from tsa03s02-in-f142.1e100.net (172.217.27.142): icmp_seq=5 ttl=53 time=16.6 ms
^C
这是我电脑ping 服务器的值

> 正在 Ping xxx 具有 32 字节的数据:
> 来自 119.28.189.197 的回复: 字节=32 时间=39ms TTL=49
> 来自 119.28.189.197 的回复: 字节=32 时间=39ms TTL=49
> 来自 119.28.189.197 的回复: 字节=32 时间=38ms TTL=49
> 来自 119.28.189.197 的回复: 字节=32 时间=40ms TTL=49

排除带宽原因， 我访问服务内容，和上传下载都挺好的。就是搭建VPN 连接很慢

**Comment by wangzhenjjcn** [comment]
@abigbone  
首先
apt-get install bc
然后
time echo "scale=5000; 4*a(1)" | bc -l -q
你看看你电脑CPU功耗怎么样
再看看TOP看看SystemLoad多少
然后你就知道是什么问题了

你要在连接VPN后测试Ping值和带宽，服务器测试是没有效果的
带宽测试的话你可以随便wget一个兆级的文件试试

**Comment by wangzhenjjcn** [comment]
或许的服务器上下带宽是不对等的
也就是传统的ADSL上网
比如说一门200Mbps的宽带，其上行带宽可能只有15Mbps
国内一门10Mbps的宽带，上行一般只有2Mbps
所以服务器上行就是你客户端的下行速度，所以造成了这个慢的原因之一呢估计就是这个。
@abigbone

**Comment by abigbone** [comment]
应该是我安装的不对，我在试试看

**Comment by hwdsl2** [comment]
@abigbone 你好！如 @wangzhenjjcn 所述，这个连接速度慢应该是你的网络原因... 不是脚本的问题。
