### ISSUE TITLE
Connection Times out

### ISSUE THREAD

**Issue by azabednego** [hwdsl2/setup-ipsec-vpn#345]
I am not able to connect from my android device. I followed the troubleshooting steps. Restarted services and modified sha2-truncbug=no within ipsec.conf. I also added rules in gce firewall to accept udp:

udp | Apply to all | IP ranges: 0.0.0.0/0 | udp:500, udp:4500

Under xl2tpd /var/log/syslog logs, noticed:

Mar 27 20:13:38 instance-1 xl2tpd[20382]: Listening on IP address 0.0.0.0, port 1701

Shouldn't it be listening on a specific IP address?

Any help would be appreciated.

**Comment by azabednego** [comment]
Here are the logs:

/var/log/auth.log
https://pastebin.com/U8VafFiF

/var/log/syslog
https://pastebin.com/BZWp4KXu

**Comment by wangzhenjjcn** [comment]
it seems like u link to your self machine

**Comment by azabednego** [comment]
How is this resolved?

**Comment by trejkaz** [comment]
Similar thing going on here after running the currently published version - it says it started the server, but when I try to connect, I can't.

**Comment by hwdsl2** [comment]
@azabednego Hello! Your logs indicate that the IPsec PSK you entered on your VPN client does not match that on your VPN server. Please double check your VPN client configuration.
