### ISSUE TITLE
阿里云美国服务器，安装了xl2tpd服务，但mac和windows都连接不上。  aliyun's American server,the xl2tpd cannot work

### ISSUE THREAD

**Issue by lvmin** [hwdsl2/setup-ipsec-vpn#346]
太纳闷了，这台机器原先是可以连上的，用的还是hwdsl2的老的脚本。
那次不知道是动了什么，连不上了，
这次就用的最新的脚本，是centos的脚本。
也连接不上了。

而且windows  mac  IOS  android连接的时候，都没有日志信息，
因为是centos系统的，/var/log/messages看的该系统日志文件，连接的时候一直没有信息。

不知道什么原因.

电脑端连接的时候一直报809错误。

我按照hwdsl2的说明，设置了注册表，REG ADD HKLM\SYSTEM\CurrentControlSet\Services\PolicyAgent /v AssumeUDPEncapsulationContextOnSendRule /t REG_DWORD /d 0x2 /f
但还是不行，依然是809

再执行更改ipsec加密的那行命令，REG ADD HKLM\SYSTEM\CurrentControlSet\Services\RasMan\Parameters /v ProhibitIpSec /t REG_DWORD /d 0x0 /f
结果错误成了789，L2TP连接失败。

不知道为甚了。

====================

before, this server can connect vpn.
then I have no idea what happened.

this time I used the newest script to run , still cannot connect.

and there is no message in log file.

the error number is 809, but I used the command to change the registry, it's still 809.

then I use another command line to change the ipsec encryption, it turned out the 789 error.

I dont know why.

please help!!!!

**Comment by hwdsl2** [comment]
@lvmin 你好！如果你使用多个不同客户端 (Windows, macOS, iOS, Android) 都连接不上，很可能是因为你的服务器被防火墙屏蔽了。建议换用其它服务器提供商，或者换用其它解决方案比如 Shadowsocks.

**Comment by wangzhenjjcn** [comment]
@lvmin  @hwdsl2 
在阿里的控制台有个安全组，添加0.0.0.0/0 的 TCP和UDP 在500 4500  1702 45等端口的允许
否则背墙
