### ISSUE TITLE
Can not connect from Win 10

### ISSUE THREAD

**Issue by sukiman** [hwdsl2/setup-ipsec-vpn#347]
Hi, I have tried both regedit workarounds, but still can't connect. 
The error message is not showing error code, but the Event Viewer shows 809

> The user SYSTEM dialed a connection named VPN which has failed. The error code returned on failure is 809.

My VPN server is running Centos 7. I am completely newbie, could you help me troubleshoot?

PS: I can connect from Android phone connected to the same network my PC connected to.

**Comment by hwdsl2** [comment]
@sukiman Hello! Did you reboot your PC after applying the regedit workaround? Also make sure you added the correct keys and values to the registry (check for typos).

**Comment by sukiman** [comment]
Hey, it works after 'Network reset'. 
I still can't connect from Windows Phone (same 809 error) but that's a different issue.
Thanks!

**Comment by OCT-Burnz** [comment]
What is "Network reset". I have the same issue here.

**Comment by i386net** [comment]
> What is "Network reset". I have the same issue here.
`netsh winsock reset`

**Comment by hwdsl2** [comment]
@sukiman Glad to hear it works now. If anyone still has this problem, please open a new issue and provide the Libreswan/xl2tpd logs for troubleshooting. See [1].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps
