### ISSUE TITLE
用的是Centos版的一键sh，win7连接没问题，按照linux的连接方式一步步来的就提示：

### ISSUE THREAD

**Issue by zxing2004** [hwdsl2/setup-ipsec-vpn#348]

**Comment by zxing2004** [comment]
服务器记录：
Apr  4 17:58:28 iZwz90tx4egvh4lhkuw2y1Z pluto[26875]: "l2tp-psk"[4] 222.209.29.98 #5: responding to Main Mode from unknown peer 222.209.29.98 on port 500
Apr  4 17:58:28 iZwz90tx4egvh4lhkuw2y1Z pluto[26875]: "l2tp-psk"[4] 222.209.29.98 #5: WARNING: connection l2tp-psk PSK length of 8 bytes is too short for sha PRF in FIPS mode (10 bytes required)
Apr  4 17:58:28 iZwz90tx4egvh4lhkuw2y1Z pluto[26875]: "l2tp-psk"[4] 222.209.29.98 #5: STATE_MAIN_R1: sent MR1, expecting MI2
Apr  4 17:58:32 iZwz90tx4egvh4lhkuw2y1Z pluto[26875]: "l2tp-psk"[4] 222.209.29.98 #5: retransmitting in response to duplicate packet; already STATE_MAIN_R1
Apr  4 17:58:39 iZwz90tx4egvh4lhkuw2y1Z pluto[26875]: "l2tp-psk"[4] 222.209.29.98 #5: retransmitting in response to duplicate packet; already STATE_MAIN_R1
Apr  4 17:58:52 iZwz90tx4egvh4lhkuw2y1Z pluto[26875]: "l2tp-psk"[4] 222.209.29.98 #5: retransmitting in response to duplicate packet; already STATE_MAIN_R1

**Comment by hwdsl2** [comment]
@zxing2004 Hello! Please open a new issue with the required details (what output or error did you see?).
