### ISSUE TITLE
Docker port bind on IPv6 ...

### ISSUE THREAD

**Issue by u-u-z** [hwdsl2/setup-ipsec-vpn#350]
When we start docker by 

`docker run     --name ipsec-vpn-server     --env-file ./vpn.env     --restart=always     -p 500:500/udp     -p 4500:4500/udp     -v /lib/modules:/lib/modules:ro     -d --privileged     hwdsl2/ipsec-vpn-server`

command .

it will bind on a IPv6 address I can't use IPv4 to connect it :-(

`scarlet ~ # netstat -nupl
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
udp        0      0 98.11.23.90:68          0.0.0.0:*                           544/systemd-network
udp6       0      0 :::4500                 :::*                                20907/docker-proxy
udp6       0      0 :::500                  :::*                                20918/docker-proxy
udp6       0      0 f9e0::f23b:1f3f:fe5:546 :::*                                544/systemd-network
udp6       0      0 f9e0::fb00:1f1:f362:546 :::*                                544/systemd-network`

**Comment by hwdsl2** [comment]
@u-u-z Hello! The output you see in "netstat" on a Docker host appears to show binding only to IPv6, but in fact it binds to both IPv4 and IPv6. You should be able to connect using your Docker host's IPv4 address.
