### ISSUE TITLE
CentOS 7 w/ WiFi can't instal

### ISSUE THREAD

**Issue by coderboy14** [hwdsl2/setup-ipsec-vpn#351]
I run a personal server at home, on a CentOS desktop, which uses WiFi. I know it's not a good idea, and I should use hardwired connections, but right now, this is what I have. I can't install it because after running the command `sudo sh vpnsetup.sh` is says `Error: Wireless interface 'wlp4s0' detected. DO NOT run this script on your PC or Mac!` is there any way to bypass this?

**Comment by hwdsl2** [comment]
@coderboy14 Hello! For your specific use case you may comment out these lines in the VPN script [1] before using it.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/vpnsetup.sh#L78-L84
