### ISSUE TITLE
Ignoring NUL at end of XAUTH User Password (Android Issue 36879?)

### ISSUE THREAD

**Issue by wangzhenjjcn** [hwdsl2/setup-ipsec-vpn#353]
problem as this
Ignoring NUL at end of XAUTH User Password (Android Issue 36879?)
And cannot use 
# IPsec whack --trafficstatus 
#grep "ESP traffic information: "  /var/log/auth.log
to view connector's IP address
So how to solve this NUL problem

pluto[18282]: "xauth-psk"[160] IP.IP.IP.IP #580:responding to Main Mode from unknown peer IP.IP.IP.IP on port 10778
#580: STATE_MAIN_R1: sent MR1, expecting MI2
#580: STATE_MAIN_R2: sent MR2, expecting MI3
#580: Peer ID is ID_IPV4_ADDR: '192.168.1.102'
#580: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=aes_256 integ=sha2_256 group=MODP1024}
#580: ignoring informational payload IPSEC_INITIAL_CONTACT, msgid=00000000, length=28
#580: received and ignored informational message
#580: XAUTH: Sending Username/Password request (MAIN_R3->XAUTH_R0)
#580: Ignoring NUL at end of XAUTH User Password (Android Issue 36879?)
#580: XAUTH: password file authentication method requested to authenticate user '$$$$$$'
#580: XAUTH: password file (/etc/ipsec.d/passwd) open.
#580: XAUTH: success user($$$$$$$:xauth-psk)
#580: XAUTH: #580: completed for user '$$$$$$$$$' with status SUCCESSS
#580: XAUTH: User $$$$$$$$ Authentication Successful
#580: XAUTH: xauth_inR1(STF_OK)
#580: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=aes_256 integ=sha2_256 group=MODP1024}
#580: modecfg_inR0(STF_OK)
#580: STATE_MODE_CFG_R1: ModeCfg Set sent, expecting Ack {auth=PRESHARED_KEY cipher=aes_256 integ=sha2_256 group=MODP1024}
#580: the peer proposed: 0.0.0.0/0:0/0 -> 192.168.43.59/32:0/0

**Comment by hwdsl2** [comment]
@wangzhenjjcn Hello! The `Ignoring NUL at end of XAUTH User Password (Android Issue 36879?)` line in your logs simply means Libreswan successfully applied such a workaround. No issue with that line. If you cannot connect, try the troubleshooting steps [1].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#android-6-and-above

**Comment by hwdsl2** [comment]
@wangzhenjjcn 这个是安卓系统某些版本的bug，不是协商问题。请搜索并参见 Android Issue 36879
