### ISSUE TITLE
IPsec/XAuth multi connection with same IP

### ISSUE THREAD

**Issue by sudanking** [hwdsl2/setup-ipsec-vpn#357]
when the first user connects using IPsec/XAuth it is working fine..... but next user when it is get connected it gets the same IP that gets the first user (first IP in the pool).
Any idea??

**Comment by wjmwjmwb** [comment]
under the same nat. I have the same problem

**Comment by sudanking** [comment]
I found a solution. you can set mark=%unique so that these conflicts won't cause any
more problems.

**Comment by sudanking** [comment]
above tip no working.... but when I use mark=-1 configuration accepted... and each user get a new IP from IP pool... but no internet connection!!!

**Comment by wjmwjmwb** [comment]
It is Libreswan's problems. did you tried certificates , rather then passwords.....
https://github.com/libreswan/libreswan/issues/166

**Comment by DozenFrozen** [comment]
The problem remains even if you use different logins and passwords. I do not know what to do. It remains only to wait?

**Comment by hwdsl2** [comment]
@sudanking @wjmwjmwb @DozenFrozen Hello! This is a know issue [1] in Libreswan. They are working on a fix for the next release.

[1] https://github.com/libreswan/libreswan/issues/166

**Comment by letoams** [comment]
note libreswan 3.26 was released that addresses the issue related to bad lease ip re-use
