### ISSUE TITLE
[Request] disable/allow user connection without PSK

### ISSUE THREAD

**Issue by CristianPietrobon** [hwdsl2/setup-ipsec-vpn#358]
Hi, my modem router doesn't support PSK, ther's a way to enable an unsecure connection but allowing other client (ex. my phone) to connect using the PSK?
Thanks

**Comment by Twml1500** [comment]
You should look at using the less secure PPTP vpn. this only uses username/password. 

the whole point of a L2TP/IPSec vpn is the encryption with a PSK

**Comment by hwdsl2** [comment]
@CristianPietrobon Hello! Using L2TP without IPsec is not recommended from a security perspective, as the traffic is not encrypted.
