### ISSUE TITLE
ping延时相差10至20毫秒左右

### ISSUE THREAD

**Issue by huangsen365** [hwdsl2/setup-ipsec-vpn#362]
您好，我有台服务器已经部署此ipsec-vpn服务，
假如服务器端公网ip为123.123.123.123，对应的IPSEC-VPN服务所获得的IP为192.168.42.1，
我的客户端拨入连接此ipsec-vpn服务器，获得的IP为192.168.42.100，
现发现有个问题，以下两个ping测试得到的延时相差10至20毫秒左右，

- 在我的客户端ping 123.123.123.123 为25毫秒左右
- 在我的客户端ping 192.168.42.1 为35至45毫秒左右

理论上来讲，123.123.123.123和192.168.42.1的链路层都是一样的，理应得到的ping延时也比较接近才对的。请问这种情况下有可能跟ipsec-vpn背后所需的底层库/对应服务所消耗的资源有关吗？

多谢解答！

**Comment by wangzhenjjcn** [comment]
ping 123.123.123.123 是直接过路由器路由表往外网发的，
ping 192.x.x.x首先要在局域网里走一圈然后再外发
你有两个局域网，本地192.168.1.x和192.168.41.x所以慢点有可能是本地路由表的问题
跃点设置下可能就好了

**Comment by hwdsl2** [comment]
@huangsen365 你好！这个可能与你说的IPsec 链接的底层库/对应服务的延时有关。具体我也不清楚。
