### ISSUE TITLE
iPhoneX 连接 提示用户鉴定失败

### ISSUE THREAD

**Issue by byf6663** [hwdsl2/setup-ipsec-vpn#365]
mac 安卓 iphone6 win  通通都可以，好奇怪啊，求指导

**Comment by hwdsl2** [comment]
@byf6663 Hello! Please provide the Libreswan/xl2tpd logs for further troubleshooting. See [1].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps

**Comment by hwdsl2** [comment]
Closed due to inactivity.
