### ISSUE TITLE
I can not connect to iOS 11.3. 

### ISSUE THREAD

**Issue by almaziphone** [hwdsl2/setup-ipsec-vpn#368]
I can not connect to iOS 11.3. C Elementary OS without problems

**Comment by Var-iazioni** [comment]
Try windows or android device.

**Comment by wangzhenjjcn** [comment]
@almaziphone  check your linkway
if l2tp, make sure your username and password in the chap-secrets file
else use IPsec and save your password and username in ipsec.d/passwd

**Comment by hwdsl2** [comment]
@almaziphone Hello! Cannot reproduce the issue on an iOS 11.3 device. The VPN connected successfully. Please double check your configuration.
