### ISSUE TITLE
如何对用户进行权限添加

### ISSUE THREAD

**Issue by guihouchang** [hwdsl2/setup-ipsec-vpn#369]
我想让某个用户在某个时间段可以使用，要这么处理呢？
例如,user A 使用期限是1月1号-2月1号，这样子的功能。要怎么做？借助编程语言？对/etc/ppp/chap-secrets文件进行添加和修改？

**Comment by hwdsl2** [comment]
@guihouchang Hello! The feature you mentioned is outside the scope of this project.
