### ISSUE TITLE
L2TP 和 shadowsocks 共存

### ISSUE THREAD

**Issue by yangchengwork** [hwdsl2/setup-ipsec-vpn#37]
我看到之前的问题，https://github.com/hwdsl2/setup-ipsec-vpn/issues/30 
我也碰到同样的问题，现将这部分的信息附后。其中3388端口是我使用的ss端口，在没有安装L2TP前确认可以使用。希望可以一起解决这个问题

$ sudo iptables -nvL
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
pkts bytes target prot opt in out source destination

10 560 fail2ban-ssh tcp -- * * 0.0.0.0/0 0.0.0.0/0 multiport dports 22
0 0 DROP all -- * * 0.0.0.0/0 0.0.0.0/0 ctstate INVALID
18 1115 ACCEPT all -- * * 0.0.0.0/0 0.0.0.0/0 ctstate RELATED,ESTABLISHED
0 0 ACCEPT all -- lo * 0.0.0.0/0 0.0.0.0/0

0 0 REJECT all -- * * 0.0.0.0/0 127.0.0.0/8 reject-with icmp-port-unreachable
0 0 ACCEPT icmp -- * * 0.0.0.0/0 0.0.0.0/0

0 0 ACCEPT udp -- * * 0.0.0.0/0 0.0.0.0/0 udp spts:67:68 dpts:67:68
0 0 ACCEPT tcp -- * * 0.0.0.0/0 0.0.0.0/0 tcp dpt:22
0 0 ACCEPT udp -- * * 0.0.0.0/0 0.0.0.0/0 multiport dports 500,4500
0 0 ACCEPT udp -- * * 0.0.0.0/0 0.0.0.0/0 udp dpt:1701 policy match dir in pol ipsec
0 0 DROP udp -- * * 0.0.0.0/0 0.0.0.0/0 udp dpt:1701
12 608 DROP all -- * * 0.0.0.0/0 0.0.0.0/0

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
pkts bytes target prot opt in out source destination

0 0 DROP all -- * * 0.0.0.0/0 0.0.0.0/0 ctstate INVALID
0 0 ACCEPT all -- eth+ ppp+ 0.0.0.0/0 0.0.0.0/0 ctstate RELATED,ESTABLISHED
0 0 ACCEPT all -- ppp+ eth+ 0.0.0.0/0 0.0.0.0/0

0 0 ACCEPT all -- ppp+ ppp+ 192.168.42.0/24 192.168.42.0/24

0 0 ACCEPT all -- eth+ * 0.0.0.0/0 192.168.43.0/24 ctstate RELATED,ESTABLISHED
0 0 ACCEPT all -- * eth+ 192.168.43.0/24 0.0.0.0/0

0 0 DROP all -- * * 0.0.0.0/0 0.0.0.0/0

Chain OUTPUT (policy ACCEPT 6 packets, 674 bytes)
pkts bytes target prot opt in out source destination

Chain fail2ban-ssh (1 references)
pkts bytes target prot opt in out source destination

0 0 REJECT all -- * * 61.51.18.101 0.0.0.0/0 reject-with icmp-port-unreachable
10 560 RETURN all -- * * 0.0.0.0/0 0.0.0.0/0

$ sudo iptables -nvL -t nat
Chain PREROUTING (policy ACCEPT 44 packets, 2232 bytes)
pkts bytes target prot opt in out source destination

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
pkts bytes target prot opt in out source destination

Chain OUTPUT (policy ACCEPT 2 packets, 178 bytes)
pkts bytes target prot opt in out source destination

Chain POSTROUTING (policy ACCEPT 2 packets, 178 bytes)
pkts bytes target prot opt in out source destination

0 0 SNAT all -- * eth+ 192.168.42.0/24 0.0.0.0/0 to:XX.XX.XX.XX
0 0 SNAT all -- * eth+ 192.168.43.0/24 0.0.0.0/0 policy match dir out pol none to:XX.XX.XX.XX

$ sudo netstat -anput
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address Foreign Address State PID/Program name
tcp 0 0 0.0.0.0:22 0.0.0.0:* LISTEN 978/sshd

tcp 0 0 XX.XX.XX.XX:3388 0.0.0.0:* LISTEN 1583/python

tcp 0 332 XX.XX.XX.XX:22 211.162.33.131:28595 ESTABLISHED 1702/sshd: ubuntu [
tcp6 0 0 :::22 :::* LISTEN 978/sshd

udp 0 0 127.0.0.1:4500 0.0.0.0:* 7749/pluto

udp 0 0 XX.XX.XX.XX:4500 0.0.0.0:* 7749/pluto

udp 0 0 127.0.0.1:500 0.0.0.0:* 7749/pluto

udp 0 0 XX.XX.XX.XX:500 0.0.0.0:* 7749/pluto

udp 0 0 0.0.0.0:68 0.0.0.0:* 651/dhclient

udp 0 0 0.0.0.0:63124 0.0.0.0:* 651/dhclient

udp 0 0 0.0.0.0:1701 0.0.0.0:* 7767/xl2tpd

udp 0 0 XX.XX.XX.XX:3388 0.0.0.0:* 1583/python

udp6 0 0 :::61828 :::* 651/dhclient

udp6 0 0 ::1:500 :::* 7749/pluto

**Comment by hwdsl2** [comment]
@yangchengwork 你好！请运行以下命令为Shadowsocks添加防火墙规则：

```
iptables -I INPUT 9 -p tcp --dport 3388 -j ACCEPT
iptables -I INPUT 9 -p udp --dport 3388 -j ACCEPT
```

为了保证服务器重启以后应用这些规则，还需将以下行添加到 `/etc/iptables.rules` 和/或 `/etc/iptables/rules.v4` （如果该文件存在）。其中第一行和第四行是已有的行，在它们之间添加两行：

``
-A INPUT -p tcp --dport 22 -j ACCEPT
-A INPUT -p tcp --dport 3388 -j ACCEPT
-A INPUT -p udp --dport 3388 -j ACCEPT
-A INPUT -p udp -m multiport --dports 500,4500 -j ACCEPT
```

**Comment by yangchengwork** [comment]
多谢指导，现在可以使用了。另外发现L2TP没有SS稳定，SS每次都可以连接上，但L2TP就要多次连接

**Comment by hwdsl2** [comment]
@yangchengwork 好的 :+1: SS抗干扰能力相对来说更强一些。

**Comment by leonsim** [comment]
👍
