### ISSUE TITLE
Is only one device at a same time?

### ISSUE THREAD

**Issue by hieudang9** [hwdsl2/setup-ipsec-vpn#374]
Hi @hwdsl2,
 First of all, many thanks for your amazing works. I followed your instructions and successfully. But I only connect 1 device at a same time.
Could you please help me?
Thanks in advance.

**Comment by Mitarexia** [comment]
Are you trying to connect from the same NAT (behind a home router for example)? Not all authentication methods support multiple devices from the same NAT.
