### ISSUE TITLE
Not working with Windows 10 1803

### ISSUE THREAD

**Issue by rayzhu2025** [hwdsl2/setup-ipsec-vpn#376]
Before in Windows 10 1709, no problem. After updating, VPN cannot be connected. Tried the setting again but still failed. Looking forward to a solution. Thanks much!

**Comment by hwdsl2** [comment]
@byf6663 Hello! Please provide the Libreswan/xl2tpd logs for further troubleshooting. See [1].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps

**Comment by rayzhu2025** [comment]
I will try.


Lin Song <notifications@github.com>于2018年5月2日 周三下午2:32写道：

**Comment by trixiefine** [comment]
[auth.log](https://github.com/hwdsl2/setup-ipsec-vpn/files/1993215/auth.log)
[syslog.txt](https://github.com/hwdsl2/setup-ipsec-vpn/files/1993216/syslog.txt)

Confirmed Windows 10 client 1709 version connects.

Windows 10 client version 1803 fails.

Android client connects normally as well.

**Comment by rayzhu2025** [comment]
yup. Any solution?

**Comment by hwdsl2** [comment]
@rayzhu2025 Hello! The logs from @trixiefine indicate that you may need to re-apply the Windows Error 809 fix [1]. The windows update process from 1709 to 1803 most likely have reset or removed this registry key. Try re-applying the fix, reboot your PC, then re-connect the VPN. Let us know if it works.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#windows-error-809

**Comment by rayzhu2025** [comment]
Thank you! I have tried that. Still not working....

**Comment by thereisnotime** [comment]
Won't the Windows registry fix make the connection less secure? @hwdsl2

**Comment by hwdsl2** [comment]
@thereisnotime No, AFAIK it won’t affect the connection security in general.

**Comment by Agraphie** [comment]
I can confirm that it's not working anymore for me either and re-applying the fix mentioned above did not solve the problem.

**Comment by wangzhenjjcn** [comment]
I suggest U use pptpd on win10 platform
apt-get install pptpd  ->>>>> work in china

**Comment by SystemDisc** [comment]
I'm also experiencing this issue. Applying the fix and rebooting does not resolve it.

**Comment by wangzhenjjcn** [comment]
@SystemDisc apt-get install pptpd  
this maybe solute you problem

**Comment by wangzhenjjcn** [comment]
@SystemDisc @rayzhu2025  and open port  500  4500  47  1701 1723

**Comment by SystemDisc** [comment]
I did get it working after the command here: https://github.com/hwdsl2/setup-ipsec-vpn/issues/347#issuecomment-380023930
```shell
netsh winsock reset
```

However, soon afterward, I ran into this problem (all tickets for the same thing): #378 #314 #323 #357 https://github.com/libreswan/libreswan/issues/166

**Comment by rayzhu2025** [comment]
Not a fan of PPTPD...

**Comment by MikeLund** [comment]
@wangzhenjjcn PPTP is insecure. Don't use it, unless there are no alternatives.

**Comment by trixiefine** [comment]
`netsh winsock reset`

Still no luck - same error after resetting, removing, recreating and rebooting (including registry change).

**Comment by pillboxru** [comment]
in ipsec.conf try to change encapsulation=auto
it helps for me to use vpn with error 809 withot any registry changes

**Comment by Suleman-Elahi** [comment]
Running on Windows 10 1803 after applying the registry fix.... thanks.!!!

**Comment by narcisse07** [comment]
fixed my issue

1. Open your Windows Registry Editor by typing regedit in the Search Windows area.

2. Browse to the Registry Key HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\CVirtA or you many have 1.	Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\vpnva 

3. From the window on the right, select and right-click on DisplayName and choose Modify from the menu. Alternatively, double-click on DisplayName: 3.	Change the value to this “ Cisco Systems VPN Adapter for 64-bit Windows”
