### ISSUE TITLE
Can not connect new client if there is an existing client session with the same IP

### ISSUE THREAD

**Issue by bbaker28050** [hwdsl2/setup-ipsec-vpn#378]
I'm trying to provide access to a VPN at my school through my own VPS. As soon as I shared the details with the first person, I discovered that once he was connected, I was not able to connect anymore (We both were on the same access point). We both have our own logins to use it, and I was able to connect via my data. What can I do to fix this issue?

**Comment by hwdsl2** [comment]
@bbaker28050 Hello! Unfortuately this is a known limitation for multiple VPN clients behind the same NAT. See README [1].

[1] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes

**Comment by SystemDisc** [comment]
@hwdsl2 Once 3.24 of libreswan is released, will this project be updated to allow multiple connections from clients behind the same NAT'd network?

https://github.com/libreswan/libreswan/issues/166#issuecomment-389507530

**Comment by hwdsl2** [comment]
@SystemDisc Hello! Users can update their Libreswan installation themselves using these upgrade scripts [1] after Libreswan 3.24 is released. Assuming that the issue is fixed in 3.24, then it should work after upgrading.

[1] https://github.com/hwdsl2/setup-ipsec-vpn#upgrade-libreswan

**Comment by SystemDisc** [comment]
Awesome! Thanks!

**Comment by SystemDisc** [comment]
Upgrading to the latest version worked. See https://github.com/libreswan/libreswan/issues/166#issuecomment-422226790
