### ISSUE TITLE
ESP IPsec Transform refused: AES_CBC_256-HMAC_SHA2_512_256 (Kernel 4.14.34 and xl2tpd)

### ISSUE THREAD

**Issue by avizd** [hwdsl2/setup-ipsec-vpn#380]
I use a Raspberry PI as a Home VPN Server. Everything was working fine until I run an apt-get upgrade that upgrade the kernel to:

Linux RaspPI-N1 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux

After that, the L2TP/PSK vpn stops to work in my Android and iOS devices. The IPSec VPN is working fine just in iOS devices.

When I tried to connect, the auth.log shows the following error messages:
May  1 16:09:50 RaspPI-N1 pluto[1408]: "l2tp-psk"[1] 177.28.122.179 #1: the peer proposed: 177.81.XX.XXX/32:17/1701 -> 177.28.122.179/32:17/0
May  1 16:09:50 RaspPI-N1 pluto[1408]: "l2tp-psk"[1] 177.28.122.179 #11: ESP IPsec Transform refused: AES_CBC_256-HMAC_SHA2_512_256
May  1 16:09:50 RaspPI-N1 pluto[1408]: "l2tp-psk"[1] 177.28.122.179 #11: no acceptable Proposal in IPsec SA
May  1 16:09:50 RaspPI-N1 pluto[1408]: "l2tp-psk"[1] 177.28.122.179 #11: sending encrypted notification NO_PROPOSAL_CHOSEN to 177.28.122.179:4500
May  1 16:09:50 RaspPI-N1 pluto[1408]: "l2tp-psk"[1] 177.28.122.179 #11: deleting state (STATE_QUICK_R0)

I tried to run the vpnsetup.sh again, but the problem was not solved. So I also tried the vpnupgrade.sh and forced the LibreSwan reinstallation, but the problem continues.

I have tried this two configurations at ipsec.conf, but none works:
**CONF1:**
  ike=aes-sha1,aes-sha1;modp1024,aes-sha2,aes-sha2;modp1024,aes256-sha2_512
  phase2alg=aes-sha1,aes-sha2

**CONF2:**
  ike=3des-sha1,3des-sha2,aes-sha1,aes-sha1;modp1024,aes-sha2,aes-sha2;modp1024,aes256-sha2_512
  phase2alg=3des-sha1,3des-sha2,aes-sha1,aes-sha2

I'm using a Samsung Galaxy S8+ with Android 8.0.0 to test the connection with L2TP/PSK.

Any suggestions about how to solve this issue?

**Comment by Agraphie** [comment]
Hi,

I had the same problem and used these lines from #380 and it worked for me

ike=3des-sha1,3des-sha2,aes-sha1,aes-sha1;modp1024,aes-sha2,aes-sha2;modp1024,aes256-sha2_512
phase2alg=3des-sha1,aes-sha1,aes-sha2,aes256-sha2_512

**Comment by avizd** [comment]
Hi Agraphie,

I solved my problem making a raspian kernel downgrade, using the procedure at this link:
https://isahatipoglu.com/2015/09/29/how-to-upgrade-or-downgrade-raspberrypis-kernel-servoblaster-problem-raspberry-pi2/

It seems to be an unsolved issue between kernel 4.14 and above with the xl2tpd daemon. I returned my raspberry to 4.9.80 and everything works fine again. I will wait some time to upgrade to 4.14.34 again, so I unable to test the parameters you mentioned.

Dou you use an Android device to connect to you VPN with this parameters? Are you running with Raspbian Kernel 4.14.34?

Thanks,

Daniel.

**Comment by Agraphie** [comment]
Hi Daniel,

I'm not using a raspberry PI so I cannot comment on that. I'm using the Debian kernel 3.16.0-6-amd64 and an Android device with version 8.0. As I said, with the new parameters I was able to connect, with the old ones I wasn't.

Best regards

**Comment by hwdsl2** [comment]
@avizd Hello! As you have observed, Linux kernels 4.14/4.15 have some issues with xl2tpd [1] [2]. For now please continue to use kernel 4.9 on your Raspberry Pi.

[1] https://github.com/libreswan/libreswan/issues/140
[1] https://github.com/xelerance/xl2tpd/issues/147
