### ISSUE TITLE
Simple way to setup ipsec vpn on Digital Ocean

### ISSUE THREAD

**Issue by ozonni** [hwdsl2/setup-ipsec-vpn#381]
I'm working on simplifying IPSec VPN setup on Digital Ocean. Was wondering if you would like to include it to README.md as alternative way to get your own VPN.

- url: https://ozonni.github.io/do-vpn/
- github: https://github.com/ozonni/do-vpn

**Comment by hwdsl2** [comment]
@ozonni Thank you for sharing your awesome work with us! However because we already have a DigitalOcean VPN setup website dovpn.carlfriess.com linked in the README, I would prefer not to link another at this time.
