### ISSUE TITLE
Run Nginx behind VPN

### ISSUE THREAD

**Issue by Luxbit** [hwdsl2/setup-ipsec-vpn#382]
I have an Nginx web server and a VPN running on the same server. 
How do I have to configure Nginx, so it can only be reached by a client when connected to the VPN.

Thanks

**Comment by hwdsl2** [comment]
@Luxbit Hello! In the default configuration, when VPN clients connect via IPsec/L2TP, the VPN server will have internal IP of `192.168.42.1` within the VPN subnet `192.168.42.0/24`. For your use case, you may be able to configure Nginx to listen on this IP only.
