### ISSUE TITLE
cant pass phase 2

### ISSUE THREAD

**Issue by ChrisZoc** [hwdsl2/setup-ipsec-vpn#384]
im starting to implement a new ipsec tunnel site to site using openswan the other site is using fortigate vpn and the config:
---Phase 1---
*IKEV1
*D-H Group 2
*3-des
*sha-1
*Main Mode Tunel
*86400s
---Phase 2---
*ESP
*3-des
*sha-1
*NO PFS
*3600s

and im receiving a error in the pluto.log that tell me 

"mytunnel" #2: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=3des_cbc_192 integ=sha group=MODP1024}
May  8 11:33:03.622862: | modecfg pull: noquirk policy:push not-client
May  8 11:33:03.622866: | **phase 1 is done, looking for phase 2 to unpend**
May  8 11:33:03.622870: | unpending state #2
May  8 11:33:03.622876: | processing: stop from 170.238.170.132:500 (BACKGROUND) (in comm_handle() at demux.c:375)
May  8 11:33:03.622882: | processing: stop state #2 connection "mytunnel" 170.238.170.132:500 (in comm_handle() at demux.c:380)
May  8 11:33:03.622886: | serialno table: hash serialno #0 to head 0x559f9274e200
May  8 11:33:03.622890: | serialno table: hash serialno #0 to head 0x559f9274e200
May  8 11:33:03.622894: | processing: STOP connection NULL (in comm_handle() at demux.c:381)
May  8 11:33:05.922288: | timer_event_cb: processing event@0x559f94443a18
May  8 11:33:05.922371: | handling event EVENT_v1_RETRANSMIT for parent state #1

i don't be able to start the phase 2 what think i can do?

**Comment by hwdsl2** [comment]
@ChrisZoc Hello! OpenSwan and site-to-site VPNs are outside the scope of this project. Besides I am not really sure about the error in your logs. I suggest that you instead ask your question on the OpenSwan/Libreswan/strongSwan users mailing lists.
