### ISSUE TITLE
forward to another server / proxy / multilayer

### ISSUE THREAD

**Issue by mhf-ir** [hwdsl2/setup-ipsec-vpn#385]
It's support for forward request to another machine and response it to client:
```
Request:
[Client] ===> [ipsecvpnserver] ===> [reqeusterServer]
Response:
[Client] <=== [ipsecvpnserver] <=== [reqeusterServer]
```
HttpProxy/Socks or another ipsecvpn server.

**Comment by hwdsl2** [comment]
@mhf-ir Hello! Unfortunately this is not currently supported.

**Comment by AnonymousWebHacker** [comment]
nothing?
