### ISSUE TITLE
ikev2 .p12文件 密码问题

### ISSUE THREAD

**Issue by bjwdttz** [hwdsl2/setup-ipsec-vpn#387]
你好，在ikev2设置进行到第四步时，
```
$ pk12util -o vpnclient.p12 -n "vpnclient" -d sql:/etc/ipsec.d
```
我使用回车直接跳过输入密码，在导入证书时密码为空，结果被提醒密码输入错误。
然后又在一个新的客户端证书里面加入了密码，在导入证书时输入相应的密码，结果还是密码错误，请问有好的解决办法吗？谢谢！

**Comment by hwdsl2** [comment]
@bjwdttz 你好！我刚刚又试了一次 IKEv2 文档中的步骤，无论是否设置 `.p12` 文件密码都可以成功的导入证书存储。建议你重新生成 `.p12` 文件再试一下。检查密码是否输入有错误，比如大小写等。

**Comment by zzuzjl** [comment]
> @bjwdttz 你好！我刚刚又试了一次 IKEv2 文档中的步骤，无论是否设置 `.p12` 文件密码都可以成功的导入证书存储。建议你重新生成 `.p12` 文件再试一下。检查密码是否输入有错误，比如大小写等。

我测试也是有问题，在安卓手机上导入证书密码就是对的，在win10上导入证书就提示密码错误，同样的密码啊

**Comment by zzuzjl** [comment]
我把证书导入firefox然后再导出就可以在win10上安装不会提示密码错误了，这应该十个问题，希望早点解决

**Comment by hwdsl2** [comment]
@zzuzjl 你好！这个是已知问题，请参见 [1] 。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#%E5%B7%B2%E7%9F%A5%E9%97%AE%E9%A2%98

**Comment by zzuzjl** [comment]
> @zzuzjl 你好！这个是已知问题，请参见 [1] 。
> 
> [1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md#%E5%B7%B2%E7%9F%A5%E9%97%AE%E9%A2%98

好的，谢谢，我去看看
