### ISSUE TITLE
求帮助：使用此基本搭建VPN服务器后，VPN服务可以正常使用，但外网无法访问80端口的WEB服务了。

### ISSUE THREAD

**Issue by gongjiehong** [hwdsl2/setup-ipsec-vpn#39]
如题，使用此基本搭建VPN服务器后，VPN服务可以正常使用，但外网无法访问80端口的WEB服务了。请问需要怎么设置才能正常使用WEB服务。

**Comment by hwdsl2** [comment]
@gongjiehong 你好！请编辑 `/etc/iptables.rules` 和/或 `/etc/iptables/rules.v4` （如果该文件存在）。在这一行之后 `-A INPUT -p tcp --dport 22 -j ACCEPT` 添加需要的防火墙规则。例如，打开TCP 80端口：

`-A INPUT -p tcp --dport 80 -j ACCEPT`

保存文件并应用新的防火墙规则：

`iptables-restore < /etc/iptables.rules`
