### ISSUE TITLE
您好，怎么新建用户？当两个客户端同时使用一个vpn账户的时候，其中一个不能访问

### ISSUE THREAD

**Issue by shiwolang** [hwdsl2/setup-ipsec-vpn#392]
您好，怎么新建用户？当两个客户端同时使用一个vpn账户的时候，其中一个不能访问，谢谢

**Comment by hwdsl2** [comment]
@shiwolang 你好！目前不支持同时连接同一个 NAT 后面的多个客户端。请参见 [1].

[1] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes
