### ISSUE TITLE
Connection L2TP Successful but No Internet Access

### ISSUE THREAD

**Issue by rjberm** [hwdsl2/setup-ipsec-vpn#393]
I follow the script to install in CentOS 7.5 x64.

Once installed, I tried in an iPhone iOS 11 using cellular network but it connects and for the first 2-3 minutes there is no connection to the internet. Then, after a few minutes it suddenly has access to the internet without a problem. 

I changed "sha2-truncbug=no" to try to fix the issue and it doesn't help. 
I changed the CentOS DNS to match that of the VPN, Google DNS and it doesn't help. 

Any possible reasons why this might be happening?

**Comment by hwdsl2** [comment]
@rjberm Hello! From your description the issue is most likely with your phone's or your VPN server's network and not with the VPN scripts. There is no need to change the `sha2-truncbug` or CentOS DNS settings - please change those back and reboot both your server and phone, then try again.
