### ISSUE TITLE
multi user

### ISSUE THREAD

**Issue by mrm15** [hwdsl2/setup-ipsec-vpn#395]
hi  thanks fror your ipsec-Vpn.

is there  any way to  create more that One user to  Connet  to ipsec-Vpn?

**Comment by hwdsl2** [comment]
@mrm15 Hello! Please see Manage VPN Users [1]. Note that even if you create multiple users, it is not currently possible to connect multiple devices simultaneously from behind the same NAT (e.g. home router) [2].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users.md
[2] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes

**Comment by shawondas** [comment]
@hwdsl2 http://prntscr.com/jqwfka would you pleasse check this ?
I don't know how to do the second step for adding multiple users. Multiple users from different router won't be any problem. If so I want to do it. 

But i can't figure out to salted and hashed.
