### ISSUE TITLE
Can't connect to L2TP through mobile internet

### ISSUE THREAD

**Issue by badfellowman** [hwdsl2/setup-ipsec-vpn#397]
Hello, hwdsl2! 
In issue #371 you said "This seems a limitation of your mobile Internet ISP and not an issue with the VPN scripts". What kind of limitation do you have in mind?

**Comment by hwdsl2** [comment]
@badfellowman Hello! Some ISPs block UDP ports 500 and/or 4500 which are
both required for IPsec VPNs to work.
