### ISSUE TITLE
Connection by l2tp always fails on macOS

### ISSUE THREAD

**Issue by gsmlg** [hwdsl2/setup-ipsec-vpn#399]
Connection by l2tp always fails on macOS

```
received and ignored empty informational notification payload
#53: received Delete SA(0x04226744) payload: deleting IPSEC State #54
#53: deleting other state #54 (STATE_QUICK_R2) and sending notification
```

**Comment by hwdsl2** [comment]
@gsmlg Hello! The initial logs you posted:

```
probable authentication failure (mismatch of preshared secrets?): malformed payload in packet
```

... indicates that the IPsec pre-shared key entered on your macOS VPN connection configuration does not match that on your VPN server. Delete and re-create the VPN connection on macOS and make sure to put the correct PSK. See [1]. You may also try IPsec/XAuth mode [2].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md

**Comment by gsmlg** [comment]
I can not figure out why it can not connect.
VPN connect fail sometimes

**Comment by gsmlg** [comment]
Thanks for you response, connect is successes.
