### ISSUE TITLE
Ubutu 14.04x64 desktop client

### ISSUE THREAD

**Issue by mhohai** [hwdsl2/setup-ipsec-vpn#4]
hello, I'm try the l2tp-ipsec-vpn client first, but it's not work.
so I purge it, and try [arch wili](https://wiki.archlinux.org/index.php/L2TP/IPsec_VPN_client_setup) and [linux-l2tpipsec-vpn-client](https://www.elastichosts.com/blog/linux-l2tpipsec-vpn-client/) 
but I can't find the ppp...

It's this have any client shell?

**Comment by hwdsl2** [comment]
Hi @mhohai, I understand that you were trying to find a client for the IPsec/L2TP VPN on Linux. Unfortunately I am not very familiar with Linux VPN clients. Can you instead try asking on the Libreswan mailing list [1] ? I believe there are many experts (including Libreswan developers) on that mailing list who would help answer your question.

I am closing this as it is not a issue with the VPN scripts.

[1] https://lists.libreswan.org/mailman/listinfo/swan

**Comment by mhohai** [comment]
Thanks you anyway...
