### ISSUE TITLE
Centos7重启后无法使用ss和web服务

### ISSUE THREAD

**Issue by fangtr** [hwdsl2/setup-ipsec-vpn#40]
我是使用centos 7，安装vpn后，ss和web服务都无法打开。
系统上没有防火墙开启
# systemctl status iptables
● iptables.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
[root@localhost ~]# systemctl start iptables
Failed to start iptables.service: Unit iptables.service failed to load: No such file or directory.

# systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

看安装源码，有/etc/sysconfig/iptables规则存在。
再看
# vi /etc/fail2ban/jail.local
[DEFAULT]
ignoreip = 127.0.0.1/8
bantime  = 600
findtime  = 600
maxretry = 5
backend = auto

[ssh-iptables]
enabled  = true
filter   = sshd
action   = iptables[name=SSH, port=ssh, protocol=tcp]
logpath  = /var/log/secure

正常应该是只针对ssh的啊？
我很奇怪这个问题，能帮我解答下吗

**Comment by hwdsl2** [comment]
@fangtr 你好！请先查看一下当前的 IPTables 防火墙规则：

`sudo iptables -nvL; sudo iptables -nvL -t nat`

然后编辑 `/etc/sysconfig/iptables` 并添加需要的规则，以打开ss和web端口。

最后应用新规则：

`iptables-restore < /etc/sysconfig/iptables`

**Comment by fangtr** [comment]
这个办法确实可以
但是很奇怪的是，我明明不存在iptables服务，为何还需要这样操作？
对于centos7来说iptables已经被firewalld给取代了啊

**Comment by hwdsl2** [comment]
@fangtr CentOS 7 确实是默认安装 `firewalld`，但是 `iptables` 命令仍然存在，只是服务未安装。这个 VPN 脚本并不依赖 iptables 服务，而是通过在 `/etc/rc.local` 中添加 `iptables-restore` 的命令，从而在重启后可以自动恢复防火墙规则。

更多关于 `firewalld` 和 `iptables` 的信息请参见 [1] [2]。

[1] https://stackoverflow.com/questions/24756240/how-can-i-use-iptables-on-centos-7
[2] https://www.digitalocean.com/community/tutorials/how-to-migrate-from-firewalld-to-iptables-on-centos-7

**Comment by fangtr** [comment]
@hwdsl2 感谢你的帮助，这块知识确实是我没深入研究过。
我是不是可以理解为，在centos7上，即使iptables服务未安装，但是也可以通过iptables-restore来实现iptables的功能？


对于这个配置文件
# vi /etc/fail2ban/jail.local
[DEFAULT]
ignoreip = 127.0.0.1/8
bantime  = 600
findtime  = 600
maxretry = 5
backend = auto

[ssh-iptables]
enabled  = true
filter   = sshd
action   = iptables[name=SSH, port=ssh, protocol=tcp]
logpath  = /var/log/secure
我理解的是应该只针对sshd服务有关联的，是否这样理解？

还有iptables-restore < /etc/sysconfig/iptables这段设计是用于和fail2ban的配合吗？

**Comment by fangtr** [comment]
@hwdsl2 虽然现在大家对于friewalld这个服务评价不一，但是我感觉对于redhat 7和未来的系列来说，这个可能未来的趋势。

是否可以考虑使用fail2ban-firewalld和fail2ban-systemd来针对centos 7部署VPN呢？
这只是一个建议

**Comment by hwdsl2** [comment]
@fangtr 谢谢你的建议。如你所说，这个脚本确实还有许多可以改进的地方。

对于第一个问题，是的，可以通过 `iptables-restore` 来实现重启时自动载入规则。或者你也可以按照上述链接中的方法安装并启用 IPTables 服务。

对于第二个问题，你的理解是对的，`/etc/fail2ban/jail.local` 中只定义了对 SSH 服务的保护。你可以添加更多的内容以保护其它服务，详情请在网上搜索教程。

关于 `iptables-restore` 命令和 `fail2ban` 的配合，其实并不是因为这个原因。该脚本没有针对 CentOS 7 做特别的优化，通过 `rc.local` 载入防火墙规则虽然可以达到目的，但并不是最佳的方案。如你所说，通过 firewalld 实现可能更佳。

**Comment by fangtr** [comment]
@hwdsl2 非常感谢你对身在重灾区人民的帮助
当我决定采用CentOS 7时，就不打算在CentOS 7上使用iptables，我想尽可能的熟悉firewalld，(❛ ᴗ ❛ )
