### ISSUE TITLE
Cant login with two different user account at the same time

### ISSUE THREAD

**Issue by ryantang08** [hwdsl2/setup-ipsec-vpn#401]
Hello,
I created two user account, but i can't use the two account at the same time. Is there any method to solve so that i can have different user account can use at the same time.

Thank you

**Comment by hwdsl2** [comment]
@ryantang08 Hello! Due to an IPsec/L2TP limitation and an Libreswan issue, even if you create multiple users, it is not currently possible to connect multiple devices simultaneously from behind the same NAT (e.g. home router) [1].

[1] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes
