### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by rijal10** [hwdsl2/setup-ipsec-vpn#405]
Hello hwdsl2.
You have a great app, unfortunately this app does not have a logo yet, may I donate a logo for your app?

**Comment by hwdsl2** [comment]
@rijal10 Hello! Thank you for your kind offer, but this project does not need a logo at the moment.

**Comment by rijal10** [comment]
Yas @hwdsl2 it's okay if one day requires a logo of mine. will gladly make the best for free for you! best regards friend!
