### ISSUE TITLE
ipsec status whack: Pluto is not running (no "/run/pluto/pluto.ctl") 

### ISSUE THREAD

**Issue by dreamylife** [hwdsl2/setup-ipsec-vpn#407]
I tried this way , finally solve my question.
> ipsec pluto 
Jun  8 18:37:34: pluto: warning: chdir("/run/pluto/") to dumpdir failed (2: No such file or directory)
pluto: FATAL: unable to create lock dir: "/run/pluto/": No such file or directory
>mkdir -p /run/pluto/ 
>ipsec pluto 
>ipsec status
Then，everything OK !

**Comment by hwdsl2** [comment]
@dreamylife Can you let us know which Linux distribution (Ubuntu, Debian,
CentOS) and which version you encountered this issue on?
