### ISSUE TITLE
安装 ipsec后导致原来的 openvpn无法使用

### ISSUE THREAD

**Issue by xiazidong** [hwdsl2/setup-ipsec-vpn#409]
你好 我的机器原本安装了 openvpn，试了一下脚本，可以执行，然后发现原本安装的 openvpn连不上了。
排查后，无法发现异常，具体表现为：openvpn进程正常，防火墙正常，客户端连接成功，服务端日志无报错，客户端连接后可以使用微信和 xshell，但是无法打开网页，也ping不通ip地址。

**Comment by hwdsl2** [comment]
@xiazidong 你好！请检查一下 IPTables 规则：
iptables -nvL; iptables -nvL -t nat
