### ISSUE TITLE
Can't access to ssh or web server after installing the vpn

### ISSUE THREAD

**Issue by jbg77** [hwdsl2/setup-ipsec-vpn#41]
Hello,

I have a problem, after installing this script, ssh server is unreachable "Operation timed out", but i can ping the server, and connect to it with VPN.

Other services like web server or ftp is unreachable too.

What can I do ?

I running with Debian 8.

**Comment by hwdsl2** [comment]
@jbg77 Are you using a custom SSH port (not 22) on the server? If so, you may have to use the rescue mode of your server to get access to it. Then edit `/etc/iptables.rules` and/or `/etc/iptables/rules.v4` and replace 22 with your actual SSH port. Reboot when finished.

**Comment by jbg77** [comment]
Thanks ! You saved me, it's working fine !
