### ISSUE TITLE
Problem with Ubuntu client connection to the server

### ISSUE THREAD

**Issue by pipehappy1** [hwdsl2/setup-ipsec-vpn#410]
Hi, 

I use the script to setup the vpn on some server and the OSX vpn client works fine. However when I use the link to configure client on ubuntu, something goes south. The client is on Ubuntu 16.04 and the auth.log on the server side, looks like this:

`next payload type of ISAKMP Identification Payload has an unknown value: 213 (0xd5)
probable authentication failure (mismatch of preshared secrets?): malformed payload in packet`

The message is repeated several times until the log says

`max number of retransmissions (8) reached STATE_MAIN_R2`

And I'm sure the PSK is right.

Please shed some light on the issue. Thank you very much!

**Comment by pipehappy1** [comment]
The /etc/ipsec.conf on the server looks like this:

`version 2.0

config setup
  virtual-private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:!192.168.42.0/24,%v4:!192.168.43.0/24
  protostack=netkey
  interfaces=%defaultroute
  uniqueids=no

conn shared
  left=%defaultroute
  leftid=SERVER_PUBLICE_IP
  right=%any
  encapsulation=yes
  authby=secret
  pfs=no
  rekey=no
  keyingtries=5
  dpddelay=30
  dpdtimeout=120
  dpdaction=clear
  ike=3des-sha1,3des-sha2,aes-sha1,aes-sha1;modp1024,aes-sha2,aes-sha2;modp1024
  phase2alg=3des-sha1,3des-sha2,aes-sha1,aes-sha2,aes256-sha2_512
  sha2-truncbug=yes

conn l2tp-psk
  auto=add
  leftprotoport=17/1701
  rightprotoport=17/%any
  type=transport
  phase2=esp
  also=shared

conn xauth-psk
  auto=add
  leftsubnet=0.0.0.0/0
  rightaddresspool=192.168.43.10-192.168.43.250
  modecfgdns1=8.8.8.8
  modecfgdns2=8.8.4.4
  leftxauthserver=yes
  rightxauthclient=yes
  leftmodecfgserver=yes
  rightmodecfgclient=yes
  modecfgpull=yes
  xauthby=file
  ike-frag=yes
  ikev2=never
  cisco-unity=yes
  also=shared
`

**Comment by pipehappy1** [comment]
The /etc/ipsec.conf on the client looks like this:

`# ipsec.conf - strongSwan IPsec configuration file

# basic configuration

config setup
  # strictcrlpolicy=yes
  # uniqueids = no

# Add connections here.

# Sample VPN connections

conn %default
  ikelifetime=60m
  keylife=20m
  rekeymargin=3m
  keyingtries=1
  keyexchange=ikev1
  authby=secret
  ike=aes128-sha1-modp1024,3des-sha1-modp1024!
  esp=aes128-sha1-modp1024,3des-sha1-modp1024!

conn myvpn
  keyexchange=ikev1
  left=%defaultroute
  auto=add
  authby=secret
  type=transport
  leftprotoport=17/1701
  rightprotoport=17/1701
  right=SERVER_PUBLICE_IP # this is the vpn server
`

**Comment by hwdsl2** [comment]
@pipehappy1 Hello! Your config files look fine. The logs clearly indicate that your IPsec pre-shared key does not match between your VPN client and VPN server. Double check by comparing the file /etc/ipsec.secrets on client and on server.

**Comment by pipehappy1** [comment]
yeah, I just cannot repeat the problem again. Thank you!
