### ISSUE TITLE
New Libreswan 3.25 compile error

### ISSUE THREAD

**Issue by sudanking** [hwdsl2/setup-ipsec-vpn#412]
New Libreswan 3.25 has been released. I tried to upgrade it using upgrade script but I get the following error:
[https://pastebin.com/NJEN6a1F](https://pastebin.com/NJEN6a1F)

Any idea to resolve this??

**Comment by hwdsl2** [comment]
@sudanking Hello! What is your Linux distribution? Please provide some details. Libreswan 3.25 has just been released and is not yet supported by the upgrade scripts. If your VPN is working fine, I would suggest that you do not upgrade at this time.

**Comment by sudanking** [comment]
I use (Linux Debian-84-jessie-64-minimal 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux) as a VPS

**Comment by hwdsl2** [comment]
@sudanking Thanks. By the way, the IPsec/XAuth multi connection with same IP issue #357 can be worked around by downgrading to Libreswan 3.22. To do so, just run the latest version of VPN setup scripts again with your current VPN credentials.

**Comment by sudanking** [comment]
thanks for the tip.... 
and waiting for upgrade script that supports 3.25
