### ISSUE TITLE
Amazon Linux support?

### ISSUE THREAD

**Issue by nodesocket** [hwdsl2/setup-ipsec-vpn#415]
`vpnsetup-centos` fails with:

```
Error: This script only supports CentOS/RHEL 6 and 7.
```

When running on Amazon Linux.

**Comment by Arefu** [comment]
What's unane -r report on the server, what OS did you chose when making the server?

**Comment by hwdsl2** [comment]
@nodesocket Hello! Amazon Linux is not supported at this time.

**Comment by hwdsl2** [comment]
@nodesocket The VPN setup script for CentOS can be used on Amazon Linux as follows. Note that this is not thoroughly tested and things could break.

For Amazon Linux version 1:
1. Create /etc/redhat-release with the following content:
   ```
   release 6
   ```
2. Download the VPN setup script for CentOS. Edit it and replace this line:
