### ISSUE TITLE
How can I use FreeIPA to auth users?

### ISSUE THREAD

**Issue by neyaoz** [hwdsl2/setup-ipsec-vpn#418]
I have installed VPN via vpnsetup.sh on an Ubuntu 16. This server has been also configured as ipa-client. Users can authenticate on the server if they are allowed to access. But how can I connect VPN service to our IPA server to authenticate users? Can these Ubuntu users authenticate themselves on the VPN via their credentials?

**Comment by hwdsl2** [comment]
@neyaoz Hello! Unfortunately I am not familiar with this. Try the Libreswan [1] or strongSwan [2] mailing lists, or search on the web.

[1] https://lists.libreswan.org/mailman/listinfo/swan
[2] https://lists.strongswan.org/mailman/listinfo/users
