### ISSUE TITLE
windows 10 无法 

### ISSUE THREAD

**Issue by XEnmaai** [hwdsl2/setup-ipsec-vpn#42]
iOS 能连接。
注册表确认已经安装了，重启了好几次电脑。
但是还是出现了下面的问题。

![11](https://cloud.githubusercontent.com/assets/4222835/16937436/7661750e-4da1-11e6-8da0-60f63c608aa5.png)

**Comment by hwdsl2** [comment]
@XEnmaai 你好！请问你添加了哪个（或哪些）注册表键？注意不要添加那个 ProhibitIpSec。

试一下Windows 10的正常模式重启 （不用 Fast Startup）：
按住 Shift 键然后点开始菜单里的关机。等一会后再按电源按钮开机。

另外请在服务器上运行一下 grep pluto /var/log/auth.log 看一下日志。可隐去IP等信息。

**Comment by XEnmaai** [comment]
就添加了AssumeUDPEncapsulationContextOnSendRule 这个注册表

下面是 日志

Jul 19 10:33:30 iZ223w80ymdZ pluto[17415]: "xauth-psk"[37] 112.65.190.151 #81: the peer proposed: 0.0.0.0/0:0/0 -> 192.168.43.11/32:0/0
Jul 19 10:33:30 iZ223w80ymdZ pluto[17415]: "xauth-psk"[37] 112.65.190.151 #82: responding to Quick Mode proposal {msgid:da68d52d}
Jul 19 10:33:30 iZ223w80ymdZ pluto[17415]: "xauth-psk"[37] 112.65.190.151 #82:     us: 0.0.0.0/0===47.88.150.242<47.88.150.242>[MS+XS+S=C]
Jul 19 10:33:30 iZ223w80ymdZ pluto[17415]: "xauth-psk"[37] 112.65.190.151 #82:   them: 112.65.190.151[10.53.231.182,+MC+XC+S=C]===192.168.43.11/32
Jul 19 10:33:30 iZ223w80ymdZ pluto[17415]: "xauth-psk"[37] 112.65.190.151 #82: transition from state STATE_QUICK_R0 to state STATE_QUICK_R1
Jul 19 10:33:30 iZ223w80ymdZ pluto[17415]: "xauth-psk"[37] 112.65.190.151 #82: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 tunnel mode {ESP/NAT=>0x010cba19 <0x3b2212d4 xfrm=AES_256-HMAC_SHA1 NATOA=none NATD=112.65.190.151:23236 DPD=active username=wow}
Jul 19 10:33:30 iZ223w80ymdZ pluto[17415]: "xauth-psk"[37] 112.65.190.151 #82: transition from state STATE_QUICK_R1 to state STATE_QUICK_R2
Jul 19 10:33:30 iZ223w80ymdZ pluto[17415]: "xauth-psk"[37] 112.65.190.151 #82: STATE_QUICK_R2: IPsec SA established tunnel mode {ESP/NAT=>0x010cba19 <0x3b2212d4 xfrm=AES_256-HMAC_SHA1 NATOA=none NATD=112.65.190.151:23236 DPD=active username=wow}
Jul 19 10:33:32 iZ223w80ymdZ pluto[17415]: "xauth-psk"[37] 112.65.190.151 #81: received Delete SA(0x010cba19) payload: deleting IPSEC State #82
Jul 19 10:33:32 iZ223w80ymdZ pluto[17415]: "xauth-psk"[37] 112.65.190.151 #81: deleting state #82 (STATE_QUICK_R2)
Jul 19 10:33:32 iZ223w80ymdZ pluto[17415]: "xauth-psk"[37] 112.65.190.151 #81: ESP traffic information: in=0B out=0B XAUTHuser=wow
Jul 19 10:33:32 iZ223w80ymdZ pluto[17415]: "xauth-psk" #81: deleting state #81 (STATE_MODE_CFG_R1)
Jul 19 10:33:32 iZ223w80ymdZ pluto[17415]: "xauth-psk"[37] 112.65.190.151: deleting connection "xauth-psk" instance with peer 112.65.190.151 {isakmp=#0/ipsec=#0}
[auth.txt](https://github.com/hwdsl2/setup-ipsec-vpn/files/370777/auth.txt)

**Comment by hwdsl2** [comment]
@XEnmaai 日志收到。请在服务器上运行
```
service ipsec restart
service xl2tpd restart
```

然后再次连接 Windows 10 计算机。看看能否成功。如果不行，检查一下有没有新的日志。

**Comment by XEnmaai** [comment]
@hwdsl2 
最后面是我用手机登录成功，的log。电脑还是不行。

server ip：47.88.150.242 用户名  wow  密码 wow123456    psk 密码 wow123456



[auth-2.txt](https://github.com/hwdsl2/setup-ipsec-vpn/files/370805/auth-2.txt)

**Comment by hwdsl2** [comment]
@XEnmaai 稍等我用 Win10 虚拟机试一下连你的服务器。我先隐去你回复里的登录信息。

**Comment by hwdsl2** [comment]
@XEnmaai 我刚刚用 Win10 虚拟机成功连接了 VPN，说明你的服务器没有问题。

请打开注册表编辑器 regedit.exe 再次检查一下注册表键。应该添加这个：

```
For Windows Vista, 7, 8, 10, and 2008 Server:

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PolicyAgent 
RegValue: AssumeUDPEncapsulationContextOnSendRule
Type: DWORD
Data Value: 2
```

**Comment by XEnmaai** [comment]
@hwdsl2 注册表没问题，我用虚拟机发现 win7,mac都没问题。应该是我电脑哪里有问题，我再确认下 我系统 看看有没有什么问题。THX

**Comment by hwdsl2** [comment]
@XEnmaai 好的！请更换一下 VPN 登录信息并指定较复杂的密码，因为刚才的回复会有人看到。可以再次运行安装脚本并指定新的登录凭证。

**Comment by XEnmaai** [comment]
@hwdsl2 好的~

**Comment by Alinlaban** [comment]
您好，我出现了同样的问题，能告诉一下是怎么解决的吗？ @XEnmaai

**Comment by zmyjs** [comment]
![image](https://user-images.githubusercontent.com/20396642/121140802-d9bd0a00-c86c-11eb-9107-1af1017b4a2a.png)
我遇到同样的问题，请问楼主解决了吗？
iOS很愉快地连上，Win10按照教程运行了下面两句重启多次都不行。
![image](https://user-images.githubusercontent.com/20396642/121140942-02dd9a80-c86d-11eb-91d6-df1028cae045.png)
