### ISSUE TITLE
通过vpn拨通内网后，我想让内网机器访问vpn 客户端的服务应该如何解决？

### ISSUE THREAD

**Issue by mds1455975151** [hwdsl2/setup-ipsec-vpn#420]
例如：
内网网段为10.1.16.0/16
vpn网段为：192.168.42.1/24

外网机器A vpn拨通后获取到IP地址为192.168.42.10，访问内网网段都正确，如何让内网10.1.16.10或者整个网段访问外网机器A呢，能否实现？应该如何设置

**Comment by mds1455975151** [comment]
测试过直接把VPN网段设置为内网网段的一部分，但是内网其他机器还是无法ping或者连接到外网机器的IP地址

**Comment by hwdsl2** [comment]
@mds1455975151 你好！在将VPN网段设置为内网网段的一部分之后，你需要调整 IPTables FORWARD Chain 中的规则。默认的规则不允许因特网上的机器直接访问 VPN 客户端 [1]。要允许访问，你可以添加规则比如：

```
iptables -I FORWARD 2 -i eth0 -o ppp+ -s 10.1.16.0/16 -j ACCEPT
```

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/vpnsetup.sh#L412
