### ISSUE TITLE
DLNA discovery

### ISSUE THREAD

**Issue by karolszklarski** [hwdsl2/setup-ipsec-vpn#421]
Hello,

Thanks for the script. It saved me so much time and frustration :)

I'm connecting using xauth/psk on android phone from outside, using cellular network, to VPN server on raspberry pi in my house plugged in to my ISP's router. My LAN is 192.168.0.0/24. Raspberry pi is 192.168.0.201. Router has opened udp ports 500 and 4500, pointed to raspberry. It works fine - from android I can connect to my home computers.

I'm trying to get DLNA server working, but its discovery process fails. As far as I know, DLNA uses multicast 239.255.255.250 to udp port 1900. Both DLNA and VPN are on the same raspberry pi 192.168.0.201 - maybe it will make things easier.

Could you please help me to get this working? I'm trying to use the same subnet for VPN and LAN, but it's not working. Maybe there are some iptables tricks needed to pass multicast. Or maybe something else.

I modified my ipsec.conf, generated by the script
```
config setup
  virtual-private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:!192.168.42.0/24,%v4:!192.168.43.0/24,%v4:!192.168.0.129/28   # added the last part (ip range 129-142)
...
conn shared
  left=192.168.0.201          # raspberry's ip
  leftid=109.241.33.181       # public ip - WAN side of the router
  leftsubnet=192.168.0.0/24   # it causes that only traffic to my home network goes through vpn, which is what I want
...
conn xauth-psk
  rightaddresspool=192.168.0.129-192.168.0.142    # part of my router's subnet - not assigned to anything
#  rightsubnet=192.168.0.129/28
  rightsubnet=192.168.0.0/24
```
Despite having rightsubnet /24 my auth.log says "them 192.168.0.129/32". I think maybe if it was 192.168.0.129/24 it would start working, but I'm not sure.

```
Jul 17 19:32:19 raspberrypi pluto[8427]: "xauth-psk"[2] 37.47.207.232 #2:     us: 192.168.0.0/24===192.168.0.201<192.168.0.201>[109.241.33.181,MS+XS+S=C]
Jul 17 19:32:19 raspberrypi pluto[8427]: "xauth-psk"[2] 37.47.207.232 #2:   them: 37.47.207.232[10.243.1.93,+MC+XC+S=C]===192.168.0.129/32
```

**Comment by hwdsl2** [comment]
@karolszklarski Hello! I understand your question but unfortunately I don't know how to enable the DLNA multicast in your use case. Maybe you can try to temporarily remove the "DROP" rule in the IPTables "FORWARD" chain and see if it works. For further questions, please try the Libreswan (or strongSwan) users mailing list.
