### ISSUE TITLE
连接自动断开

### ISSUE THREAD

**Issue by luerer** [hwdsl2/setup-ipsec-vpn#425]
当不使用的时候 2分钟左右就自动断开连接，请问怎么配置可以一直保持链接。

**Comment by jimmyguo** [comment]
+1

**Comment by hwdsl2** [comment]
@luerer 你好！如果是 iPhone/iPad 的话，它们被设计为在待机（屏幕变黑）后会自动断开 WiFi，从而自动断开 VPN。这个是正常的。某些其它类型的 VPN 比如 OpenVPN 有自动重连功能，但是 IPsec 没有。

另外 Android 手机在网络高级设置里面可以选择是否保持 WiFi 连接。如果不保持连接也会在待机后自动断开 VPN。
