### ISSUE TITLE
Instant Kick off from L2TP

### ISSUE THREAD

**Issue by ochbob** [hwdsl2/setup-ipsec-vpn#427]
Hello there :)

I just setting up ipsec-vpn with your script, seems everythings looks good.

But, when I try to connect with L2TP, I'm instant kick off, but connexion seems OK

Log from xl2tpd /var/log/syslog

> Jul 26 14:59:09 LINOLOGY xl2tpd[327]: Call established with , PID: 616, Local: 64093, Remote: 5897, Serial: 1
> Jul 26 14:59:09 LINOLOGY xl2tpd[327]: child_handler : pppd exited for call 5897 with code 2
> Jul 26 14:59:09 LINOLOGY xl2tpd[327]: call_close: Call 64093 to  disconnected
> Jul 26 14:59:09 LINOLOGY xl2tpd[327]: result_code_avp: result code endianness fix for buggy Apple client. network=768, le=3
> Jul 26 14:59:09 LINOLOGY xl2tpd[327]: control_finish: Connection closed to , serial 1 ()
> Jul 26 14:59:09 LINOLOGY xl2tpd[327]: Terminating pppd: sending TERM signal to pid 616
> Jul 26 14:59:09 LINOLOGY xl2tpd[327]: result_code_avp: result code endianness fix for buggy Apple client. network=256, le=1
> Jul 26 14:59:09 LINOLOGY xl2tpd[327]: control_finish: Connection closed to , port 61228 (), Local: 20601, Remote: 15

Log from grep pluto /var/log/auth.log

> Jul 26 14:59:08 LINOLOGY pluto[32670]: "l2tp-psk"[4]  #8: Peer ID is ID_IPV4_ADDR: '192.168.1.15'
> Jul 26 14:59:08 LINOLOGY pluto[32670]: "l2tp-psk"[4]  #8: switched from "l2tp-psk"[4]  to "l2tp-psk"
> Jul 26 14:59:08 LINOLOGY pluto[32670]: "l2tp-psk"[5]  #8: deleting connection "l2tp-psk"[4] 86.199.209.174 instance with peer 86.199.209.174 {isakmp=#0/ipsec=#0}
> Jul 26 14:59:08 LINOLOGY pluto[32670]: "l2tp-psk"[5]  #8: Peer ID is ID_IPV4_ADDR: '192.168.1.15'
> Jul 26 14:59:08 LINOLOGY pluto[32670]: "l2tp-psk"[5]  #8: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=aes_256 integ=sha2_256 group=MODP2048}
> Jul 26 14:59:09 LINOLOGY pluto[32670]: "l2tp-psk"[5]  #8: the peer proposed: 86.206.10.64/32:17/1701 -> 192.168.1.15/32:17/0
> Jul 26 14:59:09 LINOLOGY pluto[32670]: "l2tp-psk"[5]  #8: NAT-Traversal: received 2 NAT-OA. Using first, ignoring others
> Jul 26 14:59:09 LINOLOGY pluto[32670]: "l2tp-psk"[5]  #9: responding to Quick Mode proposal {msgid:725e7fc0}
> Jul 26 14:59:09 LINOLOGY pluto[32670]: "l2tp-psk"[5]  #9:     us: 192.168.1.100[]:17/1701
> Jul 26 14:59:09 LINOLOGY pluto[32670]: "l2tp-psk"[5]  #9:   them: [192.168.1.15]:17/61228
> Jul 26 14:59:09 LINOLOGY pluto[32670]: "l2tp-psk"[5] 86.199.209.174 #9: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 transport mode {ESP/NAT=>0x0a8a6dfa <0x0d8e6999 xfrm=AES_CBC_256-HMAC_SHA1_96 NATOA=192.168.1.15 NATD=:4500 DPD=active}
> Jul 26 14:59:09 LINOLOGY pluto[32670]: "l2tp-psk"[5]  #9: STATE_QUICK_R2: IPsec SA established transport mode {ESP/NAT=>0x0a8a6dfa <0x0d8e6999 xfrm=AES_CBC_256-HMAC_SHA1_96 NATOA=192.168.1.15 NATD=:4500 DPD=active}
> Jul 26 14:59:09 LINOLOGY pluto[32670]: "l2tp-psk"[5]  #8: received Delete SA(0x0a8a6dfa) payload: deleting IPSEC State #9
> Jul 26 14:59:09 LINOLOGY pluto[32670]: "l2tp-psk"[5] #8: deleting other state #9 (STATE_QUICK_R2) and sending notification
> Jul 26 14:59:09 LINOLOGY pluto[32670]: "l2tp-psk"[5]  #8: ESP traffic information: in=113B out=86B
> Jul 26 14:59:09 LINOLOGY pluto[32670]: "l2tp-psk" #8: deleting state (STATE_MAIN_R3) and sending notification
> Jul 26 14:59:09 LINOLOGY pluto[32670]: "l2tp-psk"[5] 86.199.209.174: deleting connection "l2tp-psk"[5] 86.199.209.174 instance with peer  {isakmp=#0/ipsec=#0}
> Jul 26 14:59:09 LINOLOGY pluto[32670]: packet from :4500: received and ignored empty informational notification payload

Any idea ?

Thank you !

**Comment by ochbob** [comment]
I try to upgrade to kernel 4.17 from 4.14 (found there are some issue on it with L2TP part) but same problem :(

**Comment by ochbob** [comment]
No one ? :/

**Comment by ochbob** [comment]
i'm behind NAT router, is that maybe the issue ?

`version 2.0

config setup
  virtual-private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:!192.168.42.0/24,%v4:!192.168.43.0/24
  protostack=netkey
  interfaces=%defaultroute
  uniqueids=no

conn shared
  left=192.168.1.100
  leftid=86.206.10.64
  right=%any
  encapsulation=yes
  authby=secret
  pfs=no
  rekey=no
  keyingtries=5
  dpddelay=30
  dpdtimeout=120
  dpdaction=clear
  ike=3des-sha1,3des-sha2,aes-sha1,aes-sha1;modp1024,aes-sha2,aes-sha2;modp1024
  phase2alg=3des-sha1,3des-sha2,aes-sha1,aes-sha2,aes256-sha2_512
  sha2-truncbug=yes

conn l2tp-psk
  auto=add
  leftprotoport=17/1701
  rightprotoport=17/%any
  type=transport
  phase2=esp
  also=shared

conn xauth-psk
  auto=add
  leftsubnet=0.0.0.0/0
  rightaddresspool=192.168.43.10-192.168.43.250
  modecfgdns1=192.168.1.100
  modecfgdns2=
  leftxauthserver=yes
  rightxauthclient=yes
  leftmodecfgserver=yes
  rightmodecfgclient=yes
  modecfgpull=yes
  xauthby=file
  ike-frag=yes
  ikev2=never
  cisco-unity=yes
  also=shared
`

**Comment by hwdsl2** [comment]
@ochbob Hello! Thanks for the update and happy to hear the issue was resolved.
