### ISSUE TITLE
Windows 10 l2tp-psk unable to connect

### ISSUE THREAD

**Issue by Darkvater** [hwdsl2/setup-ipsec-vpn#428]
I have setup libreswan as per the details provided here - very helpful! and can connect successfully with username/password+pre-shared-key from both android and ios; however unable to do some from Windows 10.

I have done the registry fix and connection settings as per https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#windows-error-628. Not really sure what's wrong here...
Windows log has the following error:
`CoId={95B01C36-6109-4A32-B61C-264F19C6EF8A}: The user SYSTEM dialed a connection named hattusa - HK which has failed. The error code returned on failure is 691.`

Windows connection string from logs:
>CoId={95B01C36-6109-4A32-B61C-264F19C6EF8A}: The user SYSTEM has started dialing a VPN connection using a per-user connection profile named hattusa - HK. The connection settings are: 
>Dial-in User = vpnuser
>VpnStrategy = L2TP
>DataEncryption = Require
>PrerequisiteEntry = 
>AutoLogon = No
>UseRasCredentials = Yes
>Authentication Type = CHAP 
>Ipv4DefaultGateway = Yes
>Ipv4AddressAssignment = By Server
>Ipv4DNSServerAssignment = By Server
>Ipv6DefaultGateway = Yes
>Ipv6AddressAssignment = By Server
>Ipv6DNSServerAssignment = By Server
>IpDnsFlags = 
>IpNBTEnabled = Yes
>UseFlags = Private Connection
>ConnectOnWinlogon = No
>IPsec authentication for L2TP = Pre-shared key.`

Linux application log the following:

>Jul 28 23:29:01 hattusa pluto[27654]: packet from 192.168.1.158:500: ignoring unknown Vendor ID payload [01528bbbc00696121849ab9a1c5b2a5100000001]
>Jul 28 23:29:01 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #17: responding to Main Mode from unknown peer 192.168.1.158 on port 500
>Jul 28 23:29:01 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #17: Oakley Transform [AES_CBC (256), HMAC_SHA1, DH20] refused
>Jul 28 23:29:01 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #17: Oakley Transform [AES_CBC (128), HMAC_SHA1, DH19] refused
>Jul 28 23:29:01 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #17: STATE_MAIN_R1: sent MR1, expecting MI2
>Jul 28 23:29:01 hattusa pluto[27654]: packet from 192.168.1.158:500: ignoring unknown Vendor ID payload [01528bbbc00696121849ab9a1c5b2a5100000001]
>Jul 28 23:29:01 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #18: responding to Main Mode from unknown peer 192.168.1.158 on port 500
>Jul 28 23:29:01 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #18: Oakley Transform [AES_CBC (256), HMAC_SHA1, DH20] refused
>Jul 28 23:29:01 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #18: Oakley Transform [AES_CBC (128), HMAC_SHA1, DH19] refused
>Jul 28 23:29:01 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #18: STATE_MAIN_R1: sent MR1, expecting MI2
>Jul 28 23:29:01 hattusa pluto[27654]: packet from 192.168.1.158:500: ignoring unknown Vendor ID payload [01528bbbc00696121849ab9a1c5b2a5100000001]
>Jul 28 23:29:01 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #19: responding to Main Mode from unknown peer 192.168.1.158 on port 500
>Jul 28 23:29:01 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #19: Oakley Transform [AES_CBC (256), HMAC_SHA1, DH20] refused
>Jul 28 23:29:01 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #19: Oakley Transform [AES_CBC (128), HMAC_SHA1, DH19] refused
>Jul 28 23:29:01 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #19: STATE_MAIN_R1: sent MR1, expecting MI2
>Jul 28 23:29:01 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #17: STATE_MAIN_R2: sent MR2, expecting MI3
>Jul 28 23:29:01 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #17: Peer ID is ID_IPV4_ADDR: '192.168.1.158'
>Jul 28 23:29:01 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #17: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=aes_256 integ=sha group=MODP2048}
>Jul 28 23:29:01 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #17: Configured DPD (RFC 3706) support not enabled because remote peer did not advertise DPD support
>Jul 28 23:29:01 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #17: the peer proposed: 192.168.1.109/32:17/1701 -> 192.168.1.158/32:17/0
>Jul 28 23:29:01 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #17: NAT-Traversal: received 2 NAT-OA. Using first, ignoring others
>Jul 28 23:29:01 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #20: responding to Quick Mode proposal {msgid:01000000}
>Jul 28 23:29:01 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #20:     us: 192.168.1.109<192.168.1.109>[116.49.95.172]:17/1701
>Jul 28 23:29:01 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #20:   them: 192.168.1.158:17/1701
>Jul 28 23:29:01 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #20: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 transport mode {ESP/NAT=>0x80623658 <0xd08f1f15 xfrm=AES_CBC_128-HMAC_SHA1_96 NATOA=192.168.1.158 NATD=192.168.1.158:4500 DPD=active}
>Jul 28 23:29:01 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #20: Configured DPD (RFC 3706) support not enabled because remote peer did not advertise DPD support
>Jul 28 23:29:01 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #20: STATE_QUICK_R2: IPsec SA established transport mode {ESP/NAT=>0x80623658 <0xd08f1f15 xfrm=AES_CBC_128-HMAC_SHA1_96 NATOA=192.168.1.158 NATD=192.168.1.158:4500 DPD=active}
>Jul 28 23:29:04 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #17: received Delete SA(0x80623658) payload: deleting IPSEC State #20
>Jul 28 23:29:04 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #17: deleting other state #20 (STATE_QUICK_R2) and sending notification
>Jul 28 23:29:04 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158 #17: ESP traffic information: in=208B out=270B
>Jul 28 23:29:04 hattusa pluto[27654]: "l2tp-psk" #18: deleting state (STATE_MAIN_R1)
>Jul 28 23:29:04 hattusa pluto[27654]: "l2tp-psk" #19: deleting state (STATE_MAIN_R1)
>Jul 28 23:29:04 hattusa pluto[27654]: "l2tp-psk" #17: deleting state (STATE_MAIN_R3) and sending notification
>Jul 28 23:29:04 hattusa pluto[27654]: "l2tp-psk"[5] 192.168.1.158: deleting connection "l2tp-psk"[5] 192.168.1.158 instance with peer 192.168.1.158 {isakmp=#0/ipsec=#0}
>Jul 28 23:29:04 hattusa pluto[27654]: packet from 192.168.1.158:4500: received and ignored empty informational notification payload

**Comment by hwdsl2** [comment]
@Darkvater Hello! The VPN error 691 typically indicate that you specified the wrong username and/or password for the IPsec VPN connection (they don't match those on the VPN server). Please check for typos. Also refer to these articles:

https://documentation.meraki.com/MX/Client_VPN/Troubleshooting_Client_VPN#Windows_Error_691
https://appuals.com/vpn-error-691-on-windows-78-and-10/
https://community.spiceworks.com/topic/1736120-vpn-error-691-windows-10
