### ISSUE TITLE
完全按照指引操作但是VPN client连不上

### ISSUE THREAD

**Issue by huahuayu** [hwdsl2/setup-ipsec-vpn#433]
重现步骤：
新开的阿里云服务器执行：
`wget https://git.io/vpnsetup -O vpnsetup.sh && sh vpnsetup.sh`

成功后返回vpn账号密码等信息
```
IPsec VPN server is now ready for use!
Connect to your new VPN with these details:
Server IP: 47.52.241.187
IPsec PSK: JVRVWodzFUz75mtV
Username: vpnuser
Password: {password}
Write these down. You'll need them to connect!
Important notes:   https://git.io/vpnnotes
Setup VPN clients: https://git.io/vpnclients
```

按照[OSX平台VPN client配置指引](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#os-x)配置VPN client

最后VPN连接失败：
![image](https://user-images.githubusercontent.com/1725060/44026651-52ce3c7a-9f26-11e8-96ed-65bd20fcc415.png)

**Comment by zjianfa** [comment]
会不会是端口没有开？阿里云端口要在阿里云服务的控制台设置相应端口

**Comment by huahuayu** [comment]
@zjianfa 请问要开哪个端口？如何判断是端口没开

**Comment by zjianfa** [comment]
为VPN打开UDP端口500和4500。阿里云是默认不打开额外端口的，一般没开

**Comment by zjianfa** [comment]
参考这篇博文试试？https://yq.aliyun.com/articles/225815

**Comment by huahuayu** [comment]
@zjianfa 出方向还是入方向呢，这样对吗
![image](https://user-images.githubusercontent.com/1725060/44036382-3c863580-9f44-11e8-828e-e38efb97763b.png)

**Comment by zjianfa** [comment]
对的，出入都许可

**Comment by huahuayu** [comment]
@zjianfa it works!
我把配置文件导出了，以后的同学可以从这里（https://gist.github.com/huahuayu/afa81064ea2a79e09da3f3840c5436ef）下载配置文件按下图方式导入即可
![image](https://user-images.githubusercontent.com/1725060/44037700-8d5ee0e4-9f47-11e8-9e37-73b922ba1241.png)

**Comment by huahuayu** [comment]
@hwdsl2 建议把开放端口内容放到readme中，我注意到readme中并没有说明

**Comment by JimmieMax** [comment]
为什么我的udp端口还报你的那个错误啊？需要怎么重启吗？

**Comment by ziguilp** [comment]
没有用啊，还是连不上

**Comment by Leonning** [comment]
香港轻量应用服务器设置成功。服务器tdp/udp都开放500；4500端口

**Comment by liuser** [comment]
出入\tcp\udp全部开启，依然无效，绝望！

**Comment by titusmok** [comment]
> 香港轻量应用服务器设置成功。服务器tdp/udp都开放500；4500端口

能send一份guideline给我吗？我设置发现没成功，用的也是香港轻量应用服务器

**Comment by titusmok** [comment]
@Leonning 能send一份guideline给我吗？我设置发现没成功，用的也是香港轻量应用服务器

**Comment by mzF414** [comment]
@titusmok 在防火墙那里加

**Comment by caoxmm** [comment]
防火墙都关掉了，还是不能连上 ：(

**Comment by wy-ruby** [comment]
配置了udp 500 450端口后手机可以连接了，但是mac连不上

**Comment by yulrosy** [comment]
EC2配置了udp 500 4500还是不行

**Comment by funny-dog** [comment]
配置好端口，手机可以连，win10和ubuntu还是连不上

**Comment by leolongpy** [comment]
华为云的 配置了udp 500 4500还是不行

**Comment by huahuayu** [comment]
说开放了端口还不行的同学 ，试下netstat看下vpn在哪个端口服务，然后telnet对应端口通不通

**Comment by niaup** [comment]
cisco 不是 L2TP

**Comment by jovetove** [comment]
您好，您的来信我已收到祝好~

**Comment by Noobyj2233** [comment]
按照步骤安装好了，PSK、client、密码都有了，端口也打开了，安卓strongswan用户鉴权失败，windows也不行
求助求助

**Comment by ZhangDapao121388** [comment]
跑完脚本还连不上的，除了放开指定500 4500 1701 udp端口外，试一下把文档里那两个注册表文件导入试试

**Comment by jovetove** [comment]
您好，您的来信我已收到祝好~
