### ISSUE TITLE
libreswan 3.25

### ISSUE THREAD

**Issue by sagitt** [hwdsl2/setup-ipsec-vpn#434]
Libreswan was update with 3.25 version

Not work with your script changing version.

3.23 works fine

**Comment by hwdsl2** [comment]
@sagitt Hello! You may install the VPN first and then download and run the upgrade script in this repo which supports upgrading to Libreswan 3.25. Change the version number in the script before using.

Note that Libreswan 3.23 and 3.25 has issues with connecting multiple IPsec/XAuth VPN clients from behind the same NAT. That’s why the VPN script installs Libreswan 3.22 by default.

**Comment by sagitt** [comment]
i'm trying to install 3.25 libreswan before the script but not working
instead, 3.23 works fine.

i'm using the local makefile etc.. but i'm not able to install it.

you know how to do it?

**Comment by hwdsl2** [comment]
@sagitt As I mentizoned above please install Libreswan 3.22 first and then use these upgrade scripts [1] to upgrade to 3.25.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/tree/master/extras

**Comment by sagitt** [comment]
ok thanks worked
simple line to add to makefile local

and changed modecfgdns

thanks a lot
