### ISSUE TITLE
Login user list/info

### ISSUE THREAD

**Issue by sudanking** [hwdsl2/setup-ipsec-vpn#435]
How can I get a list of users logged in with username?

**Comment by GabLeRoux** [comment]
I know it's possible to get the connected users from this command on the vpn server:

```bash
ipsec whack --trafficstatus
```

According to [this comment](https://github.com/hwdsl2/setup-ipsec-vpn/issues/314#issuecomment-364944017), it's supposed to display usernames, but it's not my case. At least I can know if there are users connected or not with that command.

**Comment by hwdsl2** [comment]
@sudanking Please refer to #105 and #166.
