### ISSUE TITLE
linux客户端怎么使用IKEv2方式连

### ISSUE THREAD

**Issue by xbo2018** [hwdsl2/setup-ipsec-vpn#436]
按照教程IKEv2方式win10可以成功连上，但是ubuntu16/18均不能连上，请教

**Comment by hwdsl2** [comment]
@xbo2018 Hello! Because Libreswan only supports IKEv2 authentication using machine certificates but not usernames/passwords, it is currently not possible to connect using Linux IKEv2 clients (which requires a username/password) to your Libreswan VPN server.

**Comment by amaothree** [comment]
请安装 networkmanager-strongswan 来取得对 IKEv2 的支持。
但是经过我的尝试了，发现并不会配置，不太清楚生成的p12与ce证书应该放在哪里？
不知道作者是否能给出建议，比如client的认证模式应该是哪种？
@hwdsl2 
![image](https://user-images.githubusercontent.com/26244249/68061541-4bca8600-fcfd-11e9-91bc-503a0cfb2f86.png)
![image](https://user-images.githubusercontent.com/26244249/68061629-bed3fc80-fcfd-11e9-9c44-e3633c171dfd.png)
