### ISSUE TITLE
Can not login WhatsApp in this way/墙外其他网页正常访问，无法访问WhatsApp

### ISSUE THREAD

**Issue by elsagong** [hwdsl2/setup-ipsec-vpn#437]
Hi,
Thank you for your great tutorial in setup of ipsec vpn, I can visit Google, Facebook, YoTube finally, except for WhatsApp, do you know the reason why I can't login WhatsApp normally?
Thank you so much for any advice.
您好，感谢您的教程，已顺利搭建好VPN，墙外其他网页正常访问，无法访问WhatsApp，可以咨询您解决方法吗？非常感谢！
Thanks and best regards,
Elsa

**Comment by hwdsl2** [comment]
@elsagong Hello! Unfortunately I don't know why you can't use WhatsApp with the IPsec VPN. It is most likely not an issue with the VPN itself. Maybe try an alternative such as OpenVPN or Shadowsocks?
