### ISSUE TITLE
Accessing servers on the LAN

### ISSUE THREAD

**Issue by dremekie** [hwdsl2/setup-ipsec-vpn#44]
Very nice container here... good job.

I got it up and running and connected to it easily. Now that I'm connected (with an IP of 192.168.42.10), how can communicate with machines on my LAN (192.168.56.x, using 255.255.255.0 subnet)?

Thanks

**Comment by hwdsl2** [comment]
@dremekie Is the VPN server within the LAN subnet 192.168.56.x? Need more information about your setup. Can you please draw a (text-based) diagram so that I can better understand? Thanks.

**Comment by dremekie** [comment]
```

                                         +
                                         |
+-----------------------------+          |              +-----------------------+
|                             |          +--------------+Server 1 (192.168.56.y)|
| VPN Server (192.168.56.x)   |          |              +-----------------------+
|                             |          |
|                             +----------+
|                             |          |
|                             |          |
| +---------------------------+          |
| | setup ipsec Vpn container||          |                   +-------------------------+
| +--------------------+------+          +-------------------+ Server 2 (192.168.56.z) |
|                      ^      |          |                   +-------------------------+
+-----------------------------+
 +----------------+    |
 | vpn client     |    |
 | (192.168.42.10)+----+
 +----------------+

```

My VPN client successfully  connects to the VPN server running as a docker container on my VPN server. My VPN server is on LAN subnet 192.168.56.x.   My VPN client is given an IP of 192.168.42.10 and cannot access Server 1 or Server 2.

**Comment by hwdsl2** [comment]
Try creating a new container, add "--network=host" to the "docker run" command line [1]. Does this fix the problem?

[1] https://docs.docker.com/engine/reference/run/#/network-settings

**Comment by dremekie** [comment]
I will give this a try and let you know. Thanks for your quick response.

**Comment by hwdsl2** [comment]
@dremekie I have tested your use case and was able to successfully connect. There is no need to add the "--network=host" parameter.

Please note that when using the VPN client to connect to Server 1 and Server 2, the traffic will appear to originate from the VPN server's IP 192.168.56.x (or its public IP), NOT the VPN client IP 192.168.42.10. If unable to connect, make sure that you configure the firewall on Server 1 and Server 2 to allow traffic from the VPN server's IP.
