### ISSUE TITLE
Cannot connect to VPN server on Google Cloud Compute Engine

### ISSUE THREAD

**Issue by lyuanqi** [hwdsl2/setup-ipsec-vpn#440]
Hi, 

I set up the server using the script on Google Cloud Compute Engine (Ubuntu 16.04), but I could not connect to it.

I used the exact same script on Amazon EC2 (Ubuntu 16.04), and it works just fine.

I am so confused about why it wouldn't work for Google Cloud Compute Engine. 

I checked the logs and the firewall rules, things look very normal on the server side.

I tried to connect from both iPhone and macbook pro, both failed for the VPN server on Google Cloud Compute Engine, but worked for Amazon EC2.

Please help.

Thanks.

**Comment by hwdsl2** [comment]
@lyuanqi Hello! Please check the Libreswan (IPsec) and xl2tpd logs:
```
grep pluto /var/log/auth.log
grep xl2tpd /var/log/syslog
```

**Comment by hwdsl2** [comment]
@lyuanqi Closed due to inactivity. Open a new issue if the problem persists.
