### ISSUE TITLE
android与windows都连不上

### ISSUE THREAD

**Issue by boot-vue** [hwdsl2/setup-ipsec-vpn#441]
试了国内外四五台vps服务器  ios与mac 都没问题可以正常连接.

好几台手机android 7, windows10都连不上,  有时候android xauth协议能连上但是无法访问网络.

windows注册表都按说明改过  文档里android 6+的配置也改过都无效

**Comment by hwdsl2** [comment]
@boot-vue 你好！Android 手机种类比较多，有时需要修改参数，还是要按照文档里的android 6+的配置再修改一下试试 [1]。另外 Windows 注册表修改后要重启。进一步故障排除请提供连接时的日志，参见 [2]。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#android-6-%E5%8F%8A%E4%BB%A5%E4%B8%8A%E7%89%88%E6%9C%AC
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E9%A2%9D%E5%A4%96%E7%9A%84%E6%AD%A5%E9%AA%A4

**Comment by boot-vue** [comment]
`
L2TP_NET=${VPN_L2TP_NET:-'10.0.0.0/10'}
L2TP_LOCAL=${VPN_L2TP_LOCAL:-'10.0.0.1'}
L2TP_POOL=${VPN_L2TP_POOL:-'10.0.0.10-10.63.255.254'}
XAUTH_NET=${VPN_XAUTH_NET:-'10.128.0.0/10'}
XAUTH_POOL=${VPN_XAUTH_POOL:-'10.128.0.10-10.191.255.254'}
DNS_SRV1=${VPN_DNS_SRV1:-'8.8.8.8'}
DNS_SRV2=${VPN_DNS_SRV2:-'8.8.4.4'}

# Create IPsec config
conf_bk "/etc/ipsec.conf"
cat > /etc/ipsec.conf <<EOF
version 2.0

config setup
  virtual-private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:!$L2TP_NET,%v4:!$XAUTH_NET
  protostack=netkey
  interfaces=%defaultroute
  uniqueids=no`

脚本里ip地址分配这样配置的

**Comment by boot-vue** [comment]
IOS设备连接正常, 日志这个样子
```
Aug 28 22:15:11 kr002 pluto[1389]: XAUTH: User root: Authentication Successful

Aug 28 22:15:11 kr002 pluto[1389]: "xauth-psk"[12] 27.154.110.183 #19: XAUTH: xauth_inR1(STF_OK)
Aug 28 22:15:11 kr002 pluto[1389]: "xauth-psk"[12] 27.154.110.183 #19: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=aes_256 integ=sha2_256 group=MODP2048}
Aug 28 22:15:11 kr002 pluto[1389]: "xauth-psk"[12] 27.154.110.183 #19: modecfg_inR0(STF_OK)
Aug 28 22:15:11 kr002 pluto[1389]: "xauth-psk"[12] 27.154.110.183 #19: STATE_MODE_CFG_R1: ModeCfg Set sent, expecting Ack {auth=PRESHARED_KEY cipher=aes_256 integ=sha2_256 group=MODP2048}
Aug 28 22:15:14 kr002 pluto[1389]: "xauth-psk"[12] 27.154.110.183 #19: the peer proposed: 0.0.0.0/0:0/0 -> 10.128.0.10/32:0/0
Aug 28 22:15:14 kr002 pluto[1389]: "xauth-psk"[12] 27.154.110.183 #20: responding to Quick Mode proposal {msgid:75d76da8}
Aug 28 22:15:14 kr002 pluto[1389]: "xauth-psk"[12] 27.154.110.183 #20:     us: 0.0.0.0/0===1.234.31.113[MS+XS+S=C]
Aug 28 22:15:14 kr002 pluto[1389]: "xauth-psk"[12] 27.154.110.183 #20:   them: 27.154.110.183[192.168.66.106,+MC+XC+S=C]===10.128.0.10/32
Aug 28 22:15:14 kr002 pluto[1389]: "xauth-psk"[12] 27.154.110.183 #20: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 tunnel mode {ESP/NAT=>0x09c964a5 <0x36840369 xfrm=AES_CBC_256-HMAC_SHA1_96 NATOA=none NATD=27.154.110.183:1038 DPD=active username=root}
Aug 28 22:15:14 kr002 pluto[1389]: "xauth-psk"[12] 27.154.110.183 #20: STATE_QUICK_R2: IPsec SA established tunnel mode {ESP/NAT=>0x09c964a5 <0x36840369 xfrm=AES_CBC_256-HMAC_SHA1_96 NATOA=none NATD=27.154.110.183:1038 DPD=active username=root}
```

**Comment by hwdsl2** [comment]
@bootvue For Android can you try appending “,aes256-sha2_256”? Refer to
this issue [1].

https://github.com/hwdsl2/docker-ipsec-vpn-server/issues/84#issuecomment-416124104

**Comment by boot-vue** [comment]
试过了,都不行
```
  phase2alg=3des-sha1,3des-sha2,aes-sha1,aes-sha2,aes256-sha2_512,aes256-sha2_256
  sha2-truncbug=yes
```

**Comment by letoams** [comment]
Note that using sha2_truncbug=yes means you are breaking non-android clients. You can really only use this when the connection is specifically only receiving androids and not iPhones or other properly working clients.

For example a vpn server with two IPs can use one for android and for for everything else.

Paul

**Comment by hwdsl2** [comment]
Thanks @letoams! What I noticed before is that most clients (Windows, iOS,
macOS) will negotiate and select SHA1 instead of SHA2 and are therefore
unaffected by the “sha2-truncbug=yes” setting.

**Comment by letoams** [comment]
On Thu, 30 Aug 2018, Lin Song wrote:

> Thanks @letoams! What I noticed before is that most clients (Windows, iOS,
> macOS) will negotiate and select SHA1 instead of SHA2 and are therefore
> unaffected by the “sha2-truncbug=yes” setting.

libreswan also will prefer sha2_512 over sha2_256, so ensure you always
add both to try and get the most success by not negotiating sha2_256.

This is also the reason we warned against sha2_256 in

https://tools.ietf.org/html/rfc8221#section-6

    AUTH_HMAC_SHA2_256_128 MUST be implemented in order to replace
    AUTH_HMAC_SHA1_96.  Note that due to a long standing common
    implementation bug of this algorithm that truncates the hash at 96
    bits instead of 128 bits, it is recommended that implementations
    prefer AUTH_HMAC_SHA2_512_256 over AUTH_HMAC_SHA2_256_128 if they
    implement AUTH_HMAC_SHA2_512_256.

**Comment by boot-vue** [comment]
是的  sha2-truncbug=yes  会导致ios连接不上

**Comment by hwdsl2** [comment]
@boot-vue From your Android client connection logs it looks like the issue is with `sha2-truncbug=yes`, which could cause the `max number of retransmissions (8) reached` error. Change it to `sha2-truncbug=no` in /etc/ipsec.conf, then run `service ipsec restart`. 

Windows 7 and 10 VPN clients have been tested before and they can successfully connect with the required registry changes [1]. Double check your registry keys for accuracy and reboot your PC.

If still not working, try the additional troubleshooting steps in [1].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting

**Comment by letoams** [comment]
> On Sep 7, 2018, at 00:13, Lin Song <notifications@github.com> wrote:
> 
> @boot-vue From your Android client connection logs it looks like the issue is with sha2-truncbug=yes, which could cause the max number of retransmissions (8) reached error.
> 
It cannot cause that. It only changes ESP truncation and is not involved at the IKE level and not negotiated. 

This error normally means mismatched configurations.

Paul

**Comment by hwdsl2** [comment]
@letoams Thank you for correcting me on that!

@boot-vue Per Paul's comments, the error `max number of retransmissions (8) reached` may not be caused by `sha2-truncbug=yes`. It could be due to mismatched configurations or network-related issues.
