### ISSUE TITLE
是不是用了访问国内网站反而更慢？

### ISSUE THREAD

**Issue by leafonsword** [hwdsl2/setup-ipsec-vpn#443]
譬如我在美国搭了个服务器做 vpn，当访问国内网站，是不是也是先到国外服务器再中转至国内，所以比不用 vpn 反而慢？

**Comment by hwdsl2** [comment]
@leafonsword 你好！你说的没错，因为流量要先到 VPN 服务器再到你要访问的网站，然后返回你的客户端。可以选择一个延时相对较短的服务器。大部分 IPsec VPN 客户端一般不支持哪些流量不走 VPN。
