### ISSUE TITLE
Can Ubuntu virtual machine use this script?

### ISSUE THREAD

**Issue by IsME420** [hwdsl2/setup-ipsec-vpn#444]
Can Ubuntu virtual machine use this script?
Execute the script and report the following error:
Error: 'apt-get update' failed.

**Comment by hwdsl2** [comment]
@IsMe420 Hello! Ubuntu LTS VMs in the cloud can use this script. What is your Ubuntu version? The`'apt-get update' failed` error indicates an issue with `apt` in your server’s Ubuntu OS. Try `apt-get clean`, then re-run the script.
