### ISSUE TITLE
Intranet not working [road warrior]

### ISSUE THREAD

**Issue by Archerious** [hwdsl2/setup-ipsec-vpn#446]
I have my PC (suffers from CG-NAT) and laptop connected to my VPS via L2TP/IPSEC, but the two devices cannot use RDP or communicate.

Apologies for this newb issue, but on OpenVPN it was a simple line to the config "client-to-client".

Many thanks!

**Comment by hwdsl2** [comment]
@Archerious Hello! VPN clients connected via IPsec/L2TP can communicate with each other using their assigned internal VPN IPs. The first connected VPN client has IP 192.168.42.10, the second connected client has IP 192.168.42.11, and so on. For example, if you want to connect from the first client to the second client, use the internal IP 192.168.42.11.

Can you try and let us know if this works?

**Comment by Archerious** [comment]
> 
> 
> @Archerious Hello! VPN clients connected via IPsec/L2TP can communicate with each other using their assigned internal VPN IPs. The first connected VPN client has IP 192.168.42.10, the second connected client has IP 192.168.42.11, and so on. For example, if you want to connect from the first client to the second client, use the internal IP 192.168.42.11.
> 
> Can you try and let us know if this works?

When I SSH the VPS, I can ssh my Desktop at 192.168.42.10. My laptop is assigned 192.168.42.11 right now.

However I cannot SSH my PC from the laptop, 192.168.42.10 shows as "timed out" in ping as well. SSH in terminal just hangs. I tried booting my Windows 10 Thinkpad, repeating the same test (it was assigned 192.168.42.11) but it also could not SSH 192.168.42.10.

My PC is under CG-NAT, not sure if that is the problem, as with OpenVPN it was a simple "client-to-client", but OVPN is too unreliable in my testings.

**Comment by hwdsl2** [comment]
@Archerious Check if it is an IPTables issue as follows. On your VPN server, run "iptables -nvL FORWARD". Please post the output. See if the packet counter is non-zero on the last rule (which says `DROP`).

**Comment by Archerious** [comment]
Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
   54  3399 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate INVALID
 132K  283M ACCEPT     all  --  eth0   ppp+    0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
 190K   22M ACCEPT     all  --  ppp+   eth0    0.0.0.0/0            0.0.0.0/0
   12   648 ACCEPT     all  --  ppp+   ppp+    192.168.42.0/24      192.168.42.0/24
    0     0 ACCEPT     all  --  eth0   *       0.0.0.0/0            192.168.43.0/24      ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  *      eth0    192.168.43.0/24      0.0.0.0/0
   16  2476 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0

**Comment by Archerious** [comment]
![Info above:](https://user-images.githubusercontent.com/26941475/45730231-22e93f00-bb96-11e8-8861-5831126ae573.PNG)

**Comment by hwdsl2** [comment]
@Archerious Please troubleshoot further as follows. Run this command:
```
iptables -I FORWARD 7 -j LOG --log-prefix "FORWARD-DROP"
```

Now try to SSH your PC from your laptop again. It will fail but we can check the log. After that, run the following and post the output.
```
dmesg | grep "FORWARD-DROP"
```

**Comment by Archerious** [comment]
Hmm, there is no output.

**Comment by Archerious** [comment]
![hmm no output](https://user-images.githubusercontent.com/26941475/45730402-0699d200-bb97-11e8-893c-bdd3a900b240.PNG)

**Comment by hwdsl2** [comment]
@Archerious Try: `sudo iptables -I FORWARD -j ACCEPT`, then try to SSH your PC from the laptop. Does it work? Be sure to remove that rule after the test: `sudo iptables -D FORWARD -j ACCEPT".

**Comment by Archerious** [comment]
![nope](https://user-images.githubusercontent.com/26941475/45730492-82941a00-bb97-11e8-8e9f-56cf028635f5.PNG)

**Comment by Archerious** [comment]
It doesn't work still :(.

**Comment by hwdsl2** [comment]
@Archerious Thanks for helping with the troubleshooting. I'll need to look into this further myself...

**Comment by Archerious** [comment]
Okay, thank you for the help. I hope we can fix it, as I really like the speed and stability I get with your VPN setup.

**Comment by hwdsl2** [comment]
@Archerious Does your Windows firewall settings on your desktop allow traffic from 192.168.42.0/24? Just want to check if that's the reason. Maybe you can temporarily disable it for a few seconds to test, then re-enable.
