### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by IngwiePhoenix** [hwdsl2/setup-ipsec-vpn#448]
Hello there! Since there is no forum or alike that I could use for this, I thought I might as well make an issue ticket about it...

So, although `af_key` wouldn't be found on my system (Kimsufi KS-7), I can actually still connect via L2TP - whilst actually not having tried out the other one.

As far as I had understood VPN networks so far, they can not just be used to tunnel and transmit regular browsing traffic, but actually build an actual yet virtual network, as L2TP stands for Layer-2 Transport Protocol and is meant to supply an OSI-2, so that basically anything could run over it.

Now, I would like to actually utilize this in order to secure backups and create a workaround for my home IP updating dynamicaly - as the VPN client would always have the same IP (as far as I know).

Since I have this docker running flawlessly now, I'd like to know how and if I can:
- Run this image on startup, just in case I have to reboot.
- Make a web service available only to VPN clients. For instance, I have an OwnCloud instance installed, but I'd like to only run it through the VPN and completely hide it from the public internet. That OwnCloud instance is actually installed in the host, not in a container.
- Verify that a vpn-only service is really von-only.
- Allow clients to communicate with each other. A few of my clients - not all - might actually be on the same local network already, but should they not be (i.e. my home-server is connected to the VPN network from home, and my laptop is connected from my work), I'd like to still have them interact with one another - so that I can utilize the same file-sharing features that I usually can.

Again, sorry for putting this into an issue ticket, but I had not seen another method - such as a mailing list, forum or alike.

Thanks for this great docker image, by the way!

Kind regards,
Ingwie

**Comment by hwdsl2** [comment]
@IngwiePhoenix Hello! The Docker image starts automatically on boot. VPN clients connected via IPsec/XAuth can communicate with each other using their assigned internal VPN IPs. In the default configuration, the first connected VPN client has IP 192.168.43.10, the second connected client has IP 192.168.43.11, and so on. For example, if you want to connect from the first client to the second client, use the internal IP 192.168.43.11. If the clients are unable to connect to each other, it is probably blocked by the firewall on each device.

 

Advanced users can change the IPsec/XAuth subnet. For your use case, re-run the VPN setup script like this:

 

export VPN_XAUTH_NET=10.10.10.0/24

export VPN_XAUTH_POOL=10.10.10.110-10.10.10.250

sudo sh vpnsetup.sh 



With the above configuration, IPsec/XAuth VPN clients would be assigned internal VPN IPs starting from 10.10.10.110. The first connected VPN client has IP 10.10.10.110, the second connected client has IP 10.10.10.111, and so on. They should be able to access each other and also access the network of the router.

**Comment by IngwiePhoenix** [comment]
Hey!

Thanks for your reply :). The only question left open is, how I can have the actual docker host - the server that I am running this service on - join the VPN network too? Or if it is already in, how do I address it?
Kevin

Kindest regards, Ingwie.

**Comment by hwdsl2** [comment]
@IngwiePhoenix For your use case, you may pass `--network host` parameter when creating the Docker container. This will remove the isolation between container and host network and use the host network directly (use at your own risk as I haven't tested this). Then the VPN server will be available at 192.168.42.1 for connected IPsec/L2TP clients to use. On the other hand, for IPsec/XAuth clients unfortunately the VPN server does not have an internal VPN IP.
