### ISSUE TITLE
Radius client support

### ISSUE THREAD

**Issue by dci39384** [hwdsl2/setup-ipsec-vpn#449]
Hi, 

Does this support radius client? I tried to set it up but couldn't get it working.

Thank you!

**Comment by letoams** [comment]
On Tue, 25 Sep 2018, dci39384 wrote:

> Does this support radius client? I tried to set it up but couldn't get it working.

libreswan supports radius via /etc/pam.d/pluto configuration for XAUTH
user/password and IKEv2 user ok/not_ok verification.

For L2TP/IPsec, I guess you would use pppd with a pam radius plugin?

I don't know if hwdsl2/setup-ipsec-vpn specifically supports this.

**Comment by dci39384** [comment]
@letoams Thanks for the reply, i tried to add the radius.so to the l2tp config and provide radius server info in radiusclient config file but didn't work.   followed this as well: https://adminvps.ru/blog/ustanovka-l2tp-radius-avtorizacija/

**Comment by hwdsl2** [comment]
Thanks @letoams!

@dci39384 Unfortunately I am not familiar with radius configuration nor does the script support it. Please direct further questions to the Libreswan mailing list.
