### ISSUE TITLE
limit number of connected devices

### ISSUE THREAD

**Issue by naoziwatele** [hwdsl2/setup-ipsec-vpn#45]
Is it possible to limit the number of simultaneous connections? Thanks

**Comment by hwdsl2** [comment]
@naoziwatele Unfortunately I am not aware of a method to limit the number of simultaneous connections. Try asking on the Libreswan or Strongswan mailing lists [1] [2].

[1] https://lists.libreswan.org/mailman/listinfo
[2] https://lists.strongswan.org/mailman/listinfo

**Comment by naoziwatele** [comment]
Thank you.. @hwdsl2
