### ISSUE TITLE
VPN_NET_IFACE doesnot take effect

### ISSUE THREAD

**Issue by qdongxu** [hwdsl2/setup-ipsec-vpn#452]
I was going to setup a 2-hop vpn tunnels, clients ---l2tp--->server1( l2tp server -> badvpn/ifacc --> sslocal(127.0.0.1:1080)--> sever2( shadowsocks server ). 

badvpn-tun2socks opened a virtural ifac : 
![image](https://user-images.githubusercontent.com/43328966/46072919-2c862e80-c1b6-11e8-96b9-55899c99e148.png)
running 
`sudo badvpn-tun2socks --netif-ipaddr 11.0.0.2  --netif-netmask 255.0.0.0 --socks-server-addr  127.0.0.1:1080 --tundev ss0 `
to redirect ss0 to the 1080 socks t proxy.

then 
`export VPN_NET_IFACE='ss0'`
and export some other variables required by vpnsetup.sh too.
run 
`vpnsetup.sh `

then configure client and connect through l2tp. 
the l2tp tunnel works but not route to the badvpn ss0 device. 

checking the iptables , it still set to the default ifac eth0:
![image](https://user-images.githubusercontent.com/43328966/46073357-4411e700-c1b7-11e8-97d9-67e91dec2904.png)

Can some help on this?

**Comment by hwdsl2** [comment]
@qdongxu Hello! For your use case, comment out this line before running `vpnsetup.sh`:

```
NET_IFACE="$def_iface"
```

`VPN_NET_IFACE` only takes effect if the default network interface cannot be detected, unless you comment out the line above.
