### ISSUE TITLE
建议移除L2TP默认加入IKEv2

### ISSUE THREAD

**Issue by zzuzjl** [hwdsl2/setup-ipsec-vpn#453]
L2TP已经不好用了，可以移除了，
IKEv2很好用，可以默认加上，

**Comment by hwdsl2** [comment]
@zzuzjl 感谢你的建议。Libreswan 暂不支持使用用户名和密码登录IKEv2，只支持使用证书。详细配置方法请参见文档。将来会尝试把IKEv2文档放到README更显著的位置。

因为本脚本受 Amazon EC2 User Data 16384 字节的限制，暂时无法整合IKEv2代码进脚本。

**Comment by zzuzjl** [comment]
请问这个IKEv2在ios系统上怎么使用啊？

**Comment by zzuzjl** [comment]
> @zzuzjl 感谢你的建议。Libreswan 暂不支持使用用户名和密码登录IKEv2，只支持使用证书。详细配置方法请参见文档。将来会尝试把IKEv2文档放到README更显著的位置。
> 
> 因为本脚本受 Amazon EC2 User Data 16384 字节的限制，暂时无法整合IKEv2代码进脚本。



> Amazon EC2 User Data 16384 字节的限制

这个字节限制我不理解，是不是把L2TP部分删除了，省出来的空间就够IKEv2使用了啊？

**Comment by hwdsl2** [comment]
@zzuzjl L2TP 目前各种操作系统支持比较广泛，Cisco IPsec 和 IKEv2 则少一些。

除了你所说的手动导入证书之外，在iOS和macOS上一个更简单的办法是导入.mobileconfig文件，比如另外这个项目 [1]。但是如果使用证书，则需要将证书和正确的配置参数包含在该文件中。

[1] https://github.com/gaomd/docker-ikev2-vpn-server

**Comment by zzuzjl** [comment]
> @zzuzjl L2TP 目前各种操作系统支持比较广泛，Cisco IPsec 和 IKEv2 则少一些。
> 
> 除了你所说的手动导入证书之外，在iOS和macOS上一个更简单的办法是导入.mobileconfig文件，比如另外这个项目 [1]。但是如果使用证书，则需要将证书和正确的配置参数包含在该文件中。
> 
> [1] https://github.com/gaomd/docker-ikev2-vpn-server

常见的操作系统就是iOS、mac、win和安卓，Cisco IPsec在ios、mac和安卓上默认都支持，IKEv2在ios、mac、win和部分安卓（比如三星）上默认也都支持，可以说Cisco IPsec 和 IKEv2已经很普遍了。
请问您的IKEv2教程部分是否可以导入导入.mobileconfig文件来配置呢？
另外您是否可以考虑两外单独写一个IKEv2的一键脚本呢？

**Comment by hwdsl2** [comment]
@zzuzjl 你好！再次感谢你的建议。目前 IKEv2 教程暂时还没有加入 iOS 配置方法（比如你所说的手动导入，或者使用 .mobileconfig 文件配置）。未来会考虑加入 iOS 配置以及自动化 IKEv2 证书生成。
