### ISSUE TITLE
TP-Link WAR302 can't connect

### ISSUE THREAD

**Issue by jszsj** [hwdsl2/setup-ipsec-vpn#454]
The log is:
`
Sep 29 05:45:02 debian pluto[14006]: "l2tp-psk"[18] 49.74.32.77 #20: responding to Main Mode from unknown peer 49.74.32.77 on port 1816

Sep 29 05:45:02 debian pluto[14006]: "l2tp-psk"[18] 49.74.32.77 #20: Oakley Transform [3DES_CBC (192), HMAC_MD5, MODP1024] refused

Sep 29 05:45:02 debian pluto[14006]: "l2tp-psk"[18] 49.74.32.77 #20: Oakley Transform [3DES_CBC (192), HMAC_SHA1, MODP1024] refused

Sep 29 05:45:02 debian pluto[14006]: "l2tp-psk"[18] 49.74.32.77 #20: no acceptable Oakley Transform

Sep 29 05:45:02 debian pluto[14006]: "l2tp-psk"[18] 49.74.32.77 #20: sending notification NO_PROPOSAL_CHOSEN to 49.74.32.77:1816

Sep 29 05:45:02 debian pluto[14006]: "l2tp-psk"[18] 49.74.32.77 #20: deleting state (STATE_MAIN_R0)

Sep 29 05:45:02 debian pluto[14006]: "l2tp-psk"[18] 49.74.32.77: deleting connection "l2tp-psk"[18] 49.74.32.77 instance with peer 49.74.32.77 {isakmp=#0/ipsec=#0}
`

How to fix this, thanks!
The router only support PPTP,L2TP and IPSec/L2TP 3 modes

**Comment by letoams** [comment]
On Sat, 29 Sep 2018, jszsj wrote:

> Sep 29 05:45:02 debian pluto[14006]: "l2tp-psk"[18] 49.74.32.77 #20: responding to Main Mode from unknown peer 49.74.32.77 on port 1816 Sep 29 05:45:02 debian
> pluto[14006]: "l2tp-psk"[18] 49.74.32.77 #20: Oakley Transform [3DES_CBC (192), HMAC_MD5, MODP1024] refused Sep 29 05:45:02 debian pluto[14006]: "l2tp-psk"[18]
> 49.74.32.77 #20: Oakley Transform [3DES_CBC (192), HMAC_SHA1, MODP1024] refused Sep 29 05:45:02 debian pluto[14006]: "l2tp-psk"[18] 49.74.32.77 #20: no acceptable Oakley
> Transform Sep 29 05:45:02 debian pluto[14006]: "l2tp-psk"[18] 49.74.32.77 #20: sending notification NO_PROPOSAL_CHOSEN to 49.74.32.77:1816 Sep 29 05:45:02 debian
> pluto[14006]: "l2tp-psk"[18] 49.74.32.77 #20: deleting state (STATE_MAIN_R0) Sep 29 05:45:02 debian pluto[14006]: "l2tp-psk"[18] 49.74.32.77: deleting connection
> "l2tp-psk"[18] 49.74.32.77 instance with peer 49.74.32.77 {isakmp=#0/ipsec=#0}

Your client connects and wants to very weak modp1024 (aka DH2) which is not part
of the default proposal list. You must fix the client to use stronger
DiffieHellman groups, at least DH5 (modp1536) but better DH14 (modp2048)

Paul

**Comment by jszsj** [comment]
@letoams Thank u for your reply, But I can't fix the router's firmware, I bought it today and it doesn't support change this settings T_T

**Comment by letoams** [comment]
That seems extremely unlikely. You can let libreswan do the old stuff but I recommend changing your router.

ike=3des-md5;modp1024,3des-sha1;modp1024

esp=3des-md5;modp1024,3des-sha1;modp1024

**Comment by hwdsl2** [comment]
Thanks @letoams!

@jszsj Please append `,3des-sha1;modp1024` to the end of `Ike=` line in your /etc/ipsec.conf on VPN server, then run `service ipsec restart`.

**Comment by jszsj** [comment]
Thanks @letoams @hwdsl2 
That works fine, now I can do some more test today!
