### ISSUE TITLE
VPN works only before reboot

### ISSUE THREAD

**Issue by seebeen** [hwdsl2/setup-ipsec-vpn#455]
I'm trying to setup a mikrotik to Ubuntu l2tp server tunnel.
When I run the install script it works flawleslly.  VPN tunnel is immediately established, but as soon as I reboot the server the connection will not complete.

Error I get on mikrotik is **phase 1 negotiation failed due to time up**

Can you shed some light on this?

**Comment by hwdsl2** [comment]
@seebeen Hello! What is your Ubuntu version? Is your VPN server behind a home router? You may check the connection logs using:
```
grep -e pluto -e xl2tpd /var/log/auth.log /var/log/syslog
```

If there is no new log after trying to connect, then the traffic did not reach the VPN server.

**Comment by hwdsl2** [comment]
@seebeen Hope you've figured it out. If the problem persists please reply or open a new issue.
