### ISSUE TITLE
L2TP doesn't work

### ISSUE THREAD

**Issue by NerdOfLinux** [hwdsl2/setup-ipsec-vpn#456]
After installation, only "pure" IPSec works. I've opened ports 500,4500, and 1701, but L2TP just times out. `service ipsec status` doesn't even register L2TP, even though it shows stuff for pure IPSec

**Comment by hwdsl2** [comment]
@NerdOfLinux Hello! L2TP without IPsec is not supported as the traffic is not encrypted at all.

If you are referring to IPsec/L2TP, however, please check the logs for errors using:
```
grep xl2tpd /var/log/syslog /var/log/messages
```

**Comment by NerdOfLinux** [comment]
That's the problem, nothing is there about IPsec/L2TP. Things appear when using only IPSec, and I can't figure out why.

**Comment by hwdsl2** [comment]
@NerdOfLinux What is your Linux distribution and version? Can you try the following (or re-run the latest version of VPN script):
```
apt-get clean
apt-get update
apt-get install xl2tpd
service xl2tpd restart
service xl2tpd status
```

Or for CentOS:
```
yum clean all
yum install xl2tpd
service xl2tpd restart
service xl2tpd status
```

**Comment by NerdOfLinux** [comment]
I've already run the script multiple times, and following the uninstall instructions after each attempt. 

Since nothing is being logged, I think the traffic is being blocked before it can reach, but I don't know what would do that considering the ports are open.

**Comment by hwdsl2** [comment]
@NerdOfLinux What is your server provider? Maybe you need to open UDP port 500 and 4500 in their firewall? Or is it a home server on Raspberry Pi?

Normally if pure IPsec works, then traffic can reach the VPN server just fine. You may check the IPsec logs with:
```
grep pluto /var/log/auth.log /var/log/secure
```

**Comment by NerdOfLinux** [comment]
I'm using Ubuntu 18.04 on DigitalOcean. I'm not using their firewall, which means everything is up to iptables.

**Comment by hwdsl2** [comment]
@NerdOfLinux I just tested on a fresh Ubuntu 18.04 system on DigitalOcean and the IPsec/L2TP mode is working fine. Please double check your VPN client's "Server IP" and "IPsec PSK" fields for typos. Maybe you typed the server IP wrong?

**Comment by NerdOfLinux** [comment]
I gave up. I tried another installer script which also had the exact same issue, which means there's nothing wrong with this script.

I even tried clearing all iptables rules, which didn't help. 

Thanks for your help though.
