### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Sitmobedaf** [hwdsl2/setup-ipsec-vpn#457]
I installed it on two different VPS with KVM and tried to connect from two different devices. Not connected. The service is working. At the same time OpenVPN without problems. WTF...?!

**Comment by hwdsl2** [comment]
@Sitmobedaf Hello! What is your VPS provider and server’s Linux version? To troubleshoot, check and post the connection logs using:
```
# Ubuntu/Debian
grep -e pluto -e xl2tpd /var/log/auth.log /var/log/syslog
# CentOS
grep -e pluto -e xl2tpd /var/log/secure /var/log/messages
```

**Comment by Sitmobedaf** [comment]
Hetzner Cloud and JustHost (Russia). Ubuntu 16.04 (x64).
https://pastebin.com/raw/jtmzrFpV
Now I tried it with a new device. The logs do not show connection attempts.

**Comment by hwdsl2** [comment]
@Sitmobedaf Thanks for the info. If the logs do not show connection attempts, then the traffic did not reach your VPN server.

Check the VPN server IP entered in your VPN client for typos, and consult your server provider’s documentation regarding any firewall that needs to be configured  (the VPN uses UDP 500 and 4500).

Also try using another client device to connect from a different network, such as 3G mobile network.
