### ISSUE TITLE
DNS leaks on Windows 10

### ISSUE THREAD

**Issue by milox** [hwdsl2/setup-ipsec-vpn#458]
Unfortunately, this setup is leaking DNS requests.

Steps to reproduce:
1. Setup server
2. Connect using any client in Windows
3. Go to ipleak.net or doileak.com, do the test and notice your ISP's DNS

It should have the ability to use the system DNS resolvers (from /etc/resolv.conf). This related OpenVPN setup doesn't leak DNSes, see how they fixed it
https://github.com/angristan/openvpn-install/blob/master/openvpn-install.sh

**Comment by hwdsl2** [comment]
@milox Hello! Unlike OpenVPN, the built-in Windows 10 VPN client (IPsec/L2TP and IKEv2) does not leak DNS if your DNS on internet adapter is out of local segment. Please refer to [1] [2].

Quote from [1]:
> Interesting fact # 2: Built-in VPN configuration (tested with IPsec IKEv2) somehow sets system up to
> avoid DNS leaks if your DNS on internet adapter is out of local segment.

[1] https://community.openvpn.net/openvpn/ticket/605
[2] https://github.com/trailofbits/algo/issues/565#issuecomment-305256230
