### ISSUE TITLE
cenotos6 无法连接

### ISSUE THREAD

**Issue by a57571735** [hwdsl2/setup-ipsec-vpn#46]
执行脚本后无法连接，错误809，关闭iptables后可连接

**Comment by a57571735** [comment]
经过修改iptables，可以连接上了，也可以上网，不过只能上一次网，打开一个页面后就再也上不了外网了，必须重连，然后又可以打开一个页面

**Comment by hwdsl2** [comment]
@a57571735 你好！请问你对 IPTables 规则做了什么修改？另外你在 Windows 系统中是否已经添加了哪个或哪些注册表键？请参见 [客户端设置方法](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md)

**Comment by hwdsl2** [comment]
@a57571735 如果关闭 IPTables 后可连接，原因可能是你的系统上添加了 ProhibitIpSec 注册表键。**不可以** 添加该键，否则会导致 809 错误。请检查并删除以下注册表键（如果存在），然后重启电脑。

```
HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Rasman\Parameters
Value Name: ProhibitIpSec
Data Type: REG_DWORD
Value: 1
```

尝试重新连接 VPN。如果正常，可以还原服务器上的 IPTables 规则。

**Comment by a57571735** [comment]
@hwdsl2 Oh my gosh！！！ it worked，thanks a lot。这个问题困扰我好几个月了，昨天才发现可以提问，试着描述了下问题，没想到在你的帮助下解决了，感谢开源精神，thanks to share
