### ISSUE TITLE
IKEv2 PSK

### ISSUE THREAD

**Issue by NerdOfLinux** [hwdsl2/setup-ipsec-vpn#460]
Is there any way to set up libreswan for IKEv2 support with PSK auth instead of certificates?

It's possible, according to the [FAQ](https://libreswan.org/wiki/FAQ#Which_IKEv1_and_IKEv2_Exchange_Modes_does_libreswan_support.3F):
> ## Supported:
> IKEv2 (**PSK**, raw RSA, X509)

**Comment by hwdsl2** [comment]
@NerdOfLinux Yes it seems possible. There are some examples in the Libreswan tests: [1] [2] [3].

@letoams Is using IKEv2 with PSK only (without certificates) a good idea? Which operating systems support this mode natively? Thanks!

[1] https://github.com/libreswan/libreswan/tree/master/testing/pluto/ikev2-05-basic-psk
[2] https://github.com/libreswan/libreswan/tree/master/testing/pluto/ikev2-11-simple-psk
[3] https://github.com/libreswan/libreswan/tree/master/testing/pluto/ikev2-12-transport-psk

**Comment by NerdOfLinux** [comment]
Thank you for links to the tests. However, I was unable to figure out how to combine those with the existing config created by your script. 

The error I always get is:

> returned STF_FAIL with v2N_NO_PROPOSAL_CHOSEN

**Comment by letoams** [comment]
On Sun, 7 Oct 2018, NerdOfLinux wrote:

> Is there any way to set up libreswan for IKEv2 support with username password auth instead of certificates?

The short answer is no. But let's clarify the question a bit.

There is authentication of the IPsec SA, and then on top of that there
is an optional user/password authentication.

For IKEv1, you can use either PSK or certificates for the IPsec SA, and
then you can use XAUTH/ModeConfig for a user + password.

For IKEv2, the protocol allows assymetric authentication. So the protocol
supports authenticating the server with a certificate, and allowing the
client to use an EAP authentication method without having their own
certificate. The two common EAP methods are EAP-TLS and EAP-mschapv2
which are password based. Libreswan does not support EAP yet, but it is
high on our list to add. Meanwhile, for IKEv2 with libreswan, you can
only use certificates for client and server authentication. You can also
use PSK like in IKEv1, but we strongly recommend you don't do that. PSK's
used are always weak and vulnerable to dictionary attacks.

Paul
