### ISSUE TITLE
L2TP IPsec can't connect

### ISSUE THREAD

**Issue by okgolove** [hwdsl2/setup-ipsec-vpn#462]
Hello! Awesome repo. It works for me on EC2 instance, but I can't set it up in my office.
I have Linksys E8350

<img width="467" alt="image" src="https://user-images.githubusercontent.com/36846182/46726570-4f6d1400-cc87-11e8-9ada-f73362c0e391.png">

PSK and password are correct.

Logs:
```
Oct 10 09:17:53 raspberrypi pluto[11722]: "l2tp-psk"[2] 192.168.1.1 #4: responding to Main Mode from unknown peer 192.168.1.1 on port 500
Oct 10 09:17:53 raspberrypi pluto[11722]: "l2tp-psk"[2] 192.168.1.1 #4: STATE_MAIN_R1: sent MR1, expecting MI2
Oct 10 09:17:53 raspberrypi pluto[11722]: "l2tp-psk"[2] 192.168.1.1 #4: STATE_MAIN_R2: sent MR2, expecting MI3
Oct 10 09:17:53 raspberrypi pluto[11722]: "l2tp-psk"[2] 192.168.1.1 #4: STATE_MAIN_R2: retransmission; will wait 0.5 seconds for response
Oct 10 09:17:54 raspberrypi pluto[11722]: "l2tp-psk"[2] 192.168.1.1 #4: STATE_MAIN_R2: retransmission; will wait 1 seconds for response
Oct 10 09:17:55 raspberrypi pluto[11722]: "l2tp-psk"[2] 192.168.1.1 #4: STATE_MAIN_R2: retransmission; will wait 2 seconds for response
Oct 10 09:17:57 raspberrypi pluto[11722]: "l2tp-psk"[2] 192.168.1.1 #4: STATE_MAIN_R2: retransmission; will wait 4 seconds for response
Oct 10 09:18:01 raspberrypi pluto[11722]: "l2tp-psk"[2] 192.168.1.1 #4: STATE_MAIN_R2: retransmission; will wait 8 seconds for response
Oct 10 09:18:09 raspberrypi pluto[11722]: "l2tp-psk"[2] 192.168.1.1 #4: STATE_MAIN_R2: retransmission; will wait 16 seconds for response
Oct 10 09:18:25 raspberrypi pluto[11722]: "l2tp-psk"[2] 192.168.1.1 #4: STATE_MAIN_R2: retransmission; will wait 32 seconds for response
Oct 10 09:18:57 raspberrypi pluto[11722]: "l2tp-psk"[2] 192.168.1.1 #4: STATE_MAIN_R2: 60 second timeout exceeded after 7 retransmits.  No response (or no acceptable response) to our IKEv1 message
Oct 10 09:18:57 raspberrypi pluto[11722]: "l2tp-psk"[2] 192.168.1.1 #4: deleting state (STATE_MAIN_R2) and NOT sending notification
Oct 10 09:18:57 raspberrypi pluto[11722]: deleting connection "l2tp-psk"[2] 192.168.1.1 instance with peer 192.168.1.1 {isakmp=#0/ipsec=#0}
```

**Comment by hwdsl2** [comment]
@okgolove Hello! Your logs indicate that this is a network-related issue. But from your screenshot it looks like you've already forwarded UDP ports 500 and 4500 to your Raspberry Pi.

Also, check if you have the line `left=%defaultroute` in your `/etc/ipsec.conf`. If you instead have `left=YOUR_PRIVATE_IP`, make sure that `YOUR_PRIVATE_IP` matches your Raspberry Pi's current private IP. If it does not match, correct it and restart the IPsec service. It is recommended to reserve a static IP for your Raspberry Pi in your router's DHCP settings, so that it does not change on reboot.

**Comment by okgolove** [comment]
@hwdsl2 I've checked it. Theere is "left=%defaultroute". Also, I had 2 interfaces (eth and wlan), I disabled wlan and tried to connect again. Nothing changed. Still doesn't work.

**Comment by xingrunzhi** [comment]
I have seen the same issue when I finished set up Ipsec on Amazon EC2 Ubuntu host. I tried to connect to the EC2 host through my mac.
On the server side, I am seeing the logs
```
```

**Comment by xingrunzhi** [comment]
Solved. I have wrongly configured my EC2 serve inbound rule to 400 instead of 4500. 😃
