### ISSUE TITLE
上不了谷歌

### ISSUE THREAD

**Issue by wxmdsh** [hwdsl2/setup-ipsec-vpn#466]
您好，
vpn安装好，也连接上了，咋上不了谷歌。

**Comment by hwdsl2** [comment]
@wxmdsh 你好！这个一般可以通过清除你的 VPN 客户端设备的 DNS 缓存（步骤请自行搜索），或者重启客户端设备解决。

**Comment by wxmdsh** [comment]
您好，清除了DNS还是不行，我发现，我连接上这个vpn后，我原来能连接的数据库都打不开




| |
15021071915
邮箱：15021071915@163.com
|

Signature is customized by Netease Mail Master

在2018年10月17日 21:14，Lin Song 写道：

@wxmdsh 你好！这个一般可以通过清除你的 VPN 客户端设备的 DNS 缓存（步骤请自行搜索），或者重启客户端设备解决。

**Comment by hwdsl2** [comment]
@wxmdsh 是不是无法打开任何网站？试一下故障排除里的步骤 [1]。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除
