### ISSUE TITLE
my ssr didnt work after setup this vpn

### ISSUE THREAD

**Issue by jesusslim** [hwdsl2/setup-ipsec-vpn#467]
my vps setup ssr before and it works,but after setup this vpn,my ssr didnt work any more,is there some confliction between this vpn and ssr?

**Comment by hwdsl2** [comment]
@jesusslim Hello! For your use case, try removing the IPTables DROP rule from the FORWARD chain:
```
iptables -D FORWARD -j DROP
```

Does it work after running this command on your server?

**Comment by jesusslim** [comment]
i run this command and restart my ssr service,but it still didnt work

**Comment by hwdsl2** [comment]
@jesusslim Can you post your IPTables rules? Run:
```
iptables -nvL; iptables -nvL -t nat
```

**Comment by jesusslim** [comment]
iptables -nvL; iptables -nvL -t nat
Chain INPUT (policy ACCEPT 135 packets, 18094 bytes)
 pkts bytes target     prot opt in     out     source               destination         
88756 8052K fail2ban-ssh  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 22
    1   129 DROP       udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:1701 policy match dir in pol none
1854K   82M DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate INVALID
 162K   22M ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
   15  6420 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 500,4500
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:1701 policy match dir in pol ipsec
    0     0 DROP       udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:1701

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  339 13560 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate INVALID
    0     0 ACCEPT     all  --  eth0   ppp+    0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  ppp+   eth0    0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  ppp+   ppp+    192.168.42.0/24      192.168.42.0/24     
87602   95M ACCEPT     all  --  eth0   *       0.0.0.0/0            192.168.43.0/24      ctstate RELATED,ESTABLISHED
83307 6945K ACCEPT     all  --  *      eth0    192.168.43.0/24      0.0.0.0/0           

Chain OUTPUT (policy ACCEPT 30 packets, 1528 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain fail2ban-ssh (1 references)
 pkts bytes target     prot opt in     out     source               destination         
70961 7099K RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           
Chain PREROUTING (policy ACCEPT 781K packets, 65M bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 178K packets, 22M bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 941K packets, 57M bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 941K packets, 57M bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MASQUERADE  all  --  *      eth0    192.168.42.0/24      0.0.0.0/0           
 2452  244K MASQUERADE  all  --  *      eth0    192.168.43.0/24      0.0.0.0/0            policy match dir out pol none

**Comment by jesusslim** [comment]
still didnt work.

iptables -nvL; iptables -nvL -t nat
Chain INPUT (policy ACCEPT 283 packets, 38327 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  103  6707 fail2ban-ssh  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 22
    0     0 DROP       udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:1701 policy match dir in pol none
  107  4708 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate INVALID
  177 18204 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 500,4500
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:1701 policy match dir in pol ipsec
    0     0 DROP       udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:1701

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate INVALID
    0     0 ACCEPT     all  --  eth0   ppp+    0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  ppp+   eth0    0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  ppp+   ppp+    192.168.42.0/24      192.168.42.0/24     
    0     0 ACCEPT     all  --  eth0   *       0.0.0.0/0            192.168.43.0/24      ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  *      eth0    192.168.43.0/24      0.0.0.0/0           
    0     0 DROP       all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT 228 packets, 16553 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain fail2ban-ssh (1 references)
 pkts bytes target     prot opt in     out     source               destination         
  103  6707 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           
Chain PREROUTING (policy ACCEPT 325 packets, 26391 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 85 packets, 9566 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 86 packets, 5192 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 86 packets, 5192 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 MASQUERADE  all  --  *      eth0    192.168.42.0/24      0.0.0.0/0           
    0     0 MASQUERADE  all  --  *      eth0    192.168.43.0/24      0.0.0.0/0            policy match dir out pol none

**Comment by hwdsl2** [comment]
@jesusslim Other than the IPTables rules, I can't think of other places where the VPN setup script could conflict with SSR. Please do some further troubleshooting yourself.
