### ISSUE TITLE
长时间运行后VPN服务不稳定无法连接

### ISSUE THREAD

**Issue by laole918** [hwdsl2/setup-ipsec-vpn#468]
刚安装完成Android、IOS、MAC都测试了正常连接，而且速度还不错。大约运行了12个小时后，所有设备均出现连接失败，IOS提示无响应，Android提示连接失败。
后来登录VPS重启VPN服务器后又可以正常连接了

**Comment by hwdsl2** [comment]
@laole918 你好！查看一下 Libreswan 和 xl2tpd 日志，看看你所说的那段时间是否有异常：

```
grep -e pluto -e xl2tpd /var/log/auth.log /var/log/syslog
```

**Comment by laole918** [comment]
[root@DGCHOST-181023-NU8N log]# grep -e pluto -e xl2tpd /var/log/auth.log /var/log/syslog
grep: /var/log/auth.log: No such file or directory
grep: /var/log/syslog: No such file or directory

**Comment by hwdsl2** [comment]
@laole918 如果你使用的是 CentOS，请运行：
```
grep -e pluto -e xl2tpd /var/log/secure /var/log/messages
```

**Comment by laole918** [comment]
[vps.log](https://github.com/hwdsl2/setup-ipsec-vpn/files/2508857/vps.log)
辛苦您帮忙看一下

**Comment by hwdsl2** [comment]
@laole918 从你的日志来看，问题在于你一开始使用了IPsec/XAuth模式，然后几小时后从同一IP又尝试使用IPsec/L2TP模式。这种转换模式导致了日志中的以下错误：
```
"l2tp-psk"[2] 111.199.81.22 #25: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
```

因为有些客户端（比如安卓某些版本）在断开连接时不删除IPsec SA，这种情况下服务器会记住上一次的模式，从而在你从同一IP换用IPsec/L2TP模式会无法连接。你可以在服务器运行以下命令解决：
```
service ipsec restart
```
