### ISSUE TITLE
This script does not support OpenVZ VPS

### ISSUE THREAD

**Issue by LvJianfeng** [hwdsl2/setup-ipsec-vpn#47]

**Comment by hwdsl2** [comment]
@LvJianfeng These VPN scripts do not support OpenVZ VPS, because IPsec kernel support may be unavailable. Please use a KVM, Xen or VMware VPS instead.

An alternative that can be used on OpenVZ VPS is OpenVPN [1].

[1] https://github.com/Nyr/openvpn-install
