### ISSUE TITLE
Problem | How to just start the vpn?

### ISSUE THREAD

**Issue by B4RD4k** [hwdsl2/setup-ipsec-vpn#470]
Hi, 
I'm trying to understand if there is a way to just start the vpn service after installation, (like when changing IP addres) ?

now im executing the installation script any time i'm changing IP addres or shut down the machine.

**Comment by hwdsl2** [comment]
@B4RD4k Hello! The VPN automatically starts after install. It should continue to work after changing your server’s IP address or on reboot. There is no need to run the install script again.

**Comment by B4RD4k** [comment]
10x
