### ISSUE TITLE
‘struct in6_addr’ 重定义

### ISSUE THREAD

**Issue by caspar-chen** [hwdsl2/setup-ipsec-vpn#471]
In file included from /opt/src/libreswan-3.27/programs/pluto/linux-copy/linux/xfrm.h:5,
                 from /opt/src/libreswan-3.27/programs/pluto/kernel_netlink.c:60:
/usr/include/linux/in6.h:31: 错误：‘struct in6_addr’重定义
/usr/include/linux/in6.h:48: 错误：‘struct sockaddr_in6’重定义
/usr/include/linux/in6.h:56: 错误：‘struct ipv6_mreq’重定义
/opt/src/libreswan-3.27/programs/pluto/kernel_netlink.c: 在函数‘netlink_find_offload_feature’中:
/opt/src/libreswan-3.27/programs/pluto/kernel_netlink.c:1077: 错误：提领指向不完全类型的指针
/opt/src/libreswan-3.27/programs/pluto/kernel_netlink.c:1077: 错误：提领指向不完全类型的指针
/opt/src/libreswan-3.27/programs/pluto/kernel_netlink.c:1079: 错误：提领指向不完全类型的指针
/opt/src/libreswan-3.27/programs/pluto/kernel_netlink.c:1079: 错误：‘ETHTOOL_GSSET_INFO’未声明(在此函数内第一次使用)
/opt/src/libreswan-3.27/programs/pluto/kernel_netlink.c:1079: 错误：(即使在一个函数内多次出现，每个未声明的标识符在其
/opt/src/libreswan-3.27/programs/pluto/kernel_netlink.c:1079: 错误：所在的函数内也只报告一次。)
/opt/src/libreswan-3.27/programs/pluto/kernel_netlink.c:1080: 错误：提领指向不完全类型的指针
/opt/src/libreswan-3.27/programs/pluto/kernel_netlink.c:1080: 错误：‘ETH_SS_FEATURES’未声明(在此函数内第一次使用)
/opt/src/libreswan-3.27/programs/pluto/kernel_netlink.c:1087: 错误：提领指向不完全类型的指针
/opt/src/libreswan-3.27/programs/pluto/kernel_netlink.c:1089: 错误：提领指向不完全类型的指针
/opt/src/libreswan-3.27/programs/pluto/kernel_netlink.c: 在函数‘netlink_detect_offload’中:
/opt/src/libreswan-3.27/programs/pluto/kernel_netlink.c:1140: 错误：提领指向不完全类型的指针
/opt/src/libreswan-3.27/programs/pluto/kernel_netlink.c:1140: 错误：提领指向不完全类型的指针
/opt/src/libreswan-3.27/programs/pluto/kernel_netlink.c:1145: 错误：提领指向不完全类型的指针
/opt/src/libreswan-3.27/programs/pluto/kernel_netlink.c:1145: 错误：‘ETHTOOL_GFEATURES’未声明(在此函数内第一次使用)
/opt/src/libreswan-3.27/programs/pluto/kernel_netlink.c:1146: 错误：提领指向不完全类型的指针
/opt/src/libreswan-3.27/programs/pluto/kernel_netlink.c:1152: 错误：提领指向不完全类型的指针
make[3]: *** [kernel_netlink.o] 错误 1
make[3]: *** 正在等待未完成的任务....
make[2]: *** [base] 错误 2
make[1]: *** [recursive-base] 错误 2
make: *** [recursive-base] 错误 2
Error: Libreswan 3.27 failed to build.

**Comment by hwdsl2** [comment]
@caspar-chen Hello! What is your Linux distribution and version? e.g. Ubuntu 18.04. Let us know.

You can try removing this line from the setup script and re-run it:
```
USE_GLIBC_KERN_FLIP_HEADERS = true
```

**Comment by letoams** [comment]
See mk/config.mk and look for something called FLIP_GLIBC_HEADER and change it’s value.

**Comment by caspar-chen** [comment]
> @caspar-chen Hello! What is your Linux distribution and version? e.g. Ubuntu 18.04. Let us know.
> 
> You can try removing this line from the setup script and re-run it:
> 
> ```
> USE_GLIBC_KERN_FLIP_HEADERS = true
> ```

I removed this line or changed the value to false, but it is still the same.

**Comment by caspar-chen** [comment]
My os : Centos 6.5
Linux version 2.6.32-431.11.25.el6.ucloud.x86_64 (root@b4e6f084c748) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) ) #1 SMP Tue Jul 19 10:06:12 EDT 2016

**Comment by letoams** [comment]
On Sun, 28 Oct 2018, Caspar wrote:

>       @caspar-chen Hello! What is your Linux distribution and version? e.g. Ubuntu 18.04. Let us know.
>
>       You can try removing this line from the setup script and re-run it:
> 
> USE_GLIBC_KERN_FLIP_HEADERS = true
> 
> I removed this line or changed the value to false, but it is still the same.

Did you run "make clean" after changing the value?

Paul

**Comment by letoams** [comment]
On Sun, 28 Oct 2018, Caspar wrote:

> To: hwdsl2/setup-ipsec-vpn <setup-ipsec-vpn@noreply.github.com>
> Subject: Re: [hwdsl2/setup-ipsec-vpn] ‘struct in6_addr’ 重定义 (#471)
> 
> My os : Centos 6.5
> Linux version 2.6.32-431.11.25.el6.ucloud.x86_64 (root@b4e6f084c748) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) ) #1 SMP Tue Jul 19 10:06:12 EDT 2016

Either using USE_GLIBC_KERN_FLIP_HEADERS=false or using USE_GLIBC_KERN_FLIP_HEADERS=true should work to compile the source.
Please run make clean (or rm -rf OBJ*) before trying to re-build from the same source tree if you change the value.

Paul

**Comment by hwdsl2** [comment]
@caspar-chen Cannot reproduce this error on a fully updated CentOS 6 system. To fix the issue, please fully update your system using `yum update` to CentOS 6.10, then download and run the latest version of the VPN setup script again.
