### ISSUE TITLE
Android 8.0 自动断开

### ISSUE THREAD

**Issue by LittleTin** [hwdsl2/setup-ipsec-vpn#472]
我安装的版本为「240a018」这个commit，近期使用了Android 8.0，发现会定时断开连线(always 1.1 minutes)，Android 7.0、6.0皆无此状况。
服务器显示断开，手机端仍显示连线中但无法连网。

> Using interface ppp0
> Connect: ppp0 <--> /dev/pts/0
> Cannot determine ethernet address for proxy ARP
> local  IP address 192.168.42.1
> remote IP address 192.168.42.10
> Terminating on signal 15
> Modem hangup
> Connect time 1.1 minutes.
> Sent 2427 bytes, received 4120 bytes.
> Connection terminated.

请问如何维持原设定更新至新版本呢?或是修正部分参数改善此问题?

**Comment by hwdsl2** [comment]
@LittleTin 你好！请先升级 [1] 到 Libreswan 最新版本再试一下。该问题也有可能是网络不稳定或者防火墙干扰导致的。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#%E5%8D%87%E7%BA%A7libreswan
