### ISSUE TITLE
照着教程，把ikev2搭好了，ios也能连上，但是隔一会就自动断开是为啥

### ISSUE THREAD

**Issue by huangshayang** [hwdsl2/setup-ipsec-vpn#474]
几分钟吧，就断开了

**Comment by hwdsl2** [comment]
@huangshayang 你好！这个是正常的。苹果手机在屏幕变黑几分钟后就会自动断开无线网络，所以 VPN 也会断开。如果你需要自动重连功能，可以考虑使用 OpenVPN。

**Comment by huangshayang** [comment]
> @huangshayang 你好！这个是正常的。苹果手机在屏幕变黑几分钟后就会自动断开无线网络，所以 VPN 也会断开。如果你需要自动重连功能，可以考虑使用 OpenVPN。

可是我根本没息屏，关闭屏幕，一直开启的 wifi也连着的

**Comment by hwdsl2** [comment]
@huangshayang 如果网络不稳定的话也可能出现此问题。你可以查看一下 IPsec 日志看看是否有错误：
grep pluto /var/log/auth.log /var/log/secure
