### ISSUE TITLE
win10 cann't access google youtube ...

### ISSUE THREAD

**Issue by sunfeilong** [hwdsl2/setup-ipsec-vpn#477]
Use win10 connect VPN, But cannot access google  youtube。

**Comment by sunfeilong** [comment]
set local network and VPN unselect IPV6 solve this problem.

**Comment by hwdsl2** [comment]
@sunfeilong Hello! Glad to hear the issue is resolved. What did you do to set the local network?

You may refer to the Win 8/10 DNS section in the Troubleshooting link under “Next steps” of README for more info.
