### ISSUE TITLE
Need help with "Cisco IPsec" on MikroTik router

### ISSUE THREAD

**Issue by smp79** [hwdsl2/setup-ipsec-vpn#479]
Hello, I'm trying to set up a "Cisco IPsec" mode on my Mikrotik hAP ac² router.

I already configured the IPsec/L2TP VPN Client on this router and it works fine. However, I want to try the "Cisco IPsec" mode without L2TP for better performance. But I can't figure out how to do that.

I configured the IPsec part and connection is successfully established. In case of L2TP mode I just added the L2TP client interface, configured the firewall and routes as per [this tutorial](https://torguard.net/knowledgebase.php?action=displayarticle&id=243).  What should I do to make it work without L2TP?

**Comment by hwdsl2** [comment]
@smp79 Hello! Here is an example [1] in the MikroTik Wiki for your use case. Other than that, I'm not sure. I would recommend that you ask on the MikroTik Forum [2].

[1] https://wiki.mikrotik.com/wiki/Manual:IP/IPsec#Simple_mutual_PSK_XAuth_configuration
[2] https://forum.mikrotik.com/
