### ISSUE TITLE
Permission denied on Ubuntu 16.04.1 LTS trying to connect

### ISSUE THREAD

**Issue by Brendan-McCoy** [hwdsl2/setup-ipsec-vpn#48]
When I run the authentication command 
` sudo echo "c XXX-YOUR-CONNECTION-NAME-XXX <user> <pass>" > /var/run/xl2tpd/l2tp-control`
(replacing the connection name, username, and password), I get the following output:
`-bash: /var/run/xl2tpd/l2tp-control: Permission denied`

I've verified that I've editing config files as instructed and have restarting the two services, and that the credentials are valid on a windows machine.

**Comment by hwdsl2** [comment]
@Brendan-McCoy Try this instead:

echo "c XXX-YOUR-CONNECTION-NAME-XXX <user> <pass>" | sudo tee /var/run/xl2tpd/l2tp-control

Ref: https://askubuntu.com/questions/20578/redirect-the-output-using-sudo
