### ISSUE TITLE
Error IPSec verify

### ISSUE THREAD

**Issue by palieter** [hwdsl2/setup-ipsec-vpn#481]
Dear,

I’m install VPN server on the raspberry pi from the follow url: 
https://www.stewright.me/2018/07/create-a-raspberry-pi-vpn-server-using-l2tpipsec/

After install i’m running the follow command: IPSec verify thuis have 2 errors:
**Pluto listening for IKE on udp 500 [FAILED]
Pluto listening for IKE/NAT-T on udp 4500 [DISABLED]**

Thanks in advance.

Regards.

**Comment by letoams** [comment]
You need to start the ipsec service before running ipsec verify. You ran run “ipsec start” for that

**Comment by hwdsl2** [comment]
Thanks @letoams!
@palieter The `ipsec verify` result on Raspberry Pis are not accurate and the two errors you mentioned can be ignored.

You may instead run `ipsec status` or check the Libreswan logs using `grep pluto /var/log/auth.log` to verify that it is running. 

You’ll need to set up port forwarding on your home router for UDP ports 500 and 4500 to your Raspberry Pi’s local IP, and it is recommended to reserve a static IP in the router’s DHCP settings so that the IP does not change on reboot.

**Comment by palieter** [comment]
Dear,

Thanks for repley.

I have sent a screenshot of the attached log file, on the home router I opened the port 500 and 4500 udp to the ip of the raspberry pi, when I try to connect to windows 10 I get the following message:

"The L2TP connection attempt because of the security layer encountered a processing error during initial
 negotiations with the remote computer. "

I also can not connect via android.

The ip address of the vpn client is teh same of the home router.

thank in advance,

regard,
palieter
Van: Lin Song<mailto:notifications@github.com>
Verzonden: zondag 11 november 2018 21:27
Aan: hwdsl2/setup-ipsec-vpn<mailto:setup-ipsec-vpn@noreply.github.com>
CC: palieter<mailto:hln1@outlook.be>; Mention<mailto:mention@noreply.github.com>
Onderwerp: Re: [hwdsl2/setup-ipsec-vpn] Error IPSec verify (#481)


@palieter<https://github.com/palieter> Watch the Libreswan logs on the VPN server:

tail -F /var/log/auth.log | grep pluto

Then connect your VPN client. If there are no new log lines showing up, then the traffic did not reach the VPN server on your Raspberry Pi, and you'll need to troubleshoot further yourself.

Double check that you've put the correct public IP (the IP on your home router) in your VPN client. Note that some ISPs may use carrier-grade NAT which blocks connections from the Internet to your public IP.

**Comment by hwdsl2** [comment]
@palieter Your logs show that the connection attempt(s) did not reach your VPN server. You'll need to troubleshoot further yourself until you can see new log lines showing up while running `tail -F /var/log/auth.log | grep pluto`, after trying to connect to the VPN server on your Raspberry Pi.
