### ISSUE TITLE
Unable to locate package linux-image-extra-4.15.0-38-generic

### ISSUE THREAD

**Issue by iamybj** [hwdsl2/setup-ipsec-vpn#482]
root@ubuntu:~# apt-get install linux-image-extra-`uname -r`
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package linux-image-extra-4.15.0-38-generic
E: Couldn't find any package by glob 'linux-image-extra-4.15.0-38-generic'
E: Couldn't find any package by regex 'linux-image-extra-4.15.0-38-generic'

**Comment by hwdsl2** [comment]
@iamybj Hello! To enable L2TP kernel support on e.g. Ubuntu 18.04, please instead install `linux-modules-extra-$(uname -r)`, then run `service xl2tpd restart`. These packages had been renamed from `linux-image-extra-$(uname -r)` for newer Ubuntu kernels.
