### ISSUE TITLE
The VPN server did not respond. Verify the server address and try reconnecting.

### ISSUE THREAD

**Issue by iamybj** [hwdsl2/setup-ipsec-vpn#483]
一直显示如下错误：
The VPN server did not respond. Verify the server address and try reconnecting.

grep pluto /var/log/auth.log 如下错误：

Nov 11 21:06:40 ubuntu pluto[2074]: loading secrets from "/etc/ipsec.secrets"
Nov 11 21:06:58 ubuntu pluto[2074]: "xauth-psk"[1] 60.10.160.132 #1: responding to Main Mode from unknown peer 60.10.160.132 on port 4446
Nov 11 21:06:58 ubuntu pluto[2074]: "xauth-psk"[1] 60.10.160.132 #1: STATE_MAIN_R1: sent MR1, expecting MI2
Nov 11 21:07:02 ubuntu pluto[2074]: "xauth-psk"[1] 60.10.160.132 #1: retransmitting in response to duplicate packet; already STATE_MAIN_R1
Nov 11 21:07:08 ubuntu pluto[2074]: message repeated 2 times: [ "xauth-psk"[1] 60.10.160.132 #1: retransmitting in response to duplicate packet; already STATE_MAIN_R1]
Nov 11 21:07:58 ubuntu pluto[2074]: "xauth-psk"[1] 60.10.160.132 #1: deleting incomplete state after 60.000 seconds
Nov 11 21:07:58 ubuntu pluto[2074]: "xauth-psk"[1] 60.10.160.132 #1: deleting state (STATE_MAIN_R1) and NOT sending notification
Nov 11 21:07:58 ubuntu pluto[2074]: deleting connection "xauth-psk"[1] 60.10.160.132 instance with peer 60.10.160.132 {isakmp=#0/ipsec=#0}
Nov 11 21:08:29 ubuntu pluto[2074]: "xauth-psk"[2] 60.10.160.132 #2: responding to Main Mode from unknown peer 60.10.160.132 on port 1603
Nov 11 21:08:29 ubuntu pluto[2074]: "xauth-psk"[2] 60.10.160.132 #2: STATE_MAIN_R1: sent MR1, expecting MI2
Nov 11 21:08:32 ubuntu pluto[2074]: "xauth-psk"[2] 60.10.160.132 #2: retransmitting in response to duplicate packet; already STATE_MAIN_R1
Nov 11 21:08:39 ubuntu pluto[2074]: message repeated 2 times: [ "xauth-psk"[2] 60.10.160.132 #2: retransmitting in response to duplicate packet; already STATE_MAIN_R1]
Nov 11 21:09:29 ubuntu pluto[2074]: "xauth-psk"[2] 60.10.160.132 #2: deleting incomplete state after 60.000 seconds
Nov 11 21:09:29 ubuntu pluto[2074]: "xauth-psk"[2] 60.10.160.132 #2: deleting state (STATE_MAIN_R1) and NOT sending notification
Nov 11 21:09:29 ubuntu pluto[2074]: deleting connection "xauth-psk"[2] 60.10.160.132 instance with peer 60.10.160.132 {isakmp=#0/ipsec=#0}
Nov 11 21:09:49 ubuntu pluto[2074]: "xauth-psk"[3] 60.10.160.132 #3: responding to Main Mode from unknown peer 60.10.160.132 on port 2258
Nov 11 21:09:49 ubuntu pluto[2074]: "xauth-psk"[3] 60.10.160.132 #3: STATE_MAIN_R1: sent MR1, expecting MI2
Nov 11 21:09:52 ubuntu pluto[2074]: "xauth-psk"[3] 60.10.160.132 #3: retransmitting in response to duplicate packet; already STATE_MAIN_R1
Nov 11 21:09:59 ubuntu pluto[2074]: message repeated 2 times: [ "xauth-psk"[3] 60.10.160.132 #3: retransmitting in response to duplicate packet; already STATE_MAIN_R1]
Nov 11 21:10:49 ubuntu pluto[2074]: "xauth-psk"[3] 60.10.160.132 #3: deleting incomplete state after 60.000 seconds
Nov 11 21:10:49 ubuntu pluto[2074]: "xauth-psk"[3] 60.10.160.132 #3: deleting state (STATE_MAIN_R1) and NOT sending notification
Nov 11 21:10:49 ubuntu pluto[2074]: deleting connection "xauth-psk"[3] 60.10.160.132 instance with peer 60.10.160.132 {isakmp=#0/ipsec=#0}
Nov 11 21:12:23 ubuntu pluto[2074]: "xauth-psk"[4] 60.10.160.132 #4: responding to Main Mode from unknown peer 60.10.160.132 on port 3047
Nov 11 21:12:23 ubuntu pluto[2074]: "xauth-psk"[4] 60.10.160.132 #4: STATE_MAIN_R1: sent MR1, expecting MI2
Nov 11 21:12:26 ubuntu pluto[2074]: "xauth-psk"[4] 60.10.160.132 #4: retransmitting in response to duplicate packet; already STATE_MAIN_R1
Nov 11 21:12:33 ubuntu pluto[2074]: message repeated 2 times: [ "xauth-psk"[4] 60.10.160.132 #4: retransmitting in response to duplicate packet; already STATE_MAIN_R1]

**Comment by hwdsl2** [comment]
@iamybj 你好！从你的日志来看，这个 VPN 连接被防火墙屏蔽或者干扰了。建议你换用其它解决方案，比如 Shadowsocks。

**Comment by iamybj** [comment]
已经换shadowsocks
