### ISSUE TITLE
请教一下，用IPsec/XAuth模式在安卓8.1上不能访问国内网站

### ISSUE THREAD

**Issue by tailgecko** [hwdsl2/setup-ipsec-vpn#484]
您好，按着您的文档成功配置vpn l2tp模式和 XAuth模式，首先非常感谢您详细的文档指导。
在使用过程中有一些问题，自己没能解决，请教一下：
在windows中以您文档中提供的软件成功以 IPsec/XAuth模式链接vpn，并能正常使用。
但在我的安卓手机上 在链接wif的情况下，i以 IPsec/XAuth模式链接的话 google等国外网站可以正常访问，但所有的国内网站不能访问，包括微信、微博等app，显示没有网络链接，更换另一个服务器依然如此。以蜂窝网络链接是正常的，中国移动和中国电信都测试正常。
不管是通过docker方式搭建还是一键脚本方式搭建都存在这个问题
测试的手机为 vivo nex 安卓8.1系统、一加5 安卓8.1系统
vpn服务器为BandwagonHOST,洛杉矶服务器
希望能得到您的帮助，谢谢。

**Comment by tailgecko** [comment]
感谢您的回复，我此前尝试了更换dns，并没有效果，可能是Android的bug，或者是国内手机厂商改过的系统的bug。
我所说的“以蜂窝网络链接”的意思是，在手机关闭wifi的情况下，以蜂窝网络链接按您文档搭建的vpn，是可以正常访问国内外web服务的。
同时我测试了L2Tp模式，在这个模式下一些是正常的。
谢谢您的指导，祝好。

**Comment by fox85** [comment]
> @tailgecko 你好！这个我也不清楚为什么。有可能是默认的 Google DNS 服务器的问题？你可以更换 DNS，参见 [1]。还有可能是你的 VPN 服务器提供商屏蔽了国内网站的连接。再可能是 Android 的 bug。你说“以蜂窝网络链接是正常的”，意思是没有连接 VPN 的时候正常吗？另外你可以试一下 IPsec/L2TP 或者 IKEv2 模式，详见 README。
> 
> [1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#%E9%87%8D%E8%A6%81%E6%8F%90%E7%A4%BA

首先非常感谢@hwdsl2 翻译了这份中文教程。
这个问题，我昨晚也遇到了。安卓系统为android 7 ，android 9，都与楼主遇到相同情况，在4G网络下连接XAUTH模式之后，访问一切网站都正常，但是切换到任意一个wifi网络下就出现部分国内站无法访问。
然后我根据自己过往网络调试的经验，果断怀疑问题出在MTU或MRU上，遂经过一番GOOGLE，终于在这里找到答案：
https://www.zeitgeist.se/2013/11/26/mtu-woes-in-ipsec-tunnels-how-to-fix/
问题出在安卓系统自带的VPN客户端上，它在编译的时候，没有人把它的默认MTU值调低，就导致了出现部分连接的问题。
根据网站给出的指引，只要在vpn服务器端执行
		iptables -t mangle -A FORWARD -o pppoe-wan \
			-p tcp -m tcp --tcp-flags SYN,RST SYN \
			-m tcpmss --mss 1361:1536 \
			-j TCPMSS --set-mss 1360

		echo 1 >/proc/sys/net/ipv4/ip_no_pmtu_disc
以上命令就可以解决。我亲测试过能解决的，希望@hwdsl2在制作一键脚本的时候考虑引入一下，谢谢！
