### ISSUE TITLE
能否增加查看当前连接的用户信息呢？

### ISSUE THREAD

**Issue by OranTing** [hwdsl2/setup-ipsec-vpn#487]
能否增加查看当前连接的用户信息呢？
比如，当前连接进来的用户的IP。归属地之类的。
这个SSR，有这些功能，不知道咱们的VPN可以加入么？
https://doub.io/ss-jc42/

**Comment by OranTing** [comment]
我在 ip-up里加了如下代码：
`echo "##################################" >> /var/log/pptpd.log
echo "Now User $PEERNAME is connected!!!" >> /var/log/pptpd.log
echo "##################################" >> /var/log/pptpd.log
echo "time: `date -d today +%F_%T`" >> /var/log/pptpd.log
echo "clientIP: $6" >> /var/log/pptpd.log
echo "username: $PEERNAME" >> /var/log/pptpd.log
echo "device: $1" >> /var/log/pptpd.log
echo "vpnIP: $4" >> /var/log/pptpd.log
echo "assignIP: $5" >> /var/log/pptpd.log`

但是 clientIP: $6  获取不到用户的IP地址。有什么办法可以获取到么？

**Comment by hwdsl2** [comment]
@OranTing 你好！这个功能超出了本项目的范围，所以不支持。关于`ip-up`，试一下这个方案[1] （添加`ipparam xl2tpd）。

[1] https://bugs.contribs.org/show_bug.cgi?id=8890#c2
