### ISSUE TITLE
How to: Allow multiple clients behind same NAT using IPSEC_psk

### ISSUE THREAD

**Issue by vamsi-una** [hwdsl2/setup-ipsec-vpn#488]
Hi i configured a vps server (ubuntu) using psk, but when i connect windows client i am able to connect only one client at a time.
Both of these clients are behind same NAT having same public IP, and it produces error 789.

**Comment by hwdsl2** [comment]
@vamsi-una Hello! This is a limitation of IPsec/L2TP. Please use Cisco IPsec (IPsec/XAuth) mode for this use case (see Important Notes in project README)

**Comment by letoams** [comment]
This is supposed to be working in recent libreswans where authby=secret always gives out a different IP?

**Comment by hwdsl2** [comment]
Hi @letoams Thanks for the comment. I did notice that multiple VPN clients
behind the same NAT in IPsec/L2TP mode (tested with macOS and iOS clients)
seems to work with Libreswan 3.27 without any IPTables marking rules.

This user uses multiple Windows clients, however, which may not work for
this use case.

**Comment by letoams** [comment]
On Thu, 15 Nov 2018, Lin Song wrote:

> Hi @letoams Thanks for the comment. I did notice that multiple VPN clients
> behind the same NAT in IPsec/L2TP mode (tested with macOS and iOS clients)
> seems to work with Libreswan 3.27 without any IPTables marking rules.
> 
> This user uses multiple Windows clients, however, which may not work for
> this use case.

Ah perhaps that is the difference. Windows might still be using
Transport Mode and not Tunnel Mode.

Paul
