### ISSUE TITLE
Help: Can ping but every other service is not responding

### ISSUE THREAD

**Issue by willfri** [hwdsl2/setup-ipsec-vpn#489]
Hello,

before I go into the problem, I will first explain my setup.

**Home network (behind NAT):**
- Local IP-Network: 192.168.178.0/24
- Raspberry Pi (Ubuntu 16.04) acts as wireguard client:
  - eth0: 192.168.178.85
  - wg0: 192.168.2.3
  - Wireguard client connected to ec2 instance (1.2.3.4)

**ec2 instance (Ubuntu 16.04) acts as wireguard and IPsec vpn server**
- Public interface (ens5): 1.2.3.4
- Wireguard
  - Network: 192.168.2.0/24
  - IP (wg0): 192.168.2.1
- IPsec
  - Network: 192.168.42.0/24
  - IP (ppp0): 192.168.42.1

With this setup (without IPsec vpn server) I'm able to reach every device on every open port from my ec2 instance in my home network how it should be.
Now I want to set up a IPsec vpn server to connect my smartphone and other devices to the ec2 instance and then over wireguard to my home network. But there is somewhere a problem. I can ping from a IPsec client (e.g. 192.168.42.11) any device in my home network. It's also possible to ping from the Raspberry Pi every IPsec clients. But that's it. I can only ping but nothing else.
Btw. the ec2 instance is able to do requests to every device (and services) and visa versa.

I suspect that it's an issue with the routing, unfortunately I am not so fit in there. Any tips? Thank you very much.

Routing table of the Raspberry Pi:
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         fritz.box       0.0.0.0         UG    0      0        0 eth0
192.168.2.0     *               255.255.255.0   U     0      0        0 wg0
192.168.42.0    *               255.255.255.0   U     0      0        0 wg0
192.168.178.0   *               255.255.255.0   U     0      0        0 eth0
```

Routing table of the ec2 instance:
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         ip-172-31-0-1.e 0.0.0.0         UG    100    0        0 ens5
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.31.0.0      0.0.0.0         255.255.240.0   U     0      0        0 ens5
ip-172-31-0-1.e 0.0.0.0         255.255.255.255 UH    100    0        0 ens5
192.168.2.0     0.0.0.0         255.255.255.0   U     0      0        0 wg0
192.168.42.0    0.0.0.0         255.255.255.0   U     0      0        0 wg0
192.168.178.0   0.0.0.0         255.255.255.0   U     0      0        0 wg0
```

**Comment by letoams** [comment]
If ping works but other things don’t, it could be a path mtu issue. See https://libreswan.org/wiki/FAQ#My_ssh_sessions_hang_or_connectivity_is_very_slow

Paul

**Comment by hwdsl2** [comment]
@willfri Hello! The VPN setup scripts insert a DROP rule at the end of the IPTables FORWARD chain for security. For your use case, try allowing traffic from/to your home network in the FORWARD chain:

```
# For IPsec/L2TP
iptables -I FORWARD 2 -s 192.168.178.0/24 -o ppp+ -j ACCEPT
iptables -I FORWARD 2 -i ppp+ -d 192.168.178.0/24 -j ACCEPT
# For IPsec/XAuth (Cisco IPsec)
iptables -I FORWARD 2 -s 192.168.178.0/24 -d 192.168.43.0/24 -j ACCEPT
iptables -I FORWARD 2 -s 192.168.43.0/24 -d 192.168.178.0/24 -j ACCEPT
```

Test it and let us know if it works. If not, it could be that you need to allow traffic from the 192.168.42.0/24 and 192.168.43.0/24 subnets in your home devices' firewalls, for example, add rules in the Windows Firewall with Advanced Security.

**Comment by willfri** [comment]
@letoams @hwdsl2 Thank you both for your fast answers.

The additional entries for the iptable works for me. Btw. thank you very much for your super easy to use script to setup a vpn server 👍 

Best regards
Willy
