### ISSUE TITLE
Unable to connect after adding new users to chap-secrets

### ISSUE THREAD

**Issue by mmocz** [hwdsl2/setup-ipsec-vpn#49]
Hi. thanks for a great script! I lately encountered an issue which i tried to solve, but with no success.

I finish the instalation and everything works fine with the first predefined user. But then if I edit the chap-secrets file, im unable to log in with any user. I have checked and tried everything - file permissions, file content for proper formating, restarted both services, rebooted and nothing.

If I edit your script before the installation with the users I need everything then works fine. But if I edit the chap-secrets file later, nothing works. Do you have any idea, what could i be doing wrong? Thanks a lot!

**Comment by hwdsl2** [comment]
@mmocz Please post your chap-secrets file, with sensitive info replaced by asterisks.

Also check the log for errors using commands:

service ipsec restart
grep pluto /var/log/auth.log

**Comment by mmocz** [comment]
I have no idea why, but the issue disappeared. I have done the same things I have done twice already, when the issue appeared, but now it miraculously works. Nevermind, Im sorry for bothering you.

Ever thought about adding a donate button? :)

**Comment by hwdsl2** [comment]
@mmocz I am glad that your issue has been resolved. Thanks for the offer but I currently don't have plans to accept donations.

**Comment by XPOTiFY** [comment]
Hey man, Thanks a lot for your hard work.
The script works perfectly however even if I add more users, only one user can connect.
Let's say, I have a Laptop and a Smartphone
When I connect the Laptop to my server, then the Smartphone won't connect!
When I connect the Smartphone to my server, then the Laptop won't connect!
As soon as I disconnect one of the devices, the other one will successfully connect.

I have followed your tutorial here:
[https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users.md
](url)

```
cat /etc/ipsec.secrets
X.X.X.X  %any  : PSK "my_PSK"

```
```
cat /etc/ppp/chap-secrets
# Secrets for authentication using CHAP
# client  server  secret  IP addresses
"first_user" l2tpd "password_for_first_user" *
"second_user"  l2tpd  "password_for_second_user"  *

```
```cat /etc/ipsec.d/passwd
first_user:first_user_hash:xauth-psk
second_user:second_user_hash:xauth-psk

```
I have created the second_user_hash using your command -> `openssl passwd -1 "password_for_second_user"`

Server OS: Debian 8 Kernel 3.16.0-4
Nothing else is installed on the server, the OS is completely new.

Thanks a lot.

**Comment by hwdsl2** [comment]
@XPOTiFY Hello! Unfortunately due to a current limitation of the IPsec (IKEv1) protocol, multiple devices behind the same NAT (e.g. home router) cannot be connected to the VPN server simultaneously, i.e. the devices can only connect one at a time. You may want to instead try OpenVPN or IKEv2, which does not have such limitation. Some example repos can be found under "See Also" in the project README.
