### ISSUE TITLE
Error: Wireless interface 'wlan0' detected. DO NOT run this script on your PC or Mac!

### ISSUE THREAD

**Issue by luckzhiwei** [hwdsl2/setup-ipsec-vpn#492]
Hello Lin Song.
When I try to run the "sudo sh vpnsetup.sh" on my PC, the error appear.
My  environment is Ubuntu 16.04.
I use the ifconfig to see my network adapter is "wlan0".
Should I change the network adapter name to solve the problem?
Thank you

**Comment by hwdsl2** [comment]
@luckzhiwei Hello! The VPN setup scripts should NOT be run on your PC or Mac, it should only be used on a dedicated server or VPS. There are checks that try to prevent this.

If you know what you are doing and are certain that you want to run this on a server at home, however, you can comment out these lines [1] before running the script.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/vpnsetup.sh#L79-L83

**Comment by luckzhiwei** [comment]
Sorry,I misunderstand your article and I do this on my laptops.
Thank you very much

**Comment by luckzhiwei** [comment]
@hwdsl2 I read your readme.md. You suggest running this script on the Amazon EC2 or VPS.Can I run the script on the aliyun ECS?

**Comment by hwdsl2** [comment]
@luckzhiwei Yes, you can use any server provider you like. Be sure to open UDP ports 500 and 4500 for the VPN. For Aliyun, see #433.

**Comment by luckzhiwei** [comment]
Thank you!
