### ISSUE TITLE
how to use L2TP without PSK?

### ISSUE THREAD

**Issue by herozhang** [hwdsl2/setup-ipsec-vpn#493]
because my wifi device can not setup VPN at IPsec/L2TP with PSK...

**Comment by iamybj** [comment]
turn to shadowsocks.

**Comment by hwdsl2** [comment]
@herozhang Hello! Using L2TP without IPsec is not supported because traffic is not encrypted at all, which defeats the purpose of using a VPN.

**Comment by baguswahyu** [comment]
> @herozhang Hello! Using L2TP without IPsec is not supported because traffic is not encrypted at all, which defeats the purpose of using a VPN.

any trick to make this happen?
my openwrt router not support psk input for l2tp. it will be great if i can connect to l2tp server with or without psk. if without psk, i already accept it will have security issue

**Comment by chasays** [comment]
https://lowendtalk.com/discussion/144539/setup-l2tp-vpn-on-centos-ubuntu-without-pre-shared-key
1. you can use port 1701
2. use openvpn instead of xxx

**Comment by chasays** [comment]
https://lowendtalk.com/discussion/144539/setup-l2tp-vpn-on-centos-ubuntu-without-pre-shared-key
1. you can use port 1701
2. use openvpn instead of xxx
