### ISSUE TITLE
CentOS 7: certutil -s: improperly formatted name: "O=IKEv2 VPN,CN="

### ISSUE THREAD

**Issue by Killuacrow** [hwdsl2/setup-ipsec-vpn#494]
Hi, i'm in this page https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md
at
Note: If you specified the server's DNS name (instead of its IP address) in step 1 above, you must replace --extSAN "ip:$PUBLIC_IP,dns:$PUBLIC_IP" in the command below with --extSAN "dns:$PUBLIC_IP".
the code is

certutil -z <(head -c 1024 /dev/urandom) \
  -S -c "IKEv2 VPN CA" -n "$PUBLIC_IP" \
  -s "O=IKEv2 VPN,CN=$PUBLIC_IP" \
  -k rsa -g 4096 -v 36 \
  -d sql:/etc/ipsec.d -t ",," \
  --keyUsage digitalSignature,keyEncipherment \
  --extKeyUsage serverAuth \
  --extSAN "ip:$PUBLIC_IP,dns:$PUBLIC_IP"

when i paste it in the bash, it tell me an error

certutil -s: improperly formatted name: "O=IKEv2 VPN,CN="

Can you help me, please? Thanks in Advance!

**Comment by hwdsl2** [comment]
@Killuacrow Hello! Your PUBLIC_IP variable is empty. In Step 1 you save your server’s IP address or DNS name in that variable:

```
PUBLIC_IP=$(wget -t 3 -T 15 -qO- http://ipv4.icanhazip.com)
```

Please remove the entire “conn ikev2-cp” section from /etc/ipsec.conf, then restart from Step 1 of the tutorial. Make sure you put your server’s public IP or DNS name in the variable PUBLIC_IP.
