### ISSUE TITLE
IOS 连接问题

### ISSUE THREAD

**Issue by subdance** [hwdsl2/setup-ipsec-vpn#495]
首先十分感谢！
我在使用ios链接搭建的vpn时，有时候会出现：
1.服务器无响应。多次尝试后可以连上
2.需要输入密码才能连接，点击取消链接后再尝试就可以直接连接。
我是用的是谷歌云。

**Comment by hwdsl2** [comment]
@subdance 你好！根据你的描述，如果有时可以连接有时不能，很可能是被防火墙干扰或屏蔽了。建议你换用其它解决方案，比如 Shadowsocks。
