### ISSUE TITLE
can not access vpn server's port though vpn

### ISSUE THREAD

**Issue by jasstionzyf** [hwdsl2/setup-ipsec-vpn#496]
very thanks for your share!  
i can successfully installed openvpn using your code.
but only one problem:  i have several service running on vpn server itself,   so i try to access those service though vpn server from my client machine,  but it does not work.

if i access others machines (locate at same network as vpn server) through vpn server, 
it works well

**Comment by hwdsl2** [comment]
@jasstionzyf Hello! I think you mean IPsec VPN, not OpenVPN. For accessing services on your VPN server itself while connected using IPsec/L2TP mode, use its internal IP address 192.168.42.1.

**Comment by jasstionzyf** [comment]
@hwdsl2  thanks for your so quick reply!
actually i use the internal ip address
