### ISSUE TITLE
On-demand VPN for iOS

### ISSUE THREAD

**Issue by NightMachinary** [hwdsl2/setup-ipsec-vpn#497]
How do we make the vpn connect on-demand? Without this feature, I need to constantly enable the vpn manually.

**Comment by hwdsl2** [comment]
@NightMachinary Hello! Enabling the on-demand VPN feature (hidden from UI) requires generating and importing `.mobileconfig`, which is not currently supported by this project. However, you may be able to do that yourself by using Apple Configurator [1] to create the VPN profile with this setting enables, then export and import to your iOS device.

[1] https://www.howtogeek.com/216137/create-a-configuration-profile-to-simplify-vpn-setup-on-iphones-and-ipads/
