### ISSUE TITLE
Help: hao to set the IPtables for clients to ssh and ping

### ISSUE THREAD

**Issue by bindaolh** [hwdsl2/setup-ipsec-vpn#499]
i sucessful set the vpn-server with docker，
my PC A and PC B could connect to vpn-server,
PC A:  IP:192.168.5.201 GW:192.168.5.1 
PC B:  IP:192.168.7.175 GW:192.168.7.254
now PC A get the pppo IP: 192.168.42.10
PC B get the pppo IP: 192.168.42.11
my question is hao to set the iptable ,that i can use PC A ping PC B and use PC A ssh PC B 
or use oher way
thankyou

**Comment by hwdsl2** [comment]
@bindaolh Hello! In the default configuration set by the VPN setup scripts, traffic among VPN clients are allowed. For your use case, make sure that you use PC A and PC B's internal VPN IPs (192.168.42.10 and 192.168.42.11) to connect to each other.

In addition, you must add the appropriate firewall rules in the "Windows Firewall with Advanced Configuration" tool in both PC A and PC B to allow incoming traffic from each other (e.g. allow from subnet 192.168.42.0/24). Windows Firewall would block your SSH traffic if you don't do this step.

**Comment by bindaolh** [comment]
ok the clients PC A and PC B are both ubuntu,not the windows,i show you the iptables, 
Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
21487 2245K DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  *      ppp+    192.168.7.0/24       0.0.0.0/0           
    0     0 ACCEPT     all  --  *      ppp+    192.168.5.0/24       0.0.0.0/0           
21487 2245K DOCKER-ISOLATION-STAGE-1  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
 9303  873K ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
  986 58536 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
11202 1313K ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0           
Chain PREROUTING (policy ACCEPT 14503 packets, 615K bytes)
 pkts bytes target     prot opt in     out     source               destination         
65811 2874K DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 14477 packets, 614K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 12 packets, 1017 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 329 packets, 19429 bytes)
 pkts bytes target     prot opt in     out     source               destination         
   66  3976 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0           
    0     0 MASQUERADE  tcp  --  *      *       172.17.0.3           172.17.0.3           tcp dpt:443
    0     0 MASQUERADE  tcp  --  *      *       172.17.0.3           172.17.0.3           tcp dpt:80
    0     0 MASQUERADE  udp  --  *      *       172.17.0.2           172.17.0.2           udp dpt:4500
    0     0 MASQUERADE  udp  --  *      *       172.17.0.2           172.17.0.2           udp dpt:500

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0           
   61  3256 DNAT       tcp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:443 to:172.17.0.3:443
  268 14292 DNAT       tcp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80 to:172.17.0.3:80
    3  1108 DNAT       udp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            udp dpt:4500 to:172.17.0.2:4500
    3   684 DNAT       udp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            udp dpt:500 to:172.17.0.2:500

**Comment by bindaolh** [comment]
my PC A set the ufw
root@network:/home/dahao# sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
Anywhere                   ALLOW       192.168.42.0/24           
22                         ALLOW       Anywhere                  
22 (v6)                    ALLOW       Anywhere (v6)    

my PC B ufw is disable , use PC B ping PC A
root@network:/home/dahao# ping 192.168.42.1
PING 192.168.42.1 (192.168.42.1) 56(84) bytes of data.
64 bytes from 192.168.42.1: icmp_seq=15 ttl=64 time=48.6 ms
64 bytes from 192.168.42.1: icmp_seq=17 ttl=64 time=48.6 ms
64 bytes from 192.168.42.1: icmp_seq=19 ttl=64 time=48.7 ms
64 bytes from 192.168.42.1: icmp_seq=23 ttl=64 time=48.7 ms
^C
--- 192.168.42.1 ping statistics ---
23 packets transmitted, 4 received, 82% packet loss, time 22100ms
rtt min/avg/max/mdev = 48.667/48.723/48.791/0.051 ms
root@network:/home/dahao# ping 192.168.42.11
PING 192.168.42.11 (192.168.42.11) 56(84) bytes of data.

it can not work

**Comment by hwdsl2** [comment]
@bindaolh Hello! Unfortunately I cannot help you troubleshoot your Ubuntu’s ufw firewall settings. As I said earlier, the VPN server does not block traffic among VPN clients in the default configuration. You’ll need to troubleshoot further yourself to see where the traffic gets dropped (most likely it is your client’s firewall).

**Comment by bindaolh** [comment]
yes,i stop the ufw use iptables,show the iptables rules
*filter
:INPUT DROP [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:syn-flood - [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -s 127.0.0.1/32 -d 127.0.0.1/32 -j ACCEPT
-A INPUT -s 192.168.42.0/24 -d 192.168.42.0/24 -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 443 -j ACCEPT
-A INPUT -p icmp -m limit --limit 100/sec --limit-burst 100 -j ACCEPT
-A INPUT -p icmp -m limit --limit 1/s --limit-burst 10 -j ACCEPT
-A INPUT -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -j syn-flood
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A syn-flood -p tcp -m limit --limit 3/sec --limit-burst 6 -j RETURN
-A syn-flood -j REJECT --reject-with icmp-port-unreachable
COMMIT
~       

what is wrong with it? thanks!
