### ISSUE TITLE
Not connected using Windows client

### ISSUE THREAD

**Issue by yahya09** [hwdsl2/setup-ipsec-vpn#5]
Hi, I want to thank you for making this super easy vpn server installation for linux. However, I followed these instruction to setup in my DigitalOcean droplet using Centos 6.7, but couldn't connect to it from my Windows client. The installation runs fine, after fresh install from new droplet I followed the instruction as it says and no problem found.

Then I tried to connect using my WIndows 7 with same credential I entered in install script. I have tried to connect using windows and android with same configuration (l2tp/ipsec with psk) but to no avail. The windows error says the remote server didn't responded (error 809). I don't know where to look or what to do to trace the problem, because your magic script do all these stuff automatically, hehe. Do you have any suggestions?

Thank you.

**Comment by yahya09** [comment]
Ups sorry, didn't read further your instruction after installation.

**Comment by hwdsl2** [comment]
Hi @yahya09 You are welcome. Please follow the instructions in [1] to add the necessary registry key in Windows and reboot your computer. This is mentioned in the important notes [2].

Edit: Looks like you've resolved the issue. Great!

[1] https://documentation.meraki.com/MX-Z/Client_VPN/Troubleshooting_Client_VPN#Windows_Error_809    
[2] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes

**Comment by yahya09** [comment]
Yes, I was careless not to read "Important Notes" just below the install instruction.
Sorry to bother you, I really appreciate your reply.

**Comment by hwdsl2** [comment]
Not a problem. I am glad to help!
