### ISSUE TITLE
can't connect from Vodafone egypt

### ISSUE THREAD

**Issue by Saugjunkie** [hwdsl2/setup-ipsec-vpn#500]
Hello actually I am in Egypt to make holiday but I can't connect to my vpn server. 

I have tested android 8 and windows 8.1

**Comment by hwdsl2** [comment]
@Saugjunkie Hello! Does your VPN server work fine before? Check the logs for errors using these steps [1] and post details, with IP redacted.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps

**Comment by hwdsl2** [comment]
@Saugjunkie If your VPN previously worked fine but you are unable to connect now, it could be blocked by censorship. You may want to try alternative tools such as Shadowsocks [1]. Alternatively, check the VPN logs for errors (as mentioned above).

[1] https://shadowsocks.org
