### ISSUE TITLE
在ubuntu gui界面当中如何使用客户端去连接服务器

### ISSUE THREAD

**Issue by vanshu** [hwdsl2/setup-ipsec-vpn#502]
服务器为centos 已经配置好了，使用macos作为客户端登录成功,但是在ubuntu界面当中如何连接服务器文档没有讲到.

**Comment by hwdsl2** [comment]
@vanshu 你好！暂时不支持 Ubuntu GUI 界面连接 VPN。

**Comment by vanshu** [comment]
你好， 我现在需要找把ubuntu当作客户端去连centos 的服务端机器，刚刚你有说gui界面不支持，但是支持客户端命令行配置去连接服务端吗？我通过文档查看,发现这个命令行配置客户端的代码貌似是在配置服务端.
linux-vpn-clients 
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#linux-vpn-clients

**Comment by hwdsl2** [comment]
@vanshu 你好！你说的这个链接是在命令行配置 Linux 客户端去连接服务端的。你可以参见该文档对应的中文文档（点最上面的语言链接）。
