### ISSUE TITLE
Works in iOS but the MacOS and Windows not work.

### ISSUE THREAD

**Issue by icetee** [hwdsl2/setup-ipsec-vpn#503]
Hi!

I can't join, can I help me?

I read all issues, Wiki etc, but no established connection on MacOS and Windows 10, but the iOS works. I try add DNS (8.8.8.8, 8.8.4.4), checked All trafix on MacOS.

I tail the syslog `sudo tail -f /var/log/syslog | grep xl2tpd`, but no response, iOS:
```
...
Connection established to XY, 54674.  Local: 45482, Remote: 2 (ref=0/0).  LNS session is 'default'
...
```

I try Wifi (UPC), 4G (Telekom). The `/usr/bin/nc -uvw5 portquiz.net` (4500, 1701, 500) ports successed.

My server is a Droplet from Frankfurt (DO) and I connect from Hungary.

**Comment by icetee** [comment]
It's work type Cisco:

https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md#os-x

**Comment by hwdsl2** [comment]
@icetee Glad to know it works in Cisco IPsec mode. For IPsec/L2TP you may check the logs for errors using these steps [1]. More likely, you might have a typo in your server IP, PSK or password when configuring your VPN clients.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps

**Comment by hwdsl2** [comment]
@icetee Most likely a client problem. If no new logs after connecting, then the connection attempt did not reach your VPN server.

**Comment by icetee** [comment]
I log my client connection:

`sudo tail -f /private/var/log/ppp`

The result:

```
Fri Dec  7 17:34:31 2018 : publish_entry SCDSet() failed: Success!
Fri Dec  7 17:34:31 2018 : publish_entry SCDSet() failed: Success!
Fri Dec  7 17:34:31 2018 : l2tp_get_router_address
Fri Dec  7 17:34:31 2018 : l2tp_get_router_address 10.0.0.1 from dict 1
Fri Dec  7 17:34:31 2018 : L2TP connecting to server 'XXX.XXX.XXX.XXX' (207.154.227.150)...
Fri Dec  7 17:34:31 2018 : L2TP sent SCCRQ
Fri Dec  7 17:34:51 2018 : L2TP cannot connect to the server
```
