### ISSUE TITLE
clarification

### ISSUE THREAD

**Issue by tdwong** [hwdsl2/setup-ipsec-vpn#507]
It will be nice to clarify in the document that whenever `Your VPN Server IP` is referred, it really means the `docker host`'s IP address (instead of the Server IP address found in `docker logs ipsec-vpn-server` output).

**Comment by hwdsl2** [comment]
@tdwong Hello! Unless you are connecting a VPN client from within your Docker host's local network, the `Your VPN Server IP` displayed in `docker logs ipsec-vpn-server` (which is the detected public IP of your Docker host) should always match your Docker host's IP address. Can you share some details of your setup that leads to a mismatch of these IPs?

**Comment by hwdsl2** [comment]
@tdwong Closing due to the reasons above. If you have further details to share, feel free to comment. Thanks!
