### ISSUE TITLE
Is there any way to bind ip address to user?

### ISSUE THREAD

**Issue by mrPsycho** [hwdsl2/setup-ipsec-vpn#508]
hello!

is there any solution in your amazing script to bind virtual IP to user? 
so everytime user connects - it gets the same IP.

**Comment by hwdsl2** [comment]
@mrPsycho Hello! For binding virtual IPs to users, please try the method in these comments [1].

[1] https://gist.github.com/hwdsl2/9030462#gistcomment-1988052

**Comment by mrPsycho** [comment]
ok, thanks a lot
