### ISSUE TITLE
路由器上配置VPN不成功，如何调整server的设置呢？

### ISSUE THREAD

**Issue by salamander-mh** [hwdsl2/setup-ipsec-vpn#511]
路由器支持` IPsec/L2TP`

应该是要配置成站点到站点

**Comment by hwdsl2** [comment]
@salamander-mh 你好！检查一下你的服务器上 Libreswan (IPsec) 和 xl2tpd 日志 [1]，看看是否有错误。站点到站点 VPN 超出了本项目范围。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E9%A2%9D%E5%A4%96%E7%9A%84%E6%AD%A5%E9%AA%A4

**Comment by salamander-mh** [comment]
@hwdsl2  如果我用`IPsec/XAuth`模式
是不是只用调整客户端的配置就可以了？？

**Comment by hwdsl2** [comment]
@salamander-mh 是的，但是你的客户端必须支持 `IPsec/XAuth` 模式才可以用。

**Comment by salamander-mh** [comment]
@hwdsl2  我是用Mac OS X连的，但是一直报错`服务器没有响应`
我在linux用`vpnc`，也是一直提示
```
vpnc: no response from target
```
但是我用IPsec/L2TP 模式是可以连上的

**Comment by hwdsl2** [comment]
@salamander-mh vpnc 使用 aggressive mode，脚本不支持。具体请搜索Issue。macOS 应该可以连。还有问题可发邮件。
