### ISSUE TITLE
Block concurrent connections for the same user

### ISSUE THREAD

**Issue by sudanking** [hwdsl2/setup-ipsec-vpn#512]
How to Block concurrent connections for the same user. I can see that one user can login more than once at the same time.

**Comment by hwdsl2** [comment]
@sudanking Hello! As far as I know there is no easy way to limit concurrent connections for each user.

**Comment by letoams** [comment]
On Wed, 26 Dec 2018, Sudanking wrote:

>       On Wed, 26 Dec 2018, Lin Song wrote: @sudanking Hello! As far as I know there is no easy way to limit concurrent connections for each user.
>       Yeah, it requires tracking users, often across multiple VPN servers. So that kind of work is usually done by the pam interface. For IKEv1 based connections, you can use the pam authentication
>       method such as pam_url via xauthby=pam. It will then handle username and password. For IKEv2, you can use pam-authorize=yes and it will also use the pam method, but only for the username (not
>       password). Both methodes require that your backend knows the state of online users. Usually people track this with changes to the _updown.netkey script that tells the backend servers when a user
>       connects and disconnects. Such script then usually also reports the traffic used by that user. The script should be non-blocking as to not delay the pluto daemon. For an example, see the
>       updown-example from the contrib/ directory. https://github.com/libreswan/libreswan/tree/master/contrib/updown-example Paul
> 
> Thanks Paul for your explanation. but I don't think that is applicable to L2TP/IPSEC.... right?

For L2TP, it is basically limited by the ppp policy (eg pppd). To
prevent simultanious users there, one typically also uses an accounting
system like RADIUS or DIAMETER, and pppd requests those systems for
authorization and those backends will then reject simultanious users.

Paul

**Comment by sudanking** [comment]
thanks Paul for your help.... Appreciated.
