### ISSUE TITLE
Do not set default gateway

### ISSUE THREAD

**Issue by rysi3k** [hwdsl2/setup-ipsec-vpn#514]
Hello,
I want only to access VPN resources when connected to VPN. I do not need to forward all traffic though VPN, how to achive this?
Currently looks like default route is set when connecting and all traffic goes though server.

Regards

**Comment by letoams** [comment]
On Thu, 3 Jan 2019, rysi3k wrote:

> I want only to access VPN resources when connected to VPN. I do not need to forward all traffic though VPN, how to achive this?
> Currently looks like default route is set when connecting and all traffic goes though server.

Change rightsubnet=0.0.0.0/0 to be just the range you want to connect to
at the VPN server.

Paul

**Comment by hwdsl2** [comment]
Thanks @letoams!

@rysi3k Use IPsec/XAuth mode and edit /etc/ipsec.conf. Change leftsubnet to just the range you want to go through the VPN server. Then restart IPsec service.

**Comment by rysi3k** [comment]
Hello @hwdsl2 @letoams 
I tried to add leftsubnet or rightsubnet to xauth and l2tp config but non of these works as I excepted. 

My config:
`version 2.0
config setup
  virtual-private=%v4:10.0.0.0/8,%v4:172.16.0.0/12,%v4:!10.8.0.0/24,%v4:!10.9.0.0/24
  protostack=netkey
  interfaces=%defaultroute
  uniqueids=no
conn shared
  left=%defaultroute
  leftid=X.X.X.X
  right=%any
  encapsulation=yes
  authby=secret
  pfs=no
  rekey=no
  keyingtries=5
  dpddelay=30
  dpdtimeout=120
  dpdaction=clear
  ike=aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1,aes256-sha2;modp1024,aes128-sha1;modp1024
  phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes256-sha2_512,aes128-sha2,aes256-sha2
  sha2-truncbug=yes
conn l2tp-psk
  auto=add
  leftprotoport=17/1701
  rightprotoport=17/%any
  rightsubnet=10.8.0.0/24
  type=transport
  phase2=esp
  also=shared

conn xauth-psk
  auto=add
  leftsubnet=10.9.0.0/0
  rightsubnet=10.9.0.0/0
  rightaddresspool=10.9.0.2-10.9.0.250
  modecfgdns="8.8.8.8 8.8.4.4"
  leftxauthserver=yes
  rightxauthclient=yes
  leftmodecfgserver=yes
  rightmodecfgclient=yes
  modecfgpull=yes
  xauthby=file
  ike-frag=yes
  ikev2=never
  cisco-unity=yes
  also=shared`

In iptables i have:
`# Generated by iptables-save v1.6.0 on Fri Jan  4 11:58:22 2019
*filter
:INPUT DROP [4661:264849]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [463289:727875223]
-A INPUT -p udp -m udp --dport 1701 -m policy --dir in --pol none -j DROP
-A INPUT -m conntrack --ctstate INVALID -j DROP
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p udp -m multiport --dports 500,4500 -j ACCEPT
-A INPUT -p udp -m udp --dport 1701 -m policy --dir in --pol ipsec -j ACCEPT
-A INPUT -p udp -m udp --dport 1701 -j DROP
-A INPUT -i br0 -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -s 192.168.100.0/24 -p tcp -m tcp --dport 3306 -j ACCEPT
-A INPUT -i br0 -p icmp -j ACCEPT
-A INPUT -i br0 -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -i tun0 -j ACCEPT
-A INPUT -i ppp+ -j ACCEPT
-A FORWARD -m conntrack --ctstate INVALID -j DROP
-A FORWARD -i br0 -o ppp+ -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i ppp+ -o br0 -j ACCEPT
-A FORWARD -s 10.8.0.0/24 -d 10.8.0.0/24 -i ppp+ -o ppp+ -j ACCEPT
-A FORWARD -d 10.9.0.0/24 -i br0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.9.0.0/24 -o br0 -j ACCEPT
-A FORWARD -i br0 -o br0 -j ACCEPT
-A FORWARD -j DROP
COMMIT
# Completed on Fri Jan  4 11:58:22 2019
# Generated by iptables-save v1.6.0 on Fri Jan  4 11:58:22 2019
*nat
:PREROUTING ACCEPT [55533:3227913]
:INPUT ACCEPT [39526:1723750]
:OUTPUT ACCEPT [12146:731741]
:POSTROUTING ACCEPT [2611:179604]
-A POSTROUTING -s 192.168.100.0/24 -j MASQUERADE
COMMIT
# Completed on Fri Jan  4 11:58:22 2019`

My external interface is br0 and i have lxc containers in subnet 192.168.100.0/24 with NAT which must be not touched. 

Thanks for help.

Regards

**Comment by letoams** [comment]
> On Jan 4, 2019, at 06:03, rysi3k <notifications@github.com> wrote:
> 
> Hello @hwdsl2 @letoams
> I tried to add leftsubnet or rightsubnet to xauth and l2tp config but non of these works as I excepted.
> 

For L2TP this is usually only done on the client side by deselecting the “send all traffic via VPN” option. 
> My config:
> 
> sha2-truncbug=yes
> 
Do you only have android clients? It breaks non-android clients if they ever end up selecting sha2_256

> conn l2tp-psk
> auto=add
> leftprotoport=17/1701
> rightprotoport=17/%any
> rightsubnet=10.8.0.0/24
> type=transport
> phase2=esp
> also=shared
> 
That should be leftsubnet= in your case.
> conn xauth-psk
> auto=add
> leftsubnet=10.9.0.0/0
> rightsubnet=10.9.0.0/0
> rightaddresspool=10.9.0.2-10.9.0.250
> 

Same here, remove rightsubnet

Paul

**Comment by hwdsl2** [comment]
@rysi3k For IPsec/XAuth mode, the VPN server does not have an assigned internal IP. I'm not aware of any workaround. You'll need to use IPsec/L2TP mode for the use case you mentioned.

**Comment by rysi3k** [comment]
@hwdsl2 @letoams how about assigning static ip for VPN clients? It is possible?

**Comment by hwdsl2** [comment]
@rysi3k For static IPs please refer to these comments [1].

[1] https://gist.github.com/hwdsl2/9030462#gistcomment-1988052
