### ISSUE TITLE
您好，手机和win7还有mac能连接，但是唯独win10不能用

### ISSUE THREAD

**Issue by Alinlaban** [hwdsl2/setup-ipsec-vpn#517]
我按照您的提示我把注册表什么的都配置了，但是还是不行，我的电脑系统版本是为win10 企业版 64位（10.0，版本 17134）

**Comment by hwdsl2** [comment]
@Alinlaban 你好！运行一下命令检查服务器上的日志，然后尝试连接你的win10客户端。把新的日志贴上来，可隐去IP。
```
# Ubuntu/Debian
tail -F /var/log/auth.log /var/log/syslog | grep -e xl2tpd -e pluto
# CentOS/RHEL
tail -F /var/log/secure /var/log/messages | grep -e xl2tpd -e pluto
```

**Comment by Alinlaban** [comment]
没有日志出来

**Comment by Alinlaban** [comment]
就是客户端报错了：无法建立计算机与vpn服务器之间的网络连接，因为远程服务器没有响应。这可能。。。。等等这些错的字样

**Comment by hwdsl2** [comment]
@Alinlaban 如果没有新的日志，那就是客户端的连接尝试没有到达你的服务器…你需要自己进一步故障排除一下为什么。如果你有新的日志可以继续在这里留言。

**Comment by Alinlaban** [comment]
谢谢

**Comment by Alinlaban** [comment]
应该是我的电脑原因，我在检查一下
