### ISSUE TITLE
Rebooting / Restarting services

### ISSUE THREAD

**Issue by cdlenfert** [hwdsl2/setup-ipsec-vpn#519]
I had a VPN running well on raspberry pi 3.  I’m also using piehole on the same device. And hoping to allow VPN users to take advantage of the ad blocking the piehole provides I tried setting the DNS address to the raspberry pie’s address and rebooted the server.  The VPN is no longer working. I’m remote and will have to wait to troubleshoot. But should thing come back online automatically? I’m running Debian 9.

**Comment by hwdsl2** [comment]
@cdlenfert Closing as it is not an issue with the VPN setup scripts. You may continue to comment here if you have new information.

**Comment by cdlenfert** [comment]
Thank you for the response and closing this ticket. It was indeed a reboot issue for me, but after unplugging/replugging all of my expected services came back online. You are correct it's not on the VPN scripts.

**Comment by hwdsl2** [comment]
@cdlenfert Thank you for the update. Did you find out what caused the connection issue?

**Comment by cdlenfert** [comment]
@hwdsl2 I did not, and things were working well for a while. Today the VPN connection failed again and a soft reboot via `systemctl reboot` didn't bring it back up, though other remote services like my Plex Media Server on the Pi were available. IP hasn't changed and shouldn't due to DHCP reservation, and PiHole that I'm running on the device continues to work.

**Comment by hwdsl2** [comment]
@cdlenfert Try: `service ipsec restart; service xl2tpd restart`. If still not working, you may also check the Libreswan (IPsec) and xl2tpd logs for errors [1].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps

**Comment by cdlenfert** [comment]
@hwdsl2 Thank you very much! I'll give those a try next time. In this case the reason I was unable to connect was an external IP address change. I need to get a better dynamic DNS setup in place, but had good luck with my IP staying the same for a full year. Go figure! I read on another old resolved issue that even if external IP changes, the VPN is supposed to still work as long as you change the IP address on the client side (the device that's making the connection). In my case that didn't help and I had to manually change the leftid parameter in etc/ipsec.conf and reboot the Pi (since I wasn't yet aware of the commands you mention above.. poor reading on my part). Can you confirm if I should have been able to connect once I changed the client side IP address for the VPN without a config change and service restart/reboot?  Thanks!

**Comment by hwdsl2** [comment]
@cdlenfert You’re welcome. Normally, after your server’s public IP changes, if you simply change the client side IP address for the VPN to match, it should continue to work. You can alternatively put your dynamic DNS hostname there. 

However, if your Raspberry Pi’s private IP changes (e.g. due to router reboot), you’ll need to restart the IPsec service and also reconfigure the port forwarding on your router. Hence it is a good idea to reserve a static IP in the router’s DHCP settings.

**Comment by cdlenfert** [comment]
@hwdsl2 Yes, I have a static IP via a DHCP reservation on the Pi so that piece of the puzzle is not changing, my public IP address did change, however when changing the client device's settings to use the VPNs new public IP, the client device was still unable to connect. Only changing the `leftid` parameter in the `/etc/ipsec.conf` file to use the new public IP and rebooting the Pi allowed me to reconnect. Next time I can't connect I'll double check that that is the case (if I haven't set up a better dynamic DNS solution by then). Thanks again
