### ISSUE TITLE
raduis server

### ISSUE THREAD

**Issue by sajadonline** [hwdsl2/setup-ipsec-vpn#520]
hi
how can connect this l2tp server to ibsng raduis server ?

**Comment by letoams** [comment]
For L2TP, pppd is used so you can configure pppd with pam that uses a radius backend

**Comment by letoams** [comment]
I don’t understand your question. If you use L2TP/IPsec, then ipsec also uses pppd so then you can use radius for user/password

**Comment by hwdsl2** [comment]
Thanks @letoams!

@sajadonline Using a Radius server is outside the scope of this project. Please refer to [1] and ask further questions on the Libreswan users mailing list [2].

[1] https://libreswan.org/wiki/VPN_server_for_remote_clients_using_IKEv1_with_L2TP
[2] https://lists.libreswan.org/mailman/listinfo/swan
