### ISSUE TITLE
How to open a port?

### ISSUE THREAD

**Issue by turbozapekanka** [hwdsl2/setup-ipsec-vpn#522]
I need a port to be open and all connections forwarded to a VPN client.
How can I do this?
I guess UPnP will not work as it would without VPN connection

**Comment by hwdsl2** [comment]
@turbozapekanka To open a port for a VPN client, add IPTables rules in your FORWARD chain. For example, for TCP port 80:
```
iptables -I FORWARD 2 -i eth0 -o ppp+ -p tcp --dport 80 -j ACCEPT
iptables -I FORWARD 2 -i eth0 -d 192.168.43.0/24 -p tcp --dport 80 -j ACCEPT
```

Note that this will open the port for ALL your VPN clients. You may want to further narrow it down by IP address if you want. To make these rules persist after reboot, add it to your `/etc/iptables.rules` and/or `/etc/iptables/rules.v4` (if exists).

**Comment by turbozapekanka** [comment]
Thanks,
This seem to work.
Not sure what your second line is for, these two worked for me:

iptables -I FORWARD 2 -i eth0 -o ppp+ -p tcp --dport 80 -j ACCEPT
iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 80 -j DNAT --to 192.168.42.10:80
