### ISSUE TITLE
XL2TP拨号不走IPSEC加密通道，嵌入式linux

### ISSUE THREAD

**Issue by junixwu** [hwdsl2/setup-ipsec-vpn#523]
您好，服务器端我是用您的脚本，客户端的配置我也是参考您给出的strongswan的配置方法。用PC和手机都可以通过L2TP/IPSEC方式做VPN。但是我的终端设备，ARM cortexA7,内核3.18.20，交叉编译strongswan和xl2tp。ipsec通道建立成功。xl2tp拨号没有走加密通道，还是直接自己去拨号了，服务器不响应。一直超时。能否帮忙看一下。为何xl2tp不走ipsec通道呢？怎么才能让xl2tp经过ipsec再送给服务器？多谢

root@mdm9607-perf:/usrdata# ipsec status 
Security Associations (1 up, 0 connecting):
       myvpn[2]: ESTABLISHED 7 minutes ago, 10.124.47.194[10.124.47.194]...47.93.13.190[47.93.13.190]
       myvpn{4}:  REKEYED, TRANSPORT, reqid 1, expires in 3 minutes
       myvpn{4}:   10.124.47.194/32[udp/l2f] === 47.93.13.190/32[udp/l2f]
       myvpn{5}:  INSTALLED, TRANSPORT, reqid 1, ESP in UDP SPIs: c2fe7693_i fc6e4633_o
       myvpn{5}:   10.124.47.194/32[udp/l2f] === 47.93.13.190/32[udp/l2f]
root@mdm9607-perf:/usrdata# echo "c myvpn" > /var/run/xl2tpd/l2tp-control 
root@mdm9607-perf:/usrdata# xl2tpd[1828]: get_call: allocating new tunnel for host 47.93.13.190, port 1701.
xl2tpd[1828]: Connecting to host 47.93.13.190, port 1701
xl2tpd[1828]: Maximum retries exceeded for tunnel 25394.  Closing.
xl2tpd[1828]: Connection 0 closed to 47.93.13.190, port 1701 (Timeout)
xl2tpd[1828]: Unable to deliver closing message for tunnel 25394. Destroying anyway.

**Comment by hwdsl2** [comment]
@junixwu 你好！你的 VPN 客户端设备我并不熟悉，建议你在 strongSwan 用户邮件列表 [1] 或其它相关论坛问一下。

[1] https://lists.strongswan.org/mailman/listinfo/users
