### ISSUE TITLE
Creating VPN Client for windows

### ISSUE THREAD

**Issue by berkayyildi** [hwdsl2/setup-ipsec-vpn#524]
Hello I am planning to create VPN client for Windows for your project.
Can you add URL of it to the cliens docs page when I create?
Thanks.

**Comment by hwdsl2** [comment]
@berkayyildi Hello! It is OK to mention this project but please note that Windows already has native VPN client for IPsec/L2TP and IKEv2.

**Comment by berkayyildi** [comment]
@hwdsl2 Hello! Yes you are right actually I am not talking about VPN Client from zero.
I just want to create gui to help user. (Because you know generally windows users do not like cmd commands) The gui help you to create VPN connection with one click (also it checks about Error_809) and user can watch status of connection and traffic usage on gui. Also I might be add feature install new vpn server on gui, already installation is so easy (thanks to you) App will just require ssh info then it will install vpn on server -> create vpn connection on windows ->connect it automatically. My aim is when user purchase new server, this gui will help them to connect new vpn server with one click.
