### ISSUE TITLE
up-client

### ISSUE THREAD

**Issue by sudanking** [hwdsl2/setup-ipsec-vpn#525]
my connection refused with the following log:

Feb  6 23:24:29.013623: "xauth-psk"[2] 37.245.163.154 #15: up-client output: sh: 1: ipsec: not found
Feb  6 23:24:29.013803: "xauth-psk"[2] 37.245.163.154 #15: up-client command exited with status 127

Any Idea??

**Comment by hwdsl2** [comment]
@sudanking Hello! Unfortunately I don't know. You'll need to provide more context on what you are trying to do (what is `up-client`?)

**Comment by sudanking** [comment]
I solve that by disable leftupdown with adding : 
leftupdown=""

**Comment by letoams** [comment]
It is very dangerous to call the IPsec command in updown, what is the call exactly?

But it should be in /use/sbin or /user/local/spin

Perhaps specify the full path in the call ?

**Comment by letoams** [comment]
Up-client is called automatically from pluto using the updown script (_updown.netkey)

**Comment by sudanking** [comment]
show in the log file that it run a default updown : 

Feb  7 00:03:28.782363: | running updown command "ipsec _updown" for verb up 
Feb  7 00:03:28.782367: | command executing up-client

but for some reason, outputs not completed ??!! as shown below : 

Feb  6 23:24:29.010195: | raw_eroute result=success
Feb  6 23:24:29.010199: | running updown command "ipsec _updown" for verb up 
Feb  6 23:24:29.010203: | command executing up-client
Feb  6 23:24:29.010210: | get_sa_info esp.62c4072@x.x.x.x
Feb  6 23:24:29.010233: | get_sa_info esp.2eedc18f@x.x.x.x
Feb  6 23:24:29.010254: | executing up-client: PLUTO_VERB='up-client' PLUTO_VERSION='2.0' PLUTO_CONNECTION='xauth-psk' PLUTO_INTERFACE='eth0' PLUTO_NEXT_HOP='x.x.x.x' PLUTO_ME='x.x.x.x' PLUTO_MY_ID='x.x.x.x' PLUTO_MY_CLIENT='0.0.0.0/0' PLUTO_MY_CLIENT_NET='0.0.0.0' PLUTO_MY_CLIENT_MASK='0.0.0.0' PLUTO_MY_PORT='0' PLUTO_MY_PROTOCOL='0' PLUTO_SA_REQID='16420' PLUTO_SA_TYPE='ESP' PLUTO_PEER='x.x.x.x' PLUTO_PEER_ID='10.17.227.14' PLUTO_PEER_CLIENT='192.168.43.10/32' PLUTO_PEER_CLIENT_NET='192.168.43.10' PLUTO_PEER_CLIENT_MASK='255.255.255.255' PLUTO_PEER_PORT='0' PLUTO_PEER_PROTOCOL='0' PLUTO_PEER_CA='' PLUTO_STACK='netkey' PLUTO_ADDTIME='1549491868' PLUTO_CONN_POLICY='PSK+ENCRYPT+TUNNEL+SHA2_TRUNCBUG+DONT_REKEY+XAUTH+MODECFG_PULL+IKEV1_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO' PLUTO_CONN_KIND='CK_INSTANCE' PLUTO_CONN_ADDRFAMILY='ipv4' XAUTH_FAILED=0 PLUTO_USERNAME='xxxxx' PLUTO_IS_PEER_CISCO='0' PLUTO_PEER_DNS_INFO='' PLUTO_PEER_DOMAIN_INFO='' PLUTO_PEER_BANNER='' PLUTO_CFG_SERVER='1' PLUTO_CFG_CLIENT='0
Feb  6 23:24:29.010259: | popen cmd is 1159 chars long
Feb  6 23:24:29.010262: | cmd(   0):PLUTO_VERB='up-client' PLUTO_VERSION='2.0' PLUTO_CONNECTION='xauth-psk' PLUTO_IN:
Feb  6 23:24:29.010265: | cmd(  80):TERFACE='eth0' PLUTO_NEXT_HOP='x.x.x.x' PLUTO_ME='x.x.x.x' PLUTO_M:
Feb  6 23:24:29.010268: | cmd( 160):Y_ID='x.x.x.x' PLUTO_MY_CLIENT='0.0.0.0/0' PLUTO_MY_CLIENT_NET='0.0.0.0' :
Feb  6 23:24:29.010271: | cmd( 240):PLUTO_MY_CLIENT_MASK='0.0.0.0' PLUTO_MY_PORT='0' PLUTO_MY_PROTOCOL='0' PLUTO_SA_:
Feb  6 23:24:29.010274: | cmd( 320):REQID='16420' PLUTO_SA_TYPE='ESP' PLUTO_PEER='x.x.x.x' PLUTO_PEER_ID='10.:
Feb  6 23:24:29.010276: | cmd( 400):17.227.14' PLUTO_PEER_CLIENT='192.168.43.10/32' PLUTO_PEER_CLIENT_NET='192.168.4:
Feb  6 23:24:29.010279: | cmd( 480):3.10' PLUTO_PEER_CLIENT_MASK='255.255.255.255' PLUTO_PEER_PORT='0' PLUTO_PEER_PR:
Feb  6 23:24:29.010282: | cmd( 560):OTOCOL='0' PLUTO_PEER_CA='' PLUTO_STACK='netkey' PLUTO_ADDTIME='1549491868' PLUT:
Feb  6 23:24:29.010285: | cmd( 640):O_CONN_POLICY='PSK+ENCRYPT+TUNNEL+SHA2_TRUNCBUG+DONT_REKEY+XAUTH+MODECFG_PULL+IK:
Feb  6 23:24:29.010287: | cmd( 720):EV1_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO' PLUTO_CONN_KIND='CK_INSTANCE' PLUTO:
Feb  6 23:24:29.010290: | cmd( 800):_CONN_ADDRFAMILY='ipv4' XAUTH_FAILED=0 PLUTO_USERNAME='xxxxx' PLUTO_IS_PEER_CISC:
Feb  6 23:24:29.010293: | cmd( 880):O='0' PLUTO_PEER_DNS_INFO='' PLUTO_PEER_DOMAIN_INFO='' PLUTO_PEER_BANNER='' PLUT:
Feb  6 23:24:29.010296: | cmd( 960):O_CFG_SERVER='1' PLUTO_CFG_CLIENT='0' PLUTO_NM_CONFIGURED='0' PLUTO_INBYTES='0' :
Feb  6 23:24:29.010299: | cmd(1040):PLUTO_OUTBYTES='0' VTI_IFACE='' VTI_ROUTING='no' VTI_SHARED='no' SPI_IN=0x62c407:
Feb  6 23:24:29.010301: | cmd(1120):2 SPI_OUT=0x2eedc18f ipsec _updown 2>&1:
Feb  6 23:24:29.013623: "xauth-psk"[2] x.x.x.x #15: up-client output: sh: 1: ipsec: not found
Feb  6 23:24:29.013803: "xauth-psk"[2] x.x.x.x #15: up-client command exited with status 127

**Comment by letoams** [comment]
On Wed, 6 Feb 2019, Sudanking wrote:

> show in the log file that it run a default updown :

> Feb 7 00:03:28.782363: | running updown command "ipsec _updown" for verb up

> Feb 6 23:24:29.013623: "xauth-psk"[2] x.x.x.x #15: up-client output: sh: 1: ipsec: not found

this indicates a compile time issue with setting paths. If this is
installed in /usr/local and /usr/local/sbin/ is not in the system path,
then issuing "ipsec" will fail. Possibly you can just link the
/usr/local/sbin/ipsec to /usr/sbin/ipsec to avoid the error?

Paul
