### ISSUE TITLE
IDir does not Match....

### ISSUE THREAD

**Issue by revillo81** [hwdsl2/setup-ipsec-vpn#526]
Thank you very much for your manual, it helped me a lot. Unfortunately I get an error message. Probably I have to change something in the configuration. Can anyone help me?

Greetings Oliver

Enclosed my situation:

_

root@raspberrypi:/home/pi# ipsec up myvpn
initiating Main Mode IKE_SA myvpn[1] to 176.XXX.XXX.XXX
generating ID_PROT request 0 [ SA V V V V V ]
sending packet: from 192.168.8.101[500] to 176.XXX.XXX.XXX[500] (180 bytes)
received packet: from 176.XXX.XXX.XXX[500] to 192.168.8.101[500] (136 bytes)
parsed ID_PROT response 0 [ SA V V V ]
received XAuth vendor ID
received DPD vendor ID
received NAT-T (RFC 3947) vendor ID
generating ID_PROT request 0 [ KE No NAT-D NAT-D ]
sending packet: from 192.168.8.101[500] to 176.XXX.XXX.XXX[500] (372 bytes)
received packet: from 176.XXX.XXX.XXX[500] to 192.168.8.101[500] (372 bytes)
parsed ID_PROT response 0 [ KE No NAT-D NAT-D ]
local host is behind NAT, sending keep alives
remote host is behind NAT
generating ID_PROT request 0 [ ID HASH N(INITIAL_CONTACT) ]
sending packet: from 192.168.8.101[4500] to 176.XXX.XXX.XXX[4500] (108 bytes)
received packet: from 176.XXX.XXX.XXX[4500] to 192.168.8.101[4500] (76 bytes)
parsed ID_PROT response 0 [ ID HASH ]
**IDir '172.16.1.254' does not match to 'vpn.mydomain.com'**
deleting IKE_SA myvpn[1] between 192.168.8.101[192.168.8.101]...176.XXX.XXX.XXX[%any]
sending DELETE for IKE_SA myvpn[1]
generating INFORMATIONAL_V1 request 3848907594 [ HASH D ]
sending packet: from 192.168.8.101[4500] to 176.XXX.XXX.XXX[4500] (92 bytes)
establishing connection 'myvpn' failed

_

CLIENT:

Internet-Router, Network 192.168.8.0/24
VPN-Client's IP: 192.168.8.101 (Raspberry-Pi, Strongswan)

SERVER:

**vpn.mydomain.com** = **176.XXX.XXX.XXX** = Example Domain/PublicIP of my Server

Internet Router = 172.16.1.1

VPN-Server is a USG-Pro4, 172.16.1.254

Office-Network = 192.168.1.0/24
VPN-Internal Network = 192.168.2.0/24

**Comment by letoams** [comment]
Tell the client to use a server id based on the name, not the ip. Similarly in the server, configured its own is as the name (both prefixed by @ to prevent it from being resolved as DNS.

Paul

**Comment by revillo81** [comment]
thanks, can you give me a hint, where i have to do this? sorry..i'm a newbie ;-)

It's something in here...?


```
# Sample VPN connections

conn %default
  ikelifetime=60m
  keylife=20m
  rekeymargin=3m
  keyingtries=1
  keyexchange=ikev1
  authby=secret
  ike=aes128-sha1-modp2048!
  esp=aes128-sha1-modp2048!

conn myvpn
  keyexchange=ikev1
  left=%defaultroute
  auto=add
  authby=secret
  type=transport
  leftprotoport=17/1701
  rightprotoport=17/1701
  right=vpn.mydomain.com
```

**Comment by hwdsl2** [comment]
Thanks @letoams!

@revillo81 Edit `/etc/ipsec.conf` on your VPN server. Find the line `leftid=...` and replace it with `leftid=@vpn.mydomain.com`, using your actual domain name prefixed by `@` and keep the line indented by two spaces. Save the file and run "service ipsec restart". Then re-connect your VPN client.
