### ISSUE TITLE
Wrap traffic over SSL

### ISSUE THREAD

**Issue by kamikazechaser** [hwdsl2/setup-ipsec-vpn#527]
It would be good to see an inbuilt feature to wrap all traffic (including initial connection to VPN server) wrapped in SSL to bypass aggressive firewalls like SonicFirewall which block VPN connections aggressively. A possible setup with Stunnel may work.

**Comment by hwdsl2** [comment]
@kamikazechaser Hello! Thank you for the suggestion. However this feature is outside the scope of this project.

**Comment by letoams** [comment]
In 2 months Linux will support IPsec over TCP (and maybe TLS). Libreswan already has support lined up for this once the kernel is released. 

https://lists.netdevconf.org/pipermail/people/20190207/000230.html

Soon!
