### ISSUE TITLE
阿里云香港服务器给我发提醒了，让我关掉24小时内关掉VPN，求推荐一个没有限制的服务器

### ISSUE THREAD

**Issue by Adgeros** [hwdsl2/setup-ipsec-vpn#528]

**Comment by hwdsl2** [comment]
@Adgeros 你好！你可以尝试一下 README 里面列出的一些云服务提供商 [1]。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#系统要求

**Comment by xiasenhai** [comment]
我一直用DigitalOcean，每月代扣的，好像付款需要visa卡
