### ISSUE TITLE
Thank you. It worked well.

### ISSUE THREAD

**Issue by haike80** [hwdsl2/setup-ipsec-vpn#529]
I've added your deposit somewhere in my bookmark, yet haven't been tried until yesterday, because there were some issues happened in the connections. I installed your software on my VPS and set up my windows client, but I couldn't reach the server. So I thought I failed, still not being able to restore the connection, which was rather bothering. But this morning after I woke up I had an idea that this might be due to the lack of a reboot after installing.  So I opened my computer and gave it a try, and it worked. With a cup of coffee, this offered me a really good mood. So in wake of your elaborated job with having written this software and the detailed and user-friendly instructions, I think it's a necessity to write some feedbacks like this, and thank all your kindness for doing this and sharing it with the world, for free.

**Comment by hwdsl2** [comment]
@haike80 You're welcome! Glad to hear that the project works well for you.
