### ISSUE TITLE
Error: This script does not support OpenVZ VPS.

### ISSUE THREAD

**Issue by leeivan** [hwdsl2/setup-ipsec-vpn#53]
@hwdsl2, I tried to deploy the VPN server with this script, it showed this error. please tell me why and how to solve the problem. thank you.

**Comment by hwdsl2** [comment]
@leeivan The VPN scripts do not support OpenVZ VPS, because IPsec kernel support may be unavailable. Please use a KVM, Xen or VMware-based VPS instead.

An alternative that can be used on OpenVZ VPS is OpenVPN [1].

[1] https://github.com/Nyr/openvpn-install

**Comment by teifler** [comment]
I also got this error is there a workaround by now?

Thank you!
