### ISSUE TITLE
Get the number of currently connected users

### ISSUE THREAD

**Issue by nodesocket** [hwdsl2/setup-ipsec-vpn#531]
Is there a shell command or script I can run to get the current number of connected IPsec/L2TP and IPsec/XAuth users? I'd like to graph this metric.

Thanks.

**Comment by hwdsl2** [comment]
@nodesocket Try: `ipsec whack --trafficstatus`. For more details, run `ipsec status`

**Comment by nodesocket** [comment]
@hwdsl2 so would the following be correct:

```
sudo ipsec whack --trafficstatus | wc -l
```

**Comment by hwdsl2** [comment]
@nodesocket Yes I think so, although I am not 100% sure.

@letoams Do you know if there’s a better way to get a count of currently connected VPN users (other than using `ipsec whack --trafficstatus`)? Thanks!

**Comment by letoams** [comment]
On Wed, 20 Feb 2019, Lin Song wrote:

> @letoams Do you know if there’s a better way to get a count of currently connected VPN users (other than using ipsec whack
> --trafficstatus)? Thanks!

Not yet. I mean you can do: ipsec status |grep Total

We hope to soon have a more structural way to dump things, possible in
xml/json or yang format, that anyone can then write tools for.

Paul

**Comment by hwdsl2** [comment]
Thanks @letoams!
