### ISSUE TITLE
Logging?

### ISSUE THREAD

**Issue by nodesocket** [hwdsl2/setup-ipsec-vpn#533]
Does this log connected client information/details at all? I.E. are there any physical logs that touch disk related to this vpn setup and who/when/where connected?

**Comment by hwdsl2** [comment]
@nodesocket Hello! Libreswan and xl2tpd logs can be checked using these commands [1]. You can see the XAuth usernames attempted during authentication in the Libreswan logs. See also: #320.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps
