### ISSUE TITLE
去年ubuntu14.04上建的还能用，最近新安装的怎么也连接不上

### ISSUE THREAD

**Issue by guoliangli123** [hwdsl2/setup-ipsec-vpn#535]
window10连接
提示L2TP连接尝试失败，安全层在初始化与远程计算机协商时遇到一个错误。

**Comment by hwdsl2** [comment]
@guoliangli123 你好！检查一下 VPN 服务器日志是否有错误。尝试连接客户端然后jci是否有新的日志。参见 [1]。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#额外的步骤
