### ISSUE TITLE
unknown IPsec command "up" 

### ISSUE THREAD

**Issue by ychaudhari7** [hwdsl2/setup-ipsec-vpn#536]
I did quick start setup exporting other server's vpn credentials on a fresh ec2 instance. I configured *IPsec/L2TP VPN Clients*. But when I run `ipsec up myvpn`

I get 

> /usr/local/sbin/ipsec: unknown IPsec command "up" ("ipsec --help" for list)

**Comment by hwdsl2** [comment]
@ychaudhari7 Hello! Which instructions did you follow for configuring IPsec/L2TP VPN clients? And what is your VPN client’s Linux distribution and version?

The Linux VPN client command line instructions in this repo have not been tested recently, it could be that strongSwan changed the syntax (try `ipsec --help`).

**Comment by ychaudhari7** [comment]
@hwdsl2 Hello I followed [this](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#linux) for *Ubuntu/Debian* by command line my VPN client's distribution is **Ubuntu 18.04.1 LTS**
Found it may be right one is `ipsec auto --up myvpn` but it is not able to find alias now

> 021 no connection named "myvpn"

Any clues?
