### ISSUE TITLE
Ubuntu 18.04 and LXC

### ISSUE THREAD

**Issue by Monarch73** [hwdsl2/setup-ipsec-vpn#537]
On Ubuntu18.04 everything works fine until I install lxc on the server.

The Client can authenticate but no traffic ist going through the VPN Connection. I know too little about ipsec to debug this scenario. But the problem is very easy repoducable. Just run the script, install lxc and reboot the machine.

**Comment by Monarch73** [comment]
I found something. Its fail2ban fucking up iptables when its blocking a connection......

**Comment by hwdsl2** [comment]
@Monarch73 Hello! Thanks for the update. As this issue is with fail2ban and not the VPN setup scripts, I am closing this. Please troubleshoot further yourself.
