### ISSUE TITLE
IDir '193.168.60.90' does not match to 'vpngw.fh-kempten.de'

### ISSUE THREAD

**Issue by saqibshakeel035** [hwdsl2/setup-ipsec-vpn#538]
I am trying to configure my client using VPN (strongswan) to access the remote server whose DNS is 
**vpngw.fh-kempten.de**

Details of my remote VPN Server are:
Authentication Method = Mutual +XAuth
PSK =****
**Phase 1**
Exchange Type = aggressive
DH exchange = group2
Cipher Algorithm = 3ds
Hash Algorithm  = md5
Key life time limit  = 28800secs

**Phase 2**
Tensform Algorithm = esp-3des
HMAC Algorithm  = md5
PFC exchange = Auto
compress Algorithm = disabled 
Key life time limit  = 28800secs

 **General**

Host Name or IP = vpngw.fh-kempten.de
port = 500
Auto configuration = IKE conf. pull
MTU = 1400
Adapter mode = use a virtual adapter and assigned address

**Client**
**firewall options**
NAT traversal = enable
NAT traversal port = 4500
Keep alive packet rate = 15s
IKE fragmentation = enable
Maximum packet siye = 540 bytes
This is all info I have related to my VPN Server which is a remote server.

Using the  command  `sudo ipsec up  ikev1-psk-xauth`, I try to run my client VPN. I get the following error in my raspberry pi

initiating Aggressive Mode IKE_SA ikev1-psk-xauth[1] to 193.174.193.64
generating AGGRESSIVE request 0 [ SA KE No ID V V V V V ]
sending packet: from 192.168.60.96[500] to 193.174.193.64[500] (363 bytes)
received packet: from 193.174.193.64[500] to 192.168.60.96[500] (404 bytes)
parsed AGGRESSIVE response 0 [ SA KE No ID HASH V V V NAT-D NAT-D V V ]
received Cisco Unity vendor ID
received XAuth vendor ID
received draft-ietf-ipsec-nat-t-ike-02\n vendor ID
received FRAGMENTATION vendor ID
received unknown vendor ID: 1f:07:f7:0e:aa:65:14:d3:b0:fa:96:54:2a:50:01:00
IDir '193.174.193.64' does not match to 'vpngw.fh-kempten.de'
generating INFORMATIONAL_V1 request 304912695 [ N(INVAL_ID) ]
sending packet: from 192.168.60.96[500] to 193.174.193.64[500] (56 bytes)
establishing connection 'ikev1-psk-xauth' failed

**Following is my ipsec.conf file**

config setup
  conn ikev1-psk-xauth
        ikelifetime=28800s
        keylife=20m
        rekeymargin=3m
        keyingtries=1
        keyexchange=ikev1
        authby=secret
        ike = 3des-md5-modp1024!
        esp = 3des-md5-modp1024!
        modeconfig = pull
        aggressive = yes
        fragmentation=yes
        #keyexchange = ikev2
        authby = secret
        type = transport
        leftauth = psk
        leftauth2 = xauth
        leftprotoport=17/1701
        rightprotoport=17/1701
        right = vpngw.fh-kempten.de
     rightauth = psk
     rightauth2 = xauth
        auto = add

My motivation is to access te shared drives which are present on the remote VPN server.
Any suggestions would be highly appreciated.
Thanks in advance!!

**Comment by letoams** [comment]
On Thu, 7 Mar 2019, saqibshakeel035 wrote:

> General
> 
> Host Name or IP = vpngw.fh-kempten.de

This matters because it sets the expected ID.

> IDir '193.174.193.64' does not match to 'vpngw.fh-kempten.de'

> Following is my ipsec.conf file

> right = vpngw.fh-kempten.de

So add:
   rightid=193.174.193.64

however, since you now have to hardcode the IP in the ID, you
can also just change the right=vpngw.fh-kempten.de to use
right=193.174.193.64 and the the rightid= will be matched to
that IP.

Paul

**Comment by saqibshakeel035** [comment]
I am out of reach of my work station. Once I will go back, I will try this and will let you know if it works. Thanks for your quick response. BRB :)

**Comment by saqibshakeel035** [comment]
So now when I have teraked my configuration file
I am getting this when I run 
`
initiating Main Mode IKE_SA ikev1-psk-xauth[2] to 193.174.193.64
generating ID_PROT request 0 [ SA V V V V V ]
sending packet: from 192.168.60.96[500] to 193.174.193.64[500] (176 bytes)
received packet: from 193.174.193.64[500] to 192.168.60.96[500] (124 bytes)
parsed ID_PROT response 0 [ SA V V ]
received draft-ietf-ipsec-nat-t-ike-02\n vendor ID
received FRAGMENTATION vendor ID
generating ID_PROT request 0 [ KE No NAT-D NAT-D ]
sending packet: from 192.168.60.96[500] to 193.174.193.64[500] (236 bytes)
received packet: from 193.174.193.64[500] to 192.168.60.96[500] (296 bytes)
parsed ID_PROT response 0 [ KE No V V V V NAT-D NAT-D ]
received Cisco Unity vendor ID
received XAuth vendor ID
received unknown vendor ID: a5:ae:a1:c7:bf:71:ce:fb:54:08:07:bd:c0:99:ec:4e
received unknown vendor ID: 1f:07:f7:0e:aa:65:14:d3:b0:fa:96:54:2a:50:01:00
local host is behind NAT, sending keep alives
generating ID_PROT request 0 [ ID HASH N(INITIAL_CONTACT) ]
sending packet: from 192.168.60.96[4500] to 193.174.193.64[4500] (100 bytes)
received packet: from 193.174.193.64[4500] to 192.168.60.96[4500] (84 bytes)
parsed ID_PROT response 0 [ ID HASH V ]
received DPD vendor ID
received packet: from 193.174.193.64[4500] to 192.168.60.96[4500] (68 bytes)
parsed TRANSACTION request 2858345813 [ HASH CPRQ(X_TYPE X_USER X_PWD) ]
no XAuth method found
generating TRANSACTION response 2858345813 [ HASH CP ]
sending packet: from 192.168.60.96[4500] to 193.174.193.64[4500] (60 bytes)
received packet: from 193.174.193.64[4500] to 192.168.60.96[4500] (68 bytes)
parsed TRANSACTION request 4276759785 [ HASH CPRQ(X_TYPE X_USER X_PWD) ]
no XAuth method found
generating TRANSACTION response 4276759785 [ HASH CP ]
sending packet: from 192.168.60.96[4500] to 193.174.193.64[4500] (60 bytes)
received packet: from 193.174.193.64[4500] to 192.168.60.96[4500] (68 bytes)
parsed TRANSACTION request 1630574200 [ HASH CPRQ(X_TYPE X_USER X_PWD) ]
**no XAuth method found**
generating TRANSACTION response 1630574200 [ HASH CP ]
sending packet: from 192.168.60.96[4500] to 193.174.193.64[4500] (60 bytes)
received packet: from 193.174.193.64[4500] to 192.168.60.96[4500] (60 bytes)
parsed TRANSACTION request 1061612663 [ HASH CPS(X_STATUS) ]
no XAuth method found
generating TRANSACTION response 1061612663 [ HASH CP ]
sending packet: from 192.168.60.96[4500] to 193.174.193.64[4500] (60 bytes)
received packet: from 193.174.193.64[4500] to 192.168.60.96[4500] (60 bytes)
received retransmit of request with ID 1061612663, retransmitting response
sending packet: from 192.168.60.96[4500] to 193.174.193.64[4500] (60 bytes)
received packet: from 193.174.193.64[4500] to 192.168.60.96[4500] (60 bytes)
received retransmit of request with ID 1061612663, retransmitting response
sending packet: from 192.168.60.96[4500] to 193.174.193.64[4500] (60 bytes)
received packet: from 193.174.193.64[4500] to 192.168.60.96[4500] (60 bytes)
received retransmit of request with ID 1061612663, retransmitting response
sending packet: from 192.168.60.96[4500] to 193.174.193.64[4500] (60 bytes)
received packet: from 193.174.193.64[4500] to 192.168.60.96[4500] (76 bytes)
queueing INFORMATIONAL_V1 request as tasks still active
sending keep alive to 193.174.193.64[4500]
peer did not initiate expected exchange, reestablishing IKE_SA
reinitiating IKE_SA ikev1-psk-xauth[2]
initiating Main Mode IKE_SA ikev1-psk-xauth[2] to 193.174.193.64
generating ID_PROT request 0 [ SA V V V V V ]
sending packet: from 192.168.60.96[4500] to 193.174.193.64[4500] (176 bytes)
establishing connection 'ikev1-psk-xauth' failed
`
Now it says **no XAuth method found**
Any suggestions?

**Comment by letoams** [comment]
On Fri, 8 Mar 2019, saqibshakeel035 wrote:

> So now when I have teraked my configuration file
> I am getting this when I run

> no XAuth method found generating T

It seems you misconfigured the ends and they do not agree on whether or
not to use XAUTH/ModeCFG. Try and match up the requirements for both
sides and configure them appropriately for xauth/modecfg or not.

Paul

**Comment by saqibshakeel035** [comment]
My server has PSK configuration but my client doesn't have any PSK because my client local and in my control whereas my server is remote VPN server as is configured on PSK. when I try to match both configurations. in secrete.conf file, I am not understanding what PSK should I define for the client as I don't have any PSK as far as I know. 
I hope you understand?
Kindly respond if you think I am on the wrong way.
Thanks

**Comment by letoams** [comment]
See the man page for /etc/ipsec.secrets.

Basically:

YourID TheirID : PSK “thesecret”

**Comment by saqibshakeel035** [comment]
I tried this but it gives me error that the pak of ip 192.168.60.96(client) does not matched/found

**Comment by hwdsl2** [comment]
Thanks @letoams!

@saqibshakeel035 Please first see my comments in [1]. Besides those, the VPN server does not support IPsec/XAuth aggressive mode in the default configuration, it only supports IPsec/L2TP and IPsec/XAuth main mode. You may alternatively use IPsec/L2TP mode to connect. Example steps can be found in section "Configure Linux VPN clients using the command line" of [2].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/issues/540#issuecomment-471218223
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#configure-linux-vpn-clients-using-the-command-line

**Comment by saqibshakeel035** [comment]
I tried this but it gives me error that the pak of ip 192.168.60.96(client) does not matched/found

**Comment by letoams** [comment]
The PSK is looked up by IDs. See ‘man ipsec.secrets’

If you only have one PSK, you can omit the
IDs:

# /etc/ipsec.secrets
: PSK “secret”
