### ISSUE TITLE
Blacklisting hosts on the VPN server

### ISSUE THREAD

**Issue by nabilfreeman** [hwdsl2/setup-ipsec-vpn#54]
Is there a way to block hosts from being accessed via the VPN? I know it can be done by changing the DNS but it's a very heavy fix.

I am trying to add "Adblock" functionality to this VPN for my iPhone.

**Comment by hwdsl2** [comment]
@nabilfreeman I understand that you want to block hosts from being accessed via the VPN. Unfortunately I am not aware of any method to achieve this, other than changing the DNS as you mentioned. Try asking on these mailing lists [1] [2].

[1] https://lists.libreswan.org/mailman/listinfo/swan
[2] https://lists.strongswan.org/mailman/listinfo/users
