### ISSUE TITLE
deleting IKE_SA VPN[3321] between 192.168.60.96[192.168.60.96]...193.174.193.64[193.174.193.64]

### ISSUE THREAD

**Issue by saqibshakeel035** [hwdsl2/setup-ipsec-vpn#540]
I am trying to connect my VPN remote server from my raspberry pi (rasbian). i am stuck at this error. 

Afer running **sudo ipsec up VPN** i get the following errors

initiating Main Mode IKE_SA VPN[3321] to 193.174.193.64
generating ID_PROT request 0 [ SA V V V V V ]
sending packet: from 192.168.60.96[500] to 193.174.193.64[500] (236 bytes)
received packet: from 193.174.193.64[500] to 192.168.60.96[500] (124 bytes)
parsed ID_PROT response 0 [ SA V V ]
received draft-ietf-ipsec-nat-t-ike-02\n vendor ID
received FRAGMENTATION vendor ID
generating ID_PROT request 0 [ KE No NAT-D NAT-D ]
sending packet: from 192.168.60.96[500] to 193.174.193.64[500] (236 bytes)
received packet: from 193.174.193.64[500] to 192.168.60.96[500] (296 bytes)
parsed ID_PROT response 0 [ KE No V V V V NAT-D NAT-D ]
received Cisco Unity vendor ID
received XAuth vendor ID
received unknown vendor ID: 61:85:41:3d:30:3f:8c:d1:84:ed:7e:f1:2c:76:1a:3f
received unknown vendor ID: 1f:07:f7:0e:aa:65:14:d3:b0:fa:96:54:2a:50:01:00
local host is behind NAT, sending keep alives
generating ID_PROT request 0 [ ID HASH N(INITIAL_CONTACT) ]
sending packet: from 192.168.60.96[4500] to 193.174.193.64[4500] (92 bytes)
received packet: from 193.174.193.64[4500] to 192.168.60.96[4500] (84 bytes)
parsed ID_PROT response 0 [ ID HASH V ]
received DPD vendor ID
IKE_SA VPN[3321] established between 192.168.60.96[192.168.60.96]...193.174.193.64[193.174.193.64]
scheduling reauthentication in 27879s
maximum IKE_SA lifetime 28419s
generating QUICK_MODE request 2516990988 [ HASH SA No ID ID ]
sending packet: from 192.168.60.96[4500] to 193.174.193.64[4500] (188 bytes)
received packet: from 193.174.193.64[4500] to 192.168.60.96[4500] (76 bytes)
parsed INFORMATIONAL_V1 request 3655823699 [ HASH D ]
**received DELETE for IKE_SA VPN[3321]**
**deleting IKE_SA VPN[3321] between 192.168.60.96[192.168.60.96]...193.174.193.64[193.174.193.64]**
initiating Main Mode IKE_SA VPN[3322] to 193.174.193.64
generating ID_PROT request 0 [ SA V V V V V ]
sending packet: from 192.168.60.96[500] to 193.174.193.64[500] (236 bytes)
**establishing connection 'VPN' failed**

when I check the status of my ipconfig, it gives me 
` sudo ipsec statusall`
Status of IKE charon daemon (strongSwan 5.5.1, Linux 4.14.98-v7+, armv7l):
  uptime: 2 minutes, since Mar 08 13:51:14 2019
  malloc: sbrk 1409024, mmap 0, used 1042400, free 366624
  worker threads: 10 of 16 idle, 5/1/0/0 working, job queue: 0/0/0/0, scheduled: 5964
  loaded plugins: charon aes rc2 sha2 sha1 md5 random nonce x509 revocation constraints pubkey pkcs1 pkcs7 pkcs8 pkcs12 pgp dnskey sshkey pem openssl fips-prf gmp agent xcbc hmac gcm attr kernel-netlink resolve socket-default connmark stroke updown
Listening IP addresses:
  192.168.60.96
Connections:
         VPN:  %any...193.174.193.64  IKEv1
         VPN:   local:  [192.168.60.96] uses pre-shared key authentication
         VPN:   remote: [193.174.193.64] uses pre-shared key authentication
         VPN:   child:  dynamic === dynamic TUNNEL
Security Associations (1 up, 0 connecting):
  none

and after sometime, when I check the status again it shows

Status of IKE charon daemon (strongSwan 5.5.1, Linux 4.14.98-v7+, armv7l):
  uptime: 3 minutes, since Mar 08 13:51:14 2019
  malloc: sbrk 1454080, mmap 0, used 1158664, free 295416
  worker threads: 10 of 16 idle, 5/0/0/1 working, job queue: 0/0/0/0, scheduled: 6766
  loaded plugins: charon aes rc2 sha2 sha1 md5 random nonce x509 revocation constraints pubkey pkcs1 pkcs7 pkcs8 pkcs12 pgp dnskey sshkey pem openssl fips-prf gmp agent xcbc hmac gcm attr kernel-netlink resolve socket-default connmark stroke updown
Listening IP addresses:
  192.168.60.96
Connections:
         VPN:  %any...193.174.193.64  IKEv1
         VPN:   local:  [192.168.60.96] uses pre-shared key authentication
         VPN:   remote: [193.174.193.64] uses pre-shared key authentication
         VPN:   child:  dynamic === dynamic TUNNEL
Security Associations (0 up, 1 connecting):
         VPN[3095]: CONNECTING, 192.168.60.96[%any]...193.174.193.64[%any]
         VPN[3095]: IKEv1 SPIs: 8e1ee8e67d694af0_i* f2b5264772f1bc29_r
         VPN[3095]: IKE proposal: 3DES_CBC/HMAC_MD5_96/PRF_HMAC_MD5/MODP_1024
         VPN[3095]: Tasks queued: QUICK_MODE QUICK_MODE QUICK_MODE
         VPN[3095]: Tasks active: ISAKMP_VENDOR MAIN_MODE ISAKMP_NATD

My .config file is as follows 
config setup

conn %default
        auto=start

conn VPN
  ```
      type=tunnel
        ike=3des-md5-modp1024
        ikelifetime=28800s
        keyexchange=ikev1
        esp=3des-md5
        #aggressive = yes
        left=%defaultroute
       #leftfirewall=yes
        leftid=192.168.60.96
        leftauth=psk
        right=193.174.193.64
#        rightprotoport=tcp/9999
       # leftprotoport = tcp/9999
        rightauth=psk
```
Kindly let guide me as i am not a neworking pro, it's just one part of my project and I am scratcing my head over it from last 2 weeks. 
Thanks

**Comment by hwdsl2** [comment]
@saqibshakeel035 Hello! Your configuration:
```
... ...
      ike=3des-md5-modp1024
      esp=3des-md5
... ...
```

By default, the VPN server does not allow 3DES and MD5 ciphers. Change your client configuration to something like:
```
  ike=aes128-sha1-modp2048!
  esp=aes128-sha1-modp2048!
```

For an example on how to connect Linux clients using the command line, see [1]. For further troubleshooting, check the VPN logs on the server for errors. Refer to [2].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#configure-linux-vpn-clients-using-the-command-line
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps

**Comment by saqibshakeel035** [comment]
The problem is that the server is set up is not in my control as it is done by the university administration and is `ike=3des-md5-modp1024` and `esp=3des-md5`. Do you recommend still I configure my client as
```
 ike=aes128-sha1-modp2048!
  esp=aes128-sha1-modp2048!
``` 
Your suggestions?

**Comment by hwdsl2** [comment]
@saqibshakeel035 No, your client cipher configuration should match the ciphers configured on the VPN server.

Because your server is not set up using the scripts in this repo, I suggest that you instead reach out to the Libreswan or strongSwan users mailing list for further questions.

**Comment by letoams** [comment]
On Sun, 10 Mar 2019, saqibshakeel035 wrote:

> The problem is that the server is set up is not in my control as it is done by the university administration and is
> ike=3des-md5-modp1024 and esp=3des-md5. Do you recommend still I configure my client as

Send your university admin these two links that state that they are using deprecated algorithms that
the RFC states as MUST NOT use, and tell them to reconfigure/upgrade:

https://tools.ietf.org/html/rfc8221

https://tools.ietf.org/html/rfc8247

    Group 2 or the 1024-bit MODP Group has been downgraded from MUST- in
    RFC 4307 to SHOULD NOT.  It is known to be weak against sufficiently
    funded attackers using commercially available mass-computing
    resources, so its security margin is considered too narrow.  It is
    expected in the near future to be downgraded to MUST NOT.

    ENCR_3DES has been downgraded from RFC 4307 MUST- to MAY.  All IKEv2
    implementations already implement ENCR_AES_CBC, so there is no need
    to keep support for the much slower ENCR_3DES.  In addition,
    ENCR_CHACHA20_POLY1305 provides a more modern alternative to AES.

    AUTH_HMAC_MD5_96 is also demoted to MUST NOT.  This is because
    there is an industry-wide trend to deprecate DES and MD5.  Note also
    that MD5 support is being removed from cryptographic libraries in
    general because its non-HMAC use is known to be subject to collision
    attacks, for example, as mentioned in [TRANSCRIPTION].

Paul
