### ISSUE TITLE
reboot centos 後 ifconfig 看不到ppp0

### ISSUE THREAD

**Issue by stevekwokdev** [hwdsl2/setup-ipsec-vpn#542]
要等到直至有device connect後才有
怎樣把它弄到永久在ipconfig , ifup 不行因為沒有device連接時是沒有的
還有win10連接後只能連上youtube google 其他連不上

謝謝

**Comment by hwdsl2** [comment]
@stevekwokdev 你好! `ppp0` 只有在连接 VPN 客户端之后才有。你所说的重启后没有是正常的。

如果不能访问其他网站，有可能是你需要清除客户端的 DNS 缓存并重启（具体请自己搜索），或者有可能是你的服务器本身就受限制不能访问其他网站。这个不是 VPN 脚本的问题。

**Comment by stevekwokdev** [comment]
应该不是客户端的 DNS 缓存 我IPHONE也连不想
还有不可能是受限制不能访问其他网站 因为我几小时前刚安装好的时候还能访问其他网站 就忽然连不想其他网站了

**Comment by hwdsl2** [comment]
@stevekwokdev 可以在服务器上用 `curl` 或 `wget` 命令试一下能否访问其他网站。如果还是不行，你可以尝试更换新的服务器。

**Comment by stevekwokdev** [comment]
那个服务器时间是2016年会不会有影响? 因为我在服务器上ping 什么网站都能连上

**Comment by hwdsl2** [comment]
@stevekwokdev 这个我觉得关系不大。你可以再重启一下服务器和客户端试试。

**Comment by stevekwokdev** [comment]
https://i.gyazo.com/edded0177dbe1fd41cc8b2ebc914b470.png

進入vpn後putty連不上主機 有時候能連上有時候不能
