### ISSUE TITLE
Works on Mac OS, but not on Huawei B525s router

### ISSUE THREAD

**Issue by ZombieTheBest** [hwdsl2/setup-ipsec-vpn#544]
Hello, I'm unable to connect from my home router. Unfortunately it does not have any log, so I can't see whats wrong.

Only thing I can see from `systemctl status xl2tpd` is that the VPN does not receive any incoming connection.
With other LT2P VPNs my modem connects just fine.

Do you have any suggestion? Thanks!

**Comment by hwdsl2** [comment]
@ZombieTheBest Hello! Libreswan and xl2tpd logs can be checked using these commands [1]. See if the VPN server logs have any error.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps

**Comment by nulloxide** [comment]
same issue here with huawei b612 , read all the docs but can't fix the problem. can n e one help ?

**Comment by hwdsl2** [comment]
@nulloxide Hello! Did you check the server logs using the link above?

**Comment by pcoombe** [comment]
Yeah i have the same issue on a b525, i think its the modem, not the server.
