### ISSUE TITLE
Configuring D-Link DIR-825ACG1 to use the tunnel

### ISSUE THREAD

**Issue by belazzz** [hwdsl2/setup-ipsec-vpn#546]
I am trying to set up the VPN tunnel on my router, but with no success. Under the IPsec section the tunnel I set up is showing as "dead", and the L2TP connection is failing also.
I think the problem is that the router only supports "DES" encryption. Can I still make this work somehow, perhaps extending the list of allowed algorithms in the config files?
![Screenshot_20190403_031901](https://user-images.githubusercontent.com/19731636/55445472-3739da00-55c4-11e9-8cba-35909dc9a8db.png)

**Comment by hwdsl2** [comment]
@belazzz Hello! 1DES is insecure and should not be used. It was removed from Libreswan due to this reason (see "ike" section in [1]), so unfortunately you cannot configure the Libreswan VPN server to use it.

[1] https://libreswan.org/man/ipsec.conf.5.html
