### ISSUE TITLE
How to connect to another peer's subnet?

### ISSUE THREAD

**Issue by uemahra** [hwdsl2/setup-ipsec-vpn#548]
Hi contributors,
Great work here, after I configured strongswan and failed, I found your project, it's working and very fast deploy. But I don't know how to connect to the peer's sbunet.
The environment I have is this: one VPS CentOS6.10, have a NAT address on eth0 and the VPS provider nat whatever eth0 listens. another one is my android phone, it connects to a WiFi, the wlan0 has the WiFi's address 192.168.2.170/24, after connect IPSec to the VPS, there is a 'tun0' device appeared with address 192.168.43.10. Now if I want to use VPS to access to 192.168.2.0/24, how am I suppose to do? I don't see any new network device or route on the VPS.

**Comment by hwdsl2** [comment]
@uemahra Hello! For IPsec VPNs it is generally difficult to access from the VPN Server to the VPN Client's network (the other way around is usually fine), unless the two endpoints are connected as subnet-to-subnet VPNs. Refer to #400 for more info. You may need to look into alternative solutions for this use case.
