### ISSUE TITLE
xauth: multiple clients behind nat

### ISSUE THREAD

**Issue by yandy** [hwdsl2/setup-ipsec-vpn#55]
I find myself stuck on a NAT issue.  When there are multiple clients behind the same NAT, Only the last connected one can connect to Internet

**Comment by hwdsl2** [comment]
@yandy Hello! Unfortunately this is currently a limitation of the IPsec (IKEv1) protocol. You may want to try IKEv2 or OpenVPN, which does support multiple clients behind the same NAT. Some example repos can be found under "See Also" in the project README.
