### ISSUE TITLE
OpenVPN/TunnelBlick

### ISSUE THREAD

**Issue by mateuszmaniecki** [hwdsl2/setup-ipsec-vpn#552]
Hello,
It's a stupid question, but how can I generate OpenVPN/TunnelBlick configuration file to connect to h2dsl2 VPN?

I use now IPSec installation.

I read this docs : https://github.com/Nyr/openvpn-install

It must be install to use the configuration for OpenVPN? It's must be installed over hwdsl2 VPN or separeted?

**Comment by hwdsl2** [comment]
@mateuszmaniecki Hello! The scripts in this repo sets up an IPsec VPN server. TunnelBlick only supports connecting to OpenVPN servers, which you may set up your own using Nyr’s script (or another method). If desired, you may try to run both scripts on the same server one after another to set up a server with both IPsec and OpenVPN.
