### ISSUE TITLE
Android 8 can't connect , but iphone, Mac, Android 6 can

### ISSUE THREAD

**Issue by DengXuening** [hwdsl2/setup-ipsec-vpn#553]
Thanks for team's script, it works well on my centOS 7. My Mac、iphone、honor 7(Andorid 6) both can connect the vpn.  But when I connect my VPN with Oppo Find X(Andorid 8) ，it didn't work. just failed. no error, no error code. I have tried many times, such as modifing `phase2alg` and `ike` of `ipsec.conf`,  but my Oppo Find X still cannot connect my VPN. Is there anybody can help me ?

The detail of`/etc/ipsec.conf`:

```config
version 2.0

config setup
  virtual-private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:!192.168.42.0/24,%v4:!192.168.43.0/24
  protostack=netkey
  interfaces=%defaultroute
  uniqueids=no

conn shared
  left=%defaultroute
  leftid=47.52.231.168
  right=%any
  encapsulation=yes
  authby=secret
  pfs=no
  rekey=no
  keyingtries=5
  dpddelay=30
  dpdtimeout=120
  dpdaction=clear
  ike=aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1,aes256-sha2;modp1024,aes128-sha1;modp1024
  phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes256-sha2_512,aes128-sha2,aes256-sha2
  sha2-truncbug=yes

conn l2tp-psk
  auto=add
  leftprotoport=17/1701
  rightprotoport=17/%any
  type=transport
  phase2=esp
  also=shared

conn xauth-psk
  auto=add
  leftsubnet=0.0.0.0/0
  rightaddresspool=192.168.43.10-192.168.43.250
  modecfgdns="8.8.8.8 8.8.4.4"
  leftxauthserver=yes
  rightxauthclient=yes
  leftmodecfgserver=yes
  rightmodecfgclient=yes
  modecfgpull=yes
  xauthby=file
  ike-frag=yes
  ikev2=never
  cisco-unity=yes
  also=shared
```

when I use my andorid 8 phone to connect the vpn, I got the log:
```
Apr 28 17:34:45 izj6c88rg4xz5rg8svvsg3z pluto[14806]: packet from 1xx.xxx.xxx.x9:60548: initial Aggressive Mode message from 1xx.xxx.xxx.x9 but no (wildcard) connection has been configured with policy PSK+AGGRESSIVE+IKEV1_ALLOW
Apr 28 17:34:48 izj6c88rg4xz5rg8svvsg3z pluto[14806]: packet from 1xx.xxx.xxx.x9:60548: initial Aggressive Mode message from 1xx.xxx.xxx.x9 but no (wildcard) connection has been configured with policy PSK+AGGRESSIVE+IKEV1_ALLOW
Apr 28 17:34:51 izj6c88rg4xz5rg8svvsg3z pluto[14806]: packet from 1xx.xxx.xxx.x9:60548: initial Aggressive Mode message from 1xx.xxx.xxx.x9 but no (wildcard) connection has been configured with policy PSK+AGGRESSIVE+IKEV1_ALLOW
Apr 28 17:34:53 izj6c88rg4xz5rg8svvsg3z pluto[14806]: packet from 1xx.xxx.xxx.x9:60548: initial Aggressive Mode message from 1xx.xxx.xxx.x9 but no (wildcard) connection has been configured with policy PSK+AGGRESSIVE+IKEV1_ALLOW
Apr 28 17:34:56 izj6c88rg4xz5rg8svvsg3z pluto[14806]: packet from 1xx.xxx.xxx.x9:60548: initial Aggressive Mode message from 1xx.xxx.xxx.x9 but no (wildcard) connection has been configured with policy PSK+AGGRESSIVE+IKEV1_ALLOW
Apr 28 17:34:59 izj6c88rg4xz5rg8svvsg3z pluto[14806]: packet from 1xx.xxx.xxx.x9:60548: initial Aggressive Mode message from 1xx.xxx.xxx.x9 but no (wildcard) connection has been configured with policy PSK+AGGRESSIVE+IKEV1_ALLOW
Apr 28 17:35:02 izj6c88rg4xz5rg8svvsg3z pluto[14806]: packet from 1xx.xxx.xxx.x9:60548: initial Aggressive Mode message from 1xx.xxx.xxx.x9 but no (wildcard) connection has been configured with policy PSK+AGGRESSIVE+IKEV1_ALLOW
Apr 28 17:35:05 izj6c88rg4xz5rg8svvsg3z pluto[14806]: packet from 1xx.xxx.xxx.x9:60548: initial Aggressive Mode message from 1xx.xxx.xxx.x9 but no (wildcard) connection has been configured with policy PSK+AGGRESSIVE+IKEV1_ALLOW
Apr 28 17:35:08 izj6c88rg4xz5rg8svvsg3z pluto[14806]: packet from 1xx.xxx.xxx.x9:60548: initial Aggressive Mode message from 1xx.xxx.xxx.x9 but no (wildcard) connection has been configured with policy PSK+AGGRESSIVE+IKEV1_ALLOW
```

**Comment by hwdsl2** [comment]
@DengXuening Hello! From your logs it looks like your Android 8 device tried to use IPsec/XAuth “aggressive mode” which the script does not support. Make sure that you leave the “group name” blank in your Android 8 VPN configuration. If not, it will try to use aggressive mode.

Alternatively, try the IPsec/L2TP mode instead of IPsec/XAuth on your Android 8.

Finally, try changing “sha2-truncbug=yes” to “no” in “/etc/ipsec.conf” and restart the ipsec service if the logs on the VPN server show connected but your Android phone cannot open any website.

**Comment by DengXuening** [comment]
@hwdsl2 Thank you for your quick response. I both try `IPsec/L2TP` mode and `IPsec/XAuth` mode, and change `“sha2-truncbug=yes` to  `no`,  but still cannot connect VPN with andorid 8 phone.  Below is a screenshot of logs:

![image](https://user-images.githubusercontent.com/19208263/56875769-6e8d9080-6a75-11e9-9d0a-9f840e3f8b25.png)
The first section of log is `IPsec/L2TP` mode, the last section is `IPsec/XAuth` mode.
Looking forward your reply.

**Comment by hwdsl2** [comment]
@DengXuening Your logs indicate that your Android 8 phone tried to connect using IPsec "aggressive mode" which is not supported by the default configuration in the VPN setup scripts.

Make sure that you leave the "IPsec identifier" blank in your Android phone's VPN configuration. If you already did that, however, your Android phone may not be compatible with this VPN server and you might want to look into alternative solutions such as OpenVPN.

**Comment by DengXuening** [comment]
Tks for your adivce. It works when I clear the `IPSec identifier` in my android phone's VPN configuration(ghost knows why I filled this item~).  This problem has been bothering me for days.
hahahhahahahahahahhahahahah
