### ISSUE TITLE
policy does not allow Extended Authentication (XAUTH) of initiator

### ISSUE THREAD

**Issue by nodesocket** [hwdsl2/setup-ipsec-vpn#557]
Connecting from macOS using Cisco IPSec and seeing intermittent connection failures. This is an office where multiple users are connecting to the VPN.

The error is `policy does not allow Extended Authentication (XAUTH) of initiator (we are responder)`.

```
May  7 18:07:08 vpn1 pluto[2387]: "l2tp-psk"[25] 172.91.135.113 #260: responding to Main Mode from unknown peer 172.91.135.113 on port 500
May  7 18:07:08 vpn1 pluto[2387]: "l2tp-psk"[25] 172.91.135.113 #260: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD
May  7 18:07:08 vpn1 pluto[2387]: message repeated 12 times: [ "l2tp-psk"[25] 172.91.135.113 #260: policy does not allow Extended Authentication (XAUTH) of initiator (we are responder).  Attribute OAKLEY_AUTHENTICATION_METHOD]
May  7 18:07:08 vpn1 pluto[2387]: "l2tp-psk"[25] 172.91.135.113 #260: OAKLEY_DES_CBC(UNUSED) is not supported.  Attribute OAKLEY_ENCRYPTION_ALGORITHM
May  7 18:07:08 vpn1 pluto[2387]: "l2tp-psk"[25] 172.91.135.113 #260: OAKLEY_DES_CBC(UNUSED) is not supported.  Attribute OAKLEY_ENCRYPTION_ALGORITHM
May  7 18:07:08 vpn1 pluto[2387]: "l2tp-psk"[25] 172.91.135.113 #260: no acceptable Oakley Transform
May  7 18:07:08 vpn1 pluto[2387]: "l2tp-psk"[25] 172.91.135.113 #260: sending notification NO_PROPOSAL_CHOSEN to 172.91.135.113:500
May  7 18:07:12 vpn1 pluto[2387]: "l2tp-psk"[25] 172.91.135.113 #260: discarding initial packet; already STATE_MAIN_R0
May  7 18:07:18 vpn1 pluto[2387]: message repeated 2 times: [ "l2tp-psk"[25] 172.91.135.113 #260: discarding initial packet; already STATE_MAIN_R0]
```

**Comment by letoams** [comment]
Looks like it is mistakenly requesting 1DES?

I would recommend trying to migrate to IKEv2 based IPsec

**Comment by nodesocket** [comment]
Even with IKEv2 according to [doc](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md):

> Connecting multiple IKEv2 clients simultaneously from behind the same NAT (e.g. home router) is not supported at this time.

The office has around 6 people who need to connect all from the same router using both Windows 10 _(l2TP)_ and macOS _(IPsec XAUTH)_.

**Comment by letoams** [comment]
I am not sure why it says that in the documentation there - it should work fine.

Paul

**Comment by nodesocket** [comment]
Can we mix and match IKEv2 and XAUTH users from the same router then?

**Comment by hwdsl2** [comment]
@nodesocket @letoams The IKEv2 multiple clients behind the same NAT issue is due to a bug in Libreswan. See #469.

Not sure about mixing IKEv2 and XAUTH users from behind the same router.

**Comment by nodesocket** [comment]
Ok, if we can't have multiple IKEv2 clients behind the NAT that does not work. How about setting up a site-to-site vpn connection between the office router and this.

**Comment by hwdsl2** [comment]
@nodesocket The error in your logs show that maybe you were mixing L2TP clients with XAUTH clients from behind the same NAT (same IP). When that happens, you’ll see the “policy does not allow...” error. Also, your device is trying to use 1DES which is disallowed in the VPN server configuration. Configure it to use e.g. AES instead.

Regarding the site-to-site VPN for your use case... I am not sure, maybe @letoams can provide some insight.

**Comment by nodesocket** [comment]
> Also, your device is trying to use 1DES which is disallowed in the VPN server configuration.

It is just a standard macOS Cisco IPSec connection. I don't know if there a way to select the cipher.

**Comment by hwdsl2** [comment]
@nodesocket I see. I don’t think macOS uses 1DES. Maybe restart the IPsec service on the VPN server and try connecting again from macOS.

**Comment by letoams** [comment]
On Tue, 7 May 2019, Lin Song wrote:

> Regarding the site-to-site VPN for your use case... I am not sure, maybe @letoams can provide some insight.

You can have a look at https://libreswan.org/wiki/Subnet_to_subnet_VPN

You don't need to use raw RSA keys as in that example. You can use PSK
too but just make sure those are really random and at least 20-32 chars
long.

Paul

**Comment by hwdsl2** [comment]
Thanks @letoams!

@nodesocket Closing this issue as we’ve discussed potential solutions and alternatives for your use case. If you have additional questions, reply here or open a new issue.
