### ISSUE TITLE
路由器不能正常连接，但IOS可以

### ISSUE THREAD

**Issue by Laruto** [hwdsl2/setup-ipsec-vpn#558]
路由器：
![image](https://user-images.githubusercontent.com/19355223/57355915-b44b0700-71a1-11e9-9517-98e491203405.png)
路由器日志：
![image](https://user-images.githubusercontent.com/19355223/57356348-ca0cfc00-71a2-11e9-8c2f-06c599cdb6b7.png)

ipsec配置：
![image](https://user-images.githubusercontent.com/19355223/57356326-b9f51c80-71a2-11e9-862c-7ba2e079199f.png)

服务器日志：
![image](https://user-images.githubusercontent.com/19355223/57356092-258aba00-71a2-11e9-9f62-4f1c2885b664.png)

**Comment by hwdsl2** [comment]
@Laruto 你好！从你的服务器日志来看，可能是连接被防火墙干扰或屏蔽了。你可以进一步检查xl2tpd日志：`grep xl2tpd /var/log/syslog /var/log/messages`，以及搜索一下这里之前的关于路由器的类似Issue。如果仍然无法解决，建议你换用其他解决方案比如Shadowsocks。

**Comment by Laruto** [comment]
@hwdsl2 你好！我不太明白是，客户端这边的防火墙问题还是服务器端的防火墙问题，因为我的IOS能连接上的话，说明服务端的墙应该是没问题的。

**Comment by hwdsl2** [comment]
@Laruto 我是说连接可能是被GFW干扰了。
