### ISSUE TITLE
after use for a while, the server will down due to disk full

### ISSUE THREAD

**Issue by JasonHao123** [hwdsl2/setup-ipsec-vpn#562]
I setup the vpn in AWS on Ubuntu 16 for several times, since use for some days, the server disk will full. Can not access the server anymore, even use ssh, need to increase the disk size or reinstall the server. Look into the log, seems to related to system journals.

**Comment by letoams** [comment]
On Mon, 13 May 2019, Jason Hao wrote:

> I setup the vpn in AWS on Ubuntu 16 for several times, since use for some days, the server disk will full. Can not access
> the server anymore, even use ssh, need to increase the disk size or reinstall the server. Look into the log, seems to
> related to system journals.

See https://wiki.archlinux.org/index.php/Systemd/Journal#Journal_size_limit on how to limit those journal sizes and how to clean them up.

Paul

**Comment by hwdsl2** [comment]
Thanks @letoams!

@JasonHao123 I don’t think the disk full issue is caused by software used by the IPsec VPN, i.e. Libreswan or xl2tpd. If you have proof that it is indeed related, let us know by providing more log details.
