### ISSUE TITLE
doesn't work at mac

### ISSUE THREAD

**Issue by xixiaocheng** [hwdsl2/setup-ipsec-vpn#563]
![image](https://user-images.githubusercontent.com/29592694/57772908-4aa29e00-7749-11e9-9cc9-c56763319e0f.png)

**Comment by hwdsl2** [comment]
@xixiaocheng Hello! Can not reproduce on macOS High Sierra. Check the Libreswan (IPsec) and xl2tpd logs on the VPN server for errors:

```
# Ubuntu & Debian
grep pluto /var/log/auth.log
grep xl2tpd /var/log/syslog

# CentOS & RHEL
grep pluto /var/log/secure
grep xl2tpd /var/log/messages
```

If there are no new logs after trying to connect, then traffic did not reach your VPN server. Open UDP ports 500 and 4500 in your server provider’s firewall (e.g. security group in EC2).
