### ISSUE TITLE
Server Configuration

### ISSUE THREAD

**Issue by saeidsl** [hwdsl2/setup-ipsec-vpn#567]
What is the minimum server configuration you recommend?
I have a Deb 8.8 | 10 GB Disck  |2 GHz (1 core) | 0.5 GB Memory.

Is it working on that?

**Comment by hwdsl2** [comment]
@saeidsl Hello! Yes, your configuration should work. The VPN server works on a wide range of server configurations, you can install it on a Raspberry Pi 3, for example (see README).

**Comment by letoams** [comment]
That should work fine
