### ISSUE TITLE
centos上无法连接

### ISSUE THREAD

**Issue by Laruto** [hwdsl2/setup-ipsec-vpn#568]
我在国外的centos服务器上运行了ipsec脚本，在我用路由器去连接它时出了问题
路由器日志：
![image](https://user-images.githubusercontent.com/19355223/58001102-1c3c0e80-7b0d-11e9-819c-f8b6c43fcbaa.png)
ipsec verify:
![image](https://user-images.githubusercontent.com/19355223/58001128-32e26580-7b0d-11e9-8f14-520655ffb3ea.png)
ipsec.conf:
![image](https://user-images.githubusercontent.com/19355223/58001159-47bef900-7b0d-11e9-9b92-870f50ca3afc.png)
pluto日志:
![image](https://user-images.githubusercontent.com/19355223/58001381-e51a2d00-7b0d-11e9-839d-56ce9434a415.png)
xl2tpd日志:
![image](https://user-images.githubusercontent.com/19355223/58001405-f7946680-7b0d-11e9-8a29-89fa5faa8278.png)

**Comment by hwdsl2** [comment]
@Laruto Hello! Your pppd log says it fails to find the plugin L2TP.ppp, which is incorrect (did you configure this somewhere?) The plugin should be named `pppol2tp.so`. See similar questions [1][2]. It is an issue with your CentOS system.

[1] https://gist.github.com/nirvdrum/775bb07795685b3db6b50806b329b074#couldnt-load-plugin-pppol2tpso-from-pppd
[2] http://forums.openl2tp.org/viewtopic.php?f=3&t=10

**Comment by Laruto** [comment]
@hwdsl2 Sorry, by 'incorrect', you mean this is not a plugin or this plugin is not necessary for vpn connection? We've reinstalled ipsec and l2tp service, it didn't work. If it may be an issue with CentOS system, should reinstalling CentOS solve the problem? Actually, I haven't got anything helpful while googling 'centos l2tp.ppp'.

**Comment by Laruto** [comment]
we change to ubuntu and success!!!
