### ISSUE TITLE
libreswan 3.28

### ISSUE THREAD

**Issue by anartikov** [hwdsl2/setup-ipsec-vpn#569]
Tell me, when to wait for the update script for libreswan 3.28?

**Comment by hwdsl2** [comment]
@anartikov Hello! Libreswan 3.28 has just been released and I have not had time to test it yet. No ETA at this time. However you are welcome to try modifying the upgrade scripts yourself and/or submit pull requests.

**Comment by hwdsl2** [comment]
The update scripts now support Libreswan 3.28.
