### ISSUE TITLE
VPN server import  detailed routes to the client

### ISSUE THREAD

**Issue by tomluffy** [hwdsl2/setup-ipsec-vpn#570]
For example, Through the server only import 8.8.0.0/16  route into the VPN Client ,  The client accesses the internet out of from the local default route，The client accesses the 8.8.0.0/16 out of from the vpn server ；I Don't want want to manually modify the client routing，Sorry, my English is very poor. Thank you.

**Comment by hwdsl2** [comment]
@tomluffy Hello! You can achieve this by configuring the `leftsubnet` option in `/etc/ipsec.conf`. See #514 for details.

**Comment by tomluffy** [comment]
I add a single route  successfully, but how to add more?   I tried these formats and failed： leftsubnet=8.8.0.0/16,123.123.0.0/16  or    leftsubnet1=8.8.0.0/16  leftsubne2t=123.123.0.0/16

**Comment by letoams** [comment]
> leftsubnets={8.8.0.0/16,123.123.0.0/16}
>

**Comment by tomluffy** [comment]
> leftsubnets={8.8.0.0/16,123.123.0.0/16}
> Sent from mobile device
> […](#)
> On May 24, 2019, at 09:43, tomluffy ***@***.***> wrote: I add a single route successfully, but how to add more? I tried these formats and failed： leftsubnet=8.8.0.0/16,123.123.0.0/16 or leftsubnet1=8.8.0.0/16 leftsubne2t=123.123.0.0/16 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Xauth mode  Still prompted：“The VPN server is not responding. Please verify the server address and try to reconnect”
Change back leftsubnet=8.8.0.0/16  Return to normal

L2TP mode  Connection is not affected ，but the import  route is also invalid

**Comment by letoams** [comment]
On Fri, 24 May 2019, tomluffy wrote:

>       leftsubnets={8.8.0.0/16,123.123.0.0/16}
>       Sent from mobile device
>       …
>       On May 24, 2019, at 09:43, tomluffy @.***> wrote: I add a single route successfully, but how to add more? I tried these formats and failed：
>       leftsubnet=8.8.0.0/16,123.123.0.0/16 or leftsubnet1=8.8.0.0/16 leftsubne2t=123.123.0.0/16 — You are receiving this because you are subscribed
>       to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> Xauth mode Still prompted：“The VPN server is not responding. Please verify the server address and try to reconnect”
> Change back leftsubnet=8.8.0.0/16 Return to normal
> 
> L2TP mode Connection is not affected ，but the import route is also invalid

Yes, with libreswan unfortunately multiple subnets are currently not
supported for L2TP/IPsec or IKEv1 XAUTH. Only for static tunnels.

Paul

**Comment by yxing-xyz** [comment]
> 在2019年5月24日星期五，tomluffy写道：leftsubnets = {8.8.0.0/16,123.123.0.0/16}从移动设备发送…在2019年5月24日09:43，tomluffy @。***>写道：我添加一条路线成功，但是如何添加更多路线？我尝试了以下格式，但失败了：leftsubnet = 8.8.0.0 / 16,123.123.0.0 / 16或leftsubnet1 = 8.8.0.0 / 16 leftsubne2t = 123.123.0.0 / 16 —您收到此消息是因为您已订阅此线程。直接回复此电子邮件，在GitHub上查看，或使该线程静音。Xauth模式仍然提示：“ VPN服务器没有响应。请验证服务器地址，然后尝试重新连接。”返回左子网= 8.8.0.0 / 16返回正常的L2TP模式连接不受影响，但导入路由也无效
> 是的，不幸的是，对于libreswan，L2TP / IPsec或IKEv1 XAUTH当前不支持多个子网。仅用于静态隧道。保罗

请问限制IKEv2支持多子网了么
