### ISSUE TITLE
Service Status

### ISSUE THREAD

**Issue by saeidsl** [hwdsl2/setup-ipsec-vpn#571]
Is there any command to have a report or log to find out the VPN server/service  status?
Thanks.

**Comment by letoams** [comment]
For libreswan use “ipsec trafficstatus” (or as of 3.28, ipsec briefstatus”, or the hard to read full “ipsec status”

Strongswan has “ipsec status” and “ipsec statusall”

**Comment by hwdsl2** [comment]
Thanks @letoams!
