### ISSUE TITLE
Web GUI to manage VPN

### ISSUE THREAD

**Issue by irfanjunaid** [hwdsl2/setup-ipsec-vpn#572]
Hi,
First of thanks for this awesome project! Works beautifully!

I am trying to accomplish something like OpenVPN Access server for GUI. It would be great if there is webgui for managing users, tracking their activities like bandwidth logs, IPs, logged-in users etc... Managing users via commands & scripts is okay but it would be awesome if there is a web gui for managing and tracking users. What would be your suggestions for this? Thanks again!

**Comment by hwdsl2** [comment]
@irfanjunaid Hello! Thank you for the suggestion. A web GUI is outside the scope of this project, and unfortunately I am not aware of a good web GUI for IPsec VPNs.
