### ISSUE TITLE
Connection Throttling - Help

### ISSUE THREAD

**Issue by MWalid** [hwdsl2/setup-ipsec-vpn#573]
Hello,

First of all, I want to say thank you for the helpful script.

This is not a bug - it's *help wanted* issue.

I'm having an issue where my VPN connection is established successfully, connection works for the first 4-5 page loads (web browsing), then it stops working, looks like the connection is throttled via some ISP firewall here (Dubai - UAE).

Is it possible to work around this?

I can't see anything helpful in [logs](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps).

Thank you,

**Comment by letoams** [comment]
They do weird things there :(

You will have to wait for RFC 8229 ESP over TLS support. We are still waiting on the kernel side to be completed. Hopefully soon

**Comment by hwdsl2** [comment]
Thanks @letoams!

@MWalid Unfortunately I'm not aware of a workaround for this. You may want to instead consider alternative solutions such as Shadowsocks.
