### ISSUE TITLE
How to use different user links under the same LAN?

### ISSUE THREAD

**Issue by lzlylxy** [hwdsl2/setup-ipsec-vpn#574]

**Comment by hwdsl2** [comment]
@lzlylxy Hello! Not sure what you are asking, but if you wish to connect multiple devices simultaneously from behind the same NAT (e.g. home router), you must use only IPsec/XAuth mode [1].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md

**Comment by lzlylxy** [comment]
ok， thanks
