### ISSUE TITLE
How to use vpn over ssh port forwarding

### ISSUE THREAD

**Issue by quick-sort** [hwdsl2/setup-ipsec-vpn#575]
If I establish a VPN server outside China and connect directly to it, the GFW will ban the VPN IP soon. Since ssh is safe from GFW, I think maybe I could do a SSH tcp port forwarding(500, 4500, 1701) first from a domestic jump server to the VPN server. I use socat to do tcp <-> udp convert. After it has been done, I can vpn connect to the domestic server successfully, but when I make a network request, the connection will lost and the error should in VPN log

```
DPD: received old or duplicate R_U_THERE
DPD: received less than 3 duplicate R_U_THERE's - will reluctantly answer
```

Here is how I do it.
in jump server

```
VPN_IP=x.x.x.x
ssh -fNT -L 127.0.0.1:500:127.0.0.1:500 -L 127.0.0.1:4500:127.0.0.1:4500 -L 127.0.0.1:1701:127.0.0.1:1701 root@$VPN_IP
socat -T15 udp4-recvfrom:500,reuseaddr,fork tcp:127.0.0.1:500 &
socat -T15 udp4-recvfrom:4500,reuseaddr,fork tcp:127.0.0.1:4500 &
socat -T15 udp4-recvfrom:1701,reuseaddr,fork tcp:127.0.0.1:1701 &
```

in VPN server
```
VPN_IP=x.x.x.x
socat tcp4-listen:500,reuseaddr,fork udp:$VPN_IP:500 &
socat tcp4-listen:4500,reuseaddr,fork udp:$VPN_IP:4500 &
socat tcp4-listen:1701,reuseaddr,fork udp:$VPN_IP:1701 &
```

Then in my laptop, I do vpn connect to jump server, connect success, but as soon as I do a network request, connection will lose. 
Hope somebody can help me with the configuration here, thanks

**Comment by letoams** [comment]
Looks like your ssh tunnel is causing retransmits or you are connecting using a  raccoon (ios < 7 or FreeBSD?)

You will want to disable dpd because it might trigger false positives and bring down the tunnel.

Ssh has a way of being used as a “real” VPN too, so I would use that and avoid the tunneling via a tcp tunnel setup where you have two tcp streams doing retransmits and fighting 

Paul

**Comment by quick-sort** [comment]
> Looks like your ssh tunnel is causing retransmits or you are connecting using a raccoon (ios < 7 or FreeBSD?) You will want to disable dpd because it might trigger false positives and bring down the tunnel. Ssh has a way of being used as a “real” VPN too, so I would use that and avoid the tunneling via a tcp tunnel setup where you have two tcp streams doing retransmits and fighting Paul Sent from mobile device
> […](#)
> On Jun 4, 2019, at 06:39, quick-sort ***@***.***> wrote: If I establish a VPN server outside China and connect directly to it, the GFW will ban the VPN IP soon. Since ssh is safe from GFW, I think maybe I could do a SSH tcp port forwarding(500, 4500, 1701) first from a domestic jump server to the VPN server. I use socat to do tcp <-> udp convert. After it has been done, I can vpn connect to the domestic server successfully, but when I make a network request, the connection will lost and the error should in VPN log ''' DPD: received old or duplicate R_U_THERE DPD: received less than 3 duplicate R_U_THERE's - will reluctantly answer ''' Here is how I do it. in jump server ''' VPN_IP=x.x.x.x ssh -fNT -L 127.0.0.1:500:127.0.0.1:500 -L 127.0.0.1:4500:127.0.0.1:4500 -L 127.0.0.1:1701:127.0.0.1:1701 root@$VPN_IP socat -T15 udp4-recvfrom:500,reuseaddr,fork tcp:127.0.0.1:500 & socat -T15 udp4-recvfrom:4500,reuseaddr,fork tcp:127.0.0.1:4500 & socat -T15 udp4-recvfrom:1701,reuseaddr,fork tcp:127.0.0.1:1701 & ''' in VPN server ''' VPN_IP=x.x.x.x socat tcp4-listen:500,reuseaddr,fork udp:$VPN_IP:500 & socat tcp4-listen:4500,reuseaddr,fork udp:$VPN_IP:4500 & socat tcp4-listen:1701,reuseaddr,fork udp:$VPN_IP:1701 & ''' Then in my laptop, I do vpn connect to jump server, connect success, but as soon as I do a network request, connection will lose. Hope somebody can help me with the configuration here, thanks — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

I am using native MacOS VPN client. I guess it maybe retransmit, but I don't know how it happens, I am still trying to figure out what do these iptables rules written in the vpnsetup.sh mean. Maybe because the VPN connection is initiated from the VPN server itself, due to SSH port forwarding
in the vpnsetup.sh script.
```
  iptables -I FORWARD 5 -i "$NET_IFACE" -d "$XAUTH_NET" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
  iptables -I FORWARD 6 -s "$XAUTH_NET" -o "$NET_IFACE" -j ACCEPT
```
I feel these two rules are suspicious. But I don't know what do they mean to the VPN server.

**Comment by hwdsl2** [comment]
Thanks @letoams!

@quick-sort I am not familiar with this use case. To try disabling dpd as @letoams mentioned, edit `/etc/ipsec.conf` and remove all `dpd*` lines. Then restart the IPsec service. For further questions, please try to seek help from VPN experts on the Libreswan or strongSwan users mailing lists.
