### ISSUE TITLE
Inconsistent connection for different locations (Oakley Transform)

### ISSUE THREAD

**Issue by harryxue1999** [hwdsl2/setup-ipsec-vpn#576]
Since a few days ago, I was suddenly not able to connect to VPN via both XAuth and L2TP in China (but it was fine before). I tried both cellular data and WiFi. I took the liberty of connecting to the same VPN via a remote computer located in the United States, and it worked. 

Below are the logs in `auth.log` for both the successful and unsuccessful attempts. This may have something to do with #379 but that issue offered no verbal solution (instead, a docs update). I have tried the connection on Android, iPhone, and Mac, so this connection problem of China is systematic across all devices. 

Unsuccessful connection (originated from China)
```
Jun  5 12:28:51 hx-main pluto[9707]: "xauth-psk"[1] 0.0.0.0 #1: responding to Main Mode from unknown peer x.x.x.x on port 500
Jun  5 12:28:51 hx-main pluto[9707]: "xauth-psk"[1] 0.0.0.0 #1: Oakley Transform [AES_CBC (256), HMAC_SHA2_384, MODP1024] refused
Jun  5 12:28:51 hx-main pluto[9707]: "xauth-psk"[1] 0.0.0.0 #1: STATE_MAIN_R1: sent MR1, expecting MI2
Jun  5 12:28:54 hx-main pluto[9707]: "xauth-psk"[1] 0.0.0.0 #1: retransmitting in response to duplicate packet; already STATE_MAIN_R1
```

Successful connection (originated from USA)
```
Jun  5 12:50:38 hx-main pluto[9707]: "xauth-psk"[3] 0.0.0.0 #3: responding to Main Mode from unknown peer x.x.x.x on port 42868
Jun  5 12:50:38 hx-main pluto[9707]: "xauth-psk"[3] 0.0.0.0 #3: STATE_MAIN_R1: sent MR1, expecting MI2
Jun  5 12:50:39 hx-main pluto[9707]: "xauth-psk"[3] 0.0.0.0 #3: STATE_MAIN_R2: sent MR2, expecting MI3
Jun  5 12:50:39 hx-main pluto[9707]: "xauth-psk"[3] 0.0.0.0 #3: STATE_MAIN_R2: retransmission; will wait 0.5 seconds for response
Jun  5 12:50:39 hx-main pluto[9707]: "xauth-psk"[3] 0.0.0.0 #3: ignoring informational payload IPSEC_INITIAL_CONTACT, msgid=00000000, length=28
Jun  5 12:50:39 hx-main pluto[9707]: | ISAKMP Notification Payload
Jun  5 12:50:39 hx-main pluto[9707]: |   00 00 00 1c  00 00 00 01  01 10 60 02
Jun  5 12:50:39 hx-main pluto[9707]: "xauth-psk"[3] 0.0.0.0 #3: Peer ID is ID_IPV4_ADDR: '1.2.3.4'
Jun  5 12:50:39 hx-main pluto[9707]: "xauth-psk"[3] 0.0.0.0 #3: switched from "xauth-psk"[3] 0.0.0.0 to "xauth-psk"
Jun  5 12:50:39 hx-main pluto[9707]: "xauth-psk"[4] 0.0.0.0 #3: deleting connection "xauth-psk"[3] 0.0.0.0 instance with peer 0.0.0.0 {isakmp=#0/ipsec=#0}
Jun  5 12:50:39 hx-main pluto[9707]: "xauth-psk"[4] 0.0.0.0 #3: Peer ID is ID_IPV4_ADDR: '1.2.3.4'
Jun  5 12:50:39 hx-main pluto[9707]: "xauth-psk"[4] 0.0.0.0 #3: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA2_256 group=MODP2048}
Jun  5 12:50:39 hx-main pluto[9707]: "xauth-psk"[4] 0.0.0.0 #3: XAUTH: Sending Username/Password request (MAIN_R3->XAUTH_R0)
(Followed by more authentication successes)
```

**Comment by letoams** [comment]
On Wed, 5 Jun 2019, Harry Xue wrote:

> Since a few days ago, I was suddenly not able to connect to VPN via both XAuth and L2TP in China (but it was fine before). I tried both
> cellular data and WiFi. I took the liberty of connecting to the same VPN via a remote computer located in the United States, and it
> worked.
> 
> Below are the logs in auth.log for both the successful and unsuccessful attempts. This may have something to do with #379 but that issue
> offered no verbal solution (instead, a docs update). I have tried the connection on Android, iPhone, and Mac, so this connection problem
> of China is systematic across all devices.
> 
> Unsuccessful connection (originated from China)
> 
> Jun  5 12:28:51 hx-main pluto[9707]: "xauth-psk"[1] 0.0.0.0 #1: responding to Main Mode from unknown peer x.x.x.x on port 500
> Jun  5 12:28:51 hx-main pluto[9707]: "xauth-psk"[1] 0.0.0.0 #1: Oakley Transform [AES_CBC (256), HMAC_SHA2_384, MODP1024] refused
> Jun  5 12:28:51 hx-main pluto[9707]: "xauth-psk"[1] 0.0.0.0 #1: STATE_MAIN_R1: sent MR1, expecting MI2
> Jun  5 12:28:54 hx-main pluto[9707]: "xauth-psk"[1] 0.0.0.0 #1: retransmitting in response to duplicate packet; already STATE_MAIN_R1

This looks like it is trying to use DiffieHellman group 2 (DH2,
modp1024) which is too small and rejected. Are you sure that client
is not misconfigured? You should at least configure to use DH5
(modp1536) for IKEv1.

> Successful connection (originated from USA)
> 
> Jun  5 12:50:38 hx-main pluto[9707]: "xauth-psk"[3] 0.0.0.0 #3: responding to Main Mode from unknown peer x.x.x.x on port 42868
> Jun  5 12:50:38 hx-main pluto[9707]: "xauth-psk"[3] 0.0.0.0 #3: STATE_MAIN_R1: sent MR1, expecting MI2

The error is missing here.

> Jun  5 12:50:39 hx-main pluto[9707]: "xauth-psk"[4] 0.0.0.0 #3: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher
> =AES_CBC_256 integ=HMAC_SHA2_256 group=MODP2048}

And it shows it used DH14 (modp2048)

Paul

**Comment by hwdsl2** [comment]
@harryxue1999 Hello! The fact that you can connect from outside China while unable to connect from China indicates that your connection could be blocked by the GFW. The `retransmitting in response to duplicate packet; already STATE_MAIN_R1` in your logs is a hint of that. The issue in #379 is likely also related to GFW, note that the doc update was mainly for addressing #326.

Unfortunately, there is no easy workaround for this, other than using a different solution, such as Shadowsocks.

**Comment by harryxue1999** [comment]
@hwdsl 嗯，仔细一想，这几天敏感，微博海外都不能post。估计过几天就好了

**Comment by harryxue1999** [comment]
Can confirm that the VPN is now working in China
