### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by aminify** [hwdsl2/setup-ipsec-vpn#577]
I'm living somewhere that uses a strict firewall that make it hard to bypass geo blocked content and I'm managing to bypass it. I installed your script on a fresh Ubuntu 18.04 server and it seems like the firewall is able to detect that I'm connecting to a server configured by your script and blocks the connection.
There are VPN sellers here that offer L2TP/IPSec and when I try to connect to them, the connection successfully establishes. I don't know about their configuration but I think they are using windows servers. Is there any way that I can detect exactly what configs they are using and try to make this script use the same?
PS: I can connect to my VPN server after I'm connected to the VPN sellers' server. that's why I believe there is nothing wrong with the setup and it is only a firewall block.

**Comment by hwdsl2** [comment]
@aminify Hello! It would be very difficult to “detect” the setup of VPN providers. What happened in your use case could be that the “strict firewall” keeps a list of server providers and block all IPs from them. Your server provider might be on that list (hence you are blocked from geo restricted contents while on your VPN), while IPs from the VPN seller are not.

**Comment by aminify** [comment]
I'm sure that my ip is not blocked. I mannually ran services on port 1701 for example and it was accessible. I also checked that on multiple servers with different locations. my guess is that certain L2TP/IPSec scenario is detectable by them and they drop packets to disallow the connection. could you please tell me how I can use different possible configurations to see which works the best?
I'm not familiar with L2TP/IPSec but for example for PPTP some changes in /etc/ppp/options.pptp about MPPE and CHAP or MSCHAP was the solution
can you help me try different configurations for this setup?

**Comment by hwdsl2** [comment]
@aminify L2TP/IPsec traffic is not difficult to detect due to using UDP ports 500 and 4500. Also there aren't different IPsec/L2TP "scenarios" other than using different ciphers. For your use case, you may want to consider alternative solutions such as Shadowsocks.

**Comment by MohammadaminMMZ** [comment]
Thanks for your answer
Actually my options are only pptp and l2tp since I want to set it up on router and my router (most routers) only support those two. Pptp works fine but the connection is not as stable and I get highly variable ping time. I think it's because it uses TCP instead of UDP.
Can you please tell me how to try those "different ciphers"?
Which configuration files should I touch? It should be related to both l2tp and ipsec files, right?

**Comment by hwdsl2** [comment]
@MohammadaminMMZ See the Libreswan `ipsec.conf` documentation [1], specifically the `ike` and `phase2alg` sections. The related configuration file on your server is `/etc/ipsec.conf`. You'll need to restart the IPsec service: `service ipsec restart` after making changes. Keep a backup of the original file in case you need to restore the configuration. To check the logs, see [2].

You can try the above but I don't think changing the ciphers would help your use case.

[1] https://libreswan.org/man/ipsec.conf.5.html
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps
