### ISSUE TITLE
How to configure Firewalld instead of the iptables in rc.local

### ISSUE THREAD

**Issue by kewlooc** [hwdsl2/setup-ipsec-vpn#58]
@hwdsl2 thanks for your work!
I want to use firewalld to instead of iptables. In your script , you use iptables and add it in the rc.local. i deleted it ! I Now i can connect to the vpn server but i cannot surf the Internet. I have already opened the needed port(500,4500). I support that is a NAT setup missing. I use 'firewall-cmd --permanent --direct --add-rule ipv4 nat POSTROUTING 0 -s 192.168.43.0/24 -o eth+ -m policy --dir out --pol none -j SNAT --to-source $my_server_ip' ... it seems right after reload firewalld.. But it dosenot work!!
After a long time search and read the firewalld man page, i still cannot find a way. Could you give me a favour!? Thank you !

**Comment by kewlooc** [comment]
I am so happy i found this : _firewall-cmd --permanent --direct --add-rule ipv4 filter FORWARD 0 -s 192.168.43.0/24 -o eth+ -j ACCEPT_.. Add this and Work!! But i still didn't know WHY!! Could anybody tell me!!!?

**Comment by hwdsl2** [comment]
@kewlooc Hello! Glad to hear it is working. The FORWARD rule is required in case your IPTables FORWARD chain is set to DROP. The NAT rule forwards traffic which must be allowed in the FORWARD chain.

I am not familiar with firewalld but you may need another rule for 192.168.42.0/24 (both in NAT and FORWARD, refer to the IPTables rules in my scripts) if you plan to use IPsec/L2TP in addition IPsec/XAuth. The 192.168.43.0/24 subnet is for IPsec/XAuth only.
