### ISSUE TITLE
l2tp无法连接

### ISSUE THREAD

**Issue by zzuzjl** [hwdsl2/setup-ipsec-vpn#581]
ipsec和ikev2可以正常连接，不过l2tp无法连接，帮我看看怎么解决。
Jun 17 01:12:57 demo pluto[1558]: "l2tp-psk"[13] 36.18.5.224 #13: received Delete SA(0x0d7fc2a2) payload: deleting IPsec State #14
Jun 17 01:12:57 demo pluto[1558]: "l2tp-psk"[13] 36.18.5.224 #14: deleting other state #14 (STATE_QUICK_R2) aged 1.200s and sending notification
Jun 17 01:12:57 demo pluto[1558]: "l2tp-psk"[13] 36.18.5.224 #14: ESP traffic information: in=243B out=443B
Jun 17 01:12:57 demo pluto[1558]: "l2tp-psk" #13: deleting state (STATE_MAIN_R3) aged 2.632s and sending notification
Jun 17 01:12:57 demo pluto[1558]: "l2tp-psk"[13] 36.18.5.224: deleting connection "l2tp-psk"[13] 36.18.5.224 instance with peer 36.18.5.224 {isakmp=#0/ipsec=#0}

**Comment by hwdsl2** [comment]
@zzuzjl 你好！请参见 [1]。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#windows-错误-809

**Comment by zzuzjl** [comment]
我ios和安卓上也都不能连接啊！

**Comment by zzuzjl** [comment]
> @zzuzjl 你好！请参见 [1]。
> 
> [1] [https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#windows-错误-809](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#windows-%E9%94%99%E8%AF%AF-809)
我ios和安卓上也都不能连接啊！

**Comment by zzuzjl** [comment]
> @zzuzjl 你好！请参见 [1]。
> 
> [1] [https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#windows-错误-809](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#windows-%E9%94%99%E8%AF%AF-809)
又增加了xl2tpd日志，帮我看看什么原因

**Comment by hwdsl2** [comment]
@zzuzjl 你的Librewsan日志显示连接成功一秒之后断开，`received Delete SA...`，这个是典型的Windows 错误 809 的问题。需要按照上面链接的步骤操作。如果iOS和安卓不能连接，请提供相应的日志。

**Comment by zzuzjl** [comment]
> @zzuzjl 你的Librewsan日志显示连接成功一秒之后断开，`received Delete SA...`，这个是典型的Windows 错误 809 的问题。需要按照上面链接的步骤操作。如果iOS和安卓不能连接，请提供相应的日志。

日志更新了，这个是安卓在4g下连接的日志，帮我看看什么原因

**Comment by hwdsl2** [comment]
@zzuzjl 看一下你的 xl2tpd 和 ppp 日志。你的问题和这个帖子比较像 [1]。
```
grep -e xl2tpd -e ppp /var/log/syslog
```

可以试一下：
```
mknod /dev/ppp c 108 0
```

[1] https://forum.ipfire.org/viewtopic.php?t=5515

**Comment by zzuzjl** [comment]
> mknod /dev/ppp c 108 0

试了mknod /dev/ppp c 108 0还是不能连接，新日志帮我看看，我是Azure香港Debian9系统上操作的

**Comment by hwdsl2** [comment]
@zzuzjl 你的日志说明确实是上述问题，这个是你的系统的问题：
```
Jun 17 03:14:56 demo pppd[1905]: Couldn't open the /dev/ppp device: No such file or directory
Jun 17 03:14:56 demo pppd[1905]: You need to create the /dev/ppp device node by#012executing the following command as root:#12#011mknod /dev/ppp c 108 0
```

如果 `mknod /dev/ppp c 108 0` 无效，你可以试一下这个解决方案：https://wiki.archlinux.org/index.php/Ppp
参见页面最下端的 `pppd cannot load kernel module ppp_generic` 一节的说明。如果还是不行，建议你更换操作系统，如换成Ubuntu 18.04。

**Comment by zzuzjl** [comment]
> @zzuzjl 你的日志说明确实是上述问题，这个是你的系统的问题：
> 
> ```
> Jun 17 03:14:56 demo pppd[1905]: Couldn't open the /dev/ppp device: No such file or directory
> Jun 17 03:14:56 demo pppd[1905]: You need to create the /dev/ppp device node by#012executing the following command as root:#12#011mknod /dev/ppp c 108 0
> ```
> 
> 如果 `mknod /dev/ppp c 108 0` 无效，你可以试一下这个解决方案：https://wiki.archlinux.org/index.php/Ppp
> 参见页面最下端的 `pppd cannot load kernel module ppp_generic` 一节的说明。如果还是不行，建议你更换操作系统，如换成Ubuntu 18.04。

好吧，我换系统试试吧，谢谢你
