### ISSUE TITLE
you have been disconnected because the PPP server is not responding

### ISSUE THREAD

**Issue by ddi98** [hwdsl2/setup-ipsec-vpn#587]
**using ubuntu 18.4**
hi, after a few minutes of inactivity on iphone this message appears "you have been disconnected because the PPP server is not responding" 
-----
and I get disconnected from the vpn, this happens mainly when I put the iphone in stendby for at least a minute and then react it
-----
I have attached a log screen at the time of disconnection
-----
![Immagine del 21-06-19 alle 12 16](https://user-images.githubusercontent.com/43742625/59916160-b3eb9000-941e-11e9-950a-ac41eb459997.jpg)

-----
this is the error returned on the client side

![IMG_2174](https://user-images.githubusercontent.com/43742625/59916415-61f73a00-941f-11e9-8a5e-69f76f77768f.PNG)

**Comment by letoams** [comment]
Use IKEv2 for iOS and OSX, that way you also have MOBIKE support (for Debian/Ubuntu, mobike requires recompile with XFRM_MIGRATION enabled)

**Comment by ddi98** [comment]
hello, how can I do this? sorry for the question but I'm not well prepared on the subject

**Comment by hwdsl2** [comment]
@ddi98 Hello! For setting up IKEv2, see [1]. The disconnection you described is a known limitation [2] of iOS/Android devices.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#iosandroid-sleep-mode
