### ISSUE TITLE
how can i have one connection per every user?

### ISSUE THREAD

**Issue by mos2fa** [hwdsl2/setup-ipsec-vpn#590]
in "Important notes" you noticed:

> The same VPN account can be used by your multiple devices. However, due to an IPsec/L2TP limitation, if you wish to connect multiple devices simultaneously from behind the same NAT (e.g. home router), you must use only IPsec/XAuth mode.

so i need to one connection per every user in same time, not more!
in this project not have a way for it?
Anyway, how can I have it? There must be a way :)
thanks alot.

**Comment by letoams** [comment]
If you use certificates, those will only be able to connect once. The second one will bump of the first one

**Comment by mos2fa** [comment]
> If you use certificates, those will only be able to connect once. The second one will bump of the first one Sent from mobile device
> […](#)
> On Jun 29, 2019, at 09:33, mos2fa ***@***.***> wrote: in "Important notes" you noticed: The same VPN account can be used by your multiple devices. However, due to an IPsec/L2TP limitation, if you wish to connect multiple devices simultaneously from behind the same NAT (e.g. home router), you must use only IPsec/XAuth mode. so i need to one connection per every user in same time, not more! in this project not have a way for it? Anyway, how can I have it? There must be a way :) thanks alot. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Could you tell me some more?

**Comment by hwdsl2** [comment]
@mos2fa Hello! To use certificates, you can set up IKEv2. See [1].

The "important notes" paragraph you quoted was for a limitation of the IPsec/L2TP mode, where you cannot connecting multiple devices simultaneously from behind the same NAT. Devices from different NATs are not subject to this limitation. Unfortunately, for your use case, I am not aware of any method to limit one connection per user.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md
