### ISSUE TITLE
How can I connect to other nodes on the cluster through vpn?

### ISSUE THREAD

**Issue by JiangWenqi** [hwdsl2/setup-ipsec-vpn#591]
Hello,
Bro.
I already send all traffic over VPN connection on my MBP, but I still can not ping other nodes, like `192.168.2.2`.
Thanks!

**Comment by JiangWenqi** [comment]
My current situation is that after **all my traffic** has passed through vpn, I can access other services on **my machine with VPN service** in browser, such as Web UI of yarn cluster: 192.168.2.x: 8088, but I can not access the services of other nodes (such as 192.168.2.y: 8088).

**Comment by JiangWenqi** [comment]
And besides being able to connect to my node that with VPN service, my mbp has no access to the internet, such as www.baidu.com

**Comment by hwdsl2** [comment]
@JiangWenqi Hello! Accessing other nodes on your VPN server's network requires additional IPTables rules. See [1]. If your VPN server itself has access to the Internet, then in the default setup, your VPN client should have access too (while connected).

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#access-vpn-servers-subnet

**Comment by JiangWenqi** [comment]
@hwdsl2 Hello! Thank you for your reply. But I still haven't solved my problem.
When my macbook (**client**) all traffic has passed through vpn,
- I can ping my **remote** vpn server node (like `192.168.2.4`) , 
- but I can't ping other remote node in the same cluster, like `192.168.2.x`, 
- and I have no way to access the network(like `baidu.com`).
The above are the problems that occur after my macbook uses vpn.

So here is my problem, vpn server node can **access the network**, but I can't use the network except the interaction on the vpn server node.
In addition, I am using centos 7 cluster, the firewall is not `IPTables`, and the firewall is set to open all ports (tcp/udp) between clusters, nodes can be connected freely.
Thanks again!
