### ISSUE TITLE
IKEv2 connected but no traffic while using "Incognito Mode" of  google chrome

### ISSUE THREAD

**Issue by Pyabecedarian** [hwdsl2/setup-ipsec-vpn#592]
I setup successfully ikev2 vpn server on GCP (OS: Debian9). It works great on my computer (Windows 10) except "Incognito Mode" of google chrome, and Microsofe Edge (or maybe other internet browser but I didn't test it).

Is this a bug or just normal?

**Comment by letoams** [comment]
On Tue, 2 Jul 2019, Pyabecedarian wrote:

> I setup successfully ikev2 vpn server on GCP (OS: Debian9). It works great on my computer (Windows 10) except "Incognito Mode" of google chrome, and Microsofe Edge (or maybe other internet browser but I
> didn't test it).

Incognito Mode only changes the HTTP/HTTPS header and body information.
The fact that the HTTP/HTTPS is transported within ESP/IPsec should not
make any difference at all. The only "wire" change that is possible as
a result of using a VPN is a slihtly lower MTU size. But how would that
affect Incognito Mode?

Paul

**Comment by Pyabecedarian** [comment]
> On Tue, 2 Jul 2019, Pyabecedarian wrote: I setup successfully ikev2 vpn server on GCP (OS: Debian9). It works great on my computer (Windows 10) except "Incognito Mode" of google chrome, and Microsofe Edge (or maybe other internet browser but I didn't test it).
> Incognito Mode only changes the HTTP/HTTPS header and body information. The fact that the HTTP/HTTPS is transported within ESP/IPsec should not make any difference at all. The only "wire" change that is possible as a result of using a VPN is a slihtly lower MTU size. But how would that affect Incognito Mode? Paul

Thanks your reply Paul, but actually I don't know what's going on with my pc.  Now I switched to L2TP mode, it's perfect.
