### ISSUE TITLE
Policy Match Error Windows 10

### ISSUE THREAD

**Issue by mrfsb-usr** [hwdsl2/setup-ipsec-vpn#593]
I am trying to connect in Windows 10 via IKEv2 and it displays the error "Policy Match Error"

![Untitled](https://user-images.githubusercontent.com/50309174/60620949-dbddda80-9db2-11e9-9a3b-f955e496fc2f.png)

**Comment by hwdsl2** [comment]
@mrfsb-usr Hello! What is your Windows 10 version? To help troubleshoot, can you post your logs (see [1]) with IPs redacted?

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps

**Comment by mrfsb-usr** [comment]
@hwdsl2 Hi! My version is 1903,I will check the logs, but I think it might be something from the internal network, thanks for the feedback!
