### ISSUE TITLE
Uses 192.168.1.1 for DNS after fresh install

### ISSUE THREAD

**Issue by joelfischerr** [hwdsl2/setup-ipsec-vpn#594]
Directly after a fresh install with the default values for the DNS servers ipsec uses `192.168.1.1` to resolve all DNS queries.

Changing `8.8.8.8` to `1.1.1.1`, `127.0.0.1` or `192.168.42.1` (which should all use a DNS server different from `192.168.1.1`) in both `/etc/ppp/options.xl2tpd` and `/etc/ipsec.conf` and restarting the server with `sudo reboot` and restarting ipsec and xl2tpd with `sudo service xl2tpd restart && sudo service ipsec restart` has not changed the situation.

The DNS queries always show up in the log of the DNS server at `192.168.1.1`.

Is there anything obvious I'm missing?

**Comment by hwdsl2** [comment]
@joelfischerr Hello! What you described is a known issue with the built-in IPsec VPN client in Windows 8.x/10. These OS use "smart multi-homed name resolution" by default, which may cause "DNS leaks" when using the native IPsec VPN client if your DNS servers on the Internet adapter are from the local network segment (in your case, `192.168.1.1`). To fix, you may either disable smart multi-homed name resolution, or configure your computer's Internet adapter to use DNS servers outside your local network (e.g. 8.8.8.8 and 8.8.4.4).

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#windows-810-dns-leaks

**Comment by joelfischerr** [comment]
Thank you for your quick reply. I had the same issue with my iOS devices running iOS 12.3.1. Does the same apply there?
