### ISSUE TITLE
Unable to connect to IPsec server through a Nginx UDP stream reverse proxy

### ISSUE THREAD

**Issue by aofei** [hwdsl2/setup-ipsec-vpn#596]
The `nginx.conf` is roughly as follows:

```nginx
stream {
    # ...
    server {
        listen 500 udp;
        proxy_pass example.com:500;
        # ...
    }

    server {
        listen 4500 udp;
        proxy_pass example.com:4500;
        # ...
    }
    # ...
}
```

I think the purpose of my doing this is obvious, I just want to use a jump server to speed up the connections to the IPsec server. So, I'd like to know, is this stuff not allowed now? If so, is it caused by the IPsec protocol or just the [hwdsl2/setup-ipsec-vpn](https://github.com/hwdsl2/setup-ipsec-vpn)'s limitation?

**Comment by hwdsl2** [comment]
@aofei Hello! It looks like NGINX may not be the right tool for this [1]. Try alternative methods for your use case. For further questions I suggest that you ask the VPN experts on the Libreswan or strongSwan users mailing lists.

[1] https://serverfault.com/questions/892232/nginx-load-balancing-persistance-udp-upstream-ipsec

**Comment by zhangyuheng** [comment]
@aofei I am using the same config you pasted here but **not worked**, I prefer nginx because I can combine other TCP proxy config together.

Here is a workaround: [socat][socat] can also be used for UDP proxy.

```bash
#!/bin/bash

nohup socat UDP4-LISTEN:500,reuseaddr,fork UDP4:hk.{host}:500 >> /var/log/socat-500.log 2>&1 &

nohup socat UDP4-LISTEN:4500,reuseaddr,fork UDP4:hk.{host}:4500 >> /var/log/socat-4500.log 2>&1 &

```

[socat]: https://linux.die.net/man/1/socat

**Comment by aofei** [comment]
@zhangyuheng Thanks for your workaround, it seems to work, I'll try it. 😊

**Comment by mannguyen0107** [comment]
@aofei can you guide me through how you get this to work?
