### ISSUE TITLE
Cannot connect to outside with Ubuntu 18.04

### ISSUE THREAD

**Issue by fx-kirin** [hwdsl2/setup-ipsec-vpn#597]
Thanks for good tutorial to establishing a vpn connection.

As I followed the [instruction](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#configure-linux-vpn-clients-using-the-command-line), the vpn connection worked very fine with ubuntu 16.04 and 18.04 with systemd 237-3ubuntu10.11. But after upgrading to 18.04 and upgrade systemd to 237-3ubuntu10.12, the connection to outside through vpn is not available. It seems nameserver hasn't worked well.

Does anybody know how to fix this problem or having the same problem?

route command shows wrong type of gateway like the output in the link below.

### related link
https://askubuntu.com/questions/1119691/ipsec-l2tp-vpn-causes-resolving-name-server-problem-with-the-latest-systemd-vers

**Comment by hwdsl2** [comment]
@fx-kirin Thanks for reporting. Will try to reproduce this issue when I get a chance.

**Comment by fx-kirin** [comment]
It's been fix with this solution.

```
sudo rm -f /etc/resolv.conf
sudo ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf
reboot
```
It was systemd bug.

https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1624320

https://askubuntu.com/questions/973017/wrong-nameserver-set-by-resolvconf-and-networkmanager
