### ISSUE TITLE
使用选项一配置的数据在哪保存？

### ISSUE THREAD

**Issue by intro2marshall** [hwdsl2/setup-ipsec-vpn#599]
选项 1: 使用脚本随机生成的 VPN 登录凭证 （完成后会在屏幕上显示）
完成后屏幕显示，我以后想查在哪可以查看？

**Comment by hwdsl2** [comment]
@intro2marshall 你好！IPsec PSK （预共享密钥）保存在文件 `/etc/ipsec.secrets`。VPN 用户信息保存在文件 `/etc/ppp/chap-secrets` (IPsec/L2TP) 和 `/etc/ipsec.d/passwd` (IPsec/XAuth)。参见 [1]。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users-zh.md
