### ISSUE TITLE
VPN was failing to start - libcurl3-nss missing

### ISSUE THREAD

**Issue by cdlenfert** [hwdsl2/setup-ipsec-vpn#601]
I run a music server on my box called [forked-daapd](https://github.com/ejurgensen/forked-daapd) and it includes Spotify integration. One requirement to build in this integration is installing `libcurl4-gnutls-dev`. However when I install that dependency I believe it removes/breaks the VPN by removing `libcurl3-nss`. When I run the VPN install script it reverses the situation and breaks forked-daapd's Spotify integration by removing `libcurl4-gnutls-dev`. 

Is there some way to make these 2 services play nicely together?

**Comment by hwdsl2** [comment]
@cdlenfert Hello! Unfortunately I did not find a workaround for your particular use case, which is to have both `libcurl3` and `libcurl4` installed.
