### ISSUE TITLE
how set user limits and set credit day??

### ISSUE THREAD

**Issue by rezat78** [hwdsl2/setup-ipsec-vpn#602]
hi i was sell this vpn 
i need set day and user limited 
can you help me

**Comment by letoams** [comment]
You can customize the updown script to report traffic statistics to your own backend. And you can hook up pam-authorize=yes via /etc/pam.d/pluto for additional user checks from your backend and deny them when they exceed traffic.

The contrib directory of libreswan has an updown example 

Paul

**Comment by rezat78** [comment]
why i use /etc/.... i see this error 
primmition dimdedd
sorry my english is bad

**Comment by rezat78** [comment]
i want set credit like 31 days
and limited user like 2 user online at same time

**Comment by hwdsl2** [comment]
@rezat78 Hello! This feature is outside the scope of this project.
