### ISSUE TITLE
when lockdown the my iPhone screen，the vpn(or maybe phone) will bedisconnected，how to keep it connected

### ISSUE THREAD

**Issue by windancerzc** [hwdsl2/setup-ipsec-vpn#603]
is this the phone setting problem or the vpn server setting problem？

**Comment by windancerzc** [comment]
and actually the reason is that i dont use the vpn for a while and the vpn icon disappeared

**Comment by hwdsl2** [comment]
@windancerzc Hello! This is a known limitation [1] of iOS devices.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#iosandroid-sleep-mode
