### ISSUE TITLE
how can i get the user login history?

### ISSUE THREAD

**Issue by weishuaiwang** [hwdsl2/setup-ipsec-vpn#607]
can i get the user login history info, and even the commands from login users?

**Comment by letoams** [comment]
Users do not login, they just sent packets

**Comment by weishuaiwang** [comment]
well ,how do the vpn server capture datas and format it for user read？-------- 原始邮件 --------主题：Re: [hwdsl2/setup-ipsec-vpn] how can i get the user login history? (#607)发件人："Paul Wouters (libreswan)" 收件人：hwdsl2/setup-ipsec-vpn 抄送：vince ,Author Users do not login, they just sent packets

**Comment by letoams** [comment]
On Sat, 10 Aug 2019, vince wrote:

> well ,how do the vpn server capture datas and format it for user read？-

IP packets. It is like a router, except it also encrypts/decrypts
packets.

If you want to look at the packet stream, then you are basically
creating a Man-in-the-Middle (MITM) eavesdropping device.

the updown script logs when the user brings up and down the VPN tunnel,
and logs the amount of traffic sent/received. If you only need that,
you can get it from the logs, or write a custom updown hook that sends
information to a personal REST based server or something.

But that is all out of scope for this project.

Paul


------- 原始邮件 --------主题：Re: [hwdsl2/setup-ipsec-vpn] how
> can i get the user login history? (#607)发件人："Paul Wouters (libreswan)" 收件人：hwdsl2/setup-ipsec-vpn 抄送：vince ,Author Users do
> not login, they just sent packets
> 
> Sent from mobile device
>

**Comment by hwdsl2** [comment]
Thanks @letoams!

@weishuaiwang This is out of scope for this project.

**Comment by weishuaiwang** [comment]
but the log file had not contains the username, just the time and some other data i dont need-------- 原始邮件 --------主题：Re: [hwdsl2/setup-ipsec-vpn] how can i get the user login history? (#607)发件人："Paul Wouters (libreswan)" 收件人：hwdsl2/setup-ipsec-vpn 抄送：vince ,Author On Sat, 10 Aug 2019, vince wrote:



> well ,how do the vpn server capture datas and format it for user read？-



IP packets. It is like a router, except it also encrypts/decrypts

packets.



If you want to look at the packet stream, then you are basically

creating a Man-in-the-Middle (MITM) eavesdropping device.



the updown script logs when the user brings up and down the VPN tunnel,

and logs the amount of traffic sent/received. If you only need that,

you can get it from the logs, or write a custom updown hook that sends

information to a personal REST based server or something.



But that is all out of scope for this project.



Paul





------- 原始邮件 --------主题：Re: [hwdsl2/setup-ipsec-vpn] how

> can i get the user login history? (#607)发件人："Paul Wouters (libreswan)" 收件人：hwdsl2/setup-ipsec-vpn 抄送：vince ,Author Users do

> not login, they just sent packets

> 

> Sent from mobile device

>
