### ISSUE TITLE
丢包率很高

### ISSUE THREAD

**Issue by insoz** [hwdsl2/setup-ipsec-vpn#610]
docker 镜像和一键脚本都安装测试后发现丢包率一直在10%-20%之间, 请问有解决办法吗? 
我自己找了很久没找到解决办法.

**Comment by hwdsl2** [comment]
@insoz 你好！这个应该是你和服务器之间网络的问题，而不是 VPN 安装脚本的问题。

**Comment by insoz** [comment]
单独测服务器丢包率是正常的, PPTP协议的也是正常的, 一连接L2TP的就丢包, 我也是被搞得很晕, 没找到问题出在哪里.
