### ISSUE TITLE
Link up but no internet

### ISSUE THREAD

**Issue by VictorBurtsev** [hwdsl2/setup-ipsec-vpn#616]
Hi! Link up but no internet (no ping 8.8.8.8 and 8.8.8.4). I think this is bad route? I use only script, no manual fix.

**Server routing table:**

> root@debian-2gb-nbg1-3:~# netstat -nr
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         172.31.1.1      0.0.0.0         UG        0 0          0 eth0
172.31.1.1      0.0.0.0         255.255.255.255 UH        0 0          0 eth0
192.168.42.10   0.0.0.0         255.255.255.255 UH        0 0          0 ppp0

**Client routing table**

> Victors-MacBook-Pro:~ vl_burtsev$ netstat -nr
Routing tables
Internet:
Destination        Gateway            Flags        Refs      Use   Netif Expire
default            link#16            UCS            62        0    ppp0       
default            10.0.0.1           UGScI          11        0     en1       
8.8.4.4            link#16            UHWIi           6       47    ppp0       
8.8.8.8            link#16            UHWIi           6       54    ppp0       
10/24              link#8             UCS             0        0     en1      !
10.0.0.1/32        link#8             UCS             1        0     en1      !
10.0.0.1           b4:86:55:8c:c3:13  UHLWIir         9     7183     en1   1173
10.0.0.5/32        link#8             UCS             0        0     en1      !
116.203.222.3      10.0.0.1           UGHS            4      152     en1       
127                127.0.0.1          UCS             0        0     lo0       
127.0.0.1          127.0.0.1          UH              1      244     lo0       
169.254            link#8             UCS             1        0     en1      !
192.168.42         ppp0               USc             1        0    ppp0       
192.168.42.1       192.168.42.10      UH              0        0    ppp0       
224.0.0/4          link#16            UmCS            1        0    ppp0       
224.0.0/4          link#8             UmCSI           0        0     en1      !
239.255.255.250    link#16            UHmW3I          0        8    ppp0     43
255.255.255.255/32 link#16            UCS             0        0    ppp0       
255.255.255.255/32 link#8             UCSI            0        0     en1      !

> Internet6:
Destination                             Gateway                         Flags         Netif Expire
default                                 fe80::b686:55ff:fe8c:c313%en1   UGcI            en1       
default                                 fe80::%utun0                    UGcI          utun0       
::1                                     ::1                             UHL             lo0       
fe80::%lo0/64                           fe80::1%lo0                     UcI             lo0       
fe80::1%lo0                             link#1                          UHLI            lo0       
fe80::%en1/64                           link#8                          UCI             en1       
fe80::457:1c71:d584:24a9%en1            88:1f:a1:13:4c:a4               UHLI            lo0       
fe80::b686:55ff:fe8c:c313%en1           b4:86:55:8c:c3:13               UHLWIir         en1       
fe80::%awdl0/64                         link#10                         UCI           awdl0       
fe80::2878:5ff:fe4f:cbb1%awdl0          2a:78:5:4f:cb:b1                UHLI            lo0       
fe80::%utun0/64                         fe80::af95:3e71:f0c1:4edb%utun0 UcI           utun0       
fe80::af95:3e71:f0c1:4edb%utun0         link#14                         UHLI            lo0       
ff01::%lo0/32                           ::1                             UmCI            lo0       
ff01::%en1/32                           link#8                          UmCI            en1       
ff01::%awdl0/32                         link#10                         UmCI          awdl0       
ff01::%utun0/32                         fe80::af95:3e71:f0c1:4edb%utun0 UmCI          utun0       
ff02::%lo0/32                           ::1                             UmCI            lo0       
ff02::%en1/32                           link#8                          UmCI            en1       
ff02::%awdl0/32                         link#10                         UmCI          awdl0       
ff02::%utun0/32                         fe80::af95:3e71:f0c1:4edb%utun0 UmCI          utun0

**Comment by VictorBurtsev** [comment]
Connecting syslog:

> Aug 25 17:29:57 debian-2gb-nbg1-3 xl2tpd[4332]: Connection established to 94.25.169.245, 56717.  Local: 40782, Remote: 33 (ref=0/0).  LNS session is 'default'
Aug 25 17:29:57 debian-2gb-nbg1-3 xl2tpd[4332]: write_packet: tty is not open yet.
Aug 25 17:29:58 debian-2gb-nbg1-3 xl2tpd[4332]: start_pppd: I'm running:
Aug 25 17:29:58 debian-2gb-nbg1-3 xl2tpd[4332]: "/usr/sbin/pppd"
Aug 25 17:29:58 debian-2gb-nbg1-3 xl2tpd[4332]: "plugin"
Aug 25 17:29:58 debian-2gb-nbg1-3 xl2tpd[4332]: "pppol2tp.so"
Aug 25 17:29:58 debian-2gb-nbg1-3 xl2tpd[4332]: "pppol2tp"
Aug 25 17:29:58 debian-2gb-nbg1-3 xl2tpd[4332]: "7"
Aug 25 17:29:58 debian-2gb-nbg1-3 xl2tpd[4332]: "pppol2tp_lns_mode"
Aug 25 17:29:58 debian-2gb-nbg1-3 xl2tpd[4332]: "pppol2tp_tunnel_id"
Aug 25 17:29:58 debian-2gb-nbg1-3 xl2tpd[4332]: "40782"
Aug 25 17:29:58 debian-2gb-nbg1-3 xl2tpd[4332]: "pppol2tp_session_id"
Aug 25 17:29:58 debian-2gb-nbg1-3 xl2tpd[4332]: "37221"
Aug 25 17:29:58 debian-2gb-nbg1-3 xl2tpd[4332]: "passive"
Aug 25 17:29:58 debian-2gb-nbg1-3 xl2tpd[4332]: "nodetach"
Aug 25 17:29:58 debian-2gb-nbg1-3 xl2tpd[4332]: "192.168.42.1:192.168.42.10"
Aug 25 17:29:58 debian-2gb-nbg1-3 xl2tpd[4332]: "refuse-pap"
Aug 25 17:29:58 debian-2gb-nbg1-3 xl2tpd[4332]: "auth"
Aug 25 17:29:58 debian-2gb-nbg1-3 xl2tpd[4332]: "require-chap"
Aug 25 17:29:58 debian-2gb-nbg1-3 xl2tpd[4332]: "name"
Aug 25 17:29:58 debian-2gb-nbg1-3 xl2tpd[4332]: "l2tpd"
Aug 25 17:29:58 debian-2gb-nbg1-3 xl2tpd[4332]: "file"
Aug 25 17:29:58 debian-2gb-nbg1-3 xl2tpd[4332]: "/etc/ppp/options.xl2tpd"
Aug 25 17:29:58 debian-2gb-nbg1-3 xl2tpd[4332]: Call established with 94.25.169.245, Local: 37221, Remote: 11922, Serial: 1
Aug 25 17:29:58 debian-2gb-nbg1-3 pppd[4805]: Plugin pppol2tp.so loaded.
Aug 25 17:29:58 debian-2gb-nbg1-3 pppd[4805]: pppd 2.4.7 started by root, uid 0
Aug 25 17:29:58 debian-2gb-nbg1-3 pppd[4805]: Using interface ppp0
Aug 25 17:29:58 debian-2gb-nbg1-3 pppd[4805]: Connect: ppp0 <-->
Aug 25 17:29:58 debian-2gb-nbg1-3 pppd[4805]: Overriding mtu 1500 to 1280
Aug 25 17:29:58 debian-2gb-nbg1-3 pppd[4805]: Overriding mru 1500 to mtu value 1280
Aug 25 17:30:00 debian-2gb-nbg1-3 pppd[4805]: Overriding mtu 1500 to 1280
Aug 25 17:30:01 debian-2gb-nbg1-3 pppd[4805]: Cannot determine ethernet address for proxy ARP
Aug 25 17:30:01 debian-2gb-nbg1-3 pppd[4805]: local  IP address 192.168.42.1
Aug 25 17:30:01 debian-2gb-nbg1-3 pppd[4805]: remote IP address 192.168.42.10

**Comment by hwdsl2** [comment]
@VictorBurtsev Hello! The connection log looks OK. What is your macOS version (e.g. High Sierra, Mojave)? Check the IPTables on the VPN server using: `sudo iptables -nvL; sudo iptables -nvL -t nat`. Also check the Libreswan and xl2tpd logs [1] for errors.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps
