### ISSUE TITLE
Issue with IPsec/XAuth client

### ISSUE THREAD

**Issue by gexijin** [hwdsl2/setup-ipsec-vpn#618]
Hi,
 Thanks for these scripts! Very helpful.
It is very easy to setup.  After creating a VPS on Amazon Lightsail, the L2TP/IPSec protocol works great on my phone and Windows 7 computer.
However, I am having trouble with IPsec/XAuth protocol. Using my Android Phone's cellular network, I can connect to the server, but there is no data transfer. Using wifi, the same phone won't connect at all. Also having trouble on my computer. 
I am not sure what I did wrong or if you guys could actually test the IPsec/XAuth protocol a bit more.  
Thanks again.

**Comment by hwdsl2** [comment]
@gexijin Hello! Try connecting using IPsec/XAuth mode again, then check the Libreswan and xl2tpd logs [1] for errors. Let us know what error you encountered. Also for Android, try these troubleshooting steps [2], including toggling the value of `sha2-truncbug`.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#android-6-and-above
