### ISSUE TITLE
XAuth server configuration, authentication error

### ISSUE THREAD

**Issue by BopaxDev** [hwdsl2/setup-ipsec-vpn#619]
I wanted to try to XAuth configuration with user saved in /etc/ipsec.d/passwd but it says me that user name is incorrect.
From /var/log/auth.log I saw these lines: 
Aug 27 12:02:30 SERVER-1 pluto[25352]: "xauth-psk"[1] 192.168.1.101 #1: Peer ID is ID_IPV4_ADDR: '192.168.1.101'
Aug 27 12:02:30 SERVER-1 pluto[25352]: "xauth-psk"[1] 192.168.1.101 #1: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA2_256 group=MODP2048}
Aug 27 12:02:30 SERVER-1 pluto[25352]: "xauth-psk"[1] 192.168.1.101 #1: XAUTH: Sending Username/Password request (MAIN_R3->XAUTH_R0)
Aug 27 12:02:30 SERVER-1 pluto[25352]: "xauth-psk"[1] 192.168.1.101 #1: XAUTH: password file authentication method requested to authenticate user 'mac_xxx'
Aug 27 12:02:30 SERVER-1 pluto[25352]: "xauth-psk"[1] 192.168.1.101 #1: XAUTH: password file (/etc/ipsec.d/passwd) open.
Aug 27 12:02:30 SERVER-1 pluto[25352]: "xauth-psk"[1] 192.168.1.101 #1: XAUTH: failure user(mac_xxx:xauth-psk)
Aug 27 12:02:30 SERVER-1 pluto[25352]: "xauth-psk"[1] 192.168.1.101 #1: XAUTH: User mac_xxx: Authentication Failed: Incorrect Username or Password
Aug 27 12:02:30 SERVER-1 pluto[25352]: "xauth-psk"[1] 192.168.1.101 #1: Expected MODE_CFG_REPLY is missing username and password attribute
Aug 27 12:02:30 SERVER-1 pluto[25352]: "xauth-psk"[1] 192.168.1.101 #1: XAUTH: Sending Username/Password request (XAUTH_R0->XAUTH_R0)
Aug 27 12:02:30 SERVER-1 pluto[25352]: "xauth-psk"[1] 192.168.1.101 #1: XAUTH: User <unknown>: Authentication Failed (retry 1)
Aug 27 12:02:30 SERVER-1 pluto[25352]: "xauth-psk"[1] 192.168.1.101 #1: received Delete SA payload: self-deleting ISAKMP State #1
Aug 27 12:02:30 SERVER-1 pluto[25352]: "xauth-psk"[1] 192.168.1.101 #1: deleting state (STATE_XAUTH_R0) aged 0.183s and sending notification
Aug 27 12:02:30 SERVER-1 pluto[25352]: packet from 192.168.1.101:4500: deleting connection "xauth-psk"[1] 192.168.1.101 instance with peer 192.168.1.101 {isakmp=#0/ipsec=#0}

But the password and username are equal I don't know why it doesn't work.

Can someone help me please?

**Comment by Lunkeqing** [comment]
why close this issue, seems not resolved

**Comment by BobbyFinland** [comment]
Hey, I'm facing this problem too, have you managed to fix it? If yes i would like to hear how ...
thanks.
The error I'm getting:
XAUTH: Sending Username/Password request (XAUTH_R0->XAUTH_R0)
