### ISSUE TITLE
error in connecting

### ISSUE THREAD

**Issue by mohamad77** [hwdsl2/setup-ipsec-vpn#62]
hi,
I tested script on ubuntu 14.04 and centos 6.8 installed on VPS powered by ESXi and 2 different datacenter.
on all of them script installed successfully but i can not connect to server!
windows error:
> The network connection between your computer and the VPN server could not be established because the remote server is not responding.
I followed Troubleshooting for this error but not resolved.
android error: unsuccessful
on android only one time connected but didn't open any websites(seems problem in iptables and nat rules)

thanks

**Comment by hwdsl2** [comment]
@mohamad77 What is your VPS provider? Does your server have an external firewall? Please check Libreswan logs for possible errors:

```
grep pluto /var/log/auth.log /var/log/secure
```

Other useful commands for troubleshooting:

```
ipsec verify
ipsec status
iptables -nvL; iptables -nvL -t nat
```

**Comment by mohamad77** [comment]
@hwdsl2 thanks for answer.
For IPSec Xauth psk : The problem is from my PC (client) that I can connect but my ISP blocked VPN traffic( similar to great firewall of china) ; is there anyway to bypass it?
But for L2TP/IPsec : I tested on other clients but I couldn't connect to server.
output of command that you sent:
http://paste.ubuntu.com/23212430/

Thanks

**Comment by hwdsl2** [comment]
@mohamad77 Your command output looks normal except for the Libreswan logs, where the VPN client refuses all encryption proposals from the server. Try commenting out the following 3 lines in `/etc/ipsec.conf`: `ike=`, `phase2alg=` and `sha2-truncbug=`, then restarting services using `service ipsec restart` and `service xl2tpd restart`.

If still not working, you may want to look into an alternative solution, such as <a href="https://github.com/shadowsocks/shadowsocks-libev" target="_blank">Shadowsocks</a>, <a href="https://github.com/breakwa11/shadowsocks-rss" target="_blank">ShadowsocksR</a> or <a href="https://github.com/Nyr/openvpn-install" target="_blank">OpenVPN Install</a>.

**Comment by mohamad77** [comment]
after commenting that lines i get this error when conneting to l2tp on windows 10 
the connection was terminated by the remote computer before it could be completed

ipsec status log:
`000 #4: "l2tp-psk"[4] 5.123.246.46:1396 STATE_QUICK_R2 (IPsec SA established); EVENT_SA_EXPIRE in 3600s; newest IPSEC; eroute owner; isakmp#3; idle; import:not set
000 #4: "l2tp-psk"[4] 5.123.246.46 esp.a077397a@5.123.246.46 esp.35417c0b@104.171.114.4 ref=0 refhim=0 Traffic: ESPin=222B ESPout=201B! ESPmax=244B
000 #3: "l2tp-psk"[4] 5.123.246.46:1396 STATE_MAIN_R3 (sent MR3, ISAKMP SA established); EVENT_SA_EXPIRE in 28799s; newest ISAKMP; nodpd; idle; import:not set
`
/var/log/secure:

`Sep 21 17:14:37 algesr pluto[9120]: "l2tp-psk"[5] 5.123.246.46 #5: responding to Main Mode from unknown peer 5.123.246.46
Sep 21 17:14:37 algesr pluto[9120]: "l2tp-psk"[5] 5.123.246.46 #5: OAKLEY_GROUP 20 not supported.  Attribute OAKLEY_GROUP_DESCRIPTION
Sep 21 17:14:37 algesr pluto[9120]: "l2tp-psk"[5] 5.123.246.46 #5: OAKLEY_GROUP 19 not supported.  Attribute OAKLEY_GROUP_DESCRIPTION
Sep 21 17:14:37 algesr pluto[9120]: "l2tp-psk"[5] 5.123.246.46 #5: transition from state STATE_MAIN_R0 to state STATE_MAIN_R1
Sep 21 17:14:37 algesr pluto[9120]: "l2tp-psk"[5] 5.123.246.46 #5: STATE_MAIN_R1: sent MR1, expecting MI2
Sep 21 17:14:37 algesr pluto[9120]: "l2tp-psk"[5] 5.123.246.46 #5: transition from state STATE_MAIN_R1 to state STATE_MAIN_R2
Sep 21 17:14:37 algesr pluto[9120]: "l2tp-psk"[5] 5.123.246.46 #5: STATE_MAIN_R2: sent MR2, expecting MI3
Sep 21 17:14:38 algesr pluto[9120]: "l2tp-psk"[5] 5.123.246.46 #5: Main mode peer ID is ID_IPV4_ADDR: '192.168.43.207'
Sep 21 17:14:38 algesr pluto[9120]: "l2tp-psk"[5] 5.123.246.46 #5: switched from "l2tp-psk"[5] 5.123.246.46 to "l2tp-psk"
Sep 21 17:14:38 algesr pluto[9120]: "l2tp-psk"[6] 5.123.246.46 #5: deleting connection "l2tp-psk"[5] 5.123.246.46 instance with peer 5.123.246.46 {isakmp=#0/ipsec=#0}
Sep 21 17:14:38 algesr pluto[9120]: "l2tp-psk"[6] 5.123.246.46 #5: transition from state STATE_MAIN_R2 to state STATE_MAIN_R3
Sep 21 17:14:38 algesr pluto[9120]: "l2tp-psk"[6] 5.123.246.46 #5: new NAT mapping for #5, was 5.123.246.46:1781, now 5.123.246.46:1396
Sep 21 17:14:38 algesr pluto[9120]: "l2tp-psk"[6] 5.123.246.46 #5: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=aes_256 integ=sha group=MODP2048}
Sep 21 17:14:38 algesr pluto[9120]: "l2tp-psk"[6] 5.123.246.46 #5: Configured DPD (RFC 3706) support not enabled because remote peer did not advertise DPD support
Sep 21 17:14:38 algesr pluto[9120]: "l2tp-psk"[6] 5.123.246.46 #5: the peer proposed: 104.171.114.4/32:17/1701 -> 192.168.43.207/32:17/0
Sep 21 17:14:38 algesr pluto[9120]: "l2tp-psk"[6] 5.123.246.46 #5: NAT-Traversal: received 2 NAT-OA. Using first, ignoring others
Sep 21 17:14:38 algesr pluto[9120]: "l2tp-psk"[6] 5.123.246.46 #6: responding to Quick Mode proposal {msgid:01000000}
Sep 21 17:14:38 algesr pluto[9120]: "l2tp-psk"[6] 5.123.246.46 #6:     us: 104.171.114.4/32===104.171.114.4<104.171.114.4>:17/1701
Sep 21 17:14:38 algesr pluto[9120]: "l2tp-psk"[6] 5.123.246.46 #6:   them: 5.123.246.46[192.168.43.207]:17/1701
Sep 21 17:14:38 algesr pluto[9120]: "l2tp-psk"[6] 5.123.246.46 #6: transition from state STATE_QUICK_R0 to state STATE_QUICK_R1
Sep 21 17:14:38 algesr pluto[9120]: "l2tp-psk"[6] 5.123.246.46 #6: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 transport mode {ESP/NAT=>0x0b3d6bf0 <0xf794a16a xfrm=AES_256-HMAC_SHA1 NATOA=192.168.43.207 NATD=5.123.246.46:1396 DPD=active}
Sep 21 17:14:38 algesr pluto[9120]: "l2tp-psk"[6] 5.123.246.46 #6: Configured DPD (RFC 3706) support not enabled because remote peer did not advertise DPD support
Sep 21 17:14:38 algesr pluto[9120]: "l2tp-psk"[6] 5.123.246.46 #6: transition from state STATE_QUICK_R1 to state STATE_QUICK_R2
Sep 21 17:14:38 algesr pluto[9120]: "l2tp-psk"[6] 5.123.246.46 #6: STATE_QUICK_R2: IPsec SA established transport mode {ESP/NAT=>0x0b3d6bf0 <0xf794a16a xfrm=AES_256-HMAC_SHA1 NATOA=192.168.43.207 NATD=5.123.246.46:1396 DPD=active}
Sep 21 17:14:42 algesr pluto[9120]: "l2tp-psk"[6] 5.123.246.46 #5: received Delete SA(0x0b3d6bf0) payload: deleting IPSEC State #6
Sep 21 17:14:42 algesr pluto[9120]: "l2tp-psk"[6] 5.123.246.46 #5: deleting other state #6 (STATE_QUICK_R2) "l2tp-psk"[6] 5.123.246.46
Sep 21 17:14:42 algesr pluto[9120]: "l2tp-psk"[6] 5.123.246.46 #5: ESP traffic information: in=125B out=116B
Sep 21 17:14:42 algesr pluto[9120]: "l2tp-psk" #5: deleting state (STATE_MAIN_R3)
Sep 21 17:14:42 algesr pluto[9120]: "l2tp-psk"[6] 5.123.246.46: deleting connection "l2tp-psk"[6] 5.123.246.46 instance with peer 5.123.246.46 {isakmp=#0/ipsec=#0}
Sep 21 17:14:42 algesr pluto[9120]: packet from 5.123.246.46:1396: received and ignored empty informational notification payload
`


thanks for your helps and answers

**Comment by hwdsl2** [comment]
@mohamad77 Your logs look normal. Please follow the steps in [1] to resolve this issue.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#windows-error-628

**Comment by mohamad77** [comment]
I followed this link but the problem not resolved.(on iOS and android device can n't connect too)

**Comment by mohamad77** [comment]
I followed this link but the problem not resolved.(on iOS and android device can n't connect too)

**Comment by hwdsl2** [comment]
@mohamad77 Do you have more detailed error info or logs to share? I was thinking that your Windows 10 connection should work after following that troubleshooting step. But it did not. Perhaps as you mentioned, your ISP is blocking VPN traffic.

You may also try other alternatives, such as <a href="https://github.com/Nyr/openvpn-install" target="_blank">OpenVPN Install</a>, <a href="https://github.com/shadowsocks/shadowsocks-libev" target="_blank">Shadowsocks</a> or <a href="https://github.com/breakwa11/shadowsocks-rss" target="_blank">ShadowsocksR</a>.

**Comment by hwdsl2** [comment]
@mohamad77 Hello! I just noticed from your logs that your local LAN network is using IP addresses from the 192.168.43.0/24 subnet, which is disallowed in the VPN configuration. This could be the cause of your VPN issues. Please change your local network to use a different subnet (not 192.168.42.0/24 or 192.168.43.0/24), then try connecting the VPN again.
