### ISSUE TITLE
Proxy IPSec/L2TP PSK server configuration

### ISSUE THREAD

**Issue by BopaxDev** [hwdsl2/setup-ipsec-vpn#620]
Is there a method to create the schema below?

CLIENT   <-----------> VPN SERVER (IPSec/L2TP PSK)  <-----------> PROXY SERVER <----------> INTERNET

Thanks for the response.

**Comment by letoams** [comment]
On Tue, 27 Aug 2019, BopaxDev wrote:

> Is there a method to create the schema below?
> 
> CLIENT <-----------> VPN SERVER (IPSec/L2TP PSK) <-----------> PROXY SERVER <----------> INTERNET

You can use iptables to (transparently) DNAT All addresspool IP's packets
with destination port 80 to your local proxy. But with current prevalent
HTTPS, your proxy will basically not be used.

You can install proxies on the clients (eg SOCKS proxies) that prevent
this and allow you to better proxy.

Paul

**Comment by BopaxDev** [comment]
I 'll try it

Thanks

**Comment by BopaxDev** [comment]
Can you explain me what I have to add on iptables.rules to do what I want?
I have installed tor on my pc and the proxy server listens on 127.0.0.1:9050 how to pass all requests on vpn server through that ip.

Thanks for response.

**Comment by hwdsl2** [comment]
@BopaxDev Please direct your question to the Libreswan users mailing list [1]. Thanks!

[1] https://lists.libreswan.org/mailman/listinfo

**Comment by aogg** [comment]
> DNAT

Did it work?
