### ISSUE TITLE
我在azure搭建之后连接上了没有网络

### ISSUE THREAD

**Issue by lzlylxy** [hwdsl2/setup-ipsec-vpn#621]
我在azure安装的，500和4500端口也开放了，但是本地连接上之后没有网络

**Comment by hwdsl2** [comment]
@lzlylxy 你好！请问你用的什么客户端（比如Windows, macOS, Android）？另外检查一下服务器上的日志 [1] 是否有错误。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E9%A2%9D%E5%A4%96%E7%9A%84%E6%AD%A5%E9%AA%A4

**Comment by lzlylxy** [comment]
我重新安装了一下 出现
a - libreswan_exit.o

cc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
../../mk/depend.mk:34: recipe for target 'kernel_netlink.o' failed
make[3]: *** [kernel_netlink.o] Error 4
make[3]: *** Waiting for unfinished jobs....
../../mk/targets.mk:69: recipe for target 'base' failed
make[2]: *** [base] Error 2
../mk/targets.mk:69: recipe for target 'recursive-base' failed
make[1]: *** [recursive-base] Error 2
mk/targets.mk:69: recipe for target 'recursive-base' failed
make: *** [recursive-base] Error 2

我用的mac自带vpn，类型思科ipsec

**Comment by hwdsl2** [comment]
@lzlylxy 这个应该是你服务器的内存不足导致的，Libreswan 编译失败：
```
cc: internal compiler error: Killed (program cc1)
```

**Comment by lzlylxy** [comment]
好的 感谢 我试试
