### ISSUE TITLE
ios12.4 can't be connected

### ISSUE THREAD

**Issue by higgsliu** [hwdsl2/setup-ipsec-vpn#622]
The iphone of ios12.4 can't be connected using mobile network, but it can be connected normally after connecting WiFi.

**Comment by hwdsl2** [comment]
@higgsliu Hello! Try connecting using mobile network again, then check the Libreswan and xl2tpd logs [1] for errors.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps

**Comment by higgsliu** [comment]
Aug 29 14:02:11 izt4nhz1bz95kh8jiack6gz pluto[4353]: "xauth-psk"[1] 223.104.63.233 #1: responding to Main Mode from unknown peer 223.104.63.233 on port 58409
Aug 29 14:02:11 izt4nhz1bz95kh8jiack6gz pluto[4353]: "xauth-psk"[1] 223.104.63.233 #1: WARNING: connection xauth-psk PSK length of 9 bytes is too short for sha2_256 PRF in FIPS mode (16 bytes required)
Aug 29 14:02:11 izt4nhz1bz95kh8jiack6gz pluto[4353]: "xauth-psk"[1] 223.104.63.233 #1: STATE_MAIN_R1: sent MR1, expecting MI2
Aug 29 14:02:11 izt4nhz1bz95kh8jiack6gz pluto[4353]: "xauth-psk"[1] 223.104.63.233 #1: STATE_MAIN_R2: sent MR2, expecting MI3
Aug 29 14:02:12 izt4nhz1bz95kh8jiack6gz pluto[4353]: "xauth-psk"[1] 223.104.63.233 #1: STATE_MAIN_R2: retransmission; will wait 0.5 seconds for response
Aug 29 14:02:12 izt4nhz1bz95kh8jiack6gz pluto[4353]: "xauth-psk"[1] 223.104.63.233 #1: STATE_MAIN_R2: retransmission; will wait 1 seconds for response
Aug 29 14:02:13 izt4nhz1bz95kh8jiack6gz pluto[4353]: "xauth-psk"[1] 223.104.63.233 #1: STATE_MAIN_R2: retransmission; will wait 2 seconds for response
Aug 29 14:02:15 izt4nhz1bz95kh8jiack6gz pluto[4353]: "xauth-psk"[1] 223.104.63.233 #1: STATE_MAIN_R2: retransmission; will wait 4 seconds for response
Aug 29 14:02:19 izt4nhz1bz95kh8jiack6gz pluto[4353]: "xauth-psk"[1] 223.104.63.233 #1: STATE_MAIN_R2: retransmission; will wait 8 seconds for response
Aug 29 14:02:27 izt4nhz1bz95kh8jiack6gz pluto[4353]: "xauth-psk"[1] 223.104.63.233 #1: STATE_MAIN_R2: retransmission; will wait 16 seconds for response
Aug 29 14:02:43 izt4nhz1bz95kh8jiack6gz pluto[4353]: "xauth-psk"[1] 223.104.63.233 #1: STATE_MAIN_R2: retransmission; will wait 32 seconds for response
