### ISSUE TITLE
小米手机连接1.1分钟后自动断开

### ISSUE THREAD

**Issue by gao-xiaoyi** [hwdsl2/setup-ipsec-vpn#623]
你好，感谢你的脚本。
我解决了很多的问题，但是现在还是有一个非常麻烦的问题。
我的小米手机在连接IPSEC L2TP时，会固定在1.1分钟后断开，我网上搜索了很久，这个问题好像是安卓手机自身的问题。请问是否有安卓的L2TP VPN客户端？不使用自带VPN应用是否有可能有好转呢？
Aug 30 18:09:06 VPN-SG pppd[20149]: Plugin pppol2tp.so loaded.
Aug 30 18:09:06 VPN-SG pppd[20149]: pppd 2.4.7 started by root, uid 0
Aug 30 18:09:06 VPN-SG pppd[20149]: Using interface ppp0
Aug 30 18:09:06 VPN-SG pppd[20149]: Connect: ppp0 <-->
Aug 30 18:09:06 VPN-SG pppd[20149]: Overriding mtu 1500 to 1280
Aug 30 18:09:06 VPN-SG pppd[20149]: Overriding mru 1500 to mtu value 1280
Aug 30 18:09:06 VPN-SG pppd[20149]: Overriding mtu 1400 to 1280
Aug 30 18:09:06 VPN-SG pppd[20149]: Cannot determine ethernet address for proxy ARP
Aug 30 18:09:06 VPN-SG pppd[20149]: local  IP address 172.17.42.1
Aug 30 18:09:06 VPN-SG pppd[20149]: remote IP address 172.17.42.10
Aug 30 18:10:10 VPN-SG xl2tpd[15219]: Maximum retries exceeded for tunnel 59987.  Closing.
Aug 30 18:10:10 VPN-SG xl2tpd[15219]: Terminating pppd: sending TERM signal to pid 20149
Aug 30 18:10:10 VPN-SG xl2tpd[15219]: Connection 43033 closed to 113.111.53.144, port 43647 (Timeout)
Aug 30 18:10:10 VPN-SG pppd[20149]: Terminating on signal 15
Aug 30 18:10:10 VPN-SG pppd[20149]: Connect time 1.1 minutes.
Aug 30 18:10:10 VPN-SG pppd[20149]: Sent 97773 bytes, received 26153 bytes.
Aug 30 18:10:10 VPN-SG pppd[20149]: Overriding mtu 1500 to 1280
Aug 30 18:10:10 VPN-SG pppd[20149]: Overriding mru 1500 to mtu value 1280
Aug 30 18:10:11 VPN-SG pppd[20149]: Connection terminated.
Aug 30 18:10:11 VPN-SG pppd[20149]: Exit.
Aug 30 18:10:15 VPN-SG xl2tpd[15219]: Unable to deliver closing message for tunnel 59987. Destroying anyway.

**Comment by hwdsl2** [comment]
@gao-xiaoyi 你好！试一下把服务器上的 `/etc/ipsec.conf` 中的 `sha2-truncbug=yes` 换成 `sha2-truncbug=no`。参见 [1] 中的第二项。另外检查一下 Libreswan 日志 [2] 是否有错误？

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#android-6-%E5%8F%8A%E4%BB%A5%E4%B8%8A%E7%89%88%E6%9C%AC
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E9%A2%9D%E5%A4%96%E7%9A%84%E6%AD%A5%E9%AA%A4

**Comment by gao-xiaoyi** [comment]
你好，小米在某一次更新后，已经解决了自动断开的问题。
近期我发现部分手机是完全正常使用的。
但是使用完全相同的配置，在其他手机上确无法连接，以下为无法连接的手机日志信息，恳请帮忙检查问题所在。


配置：
名称：123
类型：L2TP/IPSec PSK
服务器地址：47.88.159.123
L2TP密钥：
IPsec标识码：
预共享密钥：XXX
用户名：XXX
密码：XXX





Aug&nbsp; 3 15:24:21 VPN-SG pluto[1460]: "l2tp-psk"[518] 14.27.33.118 #647: responding to Main Mode from unknown peer 14.27.33.118 on port 42331
Aug&nbsp; 3 15:24:21 VPN-SG pluto[1460]: "l2tp-psk"[518] 14.27.33.118 #647: STATE_MAIN_R1: sent MR1, expecting MI2
Aug&nbsp; 3 15:24:22 VPN-SG pluto[1460]: "l2tp-psk"[518] 14.27.33.118 #647: STATE_MAIN_R2: sent MR2, expecting MI3
Aug&nbsp; 3 15:24:22 VPN-SG pluto[1460]: "l2tp-psk"[518] 14.27.33.118 #647: Peer ID is ID_IPV4_ADDR: '10.18.187.71'
Aug&nbsp; 3 15:24:22 VPN-SG pluto[1460]: "l2tp-psk"[518] 14.27.33.118 #647: switched from "l2tp-psk"[518] 14.27.33.118 to "l2tp-psk"
Aug&nbsp; 3 15:24:22 VPN-SG pluto[1460]: "l2tp-psk"[519] 14.27.33.118 #647: deleting connection "l2tp-psk"[518] 14.27.33.118 instance with peer 14.27.33.118 {isakmp=#0/ipsec=#0}
Aug&nbsp; 3 15:24:22 VPN-SG pluto[1460]: "l2tp-psk"[519] 14.27.33.118 #647: Peer ID is ID_IPV4_ADDR: '10.18.187.71'
Aug&nbsp; 3 15:24:22 VPN-SG pluto[1460]: "l2tp-psk"[519] 14.27.33.118 #647: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA2_256 group=MODP1024}
Aug&nbsp; 3 15:24:22 VPN-SG pluto[1460]: "l2tp-psk"[519] 14.27.33.118 #647: ignoring informational payload IPSEC_INITIAL_CONTACT, msgid=00000000, length=28
Aug&nbsp; 3 15:24:22 VPN-SG pluto[1460]: | ISAKMP Notification Payload
Aug&nbsp; 3 15:24:22 VPN-SG pluto[1460]: |&nbsp; &nbsp;00 00 00 1c&nbsp; 00 00 00 01&nbsp; 01 10 60 02
Aug&nbsp; 3 15:24:22 VPN-SG pluto[1460]: "l2tp-psk"[519] 14.27.33.118 #647: received and ignored notification payload: IPSEC_INITIAL_CONTACT
Aug&nbsp; 3 15:24:23 VPN-SG pluto[1460]: "l2tp-psk"[519] 14.27.33.118 #647: the peer proposed: 47.88.159.123/32:17/1701 -&gt; 10.18.187.71/32:17/0
Aug&nbsp; 3 15:24:23 VPN-SG pluto[1460]: "l2tp-psk"[519] 14.27.33.118 #648: responding to Quick Mode proposal {msgid:a839c63c}
Aug&nbsp; 3 15:24:23 VPN-SG pluto[1460]: "l2tp-psk"[519] 14.27.33.118 #648:&nbsp; &nbsp; &nbsp;us: 172.21.22.10[47.88.159.123]:17/1701
Aug&nbsp; 3 15:24:23 VPN-SG pluto[1460]: "l2tp-psk"[519] 14.27.33.118 #648:&nbsp; &nbsp;them: 14.27.33.118[10.18.187.71]:17/0
Aug&nbsp; 3 15:24:23 VPN-SG pluto[1460]: "l2tp-psk"[519] 14.27.33.118 #648: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 transport mode {ESP/NAT=&gt;0x040b4a73 <0x7c293a82 xfrm=AES_CBC_128-HMAC_SHA2_256_128 NATOA=none NATD=14.27.33.118:42460 DPD=active}
Aug&nbsp; 3 15:24:24 VPN-SG pluto[1460]: "l2tp-psk"[519] 14.27.33.118 #648: STATE_QUICK_R2: IPsec SA established transport mode {ESP/NAT=&gt;0x040b4a73 <0x7c293a82 xfrm=AES_CBC_128-HMAC_SHA2_256_128 NATOA=none NATD=14.27.33.118:42460 DPD=active}







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hwdsl2/setup-ipsec-vpn"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2019年9月9日(星期一) 上午10:26
收件人:&nbsp;"hwdsl2/setup-ipsec-vpn"<setup-ipsec-vpn@noreply.github.com&gt;;
抄送:&nbsp;"高晓义"<215662413@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [hwdsl2/setup-ipsec-vpn] 小米手机连接1.1分钟后自动断开 (#623)




Closed #623.

**Comment by hwdsl2** [comment]
@gao-xiaoyi 你好！从你的日志来看，可以试一下切换服务器上的 `/etc/ipsec.conf` 中的 `sha2-truncbug` 的值。参见 [1] 中的第二项。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#android-6-%E5%92%8C-7

**Comment by gao-xiaoyi** [comment]
已解决，非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hwdsl2/setup-ipsec-vpn"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月4日(星期二) 上午10:48
收件人:&nbsp;"hwdsl2/setup-ipsec-vpn"<setup-ipsec-vpn@noreply.github.com&gt;;
抄送:&nbsp;"高晓义"<215662413@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [hwdsl2/setup-ipsec-vpn] 小米手机连接1.1分钟后自动断开 (#623)





 
@gao-xiaoyi 你好！从你的日志来看，可以试一下切换服务器上的 /etc/ipsec.conf 中的 sha2-truncbug 的值。参见 [1] 中的第二项。
 
[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#android-6-%E5%92%8C-7
