### ISSUE TITLE
ec2 服务器centos7 系统上安装成功后，mac和iOS手机无法连接 

### ISSUE THREAD

**Issue by cqtoo** [hwdsl2/setup-ipsec-vpn#624]
服务器已放开UDP 500 、4500

客户端显示：  L2TP-VPN 服务器没有响应。请尝试重新连接。如果仍然有问题，请验证您的设置并与管理员联系。

请问 是安装不成功吗？,
使用UDP端口检测是正常的（IP做了处理）：
nc -vuz 52.199.*.* 500
found 0 associations
found 1 connections:
     1:	flags=82<CONNECTED,PREFERRED>
	outif (null)
	src 192.168.1.226 port 55383
	dst 52.199.*.* port 500
	rank info not available

Connection to 52.199.*.* port 500 [udp/isakmp] succeeded!

**Comment by hwdsl2** [comment]
@cqtoo 你好！再次尝试连接你的 VPN 客户端，然后检查一下服务器上的 Libreswan 和 xl2tpd 日志 [2] 是否有错误？

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E9%A2%9D%E5%A4%96%E7%9A%84%E6%AD%A5%E9%AA%A4
