### ISSUE TITLE
Automated or simpler command-line, Linux-vpn-client disconnect/reconnect solution?

### ISSUE THREAD

**Issue by johnnyutahh** [hwdsl2/setup-ipsec-vpn#626]
[An aside: many,  _many_ thanks for launching this project and delivering this software and documentation; we find it tremendously helpful. We greatly appreciate the efforts by all the contributors.]

**Question: _is there some existing software, even if it's an individual's simple script utility or similar, which automates the vpn-client connection/disconnect (and the associated error handling) including after client-system reboot?_**

Our vpn-client-side OS = Ubuntu 18.04.2 LTS.

Details:

The "needs to be run every time one makes a VPN-client-connection" section of the ["Configure Linux VPN clients using the command line" procedure](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#configure-linux-vpn-clients-using-the-command-line) is too complex for a human to execute every time. My team will need to write a script (or some such) to automate it, but we would like to avoid this. We are fine with the one-time installation/configuration effort, even if we have to write a script for that--although we'd like to find some client automation which handles this, too.

Does not strongSwan or some similar package provide automation to perform the disconnection/reconnection?  (Initial searches have not found anything, but I'm far from perofmring a comprehensive search. I thought it best to ask here first to see if someone's already been down this path, before I spend much more time searching.)

Our vpn client environment in this case are headless VPS machines where it's difficult to setup or at least use a GUI interface. Further, we want to be able to auto-deploy these types of systems with command-line automation (with a configuration-management/auto-deployment tool like Ansible) on a mass scale (ie, a large number of these Ubuntu 18.04.2 machines), which makes it difficult if not impossible to run a gui.

I've also done some searches (again: _not_ comprehensive in any way) through the [issues archive for this project](https://github.com/hwdsl2/setup-ipsec-vpn/issues) but have not yet found anything. 

Thanks for any help/tips/pointers.

**Comment by letoams** [comment]
auto=start in the vpn client configuration in either libreswan or strongswan will start the vpn connection when the ipsec service starts on the machine.

Paul

**Comment by johnnyutahh** [comment]
Thanks Paul, especially for the timely reply.

All- should `auto=start` be mentioned in the [setup procedure](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#configure-linux-vpn-clients-using-the-command-line
)?

> `auto=start` in the vpn client configuration in either libreswan or strongswan will start
> the vpn connection when the ipsec service starts on the machine.
>
> Paul
> Sent from mobile device

**Comment by hwdsl2** [comment]
@johnnyutahh Thank you for the suggestion. For your use case, it makes sense to set `auto=start`, if you can use a script to automate the connection steps in [1]. For the general use case, leaving `auto=start` out makes sense because as mentioned in [1], the user will still need to perform the manual steps to connect to L2TP after the IPsec tunnel is established.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#configure-linux-vpn-clients-using-the-command-line
