### ISSUE TITLE
我能否限制我的终端连接上ipsec-vpn后，仅部分流量经vpn而不是全部流量

### ISSUE THREAD

**Issue by cdy668** [hwdsl2/setup-ipsec-vpn#627]
我能否单独做路由推送或者是否具备配置黑白名单的功能？

**Comment by hwdsl2** [comment]
@cdy668 你好！你可以将通过 VPN 服务器的流量限制为指定的子网，通过更改 `/etc/ipsec.conf` 中的 `leftsubnet` 实现。完成后重启 ipsec 服务。参见 [1]。不支持更复杂的配置。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/issues/514

**Comment by cdy668** [comment]
我是通过容器跑的，setup-ipsec-vpn是否允许我将/etc/ipsec.conf文件映射至本地，而不影响它正常运行。leftsubnet变量是否允许我配置多个子网，例如192.168.1.0/24,172.16.1.0/24

**Comment by cdy668** [comment]
> @cdy668 你好！你可以将通过 VPN 服务器的流量限制为指定的子网，通过更改 `/etc/ipsec.conf` 中的 `leftsubnet` 实现。完成后重启 ipsec 服务。参见 [1]。不支持更复杂的配置。
> 
> [1] #514
我是通过docker运行服务的，setup-ipsec-vpn是否允许我将/etc/ipsec.conf文件映射至本地，而不影响它正常运行。leftsubnet变量是否允许我配置多个子网，例如192.168.1.0/24,172.16.1.0/24

**Comment by hwdsl2** [comment]
@cdy668 比较难映射到本地。你可以自己修改代码后从源代码构建 Docker 映像 [1]，然后用你的新映像重新创建容器。多个子网目前不支持 [2]。

[1] https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#%E9%AB%98%E7%BA%A7%E7%94%A8%E6%B3%95
[2] https://github.com/hwdsl2/setup-ipsec-vpn/issues/530

**Comment by cdy668** [comment]
好的，感谢

**Comment by cdy668** [comment]
> @ cdy668比较难映射到本地。你可以自己修改代码后从源代码构建Docker映像[1]，然后用你的新映像重新创建容器。多个子网目前不支持[2]。
> 
> [1] [https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#%E9%AB%98%E7%BA%A7%E7%94%A8% E6％B3％95](https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README-zh.md#%E9%AB%98%E7%BA%A7%E7%94%A8%E6%B3%95)
> [2] [＃530](https://github.com/hwdsl2/setup-ipsec-vpn/issues/530)

![image](https://user-images.githubusercontent.com/48209708/64587263-50e01880-d3d1-11e9-823f-a95a1121e222.png)
你好，我重新构建了setup-ipsec-vpn容器，在构建之前修改了run.sh的leftsubnet=192.168.100.0/24的子网，但是我在windows7使用
![image](https://user-images.githubusercontent.com/48209708/64587342-a9171a80-d3d1-11e9-9b04-451f4f25c7a4.png)连接到我的vpn服务器时。经过测试，我的流量仍然会全部走ipsec-vpn，而不是192.168.100.0/24的子网，请问是否我的步骤存在问题
