### ISSUE TITLE
undefined reference to `libevent global shutdown'

### ISSUE THREAD

**Issue by buzz3rs** [hwdsl2/setup-ipsec-vpn#628]
i am getting this error when doing 
`sh vpnsetup.sh`

**Comment by hwdsl2** [comment]
@buzz3rs What is your Linux version? e.g. Ubuntu 18.04. Please post the output of:
```
cat /etc/issue
uname -a
```

**Comment by buzz3rs** [comment]
ubuntu 16 lts

**Comment by hwdsl2** [comment]
@buzz3rs Thank you. Can you post the detailed error, including all the error messages?

**Comment by buzz3rs** [comment]
server.o: In function `free_pluto_event_list':
/opt/src/libreswan-3.29/programs/pluto/server.c:682: undefined reference to `libevent_global_shutdown'
collect2: error: ld returned 1 exit status
../../mk/program.mk:120: recipe for target 'pluto' failed
make[3]: *** [pluto] Error 1
../../mk/targets.mk:69: recipe for target 'base' failed
make[2]: *** [base] Error 2
../mk/targets.mk:69: recipe for target 'recursive-base' failed
make[1]: *** [recursive-base] Error 2
mk/targets.mk:69: recipe for target 'recursive-base' failed
make: *** [recursive-base] Error 2
Error: Libreswan 3.29 failed to build.

**Comment by hwdsl2** [comment]
@buzz3rs Cannot reproduce this error on a newly installed Ubuntu 16.04 system. The VPN setup completed without error on the test system.

Try updating your Ubuntu system with `apt-get update && apt-get dist-upgrade`, then reboot and re-run the VPN setup script.

**Comment by buzz3rs** [comment]
i did
