### ISSUE TITLE
希望访问某个网站时不启用vpn，请问该怎么设置呢

### ISSUE THREAD

**Issue by zhegeshijiehuiyouai** [hwdsl2/setup-ipsec-vpn#630]
希望访问某个网站时不启用vpn，请问该怎么设置呢？
有没有白名单或者黑名单之类的控制策略？

**Comment by hwdsl2** [comment]
@zhegeshijiehuiyouai 你好！这个不支持。但是如果你需要将通过 VPN 的流量限制在指定的子网，参见 #627。
