### ISSUE TITLE
ios12.4 和os10.13.6 都无法连接，

### ISSUE THREAD

**Issue by zgqball** [hwdsl2/setup-ipsec-vpn#634]
谢谢作者提供那么强大的脚本。安装的时候一点问题都没有

但是我在连接的时候，出现了问题，手机和电脑都无法连接，尝试了IEKv2 / L2TP / IPsec，都无法链接。
![image](https://user-images.githubusercontent.com/26289539/65024058-ab93ea00-d966-11e9-9822-2e4ffdc5b157.png)
![image](https://user-images.githubusercontent.com/26289539/65024145-d54d1100-d966-11e9-9f9b-a5511a7cbcb0.png)

我的配置：
vpn安装在：阿里云的Ubuntu18.04的ECS
运行脚本部署的vpn

pluto日志：
![image](https://user-images.githubusercontent.com/26289539/65024305-278e3200-d967-11e9-9753-c949f86fd1ec.png)
xl2tpd日志：
![image](https://user-images.githubusercontent.com/26289539/65024330-396fd500-d967-11e9-8046-8ee8100dfaf8.png)
Ipsec状态：
![image](https://user-images.githubusercontent.com/26289539/65024488-8e135000-d967-11e9-9d30-ab657e1608a3.png)
Ipsec确认情况：
![image](https://user-images.githubusercontent.com/26289539/65024524-a08d8980-d967-11e9-8b3e-abef60955deb.png)

请问我是少操作了哪一步吗？
再次谢谢作者的无私奉献

**Comment by zgqball** [comment]
另外 ecs 我已经打开了 4500 500 1701 17 端口

**Comment by zgqball** [comment]
另外 ecs 我已经打开了 4500 500 1701 17 端口 TCP

**Comment by hwdsl2** [comment]
@zgqball 你好！从你的日志来看，客户端的连接请求没有到达 VPN 服务器。你再看一下打开的端口是否正确。参见 #433。端口只需要打开 UDP 500 和 UDP 4500。
