### ISSUE TITLE
Ability to firewall SSH

### ISSUE THREAD

**Issue by ddxor** [hwdsl2/setup-ipsec-vpn#635]
I would like the ability to firewall SSH to the server to only allow connections from a given IP or subnet, or even only allow SSH from connected VPN clients. Really anything other than leaving SSH exposed to the internet would be preferable.

Is this something you could offer guidance on, or even consider adding as a feature?

I've tried all the usual IPTables stuff but I'm hitting the limit of my knowledge there.

**Comment by hwdsl2** [comment]
@ddxor Hello! This feature is outside the scope of this project. To firewall SSH is unrelated to the VPN setup and you will need to look up the information from the web yourself.

**Comment by ddxor** [comment]
@hwdsl2 since this project creates its own custom iptables rules (`/etc/iptables.rules`) I am reluctant to go changing rules outside of this project for feature of breaking future changes in this project.

**Comment by hwdsl2** [comment]
@ddxor Please feel free to edit the IPTables rules on your server according to your needs. Most likely there won't be major changes for the IPTables rules in the script in the near future.

As mentioned in the important notes [1] in the README: To modify the IPTables rules after install, edit /etc/iptables.rules and/or /etc/iptables/rules.v4 (Ubuntu/Debian) (ignore this file if it does not exist on your system), or /etc/sysconfig/iptables (CentOS/RHEL). Then reboot your server.

[1] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes
