### ISSUE TITLE
Iphone wifi下连不上vpn，用电信4G可以连上

### ISSUE THREAD

**Issue by guolibincn** [hwdsl2/setup-ipsec-vpn#636]
用的IPsec，在Mac下同样的Wifi都可以连上。就是iPhone在相同的Wifi下无法连接、但断开Wifi后是可以连接的，请问这是啥问题咋解决呢。
谢谢。

**Comment by guolibincn** [comment]
这是服务器上ipsec status：

● ipsec.service - Internet Key Exchange (IKE) Protocol Daemon for IPsec
   Loaded: loaded (/usr/lib/systemd/system/ipsec.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2019-09-18 09:33:25 EDT; 54min ago
     Docs: man:ipsec(8)
           man:pluto(8)
           man:ipsec.conf(5)
  Process: 1422 ExecStopPost=/usr/local/sbin/ipsec --stopnflog (code=exited, status=0/SUCCESS)
  Process: 1421 ExecStopPost=/sbin/ip xfrm state flush (code=exited, status=0/SUCCESS)
  Process: 1419 ExecStopPost=/sbin/ip xfrm policy flush (code=exited, status=0/SUCCESS)
  Process: 1403 ExecStop=/usr/local/libexec/ipsec/whack --shutdown (code=exited, status=0/SUCCESS)
  Process: 1695 ExecStartPre=/usr/local/sbin/ipsec --checknflog (code=exited, status=0/SUCCESS)
  Process: 1693 ExecStartPre=/usr/local/sbin/ipsec --checknss (code=exited, status=0/SUCCESS)
  Process: 1430 ExecStartPre=/usr/local/libexec/ipsec/_stackmanager start (code=exited, status=0/SUCCESS)
  Process: 1429 ExecStartPre=/usr/local/libexec/ipsec/addconn --config /etc/ipsec.conf --checkconfig (code=exited, status=0/SUCCESS)
 Main PID: 1707 (pluto)
   Status: "Startup completed."
   CGroup: /system.slice/ipsec.service
           └─1707 /usr/local/libexec/ipsec/pluto --leak-detective --config /etc/ipsec.conf --nofork

Sep 18 10:21:26 glb pluto[1707]: "xauth-psk"[18] 118.114.165.107 #34: STATE_MAIN_R2: sent MR2, expecting MI3
Sep 18 10:21:27 glb pluto[1707]: "xauth-psk"[18] 118.114.165.107 #34: STATE_MAIN_R2: retransmission; will wait 0.5 seconds for response
Sep 18 10:21:27 glb pluto[1707]: "xauth-psk"[18] 118.114.165.107 #34: STATE_MAIN_R2: retransmission; will wait 1 seconds for response
Sep 18 10:21:28 glb pluto[1707]: "xauth-psk"[18] 118.114.165.107 #34: STATE_MAIN_R2: retransmission; will wait 2 seconds for response
Sep 18 10:21:30 glb pluto[1707]: "xauth-psk"[18] 118.114.165.107 #34: STATE_MAIN_R2: retransmission; will wait 4 seconds for response
Sep 18 10:21:34 glb pluto[1707]: "xauth-psk"[18] 118.114.165.107 #34: STATE_MAIN_R2: retransmission; will wait 8 seconds for response
Sep 18 10:21:42 glb pluto[1707]: "xauth-psk"[18] 118.114.165.107 #34: STATE_MAIN_R2: retransmission; will wait 16 seconds for response
Sep 18 10:21:58 glb pluto[1707]: "xauth-psk"[18] 118.114.165.107 #34: STATE_MAIN_R2: retransmission; will wait 32 seconds for response
Sep 18 10:22:30 glb pluto[1707]: "xauth-psk"[18] 118.114.165.107 #34: STATE_MAIN_R2: 60 second timeout exceeded after 7 retransmits.  No response (or no acceptable response) to our IKEv1 message
Sep 18 10:22:30 glb pluto[1707]: "xauth-psk"[18] 118.114.165.107 #34: deleting state (STATE_MAIN_R2) aged 64.320s and NOT sending notification

**Comment by guolibincn** [comment]
如果IPHone在wifi里先连上vpn，则mac用相同的wifi就连不上了。用的不同用户名。
貌似是服务不区分同一个网段的多个客户端哇？

**Comment by hwdsl2** [comment]
@guolibincn 你好！你的日志显示数据重发，可能是连接被防火墙干扰了，或者网络不稳定。

在同一个网段 (NAT 后面) 的多个客户端的话，不支持 IPsec/L2TP 模式，要确保所有的客户端都使用 IPsec/XAuth ("Cisco IPsec") 模式连接，不管用户名是否相同。来自不同网段的多个客户端不受此限制。

**Comment by guolibincn** [comment]
@hwdls2 
谢谢你的答复，我客户端都是用的IPsec/XAuth模式。

**Comment by nxtreaming** [comment]
使用IPSec不要期望非常稳定，这是IPSec天生缺陷导致的，他不是设计用来翻墙的，依赖特定端口，很容易被干扰，但这正是由于这点，IPSec只会被干扰，而不会被彻底封杀，因为很多企业用户需要用。
建议用IPSec作为备用（90%的可用性），用其他抗干扰的实现作为主力。
