### ISSUE TITLE
服务器有多个IP，但只能连接主IP使用

### ISSUE THREAD

**Issue by ChromiumX** [hwdsl2/setup-ipsec-vpn#637]
其他的IP连不上分配不到ip地址，只能填写主ip使用

**Comment by hwdsl2** [comment]
@ChromiumX 你好！目前不支持多个IP的用例。

**Comment by ChromiumX** [comment]
服务器启动多个Docker绑定不同ip可以么实现么？

**Comment by hwdsl2** [comment]
@ChromiumX 可以，在你的vpn.env文件中设置 `VPN_PUBLIC_IP=相应的IP`，然后重新创建Docker容器。

**Comment by tik216** [comment]
> @ChromiumX 可以，在你的vpn.env文件中设置 `VPN_PUBLIC_IP=相应的IP`，然后重新创建Docker容器。

具体如何操作，正好有这个需求！非常感谢
