### ISSUE TITLE
consider changing sha2-truncbug to "no" in /etc/ipsec.conf 

### ISSUE THREAD

**Issue by ramrode** [hwdsl2/setup-ipsec-vpn#638]
[An aside: many, many thanks for launching this project and delivering this software and documentation; we find it tremendously helpful. We greatly appreciate the efforts by all the contributors.]

had to change sha2-truncbug to "no" in /etc/ipsec.conf  in order to make VPN work on iOS 13 

you can reference the link below . 

https://forums.developer.apple.com/thread/121193#379874

**Comment by letoams** [comment]
iOS should prefer AES_GCM for ESP and than it is not an issue. Perhaps you configured iOS to use AES-SHA2 by mistake ? 

Paul

**Comment by ramrode** [comment]
there was no issue at all with IOS12 the issue appeared only with ios13 update .

the issue was fixed only after changing sha2-truncbug to "no" in /etc/ipsec.conf .

no other changes has been made to the original  /etc/ipsec.conf produced by vpnsetup.sh .


IPsec.conf content :
```
version 2.0

config setup
  virtual-private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:!192.168.42.0/24,%v4:!192.168.43.0/24
  protostack=netkey
  interfaces=%defaultroute
  uniqueids=no

conn shared
  left=%defaultroute
  leftid=x.x.x.x
  right=%any
  encapsulation=yes
  authby=secret
  pfs=no
  rekey=no
  keyingtries=5
  dpddelay=30
  dpdtimeout=120
  dpdaction=clear
  ike=3des-sha1,3des-sha2,aes-sha1,aes-sha1;modp1024,aes-sha2,aes-sha2;modp1024
  phase2alg=3des-sha1,3des-sha2,aes-sha1,aes-sha2
  sha2-truncbug=no

conn l2tp-psk
  auto=add
  leftprotoport=17/1701
  rightprotoport=17/%any
  type=transport
  phase2=esp
  also=shared

conn xauth-psk
  auto=add
  leftsubnet=0.0.0.0/0
  rightaddresspool=192.168.43.10-192.168.43.250
  modecfgdns="8.8.8.8, 8.8.4.4"
  leftxauthserver=yes
  rightxauthclient=yes
  leftmodecfgserver=yes
  rightmodecfgclient=yes
  modecfgpull=yes
  xauthby=file
  ike-frag=yes
  ikev2=never
  cisco-unity=yes
  also=shared

```

**Comment by letoams** [comment]
change phase2alg= to:

phase2alg=aes_gcm, aes-sha2,aes-sha1,3des-sha1

ios13 added sha2 support to IKEv1, which means with your phase2alg, it will prefer aes-sha-2 and then you have the issue of unfixed android needing truncbug enabled and ios13 needing truncbug disabled.

By adding aes_gcm as first entry, it should pick that one first and avoid the sha2 problem on ios13

**Comment by hwdsl2** [comment]
@letoams The phase2alg line already contains aes_gcm. Maybe it is not being used by iOS13? See:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/vpnsetup.sh#L241

Thanks for the report. Will do further testing on this.

**Comment by letoams** [comment]
In the example above, conn shared did NOT contain aes_gcm

**Comment by ramrode** [comment]
@letoams i tried with aes_gcm with no luck , from my testing the only way to get vpn to work on ios13 is with sha2-truncbug=no .

**Comment by letoams** [comment]
On Thu, 19 Sep 2019, ramrode wrote:

> @letoams i tried with aes_gcm with no luck , from my testing the only way to get vpn to work on ios13 is with
> sha2-truncbug=no .

Hmm, maybe ios only supports AES_GCM for IKEv2, not IKEv1?

Then you might have to add aes-sha2_512 followed by aes-sha2_384 and
leave out aes-sha2 (which is shorthand for aes-sha2_256, which is the
only version that is affected by sha2-truncbug)

This is why RFC 8221 suggests to avoid SHA2_256:

https://tools.ietf.org/html/rfc8221#section-6

    Note that due
    to a long standing common implementation bug of this algorithm that
    truncates the hash at 96 bits instead of 128 bits, it is recommended
    that implementations prefer AUTH_HMAC_SHA2_512_256 over
    AUTH_HMAC_SHA2_256_128 if they implement AUTH_HMAC_SHA2_512_256.

Paul

**Comment by ramrode** [comment]
still the same , i need to keep sha2-truncbug=no for the vpn to work .
