### ISSUE TITLE
I use ikuai router with l2tp, but can't connet

### ISSUE THREAD

**Issue by gavingy33** [hwdsl2/setup-ipsec-vpn#640]
Sep 22 12:39:32 syxzc pluto[1717]: "l2tp-psk"[62] 221.2.56.138 #72: responding to Main Mode from unknown peer 221.2.56.138 on port 500
Sep 22 12:39:32 syxzc pluto[1717]: "l2tp-psk"[62] 221.2.56.138 #72: STATE_MAIN_R1: sent MR1, expecting MI2
Sep 22 12:39:33 syxzc pluto[1717]: "l2tp-psk"[62] 221.2.56.138 #72: STATE_MAIN_R2: sent MR2, expecting MI3
Sep 22 12:39:33 syxzc pluto[1717]: "l2tp-psk"[62] 221.2.56.138 #72: ignoring informational payload IPSEC_INITIAL_CONTACT, msgid=00000000, length=28
Sep 22 12:39:33 syxzc pluto[1717]: | ISAKMP Notification Payload
Sep 22 12:39:33 syxzc pluto[1717]: |   00 00 00 1c  00 00 00 01  01 10 60 02
Sep 22 12:39:33 syxzc pluto[1717]: "l2tp-psk"[62] 221.2.56.138 #72: Peer ID is ID_IPV4_ADDR: '221.2.56.138'
Sep 22 12:39:33 syxzc pluto[1717]: "l2tp-psk"[62] 221.2.56.138 #72: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=AES_CBC_128 integ=HMAC_SHA1 group=MODP2048}
Sep 22 12:39:33 syxzc pluto[1717]: recvfrom 221.2.56.138:4500 too small packet (0)
Sep 22 12:39:33 syxzc pluto[1717]: "l2tp-psk"[62] 221.2.56.138 #72: IKE SA expired (--dontrekey)
Sep 22 12:39:33 syxzc pluto[1717]: "l2tp-psk"[62] 221.2.56.138 #72: deleting state (STATE_MAIN_R3) aged 0.408s and sending notification
Sep 22 12:39:33 syxzc pluto[1717]: deleting connection "l2tp-psk"[62] 221.2.56.138 instance with peer 221.2.56.138 {isakmp=#0/ipsec=#0}
Sep 22 12:39:33 syxzc pluto[1717]: recvfrom 221.2.56.138:4500 too small packet (0)
Sep 22 12:39:33 syxzc pluto[1717]: recvfrom 221.2.56.138:4500 too small packet (0)
Sep 22 12:39:33 syxzc pluto[1717]: "l2tp-psk"[63] 221.2.56.138 #73: responding to Main Mode from unknown peer 221.2.56.138 on port 500
Sep 22 12:39:33 syxzc pluto[1717]: "l2tp-psk"[63] 221.2.56.138 #73: STATE_MAIN_R1: sent MR1, expecting MI2
Sep 22 12:39:33 syxzc pluto[1717]: "l2tp-psk"[63] 221.2.56.138 #73: STATE_MAIN_R2: sent MR2, expecting MI3
Sep 22 12:39:33 syxzc pluto[1717]: "l2tp-psk"[63] 221.2.56.138 #73: ignoring informational payload IPSEC_INITIAL_CONTACT, msgid=00000000, length=28
Sep 22 12:39:33 syxzc pluto[1717]: | ISAKMP Notification Payload
Sep 22 12:39:33 syxzc pluto[1717]: |   00 00 00 1c  00 00 00 01  01 10 60 02
Sep 22 12:39:33 syxzc pluto[1717]: "l2tp-psk"[63] 221.2.56.138 #73: Peer ID is ID_IPV4_ADDR: '221.2.56.138'
Sep 22 12:39:33 syxzc pluto[1717]: "l2tp-psk"[63] 221.2.56.138 #73: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=AES_CBC_128 integ=HMAC_SHA1 group=MODP2048}
Sep 22 12:39:33 syxzc pluto[1717]: "l2tp-psk"[63] 221.2.56.138 #73: IKE SA expired (--dontrekey)
Sep 22 12:39:33 syxzc pluto[1717]: "l2tp-psk"[63] 221.2.56.138 #73: deleting state (STATE_MAIN_R3) aged 0.406s and sending notification
Sep 22 12:39:33 syxzc pluto[1717]: deleting connection "l2tp-psk"[63] 221.2.56.138 instance with peer 221.2.56.138 {isakmp=#0/ipsec=#0}
Sep 22 12:39:33 syxzc pluto[1717]: "l2tp-psk"[64] 221.2.56.138 #74: responding to Main Mode from unknown peer 221.2.56.138 on port 500
Sep 22 12:39:33 syxzc pluto[1717]: "l2tp-psk"[64] 221.2.56.138 #74: STATE_MAIN_R1: sent MR1, expecting MI2
Sep 22 12:39:34 syxzc pluto[1717]: "l2tp-psk"[64] 221.2.56.138 #74: STATE_MAIN_R2: sent MR2, expecting MI3
Sep 22 12:39:34 syxzc pluto[1717]: "l2tp-psk"[64] 221.2.56.138 #74: ignoring informational payload IPSEC_INITIAL_CONTACT, msgid=00000000, length=28
Sep 22 12:39:34 syxzc pluto[1717]: | ISAKMP Notification Payload
Sep 22 12:39:34 syxzc pluto[1717]: |   00 00 00 1c  00 00 00 01  01 10 60 02
Sep 22 12:39:34 syxzc pluto[1717]: "l2tp-psk"[64] 221.2.56.138 #74: Peer ID is ID_IPV4_ADDR: '221.2.56.138'
Sep 22 12:39:34 syxzc pluto[1717]: "l2tp-psk"[64] 221.2.56.138 #74: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=AES_CBC_128 integ=HMAC_SHA1 group=MODP2048}
Sep 22 12:39:34 syxzc pluto[1717]: "l2tp-psk"[64] 221.2.56.138 #74: IKE SA expired (--dontrekey)
Sep 22 12:39:34 syxzc pluto[1717]: "l2tp-psk"[64] 221.2.56.138 #74: deleting state (STATE_MAIN_R3) aged 0.406s and sending notification
Sep 22 12:39:34 syxzc pluto[1717]: deleting connection "l2tp-psk"[64] 221.2.56.138 instance with peer 221.2.56.138 {isakmp=#0/ipsec=#0}
Sep 22 12:39:34 syxzc pluto[1717]: "l2tp-psk"[65] 221.2.56.138 #75: responding to Main Mode from unknown peer 221.2.56.138 on port 500
Sep 22 12:39:34 syxzc pluto[1717]: "l2tp-psk"[65] 221.2.56.138 #75: STATE_MAIN_R1: sent MR1, expecting MI2
Sep 22 12:39:34 syxzc pluto[1717]: "l2tp-psk"[65] 221.2.56.138 #75: STATE_MAIN_R2: sent MR2, expecting MI3
Sep 22 12:39:34 syxzc pluto[1717]: "l2tp-psk"[65] 221.2.56.138 #75: byte at offset 1 (29) of 'ISAKMP Identification Payload'.'reserved' is 0x7b but should have been zero (ignored)
Sep 22 12:39:34 syxzc pluto[1717]: "l2tp-psk"[65] 221.2.56.138 #75: length of ISAKMP Identification Payload is larger than can fit
Sep 22 12:39:34 syxzc pluto[1717]: "l2tp-psk"[65] 221.2.56.138 #75: probable authentication failure (mismatch of preshared secrets?): malformed payload in packet
Sep 22 12:39:35 syxzc pluto[1717]: "l2tp-psk"[65] 221.2.56.138 #75: STATE_MAIN_R2: retransmission; will wait 0.5 seconds for response
Sep 22 12:39:35 syxzc pluto[1717]: "l2tp-psk"[65] 221.2.56.138 #75: STATE_MAIN_R2: retransmission; will wait 1 seconds for response
Sep 22 12:39:36 syxzc pluto[1717]: "l2tp-psk"[65] 221.2.56.138 #75: STATE_MAIN_R2: retransmission; will wait 2 seconds for response
Sep 22 12:39:38 syxzc pluto[1717]: "l2tp-psk"[65] 221.2.56.138 #75: STATE_MAIN_R2: retransmission; will wait 4 seconds for response
Sep 22 12:39:38 syxzc pluto[1717]: "l2tp-psk"[65] 221.2.56.138 #75: byte at offset 1 (29) of 'ISAKMP Identification Payload'.'reserved' is 0x7b but should have been zero (ignored)
Sep 22 12:39:38 syxzc pluto[1717]: "l2tp-psk"[65] 221.2.56.138 #75: length of ISAKMP Identification Payload is larger than can fit
Sep 22 12:39:38 syxzc pluto[1717]: "l2tp-psk"[65] 221.2.56.138 #75: probable authentication failure (mismatch of preshared secrets?): malformed payload in packet
Sep 22 12:39:42 syxzc pluto[1717]: "l2tp-psk"[65] 221.2.56.138 #75: STATE_MAIN_R2: retransmission; will wait 8 seconds for response

**Comment by hwdsl2** [comment]
@gavingy33 Hello! It looks like your connection was being blocked by the GFW. You may want to use an alternative solution such as Shadowsocks.

**Comment by gavingy33** [comment]
but i can establish connect with windows and macOs

**Comment by gavingy33** [comment]
> @gavingy33 Hello! It looks like your connection was being blocked by the GFW. You may want to use an alternative solution such as Shadowsocks.

but i can establish connect with windows and macOs

**Comment by gavingy33** [comment]
同一个公网出口IP
我试了win7、win10和mac环境 L2TP和 Cisco IPSec都能成功连接
但是在IKUAI路由器上配置，就不行

**Comment by xdkaka** [comment]
> 您好 @hwdsl2 我用同一个公网出口IP
> 我试了win7、win10和mac环境 L2TP和 Cisco IPSec都能成功连接
> 但是在IKUAI路由器上配置，就不行

我也是，爱快垃圾的要死，openvpn也是别的设备都行，就他不行

**Comment by yocdynyssc** [comment]
> > 您好 @hwdsl2 我用同一个公网出口IP
> > 我试了win7、win10和mac环境 L2TP和 Cisco IPSec都能成功连接
> > 但是在IKUAI路由器上配置，就不行
> 
> 我也是，爱快垃圾的要死，openvpn也是别的设备都行，就他不行

我的也是一样，不知道是不是爱快(ikuai)只支持不加密的连接，如windows中"不允许加密（如果它需要加密，服务器将断开连接）"爱快可能使用的是这个数据加密，也就是不允许加密。
