### ISSUE TITLE
有时候能装有时候会出现这个问题，请问是什么情况，如何解决，谢谢

### ISSUE THREAD

**Issue by LoThaRQ** [hwdsl2/setup-ipsec-vpn#641]
Transaction Summary
================================================================================
Install  1 Package  (+1 Dependent package)
Upgrade  2 Packages

Total size: 1.6 M
Downloading packages:
Running transaction check
Running transaction test

Transaction check error:
  package iptables-1.4.21-33.el7.x86_64 is already installed
  package iproute-4.11.0-25.el7.x86_64 is already installed

Error Summary
-------------

Error: 'yum install' failed.

**Comment by hwdsl2** [comment]
@LoThaRQ 你好！这个应该是你系统的问题。上面你提供的错误信息不完整，没有显示具体错误在哪里。
