### ISSUE TITLE
When I Change my server IP address and the ipsec VPN doesnt work

### ISSUE THREAD

**Issue by windancerzc** [hwdsl2/setup-ipsec-vpn#647]
shoud i modify some config files? I cant found similar issue on closed status.so are there any solutions for it?

**Comment by windancerzc** [comment]
and I've changed /etc/ipsec.config leftid to my current server ip address

**Comment by letoams** [comment]
If you use left=%defaultroute then you don’t need a config change and you can do:

ipsec whack —listen
ipsec auto —up connname

How to automate that depends on the interface.

Paul

**Comment by windancerzc** [comment]
> If you use left=%defaultroute then you don’t need a config change and you can do: ipsec whack —listen ipsec auto —up connname How to automate that depends on the interface. Paul
> […](#)
> Sent from my iPhone
> On Oct 3, 2019, at 23:50, windancerzc ***@***.***> wrote: shoud i modify some config files? I cant found similar issue on closed status.so are there any solutions for it? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

first of all, I cant use ipsec auto —up (conname in config file) because of %any in auto-generated configuration, then i changed to ipsec auto --add in replace, it worked, but I still cant connect to any net by using ipsec VPN.

**Comment by hwdsl2** [comment]
@windancerzc Hello! Generally, the IPsec VPN should continue to work when your server's IP address changes. You will need to restart the IPsec service using `sudo service ipsec restart` so that Libreswan can recognize the route change. You may also restart your server. Changing the `leftid` is not required according to my tests.

**Comment by windancerzc** [comment]
hi ， i changed the physical server，and using snapshot to copy my old linux system and data to a new server. Restarting the ipsec service didint work，why？are there sth wrong in config files?



发自我的iPhone


------------------ Original ------------------

**Comment by hwdsl2** [comment]
@windancerzc It may be difficult to troubleshoot for your specific use case, It could be due to various reasons such as IPsec config files, IPTables, udev MAC address configuration, etc. I would recommend that you re-run the script on a newly installed Linux system.

**Comment by windancerzc** [comment]
OK ，thanks for your time~



发自我的iPhone


------------------ Original ------------------
