### ISSUE TITLE
How to Add a new users

### ISSUE THREAD

**Issue by aganemnam** [hwdsl2/setup-ipsec-vpn#65]
Hi All,
I have one question. how to add another user exept what i configured during install.
i Have create some users manually with the same group and settings but when i connecting to server only one session is online. All other sessions are buzy or didnt get answer from server...
I need some help.
Thank you

**Comment by hwdsl2** [comment]
@aganemnam Hello! The same VPN account can be used by your multiple devices. However, due to a limitation of the IPsec protocol, if these devices are behind the same NAT (e.g. home router), they cannot simultaneously connect to the VPN server. This applies even if you create multiple users.

To manage VPN users please see https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users.md

**Comment by aganemnam** [comment]
hwdsl2, i need configure more then 1 client on the same router....
Is it posible to do it? 
i have created 20 users on a server but when all clients on the same network they cant connect to VPN server ..... only first success connected user can work with it.....
Can i somehow bypass this restriction ? 


Thank you!

**Comment by hwdsl2** [comment]
@aganemnam This is a limitation of the IPsec protocol, where multiple devices behind the same NAT (e.g. home router) cannot simultaneously connect to the VPN server. There are workarounds such as the Connmark plugin [1] in strongSwan, however it's not easy to configure. You can try modifying the script in [2] to add Connmark support.

You may also try setting up your router as an IPsec VPN client. However most home routers do not have support for IPsec/L2TP.

Alternatively I would suggest that you look into OpenVPN [3] which does support multiple users behind the same NAT.

[1] https://wiki.strongswan.org/projects/strongswan/wiki/Connmark
[2] https://github.com/philpl/setup-strong-strongswan
[3] https://github.com/Nyr/openvpn-install

**Comment by aganemnam** [comment]
Thank you very much! 
Moved to OpenVPN and configured it to my needs.
Anyway Thank you for this tutorial and script
