### ISSUE TITLE
IPsec/XAuth VPN connected but no internet connectivity

### ISSUE THREAD

**Issue by turbozapekanka** [hwdsl2/setup-ipsec-vpn#650]
Using my Android phone I set up IPsec/XAuth VPN
It connects successfully but pages does not load. Some pages like google "my ip address" works but kind of slow loading.
L2TP VPN type works perfect.

**Comment by letoams** [comment]
On Mon, 7 Oct 2019, turbozapekanka wrote:

> Using my Android phone I set up IPsec/XAuth VPN
> It connects successfully but pages does not load. Some pages like google "my ip address" works but kind of slow loading.
> L2TP VPN type works perfect.

Check your DNS settings. Also see
https://libreswan.org/wiki/FAQ#My_ssh_sessions_hang_or_connectivity_is_very_slow

**Comment by turbozapekanka** [comment]
I did not alter any DNS settings, just verified in the /etc/ipsec.conf

conn xauth-psk
  auto=add
  leftsubnet=0.0.0.0/0
  rightaddresspool=192.168.43.10-192.168.43.250
  **modecfgdns="8.8.8.8 8.8.4.4"**
  leftxauthserver=yes
  rightxauthclient=yes
  leftmodecfgserver=yes
  rightmodecfgclient=yes
  modecfgpull=yes
  xauthby=file
  ike-frag=yes
  cisco-unity=yes
  also=shared

I also tried to execute these on the vpn server and it did not help too
**iptables -I FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS  --clamp-mss-to-pmtu
iptables -I FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1380**

BTW, Shrew soft VPN for Windows worked fine.

**Comment by turbozapekanka** [comment]
I  even tried lowering the MTU on eth0 but still did not work:

**ip link set dev eth0 mtu 1380**

**Comment by TheM4hd1** [comment]
open `/etc/ipsec.conf`
change `sha2-truncbug=yes` to `sha2-truncbug=no`
then `reboot` or `restart` the service.
this change requires for using `IPSec` on `iOS 13` and `macOS Catalina`
link: https://support.apple.com/en-us/HT210432

**Comment by hwdsl2** [comment]
Thanks @TheM4hd1!

Yes, this is most likely an issue with the `sha2-truncbug=yes` for which you may refer to [1]. Fixed in the VPN setup scripts in 3353888.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ios-13-and-macos-1015
