### ISSUE TITLE
Ikev2 VPN connects but sites wont open on Android

### ISSUE THREAD

**Issue by turbozapekanka** [hwdsl2/setup-ipsec-vpn#651]
Set up using these instructions:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#android-4x-and-newer

Everything works fine for Windows client, but does not work for Android
StrongSwann VPN connects but no internet connectivity.

**Comment by letoams** [comment]
On Mon, 7 Oct 2019, turbozapekanka wrote:

> Set up using these instructions:
> https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#android-4x-and-newer
> 
> Everything works fine for Windows client, but does not work for Android
> StrongSwann VPN connects but no internet connectivity.

You might end up on using SHA2 with old/bad androids that need
sha2-truncbug=yes (but that will break all other clients) or you
are on new android's and set the "compatilibity" mode on which
emulates those old androids.

Try using aes_gcm, or at least preferring aes_gcm in the esp=/phase2alg=
line ?

Paul

**Comment by turbozapekanka** [comment]
I'm using Android 10 on a pixel phone. I dont think I altered any settings, where I can verify this "Compatibility mode" setting?

**Comment by turbozapekanka** [comment]
here is the log on the server
I see sha1 is used:

Oct 07 13:20:19 vpnserver pluto[2059]: "ikev2-cp"[15] x.x.x.x #26: STATE_V2_IPSEC_R: IPsec SA established tunnel mode {ESP/NAT=>0x1b823122 <0x55c8d500 xfrm=AES_CBC_128                                         -HMAC_SHA1_96 NATOA=none NATD=x.x.x.x:60688 DPD=active}

**Comment by turbozapekanka** [comment]
Btw, regarding the aes_gcm the documentation suggests the opposite, removing this line from the config: https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#known-issues
I tried both with phase2alg=aes_gcm-null and without and there is no difference.

**Comment by hwdsl2** [comment]
@turbozapekanka Hello! According to the logs your client connected using the `AES_CBC_128 -HMAC_SHA1_96` cipher, so it does not look like a cipher or "sha2-truncbug" issue. Try updating to the latest version of strongSwan Android VPN client. My recent tests using Android 10 and IKEv2 worked fine and I was able to open websites while connected. If you have more findings on this, feel free to share with us.
