### ISSUE TITLE
When Tow account connect to docker IPSec VPN, the later one will fail.

### ISSUE THREAD

**Issue by windancerzc** [hwdsl2/setup-ipsec-vpn#654]
two IOS13 phones connect to Docker IPsec VPN server in different router, but the second connection always failed. Does the docker IPsec VPN server supports multi-user in multi-connection? Is the problem that the first connection occupies the second conn? If so, is there sth to deal with it?

**Comment by hwdsl2** [comment]
@windancerzc Hello! For your use case please use only IPsec/XAuth ("Cisco IPsec") mode [1] or IKEv2 [2]. The IPsec/L2TP mode has limitations which was mentioned in the important notes [3]. Also please check your VPN configuration on the second phone for errors.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md
[3] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes
