### ISSUE TITLE
Network Usage

### ISSUE THREAD

**Issue by buzz3rs** [hwdsl2/setup-ipsec-vpn#657]
Good evening,
i was just wondering if there is a way to check network usage and maybe limit usage per usage
thanks

**Comment by letoams** [comment]
ipsec trafficstatus

Displays usage. On termination, it is both logged and the “updown” script is given the traffic counters so you can call your own binary/script to push that somewhere.

Authorization can be done via pam modules that also take your “credit” into account

Paul

**Comment by buzz3rs** [comment]
Thanks alot,
and what about limiting bandwidth per user account ?

**Comment by letoams** [comment]
On Fri, 11 Oct 2019, buzz3rs wrote:

> and what about limiting bandwidth per user account ?

Again the updown script is passed the remote ID and username, so you
can launch whatever kind of iptables rules you want (install on "up"
and remove on "down"). There is no builtin facility for this.

Paul

**Comment by buzz3rs** [comment]
That Really helped Thanks
