### ISSUE TITLE
I have my own mysql installed where can I change in the script to use my own mysql server

### ISSUE THREAD

**Issue by garygng** [hwdsl2/setup-ipsec-vpn#658]
I have my own mysql installed where can I change in the script to use my own mysql server
![linix-vpn-insall-error](https://user-images.githubusercontent.com/16561835/66701989-1c93ab00-ed35-11e9-8db9-e80552d6967e.JPG)

**Comment by garygng** [comment]
any one can help?

**Comment by hwdsl2** [comment]
@garygng Hello! This looks like an issue specific to your system where the existing package `mysql-server-5.7` was not configured (the VPN setup scripts do not install this package). Please re-run the VPN setup scripts on a freshly installed system.

**Comment by garygng** [comment]
i tried to re-run the vpn setup but  still have this issue. keep asking me to upgrade the mysql, as I have a website on the AWS, dont have a freshly system. pls help.

**Comment by hwdsl2** [comment]
@garygng Unfortunately, your system has an unconfigured package `mysql-server-5.7` which blocks `apt-get` commands. You will need to find a way to fix that, or set up the VPN on another freshly installed server.
