### ISSUE TITLE
ikev2 copy certs between different vps servers to serve, is it possible?

### ISSUE THREAD

**Issue by fanyigle** [hwdsl2/setup-ipsec-vpn#659]
Hello ,there.Thxs for your good job.
And I wondered if it's possible to share the same credentials across different servers to  connect by will ?

**Comment by fanyigle** [comment]
seems there's no simple solution to this ,after a quick search.  LOL.

**Comment by hwdsl2** [comment]
@fanyigle Hello! For IKEv2... I haven't tried this before but perhaps you can stop the IPsec service then copy the entire `/etc/ipsec.d` folder to the new server?
