### ISSUE TITLE
(Result Code: expected at least 10, got 8)

### ISSUE THREAD

**Issue by codemystyle** [hwdsl2/setup-ipsec-vpn#660]
Hi,

I am getting the following error, please help. I saw some posts on previous, but I didnt see a proper solution.

result_code_avp: avp is incorrect size.  8 < 10
handle_avps: Bad exit status handling attribute 1 (Result Code) on mandatory packet.
 Terminating pppd: sending TERM signal to pid 954
(Result Code: expected at least 10, got 8)
Server Ubuntu 18.04
Cloud - google cloud
Client - Pixel Phone.

Thanks

**Comment by dkosovic** [comment]
I believe this `result_code_avp: avp is incorrect size. 8 < 10` issue was fixed upstream with the following xl2tpd commit : 

- https://github.com/xelerance/xl2tpd/commit/9b939c0e1024c8a127ad2790440a3be7bc095932 

That commit is included with xl2tpd 1.3.14 and later.

**Comment by hwdsl2** [comment]
Thanks @dkosovic!

@codemystyle Please try upgrading your xl2tpd to the latest version. Compile and install from source if necessary. Possibly related: https://github.com/xelerance/xl2tpd/issues/130 https://github.com/xelerance/xl2tpd/issues/90
