### ISSUE TITLE
How can I route DNS traffic from the VPN into Pi-Hole?

### ISSUE THREAD

**Issue by KlonoaOfTheWind** [hwdsl2/setup-ipsec-vpn#661]
I'm sorry if this isn't the best place to ask this, but I'd like to have the VPN server I have set up to go through Pi-Hole, so I can get the benefit of adblocking anywhere. I did some googling around, and I just haven't seem to have found anything on that part. I've seen people using OpenVPN and Pi-Hole together, but I don't really want to go through that process.

Would it be possible so that DNS requests coming from the VPN would be sent into Pi-Hole first?

**Comment by welljsjs** [comment]
Isn't that as simple as setting the right DNS server? 

Just edit the configuration file (e.g. `/etc/ipsec.conf` for Cisco IPsec) and set the DNS server to your PiHole server.

**Comment by hwdsl2** [comment]
@KlonoaOfTheWind Hello! As @welljsjs mentioned please try setting your VPN's DNS servers to your Pi-Hole server. See important notes [1] for more details. If your Pi-Hole is also your VPN server, try putting `192.168.42.1` as the DNS (see #300).

[1] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes

**Comment by KlonoaOfTheWind** [comment]
Ah, I didn't know that someone responded before. The email didn't notify me
about his reply.

Anyways, I changed it in both config files to 192.168.41.1, but it seems
like I'm still getting ads through it. I get internet connectivity and all,
but it just doesn't seem to be routing DNS requests. The PiHole dashboard
doesn't even show any requests from it. I don't suppose there's something
that I may be missing? The other referenced issues don't provide much help,
and neither does the notes. I really feel like I'm missing something
obvious but it just isn't jumping at me.

**Comment by welljsjs** [comment]
What does `leftsubnet` on the server-side look like? Seems like the traffic does not go through the VPN at all. (Assuming you use "left-" for "local" configuration)

**Comment by KlonoaOfTheWind** [comment]
I'm definitely getting traffic routed through to it, as I can access things
that are on the local network (router, pihole admin page, remote desktop of
my pc, etc) over 4G (disabled wifi to ensure it uses my data).

leftsubnet=0.0.0.0/0
I'm guessing there's something that I need to adjust about this?

**Comment by welljsjs** [comment]
No, `0.0.0.0` is completely fine then. I thought it might have been set to something different. 

That's weird though. Do you mind posting the whole config file, `ip a` and `ip route` if possible? To make that if you're using multiple interfaces, you configured PiHole accordingly (i.e. "Pihole->Settings->DNS->Interface Listening Behaviour" is set correctly).

**Comment by KlonoaOfTheWind** [comment]
Config file

```
config setup
  virtual-private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:!192.168.42.0/24,%v4:!192.168.43.0/24
  protostack=netkey
  interfaces=%defaultroute
  uniqueids=no

conn shared
  left=%defaultroute
  leftid=[my public ip was here]
  right=%any
  encapsulation=yes
  authby=secret
  pfs=no
  rekey=no
  keyingtries=5
  dpddelay=30
  dpdtimeout=120
  dpdaction=clear
  ikev2=never
  ike=aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1,aes256-sha2;modp1024,aes128-sha1;modp1024
  phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes128-sha2,aes256-sha2
  sha2-truncbug=no

conn l2tp-psk
  auto=add
  leftprotoport=17/1701
  rightprotoport=17/%any
  type=transport
  phase2=esp
  also=shared
conn xauth-psk
  auto=add
  leftsubnet=0.0.0.0/0
  rightaddresspool=192.168.43.10-192.168.43.250
  modecfgdns="192.168.42.1"
  leftxauthserver=yes
  rightxauthclient=yes
  leftmodecfgserver=yes
  rightmodecfgclient=yes
  modecfgpull=yes
  xauthby=file
  ike-frag=yes
  cisco-unity=yes
  also=shared
```

Output of ifconfig and ip route

```
pi@HatKid:~ $ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.7  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 2600:6c67:5d80:9f9:b38c:b265:64c9:d369  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::ce6:e0a3:9a89:d6ec  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:70:07:7d  txqueuelen 1000  (Ethernet)
        RX packets 61961  bytes 13216601 (12.6 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 62119  bytes 35288556 (33.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 241984  bytes 16941394 (16.1 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 241984  bytes 16941394 (16.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

pi@HatKid:~ $ ip route
default via 192.168.1.1 dev eth0 src 192.168.1.7 metric 202
192.168.1.0/24 dev eth0 proto dhcp scope link src 192.168.1.7 metric 202
```

Also PiHole is listening from all sources.

**Comment by welljsjs** [comment]
At first sight, it looks fine to me. 

Might be the quotation marks (`modecfgdns="..."`)? Try without them. They don't appear in the docs at least. 

Also, did you configure you're client to use Cisco IPsec/XAuth, not L2TP? Just to make sure you're actually using the "xauth-psk" connection.

@KlonoaOfTheWind

**Comment by KlonoaOfTheWind** [comment]
Yeah, it's been configured on xauth-psk on both of my devices.

And I'll try that. I just left them there because there were quotations there when it had `8.8.8.8` and `8.8.4.4` set for the DNS

**Comment by welljsjs** [comment]
Hmm, then, sorry to say, but I don't think I can help you any further. I was just commenting on your question because I use(d) a similar setup.

Last thing I'd check is if you can confirm the the clients are configured to use the DNS server. Or, in other words, you do a DNS lookup and see what server they use. Also, you shouldn't configure you're clients to use any other DNS server (though you're most likely aware of this).

**Comment by KlonoaOfTheWind** [comment]
Alright, that was it. I was a dummy and didn't set up the DNS server on the
clients. Thank you lol

And sorry for wasting your time a bit there, I'm not sure how something
simple like that missed me.

**Comment by welljsjs** [comment]
No worries, glad you finally got it to work.

**Comment by sniff122** [comment]
I know this is quite an old issue and it has been closed and stuff but im trying to set my VPN DNS to my pi hole (10.10.0.96) in both the server configs (/etc/ipsec.conf and /etc/ppp/options.xl2tpd) to no avail in resolving local domain names (.local is my local search domain). When i try setting the DNS on a client (tried on my tablet, phone and laptop, phone and tablet are android 10 and my laptop is running ubuntu 20.04) and try to make a dns query it fails to resolve any DNS (not just local domains), when using the dns set on the server, every domain name that is external from my network resolves but local domains fail with NXDOMAIN when using the host command. Just to note my VPN server is running on a proxmox container (what uses lxc) and is on 10.10.0.219. i dont have to use my pi hole for DNS but it would be useful to be able to resolve local hostnames and block ads when im outside of my home network. If anyone could shed some light onto what could be going on and a potential fix that would be amazing.

**Comment by sniff122** [comment]
Forgot to note, im using xauth on my phone and tablet and l2tp on my laptop
