### ISSUE TITLE
can't connect from windows

### ISSUE THREAD

**Issue by A2116** [hwdsl2/setup-ipsec-vpn#663]
I installed l2tp server using your script but when I want to connect to it from windows it can't
I can connect from android, also I can connect from the same windows machine to other l2tp servers
also, I am tried disabling firewall but it not help
what should I do?

**Comment by hwdsl2** [comment]
@A2116 Hello! Did you follow the instructions in [1] to add/update the registry key? You may check the VPN server logs for errors using these steps [2].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#windows-error-809
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps

**Comment by A2116** [comment]
Tanks for your reply, I did registry key adding and also I reboot the
system and the problem is solved
i have another question, is any way to limit the number of connections of
each username? one or two or...?

**Comment by hwdsl2** [comment]
@A2116 No, this feature is not supported.

**Comment by A2116** [comment]
now I am using centos 7.4, on (# service ipsec status) it prompt me (ERROR:
can't offload to eth0 because SIOCETHTOOL ETHTOOL_GSSET_INFO failed. Errno
95: Operation not supported) and i have another problem, how i can solve
this problem?
and which is better support your script and have fewer problems between
centos and ubuntu and Debian?

**Comment by hwdsl2** [comment]
@A2116 This error message can be ignored and should not affect your VPN. Any of the OS you mentioned should be fine as long as it's listed in the requirements section of the README.
```
ERROR: can't offload to eth0 because SIOCETHTOOL ETHTOOL_GSSET_INFO failed. Errno
95: Operation not supported
```
