### ISSUE TITLE
Cannot establish l2tp connection, served on a bandwagon vps in USA

### ISSUE THREAD

**Issue by martinmyj** [hwdsl2/setup-ipsec-vpn#664]
Thanks for the script.I already setup and connect successfully at vultr vps,But I finish set up at bandwagon and try to connect by my iphone(l2tp vpn), shows 'L2TP-VPN server not responding..'I try the script on ubuntu,centos,Debian, all set up success with no error message but cannot connect.
Below are the logs.
root@martin:~# ipsec verify
Verifying installed system and configuration files

Version check and ipsec on-path                         [OK]
Libreswan 3.29 (netkey) on 4.9.0-3-amd64
Checking for IPsec support in kernel                    [OK]
 NETKEY: Testing XFRM related proc values
         ICMP default/send_redirects                    [OK]
         ICMP default/accept_redirects                  [OK]
         XFRM larval drop                               [OK]
Pluto ipsec.conf syntax                                 [OK]
Checking rp_filter                                      [OK]
Checking that pluto is running                          [OK]
 Pluto listening for IKE on udp 500                     [OK]
 Pluto listening for IKE/NAT-T on udp 4500              [OK]
 Pluto ipsec.secret syntax                              [OK]
Checking 'ip' command                                   [OK]
Checking 'iptables' command                             [OK]
Checking 'prelink' command does not interfere with FIPS [OK]
Checking for obsolete ipsec.conf options                [OK]

root@martin:~# grep xl2tpd /var/log/syslog
Oct 21 09:26:26 martin xl2tpd[16320]: setsockopt recvref[30]: Protocol not available
Oct 21 09:26:26 martin xl2tpd[16320]: Using l2tp kernel support.
Oct 21 09:26:26 martin xl2tpd[16316]: Starting xl2tpd: xl2tpd.
Oct 21 09:26:26 martin xl2tpd[16333]: xl2tpd version xl2tpd-1.3.8 started on martin PID:16333
Oct 21 09:26:26 martin xl2tpd[16333]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
Oct 21 09:26:26 martin xl2tpd[16333]: Forked by Scott Balmos and David Stipp, (C) 2001
Oct 21 09:26:26 martin xl2tpd[16333]: Inherited by Jeff McAdams, (C) 2002
Oct 21 09:26:26 martin xl2tpd[16333]: Forked again by Xelerance (www.xelerance.com) (C) 2006-2016
Oct 21 09:26:26 martin xl2tpd[16333]: Listening on IP address 0.0.0.0, port 1701
Oct 21 09:28:08 martin xl2tpd[23646]: Stopping xl2tpd: xl2tpd.
Oct 21 09:28:08 martin xl2tpd[16333]: death_handler: Fatal signal 15 received
Oct 21 09:28:08 martin xl2tpd[23654]: setsockopt recvref[30]: Protocol not available
Oct 21 09:28:08 martin xl2tpd[23654]: Using l2tp kernel support.
Oct 21 09:28:08 martin xl2tpd[23651]: Starting xl2tpd: xl2tpd.
Oct 21 09:28:08 martin xl2tpd[23655]: xl2tpd version xl2tpd-1.3.8 started on martin PID:23655
Oct 21 09:28:08 martin xl2tpd[23655]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
Oct 21 09:28:08 martin xl2tpd[23655]: Forked by Scott Balmos and David Stipp, (C) 2001
Oct 21 09:28:08 martin xl2tpd[23655]: Inherited by Jeff McAdams, (C) 2002
Oct 21 09:28:08 martin xl2tpd[23655]: Forked again by Xelerance (www.xelerance.com) (C) 2006-2016
Oct 21 09:28:08 martin xl2tpd[23655]: Listening on IP address 0.0.0.0, port 1701

grep pluto /var/log/auth.log
Oct 21 09:28:08 martin pluto[23636]: 1 CPU cores online
Oct 21 09:28:08 martin pluto[23636]: starting up 1 crypto helpers
Oct 21 09:28:08 martin pluto[23636]: started thread for crypto helper 0
Oct 21 09:28:08 martin pluto[23636]: Using Linux XFRM/NETKEY IPsec interface code on 4.9.0-3-amd64
Oct 21 09:28:08 martin pluto[23636]: seccomp security for crypto helper not supported
Oct 21 09:28:08 martin pluto[23636]: selinux support is NOT enabled.
Oct 21 09:28:08 martin pluto[23636]: systemd watchdog for ipsec service configured with timeout of 200000000 usecs
Oct 21 09:28:08 martin pluto[23636]: watchdog: sending probes every 100 secs
Oct 21 09:28:08 martin pluto[23636]: seccomp security not supported
Oct 21 09:28:08 martin pluto[23636]: added connection description "l2tp-psk"
Oct 21 09:28:08 martin pluto[23636]: added connection description "xauth-psk"
Oct 21 09:28:08 martin pluto[23636]: listening for IKE messages
Oct 21 09:28:08 martin pluto[23636]: Kernel does not support NIC esp-hw-offload
Oct 21 09:28:08 martin pluto[23636]: adding interface eth0/eth0 (esp-hw-offload=no) 64.64.233.140:500
Oct 21 09:28:08 martin pluto[23636]: adding interface eth0/eth0 64.64.233.140:4500
Oct 21 09:28:08 martin pluto[23636]: Kernel does not support NIC esp-hw-offload
Oct 21 09:28:08 martin pluto[23636]: adding interface lo/lo (esp-hw-offload=no) 127.0.0.1:500
Oct 21 09:28:08 martin pluto[23636]: adding interface lo/lo 127.0.0.1:4500
Oct 21 09:28:08 martin pluto[23636]: Kernel does not support NIC esp-hw-offload
Oct 21 09:28:08 martin pluto[23636]: adding interface lo/lo (esp-hw-offload=no) ::1:500
Oct 21 09:28:08 martin pluto[23636]: loading secrets from "/etc/ipsec.secrets"
Oct 21 09:28:43 martin pluto[23636]: forgetting secrets
Oct 21 09:28:43 martin pluto[23636]: loading secrets from "/etc/ipsec.secrets"
Oct 21 09:28:48 martin pluto[23636]: "l2tp-psk"[1] 58.247.151.25 #1: responding to Main Mode from unknown peer 58.247.151.25 on port 500
Oct 21 09:28:48 martin pluto[23636]: "l2tp-psk"[1] 58.247.151.25 #1: WARNING: connection l2tp-psk PSK length of 10 bytes is too short for sha2_256 PRF in FIPS mode (16 bytes required)
Oct 21 09:28:48 martin pluto[23636]: "l2tp-psk"[1] 58.247.151.25 #1: STATE_MAIN_R1: sent MR1, expecting MI2
Oct 21 09:28:49 martin pluto[23636]: "l2tp-psk"[1] 58.247.151.25 #1: STATE_MAIN_R2: sent MR2, expecting MI3
Oct 21 09:28:49 martin pluto[23636]: "l2tp-psk"[1] 58.247.151.25 #1: ignoring informational payload IPSEC_INITIAL_CONTACT, msgid=00000000, length=28
Oct 21 09:28:49 martin pluto[23636]: | ISAKMP Notification Payload
Oct 21 09:28:49 martin pluto[23636]: |   00 00 00 1c  00 00 00 01  01 10 60 02
Oct 21 09:28:49 martin pluto[23636]: "l2tp-psk"[1] 58.247.151.25 #1: Peer ID is ID_IPV4_ADDR: '192.168.1.52'
Oct 21 09:28:49 martin pluto[23636]: "l2tp-psk"[1] 58.247.151.25 #1: switched from "l2tp-psk"[1] 58.247.151.25 to "l2tp-psk"
Oct 21 09:28:49 martin pluto[23636]: "l2tp-psk"[2] 58.247.151.25 #1: deleting connection "l2tp-psk"[1] 58.247.151.25 instance with peer 58.247.151.25 {isakmp=#0/ipsec=#0}
Oct 21 09:28:49 martin pluto[23636]: "l2tp-psk"[2] 58.247.151.25 #1: Peer ID is ID_IPV4_ADDR: '192.168.1.52'
Oct 21 09:28:49 martin pluto[23636]: "l2tp-psk"[2] 58.247.151.25 #1: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA2_256 group=MODP2048}
Oct 21 09:28:52 martin pluto[23636]: "l2tp-psk"[2] 58.247.151.25 #1: retransmitting in response to duplicate packet; already STATE_MAIN_R3
Oct 21 09:28:55 martin pluto[23636]: "l2tp-psk"[2] 58.247.151.25 #1: retransmitting in response to duplicate packet; already STATE_MAIN_R3
Oct 21 09:28:58 martin pluto[23636]: "l2tp-psk"[2] 58.247.151.25 #1: discarding duplicate packet -- exhausted retransmission; already STATE_MAIN_R3
Oct 21 09:29:11 martin pluto[23636]: "l2tp-psk"[2] 58.247.151.25 #1: discarding duplicate packet -- exhausted retransmission; already STATE_MAIN_R3

I compare the log with another workable vps.The following logs are different:

Oct 21 09:28:52 martin pluto[23636]: "l2tp-psk"[2] 58.247.151.25 #1: retransmitting in response to duplicate packet; already STATE_MAIN_R3
Oct 21 09:28:55 martin pluto[23636]: "l2tp-psk"[2] 58.247.151.25 #1: retransmitting in response to duplicate packet; already STATE_MAIN_R3
Oct 21 09:28:58 martin pluto[23636]: "l2tp-psk"[2] 58.247.151.25 #1: discarding duplicate packet -- exhausted retransmission; already STATE_MAIN_R3
Oct 21 09:29:11 martin pluto[23636]: "l2tp-psk"[2] 58.247.151.25 #1: discarding duplicate packet -- exhausted retransmission; already STATE_MAIN_R3

I try to search on google for a long time,But I can't get the solution and fix it.Would please help me.Also I see the same issue undet this project #653 but the issue is closed by the questioner.I don't know how he fix this problem.If anyone know how to fix it.Please tell me.
Thanks

**Comment by hwdsl2** [comment]
@martinmyj Hello! The logs you mentioned indicate that your traffic may be disrupted or blocked by the GFW firewall. You may instead look into alternative solutions such as Shadowsocks.

**Comment by martinmyj** [comment]
Thanks,I already transfer to the shadowsocksr.Thanks anyway.

**Comment by Lunkeqing** [comment]
> @martinmyj Hello! The logs you mentioned indicate that your traffic may be disrupted or blocked by the GFW firewall. You may instead look into alternative solutions such as Shadowsocks.

你好，我是一样的日志，retransmitting in response to duplicate packet; already STATE_MAIN_R3
感觉服务器和我设备的连接是没有问题的，且验证通过了。

如果真实GFW，是不是换个ip会比较好
请问应该如何解决，上面说的shadowsocks如何替换
