### ISSUE TITLE
Aggressive Mode and Android 9 can't connect

### ISSUE THREAD

**Issue by zicheee** [hwdsl2/setup-ipsec-vpn#665]
Hi,
I have successfully set up the VPN server using an EC2 with Ubuntu 18.04. With the default setup, my Android phone (Nokia with Android 9) can connect to the server using IPsec/XAuth as described here: 
[clients-xauth.md](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md#android)

Unfortunately for the AVM Fritz!Box the aggressive mode must be switched on and an id must be set:

```
conn xauth-psk
  ..
  cisco-unity=yes
  rightid=@[my-key-id]
  aggrmode=yes
  ..
```

I tried to use this id (my-key-id) as IPSec-ID in my phone, but I can't connect anymore to the VPN server. Is there another setting I can adjust so that both devices can connect?

Best regards
Michael

**Edit:**
In the meantime tried the following devices:
iPhone 8, iOS 13.1.3
Galaxy Tab, Android 8.1
Both devices are connecting to the VPN server within seconds. 
~~I do not have another Android device with Android 9 to test so it is 
a) something different with Android 9, or 
b) something special with Android 9 on a Nokia phone~~

I could test the VPN with two other Android 9 devices and both can not connect to the VPN server when aggressive mode is switched on.

**Comment by hwdsl2** [comment]
@zicheee Hello! The IPsec aggressive mode is not supported in the default configuration of the VPN setup scripts. You may find more related information in #304.
