### ISSUE TITLE
你好！连接不上，脚本跑了，端口开了

### ISSUE THREAD

**Issue by fnlearner** [hwdsl2/setup-ipsec-vpn#666]
![image](https://user-images.githubusercontent.com/38586156/67550667-9ebe9f00-f739-11e9-96c0-f87a07e291c8.png)
![image](https://user-images.githubusercontent.com/38586156/67550711-b72eb980-f739-11e9-95f4-54eeb37a7e35.png)
![image](https://user-images.githubusercontent.com/38586156/67550902-37551f00-f73a-11e9-8a4a-0d6cbfc0eacd.png)
![image](https://user-images.githubusercontent.com/38586156/67550934-4b991c00-f73a-11e9-9ad6-482275f20653.png)

**Comment by verydemo** [comment]
我用的docker，https://github.com/hwdsl2/docker-ipsec-vpn-server
我的win10登录成功，安卓连接不上

**Comment by fnlearner** [comment]
在线自闭
![image](https://user-images.githubusercontent.com/38586156/67560537-a9832f00-f74d-11e9-8157-bb8469425f0f.png)

**Comment by verydemo** [comment]
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#windows-error-809
这个作者文档里面有写，修改注册表，然后重启电脑 我现在测试我的win10 安卓都没问题

**Comment by fnlearner** [comment]
有改的，也重启了，reg也双击导入了，命令行那行没有运行
![image](https://user-images.githubusercontent.com/38586156/67561761-02ec5d80-f750-11e9-8974-a12052902a02.png)

**Comment by fnlearner** [comment]
@verydemo 好的 ，謝謝啦
