### ISSUE TITLE
xl2tpd files is not there

### ISSUE THREAD

**Issue by benyamin95** [hwdsl2/setup-ipsec-vpn#667]
i used this script for installing l2tp vpn and i couldnt connect to it after it finished . i searched for the problem and i found out xl2tpd files havent been created . what can i do ? i installed it 2 times it didnt help. im using debian

**Comment by hwdsl2** [comment]
@benyamin95 Hello! The VPN setup scripts has been recently tested on Debian 10/9/8 and is working fine. If the problem you described persists, feel free to open a new issue with the error details.
