### ISSUE TITLE
无法在同一个 NAT 下不同账号登录同一个 Cisco IPsec VPN

### ISSUE THREAD

**Issue by vvtommy** [hwdsl2/setup-ipsec-vpn#671]
您好，我搜索了 Issues 和文档，您提到了在同一个 NAT 下（例如我家的 Router）不能同时有多个 L2TP。但是，我在采用您提供的脚本部署了 VPN 后（仅修改了`xauth-psk`的`leftsubnet=10.8.0.0/16`)，使用一台 macOS 和一台 iPhone、分别两个账号采用 Cisco IPsec 前后相差数十秒内拨通 VPN，总是后连接的设备正常，而先拨入的无法连接远端网络，甚至为了恢复正常，我需要 `ipsec restart` 才能让先前失败的设备在重拨后复原。
相对的，这两台设备在不同的网络里则没有任何问题，我也通过改变顺序、设备进行了多次测试，会有同样的故障。🤷‍♂️

**Comment by Jimmy-Z** [comment]
我试了一下, 关掉路由器的ipsec pass-through就好了.

**Comment by vvtommy** [comment]
关掉就彻底连不上了🤷‍♂️

**Comment by Jimmy-Z** [comment]
确切的说我关的是pfsense的ISAKMP NAT静态端口规则, 我以为这个就对应常见的ipsec passthrough, 看来错了.

**Comment by hwdsl2** [comment]
@vvtommy 你好！我测试了一下你说的用例，没有发现问题，可以同时连接。这个有可能和你的路由器有关，有些路由器对 IPsec passthrough 的支持不太好。
