### ISSUE TITLE
客户端重启后重新连接失败

### ISSUE THREAD

**Issue by brijagstu7** [hwdsl2/setup-ipsec-vpn#675]
客户端：OnePlus 7 Oxygen OS 10.0.1
系统自带设置的VPN设置

服务器：Google cloud 

某次重启手机后VPN失效，推断原因是set-ipsec-vpn.sh的错误使用（使用add_user增加了和原有的用户名一致但密码不一致的用户，和另一个正常用户）或者自身bug，或者GFW的封锁，或者手机VPN服务的一些问题。(后来2次连续发现，重新启动手机导致出现了同样的问题，因此可以确定导致问题的直接原因是重新启动手机）

尝试过restart service和重启实例但无效。

在出现失效后，我重新创建了一个实例并只使用set-ipsec-vpn建立随机密码对，连接成功，但是重新启动之后就连接失败。

我重建了新的实例，但是使用原来的固定IP，发现也没有连接成功。

因此，在多次尝试下，问题可以描述为“重新启动手机后，对于同一IP的连接会失败”

对于不同IP还未尝试（有必要尝试）

值得注意的是，在关闭VPN，然后开启后，可以连接。因此另一个尝试可以是重启前手动关闭VPN。

这个问题可能是手机系统的问题，也可能是VPN程序的问题，不过我觉得任何一方都可以做出补丁从而解决这个问题。

**Comment by hwdsl2** [comment]
@brijagstu7 你好！这个看起来像是你手机的问题，因为在我的 Android 测试中并没有发现此问题。另外你可以使用这些命令 [1] 检查服务器上的日志是否有错误。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E9%A2%9D%E5%A4%96%E7%9A%84%E6%AD%A5%E9%AA%A4
