### ISSUE TITLE
IKEv2 rekey issue

### ISSUE THREAD

**Issue by mithos99** [hwdsl2/setup-ipsec-vpn#676]
Hello!
Thank you for great script.

Everything works perfectly fine until connection lifetime (Layer2) comes to end.
Router (Mikrotik) tries to renew SA, sends request and Libreswan rejects it with this line:

pluto[10758]: "ikev2-cp"[38] XXX.XXX.XXX.XXX #49: dropping unexpected CREATE_CHILD_SA message containing REKEY_SA notification; message payloads: SK; encrypted payloads: SA,KE,Ni,N,TSi,TSr,CP; unexpected payloads: CP

Then whole connection drops and router reconnects from the beginning and lifecycle starts again. Maximum lifecycle is 24h... so every 24h my home network looses connection.

I couldn't find any similar issues... Mikrotik support stays silent, Libreswan doesn't have support. You are my last hope, Lin :)

conn ikev2-cp
  left=%defaultroute
  leftcert=XXX.XXX.XXX.XXX
  leftid=@XXX.XXX.XXX.XXX
  leftsendcert=always
  leftsubnet=0.0.0.0/0
  leftrsasigkey=%cert
  right=%any
  rightid=%fromcert
  rightaddresspool=192.168.43.10-192.168.43.250
  rightca=%same
  rightrsasigkey=%cert
  narrowing=yes
  dpddelay=30
  dpdtimeout=120
  dpdaction=clear
  auto=add
  ikev2=insist
  rekey=yes
  pfs=yes
  ike-frag=yes
  ike=aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1,aes256-sha2;modp1024,aes128-sha1;modp1024
  phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes128-sha2,aes256-sha2
  modecfgdns="YYY.YYY.YYY.YYY ZZZ.ZZZ.ZZZ.ZZZ"
  encapsulation=yes
  mobike=no
  salifetime=1d
  ikelifetime=1d

**Comment by hwdsl2** [comment]
@mithos99 Hello! Thanks for the report. This could be a bug in Libreswan, or it might be incompatibility with your Mikrotik router. Unfortunately, I am not sure. Please try the following:

1. Disable `rekey` and `pfs` on your VPN server by changing them to `no` in `/etc/ipsec.conf` and restart the IPsec service.
2. Open a new issue at https://github.com/libreswan/libreswan with the details.
3. Reach out to @letoams or the Libreswan team on GitHub with your question.
3. Ask your question on the Libreswan users mailing list [1].

[1] https://lists.libreswan.org/mailman/listinfo/swan

**Comment by letoams** [comment]
It is a bug in libreswan, I should have a patch in a few days.

**Comment by letoams** [comment]
On Sat, 16 Nov 2019, Lin Song wrote:

> @mithos99 Hello! Thanks for the report. This could be a bug in Libreswan, or it might be incompatibility with your Mikrotik router.
> Unfortunately, I am not sure. Please try the following:

I filed the bug at: https://github.com/libreswan/libreswan/issues/293

Paul

**Comment by hwdsl2** [comment]
Thanks @letoams!

**Comment by mithos99** [comment]
Thank you so much, guys! 
Looking forward to the patch.

**Comment by letoams** [comment]
fixed in commit cd993436a1c8ba51bf5078c7ae21fdd8626e526b

**Comment by AuthorShin** [comment]
Hello
Sorry for bringing this up after years.
@mithos99 Can you please send me the "/ip ipsec export file=123" output of your mikrotik router I'm having a very difficult time trying to setup IKEV2 with this script on my mikrotik router.
Best Regards
