### ISSUE TITLE
Is it possible for a server to be both a L2TP server and a L2TP client?

### ISSUE THREAD

**Issue by ATheCoder** [hwdsl2/setup-ipsec-vpn#677]
I have two servers that I have ran your L2TP script on.

Lets call them Server A and Server B.

Server A does not have access to free internet but Server B does.

I was wondering if there is a way to make Server A the client for Server B so that when you connect to Server A's L2TP VPN on any client such as windows/android you could access the free Internet provided in Server B since these windows/android clients do not have access to Server B's L2TP VPN, Let's say server B's IP is blocked on the end client's network.

**Comment by hwdsl2** [comment]
@ATheCoder Hello! Unfortunately your use case isn’t supported. Perhaps you can look into alternatives such as GRE tunnels, I am not sure.
