### ISSUE TITLE
IPsec/Xauth 模式的问题

### ISSUE THREAD

**Issue by brijagstu7** [hwdsl2/setup-ipsec-vpn#678]
使用脚本启动VPN服务后，在安卓10设备上使用IPsec/Xauth模式可连接但是没有流量交互。

在Mac OS 10.14 可连接，也有流量交互，完全正常。

换用IPsec/l2tp 连接，则无论安卓Q还是Mac OS都正常。

尝试了调整 sha2-trucbug 选项（而且重启了）但是无效。

**Comment by hwdsl2** [comment]
@brijagstu7 你好！重新连接你的安卓10设备，通过IPsec/XAuth模式。然后使用这些命令 [1] 检查服务器上的日志，看看连接使用的是什么加密模式。

安卓10设备需要在/etc/ipsec.conf中设置sha2-truncbug=no并且重启IPsec服务。在我的测试中可以正常连接并上网。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E9%A2%9D%E5%A4%96%E7%9A%84%E6%AD%A5%E9%AA%A4

**Comment by fox85** [comment]
> 使用脚本启动VPN服务后，在安卓10设备上使用IPsec/Xauth模式可连接但是没有流量交互。
> 
> 在Mac OS 10.14 可连接，也有流量交互，完全正常。
> 
> 换用IPsec/l2tp 连接，则无论安卓Q还是Mac OS都正常。
> 
> 尝试了调整 sha2-trucbug 选项（而且重启了）但是无效。

https://www.zeitgeist.se/2013/11/26/mtu-woes-in-ipsec-tunnels-how-to-fix/
参考这里，极有可能是安卓系统自带的VPN客户端引起的，因为我也遇到过，为了兼容性而妥协，在VPN服务端这边把MTU调小，问题马上解决
