### ISSUE TITLE
IKEv2 按照指引无法得到预期的结果

### ISSUE THREAD

**Issue by brijagstu7** [hwdsl2/setup-ipsec-vpn#679]
使用官方文档的配置方法一步一步配置IKE v2连接方式，在尝试显示已有的客户端证书时，得到以下输出：

Certificate Nickname                                         Trust Attributes
                                                             SSL,S/MIME,JAR/XPI

IKEv2 VPN CA                                                 CTu,u,u
vpnclient                                                
    u,u,u

这与文档预期的不符，因为u,u,u位置应该是主机的IP地址。

结果继续按照指引用客户端连接时果然没有成功。日志如下：

![Screenshot_20191120-202104](https://user-images.githubusercontent.com/56994423/69238990-31851900-0bd4-11ea-89ce-486d2844c2f0.jpg)

**Comment by hwdsl2** [comment]
@brijagstu7 你好！我近期刚刚测试过IKEv2文档，没有发现问题。建议你再试一下，按照IKEv2文档的步骤重新生成证书。要删除证书，参见第6步的提示。
