### ISSUE TITLE
Android无法使用

### ISSUE THREAD

**Issue by fhyuncai** [hwdsl2/setup-ipsec-vpn#680]
服务器系统Centos7，手机系统MIUI10，Android6，使用IPSec Xauth连接成功，可ping到自己分配到的虚拟ip，但无法ping其他设备虚拟ip及访问其他任何网络。
经检查，日志正常，其他iOS设备连接可正常访问互联网和虚拟ip。

**Comment by yukiloh** [comment]
我也是类似的问题；

服务器端环境：
ubuntu18；
使用docker，镜像：hwdsl2/ipsec-vpn-server，仅配置了env文件中的
VPN_IPSEC_PSK=your_ipsec_pre_shared_key
VPN_USER=your_vpn_username
VPN_PASSWORD=your_vpn_password
这三条；

客户端：
EMUI9.0；Xauth显示连接成功L2SP，但是无法访问任何网页；
切换L2SP后可以访问很短的时间后失去连接，且此时服务器与外界失去连接，无法使用ping或者ssh（同样显示了连接成功）；
win10系统使用内置VPN服务（经调教后），协议使用L2SP，测试期间未出现失去连接；

**Comment by hwdsl2** [comment]
@fhyuncai @yukiloh Try changing the sha2-truncbug setting from “no” to “yes”. Follow instructions from step 2 in [1]. For Docker, see [2].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#android-6-and-7
[2] https://github.com/hwdsl2/docker-ipsec-vpn-server/blob/master/README.md#important-notes
