### ISSUE TITLE
Set Limit one connection per user

### ISSUE THREAD

**Issue by amirpc007** [hwdsl2/setup-ipsec-vpn#682]
hi
i make my vpn server successfuly and i add new users form "/etc/ppp/chap-secrets" File
but now i need to set connection limit for my users
one connection per user
and i don't know what need to do

**Comment by hwdsl2** [comment]
@amirpc007 Hello! This feature is not supported. Unfortunately I don’t know a method for your use case.

**Comment by letoams** [comment]
You can only do that when using certificates and then it is the default to disconnect the older connection.

Paul

**Comment by amirpc007** [comment]
This feature is supported on pptp connections , is that right?

**Comment by hassaan-dev** [comment]
> 
> You can only do that when using certificates and then it is the default to disconnect the older connection. Paul
> […](#)
> Sent from my iPhone
> On Nov 22, 2019, at 11:55, Lin Song ***@***.***> wrote: @amirpc007 Hello! This feature is not supported. Unfortunately I don’t know a method for your use case. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Can you please help to setup certificates?
For certificates, what we need on server side and what required on client side?

**Comment by letoams** [comment]
On Fri, 20 Mar 2020, hassaan-dev wrote:

>       You can only do that when using certificates and then it is the default to disconnect the older connection. Paul
>       …
>       Sent from my iPhone
>       On Nov 22, 2019, at 11:55, Lin Song @.***> wrote: @amirpc007 Hello! This feature is not supported. Unfortunately I don’t know a method for your use
>       case. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> Can you please help to setup certificates?
> For certificates, what we need on server side and what required on client side?

You can follow any tutorial that talks about SSL/TLS certificates. Just
ensure that the VPN server has the full DNS name used as a
subjectAltName (SAN) on its certificate.

We have a python script we use to generate a bunch of different (normal
and weird) certificates you can look at:

https://raw.githubusercontent.com/libreswan/libreswan/master/testing/x509/dist_certs.py

Paul

**Comment by hassaan-dev** [comment]
I have generated SSL/TLS certificates via lets encrypt for host.
In which file, I have to put/configure those certificates?

**Comment by letoams** [comment]
Create a PKCS12 file of that certificate, then run: ipsec import yourfile.p12
