### ISSUE TITLE
连接成功几分钟后自动断开

### ISSUE THREAD

**Issue by JINCHUNGEUN** [hwdsl2/setup-ipsec-vpn#683]
设备能正常连接vpn，刚开始还能正常访问外网，但是过个几分钟就访问不了，vpn还是连接的状态，接着就自动断开了，这个问题是哪个环节出了问题？ 跟出口流量管控有关系吗

**Comment by wcxaa** [comment]
我今天也是这样，这是怎么了。。

**Comment by sonwa** [comment]
同样遇到这个问题，刚开始以为机房问题，但换了机房还是一样。连接成功几分钟后就断开了

**Comment by xiaoxiongjun** [comment]
我也是

**Comment by zc-eason** [comment]
同样的问题

**Comment by walker4753** [comment]
同问题。。。。

**Comment by MattedBroadSky** [comment]
同问题。。

发自我的 iPhone

在 2019年11月23日，17:35，walker4753 <notifications@github.com<mailto:notifications@github.com>> 写道：


同问题。。。。

**Comment by brijagstu7** [comment]
我认为可能和GFW有关，但有好多不明白。

我的l2tp VPN生存了半个月左右，开始频繁断线，表现为连不上、一连上几分钟就断。不过最让我奇怪的是我换了静态IP甚至换了主机，问题仍然存在（我使用的是谷歌云），有人能为我解答吗？在我的理解里，GFW只会封IP或者端口，如果它不能认出包的内容的话（与IP无关的关键词屏蔽）。

**Comment by chengchenwish** [comment]
l2tp 使用UDP 500的端口，不像openvpn可以改端口。这两天老断，我用的azure 的云。感觉墙升级了。

**Comment by ZHANGCHUANGCHUANG1** [comment]
同问啊！

**Comment by hwdsl2** [comment]
看起来像是GFW的问题。建议大家换用其他解决方案，比如Shadowsocks。

**Comment by ljt2016** [comment]
@hwdsl2 上周也遇到过这个问题，这周重新试了一下，推测是是因为当时LoadBalancer没有使用静态IP地址，这周LB使用了静态IP，问题解决
