### ISSUE TITLE
L2TP is not Working 

### ISSUE THREAD

**Issue by MaminHakim** [hwdsl2/setup-ipsec-vpn#684]
I've tried to reboot and installed 3 times, but every time I got this message on my iPhone. " _The L2TP-VPN server did not respond. try reconnecting. if the problem continues, verify your setting and contact your Administrator."_ 

This is Also my Xl2tpd log. 
[log.txt](https://github.com/hwdsl2/setup-ipsec-vpn/files/3882452/log.txt)

**Comment by letoams** [comment]
Looks like xl2tpd is crashing ? Not sure why

**Comment by hwdsl2** [comment]
@MaminHakim From your logs it looks like the xl2tpd service is crashing. This is most likely an issue with your server. Try a different server with a freshly installed OS.
