### ISSUE TITLE
Asus router ac68u can't connect to L2TP

### ISSUE THREAD

**Issue by PeaceMaker00** [hwdsl2/setup-ipsec-vpn#685]
As the title, also there is no field to put in IPSEC KEY
One of the logs say "Too many retransmission...." or something
I have searched everywhere to no available. Is there a workaround this ?
Thanks

**Comment by hwdsl2** [comment]
@PeaceMaker00 Hello! This router does not support [1] connecting to IPsec/L2TP VPNs.

[1] https://www.snbforums.com/threads/asus-rt-ac68u-ipsec-alternative-doesnt-show.48841/
