### ISSUE TITLE
L2TP client on Mikrotik can't connect

### ISSUE THREAD

**Issue by kalhori124** [hwdsl2/setup-ipsec-vpn#686]
Everything is OK on mobile phones and windows OS but when I set L2TP/IPSec client on Mikrotik router, it does not work.

<img width="868" alt="image" src="https://user-images.githubusercontent.com/39738894/69498822-4e398d80-0f01-11ea-86a0-d09458167dcb.png">

**Comment by turbozapekanka** [comment]
change MTU/MRU in /etc/ppp/options.xl2tpd to 1450

**Comment by letoams** [comment]
I would recommend 1200

**Comment by turbozapekanka** [comment]
I did not try 1200 but I had issues with my Synology NAS and quickconnect when it was set to 1280
I don't see a need to have it THAT low
This tool can help determine the optimal value https://cway.cisco.com/tools/ipsec-overhead-calc/

**Comment by hwdsl2** [comment]
Thanks all for the suggestions. @kalhori124 Please try changing the MTU in `/etc/ppp/options.xl2tpd` as mentioned above, then restart the xl2tpd service.
