### ISSUE TITLE
get How many users is connected

### ISSUE THREAD

**Issue by radian-rgc** [hwdsl2/setup-ipsec-vpn#689]
Hi, First of all Thank you for make this , and this is very helpful and very easy to installation.

i install it on my Centos server and every thing is work fine.
i make 400users .
and now i want to add some function to my server like : get how many users already connected and how can i set  limitation for every users for only one connection .

Best regards.

**Comment by letoams** [comment]
See: ipsec trafficstatus for connected users and their traffic.

Limiting users to 1 is done automatically if you use certificates.

**Comment by radian-rgc** [comment]
Thanks sir,
i must install some thing for check users traffic ?

for Limiting already every users can simultaneous connect in every device. what is mean about certificates ?

**Comment by hwdsl2** [comment]
@radian-rgc For using certificates please see example IKEv2 setup steps [1]. The IPsec/L2TP and IPsec/XAuth ("Cisco IPsec") modes do not support limiting each user to only one connection. Traffic status can be checked using `ipsec whack --trafficstatus` [2]. Checking traffic for each user is outside the scope of this project.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md
[2] https://libreswan.org/wiki/How_to_read_status_output
