### ISSUE TITLE
Windows 10 1909 wont connect

### ISSUE THREAD

**Issue by turbozapekanka** [hwdsl2/setup-ipsec-vpn#690]
Error:  The L2TP connection attempt failed because the security layer encountered a processing error during the initial negotiations with the remote computer.

Windows 10 1903 version works

and yes, I applied that one-time registry fix.

**Comment by newbielinuxuser** [comment]
You have to either reboot your pc that applied the registry fix or apply the 2nd registry fix. 
And dont forget to reboot your server after adding new users.

**Comment by bhatti4says** [comment]
i've just fixed this issue today, 
Nope Dear, First of all you've to verify from another device e.g. phone to verify l2tp vpn is working. if this is so, Then you've follow few steps to make it work in windows 10. 

First follow these steps in this Video on Windows 10 Client.
[](https://youtu.be/Xl3BhwLFgB4?t=571)

Then, Follow these steps, 

`Enter anything you like in the Destination name field, and then click Create.
Return to Network and Sharing Center. On the left, click Change adapter settings.
Right-click on the new VPN entry and choose Properties.
Click the Security tab. Select "Layer 2 Tunneling Protocol with IPsec (L2TP/IPSec)" for the Type of VPN.
Click Allow these protocols. Check the "Challenge Handshake Authentication Protocol (CHAP)" and "Microsoft CHAP Version 2 (MS-CHAP v2)" checkboxes.
Click the Advanced settings button.
Select Use preshared key for authentication and enter Your VPN IPsec PSK for the Key.
Click OK to close the Advanced settings.
Click OK to save the VPN connection details.`

Here's my screenshot attached. 
<img width="691" alt="image" src="https://user-images.githubusercontent.com/34199272/69997337-fc2de300-1564-11ea-8f97-1c00bf09100a.png">

**Comment by Vaniu** [comment]
Make sure you have no other clients behind your router connecting to the VPN as only one device can connect.

**Comment by hwdsl2** [comment]
Thank you all for your responses.

@turbozapekanka Please try the suggestions in this thread. You may troubleshoot further by connecting your VPN client again, then checking the Libreswan and xl2tpd logs on the VPN server for errors [1].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps

**Comment by KernelPanicNT** [comment]
> i've just fixed this issue today, Nope Dear, First of all you've to verify from another device e.g. phone to verify l2tp vpn is working. if this is so, Then you've follow few steps to make it work in windows 10.
> 
> First follow these steps in this Video on Windows 10 Client.
> 
> Then, Follow these steps,
> 
> `Enter anything you like in the Destination name field, and then click Create. Return to Network and Sharing Center. On the left, click Change adapter settings. Right-click on the new VPN entry and choose Properties. Click the Security tab. Select "Layer 2 Tunneling Protocol with IPsec (L2TP/IPSec)" for the Type of VPN. Click Allow these protocols. Check the "Challenge Handshake Authentication Protocol (CHAP)" and "Microsoft CHAP Version 2 (MS-CHAP v2)" checkboxes. Click the Advanced settings button. Select Use preshared key for authentication and enter Your VPN IPsec PSK for the Key. Click OK to close the Advanced settings. Click OK to save the VPN connection details.`
> 
> Here's my screenshot attached. <img alt="image" width="691" src="https://user-images.githubusercontent.com/34199272/69997337-fc2de300-1564-11ea-8f97-1c00bf09100a.png">

Same behaviour here :( 

Did you run pure L2TP VPN or IPSec flavour?

Which video do you mean?

Thanks in advance
