### ISSUE TITLE
Multiple users with same WAN IP

### ISSUE THREAD

**Issue by newbielinuxuser** [hwdsl2/setup-ipsec-vpn#691]
I'm facing a scenario where multiple users (different username and password) trying to connect to L2TP VPN, but it doesn't work unless there isn't any other users is connecting. 

Please advise.

**Comment by irmaster** [comment]
Me too

**Comment by Vaniu** [comment]
he said it is not possible due to nat 
https://github.com/hwdsl2/setup-ipsec-vpn/issues/55#issuecomment-242284069

**Comment by SystemDisc** [comment]
You actually are able to connect to the VPN from multiple devices with the same IP. Follow the instructions here to upgrade Libreswan:
https://github.com/hwdsl2/setup-ipsec-vpn#upgrade-libreswan

See
- This issue: https://github.com/hwdsl2/setup-ipsec-vpn/issues/378
- This comment: https://github.com/libreswan/libreswan/issues/166#issuecomment-422226790

I've followed the upgrade instructions and am now able to connect to the same VPN with the same username and same IP.

**Comment by newbielinuxuser** [comment]
Hello, I tested the upgrade scripts, but still facing the same issue, but it's on a different account though.

**Comment by SystemDisc** [comment]
You may have to reboot the services
```bash
sudo service xl2tpd restart
sudo service pppd-dns restart
```
After making sure I have the latest version of libreswan and that the xl2tpd, ppp, and ipsec configuration files are set up correctly, I am able to connect to the VPN with multiple machines behind the same public IP address.

I just checked if connecting with different accounts behind the same public IP would work (previously, I used the same account on both devices). The second device initially had issues connecting, but after trying a few times, I was able to get it to work.

Both devices I have are able to connect to the VPN using the same credentials and different credentials. When I check the public IP for each device after connecting, both are connecting to the internet via the VPNs public IP.

**Comment by newbielinuxuser** [comment]
Right, that's the only thing I haven't do, and it's working like a charm now! 
Thanks

**Comment by SystemDisc** [comment]
@hwdsl2 It may be worth noting in the README.md that multiple clients with the same WAN IP is now supported if you upgrade libreswan and restart the services.

**Comment by newbielinuxuser** [comment]
I'm still having the same problem again, after the first user logged in,
the 2nd user with a different username and password could not connect,
from the auth.log, it says

malformed payload in packet

byte at offset 1 (29) of 'ISAKMP Hash Payload'.'reserved' is 0x2a but should have been zero (ignored)

length of ISAKMP Hash Payload is larger than can fit

cannot install eroute -- it is in use for "l2tp-psk"[14]

**Comment by newbielinuxuser** [comment]
Somewhat similar
https://lists.libreswan.org/pipermail/swan/2015/001278.html

**Comment by hwdsl2** [comment]
@newbielinuxuser Hello! As mentioned in my comments in #706, due to an IPsec/L2TP limitation, it is not currently supported under IPsec/L2TP mode to connect multiple devices simultaneously from behind the same NAT (e.g. home router). This applies even if you use a separate username/password. For this use case, you must use only IPsec/XAuth mode.

The `cannot install eroute` error you encountered is probably due to this limitation. On the other hand, the "malformed payload in packet" error could be due to an incorrect IPsec pre-shared key (PSK).

**Comment by SystemDisc** [comment]
@newbielinuxuser Once libreswan v3.30 comes out, it is my understanding that IPsec/L2TP will be fully supported. Right now, it works in some cases but not all.

**Comment by newbielinuxuser** [comment]
Alright, will keep trying, i'll get back to you guys once it is working,
thanks for all the support !
