### ISSUE TITLE
How to add xauth ipsec clients?? 

### ISSUE THREAD

**Issue by bhatti4says** [hwdsl2/setup-ipsec-vpn#693]
L2tp are working in chap secrets. But how about xauth clients for addition?? Please guide.

**Comment by Vaniu** [comment]
Are you asking how to connect to the vpn using IPSec/XAuth?
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md

**Comment by bhatti4says** [comment]
Yes I was asking about that. then i've fixed this issue. Just need hash the passwords with openssl and copy paste in /etc/ipsec.d/passwd.
