### ISSUE TITLE
Why can be connected even if leave preshared-key blank? 为啥不填预共享密码也可以正常连上?

### ISSUE THREAD

**Issue by JDK88** [hwdsl2/setup-ipsec-vpn#696]
直接只填个用户名和密码就可以连上了
用mac笔记本试的，可以ssh 到192.168.42.1上
我预期的是不填那个预共享密码会连不上

**Comment by sail456852** [comment]
是吗？ 神奇啊

**Comment by JDK88** [comment]
我第一次用这脚本的时候，没有指定用户名和密码和psk(不一定是这个原因造成)，没输psk也就连上了。
因为我预期的是 "就是先用mac笔记本，不输psk连不上，然后输了psk就连的上。这样才表示ok。"
所以我第二次再去运行了一下
然后我第二次重新执行脚本，指定了（还是那句话，不一定是这个原因），就没输psk就连不上了

**Comment by hwdsl2** [comment]
@JDK88 你好！不填预共享密码 (PSK) 是连不上的，在我的测试中并没有发现问题。如果你运行脚本的时候没有指定 PSK，用户名和密码，则会自动生成随机的 PSK，用户名和密码。

如果你有更详细的信息如何重现这个问题，请提供。
