### ISSUE TITLE
Interconnecting All VPN clients and VPN Server

### ISSUE THREAD

**Issue by bhatti4says** [hwdsl2/setup-ipsec-vpn#699]
Is this possible all VPN Users are connecting to VPN Server can communicate with each other and we can reach them from VPN Server also??? Plus, followings would help this also?? 

`Access VPN server's subnet

If you wish to allow VPN clients to access the VPN server's subnet, you'll need to manually add IPTables rules after setting up the VPN server. For example, if the subnet is 192.168.0.0/24:

# For IPsec/L2TP
iptables -I FORWARD 2 -i ppp+ -d 192.168.0.0/24 -j ACCEPT
iptables -I FORWARD 2 -s 192.168.0.0/24 -o ppp+ -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

# For IPsec/XAuth ("Cisco IPsec")
iptables -I FORWARD 2 -s 192.168.43.0/24 -d 192.168.0.0/24 -j ACCEPT
iptables -I FORWARD 2 -s 192.168.0.0/24 -d 192.168.43.0/24 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
`

**Comment by hwdsl2** [comment]
@bhatti4says Hello! In the default configuration of the VPN setup scripts, VPN clients can communicate with each other (and be reached from the VPN server) using their assigned VPN internal IPs, for example, 192.168.42.10 through 192.168.42.250 when using IPsec/L2TP mode, and 192.168.43.10 through 192.168.43.250 when using IPsec/XAuth ("Cisco IPsec") mode. Check your VPN client's network status to see which IP is assigned. When using IPsec/L2TP mode, the VPN server itself has internal IP 192.168.42.1. 

If you are unable to use these IPs to connect, one possible reason could be the firewall on each VPN client device, for example, iOS/Android clients may disallow incoming traffic as part of the device's firewall.

The document section you referred to is intended for a different use case, where there is an additional subnet behind the VPN server that the VPN clients need to access.

**Comment by bhatti4says** [comment]
thank you Mr Lin, i'll do check out above information in my setup and update you here.
