### ISSUE TITLE
the connection was terminated by the remote computer before it could be completed

### ISSUE THREAD

**Issue by alicoder** [hwdsl2/setup-ipsec-vpn#7]
hi,
when I setup the vpn in windows, it give me this error:
the connection was terminated by the remote computer before it could be completed

I'm sure that IPSEC_PSK, VPN_USER and VPN_PASSWORD are set.

how to solve this?

**Comment by hwdsl2** [comment]
Hi @alicoder Please double check that you have done the following:

1. Follow the first link in "important notes" [1] to add the required registry key for enabling VPN connections behind NAT.

2. In the properties of your VPN connection, make sure that CHAP is selected in the options below.

![](http://www.vpngate.net/images/ss/l2tp_win/en/10.jpg)

Which Windows version are you using? And what is the error code?

**Comment by alicoder** [comment]
my windows in windows 10 and I'm sure that I choose the vpn type l2tp.
this is my vpn server log 
```
Feb 10 14:31:46 vps xl2tpd[2248]: Connection established to xxx.xx.xx.xx, 1701.  Local: 27930, Remote: 31 (ref=0/0).  LNS session is 'default'
Feb 10 14:31:46 vps xl2tpd[2248]: Call established with xxx.xx.xx.xx, Local: 14106, Remote: 1, Serial: 0
Feb 10 14:31:46 vps pppd[2640]: Warning: can't open options file /root/.ppprc: Permission denied
Feb 10 14:31:46 vps pppd[2640]: pppd 2.4.5 started by root, uid 0
Feb 10 14:31:46 vps pppd[2640]: Using interface ppp0
Feb 10 14:31:46 vps pppd[2640]: Connect: ppp0 <--> /dev/pts/1
Feb 10 14:31:48 vps xl2tpd[2248]: control_finish: Connection closed to xxx.xx.xx.xx, serial 0 ()
Feb 10 14:31:48 vps pppd[2640]: Modem hangup
Feb 10 14:31:48 vps pppd[2640]: Connection terminated.
Feb 10 14:31:48 vps xl2tpd[2248]: control_finish: Connection closed to xxx.xx.xx.xx, port 1701 (), Local: 27930, Remote: 31
Feb 10 14:31:48 vps pppd[2640]: Exit.

```

**Comment by hwdsl2** [comment]
Thanks for the logs. Did you check that the Challenge Handshake Authentication Protocol (CHAP) is selected (put a checkmark before it) in your VPN connection properties? See image below:

![](https://support.ivacy.com/wp-content/uploads/2015/12/011-1.png)

**Comment by alicoder** [comment]
thank you very much it's working now , I was need to check that CHAP :)

**Comment by NoahDragon** [comment]
In my scenario, I have to unchecked the MS-CHAP v2, otherwise the username/password dialog won't popup.
![image](https://cloud.githubusercontent.com/assets/5704064/14538812/96b4f930-024b-11e6-9d81-fa3d3db1ce33.png)

**Comment by hwdsl2** [comment]
Thanks for pointing this out @NoahDragon ! Are you using Windows 10?

**Comment by NoahDragon** [comment]
@hwdsl2 Win 8.1. This is really odd, because when I use my pptp server, there is no such issue.

**Comment by FrankUSC** [comment]
This link solved my issue
https://www.howtogeek.com/forum/topic/vpn-error-809

1. Run "regedit", allocate HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\RasMan\Parameters, and delete ProhibitIpSec key (Or set the value to 0).
2. Restart Windows, and try to connect VPN again.

**Comment by khangdm** [comment]
thank you so much
