### ISSUE TITLE
Support for non-empty Group Name in Cisco IPSec Setting?

### ISSUE THREAD

**Issue by yangyanli** [hwdsl2/setup-ipsec-vpn#70]
Many thanks for the scripts!

It helps a lot for setting up my VPN server, and it works well for iOS/MAC clients. However, when I was setting the client up on Ubuntu 16.04, I found that the client provided by Ubuntu doesn't support empty group name. It has to be non-empty for the VPN configuration to be saved and then be used.

I am wondering if it's possible/easy to update the setup script such that it can take a non-empty group name?

Many thanks in advance!

**Comment by hwdsl2** [comment]
@yangyanli Which VPN client are you using on Ubuntu? Please give more details such as a screenshot.

**Comment by yangyanli** [comment]
I am using network-manager-vpnc-gnome client, the default of Ubuntu, installed with:
`sudo apt-get install network-manager-vpnc-gnome`
![1](https://cloud.githubusercontent.com/assets/2976460/19256417/4b285e54-8f99-11e6-919b-d1022a71ea5c.png)

After selecting the VPN type, press "Create" to the configuration:
![2](https://cloud.githubusercontent.com/assets/2976460/19256419/51b7421c-8f99-11e6-87b5-634e767242e2.png)
Here, the save button is disabled, since the group name is empty.

![3](https://cloud.githubusercontent.com/assets/2976460/19256420/51e4c6ba-8f99-11e6-967c-06ba8c1aaa80.png)
A non-empty group name enable save.

However, since the script setup vpn without group name, if I put something there to let the configuration go through, it actually doesn't connect.

It would be nice if the setup script can support a non-empty group name, such that the default ubuntu vpn client can work with the server.

**Comment by hwdsl2** [comment]
@yangyanli Thanks for the details. It is possible to achieve what you described. When the group name is non-empty, `vpnc` will automatically use the "Aggressive Mode" of IPsec. To enable this mode, you need to make a few changes to `/etc/ipsec.conf`:

1. Open `/etc/ipsec.conf` in an editor. Find this line `cisco-unity=yes`. Add the following immediately after that line. Must indent by two spaces.

```
  rightid=@mygroup1
  aggrmode=yes
```

2. Run `service ipsec restart`.
3. Use `mygroup1` as the "Group name" in your VPN client. The IPsec PSK should be put in "Group password". Fill in the VPN username and password. Connect the VPN.

Note: You can change the "mygroup1" above to anything you like. Note that there is an `@` sign before the group name in `ipsec.conf`.

**Comment by yangyanli** [comment]
hmm, this change make it impossible to connect from any client.

here is the log from the server side:
`Oct 11 05:14:29 yangyan-vps pluto[3517]: packet from 221.173.128.34:65179: IKEv1 Aggressive Mode with PSK is vulnerable to dictionary attacks and is cracked on large scale by TLA's
Oct 11 05:14:29 yangyan-vps pluto[3517]: "xauth-psk"[1] 221.173.128.34 #1: Aggressive mode peer ID is ID_KEY_ID: '@#0x76706e'
Oct 11 05:14:29 yangyan-vps pluto[3517]: "xauth-psk"[1] 221.173.128.34 #1: EXPECTATION FAILED at /opt/src/libreswan-3.18/programs/pluto/ikev1.c:2834: r != NULL
Oct 11 05:14:29 yangyan-vps pluto[3517]: "xauth-psk"[1] 221.173.128.34 #1: no suitable connection for peer '@#0x76706e'
Oct 11 05:14:29 yangyan-vps pluto[3517]: "xauth-psk"[1] 221.173.128.34 #1: initial Aggressive Mode packet claiming to be from @vpn on 221.173.128.34 but no connection has been authorized
Oct 11 05:14:29 yangyan-vps pluto[3517]: "xauth-psk"[1] 221.173.128.34 #1: sending notification INVALID_ID_INFORMATION to 221.173.128.34:65179`

**Comment by hwdsl2** [comment]
@yangyanli Try this: Edit /etc/ipsec.conf and replace "rightid=@mygroup1" with "rightid=@[mygroup1]". Note the square brackets. Save the file and restart IPsec service. I think it should work after this change.

**Comment by yangyanli** [comment]
Many thanks for the speedy reply! Now, it's a different problem:

> Oct 11 07:01:12 yangyan-vps pluto[22496]: packet from 221.173.128.34:16851: IKEv1 Aggressive Mode with PSK is vulnerable to dictionary attacks and is cracked on large scale by TLA's
Oct 11 07:01:12 yangyan-vps pluto[22496]: "xauth-psk"[1] 221.173.128.34 #1: Aggressive mode peer ID is ID_KEY_ID: '@#0x76706e'
Oct 11 07:01:12 yangyan-vps pluto[22496]: "xauth-psk"[1] 221.173.128.34 #1: responding to Aggressive Mode, state #1, connection "xauth-psk"[1] 221.173.128.34 from 221.173.128.34
Oct 11 07:01:12 yangyan-vps pluto[22496]: "xauth-psk"[1] 221.173.128.34 #1: transition from state STATE_AGGR_R0 to state STATE_AGGR_R1
Oct 11 07:01:12 yangyan-vps pluto[22496]: "xauth-psk"[1] 221.173.128.34 #1: STATE_AGGR_R1: sent AR1, expecting AI2
Oct 11 07:01:12 yangyan-vps pluto[22496]: "xauth-psk"[1] 221.173.128.34 #1: next payload type of ISAKMP Hash Payload has an unknown value: 90 (0x5a)
Oct 11 07:01:12 yangyan-vps pluto[22496]: "xauth-psk"[1] 221.173.128.34 #1: malformed payload in packet

**Comment by hwdsl2** [comment]
@yangyanli "malformed payload" means your "group password" entered in your VPN client does not match the IPsec PSK in /etc/ipsec.secrets on the server. They must match exactly. Please double check. Also try changing to a PSK without special characters and restart IPsec service.

**Comment by yangyanli** [comment]
I had switched to ss solution before further investigation of the problem, so I didn't try whether this can resolve the problem. Many thanks again for the help!

**Comment by hwdsl2** [comment]
@yangyanli You're welcome. Thanks for letting us know! Closing.
