### ISSUE TITLE
YouTube安卓客户端可以加载评论和视频说明但是无法播放视频

### ISSUE THREAD

**Issue by tangsir001** [hwdsl2/setup-ipsec-vpn#700]
YouTube安卓客户端可以加载评论和视频说明，但是无法播放视频。视频本身无法缓冲，重装YouTube或者清除应用数据可以播放视频，但是关闭YouTube后重启又不能播放视频了；使用v2ray VPN则可以正常使用YouTube，看起来YouTube客户端没有被ipsec VPN代理。

**Comment by hwdsl2** [comment]
@tangsir001 你好！你可以尝试一下调整 `sha2-truncbug` 设置，看看是否有帮助。该问题可能与你的服务器提供商或者安卓设备本身有关，在我最近的测试中并没有发现这个问题。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#android-6-%E5%92%8C-7

**Comment by suinile** [comment]
出现同样的问题，使用的IKEV2,安卓iOS都能正常加载youtube视频及打开google网站。windows11只能打开youtube网站，不能加载视频，也不能打开google网站。

**Comment by suinile** [comment]
> 出现同样的问题，使用的IKEV2,安卓iOS都能正常加载youtube视频及打开google网站。windows11只能打开youtube网站，不能加载视频，也不能打开google网站。

是路由器的原因，换个路由器就可以了。
