### ISSUE TITLE
要怎么把log打开？

### ISSUE THREAD

**Issue by JDK88** [hwdsl2/setup-ipsec-vpn#702]
我想把server这边的log全打开，级别最好开到debug，因为我client那边有receieved DELETE for ESP CHILD_SA with SPI ... 不知道啥原因，想看看log
另外改了之后要怎么重启？

**Comment by hwdsl2** [comment]
@JDK88 See `plutodebug` in [1]. Restart the IPsec service with `sudo service ipsec restart`.

[1] https://libreswan.org/man/ipsec.conf.5.html
