### ISSUE TITLE
multiple users

### ISSUE THREAD

**Issue by Daariush** [hwdsl2/setup-ipsec-vpn#703]
Cant connect to another user account while another user is connected, is there a way to do that?

**Comment by hwdsl2** [comment]
@Daariush Hello! This is a limitation of IPsec/L2TP regarding multiple users from behind the same NAT, as mentioned in the important notes. Try using only IPsec/XAuth ("Cisco IPsec") mode [2].

[1] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md
