### ISSUE TITLE
Two clients in the same subnet failed to connect to the VPN server simultaneously, only one can be successful

### ISSUE THREAD

**Issue by eyeloveu** [hwdsl2/setup-ipsec-vpn#708]
I successfully deployed my VPN server by running the batch script. Yet I found that clients failed to connect to the server if there is one client which has already been connected, no matter whatever operation system combinations, e.g. win and win, win and Ubuntu, Linux and Linux.

I also have tried with different users, and it failed either.

**Comment by admincrew** [comment]
Maybe you could try using https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md

**Comment by eyeloveu** [comment]
> Maybe you could try using https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md

Thank you!
I've found the instruction said that 'However, due to an IPsec/L2TP limitation, if you wish to connect multiple devices simultaneously from behind the same NAT (e.g. home router), you must use only IPsec/XAuth mode.'
