### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by conexaoalisson** [hwdsl2/setup-ipsec-vpn#709]
Thanks so much for the script and the tutorial.
Doing this manually is very difficult.
Thanks to your script, everything is easy.

I would like to leave a suggestion for the future.
Add IPv6 Support
And a way to use NAT over VPN over IPv4.
I even tried using iptables, but still can't.

Today I use Centos V7
Congratulations for the script.

**Comment by hwdsl2** [comment]
@conexaoalisson You are welcome! I am glad the project is useful for you.

IPv6 is not supported at this time. Thanks for your suggestions!
