### ISSUE TITLE
Sending VPN-Usertraffic through SQUID?

### ISSUE THREAD

**Issue by Gill-Bates** [hwdsl2/setup-ipsec-vpn#710]
Is it possible to send Usertraffic from a VPN-Client through SQUID Proxy?
Squid is running on 3128 on the same machine.

I was thing of adding something like this to the `/etc/iptables.rules`

`iptables -t nat -A PREROUTING -i eth1 -p tcp --dport 80 -j DNAT --to 0.0.0.0:3128`
`iptables -t nat -A PREROUTING -i eth1 -p tcp --dport 443 -j DNAT --to 0.0.0.0:3128`

**Comment by hwdsl2** [comment]
@Gill-Bates Hello! I don't know about this use case. I suggest that you ask on the Libreswan or strongSwan users mailing list, or other relevant community forum(s).

**Comment by letoams** [comment]
On Sat, 28 Dec 2019, Gill Bates wrote:

> Is it possible to send Usertraffic from a VPN-Client through SQUID Proxy?
> Squid is running on 3128 on the same machine.
> 
> I was thing of adding something like this to the /etc/iptables.rules
> 
> iptables -t nat -A PREROUTING -i eth1 -p tcp --dport 80 -j DNAT --to 192.168.1.1:3128 iptables -t nat -A PREROUTING -i eth0 -p tcp
> --dport 80 -j REDIRECT --to-port 3128

Yes it is possible, however with widespread TLS out there, you will only
see like 5% of all web traffic on your proxy. So it's not worth the
setup.

Paul
