### ISSUE TITLE
Is fail2ban needed?

### ISSUE THREAD

**Issue by markkolich** [hwdsl2/setup-ipsec-vpn#711]
First, thanks for the script!

It ran flawlessly on a Raspberry Pi 4B running Raspbian 10.

I combed through `vpnsetup.sh` before running it, and noticed it installs `fail2ban`:

https://github.com/hwdsl2/setup-ipsec-vpn/blob/4b28ce5de91e75efdbbccb6f5992e3d9458560c1/vpnsetup.sh#L167-L169

Nothing against `fail2ban`, but it's something I don't want to install (or wouldn't think I'd have to install as part of the VPN setup). I deleted all `fail2ban` references from the script and it ran fine.

Is `fail2ban` a requirement, or just something the script is installing as a suggested best practice to harden a system? If it's the latter, perhaps giving the user an option to skip the `fail2ban` install is warranted?

Happy to submit a PR.

**Comment by hwdsl2** [comment]
@markkolich Thank you for the suggestion! Yes, you are correct that the `fail2ban` is added as a best practice to harden a system. Currently, there is no command line parameter(s) to customize the script for skipping this. However, advanced users can edit the script and remove the `fail2ban` related lines without affecting the functionality of the VPN.
