### ISSUE TITLE
cant connect to server

### ISSUE THREAD

**Issue by benyamin95** [hwdsl2/setup-ipsec-vpn#714]
root@kd20621:~# systemctl status xl2tpd
● xl2tpd.service - LSB: layer 2 tunelling protocol daemon
   Loaded: loaded (/etc/init.d/xl2tpd; generated; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-01-02 10:06:26 UTC; 3min 26s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 13422 ExecStart=/etc/init.d/xl2tpd start (code=exited, status=1/FAILURE)

Jan 02 10:06:26 kd20621 systemd[1]: xl2tpd.service: Failed to reset devices.list: Operation not permitted
Jan 02 10:06:26 kd20621 systemd[1]: Starting LSB: layer 2 tunelling protocol daemon...
Jan 02 10:06:26 kd20621 xl2tpd[13422]: Starting xl2tpd:
Jan 02 10:06:26 kd20621 systemd[1]: xl2tpd.service: Control process exited, code=exited status=1
Jan 02 10:06:26 kd20621 systemd[1]: Failed to start LSB: layer 2 tunelling protocol daemon.
Jan 02 10:06:26 kd20621 systemd[1]: xl2tpd.service: Unit entered failed state.
Jan 02 10:06:26 kd20621 systemd[1]: xl2tpd.service: Failed with result 'exit-code'.
root@kd20621:~# systemctl status ipsec
● ipsec.service - Internet Key Exchange (IKE) Protocol Daemon for IPsec
   Loaded: loaded (/lib/systemd/system/ipsec.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-01-02 10:06:26 UTC; 4min 5s ago
     Docs: man:ipsec(8)
           man:pluto(8)
           man:ipsec.conf(5)
  Process: 13382 ExecStartPre=/usr/local/sbin/ipsec --checknflog (code=exited, status=0/SUCCESS)
  Process: 13379 ExecStartPre=/usr/local/sbin/ipsec --checknss (code=exited, status=0/SUCCESS)
  Process: 13230 ExecStartPre=/usr/local/libexec/ipsec/_stackmanager start (code=exited, status=0/SUCCESS)
  Process: 13229 ExecStartPre=/usr/local/libexec/ipsec/addconn --config /etc/ipsec.conf --checkconfig (code=exited, status=0/SUCCESS)
 Main PID: 13393 (pluto)
   Status: "Startup completed."
    Tasks: 24 (limit: 4915)
   CGroup: /system.slice/ipsec.service
           └─13393 /usr/local/libexec/ipsec/pluto --leak-detective --config /etc/ipsec.conf --nofork

Jan 02 10:08:58 kd20621 pluto[13393]: "l2tp-psk"[2] 188.212.244.32 #2: responding to Quick Mode proposal {msgid:e077a287}
Jan 02 10:08:58 kd20621 pluto[13393]: "l2tp-psk"[2] 188.212.244.32 #2:     us: 134.255.216.116:17/1701
Jan 02 10:08:58 kd20621 pluto[13393]: "l2tp-psk"[2] 188.212.244.32 #2:   them: 188.212.244.32[192.168.1.101]:17/0
Jan 02 10:08:58 kd20621 pluto[13393]: "l2tp-psk"[2] 188.212.244.32 #2: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 transport mode {ESP/NAT=>0x08e0
Jan 02 10:08:59 kd20621 pluto[13393]: "l2tp-psk"[2] 188.212.244.32 #2: STATE_QUICK_R2: IPsec SA established transport mode {ESP/NAT=>0x08e0b3a1 <0xe56eac28 xfrm=AES_CBC_2
Jan 02 10:09:57 kd20621 pluto[13393]: "l2tp-psk"[2] 188.212.244.32 #1: received Delete SA(0x08e0b3a1) payload: deleting IPsec State #2
Jan 02 10:09:57 kd20621 pluto[13393]: "l2tp-psk"[2] 188.212.244.32 #2: deleting other state #2 (STATE_QUICK_R2) aged 58.985s and sending notification
Jan 02 10:09:57 kd20621 pluto[13393]: "l2tp-psk"[2] 188.212.244.32 #2: ESP traffic information: in=2KB out=0B
Jan 02 10:09:57 kd20621 pluto[13393]: "l2tp-psk" #1: deleting state (STATE_MAIN_R3) aged 59.669s and sending notification
Jan 02 10:09:57 kd20621 pluto[13393]: "l2tp-psk"[2] 188.212.244.32: deleting connection "l2tp-psk"[2] 188.212.244.32 instance with peer 188.212.244.32 {isakmp=#0/ipsec=#0
lines 1-26/26 (END)

**Comment by letoams** [comment]
On Thu, 2 Jan 2020, benyamin95 wrote:

> Jan 02 10:06:26 kd20621 systemd[1]: xl2tpd.service: Failed to reset devices.list: Operation not permitted

This seems to be related to the new cgroupv2 stuff, but as I understand
it, it is not a fatal error and something else is actually going on.

> Jan 02 10:06:26 kd20621 systemd[1]: Starting LSB: layer 2 tunelling protocol daemon...
> Jan 02 10:06:26 kd20621 xl2tpd[13422]: Starting xl2tpd:
> Jan 02 10:06:26 kd20621 systemd[1]: xl2tpd.service: Control process exited, code=exited status=1

Maybe run it in the foregroup manually and see what is going on?

xl2tpd -D


> root@kd20621:~# systemctl status ipsec
> ● ipsec.service - Internet Key Exchange (IKE) Protocol Daemon for IPsec
> Loaded: loaded (/lib/systemd/system/ipsec.service; enabled; vendor preset: enabled)
> Active: active (running) since Thu 2020-01-02 10:06:26 UTC; 4min 5s ago

That part seems okay.

> Jan 02 10:09:57 kd20621 pluto[13393]: "l2tp-psk"[2] 188.212.244.32 #2: ESP traffic information: in=2KB out=0B
> Jan 02 10:09:57 kd20621 pluto[13393]: "l2tp-psk" #1: deleting state (STATE_MAIN_R3) aged 59.669s and sending

The client is deleting after establishing IPsec because the L2TP is
failing, because your xl2tpd daemon failed to start.

**Comment by benyamin95** [comment]
@letoams hi man , thx for your respond i appreciate it.
i got this .
root@kd20621:~# xl2tpd -D
xl2tpd[13952]: init_config: Unable to open config file /etc/xl2tpd/xl2tpd.conf o                               r /etc/l2tp/l2tpd.conf
xl2tpd[13952]: init: Unable to load config file

**Comment by benyamin95** [comment]
i looked for it and there s no xl2tpd folder :||

**Comment by benyamin95** [comment]
please som1 help me in this , the script smh fails to create xl2tpd folders and files , what should i do ?

**Comment by hwdsl2** [comment]
@benyamin95 This error: `Failed to reset devices.list: Operation not permitted` could indicate that you ran the VPN setup script from inside a container. Please provide more details of your setup. Running inside an OpenVZ or LXD container is not supported, as `/dev/ppp` and/or the required kernel modules may be unavailable.

**Comment by benyamin95** [comment]
@hwdsl2 hello there , thank you for your respond.
I am using zap hosting germany , im not sure that its inside a container or not, btw xl2tpd files are not created at all in /etc

**Comment by hwdsl2** [comment]
@benyamin95 I would suggest that you try a different hosting provider with a KVM-based VPS. The VPN setup scripts were recently tested and they worked fine in the tests.
