### ISSUE TITLE
No Internet Connection after 8hours

### ISSUE THREAD

**Issue by AnT00961** [hwdsl2/setup-ipsec-vpn#716]
Hello,

i am getting no internet connection after **8hours** of connectivity.

**Comment by letoams** [comment]
Looks like the client isn’t rekeying the IPsec SA? You can set salifetime=24h (the maximum allowed) in the server but the client should be reconfigured to allow rekeying.

**Comment by hwdsl2** [comment]
Thanks @letoams!

@AnT00961 Try setting `salifetime=24h` in `/etc/ipsec.conf` and run `service ipsec restart`, and make sure your VPN client has re-key enabled. Note that an IKEv2 re-key issue #676 is set to be fixed in the next Libreswan version.
