### ISSUE TITLE
mac 10.14.6 连接不上vpn

### ISSUE THREAD

**Issue by hiabp** [hwdsl2/setup-ipsec-vpn#717]
配置已经按照说明检查过，都正确。
手机iphone可能连接上。相同的配置。但是mac os连接不上。

**Comment by hwdsl2** [comment]
@guoxiangwei 你好！macOS 10.14 (Mojave) 在我的测试中没有发现问题。请把两个模式都试一下（IPsec/L2TP,
IPsec/XAuth）。检查你的客户端 VPN 凭证是否输入正确。另外用自述中的故障排除链接的最后一小节的命令检查一下 VPN 服务器日志。
