### ISSUE TITLE
I can't connect in my ubuntu 18.04

### ISSUE THREAD

**Issue by xdnroot** [hwdsl2/setup-ipsec-vpn#718]
I follow the guide to configure client on ubuntu 18.04 but the connection failed. Meanwhile, I tried in mobile phone, it's works.

this is /var/log/syslog
`Jan 15 20:58:48 xdn-id nm-l2tp-service[31469]: Check port 1701`
`Jan 15 20:58:48 xdn-id nm-l2tp-service[31469]: Can't bind to port 1701`
`Jan 15 20:58:48 xdn-id NetworkManager[1145]: Stopping strongSwan IPsec failed: starter is not running`

**Comment by hwdsl2** [comment]
@xdnroot Thanks for reporting. Looks like this is a known issue [1] [2] in NetworkManager-l2tp. Please try the workaround in [2], and let us know if it works.

[1] https://github.com/nm-l2tp/NetworkManager-l2tp/issues/38#issuecomment-538962348
[2] https://github.com/nm-l2tp/NetworkManager-l2tp/blob/master/README.md#issue-with-not-stopping-system-xl2tpd-service

**Comment by xdnroot** [comment]
> @xdnroot Thanks for reporting. Looks like this is a known issue [1] [2] in NetworkManager-l2tp. Please try the workaround in [2], and let us know if it works.
> 
> [1] [nm-l2tp/NetworkManager-l2tp#38 (comment)](https://github.com/nm-l2tp/NetworkManager-l2tp/issues/38#issuecomment-538962348)
> [2] https://github.com/nm-l2tp/NetworkManager-l2tp/blob/master/README.md#issue-with-not-stopping-system-xl2tpd-service

Okay thanks. it's works right now.

**Comment by falk-stefan** [comment]
Just got the same issue on Ubuntu 20.
