### ISSUE TITLE
TP-Link TL-WAR1200L 路由器可以建立ipsec加密隧道，但是无法成功拨号

### ISSUE THREAD

**Issue by xieyanfu** [hwdsl2/setup-ipsec-vpn#719]
这个是　ipsec status　的日志：

000 using kernel interface: netkey
000 interface lo/lo 127.0.0.1@4500
000 interface lo/lo 127.0.0.1@500
000 interface eth0/eth0 172.17.0.2@4500
000 interface eth0/eth0 172.17.0.2@500
000  
000  
000 fips mode=disabled;
000 SElinux=disabled
000 seccomp=unsupported
000  
000 config setup options:
000  
000 configdir=/etc, configfile=/etc/ipsec.conf, secrets=/etc/ipsec.secrets, ipsecdir=/etc/ipsec.d
000 nssdir=/etc/ipsec.d, dumpdir=/run/pluto, statsbin=unset
000 sbindir=/usr/local/sbin, libexecdir=/usr/local/libexec/ipsec
000 pluto_version=3.29, pluto_vendorid=OE-Libreswan-3.29
000 nhelpers=-1, uniqueids=no, dnssec-enable=no, perpeerlog=no, logappend=yes, logip=yes, shuntlifetime=900s, xfrmlifetime=30s
000 ddos-cookies-threshold=50000, ddos-max-halfopen=25000, ddos-mode=auto
000 ikeport=500, ikebuf=0, msg_errqueue=yes, strictcrlpolicy=no, crlcheckinterval=0, listen=<any>, nflog-all=0
000 ocsp-enable=no, ocsp-strict=no, ocsp-timeout=2, ocsp-uri=<unset>
000 ocsp-trust-name=<unset>
000 ocsp-cache-size=1000, ocsp-cache-min-age=3600, ocsp-cache-max-age=86400, ocsp-method=get
000 global-redirect=no, global-redirect-to=<unset>
000 secctx-attr-type=32001
000 debug:
000  
000 nat-traversal=yes, keep-alive=20, nat-ikeport=4500
000 virtual-private (%priv):
000 - allowed subnets: 10.0.0.0/8, 192.168.0.0/16, 172.16.0.0/12
000 - excluded subnets: 192.168.42.0/24, 192.168.43.0/24
000  
000 Kernel algorithms supported:
000  
000 algorithm ESP encrypt: name=3DES_CBC, keysizemin=192, keysizemax=192
000 algorithm ESP encrypt: name=AES_CBC, keysizemin=128, keysizemax=256
000 algorithm ESP encrypt: name=AES_CCM_12, keysizemin=128, keysizemax=256
000 algorithm ESP encrypt: name=AES_CCM_16, keysizemin=128, keysizemax=256
000 algorithm ESP encrypt: name=AES_CCM_8, keysizemin=128, keysizemax=256
000 algorithm ESP encrypt: name=AES_CTR, keysizemin=128, keysizemax=256
000 algorithm ESP encrypt: name=AES_GCM_12, keysizemin=128, keysizemax=256
000 algorithm ESP encrypt: name=AES_GCM_16, keysizemin=128, keysizemax=256
000 algorithm ESP encrypt: name=AES_GCM_8, keysizemin=128, keysizemax=256
000 algorithm ESP encrypt: name=CAMELLIA_CBC, keysizemin=128, keysizemax=256
000 algorithm ESP encrypt: name=CHACHA20_POLY1305, keysizemin=256, keysizemax=256
000 algorithm ESP encrypt: name=NULL, keysizemin=0, keysizemax=0
000 algorithm ESP encrypt: name=NULL_AUTH_AES_GMAC, keysizemin=128, keysizemax=256
000 algorithm ESP encrypt: name=SERPENT_CBC, keysizemin=128, keysizemax=256
000 algorithm ESP encrypt: name=TWOFISH_CBC, keysizemin=128, keysizemax=256
000 algorithm AH/ESP auth: name=AES_CMAC_96, key-length=128
000 algorithm AH/ESP auth: name=AES_XCBC_96, key-length=128
000 algorithm AH/ESP auth: name=HMAC_MD5_96, key-length=128
000 algorithm AH/ESP auth: name=HMAC_SHA1_96, key-length=160
000 algorithm AH/ESP auth: name=HMAC_SHA2_256_128, key-length=256
000 algorithm AH/ESP auth: name=HMAC_SHA2_256_TRUNCBUG, key-length=256
000 algorithm AH/ESP auth: name=HMAC_SHA2_384_192, key-length=384
000 algorithm AH/ESP auth: name=HMAC_SHA2_512_256, key-length=512
000 algorithm AH/ESP auth: name=NONE, key-length=0
000  
000 IKE algorithms supported:
000  
000 algorithm IKE encrypt: v1id=5, v1name=OAKLEY_3DES_CBC, v2id=3, v2name=3DES, blocksize=8, keydeflen=192
000 algorithm IKE encrypt: v1id=8, v1name=OAKLEY_CAMELLIA_CBC, v2id=23, v2name=CAMELLIA_CBC, blocksize=16, keydeflen=128
000 algorithm IKE encrypt: v1id=-1, v1name=n/a, v2id=20, v2name=AES_GCM_C, blocksize=16, keydeflen=128
000 algorithm IKE encrypt: v1id=-1, v1name=n/a, v2id=19, v2name=AES_GCM_B, blocksize=16, keydeflen=128
000 algorithm IKE encrypt: v1id=-1, v1name=n/a, v2id=18, v2name=AES_GCM_A, blocksize=16, keydeflen=128
000 algorithm IKE encrypt: v1id=13, v1name=OAKLEY_AES_CTR, v2id=13, v2name=AES_CTR, blocksize=16, keydeflen=128
000 algorithm IKE encrypt: v1id=7, v1name=OAKLEY_AES_CBC, v2id=12, v2name=AES_CBC, blocksize=16, keydeflen=128
000 algorithm IKE encrypt: v1id=65004, v1name=OAKLEY_SERPENT_CBC, v2id=65004, v2name=SERPENT_CBC, blocksize=16, keydeflen=128
000 algorithm IKE encrypt: v1id=65005, v1name=OAKLEY_TWOFISH_CBC, v2id=65005, v2name=TWOFISH_CBC, blocksize=16, keydeflen=128
000 algorithm IKE encrypt: v1id=65289, v1name=OAKLEY_TWOFISH_CBC_SSH, v2id=65289, v2name=TWOFISH_CBC_SSH, blocksize=16, keydeflen=128
000 algorithm IKE encrypt: v1id=-1, v1name=n/a, v2id=28, v2name=CHACHA20_POLY1305, blocksize=16, keydeflen=256
000 algorithm IKE PRF: name=HMAC_MD5, hashlen=16
000 algorithm IKE PRF: name=HMAC_SHA1, hashlen=20
000 algorithm IKE PRF: name=HMAC_SHA2_256, hashlen=32
000 algorithm IKE PRF: name=HMAC_SHA2_384, hashlen=48
000 algorithm IKE PRF: name=HMAC_SHA2_512, hashlen=64
000 algorithm IKE PRF: name=AES_XCBC, hashlen=16
000 algorithm IKE DH Key Exchange: name=MODP1024, bits=1024
000 algorithm IKE DH Key Exchange: name=MODP1536, bits=1536
000 algorithm IKE DH Key Exchange: name=MODP2048, bits=2048
000 algorithm IKE DH Key Exchange: name=MODP3072, bits=3072
000 algorithm IKE DH Key Exchange: name=MODP4096, bits=4096
000 algorithm IKE DH Key Exchange: name=MODP6144, bits=6144
000 algorithm IKE DH Key Exchange: name=MODP8192, bits=8192
000 algorithm IKE DH Key Exchange: name=DH19, bits=512
000 algorithm IKE DH Key Exchange: name=DH20, bits=768
000 algorithm IKE DH Key Exchange: name=DH21, bits=1056
000  
000 stats db_ops: {curr_cnt, total_cnt, maxsz} :context={0,0,0} trans={0,0,0} attrs={0,0,0} 
000  
000 Connection list:
000  
000 "l2tp-psk": 172.17.0.2[47.74.33.13]:17/1701---172.17.0.1...%any:17/%any; unrouted; eroute owner: #0
000 "l2tp-psk":     oriented; my_ip=unset; their_ip=unset; my_updown=ipsec _updown;
000 "l2tp-psk":   xauth us:none, xauth them:none,  my_username=[any]; their_username=[any]
000 "l2tp-psk":   our auth:secret, their auth:secret
000 "l2tp-psk":   modecfg info: us:none, them:none, modecfg policy:push, dns:unset, domains:unset, banner:unset, cat:unset;
000 "l2tp-psk":   labeled_ipsec:no;
000 "l2tp-psk":   policy_label:unset;
000 "l2tp-psk":   ike_life: 3600s; ipsec_life: 28800s; replay_window: 32; rekey_margin: 540s; rekey_fuzz: 100%; keyingtries: 5;
000 "l2tp-psk":   retransmit-interval: 500ms; retransmit-timeout: 60s;
000 "l2tp-psk":   initial-contact:no; cisco-unity:no; fake-strongswan:no; send-vendorid:no; send-no-esp-tfc:no;
000 "l2tp-psk":   policy: PSK+ENCRYPT+DONT_REKEY+IKEV1_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO;
000 "l2tp-psk":   conn_prio: 32,32; interface: eth0; metric: 0; mtu: unset; sa_prio:auto; sa_tfc:none;
000 "l2tp-psk":   nflog-group: unset; mark: unset; vti-iface:unset; vti-routing:no; vti-shared:no; nic-offload:auto;
000 "l2tp-psk":   our idtype: ID_IPV4_ADDR; our id=47.74.33.13; their idtype: %none; their id=(none)
000 "l2tp-psk":   dpd: action:clear; delay:30; timeout:120; nat-t: encaps:yes; nat_keepalive:yes; ikev1_natt:both
000 "l2tp-psk":   newest ISAKMP SA: #0; newest IPsec SA: #0;
000 "l2tp-psk":   IKE algorithms: 3DES_CBC-HMAC_MD5-MODP1024, 3DES_CBC-HMAC_SHA1-MODP1024
000 "l2tp-psk":   ESP algorithms: 3DES_CBC-HMAC_MD5_96, 3DES_CBC-HMAC_SHA1_96
000 "l2tp-psk"[4]: 172.17.0.2[47.74.33.13]:17/1701---172.17.0.1...223.167.116.147[192.168.88.108]:17/1701; erouted; eroute owner: #4
000 "l2tp-psk"[4]:     oriented; my_ip=unset; their_ip=unset; my_updown=ipsec _updown;
000 "l2tp-psk"[4]:   xauth us:none, xauth them:none,  my_username=[any]; their_username=[any]
000 "l2tp-psk"[4]:   our auth:secret, their auth:secret
000 "l2tp-psk"[4]:   modecfg info: us:none, them:none, modecfg policy:push, dns:unset, domains:unset, banner:unset, cat:unset;
000 "l2tp-psk"[4]:   labeled_ipsec:no;
000 "l2tp-psk"[4]:   policy_label:unset;
000 "l2tp-psk"[4]:   ike_life: 3600s; ipsec_life: 28800s; replay_window: 32; rekey_margin: 540s; rekey_fuzz: 100%; keyingtries: 5;
000 "l2tp-psk"[4]:   retransmit-interval: 500ms; retransmit-timeout: 60s;
000 "l2tp-psk"[4]:   initial-contact:no; cisco-unity:no; fake-strongswan:no; send-vendorid:no; send-no-esp-tfc:no;
000 "l2tp-psk"[4]:   policy: PSK+ENCRYPT+DONT_REKEY+IKEV1_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO;
000 "l2tp-psk"[4]:   conn_prio: 32,32; interface: eth0; metric: 0; mtu: unset; sa_prio:auto; sa_tfc:none;
000 "l2tp-psk"[4]:   nflog-group: unset; mark: unset; vti-iface:unset; vti-routing:no; vti-shared:no; nic-offload:auto;
000 "l2tp-psk"[4]:   our idtype: ID_IPV4_ADDR; our id=47.74.33.13; their idtype: ID_IPV4_ADDR; their id=192.168.88.108
000 "l2tp-psk"[4]:   dpd: action:clear; delay:30; timeout:120; nat-t: encaps:yes; nat_keepalive:yes; ikev1_natt:both
000 "l2tp-psk"[4]:   newest ISAKMP SA: #3; newest IPsec SA: #4;
000 "l2tp-psk"[4]:   IKE algorithms: 3DES_CBC-HMAC_MD5-MODP1024, 3DES_CBC-HMAC_SHA1-MODP1024
000 "l2tp-psk"[4]:   IKEv1 algorithm newest: 3DES_CBC_192-HMAC_MD5-MODP1024
000 "l2tp-psk"[4]:   ESP algorithms: 3DES_CBC-HMAC_MD5_96, 3DES_CBC-HMAC_SHA1_96
000 "l2tp-psk"[4]:   ESP algorithm newest: 3DES_CBC_192-HMAC_SHA1_96; pfsgroup=<N/A>
000 "xauth-psk": 0.0.0.0/0===172.17.0.2[47.74.33.13,MS+XS+S=C]---172.17.0.1...%any[+MC+XC+S=C]; unrouted; eroute owner: #0
000 "xauth-psk":     oriented; my_ip=unset; their_ip=unset; my_updown=ipsec _updown;
000 "xauth-psk":   xauth us:server, xauth them:client, xauthby:file; my_username=[any]; their_username=[any]
000 "xauth-psk":   our auth:secret, their auth:secret
000 "xauth-psk":   modecfg info: us:server, them:client, modecfg policy:pull, dns:8.8.8.8 8.8.4.4, domains:unset, banner:unset, cat:unset;
000 "xauth-psk":   labeled_ipsec:no;
000 "xauth-psk":   policy_label:unset;
000 "xauth-psk":   ike_life: 3600s; ipsec_life: 28800s; replay_window: 32; rekey_margin: 540s; rekey_fuzz: 100%; keyingtries: 5;
000 "xauth-psk":   retransmit-interval: 500ms; retransmit-timeout: 60s;
000 "xauth-psk":   initial-contact:no; cisco-unity:yes; fake-strongswan:no; send-vendorid:no; send-no-esp-tfc:no;
000 "xauth-psk":   policy: PSK+ENCRYPT+TUNNEL+DONT_REKEY+XAUTH+MODECFG_PULL+IKEV1_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO;
000 "xauth-psk":   conn_prio: 0,32; interface: eth0; metric: 0; mtu: unset; sa_prio:auto; sa_tfc:none;
000 "xauth-psk":   nflog-group: unset; mark: unset; vti-iface:unset; vti-routing:no; vti-shared:no; nic-offload:auto;
000 "xauth-psk":   our idtype: ID_IPV4_ADDR; our id=47.74.33.13; their idtype: %none; their id=(none)
000 "xauth-psk":   dpd: action:clear; delay:30; timeout:120; nat-t: encaps:yes; nat_keepalive:yes; ikev1_natt:both
000 "xauth-psk":   newest ISAKMP SA: #0; newest IPsec SA: #0;
000 "xauth-psk":   IKE algorithms: 3DES_CBC-HMAC_MD5-MODP1024, 3DES_CBC-HMAC_SHA1-MODP1024
000 "xauth-psk":   ESP algorithms: 3DES_CBC-HMAC_MD5_96, 3DES_CBC-HMAC_SHA1_96
000  
000 Total IPsec connections: loaded 3, active 1
000  
000 State Information: DDoS cookies not required, Accepting new IKE connections
000 IKE SAs: total(1), half-open(0), open(0), authenticated(1), anonymous(0)
000 IPsec SAs: total(1), authenticated(1), anonymous(0)
000  
000 #3: "l2tp-psk"[4] 223.167.116.147:4500 STATE_MAIN_R3 (sent MR3, ISAKMP SA established); EVENT_SA_EXPIRE in 38281s; newest ISAKMP; lastdpd=28s(seq in:22182 out:0); idle;
000 #4: "l2tp-psk"[4] 223.167.116.147:4500 STATE_QUICK_R2 (IPsec SA established); EVENT_SA_EXPIRE in 28652s; newest IPSEC; eroute owner; isakmp#3; idle;
000 #4: "l2tp-psk"[4] 223.167.116.147 esp.cba2a1de@223.167.116.147 esp.212e996b@172.17.0.2 ref=0 refhim=0 Traffic: ESPin=0B ESPout=0B! ESPmax=4194303B 
000  
000 Bare Shunt list:
000  

－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－

下面是　grep pluto /var/log/auth.log　的结果

Jan 16 09:36:39 08eb072dc5c1 pluto[575]: "l2tp-psk"[2] 223.167.116.147 #1: received Delete SA(0xc12a90bb) payload: deleting IPsec State #2
Jan 16 09:36:39 08eb072dc5c1 pluto[575]: "l2tp-psk"[2] 223.167.116.147 #2: deleting other state #2 (STATE_QUICK_R2) aged 481.036s and sending notification
Jan 16 09:36:39 08eb072dc5c1 pluto[575]: "l2tp-psk"[2] 223.167.116.147 #2: ESP traffic information: in=0B out=0B
Jan 16 09:36:39 08eb072dc5c1 pluto[575]: "l2tp-psk" #1: deleting state (STATE_MAIN_R3) aged 481.251s and sending notification
Jan 16 09:36:39 08eb072dc5c1 pluto[575]: "l2tp-psk"[2] 223.167.116.147: deleting connection "l2tp-psk"[2] 223.167.116.147 instance with peer 223.167.116.147 {isakmp=#0/ipsec=#0}
Jan 16 09:36:51 08eb072dc5c1 pluto[575]: "l2tp-psk"[3] 223.167.116.147 #3: responding to Main Mode from unknown peer 223.167.116.147 on port 500
Jan 16 09:36:51 08eb072dc5c1 pluto[575]: "l2tp-psk"[3] 223.167.116.147 #3: STATE_MAIN_R1: sent MR1, expecting MI2
Jan 16 09:36:52 08eb072dc5c1 pluto[575]: "l2tp-psk"[3] 223.167.116.147 #3: STATE_MAIN_R2: sent MR2, expecting MI3
Jan 16 09:36:52 08eb072dc5c1 pluto[575]: "l2tp-psk"[3] 223.167.116.147 #3: Peer ID is ID_IPV4_ADDR: '192.168.88.108'
Jan 16 09:36:52 08eb072dc5c1 pluto[575]: "l2tp-psk"[3] 223.167.116.147 #3: switched from "l2tp-psk"[3] 223.167.116.147 to "l2tp-psk"
Jan 16 09:36:52 08eb072dc5c1 pluto[575]: "l2tp-psk"[4] 223.167.116.147 #3: deleting connection "l2tp-psk"[3] 223.167.116.147 instance with peer 223.167.116.147 {isakmp=#0/ipsec=#0}
Jan 16 09:36:52 08eb072dc5c1 pluto[575]: "l2tp-psk"[4] 223.167.116.147 #3: Peer ID is ID_IPV4_ADDR: '192.168.88.108'
Jan 16 09:36:52 08eb072dc5c1 pluto[575]: "l2tp-psk"[4] 223.167.116.147 #3: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=3DES_CBC_192 integ=HMAC_MD5 group=MODP1024}
Jan 16 09:36:52 08eb072dc5c1 pluto[575]: "l2tp-psk"[4] 223.167.116.147 #3: the peer proposed: 47.74.33.13/32:17/1701 -> 192.168.88.108/32:17/0
Jan 16 09:36:52 08eb072dc5c1 pluto[575]: "l2tp-psk"[4] 223.167.116.147 #3: NAT-Traversal: received 2 NAT-OA. Using first; ignoring others
Jan 16 09:36:52 08eb072dc5c1 pluto[575]: "l2tp-psk"[4] 223.167.116.147 #4: responding to Quick Mode proposal {msgid:35ac0539}
Jan 16 09:36:52 08eb072dc5c1 pluto[575]: "l2tp-psk"[4] 223.167.116.147 #4:     us: 172.17.0.2[47.74.33.13]:17/1701
Jan 16 09:36:52 08eb072dc5c1 pluto[575]: "l2tp-psk"[4] 223.167.116.147 #4:   them: 223.167.116.147[192.168.88.108]:17/1701
Jan 16 09:36:52 08eb072dc5c1 pluto[575]: "l2tp-psk"[4] 223.167.116.147 #4: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 transport mode {ESP/NAT=>0xcba2a1de <0x212e996b xfrm=3DES_CBC-HMAC_SHA1_96 NATOA=192.168.88.108 NATD=223.167.116.147:4500 DPD=active}
Jan 16 09:36:52 08eb072dc5c1 pluto[575]: "l2tp-psk"[4] 223.167.116.147 #4: STATE_QUICK_R1: retransmission; will wait 0.5 seconds for response
Jan 16 09:36:53 08eb072dc5c1 pluto[575]: "l2tp-psk"[4] 223.167.116.147 #4: STATE_QUICK_R2: IPsec SA established transport mode {ESP/NAT=>0xcba2a1de <0x212e996b xfrm=3DES_CBC-HMAC_SHA1_96 NATOA=192.168.88.108 NATD=223.167.116.147:4500 DPD=active}

－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－

grep xl2tpd /var/log/syslog　没有任何结果

确认阿里云和服务器上　1701/tcp, 500/udp, 4500/udp 都已开放

麻烦告知如何调查问题原因以及解决方案，谢谢！

**Comment by hwdsl2** [comment]
@xieyanfu 你好！从你的日志来看，IPsec连接可以成功建立。如果没有L2TP日志，可能是L2TP的问题。再次尝试连接，然后查看一下L2TP日志。另外确保使用最新版本的 VPN 脚本。看起来你修改了配置并加入了 3DES 算法。

**Comment by javanoclaw** [comment]
同款路由器，也连接不上

**Comment by VEMTK** [comment]
解决了吗？
