### ISSUE TITLE
xl2tpd[1]: setsockopt recvref[30]: Protocol not available

### ISSUE THREAD

**Issue by kanlidy** [hwdsl2/setup-ipsec-vpn#72]
Follow your instruction, run `docker run` command, I got this:

    IPsec VPN server is now ready for use!

    Connect to your new VPN with these details:

    Server IP: xxx.xxx.xxx.xxx
    IPsec PSK: ********
    Users credentials :
    Login : ******** Password : ********
    Login : ******** Password : ********

    Write these down. You'll need them to connect!

    Setup VPN Clients: https://git.io/vpnclients

    ================================================

    Redirecting to: /etc/init.d/ipsec start
    Starting pluto IKE daemon for IPsec: .
    xl2tpd[1]: setsockopt recvref[30]: Protocol not available
    xl2tpd[1]: This binary does not support kernel L2TP.
    xl2tpd[1]: xl2tpd version xl2tpd-1.3.6 started on 2ccff18b3002 PID:1
    xl2tpd[1]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
    xl2tpd[1]: Forked by Scott Balmos and David Stipp, (C) 2001
    xl2tpd[1]: Inherited by Jeff McAdams, (C) 2002
    xl2tpd[1]: Forked again by Xelerance (www.xelerance.com) (C) 2006
    xl2tpd[1]: Listening on IP address 0.0.0.0, port 1701

Docker status:

    000 using kernel interface: netkey
    000 interface lo/lo ::1@500
    000 interface lo/lo 127.0.0.1@4500
    000 interface lo/lo 127.0.0.1@500
    000 interface eth0/eth0 172.17.0.3@4500
    000 interface eth0/eth0 172.17.0.3@500
    000  
    000  
    000 fips mode=disabled;
    000 SElinux=disabled
    000  
    000 config setup options:
    000  
    000 configdir=/etc, configfile=/etc/ipsec.conf, secrets=/etc/ipsec.secrets, ipsecdir=/etc/ipsec.d, dumpdir=/var/run/pluto, statsbin=unset
    000 sbindir=/usr/local/sbin, libexecdir=/usr/local/libexec/ipsec
    000 pluto_version=3.17, pluto_vendorid=OE-Libreswan-3.17
    000 nhelpers=0, uniqueids=no, perpeerlog=no, shuntlifetime=900s, xfrmlifetime=300s
    000 ddos-cookies-treshold=50000, ddos-max-halfopen=25000, ddos-mode=auto
    000 ikeport=500, strictcrlpolicy=no, crlcheckinterval=0, listen=<any>, nflog-all=0
    000 secctx-attr-type=<unsupported>
    000 myid = (none)
    000 debug none
    000  
    000 nat-traversal=yes, keep-alive=20, nat-ikeport=4500
    000 virtual-private (%priv):
    000 - allowed subnets: 10.0.0.0/8, 192.168.0.0/16, 172.16.0.0/12
    000 - excluded subnet: 192.168.42.0/23
    000  
    000 ESP algorithms supported:
    000  
    000 algorithm ESP encrypt: id=3, name=ESP_3DES, ivlen=8, keysizemin=192, keysizemax=192
    000 algorithm ESP encrypt: id=6, name=ESP_CAST, ivlen=8, keysizemin=128, keysizemax=128
    000 algorithm ESP encrypt: id=11, name=ESP_NULL, ivlen=0, keysizemin=0, keysizemax=0
    000 algorithm ESP encrypt: id=12, name=ESP_AES, ivlen=8, keysizemin=128, keysizemax=256
    000 algorithm ESP encrypt: id=13, name=ESP_AES_CTR, ivlen=8, keysizemin=128, keysizemax=256
    000 algorithm ESP encrypt: id=14, name=ESP_AES_CCM_A, ivlen=8, keysizemin=128, keysizemax=256
    000 algorithm ESP encrypt: id=15, name=ESP_AES_CCM_B, ivlen=8, keysizemin=128, keysizemax=256
    000 algorithm ESP encrypt: id=16, name=ESP_AES_CCM_C, ivlen=8, keysizemin=128, keysizemax=256
    000 algorithm ESP encrypt: id=18, name=ESP_AES_GCM_A, ivlen=8, keysizemin=128, keysizemax=256
    000 algorithm ESP encrypt: id=19, name=ESP_AES_GCM_B, ivlen=12, keysizemin=128, keysizemax=256
    000 algorithm ESP encrypt: id=20, name=ESP_AES_GCM_C, ivlen=16, keysizemin=128, keysizemax=256
    000 algorithm ESP encrypt: id=22, name=ESP_CAMELLIA, ivlen=8, keysizemin=128, keysizemax=256
    000 algorithm ESP encrypt: id=252, name=ESP_SERPENT, ivlen=8, keysizemin=128, keysizemax=256
    000 algorithm ESP encrypt: id=253, name=ESP_TWOFISH, ivlen=8, keysizemin=128, keysizemax=256
    000 algorithm AH/ESP auth: id=1, name=AUTH_ALGORITHM_HMAC_MD5, keysizemin=128, keysizemax=128
    000 algorithm AH/ESP auth: id=2, name=AUTH_ALGORITHM_HMAC_SHA1, keysizemin=160, keysizemax=160
    000 algorithm AH/ESP auth: id=5, name=AUTH_ALGORITHM_HMAC_SHA2_256, keysizemin=256, keysizemax=256
    000 algorithm AH/ESP auth: id=6, name=AUTH_ALGORITHM_HMAC_SHA2_384, keysizemin=384, keysizemax=384
    000 algorithm AH/ESP auth: id=7, name=AUTH_ALGORITHM_HMAC_SHA2_512, keysizemin=512, keysizemax=512
    000 algorithm AH/ESP auth: id=8, name=AUTH_ALGORITHM_HMAC_RIPEMD, keysizemin=160, keysizemax=160
    000 algorithm AH/ESP auth: id=9, name=AUTH_ALGORITHM_AES_XCBC, keysizemin=128, keysizemax=128
    000 algorithm AH/ESP auth: id=251, name=AUTH_ALGORITHM_NULL_KAME, keysizemin=0, keysizemax=0
    000  
    000 IKE algorithms supported:
    000  
    000 algorithm IKE encrypt: v1id=0, v1name=0??, v2id=16, v2name=AES_CCM_C, blocksize=16, keydeflen=128
    000 algorithm IKE encrypt: v1id=0, v1name=0??, v2id=15, v2name=AES_CCM_B, blocksize=16, keydeflen=128
    000 algorithm IKE encrypt: v1id=0, v1name=0??, v2id=14, v2name=AES_CCM_A, blocksize=16, keydeflen=128
    000 algorithm IKE encrypt: v1id=5, v1name=OAKLEY_3DES_CBC, v2id=3, v2name=3DES, blocksize=8, keydeflen=192
    000 algorithm IKE encrypt: v1id=24, v1name=OAKLEY_CAMELLIA_CTR, v2id=24, v2name=CAMELLIA_CTR, blocksize=16, keydeflen=128
    000 algorithm IKE encrypt: v1id=8, v1name=OAKLEY_CAMELLIA_CBC, v2id=23, v2name=CAMELLIA_CBC, blocksize=16, keydeflen=128
    000 algorithm IKE encrypt: v1id=20, v1name=OAKLEY_AES_GCM_C, v2id=20, v2name=AES_GCM_C, blocksize=16, keydeflen=128
    000 algorithm IKE encrypt: v1id=19, v1name=OAKLEY_AES_GCM_B, v2id=19, v2name=AES_GCM_B, blocksize=16, keydeflen=128
    000 algorithm IKE encrypt: v1id=18, v1name=OAKLEY_AES_GCM_A, v2id=18, v2name=AES_GCM_A, blocksize=16, keydeflen=128
    000 algorithm IKE encrypt: v1id=13, v1name=OAKLEY_AES_CTR, v2id=13, v2name=AES_CTR, blocksize=16, keydeflen=128
    000 algorithm IKE encrypt: v1id=7, v1name=OAKLEY_AES_CBC, v2id=12, v2name=AES_CBC, blocksize=16, keydeflen=128
    000 algorithm IKE encrypt: v1id=65004, v1name=OAKLEY_SERPENT_CBC, v2id=65004, v2name=SERPENT_CBC, blocksize=16, keydeflen=128
    000 algorithm IKE encrypt: v1id=65005, v1name=OAKLEY_TWOFISH_CBC, v2id=65005, v2name=TWOFISH_CBC, blocksize=16, keydeflen=128
    000 algorithm IKE encrypt: v1id=65289, v1name=OAKLEY_TWOFISH_CBC_SSH, v2id=65289, v2name=TWOFISH_CBC_SSH, blocksize=16, keydeflen=128
    000 algorithm IKE hash: id=1, name=OAKLEY_MD5, hashlen=16
    000 algorithm IKE hash: id=2, name=OAKLEY_SHA1, hashlen=20
    000 algorithm IKE hash: id=4, name=OAKLEY_SHA2_256, hashlen=32
    000 algorithm IKE hash: id=5, name=OAKLEY_SHA2_384, hashlen=48
    000 algorithm IKE hash: id=6, name=OAKLEY_SHA2_512, hashlen=64
    000 algorithm IKE hash: id=9, name=DISABLED-OAKLEY_AES_XCBC, hashlen=16
    000 algorithm IKE dh group: id=2, name=OAKLEY_GROUP_MODP1024, bits=1024
    000 algorithm IKE dh group: id=5, name=OAKLEY_GROUP_MODP1536, bits=1536
    000 algorithm IKE dh group: id=14, name=OAKLEY_GROUP_MODP2048, bits=2048
    000 algorithm IKE dh group: id=15, name=OAKLEY_GROUP_MODP3072, bits=3072
    000 algorithm IKE dh group: id=16, name=OAKLEY_GROUP_MODP4096, bits=4096
    000 algorithm IKE dh group: id=17, name=OAKLEY_GROUP_MODP6144, bits=6144
    000 algorithm IKE dh group: id=18, name=OAKLEY_GROUP_MODP8192, bits=8192
    000 algorithm IKE dh group: id=22, name=OAKLEY_GROUP_DH22, bits=1024
    000 algorithm IKE dh group: id=23, name=OAKLEY_GROUP_DH23, bits=2048
    000 algorithm IKE dh group: id=24, name=OAKLEY_GROUP_DH24, bits=2048
    000  
    000 stats db_ops: {curr_cnt, total_cnt, maxsz} :context={0,0,0} trans={0,0,0} attrs={0,0,0} 
    000  
    000 Connection list:
    000  
    000 "l2tp-psk": 172.17.0.3/32===172.17.0.3<172.17.0.3>[202.103.41.110]:17/1701---172.17.0.1...%any:17/%any; unrouted; eroute owner: #0
    000 "l2tp-psk":     oriented; my_ip=unset; their_ip=unset
    000 "l2tp-psk":   xauth us:none, xauth them:none,  my_username=[any]; their_username=[any]
    000 "l2tp-psk":   modecfg info: us:none, them:none, modecfg policy:push, dns1:unset, dns2:unset, domain:unset, banner:unset;
    000 "l2tp-psk":   labeled_ipsec:no;
    000 "l2tp-psk":   policy_label:unset;
    000 "l2tp-psk":   ike_life: 3600s; ipsec_life: 28800s; replay_window: 32; rekey_margin: 540s; rekey_fuzz: 100%; keyingtries: 3;
    000 "l2tp-psk":   retransmit-interval: 500ms; retransmit-timeout: 60s;
    000 "l2tp-psk":   sha2_truncbug:no; initial_contact:no; cisco_unity:no; fake_strongswan:no; send_vendorid:no;
    000 "l2tp-psk":   policy: PSK+ENCRYPT+DONT_REKEY+IKEV1_ALLOW+IKEV2_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO;
    000 "l2tp-psk":   conn_prio: 32,32; interface: eth0; metric: 0; mtu: unset; sa_prio:auto; nflog-group: unset; mark: unset;
    000 "l2tp-psk":   dpd: action:clear; delay:15; timeout:30; nat-t: force_encaps:yes; nat_keepalive:yes; ikev1_natt:both
    000 "l2tp-psk":   newest ISAKMP SA: #0; newest IPsec SA: #0;
    000 "l2tp-psk":   IKE algorithms wanted: 3DES_CBC(5)_000-SHA1(2)_000-MODP2048(14), 3DES_CBC(5)_000-SHA1(2)_000-MODP1536(5), 3DES_CBC(5)_000-SHA1(2)_000-MODP1024(2), AES_CBC(7)_000-SHA1(2)_000-MODP2048(14), AES_CBC(7)_000-SHA1(2)_000-MODP1536(5), AES_CBC(7)_000-SHA1(2)_000-MODP1024(2)
    000 "l2tp-psk":   IKE algorithms found:  3DES_CBC(5)_192-SHA1(2)_160-MODP2048(14), 3DES_CBC(5)_192-SHA1(2)_160-MODP1536(5), 3DES_CBC(5)_192-SHA1(2)_160-MODP1024(2), AES_CBC(7)_128-SHA1(2)_160-MODP2048(14), AES_CBC(7)_128-SHA1(2)_160-MODP1536(5), AES_CBC(7)_128-SHA1(2)_160-MODP1024(2)
    000 "l2tp-psk":   ESP algorithms wanted: 3DES(3)_000-SHA1(2)_000, AES(12)_000-SHA1(2)_000
    000 "l2tp-psk":   ESP algorithms loaded: 3DES(3)_000-SHA1(2)_000, AES(12)_000-SHA1(2)_000
    000 "xauth-psk": 0.0.0.0/0===172.17.0.3<172.17.0.3>[202.103.41.110,MS+XS+S=C]...%any[+MC+XC+S=C]; unrouted; eroute owner: #0
    000 "xauth-psk":     oriented; my_ip=unset; their_ip=unset
    000 "xauth-psk":   xauth us:server, xauth them:client, xauthby:file; my_username=[any]; their_username=[any]
    000 "xauth-psk":   modecfg info: us:server, them:client, modecfg policy:pull, dns1:8.8.8.8, dns2:8.8.4.4, domain:unset, banner:unset;
    000 "xauth-psk":   labeled_ipsec:no;
    000 "xauth-psk":   policy_label:unset;
    000 "xauth-psk":   ike_life: 3600s; ipsec_life: 28800s; replay_window: 32; rekey_margin: 540s; rekey_fuzz: 100%; keyingtries: 3;
    000 "xauth-psk":   retransmit-interval: 500ms; retransmit-timeout: 60s;
    000 "xauth-psk":   sha2_truncbug:no; initial_contact:no; cisco_unity:yes; fake_strongswan:no; send_vendorid:no;
    000 "xauth-psk":   policy: PSK+ENCRYPT+TUNNEL+DONT_REKEY+XAUTH+MODECFG_PULL+IKEV1_ALLOW+SAREF_TRACK+IKE_FRAG_ALLOW+ESN_NO;
    000 "xauth-psk":   conn_prio: 0,32; interface: eth0; metric: 0; mtu: unset; sa_prio:auto; nflog-group: unset; mark: unset;
    000 "xauth-psk":   dpd: action:clear; delay:15; timeout:30; nat-t: force_encaps:yes; nat_keepalive:yes; ikev1_natt:both
    000 "xauth-psk":   newest ISAKMP SA: #0; newest IPsec SA: #0;
    000 "xauth-psk":   IKE algorithms wanted: 3DES_CBC(5)_000-SHA1(2)_000-MODP2048(14), 3DES_CBC(5)_000-SHA1(2)_000-MODP1536(5), 3DES_CBC(5)_000-SHA1(2)_000-MODP1024(2), AES_CBC(7)_000-SHA1(2)_000-MODP2048(14), AES_CBC(7)_000-SHA1(2)_000-MODP1536(5), AES_CBC(7)_000-SHA1(2)_000-MODP1024(2)
    000 "xauth-psk":   IKE algorithms found:  3DES_CBC(5)_192-SHA1(2)_160-MODP2048(14), 3DES_CBC(5)_192-SHA1(2)_160-MODP1536(5), 3DES_CBC(5)_192-SHA1(2)_160-MODP1024(2), AES_CBC(7)_128-SHA1(2)_160-MODP2048(14), AES_CBC(7)_128-SHA1(2)_160-MODP1536(5), AES_CBC(7)_128-SHA1(2)_160-MODP1024(2)
    000 "xauth-psk":   ESP algorithms wanted: 3DES(3)_000-SHA1(2)_000, AES(12)_000-SHA1(2)_000
    000 "xauth-psk":   ESP algorithms loaded: 3DES(3)_000-SHA1(2)_000, AES(12)_000-SHA1(2)_000
    000  
    000 Total IPsec connections: loaded 2, active 0
    000  
    000 State Information: DDoS cookies not required, Accepting new IKE connections
    000 IKE SAs: total(0), half-open(0), open(0), authenticated(0), anonymous(0)
    000 IPsec SAs: total(0), authenticated(0), anonymous(0)
    000  
    000 Bare Shunt list:
    000  

I try to solve this problem by install `apt install strongswan-starter` and this is my ipsec version:

    root@ubuntu:~# ipsec --version
    Linux strongSwan U5.3.5/K4.4.0-21-generic
    Institute for Internet Technologies and Applications
    University of Applied Sciences Rapperswil, Switzerland
    See 'ipsec --copyright' for copyright information.

Docker version:

    root@ubuntu:~# docker --version
    Docker version 1.12.1, build 23cf638

Ubuntu version:

    root@ubuntu:~# uname -a
    Linux ubuntu 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hwdsl2** [comment]
@kanlidy Hello! This message: `xl2tpd[1]: setsockopt recvref[30]: Protocol not available` is normal and there is nothing to worry about. The VPN should work fine and no other step is required.

I think you accidentally posted your VPN credentials. I have edited your comment to remove them, but others may have seen it. Please consider changing your PSK and Password.

**Comment by kanlidy** [comment]
@hwdsl2  Thank you so much.

But I still can not connnect to my VPN server.

Got: 无法建立计算机与vpn服务器之间的网络连接 因为远程服务器未响应

Just follow your instructions.

**Comment by kanlidy** [comment]
I try to open port 1701, because I see the logs listen to 1701, tcpdump udp port 1701 got nothing.

**Comment by hwdsl2** [comment]
@kanlidy There is no need to open port 1701. For the error you encountered please see [1] for a solution.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting

**Comment by kanlidy** [comment]
@hwdsl2   Error 809 does not show, but Error 789 is show, tells : l2tp连接尝试失败 因为安全层在初始化, my system is window 10.

**Comment by hwdsl2** [comment]
@kanlidy Please try the steps in [1] and [2].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/issues/46#issuecomment-238094752
[2] https://github.com/hwdsl2/setup-ipsec-vpn/issues/28#issuecomment-222742034

**Comment by kanlidy** [comment]
follow your instructions, I try remove `ProhibitIpSec` from my regedit, and reboot. Error 789 still exit. how to debug it? I try to tcpdump my port, this is nothing shows up. 

Here is my env file: 

    VPN_PUBLIC_IP=xxx.xxx.xxx.xxx
    VPN_IPSEC_PSK=6Kyy4oOOCK2GxPQp
    VPN_USER=liwei
    VPN_PASSWORD=12345678aaa

Here is my iptables -L:

    root@ubuntu:~# iptables -L
    Chain INPUT (policy ACCEPT)
    target     prot opt source               destination         
    ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
    ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:openvpn
    ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:tproxy
    ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:8082
    ACCEPT     icmp --  anywhere             anywhere            
    ACCEPT     all  --  anywhere             anywhere            

    Chain FORWARD (policy ACCEPT)
    target     prot opt source               destination         
    DOCKER-ISOLATION  all  --  anywhere             anywhere            
    DOCKER     all  --  anywhere             anywhere            
    ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
    ACCEPT     all  --  anywhere             anywhere            
    ACCEPT     all  --  anywhere             anywhere            
    DOCKER     all  --  anywhere             anywhere            
    ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
    ACCEPT     all  --  anywhere             anywhere            
    ACCEPT     all  --  anywhere             anywhere            
    ACCEPT     all  --  anywhere             anywhere            
    ACCEPT     all  --  anywhere             anywhere            

    Chain OUTPUT (policy ACCEPT)
    target     prot opt source               destination         
    ACCEPT     icmp --  anywhere             anywhere            
    ACCEPT     all  --  anywhere             anywhere            

    Chain DOCKER (2 references)
    target     prot opt source               destination         
    ACCEPT     udp  --  anywhere             172.17.0.2           udp dpt:openvpn
    ACCEPT     tcp  --  anywhere             172.18.0.4           tcp dpt:http
    ACCEPT     tcp  --  anywhere             172.18.0.4           tcp dpt:ssh
    ACCEPT     tcp  --  anywhere             172.17.0.4           tcp dpt:1723
    ACCEPT     udp  --  anywhere             172.17.0.3           udp dpt:ipsec-nat-t
    ACCEPT     udp  --  anywhere             172.17.0.3           udp dpt:isakmp

    Chain DOCKER-ISOLATION (1 references)
    target     prot opt source               destination         
    DROP       all  --  anywhere             anywhere            
    DROP       all  --  anywhere             anywhere            
    RETURN     all  --  anywhere             anywhere  


I try to let the two pc in one network, just local, set server_ip=192.168.1.***, error exits.

**Comment by hwdsl2** [comment]
@kanlidy Error 789 could also be caused by a mismatch of IPsec PSK. Please carefully follow the steps in [1] to recreate the VPN connection on the Windows computer.

Also I noticed that you are not using the latest version of the Docker image. Please run `docker pull hwdsl2/ipsec-vpn-server` to get the latest image, then delete and recreate the container.

[1] https://git.io/vpnclients

**Comment by kanlidy** [comment]
@hwdsl2 Use your latest images, I connected fine, it works. 

Here's my problem:

1. Is it possible to change port from 500,4500 to other port? Like: xxx.xxx.com:14005,xxx.xxx.com:14006

2. How to add more people to my services? As you mentioned in [https://github.com/hwdsl2/docker-ipsec-vpn-server/issues/5](https://github.com/hwdsl2/docker-ipsec-vpn-server/issues/5), is there any convenient way to add users in vpn.env file, or command line?

**Comment by kanlidy** [comment]
I think maybe you can use `-v` tag to let `/etc/ipsec.secrets` and  `/etc/ppp/chap-secrets` to the host fold, like `docker run --name ipsec-vpn-server --env-file /home/liwei/openvpn/vpn.env -p 500:500/udp -p 4500:4500/udp -v /lib/modules:/lib/modules:ro -v /etc/vpn/ipsec.secrets:/etc/ipsec.secrets -v  /etc/vpn/chap-secrets:/etc/ppp/chap-secrets -d --privileged --restart=always hwdsl2/ipsec-vpn-server`

**Comment by hwdsl2** [comment]
@kanlidy For (2) you may want to try Francois Cojean's Docker image [1] which extends my work to support multiple users. The method you suggested might not work because the `run.sh` script will overwrite those config files on container startup.

For (3), if I understand your question correctly, you have set up an IPsec VPN server on your Test PC, and need to forward ports on your router in order for VPN clients to connect to the VPN server on your Test PC. Is that correct? If so, you need to port forward UDP ports 500 AND 4500 on your router to point to your Test PC.

[1] https://hub.docker.com/r/fcojean/l2tp-ipsec-vpn-server/
