### ISSUE TITLE
树莓派自启动

### ISSUE THREAD

**Issue by yuangezhizao** [hwdsl2/setup-ipsec-vpn#721]
冒昧打扰，在树莓派安装完成后可以正常连接，但是重启之后连接不能……

想问下需要自启动哪个进程？例如`systemctl enable xl2tpd`、`systemctl enable ipsec`这样？

**Comment by hwdsl2** [comment]
@yuangezhizao 你好！重启后你可以手动运行：
```
sudo service ipsec restart
sudo service xl2tpd restart
```

脚本已经配置重启后自启动以上进程。在树莓派上的问题可能是每次启动后无线连接建立需要较长时间。你可以尝试编辑 /etc/rc.local 并将 `sleep 15` 替换为更长的时间，比如 `sleep 30`。

**Comment by yuangezhizao** [comment]
Thanks！
