### ISSUE TITLE
How to use custom DNS provider that runs on non standard port?

### ISSUE THREAD

**Issue by ibnuh** [hwdsl2/setup-ipsec-vpn#722]
I run adguardhome on non standard port e.g 5858 instead of 53.

I've tried to edit the `/etc/ppp/options.xl2tpd` and `/etc/ipsec.conf` dns section to e.g `172.31.115.123:5858` but resulting in unable to connect, please help.

Thanks in advance,
Ibnuh.

**Comment by letoams** [comment]
On Thu, 30 Jan 2020, Muhammad Ibnuh wrote:

> I run adguardhome on non standard port e.g 5858 instead of 53.
> 
> I've tried to edit the /etc/ppp/options.xl2tpd and /etc/ipsec.conf dns section to e.g 172.31.115.123:5858 but resulting in unable to connect, please help.

The protocol does not allow for that.

You should hand out a server that is on the regular port, who itself is
using a forwarder that can be on a non-standard port.

Paul

**Comment by ibnuh** [comment]
Thanks Paul, that clear things up.
