### ISSUE TITLE
IKEv2 error Windows 10 - 2

### ISSUE THREAD

**Issue by anartikov** [hwdsl2/setup-ipsec-vpn#724]
For some reason, my past error in the status is Closed .. Although the problem is not solved.
Advice, restarting the service naturally did not help.

Configured everything as you indicated.
I'm trying to connect - error.
"Cannot connect to vpn. Group Policy mapping error"
I am ready to provide you with any information. Help solve this problem.

NartServ2 pluto[1804]: packet from 109.252.113.91:2434: initial parent SA message received on 116.203.181.10:500 but no suitable connection found with IKEv2 policy
NartServ2 pluto[1804]: packet from 109.252.113.91:2434: responding to IKE_SA_INIT (34) message (Message ID 0) from 109.252.113.91:2434 with unencrypted notification NO_PROPOSAL_CHOSEN

**Comment by hwdsl2** [comment]
@anartikov Please try the latest version of the VPN setup scripts. Libreswan has been updated to version 3.31, which contains some fixes for IKEv2. Use the latest VPN setup scripts [1] or upgrade scripts [2] to install this version.

[1] https://github.com/hwdsl2/setup-ipsec-vpn#installation
[2] https://github.com/hwdsl2/setup-ipsec-vpn#upgrade-libreswan
