### ISSUE TITLE
How can i use Proxy and Client nummber?

### ISSUE THREAD

**Issue by karma1234567** [hwdsl2/setup-ipsec-vpn#726]
Hi,

first thank you for this nice Project.
1. I have a proxy on one other server and I like to use it, also let all the clients of VPN get their connection through a proxy server.

2. How can I know how many clients are connected?

Best Regards
Karma

**Comment by letoams** [comment]
1) Using a proxy these days has very little use as almost all web traffic is https. You will get 1 to 5% hit rate for http at best.

2) ipsec trafficstatus

**Comment by karma1234567** [comment]
Thank you very much mr Paul, i'm following your channel now. 
^_^

Best Regards

**Comment by hwdsl2** [comment]
Thanks @letoams!
