### ISSUE TITLE
how to configure the client to use static ip address?

### ISSUE THREAD

**Issue by victorchaois666** [hwdsl2/setup-ipsec-vpn#729]
how to configure the client use static ip address?For example,configure the first client use the ip address of 192.168.42.100, instead of the default 192.168.42.10.
thanks

**Comment by daancart2quote** [comment]
You can set an IP per user in the file `/etc/ppp/chap-secrets` instead of the *.

If you would like to change the IP range, edit `/etc/xl2tpd/xl2tpd.conf`.

**Comment by hwdsl2** [comment]
@victorchaois666 Please see #508.
