### ISSUE TITLE
Bridging with openvpn

### ISSUE THREAD

**Issue by scj643** [hwdsl2/setup-ipsec-vpn#73]
I want to use this so I can bridge someone that is connecting to the ipsec vpn to have access to clients on an openvpn connection. Also the clients on the l2tp side should have internet access as well.

**Comment by hwdsl2** [comment]
@scj643 Yes it is possible to achieve what you described. First, please note the following:

When connecting via IPsec/L2TP, the VPN server has IP 192.168.42.1 within the VPN subnet, and VPN clients are assigned IPs from 192.168.42.10 up to 192.168.42.250.

You can build a server with both OpenVPN and IPsec VPN by first running Nyr's openvpn-install script [1], then run the vpnsetup.sh from this repo. The default configuration in Nyr's script will assign IPs from the 10.8.0.0/24 subnet to your OpenVPN clients. Now we only need to add the required IPTables rules to enable access from IPsec VPN clients to OpenVPN clients:

```
iptables -I FORWARD -i ppp+ -o tun+ -j ACCEPT
iptables -I FORWARD -i tun+ -o ppp+ -j ACCEPT
```

To persist across reboots, add the above IPTables rules to "/etc/iptables.rules".

[1] https://github.com/Nyr/openvpn-install
