### ISSUE TITLE
您好，ipsec可以连接，但是无法联网

### ISSUE THREAD

**Issue by liasica** [hwdsl2/setup-ipsec-vpn#730]
用的docker，前几天好好的，从昨天还是前天开始就不行了。

`docker exec -it vpn grep pluto /var/log/auth.log`日志：

Feb 20 04:22:35 63aab45daf3c pluto[274]: shutting down
Feb 20 04:22:35 63aab45daf3c pluto[274]: forgetting secrets
Feb 20 04:22:35 63aab45daf3c pluto[274]: shutting down interface lo/lo 127.0.0.1:4500
Feb 20 04:22:35 63aab45daf3c pluto[274]: shutting down interface lo/lo 127.0.0.1:500
Feb 20 04:22:35 63aab45daf3c pluto[274]: shutting down interface eth0/eth0 172.17.0.2:4500
Feb 20 04:22:35 63aab45daf3c pluto[274]: shutting down interface eth0/eth0 172.17.0.2:500
Feb 20 04:22:35 63aab45daf3c ipsec__plutorun: pluto killed by SIGTERM, terminating without restart
Feb 20 04:22:35 63aab45daf3c ipsec__plutorun: Starting Pluto
Feb 20 04:22:36 63aab45daf3c pluto[1626]: NSS DB directory: sql:/etc/ipsec.d
Feb 20 04:22:36 63aab45daf3c pluto[1626]: Initializing NSS
Feb 20 04:22:36 63aab45daf3c pluto[1626]: Opening NSS database "sql:/etc/ipsec.d" read-only
Feb 20 04:22:36 63aab45daf3c pluto[1626]: NSS initialized
Feb 20 04:22:36 63aab45daf3c pluto[1626]: NSS crypto library initialized
Feb 20 04:22:36 63aab45daf3c pluto[1626]: FIPS HMAC integrity support [disabled]
Feb 20 04:22:36 63aab45daf3c pluto[1626]: libcap-ng support [enabled]
Feb 20 04:22:36 63aab45daf3c pluto[1626]: Linux audit support [disabled]
Feb 20 04:22:36 63aab45daf3c pluto[1626]: Starting Pluto (Libreswan Version 3.29 XFRM(netkey) esp-hw-offload FORK PTHREAD_SETSCHEDPRIO NSS (AVA copy) LABELED_IPSEC LIBCAP_NG XAUTH_PAM NETWORKMANAGER CURL(non-NSS)) pid:1626
Feb 20 04:22:36 63aab45daf3c pluto[1626]: core dump dir: /run/pluto
Feb 20 04:22:36 63aab45daf3c pluto[1626]: secrets file: /etc/ipsec.secrets
Feb 20 04:22:36 63aab45daf3c pluto[1626]: leak-detective disabled
Feb 20 04:22:36 63aab45daf3c pluto[1626]: NSS crypto [enabled]
Feb 20 04:22:36 63aab45daf3c pluto[1626]: XAUTH PAM support [enabled]
Feb 20 04:22:36 63aab45daf3c pluto[1626]: Initializing libevent in pthreads mode: headers: 2.0.21-stable (2001500); library: 2.0.21-stable (2001500)
Feb 20 04:22:36 63aab45daf3c pluto[1626]: NAT-Traversal support  [enabled]
Feb 20 04:22:36 63aab45daf3c pluto[1626]: Encryption algorithms:
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   AES_CCM_16              IKEv1:     ESP     IKEv2:     ESP     FIPS  {256,192,*128}  aes_ccm, aes_ccm_c
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   AES_CCM_12              IKEv1:     ESP     IKEv2:     ESP     FIPS  {256,192,*128}  aes_ccm_b
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   AES_CCM_8               IKEv1:     ESP     IKEv2:     ESP     FIPS  {256,192,*128}  aes_ccm_a
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   3DES_CBC                IKEv1: IKE ESP     IKEv2: IKE ESP     FIPS  [*192]  3des
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   CAMELLIA_CTR            IKEv1:     ESP     IKEv2:     ESP           {256,192,*128}
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   CAMELLIA_CBC            IKEv1: IKE ESP     IKEv2: IKE ESP           {256,192,*128}  camellia
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   AES_GCM_16              IKEv1:     ESP     IKEv2: IKE ESP     FIPS  {256,192,*128}  aes_gcm, aes_gcm_c
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   AES_GCM_12              IKEv1:     ESP     IKEv2: IKE ESP     FIPS  {256,192,*128}  aes_gcm_b
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   AES_GCM_8               IKEv1:     ESP     IKEv2: IKE ESP     FIPS  {256,192,*128}  aes_gcm_a
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   AES_CTR                 IKEv1: IKE ESP     IKEv2: IKE ESP     FIPS  {256,192,*128}  aesctr
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   AES_CBC                 IKEv1: IKE ESP     IKEv2: IKE ESP     FIPS  {256,192,*128}  aes
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   SERPENT_CBC             IKEv1: IKE ESP     IKEv2: IKE ESP           {256,192,*128}  serpent
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   TWOFISH_CBC             IKEv1: IKE ESP     IKEv2: IKE ESP           {256,192,*128}  twofish
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   TWOFISH_SSH             IKEv1: IKE         IKEv2: IKE ESP           {256,192,*128}  twofish_cbc_ssh
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   NULL_AUTH_AES_GMAC      IKEv1:     ESP     IKEv2:     ESP     FIPS  {256,192,*128}  aes_gmac
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   NULL                    IKEv1:     ESP     IKEv2:     ESP           []
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   CHACHA20_POLY1305       IKEv1:             IKEv2: IKE ESP           [*256]  chacha20poly1305
Feb 20 04:22:36 63aab45daf3c pluto[1626]: Hash algorithms:
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   MD5                     IKEv1: IKE         IKEv2:
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   SHA1                    IKEv1: IKE         IKEv2:             FIPS  sha
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   SHA2_256                IKEv1: IKE         IKEv2:             FIPS  sha2, sha256
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   SHA2_384                IKEv1: IKE         IKEv2:             FIPS  sha384
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   SHA2_512                IKEv1: IKE         IKEv2:             FIPS  sha512
Feb 20 04:22:36 63aab45daf3c pluto[1626]: PRF algorithms:
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   HMAC_MD5                IKEv1: IKE         IKEv2: IKE               md5
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   HMAC_SHA1               IKEv1: IKE         IKEv2: IKE         FIPS  sha, sha1
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   HMAC_SHA2_256           IKEv1: IKE         IKEv2: IKE         FIPS  sha2, sha256, sha2_256
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   HMAC_SHA2_384           IKEv1: IKE         IKEv2: IKE         FIPS  sha384, sha2_384
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   HMAC_SHA2_512           IKEv1: IKE         IKEv2: IKE         FIPS  sha512, sha2_512
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   AES_XCBC                IKEv1:             IKEv2: IKE               aes128_xcbc
Feb 20 04:22:36 63aab45daf3c pluto[1626]: Integrity algorithms:
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   HMAC_MD5_96             IKEv1: IKE ESP AH  IKEv2: IKE ESP AH        md5, hmac_md5
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   HMAC_SHA1_96            IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  sha, sha1, sha1_96, hmac_sha1
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   HMAC_SHA2_512_256       IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  sha512, sha2_512, sha2_512_256, hmac_sha2_512
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   HMAC_SHA2_384_192       IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  sha384, sha2_384, sha2_384_192, hmac_sha2_384
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   HMAC_SHA2_256_128       IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  sha2, sha256, sha2_256, sha2_256_128, hmac_sha2_256
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   HMAC_SHA2_256_TRUNCBUG  IKEv1:     ESP AH  IKEv2:         AH
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   AES_XCBC_96             IKEv1:     ESP AH  IKEv2: IKE ESP AH        aes_xcbc, aes128_xcbc, aes128_xcbc_96
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   AES_CMAC_96             IKEv1:     ESP AH  IKEv2:     ESP AH  FIPS  aes_cmac
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   NONE                    IKEv1:     ESP     IKEv2: IKE ESP     FIPS  null
Feb 20 04:22:36 63aab45daf3c pluto[1626]: DH algorithms:
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   NONE                    IKEv1:             IKEv2: IKE ESP AH  FIPS  null, dh0
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   MODP1024                IKEv1: IKE ESP AH  IKEv2: IKE ESP AH        dh2
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   MODP1536                IKEv1: IKE ESP AH  IKEv2: IKE ESP AH        dh5
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   MODP2048                IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  dh14
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   MODP3072                IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  dh15
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   MODP4096                IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  dh16
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   MODP6144                IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  dh17
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   MODP8192                IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  dh18
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   DH19                    IKEv1: IKE         IKEv2: IKE ESP AH  FIPS  ecp_256, ecp256
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   DH20                    IKEv1: IKE         IKEv2: IKE ESP AH  FIPS  ecp_384, ecp384
Feb 20 04:22:36 63aab45daf3c pluto[1626]:   DH21                    IKEv1: IKE         IKEv2: IKE ESP AH  FIPS  ecp_521, ecp521
Feb 20 04:22:36 63aab45daf3c pluto[1626]: 1 CPU cores online
Feb 20 04:22:36 63aab45daf3c pluto[1626]: starting up 1 crypto helpers
Feb 20 04:22:36 63aab45daf3c pluto[1626]: started thread for crypto helper 0
Feb 20 04:22:36 63aab45daf3c pluto[1626]: Using Linux XFRM/NETKEY IPsec interface code on 4.14.129-bbrplus
Feb 20 04:22:36 63aab45daf3c pluto[1626]: selinux support is NOT enabled.
Feb 20 04:22:36 63aab45daf3c pluto[1626]: seccomp security not supported
Feb 20 04:22:36 63aab45daf3c pluto[1626]: seccomp security for crypto helper not supported
Feb 20 04:22:36 63aab45daf3c pluto[1626]: added connection description "l2tp-psk"
Feb 20 04:22:36 63aab45daf3c pluto[1626]: added connection description "xauth-psk"
Feb 20 04:22:36 63aab45daf3c pluto[1626]: listening for IKE messages
Feb 20 04:22:36 63aab45daf3c pluto[1626]: Kernel supports NIC esp-hw-offload
Feb 20 04:22:36 63aab45daf3c pluto[1626]: adding interface eth0/eth0 (esp-hw-offload=no) 172.17.0.2:500
Feb 20 04:22:36 63aab45daf3c pluto[1626]: adding interface eth0/eth0 172.17.0.2:4500
Feb 20 04:22:36 63aab45daf3c pluto[1626]: Kernel supports NIC esp-hw-offload
Feb 20 04:22:36 63aab45daf3c pluto[1626]: adding interface lo/lo (esp-hw-offload=no) 127.0.0.1:500
Feb 20 04:22:36 63aab45daf3c pluto[1626]: adding interface lo/lo 127.0.0.1:4500
Feb 20 04:22:36 63aab45daf3c pluto[1626]: loading secrets from "/etc/ipsec.secrets"
Feb 20 04:22:36 63aab45daf3c pluto[1626]: WARNING: using a weak secret (PSK)
Feb 20 04:22:46 63aab45daf3c pluto[1626]: "xauth-psk"[1] 123.118.230.148 #1: responding to Main Mode from unknown peer 123.118.230.148 on port 500
Feb 20 04:22:46 63aab45daf3c pluto[1626]: "xauth-psk"[1] 123.118.230.148 #1: WARNING: connection xauth-psk PSK length of 7 bytes is too short for sha2_256 PRF in FIPS mode (16 bytes required)
Feb 20 04:22:46 63aab45daf3c pluto[1626]: "xauth-psk"[1] 123.118.230.148 #1: STATE_MAIN_R1: sent MR1, expecting MI2
Feb 20 04:22:46 63aab45daf3c pluto[1626]: "xauth-psk"[1] 123.118.230.148 #1: STATE_MAIN_R2: sent MR2, expecting MI3
Feb 20 04:22:46 63aab45daf3c pluto[1626]: "xauth-psk"[1] 123.118.230.148 #1: ignoring informational payload IPSEC_INITIAL_CONTACT, msgid=00000000, length=28
Feb 20 04:22:46 63aab45daf3c pluto[1626]: | ISAKMP Notification Payload
Feb 20 04:22:46 63aab45daf3c pluto[1626]: |   00 00 00 1c  00 00 00 01  01 10 60 02
Feb 20 04:22:46 63aab45daf3c pluto[1626]: "xauth-psk"[1] 123.118.230.148 #1: Peer ID is ID_IPV4_ADDR: '192.168.10.239'
Feb 20 04:22:46 63aab45daf3c pluto[1626]: "xauth-psk"[1] 123.118.230.148 #1: switched from "xauth-psk"[1] 123.118.230.148 to "xauth-psk"
Feb 20 04:22:46 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #1: deleting connection "xauth-psk"[1] 123.118.230.148 instance with peer 123.118.230.148 {isakmp=#0/ipsec=#0}
Feb 20 04:22:46 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #1: Peer ID is ID_IPV4_ADDR: '192.168.10.239'
Feb 20 04:22:46 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #1: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA2_256 group=MODP2048}
Feb 20 04:22:46 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #1: XAUTH: Sending Username/Password request (MAIN_R3->XAUTH_R0)
Feb 20 04:22:46 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #1: XAUTH: password file authentication method requested to authenticate user 'magicrolan'
Feb 20 04:22:46 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #1: XAUTH: password file (/etc/ipsec.d/passwd) open.
Feb 20 04:22:46 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #1: XAUTH: success user(magicrolan:xauth-psk)
Feb 20 04:22:46 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #1: XAUTH: User magicrolan: Authentication Successful
Feb 20 04:22:46 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #1: XAUTH: xauth_inR1(STF_OK)
Feb 20 04:22:46 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #1: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA2_256 group=MODP2048}
Feb 20 04:22:46 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #1: modecfg_inR0(STF_OK)
Feb 20 04:22:46 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #1: STATE_MODE_CFG_R1: ModeCfg Set sent, expecting Ack {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA2_256 group=MODP2048}
Feb 20 04:22:46 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #1: the peer proposed: 0.0.0.0/0:0/0 -> 192.168.43.10/32:0/0
Feb 20 04:22:46 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #2: responding to Quick Mode proposal {msgid:aa543e54}
Feb 20 04:22:46 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #2:     us: 0.0.0.0/0===172.17.0.2[34.92.206.152,MS+XS+S=C]
Feb 20 04:22:46 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #2:   them: 123.118.230.148[192.168.10.239,+MC+XC+S=C]===192.168.43.10/32
Feb 20 04:22:46 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #2: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 tunnel mode {ESP/NAT=>0x0b6536aa <0xd2b547e9 xfrm=AES_CBC_256-HMAC_SHA2_256_128 NATOA=none NATD=123.118.230.148:4500 DPD=active username=magicrolan}
Feb 20 04:22:46 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #2: STATE_QUICK_R2: IPsec SA established tunnel mode {ESP/NAT=>0x0b6536aa <0xd2b547e9 xfrm=AES_CBC_256-HMAC_SHA2_256_128 NATOA=none NATD=123.118.230.148:4500 DPD=active username=magicrolan}
Feb 20 04:25:13 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #3: responding to Main Mode from unknown peer 123.118.230.148 on port 500
Feb 20 04:25:13 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #3: WARNING: connection xauth-psk PSK length of 7 bytes is too short for sha2_256 PRF in FIPS mode (16 bytes required)
Feb 20 04:25:13 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #3: STATE_MAIN_R1: sent MR1, expecting MI2
Feb 20 04:25:13 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #3: STATE_MAIN_R2: sent MR2, expecting MI3
Feb 20 04:25:13 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #3: ignoring informational payload IPSEC_INITIAL_CONTACT, msgid=00000000, length=28
Feb 20 04:25:13 63aab45daf3c pluto[1626]: | ISAKMP Notification Payload
Feb 20 04:25:13 63aab45daf3c pluto[1626]: |   00 00 00 1c  00 00 00 01  01 10 60 02
Feb 20 04:25:13 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #3: Peer ID is ID_IPV4_ADDR: '192.168.10.239'
Feb 20 04:25:13 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #3: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA2_256 group=MODP2048}
Feb 20 04:25:13 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #3: XAUTH: Sending Username/Password request (MAIN_R3->XAUTH_R0)
Feb 20 04:25:13 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #3: XAUTH: password file authentication method requested to authenticate user 'magicrolan'
Feb 20 04:25:13 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #3: XAUTH: password file (/etc/ipsec.d/passwd) open.
Feb 20 04:25:13 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #3: XAUTH: success user(magicrolan:xauth-psk)
Feb 20 04:25:13 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #3: XAUTH: User magicrolan: Authentication Successful
Feb 20 04:25:13 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #3: XAUTH: xauth_inR1(STF_OK)
Feb 20 04:25:13 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #3: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA2_256 group=MODP2048}
Feb 20 04:25:13 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #3: modecfg_inR0(STF_OK)
Feb 20 04:25:13 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #3: STATE_MODE_CFG_R1: ModeCfg Set sent, expecting Ack {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA2_256 group=MODP2048}
Feb 20 04:25:13 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #3: the peer proposed: 0.0.0.0/0:0/0 -> 192.168.43.11/32:0/0
Feb 20 04:25:13 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #4: responding to Quick Mode proposal {msgid:7770e088}
Feb 20 04:25:13 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #4:     us: 0.0.0.0/0===172.17.0.2[34.92.206.152,MS+XS+S=C]
Feb 20 04:25:13 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #4:   them: 123.118.230.148[192.168.10.239,+MC+XC+S=C]===192.168.43.11/32
Feb 20 04:25:13 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #4: keeping refhim=0 during rekey
Feb 20 04:25:13 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #4: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 tunnel mode {ESP/NAT=>0x03a80371 <0xa3e05812 xfrm=AES_CBC_256-HMAC_SHA2_256_128 NATOA=none NATD=123.118.230.148:4500 DPD=active username=magicrolan}
Feb 20 04:25:13 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #4: STATE_QUICK_R2: IPsec SA established tunnel mode {ESP/NAT=>0x03a80371 <0xa3e05812 xfrm=AES_CBC_256-HMAC_SHA2_256_128 NATOA=none NATD=123.118.230.148:4500 DPD=active username=magicrolan}
Feb 20 04:25:16 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148 #1: IKEv1 DPD action - clearing connection kind CK_INSTANCE
Feb 20 04:25:16 63aab45daf3c pluto[1626]: "xauth-psk" #4: deleting state (STATE_QUICK_R2) aged 3.003s and sending notification
Feb 20 04:25:16 63aab45daf3c pluto[1626]: "xauth-psk" #4: ESP traffic information: in=1KB out=0B XAUTHuser=magicrolan
Feb 20 04:25:16 63aab45daf3c pluto[1626]: "xauth-psk" #2: deleting state (STATE_QUICK_R2) aged 150.052s and sending notification
Feb 20 04:25:16 63aab45daf3c pluto[1626]: "xauth-psk" #2: ESP traffic information: in=31KB out=36KB XAUTHuser=magicrolan
Feb 20 04:25:16 63aab45daf3c pluto[1626]: "xauth-psk" #3: deleting state (STATE_MODE_CFG_R1) aged 3.398s and sending notification
Feb 20 04:25:16 63aab45daf3c pluto[1626]: "xauth-psk" #1: deleting state (STATE_MODE_CFG_R1) aged 150.438s and sending notification
Feb 20 04:25:16 63aab45daf3c pluto[1626]: "xauth-psk"[2] 123.118.230.148: deleting connection "xauth-psk"[2] 123.118.230.148 instance with peer 123.118.230.148 {isakmp=#0/ipsec=#0}
Feb 20 04:27:01 63aab45daf3c pluto[1626]: initiate on demand from 157.255.13.76:80 to 192.168.43.10:53045 proto=6 because: acquire

**Comment by liasica** [comment]
iptables配置

Chain INPUT (policy ACCEPT 6124 packets, 1969K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
 491K  460M DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0
 491K  460M DOCKER-ISOLATION-STAGE-1  all  --  *      *       0.0.0.0/0            0.0.0.0/0
 234K  237M ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
   71 23004 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0
 257K  223M ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
    0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 5857 packets, 2110K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain DOCKER (1 references)
 pkts bytes target     prot opt in     out     source               destination
    1   140 ACCEPT     udp  --  !docker0 docker0  0.0.0.0/0            172.17.0.2           udp dpt:4500
    1   876 ACCEPT     udp  --  !docker0 docker0  0.0.0.0/0            172.17.0.2           udp dpt:500

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination
 257K  223M DOCKER-ISOLATION-STAGE-2  all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0
 491K  460M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
 pkts bytes target     prot opt in     out     source               destination
    0     0 DROP       all  --  *      docker0  0.0.0.0/0            0.0.0.0/0
 257K  223M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain DOCKER-USER (1 references)
 pkts bytes target     prot opt in     out     source               destination
 491K  460M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0

**Comment by hwdsl2** [comment]
@liasica 你好！从你的日志来看没有发现异常。可能是你的服务器的网络的问题。
