### ISSUE TITLE
Mac OS Catalina 始终无法连接上, 低版本的OS却可以。

### ISSUE THREAD

**Issue by Aaron009** [hwdsl2/setup-ipsec-vpn#731]
问题原文链接：
https://gist.github.com/hwdsl2/9030462#gistcomment-3174087

**Comment by Aaron009** [comment]
我问了苹果客服，说要

请您尝试配置服务器以将 SHA-256 哈希的输出截断至 128 位。
截断至更少的位数可能会导致服务器丢失 VPN 客户端传输的数据。

这个配置如何改？

**Comment by xltuo** [comment]
这个需要调整VPN服务器的相关设置。最近也遇到相同的问题我在考虑是否将系统还原到上个版本。

**Comment by ciscoxll** [comment]
recommender vpn [https://shop.v2ss.bid/users/aff.php?aff=2742](https://shop.v2ss.bid/users/aff.php?aff=2742).

**Comment by hwdsl2** [comment]
如果大家有macOS Catalina 下连接错误的日志（参见 [1]）或者关于解决方案的建议，请提供。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E9%A2%9D%E5%A4%96%E7%9A%84%E6%AD%A5%E9%AA%A4

**Comment by hwdsl2** [comment]
已测试 macOS Catalina 系统，IPsec/L2TP 和 IPsec/XAuth ("Cisco IPsec") 模式下连接均正常。如果你的客户端仍然无法连接，请尝试以下步骤。

1. 确认服务器上的 `/etc/ipsec.conf` 中包含这一行 `sha2-truncbug=no`。如果是 `yes`，将它改为 `no`，保存文件并运行 `sudo service ipsec restart`。
2. 将服务器上的 Libreswan 升级到最新版本 [1]。
3. 重新创建 macOS 客户端上的 VPN 连接，参见 [2]。注意第 14 步："单击 高级 按钮，并选中 通过VPN连接发送所有通信 复选框"。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#%E5%8D%87%E7%BA%A7libreswan
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#os-x
