### ISSUE TITLE
Can't connect to server using VPN Access Manager

### ISSUE THREAD

**Issue by Maray97** [hwdsl2/setup-ipsec-vpn#732]
Hi, I'm trying to connect using PSK+XAuth method in order to set a lab to test the MITM attack.
I pulled and executed the server container on Windows 10 machine, it seems to work.
I downloaded VPN Access Manager (on the same machine) and followed the guide, but it gives me this error:
![test](https://user-images.githubusercontent.com/36514347/74922304-4a69ba00-53cf-11ea-975e-20c581cd2646.PNG)
Can anyone help me to figure out what the problem is?

**Comment by Northmelon666** [comment]
same things happen to me

**Comment by hwdsl2** [comment]
@Maray97 Hello! The Shrew Soft VPN client is old and does not support Windows 10.

**Comment by sebspion** [comment]
I know how use rhis coin
