### ISSUE TITLE
v3.30 of libreswan

### ISSUE THREAD

**Issue by sagitt** [hwdsl2/setup-ipsec-vpn#734]
Using this version the setup not work. why?

**Comment by newbielinuxuser** [comment]
I only know one of the reason was due to the upgrade script wasn't ready for v3.3 yet.

**Comment by newbielinuxuser** [comment]
@hwdsl2 any plan on updating the scripts to 3.3 ?

**Comment by hwdsl2** [comment]
Support for installing and upgrading to Libreswan 3.31 has been added.

**Comment by sagitt** [comment]
![Schermata 2020-04-12 alle 10 27 14](https://user-images.githubusercontent.com/169086/79064329-4871f800-7ca8-11ea-8468-80538d7d9411.png)


		# cat > Makefile.inc.local <<'EOF'
			# WERROR_CFLAGS =
			# USE_DNSSEC = false
			# USE_DH2 = true
			# USE_DH31 = false
			# USE_NSS_AVA_COPY = true
			# USE_NSS_IPSEC_PROFILE = false
			# USE_GLIBC_KERN_FLIP_HEADERS = true
			# USE_XFRM_INTERFACE_IFLA_HEADER = true"	
			# EOF
