### ISSUE TITLE
使用win 10 内置的VPN无法连接

### ISSUE THREAD

**Issue by zy-zero** [hwdsl2/setup-ipsec-vpn#735]
![image](https://user-images.githubusercontent.com/23359848/75088002-2dc1b380-5582-11ea-9638-c741ea13dff9.png)

报错为：L2TP连接尝试失败，因为安全层在初始化与远程计算机的协商时遇到一个处理错误

**Comment by wodeluck** [comment]
注册表导入没有？

**Comment by victorchaois666** [comment]
测试PC使用手机热点可以连接vpn，但改用wifi以后就会报楼主一样的error，两个注册表已导入

**Comment by ecoolde** [comment]
运行services.msc,找到 IPsec policy Agent, 启动，再尝试连接vpn。
it works for me.

**Comment by hwdsl2** [comment]
这个有可能是 GFW 干扰的问题。如果检查 IPsec 日志 [1]，你可能会看到 `retransmission` 之类的错误。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E9%A2%9D%E5%A4%96%E7%9A%84%E6%AD%A5%E9%AA%A4

**Comment by zy-zero** [comment]
> 注册表导入没有？

已导入
