### ISSUE TITLE
win10 1909 VPN连不上

### ISSUE THREAD

**Issue by HentaiR** [hwdsl2/setup-ipsec-vpn#736]
![图片](https://user-images.githubusercontent.com/54672936/75137727-4fa66c00-5723-11ea-84da-442baabf2885.png)
注册表已经导入，但还是不能连上，不过手机可以连上

**Comment by Aaron009** [comment]
要重启的

**Comment by hwdsl2** [comment]
@HentaiR 你好！Windows 10 版本 1909 已测试，可以正常连接。请检查你的 VPN 设置，尝试重新创建 VPN 连接 [1]。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#windows
