### ISSUE TITLE
同一局域网内同时只允许一台客户端接入vpn服务端

### ISSUE THREAD

**Issue by victorchaois666** [hwdsl2/setup-ipsec-vpn#738]
同一局域网内同时只允许一台客户端接入vpn服务端，有办法可以设置同一局域网内多客户端接入吗？

**Comment by joe-szmn** [comment]
同一个 VPN 账户可以在你的多个设备上使用。但是由于 IPsec/L2TP 的局限性，如果需要同时连接在同一个 NAT （比如家用路由器）后面的多个设备到 VPN 服务器，你必须仅使用 IPsec/XAuth 模式。

**Comment by joe-szmn** [comment]
> 同一局域网内同时只允许一台客户端接入vpn服务端，有办法可以设置同一局域网内多客户端接入吗？

同一个 VPN 账户可以在你的多个设备上使用。但是由于 IPsec/L2TP 的局限性，如果需要同时连接在同一个 NAT （比如家用路由器）后面的多个设备到 VPN 服务器，你必须仅使用 IPsec/XAuth 模式。
