### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by Ev3y** [hwdsl2/setup-ipsec-vpn#74]
As IPv6 addresses/connectivity become more prevalent will you be able to provide IPv6 support?

**Comment by hwdsl2** [comment]
@Ev3y Thanks for the suggestion. However IPv6 support is not planned at this time. An alternative that you can try is Nyr's OpenVPN script [1]. Read his notes [2] on how to enable IPv6 (requires a routable /64 on your server).

[1] https://github.com/Nyr/openvpn-install
[2] https://www.lowendtalk.com/discussion/62645/any-openvpn-auto-installer-script-that-support-ipv6
