### ISSUE TITLE
阿里云服务器安装好之后，win10与android都没能连上

### ISSUE THREAD

**Issue by albert1257** [hwdsl2/setup-ipsec-vpn#740]
阿里云服务器安装好之后，win10与android都没能连上，win10 那个routting and remote access无法启动，还需要设置别的内容吗？udp端口500 4500已开放。

**Comment by liujiusheng** [comment]
> 阿里云服务器安装好之后，win10与android都没能连上，win10 那个routting and remote access无法启动，还需要设置别的内容吗？udp端口500 4500已开放。

大兄弟你搞定没？我装了也连不上

**Comment by dullmancc** [comment]
我不用wifi 可以连接，但是用了wifi就连接不上，电脑也是，用的那个vpn access manager就可以连接。我猜是nat的问题，但是一直没解决，大佬弄好了吗

**Comment by liujiusheng** [comment]
> 我不用wifi 可以连接，但是用了wifi就连接不上，电脑也是，用的那个vpn access manager就可以连接。我猜是nat的问题，但是一直没解决，大佬弄好了吗

我好像多等一会儿，多试几下之后可以了。

**Comment by hwdsl2** [comment]
阿里云服务器端口设置请参见 #433。另外 Windows 用户用内置客户端连接的话，可能需要更改注册表 [1]。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#windows-%E9%94%99%E8%AF%AF-809
