### ISSUE TITLE
Multiple user access

### ISSUE THREAD

**Issue by asemchenko** [hwdsl2/setup-ipsec-vpn#744]
Is it possible to create multiple users(with their own credentials) so that a few connections is possible at the same time? I have not founded any information about this on READMEs.

**Comment by letoams** [comment]
On Mon, 9 Mar 2020, Andrii Semchenko wrote:

> Is it possible to create multiple users(with their own credentials) so that a few connections is possible at the same time? I
> have not founded any information about this on READMEs.

For ikev2 connections you can enable pam-authorize, and then use a pam
module like pam_curl to fire requests to your REST server and do
whatever you want to allow/disallow the client.

For ikev1 connections, there is no such facility though. But if you
use l2tp/ipsec with ikev1, I guess you can likely hook into pppd
with some options to do something similar.

Paul

**Comment by hwdsl2** [comment]
@asemchenko Please see: https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users.md
