### ISSUE TITLE
PRIVATE_IP & PUBLIC_IP are same !

### ISSUE THREAD

**Issue by shadowy70** [hwdsl2/setup-ipsec-vpn#75]
Hey I just installed your script on my server  and after connecting i hadnt any network on my device (Windows & IOS ) then i Compared it with my old server wich i already running ipsec on it
 and i gussed that the problem was that in my new server my public and private IPs were both same
 so i tried to use 127.0.0.1 as private_ip so I'd changed IPs in ipsec.conf and IPtables
and
 i failed to Auth ! and i got this error on `service ipsec status` 
`reapchild failed with errno=10 No child processes` 
So i reverted config to its default and came here to ask for your help , Any suggestions ?

**Comment by hwdsl2** [comment]
@shadowy70 Hello! It is OK if PRIVATE_IP & PUBLIC_IP are the same. This is normal for servers directly connected to the Internet (not behind a NAT device). Please do not use 127.0.0.1 as PRIVATE_IP. This message: ` reapchild failed with errno=10 No child processes` is also normal.

Please post your IPTables rules for further troubleshooting:
```
iptables -nvL; iptables -nvL -t nat
```

**Comment by shadowy70** [comment]
Ok here
` pkts bytes target     prot opt in     out     source               destination 
 2131  223K f2b-SSH    tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22
 5803 5724K ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  lo     *       0.0.0.0/0            0.0.0.0/0   
   87  6553 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0   
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp spts:67:68 dpts:67:68
  116  6352 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22
    3  1108 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 500,4500
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:1701 policy match dir in pol ipsec

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination 
    0     0 ACCEPT     all  --  venet0 ppp+    0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  ppp+   venet0  0.0.0.0/0            0.0.0.0/0   
    0     0 ACCEPT     all  --  ppp+   ppp+    192.168.42.0/24      192.168.42.0/24
    0     0 ACCEPT     all  --  venet0 *       0.0.0.0/0            192.168.43.0/24      ctstate RELATED,ESTABLISHED
  126  7548 ACCEPT     all  --  *      venet0  192.168.43.0/24      0.0.0.0/0   

Chain OUTPUT (policy ACCEPT 508 packets, 61845 bytes)
 pkts bytes target     prot opt in     out     source               destination 

Chain f2b-SSH (1 references)
 pkts bytes target     prot opt in     out     source               destination 
 1562  185K RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0   
Chain PREROUTING (policy ACCEPT 3769 packets, 192K bytes)
 pkts bytes target     prot opt in     out     source               destination 

Chain POSTROUTING (policy ACCEPT 264 packets, 16936 bytes)
 pkts bytes target     prot opt in     out     source               destination 
    0     0 SNAT       all  --  *      venet0  192.168.42.0/24      0.0.0.0/0            to:107.155.107.151
   39  2318 SNAT       all  --  *      venet0  192.168.43.0/24      0.0.0.0/0            policy match dir out pol none to:107.155.107.151

Chain OUTPUT (policy ACCEPT 264 packets, 16936 bytes)
 pkts bytes target     prot opt in     out     source               destination 
`

**Comment by shadowy70** [comment]
ok look
`iptables -nvL; iptables -nvL -t nat`
 pkts bytes target     prot opt in     out     source               destination 
 2131  223K f2b-SSH    tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22
 5803 5724K ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  lo     *       0.0.0.0/0            0.0.0.0/0   
   87  6553 ACCEPT     icmp --  *      *       0.0.0.0/0            0.0.0.0/0   
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp spts:67:68 dpts:67:68
  116  6352 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22
    3  1108 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 500,4500
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:1701 policy match dir in pol ipsec

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination 
    0     0 ACCEPT     all  --  venet0 ppp+    0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all  --  ppp+   venet0  0.0.0.0/0            0.0.0.0/0   
    0     0 ACCEPT     all  --  ppp+   ppp+    192.168.42.0/24      192.168.42.0/24
    0     0 ACCEPT     all  --  venet0 *       0.0.0.0/0            192.168.43.0/24      ctstate RELATED,ESTABLISHED
  126  7548 ACCEPT     all  --  *      venet0  192.168.43.0/24      0.0.0.0/0   

Chain OUTPUT (policy ACCEPT 508 packets, 61845 bytes)
 pkts bytes target     prot opt in     out     source               destination 

Chain f2b-SSH (1 references)
 pkts bytes target     prot opt in     out     source               destination 
 1562  185K RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0   
Chain PREROUTING (policy ACCEPT 3769 packets, 192K bytes)
 pkts bytes target     prot opt in     out     source               destination 

Chain POSTROUTING (policy ACCEPT 264 packets, 16936 bytes)
 pkts bytes target     prot opt in     out     source               destination 
    0     0 SNAT       all  --  *      venet0  192.168.42.0/24      0.0.0.0/0            to:107.155.107.151
   39  2318 SNAT       all  --  *      venet0  192.168.43.0/24      0.0.0.0/0            policy match dir out pol none to:107.155.107.151

Chain OUTPUT (policy ACCEPT 264 packets, 16936 bytes)
 pkts bytes target     prot opt in     out     source               destination

**Comment by hwdsl2** [comment]
@shadowy70 It looks like you are using an OpenVZ VPS which does not support IPsec (in most cases). The script should output an error and refuse to run, unless you have modified it to remove that check.

If you run `ipsec verify` you will see that IPsec kernel support is not available. Therefore IPsec VPN cannot be set up on your server. I would suggest that you instead try Nyr's OpenVPN [1] script.

[1] https://github.com/Nyr/openvpn-install

**Comment by shadowy70** [comment]
`ipsec verify`
Verifying installed system and configuration files

Version check and ipsec on-path                         [OK]
Libreswan 3.18 (netkey) on 2.6.32-042stab112.15
Checking for IPsec support in kernel                    [OK]
 NETKEY: Testing XFRM related proc values
         ICMP default/send_redirects                    [OK]
         ICMP default/accept_redirects                  [OK]
         XFRM larval drop                               [OK]
Pluto ipsec.conf syntax                                 [OK]
Hardware random device                                  [N/A]
Two or more interfaces found, checking IP forwarding    [OK]
Checking rp_filter                                      [ENABLED]
 /proc/sys/net/ipv4/conf/gre0/rp_filter                 [ENABLED]
 /proc/sys/net/ipv4/conf/gretap0/rp_filter              [ENABLED]
 /proc/sys/net/ipv4/conf/eth0/rp_filter                 [ENABLED]
  rp_filter is not fully aware of IPsec and should be disabled
Checking that pluto is running                          [OK]
 Pluto listening for IKE on udp 500                     [OK]
 Pluto listening for IKE/NAT-T on udp 4500              [OK]
 Pluto ipsec.secret syntax                              [OK]
Checking 'ip' command                                   [OK]
Checking 'iptables' command                             [OK]
Checking 'prelink' command does not interfere with FIPSChecking for obsolete ipsec.conf options                 [OK]
Opportunistic Encryption                                [DISABLED]

ipsec verify: encountered 7 errors - see 'man ipsec_verify' for help

**Comment by hwdsl2** [comment]
@shadowy70 Thanks for the details. Is this an OpenVZ VPS or OpenVZ host node? If VPS, which provider is it? I see that you have an `eth0` interface but you have `venet0` in your IPTables rules. Why? Please give more details about your server.

**Comment by shadowy70** [comment]
its an OpenVZ VPS and take a look at faq part:
https://wable.com/faq#faq-22
then for getiing rid of changing every setting i used to enable a fake eth0 today manually from management part :
![capture](https://cloud.githubusercontent.com/assets/23007213/19631609/7d5c6674-99ab-11e6-8466-7a9df479c6f1.JPG)

**Comment by hwdsl2** [comment]
@shadowy70 OK. Got it. Yes you can use IPsec on this VPS. What changes did you make to the VPN setup script? Did you manually specify the interface as `venet0`? Also, can you check your default route:

```
ip route
```

**Comment by shadowy70** [comment]
i simply deleted the line about OpenVZ and then as instructed gave the VPN_IFACE="venet0" in installation ..

'ip route'
'''
169.254.0.0/16 dev venet0  scope link  metric 1002
169.254.0.0/16 dev eth0  scope link  metric 1005
default dev venet0  scope link
'''

**Comment by shadowy70** [comment]
i simply deleted the line about OpenVZ and then as instructed gave the VPN_IFACE="venet0" in installation ..

`ip route`
```
169.254.0.0/16 dev venet0 scope link metric 1002
169.254.0.0/16 dev eth0 scope link metric 1005
default dev venet0 scope link
```

**Comment by hwdsl2** [comment]
@shadowy70 I see. I think your setup looks fine. Your IPTables rules look good too. Can you try connecting with IPsec/L2TP?

**Comment by hwdsl2** [comment]
@shadowy70 Other things to try:

1. Reboot your VPS and try connecting the VPN.
2. Re-install the VPS with a fresh OS and run the setup script again. Do not add the `eth0` interface.

**Comment by shadowy70** [comment]
Xl2tpd service fail 2 start ..
& other thing is i had problem even before eth0 interface 
Can it be some problem with RP_filter ?

**Comment by hwdsl2** [comment]
@shadowy70 Please try the following:

Edit `/etc/iptables.rules` and find these two lines:
```
-A POSTROUTING -s 192.168.42.0/24 -o venet0 -j SNAT --to-source YOUR_SERVER_IP
-A POSTROUTING -s 192.168.43.0/24 -o venet0 -m policy --dir out --pol none -j SNAT --to-source YOUR_SERVER_IP
```

Replace them with:
```
-A POSTROUTING -s 192.168.42.0/24 -o venet0 -j MASQUERADE
-A POSTROUTING -s 192.168.43.0/24 -o venet0 -m policy --dir out --pol none  -j MASQUERADE
```

Then run:
```
iptables-restore < /etc/iptables.rules
service fail2ban restart
echo 1 > /proc/sys/net/ipv4/ip_forward
```

Try connect the VPN again.

**Comment by shadowy70** [comment]
Ok i've changed /etc/sysconfig/iptables
but can you give equivalent commands for Centos ?
is it : 
```
service iptables restart
service fail2ban restart
echo 1 > /proc/sys/net/ipv4/ip_forward
``` 
?

**Comment by hwdsl2** [comment]
@shadowy70 For CentOS please try:
```
iptables-restore < /etc/sysconfig/iptables
service fail2ban restart
echo 1 > /proc/sys/net/ipv4/ip_forward
```

**Comment by shadowy70** [comment]
ok still nothing let us do a more simple job ! can you please authenticate on my server which is pretty empty of anything else than a yet-not-functional vpn server ? :laughing:

**Comment by hwdsl2** [comment]
@shadowy70 OK. Please drop me an email (see my GitHub profile).
