### ISSUE TITLE
pk12util cert file password error

### ISSUE THREAD

**Issue by miladmeidanshahi** [hwdsl2/setup-ipsec-vpn#750]
I generate my cert with password
```
pk12util -o vpnclient.p12 -n "vpnclient" -d sql:/etc/ipsec.d
```

but when I import in windows I got an error that password is incorrect!

**Comment by ChrisChirs** [comment]
I met the same situation.

**Comment by ponpon25** [comment]
Hi,
Could you tell me how you transfer and where is stored the vpnclient.p12 file ? With Cyberduck i navigated to the folder /etc and i didn't find anything.

**Comment by hwdsl2** [comment]
Hello! This is a known issue [1] when you generate the `.p12` file on Ubuntu 18.04 or CentOS systems.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#known-issues
