### ISSUE TITLE
service ipsec status an error.And sers can connect, but cannot use a VPN to connect to the Internet.

### ISSUE THREAD

**Issue by shanayinghua** [hwdsl2/setup-ipsec-vpn#751]
ipsec.service - Internet Key Exchange (IKE) Protocol Daemon for IPsec
   Loaded: loaded (/usr/lib/systemd/system/ipsec.service; disabled; vendor preset: disabled)
   Active: active (running) since 一 2020-03-16 16:11:26 CST; 14s ago
     Docs: man:ipsec(8)
           man:pluto(8)
           man:ipsec.conf(5)
  Process: 24584 ExecStopPost=/usr/local/sbin/ipsec --stopnflog (code=exited, status=0/SUCCESS)
  Process: 24581 ExecStopPost=/sbin/ip xfrm state flush (code=exited, status=0/SUCCESS)
  Process: 24578 ExecStopPost=/sbin/ip xfrm policy flush (code=exited, status=0/SUCCESS)
  Process: 24562 ExecStop=/usr/local/libexec/ipsec/whack --shutdown (code=exited, status=0/SUCCESS)
  Process: 24860 ExecStartPre=/usr/local/sbin/ipsec --checknflog (code=exited, status=0/SUCCESS)
  Process: 24858 ExecStartPre=/usr/local/sbin/ipsec --checknss (code=exited, status=0/SUCCESS)
  Process: 24595 ExecStartPre=/usr/local/libexec/ipsec/_stackmanager start (code=exited, status=0/SUCCESS)
  Process: 24592 ExecStartPre=/usr/local/libexec/ipsec/addconn --config /etc/ipsec.conf --checkconfig (code=exited, status=0/SUCCESS)
 Main PID: 24873 (pluto)
   Status: "Startup completed."
   CGroup: /system.slice/ipsec.service
           └─24873 /usr/local/libexec/ipsec/pluto --leak-detective --config /etc/ipsec.conf --nofork

#**3月 16 16:11:26 singapore pluto[24873]: ERROR: can't offload to eth0 because SIOCETHTOOL ETHTOOL_GSSET_INFO failed. Errno 95: Operation not supported**
3月 16 16:11:26 singapore pluto[24873]: Kernel does not support NIC esp-hw-offload
3月 16 16:11:26 singapore pluto[24873]: adding interface eth0/eth0 (esp-hw-offload=no) 192.168.1.133:500
3月 16 16:11:26 singapore pluto[24873]: adding interface eth0/eth0 192.168.1.133:4500
3月 16 16:11:26 singapore pluto[24873]: Kernel does not support NIC esp-hw-offload
3月 16 16:11:26 singapore pluto[24873]: adding interface lo/lo (esp-hw-offload=no) 127.0.0.1:500
3月 16 16:11:26 singapore pluto[24873]: adding interface lo/lo 127.0.0.1:4500
3月 16 16:11:26 singapore pluto[24873]: Kernel does not support NIC esp-hw-offload
3月 16 16:11:26 singapore pluto[24873]: adding interface lo/lo (esp-hw-offload=no) ::1:500
3月 16 16:11:26 singapore pluto[24873]: loading secrets from "/etc/ipsec.secrets"

**Comment by hwdsl2** [comment]
@shanayinghua Hello! The error you mentioned is normal. The issue you described (cannot connect to the Internet) is most likely caused by your server itself. Try the setup scripts on a new freshly installed server.
