### ISSUE TITLE
win10上配置IPsec/XAuth VPN，无法连接公网。

### ISSUE THREAD

**Issue by btlishang** [hwdsl2/setup-ipsec-vpn#752]
win10上使用 Shrew Soft VPN ，配置成功后可以ping通内网环境，但是连接成功后，无法访问英特网。

求助

**Comment by hwdsl2** [comment]
@btlishang 你好！ Shrew Soft VPN 不支持 Windows 10。你可以另外尝试 IPsec/L2TP 模式 [1]。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md
