### ISSUE TITLE
ipsec 用户存储密码的加密方式是什么

### ISSUE THREAD

**Issue by gzldc** [hwdsl2/setup-ipsec-vpn#755]
想写个web界面，手动添加用户，请问用户的密码是如何加密存储的？

**Comment by hwdsl2** [comment]
@gzldc 请参见 https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users-zh.md#%E6%89%8B%E5%8A%A8%E7%AE%A1%E7%90%86-vpn-%E7%94%A8%E6%88%B7%E5%92%8C-psk

**Comment by gzldc** [comment]
感谢
