### ISSUE TITLE
Error: Libreswan 3.29 failed to build.

### ISSUE THREAD

**Issue by pcevikogullari** [hwdsl2/setup-ipsec-vpn#756]
I got the following error log on Centos:

a - lswlog.o
a - libreswan_exit.o
In file included from /opt/src/libreswan-3.29/programs/pluto/linux-copy/linux/xfrm.h:5:0,
                 from /opt/src/libreswan-3.29/programs/pluto/kernel_netlink.c:61:
/usr/include/linux/in6.h:30:8: error: redefinition of ‘struct in6_addr’
 struct in6_addr {
        ^
In file included from /opt/src/libreswan-3.29/include/libreswan.h:63:0,
                 from /opt/src/libreswan-3.29/programs/pluto/kernel_netlink.c:60:
/usr/include/netinet/in.h:197:8: note: originally defined here
 struct in6_addr
        ^
In file included from /opt/src/libreswan-3.29/programs/pluto/linux-copy/linux/xfrm.h:5:0,
                 from /opt/src/libreswan-3.29/programs/pluto/kernel_netlink.c:61:
/usr/include/linux/in6.h:41:8: error: redefinition of ‘struct sockaddr_in6’
 struct sockaddr_in6 {
        ^
In file included from /opt/src/libreswan-3.29/include/libreswan.h:63:0,
                 from /opt/src/libreswan-3.29/programs/pluto/kernel_netlink.c:60:
/usr/include/netinet/in.h:238:8: note: originally defined here
 struct sockaddr_in6
        ^
In file included from /opt/src/libreswan-3.29/programs/pluto/linux-copy/linux/xfrm.h:5:0,
                 from /opt/src/libreswan-3.29/programs/pluto/kernel_netlink.c:61:
/usr/include/linux/in6.h:49:8: error: redefinition of ‘struct ipv6_mreq’
 struct ipv6_mreq {
        ^
In file included from /opt/src/libreswan-3.29/include/libreswan.h:63:0,
                 from /opt/src/libreswan-3.29/programs/pluto/kernel_netlink.c:60:
/usr/include/netinet/in.h:274:8: note: originally defined here
 struct ipv6_mreq
        ^
make[3]: *** [kernel_netlink.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [base] Error 2
make[1]: *** [recursive-base] Error 2
make: *** [recursive-base] Error 2
Error: Libreswan 3.29 failed to build.

**Comment by letoams** [comment]
You can grab our source and binary rpms for centos on downloads.libreswan.org/binaries/rhel/

Paul

**Comment by hwdsl2** [comment]
@pcevikogullari I was not able to reproduce this error on a CentOS 6 system. Recently I updated the scripts to support Libreswan 3.31. Please try the new version.
