### ISSUE TITLE
How to add speed limit for specific user or all users per second?

### ISSUE THREAD

**Issue by hassaan-dev** [hwdsl2/setup-ipsec-vpn#758]
Hi,

I am new to VPN Servers. I want any specific or all VPN users, should not get more than 5mb per second speed. Can you please help with this?

Thanks in advance

**Comment by letoams** [comment]
On Fri, 20 Mar 2020, hassaan-dev wrote:

> I am new to VPN Servers. I want any specific or all VPN users, should not get more than 5mb per second speed. Can you please help with this?

google for "rate limit linux tc"

You can make it conditional per user if you add something in the
_updown.netkey command and use the environment variables that
set the username and IP address. See the _updown.netkey file
(in /usr/libexec/ipsec/ or /usr/lib64/ipsec) for exact names.

Paul

**Comment by hassaan-dev** [comment]
I have searched regarding linux traffic control, I think, I need specify tunnels or ports to limit them via traffic control.

Can you help me to get list of all ports available or would used for VPN ?

**Comment by hassaan-dev** [comment]
I tried to implement `traffic control` but it is implemented on whole network not for specific user.

I tried this command to limit speed `tc qdisc add dev eth0 root tbf rate 1mbit`

**Comment by letoams** [comment]
You want to rate limit per IP, try solution #3 from this page ? https://making.pusher.com/per-ip-rate-limiting-with-iptables/

Anyway, this really has nothing to do with IPsec. You want to rate limit each IP from your addresspool used by libreswan using generic tc commands with Linux.

**Comment by hwdsl2** [comment]
Thanks @letoams!
