### ISSUE TITLE
How to get active connections list with username?

### ISSUE THREAD

**Issue by hassaan-dev** [hwdsl2/setup-ipsec-vpn#759]
Hi,

Is it possible to get list of active connections along with user name via any terminal command or way?

**Comment by letoams** [comment]
ipsec trafficstatus should give you that

**Comment by hassaan-dev** [comment]
I am using CentOS 7. I connect two users first from Windows 10 and second from mobile

`ipsec trafficstatus` output
>bash: ipsec: command not found

with `/usr/local/sbin/ipsec trafficstatus` I am able to get status. I can see list of connections but I can't identify the users with username or anything

>`006 #17: "l2tp-psk"[13] 182.***.***.74, type=ESP, add_time=1584803374, inBytes=84094, outBytes=154890, id='192.168.0.104'`
`006 #19: "l2tp-psk"[14] 182.***.***.74, type=ESP, add_time=1584803507, inBytes=26367, outBytes=21156, id='192.168.0.103'`

**Comment by letoams** [comment]
If you use L2TP then that info is really with pppd, so check on the pppd documentation

Paul

**Comment by hassaan-dev** [comment]
Can you please explain more or share some sample configurations?
I tried with pppd documentation but I am new to VPN and did not get that how to exactly I do this or how I start it

**Comment by hassaan-dev** [comment]
Is it possible, when some user request for connection then after connecting, his connection ID and username sent to some Web service via post or get methods?

**Comment by letoams** [comment]
On Thu, 26 Mar 2020, hassaan-dev wrote:

> Is it possible, when some user request for connection then after connecting, his connection ID
> and username sent to some Web service via post or get methods?

Yes, you copy the default _updown.netkey script and modify it, then use
leftupdown=/usr/local/bin/yourupdown.sh

For an example, see: https://github.com/libreswan/libreswan/tree/master/contrib/updown-example

Paul

**Comment by hassaan-dev** [comment]
Where I put this `leftupdown=/usr/local/bin/yourupdown.sh` at top of file or end of file?

second thing, how to access username, user ip and assigned ip of user in side `yourdown.sh` ?

**Comment by hassaan-dev** [comment]
Can you please guide me a bit more please?

**Comment by hassaan-dev** [comment]
I spend many days on it to figure this out but still did not get it :(

**Comment by hassaan-dev** [comment]
👎

**Comment by hwdsl2** [comment]
@hassaan-dev Hello! I'm not familiar with `/usr/local/bin/yourupdown.sh`, but for viewing the connected users locally for IPsec/L2TP, you can try my experimental script in #166.
