### ISSUE TITLE
The L2TP-VPN server did not respond

### ISSUE THREAD

**Issue by nodesocket** [hwdsl2/setup-ipsec-vpn#76]
Setup on a Raspberry Pi 3 Model B running Raspbian Jessie. When I try to connect via **L2TP** on my iPhone I am getting the error:

    The L2TP-VPN server did not respond.

Confirmed that I opened up port UDP 500 and UDP 4500 for the Raspberry Pi's local ip address.

Any ideas? Is there a way to test if indeed the ports are open? I tried netcat `nc`:

`nc -u $MY_IP 500` and `nc -u $MY_IP 4500`

But no response. Are there log files to inspect?

**Comment by hwdsl2** [comment]
@nodesocket Is your RPi directly connected to the Internet, or is it behind a router? Did you use the RPi's public IP on the iPhone? You may need to set up port forwarding on your router for UDP ports 500 and 4500, to the RPi's local IP.

To check the VPN logs on your RPi, run `grep pluto /var/log/auth.log /var/log/syslog`.

**Comment by nodesocket** [comment]
Does this indicate an error:

````
/var/log/auth.log:Oct 24 15:10:05 pi pluto[877]: reapchild failed with errno=10 No child processes
/var/log/syslog:Oct 24 15:10:03 pi pluto[877]: Oct 24 15:10:03: pluto: warning: chdir("/var/run/pluto") to dumpdir failed (2: No such file or directory)
/var/log/syslog:Oct 24 15:10:03 pi pluto: pluto: warning: chdir("/var/run/pluto") to dumpdir failed (2: No such file or directory)
````

**Comment by hwdsl2** [comment]
@nodesocket Please try the following (as root):

`mkdir -p /var/run/pluto`
`service ipsec restart`
`ipsec verify`

**Comment by nodesocket** [comment]
````
➜  init.d ipsec verify
Verifying installed system and configuration files

Version check and ipsec on-path                   	[OK]
Libreswan 3.18 (netkey) on 4.4.26-v7+
Checking for IPsec support in kernel              	[OK]
 NETKEY: Testing XFRM related proc values
         ICMP default/send_redirects              	[OK]
         ICMP default/accept_redirects            	[OK]
         XFRM larval drop                         	[OK]
Pluto ipsec.conf syntax                           	[OK]
Hardware random device                            	[N/A]
Two or more interfaces found, checking IP forwarding	[OK]
Checking rp_filter                                	[OK]
Checking that pluto is running                    	[OK]
 Pluto listening for IKE on udp 500               	[FAILED]
 Pluto listening for IKE/NAT-T on udp 4500        	[DISABLED]
 Pluto ipsec.secret syntax                        	[OK]
Checking 'ip' command                             	[OK]
Checking 'iptables' command                       	[OK]
Checking 'prelink' command does not interfere with FIPSChecking for obsolete ipsec.conf options          	[OK]
Opportunistic Encryption                          	[DISABLED]

ipsec verify: encountered 2 errors - see 'man ipsec_verify' for help
````

**Comment by nodesocket** [comment]
Ok figured it out. After a clean reboot, does not work. However, when I run:

`service ipsec restart`

It works. Any ideas?

**Comment by hwdsl2** [comment]
@nodesocket The output looks OK. Try connecting the VPN. If still not working, reboot RPi and then repeat the three commands as root.

**Comment by hwdsl2** [comment]
@nodesocket It could be that IPsec failed to start during boot. One possible reason is that the network is not ready when it tried to start, as the RPi does not guarantee this.

Edit /etc/rc.local and add a delay e.g. `sleep 180` before the `service ipsec restart` command. Then reboot, wait a few mins and see if it connects OK.

**Comment by nodesocket** [comment]
So I had to add a sleep, as well as change from `start` to `restart`.

````shell
sleep 5

service ipsec restart
````

Does that make sense?

**Comment by hwdsl2** [comment]
@nodesocket Either `start` or `restart` should work. Please set a longer sleep time, such as 60 seconds. You can reduce it if it works fine.
