### ISSUE TITLE
is it possible to limit bandwidth for users like 20mb per username

### ISSUE THREAD

**Issue by doctoralpha** [hwdsl2/setup-ipsec-vpn#760]
is it possible to limit bandwidth for users like 20mb per username
or unlimit user bandwidth

and what is uniqueids in confiquration?
is it possible to limit users to connect 1 connection per 1 user with uiqueids?

**Comment by letoams** [comment]
On Mar 20, 2020, at 09:34, doctoralpha <notifications@github.com> wrote:
> 
> ﻿
> is it possible to limit bandwidth for users like 20mb per username
> or unlimit user bandwidth
> 

Just limit a single IP to a certain bandwidth ? No need to do anything IPsec specific.
> and what is uniqueids in confiquration?
> is it possible to limit users to connect 1 connection per 1 user with uiqueids?
> 

Yes but be careful, things like Apple wifi-assist might try to connect twice - once for each interface.

Paul

**Comment by hwdsl2** [comment]
Thanks @letoams!

@doctoralpha These features are not supported.
