### ISSUE TITLE
Can't access my home network

### ISSUE THREAD

**Issue by FaxMac** [hwdsl2/setup-ipsec-vpn#761]
Hello, i installed the script on a raspberry pi and it works fine, it connects to the vpn through my local network and through the internet, but my problem is trying to access my local network resources (printers, other pcs,etc) i already tried using the configurations on 
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#access-vpn-servers-subnet but i still cant connect. 

My local network uses 192.168.1.X and here are my iptables 
![imagen](https://user-images.githubusercontent.com/39447436/77193706-7014dc80-6abd-11ea-9a50-e0bcf288ba68.png)

**Comment by hwdsl2** [comment]
@FaxMac Hello! I have tested the use case you mentioned, and was able to successfully access local network resources after connecting to the VPN. The default configuration worked fine, and there was no need to change IPTables using the link you mentioned. Please check the firewall on each device you want to access, to make sure traffic from your local network is permitted.
