### ISSUE TITLE
xl2tpd没有响应

### ISSUE THREAD

**Issue by kuramaf** [hwdsl2/setup-ipsec-vpn#762]
aws ec2 Ubuntu Server 18.04
window 10 连接失败：无法连接到VPN。无法建立计算机与VPN服务器之间的网络连接，因为远程服务器器未响应。
Ubuntu 上抓包，接收到请求报文，但是没有响应：
root@ip-172-31-34-185:/home# tcpdump udp port 1701
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
16:57:21.026082 IP 117.176.228.5.14253 > ip-172-31-34-185.ap-northeast-2.compute.internal.l2f:  l2tp:[TLS](0/0)Ns=0,Nr=0 *MSGTYPE(SCCRQ) *PROTO_VER(1.0) *FRAMING_CAP(S) *BEARER_CAP() FIRM_VER(2560) *HOST_NAME(DESKTOP-QE6MOGJ) VENDOR_NAME(Microsoft) *ASSND_TUN_ID(26) *RECV_WIN_SIZE(8)

检查服务状态均正常。

**Comment by hwdsl2** [comment]
不建议如上修改 IPTables 设置，因为会打开本应受到保护的 L2TP UDP 1701 端口。该端口在正常连接时不需要打开。关于你所说的问题，可能要更改注册表设置 [1]。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#windows-%E9%94%99%E8%AF%AF-809
