### ISSUE TITLE
Can't connect to server with more then 1 user [NOT UNDER THE SAME NAT]

### ISSUE THREAD

**Issue by Loginbug** [hwdsl2/setup-ipsec-vpn#764]
Hello, 
thanks for your work.
I'm using a Scaleway VPS as Server (Ubuntu Bionic Beaver) and two Windows 10 PCs as my clients.
L2TP/IPSEC mode.
Please note that the PCs are under two different DSL. 
Of course, i have added a second user with your script. 
Anyway i'm able to connect to server with more than 1 pc at the same time.

(Libreswan 3.31 is out, but script uses 3.29.)

**Comment by hwdsl2** [comment]
@Loginbug Libreswan 3.31 is now supported. Please try the updated VPN setup scripts.
