### ISSUE TITLE
Windows 10 connection hangs

### ISSUE THREAD

**Issue by OmarJay1** [hwdsl2/setup-ipsec-vpn#765]
Hello, thanks for putting together this awesome package.  I'm having a bit of trouble connecting with a Windows 10 client.  The connection just hangs saying "Connecting" forever.  At first I got an error message about the server not responding.  I fixed that with a Registry change that was posted.  

Here are my server logs.  I'm connecting inside a private subnet to test before giving it a live address.  

The logs show the connection established, then deleted after 5 minutes.

Any ideas or pointing in a direction would be appreciated.  Thanks.

Mar 25 11:24:12 localhost pluto[2987]: "l2tp-psk"[10] 192.168.1.112 #47: responding to Main Mode from unknown peer 192.168.1.112 on port 500
Mar 25 11:24:12 localhost pluto[2987]: "l2tp-psk"[10] 192.168.1.112 #47: WARNING: connection l2tp-psk PSK length of 9 bytes is too short for sha PRF in FIPS mode (10 bytes required)
Mar 25 11:24:12 localhost pluto[2987]: "l2tp-psk"[10] 192.168.1.112 #47: Oakley Transform [AES_CBC (256), HMAC_SHA1, DH20] refused
Mar 25 11:24:12 localhost pluto[2987]: "l2tp-psk"[10] 192.168.1.112 #47: WARNING: connection l2tp-psk PSK length of 9 bytes is too short for sha PRF in FIPS mode (10 bytes required)
Mar 25 11:24:12 localhost pluto[2987]: "l2tp-psk"[10] 192.168.1.112 #47: Oakley Transform [AES_CBC (128), HMAC_SHA1, DH19] refused
Mar 25 11:24:12 localhost pluto[2987]: "l2tp-psk"[10] 192.168.1.112 #47: WARNING: connection l2tp-psk PSK length of 9 bytes is too short for sha PRF in FIPS mode (10 bytes required)
Mar 25 11:24:12 localhost pluto[2987]: "l2tp-psk"[10] 192.168.1.112 #47: STATE_MAIN_R1: sent MR1, expecting MI2
Mar 25 11:24:12 localhost pluto[2987]: "l2tp-psk"[10] 192.168.1.112 #47: STATE_MAIN_R2: sent MR2, expecting MI3
Mar 25 11:24:12 localhost pluto[2987]: "l2tp-psk"[10] 192.168.1.112 #47: Peer ID is ID_IPV4_ADDR: '192.168.1.112'
Mar 25 11:24:12 localhost pluto[2987]: "l2tp-psk"[10] 192.168.1.112 #47: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA1 group=MODP2048}
Mar 25 11:24:12 localhost pluto[2987]: "l2tp-psk"[10] 192.168.1.112 #47: Configured DPD (RFC 3706) support not enabled because remote peer did not advertise DPD support
Mar 25 11:24:12 localhost pluto[2987]: "l2tp-psk"[10] 192.168.1.112 #47: the peer proposed: 192.168.1.22/32:17/1701 -> 192.168.1.112/32:17/0
Mar 25 11:24:12 localhost pluto[2987]: "l2tp-psk"[10] 192.168.1.112 #47: NAT-Traversal: received 2 NAT-OA. Using first; ignoring others
Mar 25 11:24:12 localhost pluto[2987]: "l2tp-psk"[10] 192.168.1.112 #48: responding to Quick Mode proposal {msgid:00000001}
Mar 25 11:24:12 localhost pluto[2987]: "l2tp-psk"[10] 192.168.1.112 #48:     us: 192.168.1.22[173.13.130.177]:17/1701
Mar 25 11:24:12 localhost pluto[2987]: "l2tp-psk"[10] 192.168.1.112 #48:   them: 192.168.1.112:17/1701
Mar 25 11:24:12 localhost pluto[2987]: "l2tp-psk"[10] 192.168.1.112 #48: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 transport mode {ESP/NAT=>0x3ed49f7e <0xecc2e99b xfrm=AES_CBC_256-HMAC_SHA1_96 NATOA=192.168.1.112 NATD=192.168.1.112:4500 DPD=unsupported}
Mar 25 11:24:12 localhost pluto[2987]: "l2tp-psk"[10] 192.168.1.112 #48: STATE_QUICK_R2: IPsec SA established transport mode {ESP/NAT=>0x3ed49f7e <0xecc2e99b xfrm=AES_CBC_256-HMAC_SHA1_96 NATOA=192.168.1.112 NATD=192.168.1.112:4500 DPD=unsupported}
Mar 25 11:29:12 localhost pluto[2987]: "l2tp-psk"[10] 192.168.1.112 #47: received Delete SA(0x3ed49f7e) payload: deleting IPsec State #48
Mar 25 11:29:12 localhost pluto[2987]: "l2tp-psk"[10] 192.168.1.112 #48: deleting other state #48 (STATE_QUICK_R2) aged 300.369s and sending notification
Mar 25 11:29:12 localhost pluto[2987]: "l2tp-psk"[10] 192.168.1.112 #48: ESP traffic information: in=660B out=0B
Mar 25 11:29:12 localhost pluto[2987]: "l2tp-psk" #47: deleting state (STATE_MAIN_R3) aged 300.433s and sending notification
Mar 25 11:29:12 localhost pluto[2987]: "l2tp-psk"[10] 192.168.1.112: deleting connection "l2tp-psk"[10] 192.168.1.112 instance with peer 192.168.1.112 {isakmp=#0/ipsec=#0}

**Comment by OmarJay1** [comment]
I was getting the above error because I hadn't opened port 1701 (L2TP) in my firewall.  I got another error that was fixed by this:
https://github.com/hwdsl2/setup-ipsec-vpn/issues/7

I can connect now. Thanks.

**Comment by letoams** [comment]
Looks like the IPsec part worked but the l2tp part did not and then windows disconnected.

Check your xl2tpd settings and logs ?

**Comment by OmarJay1** [comment]
Letoams, thanks.  It did have to do with l2tp.  My firewall was blocking port 1701.  

Thanks you very much.
