### ISSUE TITLE
Unsuccessful for android 10 on samsung m20

### ISSUE THREAD

**Issue by kevinhq** [hwdsl2/setup-ipsec-vpn#766]
Thanks for such helpful scripts.
This works perfectly well on Mac os catalina.
However, it never work on Android 10 on Samsung M20. It's just connecting forever and gets unsuccessful.

Am I missing something here?

**Comment by kevinhq** [comment]
Update: look at the auth.log, it's raising this error:

```
probable authentication failure (mismatch of preshared secrets?): malformed payload in packet
```

Not sure if this is an issue with Android 10 but I'll try to dig myself.

**Comment by kevinhq** [comment]
Now that I choose L2TP, Got another log like this:

```
OAKLEY_DES_CBC(UNUSED) is not supported
```

**Comment by prokiller1199** [comment]
how/where to see the auth.log? im new, i can connect to windows 10 but not android weird...

**Comment by hwdsl2** [comment]
@kevinhq Hello! The error `probable authentication failure (mismatch of preshared secrets?)` means the IPsec PSK in your Android VPN configuration does not match your VPN server in `/etc/ipsec.secrets`. Re-create the VPN connection and make sure it matches. If you get `unsuccessful`, try the second step in [1].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#android-6-and-7
