### ISSUE TITLE
How to block specific websites?

### ISSUE THREAD

**Issue by hassaan-dev** [hwdsl2/setup-ipsec-vpn#769]
Hi,

I want to block specific websites. For example google.com & yahoo.com

I tried to block them via `hosts` file but this did not work.

Can you please help me with this one?

**Comment by hassaan-dev** [comment]
Any update on this?

**Comment by hassaan-dev** [comment]
Can you tell me any direction here please?

**Comment by hassaan-dev** [comment]
Is there is any middle-ware bash file that stop loading specific website or which methods/files are called when user request to load website?

**Comment by hassaan-dev** [comment]
There is not one to reply here 👎

**Comment by hwdsl2** [comment]
@hassaan-dev Hello! This feature is not supported. As an alternative, you might be able to set up a custom DNS server that blocks those websites, then use those custom DNS servers when setting up the VPN server. See the DNS notes in [1]. Unfortunately, users might be able to circumvent this by e.g. visiting those websites using their IP addresses directly, so it may not work.

[1] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes
