### ISSUE TITLE
阿里云,centos7.2，安装没反应了呢。

### ISSUE THREAD

**Issue by yanpengfei** [hwdsl2/setup-ipsec-vpn#77]
阿里云,centos7.2，yum的包安装完了之后没反应，我不是翻墙，我是让国外上国内网站。。。。

**Comment by hwdsl2** [comment]
@yanpengfeu 请提供详细错误信息或脚本输出。

**Comment by yanpengfei** [comment]
抱歉我没法给你还原，因为我已经搭建上了，没法再搭建一次了，服务器也没法再重置了，不过我用的是：https://teddysun.com/448.html。

**Comment by yanpengfei** [comment]
这样，我再帮你试试，我把服务器镜像一下，还原到以前用你的再装一下。

**Comment by hwdsl2** [comment]
@yanpengfei 好的！感谢你提供这些信息。我没有阿里云账户，如果有其他用户报告同样的问题，到时我再看一下。
