### ISSUE TITLE
Failed to Configure IPsec/XAuth VPN Clients in Fedora 31

### ISSUE THREAD

**Issue by wffger** [hwdsl2/setup-ipsec-vpn#773]
I follow the [guide](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md#linux). I got issues in the 5th and 9th step:

> Select IKEv1 (XAUTH) in the Type drop-down menu.

I can't find the Type drop-down menu.

> Leave the Group name field blank.

If I leave the field blank, I can't save the configue.

**Comment by hwdsl2** [comment]
@wffger Hello! The instructions for Fedora have been tested and confirmed working. First, install the `NetworkManager-libreswan-gnome` package using `yum`. Then follow the instructions [1]. In step 2, be sure to select "IPsec based VPN".

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md#linux
