### ISSUE TITLE
Ubuntu's Network-Manager won't connect to VPN

### ISSUE THREAD

**Issue by foormea** [hwdsl2/setup-ipsec-vpn#774]
Hi,
Thanks for this great project!
I was able to set up the GCP instance with no issue. I was able to connect to the VPN using my Android phone with no issue.
However with my Kubuntu 20.04 laptop, I cannot connect. I made this [reddit post](https://www.reddit.com/r/sysadmin/comments/g17m5u/networkmanager_and_libreswan_vpn/) that sums up the situation, before thinking about just reaching out here.
Hopefully the solution will be dead easy and can be included in your doc.
Thank you!

**Comment by hwdsl2** [comment]
@foormea Hello! The documentation does not yet have instructions for Kubuntu 20.04. The instructions for GNOME can be found here [1]. For your use case, please instead try "Configure Linux VPN clients using the command line" [2].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#linux
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#configure-linux-vpn-clients-using-the-command-line
