### ISSUE TITLE
This isn't an Issue, need support for Cisco AnyConnect

### ISSUE THREAD

**Issue by bhatti4says** [hwdsl2/setup-ipsec-vpn#775]
Hi everyone, I was just wondering if there's any possibility we can make it work this VPN Setup with Cisco AnyConnect Mobility Client?? Appreciate your help.

**Comment by letoams** [comment]
The IPsec part should already work.
The SSL-VPN part of the anyconnect client is a while new different protocol. There isn’t a compelling reason to support it (especially with IKE/TCP support that has finally landed in the Linux kernel, which libreswan will support soon.

Paul

**Comment by hwdsl2** [comment]
Thanks @letoams!

@bhatti4says Cisco AnyConnect Mobility Client uses SSL VPN which is different than IPsec. Therefore it cannot be used with IPsec VPN servers.
