### ISSUE TITLE
Site to Site interconnect devices

### ISSUE THREAD

**Issue by PedroPCardoso** [hwdsl2/setup-ipsec-vpn#777]
I would like to create a site to site connection my settings are:

THE:
conn mytunnel2
    ike = aes256-sha256; modp1536
    phase2alg = aes256-sha256; modp1536
    left =% defaultroute
    leftid = 172.107.45.245
    leftsubnet = 192.168.44.0 / 24
    right = 172.107.46.211
    rightsubnet = 192.168.42.0 / 24
    authby = secret
    # use auto = start when done testing the tunnel
    auto = start

B:
conn mytunnel2
    ike = aes256-sha256; modp1536
    phase2alg = aes256-sha256; modp1536
    left =% defaultroute
    leftid = 172.107.46.211
    leftsubnet = 192.168.42.0 / 24
    right = 172.107.45.245
    rightsubnet = 192.168.44.0 / 24
    authby = secret
    # use auto = start when done testing the tunnel
    auto = start

Secrets A

172.107.46.211 172.107.45.245: PSK "*****"

% any% any: PSK "*****"

Secrets B
172.107.45.245 172.107.46.211: PSK "*****"

% any% any: PSK "*****"

I connected a device to each of the servers, and the connections were created, I would like to ping / connect the device from the other server, for example:
Server A 192.168.42.1
server device A 192.168.42.10

Server B ping 192.168.42.10

another problem was that when running the script I changed the one on server B the ip range to 192.168.44. instead of 42, but when I put this configuration in ipsec.conf I can't even ping .1, when I comment:
# leftsubnet = 192.168.44.0 / 24
and
# rightsubnet = 192.168.44.0 / 24
I can ping 192.168.42.1, using Server B

**Comment by hwdsl2** [comment]
@PedroPCardoso Hello! For site-to-site VPN questions (outside the scope of this repo), please refer to the Libreswan docs [1], or try the Libreswan or strongSwan users mailing lists [2][3].

[1] https://libreswan.org/wiki/
[2] https://lists.libreswan.org/mailman/listinfo/swan
[3] https://lists.strongswan.org/mailman/listinfo/users
