### ISSUE TITLE
连接VPN成功，但无法通过VPN访问网络？

### ISSUE THREAD

**Issue by andrewlsa** [hwdsl2/setup-ipsec-vpn#778]
谢谢你，在我的EC2上运行得很好。
但我有个问题，我在办公室ubuntu 18上运行了这个脚本搭建了服务器，通过路由器2（带代理）连接到主路由1（带公网IP）。
当客户端连接路由1，VPN正常，访问网络通过路由2返回数据。
但是当我从家里网络访问办公室公网IP（路由1已把500，4500映射到服务器），连接成功，但却无法通过代理路由器上网了？
谢谢。

**Comment by haozes** [comment]
same issue,  连接正常无法上网。导致无法FQ，之前还好好的

**Comment by andrewlsa** [comment]
> same issue, 连接正常无法上网。导致无法FQ，之前还好好的

当客户端跟服务器在同一个路由下，一切正常。可以访问网络。
我看了很多iptables的设置，似乎并没有找到原因。

**Comment by Lunkeqing** [comment]
我的苹果设备可以正常通信，但是安卓出现这种情况，也就是能连接上，但不能通过VPN访问网络

**Comment by zjsth92** [comment]
可能是DNS的问题，试下用阿里的DNS

**Comment by andrewlsa** [comment]
@zjsth92 
iptables -nvL FORWARD无数据包，INPUT正常。不知道是不是iptables里面设置要修改？

**Comment by hwdsl2** [comment]
@andrewlsa 这个可能是因为IPTables规则限制。请尝试这个解决方案 [1]。

@Lunkeqing 试一下这些步骤 [2]。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E8%AE%BF%E9%97%AE-vpn-%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%9A%84%E7%BD%91%E6%AE%B5
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#android-6-%E5%92%8C-7

**Comment by andrewlsa** [comment]
@hwdsl2 然而并没有成功
ipsec whack --trafficstatus 数据包仍然为0

**Comment by free-150** [comment]
同样有这问题，安卓可以连上ikev2，但是无法上网。ios却可以
