### ISSUE TITLE
Improve throughput

### ISSUE THREAD

**Issue by nodesocket** [hwdsl2/setup-ipsec-vpn#78]
Any tips/tricks for improving throughput? I'm running a Raspberry Pi 3 Model B on Raspbian Jessie and only seeing around 5Mbps up and down via [speedtest-cli](https://github.com/sivel/speedtest-cli) using **L2TP**. Looking at the load, memory, and cpu on the pi only seeing around 20% cpu utilization, so it is not maxing out the hardware.

**Comment by hwdsl2** [comment]
@nodesocket Please connect using IPsec/XAuth ("Cisco IPsec") [1]. It has lower overhead. In my speed tests IPsec/XAuth achieved almost double the throughput compared to IPsec/L2TP.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md

**Comment by nodesocket** [comment]
I migrated to Cisco IPsec, but still seeing a maximum of 10Mbps up and down, even though CPU and memory utilization is very low on the Raspbian Pi 3 Model B.

Perhaps we can try tuning some configurations?

**Comment by hwdsl2** [comment]
@nodesocket What result do you get if you do a speedtest on the Raspberry Pi itself? I think the Raspberry Pi's network connection is most likely where the bottleneck is. In my tests the Cisco IPsec mode has similar throughput as OpenVPN. The configurations have already been tuned via `sysctl.conf` in the script to optimize speed.

**Comment by nodesocket** [comment]
When I run speedtest-cli on the RPi directly I get 90Mbps. I am not using WiFi, plugged directly into ethernet. Using Cisco IPSec, can't get more than 10Mbps.

**Comment by hwdsl2** [comment]
@nodesocket There could be other reasons. For example:

1. The bottleneck is on the link between your VPN client and your Raspberry Pi server.
2. When you do a speedtest on the RPi, it uses a different test server compared to that on the VPN client.
3. There is overhead caused by encryption/decryption and IPsec encapsulation which affects throughput.

You may want to try OpenVPN [1] and see if it can achieve higher throughput, and/or seek help from VPN experts on the Libreswan/Strongswan mailing lists [2][3].

[1] https://github.com/Nyr/openvpn-install
[2] https://lists.libreswan.org/mailman/listinfo/swan
[3] https://lists.strongswan.org/mailman/listinfo/users

**Comment by nodesocket** [comment]
Thanks for the resources, just curious when using Cisco IPSEC and [speedtest-cli](https://github.com/sivel/speedtest-cli), what are you able  to get? I'm tempted to create a VPN server droplet on DigitalOcean and compare VPN speeds against my RPi 3.

**Comment by hwdsl2** [comment]
@nodesocket Sorry I have not tested using Cisco IPSEC and speedtest-cli. I have only tested on my Android 5.x smartphone using the Speedtest app.

**Comment by nodesocket** [comment]
Just setup a DigitalOcean droplet 512MB and was able to get over 120Mbps download through Cisco IPSec using macOS. So the problem is either bottlenecked with Raspberry Pi 3 or my iPhone VPN Client.

I'm a bit surprised because I would have a thought a Raspberry Pi 3 would not be that much slower than a 512MB droplet.

**Comment by nodesocket** [comment]
@hwdsl2 wanted to let you know that I figured out the issue why my Pi 3 was only able to max out at 10Mbps. I am super embarrassed because it makes so much sense now.

My ISP connection coming in get's around 178Mbps down 10Mbps up _(capped from ISP)_. I incorrectly assumed when I VPNd, I would see close to those numbers as well. The exception is when you VPN you use both up and down, so it's going to be limited on both up and down to the slowest. Thus I see 10Mbps down and up when VPNing.

**Comment by hwdsl2** [comment]
@nodesocket Thanks for sharing your insights with us!
