### ISSUE TITLE
tunelling specific traffic

### ISSUE THREAD

**Issue by rodmsmendes** [hwdsl2/setup-ipsec-vpn#785]
Is it possible to configure the server to use the VPN only for a specific range of IPs or hostnames?

**Comment by letoams** [comment]
On Tue, 28 Apr 2020, Rodolfo Mendes wrote:

> Is it possible to configure the server to use the VPN only for a specific range of IPs or hostnames?

You mean like:

 	leftusbnet=10.0.1.0/24
 	rightsubnet=192.168.10.0/24

or for multiple ones:

 	leftsubnts={10.0.1.0/24,10.0.2.0/24}
 	rightsubnts={192.168.0.0/24,192.168.2.0/24}


Or do you mean a Remote Access VPN where you get an IP address, and then
only use it for some remote subnets? Currently, we only support either
0.0.0.0/0 or one smaller subnet, eg:

 	leftsubnet=0.0.0.0/0
 	#leftsubnet=192.168.0.0/24
 	rightaddresspool=10.0.1.1-10.0.1.250

For full configuration examples, see https://libreswan.org/wiki/Configuration_examples

Paul

**Comment by hwdsl2** [comment]
@rodmsmendes For tunneling a specific subnet, as Paul mentioned, you may set the `leftsubnet` in `/etc/ipsec.conf` under section "conn xauth-psk", then restart the IPsec service. Refer to #570.
