### ISSUE TITLE
Allow manual IP

### ISSUE THREAD

**Issue by techroy23** [hwdsl2/setup-ipsec-vpn#787]
add option to edit these setting while installling 

L2TP_NET=${VPN_L2TP_NET:-'192.168.42.0/24'}
L2TP_LOCAL=${VPN_L2TP_LOCAL:-'192.168.42.1'}
L2TP_POOL=${VPN_L2TP_POOL:-'192.168.42.10-192.168.42.250'}
XAUTH_NET=${VPN_XAUTH_NET:-'192.168.43.0/24'}
XAUTH_POOL=${VPN_XAUTH_POOL:-'192.168.43.10-192.168.43.250'}

**Comment by hwdsl2** [comment]
@techroy23 Hello! You can pass these parameters when running the VPN setup script. For example...
```
VPN_IPSEC_PSK='your_ipsec_pre_shared_key' \
VPN_USER='your_vpn_username' \
VPN_PASSWORD='your_vpn_password' \
VPN_L2TP_NET='192.168.44.0/24' \
VPN_L2TP_LOCAL='192.168.44.1' \
VPN_L2TP_POOL='192.168.44.10-192.168.44.250' \
sh vpnsetup.sh
```
