### ISSUE TITLE
Need help enabling PAP authenication without preshared key

### ISSUE THREAD

**Issue by r8420** [hwdsl2/setup-ipsec-vpn#789]
Hello, The VPN server is working great but I need to configure my router and it doesn't allow me to set a shared secret. The config files have to be changed but I don't have the required knowledge to get it working. I searched google but can't find a solution. I think setting up a user-level authentication with the PAP authentication protocol may solve the problem but I will need some help to do that.

**Comment by hwdsl2** [comment]
@r8420 Hello! Using L2TP without IPsec is not supported, because network traffic is not encrypted at all in this mode, which defeats the purpose of using a VPN.
