### ISSUE TITLE
error: network interface

### ISSUE THREAD

**Issue by marioandluigi878** [hwdsl2/setup-ipsec-vpn#79]
```
Error: Network interface 'eth0' is not available.

DO NOT RUN THIS SCRIPT ON YOUR PC OR MAC!

If running on a server, you may fix this error by first
finding the active network interface:
route | grep '^default' | grep -o '[^ ]*$'

Then set this variable and re-run the script:
export VPN_IFACE="YOUR_INTERFACE" 
```

after running the above command I get this
enp2s0
so I go to replace it and after replacing it I get this

```
**Error: Network interface 'eth0' is not available.

DO NOT RUN THIS SCRIPT ON YOUR PC OR MAC!

If running on a server, you may fix this error by first
finding the active network interface:
route | grep '^default' | grep -o '[^ ]*$'

Then set this variable and re-run the script:
export VPN_IFACE="enp2s0" 
```

What the heck? Can I get some help for this

**Comment by marioandluigi878** [comment]
also I guess while this is open how do I have the iptables not block other ports I would like to use like port 80, 443, 9091, 10000 thanks....

**Comment by hwdsl2** [comment]
@marioandluigi878 Please try the following (if logged in as `root`):
```
export VPN_IFACE="enp2s0"
sh vpnsetup.sh
```

Alternatively, you may use `sudo`:
```
sudo VPN_IFACE="enp2s0" sh vpnsetup.sh
```

To open additional ports on the server, after VPN setup please edit `/etc/iptables.rules` and/or `/etc/iptables/rules.v4` (if it exists). Add your new rules immediately below this line: `-A INPUT -p tcp --dport 22 -j ACCEPT`. For example:

```
-A INPUT -p tcp --dport 80 -j ACCEPT
-A INPUT -p tcp --dport 443 -j ACCEPT
-A INPUT -p tcp --dport 9091 -j ACCEPT
-A INPUT -p tcp --dport 10000 -j ACCEPT
```

Save the file and apply the new IPTables rules:

`iptables-restore < /etc/iptables.rules`
`service fail2ban restart`

**Comment by marioandluigi878** [comment]
$ iptables-restore < /etc/iptables.rules
iptables-restore v1.6.0: iptables-restore: unable to initialize table 'filter'

Error occurred at line: 2
Try `iptables-restore -h' or 'iptables-restore --help' for more information.

**Comment by hwdsl2** [comment]
@marioandluigi878 Did you edit `/etc/iptables.rules` on a Windows computer? This error could be due to line ending issues [1], or it could be caused by your VPS provider using a custom kernel that does not support IPTables [2].

To fix [1], run the following commands:
```
apt-get update
apt-get install tofrodos
fromdos /etc/iptables.rules
iptables-restore < /etc/iptables.rules
service fail2ban restart
```

To fix [2], please contact your VPS or server provider.

[1] https://askubuntu.com/questions/551718/iptables-unable-to-initialize-table-filter
[2] https://askubuntu.com/questions/28215/how-can-i-fix-the-iptables-error-message-unable-to-initialize-table-filter

**Comment by marioandluigi878** [comment]
it worked thanks now i just need to test to see if i can connect to the web server

**Comment by marioandluigi878** [comment]
now one more thing before this gets closed how do I add other vpn users

**Comment by hwdsl2** [comment]
@marioandluigi878 See [1].

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users.md

**Comment by marioandluigi878** [comment]
that was fast....

**Comment by marioandluigi878** [comment]
anyways thanks
