### ISSUE TITLE
connecting to VPN through Cisco IPsec is not working on IPhone XS with iOS 13.4.1

### ISSUE THREAD

**Issue by zhou0031** [hwdsl2/setup-ipsec-vpn#790]
Hello hwdsl2. 
I am attempting to connect to a VPN server using Cisco IPsec that is built in IPhone XS because you mentioned that IPsec/L2TP has a limitation.  

I have done the following: 

1. toggled back and forth the variable, "sha2-truncbug" in "/etc/ipsec.confi" 
2. Entered all credentials correctly. (tried 3 times) 
3. Restarted the IPsec server. 

Result:
The result is "vpn server did not respond." Same credentials working fine using L2TP so I know I entered them correctly.  I have uploaded 3 images hoping they could help you solve the issue. 

Much appreciated!!! 

![微信图片_20200506110509](https://user-images.githubusercontent.com/480826/81142777-1603a400-8fa3-11ea-8c1d-686d2c113848.jpg)
![微信图片_20200506110520](https://user-images.githubusercontent.com/480826/81142784-18fe9480-8fa3-11ea-99c0-d048ee2c4604.jpg)
![微信图片_20200506135102](https://user-images.githubusercontent.com/480826/81142788-1a2fc180-8fa3-11ea-8116-8134bee9a8e9.jpg)

**Comment by hwdsl2** [comment]
@zhou0031 Hello! Please try connecting the VPN again, then go to your VPN server and check the Libreswan and xl2tpd logs for errors [1]. Post the logs here with sensitive info redacted.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#additional-steps

**Comment by zhou0031** [comment]
hi, would you please tell me the paths to these files. I am having a bit trouble locating them

**Comment by hwdsl2** [comment]
@zhou0031 Try re-connecting the VPN, then run these commands on your VPN server to check the recent logs for errors:
```
# Ubuntu & Debian
grep pluto /var/log/auth.log
grep xl2tpd /var/log/syslog

# CentOS & RHEL
grep pluto /var/log/secure
grep xl2tpd /var/log/messages
```

**Comment by zhou0031** [comment]
@hwdsl2 hello, as per you described. I have attached 2 photos. Sorry,  I took a photo shot. They are a bit shabby, but the logs are clear. I have blanked out sensitive info. ![image](https://user-images.githubusercontent.com/480826/81367374-a961e400-911f-11ea-978c-bd379358a4f5.jpeg)![image](https://user-images.githubusercontent.com/480826/81367383-ae269800-911f-11ea-8ade-709c8f8ff113.jpeg)

**Comment by zhou0031** [comment]
@hwdsl2 Hello, as per your description, I have managed to grade two photos with sensitive info blanked out. Please have a look. Cisco/IPsec sometimes work, others don’t.

Thanks
![image](https://user-images.githubusercontent.com/480826/81367486-fba30500-911f-11ea-8a70-8a78cf103029.jpeg)
![image](https://user-images.githubusercontent.com/480826/81367505-065d9a00-9120-11ea-8a55-80c648157c85.jpeg)

**Comment by zhou0031** [comment]
@hwdsl2 hello. Sorry for the shabby photos. I will post logs in txt format here

**Comment by hwdsl2** [comment]
@zhou0031 Thank you for the logs. Your logs show that:
1. You were trying to connect using IPsec/XAuth ("Cisco IPsec") mode immediately after previous connection (which used IPsec/L2TP mode). This can result in the errors as shown in the logs in your first photo. To fix, either wait a few minutes, or restart the IPsec service on the VPN server with `sudo service ipsec restart`, before switching to a different connection mode. The logs do not seem to show other errors beside this.
2. In the logs from your second photo, the L2TP part of the connection established successfully. However, it looks like your VPN client terminated the connection after a few seconds. The reason is not clear.

Let me know if you have more logs to share, that could help identify the issue further.

**Comment by hwdsl2** [comment]
@zhou0031 Reading your first comment in this thread, it looks like IPsec/L2TP mode works fine, but IPsec/XAuth ("Cisco IPsec") mode was having issues. Please see my previous comment, item (1), for how to fix that. Further logs are not required and I'll now close this issue.

**Comment by zhou0031** [comment]
Thanks Lin!
You are amazing
