### ISSUE TITLE
iOS 13与macOS 10.15无法连接VPN

### ISSUE THREAD

**Issue by HLTangbinbin** [hwdsl2/setup-ipsec-vpn#791]
19年的实例可以用，账号要到期了，换了新账号，同样的方式配置新实例，可以ping通，但是怎么都无法连接上，很郁闷，，，而且参照问题排查：19年搭建的配置中sha2-truncbug=yes可以连接使用，今年刚刚搭建的配置sha2-truncbug=no怎么都连接不上。。。。

**Comment by hwdsl2** [comment]
@HLTangbinbin 你好！编辑 `/etc/ipsec.conf`，将 `sha2-truncbug=no` 改为 `sha2-truncbug=yes`，重启 IPsec 服务 `sudo service ipsec restart`，然后重试连接？

**Comment by hwdsl2** [comment]
@HLTangbinbin 对于 iOS 13 和 macOS 10.15 系统，需要保持设置 `sha2-truncbug=no` 才能连接。

**Comment by HLTangbinbin** [comment]
不管设置为yes或者no都还是无法连接，按照故障排查都尝试了下，无法定位到问题
