### ISSUE TITLE
The L2TP-VPN server did not respond. 

### ISSUE THREAD

**Issue by chris-infstones** [hwdsl2/setup-ipsec-vpn#793]
My mac sometimes could not connect to vpn and it shows the error bellow.

Error message:
The L2TP-VPN server did not respond. Try reconnecting. If the problem continues, verify your settings and contact your Administrator.

Then I check the /var/log/auth.log. 

responding to Main Mode from unknown peer
STATE_MAIN_R1: sent MR1, expecting MI2
retransmitting in response to duplicate packet; already STATE_MAIN_R1
deleting incomplete state after 60.000 seconds
deleting state (STATE_MAIN_R1) aged 60.009s and NOT sending notification

**Comment by hwdsl2** [comment]
@chris-infstones Hello! From your logs, it looks like there's some network issue between your VPN client and VPN server. And as you described, the issue occurs inconsistently (sometimes you can connect). Therefore it's most likely not an issue with the VPN server itself.

**Comment by chris-infstones** [comment]
您好，我不太明白，我在服务器上面监控到的日志如上，说明网络应该是没有问题的，因为我是在点击连接的同时监控的日志，有可能是网络不稳定导致连接断开，但是再次连接就连接不上了，需要好久之后再连接才能连得上，日志我没有太看明白retransmitting in response to duplicate packet; already STATE_MAIN_R1 貌似是重复了？会不会是因为异常断开导致无法再次连接？

**Comment by hwdsl2** [comment]
@chris-infstones 你好！这个日志 "retransmitting in response to duplicate packet; already STATE_MAIN_R1" 说明可能是客户端和服务器之间的网络不稳定，导致数据重复传输。这也包括比如 GFW 干扰导致的连接问题。

**Comment by derekmao2019** [comment]
> 



> @chris-infstones 你好！这个日志 "retransmitting in response to duplicate packet; already STATE_MAIN_R1" 说明可能是客户端和服务器之间的网络不稳定，导致数据重复传输。这也包括比如 GFW 干扰导致的连接问题。

确实如此，干扰导致。
