### ISSUE TITLE
could not connect to the vpn on win10 however it works well on mac and iphone

### ISSUE THREAD

**Issue by TUTUBIG** [hwdsl2/setup-ipsec-vpn#794]

**Comment by hwdsl2** [comment]
@TUTUBIG Hello! The VPN was tested on Windows 10 and working fine. Please see [1] for a required one-time registry change before connecting.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#windows-error-809

**Comment by TUTUBIG** [comment]
sorry about not mention that . and i have soled the problem. thanks for helping
