### ISSUE TITLE
已拒绝远程连接，因为未识别出你提供的用户名和密码组合，或在远程访问服务器上禁止使用选定的身份验证协议

### ISSUE THREAD

**Issue by CnybTseng** [hwdsl2/setup-ipsec-vpn#797]
win10出现的上述问题

**Comment by hwdsl2** [comment]
@CnybTseng 你好！该错误说明你的 Win10 VPN 客户端配置时输入的用户名和密码有错误。请按照说明 [1] 重新配置客户端。另参见该文档的故障排除部分。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md
