### ISSUE TITLE
我在阿里云和亚马逊云上使用这个的时候，发现主机重启之后会提示维护模式，提示需要crtl+D继续，如果输入ctrl+d，会提示一个报错，sulogin catnot read /dev/tty1 ，这个是为什么啊

### ISSUE THREAD

**Issue by lebashupian** [hwdsl2/setup-ipsec-vpn#798]
我在阿里云和亚马逊云上使用这个的时候，发现主机重启之后会提示维护模式，提示需要crtl+D继续，如果输入ctrl+d，会提示一个报错，sulogin catnot read /dev/tty1 ，这个是为什么啊

**Comment by hwdsl2** [comment]
@lebashupian 你好！在测试中没有遇到过此问题。应该不是 VPN 脚本的原因，是你的服务器的问题。请自行搜索，可能与 `/etc/fstab` 有关 [1]。

[1] https://askubuntu.com/questions/797964/sulogin-cannot-read-dev-tty1-permission-denied
