### ISSUE TITLE
Cisco VPN router

### ISSUE THREAD

**Issue by zhou0031** [hwdsl2/setup-ipsec-vpn#799]
@hwdsl2 Dear Lin. Is it possible to connect to VPN server using a Cisco VPN router ?because I have seen it offers IPSec connection as well.

**Comment by hwdsl2** [comment]
@zhou0031 Hello! If your Cisco VPN router has support for IPsec/L2TP, you can give it a try. I am not familiar with the configuration, please refer to the user manual of your router for instructions.
