### ISSUE TITLE
How do you change the IP range?

### ISSUE THREAD

**Issue by ssamjh** [hwdsl2/setup-ipsec-vpn#8]
I want to change the IP range that the server uses but whenever I try the server will not accept any connections.

**Comment by hwdsl2** [comment]
1. Edit /etc/xl2tpd/xl2tpd.conf and replace these two lines:

```
ip range = 192.168.42.10-192.168.42.250
local ip = 192.168.42.1
```

with your desired new range. For example:

```
ip range = 10.1.1.10-10.1.1.250
local ip = 10.1.1.1
```

2. Edit /etc/iptables.rules and find this line:

```
-A POSTROUTING -s 192.168.42.0/24 -o eth+ -j SNAT --to-source ...
```

and replace `192.168.42.0/24` with your desired CIDR, e.g. `10.1.1.0/24`.

3. Edit /etc/ipsec.conf and replace `%v4:!192.168.42.0/24` with e.g.  `%v4:!10.1.1.0/24`.

4. Run these commands to let them take effect:

```
service ipsec restart
service xl2tpd restart
iptables-restore < /etc/iptables.rules
```
