### ISSUE TITLE
A Really stupid Question

### ISSUE THREAD

**Issue by marioandluigi878** [hwdsl2/setup-ipsec-vpn#80]
If I install another type of server on here like openvpn will it bother with l2tp im not sure if this script with screw with the vpn https://github.com/Nyr/openvpn-install/blob/master/openvpn-install.sh

**Comment by hwdsl2** [comment]
@marioandluigi878 Don't worry, you can install OpenVPN on your server using Nyr's script, and it should not affect your existing IPsec VPN server.
