### ISSUE TITLE
阿里云服务器，可以VPN链接成功，无法访问外网

### ISSUE THREAD

**Issue by shanxueyi** [hwdsl2/setup-ipsec-vpn#801]
阿里云的服务器关闭firewalld防火墙后可以链接成功，但是关闭firewalld后无法访问外网。
VPN内使用的是iptables防火墙，能出一个针对firewalld防火墙的版本吗？

**Comment by cuijianzhe** [comment]
其实就是少一个NAT的功能

**Comment by hwdsl2** [comment]
@shanxueyi 你好！感谢你的建议。目前没有针对firewalld防火墙的版本。对于CentOS系统，VPN安装脚本尝试在关闭firewalld前添加必要的IPTables规则 [1]，然后与已有的规则一起保存。所以如果你在运行脚本之后不重新手动打开firewalld的话，应该是可以正常连接的。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/vpnsetup_centos.sh#L377

**Comment by hwdsl2** [comment]
@shanxueyi 脚本已更新，以解决 VPN 安装时在 CentOS 8 下不能保存已有的 firewalld 规则的问题。更新后在关闭 firewalld 之前会保存已有的规则到 nftables。如果你使用的是 CentOS 8，可以在一个新服务器上再试一下安装 VPN。
