### ISSUE TITLE
l2tp连接尝试失败 因为安全层在初始化与远程计算机的协商时遇到一个错误

### ISSUE THREAD

**Issue by CnybTseng** [hwdsl2/setup-ipsec-vpn#802]
l2tp连接尝试失败 因为安全层在初始化与远程计算机的协商时遇到一个错误

**Comment by hwdsl2** [comment]
@CnybTseng 请参见：
https://documentation.meraki.com/MX/Client_VPN/Troubleshooting_Client_VPN#Windows_Error_789
https://docs.microsoft.com/en-us/archive/blogs/rrasblog/troubleshooting-common-vpn-related-errors
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4

**Comment by sunfeilong** [comment]
@CnybTseng 同样的问题，之前可以使用，最近几天不能使用了。解决没有？

**Comment by luoyu124578** [comment]
@hwdsl2  无效，还是连接不上
