### ISSUE TITLE
请问下，如何查看当前连接的用户，比如多用户使用的话

### ISSUE THREAD

**Issue by cuijianzhe** [hwdsl2/setup-ipsec-vpn#803]
分析日志只看到这两块：
1）服务端的鉴权日志在 /var/log/secure
2）客户端连接的日志在 /var/log/messages

但是看不到当前用户连接信息。有这些日志输出吗？还是需要配置其他功能

**Comment by analyzesm** [comment]
你的多用户，使用 IPSec/XAuth 模式吗？

**Comment by cuijianzhe** [comment]
就是创建过个用户共同使用，想知道哪些人是在线的？

**Comment by cuijianzhe** [comment]
> 你的多用户，使用 IPSec/XAuth 模式吗？

就是创建过个用户共同使用，想知道哪些人是在线的？

**Comment by cuijianzhe** [comment]
> 你的多用户，使用 IPSec/XAuth 模式吗？

使用的是L2TP/IPSEC PSK模式

**Comment by hwdsl2** [comment]
@cuijianzhe 请参见 #166。需要启用 xl2tpd debug 选项并且运行脚本查看连接信息。另外，如果是 IPsec/XAuth ("Cisco IPsec") 模式的话，可以尝试 `ipsec status | grep username`
