### ISSUE TITLE
能连美国却不能连香港的

### ISSUE THREAD

**Issue by 873217486** [hwdsl2/setup-ipsec-vpn#805]
我在美国、香港各搭一个vpn
我的电脑只能连美国的vpn，香港的有时候能连，有时候连不上。
iphone手机两个都能连，没有连不上的情况。
同一办公室的也都能连上。
不知道什么原因，也不知道该如何排查问题，有人指教一下吗？

**Comment by hwdsl2** [comment]
@873217486 你好！如果是有时候能连，有时候连不上，应该不是VPN服务器本身的问题。有可能是被GFW干扰导致的。另外，如果你在IPsec/L2TP和IPsec/XAuth ("Cisco IPsec") 模式之间切换的话，可能需要等几分钟再连。因为有些客户端断开时不删除VPN状态，导致服务器无法立即切换模式。
