### ISSUE TITLE
服务器重新拨号后，客户端就连不上了。。

### ISSUE THREAD

**Issue by liufitch** [hwdsl2/setup-ipsec-vpn#806]
我的是一台拨号vps, 使用了ddns，但是安装之后 第一次客户端都可以连接，重新拨号后就连不上了。
首先我排除了ddns的原因，因为我改成pptp，不管怎么拨号就是可行的。
所以我想知道我需要改哪些设置?

**Comment by hwdsl2** [comment]
@liufitch 你好！我对拨号VPS不熟悉。对于VPN服务器本身来讲，如果外部IP改变的话，是不影响客户端使用ddns域名再次连接的。你可以试试重启服务器或者重启服务：
```
sudo service ipsec restart
sudo service xl2tpd restart
```
