### ISSUE TITLE
请问这两天是不是全都不能访问了？

### ISSUE THREAD

**Issue by Remember2018** [hwdsl2/setup-ipsec-vpn#807]
从昨天开始，无论VPN搭建的还是V2ray搭建的，都不能访问了。但是用http://ping.chinaz.com/又能访问到服务器ip地址，显示没有被墙。用ssh也能登录到那个服务器。

不知道各位那里是什么情况呢？

**Comment by hwdsl2** [comment]
@Remember2018 你好！检查服务器的日志 [1]，如果尝试连接后没有新的日志，或者无法成功连接并出现 `retransmission` 之类的错误，则很可能是被屏蔽了。另外，其它解决方案你可以尝试一下，
比如 Shadowsocks [2]。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E9%A2%9D%E5%A4%96%E7%9A%84%E6%AD%A5%E9%AA%A4
[2] https://shadowsocks.org

**Comment by Remember2018** [comment]
@hwdsl2 您好！非常感谢您的回复！连接后出现的错误如下，我用ping可以ping通，但是用pathping这个服务器地址，只能路由到192.168.1.1，后面的路由就没有了。照理说，如果是被封了，应该也ping不通呀。不知道是不是我昨天装过一次nmap(https://nmap.org/)的原因。因为想要查找局域网某台连接的电脑的ip地址，就装了一下nmap就行扫描。装nmap好像会装很多与网络相关的一些组件，不知道是不是这些组件对电脑设置或者注册表进行了更改导致vpn连接失败。

![5E496653-0C67-465c-90B5-E3513AB2234B](https://user-images.githubusercontent.com/43327429/83663997-fdb39300-a5fb-11ea-9b43-0990935a2b2d.png)

**Comment by Remember2018** [comment]
@hwdsl2 刚试了下android手机连接vpn，没问题。说明是这个电脑设置的问题了。很可能是装了nmap导致的设置发生了改变。我已经卸载了nmap，还是不能连接。我再找找原因。

**Comment by hwdsl2** [comment]
@Remember2018 试一下重新修改注册表并重启 [1]。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#windows-%E9%94%99%E8%AF%AF-809

**Comment by Remember2018** [comment]
@hwdsl2 昨天晚上试了好几次，都不行。过程中发现防火墙的域策略开启了，我记得防火墙是全部关闭的。不知道是不是nmap修改的。然后我把防火墙都关了。还是不性，然后按照您上面的建议，下载了那个注册表修改文件，执行了，重启，还是不行。

今天早上起来，发现又能连接了。。。

**Comment by Remember2018** [comment]
今天一天都连不上。。。就早上连了一小会。如果能连上，每次只能连不到一分钟，然后就断开了。

很奇怪the wall到底是个什么机制，如果要禁那个ip，直接拉入黑名单不就行了？为什么要让连一分钟，然后又禁掉？背后到底是个什么算法呢？

今天一天打开很多国外网站都很慢

**Comment by Remember2018** [comment]
现在一切恢复正常了，看来the wall控制的级别是可变的
