### ISSUE TITLE
ipsec xauth-psk split tunnel on ios 13.5

### ISSUE THREAD

**Issue by iamomen** [hwdsl2/setup-ipsec-vpn#809]
i have been trying for solve this issue for couple of days now i have tried normal configuration( leftsubnet=0.0.0.0/0) and the VPN works but when i set leftsubnet to anything other than 0.0.0.0 vpn breaks and does not  connect

device : MAC OS LATEST
device : ios 13.5.1

from the logs it gets stuck on "xauth-psk"[2] 2.51.35.111 #1: STATE_MODE_CFG_R1: ModeCfg Set sent, expecting Ack {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA2_256 group=MODP2048}

then disconnects and i get "Negotiation with VPN server failed" on both mac and ios i have tried everything and it does not work.

seems like apple devcies try to push 0.0.0.0 and does not agree with other subnets mabe 

i even added more debuging using ipsec whack --debug-all

too see if there is anything alot of logs didnt make alot of sense why IOS isnt accepting anything other than 0.0.0.0

here is my ipsec.conf

version 2.0

config setup
  virtual-private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:!10.0.0.0/12,%v4:!10.16.1.0/12
  protostack=netkey
  interfaces=%defaultroute
  uniqueids=no

conn shared
  ikev2=never
  left=%defaultroute
  leftid=165.227.81.0
  right=%any
  encapsulation=yes
  authby=secret
  pfs=no
  rekey=no
  keyingtries=5
  dpddelay=30 
  dpdtimeout=120
  dpdaction=clear
  ike=aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1,aes256-sha2;modp1024,aes128- sha1;modp1024  << -- tried changing didnt work
  #ike=aes128-sha2,aes256-sha1,aes128-sha1;modp1024,aes128-sha1;modp1024  << -- tried changing didnt work
  phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes256-sha2_512,aes128-sha2,aes256-sha2
  sha2-truncbug=no <<< tried both

conn l2tp-psk
  auto=add
  leftprotoport=17/1701
  rightprotoport=17/%any
  type=transport
  phase2=esp
  also=shared

conn xauth-psk
  auto=add
  #aggrmode=yes
  leftsubnet=172.217.7.14/32 <--- could be anything but not 0.0.0.0
  #leftsubnet=0.0.0.0/0
  rightaddresspool=10.16.0.1-10.31.255.254
  modecfgdns=8.8.8.8 <---- my dns server this is an example
  leftxauthserver=yes
  rightxauthclient=yes
  leftmodecfgserver=yes
  rightmodecfgclient=yes
  modecfgpull=yes
  xauthby=file
  ike-frag=yes
  cisco-unity=yes
  also=shared

some logs from my IOS device

Jun 5 16:12:27 iPhone racoon[7088] <Notice>: ISAKMP-SA established spi:74c0a2282981de81:6c68daed3aa00fbf
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: IPSec Phase 1 established (Initiated by me).
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: IKE packet received from peer... rescheduling send_r_u.
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: MODE_CFG packet
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: Configuration exchange type mode config REQUEST
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: sending vpn_control xauth need info status
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: IPSec Extended Authentication requested.
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: received xauth info command vpn control socket.
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: New Phase 2
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: state changed to: IKEv1 info
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: MODE_CFG packet to send
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: sendto mode config attr.
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: IPSec Extended Authentication sent.
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: MODE_CFG packet
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: Configuration exchange type mode config SET
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: IPSec Extended Authentication Passed.
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: Sending MODE_CFG ACK
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: New Phase 2
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: state changed to: IKEv1 info
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: MODE_CFG packet to send
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: sendto mode config attr.
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: Sending MODE_CFG REQUEST
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: New Phase 2
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: state changed to: IKEv1 info
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: MODE_CFG packet to send
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: Resend Phase 2 packet 74c0a2282981de81:6c68daed3aa00fbf:000058af
Jun 5 16:12:27 iPhone racoon[7088] <Notice>: IPSec Network Configuration requested.
Jun 5 16:12:28 iPhone racoon[7088] <Notice>: MODE_CFG packet
Jun 5 16:12:28 iPhone racoon[7088] <Notice>: Configuration exchange type mode config REPLY
Jun 5 16:12:28 iPhone racoon[7088] <Error>: isakmp_cfg_reply invalid length of isakmp data, expected 4 actual 2
Jun 5 16:12:49 iPhone racoon[7088] <Notice>: DPD monitoring (for ALGORITHM_BLACKHOLE_DETECT) ....
Jun 5 16:12:49 iPhone racoon[7088] <Notice>: rescheduling DPD monitoring (for ALGORITHM_BLACKHOLE_DETECT) i = 0, peer 0.
Jun 5 16:12:57 iPhone nesessionmanager[123] <Notice>: IPSec Controller: racoon_timer expired
Jun 5 16:12:57 iPhone nesessionmanager[123] <Notice>: IPSec Controller: sending DISCONNECT to racoon control socket, address 0xa5e35100
Jun 5 16:12:57 iPhone racoon[7088] <Notice>: received disconnect command on vpn control socket.
Jun 5 16:12:57 iPhone racoon[7088] <Notice>: IPSec disconnecting from server x.x.x.x(just hiding my server ip)
Jun 5 16:12:57 iPhone racoon[7088] <Notice>: in ike_session_purgephXbydstaddrwop... purging Phase

**Comment by hwdsl2** [comment]
@iamomen Hello! I tested the IPsec XAuth ("Cisco IPsec") split tunneling that you mentioned, on an iOS 13 device and using the default configuration from the VPN setup scripts. After setup I tested by setting leftsubnet to a single IP (/32), and restarted the IPsec service. The connection and split tunneling both works fine. 

A few notes on your configuration:
1. `sha2-truncbug` should be set to `no`. iOS 13 devices cannot connect using IPsec XAuth mode if it's set to `yes`.
2. Do not set `aggrmode=yes`.
3. The default `ike=` line should work fine in most cases.
4. I see that you changed the VPN subnets to `10.0.0.0/12` and `10.16.0.0/12`. You must update the IPTables rules (see [1]) accordingly, in order to let the server forward VPN traffic correctly.
5. You must restart the IPsec service each time after modifying `/etc/ipsec.conf`.

[1] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes
