### ISSUE TITLE
Window 10 port closed

### ISSUE THREAD

**Issue by tamet83** [hwdsl2/setup-ipsec-vpn#811]
Hi,

i followed all your instruction for troubleshooting with windows 10 build 19041.264.

The VPN works perfectly if I use VPN Access Manager, but if I try to use the integrated VPN client in windows 10 the system gives me this error:

"Impossible to establish a connection with the remote machine. The port used for the connection has been closed".

I tried to find a solution without luck.

Can you please help me?

Thank you in advance.

**Comment by tamet83** [comment]
Hi, sorry I missed to updated you. I tried your solution but it didn't work. What worked was the setup of IKEv2 VPN and generating the .p12 file. Importing it as a System certificate solved my issue.
I couldn't solve the problem with the Ipsec protocol unfortunately.

**Comment by hwdsl2** [comment]
@tamet83 Thank you for the update, and glad to hear IKEv2 works. I plan to test further the IPsec issue on Windows 10 version 20.04, when available.
