### ISSUE TITLE
no internet connection after a few minutes connected

### ISSUE THREAD

**Issue by sukorenomw** [hwdsl2/setup-ipsec-vpn#812]
Hi, i'm wondering if there is anything wrong with the config, previously my VPN works great, but recently i found out after connected, a few mins later (5-10 mins) i got no internet connection, sometimes VPN still connected, so i had to reconnect the VPN and it works again,

here is some log i found for x2ltpd : 

```
xl2tpd[15520]: Maximum retries exceeded for tunnel xxxxx.  Closing.
xl2tpd[15520]: Terminating pppd: sending TERM signal to pid xxxxx
xl2tpd[15520]: Connection 59 closed to xxx.xxx.xxx.xxx, port xxxxx (Timeout)
xl2tpd[15520]: get_call: can't find call xxxxxx in tunnel xxxx#xxx (ref=0/0)
xl2tpd[15520]: message repeated 156 times: [ get_call: can't find call 25466 in tunnel xxxx#xxx (ref=0/0)]```

**Comment by hwdsl2** [comment]
@sukorenomw Hello! Please check the Libreswan (IPsec) logs for errors [1], in addition to the xl2tpd logs. If you encountered this issue on a mobile device (iOS/Android) after the screen goes to sleep, it may be normal [2].

Alternatively you may try the IPsec/XAuth ("Cisco IPsec") mode [3], or set up IKEv2 [4] with the new helper script. Let us know if you can resolve this.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#iosandroid-sleep-mode
[3] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md
[4] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md

**Comment by letoams** [comment]
If you can upgrade to either IKEv1 XAUTH (aka Cisco IPsec) or IKEv2, that would be best. The use of L2TP with IPsec transport mode is always fragile due to NAT.

Paul
