### ISSUE TITLE
can't connect from windows and ios

### ISSUE THREAD

**Issue by faizakbar18** [hwdsl2/setup-ipsec-vpn#815]
Hello

install on GCP with UBUNTU 18 OS, all installation was done.

i try to connect from windows 10 and IOS always can't connect. i've done add .reg file too
 IOS Fixed by restarting ipsec

and got error in windows like this
![image](https://user-images.githubusercontent.com/24320262/84811177-aae3cd80-b036-11ea-8625-2f1766d9ed20.png)

**Comment by hwdsl2** [comment]
@faizakbar18 Hello! Did you reboot your PC after applying the Windows error 809 fix [1]? Please reboot and try again.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#windows-error-809
