### ISSUE TITLE
How to enable Multicast traffic and IGMP Snooping

### ISSUE THREAD

**Issue by khunalex** [hwdsl2/setup-ipsec-vpn#824]
Hello.
I am trying to play multimedia via RTP (rtp://ip:port) through the VPN.
From the A side of the vpn where internet router in located, it plays without any issues. However from the B side of the VPN it doesnt. I wonder if the multicast packets are filtered. Is there any option to make it work through the VPN?

Thank you so much.

**Comment by letoams** [comment]
Multicast packets cannot go through the VPN unfortunately.

Paul

**Comment by hwdsl2** [comment]
Thanks @letoams for clarifying.

@khunalex It looks like multicast traffic through the VPN is not supported.
