### ISSUE TITLE
Question of user logging information

### ISSUE THREAD

**Issue by eos1d3** [hwdsl2/setup-ipsec-vpn#825]
If someone uses the VPN services (these IPSec, L2TP..)  which are not owned by him, will his IP information be logged in log file?

This is a security issue for people using the services and I can't find the log. Please advise. 

Thank you!

**Comment by letoams** [comment]
The VPN server logs the IP of the connection.
The VPN users appear to be the VPN server IP to sites they connect to through the VPN.

There is an option to not log the IPs of VPN clients in the log file (log-ip=no or something, check the man page for exact name). Logging is then filtered. But debug logs are not filtered so be sure to have plutodebug=none

Paul

**Comment by hwdsl2** [comment]
Thanks @letoams for clarifying. @eos1d3 To enable the option, please edit `/etc/ipsec.conf` on your VPN server and add these lines under the `config setup`. Must indent by two spaces. Then run `sudo service ipsec restart`. For more information, refer to [1].
```
  logip=no
  audit-log=no
```

[1] https://libreswan.org/man/ipsec.conf.5.html

**Comment by eos1d3** [comment]
Sorry for one more question. Does this config changes apply to IKEV2 too? I saw a lot user IPs from IKEV2 logs as well.

BTW, I use MacOS Mojave, when connecting with IKEV2, the certificate is always accepted. But user authorization is always rejected. Is this a known issue? If not, I will create another issue with full log.

**Comment by hwdsl2** [comment]
@eos1d3 Yes, this config change apply to IKEv2 as well. Regarding your MacOS IKEv2 issue, please attach the full log with sensitive info redacted.

**Comment by eos1d3** [comment]
@hwdsl2 Fixed /etc/ipsec.conf part. Thank a lot!

But I still can't understand rsyslog.conf change as the file is very different from my copy. Attached is the one I see in the server, what to change to omit xl2tpd logging? And is there any change required for `main.yml`?

```
# /etc/rsyslog.conf configuration file for rsyslog
#
# For more information install rsyslog-doc and see
# /usr/share/doc/rsyslog-doc/html/configuration/index.html
#
# Default logging rules can be found in /etc/rsyslog.d/50-default.conf


#################
#### MODULES ####
#################

module(load="imuxsock") # provides support for local system logging
#module(load="immark")  # provides --MARK-- message capability

# provides UDP syslog reception
#module(load="imudp")
#input(type="imudp" port="514")

# provides TCP syslog reception
#module(load="imtcp")
#input(type="imtcp" port="514")

# provides kernel logging support and enable non-kernel klog messages
module(load="imklog" permitnonkernelfacility="on")

###########################
#### GLOBAL DIRECTIVES ####
###########################

#
# Use traditional timestamp format.
# To enable high precision timestamps, comment out the following line.
#
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# Filter duplicated messages
$RepeatedMsgReduction on

#
# Set the default permissions for all log files.
#
$FileOwner syslog
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$PrivDropToUser syslog
$PrivDropToGroup syslog

#
# Where to place spool and state files
#
$WorkDirectory /var/spool/rsyslog

#
# Include all config files in /etc/rsyslog.d/
#
$IncludeConfig /etc/rsyslog.d/*.conf

```

**Comment by eos1d3** [comment]
I added these too rsyslog.conf, but I see no difference. The  vpn client IP is still there:

```
#
 # Filter out all L2TP/IPsec entries to prevent IP address logging
 #
 if $programname == 'pppd' then ~
 if $programname == 'charon' then ~
 if $programname == 'xl2tpd' then ~
 :msg, contains, "ppp" ~
```

**Comment by hwdsl2** [comment]
@eos1d3 Instead of adding to `/etc/rsyslog.conf`, create a new file e.g. `/etc/rsyslog.d/00-my-file.conf` and put those lines inside. Then run `service rsyslog restart`. See [1] for reference.

[1] https://askubuntu.com/questions/186592/how-do-i-configure-rsyslog-to-send-logs-from-a-specific-program-to-a-remote-sysl

**Comment by eos1d3** [comment]
This works! No user IP is logged in any log now.

Perfect!
