### ISSUE TITLE
win10使用shrewSoft 可以连接，但无法打开网站

### ISSUE THREAD

**Issue by Raccooon** [hwdsl2/setup-ipsec-vpn#827]
win10使用shrewSoft连接
可以连接上，但是无法打开网站
![image](https://user-images.githubusercontent.com/29443187/87246150-f0e95100-c47d-11ea-82a9-8b5731e2b664.png)

按照你的教程，尝试修复mtu问题
![image](https://user-images.githubusercontent.com/29443187/87245965-7a981f00-c47c-11ea-8752-eb9cb3021e2b.png)
照葫芦画瓢，把1380这个端口给添加上
iptables -t mangle -A FORWARD -m policy --pol ipsec --dir in \
  -p tcp -m tcp --tcp-flags SYN,RST SYN -m tcpmss --mss 1361:1536 \
  -j TCPMSS --set-mss 1380
iptables -t mangle -A FORWARD -m policy --pol ipsec --dir out \
  -p tcp -m tcp --tcp-flags SYN,RST SYN -m tcpmss --mss 1361:1536 \
  -j TCPMSS --set-mss 1380

echo 1 > /proc/sys/net/ipv4/ip_no_pmtu_disc

但是依旧不可能访问，还有可能哪里出了问题呢？

**Comment by hwdsl2** [comment]
@Raccooon 你好！Shrew Soft VPN client 较旧，并不支持 Windows 10。请尝试换用 IPsec/L2TP 模式 [1] 或者配置 IKEv2 [2]。

你的 MTU 修复命令有一点问题，最后应该使用 `--set-mss 1360`。你可以运行：
```
iptables -t mangle -F FORWARD
iptables -t mangle -A FORWARD -m policy --pol ipsec --dir in \
  -p tcp -m tcp --tcp-flags SYN,RST SYN -m tcpmss --mss 1361:1536 \
  -j TCPMSS --set-mss 1360
iptables -t mangle -A FORWARD -m policy --pol ipsec --dir out \
  -p tcp -m tcp --tcp-flags SYN,RST SYN -m tcpmss --mss 1361:1536 \
  -j TCPMSS --set-mss 1360

echo 1 > /proc/sys/net/ipv4/ip_no_pmtu_disc
```

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md
