### ISSUE TITLE
Support for networks using quad9 dns servers versus google

### ISSUE THREAD

**Issue by rklxmok** [hwdsl2/setup-ipsec-vpn#828]
I cant get to the web when using different dns servers, i am a noob at github and apologize if this has been done before. This project is amazing. I used your one click linode. Thanks for all the hard work

**Comment by hwdsl2** [comment]
@rklxmok Hello! To use a different DNS server, see important notes [1] from README:
```
Clients are set to use Google Public DNS when the VPN is active. If another DNS provider is preferred, replace 8.8.8.8 and 8.8.4.4 in both /etc/ppp/options.xl2tpd and /etc/ipsec.conf, then reboot your server. 
```

For your use case (quad9 dns):

1. Edit `/etc/ppp/options.xl2tpd` on the VPN server. Replace `8.8.8.8` with `9.9.9.9`, and replace `8.8.4.4` with `149.112.112.112`.
2. Edit `/etc/ipsec.conf` on the VPN server. Replace `8.8.8.8` with `9.9.9.9`, and replace `8.8.4.4` with `149.112.112.112`.
3. Restart services:
```
sudo service ipsec restart
sudo service xl2tpd restart
```

[1] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes
