### ISSUE TITLE
Are there any ways to control bandwidth for VPN users?

### ISSUE THREAD

**Issue by hmdai** [hwdsl2/setup-ipsec-vpn#829]
Hi,

We want to setup a VPN server and share it to some of the users. However, we don't want them to abuse the VPN for any undesired usage like BT, video streaming, etc. We are looking for ways to limit the bandwidth per each user.

Also, is it possible to limit the VPN to particular applications/websites like twitter, telegram?

**Comment by hwdsl2** [comment]
@hmdai Hello! These features are not supported, and are outside the scope of this project.
