### ISSUE TITLE
请问这个有人数限制吗,多余几个人会不稳定,有这个说法吗啊

### ISSUE THREAD

**Issue by lebashupian** [hwdsl2/setup-ipsec-vpn#830]
请问这个有人数限制吗,多余几个人会不稳定,有这个说法吗啊

**Comment by hwdsl2** [comment]
@lebashupian 你好！Libreswan 本身并没有同时连接用户数的限制。当多个用户同时连接时，VPN 的性能取决于你的服务器的带宽和 CPU 的处理性能等。当你的服务器性能足够的时候，应该是没有问题的。
