### ISSUE TITLE
my port forwarding for openvpn not working after install l2tp script

### ISSUE THREAD

**Issue by baguswahyu** [hwdsl2/setup-ipsec-vpn#831]
sorry for not following format

My vps has openvpn server with port forwarding to openvpn client. after i install xl2tp vpn server my port forwarding in openvpn server. i saw xl2tp script modify iptables. after i remove xl2tp and revert back iptables from backup (thanks xl2tp script) my port forwarding back to work.

im not sure it issue from script or i need to adjust my port forwarding for my openvpn server. Could u help to find out?

this is my iptables.rules, 10.8.0.2 is my port forwarding for openvpn server
```
root@localhost:~# cat /etc/iptables.rules.bak
# Modified by hwdsl2 VPN script                                                     # Generated by iptables-save v1.8.4 on Sat Jul 18 12:56:48 2020                     *filter
:INPUT ACCEPT [0:0]                                                                 :FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [2:1577]
-A INPUT -p udp -m udp --dport 1701 -m policy --dir in --pol none -j DROP
-A INPUT -m conntrack --ctstate INVALID -j DROP
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p udp -m multiport --dports 500,4500 -j ACCEPT
-A INPUT -p udp -m udp --dport 1701 -m policy --dir in --pol ipsec -j ACCEPT
-A INPUT -p udp -m udp --dport 1701 -j DROP                                         -A INPUT -d 10.8.0.2/32 -p tcp -m tcp --dport 51413 -j ACCEPT
-A INPUT -d 10.8.0.2/32 -p tcp -m tcp --dport 51413 -j ACCEPT
-A INPUT -d 10.8.0.2/32 -p tcp -m tcp --dport 51413 -j ACCEPT
-A FORWARD -m conntrack --ctstate INVALID -j DROP
-A FORWARD -i ens192 -o ppp+ -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i ppp+ -o ens192 -j ACCEPT
-A FORWARD -s 192.168.42.0/24 -d 192.168.42.0/24 -i ppp+ -o ppp+ -j ACCEPT          -A FORWARD -d 192.168.43.0/24 -i ens192 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT                                                                            -A FORWARD -s 192.168.43.0/24 -o ens192 -j ACCEPT
-A FORWARD -j DROP                                                                  COMMIT
# Completed on Sat Jul 18 12:56:48 2020
# Generated by iptables-save v1.8.4 on Sat Jul 18 12:56:48 2020
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A PREROUTING -i ens192 -p tcp -m tcp --dport 51413 -j DNAT --to-destination 10.8.0.2:51413
-A PREROUTING -i ens192 -p tcp -m tcp --dport 51413 -j DNAT --to-destination 10.8.0.2:51413
-A POSTROUTING -s 192.168.42.0/24 -o ens192 -j MASQUERADE
-A POSTROUTING -s 192.168.43.0/24 -o ens192 -m policy --dir out --pol none -j MASQUERADE
-A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to-source 74.208.252.247
COMMIT
# Completed on Sat Jul 18 12:56:48 2020
root@localhost:~#
```

**Comment by hwdsl2** [comment]
@baguswahyu Hello! The VPN scripts added a DROP rule to the IPTables FORWARD chain for security. To fix it for your use case, you just need to insert these two rules (highlighted `--->`) in the FORWARD chain:
```
-A FORWARD -m conntrack --ctstate INVALID -j DROP
--->  -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
--->  -A FORWARD -s 10.8.0.0/24 -j ACCEPT
-A FORWARD -i ens192 -o ppp+ -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i ppp+ -o ens192 -j ACCEPT
-A FORWARD -s 192.168.42.0/24 -d 192.168.42.0/24 -i ppp+ -o ppp+ -j ACCEPT          
-A FORWARD -d 192.168.43.0/24 -i ens192 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT                                                                            -A FORWARD -s 192.168.43.0/24 -o ens192 -j ACCEPT
-A FORWARD -j DROP   
```
Modify `/etc/iptables.rules.bak` on your server with the changes above, then copy it to `/etc/iptables.rules` after making a backup of this file. Run `iptables-restore < /etc/iptables.rules` for the new rules to take effect.

**Comment by baguswahyu** [comment]
> @baguswahyu Hello! The VPN scripts added a DROP rule to the IPTables FORWARD chain for security. To fix it for your use case, you just need to insert these two rules (highlighted `--->`) in the FORWARD chain:
> 
> ```
> -A FORWARD -m conntrack --ctstate INVALID -j DROP
> --->  -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
> --->  -A FORWARD -s 10.8.0.0/24 -j ACCEPT
> -A FORWARD -i ens192 -o ppp+ -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
> -A FORWARD -i ppp+ -o ens192 -j ACCEPT
> -A FORWARD -s 192.168.42.0/24 -d 192.168.42.0/24 -i ppp+ -o ppp+ -j ACCEPT          
> -A FORWARD -d 192.168.43.0/24 -i ens192 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT                                                                            -A FORWARD -s 192.168.43.0/24 -o ens192 -j ACCEPT
> -A FORWARD -j DROP   
> ```
> 
> Modify `/etc/iptables.rules.bak` on your server with the changes above, then copy it to `/etc/iptables.rules` after making a backup of this file. Run `iptables-restore < /etc/iptables.rules` for the new rules to take effect.

your response so fast! appreciate it so much!🙏
will try this tommorow.excited to try that 😅
sorry my eye sights for reading iptables is so bad
*still learning

**Comment by baguswahyu** [comment]
> @baguswahyu Hello! The VPN scripts added a DROP rule to the IPTables FORWARD chain for security. To fix it for your use case, you just need to insert these two rules (highlighted `--->`) in the FORWARD chain:
> 
> ```
> -A FORWARD -m conntrack --ctstate INVALID -j DROP
> --->  -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
> --->  -A FORWARD -s 10.8.0.0/24 -j ACCEPT
> -A FORWARD -i ens192 -o ppp+ -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
> -A FORWARD -i ppp+ -o ens192 -j ACCEPT
> -A FORWARD -s 192.168.42.0/24 -d 192.168.42.0/24 -i ppp+ -o ppp+ -j ACCEPT          
> -A FORWARD -d 192.168.43.0/24 -i ens192 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT                                                                            -A FORWARD -s 192.168.43.0/24 -o ens192 -j ACCEPT
> -A FORWARD -j DROP   
> ```
> 
> Modify `/etc/iptables.rules.bak` on your server with the changes above, then copy it to `/etc/iptables.rules` after making a backup of this file. Run `iptables-restore < /etc/iptables.rules` for the new rules to take effect.

`# Modified by hwdsl2 VPN script
# Generated by iptables-save v1.8.4 on Sun Jul 19 13:18:54 2020
*security
:INPUT ACCEPT [2568668:460721184]
:FORWARD ACCEPT [443086:331409778]
:OUTPUT ACCEPT [2792215:5321493641]
COMMIT
# Completed on Sun Jul 19 13:18:54 2020
# Generated by iptables-save v1.8.4 on Sun Jul 19 13:18:54 2020
*raw
:PREROUTING ACCEPT [3013892:792285392]
:OUTPUT ACCEPT [2793361:5323278931]
COMMIT
# Completed on Sun Jul 19 13:18:54 2020
# Generated by iptables-save v1.8.4 on Sun Jul 19 13:18:54 2020
*mangle
:PREROUTING ACCEPT [3014928:792360530]
:INPUT ACCEPT [2571715:460940306]
:FORWARD ACCEPT [443092:331410282]
:OUTPUT ACCEPT [2794659:5324970938]
:POSTROUTING ACCEPT [3237751:5656381220]
COMMIT
# Completed on Sun Jul 19 13:18:54 2020
# Generated by iptables-save v1.8.4 on Sun Jul 19 13:18:54 2020
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A PREROUTING -i ens192 -p tcp -m tcp --dport 51415 -j DNAT --to-destination 10.8.0.2:51415
-A POSTROUTING -s 192.168.42.0/24 -o ens192 -j MASQUERADE
-A POSTROUTING -s 192.168.43.0/24 -o ens192 -m policy --dir out --pol none -j MASQUERADE
-A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to-source 74.208.252.247
COMMIT
# Completed on Sun Jul 19 13:18:54 2020
# Generated by iptables-save v1.8.4 on Sun Jul 19 13:18:54 2020
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [17:44594]
-A INPUT -p udp -m udp --dport 1701 -m policy --dir in --pol none -j DROP
-A INPUT -m conntrack --ctstate INVALID -j DROP
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p udp -m multiport --dports 500,4500 -j ACCEPT
-A INPUT -p udp -m udp --dport 1701 -m policy --dir in --pol ipsec -j ACCEPT
-A INPUT -p udp -m udp --dport 1701 -j DROP
-A INPUT -p udp -m udp --dport 1194 -j ACCEPT
-A INPUT -d 10.8.0.2/32 -p tcp -m tcp --dport 51415 -j ACCEPT
-A FORWARD -m conntrack --ctstate INVALID -j DROP
-A FORWARD -i ens192 -o ppp+ -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i ppp+ -o ens192 -j ACCEPT
-A FORWARD -s 192.168.42.0/24 -d 192.168.42.0/24 -i ppp+ -o ppp+ -j ACCEPT
-A FORWARD -d 192.168.43.0/24 -i ens192 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 192.168.43.0/24 -o ens192 -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 10.8.0.0/24 -j ACCEPT
-A FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -j DROP
COMMIT
# Completed on Sun Jul 19 13:18:54 2020`

hi @hwdsl2 , i already follow and you can check my iptables.rule. before i reinstall l2tp server port forwarding still working. but after i installed l2tp server. my port forwarding not working and i already insert 2 rules from ur suggestion.

**Comment by baguswahyu** [comment]
Ok i found it
i need to add this 3 rules

> -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
> -A FORWARD -d 10.8.0.0/24 -j ACCEPT
> -A FORWARD -s 10.8.0.0/24 -j ACCEPT

port forwarding work and i can use my openvpn & forwarding from ens192 to openvpn interface
