### ISSUE TITLE
IKEv2 - EAP with username and password without any certificate

### ISSUE THREAD

**Issue by AshishDhameliya** [hwdsl2/setup-ipsec-vpn#832]
Hello sir,

Please make tutorial for script to install vpn server for IKEv2-EAP, it's needs only username and password without any certificate during vpn connect.

Thanks.

**Comment by hwdsl2** [comment]
@AshishDhameliya Hello! Thanks for the suggestion. Libreswan does not yet support EAP authentication (username and password) for IKEv2.
