### ISSUE TITLE
Connected, but no access to internal resources

### ISSUE THREAD

**Issue by 22MarioZ** [hwdsl2/setup-ipsec-vpn#833]
**Describe the issue**
I setup the VPN server with the script and everything went well. I'm able to connect to VPN, but I'm not able to access to internal computers or access to Internet through tunnel.

If I execute `sudo iptables -nvL FORWARD` I get the following:

`Chain FORWARD (policy ACCEPT 505 packets, 32609 bytes)`
` pkts bytes target     prot opt in     out     source               destination `

My iptables is the following:

```
# Modified by hwdsl2 VPN script
# Generated by iptables-save v1.6.0 on Sat Aug  1 19:39:40 2020
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -s 192.168.42.0/24 -o eth0 -j MASQUERADE
-A POSTROUTING -s 192.168.43.0/24 -o eth0 -m policy --dir out --pol none -j MASQUERADE
COMMIT
# Completed on Sat Aug  1 19:39:40 2020
# Generated by iptables-save v1.6.0 on Sat Aug  1 19:39:40 2020
*mangle
:PREROUTING ACCEPT [169708:223733104]
:INPUT ACCEPT [169708:223733104]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [82650:10953161]
:POSTROUTING ACCEPT [82716:10966642]
COMMIT
# Completed on Sat Aug  1 19:39:40 2020
# Generated by iptables-save v1.6.0 on Sat Aug  1 19:39:40 2020
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -p udp -m udp --dport 1701 -m policy --dir in --pol none -j DROP
-A INPUT -m conntrack --ctstate INVALID -j DROP
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p udp -m multiport --dports 500,4500 -j ACCEPT
-A INPUT -p udp -m udp --dport 1701 -m policy --dir in --pol ipsec -j ACCEPT
-A INPUT -p udp -m udp --dport 1701 -j DROP
-A FORWARD -m conntrack --ctstate INVALID -j DROP
-A FORWARD -i eth0 -o ppp+ -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i ppp+ -o eth0 -j ACCEPT
-A FORWARD -s 192.168.42.0/24 -d 192.168.42.0/24 -i ppp+ -o ppp+ -j ACCEPT
-A FORWARD -d 192.168.43.0/24 -i eth0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -s 192.168.43.0/24 -o eth0 -j ACCEPT
-A FORWARD -j DROP
COMMIT
# Completed on Sat Aug  1 19:39:41 2020
```

**Server (please complete the following information)**
- OS: [e.g. Debian 9]

**Client (please complete the following information)**
- Device: [e.g. iPhone XR]
- OS: [e.g. iOS 13.5.1]
- VPN mode: [IPsec/L2TP or IPsec/XAuth ("Cisco IPsec")]

**Comment by hwdsl2** [comment]
@22MarioZ Hello! From the output of `sudo iptables -nvL FORWARD`, it looks like your IPTables rules might be empty for some reason. Restore the rules using:
```
sudo iptables-restore < /etc/iptables.rules
```

Let us know if this solves your issue.

**Comment by 22MarioZ** [comment]
Thx. Is working now. How i make it permanently? When I reboot the raspberry pi the iptables rules are gone.

**Comment by 22MarioZ** [comment]
I manage to make it permanently. thank you for the support. The ticket can be closed.
