### ISSUE TITLE
client The number of connections cannot exceed 6

### ISSUE THREAD

**Issue by AlZero-t** [hwdsl2/setup-ipsec-vpn#834]
The server is deployed on the System of Ubuntu 18.04, using the L2TP protocol connection, the server is 4C8G, the bandwidth is 10M.I currently have 6 connections, after which I cannot connect, unable to achieve multi-user multi-terminal login.Is it because my agreement is different?

**Comment by hwdsl2** [comment]
@AlZero-t Hello! There is no built-in limitation regarding the number of connections for Libreswan. It is only limited by your server's CPU, RAM, bandwidth, etc. You may have encountered a limitation of the IPsec/L2TP mode [1]. If you wish to connect multiple devices simultaneously from behind the same NAT (e.g. home router), you must use only IPsec/XAuth mode [2].

[1] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth.md
