### ISSUE TITLE
script fails to update iptables

### ISSUE THREAD

**Issue by thewriteway** [hwdsl2/setup-ipsec-vpn#835]
**Checklist**

- [X] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [X] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [X] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [X] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [X] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [X] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**
iptables rules are not saved properly.

**To Reproduce**
Run the script command (copy/pasted) from hwdsl2 

**Expected behavior**
script completes successfully and iptables are loaded correctly.

**Logs**

## Updating IPTables rules...

iptables-save/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables/1.8.2 Failed to initialize nft: Protocol not supported
iptables-save/1.8.2 Failed to initialize nft: Protocol not supported

## Enabling services on boot...

**Server**
Raspberry Pi Hardware 3B+

- OS: 
Raspberry Pi OS (32-bit) - Image with desktop based on Debian Buster
Version:May 2020
Kernel version:4.19
Fully updated OS with apt upgrade.
Linux version 4.19.118-v7+ (dom@buildbot) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1311 SMP Mon Apr 27 14:21:24 BST 2020

- Hosting provider (if applicable): [e.g. GCP, AWS]
N/A

**Client**
N/A

**Additional context**
script appears to be incompatible with the new version of iptables format.

**Comment by hwdsl2** [comment]
@thewriteway Hello! Thanks for reporting. I've tested the script on a freshly installed Raspberry Pi OS Lite with kernel 4.19, and the script updated IPTables without problems. Searching the Internet gives several results (see below) that point to a possible issue in Raspberry Pi OS related to kernel updates. Try rebooting your Raspberry Pi, then re-run the VPN setup script.

https://raspberrypi.stackexchange.com/questions/108161/problem-with-iptables-on-buster-neither-legacy-or-nft-work  
https://www.raspberrypi.org/forums/viewtopic.php?t=246529
https://www.raspberrypi.org/forums/viewtopic.php?t=282120
https://www.raspberrypi.org/forums/viewtopic.php?t=264159

**Comment by hwdsl2** [comment]
@thewriteway Before re-running the VPN setup script after reboot, you may first need to remove the line `# Modified by hwdsl2 VPN script` from file `/etc/iptables.rules`, so that IPTables rules can be updated.

**Comment by thewriteway** [comment]
hi, that has working after i deleted the comment and reran the script after a reboot.
