### ISSUE TITLE
Configuration for AVM Fritz!Box

### ISSUE THREAD

**Issue by lhanne1** [hwdsl2/setup-ipsec-vpn#836]
**Checklist**

- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [ ] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
I have problems connecting my AVM Fritz!Box to the VPN server. Is it possible to create a instruction for this?

**Comment by hwdsl2** [comment]
@lhanne1 Hello! The Fritz!Box, when used as an IPsec VPN client, requires IPsec aggressive mode which is not supported in the default configuration created by the VPN setup scripts. For details, please refer to #665 and #303.

**Comment by azanke** [comment]
Dear All,

I connected my iPhone as a VPN client without any problem, but I stuck with connecting a FritzBox.
does anyone have a working configuration for using a FritzBox as a client?

Would be great if you can share this.

Thank You!
