### ISSUE TITLE
多台windows10机器IKEv2同一NAT

### ISSUE THREAD

**Issue by zero1five** [hwdsl2/setup-ipsec-vpn#837]
你好，请问多台window10机器能否使用IKEv2走同一NAT，我尝试了IPsec但无法登录第二台window10。

https://github.com/hwdsl2/setup-ipsec-vpn/issues/241 我注意到这里提到的问题，但我不知道在IKEv2是怎么样的。

**Comment by hwdsl2** [comment]
@zero1five 你好！该用例（多台window10机器使用IKEv2走同一NAT）并没有测试过，所以目前不知道是否可行。请确保你为每一台 Windows 10 客户端生成（并使用）唯一的 IKEv2 证书，而不是共享同一个证书。如果仍然无法同时登录的话，那么很可能是因为像之前 #241 中所说，如果两台客户端设备都是 Windows 的话，由于它们都尝试使用路由器上的 UDP 500 和 4500 端口，所以不能同时连接。
