### ISSUE TITLE
L2TP VPN服务器设置了多个帐户，但是不能同时连接服务器

### ISSUE THREAD

**Issue by yc88888888** [hwdsl2/setup-ipsec-vpn#839]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ ] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**

**To Reproduce**

1. ...
2. ...

**Expected behavior**

**Logs**
[Check logs and VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status), and add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- OS: [e.g. Debian 10]
- Hosting provider (if applicable): [e.g. GCP, AWS]

**Client (please complete the following information)**
- Device: [e.g. iPhone 8]
- OS: [e.g. iOS 13.6]
- VPN mode: [IPsec/L2TP, IPsec/XAuth ("Cisco IPsec") or IKEv2]

**Additional context**
L2TP VPN已经设置好也可以正常使用，但是我想多个账户一起同时连接缺连接不上，必须断开现在连接的账户下一个才可以连上。例如账户A已连接，账户B想连接使用A账户就必须断开B才能连上。请问这个问题怎么解决呢？谢谢

**Comment by hwdsl2** [comment]
@yc88888888 你好！这个是因为 IPsec/L2TP 模式的局限性。重要提示一节有说明 [1]："由于 IPsec/L2TP 的局限性，如果需要同时连接在同一个 NAT （比如家用路由器）后面的多个设备到 VPN 服务器，你必须仅使用 IPsec/XAuth 模式 [2]。"

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#%E9%87%8D%E8%A6%81%E6%8F%90%E7%A4%BA
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-xauth-zh.md
