### ISSUE TITLE
Possible to also use ipv6 ? and always on setup on Android

### ISSUE THREAD

**Issue by tunayuyar** [hwdsl2/setup-ipsec-vpn#84]
Hi,

Great work thanks for sharing it. Easy to use script working with all my devices. 

I have 2 questions 

Is it possible to also use ipv6 ? Im asking because currently Im getting ipv6 from hurricane electric with 6to4 tunnel in my router, after connecting ipsec vpn all my ipv4 is ipsec servers ip but ipv6 stays the same as before(hurricane ipv6)

My other question is android can be setup as always on vpn if i put dns server, so what dns ip should i put? I tried my servers adress, google dns, my server's dns adress none works, should i put 192.168.42.1 ?

Thanks again.

**Comment by hwdsl2** [comment]
@tunayuyar No, your IPv6 traffic will NOT go through the IPsec VPN. Regarding the "Always-on VPN" on Android, I think you can put Google Public DNS (e.g. 8.8.8.8). I tested it and it is working fine for me.

**Comment by hwdsl2** [comment]
@tunayuyar Hello again! I looked further into the "Always-on VPN" issue, and it seems that you've hit an Android bug "Issue 63450: Always-on VPN not working after 4.4". This bug affects Android 4.4 and newer. See [1].

[1] https://code.google.com/p/android/issues/detail?id=63450

**Comment by amIwho** [comment]
Welcome to the iphone user world. I have been had VPN always on on 10.0 only, it was 2 weeks of joy, but 10.0.1 kill this feature.
I just set up vpn client on router.

**Comment by tunayuyar** [comment]
@hwdsl2 actually it is working. But when I checked it wasnt. I assume when I was checking with my phone, i disconnect from vpn (not always on) I need to wait some time before reconnecting again. It is working since Im aware of this. It is working since you advised. 

Im using cyanogenmod 13 on oneplus one.

Also is it possible to configure this to also use ipv6? My home connection is killing me on ipv6 sites when goverment (Turkey) starts blocking/throttling. 

One more thing(what a pain in the ass Im) anyone knows how to set this up on mikrotik?

**Comment by hwdsl2** [comment]
@tunayuyar Thanks for the update. It looks like the Android bug I referenced above has been fixed [1] in Android 6.0.1, which CM13 is based on.

Regarding IPv6, no I am not aware of any method to achieve this. You may want to instead disable IPv6 on your PC, Mac or mobile device, so that only IPv4 is used.

Not sure about the mikrotik as VPN client. Try Google.



[1] https://code.google.com/p/android/issues/detail?id=63450#c73
