### ISSUE TITLE
经常断开连接

### ISSUE THREAD

**Issue by ndjfhk** [hwdsl2/setup-ipsec-vpn#842]
auth.log

Aug 28 07:48:53 vultr sshd[14551]: pam_unix(sshd:session): session closed for user root
Aug 28 07:48:53 vultr systemd-logind[417]: Removed session 247.
Aug 28 07:48:54 vultr sshd[14566]: pam_unix(sshd:session): session closed for user root
Aug 28 07:48:54 vultr sshd[14892]: pam_unix(sshd:session): session closed for user root
Aug 28 07:48:54 vultr systemd-logind[417]: Removed session 249.
Aug 28 07:48:54 vultr systemd-logind[417]: Removed session 250.
Aug 28 08:17:01 vultr CRON[15487]: pam_unix(cron:session): session opened for user root by (uid=0)
Aug 28 08:17:01 vultr CRON[15487]: pam_unix(cron:session): session closed for user root
Aug 28 08:49:49 vultr sshd[15496]: Accepted password for root from 182.239.123.120 port 19335 ssh2
Aug 28 08:49:49 vultr sshd[15496]: pam_unix(sshd:session): session opened for user root by (uid=0)
Aug 28 08:49:49 vultr systemd-logind[417]: New session 252 of user root.
Aug 28 08:49:49 vultr systemd: pam_unix(systemd-user:session): session opened for user root by (uid=0)
Aug 28 08:49:51 vultr sshd[15511]: Accepted password for root from 182.239.123.120 port 19336 ssh2
Aug 28 08:49:51 vultr sshd[15511]: pam_unix(sshd:session): session opened for user root by (uid=0)
Aug 28 08:49:51 vultr systemd-logind[417]: New session 254 of user root.
Aug 28 08:50:05 vultr sshd[15662]: Accepted password for root from 182.239.123.120 port 19337 ssh2
Aug 28 08:50:05 vultr sshd[15662]: pam_unix(sshd:session): session opened for user root by (uid=0)
Aug 28 08:50:05 vultr systemd-logind[417]: New session 255 of user root.
------------------------------------------------------------------------------------------------------------------

syslog.log
Aug 28 07:48:54 vultr systemd[14553]: Stopped target Default.
Aug 28 07:48:54 vultr systemd[14553]: Stopped target Basic System.
Aug 28 07:48:54 vultr systemd[14553]: Stopped target Paths.
Aug 28 07:48:54 vultr systemd[14553]: Stopped target Sockets.
Aug 28 07:48:54 vultr systemd[14553]: Closed GnuPG cryptographic agent (access for web browsers).
Aug 28 07:48:54 vultr systemd[14553]: Closed GnuPG cryptographic agent and passphrase cache (restricted).
Aug 28 07:48:54 vultr systemd[14553]: Closed GnuPG cryptographic agent and passphrase cache.
Aug 28 07:48:54 vultr systemd[14553]: Closed GnuPG cryptographic agent (ssh-agent emulation).
Aug 28 07:48:54 vultr systemd[14553]: Reached target Shutdown.
Aug 28 07:48:54 vultr systemd[14553]: Starting Exit the Session...
Aug 28 07:48:54 vultr systemd[14553]: Stopped target Timers.
Aug 28 07:48:54 vultr systemd[1]: Stopping User Manager for UID 0...
Aug 28 07:48:54 vultr systemd[14553]: Received SIGRTMIN+24 from PID 15474 (kill).
Aug 28 07:48:54 vultr systemd[1]: Stopped User Manager for UID 0.
Aug 28 07:48:54 vultr systemd[1]: Removed slice User Slice of root.
Aug 28 08:17:01 vultr CRON[15488]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Aug 28 08:49:49 vultr systemd[1]: Created slice User Slice of root.
Aug 28 08:49:49 vultr systemd[1]: Started Session 252 of user root.
Aug 28 08:49:49 vultr systemd[1]: Starting User Manager for UID 0...
Aug 28 08:49:49 vultr systemd[15498]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Aug 28 08:49:49 vultr systemd[15498]: Listening on GnuPG cryptographic agent and passphrase cache.
Aug 28 08:49:49 vultr systemd[15498]: Listening on GnuPG cryptographic agent (access for web browsers).
Aug 28 08:49:49 vultr systemd[15498]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Aug 28 08:49:49 vultr systemd[15498]: Reached target Sockets.
Aug 28 08:49:49 vultr systemd[15498]: Reached target Timers.
Aug 28 08:49:49 vultr systemd[15498]: Reached target Paths.
Aug 28 08:49:49 vultr systemd[15498]: Reached target Basic System.
Aug 28 08:49:49 vultr systemd[15498]: Reached target Default.
Aug 28 08:49:49 vultr systemd[15498]: Startup finished in 7ms.
Aug 28 08:49:49 vultr systemd[1]: Started User Manager for UID 0.
Aug 28 08:49:51 vultr systemd[1]: Started Session 254 of user root.
Aug 28 08:50:05 vultr systemd[1]: Started Session 255 of user root.
帮忙看看，谢谢

**Comment by hwdsl2** [comment]
@ndjfhk 你好！你的日志中并没有 VPN 连接相关的日志，可以参见这里 [1]。IPsec VPN 较容易被 GFW 干扰，你可以考虑其他更好的解决方案，比如 Shadowsocks。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E6%A3%80%E6%9F%A5%E6%97%A5%E5%BF%97%E5%8F%8A-vpn-%E7%8A%B6%E6%80%81
