### ISSUE TITLE
mac下 l2tp如何与v2ray等代理共存

### ISSUE THREAD

**Issue by doolindalton** [hwdsl2/setup-ipsec-vpn#843]
**任务列表**

- [ ] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [ ] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [ ] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [ ] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [ ] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ ] 这个 bug 是关于 VPN 安装脚本，而不是 IPsec VPN 本身

**问题描述**
使用清楚简明的语言描述这个 bug。

**重现步骤**
重现该 bug 的步骤：

1. ...
2. ...

**期待的正确结果**
简要地描述你期望的正确结果。

**日志**
[检查日志及 VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)，并添加错误日志以帮助解释该问题（如果适用）。

**服务器信息（请填写以下信息）**
- 操作系统: [比如 Debian 10]
- 服务提供商（如果适用）: [比如 GCP, AWS]

**客户端信息（请填写以下信息）**
- 设备: [比如 iPhone 8]
- 操作系统: [比如 iOS 13.6]
- VPN 模式: [IPsec/L2TP, IPsec/XAuth ("Cisco IPsec") 或 IKEv2]

**其它信息**
添加关于该 bug 的其它信息。

**Comment by doolindalton** [comment]
mac下 l2tp如何与v2ray等代理共存？公司使用l2tp代理，通过静态路由等方式；    这和我使用的科学上网冲突

**Comment by hwdsl2** [comment]
@doolindalton 你好！你说的用例可能比较难实现，因为 L2TP 会通过 VPN 服务器发送所有流量，所以可能不能和v2ray等代理同时使用。

**Comment by doolindalton** [comment]
> @doolindalton 你好！你说的用例可能比较难实现，因为 L2TP 会通过 VPN 服务器发送所有流量，所以可能不能和v2ray等代理同时使用。
我取消了勾选所有流量呢
