### ISSUE TITLE
IKEV2每小时自动断开连接

### ISSUE THREAD

**Issue by ndjfhk** [hwdsl2/setup-ipsec-vpn#844]
ug 31 08:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126: local IKE proposals (IKE SA responder matching remote proposals):
Aug 31 08:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126:   1:IKE=AES_CBC_256-HMAC_SHA2_256-HMAC_SHA2_256_128-MODP2048+MODP3072+MODP4096+MODP8192+ECP_256+ECP_384+ECP_521
Aug 31 08:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126:   2:IKE=AES_CBC_128-HMAC_SHA2_256-HMAC_SHA2_256_128-MODP2048+MODP3072+MODP4096+MODP8192+ECP_256+ECP_384+ECP_521
Aug 31 08:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126:   3:IKE=AES_CBC_256-HMAC_SHA1-HMAC_SHA1_96-MODP2048+MODP3072+MODP4096+MODP8192+ECP_256+ECP_384+ECP_521
Aug 31 08:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126:   4:IKE=AES_CBC_128-HMAC_SHA1-HMAC_SHA1_96-MODP2048+MODP3072+MODP4096+MODP8192+ECP_256+ECP_384+ECP_521
Aug 31 08:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126:   5:IKE=AES_CBC_256-HMAC_SHA2_256-HMAC_SHA2_256_128-MODP1024
Aug 31 08:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126:   6:IKE=AES_CBC_128-HMAC_SHA1-HMAC_SHA1_96-MODP1024
Aug 31 08:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126 #95: proposal 2:IKE=AES_CBC_256-HMAC_SHA2_256-HMAC_SHA2_256_128-MODP2048 chosen from remote proposals 1:IKE:ENCR=AES_CBC_256;INTEG=HMAC_SHA1_96;PRF=HMAC_SHA1;DH=MODP2048[first-match] 2:IKE:ENCR=AES_CBC_256;INTEG=HMAC_SHA2_256_128;PRF=HMAC_SHA2_256;DH=MODP2048[better-match] 3:IKE:ENCR=AES_CBC_256;INTEG=HMAC_SHA2_384_192;PRF=HMAC_SHA2_384;DH=MODP2048
Aug 31 08:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126 #95: STATE_PARENT_R1: received v2I1, sent v2R1 {auth=IKEv2 cipher=AES_CBC_256 integ=HMAC_SHA2_256_128 prf=HMAC_SHA2_256 group=MODP2048}
Aug 31 08:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126 #95: processing decrypted IKE_AUTH request: SK{IDi,CERT,CERTREQ,AUTH,N,CP,SA,TSi,TSr}
Aug 31 08:12:06 vultr pluto[1464]: loading root certificate cache
Aug 31 08:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126 #95: certificate verified OK: O=IKEv2 VPN,CN=vpnclient
Aug 31 08:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126 #95: IKEv2 mode peer ID is ID_DER_ASN1_DN: 'CN=vpnclient, O=IKEv2 VPN'
Aug 31 08:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126 #95: Authenticated using RSA with IKEv2_AUTH_HASH_SHA1
Aug 31 08:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126: local ESP/AH proposals (IKE_AUTH responder matching remote ESP/AH proposals):
Aug 31 08:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126:   1:ESP=AES_GCM_C_128+AES_GCM_C_256-NONE-NONE-DISABLED
Aug 31 08:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126:   2:ESP=AES_CBC_128-HMAC_SHA1_96-NONE-DISABLED
Aug 31 08:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126:   3:ESP=AES_CBC_256-HMAC_SHA1_96-NONE-DISABLED
Aug 31 08:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126:   4:ESP=AES_CBC_128-HMAC_SHA2_256_128-NONE-DISABLED
Aug 31 08:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126:   5:ESP=AES_CBC_256-HMAC_SHA2_256_128-NONE-DISABLED
Aug 31 08:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126 #95: proposal 1:ESP=AES_CBC_256-HMAC_SHA1_96-DISABLED SPI=a04a6982 chosen from remote proposals 1:ESP:ENCR=AES_CBC_256;INTEG=HMAC_SHA1_96;ESN=DISABLED[first-match] 2:ESP:ENCR=3DES;INTEG=HMAC_SHA1_96;ESN=DISABLED
Aug 31 08:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126 #96: negotiated connection [0.0.0.0-255.255.255.255:0-65535 0] -> [192.168.43.10-192.168.43.10:0-65535 0]
Aug 31 08:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126 #96: STATE_V2_IPSEC_R: IPsec SA established tunnel mode {ESP/NAT=>0xa04a6982 <0x4a19ec9b xfrm=AES_CBC_256-HMAC_SHA1_96 NATOA=none NATD=182.239.92.126:21501 DPD=active}
Aug 31 08:17:01 vultr CRON[7584]: pam_unix(cron:session): session opened for user root by (uid=0)
Aug 31 08:17:01 vultr CRON[7584]: pam_unix(cron:session): session closed for user root
Aug 31 08:17:06 vultr pluto[1464]: destroying root certificate cache
Aug 31 08:28:29 vultr sshd[7599]: Accepted password for root from 182.239.92.126 port 57926 ssh2
Aug 31 08:28:29 vultr sshd[7599]: pam_unix(sshd:session): session opened for user root by (uid=0)
Aug 31 08:28:29 vultr systemd-logind[400]: New session 167 of user root.
Aug 31 08:28:29 vultr systemd: pam_unix(systemd-user:session): session opened for user root by (uid=0)
Aug 31 08:28:31 vultr sshd[7614]: Accepted password for root from 182.239.92.126 port 57927 ssh2
Aug 31 08:28:31 vultr sshd[7614]: pam_unix(sshd:session): session opened for user root by (uid=0)
Aug 31 08:28:31 vultr systemd-logind[400]: New session 169 of user root.
Aug 31 08:28:50 vultr sshd[7809]: Accepted password for root from 182.239.92.126 port 57928 ssh2
Aug 31 08:28:50 vultr sshd[7809]: pam_unix(sshd:session): session opened for user root by (uid=0)
Aug 31 08:28:50 vultr systemd-logind[400]: New session 170 of user root.
Aug 31 09:07:52 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126: local ESP/AH proposals (CREATE_CHILD_SA responder matching remote ESP/AH proposals):
Aug 31 09:07:52 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126:   1:ESP=AES_GCM_C_128+AES_GCM_C_256-NONE-NONE-DISABLED
Aug 31 09:07:52 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126:   2:ESP=AES_CBC_128-HMAC_SHA1_96-NONE-DISABLED
Aug 31 09:07:52 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126:   3:ESP=AES_CBC_256-HMAC_SHA1_96-NONE-DISABLED
Aug 31 09:07:52 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126:   4:ESP=AES_CBC_128-HMAC_SHA2_256_128-NONE-DISABLED
Aug 31 09:07:52 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126:   5:ESP=AES_CBC_256-HMAC_SHA2_256_128-NONE-DISABLED
Aug 31 09:07:52 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126 #95: proposal 1:ESP=AES_CBC_256-HMAC_SHA1_96-DISABLED SPI=f0cc90d8 chosen from remote proposals 1:ESP:ENCR=AES_CBC_256;INTEG=HMAC_SHA1_96;ESN=DISABLED[first-match] 2:ESP:ENCR=3DES;INTEG=HMAC_SHA1_96;ESN=DISABLED
Aug 31 09:07:52 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126 #97: negotiated new IPsec SA [0.0.0.0-255.255.255.255:0-65535 0] -> [192.168.43.10-192.168.43.10:0-65535 0]
Aug 31 09:07:52 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126 #97: negotiated connection [0.0.0.0-255.255.255.255:0-65535 0] -> [192.168.43.10-192.168.43.10:0-65535 0]
Aug 31 09:07:52 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126 #97: STATE_V2_IPSEC_R: IPsec SA established tunnel mode {ESP/NAT=>0xf0cc90d8 <0x61e3dac4 xfrm=AES_CBC_256-HMAC_SHA1_96 NATOA=none NATD=182.239.92.126:21501 DPD=active}
Aug 31 09:07:52 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126 #95: received Delete SA payload: expire IPsec State #96 now
Aug 31 09:07:52 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126 #95: STATE_PARENT_R2: received v2I2, PARENT SA established
Aug 31 09:07:52 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126 #96: deleting state (STATE_V2_IPSEC_R) aged 3345.431s and NOT sending notification
Aug 31 09:07:52 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126 #96: ESP traffic information: in=4MB out=30MB
Aug 31 09:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126 #95: IKE SA expired (--dontrekey)
Aug 31 09:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126 #97: deleting other state #97 (STATE_V2_IPSEC_R) aged 254.703s and sending notification
Aug 31 09:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126 #97: ESP traffic information: in=221KB out=558KB
Aug 31 09:12:06 vultr pluto[1464]: "ikev2-cp"[22] 182.239.92.126 #95: deleting state (STATE_PARENT_R2) aged 3600.254s and sending notification
Aug 31 09:12:06 vultr pluto[1464]:  #95: deleting connection "ikev2-cp"[22] 182.239.92.126 instance with peer 182.239.92.126 {isakmp=#0/ipsec=#0}
Aug 31 09:12:06 vultr pluto[1464]: packet from 182.239.92.126:21501: ISAKMP_v2_INFORMATIONAL message response has no matching IKE SA
Aug 31 09:12:06 vultr pluto[1464]: packet from 182.239.92.126:21501: ISAKMP_v2_INFORMATIONAL message response has no matching IKE SA
这是日志，感谢您的回答

**Comment by hwdsl2** [comment]
@ndjfhk Hello! The logs show that your IKEv2 connection was successfully re-keyed after one hour, however after a few minutes the connection was deleted. This could be a bug in your VPN client's re-key process, or it might be a bug in Libreswan. As a workaround:

Edit `/etc/ipsec.d/ikev2.conf` on your VPN server. Add these two lines, indented by two spaces. Save the file and run `sudo service ipsec restart`.
```
  ikelifetime=24h
  salifetime=24h
```
This should set the re-key to every 24 hours from the server side.

**Comment by ndjfhk** [comment]
这是不是每24小时就会断开一次呢

**Comment by ndjfhk** [comment]
> @ndjfhk您好！日志显示一小时后，您的IKEv2连接已成功重新设置密钥，但是几分钟后，该连接被删除。这可能是VPN客户端重新密钥过程中的错误，也可能是Libreswan中的错误。解决方法：
> 
> `/etc/ipsec.d/ikev2.conf`在您的VPN服务器上编辑。将这两行相加，以两个空格缩进。保存文件并运行`sudo service ipsec restart`。
> 
> ```
>   ikelifetime=24h
>   salifetime=24h
> ```
> 
> 这将从服务器端将重新密钥设置为每24小时一次。

首先感谢您的回复，请容许我再提一下疑问：这是不是意味着24小时就会断开一次吗，VPN客户端应该是没有问题的，我测试了别人提供的VPN没有这种情况发生。

**Comment by hwdsl2** [comment]
@ndjfhk 是有可能断开，这个只是workaround。从你的日志来看，并不清楚具体的断开原因。建议你到 Libreswan 这里 [1] 开一个新的 Issue 问一下，附上日志。

[1] https://github.com/libreswan/libreswan/issues
