### ISSUE TITLE
Unable to install using the script

### ISSUE THREAD

**Issue by binglenozumi** [hwdsl2/setup-ipsec-vpn#845]
Hi, I was attempt to install the VPN Server and it gives me 2 error

vpnsetup.sh: 1: —2020-09-04: not found
vpnsetup.sh: 2: Syntax error: “(“ unexpected

Not sure which part of the file creating the issue

**Comment by malikshi** [comment]
maybe these the problem,
`SYS_DT=$(date +%F-%T | tr ':' '_')` 
please run the script with `root` users

**Comment by hwdsl2** [comment]
@binglenozumi Please try re-download the script from [1]. It could be that your download was corrupted. I checked just now and did not find any issue.

[1] https://raw.githubusercontent.com/hwdsl2/setup-ipsec-vpn/master/vpnsetup.sh
