### ISSUE TITLE
ppp目录下没有登录日志

### ISSUE THREAD

**Issue by ylmcr7** [hwdsl2/setup-ipsec-vpn#846]
root@ylm_aliyun ~]# cd /var/log/ppp/
[root@ylm_aliyun ppp]# ls
[root@ylm_aliyun ppp]# ls
[root@ylm_aliyun ppp]#

**Comment by hwdsl2** [comment]
@ylmcr7 你好！VPN 脚本的默认配置下没有 ppp 登录日志。如需启用详细日志或统计用户信息，请参见 #166 中的解决方案。
