### ISSUE TITLE
如何找回之前设置的密码

### ISSUE THREAD

**Issue by 13480628384** [hwdsl2/setup-ipsec-vpn#847]
**任务列表**

- [ ] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)，没有找到类似的改进建议
- [ ] 这个改进建议是关于 VPN 安装脚本，而不是 IPsec VPN 本身
- [ ] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [ ] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [ ] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [ ] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)

**描述改进建议**
使用清楚简明的语言描述你的改进建议。

**你的改进建议与遇到的问题有关吗？请描述。**
（如果适用）清楚，简洁地说明问题所在。

**其它信息**
添加关于该改进建议的其它信息。

**Comment by hwdsl2** [comment]
@13480628384 请看服务器上的 `/etc/ipsec.secrets` (包含 IPsec PSK) 和 `/etc/ppp/chap-secrets` (包含用户名和密码)。
