### ISSUE TITLE
Android cannot connect using xauth

### ISSUE THREAD

**Issue by NazeehSheikh** [hwdsl2/setup-ipsec-vpn#848]
Hi I am using Android 6.0.1 and IPSec/Xauth

Here is the code from server
NUL at end of XAUTH User Password (Android Issue 36879?)
Sep 12 17:59:33 localhost pluto[34252]: "xauth-psk"[2] 192.168.1.1 #4: XAUTH: password file authentication method requested to authenticate user 'nazeeh'
Sep 12 17:59:33 localhost pluto[34252]: "xauth-psk"[2] 192.168.1.1 #4: XAUTH: password file (/etc/ipsec.d/passwd) open.
Sep 12 17:59:33 localhost pluto[34252]: "xauth-psk"[2] 192.168.1.1 #4: XAUTH: success user(nazeeh:xauth-psk)
Sep 12 17:59:33 localhost pluto[34252]: "xauth-psk"[2] 192.168.1.1 #4: discarding packet received during asynchronous work (DNS or crypto) in STATE_XAUTH_R0
Sep 12 17:59:33 localhost pluto[34252]: "xauth-psk"[2] 192.168.1.1 #4: XAUTH: User nazeeh: Authentication Successful
Sep 12 17:59:33 localhost pluto[34252]: "xauth-psk"[2] 192.168.1.1 #4: XAUTH: xauth_inR1(STF_OK)
Sep 12 17:59:33 localhost pluto[34252]: "xauth-psk"[2] 192.168.1.1 #4: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA2_256 group=MODP1024}
Sep 12 17:59:33 localhost pluto[34252]: | pool 192.168.49.10-192.168.49.250: growing address pool from 2 to 4
Sep 12 17:59:33 localhost pluto[34252]: "xauth-psk"[2] 192.168.1.1 #4: modecfg_inR0(STF_OK)
Sep 12 17:59:33 localhost pluto[34252]: "xauth-psk"[2] 192.168.1.1 #4: STATE_MODE_CFG_R1: ModeCfg Set sent, expecting Ack {auth=PRESHARED_KEY cipher=AES_CBC_256 integ=HMAC_SHA2_256 group=MODP1024}

It stuck like this and the android won't connect.
I tried it with iPhone and worked fine

**Comment by hwdsl2** [comment]
@NazeehSheikh Hello! It looks like you may encountered the Android 6/7 `sha2-truncbug` issue. Can you try step 2 from [1] to see if it resolves the issue?

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#android-6-and-7

**Comment by NazeehSheikh** [comment]
Thank you @hwdsl2 for replying
I tried to change the sha2-truncbug but its still the same issue
I tried testing it inside and outside of NAT, both cannot connect at all while on iOS it worked

**Comment by NazeehSheikh** [comment]
Issue fixed
I changed sha2-truncbug and I was using easy password and PSK after set it to go random everything is working Fine
Thank you
