### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by ptorrent** [hwdsl2/setup-ipsec-vpn#849]
Hello,

I m not able to connect to the server with l2tp (on android/windows)

**Server**
- OS: Debian 9

**Client**
- Device: samsung a41
- OS: android / win 10
- VPN mode:[IPsec/L2TP

**Additional context**
Server directly connected on internet, without NAT / firewall

Console output:
root@serverWeble:/install# xl2tpd -D
xl2tpd[52299]: Not looking for kernel SAref support.
xl2tpd[52299]: Using l2tp kernel support.
xl2tpd[52299]: xl2tpd version xl2tpd-1.3.12 started on serverWeble PID:52299
xl2tpd[52299]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
xl2tpd[52299]: Forked by Scott Balmos and David Stipp, (C) 2001
xl2tpd[52299]: Inherited by Jeff McAdams, (C) 2002
xl2tpd[52299]: Forked again by Xelerance (www.xelerance.com) (C) 2006-2016
xl2tpd[52299]: Listening on IP address 0.0.0.0, port 1701
xl2tpd[52299]: check_control: Received out of order control packet on tunnel -1 (got 1, expected 0)
xl2tpd[52299]: handle_packet: bad control packet!
xl2tpd[52299]: Maximum retries exceeded for tunnel 43101.  Closing.
xl2tpd[52299]: Connection 31676 closed to 178.197.234.15, port 64740 (Timeout)
xl2tpd[52299]: check_control: Received out of order control packet on tunnel -1 (got 1, expected 0)
xl2tpd[52299]: handle_packet: bad control packet!
xl2tpd[52299]: Unable to deliver closing message for tunnel 43101. Destroying anyway.
 handle_packet: bad control packet!xl2tpd[52299]: Maximum retries exceeded for tunnel 22768.  Closing.
xl2tpd[52299]: Connection 21940 closed to 178.197.234.15, port 64742 (Timeout)
xl2tpd[52299]: Unable to deliver closing message for tunnel 22768. Destroying anyway.

Working very well on pptp... 

Installation script working well without error...

Thanks for your help !

**Comment by ptorrent** [comment]
Maybe this can help :

root@serverWeble:/install# /usr/local/sbin/ipsec verify
Verifying installed system and configuration files

Version check and ipsec on-path                         [OK]
Libreswan 3.32 (netkey) on 4.9.0-13-amd64
Checking for IPsec support in kernel                    [OK]
 NETKEY: Testing XFRM related proc values
         ICMP default/send_redirects                    [OK]
         ICMP default/accept_redirects                  [OK]
         XFRM larval drop                               [OK]
Pluto ipsec.conf syntax                                 [OK]
Checking rp_filter                                      [OK]
Checking that pluto is running                          [FAILED]
Checking 'ip' command                                   [OK]
Checking 'iptables' command                             [OK]
Checking 'prelink' command does not interfere with FIPS [OK]
Checking for obsolete ipsec.conf options                [OK]

**Comment by ptorrent** [comment]
this can help maybe? 

![image](https://user-images.githubusercontent.com/6083644/93017884-58ca2e00-f5cc-11ea-8f0a-d13a76cf5cbd.png)

**Comment by ptorrent** [comment]
Sep 13 14:23:38 localhost pluto[72935]: NSS DB directory: sql:/etc/ipsec.d
Sep 13 14:23:38 localhost pluto[72935]: Initializing NSS
Sep 13 14:23:38 localhost pluto[72935]: Opening NSS database "sql:/etc/ipsec.d" read-only
Sep 13 14:23:38 localhost pluto[72935]: NSS crypto library initialized
Sep 13 14:23:38 localhost pluto[72935]: FIPS Mode: NO
Sep 13 14:23:38 localhost pluto[72935]: FIPS mode disabled for pluto daemon
Sep 13 14:23:38 localhost pluto[72935]: FIPS HMAC integrity support [disabled]
Sep 13 14:23:38 localhost pluto[72935]: libcap-ng support [enabled]
Sep 13 14:23:38 localhost pluto[72935]: Linux audit support [disabled]
Sep 13 14:23:38 localhost pluto[72935]: Starting Pluto (Libreswan Version 3.32 XFRM(netkey) XFRMI esp-hw-offload FORK PTHREAD_SETSCHEDPRIO NSS (AVA copy) (native-PRF) SYSTEMD_WATCHDOG LIBCAP_NG XAUTH_PAM NETWORKMANAGER CURL(non-NSS)) pid:72935
Sep 13 14:23:38 localhost pluto[72935]: core dump dir: /run/pluto
Sep 13 14:23:38 localhost pluto[72935]: secrets file: /etc/ipsec.secrets
Sep 13 14:23:38 localhost pluto[72935]: leak-detective enabled
Sep 13 14:23:38 localhost pluto[72935]: NSS crypto [enabled]
Sep 13 14:23:38 localhost pluto[72935]: XAUTH PAM support [enabled]
Sep 13 14:23:38 localhost pluto[72935]: Initializing libevent in pthreads mode: headers: 2.1.12-stable (2010c00); library: 2.1.12-stable (2010c00)
Sep 13 14:23:38 localhost pluto[72935]: NAT-Traversal support  [enabled]
Sep 13 14:23:38 localhost pluto[72935]: Encryption algorithms:
Sep 13 14:23:38 localhost pluto[72935]:   AES_CCM_16              IKEv1:     ESP     IKEv2:     ESP     FIPS  {256,192,*128}  aes_ccm, aes_ccm_c
Sep 13 14:23:38 localhost pluto[72935]:   AES_CCM_12              IKEv1:     ESP     IKEv2:     ESP     FIPS  {256,192,*128}  aes_ccm_b
Sep 13 14:23:38 localhost pluto[72935]:   AES_CCM_8               IKEv1:     ESP     IKEv2:     ESP     FIPS  {256,192,*128}  aes_ccm_a
Sep 13 14:23:38 localhost pluto[72935]:   3DES_CBC                IKEv1: IKE ESP     IKEv2: IKE ESP     FIPS  [*192]  3des
Sep 13 14:23:38 localhost pluto[72935]:   CAMELLIA_CTR            IKEv1:     ESP     IKEv2:     ESP           {256,192,*128}
Sep 13 14:23:38 localhost pluto[72935]:   CAMELLIA_CBC            IKEv1: IKE ESP     IKEv2: IKE ESP           {256,192,*128}  camellia
Sep 13 14:23:38 localhost pluto[72935]:   AES_GCM_16              IKEv1:     ESP     IKEv2: IKE ESP     FIPS  {256,192,*128}  aes_gcm, aes_gcm_c
Sep 13 14:23:38 localhost pluto[72935]:   AES_GCM_12              IKEv1:     ESP     IKEv2: IKE ESP     FIPS  {256,192,*128}  aes_gcm_b
Sep 13 14:23:38 localhost pluto[72935]:   AES_GCM_8               IKEv1:     ESP     IKEv2: IKE ESP     FIPS  {256,192,*128}  aes_gcm_a
Sep 13 14:23:38 localhost pluto[72935]:   AES_CTR                 IKEv1: IKE ESP     IKEv2: IKE ESP     FIPS  {256,192,*128}  aesctr
Sep 13 14:23:38 localhost pluto[72935]:   AES_CBC                 IKEv1: IKE ESP     IKEv2: IKE ESP     FIPS  {256,192,*128}  aes
Sep 13 14:23:38 localhost pluto[72935]:   SERPENT_CBC             IKEv1: IKE ESP     IKEv2: IKE ESP           {256,192,*128}  serpent
Sep 13 14:23:38 localhost pluto[72935]:   TWOFISH_CBC             IKEv1: IKE ESP     IKEv2: IKE ESP           {256,192,*128}  twofish
Sep 13 14:23:38 localhost pluto[72935]:   TWOFISH_SSH             IKEv1: IKE         IKEv2: IKE ESP           {256,192,*128}  twofish_cbc_ssh
Sep 13 14:23:38 localhost pluto[72935]:   NULL_AUTH_AES_GMAC      IKEv1:     ESP     IKEv2:     ESP     FIPS  {256,192,*128}  aes_gmac
Sep 13 14:23:39 localhost pluto[72935]:   NULL                    IKEv1:     ESP     IKEv2:     ESP           []
Sep 13 14:23:39 localhost pluto[72935]:   CHACHA20_POLY1305       IKEv1:             IKEv2: IKE ESP           [*256]  chacha20poly1305
Sep 13 14:23:39 localhost pluto[72935]: Hash algorithms:
Sep 13 14:23:39 localhost pluto[72935]:   MD5                     IKEv1: IKE         IKEv2:
Sep 13 14:23:39 localhost pluto[72935]:   SHA1                    IKEv1: IKE         IKEv2:             FIPS  sha
Sep 13 14:23:39 localhost pluto[72935]:   SHA2_256                IKEv1: IKE         IKEv2:             FIPS  sha2, sha256
Sep 13 14:23:39 localhost pluto[72935]:   SHA2_384                IKEv1: IKE         IKEv2:             FIPS  sha384
Sep 13 14:23:39 localhost pluto[72935]:   SHA2_512                IKEv1: IKE         IKEv2:             FIPS  sha512
Sep 13 14:23:39 localhost pluto[72935]: PRF algorithms:
Sep 13 14:23:39 localhost pluto[72935]:   HMAC_MD5                IKEv1: IKE         IKEv2: IKE               md5
Sep 13 14:23:39 localhost pluto[72935]:   HMAC_SHA1               IKEv1: IKE         IKEv2: IKE         FIPS  sha, sha1
Sep 13 14:23:39 localhost pluto[72935]:   HMAC_SHA2_256           IKEv1: IKE         IKEv2: IKE         FIPS  sha2, sha256, sha2_256
Sep 13 14:23:39 localhost pluto[72935]:   HMAC_SHA2_384           IKEv1: IKE         IKEv2: IKE         FIPS  sha384, sha2_384
Sep 13 14:23:39 localhost pluto[72935]:   HMAC_SHA2_512           IKEv1: IKE         IKEv2: IKE         FIPS  sha512, sha2_512
Sep 13 14:23:39 localhost pluto[72935]:   AES_XCBC                IKEv1:             IKEv2: IKE               aes128_xcbc
Sep 13 14:23:39 localhost pluto[72935]: Integrity algorithms:
Sep 13 14:23:39 localhost pluto[72935]:   HMAC_MD5_96             IKEv1: IKE ESP AH  IKEv2: IKE ESP AH        md5, hmac_md5
Sep 13 14:23:39 localhost pluto[72935]:   HMAC_SHA1_96            IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  sha, sha1, sha1_96, hmac_sha1
Sep 13 14:23:39 localhost pluto[72935]:   HMAC_SHA2_512_256       IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  sha512, sha2_512, sha2_512_256, hmac_sha2_512
Sep 13 14:23:39 localhost pluto[72935]:   HMAC_SHA2_384_192       IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  sha384, sha2_384, sha2_384_192, hmac_sha2_384
Sep 13 14:23:39 localhost pluto[72935]:   HMAC_SHA2_256_128       IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  sha2, sha256, sha2_256, sha2_256_128, hmac_sha2_256
Sep 13 14:23:39 localhost pluto[72935]:   HMAC_SHA2_256_TRUNCBUG  IKEv1:     ESP AH  IKEv2:         AH
Sep 13 14:23:39 localhost pluto[72935]:   AES_XCBC_96             IKEv1:     ESP AH  IKEv2: IKE ESP AH        aes_xcbc, aes128_xcbc, aes128_xcbc_96
Sep 13 14:23:39 localhost pluto[72935]:   AES_CMAC_96             IKEv1:     ESP AH  IKEv2:     ESP AH  FIPS  aes_cmac
Sep 13 14:23:39 localhost pluto[72935]:   NONE                    IKEv1:     ESP     IKEv2: IKE ESP     FIPS  null
Sep 13 14:23:39 localhost pluto[72935]: DH algorithms:
Sep 13 14:23:39 localhost pluto[72935]:   NONE                    IKEv1:             IKEv2: IKE ESP AH  FIPS  null, dh0
Sep 13 14:23:39 localhost pluto[72935]:   MODP1024                IKEv1: IKE ESP AH  IKEv2: IKE ESP AH        dh2
Sep 13 14:23:39 localhost pluto[72935]:   MODP1536                IKEv1: IKE ESP AH  IKEv2: IKE ESP AH        dh5
Sep 13 14:23:39 localhost pluto[72935]:   MODP2048                IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  dh14
Sep 13 14:23:39 localhost pluto[72935]:   MODP3072                IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  dh15
Sep 13 14:23:39 localhost pluto[72935]:   MODP4096                IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  dh16
Sep 13 14:23:39 localhost pluto[72935]:   MODP6144                IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  dh17
Sep 13 14:23:39 localhost pluto[72935]:   MODP8192                IKEv1: IKE ESP AH  IKEv2: IKE ESP AH  FIPS  dh18
Sep 13 14:23:39 localhost pluto[72935]:   DH19                    IKEv1: IKE         IKEv2: IKE ESP AH  FIPS  ecp_256, ecp256
Sep 13 14:23:39 localhost pluto[72935]:   DH20                    IKEv1: IKE         IKEv2: IKE ESP AH  FIPS  ecp_384, ecp384
Sep 13 14:23:39 localhost pluto[72935]:   DH21                    IKEv1: IKE         IKEv2: IKE ESP AH  FIPS  ecp_521, ecp521
Sep 13 14:23:39 localhost pluto[72935]: testing CAMELLIA_CBC:
Sep 13 14:23:39 localhost pluto[72935]:   Camellia: 16 bytes with 128-bit key
Sep 13 14:23:39 localhost pluto[72935]:   Camellia: 16 bytes with 128-bit key
Sep 13 14:23:39 localhost pluto[72935]:   Camellia: 16 bytes with 256-bit key
Sep 13 14:23:39 localhost pluto[72935]:   Camellia: 16 bytes with 256-bit key
Sep 13 14:23:39 localhost pluto[72935]: testing AES_GCM_16:
Sep 13 14:23:39 localhost pluto[72935]:   empty string
Sep 13 14:23:39 localhost pluto[72935]: NSS: AEAD decryption using AES_GCM_16_128 and PK11_Decrypt() failed (SECERR: 2 (0x2): security library: received bad data.)
Sep 13 14:23:39 localhost pluto[72935]: NSS: AEAD encryption using AES_GCM_16_128 and PK11_Encrypt() failed (SECERR: 2 (0x2): security library: received bad data.)
Sep 13 14:23:39 localhost pluto[72935]:   one block
Sep 13 14:23:39 localhost pluto[72935]: NSS: AEAD decryption using AES_GCM_16_128 and PK11_Decrypt() failed (SECERR: 2 (0x2): security library: received bad data.)
Sep 13 14:23:39 localhost pluto[72935]: NSS: AEAD encryption using AES_GCM_16_128 and PK11_Encrypt() failed (SECERR: 2 (0x2): security library: received bad data.)
Sep 13 14:23:39 localhost pluto[72935]:   two blocks
Sep 13 14:23:39 localhost pluto[72935]: NSS: AEAD decryption using AES_GCM_16_128 and PK11_Decrypt() failed (SECERR: 2 (0x2): security library: received bad data.)
Sep 13 14:23:39 localhost pluto[72935]: NSS: AEAD encryption using AES_GCM_16_128 and PK11_Encrypt() failed (SECERR: 2 (0x2): security library: received bad data.)
Sep 13 14:23:39 localhost pluto[72935]:   two blocks with associated data
Sep 13 14:23:39 localhost pluto[72935]: NSS: AEAD decryption using AES_GCM_16_128 and PK11_Decrypt() failed (SECERR: 2 (0x2): security library: received bad data.)
Sep 13 14:23:39 localhost pluto[72935]: NSS: AEAD encryption using AES_GCM_16_128 and PK11_Encrypt() failed (SECERR: 2 (0x2): security library: received bad data.)
Sep 13 14:23:39 localhost pluto[72935]: ABORT: ASSERTION FAILED: test_gcm_vectors(&ike_alg_encrypt_aes_gcm_16, aes_gcm_tests) (in test_ike_alg() at ike_alg_test.c:41)

**Comment by ptorrent** [comment]
Working better if I install apt-get install strongswan-starter

Now:
![image](https://user-images.githubusercontent.com/6083644/93018127-caef4280-f5cd-11ea-895c-2aaee1c41fa3.png)

**Comment by ptorrent** [comment]
Looks better with libreswan 3.30...

What a public nightmare...

![image](https://user-images.githubusercontent.com/6083644/93018945-f8d78580-f5d3-11ea-929d-1b547a30a298.png)

**Comment by letoams** [comment]
Ohhh

It is crashing on the unannounced nss library API change

Please upgrade libreswan or downgrade nss. If this happens with all packages up to date than dkg needs to rebuild the libreswan package against the latest nss.

Paul

**Comment by ptorrent** [comment]
Thanks for your answer ! You mean Libreswan 3.32 is an old version ?

**Comment by ptorrent** [comment]
After some reseach if I try:

ipsec auto --add l2tp-psk
030 message from whack contains bad string or key

https://bugzilla.redhat.com/show_bug.cgi?id=1345959

Is there a link between this issue and mine ?

**Comment by letoams** [comment]
Do you have two libreswan installs? One in /usr/local and one from a package install ?

**Comment by ptorrent** [comment]
I've installed libreswan with vpnsetup.sh and then I install it with apt-get install libreswan because I was not able to run it with the script.

"Please upgrade libreswan or downgrade nss." I don't know how to downgrade nss, so I tried to install last version...

**Comment by hwdsl2** [comment]
@ptorrent I believe @letoams was referring to the NSS 3.51 -> 3.52 issue mentioned in https://github.com/libreswan/libreswan/issues/342#issuecomment-631538563. However, you listed Debian 9 as your server's OS, which has NSS 3.26.2 (as of today) [1]. Therefore this NSS issue probably do NOT apply in your case.

Please don't use `apt-get` to install another copy of Libreswan, if you already used the VPN setup script to install. This will create two copies of both the binary (one in /usr/local and one from package install) and configuration, and cause issues.

To fix, please re-run the VPN setup script on a newly installed Debian system.

I'm closing this issue but if you have detailed logs (see [2]) regarding why Libreswan was crashing, please reply here.

[1] https://packages.debian.org/search?keywords=libnss3
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status
