### ISSUE TITLE
Working with Ubuntu 16.10

### ISSUE THREAD

**Issue by RomainBoulay** [hwdsl2/setup-ipsec-vpn#85]
Hey @hwdsl2,

First, thanks so much for sharing your script, that's a big help for a lot of people.

I know you specified the script works for `Ubuntu 16.04/14.04/12.04` but I just run it on a fresh install of `Ubuntu 16.10` and it seems to work like a charm. I just wanted to ping you in case you'd like to update your documentation.

Have a nice day and thanks again!
Romain

**Comment by hwdsl2** [comment]
@RomainBoulay You're very welcome. Thanks for letting us know. Yes the script may also work on other Ubuntu versions such as 16.10. However because most servers run Ubuntu LTS versions 16.04/14.04/12.04, I only mentioned those in the documentation.
