### ISSUE TITLE
问题：如何实现客户端与服务器互通

### ISSUE THREAD

**Issue by Caratacus** [hwdsl2/setup-ipsec-vpn#851]
**问题**
我在搭建setup-ipsec-vpn项目后，客户端访问服务器端是可以的，但是不可以通过服务器访问到客户端，有什么办法可以互通吗？麻烦解答下，或给一个思路。谢谢

**Comment by hwdsl2** [comment]
@Caratacus 你好！通过服务器端访问客户端的话，可以通过 VPN 时自动分配的 VPN 内部 IP 来实现。要找到该 IP，请查看你的客户端上的 VPN 网络状态。比如 IPsec/L2TP 模式可能分配区间 192.168.42.10-192.168.42.250。找到之后使用该 IP 访问客户端。如果不能访问，可能是客户端上的防火墙禁止了通信。

**Comment by Caratacus** [comment]
@hwdsl2 我用了两台机器（客户端简称A、B）连上VPN后，分配的IP地址分别是192.168.42.10、192.168.42.11，服务器IP地址为192.168.0.15，服务器ping A、B都不通，但是A ping B、B ping A是可以通的

**Comment by Caratacus** [comment]
是我自己的问题，抱歉

**Comment by adcen0107** [comment]
想问一下：部署ipsec server时，是不是要保证server的公网IP就在docker同一个机器上？或者保证公网IP收到的500或4500的包能够被映射到ipsec server所在的docker ?

**Comment by hwdsl2** [comment]
@adcen0107 关于你的问题，可以映射到docker容器即可。

**Comment by adcen0107** [comment]
就是说，如果docker所在的机器分配的是局域网IP，需要经过1个或多个路由器才能连到公网。这种部署除非沿途的所有路由器都做端口500/4500的映射，否则client是连不到server的。对吧？

**Comment by hwdsl2** [comment]
@adcen0107 是的。

**Comment by adcen0107** [comment]
明白了，谢谢解答！
