### ISSUE TITLE
树莓派4B ubuntu20.04 64位无法安装

### ISSUE THREAD

**Issue by Crazydear** [hwdsl2/setup-ipsec-vpn#852]
**任务列表**

- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [x] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [ ] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [ ] 这个 bug 是关于 VPN 安装脚本，而不是 IPsec VPN 本身

**问题描述**
硬件：树莓派4B 4G版 V1.2
操作系统：Linux Raspi 5.4.0-1018-raspi #20-Ubuntu SMP Sun Sep 6 05:11:16 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

**重现步骤**
重现该 bug 的步骤：

1. 下载脚本
2. 运行setupvpn.sh

报错：
root@Raspi:~/setup-ipsec-vpn# sudo sh vpnsetup.sh 
Error: Wireless interface 'wlan0' detected. DO NOT run this script on your PC or Mac!

**Comment by Scottpedia** [comment]
你好！目前来看的话是因为脚本检测到了网络接口`wlan0`（树莓派的无线网卡），从而认为该平台是一个消费者产品（比如MacBook或者Lenovo笔记本）。您可以尝试将树莓派用网线连接到互联网，并且`sudo ifdown wlan0`来临时禁用无线网络接口。然后重新执行脚本。希望这个能帮到你！

**Comment by Crazydear** [comment]
谢谢，问题解决了
