### ISSUE TITLE
centos 7 4500端口和5000端口0.0.0.0没有监听

### ISSUE THREAD

**Issue by ffpepwowa** [hwdsl2/setup-ipsec-vpn#853]
系统： centos 7 
采用一键安装模式
防火墙已关闭

安装完成后，查看netstat -ano|grep 500
`udp        0      0 127.0.0.1:4500          0.0.0.0:*
udp        0      0 192.168.1.162:4500      0.0.0.0:*
udp        0      0 127.0.0.1:500           0.0.0.0:*
udp        0      0 192.168.1.162:500       0.0.0.0:*
udp6       0      0 fd1d:2316:321d:0:9d:500 :::*
udp6       0      0 fd1d:2316:321d::44a:500 :::*
udp6       0      0 ::1:500                 :::*
`

发现500端口和4500端口均属于127.0.0.1和192.168.1.162，而不是0.0.0.0
尝试利用本机telnet 127.0.0.1 500和4500
发现端口没有开放
`
[root@localhost vpn]# telnet 127.0.0.1 500
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
`

**Comment by ffpepwowa** [comment]
利用其它内网机器访问192.168.1.162的500端口和4500端口，均提示未开放，防火墙已关闭。内部网络处于互通状态，SSH也是可以连上的。

**Comment by Cocogin** [comment]
你好，我现在也遇到这个问题，请问你解决这个问题了吗？可否赐教一下谢谢！

**Comment by ffpepwowa** [comment]
> 你好，我现在也遇到这个问题，请问你解决这个问题了吗？可否赐教一下谢谢！

个人能力有限，无法解决，后来换了另外一个vpn，softether

**Comment by Cocogin** [comment]
我昨晚解决啦 我是将DNS配置到了google的8.8.8.8

**Comment by kazuko** [comment]
> > 你好，我现在也遇到这个问题，请问你解决这个问题了吗？可否赐教一下谢谢！
> 
> 个人能力有限，无法解决，后来换了另外一个vpn，softether

这个不错。谢了

**Comment by hwdsl2** [comment]
@ffpepwowa 你好！Libreswan 监听特定的 IP 地址比如 192.168.1.162:500，而不是 0.0.0.0:500，这个是正常的，在我的 CentOS 7 测试中没有发现问题，可以正常连接。你再检查一下是不是你的网络的问题。
