### ISSUE TITLE
试过方法了  运行了脚本  还是没有日志 谁能给个 详细的步骤呀

### ISSUE THREAD

**Issue by ylmcr7** [hwdsl2/setup-ipsec-vpn#854]
[root@ylm_aliyun log]# cd ppp/
[root@ylm_aliyun ppp]# ls
[root@ylm_aliyun ppp]# ls
[root@ylm_aliyun ppp]#

**Comment by hwdsl2** [comment]
@ylmcr7 请参见 https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E6%A3%80%E6%9F%A5%E6%97%A5%E5%BF%97%E5%8F%8A-vpn-%E7%8A%B6%E6%80%81
