### ISSUE TITLE
User Authentication error on Mac OS X 

### ISSUE THREAD

**Issue by bhatti4says** [hwdsl2/setup-ipsec-vpn#856]
Have followed auto script instructions and setup Ikev2 server. Successfully ran before XAUTH & L2TP in a productions environment, Wanted to try Ikev2 but its giving User Authentication error. How to debug or logs? I can paste here. Authentication is CA everything i followed don't know whats wrong with it. Please help

**Comment by bhatti4says** [comment]
this is logs i just extracted 

`Sep 26 10:48:43 VPNSRVR pluto[2481]: loading root certificate cache
Sep 26 10:48:43 VPNSRVR pluto[2481]: "ikev2-cp"[16] 178.80.161.193 #58: certificate verified OK: O=IKEv2 VPN,CN=SAMABR
Sep 26 10:48:43 VPNSRVR pluto[2481]: "ikev2-cp"[16] 178.80.161.193 #58: switched from "ikev2-cp"[16] 178.80.161.193 to "ikev2-cp"
Sep 26 10:48:43 VPNSRVR pluto[2481]: "ikev2-cp"[17] 178.80.161.193 #58: deleting connection "ikev2-cp"[16] 178.80.161.193 instance with peer 178.80.161.193 {isakmp=#0/ipsec=#0}
Sep 26 10:48:43 VPNSRVR pluto[2481]: "ikev2-cp"[17] 178.80.161.193 #58: IKEv2 mode peer ID is ID_FQDN: '@SAMABR'
Sep 26 10:48:43 VPNSRVR pluto[2481]: "ikev2-cp"[17] 178.80.161.193 #58: Authenticated using RSA with IKEv2_AUTH_HASH_SHA1
Sep 26 10:48:43 VPNSRVR pluto[2481]: "ikev2-cp"[17] 178.80.161.193: local ESP/AH proposals (IKE_AUTH responder matching remote ESP/AH proposals):
Sep 26 10:48:43 VPNSRVR pluto[2481]: "ikev2-cp"[17] 178.80.161.193:   1:ESP=AES_GCM_C_128+AES_GCM_C_256-NONE-NONE-DISABLED
Sep 26 10:48:43 VPNSRVR pluto[2481]: "ikev2-cp"[17] 178.80.161.193:   2:ESP=AES_CBC_128-HMAC_SHA1_96-NONE-DISABLED
Sep 26 10:48:43 VPNSRVR pluto[2481]: "ikev2-cp"[17] 178.80.161.193:   3:ESP=AES_CBC_256-HMAC_SHA1_96-NONE-DISABLED
Sep 26 10:48:43 VPNSRVR pluto[2481]: "ikev2-cp"[17] 178.80.161.193:   4:ESP=AES_CBC_128-HMAC_SHA2_256_128-NONE-DISABLED
Sep 26 10:48:43 VPNSRVR pluto[2481]: "ikev2-cp"[17] 178.80.161.193:   5:ESP=AES_CBC_256-HMAC_SHA2_256_128-NONE-DISABLED
Sep 26 10:48:43 VPNSRVR pluto[2481]: "ikev2-cp"[17] 178.80.161.193 #58: proposal 4:ESP=AES_CBC_128-HMAC_SHA1_96-DISABLED SPI=0ccd5411 chosen from remote proposals 1:ESP:ENCR=AES_CBC_256;INTEG=HMAC_SHA2_256_128;ESN=DISABLED[first-match] 2:ESP:ENCR=AES_CBC_256;INTEG=HMAC_SHA2_256_128;ESN=DISABLED 3:ESP:ENCR=AES_CBC_256;INTEG=HMAC_SHA2_256_128;ESN=DISABLED 4:ESP:ENCR=AES_CBC_128;INTEG=HMAC_SHA1_96;ESN=DISABLED[better-match] 5:ESP:ENCR=3DES;INTEG=HMAC_SHA1_96;ESN=DISABLED
Sep 26 10:48:43 VPNSRVR pluto[2481]: "ikev2-cp"[17] 178.80.161.193 #58: received unsupported NOTIFY v2N_NON_FIRST_FRAGMENTS_ALSO
Sep 26 10:48:43 VPNSRVR pluto[2481]: "ikev2-cp"[17] 178.80.161.193 #59: negotiated connection [0.0.0.0-255.255.255.255:0-65535 0] -> [192.168.43.19-192.168.43.19:0-65535 0]
Sep 26 10:48:43 VPNSRVR pluto[2481]: "ikev2-cp"[17] 178.80.161.193 #59: STATE_V2_IPSEC_R: IPsec SA established tunnel mode {ESP/NAT=>0x0ccd5411 <0x75e8fbfd xfrm=AES_CBC_128-HMAC_SHA1_96 NATOA=none NATD=178.80.161.193:4500 DPD=active}
Sep 26 10:48:43 VPNSRVR pluto[2481]: "ikev2-cp"[17] 178.80.161.193 #58: received duplicate IKE_AUTH message request (Message ID 1, fragment 1); retransmitting response
`

**Comment by letoams** [comment]
The client doesn’t seem to receive the last packet? The server completed and installed the tunnel.

So either:

Client did not get packet ?

Client got packet, didn’t like it and erroneously retransmitted its packet in the hope of a better answer (wrong behaviour but some clients do this)

**Comment by bhatti4says** [comment]
So any idea how to fix this??

**Comment by hwdsl2** [comment]
@bhatti4says Hello! From your logs, it looks like the server successfully established the VPN connection, but the client disconnected. This behavior was previously observed in cases such as "not importing the CA certificate, only the client certificate on iOS or Mac OS X", or "did not configure certificate trust settings correctly on Mac OS X".

To fix, follow the instructions in [1] and make sure those steps are completed correctly.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#os-x-macos
