### ISSUE TITLE
Can you connect IPSEC_PSK directly without setting IPSEC_PSK?

### ISSUE THREAD

**Issue by LPink777** [hwdsl2/setup-ipsec-vpn#859]
能不设置IPSEC_PSK直接连吗，有的软件没有IPSEC_PSK的输入项，然后连不上？

Can you connect IPSEC_PSK directly without setting IPSEC_PSK? Some software does not have the input item of IPSEC_PSK, and then cannot connect

**Comment by hwdsl2** [comment]
@LPink777 Hello! Using L2TP without IPsec is not supported, because network traffic is not encrypted at all in this mode, which defeats the purpose of using a VPN.
