### ISSUE TITLE
VPN not working after iOS 14 upgrade

### ISSUE THREAD

**Issue by jackie1100** [hwdsl2/setup-ipsec-vpn#862]
Hi,
I've been using https://github.com/mobilejazz/docker-ipsec-vpn-server for 2 years and recently got to know that its a fork or derived from this project. Thanks for the amazing work, I'm sure thousands or more like me benefit from this.
I've reported this issue: https://github.com/mobilejazz/docker-ipsec-vpn-server/issues/25 but while going through the troubleshooting section, realized that their troubleshooting section points to this project, hence thought to document here as it might be a better place.
Issue: Since iOS 14 upgrade, the VPN wasn't connecting, Android was fine. Apple suggested with changing the SHA 256 compatibility mode: https://developer.apple.com/forums/thread/660499. My env is a simple VPS with the above github ipsec-vpn-server in a docker container. Reading the troubleshooting, I came across changing sha2-truncbug to "no" in /etc/ipsec.conf and that did the trick. But I'm not sure if this is just a band-aid because if I restart the container, the old value of sha2-truncbug=yes comes back. Also, if I restart ipsec and xl2tpd, the original value comes back. 
I also read through https://github.com/hwdsl2/setup-ipsec-vpn/issues/638 which mentions that just changing this value might affect Android clients, but in my case both Android and IOS are working, so just wanted to clarify if this is the right fix.

I'm new to github and would be more than happy to contribute and help others as I know many people would be facing this issue, but need some initial help in figuring out and navigating the right github workflow.
P.S. The https://github.com/mobilejazz/docker-ipsec-vpn-server  project is for multi-user which is very handy for a lot of people, not sure if your docker project: https://github.com/hwdsl2/docker-ipsec-vpn-server is multi-user or not?
Thanks

**Comment by martyndix** [comment]
I’m having the same issue with iOS when connecting to the VPN service running on my RPi 3. If anyone can help it would be much appreciated.

**Comment by jackie1100** [comment]
> I’m having the same issue with iOS when connecting to the VPN service running on my RPi 3. If anyone can help it would be much appreciated.
@martyndix: If you're running ipsec in your RPi 3, you can change the value of sha2-truncbug to "no" from "yes" and restart ipsec. It should work after that

**Comment by martyndix** [comment]
> I’m having the same issue with iOS when connecting to the VPN service running on my RPi 3. If anyone can help it would be much appreciated.
> @martyndix: If you're running ipsec in your RPi 3, you can change the value of sha2-truncbug to "no" from "yes" and restart ipsec. It should work after that

I’ve just checked and it already says sha2-truncbug=yes so not sure what I should do. Any advice please? Thanks for all your help!

**Comment by jackie1100** [comment]
@martyndix : So you need to edit ipsec.conf with whatever editor you have (vim, emacs, nano, etc.). Open the file ipsec.conf in your editor, go to the line with sha2-truncbug=yes, change yes to no and save the file, then restart ipsec.

**Comment by martyndix** [comment]
> @martyndix : So you need to edit ipsec.conf with whatever editor you have (vim, emacs, nano, etc.). Open the file ipsec.conf in your editor, go to the line with sha2-truncbug=yes, change yes to no and save the file, then restart ipsec.

Brilliant! It works. Thanks so very much!

**Comment by liweizhi** [comment]
@jackie1100 I use the docker image from https://github.com/hwdsl2/docker-ipsec-vpn-server. Now I met the same issue with IOS. You said we can edit the value sha2-truncbug of file ipsec.conf. But how can I edit the value in a docker container? I used command "docker exec -it ipsec-vpn-server env TERM=xterm bash -l" to login the container, while there is no editor (vim or vi) installed on the container...

**Comment by jackie1100** [comment]
@liweizhi sorry I didn't look at it for a couple days. Yes you're right, if you do a docker restart it will load the original config, which I think is how a container is supposed to behave. I noted this too and ended up doing just an ipsec restart for now so my VPN could work. I think what needs to be done is edit the docker container itself via docker commit or something. I'm not too familiar with docker hence didn't mess with it, but I plan to figure it out in a few days hopefully and will then provide an update here.

**Comment by RonanDex** [comment]
把你本地的镜像删除，然后重新运行新的镜像，即可解决。@jackie1100

**Comment by yaukampiu** [comment]
sha2-truncbug is already set to no in the vpnsetup.sh   
But my IOS14 still cannot connect.  Any solution?

**Comment by jackie1100** [comment]
@yaukampiu check the value of sha2-truncbug in ipsec.conf and change to "no" there

**Comment by yaukampiu** [comment]
> @yaukampiu check the value of sha2-truncbug in ipsec.conf and change to "no" there

it is already set to no in my ipsec.conf under the "conn shared" session.  But it does not work for IOS14 in my case.
sha2-truncbug=no

**Comment by hwdsl2** [comment]
@jackie1100 Thanks for reporting this issue. The correct fix is indeed setting `sha2-truncbug` to `no` in `/etc/ipsec.conf`, and restart the IPsec service. See [1]. Note that `sha2-truncbug=no` has been the default value since Sep. 22, 2019 for both the VPN setup scripts [2] and the Docker image [3]. If you use the Docker image, please upgrade to the latest version by following these instructions [4].

For your other question, yes the Docker image [5] does support multiple VPN users.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ios-13-and-macos-1015
[2] https://github.com/hwdsl2/setup-ipsec-vpn/commit/3353888ee908c5365a36cd7f3d25bbb0651054aa
[3] https://github.com/hwdsl2/docker-ipsec-vpn-server/commit/57fa056deb35d19913ee795950d24746c9c85d87
[4] https://github.com/hwdsl2/docker-ipsec-vpn-server#update-docker-image
[5] https://github.com/hwdsl2/docker-ipsec-vpn-server
