### ISSUE TITLE
IPv6 Public IP

### ISSUE THREAD

**Issue by LiohMoeller** [hwdsl2/setup-ipsec-vpn#863]
I have an IPv6 only system (no IPv4 available here). The automatic determination of the IPv6 address does not work, neither setting VPN_PUBLIC_IP to my IPv6 address in the ENV.

**Comment by saudiqbal** [comment]
I would like to see some IPv6 support as well.

**Comment by hohl** [comment]
Yes, this script is an amazing tool, but it is a pity that it seems to setup the VPN with IPv4 support only.

**Comment by hwdsl2** [comment]
Thank you for the suggestions. You are correct that the VPN setup scripts does not yet support IPv6. It's not yet clear to me how to add proper IPv6 support in the Libreswan configuration, for road warrior scenarios with IPv6 only VPN servers. @letoams Any suggestion?
