### ISSUE TITLE
WinCE 7 connection problem

### ISSUE THREAD

**Issue by leonardospeca** [hwdsl2/setup-ipsec-vpn#864]
Hi, I like so much this vpn server, but I have a problem connecting from a WinCE 7 Panel.
I have the problem "Windows Error 809", and for CE I found [this link](https://support.microsoft.com/it-it/help/3046488/fix-you-cannot-connect-to-an-l2tp-ipsec-server-behind-a-nat-t-device-i) on Microsoft to edit the **AssumeUDPEncapsulationContextOnSendRule** key, But without any result.
The only l2tp server that i'm able to connect from that WinCE is SoftEther, that for some reason don't have need to change anything on the registry. Do you know something about that?

**Comment by hwdsl2** [comment]
@leonardospeca Hello! Unfortunately Windows CE has not been tested for this project as a VPN client.
