### ISSUE TITLE
/etc/ppp/chap_sercerts AND /etc/ipsec.secrets securty

### ISSUE THREAD

**Issue by ptorrent** [hwdsl2/setup-ipsec-vpn#865]
Hello there !

Is there a way to store user's password in chap_secrets in md5 or something crypted ?

Is there a way to have multiple ipsec secrets ? 

Thanks for your help !

**Comment by hwdsl2** [comment]
@ptorrent Hello! AFAIK chap_secrets file cannot store md5 or encrypted passwords. For ipsec.secrets, please refer to [1]. There is a concept of "ID selector" but setting multiple secrets is uncommon in "road warrior" VPN configurations.

[1] https://wiki.strongswan.org/projects/strongswan/wiki/Ipsecsecrets
