### ISSUE TITLE
Windows 10 L2TP connecting...

### ISSUE THREAD

**Issue by ptorrent** [hwdsl2/setup-ipsec-vpn#866]
Hello there,

I'm trying to use L2TP connection on my windows 10 ... I'm stuck on "Connecting to server" (no log server side).

It's working very well on IOS /Android...

I made the  one-time registry change... I reset all my connections "reset network connection" etc... 

Removing those interfaces:
![image](https://user-images.githubusercontent.com/6083644/96024964-cc25c080-0e54-11eb-931f-530bd4a17650.png)

![image](https://user-images.githubusercontent.com/6083644/96025154-0abb7b00-0e55-11eb-8757-7a1937e3e7ec.png)

This looks like a known problem with Windows 10 (I tried everything on google) . But none of the "solutions" work for me.

I'm desperate, does Windows 10 support L2TP? 

PPTP works fine.

**Comment by ptorrent** [comment]
I'm updating my windows, maybe I'm lucky..

**Comment by ptorrent** [comment]
Ok got some news. It's better after windows update, I've some log on the server..

![image](https://user-images.githubusercontent.com/6083644/96032265-b917ee00-0e5e-11eb-9024-5c5d26b64206.png)

**Comment by thewebcapsule** [comment]
Were you able to solve it? I'm stuck with the same issue.

**Comment by ptorrent** [comment]
yes , test with this command:

ipsec verify 

![image](https://user-images.githubusercontent.com/6083644/96704685-a8063a00-1394-11eb-9d4d-6e18cba10527.png)

Be sure that everything is running with this command:

 ps aux | grep ipsec
 ps aux | grep pluto

**Comment by thewebcapsule** [comment]
Should i do it whilst the VPN is stuck at connecting?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hwdsl2** [comment]
Looks like this issue is solved. If you encountered issues with the VPN stuck on "connecting" on Windows 10, also see this solution:  
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#windows-10-connecting
