### ISSUE TITLE
Question: How many maximum users can be connected to 1 server at same time?

### ISSUE THREAD

**Issue by hassaan-dev** [hwdsl2/setup-ipsec-vpn#868]
Hi,

I want to know is there is any limit of connecting maximum user at same time with server?

For specification let's suppose.

I have dedicated hardware with 32GB RAM and 1 GB of internet port. Then how many users can be connected?

I actually don't know, what is matter most for connected users. Is it RAM or Internet speed or what

Can someone please guide me in this?

**Comment by letoams** [comment]
Ensure you are using AES_GCM and ensure to have libreswan 3.31 or better. Then your performance is limited by the amount of traffic your clients are doing and you should be able to fill your 1gbps (or 10gbps). 

You can enable plutodebug=cpu-usage if you suspect libreswan is using too much CPU to get timing debugging information

**Comment by pauloesteban** [comment]
I have Libreswan 3.32 on server.

Can anyone help me to ensure `AES_GCM`? I have this.

Server:
```
config setup
  virtual-private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12,%v4:!192.168.42.0/24,%v4:!192.168.43.0/24
  protostack=netkey
  interfaces=%defaultroute
  uniqueids=no

conn shared
  left=%defaultroute
  leftid=@vpn.devsu.com
  right=%any
  encapsulation=yes
  authby=secret
  pfs=no
  rekey=no
  keyingtries=5
  dpddelay=30
  dpdtimeout=120
  dpdaction=clear
  ikev2=never
  ike=aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1,aes256-sha2;modp1024,aes128-sha1;modp1024
  phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes256-sha2_512,aes128-sha2,aes256-sha2
  sha2-truncbug=no

conn l2tp-psk
  auto=add
  leftprotoport=17/1701
  rightprotoport=17/%any
  type=transport
  phase2=esp
  also=shared 
```

Client
```
onn %default
  ikelifetime=60m
  keylife=20m
  rekeymargin=3m
  keyingtries=1
  keyexchange=ikev1
  authby=secret
  ike=aes128-sha1-modp2048!
  esp=aes128-sha1-modp2048!

conn myvpn
  keyexchange=ikev1
  left=%defaultroute
  auto=add
  authby=secret
  type=transport
  leftprotoport=17/1701
  rightprotoport=17/1701
  right=vpn.devsu.com

```

**Comment by letoams** [comment]
If your clients do L2TP they most likely don’t do aes-gcm. L2TP is ancient

**Comment by hwdsl2** [comment]
Thanks @letoams!
