### ISSUE TITLE
How to forward port from client ?

### ISSUE THREAD

**Issue by pethot** [hwdsl2/setup-ipsec-vpn#869]
I use this command not work
```iptables -t nat -A PREROUTING -d $(my public ip) -p tcp --dport 443 -j DNAT --to-dest 192.168.42.10:443```
```iptables -t filter -A INPUT -p tcp -d 192.168.42.10 --dport 443 -j ACCEPT```

**Comment by eduardomendes2** [comment]
iptables -I FORWARD 2 -i eth0 -o ppp+ -p tcp --dport 443 -j ACCEPT
iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 443 -j DNAT --to 192.168.42.10:443

**Comment by pethot** [comment]
> iptables -I FORWARD 2 -i eth0 -o ppp+ -p tcp --dport 443 -j ACCEPT
> iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 443 -j DNAT --to 192.168.42.10:443

I will try it

**Comment by pethot** [comment]
> iptables -I FORWARD 2 -i eth0 -o ppp+ -p tcp --dport 443 -j ACCEPT
> iptables -A PREROUTING -t nat -i eth0 -p tcp --dport 443 -j DNAT --to 192.168.42.10:443

just try it and not work.

**Comment by pethot** [comment]
someone can help me plz 😢😢😢

**Comment by pethot** [comment]
😥😥😥😥😥

**Comment by hwdsl2** [comment]
@pethot Hello! The IPTables commands that @eduardomendes2 mentioned look correct. This is only applicable to IPsec/L2TP mode. You will need to replace `eth0` with the (Internet) network interface of your VPN server, and replace 192.168.42.10 with the internal VPN IP of your VPN client. You can find this IP in your VPN client's connection status.

**Comment by pethot** [comment]
thanks I will try again on different server provider

**Comment by pethot** [comment]
I connect l2tp on my mikrotik and forward the port on mikrotik. does it problem from the cross platform ?

**Comment by 4310V343k** [comment]
Hello
I'm trying to accomplish the same thing pethot tried and it didn't work
Commands i used:
```
iptables -I FORWARD 2 -i enp0s3 -o ppp+ -p tcp --dport 56694 -j ACCEPT
iptables -A PREROUTING -t nat -i enp0s3 -p tcp --dport 56694 -j DNAT --to 192.168.42.10:56694
```
Oracle VCN Rules: https://i.imgur.com/1TLAsAH.png

After typing in the command i didn't see changes in `iptables --list`
