### ISSUE TITLE
I need VPN site-multisite is possible?

### ISSUE THREAD

**Issue by jchelp** [hwdsl2/setup-ipsec-vpn#870]
**Checklist**

- [ ] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [ ] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [ ] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [ ] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [ ] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [ ] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
A clear and concise description of your enhancement request.

**Is your enhancement request related to a problem? Please describe.**
(If applicable) A clear and concise description of what the problem is.

**Additional context**
Add any other context about the enhancement request here.

**Comment by jchelp** [comment]
It is possible to connect the vpn site-site with mikrotik and the vpn server to access the stations behind mikrotik, can you indicate the necessary changes?

**Comment by jchelp** [comment]
Is it possible to add a route to the server when the customer connects to the vpn?

**Comment by letoams** [comment]
> 
> On Oct 21, 2020, at 23:11, José Carlos Costa <notifications@github.com> wrote:
> 
> ﻿
> Is it possible to add a route to the server when the customer connects to the vpn?
> 
Normally routes are not needed. You cannot route arbitrary traffic over the VPN. What are you trying to do ?

**Comment by jchelp** [comment]
I was able to use this solution to create the route when the vpn user connects:

The final step is to add a route to each router's LAN when it connects.
There is a file for running commands when PPP goes up or down. On CentOS it is located at /etc/ppp/ip-up.local or / etc / ppp / ip-up

Adding the following lines does the trick:

#! / bin / bash

case "$ 5" in
        172.16.4.200)
                / sbin / route add -net 172.16.3.64/26 gw 172.16.4.200
                ;;
        172.16.4.201)
                / sbin / route add -net 172.16.3.128/26 gw 172.16.4.201
                ;;
        *)
esac
