### ISSUE TITLE
VPN not working on Windows10, working well on Android

### ISSUE THREAD

**Issue by daywalkerd** [hwdsl2/setup-ipsec-vpn#872]
**Describe the issue**
installed VPN using script, AWS EC2, working well on android phone, but windows10 not working

Windows10 can ping google, but cant surf on the web;
sometimes can log into youtube, but the video is not working (only loading, can see some preview imagines)

**Logs**
Run following commands on server:

grep pluto /var/log/auth.log
grep xl2tpd /var/log/syslog

ERROS as follows:

Oct 25 16:29:39 ip-17         pluto[14769]: "l2tp-psk"[26] 112.2.226.60 #55: ERROR: netlink response for Del SA esp.caa700da@112.2.226.60 included errno 3: No such process
Oct 25 16:29:39 ip-17         pluto[14769]: "l2tp-psk"[26] 112.2.226.60 #55: ERROR: netlink response for Del SA esp.d08b073c@17             included errno 3: No such process
Oct 25 16:29:39 ip-17         pluto[14769]:  #55: deleting connection "l2tp-psk"[26] 112.2.226.60 instance with peer 112.2.226.60 {isakmp=#0/ipsec=#0}

What should i do next?

**Comment by daywalkerd** [comment]
Tried these code for solving Andoid MTS/MSS issues, still not working:

iptables -t mangle -A FORWARD -m policy --pol ipsec --dir in \
  -p tcp -m tcp --tcp-flags SYN,RST SYN -m tcpmss --mss 1361:1536 \
  -j TCPMSS --set-mss 1360
iptables -t mangle -A FORWARD -m policy --pol ipsec --dir out \
  -p tcp -m tcp --tcp-flags SYN,RST SYN -m tcpmss --mss 1361:1536 \
  -j TCPMSS --set-mss 1360

echo 1 > /proc/sys/net/ipv4/ip_no_pmtu_disc

**Comment by hwdsl2** [comment]
@daywalkerd Hello! It looks like you used IPsec/L2TP mode, which is probably not affected by the Android MTU/MSS issue. However, on the other hand, the symptoms you described may be MTU/MSS related. Not sure about the errors in your logs.

It could also be network issues between your VPN client and VPN server. You may give IKEv2 mode a try, to see if it works fine for you.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md
