### ISSUE TITLE
For those who encountered "parameter is incorrect" error (参数错误) for Windows 10 ikev2

### ISSUE THREAD

**Issue by ininex** [hwdsl2/setup-ipsec-vpn#873]
Just figured out the solution by referencing issues from another repo:
**Clear Network Cache & Reset All Adapters => everything will work like a charm :)**
Reference: https://github.com/trailofbits/algo/issues/1051#issue-348033760

This only applies to windows 10 with IKEV2 & p12 setup

**Comment by hwdsl2** [comment]
Thanks for the suggestions @ininex!
