### ISSUE TITLE
About Ipsec Addresspool

### ISSUE THREAD

**Issue by kamalsust** [hwdsl2/setup-ipsec-vpn#874]
**Describe the issue**
I have installed this script successfully. After running couple of hour I can't connect ot VPN Server from iOS client. 
It's seems to be an issue of ip_addresspool. I have found following comments from libreswan addrespool implementation 

/*
 * A lease is an assignment of a single address from a particular pool.
 *
 * Leases are shared between appropriate connections.
 *
 * Because leases are shared, they are reference-counted.
 * (Since we don't (yet?) free leases that could be shared,
 * we don't actually need reference counting.)
 *
 * When a lease ends, if it could not be shared, it is freed.
 * Otherwise it "lingers" so that the same client (based on ID) can later
 * be assigned the same address from the pool.
 *
 * In the future we may implement code to delete a lingering lease to free
 * the address if there is no free address in the pool.
 *
 * Life cycle:
 *
 * - created by lease_an_address if an existing or lingering lease for the
 *   same thatid isn't found.
 *
 * - released (to linger or freed) by rel_lease_addr.
 *
 * - current code never frees a lease that could be shared.
 *   ??? This constitutes a leak.
 */
which means when addresspool would be full then it wouldn't clear it's unused pool.  
How do i solve the problem or how do i increase the addresspool also.

**To Reproduce**
I am serving multipool user using same username and password. After running sometimes the addresspool goes to be full.

**Expected behavior**
Then client couldn't connect to server. 

**Logs**
pluto[1040425]: "xauth-psk"[15812] 213.205.241.87 #16507: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 inte>
pluto[1040425]: "xauth-psk"[15812] 213.205.241.87 #16507: XAUTH: Sending Username/Password request (MAIN_R3->XAUTH_R0)
pluto[1040425]: "xauth-psk"[15812] 213.205.241.87 #16507: XAUTH: password file authentication method requested to authenticate user 'vpnuser'
pluto[1040425]: "xauth-psk"[15812] 213.205.241.87 #16507: XAUTH: password file (/etc/ipsec.d/passwd) open.
pluto[1040425]: "xauth-psk"[15812] 213.205.241.87 #16507: XAUTH: success user(vpnuser:xauth-psk)
pluto[1040425]: "xauth-psk"[15812] 213.205.241.87 #16507: XAUTH: User vpnuser: Authentication Successful
pluto[1040425]: "xauth-psk"[15812] 213.205.241.87 #16507: XAUTH: xauth_inR1(STF_OK)
pluto[1040425]: "xauth-psk"[15812] 213.205.241.87 #16507: STATE_MAIN_R3: sent MR3, ISAKMP SA established {auth=PRESHARED_KEY cipher=AES_CBC_256 inte>
pluto[1040425]: "xauth-psk"[15812] 213.205.241.87 #16507: lease_an_address failure no free address in addresspool
pluto[1040425]: "xauth-psk"[15812] 213.205.241.87 #16507: state transition function for STATE_MAIN_R3 had internal error
lines 1-23/23 (END)

**Server**
- OS: Ubuntu 20.04/18.04

**Client **
- VPN mode: [IPsec]

**Additional context**
Here is my ipsec.conf file details 
conn shared
  left=%defaultroute
  leftid=103.230.173.152
  right=%any
  encapsulation=yes
  authby=secret
  pfs=no
  rekey=no
  keyingtries=5
  dpddelay=30
  dpdtimeout=120
  dpdaction=clear
  ikev2=never
  ike=aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1,aes256-sha2;modp1024,aes128-sha1;modp1024
  phase2alg=aes_gcm-null,aes128-sha1,aes256-sha1,aes256-sha2_512,aes128-sha2,aes256-sha2
  sha2-truncbug=no

conn l2tp-psk
  auto=add
  leftprotoport=17/1701
  rightprotoport=17/%any
  type=transport
  phase2=esp
  also=shared

conn xauth-psk
  auto=add
  leftsubnet=0.0.0.0/0
  rightaddresspool=192.168.43.10-192.168.43.250
  modecfgdns="8.8.8.8 8.8.4.4"
  leftxauthserver=yes
  rightxauthclient=yes
  leftmodecfgserver=yes
  rightmodecfgclient=yes
  modecfgpull=yes
  xauthby=file
  ike-frag=yes
  cisco-unity=yes
  also=shared

include /etc/ipsec.d/*.conf

If I increse the rightaddresspool like 192.168.43.250 to 192.168.83.250 then client can connect to server but no internet access. 
Some times I get following as Ipsec Service log:

pluto[1040425]: "xauth-psk"[15838] 213.205.241.87 #16522:   them: 213.205.241.87[%any,+MC+XC+S=C]===192.168.43.145/32
pluto[1040425]: "xauth-psk"[15838] 213.205.241.87 #16522: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 tunnel mode {ESP/NAT=>>
pluto[1040425]: "xauth-psk"[15838] 213.205.241.87 #16522: STATE_QUICK_R2: IPsec SA established tunnel mode {ESP/NAT=>0x03f948ad <0x00b16fc5 xfrm=AES>
pluto[1040425]: "xauth-psk"[15836] 89.189.188.111 #16520: STATE_XAUTH_R0: retransmission; will wait 16 seconds for response
pluto[1040425]: "xauth-psk"[15836] 89.189.188.111 #16520: XAUTH: Sending Username/Password request (XAUTH_R0->XAUTH_R0)
pluto[1040425]: "xauth-psk"[15836] 89.189.188.111 #16520: STATE_XAUTH_R0: retransmission; will wait 32 seconds for response
pluto[1040425]: "xauth-psk"[15836] 89.189.188.111 #16520: XAUTH: Sending Username/Password request (XAUTH_R0->XAUTH_R0)
pluto[1040425]: "xauth-psk"[15836] 89.189.188.111 #16520: STATE_XAUTH_R0: 60 second timeout exceeded after 7 retransmits.  No response (or no accept>
pluto[1040425]: "xauth-psk"[15836] 89.189.188.111 #16520: deleting state (STATE_XAUTH_R0) aged 66.530s and sending notification
pluto[1040425]:  #16520: deleting connection "xauth-psk"[15836] 89.189.188.111 instance with peer 89.189.188.111 {isakmp=#0/ipsec=#0}
lines 1-23/23 (END)

and sometimes I get like as follows:
pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16523: STATE_MODE_CFG_R1: ModeCfg Set sent, expecting Ack {auth=PRESHARED_KEY cipher=AES_CBC_256 >
pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16523: the peer proposed: 0.0.0.0/0:0/0 -> 192.168.43.145/32:0/0
pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16524: responding to Quick Mode proposal {msgid:81106fcb}
pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16524:     us: 0.0.0.0/0===167.71.116.96[MS+XS+S=C]
pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16524:   them: 202.134.14.134[10.236.154.244,+MC+XC+S=C]===192.168.43.145/32
pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16524: STATE_QUICK_R1: sent QR1, inbound IPsec SA installed, expecting QI2 tunnel mode {ESP/NAT=>>
pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16524: STATE_QUICK_R1: retransmission; will wait 0.5 seconds for response
pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16524: STATE_QUICK_R1: retransmission; will wait 1 seconds for response
pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16524: STATE_QUICK_R1: retransmission; will wait 2 seconds for response
pluto[1040425]: "xauth-psk"[15764] 202.134.14.134 #16524: STATE_QUICK_R2: IPsec SA established tunnel mode {ESP/NAT=>0x0c97eb1f <0xbb9c66f8 xfrm=AES>

**Comment by letoams** [comment]
On Fri, 30 Oct 2020, kamalsust wrote:

> Subject: [hwdsl2/setup-ipsec-vpn] About Ipsec Addresspool (#874)

I've started a discussion on the libreswan/libreswan issue which is a
copy of this discussion.

Paul

**Comment by hwdsl2** [comment]
Closing, see https://github.com/libreswan/libreswan/issues/377.
