### ISSUE TITLE
rasspberry debian

### ISSUE THREAD

**Issue by josefgull** [hwdsl2/setup-ipsec-vpn#877]
-bash: /etc/ipsec.conf: Permission denied

**Comment by letoams** [comment]
Why is it trying to execute a config file ?

**Comment by josefgull** [comment]
cat > /etc/ipsec.conf <<EOF
# ipsec.conf - strongSwan IPsec configuration file

i typed in sudo su and now everthing is working.

butt i get en error when i start the service

received NO_PROPOSAL_CHOSEN error notify
establishing connection 'myvpn' failed

**Comment by letoams** [comment]
That is a mismatch of configuration between the two endpoints.
