### ISSUE TITLE
能否提供服务器之间连接的ikev2配置脚本或者客户端连接说明

### ISSUE THREAD

**Issue by nickfan** [hwdsl2/setup-ipsec-vpn#880]
**任务列表**

- [ x ] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)，没有找到类似的改进建议
- [ x ] 这个改进建议是关于 VPN 安装脚本，而不是 IPsec VPN 本身
- [ x ] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [ x ] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [ x ] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [ x ] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)

**描述改进建议**
现在的ikev2辅助脚本只有服务端部分的配置，但site2site类型的服务器之间的vpn连接的配置没有对应的脚本
比如说这样一个常见的场景：
serverA(172.17.0.1)在aws的a账户的VPC1(172.17.0.0/16)中通过igw1互联网网关链路到公网，serverB(172.16.0.1)在aliyun的账户的VPC2(172.16.0.0/16)中通过igw2互联网网关链路到公网，
比如现在用了hwdsl2的vpnsetup和ikev2.sh在serverA上配置好了vpn服务端，在serverB上需要走ikev2协议连接到serverA上

**你的改进建议与遇到的问题有关吗？请描述。**
有没有计划提供一下ikev2的客户端strongswan的配置脚本，或者linux非gui的纯终端的配置ikev2指南

**其它信息**
添加关于该改进建议的其它信息。

**Comment by hwdsl2** [comment]
@nickfan 你好！感谢你的建议。Site to site 的 VPN 连接超出了这个项目的范围。你可以自己阅读 Libreswan wiki 等。

目前暂没有计划添加 IKEv2 的客户端 strongSwan 的配置脚本，或者 Linux 非 GUI 终端的 IKEv2 配置方法。
