### ISSUE TITLE
Issue with clients on Apple iOS 14 and macOS Big Sur

### ISSUE THREAD

**Issue by bizsys-appfire** [hwdsl2/setup-ipsec-vpn#882]
Apple iOS 14 and macOS Big Sur are having issue in connecting VPN server. As per this support KB - https://support.apple.com/en-us/HT211840 we need to configure the server to truncate the output of the SHA-256 hash to 128 bits.

**Comment by hwdsl2** [comment]
@bizsys-appfire Hello! This setting is controlled by `sha2-truncbug` in `/etc/ipsec.conf`. Please follow instructions in [1] to fix the issue. Let us know if it works for you.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#ios-13-and-macos-1015

**Comment by woniusnai** [comment]
非常感谢，已经解决了，应该是因为Libreswan的版本太低了，加密算法不支持，现在升级了Libreswan 4.1 后使用L2tpd连接恢复正常。
如果不升级Libreswan 再旧版本的Libreswan 增加IKEv2方式后也可以连接。

**Comment by hwdsl2** [comment]
@woniusnai Thanks for the update.
@bizsys-appfire In case the instructions above don't work, please also try upgrading Libreswan [1] to the latest version.

[1] https://github.com/hwdsl2/setup-ipsec-vpn#upgrade-libreswan
