### ISSUE TITLE
同一局域网下多设备连接的问题

### ISSUE THREAD

**Issue by wolfwithsheep** [hwdsl2/setup-ipsec-vpn#885]
你好，我按照你的脚本搭建好了ipse-vpn后，在同一局域网内多台win10的电脑无法同时连接，而Shrew Soft VPN 客户端不支持win10系统，并且当一台win10电脑连接vpn后iphone选择IPsec类型后也无法连接，显示服务器未响应，这种情况该怎么解决
Thanks for your reply!

**Comment by hwdsl2** [comment]
@wolfwithsheep 你好！你所描述的问题是已知问题，对于此用例建议尝试 IKEv2。请参见配置指南：
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto-zh.md
