### ISSUE TITLE
Strongswan client

### ISSUE THREAD

**Issue by pawel-zajac90** [hwdsl2/setup-ipsec-vpn#889]
Hi, 
i need to set up gui client for vpn on ubuntu 20.04. Network-manager-l2tp is really cool, but there is a little problem...this plugin is using strongswan, which have got a little differend config (i.e. authby=pubkey not rsaig for certs)
Is there any possibbility to use strongswan client with libreswan server?
Thanks for Your help!

**Comment by letoams** [comment]
On Tue, 8 Dec 2020, pawel-zajac90 wrote:

> i need to set up gui client for vpn on ubuntu 20.04. Network-manager-l2tp is really cool, but there is a little problem...this plugin is using
> strongswan, which have got a little differend config (i.e. authby=pubkey not rsaig for certs)
> Is there any possibbility to use strongswan client with libreswan server?

There will unfortunately be other changes to the config file between
libreswan as a client and strongswan as a client. I guess ideally,
the Network-manager-l2tp would allow support for either.

With libreswan defaulting to ikev2, for l2tp/ipsec you will likely want
to say ikev2=never in libreswan, which is keyexchange=ikev1 in
strongswan. There are more differences ....

Paul

**Comment by pawel-zajac90** [comment]
So, there is no possibility to use gui?

**Comment by hwdsl2** [comment]
@pawel-zajac90 Please take a look at these instructions [1]. Does this answer your question?

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#linux

**Comment by pawel-zajac90** [comment]
this is manager which i was talking about. It's using strongswan, which is incompatible with libreswan configuration.
i'm talking with autor of this manager, maybe we will find resolution :)
