### ISSUE TITLE
VPN Error 720

### ISSUE THREAD

**Issue by tobiaspihale** [hwdsl2/setup-ipsec-vpn#893]
I keep getting a Windows 10 VPN Error 720 on my Laptop while I try to connect to the VPN Server. It is working perfectly on an other device but not on the Laptop. Here is the log when I try to connect with the laptop https://hastebin.com/ipuhatokaw.yaml

**Comment by letoams** [comment]
It looks like the client connects to the server and the server is happy but the client is not.

Check the Windows console/log messages so see what makes it unhappy

**Comment by hwdsl2** [comment]
@tobiaspihale Hello! As @letoams said, this looks like a client-side issue. Please try the solutions mentioned here:
https://stackoverflow.com/questions/25245854/windows-8-1-gets-error-720-on-connect-vpn
