### ISSUE TITLE
关于VPN速度的问题

### ISSUE THREAD

**Issue by hyunsu-git** [hwdsl2/setup-ipsec-vpn#895]
我用的香港云服务器来搭建vpn，带宽方式是 100M 按照流量计费。
我本地使用vpn下载速度 最多在 1M/S 左右， 我想问下， 使用vpn 和我本地网络的上行带宽有关系吗

**Comment by hwdsl2** [comment]
@hyunsu-git 你好！使用 VPN 的下载速度主要受你的本地网络的下行带宽，以及服务器的上行和下行带宽等因素影响。另外 VPN 有对数据进行加密需要的带宽的额外开销，参见 [1] 的测试结果。一般来说，IPsec/L2TP 模式的额外开销比 IPsec/XAuth ("Cisco IPsec") 和 IKEv2 都要高一些。你可以尝试后两种模式，在自述文档里有说明。另外在计算带宽的时候注意 MB/s 和 Mb/s 的区别。这里有个关于 VPN 速度的文章可以参考一下 [2]。

[1] https://libreswan.org/wiki/Benchmarking_and_Performance_testing
[2] https://www.vpnuniversity.com/learn/vpn-speed
