### ISSUE TITLE
Connected but no internet access

### ISSUE THREAD

**Issue by malikshi** [hwdsl2/setup-ipsec-vpn#896]
windows 10
here the log in server
>Dec 16 13:35:46 VPS xl2tpd[4680]: write_packet: tty is not open yet.
Dec 16 13:35:46 VPS pppd[4782]: Plugin pppol2tp.so loaded.
Dec 16 13:35:46 VPS pppd[4782]: pppd 2.4.7 started by root, uid 0
Dec 16 13:35:46 VPS pppd[4782]: Using interface ppp0
Dec 16 13:35:46 VPS pppd[4782]: Connect: ppp0 <-->
Dec 16 13:35:46 VPS pppd[4782]: Overriding mtu 1500 to 1280
Dec 16 13:35:46 VPS pppd[4782]: Overriding mru 1500 to mtu value 1280
Dec 16 13:35:46 VPS systemd-udevd[4784]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writa
Dec 16 13:35:48 VPS pppd[4782]: Overriding mtu 1400 to 1280
Dec 16 13:35:49 VPS pppd[4782]: Cannot determine ethernet address for proxy ARP
Dec 16 13:35:49 VPS pppd[4782]: local  IP address 192.168.42.1
Dec 16 13:35:49 VPS pppd[4782]: remote IP address 192.168.42.10

**Comment by hwdsl2** [comment]
@malikshi What is your Windows 10 version (e.g. 2004)? Please check the Libreswan logs [1] on your server for errors. Also can you post the output of `iptables -nvL; iptables -nvL -t nat`?

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status

**Comment by hwdsl2** [comment]
Closing. If you have more information feel free to comment.
