### ISSUE TITLE
爱快无法连接到L2TP的VPN

### ISSUE THREAD

**Issue by helloweizhang** [hwdsl2/setup-ipsec-vpn#897]
**搭建脚本：setup-ipsec-vpn**
Openwrt：连接失败
爱快路由器：连接失败
Mikrotik：连接成功

如果使用Softether搭建，Openwrt、爱快和Mikrotik都可以连接成功。
请问脚本设置要在哪里设置，以便它支持Openwrt和爱快呢？

**Comment by hwdsl2** [comment]
@helloweizhang 你好！我对 OpenWrt 或爱快路由器配置不熟悉。你可以在尝试连接之后检查 Libreswan 日志是否有错误 [1]。建议你在对应的论坛问一下。比如这里有两个相关的讨论 [2] [3]。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E6%A3%80%E6%9F%A5%E6%97%A5%E5%BF%97%E5%8F%8A-vpn-%E7%8A%B6%E6%80%81
[2] https://bbs.ikuai8.com/thread-95296-1-1.html
[3] https://forum.openwrt.org/t/how-to-configure-l2tp-ipsec-client-in-openwrt-18/49878

**Comment by helloweizhang** [comment]
问题原因已经找到，因为Softether同时支持 L2TP over IPsec 和 Raw L2TP with No Encryptions，而setup-ipsec-vpn脚本只支持 L2TP over IPsec 爱快和Openwrt都是需要不带IPsec的预共享密钥登陆。所以导致用脚本生成的L2TP在爱快和Openwrt无法连接上

**Comment by xdkaka** [comment]
> Openwrt
这两个路由器有什么办法么

**Comment by yocdynyssc** [comment]
> 问题原因已经找到，因为Softether同时支持 L2TP over IPsec 和 Raw L2TP with No Encryptions，而setup-ipsec-vpn脚本只支持 L2TP over IPsec 爱快和Openwrt都是需要不带IPsec的预共享密钥登陆。所以导致用脚本生成的L2TP在爱快和Openwrt无法连接上

请问你是如何解决使用爱快(ikuai)连接的？
