### ISSUE TITLE
2 connection from the same IP

### ISSUE THREAD

**Issue by alicoder** [hwdsl2/setup-ipsec-vpn#9]
I made another account for my another PC , but I can't connect to it.

**Comment by hwdsl2** [comment]
Hi @alicoder, this is due to a limitation of IPsec/L2TP VPNs. Only ONE device behind the same NAT (e.g. a home router) can connect to the VPN server at any time.

**Comment by alicoder** [comment]
thank you for your reply.
what about PPTP or openVPN ? are they have the same limitation?

**Comment by hwdsl2** [comment]
I believe OpenVPN does not have such limitation. You may want to try Nyr's OpenVPN script at https://github.com/Nyr/openvpn-install

**Comment by alicoder** [comment]
So PPTP has it too.
are there is any configuration that make it leave that limitation ?

**Comment by hwdsl2** [comment]
Not sure about PPTP. For IPsec VPNs there may be workarounds, see search results [1]. However I am not very familiar with those. Try asking on the Libreswan mailing list [2].

[1] https://www.google.com/search?q=ipsec+vpn+multiple+users+same+nat
[2] https://lists.libreswan.org/mailman/listinfo/swan

**Comment by alicoder** [comment]
thank you for your help.
