### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by nmeheus** [hwdsl2/setup-ipsec-vpn#90]
This is more a question than an issue, but I can't seem to get my VPN client to work.

In the provided screen, i get a message : ' deleting IKE_SA ips-tunnel ' 

![vpn_trouble_b](https://cloud.githubusercontent.com/assets/24569649/21188842/f5075d7a-c21c-11e6-8ea0-8179d2e4f4f6.png)

The *** in the screen is a IP address within my subnet range, however it does not exist a this moment/ or is unreachable by me.

I think this deletion causes the ppp0 dev to not be created, as I can not see it in the ifconfig output.

It wondered if you have encountered similar problems before.

**Comment by nmeheus** [comment]
Ok, so I was able to overcome this by adding 'rightid=***' to the ipsec.conf file,
however, there is still no ppp device

**Comment by hwdsl2** [comment]
@nmeheus I think there is no need to change the `rightid=***` in ipsec.conf. In case of issues, restart the IPsec and xl2tpd services on both the VPN server and VPN client. Then try connecting again:

```
service ipsec restart
(On the client: service strongswan restart)
service xl2tpd restart
```

It is normal to not have a ppp0 device at this point. The ppp0 should appear AFTER running the following command (refer to [1]):

```
echo "c myvpn" > /var/run/xl2tpd/l2tp-control
```

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#linux

**Comment by nmeheus** [comment]
@hwdsl2 Thanks for the quick response, I found that adding the rightid option was the only way to get the tunnel up [1]. I can't change anything to the server, because it's a public server that i want to use [2].

I checked the ifconfig output after i ran 
`echo "c ips-tunnel" > /var/run/xl2tpd/l2tp-control` (i replaced myvpn with ips-tunnel in all occurrences)

[1] https://doc.pfsense.org/index.php/IPsec_Troubleshooting#Mismatched_Identifier_with_NAT
[2] http://www.vpngate.net/en/

**Comment by hwdsl2** [comment]
@nmeheus Ah I see. So you are using a public VPN server which may be running strongSwan. Remember that the Linux client instructions in this repo were developed with Libreswan and one's own VPN server. In your use case I would suggest that you instead seek help from the strongSwan mailing list [1]:

I'm going to close this as it is not an issue with the VPN scripts.

[1] https://lists.strongswan.org/mailman/listinfo/users
