### ISSUE TITLE
Xauth mode in mikrotik

### ISSUE THREAD

**Issue by amirabasalinaghi** [hwdsl2/setup-ipsec-vpn#902]
Hi
I am now using l2tp ipsec mode to connect my mikrotik router to vpn and it wogks fine!
But i want to setup xauth mode on my router but i dont find the correct way to fo that 
Can you help me solve my problem?
Thanks

**Comment by hwdsl2** [comment]
@amirabasalinaghi Hello! I am not familiar with Mikrotik VPN client configuration. I suggest that you ask in the Mikrotik forums. I did a quick search and found this post [1] which may be helpful. Note that by default, the IPsec/XAuth ("Cisco IPsec") mode set up by the VPN scripts does not require a "group name" (i.e. leave it empty in the client configuration).

[1] https://forum.mikrotik.com/viewtopic.php?t=152466#p763583
