### ISSUE TITLE
Create iOS/macOS .mobileconfig as part of user configuration

### ISSUE THREAD

**Issue by gspannu** [hwdsl2/setup-ipsec-vpn#908]
**Checklist**

- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [x] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
- Add an option to create a per-client .mobileconfig for iOS/macOS users.
This mobileconfig (when installed on client devices) will create a profile in iOS/macOS which automatically installs the correct VPN settings in the Client.
- Option to include the certificate(s) to be included in the mobileconfig to make the whole process seamless.
- Option to enable the 'Connect-On-Demand' feature in the VPN setting as part of the client configuration and make the appropriate setting in the mobileconfig. Default value may be OFF

**Is your enhancement request related to a problem? Please describe.**
I am trying to setup a mechanism for a few iOS/macOS users to VPN connect into the workplace.
With the above feature, I can create .mobileconfigs and provide the files to individual users.
Since, I also have a Apple Developer subscription, I can sign these generated .mobileconfigs and the end-user will then not need to 'trust the certificate' as signed .mobileconfigs automatically treat the included certs as trusted - so avoids another step for end users.

**Additional context**
Some ideas here about mobileconfig generation here
https://github.com/Juev/debian-ikev2-vpn-server
https://github.com/tbartelmess/docker-ikev2-vpn-server

**Comment by hwdsl2** [comment]
Thank you for the suggestions! Supporting .mobileconfig has been on my list of improvements for a while. The good news is that this feature has just been implemented and is now available! Give it a try and if you have feedback, feel free to reply here.

For macOS and iOS clients, the IKEv2 helper script can now create .mobileconfig files to simplify client setup and improve VPN performance with ciphers such as AES-GCM. And the VPN On Demand feature is now available. See b004aaa and https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md for more details.
