### ISSUE TITLE
A unified script only for IKEv2 (or maybe choose everything at install time)?

### ISSUE THREAD

**Issue by gspannu** [hwdsl2/setup-ipsec-vpn#911]
**Checklist**

- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [x] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
**1**) Can we have an install script only for IKEv2? Or *better maybe a script that allows choices* at start of installation?
- Choose VPN server protocols? IKEv2 (with X-Auth, pubkey, PSK, IKEv1, etc...
- Choose target installation
- Choose Cert details, validity, CN, SN, O, SAN, etc.. (also maybe add the option to have client Certs of max 2 years and the caCert to be of 10 years)
- Choose details (of .mobleconfig) Display names of VPN, Profile, Certs, etc...? 
- Choose PSKs, etc... (if appropriate)
- Choose Server names, IP addresses, domains, etc..
- Choose DNS servers, etc?
- Choose user(s)?
- Choose target configs (iOS, MacOS, Windows, Android, etc..) and target folder location (of .p12 and .mobileconfig files or local folder, etc...)?

And then it generates the appropriate files, certs, mobileconfigs, etc...

The end result would be a leaner implementation.

**2**) Any possibility of building this on Strongswan (instead of Libreswan) - or your specific reasons of choosing Libreswan?

**Is your enhancement request related to a problem? Please describe.**
The current installation method forces an installation of IKE and only then can an installation of IKEv2 be done. Any script to circumvent this?
Allow more configuration for Certificate names, organisation, Display names of certs, etc?

**Additional context**
Many thanks for building the option of .mobileconigs (and embedding it with the necessary certs) in response to my request https://github.com/hwdsl2/setup-ipsec-vpn/issues/908#issue-782938837. Thank you and much appreciated. I have tested and it works fine.

**Comment by hwdsl2** [comment]
@gspannu Thank you for your suggestions. For your information, I've recently made improvements to the IKEv2 setup script, so that it can be run in "auto mode" without any user input. As I mentioned earlier, the script can now generate .mobileconfig files for iOS and macOS clients to simplify client setup and further improve VPN performance.

For your question (1): You can now easily achieve this (install only IKEv2) by running the VPN setup script followed by the IKEv2 setup script in "auto mode", and after that, comment out both the "conn l2tp-psk" and "conn xauth-psk" sections in "/etc/ipsec.conf" and run "sudo service ipsec restart".

Some of the customization features you mentioned are already available in the setup scripts, such as setting client cert validity, client name for IKEv2, set your own PSK, server name for IKEv2, etc. For customizing DNS servers and managing VPN users, see the important notes section of README. Note that the VPN setup scripts were designed with the goal that no user input is needed for the installation, so some customization are not available.

For your question (2), Libreswan has been actively developed by the Libreswan team, and this project has been using it since 2014. Building on strongSwan would possibly also work, and there are examples on GitHub that use strongSwan. I've never tried it myself, but you are welcome to take a look if you prefer.

**Comment by gspannu** [comment]
> @gspannu 
> For your question (1): You can now easily achieve this (install only IKEv2) by running the VPN setup script followed by the IKEv2 setup script in "auto mode", and after that, comment out both the "conn l2tp-psk" and "conn xauth-psk" sections in "/etc/ipsec.conf" and run "sudo service ipsec restart".
> 

Thankyou for updating the script.
1) Is there anyway to completely disable the IKEv1 services (L2P and XAuth)?
2) Even after commenting the sections (as suggested above); I noticed that the server is still listening on port 1701.
3) Any way to have a super-lean IKEv2 server only?

Thank you for your support...

**Comment by hwdsl2** [comment]
@gspannu To answer your questions... To disable the IKEv1 services and enable only IKEv2 when installing, make these changes in the current revision of the VPN setup script for Ubuntu/Debian [1] before running:

1. Remove `ppp xl2tpd` from line 190.
2. Remove `%v4:!$L2TP_NET,` from line 258.
3. Comment out lines 262-302, 319-363.
4. Remove `xl2tpd` from line 479.
5. Comment out line 496 and 512.
6. Remove `/etc/ppp/chap-secrets*` from line 507.

Next, remove `|| [ ! -f /etc/ppp/chap-secrets ]` from function `check_swan_install()` in the IKEv2 setup script [2]. Finally, run the VPN setup script followed by the IKEv2 setup script in auto mode.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/2b6586cf1b808f8ed2027469d4902198d3c26a74/vpnsetup.sh

**Comment by gspannu** [comment]
> @gspannu To answer your questions... To disable the IKEv1 services and enable only IKEv2 when installing, make these changes in the current revision of the VPN setup script for Ubuntu/Debian [1] before running:
> 
> 1. Remove `ppp xl2tpd` from line 190.
> 2. Remove `%v4:!$L2TP_NET,` from line 258.
> 3. Comment out lines 262-302, 319-363.
> 4. Remove `xl2tpd` from line 479.
> 5. Comment out line 496 and 512.
> 6. Remove `/etc/ppp/chap-secrets*` from line 507.
> 
> Next, remove `|| [ ! -f /etc/ppp/chap-secrets ]` from function `check_swan_install()` in the IKEv2 setup script. Finally, run the VPN setup script followed by the IKEv2 setup script in auto mode.
> 
> [1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/2b6586cf1b808f8ed2027469d4902198d3c26a74/vpnsetup.sh

**Tried the above**.... (exactly as per instructions above) but the vpnsetup.sh throws up errors.

```
## Restarting IPsec service...
Job for ipsec.service failed because the control process exited with error code.
See "systemctl status ipsec.service" and "journalctl -xe" for details.

```
sudo ipsec status returns **pluto not running error**.

**Comment by hwdsl2** [comment]
@gspannu The instructions were tested and working fine. Please re-try them (exactly as written). You may have made incorrect changes in ipsec.conf.

**Comment by gspannu** [comment]
I think the issue is in the main vpnsetup.sh itself. 

I have raised the issue [919](https://github.com/hwdsl2/setup-ipsec-vpn/issues/919) as a separate issue.

I checked the above lean setup on a Raspberry Pi 4 - and all works fine. I get a lean setup (as described above).
However, I could don't get the same running on a Mac mini.
**I initially thought that it was the changes (for the lean setup) that were causing the Pluto problem.**

Then after a lot of clean formats and fresh installs, **I finally figured out that even the original vpnsetup.sh does not install Pluto properly on a Mac mini running Raspberry Pi Desktop**.

**Comment by gspannu** [comment]
> @gspannu To answer your questions... To disable the IKEv1 services and enable only IKEv2 when installing, make these changes in the current revision of the VPN setup script for Ubuntu/Debian [1] before running:
> 
> 1. Remove `ppp xl2tpd` from line 190.
> 2. Remove `%v4:!$L2TP_NET,` from line 258.
> 3. Comment out lines 262-302, 319-363.
> 4. Remove `xl2tpd` from line 479.
> 5. Comment out line 496 and 512.
> 6. Remove `/etc/ppp/chap-secrets*` from line 507.
> 
> Next, remove `|| [ ! -f /etc/ppp/chap-secrets ]` from function `check_swan_install()` in the IKEv2 setup script. Finally, run the VPN setup script followed by the IKEv2 setup script in auto mode.
> 
> [1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/2b6586cf1b808f8ed2027469d4902198d3c26a74/vpnsetup.sh

Just. very quick one...

I now have a lean setup (only using IKEv2). **Many thanks of your support on this**.

However I noticed that iptable routing is still being done for ports 1701 (I guess not needed for only IKEv2).

Can you please send me _what additional lines to comment_ from vpnsetup.sh so that the script only modifies the iptables settings for IKEv2 (port 500,4500)?

**Comment by hwdsl2** [comment]
@gspannu To only add the IPTables rules necessary for IKEv2, make these changes in the current revision [1] of the VPN setup script: Comment out lines 406, 410, 413-415 and 423.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/1808095bb7a6eb40475f45e35571fc1799c06e5b/vpnsetup.sh

**Comment by gspannu** [comment]
> @gspannu To only add the IPTables rules necessary for IKEv2, make these changes in the current revision [1] of the VPN setup script: Comment out lines 406, 410, 413-415 and 423.
> 
> [1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/1808095bb7a6eb40475f45e35571fc1799c06e5b/vpnsetup.sh

I have followed the instructions, but I get the error
**Index of insertion too big**.
```
## Updating IPTables rules...

iptables: Index of insertion too big.
iptables: Index of insertion too big.
iptables: Index of insertion too big.
iptables: Index of insertion too big.
iptables: Index of insertion too big.
iptables: Index of insertion too big.

```

For reference, my iptables section (lines commented per your instruction) looks like this...

<img width="851" alt="iptable-section" src="https://user-images.githubusercontent.com/137664/106967164-90ce3b00-673e-11eb-832e-b209b19a2741.png">

**_Can you please advise if I have missed anything?_** 
As advised, I have commented out lines 406, 410, 413-415 and 423

**Comment by hwdsl2** [comment]
@gspannu You'll need to update the IPTables line numbers so that they are sequentially increasing starting from 1, for each IPTables chain, respectively. For example, line 407 would become "iptables -I INPUT 1 ...".
