### ISSUE TITLE
Mikrotik

### ISSUE THREAD

**Issue by dettofatto** [hwdsl2/setup-ipsec-vpn#914]
Hi,
I have a Mikrotik as client, i've edited all infos as shown, but only two times i've been able to contect to my vps.
I can't understan how is possible.
I've also changed mtu/mru to 1200 from 1210 as discussed.

I must open any ports on  my VPS' firewall?
Thank you.

![Cattura](https://user-images.githubusercontent.com/36331389/105164673-b12eb080-5b15-11eb-96e3-f68906ee9dcc.JPG)

**Comment by trochdewei** [comment]
@dettofatto You can try to enable verbose IPSec logging to see what's going on `/system/logging/add action=memory topics=ipsec`

**Comment by Scottpedia** [comment]
As a possible cause, you might want to open port 4500 UDP and port 500 UDP on your VPS's firewall, such that the VPN connections can be made. 

- Reference: https://github.com/hwdsl2/setup-ipsec-vpn#important-notes

**Comment by dettofatto** [comment]
Perfect! It was the firewall!

**Comment by Archerious** [comment]
I have the same issue but it's not my firewall. 4500, 500, and 1701 are open in Mikrotik input chain and on the VPS itself. 

VPS:
-A INPUT -p udp -m multiport --dports 500,4500 -j ACCEPT
-A INPUT -p udp -m udp --dport 1701 -m policy --dir in --pol ipsec -j ACCEPT

MikroTik:
<img width="904" alt="Screen Shot 2021-02-12 at 10 55 31 PM" src="https://user-images.githubusercontent.com/26941475/107842001-7d961d80-6d85-11eb-9af3-299e8218f20d.png">
<img width="324" alt="Screen Shot 2021-02-12 at 10 55 48 PM" src="https://user-images.githubusercontent.com/26941475/107842004-7e2eb400-6d85-11eb-8444-70a980c496c7.png">

**Comment by letoams** [comment]
On Fri, 12 Feb 2021, Archerious wrote:

> I have the same issue but it's not my firewall. 4500, 500, and 1701 are open in Mikrotik input chain and on the VPS itself.
> 
> VPS:
> -A INPUT -p udp -m multiport --dports 500,4500 -j ACCEPT
> -A INPUT -p udp -m udp --dport 1701 -m policy --dir in --pol ipsec -j ACCEPT

These rules are not correct if there is NAT. The destination port might
not be 4500 but an ephemeral port, eg:




GW1 1.2.3.4:4500 ---- NAT ---> 6.7.8.9:33456 ----> GW2 192.168.0.1:4500

firewall rules for the VPN GW should allow sport 500/4500 to ANY port
outgoing. For incoming it can say destination MUST be 500/4500.

Paul

**Comment by Archerious** [comment]
I ended up getting it working by using ikev2, that seems to work really well with MikroTik.
