### ISSUE TITLE
The ipsec service does not seem to take effect

### ISSUE THREAD

**Issue by xiaomaolver** [hwdsl2/setup-ipsec-vpn#917]
![image](https://user-images.githubusercontent.com/47557223/105815275-a3819b00-5fed-11eb-8594-76e143aefdcb.png)
The port is not listening normally, but systemctl status ipsec.service prompts active (running)
![image](https://user-images.githubusercontent.com/47557223/105815625-328eb300-5fee-11eb-81ed-f3adc21db6b4.png)
Cannot scan to the port

**Comment by hwdsl2** [comment]
@xiaomaolver Hello! The `netstat` output indicates that both Libreswan ("pluto") and xl2tpd are listening normally (UDP port 500, 4500 and 1701). If you cannot connect, you may need to open UDP port 500 and 4500 in your server provider's firewall settings, if applicable. See [1] for more information.

[1] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes

**Comment by xiaomaolver** [comment]
> @xiaomaolver Hello! The `netstat` output indicates that both Libreswan ("pluto") and xl2tpd are listening normally (UDP ports 500, 4500 and 1701). If you cannot connect, you may need to open UDP port 500 and 4500 in your server provider's firewall settings, if applicable. See [1] for more information.
> 
> [1] https://github.com/hwdsl2/setup-ipsec-vpn#important-notes

@hwdsl2 But I use other services to monitor port 500 and 4500, both can be accessed, and the port is also available
