### ISSUE TITLE
Wrong ipsec.secret syntax generated

### ISSUE THREAD

**Issue by zsjoska** [hwdsl2/setup-ipsec-vpn#918]
$ lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

$ uname -a
Linux krux 5.4.0-62-generic #70-Ubuntu SMP Tue Jan 12 12:45:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Running the script completes without problem but android client is unable to connect.
In syslog appears:
Jan 26 12:36:31 krux pppd[47981]: pppd 2.4.7 started by root, uid 0
Jan 26 12:36:31 krux pppd[47981]: Using interface ppp0
Jan 26 12:36:31 krux pppd[47981]: Connect: ppp0 <--> 
Jan 26 12:36:31 krux pppd[47981]: Overriding mtu 1500 to 1280
Jan 26 12:36:31 krux pppd[47981]: Overriding mru 1500 to mtu value 1280
Jan 26 12:36:31 krux systemd-udevd[47983]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
Jan 26 12:36:35 krux pppd[47981]: Overriding mtu 1300 to 1280
Jan 26 12:36:35 krux pppd[47981]: Peer zsjoska failed CHAP authentication
Jan 26 12:36:35 krux pppd[47981]: Overriding mtu 1500 to 1280
Jan 26 12:36:35 krux pppd[47981]: Overriding mru 1500 to mtu value 1280
Jan 26 12:36:35 krux pppd[47981]: Connection terminated.
Jan 26 12:36:35 krux pppd[47981]: Exit.
Jan 26 12:36:35 krux xl2tpd[47970]: child_handler : pppd exited for call 30750 with code 11
Jan 26 12:36:35 krux xl2tpd[47970]: call_close: Call 48298 to 46.97.168.104 disconnected
Jan 26 12:36:35 krux xl2tpd[47970]: result_code_avp: avp is incorrect size.  8 < 10
Jan 26 12:36:35 krux xl2tpd[47970]: handle_avps: Bad exit status handling attribute 1 (Result Code) on mandatory packet.
Jan 26 12:36:35 krux xl2tpd[47970]: Terminating pppd: sending TERM signal to pid 47981
Jan 26 12:36:35 krux xl2tpd[47970]: Connection 24470 closed to 46.97.168.104, port 46097 (Result Code: expected at least 10, got 8)

$ ipsec verify
Verifying installed system and configuration files

Version check and ipsec on-path                   	[OK]
Libreswan 3.27 (netkey) on 5.4.0-62-generic
Checking for IPsec support in kernel              	[OK]
 NETKEY: Testing XFRM related proc values
         ICMP default/send_redirects              	[OK]
         ICMP default/accept_redirects            	[OK]
         XFRM larval drop                         	[OK]
Pluto ipsec.conf syntax                           	[OK]
Two or more interfaces found, checking IP forwarding	[OK]
Checking rp_filter                                	[OK]
Checking that pluto is running                    	[OK]
 Pluto listening for IKE on udp 500               	[OK]
 Pluto listening for IKE/NAT-T on udp 4500        	[OK]
 Pluto ipsec.secret syntax                        	[UNKNOWN]
 (run ipsec verify as root to test ipsec.secrets)
Checking 'ip' command                             	[OK]
Checking 'iptables' command                       	[OK]
Checking 'prelink' command does not interfere with FIPS	[OK]
Checking for obsolete ipsec.conf options          	[OK]

**Comment by hwdsl2** [comment]
@zsjoska Hello! Your logs show `failed CHAP authentication`, which indicates that you typed the wrong password (mismatch from the server) in your Android VPN settings. Please delete and re-add the connection on your Android device and type the correct password. If you forgot it, check `/etc/ppp/chap-secrets` on the server.
