### ISSUE TITLE
Why not write `sha2-truncbug=yes` in run.sh?

### ISSUE THREAD

**Issue by cncolder** [hwdsl2/setup-ipsec-vpn#92]
`/opt/src/run.sh` will rewrite `/etc/ipsec.conf` after restart docker. I must edit every time.
I think it's good to move it from troubleshoot into `/opt/src/run.sh`

I setup `-v ./ipsec.conf:/etc/ipsec.conf` now. But I found there are some dynamic ip addresses in gen script.

**Comment by hwdsl2** [comment]
@cncolder Issue moved to the correct repository https://github.com/hwdsl2/docker-ipsec-vpn-server.
