### ISSUE TITLE
The service is listening normally, the firewall is normally on, and the external network can access the UDP port, but the device cannot be connected

### ISSUE THREAD

**Issue by xiaomaolver** [hwdsl2/setup-ipsec-vpn#921]
The service is listening normally, the firewall is normally on, and the external network can access the UDP port, but the device cannot be connected
![image](https://user-images.githubusercontent.com/47557223/106292133-72bc9280-6287-11eb-9b4f-f9c8d569bb6b.png)
![image](https://user-images.githubusercontent.com/47557223/106292202-836d0880-6287-11eb-87b7-173ac01be6ec.png)

 Linux external network devices can use the nc tool to access the UDP port, but Android and Windows devices cannot connect
![image](https://user-images.githubusercontent.com/47557223/106291593-ca0e3300-6286-11eb-856c-a443ff712eae.png)
Can not find what the problem is

**Comment by hwdsl2** [comment]
@xiaomaolver Please check the Libreswan (IPsec) and xl2tpd logs for errors, and post the redacted logs here to troubleshoot further:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status

**Comment by xiaomaolver** [comment]
@hwdsl2 
"seccomp security for helper not supported" Is this a mistake?
The picture below is the log information
![image](https://user-images.githubusercontent.com/47557223/106345572-366f4d80-62ec-11eb-8435-55db9aed9635.png)

**Comment by hwdsl2** [comment]
@xiaomaolver Your logs show that both Libreswan and xl2tpd have started successfully and are listening for connections. The "seccomp security for helper not supported", "death_handler: Fatal signal 15 received" and "Not looking for kernel SAref support." can be safely ignored and does not affect the VPN.

I'm not sure why your VPN clients cannot connect. This is most likely a problem with your VPN client device configuration, see troubleshooting [1]. Or there may be network issues between the VPN client and VPN server (e.g. if GFW blocks traffic), in which case you may want to instead try e.g. Shadowsocks.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting
