### ISSUE TITLE
Add customization variables in ikev2 helper script.

### ISSUE THREAD

**Issue by Scottpedia** [hwdsl2/setup-ipsec-vpn#923]
**Checklist**

- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [x] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
A clear and concise description of your enhancement request.

I hope ikev2 helper script can have variables at the start of the file that allow users to customize the setup without interactively entering the values, like the way the VPN setup script is written.(e.g. `VPN_PASSWORD = ''`, etc)

**Is your enhancement request related to a problem? Please describe.**
(If applicable) A clear and concise description of what the problem is.

**Additional context**
Add any other context about the enhancement request here.

**Comment by hwdsl2** [comment]
@Scottpedia Thank you for your suggestions. Currently, users can run the IKEv2 helper script interactively (without arguments) to customize IKEv2 setup options, or they can specify parameter "--auto" to set up automatically using default options.

I think there is not much demand for the enhancement you mentioned here (use variables to customize). You are welcome to customize the script for your use case, however, which should be relatively straightforward to do.
