### ISSUE TITLE
PSK cannot exceed certain length

### ISSUE THREAD

**Issue by Scottpedia** [hwdsl2/setup-ipsec-vpn#925]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**

It seems to me that IPSec Pre-shared key cannot be more than certain length of characters. I deployed two servers with cloudformation template using a PSK of 38 characters.(as recommended by the document to have a PSK of more than 20 characters) And I could not connect to these servers for some reason, with all credentials re-checked. And I logged into one of these servers to see the log, and the error appears to be caused by some kind of payload.(the log attached below)

```
Feb 01 21:21:12 ip-10-0-0-88 pluto[15404]: "xauth-psk"[2] 70.48.9.156 #3: probable authentication failure (mismatch of preshared secrets?): malformed payload in packet
Feb 01 21:21:12 ip-10-0-0-88 pluto[15404]: "xauth-psk"[2] 70.48.9.156 #3: 53683-byte length of ISAKMP Identification Payload is larger than can fit
Feb 01 21:21:05 ip-10-0-0-88 pluto[15404]: "xauth-psk"[2] 70.48.9.156 #3: STATE_MAIN_R2: retransmission; will wait 16 seconds for response
```

Then, I deployed one more server using a PSK of 6 characters and it worked again. I suspect the error was caused by the exceeded number of characters of Pre-shared key.

**To Reproduce**

Deploy an IPSec-xauth server, using AWS cloudformation template, in any region, using a PSK of 38 characters.

1. ...
2. ...

**Expected behavior**

Either the documentation should mention the character number limit or the script should be modified such that no character number limit is imposed.

**Logs**
[Check logs and VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status), and add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- OS: Ubuntu20.04
- Hosting provider (if applicable): AWS

**Client (please complete the following information)**
- Device: [e.g. iPhone 8]
- OS: [e.g. iOS 13.6]
- VPN mode: [IPsec/L2TP, IPsec/XAuth ("Cisco IPsec") or IKEv2]

**Additional context**

**Comment by hwdsl2** [comment]
@Scottpedia Thank you for reporting this issue. However, a PSK of 38 characters should not be a problem, as Libreswan can support PSK length of 64 characters or more [1].

The error from your logs, `probable authentication failure (mismatch of preshared secrets?): malformed payload in packet`, indicates that the IPsec PSK on your server does not match the PSK in your VPN client configuration. The reason could be that you typed the PSK incorrectly in the client configuration, or maybe you used certain special characters `\ ' "` in your PSK, which should be avoided according to the documentation. I suggest that you check further regarding those. The PSK on the VPN server can be found in `/etc/ipsec.secrets`. 

[1] https://libreswan.org/wiki/Host_to_host_VPN_with_PSK
