### ISSUE TITLE
Script not create a ppp0 interface

### ISSUE THREAD

**Issue by dettofatto** [hwdsl2/setup-ipsec-vpn#927]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**
Script not create a ppp0 interface.
After the script, if I type ifconfig I have only ens192 and lo interfaces.
So I can't connect to my vps.

**To Reproduce**

1. Install
2. connect
3. ifconfig

**Expected behavior**
I can't connect to my VPS

**Logs**
Log
Feb  4 11:55:51 debian xl2tpd[2063]: xl2tpd version xl2tpd-1.3.12 started on debian PID:2063
Feb  4 11:55:51 debian xl2tpd[2063]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
Feb  4 11:55:51 debian xl2tpd[2063]: Forked by Scott Balmos and David Stipp, (C) 2001
Feb  4 11:55:51 debian xl2tpd[2063]: Inherited by Jeff McAdams, (C) 2002
Feb  4 11:55:51 debian xl2tpd[2063]: Forked again by Xelerance (www.xelerance.com) (C) 2006-2016
Feb  4 11:55:51 debian xl2tpd[2063]: Listening on IP address 0.0.0.0, port 1701
Feb  4 11:56:42 debian xl2tpd[2063]: death_handler: Fatal signal 15 received
Feb  4 11:56:42 debian xl2tpd[6702]: Stopping xl2tpd: xl2tpd.
Feb  4 11:56:42 debian systemd[1]: xl2tpd.service: Succeeded.
Feb  4 11:56:42 debian xl2tpd[6709]: Not looking for kernel SAref support.
Feb  4 11:56:42 debian xl2tpd[6709]: Using l2tp kernel support.
Feb  4 11:56:42 debian xl2tpd[6706]: Starting xl2tpd: xl2tpd.
Feb  4 11:56:42 debian xl2tpd[6710]: xl2tpd version xl2tpd-1.3.12 started on debian PID:6710
Feb  4 11:56:42 debian xl2tpd[6710]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
Feb  4 11:56:42 debian xl2tpd[6710]: Forked by Scott Balmos and David Stipp, (C) 2001
Feb  4 11:56:42 debian xl2tpd[6710]: Inherited by Jeff McAdams, (C) 2002
Feb  4 11:56:42 debian xl2tpd[6710]: Forked again by Xelerance (www.xelerance.com) (C) 2006-2016
Feb  4 11:56:42 debian xl2tpd[6710]: Listening on IP address 0.0.0.0, port 1701
and:
Feb  4 11:56:42 debian pluto[6693]: testing HMAC_MD5:
Feb  4 11:56:42 debian pluto[6693]:   RFC 2104: MD5_HMAC test 1
Feb  4 11:56:42 debian pluto[6693]:   RFC 2104: MD5_HMAC test 2
Feb  4 11:56:42 debian pluto[6693]:   RFC 2104: MD5_HMAC test 3
Feb  4 11:56:42 debian pluto[6693]: 1 CPU cores online
Feb  4 11:56:42 debian pluto[6693]: starting up 1 helper threads
Feb  4 11:56:42 debian pluto[6693]: started thread for helper 0
Feb  4 11:56:42 debian pluto[6693]: using Linux xfrm kernel support code on #1 SMP Debian 4.19.171-2 (2021-01-30)
Feb  4 11:56:42 debian pluto[6693]: systemd watchdog for ipsec service configured with timeout of 200000000 usecs
Feb  4 11:56:42 debian pluto[6693]: watchdog: sending probes every 100 secs
Feb  4 11:56:42 debian pluto[6693]: seccomp security not supported
Feb  4 11:56:42 debian pluto[6693]: seccomp security for helper not supported
Feb  4 11:56:42 debian pluto[6693]: "l2tp-psk": added IKEv1 connection
Feb  4 11:56:42 debian pluto[6693]: "xauth-psk": added IKEv1 connection
Feb  4 11:56:42 debian pluto[6693]: listening for IKE messages
Feb  4 11:56:42 debian pluto[6693]: Kernel supports NIC esp-hw-offload
Feb  4 11:56:42 debian pluto[6693]: adding UDP interface ensx.x.x.x:500
Feb  4 11:56:42 debian pluto[6693]: adding UDP interface ensx.x.x.:4500
Feb  4 11:56:42 debian pluto[6693]: adding UDP interface lo 127.0.0.1:500
Feb  4 11:56:42 debian pluto[6693]: adding UDP interface lo 127.0.0.1:4500
Feb  4 11:56:42 debian pluto[6693]: adding UDP interface lo [::1]:500
Feb  4 11:56:42 debian pluto[6693]: adding UDP interface ens192 [2001:470:26:10:250:56ff:fea6:d455]:500
Feb  4 11:56:42 debian pluto[6693]: loading secrets from "/etc/ipsec.secrets"

**Server (please complete the following information)**
- OS: Debian 10
- Hosting provider: Revolution Hosting

**Client (please complete the following information)**
- Device: [e.g. iPhone 8]
- OS: [e.g. iOS 13.6]
- VPN mode: [IPsec/L2TP, IPsec/XAuth ("Cisco IPsec") or IKEv2]

Thank you

**Comment by hwdsl2** [comment]
@dettofatto Hello! This is normal, the `ppp0` interface is only created *after* you connect a VPN client using IPsec/L2TP mode. Your logs show that both Libreswan and xl2tpd are listening normally, but there is no client connection attempt. If you have additional logs that show the failed connection, or errors on the VPN client, feel free to reply here.
