### ISSUE TITLE
how do I change IP address

### ISSUE THREAD

**Issue by joeylu** [hwdsl2/setup-ipsec-vpn#93]
first of all, great script!
I need to change my ubuntu l2tp server's IP to another one, I have modified the network/interfaces and right now my server is pingable
I also changed to /etc/iptables.rules and /etc/ipsec.secrets to the new ip, however, my l2tp services is no longer working, am I missing anything? please advice, tks

**Comment by hwdsl2** [comment]
@joeylu Hello! If your server's IP changes, just run the VPN setup script again. Basically, in addition to the configuration files, the IPTables rules also need to be modified. The VPN setup script will take care of that for you.
