### ISSUE TITLE
是否支持指定网关服务器？

### ISSUE THREAD

**Issue by liyouleo911** [hwdsl2/setup-ipsec-vpn#931]
我在家里同一台主机上部署了openwrt的docker镜像做旁路由，旁路由的ip是192.168.21.120，需要访问外网的设备将网关改到该ip即可。现在的情况是vpn连上后局域网和国内网站访问正常，需要翻墙的服务无法访问，猜测是网关服务器的问题？是否支持给客户端指定网关呢？

**Comment by hwdsl2** [comment]
@liyouleo911 你好！据我所知，不支持从 VPN 服务器为客户端指定网关地址。但你可以试一下将 VPN 服务器的默认网关改为该网关，从而使客户端连接后自动使用这个网关？你的这个用例我不太了解，没有测试过。
