### ISSUE TITLE
请问一下这种情况是不是路由器的问题？

### ISSUE THREAD

**Issue by liuyuan22** [hwdsl2/setup-ipsec-vpn#932]
以前用的tp-link路由器，按照说明设置的一直很好用。

昨天换成了新买的红米ac2100路由器，vpn仍然能连接成功，但是像谷歌之类的网页却打不开了，我把原来的vpn连接删了重新创建依然如此。

想问一下这可不可能是路由器造成的问题？

**Comment by hwdsl2** [comment]
@liuyuan22 你好！这个问题是有可能和路由器有关。检查一下比如路由器的 VPN Passthrough 相关设置，参见 [1]。另外你可以尝试清除客户端上的 DNS 缓存。

[1] https://www.tp-link.com/us/support/faq/558/

**Comment by Scottpedia** [comment]
@liuyuan22 请问 VPN 客户端是在路由器上运行的吗？连接上 VPN 以后，试图访问`api.ipify.org`来检查当前公网IP，然后看其是否与VPN服务器的IP相符。

**Comment by liuyuan22** [comment]
> @liuyuan22 请问 VPN 客户端是在路由器上运行的吗？连接上 VPN 以后，试图访问`api.ipify.org`来检查当前公网IP，然后看其是否与VPN服务器的IP相符。

不是的，我是在Windows 10的网络和共享中心里设置的vpn。连上vpn之后，访问api.ipify.org看到的ip和我vpn服务器的ip是一样的。总之很神奇，我越来越怀疑是路由器的问题了。

**Comment by Scottpedia** [comment]
我记得几年前小米路由器刚发布的时候，媒体揭露了有中间人攻击（Man-in-the-middle attack）的程序在小米路由器的固件里。用户的数据包有时候会被拦截。 不过技术上来讲，Ipsec VPN的加密措施应该不太可能被破解。总之我是不会信任小米的网络硬件的。
