### ISSUE TITLE
VPN and internet OK, but LAN devices unreachable

### ISSUE THREAD

**Issue by pboiseau** [hwdsl2/setup-ipsec-vpn#933]
Hello,

I'm experiencing an issue with the default VPN configuration of hwdsl2.

When my remote client is connected to the VPN it cannot access to every LAN device that are connected to my local network.

The strange things it's I don't know why but the LAN access is working when using a LTE cellular connection from my phone to connect to the VPN. But when I using a standard WIFI connection with a router, LAN connection is not working.

Here is a schema of my network :

CLIENT LAN NETWORK 192.168.1.0

HOST LAN NETWORK 192.168.1.0

VPN CLIENT (192.168.42.10) -> VPN Server (192.168.56.x) -> LAN ROUTER (192.168.1.1) -> Server 1 (192.168.1.26)

I'm exploring everything I can through the internet but I didn't found any solution for now ...

I was using the L2TP VPN from Synology before and has no problem with it.

Thanks for your help.

**Comment by pboiseau** [comment]
I found something interesting and I think my problem is something like that https://serverfault.com/questions/548888/connecting-to-a-remote-server-through-a-vpn-when-the-local-network-subnet-addres

I curious why the L2TP VPN Server is working perfectly on the Synology package but not using this one here ?

**Comment by hwdsl2** [comment]
@pboiseau Hello! In my earlier tests I was able to access LAN devices when connected to the VPN, without additional configuration.

If it does not work for your use case, usually it's because firewall rules on your LAN devices themselves disallow such traffic, or perhaps you need to add additional routes on the VPN server for the LAN devices. It is not clear why it worked when you connected via LTE.

**Comment by hwdsl2** [comment]
@pboiseau I see that your VPN server (192.168.56.x) and your LAN devices (192.168.1.x) are not on the same network segment. Perhaps you need to add a route on your VPN server in order to be able to access those LAN devices. If you search for earlier issues you'll find some examples.

**Comment by pboiseau** [comment]
Hello @hwdsl2 

Thanks for you'r quick answers ! 

I found that my problem is because I have two same network typology both on local and on host (192.168.1.0). When client try to reach another device from the host, it was routed to his local network and not the host local network.

For exemple, when I try to reach 192.168.1.1 from the client, I end-up with the local client router UI interface and not the host routeur UI interface. 

The only solution I found for now is to specificaly add a route in the client routes table like this : 

`route add 192.168.1.26 192.168.42.10 ppo0`

where 192.168.1.26 is the server on the host I want to reach, and ppo0 the VPN interface on the client.

But I'm wanted to know why I don't need to do that using the L2TP VPN from Synology. 

Did you have any idea ?

**Comment by hwdsl2** [comment]
@pboiseau Thanks for the update. In this case, I think the VPN client would automatically route requests to its local network first, which is "more preferred" than the remote network with the same subnet. Unfortunately I am not aware of a workaround for that.

I suggest that you switch the client and host to use different subnets, if possible. Alternatively, you can add a route like you mentioned. On the other hand, for the Synology case you mentioned, perhaps local and host have different subnets?

**Comment by pboiseau** [comment]
No, when I use the Synology VPN, this was the same subnet for client and host.

Here is the L2TP Synology VPN configuration

```
version 2.0
config setup
    nat_traversal=yes
    virtual_private=%v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12
    oe=off
    protostack=netkey
    listen=192.168.1.24
    #plutodebug=all
    #plutostderrlog=/var/log/pluto.log

conn L2TP-PSK-NAT
    rightsubnet=vhost:%priv
    also=L2TP-PSK-noNAT

conn L2TP-PSK-noNAT
    authby=secret
    pfs=no
    auto=add
    keyingtries=3
    rekey=yes
    ikelifetime=8h
    keylife=1h
    type=transport
    left=192.168.1.24
    leftprotoport=17/1701
    right=%any
    rightprotoport=17/%any
    forceencaps=no
    sha2_truncbug=no
    dpddelay=10
    dpdtimeout=90
    dpdaction=clear
```

Maybe it's the NAT traversal option that does the trick ?

**Comment by hwdsl2** [comment]
@pboiseau I doubt it's the nat_traversal option because that's the default. In this case, I am not sure why it worked with the Synology VPN.
