### ISSUE TITLE
Windows10 ikev2客户端 连接提示：  IKE身份验证凭证不可接受

### ISSUE THREAD

**Issue by lowkey1** [hwdsl2/setup-ipsec-vpn#934]
已经导入vpnclient.p12， 还是报上面错误： IKE身份验证凭证不可接受 。
不导入vpnclient.p12，提示：IKE 无法找到有效的计算机证书。

**Comment by hwdsl2** [comment]
@lowkey1 你好！你的Windows 10版本是什么？到开始菜单搜索并运行certlm.msc, 转到个人->证书，双击你导入到客户端证书。点击证书路径选项卡。看看证书状态是否显示“该证书没有问题”？
如果显示不能验证证书，你需要将IKEv2 VPN CA 移到受信任的根证书颁发机构->证书。

**Comment by hwdsl2** [comment]
@lowkey1 你好！你的Windows 10版本是什么？到开始菜单搜索并运行certlm.msc, 转到个人->证书，双击你导入到客户端证书。点击证书路径选项卡。看看证书状态是否显示“该证书没有问题”？
如果显示不能验证证书，你需要将IKEv2 VPN CA 移到受信任的根证书颁发机构->证书。

**Comment by hwdsl2** [comment]
@lowkey1 你好！你的Windows 10版本是什么？到开始菜单搜索并运行certlm.msc, 转到个人->证书，双击你导入到客户端证书。点击证书路径选项卡。看看证书状态是否显示“该证书没有问题”？
如果显示不能验证证书，你需要将IKEv2 VPN CA 移到受信任的根证书颁发机构->证书。

**Comment by lowkey1** [comment]
Windows 10专业版 版本号 1909， 证书没有问题。
![image](https://user-images.githubusercontent.com/30519246/107878759-b2ce7700-6f0f-11eb-85cc-d81087a99188.png)
![image](https://user-images.githubusercontent.com/30519246/107878784-d0034580-6f0f-11eb-88e5-d5a5357dbb7b.png)

测试下 ：没有将IKEv2 VPN CA 移到受信任的根证书颁发机构->证书, 连接提示 IKE 无法找到有效的计算机证书。

**Comment by hwdsl2** [comment]
@lowkey1 请再次尝试连接，然后检查一下服务器上的 Libreswan 日志。参见这些步骤 [1]。看一下最新的日志有什么错误？如果需要可以贴到这里（去掉你的 IP 地址等）。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E6%A3%80%E6%9F%A5%E6%97%A5%E5%BF%97%E5%8F%8A-vpn-%E7%8A%B6%E6%80%81

**Comment by hwdsl2** [comment]
@lowkey1 另外，检查一下你在配置客户端时指定的服务器地址是否与你在安装 IKEv2 时指定的地址一致？例如，如果在安装 IKEv2 时指定了服务器的 IP 地址，则不能使用域名连接到 VPN 服务器，必须使用 IP 地址。

你可以在服务器上的 `/etc/ipsec.d/ikev2.conf` 中的 `leftid=` 一行找到安装 IKEv2 时指定的服务器地址。

**Comment by lowkey1** [comment]
感谢，就是安装时候没有指定域名，连接的时候用的域名导致 IKE身份验证凭证不可接受 。
删掉容器后，配置VPN_DNS_NAME=vpn.example.com，使用域名连接成功了。
