### ISSUE TITLE
Add aws instance-scheduler to the template?

### ISSUE THREAD

**Issue by Tigerzuo** [hwdsl2/setup-ipsec-vpn#935]
I wish there can be a way to schedule the aws instance, could that be added to the template somehow? Thanks!

**Comment by Scottpedia** [comment]
Can you please further elaborate on the use of that feature?

**Comment by Tigerzuo** [comment]
Yeah, say I only want to turn it on on Sunday morning. Just to save some ec2 credits.

**Comment by Scottpedia** [comment]
Sorry but I personally do not see that feature needed by a lot of people. Let's see what the project author says.  @hwdsl2 

Alternatively,  you can do it yourself in a forked directory. I previously have tried to do the same and it's completely feasible, with AWS cloudwatch.

**Comment by Scottpedia** [comment]
@Tigerzuo For your personal needs, I can help you add this feature for you, but not added to the main repo. It's not a big deal.

**Comment by Tigerzuo** [comment]
@Scottpedia great, that would be really helpful. How can we chat about it?

**Comment by Scottpedia** [comment]
Let's do it via email. me@theanonymity.de

**Comment by Scottpedia** [comment]
@Tigerzuo By the way, close this issue if you don't have any further questions.
