### ISSUE TITLE
How to connect the designated website directly to the local network instead of using the VPN network 

### ISSUE THREAD

**Issue by s8xym2n** [hwdsl2/setup-ipsec-vpn#939]
Once this type of VPN is connected, it will cause all the traffic of the device to flow through the VPN. 
Including access to external network resources. 
If the VPN server external network is slow, or the distance from the server is too far, it will seriously affect the speed of access to the external network.
Some websites and apps require a VPN, but some do not require a VPN to access.

Thank you again for your selfless dedication and answers.

**Comment by hwdsl2** [comment]
@s8xym2n This feature is not supported, you cannot exclude specific websites from the VPN. There is a different feature where you can let one specific subnet go through the VPN, and exclude all other traffic. See #785 for more information. This may not be what you want, however. You can look into alternative solutions for your use case.

**Comment by s8xym2n** [comment]
Thank you!
