### ISSUE TITLE
Setting up this alongside nginx and irc server 

### ISSUE THREAD

**Issue by tunayuyar** [hwdsl2/setup-ipsec-vpn#94]
Hi,

I checked the script but wanted to be sure.

Can I run/setup this vpn alongside nginx and irc server (using the default ports) ?

Thanks.

**Comment by hwdsl2** [comment]
@tunayuyar Yes, you should be able to do that without issues. In case you need to modify the IPTables rules after install, edit `/etc/iptables.rules` and/or `/etc/iptables/rules.v4` (Ubuntu/Debian), or `/etc/sysconfig/iptables` (CentOS). Then reboot your server.
