### ISSUE TITLE
problem on windows 7

### ISSUE THREAD

**Issue by Arioshoma** [hwdsl2/setup-ipsec-vpn#940]
The following command is not working on windows7:

```
set server_addr="Your VPN Server IP (or DNS name)"
# Create VPN connection
powershell -command "Add-VpnConnection -Name 'My IKEv2 VPN' -ServerAddress '%server_addr%' -TunnelType IKEv2 -AuthenticationMethod MachineCertificate -EncryptionLevel Required -PassThru"
# Set IPsec configuration
powershell -command "Set-VpnConnectionIPsecConfiguration -ConnectionName 'My IKEv2 VPN' -AuthenticationTransformConstants GCMAES256 -CipherTransformConstants GCMAES256 -EncryptionMethod AES256 -IntegrityCheckMethod SHA256 -PfsGroup None -DHGroup Group14 -PassThru -Force"
```

**Comment by hwdsl2** [comment]
@Arioshoma Hello! Windows 7 does not support creating VPN connections using PowerShell commands. Please instead follow these manual instructions [1].

This is mentioned in the IKEv2 client instructions [2]: "For Windows 8.x and 10, it is recommended to create the VPN connection using the following commands from a command prompt".

[1] https://wiki.strongswan.org/projects/strongswan/wiki/Win7Config
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md#configure-ikev2-vpn-clients
