### ISSUE TITLE
Port forwarding with mikrotik as client

### ISSUE THREAD

**Issue by dettofatto** [hwdsl2/setup-ipsec-vpn#941]
I didn't found any good solution for my issue, so I write here, how I've done.
I've done with mikrotik as client.
On my vps I've set this rules for port 443
In your case you must change ens192, with your ethernet name 

iptables -I FORWARD 2 -i ens192 -o ppp+ -p tcp --dport 443 -j ACCEPT
iptables -t nat -A PREROUTING -p tcp --dport 443 -j DNAT --to 192.168.42.10
iptables -t nat -A POSTROUTING -d 192.168.42.10 -p tcp --dport 443 -j SNAT --to-source 192.168.42.1

On my mikrotik under firewall >nat  add chain dstnat , protocol TCP , dst port 443, in interface our vpn named, 
Under action dst-nat to address IP our server, to port 443

I've also edited the file chap-secrets and replaced * with 192.168.42.10 on my vps for assigning the right ip to my mikrotik, because sometimes change.

**Comment by hwdsl2** [comment]
@dettofatto Thank you for sharing your solution for forwarding ports to Mikrotik.

**Comment by bakhtiyarsierad** [comment]
anybody try this?
