### ISSUE TITLE
IPsec VPN XAUTH PSK on Ubuntu

### ISSUE THREAD

**Issue by bk7473077** [hwdsl2/setup-ipsec-vpn#943]
I need help with IPsec VPN XAUTH PSK on Ubuntu.
I made VPN connection with [https://github.com/hwdsl2/setup-ipsec-vpn](url) script, it works with Windows client.
But I need to install it directly to my router (Fritz!Box).
In router settings I need to introduce:
- The VPN server's internet address - it's clear
- IP network of the company's VPN (IP and subnet mask) - I've just try everything (on the ground of ipconfig date on Ubuntu)
- VPN user name (IPsec ID, Key ID) of the VPN connection in the VPN server - isn't it a Group? I've added it to ipsec.conf, by don't know if correctly
- PSK - it's clear
The router has limited support of vpn protocols :

> The FRITZ!Box supports VPN connections according to the IPSec standard with ESP, IKEv1, and pre-shared keys. Authentication Header (AH) and Perfect Forward Security (PFS) are not supported.
Supported IPSec algorithms for IKE phase 1:
Encryption method: AES with 256, 192, 128 bit, Triple DES with 168 bit or DES with 56 bit
Hash algorithms: SHA2-512, SHA1 or MD5-96
The FRITZ!Box uses 1024-bit Diffie-Hellman initial key exchange (DH group 2). It then also accepts 768, 1536, 2048 and 3072 bit (DH groups 1, 5, 14, and 15).
Supported IPSec algorithms for IKE phase 2:
Encryption method: AES with 256, 192, 128 bit, Triple DES with 168 bit or DES with 56 bit
Hash algorithms: SHA2-512, SHA1 or MD5-96
The Diffie-Hellman group is determined by IKE phase 1
Compression: none

Please help! I really need it works on this router!
Thanks a lot

**Comment by hwdsl2** [comment]
@bk7473077 Hello! For your use case, Fritz!Box as an IPsec VPN client requires IPsec aggressive mode which is not supported in the default configuration created by the VPN setup scripts. Refer to earlier issues #836, #665 and #303 for more information.
