### ISSUE TITLE
Can connect to VPN and browse local network but no internet..

### ISSUE THREAD

**Issue by jamesholz** [hwdsl2/setup-ipsec-vpn#944]
Hi there

Have been using your VPN script successfully for a while but it seems recently I'm unable to use the VPN to browse external internet sites using safari on iPhone (not tested on other clients). I can access any local sites/applications/files but nothing external. 

So in short, I can connect, I can browse locally, but can't browse any external or internet sites.

The server is - Ubuntu 20.04.1 LTS

I haven't changed any settings on the script at all. Using the defaults.

Any suggestions?

Thanks heaps

**Comment by hwdsl2** [comment]
@jamesholz Hello! Which mode did you use to connect to the VPN from the iPhone (is it IPsec/L2TP, Cisco IPsec or IKEv2)? This could be caused by incorrect IPTables rules on your VPN server (check using: `sudo iptables -nL; sudo iptables -nL -t nat`), or perhaps your VPN server itself has issues accessing the Internet. Can you also try using a different device to connect to the VPN?

**Comment by jamesholz** [comment]
Great thanks.. I have tried all 3 modes. The VPN server is able to connect to the internet without any issue. 

This is the IPTables output. Do you think this looks okay?

I don't know too much about this so I appreciate you taking some time to look. As I mentioned it has worked perfectly for a long period of time and then stopped.  Today I uninstalled and removed everything as per the instructions listed and re-installed to same outcome.

`Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
DROP       udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:1701 policy match dir in pol none
DROP       all  --  0.0.0.0/0            0.0.0.0/0            ctstate INVALID
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 500,4500
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:1701 policy match dir in pol ipsec
DROP       udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:1701

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
DROP       all  --  0.0.0.0/0            0.0.0.0/0            ctstate INVALID
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0           
ACCEPT     all  --  192.168.42.0/24      192.168.42.0/24     
ACCEPT     all  --  0.0.0.0/0            192.168.43.0/24      ctstate RELATED,ESTABLISHED
ACCEPT     all  --  192.168.43.0/24      0.0.0.0/0           
DROP       all  --  0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
MASQUERADE  all  --  192.168.42.0/24      0.0.0.0/0           
MASQUERADE  all  --  192.168.43.0/24      0.0.0.0/0            policy match dir out pol none`

**Comment by hwdsl2** [comment]
@jamesholz Can you also check the output of
`iptables -nvL -t nat` and `ip route`? Do you have multiple network interfaces on the server?

It could also be an issue with DNS. Try if you can connect to https://1.1.1.1 while connected to the VPN?

**Comment by Masood-Lapeh** [comment]
I had a similar problem where I could connect to server but I had no internet (Not even to `https://9.9.9.9:5053/dns-query`) and rebooting or reinstalling VPNs didn't solve the issue, but DNATting some ipsec traffics to a transparent proxy (ran by gost) could work. So I executed something like `ip route add 192.168.0.0/16 via ---.---.---.--- dev ens160`. Now the problem is gone. But is it the correct way? And why it wasn't there?

**Comment by hwdsl2** [comment]
@Masood-Lapeh Hello! Your VPN server may be missing some required IPTables rules for the VPN, for example, some rules could be accidentally removed after VPN setup. For Ubuntu/Debian, here is the relevant section in the script:
https://github.com/hwdsl2/setup-ipsec-vpn/blob/24ceda8809c70d1cfe8d0908b303717a5081f3ca/vpnsetup_ubuntu.sh#L571-L609
Check using `sudo iptables -nvL; sudo iptables -nvL -t nat`.
