### ISSUE TITLE
Update cloudformation template for "Advanved Usage"

### ISSUE THREAD

**Issue by Scottpedia** [hwdsl2/setup-ipsec-vpn#945]
**Checklist**

- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [x] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
A clear and concise description of your enhancement request.

I saw you added "Advanced Usage" section in the README.md. I wonder if I can add the corresponding configs to cloudformation template.(i.e. custom dns servers)?

**Is your enhancement request related to a problem? Please describe.**
(If applicable) A clear and concise description of what the problem is.

**Additional context**
Add any other context about the enhancement request here.

**Comment by hwdsl2** [comment]
@Scottpedia Hello! The custom DNS servers is not a frequently used feature (which is why it was added as an advanced usage). I don't think there's any urgent need to add it to the CloudFormation template. However, if you would like to do that, please feel free to open a PR. Thanks for contributing!
