### ISSUE TITLE
Android 9 无法连接

### ISSUE THREAD

**Issue by power76** [hwdsl2/setup-ipsec-vpn#949]
win7成功连接，android 9一直连接不上server，不管是使用移动网络还是wifi都不行

**Comment by power76** [comment]
> win7成功连接，android 9一直连接不上server，不管是使用移动网络还是wifi都不行

非常奇怪，android服务端配置成IPsec/XAuth mode.后可以正常连接了，L2TP始终不行。

**Comment by hwdsl2** [comment]
@power76 你好！如果你的 Windows 7 和 Android 设备在同一个 NAT （比如家用路由器）后面的话，它们必须使用同一模式连接，不能混用 IPsec/L2TP 和 IPsec/XAuth ("Cisco IPsec") 模式。例如，如果 Windows 7 使用 IPsec/XAuth 模式，则 Android 也必须使用该模式连接。如果要重置 VPN 服务器的状态，可以尝试运行 `service ipsec restart` 之后再切换模式连接。

**Comment by power76** [comment]
那如果win7使用wifi，android使用移动网络的话是不是就没有这个限制呢？

 

发件人: Lin Song ***@***.*** 
发送时间: 2021年3月12日 14:20
收件人: hwdsl2/setup-ipsec-vpn ***@***.***>
抄送: power76 ***@***.***>; Mention ***@***.***>
主题: Re: [hwdsl2/setup-ipsec-vpn] Android 9 无法连接 (#949)

 

@power76 <https://github.com/power76>  你好！如果你的 Windows 7 和 Android 设备在同一个 NAT （比如家用路由器）后面的话，它们必须使用同一模式连接，不能混用 IPsec/L2TP 和 IPsec/XAuth ("Cisco IPsec") 模式。例如，如果 Windows 7 使用 IPsec/XAuth 模式，则 Android 也必须使用该模式连接。如果要重置 VPN 服务器的状态，可以尝试运行 service ipsec restart 之后再切换模式连接。

**Comment by hwdsl2** [comment]
@power76 是的。另外请检查一下你的 Android 客户端配置，有可能是在添加 IPsec/L2TP 连接时输入了错误的密码或 PSK。更多的故障排除信息请参见 [1]。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E6%A3%80%E6%9F%A5%E6%97%A5%E5%BF%97%E5%8F%8A-vpn-%E7%8A%B6%E6%80%81
