### ISSUE TITLE
Error on install on entos 7.3

### ISSUE THREAD

**Issue by caroseuk** [hwdsl2/setup-ipsec-vpn#95]
Hi, just tried running this on a DO droplet running cento 7.3, after a few seconds the script fails with the following error:

Error: Package: xl2tpd-1.3.8-1.el7.x86_64 (epel)
           Requires: kmod(l2tp_ppp.ko)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by hwdsl2** [comment]
@caroseuk Hello! Thanks for the report. This error is due to a bug [1] in the xl2tpd package (version 1.3.8-1.el7 from EPEL), which affects CentOS 7. I will add a temporary workaround to fix this.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1406360
