### ISSUE TITLE
vpn配置好后，安卓手机连接后无法访问Google

### ISSUE THREAD

**Issue by syjml** [hwdsl2/setup-ipsec-vpn#950]
**任务列表**

- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [x] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] 这个 bug 是关于 VPN 安装脚本，而不是 IPsec VPN 本身

**问题描述**
vpn配置好后，Windows系统可以连上翻墙，安卓手机连上无法翻墙

**重现步骤**
重现该 bug 的步骤：

1. 在Ubuntu 20.04系统上执行vpn.sh安装配置
2. 用安卓手机连接vpn地址
3.vpn连接后访问Google

**期待的正确结果**
可以打开Google页面

**服务器信息（请填写以下信息）**
- 操作系统:ubuntu-20.04
- 服务提供商（如果适用）:GCP

**客户端信息（请填写以下信息）**
- 设备: 一加手机 
- 操作系统: android 11
- VPN 模式:IPsec/L2TP

**Comment by hwdsl2** [comment]
@syjml 你好！该问题比较可能的原因是：
1. 手机的 DNS 缓存之前保存了错误的 Google 的 IP 地址，在连接 VPN 后未请求正确的地址。尝试重启你的 Android 手机，并重新连接 VPN。
2. 你的 VPN 服务器本身屏蔽了对 Google 的访问。你可以在服务器上这样测试：`curl https://www.google.com`，看看能不能正常连接。
请尝试以上步骤。另外，你的 Android 手机在连接 VPN 后能不能正常访问除 Google 之外的网站？

**Comment by syjml** [comment]
> @syjml 你好！该问题比较可能的原因是：
> 
> 1. 手机的 DNS 缓存之前保存了错误的 Google 的 IP 地址，在连接 VPN 后未请求正确的地址。尝试重启你的 Android 手机，并重新连接 VPN。
> 2. 你的 VPN 服务器本身屏蔽了对 Google 的访问。你可以在服务器上这样测试：`curl https://www.google.com`，看看能不能正常连接。
> 
> 请尝试以上步骤。另外，你的 Android 手机在连接 VPN 后能不能正常访问除 Google 之外的网站？

1、我在手机上重了VPN，输入的是GCP服务器地址。
2、在服务器上执行curl https://www.google.com 可以正常得到结果。
3、连上VPN后，可以访问国内网站。

**Comment by hwdsl2** [comment]
@syjml 重启一下手机（以清除 DNS 缓存）试试看？我上面的 (1) 是说在没有连接 VPN 的时候，Android 手机可能因为被 DNS 干扰而在缓存中保存了 Google 的错误 IP 地址。可以试一下重启。
另外你可以尝试更换 DNS 服务器。比如换成 Cloudflare DNS 服务 (1.1.1.1, 1.0.0.1)。具体操作步骤请见：
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#%E4%BD%BF%E7%94%A8%E5%85%B6%E4%BB%96%E7%9A%84-dns-%E6%9C%8D%E5%8A%A1%E5%99%A8

**Comment by hwdsl2** [comment]
@syjml 请尝试重启手机或者更换DNS（见上面），看看是否有帮助？

**Comment by hwdsl2** [comment]
Closing. If the problem persists feel free to reply here.
