### ISSUE TITLE
No full Client-Client communication and L2TP issues

### ISSUE THREAD

**Issue by BarbaxX15** [hwdsl2/setup-ipsec-vpn#956]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)
- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] This bug is about the VPN setup scripts, and not IPsec VPN itself

**Describe the issue**
1. ikev2 clients only get assigned different IPv4 adresses, if they use separate certs (maybe intentional).
Once both clients are connected they can ping each other on the 192.168.43.0/24 net.
A hosted game server on one of the clients is not visible on the other (worked prior using Softether VPN Server with L2TP/IPsec on the server machine). UFW is inactive on the Ubuntu 20.04 server, no settings have been changed since running the script and creating the certs.

2. Connecting both clients using L2TP/IPsec simultaneously does not work, only one at a time (does not reach the login phase on the second client if the first is connected).

The server has been rebooted multiple times during testing and diagnosing.

**Server**
- OS: Ubuntu 20.04
- Hosting provider (if applicable): Home (behind NAT)

**Client (please complete the following information)**
- Device: PC
- OS: Windows 10 2009
- VPN mode: IPsec/L2TP,  IKEv2

**Comment by letoams** [comment]
On Wed, 24 Mar 2021, BarbaxX15 wrote:

>     ikev2 clients only get assigned different IPv4 adresses, if they use separate certs (maybe intentional).

Yes it is. certificates are assumed to be unique. You can change this by
setting uniqueids=false. For PSK based connections, it automatically
assumes that.

>     Once both clients are connected they can ping each other on the 192.168.43.0/24 net.
>     A hosted game server on one of the clients is not visible by the other (worked prior using Softether VPN Server with L2TP/IPsec on the server machine). UFW is inactive on the Ubuntu 20.04 server, no
>     settings have been changed since running the script and creating the certs.

That might be related to MTU issues ? Or perhaps some iptables rules
preventing this?

>     Connecting both clients using L2TP/IPsec simultaneously does not work, only one at a time (does not reach the login phase on the second client if the first is connected).

two L2TP clients behind the same NAT won't work in IPsec transport mode.
Please don't try, and use IKEv2 instead. It's a known limitation and
why microsoft also moved away from L2TP/IPsec.

**Comment by BarbaxX15** [comment]
> That might be related to MTU issues ? Or perhaps some iptables rules
preventing this?

I havent touched the iptables since running the script and the script was run after a clean ubuntu install.
Like I said, the same setup worked before using Windows and Softether VPN with L2TP/IPsec (both being connected at the same time).

> two L2TP clients behind the same NAT won't work in IPsec transport mode.

I'm curious then why it worked with Softether prior to switching to Linux... Nevertheless the non-communication issue is my main concern and that occurs in ikev2.

**Comment by hwdsl2** [comment]
@BarbaxX15 Hello! The VPN setup scripts allow client-to-client communication by default [1]. For IKEv2, clients can use their assigned internal IPs in the `192.168.43.0/24` subnet to reach each other.

On your VPN server, run this command and see if it resolves the issue:
```
iptables -I FORWARD -s 192.168.43.0/24 -d 192.168.43.0/24 -j ACCEPT
```

If not, what is the operating system of your game server? I think this could also be related to firewall rules on your game server, you may need to add rule(s) to specifically allow traffic from the `192.168.43.0/24` subnet.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/f6dd26abba08fd421a638caf3d1d0135d0fd154d/vpnsetup.sh#L421-L430

**Comment by BarbaxX15** [comment]
I added the rule via terminal but no luck unfortunately.
It's not a game server per se. Nevertheless I temporarily disabled the firewalls of host and client of the game (both Windows 10) for testing.

What I found out, though is that when I select the normal Ethernet interface in game while ikev2 VPN is active the server shows up with the 192.168.43.10 IP on the other client, but it cant connect to the hosts game session.

Prior I would set the adapter to the Windows VPN adapter (L2TP before) in-game and it would show up and connect.

I noticed that once connected and all traffic is routed through VPN (not only .43.0/24 traffic) some websites do not load (msg: github did not answer to the gateway).

**Comment by hwdsl2** [comment]
@BarbaxX15 If some websites do not load while connected to IKEv2 mode, it could be an MTU/MSS issue. Try the fix in [1].

Did you try setting the adapter to the Windows VPN adapter in-game while connected in IKEv2 mode (similar to what you did for L2TP), and see if it works?

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#android-mtumss-issues

**Comment by BarbaxX15** [comment]
Unfortunately the in-game setting for the adapter did not work either. I tested that initially.

I can not rule out the MTU issue, because I installed Softether VPN with the local bridge functionality since I needed a quick working solution. Will report back when I have time/reason to switch back to Libreswan with NAT.

Thank you
