### ISSUE TITLE
789 error

### ISSUE THREAD

**Issue by Arioshoma** [hwdsl2/setup-ipsec-vpn#957]
While using IPsec/L2TP on windows 7 I get 789 error code
![Ca2pture](https://user-images.githubusercontent.com/36165265/112802682-b6652a00-9087-11eb-9a0b-0d2da02446a8.PNG)

**Comment by hwdsl2** [comment]
@Arioshoma Please see the following link for troubleshooting Windows error 789:
https://documentation.meraki.com/MX/Client_VPN/Troubleshooting_Client_VPN#Windows_Error_789
