### ISSUE TITLE
Wanted to replace SoftEther with this and got following issues.

### ISSUE THREAD

**Issue by borgdrone7** [hwdsl2/setup-ipsec-vpn#958]
Hi,
I have docker containers which are in the same network as my VPN container based on SoftEther. I wanted to setup DNS resolver and configure VPN to use my DNS so I can use names instead of IPs inside VPN, however I couldn't find a way to set DNS server for SoftEther VPN. So I decided to replace it with setup-ipsec-vpn, but I found 2 issues:
1 - For it even to work behind NAT I need to import REG into Windows
2 - It doesn't support multiple connections behind NAT (IPsec/L2TP limitation)
These are pretty big issues and they don't exist with SoftEther. SoftEther works with IPsec/L2TP without any registry import and I can connect as much devices as I want behind NAT all having same external IP without any issues. 
Does anyone know how can I get the same behavior for DNS with SoftEther like with yours VPN_DNS_SRV1 config option? 
Or is there a way to get Windows working without reg import and get more simultaneous connections and I am missing something? 
Thanks

**Comment by hwdsl2** [comment]
@borgdrone7 Hello! IPsec/L2TP mode does have the limitation where multiple devices from behind the same NAT cannot connect simultaneously. I'm not sure why that works using SoftEther. For this project, it is recommended to set up and connect using IKEv2 mode [1]. IKEv2 mode does not require any registry import on Windows, and you will be able to connect multiple devices simultaneously as long as you generate a unique certificate for each VPN client. Read the linked document for more details.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/ikev2-howto.md
