### ISSUE TITLE
Running after reboot?

### ISSUE THREAD

**Issue by antares2001** [hwdsl2/setup-ipsec-vpn#96]
Hello,

does the VPN server start on machine reboot with the same credentials, or do I need to re-run the installer every time I reboot the machine?

Can I after installation change the login credentials or add more users?

Which ports do I need to forward, when the server is behind an internet router?

Thanks for this great script. It really installed without problems within a minute!

**Comment by hwdsl2** [comment]
@antares2001 Hello! To answer your questions:

1. Yes, the VPN server should start on server reboot with the same credentials. There is no need to re-run the installer unless the server's private or public IP changes.
2. To manage VPN users after install, please see [1].
3. You will need to forward UDP ports 500 and 4500 on the router, to your server's private IP.

You're welcome. I am glad the script was helpful.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/manage-users.md
