### ISSUE TITLE
无法通过端口转发的新地址连接

### ISSUE THREAD

**Issue by justingkao** [hwdsl2/setup-ipsec-vpn#962]
**任务列表**

- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [x] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)
- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)
- [x] 这个 bug 是关于 VPN 安装脚本，而不是 IPsec VPN 本身

**问题描述**
我在家庭局域网下的一台ubuntu系统上使用一键脚本安装了服务，从家庭局域网下其他设备直接访问这个IP是可以正常连接服务的。
我的家庭网络具有公网ip地址，我想通过端口转发 绑定到主路由的1701端口 然后从公网访问。
几个月前这种方式是可以访问的。
但是目前使用最新的脚本却无法连接
![image](https://user-images.githubusercontent.com/10344954/114331333-5d60c000-9b76-11eb-9439-bd1767a4c1c1.png)

**重现步骤**
重现该 bug 的步骤：

1. ...
2. ...

**期待的正确结果**
简要地描述你期望的正确结果。

**日志**
[检查日志及 VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)，并添加错误日志以帮助解释该问题（如果适用）。

**服务器信息（请填写以下信息）**
- 操作系统: [比如 Debian 10]
- 服务提供商（如果适用）: [比如 GCP, AWS]

**客户端信息（请填写以下信息）**
- 设备: [比如 iPhone 8]
- 操作系统: [比如 iOS 13.6]
- VPN 模式: [IPsec/L2TP, IPsec/XAuth ("Cisco IPsec") 或 IKEv2]

**其它信息**
添加关于该 bug 的其它信息。

**Comment by hwdsl2** [comment]
@justingkao 你好！对于你的用例，端口转发应该绑定 UDP 500 和 UDP 4500 端口，而不是 UDP 1701。你绑定正确的端口之后再试试看？另外，请确保路由器的端口转发设置了正确的地址，应该是 VPN 服务器的内网地址。

**Comment by justingkao** [comment]
> @justingkao 你好！对于你的用例，端口转发应该绑定 UDP 500 和 UDP 4500 端口，而不是 UDP 1701。你绑定正确的端口之后再试试看？另外，请确保路由器的端口转发设置了正确的地址，应该是 VPN 服务器的内网地址。

我测试的L2tpd的服务，端口是1701，端口转发配置绝对是正确的，从截图的日志里可以看到，服务已经收到连接请求，所以不是网络配置问题。
