### ISSUE TITLE
启动VPN_PUBLIC_IP找不到

### ISSUE THREAD

**Issue by microzhang715** [hwdsl2/setup-ipsec-vpn#963]
最新版本启动日志一直提示下面错误信息，除非手动指定固定IP否则无法正常启动，老版本的Docker能够正常启动且无需指定固定IP信息，应该是新版本出现给你IP检测的bug导致，麻烦修复一下，谢谢

Error: Cannot detect this server's public IP. Define it in your 'env' file as 'VPN_PUBLIC_IP'.

Trying to auto discover IP of this server...
Error: Cannot detect this server's public IP. Define it in your 'env' file as 'VPN_PUBLIC_IP'.

Trying to auto discover IP of this server...
Error: Cannot detect this server's public IP. Define it in your 'env' file as 'VPN_PUBLIC_IP'.

**Comment by hwdsl2** [comment]
@microzhang715 你好！最新版本已测试，无法重现此问题。`run.sh` 中检测公有 IP 的代码最近并没有修改过。你说的这个错误一般是因为 Docker 容器无法访问因特网导致的。请检查一下你的 Docker 配置，尤其是网络相关的配置。你也可以尝试运行其它的镜像，看看是否也不能访问网络。如果你有更多信息，可以在这里回复。

**Comment by zhongwei** [comment]
同样的镜像在ubuntu 21.10中就报错 Error: Cannot detect this server's public IP. Define it in your 'env' file as 'VPN_PUBLIC_IP'.
ubuntu 20.04 就可以，尝试了好几次都是一样的错。几个月前的版本也一样。
