### ISSUE TITLE
How to Check Active user connected to monitoring speed

### ISSUE THREAD

**Issue by bakhtiyarsierad** [hwdsl2/setup-ipsec-vpn#965]
Hi...
Thank's before

ihave a questions, how to we know user active connected? may be you have advice

Thank;s before

**Checklist**

- [ ] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [ ] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [ ] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [ ] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [ ] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [ ] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
A clear and concise description of your enhancement request.

**Is your enhancement request related to a problem? Please describe.**
(If applicable) A clear and concise description of what the problem is.

**Additional context**
Add any other context about the enhancement request here.

**Comment by hwdsl2** [comment]
@bakhtiyarsierad Hello! You may run `ipsec whack --trafficstatus` on the VPN server to see currently connected VPN users, etc. For IKEv2 mode, look for the `id` field in the output. For IPsec/XAuth ("Cisco IPsec") mode, look for the "username" field. For IPsec/L2TP mode, there is no easy way to check connected VPN users.

**Comment by letoams** [comment]
ipsec trafficstatus

**Comment by horasjey** [comment]
> @bakhtiyarsierad Hello! You may run `ipsec whack --trafficstatus` on the VPN server to see currently connected VPN users, etc. For IKEv2 mode, look for the `id` field in the output. For IPsec/XAuth ("Cisco IPsec") mode, look for the `username` field. For IPsec/L2TP mode, there is no easy way to check connected VPN users.

how about if my vpn not use ipsec IKEv2 sir..?
