### ISSUE TITLE
如何给某一客户端，分配固定的局域网ip

### ISSUE THREAD

**Issue by userofjack** [hwdsl2/setup-ipsec-vpn#966]
如何让某个客户端连接时，始终获得固定的局域网ip

**Comment by hwdsl2** [comment]
@userofjack 你好！该功能仅在 IPsec/L2TP 模式下可用，不支持其他模式。请参见 [1]，按照链接中的说明编辑 `/etc/ppp/chap-secrets` 并运行 `service xl2tpd restart`。要注意，为客户端指定的固定 IP 必须在子网 `192.168.42.0/24` 中，而且不能是自动分配的 IP 地址池 `192.168.42.10-192.168.42.250` 中的 IP。也就是说，在默认配置下只能分配这些固定 IP：`192.168.42.2-192.168.42.9`。

如果要分配更多的固定 IP，则必须缩小自动分配的 IP 地址池。例如，你可以编辑 `/etc/xl2tpd/xl2tpd.conf` 并将`192.168.42.10-192.168.42.250` 替换为比如 `192.168.42.100-192.168.42.250`，这样就可以分配更多的固定 IP：`192.168.42.2-192.168.42.99`。

[1] https://libreswan.org/wiki/VPN_server_for_remote_clients_using_IKEv1_with_L2TP#PPP_server_configuration
