### ISSUE TITLE
使用vpn正常也可以ping通但是局域网游戏无法进行war3

### ISSUE THREAD

**Issue by Cashew-wood** [hwdsl2/setup-ipsec-vpn#969]
**任务列表**

- [√] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)，没有找到类似的改进建议
- [√ ] 这个改进建议是关于 VPN 安装脚本，而不是 IPsec VPN 本身
- [√] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [√] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [√] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [√] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)

**描述改进建议**
使用清楚简明的语言描述你的改进建议。
进行war3(魔兽争霸3)或者其他局域网游戏无法找到对方信息，vpn正常可以互相ping通联网正常，防火墙服务器(Centos7)，两个客户端(Windows10)都已经关闭,本地测试游戏互相联网正常。
**你的改进建议与遇到的问题有关吗？请描述。**
（如果适用）清楚，简洁地说明问题所在。

**其它信息**
添加关于该改进建议的其它信息。

**Comment by hwdsl2** [comment]
@Cashew-wood 你好！你的两个 VPN 客户端是用什么模式连接，IPsec/L2TP, IPsec/XAuth ("Cisco IPsec") 还是 IKEv2？它们应该使用同一模式连接才能通信。关于内网 IP 请参见 [1]，VPN 客户端可以用分配的内网 IP 进行通信，比如客户端 1 分配了 IP 192.168.42.10，客户端 2 分配了 IP 192.168.42.11，则客户端 1 可以使用 IP 192.168;.42.11 访问客户端 2。要找到为特定的客户端分配的 IP，可以查看该客户端上的连接状态。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#vpn-%E5%86%85%E7%BD%91-ip-%E5%92%8C%E6%B5%81%E9%87%8F

**Comment by Cashew-wood** [comment]
> @Cashew-wood 你好！你的两个 VPN 客户端是用什么模式连接，IPsec/L2TP, IPsec/XAuth ("Cisco IPsec") 还是 IKEv2？它们应该使用同一模式连接才能通信。关于内网 IP 请参见 [1]，VPN 客户端可以用分配的内网 IP 进行通信，比如客户端 1 分配了 IP 192.168.42.10，客户端 2 分配了 IP 192.168.42.11，则客户端 1 可以使用 IP 192.168.42.11 访问客户端 2。要找到为特定的客户端分配的 IP，可以查看该客户端上的连接状态。
> 
> [1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#vpn-%E5%86%85%E7%BD%91-ip-%E5%92%8C%E6%B5%81%E9%87%8F

你好两个客户端都采用IKEv2方式连接。

**Comment by hwdsl2** [comment]
@Cashew-wood 好的。请按照上面链接中的说明操作，对于 IKEv2，客户端分配的内网 IP 在 192.168.43.10-192.168.43.250 范围内。比如客户端 1 分配了 IP 192.168.43.10，客户端 2 分配了 IP 192.168.43.11，则客户端 1 可以输入 IP 192.168.43.11 访问客户端 2。要找到为特定的客户端分配的 IP，可以查看该客户端上的连接状态。在默认配置下允许客户端之间的通信。你再尝试一下？

**Comment by Cashew-wood** [comment]
你好，我在客户端启动UDP进行测试是没问题的，我猜测应该不是连接问题，可能vpn不是真正局域网导致的又或者是缺少网关。

**Comment by hwdsl2** [comment]
@Cashew-wood 客户端连接测试没有问题的话，如你所说确实可能是 VPN 客户端内网的问题。建议你可以另外尝试一下 OpenVPN [1]。

[1] https://github.com/Nyr/openvpn-install
