### ISSUE TITLE
Help setting up router as l2tp/ipsec client

### ISSUE THREAD

**Issue by mosimo** [hwdsl2/setup-ipsec-vpn#97]
Great setup guide. I have the server set up as L2TP/IPSEC and I can connect fine within windows and my android phone. I'm not trying to set up a 3G router (Teltonica RUT950) to connect as a client but I'm not sure what I need to enter for all the IPSEC settings in the router. Manual is at: http://www.teltonika.lt/product/rut950/ -> Downloads -> User Manual. Relevant pages are 90 onwards for the IPSEC part.

I'll filled this in the best I can using after looking at the linux config. This router uses xl2tpd and strongswan. I can't edit the config files direct as the keep getting overwritten so would like to get it done via the web interface.

Enabled: yes
IKE: IKEv1
Mode: Main
My Identifier type: Address
My Identifier 192.168.2.1 (Router internal IP)
DeadPeer detection: no
Pre Shared Key: ****My PSK***
Remote Endpoint: ****VPN Server External IP****
IP Address/Subnet: /192.168.42.0/24
Enable Keep Alive: yes
Host: 192.168.42.1
Ping Period: 30

Phase 1:
Algo: aes128
Auth: sha1
DH Group: modp1024
Lifetime 1hr

Phase 2:
Algo: aes128
Auth: sha1
PFS Group: modp1024
Lifetime 1hr

I'm getting nothing on the server logs (added debug, and logfile to xl2tpd conf) for attempted connections so I'm not 100% sure if the router is even trying. But I just want to double check the config looks correct or if I need to change anything too.

**Comment by hwdsl2** [comment]
@mosimo Hello! I looked at your configuration for the Teltonica RUT950. They all look fine except the following:

My Identifier: (leave this field empty if possible)
IP Address /Subnet: 0.0.0.0/0

To debug ipsec connections, try this on the server:
```
grep pluto /var/log/auth.log /var/log/secure
grep -e xl2tpd -e ppp /var/log/syslog /var/log/messages
```

If you still cannot get it to work, try alternatives such as OpenVPN with Nyr's script [1]. Any question should be directed to his repo.

[1] https://github.com/Nyr/openvpn-install
