### ISSUE TITLE
More hints about keeping everything uptodate

### ISSUE THREAD

**Issue by vguna** [hwdsl2/setup-ipsec-vpn#970]
First of all, great project! It probably saved me hours of work to setup the different VPN types. Thank you!

I was wondering what has to be done to keep the system uptodate during its lifetime. I read the chapter regarding libreswan and just upgraded it to 4.4. I also did a `apt-get upgrade` with nothing to apply. Is it enough to check from time to time with apt-get and the libreswan script for updates? All the scripts provided I have to update manually from time to time I guess?

It would be cool if the docs explain a bit around this topic.

**Comment by hwdsl2** [comment]
@vguna Thank you for your suggestions! Yes, generally you only need to run the Libreswan upgrade scripts [1] (which you have already done) when a newer version is available. There may be a delay before the new version is supported in this repo. You can subscribe to the Libreswan announcement mailing list [2] for notifications.

For xl2tpd and other packages that the VPN scripts installed during setup, just use the normal update process provided by the OS. For example, on Ubuntu/Debian, run `sudo apt-get update && sudo apt-get dist-upgrade` to update packages, or use `unattended-upgrades` for automatic package updates. Refer to your Linux distribution's documentation for more details.

[1] https://github.com/hwdsl2/setup-ipsec-vpn#upgrade-libreswan
[2] https://lists.libreswan.org/mailman/listinfo/swan-announce
