### ISSUE TITLE
【建议】GCloud访问有问题，删除Linux VMs中对Google Cloud的推荐

### ISSUE THREAD

**Issue by jamesguo71** [hwdsl2/setup-ipsec-vpn#973]
**任务列表**

- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)，没有找到类似的改进建议
- [x] 这个改进建议是关于 VPN 安装脚本，而不是 IPsec VPN 本身
- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [x] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)

**描述改进建议**
考虑删除Linux VMs中对Google Cloud Platform(Google Compute Engine)的推荐，或者添加一些使用警告

**你的改进建议与遇到的问题有关吗？请描述。**
首先，感谢制作并维护这个项目！

我这两天试了一下在GCP的VM（香港服务器）中用这个脚本设置VPN，但是在Mac上连接后，有很多很奇怪的问题：

- Google、Youtube等网站的访问，有时可以，有时又不行
- 国内站点如baidu.com时断时续可以访问，而像https://qifu.baidu.com/ 则总是Failed (TIMEOUT)
- 类似地，访问比如cip.cc，通过浏览器开发者工具观察，无法加载JS、CSS等文件
- 一些国外网站，如panopto.com，也是完全无法访问，因此估计不只是对国内网站的限制

很奇怪的是，SSH登陆之后，ping和curl这些地址是没什么问题的。

我看了在GCP部署VPN的教程，我的配置与这些教程一致。实在不知道Google Cloud做了什么奇怪的限制。

最后我试了下DigitalOcean上部署，上面这些问题就完全消失。

虽然GCP本来也就小众，但是如果有这些问题，也是挺讨厌的。

**其它信息**
无

**Comment by hwdsl2** [comment]
@jamesguo71 你好！感谢你的建议。我在之前的测试中并没有遇到这些问题。我觉得你所说的问题可能和 DNS 缓存 和/或 MTU/MSS 相关。你是用的什么模式连接到 VPN？可以尝试以下解决方案：

1. 清除 Mac 的 DNS 缓存或者重启计算机，然后重新连接。
2. 检查是否启用了 "通过VPN连接发送所有通信" [1]。
3. 在服务器上应用 MTU/MSS 解决方案 [2]。
4. 检查 Libreswan 日志是否有错误 [3]。

另外你可以试一下其它 GCP 区域（比如 us-west1）。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#macos-%E9%80%9A%E8%BF%87-vpn-%E5%8F%91%E9%80%81%E9%80%9A%E4%BF%A1
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#android-mtumss-%E9%97%AE%E9%A2%98
[3] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#%E6%A3%80%E6%9F%A5%E6%97%A5%E5%BF%97%E5%8F%8A-vpn-%E7%8A%B6%E6%80%81
