### ISSUE TITLE
EAP

### ISSUE THREAD

**Issue by viramaham73** [hwdsl2/setup-ipsec-vpn#974]
Hi
Thanks for this repo
but this project use TSK how set EAP connection for ikev2
thanks.

**Comment by hwdsl2** [comment]
@viramaham73 Hello! For IKEv2, this project configures Libreswan to use certificate-based authentication. Libreswan does not yet support EAP authentication for IKEv2.

**Comment by letoams** [comment]
EAPTLS support should in a few months

**Comment by viramaham73** [comment]
thanks
