### ISSUE TITLE
VPN如何设置在访问某个局域网段生效

### ISSUE THREAD

**Issue by Caratacus** [hwdsl2/setup-ipsec-vpn#977]
**任务列表**

- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue)，没有找到类似的改进建议
- [ ] 这个改进建议是关于 VPN 安装脚本，而不是 IPsec VPN 本身
- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md)
- [x] 我已阅读 [重要提示](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#重要提示)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#下一步)
- [x] 我检查了 [故障排除](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#故障排除) 以及 [VPN 状态](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients-zh.md#检查日志及-vpn-状态)

**描述改进建议**
首先十分感谢作者写的项目，我已经使用了两年。目前有一个问题，就是我在连接vpn后，导致我访问其他网站网速变慢（查询到主要原因是因为全局使用了vpn服务器的网络），是否可以设置vpn的作用访问，比如在访问局域网172.16.0.0/12 VPN才生效，否则只使用当前系统的网络？还有一个问题，vpn的配置如何导出，我可能需要把vpn服务器迁移到其他机器上，但是我用的是IKEv2，所以在切换服务器后需要再次生成各个用户的配置文件，如果可以有办法导出再放到对应目录那就最好不过了

**你的改进建议与遇到的问题有关吗？请描述。**
目前的主要原因是因为我在使用贵项目时，没有用作于翻墙，主要用于直接访问其他服务器的内网环境为主，所有有这个场景需要

**其它信息**
再次感谢作者

**Comment by Caratacus** [comment]
我刚刚看了IKEv2的配置文件在/etc/ipsec.d下，麻烦作者有时间解答一下局域网段生效的问题

**Comment by hwdsl2** [comment]
@Caratacus 你好！如果要将 IKEv2 配置迁移到新服务器，可以将目录 `/etc/ipsec.d` 完整复制到新服务器，并保持文件权限一致。然后重启 IPsec 服务。但是请注意，如果你想要 IKEv2 在服务器的 IP 更改后（迁移后）继续正常工作，则必须在一开始配置 IKEv2 时就指定一个域名作为 VPN 服务器的地址。参见 [1]。如果没有指定域名，则需要在新服务器重新配置 IKEv2。

对于设置 VPN 仅在访问某个局域网段生效，这个功能叫做 "split tunneling"。你可以编辑 `/etc/ipsec.conf` 和 `/etc/ipsec.d/ikev2.conf` 两个文件，并将 `leftsubnet` 替换为你想要的网段，比如 `leftsubnet=172.16.0.0/12`。保存修改并重启 IPsec 服务 `sudo service ipsec restart`。该功能在 IPsec/L2TP 模式下不支持。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#%E5%9F%9F%E5%90%8D%E5%92%8C%E6%9B%B4%E6%94%B9%E6%9C%8D%E5%8A%A1%E5%99%A8-ip

**Comment by Caratacus** [comment]
感谢 @hwdsl2 ，已经解决

**Comment by shi-lai-mu** [comment]
> @Caratacus你好注意！如果将 IKEv2 配置迁移到新服务器，可以将`/etc/ipsec.d`完整复制到新服务器，并保持文件一致。然后重新目录如果 IPsec 。但是，你想要 IKEv2 在服务器的 IP 更改后（迁移[1] 如果域名，则需要在新服务器重新配置 IKEv2。
> 
> 为 VPN 设置在访问功能设置的两个段并编辑。这个修改“隧道”`/etc/ipsec.conf`和`/etc/ipsec.d/ikev2.conf`文件，替换`leftsubnet`为你想要的，例如。该`leftsubnet=172.16.0.0/12`重新启动 IPsec`sudo service ipsec restart`在 IPsec/L2TP 模式下不支持。拆分隧道有几种，参见 [2]。
> 
> [1] [https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#%E5%9F%9F%E5%90%8D%E5%92%8C%E6% 9B%B4%E6%94%B9%E6%9C%8D%E5%8A%A1%E5%99%A8-ip](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README-zh.md#%E5%9F%9F%E5%90%8D%E5%92%8C%E6%9B%B4%E6%94%B9%E6%9C%8D%E5%8A%A1%E5%99%A8-ip) [2] [https://wiki.strongswan.org/projects/strongswan/wiki/ForwardingAndSplitTunneling#拆分隧道](https://wiki.strongswan.org/projects/strongswan/wiki/ForwardingAndSplitTunneling#Split-Tunneling)

leftsubnet 该如何配置多个 ip？xxx.xx.xx.xx-xxx.xx.xx.xx，xxx.xx.xx.xx,xxx.xx.xx.xx，"xxx.xx.xx.xx xxx.xx.xx.xx"好像都不行

**Comment by hwdsl2** [comment]
@shi-lai-mu 你好！请参见：
https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/advanced-usage-zh.md#vpn-%E5%88%86%E6%B5%81
