### ISSUE TITLE
使用您的工具进行进一步的应用，但是遇到iptables配置问题，想了好久无法想明白

### ISSUE THREAD

**Issue by andmeics** [hwdsl2/setup-ipsec-vpn#979]
我的基本思路是如下。

首先，通过使用您在GitHub上开源的setup-ipsec-vpn在Vultr上搭建一台IKEv2服务器，位于国内的客户机能顺利代理出去。
然后，在Google Cloud上搭建Wireguard，经过我自己的测试，位于国内的Android手机和Windows 10设备可以顺利代理出去。
最后，[这是我自己的思路做的设置](https://github.com/andmeics/setup-wireguard)，[到这一步](https://github.com/andmeics/setup-wireguard#11%E4%BF%AE%E6%94%B9%E9%98%B2%E7%81%AB%E5%A2%99%E8%A7%84%E5%88%99)，我尝试了2天时间，仍然没能成功。

想请教如何设置iptables规则实现将搭建有IPSec的Vultr服务器作为NAT，最终以Google Cloud上搭建的Wireguard作为出口，位于国内的客户端访问ipinfo将显示Google Cloud的IP。

**Comment by hwdsl2** [comment]
@andmeics 你好！你的这个用例比较特殊，我没有尝试过。在你的用例中，客户端连接到 IPsec VPN 服务器，然后 IPsec 服务器本身再连接到 Wireguard。一般来说，这种 nested VPN 比较难实现。建议你尝试换用其他的解决方案。
