### ISSUE TITLE
Can't connect via Android/Windows 10 device.

### ISSUE THREAD

**Issue by hoyang** [hwdsl2/setup-ipsec-vpn#98]
After add follow line to /etc/ipsec.conf, it can be connect again just like iOS client.
`sha2-truncbug=yes`

See:
[https://code.google.com/p/android/issues/detail?id=196939](https://code.google.com/p/android/issues/detail?id=196939)

**Comment by hwdsl2** [comment]
@hoyang Thank you for the suggestion. Please note that the change to /etc/ipsec.conf you mentioned has already been (re-)added via commit 89d75f7 [1] on Jan. 3, 2017. And yes, this change will fix VPN connections from Android 6 and 7 clients in my tests.

[1] 89d75f7
