### ISSUE TITLE
Possibility to route bewteen subnets?

### ISSUE THREAD

**Issue by bobbyl140** [hwdsl2/setup-ipsec-vpn#983]
**Checklist**

- [x] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [x] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [x] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [x] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [x] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
A clear and concise description of your enhancement request.
The VPN scripts currently allow reaching other devices on the internet, other devices on the server's physical LAN, and other devices on the VPN subnet. However, you cannot communicate between the VPN's subnets. I am currently trying to achieve this, however I don't have enough knowledge about doing this kind of stuff, so if anyone could help me I would appreciate it. Back to the request, I think that the script could be improved if it enabled these routes by default, or maybe provide an option to enable or disable it. My reasoning is, if one device cannot use the same protocol as another, but they need to communicate, by default this won't work. 

**Is your enhancement request related to a problem? Please describe.**
(If applicable) A clear and concise description of what the problem is.
If anyone knows how I could create these routes I would appreciate it, but there isn't a global problem, just an inconvenience for my type of use.

**Additional context**
Add any other context about the enhancement request here.
I have tried using `ip route` to add these, but IPsec and IKEv2 don't use actual interfaces, and L2TP creates and destroys interfaces on the fly and per device. I was able to get a connection from an L2TP client to an IPsec client, but not the other way around. Also, as soon as you disconnect the L2TP device, the route gets destroyed. If anyone knows how I can solve this I would greatly appreciate it. Thanks!

**Comment by hwdsl2** [comment]
@bobbyl140 Hello! By default, IPsec/L2TP VPN clients can reach IKEv2 and IPsec/XAuth ("Cisco IPsec") VPN clients. For the other way around, which is to allow IKEv2 and IPsec/XAuth ("Cisco IPsec") VPN clients to reach IPsec/L2TP VPN clients, run the following command on the VPN server (as `root` or using `sudo`):
```
iptables -I FORWARD 7 -s 192.168.43.0/24 -o ppp+ -j ACCEPT
```
To persist after reboot, add this line to your `/etc/rc.local`, or alternatively, modify `/etc/iptables.rules` and `/etc/iptables/rules.v4` (if exists).
