### ISSUE TITLE
IP Sec ID Router

### ISSUE THREAD

**Issue by danielehrhardt** [hwdsl2/setup-ipsec-vpn#984]
I have a Router that i am trying to connect to this VPN but the Router have a required field for a IPSec ID. 
Can someone tell me what i need to enter there?

On other devices it does work flaweless.

**Comment by letoams** [comment]
You can try putting in the IP or the DNS name

Sent using a virtual keyboard on a phone

**Comment by hwdsl2** [comment]
@danielehrhardt Hello! Please try @letoams's suggestion. It is also likely that the router requires an IPsec "group ID", which should be left blank, otherwise the client may use IPsec "aggressive mode" which is not supported by the VPN setup scripts.
