### ISSUE TITLE
I don`t get an IPv6 address

### ISSUE THREAD

**Issue by FeelLiao** [hwdsl2/setup-ipsec-vpn#985]
**Checklist**

- [ ] I searched existing [Issues](https://github.com/hwdsl2/setup-ipsec-vpn/issues?q=is%3Aissue), and did not find a similar enhancement request
- [ ] This enhancement request is about the VPN setup scripts, and not IPsec VPN itself
- [ ] I read the [README](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md)
- [ ] I read the [Important notes](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#important-notes)
- [ ] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/README.md#next-steps)
- [ ] I checked [Troubleshooting](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#troubleshooting) and [VPN status](https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status)

**Describe the enhancement request**
A clear and concise description of your enhancement request.
I do not have an access to the ipv6 net
If I would like to, what should I do
**Is your enhancement request related to a problem? Please describe.**
(If applicable) A clear and concise description of what the problem is.

**Additional context**
Add any other context about the enhancement request here.

**Comment by hwdsl2** [comment]
@FeelLiao Hello! IPv6 is not yet supported for this project. For this use case, there are alternatives such as OpenVPN [1].

[1] https://github.com/Nyr/openvpn-install
