### ISSUE TITLE
Problems connecting via NAT on only 1 VPS

### ISSUE THREAD

**Issue by hernancussit** [hwdsl2/setup-ipsec-vpn#988]
I have the script configured in several VPS and in only one I have problems connecting, they are all under the same conditions and were tested from my home connection.
In one of these VPS I cannot connect, the Windows error 789 appears, however in the other servers I can connect correctly.
I have checked the firewall rules, I have also left all ports open to the server with no results.
I have compared the `/var/log/auth.log` with the servers where it works and the difference is in the connection port:

The server that does not work, it uses port 500:
`"l2tp-psk" [1] MYHOMEIP # 1: responding to Main Mode from unknown peer MYHOMEIP: 500`

The server that works it uses port 4500:
`"l2tp-psk" [1] MYHOMEIP # 1: responding to Main Mode from unknown peer MYHOMEIP: 4500`

I do not have IKEv2 configured and I do not need it either, I am satisfied with L2TP, so apparently the problem is that it tries to establish an IKE connection when I have L2TP configured in the Windows client

EDIT:
This complete log:
```

"l2tp-psk"[1] MYHOMEIP #1: responding to Main Mode from unknown peer MYHOMEIP:500
"l2tp-psk"[1] MYHOMEIP #2: Oakley Transform [AES_CBC (256), HMAC_SHA1, DH20] refused
"l2tp-psk"[1] MYHOMEIP #2: Oakley Transform [AES_CBC (128), HMAC_SHA1, DH19] refused
"l2tp-psk"[1] MYHOMEIP #2: sent Main Mode R1
"l2tp-psk"[1] MYHOMEIP #2: sent Main Mode R2
"l2tp-psk"[1] MYHOMEIP #2: STATE_MAIN_R2: retransmission; will wait 0.5 seconds for response
"l2tp-psk"[1] MYHOMEIP #2: STATE_MAIN_R2: retransmission; will wait 1 seconds for response
"l2tp-psk"[1] MYHOMEIP #2: STATE_MAIN_R2: retransmission; will wait 2 seconds for response
"l2tp-psk"[1] MYHOMEIP #2: STATE_MAIN_R2: retransmission; will wait 4 seconds for response
"l2tp-psk"[1] MYHOMEIP #2: STATE_MAIN_R2: retransmission; will wait 8 seconds for response
"l2tp-psk"[1] MYHOMEIP #2: STATE_MAIN_R2: retransmission; will wait 16 seconds for response
"l2tp-psk"[1] MYHOMEIP #1: STATE_MAIN_R2: 60 second timeout exceeded after 7 retransmits.  No response (or no acceptable response) to our IKEv1 message
"l2tp-psk"[1] MYHOMEIP #1: deleting state (STATE_MAIN_R2) aged 64.044811s and NOT sending notification
"l2tp-psk"[1] MYHOMEIP #2: STATE_MAIN_R2: retransmission; will wait 32 seconds for response
"l2tp-psk"[1] MYHOMEIP #2: STATE_MAIN_R2: 60 second timeout exceeded after 7 retransmits.  No response (or no acceptable response) to our IKEv1 message
"l2tp-psk"[1] MYHOMEIP #2: deleting state (STATE_MAIN_R2) aged 64.04426s and NOT sending notification
"l2tp-psk"[1] MYHOMEIP: deleting connection instance with peer MYHOMEIP {isakmp=#0/ipsec=#0}
```

**Comment by hwdsl2** [comment]
@hernancussit Hello! The VPN server should have UDP port 500 and UDP port 4500 open. It looks like you've already opened both of those ports. Your logs indicate that there are network issues (which interfere with IPsec VPN traffic on either port 500 or 4500) between your VPN client and the VPS server. You may want to check with your VPS provider, or alternatively, try a different VPS provider. On the other hand, the logs "responding to Main Mode from unknown peer ...:500" is normal.
