### ISSUE TITLE
clients-xauth-zh.md 中的错误

### ISSUE THREAD

**Issue by yike8** [hwdsl2/setup-ipsec-vpn#989]
_下载并安装免费的 Shrew Soft VPN 客户端。在安装时请选择 Standard Edition。
注： 该 VPN 客户端 不支持 Windows 10。_
--------------------------------
实际上Shrew Soft VPN 2.2.2 是支持Windown10的，详细配置过程请参考
https://www.asus.com/support/FAQ/1033576/

**Comment by Scottpedia** [comment]
@yike8 

你好

你自己试过了吗？我几个月前尝试的时候Windows10上无法使用此客户端。

**Comment by hwdsl2** [comment]
@yike8 你好！Shrew Soft VPN 客户端最后一次更新为 2013 年，它的官网显示并不支持 Windows 10：https://www.shrew.net/download/vpn
我之前测试过，在 Windows 10 上虽然可以连接，但是有一些较严重的 bug，比如流量不经过 VPN。所以不推荐在 Windows 10 上使用。

**Comment by yike8** [comment]
> @yike8
> 
> 你好
> 
> 你自己试过了吗？我几个月前尝试的时候Windows10上无法使用此客户端。
> 而且你提供的教程文章里使用的操作系统很明显是Windows 7 。

我测试了，按照链接配置可以正常使用。



> @yike8 你好！Shrew Soft VPN 客户端最后一次更新为 2013 年，它的官网显示并不支持 Windows 10：https://www.shrew.net/download/vpn
> 我之前测试过，在 Windows 10 上虽然可以连接，但是有一些较严重的 bug，比如流量不经过 VPN。所以不推荐在 Windows 10 上使用。

流量不经过VPN？怎么理解这句话？
我使用这个软件之后，是可以连回自己的设备。
我的使用场景，连上VPN后，使用mstsc连接家里的windowns机器。

**Comment by hwdsl2** [comment]
@yike8 我之前使用 Shrew Soft VPN client 在 Windows 10 上测试过几次，在其中一次测试中，连接 VPN 后浏览器检测 IP 网站显示的是计算机的公网 IP 而不是 VPN 服务器的 IP。具体原因未知。
