### ISSUE TITLE
如何修改出口网关/网卡？

### ISSUE THREAD

**Issue by Ssssix40** [hwdsl2/setup-ipsec-vpn#990]
您好，我的主网卡是eth0，然后有一个虚拟网卡wg0，我想把ipsec client的流量通过wg0出去
我有尝试过修改`/etc/ipsec.conf`文件中的`left`为wg0的ip地址，但是并不奏效，此时client也无法连接

**Comment by Ssssix40** [comment]
这里是大概的一个拓扑图

![](https://ftp.bmp.ovh/imgs/2021/07/e93537bd528e1106.png)

目前我在ipsec client访问ifconfig.me能得到ipsec server的公网IP，我的目的是想要获得wireguard server的公网IP

**Comment by hwdsl2** [comment]
@Ssssix40 你好！如果要指定出口网卡，你可以尝试编辑 `/etc/sysctl.conf`, `/etc/iptables.rules` 和 `/etc/iptables/rules.v4`（如果存在）。将所有相关的 `eth0` 替换为 `wg0`。保存文件并重启服务器。应该不需要修改 `/etc/ipsec.conf`。VPN 相关的 IPTables 规则请参见脚本 [1] 中的包含 `NET_IFACE` 变量的行。

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/vpnsetup.sh

**Comment by AnonymousWebHacker** [comment]
> @Ssssix40 你好！如果要指定出口网卡，你可以尝试编辑 `/etc/sysctl.conf`, `/etc/iptables.rules` 和 `/etc/iptables/rules.v4`（如果存在）。将所有相关的 `eth0` 替换为 `wg0`。保存文件并重启服务器。应该不需要修改 `/etc/ipsec.conf`。需要修改的 VPN 相关的 IPTables 规则请参见脚本 [1] 中的包含 `NET_IFACE` 变量的行。
> 
> [1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/vpnsetup.sh

@Ssssix40 this work for you?

**Comment by Ssssix40** [comment]
> > @Ssssix40 你好！如果要指定出口网卡，你可以尝试编辑 `/etc/sysctl.conf`, `/etc/iptables.rules` 和 `/etc/iptables/rules.v4`（如果存在）。将所有相关的 `eth0` 替换为 `wg0`。保存文件并重启服务器。应该不需要修改 `/etc/ipsec.conf`。需要修改的 VPN 相关的 IPTables 规则请参见脚本 [1] 中的包含 `NET_IFACE` 变量的行。
> > [1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/vpnsetup.sh
> 
> @Ssssix40 this work for you?

Actually, I gave up.
I'm sorry.
But I think this will work.

**Comment by AnonymousWebHacker** [comment]
I already tried several things, and nothing works. Every time I activate the wg client, it encapsulates all the traffic, and I can't connect to the l2tp server
