### ISSUE TITLE
how can i start firewalld service?

### ISSUE THREAD

**Issue by TCLS2014** [hwdsl2/setup-ipsec-vpn#994]
excuse me, when i install vpn, the "firewalld" service is masked. if i start the firewalld service, the vpn could not work, how can i enable the firewalld service?

**Comment by hwdsl2** [comment]
@TCLS2014 Hello! Currently this is not supported. By default, on CentOS 7 and 8, the VPN setup scripts masks the firewalld service and adds required rules directly to IPTables (or nftables). If you re-enable firewalld, the server may lose VPN-related rules and not work. Support for firewalld may be added in the future.
