### ISSUE TITLE
Everything works just fine, but is there a way to remove the 

### ISSUE THREAD

**Issue by Mattz-P** [hwdsl2/setup-ipsec-vpn#995]
After a perfectly functional server setted up, and the IOS vpn client being installed just fine, the only thing that bothers me is the Unknown under my Server Description. Any methods so I can change this value?

![image](https://user-images.githubusercontent.com/33806410/129389431-7514d558-e185-4e00-8fbc-46044569c903.png)

**Comment by letoams** [comment]
I think (but am not 100% sure) these you see that for all unsigned .mobileconfig profiles.

Paul

Sent using a virtual keyboard on a phone

**Comment by Mattz-P** [comment]
Thanks for the assumption paul. It does sounds reasonable that the "Unknown" may be induced by unsigned profiles. I'll try signing it.

**Comment by gspannu** [comment]
> I think (but am not 100% sure) these you see that for all unsigned .mobileconfig profiles. Paul Sent using a virtual keyboard on a phone
> […](#)

**Unfortunately not**
The unknown tag does not get resolved by signing the profile. 
I have always sign all my profiles and it still shows as unknown. 
Some other setting needs to be changed… 😒

**Comment by hwdsl2** [comment]
@Mattz-P Hello! I think the "Unknown" discussed above is likely related to unsigned iOS configuration profiles, although @gspannu suggested that it's not. If you figure out the answer, let us know. There is no need to worry, as this wording has no effect on the security of the IKEv2 VPN.

**Comment by gspannu** [comment]
> @Mattz-P Hello! I think the "Unknown" discussed above is likely related to unsigned iOS configuration profiles, although @gspannu suggested that it's not. If you figure out the answer, let us know. There is no need to worry, as this wording has no effect on the security of the IKEv2 VPN.

I have been searching for the ‘unknown’ fix for quite sometime. **Signed or unsigned profiles make no difference - with Apple Developer Account signing**. 
_Some of the iOS apps (like Astrill VPN above and many others) that install an iOS  profile automatically do show their individual names; so there is definitely a setting somewhere._ 
About a year back, I did try to find this out by trying to read such a ‘known’ profile back from the iPhone, but never got around to completing it. Got involved in something else… maybe time to look at this again !

**Comment by Mattz-P** [comment]
@gspannu I did attempt to look it in the profile documentation in [Configuration-Profile-Reference.pdf](https://developer.apple.com/business/documentation/Configuration-Profile-Reference.pdf) provided by Apple, though, no luck. I also believed that it's a part within the mobileconfig XML file that can be added by adding a key value pair.

**Comment by Mattz-P** [comment]
@hwdsl2 as tested, the unknown wasn't caused by unsigned profiles; do you have any interest in re-opening this issue? I understand this may not be a top priority issue nor a proper bug, but there are people more than me just looking into the problem and might needs some attention from the community.

**Comment by hwdsl2** [comment]
@Mattz-P Thanks for confirming. Yes I can reopen this for visibility, however because this is mostly a cosmetic issue and not a bug, I might close it after 2 weeks if it's still not clear how this field is set.

**Comment by gspannu** [comment]
> @Mattz-P Thanks for confirming. Yes I can reopen this for visibility, however because this is mostly a cosmetic issue and not a bug, I might close it after 2 weeks if it's still not clear how this field is set.

I agree with Mattz-P. It would be helpful keeping it open, as someone may have figured out the way to set this... And although, it is not a bug, it is an annoyance !

**Comment by Mattz-P** [comment]
After digging in through some [documentations](https://developer.apple.com/documentation/devicemanagement/configuring_multiple_devices_using_profiles), I found the solution:

Add the following key/value pair to the XML mobileconfig file：
      <key>PayloadOrganization</key> 
      <string>YourName, Inc.</string> 
![33335b7a6dda24af3a1c29a51e90a2d](https://user-images.githubusercontent.com/33806410/130323786-42a5c3ab-8f98-4c73-b2a6-2453f15fea80.jpg)

**Comment by Mattz-P** [comment]
In addition, I found this might be helpful:

Adding the following helps you bypass manually typing in passwords:
				<key>SharedSecret</key>
				<data>
				RAN/*DOMLYGENE/RATEDPASSPHR4ASE
				</data>

**Comment by gspannu** [comment]
> After digging in through some [documentations](https://developer.apple.com/documentation/devicemanagement/configuring_multiple_devices_using_profiles), I found the solution:
> 
> Add the following key/value pair to the XML mobileconfig file：
> 
> ```
>       <key>PayloadOrganization</key> 
>       <string>YourName, Inc.</string> 
> ```
> 
> ![33335b7a6dda24af3a1c29a51e90a2d](https://user-images.githubusercontent.com/33806410/130323786-42a5c3ab-8f98-4c73-b2a6-2453f15fea80.jpg)

You are a star !!!

**Comment by letoams** [comment]
On Sat, 21 Aug 2021, Matt wrote:

> After digging in through some documentations, I found the solution:
> 
> Add the following key/value pair to the XML mobileconfig file：
> PayloadOrganization
> YourName, Inc.

In which subsection does this go? The payload for the CA or EE? Or
the payload for the IKEv2 parameters?

**Comment by Mattz-P** [comment]
> On Sat, 21 Aug 2021, Matt wrote: After digging in through some documentations, I found the solution: Add the following key/value pair to the XML mobileconfig file： PayloadOrganization YourName, Inc.
> In which subsection does this go? The payload for the CA or EE? Or the payload for the IKEv2 parameters?

The key/string pair belongs to the same level as <PayloadDisplayName> and other similar payload info tags as shown in the documentation - which is under IKEV2's dictionary value. 
      <key>IKEv2</key>
      <dict>
        <key>PayloadOrganization</key> 
        <string>YourName, Inc.</string> 
       .....
       </dict>

**Comment by LightMoon** [comment]
Hi,

I upgraded to the latest version; however, I see the Unkown under the server description for new users.
Should install everything from scratch to get this fixed?

**Comment by hwdsl2** [comment]
@LightMoon Hello! You'll need to update the IKEv2 helper script to the latest version (which is not currently done during VPN upgrades), then re-export the client's configuration. Finally, remove and re-import the VPN profile on your iOS device.
```
# Update the IKEv2 helper script
wget https://git.io/ikev2setup -O /opt/src/ikev2.sh
# Run the script, then select the option to re-export configuration for a client
sudo bash /opt/src/ikev2.sh
```

**Comment by Mattz-P** [comment]
@LightMoon 

Alternatively you may manually add the following to .iosconfig under <IKEv2>:
      <key>IKEv2</key>
      <dict>
       .....
        <key>PayloadOrganization</key> 
        <string>YourName, Inc.</string> 
       .....
      </dict>

**Comment by Mattz-P** [comment]
@LightMoon

Alternatively you may manually add the following to .iosconfig under :
IKEv2
```
.....
PayloadOrganization
YourName, Inc.
.....
```

**Comment by romatou** [comment]
> I have always sign all my profiles and it still shows as unknown.

@gspannu, how do you sign `.mobileconfig` profiles?

**Comment by gspannu** [comment]
Using Apple Configurator Utility and with a Apple Developer account (£79/ year membership that gives access to Apple developer resources including signing certificates)

On a macOS, open Apple Confogurator, open the mobileconfig file and choose File -> Sign. Select the certificate and the .mobileconfig is signed.

I believe there is a command line to do the same job... but I just use Apple Configurator.

Something like... 
`openssl smime -sign -in abc.mobileconfig -out signed_abc.mobileconfig -signer server.crt -inkey server.key -certfile cert-chain.crt -outform der -nodetach`

**Comment by romatou** [comment]
> openssl smime -sign -in abc.mobileconfig -out signed_abc.mobileconfig -signer server.crt -inkey server.key -certfile cert-chain.crt -outform der -nodetach

Thanks for the tip ✋
