### ISSUE TITLE
cant connect google while using Ethernet

### ISSUE THREAD

**Issue by epsilon-code** [hwdsl2/setup-ipsec-vpn#996]
I follow this guidance and set my own ipsec vpn on my vps server , but i cant connect google while using Ethernet but can connect success while using wifi ,what should i do?

**Comment by hwdsl2** [comment]
@epsilon-code Hello! I don't understand your question. What do you mean by "cant connect google while using Ethernet but can connect success while using wifi"? Please provide more details.

**Comment by epsilon-code** [comment]
Hello, thank you for your reply. After successfully setting up my vps server, I tried to connect to the Internet using a laptop. When using Ethernet to provide the network, it is impossible to access websites that  GFW banned. When I unplug the network cable, use wifi to provide  network, and then connect to the vpn, I can access the website such as google and youtube normally.How can I solve this problem?

**Comment by hwdsl2** [comment]
@epsilon-code You can try flushing the DNS cache [1]. After that, re-connect the VPN and try again. If that doesn't work, unfortunately it may be because your laptop's Ethernet connection have more strict GFW blocking.

[1] https://www.pcmag.com/how-to/how-to-flush-your-dns-cache
