### ISSUE TITLE
Multiple errors and unable to connect (IKEv2)

### ISSUE THREAD

**Issue by squishycat92** [hwdsl2/setup-ipsec-vpn#997]
Hey! I was able to install and setup a VPN server on my Ubuntu 21.04 server today, but I ran into a few issues. The certificates for IKEv2 imported successfully, but when I try to connect on Windows 11, I get a `The network connection between your computer and the VPN server could not be established because the remote server is not responding. This could be because one of the network devices (e.g, firewalls, NAT, routers, etc) between your computer and the remote server is not configured to allow VPN connections. Please contact your Administrator or your service provider to determine which device may be causing the problem.` error (after getting stuck on `Verifying your sign-in info` for some time). This behavior persists even after modifying registry settings as mentioned in the respository. When I try to connect on iOS 12.5.4, I get an error that just states `The VPN server did not respond.`

I've opened ports 500, 1701, and 4500 on my router and server firewall, is there anything else that I could try to help solve this issue? Thank you!

(By the way, I'm not entirely sure where to find the logs, if you could point me in the direction to find them I'll happily share them :D)

**Comment by hwdsl2** [comment]
@squishycat92 Hello! You may check VPN logs for errors [1]. When using IKEv2 mode, it is NOT necessary to make the one-time registry change [2]. Because you cannot connect from Windows and iOS devices, it is very likely that VPN traffic did not reach the VPN server. Check this by connecting using a VPN client, then check the logs before and after the connection attempt. If no new logs appear, then traffic did not reach the VPN server.

It looks like your server is behind a (local) router. You only need to open (forward) UDP port 500 and 4500 for the VPN. UDP port 1701 is not required.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#check-logs-and-vpn-status
[2] https://github.com/hwdsl2/setup-ipsec-vpn/blob/master/docs/clients.md#windows-error-809

**Comment by squishycat92** [comment]
Ah hmmm interesting, I've looked into it a bit more and checked the logs and it seems as if the VPN traffic is unable to reach my server. I am resolving my server IP using DuckDNS though, would that have anything to do with not being able to connect? I've also double-checked my firewall settings and router settings and both are set to allow from port 500 and 4500 across UDP.

![image](https://user-images.githubusercontent.com/62223616/129656653-1cfad1d8-95bb-4778-9f38-e8cfefc76b84.png)

**Comment by hwdsl2** [comment]
@squishycat92 Some Internet service providers (ISPs) use carrier-grade NAT [1] which makes it impossible to host services from your (home) Internet connection. Some other ISPs may block hosted services. These may or may not be apply in your case, however. Perhaps you can test whether other port(s) on your IP address can be reached (e.g. an Nginx server on port 80). If you can't get it to work, I'd suggest that you instead consider setting up the VPN server on a VPS.

[1] https://en.wikipedia.org/wiki/Carrier-grade_NAT

**Comment by squishycat92** [comment]
I don't think that my ISP (Spectrum in the Los Angeles area) blocks any services or ports on my network as I've previously been able to host a Minecraft server (port 25565) and a local Home Assistant install that I was able to portforward without any issues. Any other ideas or suggestions? I can try resetting the network settings on the server (along with redoing the firewall) just to double-check.

**Comment by keliew** [comment]
https://www.yougetsignal.com/tools/open-ports/
https://portchecker.co/
Have you checked whether the port is _really_ open?

**Comment by squishycat92** [comment]
Ah, it says not- I'll try double checking my port forwarding configs then. Thanks!
