### ISSUE TITLE
windows10,debian ikev2客户端可以正常连接，但是部分网页无法访问，比如google,youtube (IKEv2)

### ISSUE THREAD

**Issue by mappinglan** [hwdsl2/setup-ipsec-vpn#998]
**问题描述**
完全按照教程配置，IPsec/L2TP正常。 IKEv2连接正常，facebook可以正常访问，但google无论如何都无法访问。
安卓客户端strongswan在服务器修改MTU值为1500后问题消失。但windows10,linux客户端始终无法访问google，而且能访问的网站速度也很慢

**重现步骤**
我GCP上试过ubuntu20.04,ubuntu21.04,debian10，所有服务器存在同样的问题。

**服务器日志**
Aug 16 12:31:04 debian10 pluto[14425]: "ikev2-cp"[8] 117.154.103.49 #12: received unsupported NOTIFY v2N_ADDITIONAL_IP6_ADDRESS
Aug 16 12:31:04 debian10 pluto[14425]: "ikev2-cp"[8] 117.154.103.49 #12: received unsupported NOTIFY v2N_EAP_ONLY_AUTHENTICATION
Aug 16 12:31:04 debian10 pluto[14425]: "ikev2-cp"[8] 117.154.103.49 #12: received unsupported NOTIFY v2N_IKEV2_MESSAGE_ID_SYNC_SUPPORTED
Aug 16 12:31:04 debian10 pluto[14425]: "ikev2-cp"[8] 117.154.103.49 #12: negotiated connection [0.0.0.0-255.255.255.255:0-65535 0] -> [192.168.43.10-192.168.43.10:0-65535 0]
Aug 16 12:31:04 debian10 pluto[14425]: "ikev2-cp"[8] 117.154.103.49 #12: IPsec SA established tunnel mode {ESPinUDP=>0xcfd43c5b <0x74a19420 xfrm=AES_GCM_16_128-NONE NATOA=none NATD=117.154.103.49:14117 DPD=active}
Aug 16 12:31:54 debian10 pluto[14425]: "ikev2-cp"[8] 117.154.103.49 #11: deleting other state #12 (STATE_V2_ESTABLISHED_CHILD_SA) aged 49.787176s and NOT sending notification
Aug 16 12:31:54 debian10 pluto[14425]: "ikev2-cp"[8] 117.154.103.49 #12: ESP traffic information: in=4KB out=3KB
Aug 16 12:31:54 debian10 pluto[14425]: "ikev2-cp"[8] 117.154.103.49 #11: deleting state (STATE_V2_ESTABLISHED_IKE_SA) aged 50.079656s and NOT sending notification
Aug 16 12:31:54 debian10 pluto[14425]: "ikev2-cp"[8] 117.154.103.49: deleting connection instance with peer 117.154.103.49 {isakmp=#0/ipsec=#0}

我配置过许多VPN，wireguard,openVPN，v2fly,shadowsocks都没有问题。被这个IKEV2问题困扰了许久，网上一直没有找到解决方案，希望博主能帮忙分析分析问题所在，感激不尽！

**Comment by mappinglan** [comment]
现在我在windows11宿主机下测试正常（Linux虚拟机依然能连接，但是没流量）。之前Linux宿主机Windows虚拟机，均有问题。

**Comment by hwdsl2** [comment]
@mappinglan 你好！你提供的日志看起来正常。之前有用户报告过 GCP 上面的服务器在配置 VPN 之后访问有一些问题，参见 #973 和 #819。具体原因未知。该问题好像是 GCP 所特有，建议你尝试一下其他的云服务提供商。在进一步测试之前，我准备把 GCP 的链接从自述文件中移除。

**Comment by mappinglan** [comment]
@hwdsl2 这个问题似乎不是GCP所特有，今天我在aliyun,azure（选择系统ubuntu20.04,debian10）都测试过，都存在这个问题。我确定本地Linux电脑可以连接，并且可以访问我的个人主页，反馈的公网IP确实是所搭建的IKEV2服务器IP，但是Google YouTube这些网站无法访问。目前在我的网络环境下，Windows11,Android作为IKEV2客户端能正常使用，只有linux客户端（debian11,ubuntu21.04)表现异常。我怀疑是strongswan client配置有问题，但是不知道怎么配置。或者可能我的网络环境有问题，怪异的是其他类型的VPN就很正常。

**Comment by mappinglan** [comment]
3	4.867814	192.168.154.130	192.168.154.2	DNS	70	Standard query 0xc34f A wower.cool
4	4.868252	192.168.154.130	192.168.154.2	DNS	70	Standard query 0xece5 AAAA wower.cool
5	4.875031	192.168.154.2	192.168.154.130	DNS	86	Standard query response 0xc34f A wower.cool A 34.126.153.122
6	4.881721	192.168.154.2	192.168.154.130	DNS	70	Standard query response 0xece5 AAAA wower.cool
7	4.883991	192.168.154.130	34.126.153.122	ISAKMP	978	IKE_SA_INIT MID=00 Initiator Request
8	4.978739	34.126.153.122	192.168.154.130	ISAKMP	80	IKE_SA_INIT MID=00 Responder Response
9	4.986456	192.168.154.130	34.126.153.122	ISAKMP	1170	IKE_SA_INIT MID=00 Initiator Request
10	5.083467	34.126.153.122	192.168.154.130	ISAKMP	507	IKE_SA_INIT MID=00 Responder Response
11	5.106340	192.168.154.130	34.126.153.122	ISAKMP	1282	IKE_AUTH MID=01 Initiator Request (fragment 1/2)
12	5.106819	192.168.154.130	34.126.153.122	ISAKMP	690	IKE_AUTH MID=01 Initiator Request (fragment 2/2)
13	5.219138	34.126.153.122	192.168.154.130	UDPENCAP	43	NAT-keepalive
14	5.246658	34.126.153.122	192.168.154.130	ISAKMP	578	IKE_AUTH MID=01 Responder Response (fragment 1/4)
15	5.246779	34.126.153.122	192.168.154.130	ISAKMP	578	IKE_AUTH MID=01 Responder Response (fragment 2/4)
16	5.246843	34.126.153.122	192.168.154.130	ISAKMP	578	IKE_AUTH MID=01 Responder Response (fragment 3/4)
17	5.246902	34.126.153.122	192.168.154.130	ISAKMP	306	IKE_AUTH MID=01 Responder Response (fragment 4/4)
这是我用wireshark抓取的IKEV2连接过程数据包
me@virtual-machine:~$ wget -qO- http://ipv4.icanhazip.com; echo
34.126.153.122
反馈的公网IP是服务器IP

**Comment by mappinglan** [comment]
@hwdsl2 突发奇想，在本地组建虚拟机局域网网络，一台debian11做ikev2服务器，一台ubuntu做客户端，宿主机做路由器。ubuntu的流量经过debian再经过主机，竟然奇迹般的正常了。 照此看，配置是没有问题的。问题在云服务或者网络接入服务商那里。

**Comment by Scottpedia** [comment]
@mappinglan 
我 whois 了一下你提供的服务端公网 IP ，结果发现你的服务器是在中国大陆。所有在中国大陆的云平台提供商的网络环境都是被中国大陆防火墙屏蔽的，所以说使用此类服务器来搭建虚拟专用网肯定没法访问谷歌。除此之外，内地的各大云服务提供商（如世纪互联的 Azure ）都明言规定不允许私人搭建和使用虚拟专用网来访问被封锁的网站和服务，所以很有可能他们所有的 ISP 都有给 VPN 端口限速，从而导致像你说的 VPN 带宽低。

```
% IANA WHOIS server
% for more information on IANA, visit http://www.iana.org
% This query returned 1 object

refer:        whois.apnic.net

inetnum:      117.0.0.0 - 117.255.255.255
organisation: APNIC
status:       ALLOCATED

whois:        whois.apnic.net

changed:      2007-01
source:       IANA

# whois.apnic.net

% [whois.apnic.net]
% Whois data copyright terms    http://www.apnic.net/db/dbcopyright.html

% Information related to '117.128.0.0 - 117.191.255.255'

% Abuse contact for '117.128.0.0 - 117.191.255.255' is 'abuse@chinamobile.com'

inetnum:        117.128.0.0 - 117.191.255.255
netname:        CMNET
descr:          China Mobile Communications Corporation
descr:          Mobile Communications Network Operator in China
descr:          Internet Service Provider in China
country:        CN
org:            ORG-CM1-AP
admin-c:        ct74-AP
tech-c:         HL1318-AP
abuse-c:        AC2006-AP
status:         ALLOCATED PORTABLE
remarks:        service provider
remarks:        --------------------------------------------------------
remarks:        To report network abuse, please contact mnt-irt
remarks:        For troubleshooting, please contact tech-c and admin-c
remarks:        Report invalid contact via www.apnic.net/invalidcontact
remarks:        --------------------------------------------------------
mnt-by:         APNIC-HM
mnt-lower:      MAINT-CN-CMCC
mnt-routes:     MAINT-CN-CMCC
mnt-irt:        IRT-CHINAMOBILE-CN
last-modified:  2020-07-15T13:10:03Z
source:         APNIC

irt:            IRT-CHINAMOBILE-CN
address:        China Mobile Communications Corporation
address:        29, Jinrong Ave., Xicheng District, Beijing, 100032
e-mail:         abuse@chinamobile.com
abuse-mailbox:  abuse@chinamobile.com
admin-c:        CT74-AP
tech-c:         CT74-AP
auth:           # Filtered
remarks:        abuse@chinamobile.com was validated on 2021-07-21
mnt-by:         MAINT-CN-CMCC
last-modified:  2021-07-21T00:47:50Z
source:         APNIC

organisation:   ORG-CM1-AP
org-name:       China Mobile
country:        CN
address:        29, Jinrong Ave.
phone:          +86-10-5268-6688
fax-no:         +86-10-5261-6187
e-mail:         hostmaster@chinamobile.com
mnt-ref:        APNIC-HM
mnt-by:         APNIC-HM
last-modified:  2019-12-27T12:55:58Z
source:         APNIC

role:           ABUSE CHINAMOBILECN
address:        China Mobile Communications Corporation
address:        29, Jinrong Ave., Xicheng District, Beijing, 100032
country:        ZZ
phone:          +000000000
e-mail:         abuse@chinamobile.com
admin-c:        CT74-AP
tech-c:         CT74-AP
nic-hdl:        AC2006-AP
remarks:        Generated from irt object IRT-CHINAMOBILE-CN
abuse-mailbox:  abuse@chinamobile.com
mnt-by:         APNIC-ABUSE
last-modified:  2020-07-15T13:10:00Z
source:         APNIC

role:           chinamobile tech
address:        29, Jinrong Ave.,Xicheng district
address:        Beijing
country:        CN
phone:          +86 5268 6688
fax-no:         +86 5261 6187
e-mail:         hostmaster@chinamobile.com
admin-c:        HL1318-AP
tech-c:         HL1318-AP
nic-hdl:        ct74-AP
notify:         hostmaster@chinamobile.com
mnt-by:         MAINT-cn-cmcc
abuse-mailbox:  abuse@chinamobile.com
last-modified:  2016-11-29T09:37:27Z
source:         APNIC

person:         haijun li
nic-hdl:        HL1318-AP
e-mail:         hostmaster@chinamobile.com
address:        29,Jinrong Ave, Xicheng district,beijing,100032
phone:          +86 1052686688
fax-no:         +86 10 52616187
country:        CN
mnt-by:         MAINT-CN-CMCC
abuse-mailbox:  abuse@chinamobile.com
last-modified:  2016-11-29T09:38:38Z
source:         APNIC

% Information related to '117.152.0.0/14as9808'

route:          117.152.0.0/14
descr:          China Mobile communications corporation
origin:         as9808
mnt-by:         MAINT-CN-CMCC
last-modified:  2008-09-04T07:55:15Z
source:         APNIC

% This query was served by the APNIC Whois Service version 1.88.15-SNAPSHOT (WHOIS-US3)
```

**Comment by mappinglan** [comment]
@Scottpedia 那个117是我电脑的公网IP。我用的云是GCP。而且就算国内的云服务商，比如阿里云华为云都有提高国外的云服务。你好好看看我的问题，跟你描述的八杆子打不着。

**Comment by Scottpedia** [comment]
> @Scottpedia 那个117是我电脑的公网IP。我用的云是GCP。而且就算国内的云服务商，比如阿里云华为云都有提高国外的云服务。你好好看看我的问题，跟你描述的八杆子打不着。

抱歉是我的失误

**Comment by Mattz-CE** [comment]
I haven't seen other people mentioning this, so, have you tried changing both your ethernet and VPN DNS to 8.8.4.4? I'm also currently living in China, and usually my vpn problems can be resolved with changing to an accessible foreign DNS. You clearly seems to know what you're doing but I'm just want to provide some potential alternative.
